Repository transcom/mymove, pull requests merged in 2019-09, with the labels that each got.

#2640 Automated dependency updates | Update pre-commit dependencies
  .pre-commit-config.yaml
Labels: dependencies, 🦇team

#2579 Update SSW
  cmd/generate-shipment-summary/main.go
  pkg/handlers/internalapi/moves.go
  pkg/models/shipment_summary_worksheet.go
  pkg/models/shipment_summary_worksheet_test.go
  pkg/paperwork/formtemplates/shipment_summary_worksheet_page1.png
  pkg/paperwork/formtemplates/shipment_summary_worksheet_page2.png
  pkg/paperwork/formtemplates/shipment_summary_worksheet_page3.png
  pkg/paperwork/shipment_summary.go
  pkg/paperwork/shipment_summary_worksheet.go
  pkg/rateengine/rateengine.go
  pkg/unit/miles.go
  pkg/unit/miles_test.go
Labels: roci

#2556 Update uploads/documents deletion to use soft delete
  cypress/integration/office/documentViewer.js
  migrations/20190730225048_add_deleted_at_to_document_tables.up.sql
  migrations/20190829152347_create-deleted-at-indices-for-document-tables.up.sql
  migrations_manifest.txt
  pkg/db/utilities/utilities.go
  pkg/db/utilities/utilities_test.go
  pkg/handlers/internalapi/documents.go
  pkg/handlers/internalapi/move_documents.go
  pkg/handlers/internalapi/personally_procured_move.go
  pkg/handlers/internalapi/uploads.go
  pkg/handlers/internalapi/uploads_test.go
  pkg/models/document.go
  pkg/models/document_test.go
  pkg/models/move_document.go
  pkg/models/move_document_test.go
  pkg/models/move_documents_extractor.go
  pkg/models/move_documents_extractor_test.go
  pkg/models/moving_expense_document.go
  pkg/models/personally_procured_move.go
  pkg/models/personally_procured_move_test.go
  pkg/models/shipment_summary_worksheet.go
  pkg/models/upload.go
  pkg/models/upload_test.go
  pkg/models/weight_ticket_set_document.go
  pkg/models/weight_ticket_set_document_test.go
  pkg/services/move_documents/generic_move_document_updater.go
  pkg/services/move_documents/ppm_completer_test.go
  pkg/services/move_documents/storage_expense_updater.go
  pkg/services/move_documents/storage_expense_updater_test.go
  pkg/services/move_documents/update_move_document.go
  pkg/services/move_documents/update_move_document_test.go
  pkg/services/move_documents/weight_ticket_updater_test.go
Labels: roci

#2510 Add admin orders index endpoint
  pkg/handlers/adminapi/api.go
  pkg/handlers/adminapi/electronic_orders.go
  pkg/services/electronic_order.go
  pkg/services/electronic_order/electronic_order_list_fetcher.go
  pkg/services/electronic_order/electronic_order_list_fetcher_test.go
  pkg/services/electronic_order/electronic_order_service_test.go
  pkg/services/electronic_order/logger.go
  swagger/admin.yaml
Labels: ttv

#2533 Remove Truss test TSP user from staging and prod
  local_migrations/20190814195556_delete-truss-tsp-user-data.sql
  migrations_manifest.txt
Labels: A-Team

#2625 Add validation to EDI
  go.mod
  go.sum
  pkg/edi/segment/bx.go
  pkg/edi/segment/bx_test.go
  pkg/edi/segment/fa1.go
  pkg/edi/segment/fa1_test.go
  pkg/edi/segment/fa2.go
  pkg/edi/segment/fa2_test.go
  pkg/edi/segment/ge.go
  pkg/edi/segment/ge_test.go
  pkg/edi/segment/gs.go
  pkg/edi/segment/gs_test.go
  pkg/edi/segment/hl.go
  pkg/edi/segment/hl_test.go
  pkg/edi/segment/iea.go
  pkg/edi/segment/iea_test.go
  pkg/edi/segment/isa.go
  pkg/edi/segment/isa_test.go
  pkg/edi/segment/l0.go
  pkg/edi/segment/l0_test.go
  pkg/edi/segment/l1.go
  pkg/edi/segment/l10.go
  pkg/edi/segment/l10_test.go
  pkg/edi/segment/l1_test.go
  pkg/edi/segment/l7.go
  pkg/edi/segment/l7_test.go
  pkg/edi/segment/lx.go
  pkg/edi/segment/lx_test.go
  pkg/edi/segment/mea.go
  pkg/edi/segment/mea_test.go
  pkg/edi/segment/n1.go
  pkg/edi/segment/n1_test.go
  pkg/edi/segment/n3.go
  pkg/edi/segment/n3_test.go
  pkg/edi/segment/n4.go
  pkg/edi/segment/n4_test.go
  pkg/edi/segment/n9.go
  pkg/edi/segment/n9_test.go
  pkg/edi/segment/nte.go
  pkg/edi/segment/nte_test.go
  pkg/edi/segment/se.go
  pkg/edi/segment/se_test.go
  pkg/edi/segment/segment_test.go
  pkg/edi/segment/st.go
  pkg/edi/segment/st_test.go
  pkg/edi/segment/validators.go
  pkg/services/tsp/tsp_service_test.go
Labels: A-Team

#2647 Admin index UI for electronic orders
  src/scenes/SystemAdmin/ElectronicOrderList.jsx
  src/scenes/SystemAdmin/Home.jsx
  src/scenes/SystemAdmin/TitleizedField.jsx
  src/scenes/SystemAdmin/TitleizedField.test.js
Labels: ttv

#2630 Send post move survey email
  Dockerfile.tasks
  Dockerfile.tasks_local
  Makefile
  cmd/send_post_move_survey_email/logger.go
  cmd/send_post_move_survey_email/main.go
  local_migrations/20190822210248_add-payment-reviewed-date-to-personally-procured-moves.up.sql
  migrations/20190829150706_create_notifications_table.up.sql
  migrations_manifest.txt
  pkg/models/notifications.go
  pkg/models/personally_procured_move.go
  pkg/notifications/move_reviewed.go
  pkg/notifications/move_reviewed_test.go
  pkg/notifications/notification_sender.go
  pkg/notifications/notification_stub.go
  pkg/notifications/notification_test.go
  pkg/notifications/templates/move_reviewed_template.html
  pkg/notifications/templates/move_reviewed_template.txt
  pkg/services/move_documents/ppm_completer.go
Labels: roci

#2653 Add DB_REGION env var for environmental tests
  .circleci/config.yml
Labels: 🦇team

#2656 Add pagination to admin resources
  pkg/handlers/adminapi/api.go
  pkg/handlers/adminapi/electronic_orders.go
  pkg/handlers/adminapi/office_users.go
  pkg/handlers/adminapi/office_users_test.go
  pkg/handlers/adminapi/offices.go
  pkg/handlers/adminapi/offices_test.go
  pkg/services/electronic_order.go
  pkg/services/electronic_order/electronic_order_list_fetcher.go
  pkg/services/electronic_order/electronic_order_list_fetcher_test.go
  pkg/services/office.go
  pkg/services/office/office_list_fetcher.go
  pkg/services/office/office_list_fetcher_test.go
  pkg/services/pagination.go
  pkg/services/pagination/logger.go
  pkg/services/pagination/pagination.go
  pkg/services/pagination/pagination_service_test.go
  pkg/services/pagination/pagination_test.go
  pkg/services/query/query_builder.go
  pkg/services/query/query_builder_test.go
  pkg/services/user.go
  pkg/services/user/office_user_list_fetcher.go
  pkg/services/user/office_user_list_fetcher_test.go
  src/scenes/SystemAdmin/ElectronicOrderList.jsx
  src/scenes/SystemAdmin/Home.jsx
  src/scenes/SystemAdmin/OfficeList.jsx
  src/scenes/SystemAdmin/UserList.jsx
  src/scenes/SystemAdmin/rest_provider.js
  swagger/admin.yaml
Labels: ttv

#2578 documentation for soft delete
  .spelling
  docs/README.md
  docs/adr/0038-soft-delete.md
  docs/how-to/soft-delete.md
Labels: roci

#2666 Update MoveSummaryComponent to always fetch estimate
  src/scenes/Landing/MoveSummary.jsx
Labels: roci

#2674 [System admin] Show disabled/deactivated column, and other cleanup
  pkg/handlers/adminapi/office_users.go
  src/scenes/SystemAdmin/UserList.jsx
  src/scenes/SystemAdmin/UserShow.jsx
  swagger/admin.yaml
Labels: ttv

#2685 Add copy to Payment Requested Step: 168153437
  src/scenes/Landing/MoveSummary.jsx
Labels: ttv

#2687 Update duty station names (normalize): 168408650
  cypress/integration/mymove/orders.js
  cypress/integration/mymove/serviceMemberProfile.js
  migrations/20190912202709_update-duty-station-names.up.sql
  migrations_manifest.txt
  src/scenes/Orders/ducks.test.js
  src/shared/User/sampleLoggedInUserPayload.js
Labels: ttv

#2655 Add deploy task for post move survey email
  .circleci/config.yml
  Dockerfile.tasks
  Dockerfile.tasks_local
  Makefile
  cmd/ecs-deploy-task-container/main.go
  cmd/milmove-tasks/logger.go
  cmd/milmove-tasks/main.go
  cmd/milmove-tasks/save_fuel_price_data.go
  cmd/milmove-tasks/send_post_move_survey_email.go
  cmd/milmove-tasks/version.go
  cmd/milmove/serve.go
  cmd/send_post_move_survey_email/logger.go
  pkg/notifications/move_reviewed.go
  pkg/notifications/notification_sender.go
Labels: roci

#2681 Builds out Office User creator in admin app
  src/scenes/SystemAdmin/Home.jsx
  src/scenes/SystemAdmin/UserCreate.jsx
  swagger/admin.yaml
Labels: ttv

#2670 Fix TSPP load instructions and obfuscator script
  docs/data/tspp-data-creation.md
  scripts/export-obfuscated-tspp-sample
Labels: A-Team

#2678 Move email content into templates
  pkg/notifications/move_approved.go
  pkg/notifications/move_canceled.go
  pkg/notifications/move_submitted.go
  pkg/notifications/notification_test.go
  pkg/notifications/templates/move_approved_template.html
  pkg/notifications/templates/move_approved_template.txt
  pkg/notifications/templates/move_canceled_template.html
  pkg/notifications/templates/move_canceled_template.txt
  pkg/notifications/templates/move_submitted_template.html
  pkg/notifications/templates/move_submitted_template.txt
Labels: roci

#2688 Add admin api orders metadata
  pkg/handlers/adminapi/api.go
  pkg/handlers/adminapi/electronic_orders.go
  pkg/handlers/adminapi/electronic_orders_test.go
  pkg/services/electronic_order.go
  pkg/services/electronic_order/electronic_order_category_count_fetcher.go
  pkg/services/electronic_order/electronic_order_category_count_fetcher_test.go
  pkg/services/query/query_builder.go
  pkg/services/query/query_builder_test.go
  swagger/admin.yaml
Labels: ttv

#2694 Use dollars to calculate dollar amounts for other expenses
  pkg/models/shipment_summary_worksheet.go
  pkg/models/shipment_summary_worksheet_test.go
Labels: bug, roci

#2669 Delete weight ticket and expense tickets as a service member
  cypress/integration/mymove/ppmCloseout.js
  pkg/handlers/internalapi/api.go
  pkg/handlers/internalapi/move_documents.go
  pkg/handlers/internalapi/move_documents_test.go
  pkg/models/move_document.go
  pkg/models/move_document_test.go
  src/scenes/Moves/Ppm/PaymentReview/DocumentsUploaded.js
  src/scenes/Moves/Ppm/PaymentReview/ExpenseTicketListItem.jsx
  src/scenes/Moves/Ppm/PaymentReview/WeightTicketListItem.jsx
  src/scenes/Moves/Ppm/PaymentReview/index.jsx
  src/shared/AlertWithDeleteConfirmation/index.jsx
  src/shared/AlertWithDeleteConfirmation/index.module.scss
  src/shared/AlertWithDeleteConfirmation/index.test.jsx
  src/shared/Entities/modules/moveDocuments.js
  src/shared/Swagger/request.js
  swagger/internal.yaml
Labels: roci

#2696 Remove duplicate duty stations: 168408874
  migrations/20190913205819_delete_dup_duty_stations.up.sql
  migrations/20190917162117_update_duty_station_names.up.sql
  migrations_manifest.txt
Labels: ttv

#2692 Add tags to generated files
  go.mod
  pkg/handlers/internalapi/personally_procured_move_attachments.go
  pkg/handlers/internalapi/personally_procured_move_attachments_test.go
  pkg/handlers/internalapi/uploads.go
  pkg/handlers/internalapi/uploads_test.go
  pkg/paperwork/generator_test.go
  pkg/services/invoice/store_invoice.go
  pkg/services/invoice/update_invoice_upload_test.go
  pkg/storage/filesystem.go
  pkg/storage/memory.go
  pkg/storage/s3.go
  pkg/storage/storage.go
  pkg/storage/test/s3.go
  pkg/testdatagen/make_upload.go
  pkg/uploader/uploader.go
  pkg/uploader/uploader_test.go
Labels: roci

#2695 Add paperwork tests back in with SSW instead of GBL
  pkg/services/paperwork/create_form_test.go
Labels: roci

#2712 Disable DB_DEBUG for migrations
  Makefile
Labels: A-Team

#2715 remove dup duty stations - take 2: 168408874
  migrations/20190913205819_delete_dup_duty_stations.up.sql
  migrations/20190917162117_update_duty_station_names.up.sql
  migrations_manifest.txt
Labels: ttv

#2701 Add tooltip if currently missing BVS scores for date provided
  cypress/integration/mymove/ppm.js
  pkg/handlers/internalapi/api.go
  pkg/handlers/internalapi/personally_procured_move.go
  pkg/handlers/internalapi/personally_procured_move_test.go
  pkg/testdatagen/scenario/e2ebasic.go
  src/scenes/Landing/MoveSummary.jsx
  src/scenes/Moves/Ppm/DateAndLocation.jsx
  src/scenes/Moves/Ppm/Weight.jsx
  src/scenes/Moves/Ppm/ducks.js
  src/scenes/Moves/Ppm/ducks.test.js
  src/scenes/Review/EditDateAndLocation.jsx
  src/scenes/Review/EditWeight.jsx
  src/scenes/Review/PPMShipmentSummary.jsx
  src/scenes/Review/ServiceMemberSummary.jsx
  src/shared/Entities/modules/ppms.js
  src/shared/ToolTip/IconWithTooltip.jsx
  src/shared/ToolTip/IconWithTooltip.module.scss
  src/shared/ToolTip/index.css
  swagger/internal.yaml
Labels: roci

#2704 TTV remove unused db tables [delivers #167977685]
  migrations/20190919173143_delete_hhg_tables_data.up.sql
  migrations_manifest.txt
  pkg/migrate/SplitStatements_test.go
  pkg/migrate/fixtures/deleteUsers.sql
  pkg/migrate/fixtures/loop.sql
Labels: mothball, ttv

#2723 TTV remove unused db tables part 3
  migrations/20190919173143_delete_hhg_tables_data.up.sql
  migrations_manifest.txt
  pkg/migrate/SplitStatements_test.go
  pkg/migrate/fixtures/deleteUsers.sql
  pkg/migrate/fixtures/loop.sql
Labels: mothball, ttv

#2700 Add access codes to admin interface
  pkg/handlers/adminapi/access_code.go
  pkg/handlers/adminapi/access_code_test.go
  pkg/handlers/adminapi/api.go
  pkg/models/access_code.go
  pkg/services/accesscode.go
  pkg/services/accesscode/fetch_access_code_list.go
  pkg/services/accesscode/fetch_access_code_list_test.go
  pkg/services/query.go
  pkg/services/query/query_association.go
  pkg/services/query/query_builder.go
  pkg/services/query/query_builder_test.go
  pkg/testdatagen/scenario/e2ebasic.go
  src/scenes/SystemAdmin/AccessCodeList.jsx
  src/scenes/SystemAdmin/Home.jsx
  src/scenes/SystemAdmin/Home.module.scss
  swagger/admin.yaml
Labels: roci

#2732 Fix design debt
  src/scenes/Legalese/index.css
  src/scenes/Moves/Ppm/PPMPaymentRequest.css
  src/scenes/Moves/Ppm/PaymentReview/PaymentReview.css
  src/scenes/Moves/WizardHeader.jsx
  src/scenes/Review/EditProfile.jsx
  src/shared/Uploader/index.css
Labels: roci

#2720 Fix sit estimate
  cypress/integration/mymove/ppm.js
  src/scenes/Review/EditDateAndLocation.jsx
  src/scenes/Review/PPMShipmentSummary.jsx
Labels: roci

#2691 Add log event for creating office users
  cmd/ecs-service-logs/README.md
  pkg/handlers/adminapi/office_users.go
Labels: ttv

#2734 Remove Liz from experimental, staging, and prod
  local_migrations/20190925190920_disable_liz.up.sql
  migrations_manifest.txt
Labels: ttv

#2736 Reorganize the system admin frontend folder
  src/scenes/SystemAdmin/AccessCodes/AccessCodeList.jsx
  src/scenes/SystemAdmin/ElectronicOrders/ElectronicOrderList.jsx
  src/scenes/SystemAdmin/Home.jsx
  src/scenes/SystemAdmin/Home.test.jsx
  src/scenes/SystemAdmin/OfficeUsers/UserCreate.jsx
  src/scenes/SystemAdmin/OfficeUsers/UserEdit.jsx
  src/scenes/SystemAdmin/OfficeUsers/UserList.jsx
  src/scenes/SystemAdmin/OfficeUsers/UserShow.jsx
  src/scenes/SystemAdmin/Offices/OfficeList.jsx
  src/scenes/SystemAdmin/auth_provider.js
  src/scenes/SystemAdmin/index.jsx
  src/scenes/SystemAdmin/shared/AdminPagination.jsx
  src/scenes/SystemAdmin/shared/LoginButton.jsx
  src/scenes/SystemAdmin/shared/LoginButton.module.scss
  src/scenes/SystemAdmin/shared/LogoutButton.jsx
  src/scenes/SystemAdmin/shared/Menu.jsx
  src/scenes/SystemAdmin/shared/SignIn.jsx
  src/scenes/SystemAdmin/shared/SignIn.module.scss
  src/scenes/SystemAdmin/shared/TitleizedField.jsx
  src/scenes/SystemAdmin/shared/TitleizedField.test.js
  src/scenes/SystemAdmin/shared/form_validators.js
  src/scenes/SystemAdmin/shared/rest_provider.js
Labels: ttv

#2741 Ttv 167977685 remove unused db tables 5
  migrations/20190919173143_delete_hhg_tables_data.up.sql
  migrations_manifest.txt
  pkg/migrate/SplitStatements_test.go
  pkg/migrate/fixtures/deleteUsers.sql
  pkg/migrate/fixtures/loop.sql
Labels: mothball, ttv
