Repository transcom/mymove, pull requests merged in 2019-12, with the labels that each got.

#3112 MB-712: ma change default migration type to sql
  pkg/cli/migration_file.go
Labels: roci

#3139 MB-217 left align cancel button for service member flow
  src/shared/WizardPage/index.jsx
Labels: ttv

#3078 168524581: Authorization ADR
  .spelling
  docs/README.md
  docs/adr/0040-role-base-authorization.md
  docs/adr/index.md
Labels: roci

#3148 Create tables for user types
  migrations/20191204160349_add_new_user_type_tables.up.sql
  migrations_manifest.txt
Labels: roci

#3152 MB-588 Delete existing MTO tables
  migrations/20191204170511_remove-old-tables.up.sql
  migrations_manifest.txt
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/api_test.go
  pkg/handlers/ghcapi/customer.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/move_task_order.go
  pkg/handlers/ghcapi/move_task_order_test.go
  pkg/handlers/ghcapi/service_items.go
  pkg/handlers/ghcapi/service_items_test.go
  pkg/handlers/primeapi/api.go
  pkg/handlers/primeapi/internal/payloads/model_to_payload.go
  pkg/handlers/primeapi/move_task_order.go
  pkg/handlers/primeapi/move_task_order_test.go
  pkg/handlers/primeapi/payment_request.go
  pkg/handlers/primeapi/payment_request_test.go
  pkg/models/customer.go
  pkg/models/customer_test.go
  pkg/models/ghc_entitlement.go
  pkg/models/move_task_order.go
  pkg/models/move_task_order_test.go
  pkg/models/payment_request.go
  pkg/models/payment_request_test.go
  pkg/models/service_item.go
  pkg/services/mocks/MoveTaskOrderActualWeightUpdater.go
  pkg/services/mocks/MoveTaskOrderDestinationAddressUpdater.go
  pkg/services/mocks/MoveTaskOrderFetcher.go
  pkg/services/mocks/MoveTaskOrderPrimeEstimatedWeightUpdater.go
  pkg/services/mocks/MoveTaskOrderPrimePostCounselingUpdater.go
  pkg/services/mocks/MoveTaskOrderStatusUpdater.go
  pkg/services/mocks/ServiceItemCreator.go
  pkg/services/mocks/ServiceItemListFetcher.go
  pkg/services/move_task_order.go
  pkg/services/move_task_order/move_task_order.go
  pkg/services/move_task_order/move_task_order_service_test.go
  pkg/services/move_task_order/move_task_order_test.go
  pkg/services/payment_request/payment_request_creator_test.go
  pkg/services/service_item.go
  pkg/services/service_item/logger.go
  pkg/services/service_item/service_item_creator.go
  pkg/services/service_item/service_item_creator_test.go
  pkg/services/service_item/service_item_list_fetcher.go
  pkg/services/service_item/service_item_service_test.go
  pkg/testdatagen/make_ghc_entitlement.go
  pkg/testdatagen/make_move_task_order.go
  pkg/testdatagen/make_payment_request.go
  pkg/testdatagen/make_service_item.go
  pkg/testdatagen/scenario/e2ebasic.go
  pkg/testdatagen/shared.go
Labels: roci

#3117 MB-470/168357698 import data 2b 2c other domestic prices
  pkg/services/ghcimport/import.go
  pkg/services/ghcimport/import_re_domestic_service_area_prices.go
  pkg/services/ghcimport/import_re_domestic_service_area_prices_test.go
  pkg/services/ghcimport/import_test.go
Labels: A-Team

#3155 Create customer after signup (local dev only)
  cmd/milmove/serve.go
  config/env/experimental.env
  config/env/prod.env
  config/env/staging.env
  migrations/20191204231026_add_user_id_to_customers.up.sql
  migrations_manifest.txt
  pkg/auth/authentication/auth.go
  pkg/auth/authentication/auth_test.go
  pkg/cli/featureflag.go
  pkg/models/customer.go
Labels: roci

#3166 Add commit message helper to add Jira Ids
  docs/README.md
  docs/how-to/automatically-add-jira-id-to-commit-message.md
  scripts/commit-msg
Labels: A-Team

#3164 MB-589: Create New Database tables and update models
  migrations/20191210171244_create_entitlements.up.sql
  migrations/20191210171408_create_move_orders.up.sql
  migrations/20191210171518_create_move_task_orders.up.sql
  migrations/20191210171620_create_mto_shipments.up.sql
  migrations/20191210171655_create_mto_service_items.up.sql
  migrations/20191210171752_alter_customers.up.sql
  migrations/20191210171828_alter_payment_requests_move_task_order_reference.up.sql
  migrations_manifest.txt
  pkg/handlers/primeapi/payment_request.go
  pkg/handlers/primeapi/payment_request_test.go
  pkg/models/customer.go
  pkg/models/customer_test.go
  pkg/models/ghc_entitlements.go
  pkg/models/move_order.go
  pkg/models/move_order_test.go
  pkg/models/move_task_order.go
  pkg/models/move_task_order_test.go
  pkg/models/mto_service_items.go
  pkg/models/mto_service_items_test.go
  pkg/models/mto_shipments.go
  pkg/models/mto_shipments_test.go
  pkg/models/payment_request.go
  pkg/models/payment_request_test.go
  pkg/services/payment_request/payment_request_creator_test.go
  pkg/testdatagen/make_address.go
  pkg/testdatagen/make_customer.go
  pkg/testdatagen/make_duty_station.go
  pkg/testdatagen/make_entitlement.go
  pkg/testdatagen/make_move_order.go
  pkg/testdatagen/make_move_task_order.go
  pkg/testdatagen/make_mto_service_item.go
  pkg/testdatagen/make_mto_shipment.go
  pkg/testdatagen/make_payment_request.go
  pkg/testdatagen/scenario/e2ebasic.go
  pkg/testdatagen/shared.go
Labels: roci

#3165 MB-753 Map Geographic Regional Codes to States for JPPSO Assignment
  migrations/20191205190530_jppso-assignment-tables.up.sql
  migrations/20191205211911_jppso-assignment-data.up.sql
  migrations_manifest.txt
Labels: roci

#3163 [MB-621] Add proofOfServicePackage to CreatePaymentRequestPayload
  pkg/gen/primeapi/configure_mymove.go
  pkg/gen/primeapi/doc.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/mymove_api.go
  pkg/gen/primemessages/create_payment_request_payload.go
  pkg/gen/primemessages/proof_of_service_package.go
  pkg/gen/primemessages/service_item.go
  pkg/gen/primemessages/upload.go
  swagger/prime.yaml
Labels: A-Team

#3177 Redirect TOO on signup (local dev only)
  migrations/20191205201215_add_user_id_to_too.up.sql
  migrations_manifest.txt
  pkg/auth/authentication/auth.go
  pkg/auth/authentication/auth_test.go
  pkg/auth/authentication/authgch_test.go
  pkg/auth/authentication/authghc.go
  pkg/auth/authentication/mocks/AdminUserAssociator.go
  pkg/auth/authentication/mocks/CustomerCreatorAndAssociator.go
  pkg/auth/authentication/mocks/OfficeUserAssociator.go
  pkg/auth/authentication/mocks/RoleAssociator.go
  pkg/auth/authentication/mocks/UserCreator.go
  pkg/models/transportation_ordering_officer.go
  pkg/testdatagen/make_admin_user.go
  pkg/testdatagen/make_office_user.go
  src/scenes/Office/TOO/tooVerificationInProgress.jsx
  src/scenes/Office/index.jsx
Labels: roci

#3196 TOO can view draft MTO
  migrations/20191212203155_fix_spelling_is_canceled.up.sql
  migrations_manifest.txt
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/customer/get_customer.go
  pkg/gen/ghcapi/ghcoperations/customer/get_customer_info.go
  pkg/gen/ghcapi/ghcoperations/customer/get_customer_info_responses.go
  pkg/gen/ghcapi/ghcoperations/customer/get_customer_parameters.go
  pkg/gen/ghcapi/ghcoperations/customer/get_customer_responses.go
  pkg/gen/ghcapi/ghcoperations/customer/get_customer_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/move_order/get_move_order.go
  pkg/gen/ghcapi/ghcoperations/move_order/get_move_order_parameters.go
  pkg/gen/ghcapi/ghcoperations/move_order/get_move_order_responses.go
  pkg/gen/ghcapi/ghcoperations/move_order/get_move_order_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/ghcmessages/customer.go
  pkg/gen/ghcmessages/duty_station.go
  pkg/gen/ghcmessages/entitlements.go
  pkg/gen/ghcmessages/move_order.go
  pkg/gen/ghcmessages/move_task_order.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/customer.go
  pkg/handlers/ghcapi/customer_test.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/move_order_test.go
  pkg/handlers/ghcapi/move_orders.go
  pkg/handlers/ghcapi/move_task_order.go
  pkg/handlers/ghcapi/move_task_order_test.go
  pkg/models/move_task_order.go
  pkg/services/customer.go
  pkg/services/move_order.go
  pkg/services/move_order/move_order.go
  pkg/services/move_order/move_order_service_test.go
  pkg/services/move_order/move_order_test.go
  pkg/services/move_task_order.go
  pkg/services/move_task_order/move_task_order.go
  pkg/services/move_task_order/move_task_order_service_test.go
  pkg/services/move_task_order/move_task_order_test.go
  pkg/services/office_user/customer/customer.go
  pkg/services/office_user/customer/customer_service_test.go
  pkg/services/office_user/customer/customer_test.go
  pkg/testdatagen/make_move_task_order.go
  pkg/testdatagen/scenario/e2ebasic.go
  src/scenes/Office/TOO/customerDetails.jsx
  src/scenes/Office/index.jsx
  src/shared/Entities/modules/moveTaskOrders.js
  src/shared/Entities/schema.js
  swagger/ghc.yaml
Labels: roci

#3189 Update docs to reflect new error wrap pattern
  docs/backend.md
  docs/backend/service-objects.md
Labels: A-Team

#3197 MB-791: fetch active mtos
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/customer.go
  pkg/gen/primemessages/duty_station.go
  pkg/gen/primemessages/entitlements.go
  pkg/gen/primemessages/move_order.go
  pkg/gen/primemessages/move_task_order.go
  pkg/handlers/primeapi/api.go
  pkg/handlers/primeapi/internal/payloads/model_to_payload.go
  pkg/handlers/primeapi/move_task_order.go
  pkg/handlers/primeapi/move_task_order_test.go
  swagger/prime.yaml
Labels: roci

#3204 MB-748: ma - customer can log in
  migrations/20191210193133_update_roles_table.up.sql
  migrations_manifest.txt
  pkg/auth/authentication/auth.go
  pkg/auth/authentication/devlocal.go
  pkg/auth/session.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/logged_in_user_payload.go
  pkg/gen/internalmessages/role.go
  pkg/handlers/apitests.go
  pkg/handlers/internalapi/users.go
  pkg/handlers/internalapi/users_test.go
  pkg/models/roles.go
  pkg/models/user.go
  pkg/models/user_test.go
  pkg/testdatagen/scenario/e2ebasic.go
  src/shared/Entities/schema.js
  swagger/internal.yaml
Labels: roci

#3174 Auditing first pass
  pkg/gen/adminapi/embedded_spec.go
  pkg/gen/adminmessages/admin_user_update_payload.go
  pkg/gen/adminmessages/office_user_update_payload.go
  pkg/handlers/adminapi/admin_users.go
  pkg/handlers/adminapi/admin_users_test.go
  pkg/handlers/adminapi/office_users.go
  pkg/handlers/adminapi/office_users_test.go
  pkg/models/user.go
  pkg/services/admin_user.go
  pkg/services/admin_user/admin_user_updater.go
  pkg/services/admin_user/admin_user_updater_test.go
  pkg/services/audit/audit.go
  pkg/services/audit/audit_test.go
  pkg/services/audit/logger.go
  pkg/services/mocks/AdminUserUpdater.go
  pkg/services/mocks/OfficeUserUpdater.go
  pkg/services/office_user.go
  pkg/services/office_user/office_user_updater.go
  pkg/services/office_user/office_user_updater_test.go
  src/scenes/SystemAdmin/shared/rest_provider.js
  swagger/admin.yaml
Labels: ttv

#3216 MB-699: Change copy for weight ticket screen to mention pro-gear weigh
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/create_weight_ticket_documents_payload.go
  pkg/gen/internalmessages/move_document_payload.go
  pkg/gen/internalmessages/vehicle_options.go
  src/scenes/Moves/Ppm/WeightTicket.jsx
  swagger/internal.yaml
Labels: roci

#3232 fix failing integration tests
  Dockerfile.cypress
  cypress.json
  cypress/integration/office/ppmMoveDocuments.js
  package.json
  src/scenes/Moves/Ppm/WeightTicket.jsx
  src/scenes/Moves/Ppm/api.js
  src/scenes/Office/Ppm/api.js
  src/shared/Entities/modules/ppms.js
  src/shared/JsonSchemaForm/SingleDatePicker.jsx
  src/shared/JsonSchemaForm/reduxFieldNormalizer.js
  src/shared/JsonSchemaForm/validator.js
  src/shared/dates.js
  src/shared/dates.test.js
  src/shared/utils.js
  yarn.lock
Labels: ttv

#3217 Too can login after assigning role (local dev only)
  cmd/milmove/serve.go
  pkg/auth/authentication/auth.go
  pkg/auth/authentication/authgch_test.go
  pkg/auth/authentication/authghc.go
  pkg/auth/authentication/devlocal.go
  pkg/auth/authentication/mocks/RoleAssociator.go
  pkg/auth/authentication/mocks/TOORoleChecker.go
  pkg/auth/authentication/mocks/TOOUserAssociator.go
  pkg/auth/session.go
  pkg/handlers/apitests.go
  pkg/handlers/internalapi/users.go
  pkg/handlers/internalapi/users_test.go
  pkg/models/roles/roles.go
  pkg/models/user.go
  pkg/models/user_test.go
  pkg/testdatagen/scenario/e2ebasic.go
  pkg/testdatagen/shared.go
Labels: roci

#3207 Make MTO Available to prime
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/move_task_order/update_move_task_order_status.go
  pkg/gen/ghcapi/ghcoperations/move_task_order/update_move_task_order_status_parameters.go
  pkg/gen/ghcmessages/move_task_order.go
  pkg/gen/ghcmessages/move_task_order_status.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/move_task_order.go
  pkg/handlers/ghcapi/move_task_order_test.go
  pkg/models/payment_service_item_param_test.go
  pkg/models/proof_of_service_doc_test.go
  pkg/models/re_rate_area.go
  pkg/models/service_param_test.go
  pkg/services/mocks/MoveTaskOrderStatusUpdater.go
  pkg/services/move_task_order.go
  pkg/services/move_task_order/move_task_order.go
  pkg/services/payment_request/payment_request_list_fetcher.go
  pkg/testdatagen/make_move_task_order.go
  src/scenes/Office/TOO/customerDetails.jsx
  src/shared/Entities/modules/moveTaskOrders.js
  swagger/ghc.yaml
Labels: roci

#3206 Persists payment service items and associated records with payment requests
  migrations/20191212160348_add_fk_to_payment_service_items.up.sql
  migrations_manifest.txt
  pkg/gen/primeapi/configure_mymove.go
  pkg/gen/primeapi/doc.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/mymove_api.go
  pkg/gen/primemessages/create_payment_request_payload.go
  pkg/handlers/primeapi/payment_request.go
  pkg/handlers/primeapi/payment_request_test.go
  pkg/models/payment_request.go
  pkg/models/payment_request_test.go
  pkg/models/payment_service_item.go
  pkg/models/payment_service_item_param.go
  pkg/models/payment_service_item_test.go
  pkg/services/payment_request/payment_request_creator.go
  pkg/services/payment_request/payment_request_creator_test.go
  pkg/testdatagen/make_service_item_param_key.go
  pkg/testdatagen/scenario/e2ebasic.go
  pkg/testdatagen/shared.go
  swagger/prime.yaml
Labels: A-Team

#3238 Prime move-task-orders only returns MTOs isAvailableToPrime
  pkg/handlers/primeapi/move_task_order.go
  pkg/handlers/primeapi/move_task_order_test.go
  pkg/testdatagen/scenario/e2ebasic.go
Labels: roci

#3237 [TOO Skeleton] Add status label to MTO
  src/scenes/Office/TOO/customerDetails.jsx
Labels: roci

#3230 Add documentation on how to call the prime api
  docs/README.md
  docs/how-to/make-a-sample-prime-api-call.md
  docs/how-to/setup-postman-to-make-mutual-tls-api-calls.md
  docs/images/postman_client_cert.png
  docs/images/postman_collections_response.png
  docs/images/postman_environment.png
  docs/images/postman_import.png
  docs/images/postman_import_dialog.png
  docs/images/postman_manage_environment_add.png
  docs/images/postman_manage_environment_dialog.png
  docs/images/postman_set_environment.png
  docs/images/postman_settings_menu.png
  docs/images/postman_ssl_verification.png
  scripts/prime-api
Labels: A-Team

#3222 Creating default service items
  migrations/20191210171655_create_mto_service_items.up.sql
  migrations/20191216184630_make_mto_service_items_meta_optional.up.sql
  migrations_manifest.txt
  pkg/handlers/ghcapi/move_task_order.go
  pkg/handlers/ghcapi/move_task_order_test.go
  pkg/handlers/ghcapi/mto_service_items.go
  pkg/handlers/ghcapi/mto_service_items_test.go
  pkg/models/move_task_order.go
  pkg/models/mto_service_items.go
  pkg/models/mto_service_items_test.go
  pkg/services/move_task_order/move_task_order.go
  pkg/services/move_task_order/move_task_order_test.go
  pkg/testdatagen/make_mto_service_item.go
Labels: ttv

#3240 MB-660 TOO list service items for MTO
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/mto_service_item/list_m_t_o_service_items_parameters.go
  pkg/gen/ghcapi/ghcoperations/mto_service_item/list_m_t_o_service_items_responses.go
  pkg/gen/ghcapi/ghcoperations/mto_service_item/list_m_t_o_service_items_urlbuilder.go
  pkg/gen/ghcmessages/m_t_o_service_item.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/mto_service_items.go
  pkg/handlers/ghcapi/mto_service_items_test.go
  pkg/models/mto_service_items.go
  pkg/services/fetch.go
  pkg/services/fetch/fetcher.go
  pkg/services/fetch/fetcher_test.go
  pkg/services/mocks/Fetcher.go
  pkg/services/query/query_builder.go
  src/scenes/Office/TOO/customerDetails.jsx
  src/shared/Entities/modules/moveTaskOrders.js
  src/shared/Entities/modules/mtoServiceItems.js
  src/shared/Entities/schema.js
  swagger/ghc.yaml
Labels: ttv

#3251 MB-1015: fix pointer issue to pass back correct values for payloadForMTOServiceItem
  pkg/handlers/ghcapi/mto_service_items.go
Labels: ttv

#3262 Import Jan 2020 discount rates
  local_migrations/20191229234501_import_rates_jan_2020.up.sql
  migrations/20191229183600_add_top_tsp_for_ppms.up.sql
  migrations_manifest.txt
Labels: A-Team
