Repository transcom/mymove, pull requests merged in 2019-05, with the labels that each got.

#2053 400ng yearly import docs
  docs/data/accessorials_spreadsheet.png
  docs/data/additional_rates_spreadsheet.png
  docs/data/tariff400ng-yearly-import.md
Labels: 🦇team

#2062 Link and button should go to ppm info sheet
  cypress/integration/mymove/ppm.js
  src/scenes/Landing/MoveSummary.jsx
Labels: roci

#2064 Removes Feature Flag for Robust Item 125A/B/C/D [delivers #164869508]
  cypress/fixtures/preApprovals/requests/createRobustAccessorial.js
  cypress/integration/tsp/preApprovalRequest.js
  cypress/support/preapprovals/test125abcd.js
  src/shared/PreApprovalRequest/Code125Form.jsx
  src/shared/PreApprovalRequest/DetailsHelper.js
  src/shared/PreApprovalRequest/DetailsHelper.test.js
  src/shared/PreApprovalRequest/PreApprovalForm.jsx
  src/shared/PreApprovalRequest/PreApprovalRequest.css
  src/shared/PreApprovalRequest/PreApprovalRequest.jsx
  src/shared/featureFlags.js
Labels: ttv

#2067 Show "Actual item dimensions (inches)" label if editing robust item 105 [delivers #165747893]
  src/shared/PreApprovalRequest/Code105Form.jsx
Labels: ttv

#2075 Remove email and phone number with the customer service link in footer
  cypress/integration/mymove/homepage.js
  src/shared/Footer/index.jsx
Labels: roci

#2086 Upgrade React-Select to Latest Version [delivers #165750917]
  cypress/support/commands.js
  package.json
  yarn.lock
Labels: ttv

#2030 Access Code Table, Model, and Validation Endpoint
  docs/backend/service-objects.md
  migrations/20190422163230_create_access_code.up.sql
  mocks/AccessCodeValidator.go
  pkg/handlers/publicapi/access_code.go
  pkg/handlers/publicapi/access_code_test.go
  pkg/handlers/publicapi/api.go
  pkg/models/access_code.go
  pkg/models/move.go
  pkg/services/accesscode.go
  pkg/services/accesscode/validate_access_code.go
  pkg/services/accesscode/validate_access_code_test.go
  swagger/api.yaml
Labels: roci

#2098 Enable Clearable Input and Set Min Search Length to 1 for DutyStationSearchBox [delivers #165750917]
  src/scenes/ServiceMembers/DutyStationSearchBox.jsx
Labels: ttv

#2091 Save HHG submit date/time (with timezone) in DB
  docs/how-to/migrate-the-database.md
  migrations/20190503223719_add_submit_date_to_hhg.up.fizz
  pkg/models/move.go
  pkg/models/shipment.go
  pkg/models/shipment_test.go
  src/scenes/Legalese/ducks.js
  src/scenes/Legalese/index.jsx
Labels: ttv

#2094 Modify condensed to not precede single digit dates with 0
  src/shared/formatters.js
Labels: roci

#2084 Copy updates for ppm payment request intro and weight ticket scenarios pages
  cypress/integration/mymove/ppm.js
  src/scenes/Moves/Ppm/PPMPaymentRequestIntro.jsx
  src/scenes/Moves/Ppm/WeightTicketExamples.jsx
Labels: roci

#2095 Add linter rule for it.only tests
  .eslintrc
  package.json
  yarn.lock
Labels: roci

#2104 Office HHG Queue List Reorganization and Text Update [delivers #165769910]
  cypress/integration/office/documentViewer.js
  src/scenes/Office/OrdersInfo.jsx
  src/scenes/Office/OrdersViewerPanel.js
  src/scenes/Office/QueueList.jsx
  src/scenes/Office/index.jsx
  src/scenes/Office/office.scss
  src/shared/styles/fonts.scss
Labels: ttv

#2116 Remove ducks and api file for HHG
  src/scenes/Moves/Hhg/api.js
  src/scenes/Moves/Hhg/ducks.js
Labels: ttv

#2112 Kim 163338392 office denies sit request
  cypress/integration/office/storageInTransitPanel.js
  pkg/handlers/publicapi/storage_in_transits.go
  pkg/handlers/publicapi/storage_in_transits_test.go
  pkg/testdatagen/scenario/e2ebasic.go
  src/shared/Entities/modules/storageInTransits.js
  src/shared/StorageInTransit/ApproveSitRequest.jsx
  src/shared/StorageInTransit/DenySitRequest.jsx
  src/shared/StorageInTransit/PlaceInSit.jsx
  src/shared/StorageInTransit/StorageInTransit.jsx
  src/shared/StorageInTransit/StorageInTransitOfficeDenyForm.jsx
  swagger/api.yaml
Labels: A-Team

#1980 Add and wire up swagger file for admin API
  .circleci/config.yml
  .envrc
  .gitignore
  .pre-commit-config.yaml
  README.md
  cmd/milmove/main.go
  pkg/auth/authentication/auth.go
  pkg/auth/authentication/auth_test.go
  pkg/auth/authentication/devlocal.go
  pkg/auth/authentication/devlocal_test.go
  pkg/auth/authentication/login_gov.go
  pkg/auth/session.go
  pkg/cli/auth.go
  pkg/cli/swagger.go
  pkg/handlers/adminapi/api.go
  pkg/models/user.go
  pkg/models/user_test.go
  public/swagger-ui/admin.html
  scripts/copy-swagger-ui
  scripts/gen-server
  scripts/run-e2e-test-docker
  src/scenes/Admin/AdminHome.jsx
  src/scenes/Admin/AdminHome.test.jsx
  src/scenes/Admin/AdminUsers.jsx
  src/scenes/Admin/customRoutes.js
  src/scenes/Admin/index.jsx
  src/setupProxy.js
  src/shared/Data/users.js
  src/shared/Header/Admin/index.css
  src/shared/Header/Admin/index.jsx
  swagger/admin.yaml
Labels: A-Team

#2066 Migration to revert HHG shipments from `COMPLETED` back to `DELIVERED`, remove references to `COMPLETED` from test data gen, cypress tests, models, handlers, error responses
  cmd/generate_test_data/main.go
  cypress/integration/mymove/landingPages.js
  cypress/integration/office/officeUserHHG.js
  cypress/integration/office/officeUserHHGPPM.js
  cypress/integration/tsp/queues.js
  migrations/20190411173050_remove-complete-state-from-hhg-shipments.up.sql
  pkg/handlers/internalapi/personally_procured_move_test.go
  pkg/handlers/internalapi/shipments.go
  pkg/models/move.go
  pkg/models/move_test.go
  pkg/models/queue.go
  pkg/models/shipment.go
  pkg/models/shipment_test.go
  pkg/services/shipment/process_recalculate_shipment.go
  pkg/services/shipment/process_recalculate_shipment_test.go
  pkg/testdatagen/make_shipment_offer_records.go
  pkg/testdatagen/scenario/e2ebasic.go
  scripts/find-invoices
  src/scenes/Landing/MoveSummary.jsx
  src/scenes/Landing/MoveSummary.test.jsx
  src/scenes/Landing/StatusTimeline.jsx
  src/scenes/Office/MoveInfo.jsx
  src/scenes/Office/QueueList.jsx
  src/scenes/Office/QueueTable.jsx
  src/scenes/TransportationServiceProvider/ShipmentInfo.jsx
  src/scenes/TransportationServiceProvider/api.js
  src/shared/utils.js
  swagger/api.yaml
  swagger/internal.yaml
Labels: A-Team

#2109 Shipments column in the new moves/shipments queue
  pkg/models/queue.go
  src/scenes/Office/QueueTable.jsx
  src/scenes/Office/QueueTable.test.js
  src/scenes/Office/index.jsx
Labels: ttv

#2117 Add .queue-heading class to decrease queue top margin
  src/scenes/Office/QueueList.jsx
  src/scenes/Office/QueueTable.jsx
  src/scenes/Office/office.scss
  src/scenes/TransportationServiceProvider/QueueList.jsx
  src/scenes/TransportationServiceProvider/QueueTable.jsx
  src/scenes/TransportationServiceProvider/tsp.css
Labels: ttv

#2065 Alert users when we do not have rate data for their move date
  cypress/integration/mymove/ppm.js
  pkg/testdatagen/scenario/e2ebasic.go
  src/scenes/Moves/Ppm/DateAndLocation.jsx
  src/scenes/Moves/Ppm/Weight.jsx
  src/shared/WizardPage/Form.jsx
Labels: roci

#1959 Suppress bad moves in list: 164439301
  cypress/integration/office/homepage.js
  cypress/integration/tsp/homepage.js
  local_migrations/20190403150700_update-moves-show-flag.sql
  migrations/20190402183801_add-show-column-to-moves.up.fizz
  migrations/20190403150700_update-moves-show-flag.up.fizz
  pkg/handlers/internalapi/move_queue_items_test.go
  pkg/handlers/internalapi/office_test.go
  pkg/handlers/internalapi/orders.go
  pkg/handlers/internalapi/personally_procured_move_test.go
  pkg/models/move.go
  pkg/models/move_test.go
  pkg/models/order.go
  pkg/models/order_test.go
  pkg/models/personally_procured_move_test.go
  pkg/models/queue.go
  pkg/models/queue_test.go
  pkg/models/shipment.go
  pkg/testdatagen/make_move.go
  pkg/testdatagen/scenario/e2ebasic.go
  src/scenes/Office/QueueTable.jsx
  src/scenes/TransportationServiceProvider/QueueTable.jsx
Labels: ttv

#2126 Add single click handler for queue rows
  cypress/integration/office/homepage.js
  src/scenes/Office/QueueTable.jsx
  src/scenes/Office/office.scss
Labels: ttv

#2076 Incident followup: Error message for having the same current and new duty station
  cypress/integration/mymove/orders.js
  src/scenes/Orders/Orders.jsx
  src/scenes/ServiceMembers/DutyStation.css
  src/scenes/ServiceMembers/DutyStation.jsx
  src/scenes/ServiceMembers/DutyStationSearchBox.jsx
  src/shared/JsonSchemaForm/index.jsx
  src/shared/WizardPage/Form.jsx
Labels: roci

#2079 TSP redux refactoring
  cypress/integration/tsp/premoveSurvey.js
  src/appReducer.js
  src/scenes/TransportationServiceProvider/CustomerInfo.jsx
  src/scenes/TransportationServiceProvider/DocumentViewerContainer.jsx
  src/scenes/TransportationServiceProvider/NewDocumentContainer.jsx
  src/scenes/TransportationServiceProvider/PickupForm.jsx
  src/scenes/TransportationServiceProvider/PremoveSurveyForm.jsx
  src/scenes/TransportationServiceProvider/ServiceAgentForm.jsx
  src/scenes/TransportationServiceProvider/ShipmentInfo.jsx
  src/scenes/TransportationServiceProvider/api.js
  src/scenes/TransportationServiceProvider/ducks.js
  src/shared/Entities/modules/serviceAgents.js
  src/shared/Entities/modules/shipments.js
  src/shared/LocationsPanel/LocationsContainer.js
  src/shared/StorageInTransit/StorageInTransitPanel.jsx
  src/shared/TspPanel/TspContainer.jsx
  src/shared/store.js
Labels: ttv

#2080 Fix move date for moves in the 'new' and 'all' queues
  pkg/handlers/internalapi/move_queue_items_test.go
  pkg/models/queue.go
Labels: ttv

#2133 Add refresh button to office queue
  src/scenes/Office/QueueTable.jsx
  src/scenes/Office/QueueTable.test.js
  src/scenes/Office/office.scss
Labels: ttv

#2132 Add weight ticket uploader to PPM payment request Weight ticket page
  cypress/integration/mymove/ppm.js
  src/scenes/Moves/Ppm/WeightTicket.jsx
  src/scenes/Orders/UploadOrders.jsx
  src/scenes/Review/EditOrders.jsx
  src/shared/Uploader/index.jsx
Labels: roci

#2148 PPM success message persists after logout
  src/scenes/Landing/MoveSummary.jsx
  src/scenes/Landing/MoveSummary.test.jsx
  src/scenes/Landing/index.jsx
Labels: roci

#2138 Change office queue table highlight styling to blue
  src/scenes/Office/QueueTable.jsx
  src/scenes/Office/office.scss
Labels: ttv

#2153 Add link with weight scale locations to Move Summary page
  cypress/integration/mymove/ppm.js
  src/scenes/Landing/MoveSummary.jsx
Labels: roci

#2150 Show the proper move date in the "new" and "all" queues
  pkg/handlers/internalapi/move_queue_items_test.go
  pkg/models/queue.go
Labels: ttv

#2088 Generate access codes
  Makefile
  cmd/generate_access_codes/main.go
  local_migrations/20190507213921_add_access_codes.sql
  migrations/20190507213921_add_access_codes.up.fizz
Labels: roci

#2152 Update PPM success alerts
  cypress/integration/mymove/hhgPPM.js
  cypress/integration/mymove/ppm.js
  src/scenes/Landing/MoveSummary.jsx
  src/scenes/Landing/MoveSummary.test.jsx
  src/scenes/Landing/index.jsx
  src/scenes/Landing/index.test.js
  src/shared/WizardPage/Form.jsx
Labels: roci

#2163 Weight ticket page layout
  cypress/integration/mymove/ppm.js
  src/scenes/Moves/Ppm/PPMPaymentRequest.css
  src/scenes/Moves/Ppm/WeightTicket.jsx
  src/shared/RadioButton/index.js
  swagger/internal.yaml
Labels: roci

#2164 PPM Closeout Flow: Toggle between "Save & Add Another" and "Save & Continue" buttons
  cypress/integration/mymove/ppm.js
  src/scenes/Moves/Ppm/WeightTicket.jsx
  src/scenes/Moves/Ppm/WeightTicket.test.js
Labels: roci

#2147 Add queue staleness indicator
  cypress/integration/office/homepage.js
  src/scenes/Office/QueueTable.jsx
  src/scenes/Office/office.scss
  src/shared/formatters.js
  src/shared/formatters.test.js
Labels: ttv

#2145 Dt #165775587 migrate functions entities moves
  cypress/integration/mymove/hhgPPM.js
  cypress/integration/mymove/ppm.js
  src/scenes/Landing/index.jsx
  src/scenes/Legalese/SubmitPpm.jsx
  src/scenes/Legalese/ducks.js
  src/scenes/Legalese/index.jsx
  src/scenes/Moves/Hhg/Locations.jsx
  src/scenes/Moves/Hhg/MoveDate.jsx
  src/scenes/Moves/Hhg/Progear.jsx
  src/scenes/Moves/Hhg/WeightEstimate.jsx
  src/scenes/Moves/MoveType.jsx
  src/scenes/Moves/MoveTypeWizard.jsx
  src/scenes/Moves/Ppm/PPMSizeWizard.jsx
  src/scenes/Moves/Ppm/Weight.jsx
  src/scenes/Moves/Ppm/ducks.js
  src/scenes/Moves/Ppm/ducks.test.js
  src/scenes/Moves/api.js
  src/scenes/Moves/ducks.js
  src/scenes/Moves/ducks.test.js
  src/scenes/MyMove/index.jsx
  src/scenes/Orders/ducks.js
  src/scenes/Review/EditDateAndLocation.jsx
  src/scenes/Review/EditOrders.jsx
  src/scenes/Review/EditProfile.jsx
  src/scenes/Review/EditShipment.jsx
  src/scenes/Review/ProfileReview.jsx
  src/scenes/Review/Review.jsx
  src/scenes/Review/Summary.jsx
  src/shared/Data/users.js
  src/shared/Entities/modules/moves.js
  src/shared/UI/ducks.js
  src/shared/utils.js
Labels: ttv

#2178 Add /office_users endpoint for admin API
  pkg/handlers/adminapi/api.go
  pkg/handlers/adminapi/api_test.go
  pkg/handlers/adminapi/office_users.go
  pkg/handlers/adminapi/office_users_test.go
  swagger/admin.yaml
Labels: ttv

#2193 Allow TSP user to use a single click to open shipment
  cypress/integration/tsp/homepage.js
  src/scenes/TransportationServiceProvider/QueueTable.jsx
  src/scenes/TransportationServiceProvider/tsp.css
Labels: ttv

#2194 TSP queue refresh and staleness indicator
  cypress/integration/tsp/homepage.js
  src/scenes/TransportationServiceProvider/QueueList.jsx
  src/scenes/TransportationServiceProvider/QueueTable.jsx
  src/scenes/TransportationServiceProvider/QueueTable.test.js
  src/scenes/TransportationServiceProvider/ShipmentInfo.jsx
  src/scenes/TransportationServiceProvider/index.jsx
  src/scenes/TransportationServiceProvider/tsp.scss
Labels: ttv

#2196 Open "weight scales" link in new tab
  src/scenes/Landing/MoveSummary.jsx
Labels: roci

#2177 Jm 165553482 tsp release sit button form
  cypress/integration/tsp/storageInTransit.js
  pkg/services/storage_in_transit/release_storage_in_transit.go
  pkg/testdatagen/scenario/e2ebasic.go
  src/shared/Entities/modules/storageInTransits.js
  src/shared/StorageInTransit/ReleaseFromSit.jsx
  src/shared/StorageInTransit/ReleaseFromSitForm.jsx
  src/shared/StorageInTransit/ReleaseFromSitForm.test.jsx
  src/shared/StorageInTransit/StorageInTransit.css
  src/shared/StorageInTransit/StorageInTransit.jsx
  src/shared/StorageInTransit/StorageInTransitPanel.jsx
Labels: A-Team

#2199 duplicate copy-paste error with data-cy value fixed
  src/shared/StorageInTransit/StorageInTransit.jsx
Labels: A-Team

#2198 Add and organize new moves/shipments queue columns [delivers #165769221]
  src/scenes/Office/QueueTable.jsx
  src/scenes/Office/queueTableColumns.js
Labels: ttv

#2195 Update text to read 'Storage in Transit'
  src/scenes/Office/OrdersPanel.jsx
Labels: A-Team, bug

#2200 Display GBL# on the move info page
  cypress/integration/office/officeUserHHG.js
  cypress/integration/office/officeUserPPM.js
  src/scenes/Office/MoveInfo.jsx
Labels: ttv

#2206 Connect to the correct swagger package.
  pkg/handlers/adminapi/api.go
Labels: ttv

#2210 Hover styling for tsp queues
  src/scenes/Office/QueueTable.jsx
  src/scenes/Office/office.scss
  src/scenes/TransportationServiceProvider/index.jsx
  src/scenes/TransportationServiceProvider/tsp.scss
Labels: ttv

#2208 Update description of shipment language on GBL form [delivers #165924373]
  pkg/models/gov_bill_of_lading.go
Labels: ttv

#2201 Weight ticket checkboxes
  cypress/integration/mymove/ppm.js
  src/scenes/Moves/Ppm/PPMPaymentRequest.css
  src/scenes/Moves/Ppm/WeightTicket.jsx
  src/shared/Alert/index.jsx
  src/shared/Checkbox/Checkbox.css
  src/shared/Checkbox/index.js
Labels: roci

#2129 Claim Access Code
  mocks/AccessCodeClaimer.go
  pkg/handlers/publicapi/access_code.go
  pkg/handlers/publicapi/access_code_test.go
  pkg/handlers/publicapi/api.go
  pkg/services/accesscode.go
  pkg/services/accesscode/claim_access_code.go
  pkg/services/accesscode/claim_access_code_test.go
  swagger/api.yaml
Labels: roci

#2189 Add save button behavior to weight ticket page for new PPM closeout flow
  cypress/integration/mymove/ppm.js
  src/scenes/Moves/Ppm/PPMPaymentRequestActionBtns.jsx
  src/scenes/Moves/Ppm/PPMPaymentRequestIntro.jsx
  src/scenes/Moves/Ppm/WeightTicket.jsx
  src/scenes/Moves/Ppm/WeightTicket.test.js
  src/shared/JsonSchemaForm/SingleDatePicker.jsx
  src/shared/Uploader/index.jsx
Labels: roci

#2184 Update office new moves queue heading: 165749867
  cypress/integration/office/officeCSRFProtect.js
  src/scenes/Office/MoveInfo.jsx
  src/scenes/Office/MoveInfo.test.js
  src/scenes/Office/QueueList.jsx
  src/scenes/Office/QueueTable.jsx
Labels: ttv
