Repository transcom/mymove, pull requests merged in 2019-06, with the labels that each got.

#2225 PPM Weight Ticket: Car + Trailer layout
  cypress/integration/mymove/ppm.js
  src/scenes/Moves/Ppm/PPMPaymentRequest.css
  src/scenes/Moves/Ppm/WeightTicket.jsx
  src/shared/images/car-trailer_mobile.png
Labels: roci

#2215 Autogenerate mockery mocks
  .circleci/config.yml
  .dockerignore
  .gitignore
  Makefile
  docs/how-to/generate-mocks-with-mockery.md
  go.mod
  go.sum
  mocks/AccessCodeClaimer.go
  mocks/AccessCodeValidator.go
  mocks/FileStorer.go
  mocks/FormFiller.go
  mocks/StorageInTransitApprover.go
  mocks/StorageInTransitByIDFetcher.go
  mocks/StorageInTransitCreator.go
  mocks/StorageInTransitDeleter.go
  mocks/StorageInTransitDeliverer.go
  mocks/StorageInTransitDenier.go
  mocks/StorageInTransitInSITPlacer.go
  mocks/StorageInTransitPatcher.go
  mocks/StorageInTransitReleaser.go
  mocks/StorageInTransitsIndexer.go
  pkg/handlers/publicapi/access_code_test.go
  pkg/handlers/publicapi/storage_in_transits_test.go
  pkg/services/accesscode.go
  pkg/services/paperwork/create_form.go
  pkg/services/paperwork/create_form_test.go
  pkg/services/storage_in_transit.go
  pkg/tools/tools.go
Labels: roci

#2219 Reset vehicleType state to empty after submission
  src/scenes/Moves/Ppm/WeightTicket.jsx
Labels: roci

#2146 Migrate lastMoveIsCanceled and isPpm to entities
  src/scenes/Landing/index.jsx
  src/scenes/Moves/ducks.js
  src/scenes/MyMove/index.jsx
  src/scenes/Review/EditOrders.jsx
  src/scenes/Review/EditProfile.jsx
  src/scenes/Review/ProfileReview.jsx
  src/scenes/Review/Summary.jsx
  src/shared/Entities/modules/moves.js
Labels: ttv

#2243 TSP has ability to delete SIT
  cypress/integration/tsp/storageInTransit.js
  pkg/handlers/publicapi/storage_in_transits.go
  pkg/handlers/publicapi/storage_in_transits_test.go
  pkg/models/storage_in_transit.go
  pkg/models/storage_in_transit_test.go
  pkg/services/storage_in_transit.go
  pkg/services/storage_in_transit/delete_storage_in_transit.go
  pkg/services/storage_in_transit/delete_storage_in_transit_test.go
  src/shared/Entities/modules/storageInTransits.js
  src/shared/StorageInTransit/DeleteSitRequest.jsx
  src/shared/StorageInTransit/DeleteSitRequest.test.jsx
  src/shared/StorageInTransit/StorageInTransit.jsx
  src/shared/StorageInTransit/StorageInTransitPanel.jsx
  swagger/api.yaml
Labels: A-Team

#2240 Add endpoint for create and fetch weight ticket document
  migrations/20190604171035_create_weight_ticket_documents.up.sql
  pkg/handlers/internalapi/move_documents.go
  pkg/handlers/internalapi/move_documents_test.go
  pkg/handlers/internalapi/weight_ticket_set_documents.go
  pkg/handlers/internalapi/weight_ticket_set_documents_test.go
  pkg/models/move.go
  pkg/models/move_document.go
  pkg/models/move_documents_extractor.go
  pkg/models/move_documents_extractor_test.go
  pkg/models/weight_ticket_set_document.go
  pkg/models/weight_ticket_set_document_test.go
  pkg/testdatagen/make_weight_ticket_set_document.go
  pkg/testdatagen/shared.go
  src/scenes/Moves/Ppm/WeightTicket.jsx
  swagger/internal.yaml
Labels: roci

#2231 Expenses interstitial page
  cypress/integration/mymove/ppm.js
  src/scenes/Moves/Ppm/Expenses.css
  src/scenes/Moves/Ppm/ExpensesLanding.jsx
  src/scenes/Moves/Ppm/PPMPaymentRequest.css
  src/scenes/Moves/Ppm/PPMPaymentRequestActionBtns.jsx
  src/scenes/Moves/Ppm/WeightTicket.jsx
  src/scenes/MyMove/index.jsx
  src/shared/images/car_mobile.png
Labels: roci

#2229 Async validate zips and date in PPM creation
  cypress/integration/mymove/ppm.js
  cypress/integration/office/datesPanel.js
  cypress/integration/tsp/datesPanel.js
  cypress/support/datesPanel.js
  mocks/PostalCodeValidator.go
  pkg/handlers/publicapi/api.go
  pkg/handlers/publicapi/postal_codes.go
  pkg/handlers/publicapi/postal_codes_test.go
  pkg/services/postal_code.go
  pkg/services/postal_codes/validate_postal_code.go
  pkg/services/postal_codes/validate_postal_code_test.go
  src/scenes/Moves/Ppm/DateAndLocation.jsx
  src/scenes/Moves/Ppm/api.js
  src/shared/JsonSchemaForm/SingleDatePicker.jsx
  src/shared/WizardPage/Form.jsx
  swagger/api.yaml
Labels: roci

#2252 Save trailer weight ticket information
  cypress/integration/mymove/ppm.js
  migrations/20190607214336_add_missing_ownership_documentation_weight_ticket_documents.up.sql
  pkg/handlers/internalapi/api.go
  pkg/handlers/internalapi/move_documents.go
  pkg/handlers/internalapi/move_documents_test.go
  pkg/handlers/internalapi/weight_ticket_set_documents.go
  pkg/handlers/internalapi/weight_ticket_set_documents_test.go
  pkg/models/move.go
  pkg/models/move_documents_extractor.go
  pkg/models/weight_ticket_set_document.go
  src/scenes/Moves/Ppm/WeightTicket.jsx
  src/shared/Entities/modules/weightTicketSetDocuments.js
  swagger/internal.yaml
Labels: roci

#2247 Add trailer criteria for ppm weight ticket page
  cypress/integration/mymove/ppm.js
  src/scenes/Moves/Ppm/PPMPaymentRequest.css
  src/scenes/Moves/Ppm/TrailerCriteria.jsx
  src/scenes/Moves/Ppm/WeightTicket.jsx
  src/scenes/MyMove/index.jsx
Labels: roci

#2222 Editing SIT requests as TSP
  cypress/integration/office/storageInTransitPanel.js
  cypress/integration/tsp/storageInTransit.js
  pkg/models/storage_in_transit_test.go
  pkg/services/storage_in_transit/patch_storage_in_transit.go
  pkg/testdatagen/make_storage_in_transit.go
  pkg/testdatagen/scenario/e2ebasic.go
  src/shared/StorageInTransit/StorageInTransitTspEditForm.jsx
  src/shared/StorageInTransit/StorageInTransitTspEditForm.test.jsx
  src/shared/StorageInTransit/TspEditor.jsx
Labels: A-Team

#2265 Fix flaky go test TestGetMoveQueueItemsComboSubmittedDate
  pkg/handlers/internalapi/move_queue_items_test.go
Labels: ttv

#2254 Changed copy for allowable expenses
  cypress/integration/mymove/ppm.js
  src/scenes/Moves/Ppm/AllowableExpenses.jsx
  src/scenes/Moves/Ppm/PPMPaymentRequest.css
  src/scenes/Moves/Ppm/PPMPaymentRequestIntro.jsx
Labels: roci

#2259 Add moving expenses landing page
  cypress/integration/mymove/ppm.js
  src/scenes/Moves/Ppm/Expenses.css
  src/scenes/Moves/Ppm/ExpensesLanding.jsx
  src/scenes/Moves/Ppm/ExpensesUpload.jsx
  src/scenes/Moves/Ppm/PPMPaymentRequest.css
  src/scenes/MyMove/index.jsx
  swagger/internal.yaml
Labels: roci

#2253 add queue to show approved hhg moves
  cypress/integration/office/officeUserHHG.js
  cypress/integration/office/officeUserHHGPPM.js
  cypress/integration/office/storageInTransitPanel.js
  pkg/models/queue.go
  pkg/testdatagen/scenario/e2ebasic.go
  scripts/find-invoices
  src/scenes/Office/MoveInfo.jsx
  src/scenes/Office/MoveInfo.test.js
  src/scenes/Office/QueueList.jsx
  src/scenes/Office/QueueTable.jsx
  swagger/internal.yaml
Labels: ttv

#2273 PPM payment request: Non-storage Expense page: Save behavior
  cypress/integration/mymove/ppm.js
  migrations/20190612185213_add_receipt_missing_moving_expense_documents.up.sql
  pkg/handlers/internalapi/move_documents.go
  pkg/handlers/internalapi/moving_expense_documents.go
  pkg/handlers/internalapi/moving_expense_documents_test.go
  pkg/models/move.go
  pkg/models/move_documents_extractor.go
  pkg/models/moving_expense_document.go
  src/scenes/Moves/Ppm/ExpensesUpload.jsx
  src/scenes/Moves/Ppm/PaymentRequest.jsx
  src/scenes/Office/DocumentViewer/DocumentUploader.jsx
  src/scenes/Office/DocumentViewer/index.jsx
  src/shared/Entities/modules/movingExpenseDocuments.js
  swagger/internal.yaml
Labels: roci

#2282 PPM payment request: Weight ticket page: Allow Saving empty weight tickets
  cypress/integration/mymove/ppm.js
  pkg/handlers/internalapi/weight_ticket_set_documents.go
  src/scenes/Moves/Ppm/WeightTicket.jsx
  src/scenes/Moves/Ppm/WeightTicket.test.js
Labels: roci

#2278 Add deploy to experimental instructions
  .spelling
  docs/README.md
  docs/how-to/deploy-to-experimental.md
Labels: roci

#2272 Dt rk #164080608 fetch accessorial errors
  mocks/ShipmentLineItemFetcher.go
  mocks/ShipmentLineItemRecalculator.go
  pkg/handlers/publicapi/api.go
  pkg/handlers/publicapi/shipment_line_items.go
  pkg/handlers/publicapi/shipment_line_items_test.go
  pkg/services/shipment_line_item.go
  pkg/services/shipment_line_item/get_shipment_line_items.go
  pkg/services/shipment_line_item/get_shipment_line_items_test.go
  pkg/services/shipment_line_item/logger.go
  pkg/services/shipment_line_item/recalculate_shipment_line_items.go
  pkg/services/shipment_line_item/recalculate_shipment_line_items_test.go
  pkg/services/shipment_line_item/shipment_line_item_service_test.go
  src/scenes/Office/MoveInfo.jsx
  src/scenes/TransportationServiceProvider/ShipmentInfo.jsx
  src/shared/Entities/modules/shipmentLineItems.js
  src/shared/Invoice/InvoicePanel.jsx
  src/shared/Invoice/InvoicePanel.module.scss
  swagger/api.yaml
Labels: ttv

#2294 Add storage dates to moving_expense_documents endpoint
  migrations/20190617184232_add_storage_start_end_date_to_moving_expenses.up.sql
  pkg/handlers/internalapi/move_documents.go
  pkg/handlers/internalapi/moving_expense_documents.go
  pkg/handlers/internalapi/moving_expense_documents_test.go
  pkg/models/move.go
  pkg/models/move_document_test.go
  pkg/models/move_documents_extractor.go
  pkg/models/moving_expense_document.go
  swagger/internal.yaml
Labels: roci

#2292 Office PPM queue: only show ppms in approved, payment requested and completed status [delivers #165859430]
  cypress/integration/office/officeUserPPM.js
  pkg/handlers/internalapi/move_queue_items_test.go
  pkg/models/queue.go
  pkg/models/queue_test.go
Labels: ttv

#2295 PPM Payment Request: Add storage expense form
  cypress/integration/mymove/ppm.js
  cypress/integration/office/documentViewer.js
  cypress/integration/office/officeUserHHGPPM.js
  src/scenes/Moves/Ppm/Expenses.css
  src/scenes/Moves/Ppm/ExpensesUpload.jsx
  src/shared/Entities/modules/movingExpenseDocuments.js
  swagger/internal.yaml
Labels: roci

#2297 PPM Payment Request: Weight Ticket Set Indicator Behavior
  cypress/integration/mymove/ppm.js
  pkg/handlers/internalapi/weight_ticket_set_documents.go
  src/scenes/Moves/Ppm/ExpensesUpload.jsx
  src/scenes/Moves/Ppm/WeightTicket.jsx
  src/scenes/Moves/Ppm/utility.js
  src/shared/Entities/modules/movingExpenseDocuments.js
Labels: roci

#2303 Validate SM current address zip
  cypress/integration/mymove/serviceMemberProfile.js
  src/scenes/Moves/Ppm/DateAndLocation.jsx
  src/scenes/Moves/Ppm/api.js
  src/scenes/ServiceMembers/ResidentialAddress.jsx
  src/shared/api.js
Labels: roci

#2305 PPM payment request: Number of documents loaded shows (alert) on pages in flow
  cypress/integration/mymove/ppm.js
  src/scenes/Moves/Ppm/DocumentsUploaded.js
  src/scenes/Moves/Ppm/DocumentsUploaded.test.js
  src/scenes/Moves/Ppm/ExpensesLanding.jsx
  src/scenes/Moves/Ppm/ExpensesUpload.jsx
  src/scenes/Moves/Ppm/WeightTicket.jsx
Labels: roci

#2311 PPM Closeout: Revisiting weight tickets and expense page behavior.
  cypress/integration/mymove/ppm.js
  pkg/handlers/internalapi/move_documents.go
  src/scenes/Moves/Ppm/ExpensesLanding.jsx
  src/scenes/Moves/Ppm/ExpensesUpload.jsx
  src/scenes/Moves/Ppm/PaymentReview/index.jsx
  src/scenes/Moves/Ppm/WeightTicket.jsx
  src/scenes/Moves/Ppm/WeightTicket.test.js
  src/scenes/Moves/Ppm/utility.js
  src/scenes/Moves/Ppm/utility.test.js
  src/scenes/MyMove/index.jsx
Labels: roci

#2316 PPM Payment Request: Payment Review Layout
  src/scenes/Moves/Ppm/PaymentReview/ExpenseTicketListItem.jsx
  src/scenes/Moves/Ppm/PaymentReview/PaymentReview.css
  src/scenes/Moves/Ppm/PaymentReview/WeightTicketListItem.jsx
  src/scenes/Moves/Ppm/PaymentReview/index.jsx
  src/scenes/Moves/Ppm/WeightTicket.jsx
  src/scenes/MyMove/index.jsx
  src/shared/images/box_truck_mobile.png
  src/shared/images/delete-doc-button.png
Labels: roci

#2293 Add Active queue to Office
  cypress/integration/office/officeUserHHG.js
  cypress/integration/office/officeUserHHGPPM.js
  pkg/handlers/internalapi/move_queue_items.go
  pkg/handlers/internalapi/move_queue_items_test.go
  pkg/handlers/internalapi/storage_in_transits.go
  pkg/models/queue.go
  pkg/models/queue_test.go
  pkg/models/shipment.go
  scripts/find-invoices
  src/scenes/Office/MoveInfo.jsx
  src/scenes/Office/MoveInfo.test.js
  src/scenes/Office/QueueList.jsx
  src/scenes/Office/QueueTable.jsx
  src/scenes/Office/queueTableColumns.js
  swagger/internal.yaml
Labels: ttv

#2317 Remove usa-width css and utilize media css
  cypress/integration/mymove/hhgPPM.js
  src/scenes/Moves/WizardHeader.css
  src/scenes/Moves/WizardHeader.jsx
Labels: roci

#2318 PPM Closeout: Add customer agreement + legalese page
  cypress/integration/mymove/ppm.js
  src/scenes/Legalese/CustomerAgreement.jsx
  src/scenes/Moves/Ppm/CustomerAgreeementLegalese.css
  src/scenes/Moves/Ppm/CustomerAgreementLegalese.js
  src/scenes/Moves/Ppm/PaymentReview/PaymentReview.css
  src/scenes/Moves/Ppm/PaymentReview/index.jsx
  src/scenes/MyMove/index.jsx
Labels: roci

#2327 PPM Closeout: Make weight ticket fields optional when users are missing weight ticket
  cypress/integration/mymove/ppm.js
  pkg/handlers/internalapi/move_documents_test.go
  pkg/handlers/internalapi/weight_ticket_set_documents.go
  pkg/models/move.go
  pkg/models/weight_ticket_set_document.go
  pkg/models/weight_ticket_set_document_test.go
  pkg/testdatagen/make_weight_ticket_set_document.go
  src/scenes/Moves/Ppm/WeightTicket.jsx
  swagger/internal.yaml
Labels: roci

#2326 Only fire blur event when the calendar closes.
  src/shared/JsonSchemaForm/SingleDatePicker.jsx
Labels: roci
