Repository transcom/mymove, pull requests merged in 2019-04, with the labels that each got.

#1935 Adding secure migration for new office users
  local_migrations/20190329144450_add_office_users.sql
  migrations/20190329144450_add_office_users.up.fizz
Labels: 🦇team

#1944 Enable combo button in production and update e2e tests
  cypress/integration/office/officeUserHHG.js
  cypress/integration/office/officeUserHHGPPM.js
  cypress/integration/office/officeUserPPM.js
  src/scenes/Office/MoveInfo.jsx
  src/shared/featureFlags.js
Labels: roci

#1941 Create PPM Payment Request Instructions Page
  cypress/integration/mymove/ppm.js
  src/scenes/Landing/MoveSummary.jsx
  src/scenes/Landing/index.jsx
  src/scenes/Moves/Ppm/PPMPaymentRequest.css
  src/scenes/Moves/Ppm/PPMPaymentRequestActionBtns.jsx
  src/scenes/Moves/Ppm/PPMPaymentRequestIntro.jsx
  src/scenes/MyMove/index.jsx
  src/shared/featureFlags.js
Labels: roci

#1938 Support Create Robust Item 125A/B/C/D Pre-Approval Request [delivers #164842324]
  migrations/20190328164048_shipment_line_items_new_cols_item_125.up.fizz
  pkg/handlers/converters.go
  pkg/handlers/publicapi/shipment_line_items.go
  pkg/models/robust_accessorial_line_item.go
  pkg/models/robust_accessorial_line_item_test.go
  pkg/models/shipment.go
  pkg/models/shipment_line_item.go
  pkg/models/validators.go
  swagger/api.yaml
Labels: ttv

#1915 Update PPM Panel Homepage Timeline From Image to CSS
  src/scenes/Landing/MoveSummary.jsx
  src/scenes/Landing/StatusTimeline.css
  src/scenes/Landing/StatusTimeline.jsx
  src/scenes/Landing/StatusTimeline.test.jsx
Labels: roci

#1942 Add "Delivered on" column to TSP queue.
  cypress/integration/tsp/queues.js
  src/scenes/TransportationServiceProvider/QueueTable.jsx
Labels: ttv

#1947 Add payment steps to the PPM timeline
  src/scenes/Landing/StatusTimeline.css
  src/scenes/Landing/StatusTimeline.jsx
  src/scenes/Landing/StatusTimeline.test.jsx
Labels: roci

#1939 Remove pagination from TSP queues index
  pkg/handlers/publicapi/shipments.go
  pkg/handlers/publicapi/shipments_test.go
  pkg/models/shipment.go
  src/scenes/TransportationServiceProvider/QueueTable.jsx
  src/scenes/TransportationServiceProvider/api.js
  src/scenes/TransportationServiceProvider/tsp.css
  swagger/api.yaml
Labels: ttv

#1956 update BuyerID to use DDSAOFM for initial invoicing payments
  pkg/edi/invoice/generator.go
  pkg/edi/invoice/testdata/expected_invoice.edi.golden
Labels: A-Team

#1963 Prepopulate date field in office sit approval form
  cypress/integration/office/storageInTransitPanel.js
  src/shared/StorageInTransit/ApproveSitRequest.jsx
  src/shared/StorageInTransit/StorageInTransit.jsx
  src/shared/StorageInTransit/StorageInTransitOfficeApprovalForm.test.jsx
Labels: A-Team

#1965 Kim 164903358 tsp place into sit buttons
  cypress/integration/tsp/storageInTransit.js
  pkg/handlers/publicapi/storage_in_transits.go
  pkg/testdatagen/scenario/e2ebasic.go
  src/shared/EditablePanel/index.css
  src/shared/StorageInTransit/PlaceInSit.jsx
  src/shared/StorageInTransit/PlaceInSitForm.jsx
  src/shared/StorageInTransit/PlaceInSitForm.test.jsx
  src/shared/StorageInTransit/StorageInTransit.css
  src/shared/StorageInTransit/StorageInTransit.jsx
  src/shared/StorageInTransit/StorageInTransitPanel.jsx
Labels: A-Team

#1974 Remove "Complete Shipments" button and associated tests
  cypress/integration/office/officeUserHHG.js
  pkg/handlers/internalapi/api.go
  pkg/handlers/internalapi/shipments.go
  pkg/handlers/internalapi/shipments_test.go
  src/scenes/Office/MoveInfo.jsx
  src/shared/Entities/modules/shipments.js
Labels: A-Team

#1929 Add digital signature to shipment summary worksheet
  cmd/generate_shipment_summary/main.go
  migrations/20190327145406_update-signed-certifications-date-to-datetime.up.sql
  pkg/handlers/internalapi/moves.go
  pkg/handlers/internalapi/moves_test.go
  pkg/handlers/internalapi/signed_certifications.go
  pkg/handlers/internalapi/signed_certifications_test.go
  pkg/models/shipment_summary_worksheet.go
  pkg/models/shipment_summary_worksheet_test.go
  pkg/models/signed_certification.go
  pkg/models/signed_certification_test.go
  pkg/paperwork/forms.go
  pkg/paperwork/formtemplates/shipment_summary_worksheet_page1.png
  pkg/paperwork/formtemplates/shipment_summary_worksheet_page2.png
  pkg/paperwork/shipment_summary_worksheet.go
  pkg/testdatagen/make_signed_certification.go
  pkg/testdatagen/shared.go
  src/scenes/Legalese/ducks.js
  src/scenes/Legalese/ducks.test.js
  src/scenes/Moves/Ppm/PaymentRequest.jsx
  swagger/internal.yaml
Labels: roci

#1962 Support Update Robust Item 125 Pre-Approval Request [delivers #164815871]
  migrations/20190403232809_shipment_line_item_update_foreign_key.up.sql
  pkg/handlers/converters_strfmt.go
  pkg/handlers/publicapi/addresses.go
  pkg/handlers/publicapi/shipment_line_items.go
  pkg/handlers/publicapi/shipment_line_items_test.go
  pkg/models/robust_accessorial_line_item.go
  pkg/models/robust_accessorial_line_item_test.go
  pkg/models/shipment_line_item.go
Labels: ttv

#1971 Fix flaky test by clearing all BaseUrl cookies: 164803621
  cypress/integration/mymove/hhgPPM.js
  cypress/integration/mymove/landingPages.js
  cypress/integration/mymove/orders.js
  cypress/integration/mymove/ppm.js
  cypress/integration/mymove/shipment.js
  cypress/support/commands.js
Labels: ttv

#1973 Bug fix - allow 35A legacy invoices: 165099148
  pkg/services/invoice/fetch_invoice_for_shipment.go
  pkg/services/invoice/fetch_invoice_for_shipment_test.go
  src/shared/Invoice/LineItemTable.jsx
  src/shared/Invoice/LineItemTable.test.js
  src/shared/Invoice/UnbilledTable.test.js
Labels: ttv

#1984 Add New Office Users Secure Migration [delivers #165129500]
  local_migrations/20190408211953_add_office_users_040819.sql
  migrations/20190408211953_add_office_users_040819.up.fizz
Labels: 🦇team

#1953 Fix bug with missing moving dates summary in shipments.
  cypress/integration/mymove/shipment.js
  src/scenes/Landing/MoveSummary.jsx
  src/scenes/Landing/StatusTimeline.jsx
  src/shared/Data/users.js
Labels: roci

#1988 Remove scrollable queue table div to get rid of gray bar.
  src/scenes/Office/index.jsx
  src/scenes/Office/office.css
  src/scenes/TransportationServiceProvider/index.jsx
Labels: ttv

#1983 TSP queue default sort
  src/scenes/TransportationServiceProvider/QueueTable.jsx
Labels: ttv

#1982 Office queue default sort
  pkg/testdatagen/scenario/e2ebasic.go
  src/scenes/Office/QueueTable.jsx
Labels: ttv

#1989 Remove duplicate cancel move and approval buttons on office app
  cypress/integration/office/officeUserHHG.js
  src/scenes/Office/MoveInfo.jsx
Labels: roci

#1992 Add April diesel fuel price data
  migrations/20190409155001_add_april_fuel_eia_diesel_prices.up.sql
Labels: A-Team

#1958 ActualAmount remains editable after 35A PAR has been approved RESTART
  cypress/integration/office/preApprovalRequest.js
  cypress/support/commands.js
  pkg/handlers/publicapi/shipment_line_items.go
  pkg/handlers/publicapi/shipment_line_items_test.go
  pkg/models/robust_accessorial_line_item.go
  pkg/models/shipment_line_item.go
  pkg/services/invoice/fetch_invoice_for_shipment.go
  pkg/services/invoice/fetch_invoice_for_shipment_test.go
  src/shared/Entities/modules/shipmentLineItems.js
  src/shared/Invoice/LineItemTable.jsx
  src/shared/PreApprovalRequest/Code35Form.jsx
  src/shared/PreApprovalRequest/PreApprovalForm.jsx
  src/shared/PreApprovalRequest/PreApprovalRequest.jsx
  src/shared/utils.js
  swagger/api.yaml
Labels: ttv

#1985 PPM Payment Request Instructions Page
  cypress/integration/mymove/ppm.js
  src/scenes/Moves/Ppm/AllowableExpenses.jsx
  src/scenes/Moves/Ppm/PPMPaymentRequest.css
  src/scenes/Moves/Ppm/PPMPaymentRequestIntro.jsx
  src/scenes/Moves/Ppm/WeightTicketExamples.jsx
  src/scenes/MyMove/index.jsx
  src/shared/images/weight_scenario1.png
  src/shared/images/weight_scenario2.png
  src/shared/images/weight_scenario3.png
  src/shared/images/weight_scenario4.png
  src/shared/images/weight_scenario5.png
  src/shared/images/weight_tix_example.png
Labels: roci

#1990 Remove duplicate success messages for completion of PPM setup
  cypress/integration/mymove/ppm.js
  src/scenes/Landing/index.jsx
Labels: roci

#1991 Show all expenses regardless of status shipment summary worksheet
  pkg/handlers/internalapi/personally_procured_move.go
  pkg/models/move_document.go
  pkg/models/move_document_test.go
  pkg/models/shipment_summary_worksheet.go
  pkg/models/shipment_summary_worksheet_test.go
Labels: roci

#2001 Secure Migration to Add New Office Users [delivers #165257230]
  local_migrations/20190411175501_add_office_users.sql
  migrations/20190411175501_add_office_users.up.fizz
Labels: 🦇team

#1969 TSP column cleanup
  pkg/handlers/internalapi/move_queue_items.go
  pkg/models/queue.go
  src/scenes/Office/QueueTable.jsx
  src/scenes/TransportationServiceProvider/QueueTable.jsx
  src/shared/formatters.js
  src/shared/formatters.test.js
  swagger/internal.yaml
Labels: ttv

#1998 Remove old shipment summary worksheet code
  Makefile
  cmd/paperwork/shipment_summary.go
  pkg/paperwork/advance_paperwork.go
  pkg/paperwork/shipment_summary.go
Labels: roci

#1999 Replace patchShipment and loadShipmentDependencies
  src/scenes/TransportationServiceProvider/CustomerInfo.jsx
  src/scenes/TransportationServiceProvider/DocumentViewerContainer.jsx
  src/scenes/TransportationServiceProvider/NewDocumentContainer.jsx
  src/scenes/TransportationServiceProvider/ShipmentInfo.jsx
  src/scenes/TransportationServiceProvider/api.js
  src/scenes/TransportationServiceProvider/ducks.js
  src/shared/Entities/modules/shipments.js
  src/shared/LocationsPanel/LocationsContainer.js
  src/shared/StorageInTransit/StorageInTransitPanel.jsx
Labels: ttv

#2006 Only show relevant entitlement line items on shipment summary worksheet
  pkg/models/shipment_summary_worksheet.go
  pkg/models/shipment_summary_worksheet_test.go
  pkg/paperwork/shipment_summary.go
  pkg/paperwork/shipment_summary_test.go
Labels: roci

#2003 Update PPM model to use unit.Pound for weights
  pkg/handlers/internalapi/entitlements_test.go
  pkg/handlers/internalapi/moves_test.go
  pkg/handlers/internalapi/personally_procured_move.go
  pkg/handlers/internalapi/personally_procured_move_test.go
  pkg/models/move.go
  pkg/models/personally_procured_move.go
  pkg/models/shipment_summary_worksheet_test.go
  pkg/testdatagen/make_ppm.go
Labels: roci

#2011 Remove feature flag check for 35a
  src/shared/Invoice/LineItemTable.jsx
  src/shared/PreApprovalRequest/DetailsHelper.js
  src/shared/PreApprovalRequest/DetailsHelper.test.js
Labels: ttv

#2009 Secure Migration to Add New Office Users [delivers #165229675]
  local_migrations/20190412211739_add_office_users.sql
  migrations/20190412211739_add_office_users.up.fizz
Labels: 🦇team

#2016 update supplier IDs for TSPs in production
  local_migrations/20190415193743_update_tsp_supplier_id.sql
  migrations/20190415193743_update_tsp_supplier_id.up.fizz
Labels: A-Team

#2012 Limit visibility of Storage, Weight, and Locations panels for ppm tab
  cypress/integration/mymove/landingPages.js
  cypress/integration/office/officeUserPPM.js
  pkg/testdatagen/scenario/e2ebasic.go
  src/scenes/Landing/StatusTimeline.jsx
  src/scenes/Office/MoveInfo.jsx
Labels: roci

#2019 Replace completePmSurvey
  cypress/integration/tsp/premoveSurvey.js
  src/scenes/TransportationServiceProvider/ShipmentInfo.jsx
  src/scenes/TransportationServiceProvider/api.js
  src/scenes/TransportationServiceProvider/ducks.js
  src/shared/Entities/modules/shipments.js
Labels: ttv

#2026 Sb 165150181 replace shipment actions with swagger actions
  src/scenes/TransportationServiceProvider/ShipmentInfo.jsx
  src/scenes/TransportationServiceProvider/api.js
  src/scenes/TransportationServiceProvider/ducks.js
  src/shared/Entities/modules/shipments.js
Labels: ttv

#2018 Disable shipment summary worksheet button when req data is missing
  pkg/handlers/internalapi/api.go
  pkg/handlers/internalapi/signed_certifications.go
  pkg/handlers/internalapi/signed_certifications_test.go
  pkg/models/signed_certification.go
  pkg/models/signed_certification_test.go
  src/scenes/Office/Ppm/PaymentsPanel.jsx
  src/scenes/Office/Ppm/PaymentsPanel.test.js
  src/shared/Entities/modules/signed_certifications.js
  src/shared/Entities/reducer.js
  src/shared/Entities/schema.js
  swagger/internal.yaml
Labels: roci

#2023 Add goland debugger build to makefile
  Makefile
  README.md
Labels: roci

#2022 Mk 165498814 fix submit docs combo move
  cypress/integration/office/officeUserHHGPPM.js
  pkg/models/move.go
Labels: roci

#2010 Add Normalizer Function for Edipi (DoD ID) fields [delivers #164807455]
  src/scenes/ServiceMembers/DodInfo.jsx
  src/shared/JsonSchemaForm/JsonSchemaField.js
  src/shared/JsonSchemaForm/reduxFieldNormalizer.js
  src/shared/JsonSchemaForm/validations.test.js
  src/shared/JsonSchemaForm/validator.js
  swagger/api.yaml
  swagger/internal.yaml
Labels: 🦇team

#2017 update SIT GET handler to use service structure
  mocks/StorageInTransitByIDFetcher.go
  pkg/handlers/publicapi/api.go
  pkg/handlers/publicapi/storage_in_transits.go
  pkg/handlers/publicapi/storage_in_transits_test.go
  pkg/models/storage_in_transit.go
  pkg/services/storage_in_transit/fetch_storage_in_transit_by_id.go
  pkg/services/storage_in_transit/fetch_storage_in_transit_by_id_test.go
  pkg/services/storage_in_transit/logger.go
  pkg/services/storage_in_transit/storage_in_transit_service_test.go
Labels: A-Team, wip

#2031 Remove pre-move survey panel
  cypress/integration/office/officePremoveSurvey.js
  cypress/integration/office/weightsAndItemsPanel.js
  src/scenes/Office/MoveInfo.jsx
  src/scenes/Office/PremoveSurvey.jsx
Labels: ttv

#2034 Add panic middleware
  cmd/milmove/main.go
  cmd/milmove/main_test.go
Labels: roci

#1925 Prepare Address Field for Robust Accessorial use
  cypress/integration/office/locationsPanel.js
  cypress/integration/tsp/locationsPanel.js
  cypress/integration/tsp/storageInTransit.js
  cypress/support/testCreateStorageInTransit.js
  src/scenes/Office/BackupInfoPanel.jsx
  src/scenes/Office/CustomerInfoPanel.jsx
  src/scenes/TransportationServiceProvider/Locations.jsx
  src/scenes/TransportationServiceProvider/LocationsContainer.js
  src/shared/Address/index.jsx
  src/shared/Address/index.module.scss
  src/shared/Address/index.test.js
  src/shared/LocationsPanel/LocationsPanel.jsx
  src/shared/LocationsPanel/LocationsPanel.test.js
  src/shared/StorageInTransit/StorageInTransit.jsx
  src/shared/StorageInTransit/StorageInTransitForm.jsx
  swagger/api.yaml
  swagger/internal.yaml
Labels: ttv

#2048 Adjust field alignment for shipment summary worksheet
  pkg/models/shipment_summary_worksheet.go
  pkg/models/shipment_summary_worksheet_test.go
  pkg/paperwork/shipment_summary_worksheet.go
Labels: roci

#1930 Saves PPM Submit Date
  Makefile
  docs/how-to/instrument-data-in-honeycomb.md
  migrations/20190326180606_add_submit_date_to_ppm.up.fizz
  pkg/handlers/internalapi/moves.go
  pkg/handlers/internalapi/moves_test.go
  pkg/handlers/internalapi/office.go
  pkg/handlers/internalapi/office_test.go
  pkg/handlers/internalapi/personally_procured_move.go
  pkg/handlers/internalapi/personally_procured_move_test.go
  pkg/models/move.go
  pkg/models/move_test.go
  pkg/models/order_test.go
  pkg/models/personally_procured_move.go
  pkg/models/shipment_summary_worksheet_test.go
  pkg/testdatagen/scenario/e2ebasic.go
  src/scenes/Legalese/ducks.js
  src/scenes/Legalese/index.jsx
  src/scenes/Moves/api.js
  swagger/internal.yaml
Labels: roci

#2054 Remove deprecated test data generator code
  pkg/awardqueue/awardqueue_test.go
  pkg/edi/invoice/generator_test.go
  pkg/models/shipment_offer_test.go
  pkg/models/shipment_test.go
  pkg/models/traffic_distribution_list_test.go
  pkg/models/transportation_service_provider_performance_test.go
  pkg/services/invoice/invoice_service_test.go
  pkg/services/invoice/update_invoice_upload_test.go
  pkg/testdatagen/make_shipment_offer_records.go
  pkg/testdatagen/make_tsp_performance_records.go
  pkg/testdatagen/scenario/awardqueue.go
  pkg/testdatagen/scenario/e2ebasic.go
Labels: roci

#2051 Add missing 400ng item rate for `130J`
  migrations/20190426134841_insert_missing_400ng_item_rate_130J.up.sql
Labels: 🦇team

#2059 Hide expenses panel in SSW PPM tab
  cypress/integration/office/officeUserPPM.js
  src/scenes/Office/MoveInfo.jsx
Labels: roci

#2060 Fix tariff400ng_item_rates lower weight and rate_cents
  migrations/20190429161555_fix-item-rates-cents-weight-lower.up.sql
Labels: 🦇team

#2008 Update go dependencies
  Makefile
  cmd/update_deps/main.go
  docs/README.md
  docs/how-to/manage-dependencies-with-go-mod.md
  go.mod
  go.sum
  pkg/tools/tools.go
Labels: roci

#2046 Integrate React admin into app
  package.json
  src/appReducer.js
  src/scenes/Admin/AdminHome.jsx
  src/scenes/Admin/AdminUsers.jsx
  src/scenes/Admin/customRoutes.js
  src/scenes/Admin/index.jsx
  src/scenes/Admin/index.test.jsx
  src/shared/store.js
  yarn.lock
Labels: A-Team

#2055 Office queue PPM changes
  cypress/integration/office/ppmQueue.js
  pkg/models/queue.go
  src/scenes/Office/QueueList.jsx
  src/scenes/Office/QueueTable.jsx
Labels: ttv

#2056 Show submitted, approved, and in progress dates in PPM timeline.
  cypress/integration/mymove/ppm.js
  src/scenes/Landing/StatusTimeline.jsx
  src/scenes/Landing/StatusTimeline.test.jsx
Labels: roci

#2061 Dissallow same destination and pickup zip for PPMs
  cypress/integration/mymove/ppm.js
  src/scenes/Moves/Ppm/DateAndLocation.jsx
Labels: roci
