Repository transcom/mymove, pull requests merged in 2019-02, with the labels that each got.

#1683 Redux Refactor - Move backup contacts to entities
  pkg/handlers/internalapi/backup_contacts.go
  pkg/handlers/publicapi/backup_contacts.go
  src/scenes/Office/BackupInfoPanel.jsx
  src/scenes/Office/MoveInfo.jsx
  src/scenes/Office/api.js
  src/scenes/Office/ducks.js
  src/shared/Entities/modules/serviceMembers.js
  src/shared/Entities/reducer.js
  src/shared/Entities/schema.js
  swagger/api.yaml
  swagger/internal.yaml
Labels: roci

#1689 Move service member to entities
  src/scenes/Office/BackupInfoPanel.jsx
  src/scenes/Office/CustomerInfoPanel.jsx
  src/scenes/Office/DocumentViewer/index.jsx
  src/scenes/Office/MoveInfo.jsx
  src/scenes/Office/OrdersInfo.jsx
  src/scenes/Office/OrdersPanel.jsx
  src/scenes/Office/OrdersViewerPanel.js
  src/scenes/Office/QueueTable.jsx
  src/scenes/Office/ducks.js
  src/shared/Entities/modules/serviceMembers.js
  src/shared/Entities/schema.js
  src/shared/Swagger/selectors.js
Labels: roci

#1697 modify allowed location for Linehaul Transportation(LHS) to origin: #163407346
  migrations/20190201172557_modify_lhs_location.up.sql
  pkg/edi/invoice/generator_test.go
  pkg/models/shipment_line_item.go
  pkg/models/shipment_test.go
  pkg/rateengine/line_items.go
  pkg/rateengine/line_items_test.go
  pkg/service/invoice/update_invoice_upload_test.go
  pkg/testdatagen/make_shipment_offer_records.go
  pkg/testingsuite/pop_suite.go
Labels: ttv

#1679 CreateForm service object
  Gopkg.lock
  Gopkg.toml
  docs/README.md
  docs/how-to/generate-mocks-with-mockery.md
  mocks/FileStorer.go
  mocks/FormFiller.go
  pkg/handlers/publicapi/api.go
  pkg/handlers/publicapi/shipments.go
  pkg/handlers/publicapi/shipments_test.go
  pkg/services/paperwork.go
  pkg/services/paperwork/create_form.go
  pkg/services/paperwork/create_form_test.go
Labels: roci

#1693 Support for More Robust Item Code 105B/E Pre-Approval Request Creation
  migrations/20190129191416_shipmentLineItem_dimensions.up.fizz
  pkg/handlers/publicapi/shipment_line_items.go
  pkg/models/shipment.go
  pkg/models/shipment_line_item.go
  pkg/models/shipment_line_item_dimension.go
  pkg/models/shipment_test.go
  pkg/unit/base_quantity.go
  pkg/unit/thousandth_inches.go
  src/shared/PreApprovalRequest/Creator.jsx
  src/shared/PreApprovalRequest/DetailsHelper.js
  src/shared/PreApprovalRequest/DetailsHelper.test.js
  src/shared/formatters.js
  swagger/api.yaml
Labels: ttv

#1709 Roc #163244221 office ppms to entities
  src/scenes/Office/DocumentViewer/DocumentDetailPanel.jsx
  src/scenes/Office/DocumentViewer/DocumentUploader.jsx
  src/scenes/Office/DocumentViewer/index.jsx
  src/scenes/Office/MoveInfo.jsx
  src/scenes/Office/Ppm/ExpensesPanel.jsx
  src/scenes/Office/Ppm/IncentiveCalculator.jsx
  src/scenes/Office/Ppm/PPMEstimatesPanel.jsx
  src/scenes/Office/Ppm/PaymentsPanel.jsx
  src/scenes/Office/Ppm/StorageReimbursementCalculator.jsx
  src/scenes/Office/api.js
  src/scenes/Office/ducks.js
  src/scenes/Office/ducks.test.js
  src/shared/Entities/modules/ppms.js
  src/shared/Entities/schema.js
  src/shared/Swagger/request.js
Labels: roci

#1690 Populate Maximum Obligations Section of SSW
  cmd/generate_shipment_summary/main.go
  pkg/handlers/internalapi/moves.go
  pkg/handlers/internalapi/personally_procured_move.go
  pkg/handlers/internalapi/personally_procured_move_estimate.go
  pkg/handlers/internalapi/personally_procured_move_incentive.go
  pkg/handlers/internalapi/personally_procured_move_sit_estimate.go
  pkg/models/estimate_helper.go
  pkg/models/shipment_summary_worksheet.go
  pkg/models/shipment_summary_worksheet_test.go
  pkg/paperwork/shipment_summary_worksheet.go
  pkg/rateengine/rateengine.go
  pkg/rateengine/rateengine_test.go
Labels: roci

#1712 Move orders to entities reducers
  src/scenes/Office/AccountingPanel.jsx
  src/scenes/Office/DocumentViewer/index.jsx
  src/scenes/Office/Hhg/LocationsContainer.js
  src/scenes/Office/MoveInfo.jsx
  src/scenes/Office/OrdersInfo.jsx
  src/scenes/Office/OrdersPanel.jsx
  src/scenes/Office/OrdersViewerPanel.js
  src/scenes/Office/Ppm/PPMEstimatesPanel.jsx
  src/scenes/Office/ducks.js
  src/shared/Entities/modules/orders.js
  src/shared/Entities/schema.js
  src/shared/User/ducks.js
Labels: roci

#1637 Add shipment validation for workdays and remove GET validation
  cypress/integration/mymove/hhgPPM.js
  cypress/integration/office/officeCSRFProtect.js
  cypress/integration/tsp/premoveSurvey.js
  cypress/integration/tsp/shipShipment.js
  cypress/support/datesPanel.js
  cypress/support/testPremoveSurvey.js
  pkg/awardqueue/awardqueue_test.go
  pkg/dates/calculators.go
  pkg/dates/calendar.go
  pkg/dates/calendar_test.go
  pkg/handlers/publicapi/shipments_test.go
  pkg/models/blackout_dates_test.go
  pkg/models/gov_bill_of_lading_test.go
  pkg/models/move_test.go
  pkg/models/shipment.go
  pkg/models/shipment_offer_test.go
  pkg/models/shipment_test.go
  pkg/models/validators.go
  pkg/models/validators_test.go
  pkg/testdatagen/make_shipment_offer_records.go
  src/scenes/Office/MoveInfo.jsx
  src/scenes/Office/PremoveSurvey.jsx
  src/shared/EditablePanel/index.jsx
  src/shared/Entities/modules/shipments.js
  src/shared/ShipmentDates/index.jsx
  src/shared/ShipmentDates/index.test.js
  src/shared/utils.js
Labels: wip

#1725 Allow service member to continue move after logging out
  src/scenes/MyMove/getWorkflowRoutes.jsx
Labels: roci

#1722 Move invoicing to entities (plus some additional cleanup)
  src/scenes/Office/BackupInfoPanel.jsx
  src/scenes/Office/MoveInfo.jsx
  src/scenes/Office/OrdersPanel.jsx
  src/scenes/Office/OrdersViewerPanel.js
  src/scenes/Office/Ppm/PaymentsPanel.jsx
  src/scenes/Office/api.js
  src/scenes/Office/ducks.js
  src/shared/Entities/modules/invoices.js
  src/shared/Entities/modules/ppms.js
  src/shared/Invoice/InvoicePanel.jsx
Labels: roci

#1720 Add weight units to 4 line haul items: 163331822
  src/shared/Invoice/LineItemTable.jsx
  src/shared/formatters.js
  src/shared/formatters.test.js
  src/shared/lineItems.js
  src/shared/lineItems.test.js
Labels: ttv

#1718 Add validation to 105B and 105E pre approval requests so item and crate dimension are required
  src/shared/JsonSchemaForm/DimensionsField.jsx
  src/shared/JsonSchemaForm/DimensionsField.test.js
  src/shared/PreApprovalRequest/Code105Details.jsx
  src/shared/PreApprovalRequest/Code105Details.test.js
Labels: ttv

#1730 Port moves to entities
  src/scenes/Landing/MoveSummary.jsx
  src/scenes/Moves/Ppm/ducks.js
  src/scenes/Office/AccountingPanel.jsx
  src/scenes/Office/DocumentViewer/DocumentDetailPanel.jsx
  src/scenes/Office/DocumentViewer/index.jsx
  src/scenes/Office/Hhg/RoutingPanel.jsx
  src/scenes/Office/MoveInfo.jsx
  src/scenes/Office/MoveInfo.test.js
  src/scenes/Office/OrdersPanel.jsx
  src/scenes/Office/OrdersViewerPanel.js
  src/scenes/Office/Ppm/PPMEstimatesPanel.jsx
  src/scenes/Office/Ppm/PaymentsPanel.jsx
  src/scenes/Office/QueueTable.jsx
  src/scenes/Office/api.js
  src/scenes/Office/ducks.js
  src/scenes/Review/PPMShipmentSummary.jsx
  src/scenes/Review/Summary.jsx
  src/shared/Entities/modules/moves.js
  src/shared/Entities/modules/ppms.js
  src/shared/Entities/modules/shipments.js
  src/shared/Entities/reducer.js
  src/shared/Entities/schema.js
Labels: roci

#1726 Created jsconfig file for react project used in VS Code
  src/jsconfig.json
Labels: ttv, vs-code

#1734 Support Editing Pre-Approval Robust Accessorial 105B/E #162846573
  pkg/handlers/publicapi/shipment_line_items.go
  pkg/models/shipment.go
  pkg/models/shipment_test.go
  pkg/testdatagen/make_shipment_line_item_dimensions.go
  pkg/testdatagen/shared.go
  src/shared/PreApprovalRequest/Editor.jsx
Labels: ttv

#1749 Office app breaks when no advance
  cypress/integration/office/officeUserPPM.js
  pkg/testdatagen/make_ppm.go
  pkg/testdatagen/scenario/e2ebasic.go
  src/scenes/Office/MoveInfo.jsx
Labels: roci

#1766 Sb get rid of office ducks
  pkg/handlers/internalapi/moves.go
  src/appReducer.js
  src/scenes/Office/AccountingPanel.jsx
  src/scenes/Office/BackupInfoPanel.jsx
  src/scenes/Office/DocumentViewer/DocumentDetailPanel.jsx
  src/scenes/Office/DocumentViewer/DocumentUploader.jsx
  src/scenes/Office/DocumentViewer/index.jsx
  src/scenes/Office/Hhg/RoutingPanel.jsx
  src/scenes/Office/MoveInfo.jsx
  src/scenes/Office/OrdersInfo.jsx
  src/scenes/Office/OrdersPanel.jsx
  src/scenes/Office/OrdersViewerPanel.js
  src/scenes/Office/QueueTable.jsx
  src/scenes/Office/ducks.js
  src/shared/Entities/modules/moves.js
  src/shared/Entities/modules/orders.js
  src/shared/Entities/modules/serviceMembers.js
  swagger/internal.yaml
Labels: roci

#1769 Use code of service from TDL instead of Shipment
  pkg/handlers/internalapi/shipments.go
  pkg/handlers/internalapi/shipments_test.go
  src/scenes/Office/Hhg/RoutingPanel.jsx
  swagger/internal.yaml
Labels: roci

#1744 Office PPM Weights panel
  cypress/integration/office/officeUserPPM.js
  migrations/20190212181259_add_net_weight_column.up.fizz
  pkg/handlers/internalapi/personally_procured_move.go
  pkg/models/personally_procured_move.go
  src/scenes/Office/MoveInfo.jsx
  src/scenes/Office/Ppm/NetWeightPanel.jsx
  src/shared/EditablePanel/index.css
  swagger/internal.yaml
Labels: roci

#1741 Generate GBL notification only shows once
  cypress/integration/tsp/generateGBL.js
  src/scenes/TransportationServiceProvider/ShipmentInfo.jsx
  src/shared/Swagger/request.js
  src/shared/Swagger/requestsReducer.js
Labels: roci

#1773 Sb standardize request pattern
  src/scenes/Moves/Hhg/DatePicker.jsx
  src/scenes/Moves/Hhg/Locations.jsx
  src/scenes/Moves/Hhg/MoveDate.jsx
  src/scenes/Moves/Hhg/Progear.jsx
  src/scenes/Moves/Hhg/WeightEstimate.jsx
  src/scenes/Office/MoveInfo.jsx
  src/scenes/Office/PremoveSurvey.jsx
  src/scenes/Review/EditShipment.jsx
  src/scenes/TransportationServiceProvider/ContactInfo.jsx
  src/scenes/TransportationServiceProvider/DocumentViewerContainer.jsx
  src/scenes/TransportationServiceProvider/NewDocumentContainer.jsx
  src/scenes/TransportationServiceProvider/ShipmentInfo.jsx
  src/shared/Entities/modules/invoices.js
  src/shared/Entities/modules/moves.js
  src/shared/Entities/modules/orders.js
  src/shared/Entities/modules/ppms.js
  src/shared/Entities/modules/serviceAgents.js
  src/shared/Entities/modules/serviceMembers.js
  src/shared/Entities/modules/shipmentDocuments.js
  src/shared/Entities/modules/shipmentLineItems.js
  src/shared/Entities/modules/shipments.js
  src/shared/Entities/modules/tariff400ngItems.js
  src/shared/Entities/modules/transportationServiceProviders.js
  src/shared/Entities/modules/uploads.js
  src/shared/Invoice/InvoicePanel.jsx
  src/shared/PreApprovalRequest/PreApprovalPanel.jsx
  src/shared/User/ducks.js
Labels: roci

#1780 Update call to match new request pattern.
  src/scenes/Review/Summary.jsx
Labels: roci

#1771 Refactor upload filetype validations [delivers #162522106]
  pkg/handlers/internalapi/personally_procured_move_attachments.go
  pkg/handlers/internalapi/personally_procured_move_attachments_test.go
  pkg/handlers/internalapi/uploads.go
  pkg/handlers/publicapi/shipments.go
  pkg/models/upload.go
  pkg/models/upload_test.go
  pkg/models/validators.go
  pkg/models/validators_test.go
  pkg/paperwork/generator_test.go
  pkg/services/invoice/store_invoice.go
  pkg/services/invoice/update_invoice_upload_test.go
  pkg/testdatagen/make_upload.go
  pkg/testdatagen/scenario/e2ebasic.go
  pkg/testingsuite/base_test_suite.go
  pkg/uploader/allowed_file_types.go
  pkg/uploader/allowed_file_types_test.go
  pkg/uploader/uploader.go
  pkg/uploader/uploader_test.go
  src/shared/Uploader/index.jsx
Labels: 🦇team

#1748 Fix bug for alert showing on successful backup info change
  src/scenes/Office/CustomerInfoPanel.jsx
Labels: roci

#1783 Add service member info to shipment summary worksheet
  pkg/models/shipment_summary_worksheet.go
  pkg/models/shipment_summary_worksheet_test.go
  pkg/paperwork/shipment_summary_worksheet.go
Labels: roci

#1785 Fix a bug if a pre-approval is not approved
  src/shared/Entities/schema.js
Labels: ttv

#1788 Add notes to details column for PARs 105be: 162820562
  src/shared/PreApprovalRequest/Code105Details.jsx
Labels: ttv

#1787 remove unused column and use actual dates in calculators if we have them
  migrations/20190225165937_remove_planned_move_date.up.fizz
  src/scenes/Office/Ppm/IncentiveCalculator.jsx
  src/scenes/Office/Ppm/StorageReimbursementCalculator.jsx
Labels: roci

#1758 When deleting a shipment line item, also deletes associated dimensions items
  pkg/handlers/publicapi/shipment_line_items_test.go
  pkg/models/shipment_line_item.go
Labels: ttv

#1792 Reset requests on unmount in the office app
  src/scenes/Office/MoveInfo.jsx
Labels: roci

#1778 Populate actual obligations on SSW
  cmd/generate_shipment_summary/main.go
  pkg/handlers/internalapi/moves.go
  pkg/handlers/internalapi/moves_test.go
  pkg/models/shipment_summary_worksheet.go
  pkg/models/shipment_summary_worksheet_test.go
  pkg/paperwork/shipment_summary.go
  pkg/paperwork/shipment_summary_test.go
  pkg/paperwork/shipment_summary_worksheet.go
Labels: roci

#1765 Updates app to allow office user to set origin and destination zip.
  cypress/integration/office/officeUserPPM.js
  src/scenes/Office/Ppm/DatesAndLocationsPanel.jsx
  src/shared/EditablePanel/index.jsx
Labels: roci

#1774 Remove cookie decoding
  cypress/integration/mymove/hhgPPM.js
  cypress/integration/mymove/orders.js
  cypress/integration/mymove/shipment.js
  cypress/support/createOrders.js
  pkg/handlers/internalapi/users.go
  pkg/testdatagen/scenario/e2ebasic.go
  src/appReducer.js
  src/scenes/Landing/index.jsx
  src/scenes/Legalese/SubmitPpm.jsx
  src/scenes/Legalese/index.jsx
  src/scenes/Moves/Ppm/ducks.js
  src/scenes/Moves/ducks.js
  src/scenes/MyMove/index.jsx
  src/scenes/Office/index.jsx
  src/scenes/Orders/ducks.js
  src/scenes/ServiceMembers/ContactInfo.jsx
  src/scenes/ServiceMembers/ducks.js
  src/scenes/TransportationServiceProvider/ContactInfo.jsx
  src/scenes/TransportationServiceProvider/index.jsx
  src/shared/Data/users.js
  src/shared/UI/ducks.js
  src/shared/User/LoginButton.jsx
  src/shared/User/LogoutOnInactivity.jsx
  src/shared/User/PrivateRoute.jsx
  src/shared/User/UserGreeting.jsx
  swagger/internal.yaml
Labels: roci

#1789 Puts 105b robust accessorial under e2e test to ensure both robust and original versions of 105b are functional
  cypress/integration/office/preApprovalRequest.js
  cypress/integration/tsp/preApprovalRequest.js
  cypress/support/commands.js
  cypress/support/preapprovals/test105be.js
  cypress/support/preapprovals/testCreateRequest.js
  src/shared/PreApprovalRequest/Code105Details.jsx
  src/shared/PreApprovalRequest/DefaultDetails.jsx
Labels: ttv

#1796 Format SSW Download Name
  pkg/handlers/internalapi/moves.go
  swagger/internal.yaml
Labels: roci
