Repository transcom/mymove, pull requests merged in 2019-03, with the labels that each got.

#1807 Add NetWeight for ppms on shipment summary worksheet
  pkg/models/shipment_summary_worksheet.go
  pkg/models/shipment_summary_worksheet_test.go
Labels: roci

#1791 Create Form for Robust Accessorial Item Code 35A #163880118
  src/shared/JsonSchemaForm/JsonSchemaField.js
  src/shared/JsonSchemaForm/index.css
  src/shared/PreApprovalRequest/Code105Form.jsx
  src/shared/PreApprovalRequest/Code35Form.jsx
  src/shared/PreApprovalRequest/Code35Form.test.js
  src/shared/PreApprovalRequest/DetailsHelper.js
  src/shared/PreApprovalRequest/DetailsHelper.test.js
  src/shared/PreApprovalRequest/PreApprovalRequest.css
  swagger/api.yaml
Labels: ttv

#1800 Add Approve Combo button
  src/scenes/Office/MoveInfo.jsx
  src/scenes/Office/Ppm/PaymentsPanel.jsx
  src/scenes/Office/office.css
  src/scenes/StyleGuide/index.js
  src/shared/ComboButton/index.css
  src/shared/ComboButton/index.jsx
  src/shared/ComboButton/index.test.js
  src/shared/featureFlags.js
  src/shared/shared.css
Labels: roci

#1798 Office saves ppm storage
  cypress/integration/office/officeUserPPM.js
  cypress/support/storagePanel.js
  migrations/20190221204334_add_total_sit_cost_to_ppm.up.fizz
  pkg/handlers/converters.go
  pkg/handlers/internalapi/personally_procured_move.go
  pkg/handlers/internalapi/personally_procured_move_test.go
  pkg/models/personally_procured_move.go
  pkg/testdatagen/scenario/e2ebasic.go
  src/scenes/Office/MoveInfo.jsx
  src/scenes/Office/Ppm/StoragePanel.js
  swagger/internal.yaml
Labels: roci

#1803 Use an added common function vs a local function in hhgPPM test
  cypress/integration/mymove/hhgPPM.js
Labels: ttv

#1810 Update pre approval tests (refactor)
  cypress/integration/office/preApprovalRequest.js
  cypress/integration/tsp/preApprovalRequest.js
  cypress/support/preapprovals/testCreateRequest.js
  src/shared/PreApprovalRequest/Code105Details.jsx
  src/shared/PreApprovalRequest/DefaultDetails.jsx
  src/shared/PreApprovalRequest/PreApprovalRequest.jsx
Labels: ttv

#1793 Kma 163213435 write import fuel function
  .envrc
  Makefile
  cmd/save_fuel_price_data/main.go
  cmd/webserver/main.go
  cmd/webserver/main_test.go
  config/app-client-tls.container-definition.json
  config/app.container-definition.json
  config/env/experimental.env
  pkg/models/fuel_eia_diesel_price.go
  pkg/models/fuel_eia_diesel_price_test.go
  pkg/services/fuelprice/diesel_fuel_price_storer.go
  pkg/services/fuelprice/diesel_fuel_price_storer_test.go
  pkg/unit/cents.go
Labels: A-Team

#1827 Remove 105B and 105E from behind the flag flag: 162850111
  cypress/fixtures/preApprovals/requests/create105.js
  cypress/integration/tsp/preApprovalRequest.js
  cypress/support/preapprovals/test105be.js
  src/shared/PreApprovalRequest/DetailsHelper.js
  src/shared/PreApprovalRequest/PreApprovalForm.test.js
Labels: ttv

#1816 Use final destination (if known) to calculate distance: 163605913
  migrations/20190301165102_update_shipment_with_destination_on_acceptance.up.fizz
  pkg/models/shipment.go
  pkg/models/shipment_test.go
  pkg/services/shipment/price_shipment.go
Labels: ttv

#1832 162736964 tsp view pending sit requests
  cypress/support/testCreateStorageInTransit.js
  pkg/models/storage_in_transit.go
  src/shared/StorageInTransit/Creator.jsx
  src/shared/StorageInTransit/StorageInTransit.css
  src/shared/StorageInTransit/StorageInTransitPanel.jsx
  src/shared/StorageInTransit/StorageInTransitPanel.test.jsx
Labels: A-Team

#1829 Support Creating Robust Accessorial 35A Preapproval Request #163403052
  migrations/20190304233837_shipment-line-item-new-columns.up.fizz
  pkg/handlers/publicapi/shipment_line_items.go
  pkg/models/shipment.go
  pkg/models/shipment_line_item.go
  pkg/models/shipment_test.go
  src/shared/PreApprovalRequest/Creator.jsx
  src/shared/utils.js
Labels: ttv

#1820 Add dropdown to Approve Move ComboButton
  src/scenes/Office/MoveInfo.jsx
  src/scenes/Office/Ppm/PaymentsPanel.jsx
  src/scenes/StyleGuide/index.js
  src/shared/ComboButton/index.css
  src/shared/ComboButton/index.jsx
  src/shared/ComboButton/index.test.js
  src/shared/ToolTip/index.css
  src/shared/ToolTip/index.jsx
  src/shared/shared.css
Labels: roci

#1821 Populate Expenses on Shipment Summary Worksheet
  pkg/models/shipment_summary_worksheet.go
  pkg/models/shipment_summary_worksheet_test.go
  pkg/paperwork/shipment_summary_worksheet.go
Labels: roci

#1833 Add weight and distance units to LHS and 16A: 163331256
  src/shared/lineItems.js
  src/shared/lineItems.test.js
Labels: ttv

#1843 Remove incentive and storage calculators from office view
  cypress/integration/office/incentiveCalculator.js
  cypress/integration/office/officeUserPPM.js
  cypress/integration/office/storageReimbursementCalculator.js
  src/scenes/Office/MoveInfo.jsx
  src/scenes/Office/Ppm/IncentiveCalculator.jsx
Labels: roci

#1831 Prepopulate HHG pickup address with SM residential address
  cypress/integration/mymove/shipment.js
  src/scenes/Moves/Hhg/Locations.jsx
Labels: roci

#1855 Shipment Summary Worksheet - Actual Obligations PPM Weight
  pkg/models/shipment_summary_worksheet.go
  pkg/models/shipment_summary_worksheet_test.go
Labels: roci

#1844 pre-commit pass through
  .pre-commit-config.yaml
  bin/pre-commit-go-lint
  bin/pre-commit-go-vet
  docs/README.md
  docs/how-to/run-pre-commit-hooks.md
Labels: infra

#1865 Display debug labels beneath field cells to improve legibility
  pkg/paperwork/forms.go
Labels: roci

#1862 Pre-Approval Request Panel Style Clean Up [delivers #164389307]
  src/App/index.css
  src/shared/BasicPanel/index.css
  src/shared/PreApprovalRequest/Code105Form.jsx
  src/shared/PreApprovalRequest/Creator.jsx
  src/shared/PreApprovalRequest/Editor.jsx
  src/shared/PreApprovalRequest/PreApprovalForm.jsx
  src/shared/PreApprovalRequest/PreApprovalRequest.css
  src/shared/PreApprovalRequest/PreApprovalRequest.jsx
  src/shared/StorageInTransit/Creator.jsx
  src/shared/StorageInTransit/StorageInTransit.css
Labels: ttv

#1856 ComboButton Approve Basics active when Basic move information is available
  src/scenes/Office/MoveInfo.jsx
  src/scenes/StyleGuide/index.js
  src/shared/ComboButton/dropdown.css
  src/shared/ComboButton/dropdown.jsx
  src/shared/ComboButton/index.css
  src/shared/ComboButton/index.jsx
  src/shared/ComboButton/index.test.js
  src/shared/ToolTip/index.jsx
  src/shared/ToolTip/index.test.js
Labels: roci

#1860 Show warning for 35A if actual is more than estimated amount: 163487135
  src/shared/PreApprovalRequest/Code35Form.jsx
  src/shared/PreApprovalRequest/Code35FormAlert.jsx
  src/shared/PreApprovalRequest/Code35FormAlert.test.js
  src/shared/PreApprovalRequest/PreApprovalForm.jsx
  src/shared/PreApprovalRequest/PreApprovalRequest.css
Labels: ttv

#1846 View Code 35A details in Preapproval Table
  cypress/fixtures/preApprovals/requests/createRobustAccessorial.js
  cypress/integration/tsp/preApprovalRequest.js
  cypress/support/preapprovals/test105be.js
  cypress/support/preapprovals/test35a.js
  cypress/support/preapprovals/testRobustAccessorials.js
  src/shared/PreApprovalRequest/Code35Details.jsx
  src/shared/PreApprovalRequest/DetailsHelper.js
  src/shared/PreApprovalRequest/PreApprovalTable.test.js
  src/shared/preApprovals.js
Labels: ttv

#1878 ComboButton Add Approve Basics
  .eslintrc
  src/scenes/Office/MoveInfo.jsx
  src/scenes/Office/Ppm/PaymentsPanel.jsx
  src/scenes/StyleGuide/index.js
  src/shared/ComboButton/dropdown.css
  src/shared/ComboButton/dropdown.jsx
  src/shared/ComboButton/dropdown.test.js
  src/shared/Invoice/InvoicePanel.test.jsx
  src/shared/JsonSchemaForm/DimensionsField.test.js
  src/shared/PreApprovalRequest/PreApprovalForm.test.js
  src/shared/PreApprovalRequest/PreApprovalPanel.jsx
  src/shared/StorageInTransit/StorageInTransitForm.jsx
  src/shared/StorageInTransit/StorageInTransitPanel.jsx
Labels: roci

#1864 Add Actual SIT to SSW
  cmd/generate_shipment_summary/main.go
  pkg/handlers/internalapi/moves.go
  pkg/models/shipment_summary_worksheet.go
  pkg/models/shipment_summary_worksheet_test.go
  pkg/paperwork/shipment_summary.go
  pkg/paperwork/shipment_summary_test.go
  pkg/paperwork/shipment_summary_worksheet.go
Labels: roci

#1884 [DNR UNTIL #1880 MERGED] ComboButton Add Approve PPM
  src/scenes/Office/MoveInfo.jsx
Labels: roci

#1872 Get list of local users details in single query
  pkg/auth/authentication/devlocal.go
  pkg/models/user.go
  pkg/models/user_test.go
Labels: ttv

#1869 Use remaining Entitlement for Shipment Summary worksheet Actual Obligations
  pkg/models/shipment_summary_worksheet.go
  pkg/models/shipment_summary_worksheet_test.go
  pkg/paperwork/shipment_summary.go
  pkg/paperwork/shipment_summary_test.go
  pkg/paperwork/shipment_summary_worksheet.go
Labels: roci

#1888 Service member sees way to accept payment legalese
  cypress/integration/mymove/ppm.js
  pkg/testdatagen/scenario/e2ebasic.go
  src/scenes/Moves/Ppm/PaymentRequest.css
  src/scenes/Moves/Ppm/PaymentRequest.jsx
Labels: roci

#1875 Sets base quantity if ActualAmountCents is set in 35A PAR.
  pkg/models/shipment.go
  pkg/models/shipment_test.go
  pkg/unit/base_quantity.go
Labels: ttv

#1877 Storage Panel Updates
  cypress/support/storagePanel.js
  src/scenes/Office/Ppm/StoragePanel.js
  swagger/internal.yaml
Labels: roci

#1854 Jm 163338386 office sit storage transit v2
  cypress/integration/office/officeUserPPM.js
  src/scenes/Office/MoveInfo.jsx
  src/shared/Entities/modules/moves.js
  src/shared/Entities/modules/serviceMembers.js
  src/shared/StorageInTransit/StorageInTransitPanel.jsx
  src/shared/StorageInTransit/StorageInTransitPanel.test.jsx
Labels: A-Team

#1880 ComboButton Add Approve HHG
  src/scenes/Office/MoveInfo.jsx
Labels: roci

#1890 On Edit Move page only show details relevant to move type
  cypress/integration/mymove/ppm.js
  src/scenes/Review/Summary.jsx
Labels: roci

#1892 Office View Details for Robust Accessorial 35A [delivers #163403049]
  cypress/support/preapprovals/test35a.js
  src/shared/PreApprovalRequest/Code35Details.jsx
Labels: ttv

#1882 Fix address used for linehaul calculations
  pkg/models/shipment.go
  pkg/models/shipment_test.go
Labels: ttv

#1897 Disable cancel button if hhg is picked up
  cypress/integration/office/officeUserHHG.js
  src/scenes/Office/MoveInfo.jsx
Labels: roci

#1795 SSW Destination Layout bug
  pkg/handlers/internalapi/moves.go
  pkg/models/shipment_summary_worksheet.go
  pkg/models/shipment_summary_worksheet_test.go
  pkg/paperwork/forms.go
  pkg/paperwork/forms_test.go
  pkg/paperwork/shipment_summary_worksheet.go
Labels: roci

#1893 Actual Amount remains editable after 35A PAR has been approved. [delivers #163439684]
  pkg/handlers/publicapi/shipment_line_items.go
  pkg/handlers/publicapi/shipment_line_items_test.go
  pkg/models/shipment.go
  pkg/models/shipment_test.go
  src/shared/PreApprovalRequest/Code35Form.jsx
  src/shared/PreApprovalRequest/PreApprovalForm.jsx
  src/shared/PreApprovalRequest/PreApprovalForm.test.js
  src/shared/PreApprovalRequest/PreApprovalRequest.css
  src/shared/PreApprovalRequest/PreApprovalRequest.jsx
  src/shared/PreApprovalRequest/PreApprovalRequest.test.js
  swagger/api.yaml
Labels: ttv

#1899 Combo button all are approved
  src/scenes/Office/MoveInfo.jsx
  src/shared/ComboButton/index.css
  src/shared/ComboButton/index.jsx
  src/shared/ComboButton/index.test.js
Labels: roci

#1912 Upgrade go to 1.12.1
  .circleci/config.yml
Labels: 🦇team

#1908 postgres - add indexes to foreign keys
  migrations/20190306205302_add-indexes-for-foreign-keys.up.fizz
Labels: ttv

#1909 Service Member confirms responsibilities for payment request submission
  cypress/integration/mymove/ppm.js
  migrations/20190321165456_add-signed-certification-ppm-hhg-ids.up.sql
  pkg/handlers/internalapi/signed_certifications.go
  pkg/models/move.go
  pkg/models/signed_certification.go
  src/scenes/Legalese/CustomerAgreement.jsx
  src/scenes/Legalese/CustomerAgreement.test.js
  src/scenes/Legalese/legaleseText.js
  src/scenes/Moves/Ppm/PaymentRequest.jsx
  src/scenes/Moves/Ppm/PaymentRequest.test.js
  src/shared/Entities/modules/signed_certifications.js
  src/shared/Entities/schema.js
  swagger/internal.yaml
Labels: roci

#1922 Fixes nil issue that causes Service Member UI to fail at times
  pkg/handlers/internalapi/signed_certifications.go
  pkg/models/move.go
  pkg/models/signed_certification.go
  pkg/models/validators.go
  pkg/models/validators_test.go
  swagger/internal.yaml
Labels: 🦇team

#1918 Upgrade dep version
  .circleci/config.yml
  .gitignore
  bin/check_dep_version
Labels: 🦇team

#1907 a user can edit a 226A item: 163829455
  pkg/models/robust_accessorial_line_item_test.go
  pkg/models/shipment_test.go
Labels: ttv

#1916 Add form to office to approve sit request
  cypress/integration/office/storageInTransitPanel.js
  src/shared/StorageInTransit/ApproveSitRequest.jsx
  src/shared/StorageInTransit/StorageInTransit.css
  src/shared/StorageInTransit/StorageInTransit.jsx
  src/shared/StorageInTransit/StorageInTransitOfficeApprovalForm.jsx
  src/shared/StorageInTransit/StorageInTransitOfficeApprovalForm.test.jsx
Labels: A-Team

#1900 Refactor Robust Accessorial work into new file in models package.
  pkg/models/robust_accessorial_line_item.go
  pkg/models/shipment.go
Labels: ttv

#1910 Add Code 226A PAR table details.
  cypress/fixtures/preApprovals/requests/createRobustAccessorial.js
  cypress/integration/tsp/preApprovalRequest.js
  cypress/support/preapprovals/test226a.js
  src/shared/PreApprovalRequest/Code226Details.jsx
  src/shared/PreApprovalRequest/DetailsHelper.js
  src/shared/PreApprovalRequest/DetailsHelper.test.js
  src/shared/PreApprovalRequest/PreApprovalRequest.jsx
  src/shared/lineItems.js
  src/shared/preApprovals.js
  src/shared/preApprovals.test.js
Labels: ttv

#1898 Pre-approval 35A must have an actualAmount to be invoiced: 163439671
  pkg/services/invoice/fetch_invoice_for_shipment.go
  pkg/services/invoice/fetch_invoice_for_shipment_test.go
  src/shared/Entities/modules/shipmentLineItems.js
  src/shared/Entities/modules/shipmentLineItems.test.js
  src/shared/Invoice/LineItemTable.jsx
  src/shared/shared.css
Labels: ttv

#1936 Remove pagination controls from office queue index
  src/scenes/Office/QueueTable.jsx
  src/scenes/Office/office.css
Labels: ttv
