Repository transcom/mymove, pull requests merged in 2019-10, with the labels that each got.

#2738 Fix milmove/gen_disable_user_migration script and disable Liz
  cmd/milmove/gen_disable_user_migration.go
  local_migrations/20190925190920_disable_liz.up.sql
  migrations_manifest.txt
Labels: ttv

#2755 Add log line for updating office users and remove feature flag
  pkg/handlers/adminapi/office_users.go
  src/scenes/SystemAdmin/Home.jsx
  src/shared/featureFlags.js
Labels: ttv

#2718 Fix old payment request transition
  cypress/integration/mymove/ppmCloseout.js
  pkg/models/move_document.go
  pkg/testdatagen/scenario/e2ebasic.go
  src/scenes/Moves/Ppm/PaymentReview/DocumentsUploaded.js
  src/scenes/Moves/Ppm/PaymentReview/DocumentsUploaded.test.js
  src/scenes/Moves/Ppm/PaymentReview/WeightTicketListItem.jsx
Labels: roci

#2763 Automated dependency updates pre-commit | Mon, 30 Sep 2019 12:00:30 +…
  .pre-commit-config.yaml
Labels: dependencies, roci

#2758 Fix a typo, add link to chamber documentation
  README.md
Labels: A-Team

#2761 Create TOO placeholder route
  src/scenes/Office/TOO/too.jsx
  src/scenes/Office/TOO/too.test.js
  src/scenes/Office/index.jsx
  src/shared/featureFlags.js
Labels: roci

#2754 Enable test result collection for go tests in CircleCI
  .circleci/config.yml
  Makefile
  go.mod
  go.sum
  pkg/tools/tools.go
Labels: A-Team

#2760 Add duty station search improvements: 167501188
  cypress/support/commands.js
  migrations/20190924175530_add_trigram_matching_extension.up.sql
  migrations/20190926142600_add_duty_station_names.up.fizz
  migrations/20190927150748_insert_duty_station_names.up.sql
  migrations_manifest.txt
  pkg/handlers/internalapi/duty_stations.go
  pkg/handlers/internalapi/duty_stations_test.go
  pkg/handlers/internalapi/transportation_offices.go
  pkg/models/duty_station.go
  pkg/models/duty_station_names.go
  pkg/models/duty_station_test.go
  src/scenes/ServiceMembers/DutyStationSearchBox.jsx
Labels: ttv

#2779 Automated dependency updates js | Mon, 07 Oct 2019 12:02:10 +0000
  yarn.lock
Labels: dependencies, roci

#2784 Add endpoint to get ALL moves including suppressed: 169015597
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalapi/internaloperations/queues/show_queue_parameters.go
  pkg/models/queue.go
  swagger/internal.yaml
Labels: ttv

#2791 Update access codes cmd to use cli package for db connection
  cmd/generate_access_codes/logger.go
  cmd/generate_access_codes/main.go
Labels: roci

#2790 Setup ghc api
  .envrc
  .gitignore
  Makefile
  cmd/milmove/serve.go
  config/app.container-definition.json
  config/env/experimental.env
  config/env/prod.env
  config/env/staging.env
  docker-compose.local.yml
  docker-compose.yml
  pkg/cli/services.go
  pkg/cli/swagger.go
  pkg/gen/ghcapi/doc.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/move_task_order/delete_move_task_order_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/move_task_order/get_move_task_order_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/move_task_order/list_move_task_orders_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/move_task_order/update_move_task_order_status_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/move_task_order/update_move_task_order_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/payment_requests/create_payment_request_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/payment_requests/get_payment_request_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/payment_requests/list_payment_requests_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/payment_requests/update_payment_request_status_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/payment_requests/update_payment_request_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/service_item/create_service_item_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/service_item/delete_service_item_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/service_item/get_service_item_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/service_item/list_service_items_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/service_item/update_service_item_status_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/service_item/update_service_item_urlbuilder.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/api_test.go
  public/swagger-ui/ghc.html
  src/setupProxy.js
  src/shared/Swagger/api.js
  swagger/ghc.yaml
Labels: roci

#2771 Jm parse ratengine domestic linehaul data ghc xlsx part 1
  cmd/parse_ratengine_data_ghc/main.go
  cmd/parse_ratengine_data_ghc/shared.go
Labels: A-Team

#2786 Rate engine reference tables
  migrations/20191008151614_re_create_reference_tables.up.sql
  migrations_manifest.txt
  pkg/models/models_test.go
  pkg/models/re_contract.go
  pkg/models/re_contract_test.go
  pkg/models/re_contract_year.go
  pkg/models/re_contract_year_test.go
  pkg/models/re_domestic_service_area.go
  pkg/models/re_domestic_service_area_test.go
  pkg/models/re_rate_area.go
  pkg/models/re_rate_area_test.go
  pkg/models/re_service.go
  pkg/models/re_service_test.go
  pkg/models/re_shipment_type.go
  pkg/models/re_shipment_type_test.go
  pkg/models/re_zip3s.go
  pkg/models/re_zip3s_test.go
  pkg/models/validators.go
  pkg/models/validators_test.go
Labels: A-Team

#2799 fix signature alignment when field has error: 168581468
  src/scenes/Legalese/index.css
Labels: ttv

#2796 Add ability to edit disabled field on office users
  cmd/milmove/gen_disable_user_migration.go
  docs/how-to/create-or-disable-users.md
  pkg/gen/adminapi/embedded_spec.go
  pkg/gen/adminmessages/office_user_update_payload.go
  pkg/handlers/adminapi/office_users.go
  pkg/services/office_user/office_user_updater.go
  src/scenes/SystemAdmin/Home.module.scss
  src/scenes/SystemAdmin/OfficeUsers/OfficeUserEdit.jsx
  swagger/admin.yaml
Labels: ttv

#2804 Update file size comparison in upload-secure-migration to use integer comparison operator
  scripts/upload-secure-migration
Labels: roci

#2802 Add tables and models for rate engine domestic pricing
  migrations/20191011191842_re_create_domestic_tables.up.sql
  migrations_manifest.txt
  pkg/models/re_domestic_linehaul_price.go
  pkg/models/re_domestic_linehaul_price_test.go
  pkg/models/re_domestic_other_price.go
  pkg/models/re_domestic_other_price_test.go
  pkg/models/re_domestic_service_area_price.go
  pkg/models/re_domestic_service_area_price_test.go
Labels: A-Team

#2803 Add New Admin Users
  local_migrations/20191011162818_add-admin-users.up.sql
  migrations_manifest.txt
Labels: roci

#2807 Update circle-ci-primary docker image
  .circleci/config.yml
  Dockerfile.dep_updater
Labels: roci

#2794 Auto create PRs for dependency updates
  scripts/circleci-push-dependency-updates
Labels: roci

#2787 Add code splitting to TOO route
  cypress/integration/office/too.js
  src/scenes/Office/TOO/too.test.js
  src/scenes/Office/index.jsx
Labels: roci

#2797 Ttv #168871974 admin tspp
  pkg/gen/adminapi/adminoperations/mymove_api.go
  pkg/gen/adminapi/adminoperations/transportation_service_provider_performances/index_t_s_p_ps.go
  pkg/gen/adminapi/adminoperations/transportation_service_provider_performances/index_t_s_p_ps_parameters.go
  pkg/gen/adminapi/adminoperations/transportation_service_provider_performances/index_t_s_p_ps_responses.go
  pkg/gen/adminapi/adminoperations/transportation_service_provider_performances/index_t_s_p_ps_urlbuilder.go
  pkg/gen/adminapi/configure_mymove.go
  pkg/gen/adminapi/embedded_spec.go
  pkg/gen/adminmessages/transportation_service_provider_performance.go
  pkg/gen/adminmessages/transportation_service_provider_performances.go
  pkg/handlers/adminapi/api.go
  pkg/handlers/adminapi/transportation_service_provider_performances.go
  pkg/handlers/adminapi/transportation_service_provider_performances_test.go
  pkg/handlers/converters.go
  pkg/models/transportation_service_provider_performance.go
  pkg/services/mocks/TransportationServiceProviderPerformanceListFetcher.go
  pkg/services/tsp.go
  pkg/services/tsp/transportation_service_provider_performance_list_fetcher.go
  pkg/services/tsp/transportation_service_provider_performance_list_fetcher_test.go
  src/scenes/SystemAdmin/Home.jsx
  src/scenes/SystemAdmin/Home.module.scss
  src/scenes/SystemAdmin/TSPPs/TSPPList.jsx
  swagger/admin.yaml
Labels: ttv

#2801 Add admin user show page endpoint and UI
  pkg/gen/adminapi/adminoperations/admin_users/get_admin_user.go
  pkg/gen/adminapi/adminoperations/admin_users/get_admin_user_parameters.go
  pkg/gen/adminapi/adminoperations/admin_users/get_admin_user_responses.go
  pkg/gen/adminapi/adminoperations/admin_users/get_admin_user_urlbuilder.go
  pkg/gen/adminapi/adminoperations/admin_users/index_admin_users_responses.go
  pkg/gen/adminapi/adminoperations/mymove_api.go
  pkg/gen/adminapi/configure_mymove.go
  pkg/gen/adminapi/embedded_spec.go
  pkg/handlers/adminapi/admin_users.go
  pkg/handlers/adminapi/admin_users_test.go
  pkg/handlers/adminapi/api.go
  pkg/services/admin_user.go
  pkg/services/admin_user/admin_fetcher_test.go
  pkg/services/admin_user/admin_user_fetcher.go
  pkg/services/mocks/AdminUserFetcher.go
  src/scenes/SystemAdmin/AdminUsers/AdminUserShow.jsx
  src/scenes/SystemAdmin/Home.jsx
  swagger/admin.yaml
Labels: ttv

#2798 Add tables for rate engine misc pricing
  migrations/20191010165703_re_create_misc_pricing_tables.up.sql
  migrations_manifest.txt
  pkg/models/re_domestic_accessorial_price.go
  pkg/models/re_domestic_accessorial_price_test.go
  pkg/models/re_domestic_service_area.go
  pkg/models/re_domestic_service_area_test.go
  pkg/models/re_intl_accessorial_price.go
  pkg/models/re_intl_accessorial_price_test.go
  pkg/models/re_shipment_type_price.go
  pkg/models/re_shipment_type_price_test.go
  pkg/models/re_task_order_fee.go
  pkg/models/re_task_order_fee_test.go
Labels: A-Team

#2816 Add mergify.io config to enable automerges
  .circleci/config.yml
  .mergify.yml
Labels: roci

#2792 TOO view customer entitlements
  migrations_manifest.txt
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/entitlements/get_entitlements.go
  pkg/gen/ghcapi/ghcoperations/entitlements/get_entitlements_parameters.go
  pkg/gen/ghcapi/ghcoperations/entitlements/get_entitlements_responses.go
  pkg/gen/ghcapi/ghcoperations/entitlements/get_entitlements_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/ghcmessages/entitlements.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/entitlements.go
  pkg/handlers/ghcapi/entitlements_test.go
  src/scenes/Office/TOO/customerDetails.jsx
  src/scenes/Office/TOO/customerDetails.test.js
  src/scenes/Office/index.jsx
  src/shared/Entities/modules/moveTaskOrders.js
  src/shared/Entities/schema.js
  src/shared/Swagger/request.js
  swagger/ghc.yaml
Labels: roci

#2822 Add "deactivated" column and replace "disabled" in the codebase
  docs/README.md
  docs/how-to/create-or-deactivate-users.md
  internal/pkg/dutystationsloader/duty_stations_loader_test.go
  migrations/20191016153532_replace_disabled.up.sql
  migrations/20191016214136_remove_disabled_column.up.sql
  migrations_manifest.txt
  pkg/auth/authentication/auth.go
  pkg/auth/authentication/auth_test.go
  pkg/auth/authentication/devlocal.go
  pkg/gen/adminapi/embedded_spec.go
  pkg/gen/adminmessages/admin_user.go
  pkg/gen/adminmessages/office_user.go
  pkg/gen/adminmessages/office_user_update_payload.go
  pkg/handlers/adminapi/admin_users.go
  pkg/handlers/adminapi/office_users.go
  pkg/models/admin_user.go
  pkg/models/dps_users.go
  pkg/models/office_user.go
  pkg/models/user.go
  pkg/services/office_user/office_user_updater.go
  pkg/testdatagen/make_admin_user.go
  pkg/testdatagen/make_dps_user.go
  pkg/testdatagen/make_office_user.go
  pkg/testdatagen/make_user.go
  src/scenes/SystemAdmin/AdminUsers/AdminUserList.jsx
  src/scenes/SystemAdmin/AdminUsers/AdminUserShow.jsx
  src/scenes/SystemAdmin/OfficeUsers/OfficeUserEdit.jsx
  src/scenes/SystemAdmin/OfficeUsers/OfficeUserList.jsx
  src/scenes/SystemAdmin/OfficeUsers/OfficeUserShow.jsx
  swagger/admin.yaml
Labels: ttv

#2821 Ttv #168872059 admin tspp show
  pkg/gen/adminapi/adminoperations/mymove_api.go
  pkg/gen/adminapi/adminoperations/transportation_service_provider_performances/get_t_s_p_p.go
  pkg/gen/adminapi/adminoperations/transportation_service_provider_performances/get_t_s_p_p_parameters.go
  pkg/gen/adminapi/adminoperations/transportation_service_provider_performances/get_t_s_p_p_responses.go
  pkg/gen/adminapi/adminoperations/transportation_service_provider_performances/get_t_s_p_p_urlbuilder.go
  pkg/gen/adminapi/configure_mymove.go
  pkg/gen/adminapi/embedded_spec.go
  pkg/handlers/adminapi/api.go
  pkg/handlers/adminapi/transportation_service_provider_performances.go
  pkg/handlers/adminapi/transportation_service_provider_performances_test.go
  src/scenes/SystemAdmin/Home.jsx
  src/scenes/SystemAdmin/TSPPs/TSPPList.jsx
  src/scenes/SystemAdmin/TSPPs/TSPPShow.jsx
  swagger/admin.yaml
Labels: ttv

#2828 Fix TSPP show page can't display 20 decimal points in IE11
  src/scenes/SystemAdmin/TSPPs/TSPPShow.jsx
Labels: bug, ttv

#2829 Add migration to remove disabled column and some docs changes
  docs/how-to/create-or-deactivate-users.md
  migrations/20191016214136_remove_disabled_column.up.sql
  migrations_manifest.txt
Labels: ttv

#2789 revert addition of ppm queue that shows suppressed: 169015597
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalapi/internaloperations/queues/show_queue_parameters.go
  pkg/models/queue.go
  swagger/internal.yaml
Labels: ttv

#2835 Ttv #168412801 convert combo moves to PPM
  migrations/20191018211440_update_combo_moves_to_ppm.up.sql
  migrations_manifest.txt
Labels: mothball, ttv

#2830 Office user alerted of infected file
  pkg/cli/vault.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/tag.go
  pkg/gen/internalmessages/tags.go
  pkg/gen/internalmessages/upload_payload.go
  pkg/handlers/internalapi/documents.go
  pkg/handlers/internalapi/personally_procured_move_attachments.go
  pkg/handlers/internalapi/uploads.go
  pkg/storage/filesystem.go
  pkg/storage/memory.go
  pkg/storage/mocks/FileStorer.go
  pkg/storage/s3.go
  pkg/storage/storage.go
  pkg/storage/test/s3.go
  src/scenes/Office/OrdersInfo.jsx
  src/shared/DocumentViewer/DocumentContent.jsx
  src/shared/DocumentViewer/DocumentContent.test.jsx
  src/shared/DocumentViewer/DocumentUploadViewer.jsx
  src/shared/DocumentViewer/MoveDocumentView.jsx
  src/shared/Entities/modules/uploadTags.js
  swagger/internal.yaml
Labels: roci

#2833 Add user info to upload lookup
  pkg/gen/adminapi/embedded_spec.go
  pkg/gen/adminmessages/upload_information.go
  pkg/handlers/adminapi/api.go
  pkg/handlers/adminapi/upload.go
  pkg/handlers/adminapi/upload_information.go
  pkg/handlers/adminapi/upload_information_test.go
  pkg/services/mocks/UploadFetcher.go
  pkg/services/mocks/UploadInformationFetcher.go
  pkg/services/upload.go
  pkg/services/upload/upload_fetcher.go
  pkg/services/upload/upload_fetcher_test.go
  pkg/services/upload/upload_information_fetcher.go
  pkg/services/upload/upload_information_fetcher_test.go
  pkg/services/upload_information.go
  src/scenes/SystemAdmin/Uploads/UploadShow.jsx
  swagger/admin.yaml
Labels: roci

#2840 Run language specific linters for dependency update
  scripts/circleci-push-dependency-updates
Labels: roci

#2850 Revert changes to circle ci config for dependency updater
  .circleci/config.yml
Labels: roci

#2848 Add additional user fields to uploads screen in admin interface
  pkg/gen/adminapi/embedded_spec.go
  pkg/gen/adminmessages/upload_information.go
  pkg/handlers/adminapi/upload_information.go
  pkg/services/upload/upload_information_fetcher.go
  pkg/services/upload/upload_information_fetcher_test.go
  pkg/services/upload_information.go
  pkg/testdatagen/make_service_member.go
  src/scenes/SystemAdmin/Uploads/UploadShow.jsx
  swagger/admin.yaml
Labels: roci

#2841 improve duty station search performance: 168905571
  pkg/gen/internalapi/configure_mymove.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalapi/internaloperations/addresses/show_address.go
  pkg/gen/internalapi/internaloperations/addresses/show_address_parameters.go
  pkg/gen/internalapi/internaloperations/addresses/show_address_responses.go
  pkg/gen/internalapi/internaloperations/addresses/show_address_urlbuilder.go
  pkg/gen/internalapi/internaloperations/mymove_api.go
  pkg/gen/internalmessages/duty_station_payload.go
  pkg/handlers/internalapi/addresses.go
  pkg/handlers/internalapi/addresses_test.go
  pkg/handlers/internalapi/api.go
  pkg/handlers/internalapi/duty_stations.go
  pkg/handlers/internalapi/duty_stations_test.go
  pkg/models/duty_station.go
  pkg/models/duty_station_test.go
  src/scenes/ServiceMembers/DutyStationSearchBox.jsx
  src/scenes/ServiceMembers/api.js
  swagger/internal.yaml
Labels: ttv

#2843 Show virus scan status
  pkg/assets/assets.go
  src/scenes/Moves/Ppm/PaymentReview/DocumentsUploaded.js
  src/scenes/Moves/Ppm/PaymentReview/ExpenseTicketListItem.jsx
  src/scenes/Moves/Ppm/PaymentReview/PaymentReview.css
  src/scenes/Moves/Ppm/PaymentReview/WeightTicketListItem.jsx
  src/scenes/Moves/Ppm/utility.js
  src/scenes/MyMove/index.jsx
  src/shared/Uploader/InfectedUpload.jsx
  src/shared/Uploader/UploadsTable.jsx
Labels: roci

#2853 Update dependency failure script
  .circleci/config.yml
  scripts/circleci-dependency-update-failure
  scripts/circleci-push-dependency-updates
Labels: roci

#2836 Service-object-based implementation of domestic linehaul pricer
  pkg/ghcrateengine/domestic_pricing.go
  pkg/ghcrateengine/domestic_pricing_test.go
  pkg/ghcrateengine/intl_pricing.go
  pkg/ghcrateengine/other_pricing.go
  pkg/ghcrateengine/rateengine.go
  pkg/services/ghc_rate_engine.go
  pkg/services/ghcrateengine/ghc_rate_engine_service_test.go
  pkg/services/ghcrateengine/logger.go
  pkg/services/ghcrateengine/price_domestic_linehaul.go
  pkg/services/ghcrateengine/price_domestic_linehaul_test.go
  pkg/services/ghcrateengine/shared.go
  pkg/services/ghcrateengine/shared_test.go
  pkg/services/mocks/DomesticLinehaulPricer.go
  pkg/testdatagen/constants.go
  pkg/testdatagen/make_re_contract.go
  pkg/testdatagen/make_re_contract_year.go
  pkg/testdatagen/make_re_domestic_service_area.go
  pkg/testdatagen/shared.go
  pkg/unit/miles.go
  pkg/unit/miles_test.go
  pkg/unit/millicents.go
  pkg/unit/millicents_test.go
  pkg/unit/weights.go
  pkg/unit/weights_test.go
Labels: A-Team

#2621 Add cmdline flag to enable pprof debugging routes
  cmd/milmove/serve.go
  config/app.container-definition.json
  config/env/experimental.env
  config/env/prod.env
  config/env/staging.env
  pkg/cli/debug.go
  pkg/cli/debug_test.go
  src/setupProxy.js
Labels: roci

#2859 Do not require document id is present for upload lookup
  pkg/handlers/adminapi/upload_information.go
  pkg/services/upload/upload_information_fetcher.go
Labels: roci

#2862 Add docs on testing virus scanning.
  .spelling
  docs/README.md
  docs/how-to/test-virus-scanning.md
Labels: roci

#2855 Show in progress message for uploads being scanned
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/tag.go
  pkg/gen/internalmessages/tags.go
  pkg/gen/internalmessages/upload_payload.go
  pkg/handlers/internalapi/documents.go
  pkg/handlers/internalapi/personally_procured_move_attachments.go
  pkg/handlers/internalapi/uploads.go
  src/scenes/Moves/Ppm/PaymentReview/ExpenseTicketListItem.jsx
  src/scenes/Moves/Ppm/PaymentReview/WeightTicketListItem.jsx
  src/scenes/MyMove/index.jsx
  src/scenes/Office/OrdersInfo.jsx
  src/shared/DocumentViewer/DocumentContent.jsx
  src/shared/DocumentViewer/DocumentContent.test.jsx
  src/shared/DocumentViewer/DocumentUploadViewer.jsx
  src/shared/DocumentViewer/MoveDocumentView.jsx
  src/shared/Uploader/ProcessingUpload.jsx
  src/shared/Uploader/UploadsTable.jsx
  src/shared/constants.js
  swagger/internal.yaml
Labels: roci

#2871 Fix responsible_user_id and add names to audit log
  pkg/handlers/adminapi/admin_users.go
  pkg/handlers/adminapi/office_users.go
Labels: ttv

#2873 Regenerate go.mod and go.sum
  cmd/update_deps/main.go
  go.mod
  go.sum
Labels: dependencies, roci

#2875 Added service object for CreateTableFromSlice
  go.mod
  pkg/services/db_tools.go
  pkg/services/dbtools/create_table_from_slice.go
  pkg/services/dbtools/create_table_from_slice_test.go
  pkg/services/dbtools/db_tools_service_test.go
  pkg/services/dbtools/logger.go
  pkg/services/mocks/TableFromSliceCreator.go
Labels: A-Team

#2837 Show All Customer Moves to a TOO
  cypress/integration/office/too.js
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/customer/get_all_customer_moves.go
  pkg/gen/ghcapi/ghcoperations/customer/get_all_customer_moves_parameters.go
  pkg/gen/ghcapi/ghcoperations/customer/get_all_customer_moves_responses.go
  pkg/gen/ghcapi/ghcoperations/customer/get_all_customer_moves_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/customer/get_customer_info_parameters.go
  pkg/gen/ghcapi/ghcoperations/customer/get_customer_info_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/ghcmessages/customer.go
  pkg/gen/ghcmessages/customer_move_item.go
  pkg/gen/ghcmessages/customer_move_items.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/customer.go
  pkg/handlers/ghcapi/customer_test.go
  pkg/models/customer.go
  pkg/models/customer_test.go
  src/scenes/Office/TOO/customerDetails.jsx
  src/scenes/Office/TOO/customerDetails.test.js
  src/scenes/Office/TOO/too.jsx
  src/scenes/Office/index.jsx
  src/shared/Entities/modules/customer.js
  src/shared/Entities/modules/moveTaskOrders.js
  src/shared/Entities/schema.js
  src/shared/Swagger/request.js
  swagger/ghc.yaml
Labels: roci

#2880 Fix lazy loaded customer routes
  src/scenes/Office/index.jsx
Labels: roci

#2872 Add Create MTO to TOO interface
  migrations/20191023200010_create_mto_required_fields_tables.up.sql
  migrations_manifest.txt
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/customer.go
  pkg/gen/ghcmessages/entitlements.go
  pkg/gen/ghcmessages/move_task_order.go
  pkg/gen/ghcmessages/move_task_order_status.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/customer.go
  pkg/handlers/ghcapi/entitlements.go
  pkg/handlers/ghcapi/entitlements_test.go
  pkg/handlers/ghcapi/move_task_order.go
  pkg/handlers/ghcapi/move_task_order_test.go
  pkg/models/customer_test.go
  pkg/models/ghc_entitlement.go
  pkg/models/move_task_order.go
  pkg/models/service_item.go
  pkg/services/mocks/MoveTaskOrderFetcher.go
  pkg/services/mocks/MoveTaskOrderStatusUpdater.go
  pkg/services/move_task_order.go
  pkg/services/move_task_order/move_task_order.go
  pkg/services/move_task_order/move_task_order_service_test.go
  pkg/services/move_task_order/move_task_order_test.go
  pkg/testdatagen/make_ghc_entitlement.go
  pkg/testdatagen/make_move_task_order.go
  pkg/testdatagen/make_service_item.go
  pkg/testdatagen/scenario/e2ebasic.go
  pkg/testdatagen/shared.go
  src/scenes/Office/TOO/customerDetails.jsx
  src/shared/Entities/modules/moveTaskOrders.js
  src/shared/Entities/schema.js
  swagger/ghc.yaml
Labels: roci

#2866 Split GHC Swaggerfile
  .gitignore
  .pre-commit-config.yaml
  Makefile
  pkg/assets/assets.go
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/customer/get_all_customer_moves_responses.go
  pkg/gen/ghcapi/ghcoperations/customer/get_customer_info_responses.go
  pkg/gen/ghcapi/ghcoperations/move_task_order/delete_move_task_order_responses.go
  pkg/gen/ghcapi/ghcoperations/move_task_order/get_move_task_order_responses.go
  pkg/gen/ghcapi/ghcoperations/move_task_order/list_move_task_orders_responses.go
  pkg/gen/ghcapi/ghcoperations/move_task_order/update_move_task_order_responses.go
  pkg/gen/ghcapi/ghcoperations/move_task_order/update_move_task_order_status_responses.go
  pkg/gen/ghcapi/ghcoperations/payment_requests/create_payment_request_responses.go
  pkg/gen/ghcapi/ghcoperations/payment_requests/get_payment_request_responses.go
  pkg/gen/ghcapi/ghcoperations/payment_requests/update_payment_request_responses.go
  pkg/gen/ghcapi/ghcoperations/payment_requests/update_payment_request_status_responses.go
  pkg/gen/ghcapi/ghcoperations/service_item/create_service_item_parameters.go
  pkg/gen/ghcapi/ghcoperations/service_item/create_service_item_responses.go
  pkg/gen/ghcapi/ghcoperations/service_item/delete_service_item_responses.go
  pkg/gen/ghcapi/ghcoperations/service_item/get_service_item_responses.go
  pkg/gen/ghcapi/ghcoperations/service_item/list_service_items.go
  pkg/gen/ghcapi/ghcoperations/service_item/list_service_items_responses.go
  pkg/gen/ghcapi/ghcoperations/service_item/update_service_item_responses.go
  pkg/gen/ghcapi/ghcoperations/service_item/update_service_item_status_responses.go
  pkg/gen/ghcmessages/address.go
  pkg/gen/ghcmessages/create_payment_request_payload.go
  pkg/gen/ghcmessages/customer.go
  pkg/gen/ghcmessages/customer_move_item.go
  pkg/gen/ghcmessages/customer_move_items.go
  pkg/gen/ghcmessages/entitlements.go
  pkg/gen/ghcmessages/error.go
  pkg/gen/ghcmessages/invalid_request.go
  pkg/gen/ghcmessages/move_task_order.go
  pkg/gen/ghcmessages/move_task_order_status.go
  pkg/gen/ghcmessages/move_task_orders.go
  pkg/gen/ghcmessages/not_found.go
  pkg/gen/ghcmessages/payment_request.go
  pkg/gen/ghcmessages/payment_request_status.go
  pkg/gen/ghcmessages/permission_denied.go
  pkg/gen/ghcmessages/proof_of_service_package.go
  pkg/gen/ghcmessages/server_error.go
  pkg/gen/ghcmessages/service_item.go
  pkg/gen/ghcmessages/service_item_status.go
  pkg/gen/ghcmessages/service_items.go
  pkg/gen/ghcmessages/update_payment_request_payload.go
  pkg/gen/ghcmessages/update_payment_request_status_payload.go
  pkg/gen/ghcmessages/upload.go
  scripts/gen-server
  swagger/ghc.yaml
  swagger/ghc_definitions.yaml
  swagger/ghc_paths.yaml
  swagger/ghc_responses.yaml
Labels: roci

#2883 Migration to hide all moves for experimental and staging
  local_migrations/20191028210245_hide_moves_experimental_staging.up.sql
  migrations_manifest.txt
Labels: ttv

#2860 Prime update mto actual weight
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/move_task_order/update_move_task_order_actual_weight.go
  pkg/gen/ghcapi/ghcoperations/move_task_order/update_move_task_order_actual_weight_parameters.go
  pkg/gen/ghcapi/ghcoperations/move_task_order/update_move_task_order_actual_weight_responses.go
  pkg/gen/ghcapi/ghcoperations/move_task_order/update_move_task_order_actual_weight_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/ghcmessages/move_task_order.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/move_task_order.go
  pkg/handlers/ghcapi/prime_move_task_order.go
  pkg/handlers/ghcapi/prime_move_task_order_test.go
  pkg/models/move_task_order.go
  pkg/services/mocks/MoveTaskOrderActualWeightUpdater.go
  pkg/services/move_task_order.go
  pkg/services/move_task_order/move_task_order.go
  pkg/services/move_task_order/move_task_order_test.go
  swagger/ghc.yaml
Labels: roci

#2891 Send SM email payment reminder: 168950704
  .circleci/config.yml
  Dockerfile.tasks_local
  Makefile
  cmd/milmove-tasks/main.go
  cmd/milmove-tasks/send_payment_reminder_email.go
  migrations/20191031182540_add_notification_indexes.up.sql
  migrations_manifest.txt
  pkg/assets/assets.go
  pkg/models/notifications.go
  pkg/notifications/move_payment_reminder.go
  pkg/notifications/move_payment_reminder_test.go
  pkg/notifications/templates/move_payment_reminder_template.html
  pkg/notifications/templates/move_payment_reminder_template.txt
Labels: ttv

#2893 revert deploy payment-reminder
  .circleci/config.yml
Labels: ttv
