Repository transcom/mymove, pull requests merged in 2019-08, with the labels that each got.

#2469 Add endpoint to get a specific office user
  pkg/handlers/adminapi/api.go
  pkg/handlers/adminapi/office_users.go
  pkg/handlers/adminapi/office_users_test.go
  pkg/services/user.go
  swagger/admin.yaml
Labels: ttv

#2476 update error msgs
  pkg/auth/authentication/auth_test.go
Labels: ttv

#2468 Change privacy policy statement
  src/shared/Statements/PrivacyAndPolicyStatement.jsx
Labels: ttv

#2438 Update ppm pricing
  cypress/integration/mymove/hhgPPM.js
  pkg/handlers/internalapi/personally_procured_move.go
  pkg/handlers/internalapi/personally_procured_move_estimate.go
  pkg/handlers/internalapi/personally_procured_move_estimate_test.go
  pkg/handlers/internalapi/personally_procured_move_incentive.go
  pkg/handlers/internalapi/personally_procured_move_incentive_test.go
  pkg/handlers/internalapi/personally_procured_move_test.go
  pkg/models/personally_procured_move.go
  pkg/models/service_member.go
  pkg/paperwork/shipment_summary.go
  pkg/paperwork/shipment_summary_test.go
  pkg/rateengine/rateengine.go
  pkg/rateengine/rateengine_test.go
  src/scenes/Moves/Ppm/DateAndLocation.jsx
  src/scenes/Moves/Ppm/Weight.jsx
  src/scenes/Moves/Ppm/api.js
  src/scenes/Moves/Ppm/ducks.js
  src/scenes/Office/Ppm/api.js
  src/scenes/Review/EditWeight.jsx
  swagger/internal.yaml
Labels: A-Team

#2485 Office user can edit weight ticket set weights (updated branch name)
  cypress/integration/office/documentViewer.js
  pkg/handlers/internalapi/move_documents.go
  pkg/handlers/internalapi/move_documents_test.go
  src/scenes/Office/DocumentViewer/DocumentDetailPanel.jsx
  swagger/internal.yaml
Labels: roci

#2487 Add full to weight ticket date in ppm closeout
  swagger/internal.yaml
Labels: roci

#2491 System admin transportation offices via admin ui[delivers #166121432]
  pkg/handlers/adminapi/offices.go
  src/scenes/SystemAdmin/Home.jsx
  swagger/admin.yaml
Labels: ttv

#2489 PPM Closeout: Entitlement value
  cypress/integration/mymove/ppm.js
  src/scenes/Moves/Ppm/PaymentReview/ExpenseTicketListItem.jsx
  src/scenes/Moves/Ppm/PaymentReview/WeightTicketListItem.jsx
  src/scenes/Moves/Ppm/PaymentReview/index.jsx
  src/scenes/Moves/Ppm/utility.js
  src/scenes/Moves/Ppm/utility.test.js
Labels: roci

#2495 Display form errors below field
  src/scenes/ServiceMembers/DodInfo.jsx
  src/scenes/ServiceMembers/DutyStationSearchBox.jsx
  src/shared/JsonSchemaForm/JsonSchemaField.js
  src/shared/JsonSchemaForm/index.css
Labels: roci

#2492 Update updateServiceMember dispatch call so service member current du…
  src/scenes/Office/OrdersPanel.jsx
  src/scenes/Office/OrdersViewerPanel.js
Labels: A-Team, bug

#2499 Add office user show component
  src/scenes/SystemAdmin/AdminPagination.jsx
  src/scenes/SystemAdmin/Home.jsx
  src/scenes/SystemAdmin/OfficeList.jsx
  src/scenes/SystemAdmin/UserList.jsx
  src/scenes/SystemAdmin/UserShow.jsx
Labels: ttv

#2498 PPM Closeout: Estimated Payment Amount on Homepage
  cypress/integration/mymove/ppm.js
  src/scenes/Landing/MoveSummary.jsx
  src/scenes/Landing/MoveSummary.test.jsx
  src/scenes/Landing/index.test.js
Labels: roci

#2504 Manually add styles to react-admin
  src/index.js
  src/scenes/SystemAdmin/Home.jsx
  src/scenes/SystemAdmin/Home.module.scss
  src/scenes/SystemAdmin/SignIn.module.scss
Labels: ttv

#2507 Added missing weight estimate
  src/scenes/Landing/MoveSummary.jsx
Labels: roci

#2467 Office App Calculate days for Storage Expenses
  pkg/handlers/internalapi/api.go
  pkg/handlers/internalapi/move_documents.go
  pkg/handlers/internalapi/move_documents_test.go
  pkg/models/moving_expense_document.go
  pkg/models/moving_expense_document_test.go
  pkg/models/shipment_summary_worksheet.go
  pkg/models/shipment_summary_worksheet_test.go
  pkg/services/move_document.go
  pkg/services/move_documents/generic_move_document_updater.go
  pkg/services/move_documents/logger.go
  pkg/services/move_documents/move_document_test.go
  pkg/services/move_documents/ppm_completer.go
  pkg/services/move_documents/ppm_completer_test.go
  pkg/services/move_documents/storage_expense_updater.go
  pkg/services/move_documents/storage_expense_updater_test.go
  pkg/services/move_documents/update_move_document.go
  pkg/services/move_documents/update_move_document_test.go
  pkg/services/move_documents/weight_ticket_updater.go
  pkg/services/move_documents/weight_ticket_updater_test.go
  src/scenes/Office/DocumentViewer/DocumentDetailPanel.jsx
Labels: roci

#2509 Add product admin users secure migration
  local_migrations/20190812151703_add_product_admin_users.sql
  migrations/20190812151703_add_product_admin_users.up.fizz
  migrations_manifest.txt
Labels: ttv

#2508 Changed path of pdfcpu package (was causing dependency updater to fail)
  docs/adr/0027-pdf-generation.md
  go.mod
  go.sum
  pkg/handlers/internalapi/personally_procured_move_attachments_test.go
  pkg/paperwork/generator.go
  pkg/paperwork/generator_test.go
Labels: dependencies, 🦇team

#2458 Exclude documents from calculation if indicated by status
  cypress/integration/office/ppmMoveDocuments.js
  pkg/models/move_document.go
  pkg/models/shipment_summary_worksheet.go
  pkg/models/shipment_summary_worksheet_test.go
  pkg/testdatagen/scenario/e2ebasic.go
  src/scenes/Office/MoveInfo.jsx
  src/scenes/Office/Ppm/ExpensesPanel.jsx
  src/scenes/Office/office.scss
  swagger/internal.yaml
Labels: roci

#2512 Default ppm to empty object if it is an HHG move to prevent app crashing
  src/scenes/Moves/Ppm/ducks.js
  src/scenes/Review/PPMShipmentSummary.jsx
Labels: roci

#2511 Kim 167580601 remove texting option
  cypress/fixtures/serviceMember.json
  cypress/integration/mymove/hhgPPM.js
  pkg/handlers/internalapi/service_members.go
  pkg/handlers/internalapi/service_members_test.go
  pkg/handlers/publicapi/service_members.go
  pkg/models/service_member.go
  src/scenes/MyMove/getWorkflowRoutes.jsx
  src/scenes/Office/CustomerInfoPanel.jsx
  src/scenes/Office/MoveInfo.jsx
  src/scenes/Review/EditContactInfo.jsx
  src/scenes/Review/ServiceMemberSummary.jsx
  src/scenes/ServiceMembers/ContactInfo.jsx
  src/scenes/ServiceMembers/ducks.test.js
  src/scenes/TransportationServiceProvider/CustomerInfo.jsx
  src/scenes/TransportationServiceProvider/ShipmentInfo.jsx
  src/shared/User/sampleLoggedInUserPayload.js
  swagger/api.yaml
  swagger/internal.yaml
Labels: A-Team

#2506 Upgrade fizz files to the latest spec
  config/database.yml
  migrations/20180103215841_create_issues.up.fizz
  migrations/20180126235545_create_form1299s.up.fizz
  migrations/20180205195330_create_traffic_distribution_lists.up.fizz
  migrations/20180205233329_create_shipments.up.fizz
  migrations/20180206001437_create_transportation_service_providers.up.fizz
  migrations/20180206005125_create_best_value_scores.up.fizz
  migrations/20180206005540_create_awarded_shipments.up.fizz
  migrations/20180207003233_create_addresses.up.fizz
  migrations/20180214004003_create_blackout_dates.up.fizz
  migrations/20180214004029_create_performance_periods.up.fizz
  migrations/20180214004139_create_quality_band_assignments.up.fizz
  migrations/20180227224236_create_users.up.fizz
  migrations/20180227230828_switch_to_tsp_performance.up.fizz
  migrations/20180308004703_create_moves.up.fizz
  migrations/20180308191758_create_signed_certifications.up.fizz
  migrations/20180314215702_create_personally_procured_moves.up.fizz
  migrations/20180316163100_create_documents.up.fizz
  migrations/20180316163223_create_uploads.up.fizz
  migrations/20180329183912_internationalize_addresses.up.fizz
  migrations/20180404214855_create_service_members.up.fizz
  migrations/20180405193958_create_duty_stations.up.fizz
  migrations/20180411220843_create_social_security_numbers.up.fizz
  migrations/20180411230846_create_backup_contacts.up.fizz
  migrations/20180420230011_add_duty_station_to_service_member.up.fizz
  migrations/20180425233321_create_orders.up.fizz
  migrations/20180503234257_create_transportation_offices.up.fizz
  migrations/20180504002127_create_office_phone_lines.up.fizz
  migrations/20180504002218_create_office_emails.up.fizz
  migrations/20180504002320_create_office_users.up.fizz
  migrations/20180522211533_create_reimbursements.up.fizz
  migrations/20180703193725_create_move_document.up.fizz
  migrations/20180709203345_create_tsp_users.up.fizz
  migrations/20180722002959_add_moving_expense_docs.up.fizz
  migrations/20180810112708_create_service_agents.up.fizz
  migrations/20180822222712_premove_changes.up.fizz
  migrations/20180925065510_create-accessorials-table.up.fizz
  migrations/20181023215214_add_shipment_line_item.up.fizz
  migrations/20181024184423_create_dps_users.up.fizz
  migrations/20181029190859_create_invoices_table.up.fizz
  migrations/20181029213131_create_400ng_item_rate_table.up.fizz
  migrations/20181114202201_add_shipment_fk_to_invoices.up.fizz
  migrations/20181220160608_add_invoice_upload.up.fizz
  migrations/20190129191416_shipmentLineItem_dimensions.up.fizz
  migrations/20190130193728_create_storage_in_transits.up.fizz
  migrations/20190131194835_create_shipment_recalculate_logs.up.fizz
  migrations/20190131201437_create_shipment_recalculates.up.fizz
  migrations/20190131222220_add_shipment_recalculate_date.up.fizz
  migrations/20190207001056_create_distance_calculations.up.fizz
  migrations/20190213220918_create_electronic_orders.up.fizz
  migrations/20190227184037_add-user-disable.up.fizz
  migrations/20190306205302_add-indexes-for-foreign-keys.up.fizz
  migrations/20190328002445_add_superuser_bool_to_users.up.fizz
  migrations/20190328164048_shipment_line_items_new_cols_item_125.up.fizz
  migrations/20190523210038_index_move_status.up.fizz
  migrations/20190612091000_add-office-tsp-dps-disable.up.fizz
  migrations/20190701205931_add_duty_station_index.up.fizz
Labels: 🦇team

#2516 Sum net weight of multiple weight tickets
  pkg/services/move_documents/storage_expense_updater.go
  pkg/services/move_documents/storage_expense_updater_test.go
  pkg/services/move_documents/update_move_document.go
  pkg/services/move_documents/weight_ticket_updater.go
  pkg/services/move_documents/weight_ticket_updater_test.go
Labels: roci

#2522 Change OTHER label to Not GTCC
  src/scenes/Moves/Ppm/PaymentReview/ExpenseTicketListItem.jsx
Labels: roci

#2474 Add tests for AuthorizeUnknownUser
  pkg/auth/authentication/auth.go
  pkg/auth/authentication/auth_test.go
  pkg/models/backup_contact.go
  pkg/models/client_cert.go
  pkg/models/document.go
  pkg/models/duty_station.go
  pkg/models/electronic_order.go
  pkg/models/errors.go
  pkg/models/invoice.go
  pkg/models/move.go
  pkg/models/move_document.go
  pkg/models/order.go
  pkg/models/personally_procured_move.go
  pkg/models/reimbursement.go
  pkg/models/service_member.go
  pkg/models/shipment.go
  pkg/models/shipment_summary_worksheet.go
  pkg/models/signed_certification.go
  pkg/models/traffic_distribution_list.go
  pkg/models/transportation_service_provider.go
  pkg/models/transportation_service_provider_performance.go
  pkg/models/upload.go
Labels: ttv

#2527 Add exit condition to prevent curl from breaking the build
  .circleci/config.yml
Labels: 🦇team

#2521 Convereted anchor tag to react-router link
  src/scenes/Legalese/CustomerAgreement.jsx
Labels: roci

#2530 Enable PPM Closeout flow in staging and production by default
  cypress/integration/mymove/ppm.js
  src/shared/featureFlags.js
Labels: roci

#2449 Add additional date validations for TSP edit form
  cypress/integration/tsp/storageInTransit.js
  src/shared/JsonSchemaForm/JsonSchemaField.js
  src/shared/JsonSchemaForm/validator.js
  src/shared/StorageInTransit/StorageInTransitTspEditForm.jsx
  src/shared/StorageInTransit/TspEditor.jsx
Labels: A-Team

#2537 Add John Gedeon to office, tsp and admin
  local_migrations/20190814223800_add_john_gedeon.sql
  migrations/20190814223800_add_john_gedeon.up.fizz
  migrations_manifest.txt
Labels: 🦇team

#2497 update moves and delete duty stations w/ no zip3: 167301662
  migrations/20190807163505_modify-moves-bad-zip3-and-delete.up.sql
  migrations_manifest.txt
Labels: ttv

#2542 Disable Mikena's users
  local_migrations/20190815172746_disable_mikena.up.sql
  migrations/20190815172746_disable_mikena.up.fizz
  migrations_manifest.txt
Labels: 🦇team

#2538 Update the ppm submission text copy
  cypress/integration/mymove/hhgPPM.js
  src/scenes/Landing/MoveSummary.jsx
Labels: roci

#2534 Office PPM payment requests queue [delivers #167575622]
  pkg/models/queue.go
  pkg/models/queue_test.go
  src/scenes/Office/MoveInfo.jsx
  src/scenes/Office/QueueList.jsx
  src/scenes/Office/QueueTable.jsx
  swagger/internal.yaml
Labels: ttv

#2513 Add migration to remove TextMessageIsPreferred column
  migrations/20190812184046_remove_column_text_message_is_preferred.up.fizz
  migrations_manifest.txt
Labels: A-Team

#2546 Remove backend uploader filesize limit
  pkg/uploader/uploader.go
  pkg/uploader/uploader_test.go
Labels: roci

#2548 Update the Memory reservations for app containers by doubling them
  scripts/ecs-deploy-service-container
Labels: roci

#2532 Rotate images for pdf download if needed
  cmd/image-to-pdf/main.go
  go.mod
  go.sum
  pkg/handlers/internalapi/personally_procured_move_attachments.go
  pkg/paperwork/generator.go
  pkg/paperwork/generator_test.go
  pkg/paperwork/testdata/example_landscape.jpg
  pkg/paperwork/testdata/example_landscape.png
Labels: roci

#2571 Remove tsp scene directory
  src/scenes/TransportationServiceProvider/ContactInfo.jsx
  src/scenes/TransportationServiceProvider/ContactInfo.test.jsx
  src/scenes/TransportationServiceProvider/CustomerInfo.jsx
  src/scenes/TransportationServiceProvider/DocumentViewerContainer.jsx
  src/scenes/TransportationServiceProvider/FormButton.jsx
  src/scenes/TransportationServiceProvider/NewDocumentContainer.jsx
  src/scenes/TransportationServiceProvider/PickupForm.jsx
  src/scenes/TransportationServiceProvider/PremoveSurveyForm.jsx
  src/scenes/TransportationServiceProvider/QueueList.jsx
  src/scenes/TransportationServiceProvider/QueueTable.jsx
  src/scenes/TransportationServiceProvider/QueueTable.test.js
  src/scenes/TransportationServiceProvider/ServiceAgentForm.jsx
  src/scenes/TransportationServiceProvider/ShipmentInfo.jsx
  src/scenes/TransportationServiceProvider/ShipmentInfo.test.js
  src/scenes/TransportationServiceProvider/api.js
  src/scenes/TransportationServiceProvider/index.jsx
  src/scenes/TransportationServiceProvider/index.test.js
  src/scenes/TransportationServiceProvider/tsp.scss
Labels: ttv

#2553 Removed storage estimate from PPM dates/locations page; enabled on summary page
  cypress/integration/mymove/ppm.js
  src/scenes/Moves/Ppm/DateAndLocation.jsx
  src/scenes/Review/PPMShipmentSummary.jsx
Labels: A-Team

#2565 Remove Payment requested and Get ready to move copies
  cypress/integration/mymove/landingPages.js
  cypress/integration/mymove/ppm.js
  src/scenes/Landing/MoveSummary.jsx
Labels: roci

#2551 Remove advance related text from Customize Weight page
  cypress/integration/mymove/ppm.js
  src/scenes/Moves/Ppm/Weight.jsx
Labels: roci

#2584 move postal codes to internal API: 167953116
  pkg/handlers/internalapi/api.go
  pkg/handlers/internalapi/postal_codes.go
  pkg/handlers/internalapi/postal_codes_test.go
  pkg/handlers/publicapi/api.go
  src/shared/api.js
  swagger/api.yaml
  swagger/internal.yaml
Labels: ttv

#2591 Add new office user: 167871666
  local_migrations/20190821192638_add_office_user.up.sql
  migrations_manifest.txt
Labels: ttv

#2518 Separate PPM closeout tests and lightly refactor
  cypress/integration/mymove/ppm.js
  cypress/integration/mymove/ppmCloseout.js
  src/scenes/Landing/MoveSummary.jsx
Labels: roci

#2494 Kma 167028390 open link new window 2
  cypress/integration/office/documentViewer.js
  cypress/integration/office/ppmMoveDocuments.js
  cypress/integration/tsp/documentViewer.js
  cypress/integration/tsp/generateGBL.js
  src/scenes/MyMove/index.jsx
  src/scenes/Office/DocumentViewer/DocumentDetailPanel.jsx
  src/scenes/Office/DocumentViewer/index.jsx
  src/scenes/Office/MoveInfo.jsx
  src/scenes/Office/OrdersInfo.jsx
  src/scenes/Office/OrdersPanel.jsx
  src/scenes/Office/index.jsx
  src/scenes/Office/index.test.js
  src/scenes/TransportationServiceProvider/ShipmentInfo.jsx
  src/scenes/TransportationServiceProvider/index.jsx
  src/shared/DocumentViewer/DocumentList.jsx
  src/shared/DocumentViewer/DocumentList.module.scss
  src/shared/DocumentViewer/DocumentList.test.jsx
  src/shared/DocumentViewer/DocumentUploadViewer.jsx
  src/shared/DocumentViewer/MoveDocumentView.jsx
  src/shared/Entities/modules/moveDocuments.js
  src/shared/SomethingWentWrong/index.jsx
  src/shared/constants.js
  src/shared/utils.js
Labels: A-Team

#2596 Add a survey link to move submitted email
  pkg/notifications/move_submitted.go
Labels: roci

#2602 Remove tdl swagger definition
  swagger/api.yaml
Labels: ttv

#2603 Remove move docs and uploads from public API
  pkg/handlers/publicapi/api.go
  pkg/handlers/publicapi/generic_move_documents.go
  pkg/handlers/publicapi/generic_move_documents_test.go
  pkg/handlers/publicapi/move_documents.go
  pkg/handlers/publicapi/move_documents_test.go
  pkg/handlers/publicapi/uploads.go
  pkg/handlers/publicapi/uploads_test.go
  src/shared/Entities/modules/moveDocuments.js
  swagger/api.yaml
Labels: ttv

#2614 Fix issues on PPM shipment summary (bad merge)
  src/scenes/Moves/Ppm/DateAndLocation.jsx
  src/scenes/Review/PPMShipmentSummary.jsx
Labels: A-Team

#2583 Give office users the ability to rotate images in the document viewer
  src/scenes/Office/DocumentViewer/index.css
  src/shared/DocumentViewer/DocumentContent.jsx
  src/shared/DocumentViewer/DocumentContent.module.scss
  src/shared/DocumentViewer/DocumentContent.test.jsx
  src/shared/DocumentViewer/DocumentUploadViewer.jsx
  src/shared/DocumentViewer/index.css
  src/shared/RotationBar/RotationBar.jsx
  src/shared/RotationBar/RotationBar.module.scss
  src/shared/images/left-rotation.png
  src/shared/images/right-rotation.png
Labels: roci

#2632 Remove concept of tsp user
  Makefile
  cmd/make_tsp_user/main.go
  cypress/support/commands.js
  cypress/support/constants.js
  cypress/support/testTspStatus.js
  pkg/auth/authentication/auth.go
  pkg/auth/authentication/auth_test.go
  pkg/auth/authentication/devlocal.go
  pkg/auth/authentication/devlocal_test.go
  pkg/auth/session.go
  pkg/handlers/apitests.go
  pkg/middleware/request_logger.go
  pkg/models/invoice.go
  pkg/models/move_document.go
  pkg/models/service_member.go
  pkg/models/shipment.go
  pkg/models/tsp_users.go
  pkg/models/tsp_users_test.go
  pkg/models/user.go
  pkg/models/user_test.go
  pkg/services/shipment_line_item/get_shipment_line_items.go
  pkg/services/shipment_line_item/recalculate_shipment_line_items.go
  pkg/testdatagen/make_tsp_user.go
  pkg/testdatagen/shared.go
Labels: ttv

#2638 fix test error msg
  pkg/auth/authentication/devlocal_test.go
Labels: ttv
