Repository transcom/mymove, pull requests merged in 2019-07, with the labels that each got.

#2260 Remove project alumni from all environments.
  local_migrations/20190624154036_remove-project-alumni.sql
  migrations/20190624154036_remove-project-alumni.up.fizz
Labels: roci

#2331 New PPM closeout submission + completion flow
  cypress/integration/mymove/landingPages.js
  cypress/integration/mymove/orders.js
  cypress/integration/mymove/ppm.js
  pkg/testdatagen/scenario/e2ebasic.go
  src/scenes/Landing/MoveSummary.jsx
  src/scenes/Landing/PPMStatusTimeline.js
  src/scenes/Landing/StatusTimeline.jsx
  src/scenes/Landing/StatusTimeline.test.jsx
  src/scenes/Moves/Ppm/PaymentReview/index.jsx
Labels: roci

#2301 Redirect to login page upon queues 401 error [delivers #166389725]
  src/scenes/Office/QueueTable.jsx
  src/scenes/Office/QueueTable.test.js
  src/shared/Data/users.js
  src/shared/Swagger/api.js
Labels: ttv

#2333 PPM Payment Request: Documents Added Alert
  src/scenes/Moves/Ppm/DocumentsUploaded.js
  src/scenes/Moves/Ppm/DocumentsUploaded.test.js
  src/scenes/Moves/Ppm/ExpensesLanding.jsx
  src/scenes/Moves/Ppm/ExpensesUpload.jsx
  src/scenes/Moves/Ppm/PaymentReview/DocumentsUploaded.js
  src/scenes/Moves/Ppm/PaymentReview/DocumentsUploaded.test.js
  src/scenes/Moves/Ppm/PaymentReview/ExpenseTicketListItem.jsx
  src/scenes/Moves/Ppm/PaymentReview/PaymentReview.css
  src/scenes/Moves/Ppm/PaymentReview/WeightTicketListItem.jsx
  src/scenes/Moves/Ppm/PaymentReview/index.jsx
  src/scenes/Moves/Ppm/WeightTicket.jsx
  src/scenes/Moves/Ppm/utility.js
  src/scenes/Moves/Ppm/utility.test.js
  src/shared/formatters.js
  src/shared/formatters.test.js
  src/shared/images/docs_added_checkmark.png
Labels: roci

#2342 Add Trussel to staging and experimental office and tsp [delivers #167048259]
  local_migrations/20190702170631_add_new_office_user.sql
  migrations/20190702170631_add_new_office_user.up.fizz
Labels: 🦇team

#2340 Alert if no receipt for storage exepsne
  cypress/integration/mymove/ppm.js
  src/scenes/Moves/Ppm/ExpensesUpload.jsx
Labels: roci

#2330 Add missing space around UI elements.
  src/scenes/Review/Edit.jsx
  src/scenes/Review/Review.css
  src/scenes/Review/ServiceMemberSummary.jsx
Labels: roci

#2348 Add USMC office users
  local_migrations/20190703141326_add-usmc-office-users.sql
  migrations/20190703141326_add-usmc-office-users.up.fizz
Labels: 🦇team

#2337 Automated dependency updates | Mon, 01 Jul 2019 12:02:33 +0000 [delivers #167025231]
  yarn.lock
Labels: 🦇team

#2341 Fix invalid date selection issue for e2e_tests
  Dockerfile.cypress
  cypress/integration/tsp/shipShipment.js
  cypress/support/commands.js
  cypress/support/utils.js
Labels: 🦇team

#2356 Automated dependency updates | Mon, 08 Jul 2019 12:02:31 +0000
  yarn.lock
Labels: 🦇team

#2357 Automated dependency updates | Mon, 08 Jul 2019 12:03:13 +0000
  go.mod
  go.sum
Labels: 🦇team

#2346 Admin users and organizations
  migrations/20190702150158_create_admin_users.up.fizz
  migrations/20190702195904_create_organizations.up.fizz
  pkg/models/admin_user.go
  pkg/models/admin_user_test.go
  pkg/models/organization.go
  pkg/models/organization_test.go
Labels: ttv

#2307 Redirect user to landing page if multiple sessions have different cookies
  pkg/auth/authentication/auth.go
  pkg/auth/authentication/auth_test.go
  pkg/auth/cookie.go
Labels: roci, 🦇team

#2359 Update SwaggerRequest to be compatible with swagger-client 3.9.0
  package.json
  src/shared/Swagger/request.js
  yarn.lock
Labels: 🦇team

#2360 Calculate and Display PPM Storage Costs
  pkg/handlers/internalapi/move_documents.go
Labels: roci

#2353 Add an edit payment request button
  cypress/integration/mymove/ppm.js
  pkg/models/personally_procured_move.go
  src/scenes/Landing/MoveSummary.jsx
Labels: roci

#2361 Update canceled move email
  pkg/notifications/move_canceled.go
Labels: roci

#2364 Update submitted email
  pkg/notifications/move_submitted.go
Labels: roci

#2368 Add USMC office users
  local_migrations/20190709204712_add-office-users.sql
  migrations/20190709204712_add-office-users.up.fizz
Labels: 🦇team

#2381 Update yarn lock for swagger-client
  yarn.lock
Labels: 🦇team

#2372 Skip button for PPM Closeout
  cypress/integration/mymove/ppm.js
  src/scenes/Moves/Ppm/ExpensesUpload.jsx
  src/scenes/Moves/Ppm/PPMPaymentRequestActionBtns.jsx
  src/scenes/Moves/Ppm/WeightTicket.jsx
Labels: roci

#2355 Add command line tool for adding multiple office users
  cmd/milmove/gen_migration.go
  cmd/milmove/gen_office_user_migration.go
  cmd/milmove/main.go
  docs/how-to/create-or-disable-users.md
Labels: 🦇team

#2384 Change text for trailer criteria link question
  cypress/integration/mymove/ppm.js
  src/scenes/Moves/Ppm/WeightTicket.jsx
Labels: roci

#2382 Add more new lines to submitted and cancelled emails
  pkg/notifications/move_canceled.go
  pkg/notifications/move_submitted.go
Labels: roci

#2388 Load missing Marine duty stations
  migrations/20190711215901_load_usmc_duty_stations.up.sql
  migrations_manifest.txt
Labels: ttv

#2392 Add migration to manifest file (bad zip codes)
  migrations/20190705235827_fix_duty_station_zip.up.sql
  migrations_manifest.txt
Labels: ttv

#2378 Add an alert if any of the storage expenses have not been OK'd
  src/scenes/Office/MoveInfo.jsx
  src/scenes/Office/Ppm/StoragePanel.js
  src/scenes/Office/Ppm/StoragePanel.test.js
  src/scenes/Office/office.scss
Labels: roci

#2393 Delete duty stations w/ no corresponding zip3: 165924370
  migrations/20190715122032_delete-duty-stations-with-no-zip3.up.sql
  migrations_manifest.txt
Labels: ttv

#2394 Update country to `United States` vs `US`
  migrations/20190713214312_update-county-code-us.up.sql
  migrations_manifest.txt
Labels: ttv

#2395 Automated dependency updates | Mon, 15 Jul 2019 12:03:23 +0000
  go.mod
  go.sum
Labels: 🦇team

#2396 Automated dependency updates | Mon, 15 Jul 2019 12:07:08 +0000
  yarn.lock
Labels: 🦇team

#2397 delete duty stations w/ no corresponding zip3 row - skip conflicts
  migrations/20190715122032_delete-duty-stations-with-no-zip3.up.sql
  migrations/20190715144534_delete-duty-stations-with-no-zip3-conflict.up.sql
  migrations_manifest.txt
  pkg/models/queue.go
Labels: ttv

#2362 Disable download all attachments button when there are no attachments…
  cypress/integration/office/officeUserPPM.js
  src/scenes/Office/Ppm/PaymentsPanel.jsx
Labels: A-Team, bug

#1776 Run go tests in a package-specific database
  .circleci/config.yml
  .envrc
  Makefile
  config/database.yml
  go.mod
  internal/pkg/dutystationsloader/duty_stations_loader_test.go
  pkg/auth/authentication/auth_test.go
  pkg/awardqueue/awardqueue_test.go
  pkg/dates/calculators_test.go
  pkg/db/dbfmt/dbfmt_test.go
  pkg/db/sequence/sequencer_test.go
  pkg/edi/invoice/generator_test.go
  pkg/handlers/adminapi/api_test.go
  pkg/handlers/apitests.go
  pkg/handlers/dpsapi/api_test.go
  pkg/handlers/errors_test.go
  pkg/handlers/internalapi/api_test.go
  pkg/handlers/ordersapi/api_test.go
  pkg/handlers/publicapi/api_test.go
  pkg/models/models_test.go
  pkg/notifications/notification_test.go
  pkg/paperwork/paperwork_test.go
  pkg/rateengine/rateengine_test.go
  pkg/route/here_planner_test.go
  pkg/services/accesscode/access_code_service_test.go
  pkg/services/accesscode/claim_access_code_test.go
  pkg/services/accesscode/fetch_access_code_test.go
  pkg/services/fuelprice/fuel_price_service_test.go
  pkg/services/invoice/invoice_service_test.go
  pkg/services/invoice/send_to_gex_http_test.go
  pkg/services/paperwork/paperwork_service_test.go
  pkg/services/postal_codes/validate_postal_code_test.go
  pkg/services/query/query_builder_test.go
  pkg/services/shipment/shipment_service_test.go
  pkg/services/shipment_line_item/shipment_line_item_service_test.go
  pkg/services/storage_in_transit/storage_in_transit_service_test.go
  pkg/services/user/user_service_test.go
  pkg/testingsuite/pop_suite.go
  pkg/uploader/uploader_test.go
Labels: roci

#2371 Accumulate Net Weight of Approved Weight Ticket Set Docs
  cypress/integration/office/officeUserPPM.js
  src/scenes/Office/DocumentViewer/DocumentDetailPanel.jsx
  src/scenes/Office/Ppm/NetWeightPanel.jsx
  src/scenes/TransportationServiceProvider/ShipmentInfo.jsx
  src/shared/Entities/modules/moveDocuments.js
  src/shared/Entities/modules/moveDocuments.test.js
  src/shared/constants.js
Labels: roci

#2291 When destination SIT delivery date is changed the actual delivery dat…
  cypress/integration/tsp/storageInTransit.js
  pkg/models/storage_in_transit.go
  pkg/models/storage_in_transit_test.go
  pkg/services/storage_in_transit/patch_storage_in_transit.go
  pkg/services/storage_in_transit/storage_in_transit_service_test.go
  pkg/testdatagen/scenario/e2ebasic.go
  src/scenes/TransportationServiceProvider/ShipmentInfo.jsx
  src/shared/StorageInTransit/StorageInTransit.css
  src/shared/StorageInTransit/TspEditor.jsx
Labels: A-Team

#2370 PPM Closeout: Continue requesting payment button
  cypress/integration/mymove/ppm.js
  pkg/testdatagen/scenario/e2ebasic.go
  src/scenes/Landing/MoveSummary.jsx
  yarn.lock
Labels: roci

#2400 Replace cancel and save for later with finish later button
  cypress/integration/mymove/ppm.js
  src/scenes/Moves/Ppm/ExpensesLanding.jsx
  src/scenes/Moves/Ppm/ExpensesUpload.jsx
  src/scenes/Moves/Ppm/PPMPaymentRequest.css
  src/scenes/Moves/Ppm/PPMPaymentRequestActionBtns.jsx
  src/scenes/Moves/Ppm/PPMPaymentRequestIntro.jsx
  src/scenes/Moves/Ppm/PaymentReview/index.jsx
  src/scenes/Moves/Ppm/WeightTicket.jsx
  src/scenes/Moves/Ppm/WeightTicket.test.js
  src/shared/AlertWithConfirmation/index.css
  src/shared/AlertWithConfirmation/index.jsx
  src/shared/AlertWithConfirmation/index.test.jsx
Labels: roci

#2410 Update DB_PORT to use DB_PORT_TEST in pop_suite.go
  .circleci/config.yml
  docs/how-to/run-go-tests.md
  pkg/testingsuite/pop_suite.go
  scripts/README.md
  scripts/go-test
Labels: roci

#2402 Disable users associated with Patrick D
  local_migrations/20190716161854_remove_patrick_d.sql
  migrations/20190716161854_remove_patrick_d.up.fizz
  migrations_manifest.txt
Labels: 🦇team

#2417 Script to generate migrations for disabling users
  cmd/milmove/gen_disable_user_migration.go
  cmd/milmove/main.go
  docs/how-to/create-or-disable-users.md
Labels: 🦇team

#2401 Add empty and full weight ticket fields to document viewer
  cypress/integration/office/documentViewer.js
  pkg/handlers/internalapi/move_documents.go
  pkg/handlers/internalapi/move_documents_test.go
  pkg/handlers/publicapi/move_documents.go
  pkg/models/move_document.go
  pkg/models/weight_ticket_set_document.go
  pkg/testdatagen/make_move_document.go
  pkg/testdatagen/make_weight_ticket_set_document.go
  pkg/testdatagen/scenario/e2ebasic.go
  src/scenes/Office/DocumentViewer/DocumentDetailPanel.jsx
  swagger/internal.yaml
Labels: roci

#2422 Automated dependency updates | Mon, 22 Jul 2019 12:02:47 +0000
  yarn.lock
Labels: 🦇team

#2423 Automated dependency updates | Mon, 22 Jul 2019 12:04:03 +0000
  go.mod
  go.sum
Labels: 🦇team

#2377 Use new admin users table to authentication and authorization.
  cmd/milmove/serve.go
  internal/pkg/dutystationsloader/duty_stations_loader_test.go
  local_migrations/20190710174257_add_system_admin_users.sql
  migrations/20190708201347_make_admin_users_fname_and_lname_required.up.fizz
  migrations/20190710151514_make_organizations_poc_nullable.up.fizz
  migrations/20190710174257_add_system_admin_users.up.fizz
  migrations_manifest.txt
  pkg/auth/authentication/auth.go
  pkg/auth/authentication/auth_test.go
  pkg/auth/authentication/devlocal.go
  pkg/auth/authentication/devlocal_test.go
  pkg/auth/session.go
  pkg/models/admin_user.go
  pkg/models/admin_user_test.go
  pkg/models/user.go
  pkg/models/user_test.go
  pkg/testdatagen/make_admin_user.go
  pkg/testdatagen/shared.go
Labels: ttv

#2421 remove move type selection
  cypress/integration/mymove/shipment.js
  src/scenes/MyMove/getWorkflowRoutes.jsx
  src/scenes/MyMove/getWorkflowRoutes.test.js
  src/scenes/Orders/TransitionToMove.jsx
Labels: roci

#2433 Add Albany GA duty station and PPPO
  migrations/20190723165935_add-duty-station-uslb-albany-ga.up.sql
  migrations_manifest.txt
Labels: ttv

#2408 Update pdfcpu to current version (and do not use fork)
  cmd/update_deps/main.go
  go.mod
  go.sum
  pkg/handlers/fixtures/orders.pdf
  pkg/handlers/internalapi/personally_procured_move_attachments.go
  pkg/handlers/internalapi/personally_procured_move_attachments_test.go
  pkg/paperwork/generator.go
  pkg/paperwork/generator_test.go
  src/scenes/Office/Ppm/PaymentsPanel.jsx
Labels: roci

#2439 Add failwhale to office app
  src/scenes/MyMove/index.jsx
  src/scenes/MyMove/index.test.js
  src/scenes/Office/index.jsx
  src/scenes/Office/index.test.js
  src/shared/SomethingWentWrong/index.jsx
  src/shared/SomethingWentWrong/index.test.js
Labels: roci

#2404 SAC required to approve basics
  cypress/integration/office/officeUserPPM.js
  pkg/handlers/internalapi/office_test.go
  pkg/models/order.go
  pkg/testdatagen/make_order.go
  pkg/testdatagen/scenario/e2ebasic.go
  src/scenes/Office/AccountingPanel.jsx
  src/scenes/Office/MoveInfo.jsx
  src/scenes/Office/OrdersViewerPanel.js
Labels: ttv

#2414 Use object tag to show pdf if browser compatible
  src/shared/DocumentViewer/DocumentContent.jsx
  src/shared/DocumentViewer/DocumentContent.module.scss
  src/shared/utils.js
Labels: A-Team

#2428 Capture actual_move_date in ppm closeout.
  cypress/integration/mymove/ppm.js
  src/scenes/Moves/Ppm/PPMPaymentRequest.css
  src/scenes/Moves/Ppm/PPMPaymentRequestIntro.jsx
  src/scenes/Moves/Ppm/PPMPaymentRequestIntro.module.scss
Labels: roci

#2242 Add data to office users endpoint
  pkg/handlers/adminapi/office_users.go
  pkg/handlers/adminapi/office_users_test.go
  pkg/services/user.go
  pkg/services/user/office_user_list_fetcher.go
  pkg/services/user/office_user_list_fetcher_test.go
Labels: ttv

#2431 Fix alignment of Read PPM Info Packet and Requesting Payment buttons
  src/scenes/Moves/Ppm/PPMPaymentRequest.css
Labels: roci

#2403 Changed copy of approved move email and added more spacing
  pkg/notifications/move_approved.go
Labels: roci

#2445 Added army to department indicator options
  swagger/internal.yaml
Labels: roci

#2436 PPM Net Weight Panel
  pkg/handlers/internalapi/move_documents.go
  pkg/handlers/internalapi/move_documents_test.go
  pkg/handlers/internalapi/personally_procured_move.go
  pkg/models/move_document.go
  pkg/models/move_document_test.go
  pkg/models/shipment_summary_worksheet.go
  pkg/models/weight_ticket_set_document.go
  pkg/models/weight_ticket_set_document_test.go
  src/scenes/Office/MoveInfo.jsx
  src/scenes/Office/Ppm/NetWeightPanel.jsx
  src/scenes/Office/Ppm/PaymentsPanel.jsx
  src/shared/Entities/modules/moveDocuments.js
  src/shared/Entities/modules/moveDocuments.test.js
Labels: roci

#2444 Add SIT line items and total cost breakout to SSW
  pkg/models/moving_expense_document.go
  pkg/models/moving_expense_document_test.go
  pkg/models/shipment_summary_worksheet.go
  pkg/models/shipment_summary_worksheet_test.go
  pkg/paperwork/shipment_summary_worksheet.go
Labels: roci

#2420 Use entitlements API
  pkg/handlers/internalapi/move_queue_items.go
  pkg/handlers/internalapi/service_members.go
  pkg/handlers/internalapi/weight_allotment.go
  pkg/handlers/publicapi/service_members.go
  pkg/handlers/publicapi/weight_allotment.go
  pkg/models/queue.go
  src/scenes/Moves/Ppm/ducks.test.js
  src/scenes/Office/queueTableColumns.js
  src/shared/Entities/modules/moves.js
  src/shared/Entities/modules/shipments.js
  src/shared/entitlements.js
  src/shared/entitlements.test.js
  swagger/api.yaml
  swagger/internal.yaml
Labels: ttv

#2426 166359453 sysadmin office user creation
  pkg/handlers/adminapi/api.go
  pkg/handlers/adminapi/office_users.go
  pkg/handlers/adminapi/office_users_test.go
  pkg/services/query/query_builder.go
  pkg/services/query/query_builder_test.go
  pkg/services/user.go
  pkg/services/user/office_user_creator.go
  pkg/services/user/office_user_creator_test.go
  pkg/services/user/office_user_fetcher.go
  pkg/services/user/office_user_fetcher_test.go
  swagger/admin.yaml
  swagger/api.yaml
Labels: ttv

#2386 load script to find missing marine duty stations
  cmd/load_duty_stations/main.go
  cmd/milmove/gen_duty_stations_migration.go
  cmd/milmove/main.go
  pkg/models/duty_station.go
  pkg/models/transportation_office.go
  pkg/route/here_planner.go
  pkg/services/duty_stations/load_duty_stations.go
Labels: ttv

#2472 Remove is_superuser column from users table
  migrations/20190731163048_remove_is_superuser.up.fizz
  migrations_manifest.txt
Labels: ttv

#2455 Implement "tiebreaker" for TSPs with matching BVS scores
  pkg/models/transportation_service_provider.go
  pkg/models/transportation_service_provider_performance.go
  pkg/models/transportation_service_provider_performance_test.go
Labels: A-Team

#2465 Admin offices endpoint [delivers #166121315]
  pkg/handlers/adminapi/api.go
  pkg/handlers/adminapi/api_test.go
  pkg/handlers/adminapi/office_users_test.go
  pkg/handlers/adminapi/offices.go
  pkg/handlers/adminapi/offices_test.go
  pkg/services/office.go
  pkg/services/office/logger.go
  pkg/services/office/office_service_test.go
  swagger/admin.yaml
Labels: ttv
