Repository transcom/mymove, pull requests merged in 2020-10, with the labels that each got.

#4887 [MB-4447] Added checks for nil pointer dereference
  pkg/services/invoice/ghc_payment_request_invoice_generator.go
  pkg/services/invoice/ghc_payment_request_invoice_generator_test.go
Labels: A-Team

#4894 MB-3973 Add handler to assemble MoveOrder notification payload
  pkg/services/event/event.go
  pkg/services/event/event_test.go
  pkg/services/event/notification.go
  pkg/services/event/notification_test.go
Labels: roci

#4896 [MB-4442] Add Ability to Generate EDI for DPK, DUPK, DOP and DDP Service Items
  pkg/services/invoice/ghc_payment_request_invoice_generator.go
  pkg/services/invoice/ghc_payment_request_invoice_generator_test.go
Labels: A-Team

#4883 Kim mb 4125 selectable card component
  .loki/reference/chrome_iphone7_Components_Tables_Service_Item_Tables.png
  .loki/reference/chrome_iphone7_Customer_Components_SelectableCard_Disabled.png
  .loki/reference/chrome_iphone7_Customer_Components_SelectableCard_Selected.png
  .loki/reference/chrome_iphone7_Customer_Components_SelectableCard_Unselected.png
  .loki/reference/chrome_iphone7_TOO_TIO_Components_RejectServiceItemModal_Basic.png
  .loki/reference/chrome_iphone7_TOO_TIO_Components_RequestedServiceItemsTable_Approved_Service_Items.png
  .loki/reference/chrome_iphone7_TOO_TIO_Components_RequestedServiceItemsTable_Default.png
  .loki/reference/chrome_iphone7_TOO_TIO_Components_RequestedServiceItemsTable_Rejected_Service_Items.png
  .loki/reference/chrome_laptop_Components_Tables_Service_Item_Tables.png
  .loki/reference/chrome_laptop_Customer_Components_SelectableCard_Disabled.png
  .loki/reference/chrome_laptop_Customer_Components_SelectableCard_Selected.png
  .loki/reference/chrome_laptop_Customer_Components_SelectableCard_Unselected.png
  .loki/reference/chrome_laptop_TOO_TIO_Components_RejectServiceItemModal_Basic.png
  .loki/reference/chrome_laptop_TOO_TIO_Components_RequestedServiceItemsTable_Approved_Service_Items.png
  .loki/reference/chrome_laptop_TOO_TIO_Components_RequestedServiceItemsTable_Default.png
  .loki/reference/chrome_laptop_TOO_TIO_Components_RequestedServiceItemsTable_Rejected_Service_Items.png
  .loki/reference/chrome_laptop_TOO_TIO_Components_ReviewServiceItems_ReviewDetails_Payment_Authorized.png
  .loki/reference/chrome_laptop_TOO_TIO_Components_ReviewServiceItems_ReviewDetails_Payment_Authorized_Rejected.png
  src/components/Customer/SelectableCard.jsx
  src/components/Customer/SelectableCard.module.scss
  src/components/Customer/SelectableCard.stories.jsx
  src/components/Customer/SelectableCard.test.jsx
  src/shared/styles/colors.scss
Labels: Pamplemoose

#4872 [MB-4108] HHG and PPM ShipmentCard storybook components
  .loki/reference/chrome_iphone7_Customer_Components_HHGShipmentCard_Basic.png
  .loki/reference/chrome_iphone7_Customer_Components_PPMShipmentCard_Basic.png
  .loki/reference/chrome_laptop_Customer_Components_HHGShipmentCard_Basic.png
  .loki/reference/chrome_laptop_Customer_Components_PPMShipmentCard_Basic.png
  src/components/Customer/Review/ShipmentCard/HHGShipmentCard/HHGShipmentCard.module.scss
  src/components/Customer/Review/ShipmentCard/HHGShipmentCard/index.jsx
  src/components/Customer/Review/ShipmentCard/HHGShipmentCard/index.test.jsx
  src/components/Customer/Review/ShipmentCard/PPMShipmentCard/index.jsx
  src/components/Customer/Review/ShipmentCard/PPMShipmentCard/index.test.jsx
  src/components/Customer/Review/ShipmentCard/ShipmentCard.module.scss
  src/components/Customer/Review/ShipmentCard/ShipmentCard.stories.jsx
  src/components/Customer/Review/ShipmentCard/index.jsx
  src/components/Office/ShipmentContainer.jsx
  src/shared/utils.js
  src/shared/utils.test.js
  src/types/shipment.js
Labels: Pamplemoose

#4905 [MB-4224] Added additional G62 segments for scheduled/actual dates
  pkg/edi/segment/g62.go
  pkg/edi/segment/g62_test.go
  pkg/handlers/supportapi/payment_request_test.go
  pkg/services/ghcrateengine/counseling_services_pricer_test.go
  pkg/services/ghcrateengine/domestic_destination_pricer_test.go
  pkg/services/ghcrateengine/domestic_linehaul_pricer_test.go
  pkg/services/ghcrateengine/domestic_origin_pricer_test.go
  pkg/services/ghcrateengine/domestic_pack_pricer_test.go
  pkg/services/ghcrateengine/domestic_shorthaul_pricer_test.go
  pkg/services/ghcrateengine/domestic_unpack_pricer_test.go
  pkg/services/ghcrateengine/fuel_surcharge_pricer_test.go
  pkg/services/ghcrateengine/management_services_pricer_test.go
  pkg/services/ghcrateengine/service_item_pricer_test.go
  pkg/services/invoice/ghc_payment_request_invoice_generator.go
  pkg/services/invoice/ghc_payment_request_invoice_generator_test.go
  pkg/testdatagen/make_payment_service_item_param.go
Labels: A-Team

#4902 Migration for updated CAC
  migrations/app/migrations_manifest.txt
  migrations/app/secure/20201001183657_rriser_cac.up.sql
Labels: A-Team

#4903 MB-3641 Update Certs Migration generator and fix upload secure migration script
  cmd/milmove/gen_certs_migration.go
  scripts/upload-secure-migration
Labels: A-Team

#4859 MB-3616 TOO should only be able to add Mgmt & Counseling service items once
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/move_task_order/update_move_task_order_status_parameters.go
  pkg/gen/ghcmessages/m_t_o_approval_service_item_code.go
  pkg/gen/ghcmessages/m_t_o_approval_service_item_codes.go
  pkg/handlers/ghcapi/move_task_order.go
  pkg/handlers/ghcapi/move_task_order_test.go
  pkg/handlers/supportapi/move_task_order.go
  pkg/services/mocks/MoveTaskOrderUpdater.go
  pkg/services/move_task_order.go
  pkg/services/move_task_order/move_task_order_updater.go
  pkg/testdatagen/make_move.go
  pkg/testdatagen/scenario/e2ebasic.go
  src/components/Office/RequestedShipments/RequestedShipments.jsx
  src/components/Office/RequestedShipments/RequestedShipments.module.scss
  src/components/Office/RequestedShipments/RequestedShipments.test.jsx
  src/components/Office/ShipmentApprovalPreview.jsx
  src/pages/Office/MoveDetails/MoveDetails.jsx
  swagger/ghc.yaml
Labels: ttv

#4910 [MB-3615] MTO Basic Service Items Fix Parsing of approvedAt Date
  pkg/services/move_task_order/move_task_order_updater.go
  src/components/Office/RequestedShipments/RequestedShipments.jsx
  src/components/Office/RequestedShipments/RequestedShipments.test.jsx
Labels: ttv

#4891 MB-4385 Allow MTO tab to render all the time
  package.json
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.test.jsx
Labels: ttv

#4899 PrimeAPI / UpdateMTOShipmentHandler - update payload
  pkg/handlers/primeapi/mto_shipment.go
  pkg/handlers/primeapi/mto_shipment_test.go
  pkg/handlers/primeapi/payloads/model_to_payload.go
  pkg/services/mto_shipment/mto_shipment_updater.go
Labels: roci

#4911 [MB-3940] Event trigger patchMTOShipmentStatus
  pkg/handlers/apitests.go
  pkg/handlers/ghcapi/mto_shipment.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/services/event/notification.go
Labels: roci

#4900 MB 4436 Standardize Heading type/size across all move setup screens
  cypress/integration/mymove/hhg.js
  src/components/Customer/EditShipment.jsx
  src/components/Customer/HHGDetailsForm.jsx
  src/components/Customer/HHGDetailsForm.module.scss
  src/scenes/Legalese/index.jsx
  src/scenes/Moves/Ppm/AllowableExpenses.jsx
  src/scenes/Moves/Ppm/CustomerAgreementLegalese.js
  src/scenes/Moves/Ppm/PPMPaymentRequestIntro.jsx
  src/scenes/Moves/Ppm/TrailerCriteria.jsx
  src/scenes/Moves/Ppm/Weight.jsx
  src/scenes/Moves/Ppm/WeightTicketExamples.jsx
  src/scenes/MyMove/getWorkflowRoutes.jsx
  src/scenes/MyMove/index.jsx
  src/scenes/PpmLanding/MoveSummary/CanceledMoveSummary.jsx
  src/scenes/PpmLanding/PpmSummary.test.jsx
  src/scenes/Review/Review.jsx
  src/scenes/SystemAdmin/shared/SignIn.jsx
  src/shared/User/SignIn.jsx
  src/shared/styles/_typography.scss
Labels: Pamplemoose

#4918 Add experimental testing checkbox to PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ttv

#4919 MB 4545 my.move.mil Landing page Spacing
  src/scenes/PpmLanding/StatusTimeline.scss
  src/scenes/SystemAdmin/shared/SignIn.jsx
  src/shared/User/SignIn.jsx
Labels: Pamplemoose

#4927 Add secure migration for gidjin cac update
  migrations/app/migrations_manifest.txt
  migrations/app/secure/20201006232216_gidjin_cac.up.sql
Labels: A-Team

#4934 [MB-4429] Set FA1 Segment to service-specific code
  pkg/edi/segment/fa1.go
  pkg/edi/segment/fa1_test.go
  pkg/services/invoice/ghc_payment_request_invoice_generator.go
  pkg/services/invoice/ghc_payment_request_invoice_generator_test.go
Labels: A-Team

#4937 MB-4458 Create txo queue table storybook
  package.json
  src/components/Table/Table.jsx
  src/components/Table/Table.module.scss
  src/components/Table/Table.stories.jsx
  src/components/Table/Table.test.jsx
  src/components/Table/utils.js
  src/components/Table/utils.test.js
  yarn.lock
Labels: ttv

#4912 MB-4126 | add another shipment logic
  src/components/Customer/Home/ShipmentList/ShipmentList.module.scss
  src/components/Customer/Home/ShipmentList/ShipmentList.test.jsx
  src/components/Customer/Home/ShipmentList/index.jsx
  src/pages/MyMove/Home/Home.module.scss
  src/pages/MyMove/Home/index.jsx
  src/pages/MyMove/Home/index.test.jsx
  src/pages/MyMove/SelectMoveType.jsx
  src/pages/MyMove/SelectMoveType.mapStateToProps.test.jsx
  src/pages/MyMove/SelectMoveType.test.jsx
  src/scenes/Review/Summary.jsx
Labels: Pamplemoose, moose

#4923 MB-3917 Add event trigger to GHC API's updateMoveTaskOrderStatus endpoint
  pkg/handlers/ghcapi/move_task_order.go
  pkg/handlers/ghcapi/move_task_order_test.go
Labels: roci

#4913 [MB-4578] Create payment request golang script
  cmd/prime-api-client/utils/connection.go
  cmd/prime-api-dev/main.go
  cmd/prime-api-dev/scripts/payment_requests.go
  pkg/cli/cac.go
Labels: A-Team

#4556 [MB-4410] param value caching for create payment request
  pkg/models/service_item_param_key.go
  pkg/models/service_item_param_key_test.go
  pkg/payment_request/service_param_value_lookups/actual_pickup_date_lookup_test.go
  pkg/payment_request/service_param_value_lookups/contract_code_lookup_test.go
  pkg/payment_request/service_param_value_lookups/distance_zip3_lookup_test.go
  pkg/payment_request/service_param_value_lookups/distance_zip5_lookup_test.go
  pkg/payment_request/service_param_value_lookups/eia_fuel_price_lookup_test.go
  pkg/payment_request/service_param_value_lookups/fsc_weight_based_distance_multiplier_lookup_test.go
  pkg/payment_request/service_param_value_lookups/mto_available_to_prime_at_lookup_test.go
  pkg/payment_request/service_param_value_lookups/requested_pickup_date_lookup_test.go
  pkg/payment_request/service_param_value_lookups/service_area_lookup_test.go
  pkg/payment_request/service_param_value_lookups/service_param_value_lookups.go
  pkg/payment_request/service_param_value_lookups/service_param_value_lookups_test.go
  pkg/payment_request/service_param_value_lookups/service_params_cache.go
  pkg/payment_request/service_param_value_lookups/service_params_cache_test.go
  pkg/payment_request/service_param_value_lookups/services_schedule_lookup_test.go
  pkg/payment_request/service_param_value_lookups/weight_actual_lookup_test.go
  pkg/payment_request/service_param_value_lookups/weight_billed_actual_lookup_test.go
  pkg/payment_request/service_param_value_lookups/weight_estimated_lookup_test.go
  pkg/payment_request/service_param_value_lookups/zip_address_lookup_test.go
  pkg/services/payment_request/payment_request_creator.go
Labels: A-Team

#4938 [MB-3718] Generate reference ID for payment service items
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20201006145421_add_reference_id_to_psi.up.sql
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/payment_service_item.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/payment_service_item.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/primeapi/payloads/model_to_payload.go
  pkg/models/payment_service_item.go
  pkg/models/payment_service_item_test.go
  pkg/services/event/notification_payloads.go
  pkg/services/invoice/ghc_payment_request_invoice_generator.go
  pkg/services/invoice/ghc_payment_request_invoice_generator_test.go
  swagger/ghc.yaml
  swagger/prime.yaml
Labels: A-Team

#4935 [MB-4422] fix edi error handling
  pkg/services/invoice/ghc_payment_request_invoice_generator.go
Labels: A-Team

#4945 MB-4425 Filter Move Orders by Office User GBLOC in TOO
  pkg/handlers/ghcapi/move_orders.go
  pkg/services/mocks/MoveOrderFetcher.go
  pkg/services/move_order.go
  pkg/services/move_order/move_order_fetcher.go
  pkg/services/move_order/move_order_fetcher_test.go
  pkg/testdatagen/make_office_user.go
  pkg/testdatagen/make_user.go
Labels: ttv

#4914 Kim mb 4302 integrate selectable card
  src/components/Customer/SelectableCard.jsx
  src/components/Customer/SelectableCard.module.scss
  src/pages/MyMove/SelectMoveType.jsx
  src/pages/MyMove/SelectMoveType.module.scss
  src/pages/MyMove/SelectMoveType.test.jsx
  src/pages/MyMove/index.module.scss
  src/shared/WizardPage/index.jsx
  src/shared/constants.js
Labels: Pamplemoose

#4948 [MB-4457] TOO Move Queues API Endpoint
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/ghcapi/ghcoperations/queues/get_moves_queue.go
  pkg/gen/ghcapi/ghcoperations/queues/get_moves_queue_parameters.go
  pkg/gen/ghcapi/ghcoperations/queues/get_moves_queue_responses.go
  pkg/gen/ghcapi/ghcoperations/queues/get_moves_queue_urlbuilder.go
  pkg/gen/ghcmessages/g_b_l_o_c.go
  pkg/gen/ghcmessages/queue_move.go
  pkg/gen/ghcmessages/queue_move_status.go
  pkg/gen/ghcmessages/queue_moves.go
  pkg/gen/ghcmessages/queue_moves_result.go
  pkg/handlers/apitests.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/queues.go
  pkg/handlers/ghcapi/queues_test.go
  pkg/services/move_order/move_order_fetcher.go
  pkg/services/office_user/office_user_creator_test.go
  pkg/services/office_user/office_user_fetcher.go
  pkg/services/office_user/office_user_fetcher_test.go
  swagger/ghc.yaml
Labels: ttv

#4957 [MB-4571] TOO moves queues new office page
  src/pages/Office/MoveQueue/MoveQueue.jsx
  src/pages/Office/MoveQueue/MoveQueue.module.scss
  src/pages/Office/MoveQueue/MoveQueue.test.jsx
  src/pages/Office/index.jsx
Labels: ttv

#4958 [MB-4517 and MB-3904] Select NTS move
  cypress/integration/mymove/hhg.js
  cypress/integration/mymove/nts.js
  cypress/integration/mymove/utilities/customer.js
  src/components/Customer/SelectableCard.module.scss
  src/pages/MyMove/NTSSetup.jsx
  src/pages/MyMove/SelectMoveType.jsx
  src/pages/MyMove/SelectMoveType.module.scss
  src/pages/MyMove/SelectMoveType.test.jsx
  src/scenes/MyMove/getWorkflowRoutes.jsx
Labels: Pamplemoose

#4970 check for mto referenceID
  pkg/services/invoice/ghc_payment_request_invoice_generator.go
Labels: A-Team

#4972 removed todo comment
  pkg/services/invoice/ghc_payment_request_invoice_generator.go
Labels: A-Team

#4969 [mb-4572] Integrate TOO move queue UI component with moves queue api
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/queue_move.go
  pkg/gen/ghcmessages/queue_moves_result.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/queues.go
  pkg/handlers/ghcapi/queues_test.go
  pkg/services/move_order/move_order_fetcher.go
  src/components/Table/Table.jsx
  src/components/Table/Table.test.jsx
  src/constants/departmentIndicators.js
  src/constants/queryKeys.js
  src/hooks/queries.js
  src/hooks/queries.test.js
  src/pages/Office/MoveQueue/MoveQueue.jsx
  src/pages/Office/MoveQueue/MoveQueue.module.scss
  src/pages/Office/MoveQueue/MoveQueue.test.jsx
  src/services/ghcApi.js
  src/shared/Entities/schema.js
  src/shared/formatters.js
  swagger/ghc.yaml
Labels: ttv

#4960 MB-4425 edits to MoveOrderFetcher Tests and ListMoveOrders
  pkg/handlers/ghcapi/move_order_test.go
  pkg/handlers/ghcapi/move_orders.go
  pkg/services/move_order/move_order_fetcher_test.go
  pkg/testdatagen/make_office_user.go
Labels: ttv

#4984 MB-4625 Fix 500 error TOO queue
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
Labels: ttv

#4982 [MB-3962] Change validation keys for Pop models
  pkg/models/electronic_orders_revision_test.go
  pkg/models/fuel_eia_diesel_price_test.go
  pkg/models/mto_service_item_customer_contacts_test.go
  pkg/models/mto_service_item_dimensions_test.go
  pkg/models/payment_service_item_test.go
  pkg/models/re_domestic_service_area_test.go
  pkg/models/tariff400ng_service_area_test.go
Labels: A-Team

#4946 [MB-4529] MyMove API data load
  jsconfig.json
  src/pages/MyMove/HHGShipmentSetup.jsx
  src/pages/MyMove/Home/index.jsx
  src/sagas/index.js
  src/sagas/onboarding.js
  src/sagas/onboarding.test.js
  src/scenes/MyMove/index.jsx
  src/scenes/ServiceMembers/ducks.js
  src/scenes/ServiceMembers/ducks.test.js
  src/services/ghcApi.js
  src/services/internalApi.js
  src/services/swaggerRequest.js
  src/services/swaggerRequest.test.js
  src/shared/store.js
  src/store/onboarding/actions.js
Labels: moose

#4995 MB-4599 MTOShipment Counts Column
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/queues_test.go
  pkg/testdatagen/scenario/e2ebasic.go
Labels: ttv

#4997 [MB-4601] Initial TIO payment request queue component with routing
  src/pages/Office/PaymentRequestQueue/PaymentRequestQueue.jsx
  src/pages/Office/PaymentRequestQueue/PaymentRequestQueue.module.scss
  src/pages/Office/PaymentRequestQueue/PaymentRequestQueue.test.jsx
  src/pages/Office/index.jsx
Labels: ttv

#5008 [MB-4751] fix g62 validation
  pkg/edi/segment/g62.go
Labels: A-Team

#4992 [MB-4225] capture per segment
  pkg/edi/segment/per.go
  pkg/edi/segment/per_test.go
  pkg/services/invoice/ghc_payment_request_invoice_generator.go
  pkg/services/invoice/ghc_payment_request_invoice_generator_test.go
Labels: A-Team

#4994 [MB-4612] Write a CLI tool to upload a file to Syncada via SFTP
  Makefile
  cmd/generate-payment-request-edi/main.go
  cmd/send-to-gex/main.go
  cmd/send-to-syncada-via-sftp/logger.go
  cmd/send-to-syncada-via-sftp/main.go
  go.mod
  go.sum
  new_payment_request.json
  pkg/cli/syncada_sftp.go
  sample_edi.txt
Labels: A-Team, wip

#5020 [MB-3963] Change comparison of Postgres error strings to error codes
  cmd/model-vet/main.go
  go.mod
  go.sum
  pkg/db/dberr/dberr_test.go
  pkg/db/dberr/errors.go
  pkg/db/dberr/errors_test.go
  pkg/handlers/errors.go
  pkg/migrate/prepareCopyFromStdin_test.go
  pkg/models/address.go
  pkg/models/errors.go
  pkg/models/fuel_eia_diesel_price_test.go
  pkg/models/move.go
  pkg/models/prime_upload_test.go
  pkg/models/transportation_service_provider_performance.go
  pkg/models/user_test.go
  pkg/models/user_upload_test.go
  pkg/services/accesscode/access_code_claimer_test.go
  pkg/services/dbtools/table_from_slice_creator_test.go
  pkg/services/ghcimport/import_re_contract_years_test.go
  pkg/services/ghcimport/import_re_domestic_accessorial_prices_test.go
  pkg/services/ghcimport/import_re_domestic_linehaul_prices_test.go
  pkg/services/ghcimport/import_re_domestic_other_prices_test.go
  pkg/services/ghcimport/import_re_domestic_service_area_prices_test.go
  pkg/services/ghcimport/import_re_intl_accessorial_prices_test.go
  pkg/services/ghcimport/import_re_intl_other_prices_test.go
  pkg/services/ghcimport/import_re_intl_prices_test.go
  pkg/services/ghcimport/import_re_rate_area.go
  pkg/services/ghcimport/import_re_shipment_type_prices_test.go
  pkg/services/ghcimport/import_re_task_order_fees_test.go
  pkg/services/ghcrateengine/domestic_destination_pricer_test.go
  pkg/services/ghcrateengine/domestic_origin_pricer_test.go
  pkg/services/ghcrateengine/domestic_pack_pricer_test.go
  pkg/services/ghcrateengine/domestic_shorthaul_pricer_test.go
  pkg/services/ghcrateengine/domestic_unpack_pricer_test.go
  pkg/services/invoice/invoice_upload_updater_test.go
  pkg/services/mto_service_item/mto_service_item_updater.go
  pkg/services/mto_shipment/mto_shipment_address_updater.go
  pkg/services/mto_shipment/mto_shipment_updater.go
  pkg/services/payment_request/payment_request_fetcher_test.go
  pkg/services/payment_request/payment_request_status_updater.go
Labels: A-Team

#5005 [MB-4620] Multiple NTS validation
  pkg/services/mto_shipment/mto_shipment_creator.go
  pkg/services/mto_shipment/mto_shipment_creator_test.go
  pkg/testdatagen/make_mto_shipment.go
Labels: Pamplemoose

#5022 MB-4602 TIO queue hook up react query
  cypress/integration/office/txo/tooFlows.js
  pkg/testdatagen/scenario/e2ebasic.go
  src/constants/paymentRequestStatus.js
  src/constants/queryKeys.js
  src/hooks/queries.js
  src/hooks/queries.test.js
  src/pages/Office/PaymentRequestQueue/PaymentRequestQueue.jsx
  src/pages/Office/PaymentRequestQueue/PaymentRequestQueue.test.jsx
  src/services/ghcApi.js
  src/shared/Entities/schema.js
  src/shared/formatters.js
  src/shared/formatters.test.js
Labels: ttv

#4950 MB-3109, MB-4542, MB-4543 | refactor create hhg form & create new nts(r) forms
  cypress/integration/mymove/hhg.js
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/create_shipment.go
  pkg/gen/internalmessages/selected_move_type.go
  pkg/models/move.go
  pkg/models/mto_shipments.go
  pkg/services/mto_shipment/mto_shipment_creator.go
  src/components/Customer/HHGDetailsForm.jsx
  src/components/Customer/HHGDetailsForm.stories.jsx
  src/components/Customer/HHGDetailsForm.test.jsx
  src/components/Customer/MtoShipmentForm/MtoShipmentForm.jsx
  src/components/Customer/MtoShipmentForm/MtoShipmentForm.module.scss
  src/components/Customer/MtoShipmentForm/MtoShipmentForm.stories.jsx
  src/components/Customer/MtoShipmentForm/MtoShipmentForm.test.jsx
  src/components/Customer/MtoShipmentForm/validationSchemas.js
  src/components/Office/RequestedShipments/RequestedShipments.jsx
  src/components/Office/RequestedShipments/RequestedShipments.stories.jsx
  src/components/Office/ShipmentContainer.test.jsx
  src/components/Office/ShipmentDisplay/ShipmentDisplay.stories.jsx
  src/pages/MyMove/CreateOrEditMtoShipment.jsx
  src/pages/MyMove/CreateOrEditMtoShipment.test.jsx
  src/pages/MyMove/HHGShipmentSetup.jsx
  src/pages/MyMove/NTSSetup.jsx
  src/pages/MyMove/SelectMoveType.jsx
  src/pages/MyMove/SelectMoveType.test.jsx
  src/scenes/MyMove/getWorkflowRoutes.jsx
  src/scenes/MyMove/index.jsx
  src/shared/constants.js
  src/types/address.js
  src/types/customerShapes.js
  src/types/shipment.js
  src/utils/formatMtoShipment.js
  src/utils/formatMtoShipment.test.js
  swagger/internal.yaml
Labels: Pamplemoose, moose

#5047 [MB-4863] Add finish later button on review page
  cypress/integration/mymove/hhg.js
  src/pages/MyMove/Review/index.jsx
  src/scenes/Review/Review.jsx
Labels: Pamplemoose

#5050 [one line change] fix delivery address bug
  src/components/Customer/MtoShipmentForm/MtoShipmentForm.jsx
Labels: Pamplemoose, bug, moose

#5041 MB-4750 Correct validation errors in ISA segment of EDI
  pkg/edi/segment/isa_test.go
  pkg/services/invoice/ghc_payment_request_invoice_generator.go
  pkg/services/invoice/ghc_payment_request_invoice_generator_test.go
Labels: A-Team

#5049 Update script to check for latest aws-vault
  scripts/check-aws-vault-version
Labels: A-Team

#5039 [MB-4868] Remove host key requirement from send to Syncada via SFTP command line utility
  cmd/send-to-syncada-via-sftp/main.go
Labels: A-Team

#5038 [MB-3968] Get lib/pq working again under Pop 5.x
  go.mod
  go.sum
  pkg/db/dberr/errors.go
  pkg/db/dberr/errors_test.go
  pkg/handlers/errors.go
  pkg/testingsuite/pop_suite.go
Labels: A-Team

#5048 [MB-4524] Job Runner: Approved Payment Request Fetcher
  pkg/services/mocks/PaymentRequestReviewedFetcher.go
  pkg/services/payment_request.go
  pkg/services/payment_request/payment_request_reviewed_fetcher.go
  pkg/services/payment_request/payment_request_reviewed_fetcher_test.go
Labels: A-Team

#5042 MB-3020 & MB-4569 | edit NTS/NTS-R shipments
  cypress/integration/mymove/hhg.js
  src/components/Customer/EditShipment.jsx
  src/components/Customer/EditShipment.module.scss
  src/components/Customer/EditShipment.stories.jsx
  src/components/Customer/EditShipment.test.jsx
  src/components/Customer/MtoShipmentForm/MtoShipmentForm.jsx
  src/components/Customer/MtoShipmentForm/MtoShipmentForm.module.scss
  src/components/Customer/MtoShipmentForm/MtoShipmentForm.stories.jsx
  src/components/Customer/MtoShipmentForm/MtoShipmentForm.test.jsx
  src/components/Customer/MtoShipmentForm/MtoShipmentFormFields.jsx
  src/components/Customer/MtoShipmentForm/getShipmentOptions.js
  src/components/form/AddressFields/AddressFields.jsx
  src/components/form/ContactInfoFields/ContactInfoFields.jsx
  src/pages/MyMove/CreateOrEditMtoShipment.jsx
  src/pages/MyMove/CreateOrEditMtoShipment.test.jsx
  src/pages/MyMove/Home/index.jsx
  src/pages/MyMove/index.module.scss
  src/scenes/MyMove/getWorkflowRoutes.jsx
  src/scenes/MyMove/getWorkflowRoutes.test.js
  src/scenes/MyMove/index.jsx
  src/types/customerShapes.js
  src/utils/formatMtoShipment.js
  src/utils/formatMtoShipment.test.js
Labels: Pamplemoose, moose

#5062 MB-4564 Step Component Number Alignment + Home Page Header Full Bleed Background
  src/components/Customer/Home/Step/Step.module.scss
  src/pages/MyMove/Home/index.jsx
Labels: Pamplemoose

#5075 [MB-4570 and MB-4568] Route Edit NTS/NTS-R Shipment
  cypress/integration/mymove/hhg.js
  cypress/integration/mymove/nts.js
  cypress/integration/mymove/ntsr.js
  src/components/Customer/Home/Step/Step.test.jsx
  src/components/Customer/Home/Step/index.jsx
  src/components/Customer/MtoShipmentForm/MtoShipmentForm.jsx
  src/components/Customer/Review/ShipmentCard/NTSRShipmentCard/index.jsx
  src/components/Customer/Review/ShipmentCard/NTSShipmentCard/index.jsx
  src/components/Customer/Review/ShipmentCard/ShipmentCard.stories.jsx
  src/components/Customer/Review/Summary/index.jsx
  src/components/Customer/Review/Summary/index.test.jsx
  src/pages/MyMove/Home/index.jsx
  src/pages/MyMove/SelectMoveType.jsx
Labels: Pamplemoose

#5074 [MB-4557] added addl error handling into support api
  pkg/gen/supportapi/embedded_spec.go
  pkg/gen/supportapi/supportoperations/payment_request/get_payment_request_e_d_i_responses.go
  pkg/gen/supportclient/payment_request/get_payment_request_e_d_i_responses.go
  pkg/handlers/supportapi/payment_request.go
  pkg/handlers/supportapi/payment_request_test.go
  swagger/support.yaml
Labels: A-Team

#5077 MB-4845 TOO queue can filter status
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/queues/get_moves_queue_parameters.go
  pkg/gen/ghcapi/ghcoperations/queues/get_moves_queue_urlbuilder.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/queues.go
  pkg/handlers/ghcapi/queues_test.go
  pkg/services/move_order/move_order_fetcher.go
  swagger/ghc.yaml
Labels: ttv

#5076 mb-4886 | migrate selected move type nts raw value
  README.md
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20201023202845_update_selectedMoveType_NTS.up.sql
Labels: Pamplemoose, moose

#5108 minor tweak: don't send delivery address in API call when customer clears their delivery address info.
  src/components/Customer/MtoShipmentForm/MtoShipmentForm.jsx
Labels: Pamplemoose, moose

#5116 fix nts-r logic hole
  pkg/services/mto_shipment/mto_shipment_creator.go
Labels: Pamplemoose, moose

#5129 MB-4973 customer info & Date submitted filters for TIO - backend
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/queues/get_payment_requests_queue_parameters.go
  pkg/gen/ghcapi/ghcoperations/queues/get_payment_requests_queue_urlbuilder.go
  pkg/handlers/ghcapi/queues.go
  pkg/handlers/ghcapi/queues_test.go
  swagger/ghc.yaml
Labels: ttv

#5090 MB-4869 Enable validation of EDI during its generation
  cmd/generate-payment-request-edi/main.go
  go.mod
  go.sum
  pkg/edi/invoice/generator.go
  pkg/edi/invoice/generator_test.go
  pkg/edi/segment/bx.go
  pkg/edi/segment/bx_test.go
  pkg/edi/segment/g62.go
  pkg/edi/segment/g62_test.go
  pkg/edi/segment/gs.go
  pkg/edi/segment/gs_test.go
  pkg/edi/segment/hl.go
  pkg/edi/segment/hl_test.go
  pkg/edi/segment/isa.go
  pkg/edi/segment/isa_test.go
  pkg/edi/segment/l0.go
  pkg/edi/segment/l0_test.go
  pkg/edi/segment/l3.go
  pkg/edi/segment/l3_test.go
  pkg/edi/segment/n1.go
  pkg/edi/segment/n1_test.go
  pkg/edi/segment/n9.go
  pkg/edi/segment/n9_test.go
  pkg/edi/segment/segment_test.go
  pkg/edi/segment/validators.go
  pkg/handlers/supportapi/payment_request.go
  pkg/models/address.go
  pkg/models/address_test.go
  pkg/services/invoice/ghc_payment_request_invoice_generator.go
  pkg/services/invoice/ghc_payment_request_invoice_generator_test.go
  pkg/tools/tools.go
Labels: A-Team
