Repository transcom/mymove, pull requests merged in 2020-04, with the labels that each got.

#3854 Adding shauna keating's cac migration
  migrations/app/migrations_manifest.txt
  migrations/app/secure/20200327154306_shauna_cac.up.sql
Labels: roci

#3869 MB-1319 Create MTO Service Item Dom. Crating Uncrating
  cmd/prime-api-client/create_mto_service_item.go
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20200323215437_mto_service_items_add_dimensions.up.sql
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/dimension_type.go
  pkg/gen/primemessages/m_t_o_service_item.go
  pkg/gen/primemessages/m_t_o_service_item_dimension.go
  pkg/gen/primemessages/m_t_o_service_item_domestic_crating.go
  pkg/gen/primemessages/m_t_o_service_item_model_type.go
  pkg/handlers/primeapi/internal/payloads/model_to_payload.go
  pkg/handlers/primeapi/internal/payloads/payload_to_model.go
  pkg/handlers/primeapi/move_task_order.go
  pkg/handlers/primeapi/move_task_order_test.go
  pkg/handlers/primeapi/mto_service_item.go
  pkg/handlers/primeapi/mto_service_item_test.go
  pkg/models/mto_service_item_dimensions.go
  pkg/models/mto_service_item_dimensions_test.go
  pkg/models/mto_service_items.go
  pkg/models/validators.go
  pkg/models/validators_test.go
  pkg/services/mto_service_item/mto_service_item_creator.go
  pkg/services/mto_service_item/mto_service_item_creator_test.go
  pkg/testdatagen/make_mto_service_item_dimension.go
  pkg/testdatagen/shared.go
  pkg/unit/thousandth_inches.go
  pkg/unit/thousandth_inches_test.go
  swagger/prime.yaml
Labels: ttv

#3880 MB-2231 enable danger circleci job
  .circleci/config.yml
  dangerfile.ts
Labels: A-Team

#3845 [MB-1388] Imported 2020 400ng data; fixed some migrator issues
  .spelling
  docs/data/tariff400ng-yearly-import.md
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20200325144739_fix_service_area_for_zip_629.up.sql
  migrations/app/schema/20200325145334_import_2020_400ng.up.sql
  pkg/migrate/Exec_test.go
  pkg/migrate/SplitStatements.go
  pkg/migrate/SplitStatements_test.go
  pkg/migrate/fixtures/copyFromStdinMultiple.sql
  pkg/migrate/migrate.go
  pkg/migrate/migrate_test.go
Labels: A-Team

#3871 MB-2092 Add Request and Panic logging to Prime api calls
  cmd/milmove/serve.go
  pkg/middleware/recovery.go
  pkg/middleware/request_logger.go
Labels: roci

#3870 MB-57 new form conventions samples
  .loki/reference/chrome_iphone7_Samples_Form_personal_info.png
  .loki/reference/chrome_laptop_Samples_Form_personal_info.png
  package.json
  src/components/form/ErrorMessage.jsx
  src/components/form/ErrorMessage.test.jsx
  src/components/form/Form.jsx
  src/components/form/Form.test.jsx
  src/components/form/fields/TextInput.jsx
  src/components/form/fields/TextInput.test.jsx
  src/components/form/fields/index.js
  src/components/form/index.js
  src/stories/samples.stories.jsx
  yarn.lock
Labels: A-Team

#3897 [MB-1889] Changed nullability on tariff400ng_full_unpack_rates columns
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20200408212210_change_nullability_in_tariff400ng_full_unpack_rates.up.sql
  pkg/models/tariff400ng_full_unpack_rate.go
  pkg/models/tariff400ng_full_unpack_rate_test.go
Labels: A-Team

#3898 [MB-1890] Changed nullability on tariff400ng_linehaul_rates columns
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20200408215659_change_nullability_in_tariff400ng_linehaul_rates.up.sql
  pkg/models/tariff400ng_linehaul_rate.go
  pkg/models/tariff400ng_linehaul_rate_test.go
Labels: A-Team

#3904 [MB-1891] Changed nullability of some columns in tariff400ng_service_areas
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20200409151333_change_nullability_in_tariff400ng_service_area.up.sql
  pkg/models/tariff400ng_linehaul_rate_test.go
  pkg/models/tariff400ng_service_area.go
  pkg/models/tariff400ng_service_area_test.go
  pkg/rateengine/linehaul_test.go
  pkg/rateengine/nonlinehaul_test.go
  pkg/testdatagen/scenario/estimate.go
Labels: A-Team

#3900 MB-1318 Prime create service item domestic destination 1st day SIT
  cmd/prime-api-client/create_mto_service_item.go
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20200406200751_support_destination_first_day_sit.up.sql
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/customer_contact_type.go
  pkg/gen/primemessages/m_t_o_service_item.go
  pkg/gen/primemessages/m_t_o_service_item_d_d_f_s_i_t.go
  pkg/gen/primemessages/m_t_o_service_item_domestic_crating.go
  pkg/gen/primemessages/m_t_o_service_item_model_type.go
  pkg/handlers/primeapi/internal/payloads/model_to_payload.go
  pkg/handlers/primeapi/internal/payloads/payload_to_model.go
  pkg/handlers/primeapi/move_task_order.go
  pkg/handlers/primeapi/move_task_order_test.go
  pkg/handlers/primeapi/mto_service_item.go
  pkg/handlers/primeapi/mto_service_item_test.go
  pkg/models/mto_service_item_customer_contacts.go
  pkg/models/mto_service_item_customer_contacts_test.go
  pkg/models/mto_service_items.go
  pkg/services/mto_service_item/mto_service_item_creator.go
  pkg/services/mto_service_item/mto_service_item_creator_test.go
  pkg/services/query/query_builder.go
  pkg/services/query/query_builder_test.go
  pkg/testdatagen/make_mto_service_item_customer_contact.go
  pkg/testdatagen/shared.go
  swagger/prime.yaml
Labels: ttv

#3896 remove unused function setPendingPpmWeight: MB-292
  src/scenes/Moves/Ppm/ducks.js
Labels: moose

#3918 MB-2269 Add contract_id column to re_zip5_rate_areas table
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20200410162529_add_contract_id_to_re_zip5_rate_areas_table.up.sql
  pkg/models/re_zip5_rate_areas.go
  pkg/models/re_zip5_rate_areas_test.go
Labels: A-Team

#3907 MB-2244 Add shuttle service to prime api client
  cmd/prime-api-client/create_mto_service_item.go
Labels: ttv

#3921 [MB-1893] Changed nullability of some columns in tariff400ng_zip3s
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20200413185502_change_nullability_in_tariff400ng_zip3s.up.sql
  pkg/models/tariff400ng_zip3_test.go
Labels: A-Team

#3911 MB-1892 Fix Tariff400ngShortHaulRate to pass Model Vet
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20200410194345_change_nullability_in_tariff400ng_shorthaul_rate.up.sql
  pkg/models/tariff400ng_shorthaul_rate.go
  pkg/models/tariff400ng_shorthaul_rate_test.go
Labels: A-Team

#3919 MB-2149 Skeleton TOO accessorials page
  src/pages/TOO/accessorials.jsx
  src/pages/TOO/accessorials.test.jsx
  src/scenes/Office/index.jsx
Labels: ttv

#3932 [MB-1777] Added create-payment-request command to prime-api-client
  cmd/prime-api-client/create_payment_request.go
  cmd/prime-api-client/main.go
  pkg/testdatagen/scenario/e2ebasic.go
Labels: A-Team

#3864 Invalid input error when adding an MTO Agent
  pkg/services/mto_shipment/mto_shipment_updater.go
Labels: roci

#3909 [MB-2117] Get individual MTO endpoint for Support API
  cmd/prime-api-client/get_mto.go
  cmd/prime-api-client/main.go
  pkg/gen/supportapi/configure_mymove.go
  pkg/gen/supportapi/embedded_spec.go
  pkg/gen/supportapi/supportoperations/move_task_order/get_move_task_order.go
  pkg/gen/supportapi/supportoperations/move_task_order/get_move_task_order_parameters.go
  pkg/gen/supportapi/supportoperations/move_task_order/get_move_task_order_responses.go
  pkg/gen/supportapi/supportoperations/move_task_order/get_move_task_order_urlbuilder.go
  pkg/gen/supportapi/supportoperations/mymove_api.go
  pkg/gen/supportclient/move_task_order/get_move_task_order_parameters.go
  pkg/gen/supportclient/move_task_order/get_move_task_order_responses.go
  pkg/gen/supportclient/move_task_order/move_task_order_client.go
  pkg/handlers/supportapi/api.go
  pkg/handlers/supportapi/move_task_order.go
  pkg/handlers/supportapi/move_task_order_test.go
  swagger/support.yaml
Labels: roci

#3952 [MB-2256] Added standalone crating service items
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20200420154249_add_crating_standalone.up.sql
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/m_t_o_service_item_domestic_crating.go
  pkg/gen/primemessages/re_service_code.go
  pkg/models/re_service.go
  pkg/services/ghcimport/fixtures/re_services_data.sql
  pkg/services/ghcimport/import_re_domestic_accessorial_prices.go
  pkg/services/ghcimport/import_re_domestic_accessorial_prices_test.go
  pkg/services/ghcimport/import_re_intl_accessorial_prices.go
  pkg/services/ghcimport/import_re_intl_accessorial_prices_test.go
  swagger/prime.yaml
Labels: A-Team

#3927 MB-2104 Shipment Container and Heading components for TOO
  .loki/reference/chrome_iphone7_TOO_TIO_Components_ShipmentContainer_ShipmentHeading_Shipment_Heading.png
  .loki/reference/chrome_iphone7_TOO_TIO_Components_ShipmentContainer_Shipment_Container.png
  .loki/reference/chrome_iphone7_TOO_TIO_Components_ShipmentHeading_Shipment_Heading.png
  .loki/reference/chrome_laptop_TOO_TIO_Components_ShipmentContainer_ShipmentHeading_Shipment_Heading.png
  .loki/reference/chrome_laptop_TOO_TIO_Components_ShipmentContainer_Shipment_Container.png
  .loki/reference/chrome_laptop_TOO_TIO_Components_ShipmentHeading_Shipment_Heading.png
  src/components/Office/ShipmentContainer.jsx
  src/components/Office/ShipmentContainer.test.jsx
  src/components/Office/ShipmentHeading.jsx
  src/components/Office/ShipmentHeading.test.jsx
  src/components/Office/shipmentContainer.module.scss
  src/components/Office/shipmentHeading.module.scss
  src/stories/shipmentContainer.stories.jsx
  src/stories/shipmentheading.stories.jsx
Labels: ttv

#3955 MB-2238 add required delivery date to shipments
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/m_t_o_shipment.go
  pkg/handlers/primeapi/internal/payloads/model_to_payload.go
  pkg/handlers/primeapi/internal/payloads/payload_to_model.go
  pkg/testdatagen/make_mto_shipment.go
  swagger/prime.yaml
Labels: roci

#3973 [MB-1894] Changed nullability of some columns in tariff400ng_zip5_rate_areas
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20200422184129_change_nullability_in_tariff400ng_zip5_rate_areas.up.sql
  pkg/models/tariff400ng_zip5_rate_area.go
  pkg/models/tariff400ng_zip5_rate_area_test.go
Labels: A-Team

#3963 MB-2091 Merge storybook test and build and fix failure in cirlce ci
  .circleci/config.yml
  Dockerfile.storybook
  Dockerfile.storybook_local
  Makefile
  scripts/start-storybook-tests
Labels: A-Team

#3951 MB-2437 Add ADR 0045 to eliminate nesting parent IDs in swagger paths
  docs/README.md
  docs/adr/0045-nesting-swagger-paths.md
  docs/adr/index.md
Labels: roci

#3948 [MB-1996] Add placeholder values and comments to envrc.local.template
  .envrc
  .envrc.local.template
  .pre-commit-config.yaml
Labels: roci

#3895 MB-1969 Connect Contractor ID to Move Task Order
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20200407152204_add_contractor_fkey_to_move_task_orders.up.sql
  pkg/models/contractor.go
  pkg/models/contractor_test.go
  pkg/models/contracts_test.go
  pkg/models/move_task_order.go
  pkg/models/move_task_order_test.go
  pkg/services/converthelper/convert.go
  pkg/services/converthelper/convert_test.go
  pkg/services/move_task_order/move_task_order_creator_test.go
  pkg/testdatagen/constants.go
  pkg/testdatagen/make_contractor.go
  pkg/testdatagen/make_move_task_order.go
Labels: A-Team

#3991 MB-2360 Admin sorting woes
  src/scenes/SystemAdmin/AccessCodes/AccessCodeList.jsx
  src/scenes/SystemAdmin/Moves/MoveList.jsx
  src/scenes/SystemAdmin/shared/rest_provider.js
Labels: ttv

#3953 MB-2111 TOO customer remarks agent details
  .loki/reference/chrome_iphone7_Components_Containers_all.png
  .loki/reference/chrome_iphone7_Components_Left_Nav_layout.png
  .loki/reference/chrome_iphone7_Components_Tables_Standard_Tables.png
  .loki/reference/chrome_iphone7_Components_Tables_Table_Elements.png
  .loki/reference/chrome_iphone7_Samples_Form_personal_info.png
  .loki/reference/chrome_iphone7_TOO_TIO_Components_CustomerRemarksAgentsDetails_with_details.png
  .loki/reference/chrome_iphone7_TOO_TIO_Components_CustomerRemarksAgentsDetails_with_no_details.png
  .loki/reference/chrome_iphone7_TOO_TIO_Components_ShipmentContainer_ShipmentHeading_Shipment_Heading.png
  .loki/reference/chrome_iphone7_TOO_TIO_Components_ShipmentContainer_Shipment_Container.png
  .loki/reference/chrome_laptop_Components_Containers_all.png
  .loki/reference/chrome_laptop_Components_Left_Nav_layout.png
  .loki/reference/chrome_laptop_Components_Tables_Standard_Tables.png
  .loki/reference/chrome_laptop_Components_Tables_Table_Elements.png
  .loki/reference/chrome_laptop_Samples_Form_personal_info.png
  .loki/reference/chrome_laptop_TOO_TIO_Components_CustomerRemarksAgentsDetails_with_details.png
  .loki/reference/chrome_laptop_TOO_TIO_Components_CustomerRemarksAgentsDetails_with_no_details.png
  .loki/reference/chrome_laptop_TOO_TIO_Components_ShipmentContainer_ShipmentHeading_Shipment_Heading.png
  .loki/reference/chrome_laptop_TOO_TIO_Components_ShipmentContainer_Shipment_Container.png
  src/components/.eslintrc
  src/components/CustomerRemarksAgentsDetails/index.jsx
  src/components/CustomerRemarksAgentsDetails/index.test.jsx
  src/components/DataPoint/index.jsx
  src/components/DataPoint/index.test.jsx
  src/shared/styles/_custom.scss
  src/stories/customerRemarksAgentsDetails.stories.jsx
  src/stories/tables.stories.jsx
Labels: ttv

#3993 MB-2257 Prime create mto service item domestic crating stand alone
  pkg/handlers/primeapi/internal/payloads/model_to_payload.go
  pkg/handlers/primeapi/mto_service_item_test.go
  pkg/services/mto_service_item/mto_service_item_creator.go
Labels: ttv

#3997 [MB-2115] Add post-counseling-info endpoint to prime-api-client
  cmd/prime-api-client/main.go
  cmd/prime-api-client/update_post_counseling_info.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/move_task_order/update_m_t_o_post_counseling_information.go
  pkg/gen/primeclient/move_task_order/update_m_t_o_post_counseling_information_responses.go
  swagger/prime.yaml
Labels: roci

#3943 Kim mb 1045 payment request errors
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/payment_requests/create_payment_request_responses.go
  pkg/gen/primeclient/payment_requests/create_payment_request_responses.go
  pkg/handlers/errors.go
  pkg/handlers/primeapi/internal/payloads/model_to_payload.go
  pkg/handlers/primeapi/payment_request.go
  pkg/handlers/primeapi/payment_request_test.go
  pkg/services/errors.go
  pkg/services/payment_request/payment_request_creator.go
  pkg/services/payment_request/payment_request_creator_test.go
  swagger/prime.yaml
Labels: roci

#4008 MB-2336 Move details page placeholder
  src/pages/TOO/moveDetails.jsx
  src/pages/TOO/moveDetails.test.jsx
  src/scenes/Office/index.jsx
Labels: ttv

#3992 [MB-2113] Add CreateMoveTaskOrder support endpoint
  cmd/prime-api-client/create_move_task_order.go
  cmd/prime-api-client/main.go
  pkg/gen/supportapi/configure_mymove.go
  pkg/gen/supportapi/embedded_spec.go
  pkg/gen/supportapi/supportoperations/move_task_order/create_move_task_order.go
  pkg/gen/supportapi/supportoperations/move_task_order/create_move_task_order_parameters.go
  pkg/gen/supportapi/supportoperations/move_task_order/create_move_task_order_responses.go
  pkg/gen/supportapi/supportoperations/move_task_order/create_move_task_order_urlbuilder.go
  pkg/gen/supportapi/supportoperations/move_task_order/get_move_task_order_responses.go
  pkg/gen/supportapi/supportoperations/move_task_order/update_move_task_order_status_responses.go
  pkg/gen/supportapi/supportoperations/mymove_api.go
  pkg/gen/supportclient/move_task_order/create_move_task_order_parameters.go
  pkg/gen/supportclient/move_task_order/create_move_task_order_responses.go
  pkg/gen/supportclient/move_task_order/get_move_task_order_responses.go
  pkg/gen/supportclient/move_task_order/move_task_order_client.go
  pkg/gen/supportclient/move_task_order/update_move_task_order_status_responses.go
  pkg/gen/supportmessages/customer.go
  pkg/gen/supportmessages/entitlement.go
  pkg/gen/supportmessages/entitlements.go
  pkg/gen/supportmessages/move_order.go
  pkg/gen/supportmessages/move_task_order.go
  pkg/handlers/supportapi/api.go
  pkg/handlers/supportapi/internal/payloads/model_to_payload.go
  pkg/handlers/supportapi/internal/payloads/payload_to_model.go
  pkg/handlers/supportapi/move_task_order.go
  pkg/handlers/supportapi/move_task_order_test.go
  pkg/services/errors.go
  swagger/support.yaml
Labels: roci

#3941 MB-2108 Important shipment dates component
  .loki/reference/chrome_iphone7_Global_Typography_Headers.png
  .loki/reference/chrome_iphone7_TOO_TIO_Components_ImportantShipmentDates_default.png
  .loki/reference/chrome_laptop_TOO_TIO_Components_ImportantShipmentDates_default.png
  src/components/Office/ImportantShipmentDates.jsx
  src/components/Office/ImportantShipmentDates.test.jsx
  src/components/Office/importantShipmentDates.module.scss
  src/pages/TOO/moveTaskOrder.jsx
  src/stories/importantShipmentDates.stories.jsx
Labels: ttv

#4022 MB-2495 Clarify endpoints are support and not production
  pkg/gen/supportapi/doc.go
  pkg/gen/supportapi/embedded_spec.go
  pkg/gen/supportapi/supportoperations/move_task_order/create_move_task_order.go
  pkg/gen/supportapi/supportoperations/move_task_order/get_move_task_order.go
  pkg/gen/supportapi/supportoperations/move_task_order/update_move_task_order_status.go
  pkg/gen/supportapi/supportoperations/move_task_order/update_move_task_order_status_responses.go
  pkg/gen/supportapi/supportoperations/mto_service_item/update_m_t_o_service_item_status.go
  pkg/gen/supportapi/supportoperations/mto_service_item/update_m_t_o_service_item_status_responses.go
  pkg/gen/supportapi/supportoperations/mto_shipment/patch_m_t_o_shipment_status.go
  pkg/gen/supportapi/supportoperations/mto_shipment/patch_m_t_o_shipment_status_responses.go
  pkg/gen/supportapi/supportoperations/mymove_api.go
  pkg/gen/supportapi/supportoperations/payment_requests/update_payment_request_status.go
  pkg/gen/supportapi/supportoperations/payment_requests/update_payment_request_status_responses.go
  pkg/gen/supportclient/move_task_order/move_task_order_client.go
  pkg/gen/supportclient/move_task_order/update_move_task_order_status_responses.go
  pkg/gen/supportclient/mto_service_item/mto_service_item_client.go
  pkg/gen/supportclient/mto_service_item/update_m_t_o_service_item_status_responses.go
  pkg/gen/supportclient/mto_shipment/mto_shipment_client.go
  pkg/gen/supportclient/mto_shipment/patch_m_t_o_shipment_status_responses.go
  pkg/gen/supportclient/payment_requests/payment_requests_client.go
  pkg/gen/supportclient/payment_requests/update_payment_request_status_responses.go
  pkg/gen/supportmessages/update_payment_request_status.go
  swagger/support.yaml
Labels: roci
