Repository transcom/mymove, pull requests merged in 2020-02, with the labels that each got.

#3463 Add move locator to rate engine log messages
  cmd/generate-shipment-summary/main.go
  pkg/handlers/internalapi/moves.go
  pkg/handlers/internalapi/personally_procured_move.go
  pkg/handlers/internalapi/personally_procured_move_estimate.go
  pkg/handlers/internalapi/personally_procured_move_estimate_test.go
  pkg/handlers/internalapi/personally_procured_move_incentive.go
  pkg/handlers/internalapi/personally_procured_move_incentive_test.go
  pkg/handlers/internalapi/personally_procured_move_sit_estimate.go
  pkg/handlers/internalapi/personally_procured_move_sit_estimate_test.go
  pkg/models/estimate_helper.go
  pkg/models/move.go
  pkg/rateengine/linehaul.go
  pkg/rateengine/linehaul_test.go
  pkg/rateengine/nonlinehaul.go
  pkg/rateengine/nonlinehaul_test.go
  pkg/rateengine/rateengine.go
  pkg/rateengine/rateengine_test.go
Labels: ppm

#3401 JM MB-506 save pricing params
  pkg/handlers/primeapi/payment_request.go
  pkg/models/payment_service_item.go
  pkg/models/payment_service_item_test.go
  pkg/models/service_param.go
  pkg/payment_request/payment_request_helper.go
  pkg/payment_request/payment_request_helper_test.go
  pkg/payment_request/service_param_list_fetcher.go
  pkg/payment_request/service_param_list_valid.go
  pkg/payment_request/service_param_list_valid_test.go
  pkg/payment_request/service_param_value_lookups/distance_zip3_lookup.go
  pkg/payment_request/service_param_value_lookups/requested_pickup_date_lookup.go
  pkg/payment_request/service_param_value_lookups/service_area_origin_lookup.go
  pkg/payment_request/service_param_value_lookups/service_param_value_lookups.go
  pkg/payment_request/service_param_value_lookups/weight_actual_lookup.go
  pkg/payment_request/service_param_value_lookups/weight_billed_actual_lookup.go
  pkg/payment_request/service_param_value_lookups/weight_estimated_lookup.go
  pkg/payment_request/service_param_value_lookups/zip_dest_address_lookup.go
  pkg/payment_request/service_param_value_lookups/zip_pickup_address_lookup.go
  pkg/services/payment_request/payment_request_creator.go
  pkg/services/payment_request/payment_request_creator_test.go
  pkg/testdatagen/make_service_param.go
  pkg/testdatagen/shared.go
Labels: A-Team

#3452 Initial implementation of database and model field checker.
  Makefile
  cmd/model-vet/main.go
Labels: roci

#3480 Copy more values over to move order and expand test coverage.
  pkg/models/convert.go
  pkg/models/convert_test.go
  pkg/services/move_order/move_order_fetcher.go
  src/scenes/Office/TOO/customerDetails.jsx
Labels: roci

#3476 MB-604 Prime updates actual shipment weight
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/m_t_o_shipment.go
  pkg/services/mto_shipment/mto_shipment_updater.go
  pkg/services/mto_shipment/mto_shipment_updater_test.go
  swagger/prime.yaml
Labels: roci

#3490 MB-1324 Add project overview to README
  .spelling
  README.md
Labels: roci

#3438 Jm mb 506 part2 zero down migration
  README.md
  migrations/20200131173648_remove-service_id-from-payment_service_item.up.sql
  migrations_manifest.txt
  pkg/services/payment_request/payment_request_creator.go
Labels: A-Team

#3504 Show mto shipments when fetching MTOs
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeclient/mto_shipment/mto_shipment_client.go
  pkg/gen/primemessages/move_task_order.go
  pkg/handlers/primeapi/internal/payloads/model_to_payload.go
  pkg/handlers/primeapi/move_task_order.go
  pkg/handlers/primeapi/move_task_order_test.go
  pkg/models/move_task_order.go
  pkg/testdatagen/scenario/e2ebasic.go
  swagger/prime.yaml
Labels: roci

#3503 send correct move submitted email: MB-1328
  pkg/notifications/move_submitted.go
Labels: ppm

#3510 Weight entitlement shows base weight: MB-1230
  cypress/integration/mymove/orders.js
  cypress/integration/mymove/ppm.js
  src/scenes/Landing/MoveSummary.jsx
Labels: ppm

#3502 use originalMoveDate for incentive calc on ssw: MB-1520
  pkg/paperwork/shipment_summary.go
  pkg/paperwork/shipment_summary_test.go
Labels: ppm

#3499 MB-1139 TOO approve reject shipments
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20200203200715_mto_shipments_add_rejection_reason.up.sql
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/mto_shipment/patch_m_t_o_shipment_status_responses.go
  pkg/gen/ghcmessages/m_t_o_shipment.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/mto_shipment.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/models/mto_shipments.go
  pkg/services/mto_shipment/mto_shipment_status_updater.go
  pkg/services/mto_shipment/mto_shipment_status_updater_test.go
  pkg/services/query/query_builder.go
  pkg/testdatagen/make_mto_shipment.go
  src/scenes/Office/TOO/customerDetails.jsx
  src/shared/ApproveRejectModal/index.jsx
  src/shared/ApproveRejectModal/index.test.js
  src/shared/Entities/modules/mtoShipments.js
  swagger/ghc.yaml
Labels: ttv

#3505 Fix bugs w/ incentive estimate calculation: MB-1231/MB-1520
  src/scenes/Landing/MoveSummary.jsx
  src/scenes/Moves/Ppm/PaymentReview/index.jsx
  src/scenes/Review/PPMShipmentSummary.jsx
Labels: ppm

#3538 Add actual_move_date and original_move_date to queues payload
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/move_queue_item.go
  pkg/handlers/internalapi/move_queue_items.go
  pkg/models/queue.go
  swagger/internal.yaml
Labels: ppm

#3498 MB-478 import verification check
  .spelling
  cmd/ghc-pricing-parser/main.go
  docs/data/ghc-pricing-import.md
Labels: A-Team

#3529 Remove unused prime api endpoints
  pkg/gen/primeapi/configure_mymove.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/move_task_order/get_prime_entitlements.go
  pkg/gen/primeapi/primeoperations/move_task_order/get_prime_entitlements_parameters.go
  pkg/gen/primeapi/primeoperations/move_task_order/get_prime_entitlements_responses.go
  pkg/gen/primeapi/primeoperations/move_task_order/get_prime_entitlements_urlbuilder.go
  pkg/gen/primeapi/primeoperations/move_task_order/update_move_task_order_actual_weight.go
  pkg/gen/primeapi/primeoperations/move_task_order/update_move_task_order_actual_weight_parameters.go
  pkg/gen/primeapi/primeoperations/move_task_order/update_move_task_order_actual_weight_responses.go
  pkg/gen/primeapi/primeoperations/move_task_order/update_move_task_order_actual_weight_urlbuilder.go
  pkg/gen/primeapi/primeoperations/move_task_order/update_move_task_order_destination_address.go
  pkg/gen/primeapi/primeoperations/move_task_order/update_move_task_order_destination_address_parameters.go
  pkg/gen/primeapi/primeoperations/move_task_order/update_move_task_order_destination_address_responses.go
  pkg/gen/primeapi/primeoperations/move_task_order/update_move_task_order_destination_address_urlbuilder.go
  pkg/gen/primeapi/primeoperations/move_task_order/update_move_task_order_estimated_weight.go
  pkg/gen/primeapi/primeoperations/move_task_order/update_move_task_order_estimated_weight_parameters.go
  pkg/gen/primeapi/primeoperations/move_task_order/update_move_task_order_estimated_weight_responses.go
  pkg/gen/primeapi/primeoperations/move_task_order/update_move_task_order_estimated_weight_urlbuilder.go
  pkg/gen/primeapi/primeoperations/mymove_api.go
  pkg/gen/primeclient/move_task_order/get_prime_entitlements_parameters.go
  pkg/gen/primeclient/move_task_order/get_prime_entitlements_responses.go
  pkg/gen/primeclient/move_task_order/move_task_order_client.go
  pkg/gen/primeclient/move_task_order/update_move_task_order_actual_weight_parameters.go
  pkg/gen/primeclient/move_task_order/update_move_task_order_actual_weight_responses.go
  pkg/gen/primeclient/move_task_order/update_move_task_order_destination_address_parameters.go
  pkg/gen/primeclient/move_task_order/update_move_task_order_destination_address_responses.go
  pkg/gen/primeclient/move_task_order/update_move_task_order_estimated_weight_parameters.go
  pkg/gen/primeclient/move_task_order/update_move_task_order_estimated_weight_responses.go
  swagger/prime.yaml
Labels: roci

#3547 Add contract_id to rate engine reference tables
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20200212153937_add_contract_id_to_re_ref_tables.up.sql
  pkg/models/re_domestic_service_area.go
  pkg/models/re_domestic_service_area_test.go
  pkg/models/re_rate_area.go
  pkg/models/re_rate_area_test.go
  pkg/models/re_zip3s.go
  pkg/models/re_zip3s_test.go
  pkg/services/ghcimport/ghc_rateengine_importer_test.go
  pkg/services/ghcimport/import_re_contract_years_test.go
  pkg/services/ghcimport/import_re_domestic_linehaul_prices_test.go
  pkg/services/ghcimport/import_re_domestic_service_area.go
  pkg/services/ghcimport/import_re_domestic_service_area_prices_test.go
  pkg/services/ghcimport/import_re_domestic_service_area_test.go
  pkg/services/ghcimport/import_re_intl_other_prices_test.go
  pkg/services/ghcimport/import_re_intl_prices_test.go
  pkg/services/ghcimport/import_re_rate_area.go
  pkg/services/ghcimport/import_re_rate_area_test.go
  pkg/services/ghcimport/import_re_shipment_type_prices_test.go
  pkg/services/ghcimport/import_re_task_order_fees_test.go
  pkg/services/ghcrateengine/domestic_linehaul_pricer_test.go
  pkg/services/ghcrateengine/domestic_service_area_pricer_test.go
  pkg/services/ghcrateengine/domestic_shorthaul_pricer_test.go
  pkg/testdatagen/make_re_domestic_service_area.go
Labels: A-Team

#3558 Remove SQL Injections w/i MTO Shipment Updater
  pkg/services/mto_shipment/mto_shipment_updater.go
  pkg/services/mto_shipment/mto_shipment_updater_test.go
Labels: roci

#3515 Remove first estimate page under progearChanges feature flag
  cypress/integration/mymove/ppm.js
  src/scenes/Moves/Ppm/ducks.js
  src/scenes/MyMove/getWorkflowRoutes.jsx
  src/scenes/MyMove/index.jsx
Labels: ppm

#3561 MB-1634 john cac access to dev exp stg
  docs/how-to/use-mtls-with-cac.md
  migrations/app/migrations_manifest.txt
  migrations/app/secure/20200217200526_gidjin_cac.up.sql
Labels: A-Team

#3554 MB-58 Document component organization
  .storybook/config.js
  docs/frontend.md
  src/README.md
  src/config/.eslintrc
  src/constants/.eslintrc
  src/containers/.eslintrc
  src/helpers/.eslintrc
  src/layout/.eslintrc
  src/pages/.eslintrc
  src/stories/.eslintrc
  src/stories/dateAndLocation.stories.js
  src/stories/index.stories.jsx
  src/stories/statusTimeLine.stories.jsx
Labels: A-Team

#3546 MB-1410 Add First Available Delivery Date to db and shipments endpoint
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20200211232054_add_fadd_to_mto_shipments.up.sql
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/m_t_o_shipment.go
  pkg/models/mto_shipments.go
  pkg/services/mto_shipment/mto_shipment_updater.go
  pkg/services/mto_shipment/mto_shipment_updater_test.go
  swagger/prime.yaml
Labels: roci

#3563 Jm mb 1250 zip2rate models
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20200214175204_create_re_zip5_rate_areas_table.up.sql
  pkg/models/re_zip3s.go
  pkg/models/re_zip5_rate_areas.go
  pkg/models/re_zip5_rate_areas_test.go
Labels: A-Team

#3565 Add @trussworks/react-uswds module
  package.json
  yarn.lock
Labels: A-Team

#3575 Remove gidjin from db owners group
  .github/CODEOWNERS
Labels: A-Team

#3580 Add Reggie's CAC to staging/experimental
  docs/how-to/use-mtls-with-cac.md
  migrations/app/migrations_manifest.txt
  migrations/app/secure/20200219185845_rriser_cac.up.sql
Labels: A-Team

#3574 Update logging for payment reminder emails
  cmd/milmove-tasks/send_payment_reminder_email.go
  pkg/notifications/move_payment_reminder.go
  pkg/notifications/move_payment_reminder_test.go
Labels: ppm

#3532 MB-601: update shipments endpoint estimated weight
  migrations/app/migrations_manifest.txt
  migrations/app/secure/20200211184638_add_approved_date_to_mto_shipments.up.sql
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/m_t_o_shipment.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/mto_shipment/update_m_t_o_shipment_responses.go
  pkg/gen/primeclient/mto_shipment/update_m_t_o_shipment_responses.go
  pkg/gen/primemessages/m_t_o_shipment.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/primeapi/internal/payloads/model_to_payload.go
  pkg/handlers/primeapi/mto_shipment.go
  pkg/handlers/primeapi/mto_shipment_test.go
  pkg/models/mto_shipments.go
  pkg/services/mto_shipment/mto_shipment_status_updater.go
  pkg/services/mto_shipment/mto_shipment_status_updater_test.go
  pkg/services/mto_shipment/mto_shipment_updater.go
  pkg/services/mto_shipment/mto_shipment_updater_test.go
  pkg/testdatagen/make_mto_shipment.go
  swagger/ghc.yaml
  swagger/prime.yaml
Labels: roci

#3590 Put add_approved_date_to_mto_shipments migration in correct folder.
  migrations/app/schema/20200211184638_add_approved_date_to_mto_shipments.up.sql
Labels: roci

#3562 MB-1530: Modify update shipments endpoint so that there are no required fields
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/m_t_o_shipment.go
  pkg/handlers/primeapi/internal/payloads/model_to_payload.go
  pkg/handlers/primeapi/internal/payloads/payload_to_model.go
  pkg/handlers/primeapi/mto_shipment.go
  pkg/services/mocks/MTOShipmentUpdater.go
  pkg/services/mto_shipment.go
  pkg/services/mto_shipment/mto_shipment_updater.go
  pkg/services/mto_shipment/mto_shipment_updater_test.go
  swagger/prime.yaml
Labels: roci

#3596 Fix payload to model and model to payload for mto shipments
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/m_t_o_shipment.go
  pkg/handlers/primeapi/internal/payloads/model_to_payload.go
  pkg/handlers/primeapi/internal/payloads/payload_to_model.go
  pkg/handlers/primeapi/mto_shipment_test.go
  swagger/prime.yaml
Labels: roci

#3595 Refactor import verification check
  cmd/ghc-pricing-parser/main.go
  docs/data/ghc-pricing-import.md
  pkg/services/ghcimport/ghc_rateengine_importer.go
  pkg/services/ghcimport/import_re_contract.go
  pkg/services/ghcimport/import_re_contract_test.go
  pkg/services/ghcimport/import_re_contract_years.go
  pkg/services/ghcimport/import_re_domestic_accessorial_prices.go
  pkg/services/ghcimport/import_re_domestic_linehaul_prices.go
  pkg/services/ghcimport/import_re_domestic_other_prices.go
  pkg/services/ghcimport/import_re_domestic_other_prices_test.go
  pkg/services/ghcimport/import_re_domestic_service_area.go
  pkg/services/ghcimport/import_re_domestic_service_area_prices.go
  pkg/services/ghcimport/import_re_domestic_service_area_prices_test.go
  pkg/services/ghcimport/import_re_intl_accessorial_prices.go
  pkg/services/ghcimport/import_re_intl_other_prices.go
  pkg/services/ghcimport/import_re_intl_prices.go
  pkg/services/ghcimport/import_re_rate_area.go
  pkg/services/ghcimport/import_re_shipment_type_prices.go
Labels: A-Team

#3523 Add ReferenceID to MTO
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20200224175606_update-mto-reference-id-constraints-and-backfill-existing.up.sql
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/customer/get_all_customer_moves.go
  pkg/gen/ghcapi/ghcoperations/customer/get_all_customer_moves_parameters.go
  pkg/gen/ghcapi/ghcoperations/customer/get_all_customer_moves_responses.go
  pkg/gen/ghcapi/ghcoperations/customer/get_all_customer_moves_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/ghcmessages/customer_move_item.go
  pkg/gen/ghcmessages/customer_move_items.go
  pkg/gen/ghcmessages/move_task_order.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/move_task_order.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/move_task_order_test.go
  pkg/models/move_task_order.go
  pkg/models/move_task_order_test.go
  pkg/services/move_task_order/move_task_order_fetcher_test.go
  pkg/testdatagen/make_move_task_order.go
  src/scenes/Office/TOO/customerDetails.jsx
  swagger/ghc.yaml
  swagger/prime.yaml
Labels: roci

#3599 Fix payment reminder email bugs (nil, add moveLocator): MB-1716
  pkg/assets/assets.go
  pkg/notifications/move_payment_reminder.go
  pkg/notifications/move_payment_reminder_test.go
  pkg/notifications/templates/move_payment_reminder_template.html
  pkg/notifications/templates/move_payment_reminder_template.txt
Labels: moose

#3616 Add moveLocator to email and logs and modify logging: MB-1747
  pkg/assets/assets.go
  pkg/notifications/move_submitted.go
  pkg/notifications/templates/move_submitted_template.html
  pkg/notifications/templates/move_submitted_template.txt
Labels: moose

#3570 MB-1384 Migration to add domestic transit times
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20200218231559_create_insert_ghc_domestic_transit_times.up.sql
Labels: ttv

#3589 Fix typo in access-global-variables.md
  docs/how-to/access-global-variables.md
Labels: moose

#3621 Add lynzt cac to staging/experimental
  migrations/app/migrations_manifest.txt
  migrations/app/secure/20200225133755_lynzt_cac.up.sql
Labels: moose

#3602 MB-1473: Expand payload for Prime ListMTOs
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20200219223252_add_lines_of_accounting_to_move_orders.up.sql
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/customer.go
  pkg/gen/primemessages/move_order.go
  pkg/gen/primemessages/move_task_order.go
  pkg/handlers/primeapi/internal/payloads/model_to_payload.go
  pkg/handlers/primeapi/move_task_order.go
  pkg/models/convert.go
  pkg/models/move_order.go
  pkg/models/move_task_order.go
  pkg/services/mto_shipment/mto_shipment_updater.go
  pkg/testdatagen/make_move_order.go
  pkg/testdatagen/scenario/e2ebasic.go
  swagger/prime.yaml
Labels: roci

#3615 Show incentive range after ppm move approved: MB-1231
  src/scenes/Landing/MoveSummary/PpmMoveDetails.jsx
Labels: moose

#3629 Revert "MB-1473: Expand payload for Prime ListMTOs"
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20200219223252_add_lines_of_accounting_to_move_orders.up.sql
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/customer.go
  pkg/gen/primemessages/move_order.go
  pkg/gen/primemessages/move_task_order.go
  pkg/handlers/primeapi/internal/payloads/model_to_payload.go
  pkg/handlers/primeapi/move_task_order.go
  pkg/models/convert.go
  pkg/models/move_order.go
  pkg/models/move_task_order.go
  pkg/services/mto_shipment/mto_shipment_updater.go
  pkg/testdatagen/make_move_order.go
  pkg/testdatagen/scenario/e2ebasic.go
  swagger/prime.yaml
Labels: roci

#3638 jacqueline cac migration
  migrations/app/migrations_manifest.txt
  migrations/app/secure/20200226211945_jacquelinemckinney_cac.up.sql
Labels: A-Team

#3630 MB-1531 Fix GHC pricing parser SQL in tests
  pkg/services/ghcimport/fixtures/20191101201107_create-re-services-table-with-values.up.sql
  pkg/services/ghcimport/fixtures/20191126160639_update-and-add-values-for-reservices-table.up.sql
  pkg/services/ghcimport/fixtures/re_services_data.sql
  pkg/services/ghcimport/ghc_rateengine_importer_test.go
Labels: A-Team

#3637 MB-1408 Slim down payload for updating shipment status.
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/mto_shipment/patch_m_t_o_shipment_status_parameters.go
  pkg/gen/ghcmessages/patch_m_t_o_shipment_status_payload.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  swagger/ghc.yaml
Labels: ttv

#3609 MB-603 submit actual pickup date
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20200208013050_add_actual_pickup_date_to_mto_shipments.up.sql
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/m_t_o_shipment.go
  pkg/handlers/primeapi/internal/payloads/model_to_payload.go
  pkg/handlers/primeapi/internal/payloads/payload_to_model.go
  pkg/models/mto_shipments.go
  pkg/services/mto_shipment/mto_shipment_updater.go
  pkg/services/mto_shipment/mto_shipment_updater_test.go
  swagger/prime.yaml
Labels: roci

#3631 Refactor logging in GHC pricing parser
  cmd/ghc-pricing-parser/logger.go
  cmd/ghc-pricing-parser/main.go
  docs/data/ghc-pricing-import.md
  pkg/models/stage_pricing.go
  pkg/parser/pricing/parse.go
  pkg/parser/pricing/parse_access_and_add_prices.go
  pkg/parser/pricing/parse_access_and_add_prices_test.go
  pkg/parser/pricing/parse_domestic_linehaul_prices.go
  pkg/parser/pricing/parse_domestic_linehaul_prices_test.go
  pkg/parser/pricing/parse_domestic_other_prices.go
  pkg/parser/pricing/parse_domestic_other_prices_test.go
  pkg/parser/pricing/parse_domestic_service_area_prices.go
  pkg/parser/pricing/parse_domestic_service_area_prices_test.go
  pkg/parser/pricing/parse_international_prices.go
  pkg/parser/pricing/parse_international_prices_test.go
  pkg/parser/pricing/parse_management_counseling_transition_prices.go
  pkg/parser/pricing/parse_management_counseling_transition_prices_test.go
  pkg/parser/pricing/parse_nonstandard_location_prices.go
  pkg/parser/pricing/parse_nonstandard_location_prices_test.go
  pkg/parser/pricing/parse_other_intl_prices.go
  pkg/parser/pricing/parse_other_intl_prices_test.go
  pkg/parser/pricing/parse_price_escalation_discount.go
  pkg/parser/pricing/parse_price_escalation_discount_test.go
  pkg/parser/pricing/parse_service_areas.go
  pkg/parser/pricing/parse_service_areas_test.go
  pkg/parser/pricing/parse_test.go
  pkg/parser/pricing/shared.go
  pkg/services/ghcimport/ghc_rateengine_importer_test.go
  pkg/services/ghcimport/import_re_domestic_accessorial_prices.go
  pkg/services/ghcimport/import_re_intl_accessorial_prices.go
  pkg/services/ghcimport/import_re_rate_area_test.go
  pkg/services/ghcimport/import_re_shipment_type_prices.go
Labels: A-Team

#3643 Fix missing incentive range values not showing: MB-1231
  src/scenes/Landing/MoveSummary/PpmMoveDetails.jsx
  src/scenes/Landing/MoveSummary/SubmittedPpmMoveDetails.jsx
  src/shared/incentive.js
  src/shared/incentive.test.js
Labels: moose

#3640 remove progear flag: MB-1402
  cypress/integration/mymove/ppm.js
  src/scenes/Moves/Ppm/Weight.jsx
  src/scenes/Moves/Ppm/Weight.module.scss
  src/scenes/Moves/Ppm/Weight.test.js
  src/scenes/MyMove/getWorkflowRoutes.jsx
  src/scenes/MyMove/getWorkflowRoutes.test.js
  src/scenes/Orders/Orders.jsx
  src/scenes/Review/EditOrders.jsx
  src/shared/featureFlags.js
Labels: moose

#3644 MB-1473.1: Expand payload for Prime ListMTO with lines_of_accounting as nullable
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20200219223252_add_lines_of_accounting_to_move_orders.up.sql
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/customer.go
  pkg/gen/primemessages/move_order.go
  pkg/gen/primemessages/move_task_order.go
  pkg/handlers/primeapi/internal/payloads/model_to_payload.go
  pkg/handlers/primeapi/move_task_order.go
  pkg/models/convert.go
  pkg/models/move_order.go
  pkg/models/move_task_order.go
  pkg/testdatagen/make_move_order.go
  pkg/testdatagen/scenario/e2ebasic.go
  swagger/prime.yaml
Labels: roci
