Repository transcom/mymove, pull requests merged in 2020-12, with the labels that each got.

#5379 [MB-5716] Resolve approve MTO Shipment promises inside approve MTO callback
  src/components/Office/RequestedShipments/RequestedShipments.jsx
Labels: ttv

#5370 Update chamber, aws cli, and opensc version checks
  scripts/check-aws-cli-version
  scripts/check-chamber-version
  scripts/check-opensc-version
Labels: A-Team

#5368 MB-5593 | gosec G402: annotate all remaining g402s
  cmd/prime-api-client/utils/connection.go
  cmd/webhook-client/utils/connection.go
Labels: Pamplemoose, moose

#5374 [MB-5732] Create static approved fake data file
  pkg/fakedata_approved/fakedata_approved.go
  pkg/fakedata_approved/fakedata_approved_test.go
  pkg/fakedata_approved/fakedata_test.go
  pkg/fakedata_approved/logger.go
Labels: A-Team

#5325 [MB 5474] set sent to gex timestamp in ProcessReviewedPaymentRequest service
  pkg/services/payment_request/payment_request_reviewed_processor.go
  pkg/services/payment_request/payment_request_reviewed_processor_test.go
Labels: A-Team

#5384 MB-5744 remediation g106 ssh host key violation
  cmd/send-to-syncada-via-sftp/main.go
  pkg/cli/syncada_sftp.go
  pkg/services/invoice/syncada_sftp_sender.go
  pkg/services/invoice/syncada_sftp_sender_test.go
  pkg/testdatagen/scenario/devseed.go
Labels: A-Team, Pamplemoose

#5392 MB-5590 Add UpdateMTOServiceItem service object
  pkg/handlers/primeapi/mto_agent.go
  pkg/services/mocks/MTOAgentUpdater.go
  pkg/services/mocks/MTOServiceItemUpdater.go
  pkg/services/mocks/OfficeUserFetcherPop.go
  pkg/services/mto_agent.go
  pkg/services/mto_agent/mto_agent_updater.go
  pkg/services/mto_agent/mto_agent_updater_test.go
  pkg/services/mto_agent/mto_agent_validators.go
  pkg/services/mto_agent/mto_agent_validators_test.go
  pkg/services/mto_service_item.go
  pkg/services/mto_service_item/mto_service_item_creator_test.go
  pkg/services/mto_service_item/mto_service_item_updater.go
  pkg/services/mto_service_item/mto_service_item_updater_test.go
  pkg/services/mto_service_item/mto_service_item_validators.go
  pkg/services/mto_service_item/mto_service_item_validators_test.go
Labels: roci

#5334 Ignore dangerjs if acceptable rule
  dangerfile.ts
Labels: Pamplemoose

#5408 [MB-5594] Add Updatemtoserviceitem handler
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/mto_service_item/update_m_t_o_service_item.go
  pkg/gen/primeapi/primeoperations/mto_service_item/update_m_t_o_service_item_responses.go
  pkg/gen/primeapi/primeoperations/mymove_api.go
  pkg/gen/primeclient/mto_service_item/mto_service_item_client.go
  pkg/gen/primeclient/mto_service_item/update_m_t_o_service_item_responses.go
  pkg/handlers/primeapi/api.go
  pkg/handlers/primeapi/mto_service_item.go
  pkg/handlers/primeapi/mto_service_item_test.go
  pkg/handlers/primeapi/payloads/model_to_payload.go
  pkg/handlers/primeapi/payloads/payload_to_model.go
  pkg/services/errors.go
  swagger/prime.yaml
Labels: roci

#5381 create getSeverity function
  cmd/webhook-client/webhook/webhook.go
  cmd/webhook-client/webhook/webhook_test.go
Labels: roci

#5382 MB-5723 Allow log level to be configurable
  .envrc
  Dockerfile
  Dockerfile.local
  Makefile
  cmd/compare-secure-migrations/main.go
  cmd/ecs-deploy/put_target.go
  cmd/ecs-deploy/task_def.go
  cmd/find-guardduty-user/main.go
  cmd/generate-payment-request-edi/main.go
  cmd/generate-shipment-summary/main.go
  cmd/generate-test-data/main.go
  cmd/generate_access_codes/main.go
  cmd/ghc-pricing-parser/main.go
  cmd/ghc-transit-time-parser/main.go
  cmd/milmove-tasks/post_file_to_gex.go
  cmd/milmove-tasks/save_ghc_fuel_price_data.go
  cmd/milmove-tasks/send_payment_reminder_email.go
  cmd/milmove-tasks/send_post_move_survey_email.go
  cmd/milmove/gen_duty_stations_migration.go
  cmd/milmove/main_test.go
  cmd/milmove/migrate.go
  cmd/milmove/serve.go
  cmd/model-vet/main.go
  cmd/prime-api-client/main.go
  cmd/prime-api-client/utils/connection.go
  cmd/prime-api-client/utils/shared.go
  cmd/prime-api-dev/main.go
  cmd/query-lb-logs/main.go
  cmd/send-to-gex/main.go
  cmd/send-to-syncada-via-sftp/main.go
  cmd/webhook-client/command_test.go
  cmd/webhook-client/main.go
  cmd/webhook-client/utils/connection.go
  cmd/webhook-client/webhook/webhook_test.go
  config/env/exp.app-client-tls.env
  config/env/exp.app.env
  config/env/prd.app-client-tls.env
  config/env/prd.app.env
  config/env/stg.app-client-tls.env
  config/env/stg.app.env
  pkg/certs/certs_test.go
  pkg/cli/cli_test.go
  pkg/cli/logging.go
  pkg/cli/verbose.go
  pkg/cli/verbose_test.go
  pkg/logging/log.go
Labels: security, ttv

#5409 [MB-3630] Review service items button on Payment Request cards
  cypress/integration/office/txo/tioFlows.js
  src/components/Office/PaymentRequestCard/PaymentRequestCard.jsx
  src/components/Office/PaymentRequestCard/PaymentRequestCard.module.scss
  src/components/Office/PaymentRequestCard/PaymentRequestCard.stories.jsx
  src/components/Office/PaymentRequestCard/PaymentRequestCard.test.jsx
  src/pages/Office/MovePaymentRequests/MovePaymentRequests.jsx
  src/pages/Office/PaymentRequestReview/PaymentRequestReview.jsx
Labels: ttv

#5398 [MB-5727] Prime API Client Command - update-mto-service-item
  cmd/prime-api-client/main.go
  cmd/prime-api-client/prime/update_mto_service_item.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/mto_service_item/update_m_t_o_service_item_parameters.go
  swagger/prime.yaml
Labels: roci

#5388 Major version update of cypress to 6.0.0
  cypress/integration/mymove/hhg.js
  cypress/integration/mymove/ppm.js
  cypress/integration/mymove/ppmCloseout.js
  cypress/integration/office/homepage.js
  cypress/integration/office/officeUserPPM.js
  cypress/integration/office/txo/tioFlows.js
  cypress/integration/office/txo/tooFlows.js
  cypress/package.json
  cypress/support/commands.js
  cypress/yarn.lock
  package.json
  yarn.lock
Labels: Pamplemoose

#5400 MB-5263 Enable CreateMTOServiceItemHandler to use new SIT codes
  cmd/prime-api-client/prime/create_mto_service_item.go
  docs/adr/0045-nesting-swagger-paths.md
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/mto_service_item/create_m_t_o_service_item.go
  pkg/gen/primeclient/mto_service_item/mto_service_item_client.go
  pkg/gen/primemessages/m_t_o_service_item.go
  pkg/gen/primemessages/m_t_o_service_item_dest_s_i_t.go
  pkg/gen/primemessages/m_t_o_service_item_model_type.go
  pkg/gen/primemessages/m_t_o_service_item_origin_s_i_t.go
  pkg/gen/supportapi/embedded_spec.go
  pkg/gen/supportmessages/m_t_o_service_item_model_type.go
  pkg/handlers/primeapi/move_task_order_test.go
  pkg/handlers/primeapi/mto_service_item.go
  pkg/handlers/primeapi/mto_service_item_test.go
  pkg/handlers/primeapi/mto_shipment_test.go
  pkg/handlers/primeapi/payloads/model_to_payload.go
  pkg/handlers/primeapi/payloads/payload_to_model.go
  pkg/services/event/notification_test.go
  pkg/services/mto_service_item/mto_service_item_creator.go
  pkg/services/mto_service_item/mto_service_item_creator_test.go
  swagger/prime.yaml
  swagger/support.yaml
Labels: roci

#5397 [MB-5654] Create a service to hide fake data
  pkg/fakedata_approved/fakedata_approved.go
  pkg/fakedata_approved/fakedata_approved_test.go
  pkg/services/mocks/MoveTaskOrderHider.go
  pkg/services/move_task_order.go
  pkg/services/move_task_order/export_test.go
  pkg/services/move_task_order/move_task_order_checker_test.go
  pkg/services/move_task_order/move_task_order_creator_test.go
  pkg/services/move_task_order/move_task_order_hide_non_fake.go
  pkg/services/move_task_order/move_task_order_hide_non_fake_test.go
Labels: A-Team

#5432 [MB-5797] Add migration to create zip3_distances table
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20201207223002_create_zip3_distances.up.sql
Labels: A-Team

#5395 [MB-5588 // MB-5656 // MB-5657] Add an endpoint that call service to check MTOs against fake data
  pkg/gen/supportapi/configure_mymove.go
  pkg/gen/supportapi/embedded_spec.go
  pkg/gen/supportapi/supportoperations/move_task_order/hide_non_fake_move_task_orders.go
  pkg/gen/supportapi/supportoperations/move_task_order/hide_non_fake_move_task_orders_parameters.go
  pkg/gen/supportapi/supportoperations/move_task_order/hide_non_fake_move_task_orders_responses.go
  pkg/gen/supportapi/supportoperations/move_task_order/hide_non_fake_move_task_orders_urlbuilder.go
  pkg/gen/supportapi/supportoperations/mymove_api.go
  pkg/gen/supportclient/move_task_order/hide_non_fake_move_task_orders_parameters.go
  pkg/gen/supportclient/move_task_order/hide_non_fake_move_task_orders_responses.go
  pkg/gen/supportclient/move_task_order/move_task_order_client.go
  pkg/handlers/supportapi/api.go
  pkg/handlers/supportapi/move_task_order.go
  pkg/handlers/supportapi/move_task_order_test.go
  pkg/services/move_task_order.go
  swagger/support.yaml
Labels: A-Team

#5441 [MB-5887] Fix switch case statements for payment request card reviewed statuses
  src/components/Office/PaymentRequestCard/PaymentRequestCard.jsx
  src/components/Office/PaymentRequestCard/PaymentRequestCard.test.jsx
Labels: ttv

#5444 Create MoveDocument in createPPMWithAdvance scenario
  pkg/testdatagen/scenario/devseed.go
Labels: roci

#5436 [MB-4635] Display allowances in move allowances sidebar component
  src/components/Office/AllowancesDetailForm/AllowancesDetailForm.jsx
  src/components/Office/AllowancesDetailForm/AllowancesDetailForm.module.scss
  src/components/Office/AllowancesDetailForm/AllowancesDetailForm.stories.jsx
  src/components/Office/AllowancesDetailForm/AllowancesDetailForm.test.jsx
  src/components/Office/AllowancesTable/AllowancesTable.jsx
  src/components/Office/AllowancesTable/AllowancesTable.test.jsx
  src/components/Office/MoveDetailTable.module.scss
  src/pages/Office/MoveAllowances/MoveAllowances.jsx
  src/pages/Office/MoveAllowances/MoveAllowances.test.jsx
  src/shared/formatters.js
  src/shared/formatters.test.js
Labels: ttv

#5445 MB-5714 MB-5848 MB-5849 MB-5850 Pass the ICNSequencer down to the EDI generator
  cmd/generate-payment-request-edi/main.go
  pkg/handlers/supportapi/api.go
  pkg/handlers/supportapi/payment_request.go
  pkg/handlers/supportapi/payment_request_test.go
  pkg/services/invoice/ghc_payment_request_invoice_generator.go
  pkg/services/invoice/ghc_payment_request_invoice_generator_test.go
  pkg/services/payment_request/payment_request_reviewed_processor.go
  pkg/services/payment_request/payment_request_reviewed_processor_test.go
  pkg/services/payment_request/payment_request_service_test.go
Labels: A-Team

#5439 MB-4638 Storybook allowances viewer form authorized weight
  package.json
  src/components/Office/AllowancesDetailForm/AllowancesDetailForm.jsx
  src/components/Office/AllowancesDetailForm/AllowancesDetailForm.module.scss
  src/components/Office/AllowancesDetailForm/AllowancesDetailForm.stories.jsx
  src/components/Office/AllowancesDetailForm/AllowancesDetailForm.test.jsx
  src/components/form/fields/TextInput.jsx
  src/components/form/fields/TextInput.test.jsx
  src/pages/Office/MoveAllowances/MoveAllowances.jsx
  src/pages/Office/MoveOrders/MoveOrders.module.scss
  yarn.lock
Labels: ttv

#5449 Sc mb 5065 notifications severity alerts
  cmd/webhook-client/db_webhook_notify.go
  cmd/webhook-client/webhook/webhook.go
  cmd/webhook-client/webhook/webhook_test.go
Labels: roci

#5448 [MB-5912] Payment request card storybook happo relative date fix
  src/components/Office/PaymentRequestCard/PaymentRequestCard.stories.jsx
  src/components/Office/RejectServiceItemModal/RejectServiceItemModal.stories.jsx
  src/components/Office/RequestedServiceItemsTable/RequestedServiceItemsTable.stories.jsx
  src/stories/tables.stories.jsx
Labels: ttv

#5437 [MB-5737] add cli to hide mtos
  cmd/prime-api-client/main.go
  cmd/prime-api-client/support/hide_non_fake_move_task_orders.go
  cypress/yarn.lock
  pkg/gen/supportapi/embedded_spec.go
  pkg/gen/supportapi/supportoperations/move_task_order/hide_non_fake_move_task_orders_responses.go
  pkg/gen/supportclient/move_task_order/hide_non_fake_move_task_orders_responses.go
  pkg/handlers/supportapi/move_task_order.go
  pkg/handlers/supportapi/move_task_order_test.go
  swagger/support.yaml
Labels: A-Team

#5446 [MB-5532] Replace Qualifying BadDataError with ConflictError in the GHC EDI Generator
  pkg/gen/supportapi/embedded_spec.go
  pkg/gen/supportapi/supportoperations/payment_request/get_payment_request_e_d_i_responses.go
  pkg/gen/supportclient/payment_request/get_payment_request_e_d_i_responses.go
  pkg/handlers/supportapi/payment_request.go
  pkg/handlers/supportapi/payment_request_test.go
  pkg/services/invoice/ghc_payment_request_invoice_generator.go
  swagger/support.yaml
Labels: A-Team

#5474 [MB-5453] update error handling for send to syncada
  pkg/handlers/supportapi/payment_request.go
  pkg/handlers/supportapi/payment_request_test.go
  pkg/payment_request/send_to_syncada.go
  pkg/services/payment_request/payment_request_reviewed_processor.go
  pkg/services/payment_request/payment_request_reviewed_processor_test.go
Labels: A-Team

#5488 Roc mb-5846 edit authorized weight
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/update_move_order_payload.go
  pkg/handlers/ghcapi/move_order_test.go
  pkg/handlers/ghcapi/move_orders.go
  pkg/services/move_order/move_order_updater.go
  swagger/ghc.yaml
Labels: ttv

#5502 Remove moose ownership of circleci config
  .github/CODEOWNERS
Labels: Pamplemoose

#5482 [MB-5972] Minor cleanup rename test function
  pkg/fakedata_approved/fakedata_approved_test.go
  pkg/services/move_task_order/move_task_order_hide_non_fake.go
Labels: A-Team

#5501 [MB-4584, MB-5940, MB-5941, MB-5942] Adds skeleton for GHC planner
  cmd/milmove/serve.go
  pkg/handlers/contexts.go
  pkg/handlers/mocks/HandlerContext.go
  pkg/route/ghc_planner.go
  pkg/route/ghc_planner_test.go
  pkg/route/planner.go
Labels: A-Team

#5508 [MB-5925] DTOD SOAP Connection
  go.mod
  go.sum
  pkg/services/dtod_planner.go
  pkg/services/dtod_planner/dtod_planner_service_test.go
  pkg/services/dtod_planner/dtod_zip5_distance.go
  pkg/services/dtod_planner/dtod_zip5_distance_test.go
  pkg/services/dtod_planner/logger.go
  pkg/services/mocks/DTODPlannerMileage.go
Labels: A-Team

#5498 [MB-5921] Filter zap error fields and limit verbose stacktrace
  pkg/logging/log.go
  pkg/logging/log_test.go
Labels: ttv

#5525 Switch cypress dockerfile to use milmove-cypress image
  .circleci/config.yml
  cypress/Dockerfile.cypress
  cypress/package.json
  cypress/yarn.lock
  dangerfile.ts
  package.json
  yarn.lock
Labels: A-Team

#5528 [MB-6010] create model for Rand McNally data
  pkg/models/zip3_distance.go
  pkg/models/zip3_distance_test.go
  pkg/testdatagen/make_zip3_distance.go
  pkg/testdatagen/shared.go
Labels: A-Team

#5537 MB-5927 Query Rand McNally database table for distances
  cmd/milmove/serve.go
  pkg/route/ghc_planner.go
  pkg/route/ghc_planner_test.go
  pkg/route/planner.go
  pkg/route/rand_mcnally_distance.go
  pkg/route/rand_mcnally_distance_test.go
  pkg/services/rand_mcnally_planner.go
Labels: A-Team

#5529 [MB-6049] move locator react query ghc api
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/move/get_move.go
  pkg/gen/ghcmessages/move.go
  pkg/gen/ghcmessages/move_status.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload_test.go
  pkg/handlers/ghcapi/move.go
  pkg/handlers/ghcapi/move_test.go
  pkg/services/mocks/MoveFetcher.go
  pkg/services/move.go
  pkg/services/move/move_fetcher.go
  pkg/services/move/move_fetcher_test.go
  src/constants/queryKeys.js
  src/services/ghcApi.js
  swagger/ghc.yaml
Labels: ttv

#5539 [MB-4636] Edit Branch in TOO Move Allowances
  cypress/integration/office/txo/tooFlows.js
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/branch.go
  pkg/gen/ghcmessages/move_order.go
  pkg/gen/ghcmessages/update_move_order_payload.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/move_order_test.go
  pkg/handlers/ghcapi/move_orders.go
  pkg/services/move_order/move_order_updater.go
  src/components/Office/AllowancesDetailForm/AllowancesDetailForm.jsx
  src/constants/orders.js
  src/pages/Office/MoveAllowances/MoveAllowances.jsx
  src/pages/Office/MoveOrders/MoveOrders.jsx
  swagger/ghc.yaml
Labels: ttv

#5538 MB-5994 Orders and allowances viewer url change to locator/move code
  cypress/integration/office/txo/tooFlows.js
  src/components/Office/OrdersTable/OrdersTable.test.jsx
  src/hooks/queries.js
  src/hooks/queries.test.js
  src/pages/Office/MoveAllowances/MoveAllowances.jsx
  src/pages/Office/MoveDetails/MoveDetails.jsx
  src/pages/Office/MoveDetails/MoveDetails.test.jsx
  src/pages/Office/MoveOrders/MoveOrders.jsx
  src/pages/Office/MoveQueue/MoveQueue.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
  src/pages/Office/TXOMoveInfo/TXOMoveInfo.jsx
  src/pages/Office/TXOMoveInfo/TXOMoveInfo.test.jsx
  src/services/ghcApi.js
  src/shared/Entities/modules/moves.js
Labels: ttv

#5544 MB-2707 Update createMoveTaskOrder to add TAC and Rank
  pkg/gen/supportapi/embedded_spec.go
  pkg/gen/supportapi/supportoperations/move_task_order/create_move_task_order.go
  pkg/gen/supportapi/supportoperations/move_task_order/get_move_task_order_responses.go
  pkg/gen/supportclient/move_task_order/get_move_task_order_responses.go
  pkg/gen/supportclient/move_task_order/move_task_order_client.go
  pkg/gen/supportmessages/customer.go
  pkg/gen/supportmessages/duty_station.go
  pkg/gen/supportmessages/move_order.go
  pkg/gen/supportmessages/move_task_order.go
  pkg/gen/supportmessages/rank.go
  pkg/handlers/supportapi/internal/payloads/model_to_payload.go
  pkg/handlers/supportapi/internal/payloads/payload_to_model.go
  pkg/handlers/supportapi/move_task_order.go
  pkg/handlers/supportapi/move_task_order_test.go
  pkg/models/validators.go
  pkg/models/validators_test.go
  pkg/services/support/move_task_order/move_task_order_creator.go
  pkg/testdatagen/make_service_member.go
  swagger/support.yaml
Labels: roci

#5543 [MB-5926,MB-5948, MB-5951, MB-6016] Parse/test DTOD response and integrate into GHC planner
  cmd/milmove/serve.go
  pkg/cli/route.go
  pkg/route/dtod_zip5_distance.go
  pkg/route/dtod_zip5_distance_test.go
  pkg/route/ghc_planner.go
  pkg/route/ghc_planner_test.go
  pkg/route/ghcmocks/SoapCaller.go
  pkg/route/logger.go
  pkg/route/planner.go
  pkg/services/dtod_planner.go
  pkg/services/dtod_planner/dtod_planner_service_test.go
  pkg/services/dtod_planner/dtod_zip5_distance.go
  pkg/services/dtod_planner/dtod_zip5_distance_test.go
  pkg/services/dtod_planner/logger.go
  pkg/services/mocks/DTODPlannerMileage.go
  pkg/services/mocks/MTOAgentListFetcher.go
  pkg/services/mocks/MTOShipmentFetcher.go
  pkg/services/mocks/MoveTaskOrderStatusUpdater.go
  pkg/services/mocks/OfficeUserListFetcher.go
  pkg/services/mocks/OrganizationFetcher.go
  pkg/services/rand_mcnally_planner.go
Labels: A-Team

#5510 [MB-5550] Use map instead of slice for EDI segments
  pkg/edi/invoice/generator.go
  pkg/edi/invoice/generator_test.go
  pkg/services/invoice/ghc_payment_request_invoice_generator.go
  pkg/services/invoice/ghc_payment_request_invoice_generator_test.go
Labels: A-Team

#5553 MB-6054 Pass customer's rank into ServiceMember model
  pkg/services/support/move_task_order/move_task_order_creator.go
Labels: roci

#5548 MB-6075 Update move order updater service object to use transaction connection
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/move_order_test.go
  pkg/handlers/ghcapi/move_orders.go
  pkg/services/mocks/MoveOrderUpdater.go
  pkg/services/mocks/OrderUpdater.go
  pkg/services/move_order.go
  pkg/services/move_order/move_order_updater.go
  pkg/services/move_order/order_updater.go
  pkg/services/move_order/order_updater_test.go
Labels: ttv

#5552 [MB-3912] Drop unused confirmation_number column, replace with move code in payloads
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20201229155602_drop_confirmation_number_from_orders.up.sql
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/move_order.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/move_order.go
  pkg/gen/primemessages/move_task_order.go
  pkg/gen/supportapi/embedded_spec.go
  pkg/gen/supportmessages/move_task_order.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/move_order_test.go
  pkg/handlers/primeapi/payloads/model_to_payload.go
  pkg/handlers/supportapi/internal/payloads/model_to_payload.go
  pkg/handlers/supportapi/move_task_order_test.go
  pkg/models/order.go
  pkg/services/move_order/move_order_fetcher.go
  pkg/services/move_order/move_order_fetcher_test.go
  pkg/services/support/move_task_order/move_task_order_creator.go
  swagger/ghc.yaml
  swagger/prime.yaml
  swagger/support.yaml
Labels: ttv

#5565 use latest milmove-cypress image
  cypress/Dockerfile.cypress
Labels: Pamplemoose

#5556 [MB-5237] Return total sum of payment request's items
  pkg/handlers/supportapi/payment_request_test.go
  pkg/services/invoice/ghc_payment_request_invoice_generator.go
  pkg/services/invoice/ghc_payment_request_invoice_generator_test.go
  pkg/services/payment_request/payment_request_reviewed_processor_test.go
Labels: A-Team

#5557 [MB-4530] adding aditional UT to make sure payment request number is being test…
  pkg/handlers/primeapi/payment_request_test.go
  pkg/services/payment_request/payment_request_creator.go
  pkg/services/payment_request/payment_request_creator_test.go
  pkg/testdatagen/make_re_domestic_linehaul_price.go
  pkg/testdatagen/shared.go
Labels: A-Team

#5574 [MB-6102] escape regex characters in duty station highlight library
  src/components/form/fields/DutyStationInput.test.jsx
  src/scenes/ServiceMembers/DutyStationSearchBox.jsx
Labels: ttv

#5570 MB-5950 use ghc planner in payment request create
  pkg/handlers/primeapi/api.go
  pkg/route/ghc_planner.go
  pkg/route/ghc_planner_test.go
  pkg/route/rand_mcnally_distance.go
  pkg/services/errors.go
  pkg/services/invoice/ghc_payment_request_invoice_generator.go
  pkg/services/mto_service_item/mto_service_item_creator_test.go
  pkg/services/payment_request/payment_request_creator.go
  pkg/services/payment_request/payment_request_creator_test.go
Labels: A-Team

#5575 MB-6104 Set document viewer react-query to not refetch onFocus
  src/hooks/queries.js
  src/pages/Office/MoveDocumentWrapper/MoveDocumentWrapper.jsx
Labels: ttv
