Repository transcom/mymove, pull requests merged in 2020-09, with the labels that each got.

#4715 [quick review] fix typo before demo
  src/pages/MyMove/Home/index.jsx
Labels: bug, help wanted, moose

#4703 add db comments for ppm(ish) tables: MB-3660
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20200827155542_add_db_comments.up.sql
Labels: Pamplemoose, moose

#4713 MB-3691 Refactor create/update address for updating mto shipment
  pkg/handlers/internalapi/mto_shipment_test.go
  pkg/services/mto_shipment/mto_shipment_updater.go
  pkg/services/mto_shipment/mto_shipment_updater_test.go
Labels: roci

#4731 [MB-3502] Orders Information table loads/formats all information on Move Details page
  .loki/reference/chrome_iphone7_TOO_TIO_Components_OrdersTable_Basic.png
  .loki/reference/chrome_iphone7_TOO_TIO_Components_OrdersTable_Orders_Table.png
  .loki/reference/chrome_laptop_TOO_TIO_Components_OrdersTable_Basic.png
  .loki/reference/chrome_laptop_TOO_TIO_Components_OrdersTable_Orders_Table.png
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/dept_indicator.go
  pkg/gen/ghcmessages/move_order.go
  pkg/gen/ghcmessages/orders_type.go
  pkg/gen/ghcmessages/orders_type_detail.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  src/components/Office/OrdersTable.jsx
  src/components/Office/OrdersTable.test.jsx
  src/components/Office/OrdersTable/OrdersTable.jsx
  src/components/Office/OrdersTable/OrdersTable.module.scss
  src/components/Office/OrdersTable/OrdersTable.stories.jsx
  src/components/Office/OrdersTable/OrdersTable.test.jsx
  src/components/Office/ordersTable.stories.jsx
  src/constants/departmentIndicators.js
  src/constants/orders.js
  src/pages/Office/MoveDetails/MoveDetails.jsx
  src/services/ghcApi.js
  src/shared/formatters.js
  src/types/moveOrder.js
  swagger/ghc.yaml
  swagger/internal.yaml
Labels: ttv

#4629 MB-3667 Create order with all fields at same time
  .envrc
  cmd/milmove/serve.go
  config/env/exp.app.env
  config/env/experimental.app.env
  config/env/prd.app.env
  config/env/prod.app.env
  config/env/staging.app.env
  config/env/stg.app.env
  pkg/cli/featureflag.go
  pkg/handlers/internalapi/orders.go
  pkg/handlers/internalapi/orders_test.go
  pkg/models/service_member.go
  pkg/services/converthelper/convert.go
  pkg/services/converthelper/convert_suite_test.go
  pkg/services/converthelper/convert_test.go
Labels: ttv

#4738 [MB-2493] Add image file support to orders document viewer
  .loki/reference/chrome_iphone7_Components_Document_Viewer_Document_Viewer_Image_Viewer.png
  .loki/reference/chrome_laptop_Components_Document_Viewer_Document_Viewer_Image_Viewer.png
  package.json
  src/components/DocumentViewer/Content/Content.module.scss
  src/components/DocumentViewer/DocumentViewer.jsx
  src/components/DocumentViewer/DocumentViewer.stories.jsx
  src/components/DocumentViewer/DocumentViewer.test.jsx
  src/components/DocumentViewer/sample.jpg
  src/components/DocumentViewer/sample2.png
  src/components/DocumentViewer/sample3.gif
  src/pages/Office/MoveOrders/MoveOrders.jsx
  yarn.lock
Labels: ttv

#4756 MB-3661 Add DB comments to Roci tables
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20200908162414_roci_db_comments.up.sql
Labels: roci

#4750 Kim mb 3878 new edit route
  .loki/reference/chrome_iphone7_Customer_Components_EditShipment_Basic.png
  .loki/reference/chrome_iphone7_Customer_Components_Step_Confirm_Move.png
  .loki/reference/chrome_laptop_Customer_Components_EditShipment_Basic.png
  .loki/reference/chrome_laptop_Customer_Components_Step_Confirm_Move.png
  cypress/integration/mymove/hhg.js
  src/components/Customer/EditShipment.jsx
  src/components/Customer/Home/ShipmentList/ShipmentList.test.jsx
  src/components/Customer/Home/ShipmentList/index.jsx
  src/components/Customer/Home/Step/Step.module.scss
  src/components/Customer/Home/Step/Step.stories.jsx
  src/components/Customer/Home/Step/index.jsx
  src/pages/MyMove/HHGShipmentSetup.jsx
  src/pages/MyMove/HHGShipmentSummary.jsx
  src/pages/MyMove/Home/index.jsx
  src/scenes/MyMove/index.jsx
  src/shared/Entities/modules/mtoShipments.js
Labels: Pamplemoose

#4766 [MB-3928] Add submitted_at to move
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20200910033042_add-move-submitted-at.up.sql
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/move_payload.go
  pkg/handlers/internalapi/moves.go
  pkg/handlers/internalapi/moves_test.go
  pkg/models/move.go
  swagger/internal.yaml
Labels: Pamplemoose

#4761 Kim mb duplicate ppm home path
  .loki/reference/chrome_iphone7_Customer_Components_ShipmentList_Basic.png
  .loki/reference/chrome_iphone7_Customer_Components_Step_Shipments.png
  .loki/reference/chrome_laptop_Customer_Components_ShipmentList_Basic.png
  .loki/reference/chrome_laptop_Customer_Components_Step_Shipments.png
  src/components/Customer/Home/ShipmentList/ShipmentList.test.jsx
  src/components/Customer/Home/ShipmentList/index.jsx
  src/pages/MyMove/HHGShipmentSummary.jsx
  src/scenes/MyMove/index.jsx
Labels: Pamplemoose

#4702 MB-3786 Customer App Buttons
  .loki/reference/chrome_iphone7_Customer_Components_HHGDetailsForm_Basic.png
  .loki/reference/chrome_iphone7_TOO_TIO_Components_ReviewServiceItems_Basic.png
  .loki/reference/chrome_iphone7_TOO_TIO_Components_ReviewServiceItems_Basic_With_Two_Items.png
  .loki/reference/chrome_iphone7_TOO_TIO_Components_ReviewServiceItems_HHG.png
  .loki/reference/chrome_iphone7_TOO_TIO_Components_ReviewServiceItems_Multiple_Shipments_Groups.png
  .loki/reference/chrome_iphone7_TOO_TIO_Components_ReviewServiceItems_Non_Temporary_Storage.png
  .loki/reference/chrome_iphone7_TOO_TIO_Components_ReviewServiceItems_With_Payment_Reviewed_Approved.png
  .loki/reference/chrome_iphone7_TOO_TIO_Components_ReviewServiceItems_With_Payment_Reviewed_Rejected.png
  .loki/reference/chrome_iphone7_TOO_TIO_Components_ReviewServiceItems_With_Status_And_Reason.png
  .loki/reference/chrome_laptop_Customer_Components_HHGDetailsForm_Basic.png
  .loki/reference/chrome_laptop_TOO_TIO_Components_ReviewServiceItems_Basic.png
  .loki/reference/chrome_laptop_TOO_TIO_Components_ReviewServiceItems_Basic_With_Two_Items.png
  .loki/reference/chrome_laptop_TOO_TIO_Components_ReviewServiceItems_HHG.png
  .loki/reference/chrome_laptop_TOO_TIO_Components_ReviewServiceItems_Multiple_Shipments_Groups.png
  .loki/reference/chrome_laptop_TOO_TIO_Components_ReviewServiceItems_Non_Temporary_Storage.png
  .loki/reference/chrome_laptop_TOO_TIO_Components_ReviewServiceItems_With_Payment_Reviewed_Approved.png
  .loki/reference/chrome_laptop_TOO_TIO_Components_ReviewServiceItems_With_Payment_Reviewed_Rejected.png
  .loki/reference/chrome_laptop_TOO_TIO_Components_ReviewServiceItems_With_Status_And_Reason.png
  cypress/integration/mymove/hhg.js
  cypress/integration/mymove/orders.js
  cypress/integration/mymove/ppm.js
  cypress/integration/mymove/serviceMemberProfile.js
  cypress/support/commands.js
  src/components/Office/ReviewServiceItems/ReviewServiceItems.stories.jsx
  src/shared/WizardPage/Form.jsx
  src/shared/WizardPage/index.css
  src/shared/WizardPage/index.jsx
  src/shared/WizardPage/index.test.js
Labels: Pamplemoose

#4768 MB-4186 Fix bug for checking verrs in ResponseForVErrors
  pkg/handlers/errors.go
Labels: bug

#4773 MB-4188 Add fake contractor to PROD
  migrations/app/migrations_manifest.txt
  migrations/app/secure/20200911161101_add_fake_contractors_prod.up.sql
Labels: 🦇team

#4767 MB-3913 Add updatePaymentServiceItemStatus event trigger
  pkg/handlers/ghcapi/payment_service_items.go
  pkg/handlers/ghcapi/payment_service_items_test.go
Labels: roci

#4776 [MB-2698 // MB-3647] Create EDI Header // Command Line utility for generating an EDI for testing with US Bank
  cmd/generate-payment-request-edi/logger.go
  cmd/generate-payment-request-edi/main.go
  pkg/edi/invoice/generator.go
  pkg/edi/segment/g62.go
  pkg/edi/segment/g62_test.go
  pkg/edi/segment/l0.go
  pkg/services/ghcrateengine/counseling_services_pricer_test.go
  pkg/services/ghcrateengine/domestic_destination_pricer_test.go
  pkg/services/ghcrateengine/domestic_linehaul_pricer_test.go
  pkg/services/ghcrateengine/domestic_origin_pricer_test.go
  pkg/services/ghcrateengine/domestic_pack_pricer_test.go
  pkg/services/ghcrateengine/domestic_shorthaul_pricer_test.go
  pkg/services/ghcrateengine/domestic_unpack_pricer_test.go
  pkg/services/ghcrateengine/fuel_surcharge_pricer_test.go
  pkg/services/ghcrateengine/ghc_rate_engine_service_test.go
  pkg/services/ghcrateengine/management_services_pricer_test.go
  pkg/services/ghcrateengine/service_item_pricer_test.go
  pkg/services/invoice/ghc_payment_request_invoice_generator.go
  pkg/services/invoice/ghc_payment_request_invoice_generator_test.go
  pkg/testdatagen/make_payment_service_item_param.go
Labels: A-Team

#4778 [MB-3440] Removes unnecessary updatePaymentRequest declaration + references
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/ghcapi/ghcoperations/payment_requests/update_payment_request.go
  pkg/gen/ghcapi/ghcoperations/payment_requests/update_payment_request_parameters.go
  pkg/gen/ghcapi/ghcoperations/payment_requests/update_payment_request_responses.go
  pkg/gen/ghcapi/ghcoperations/payment_requests/update_payment_request_urlbuilder.go
  pkg/services/event/ghc_endpoint.go
  swagger/ghc.yaml
Labels: roci

#4783 MB-4228 Hide move on PROD GovCloud
  migrations/app/migrations_manifest.txt
  migrations/app/secure/20200914173006_hide_move_on_prod_gov_cloud.up.sql
Labels: 🦇team

#4785 MB-4226 Rename internal folders to payloads and move files up one level
  pkg/handlers/primeapi/move_task_order.go
  pkg/handlers/primeapi/mto_service_item.go
  pkg/handlers/primeapi/mto_service_item_test.go
  pkg/handlers/primeapi/mto_shipment.go
  pkg/handlers/primeapi/mto_shipment_address.go
  pkg/handlers/primeapi/mto_shipment_address_test.go
  pkg/handlers/primeapi/mto_shipment_test.go
  pkg/handlers/primeapi/payloads/model_to_payload.go
  pkg/handlers/primeapi/payloads/payload_to_model.go
  pkg/handlers/primeapi/payment_request.go
  pkg/handlers/primeapi/upload.go
Labels: roci

#4793 [MB-4262] Create Way to Handle to Build Payment Service Item Lines Depending on the Type of Service Item
  pkg/services/invoice/ghc_payment_request_invoice_generator.go
Labels: A-Team

#4782 [MB-2981] [MB-4093] Orders Detail Form API and FE Integration
  .loki/reference/chrome_iphone7_TOO_TIO_Components_OrdersDetailForm_Empty_Values.png
  .loki/reference/chrome_iphone7_TOO_TIO_Components_OrdersDetailForm_Initial_Values.png
  .loki/reference/chrome_iphone7_TOO_TIO_Components_OrdersDetailForm_with_empty_values.png
  .loki/reference/chrome_iphone7_TOO_TIO_Components_OrdersDetailForm_with_initial_values.png
  .loki/reference/chrome_iphone7_TOO_TIO_Components_OrdersTable_Basic.png
  .loki/reference/chrome_laptop_TOO_TIO_Components_OrdersDetailForm_Empty_Values.png
  .loki/reference/chrome_laptop_TOO_TIO_Components_OrdersDetailForm_Initial_Values.png
  .loki/reference/chrome_laptop_TOO_TIO_Components_OrdersDetailForm_with_empty_values.png
  .loki/reference/chrome_laptop_TOO_TIO_Components_OrdersDetailForm_with_initial_values.png
  .loki/reference/chrome_laptop_TOO_TIO_Components_OrdersTable_Basic.png
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/move_order/update_move_order.go
  pkg/gen/ghcapi/ghcoperations/move_order/update_move_order_parameters.go
  pkg/gen/ghcapi/ghcoperations/move_order/update_move_order_responses.go
  pkg/gen/ghcapi/ghcoperations/move_order/update_move_order_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/ghcmessages/move_order.go
  pkg/gen/ghcmessages/update_move_order_payload.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/move_order_test.go
  pkg/handlers/ghcapi/move_orders.go
  pkg/services/mocks/MoveOrderUpdater.go
  pkg/services/move_order.go
  pkg/services/move_order/move_order_updater.go
  pkg/testdatagen/make_order.go
  src/components/Office/OrdersDetailForm.jsx
  src/components/Office/OrdersDetailForm.module.scss
  src/components/Office/OrdersDetailForm.stories.jsx
  src/components/Office/OrdersDetailForm.test.jsx
  src/components/Office/OrdersDetailForm/OrdersDetailForm.jsx
  src/components/Office/OrdersDetailForm/OrdersDetailForm.module.scss
  src/components/Office/OrdersDetailForm/OrdersDetailForm.stories.jsx
  src/components/Office/OrdersDetailForm/OrdersDetailForm.test.jsx
  src/components/Office/OrdersTable/OrdersTable.jsx
  src/components/Office/OrdersTable/OrdersTable.module.scss
  src/components/Office/OrdersTable/OrdersTable.stories.jsx
  src/components/Office/OrdersTable/OrdersTable.test.jsx
  src/components/form/fields/DutyStationInput.jsx
  src/constants/departmentIndicators.js
  src/constants/orders.js
  src/hooks/queries.js
  src/hooks/queries.test.js
  src/pages/Office/MoveOrders/MoveOrders.jsx
  src/pages/Office/MoveOrders/MoveOrders.module.scss
  src/pages/Office/MoveOrders/MoveOrders.test.jsx
  src/scenes/ServiceMembers/DutyStationSearchBox.jsx
  src/services/ghcApi.js
  src/services/swaggerRequest.js
  src/shared/formatters.js
  src/types/moveOrder.js
  swagger/ghc.yaml
Labels: ttv

#4786 MB-4219 Add new prime-api-client command for updating mtoShipment address
  cmd/prime-api-client/main.go
  cmd/prime-api-client/prime/update_mto_shipment_address.go
Labels: roci

#4797 [MB-4260] Create L5 Segment
  pkg/edi/segment/l5.go
  pkg/edi/segment/l5_test.go
Labels: A-Team

#4795 Add L3 segment
  pkg/edi/segment/l3.go
  pkg/edi/segment/l3_test.go
Labels: A-Team

#4804 MB-4209 Add definition for updateMTOAgents endpoint to prime.yaml
  pkg/gen/primeapi/configure_mymove.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/mto_shipment/update_m_t_o_agent.go
  pkg/gen/primeapi/primeoperations/mto_shipment/update_m_t_o_agent_parameters.go
  pkg/gen/primeapi/primeoperations/mto_shipment/update_m_t_o_agent_responses.go
  pkg/gen/primeapi/primeoperations/mto_shipment/update_m_t_o_agent_urlbuilder.go
  pkg/gen/primeapi/primeoperations/mymove_api.go
  pkg/gen/primeclient/mto_shipment/mto_shipment_client.go
  pkg/gen/primeclient/mto_shipment/update_m_t_o_agent_parameters.go
  pkg/gen/primeclient/mto_shipment/update_m_t_o_agent_responses.go
  swagger/prime.yaml
Labels: roci

#4788 [MB-4223] Creates notification handler for mtoshipment events
  pkg/services/event/event.go
  pkg/services/event/event_test.go
  pkg/services/event/notification.go
Labels: roci

#4807 [MB-2697 // MB-4287] Generate EDI segments for DLH
  pkg/edi/segment/l3.go
  pkg/edi/segment/l3_test.go
  pkg/edi/segment/l5.go
  pkg/edi/segment/l5_test.go
  pkg/services/invoice/ghc_payment_request_invoice_generator.go
  pkg/services/invoice/ghc_payment_request_invoice_generator_test.go
Labels: A-Team

#4796 MB-3550 Show backup contact info in Move details
  .loki/reference/chrome_iphone7_TOO_TIO_Components_CustomerInfoTable_Default.png
  .loki/reference/chrome_laptop_TOO_TIO_Components_CustomerInfoTable_Default.png
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/backup_contact.go
  pkg/gen/ghcmessages/customer.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  src/components/Office/CustomerInfoTable.jsx
  src/components/Office/CustomerInfoTable.test.jsx
  src/components/Office/customerInfoTable.stories.jsx
  src/pages/Office/MoveDetails/MoveDetails.jsx
  src/types/backupContact.js
  src/types/moveOrder.js
  swagger/ghc.yaml
Labels: ttv

#4815 MB-4235 Add UpdateMTOAgentHandler
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/mto_shipment/update_m_t_o_agent_responses.go
  pkg/gen/primeclient/mto_shipment/update_m_t_o_agent_responses.go
  pkg/handlers/errors.go
  pkg/handlers/primeapi/api.go
  pkg/handlers/primeapi/mto_agent.go
  pkg/handlers/primeapi/mto_agent_test.go
  pkg/handlers/primeapi/payloads/model_to_payload.go
  swagger/prime.yaml
Labels: roci

#4813 [MB-3635] Proof of Service Document Viewer Integration
  Dockerfile.tools
  Dockerfile.tools_local
  cmd/generate-test-data/main.go
  package.json
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/payment_request.go
  pkg/gen/ghcmessages/proof_of_service_doc.go
  pkg/gen/ghcmessages/proof_of_service_docs.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/documents.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/payment_request.go
  pkg/handlers/supportapi/api.go
  pkg/handlers/supportapi/payment_request.go
  pkg/handlers/supportapi/payment_request_test.go
  pkg/models/proof_of_service_doc.go
  pkg/services/mocks/PaymentRequestFetcher.go
  pkg/services/payment_request.go
  pkg/services/payment_request/payment_request_fetcher.go
  pkg/services/payment_request/payment_request_fetcher_test.go
  pkg/testdatagen/make_prime_upload.go
  pkg/testdatagen/make_upload.go
  pkg/testdatagen/make_user_upload.go
  pkg/testdatagen/scenario/e2ebasic.go
  pkg/testdatagen/shared.go
  pkg/testdatagen/testdata/test.jpg
  pkg/testdatagen/testdata/test.png
  src/components/DocumentViewer/DocumentViewer.jsx
  src/components/DocumentViewer/DocumentViewer.test.jsx
  src/components/DocumentViewer/Menu/Menu.jsx
  src/components/DocumentViewer/Menu/Menu.module.scss
  src/pages/Office/MoveOrders/MoveOrders.test.jsx
  src/pages/Office/PaymentRequestReview/PaymentRequestReview.jsx
  src/pages/Office/PaymentRequestReview/PaymentRequestReview.test.jsx
  src/shared/formatters.js
  src/shared/formatters.test.js
  swagger/ghc.yaml
  yarn.lock
Labels: ttv

#4831 SupportAPI: Alphabetical sort of definitions in support.yaml
  swagger/support.yaml
Labels: roci

#4808 [MB-4208] Adds testdatagen function for MTOAgent.
  pkg/models/mto_agents_test.go
  pkg/testdatagen/make_mto_agent.go
Labels: roci

#4833 MB-4222 mto service item payload notification
  pkg/services/event/event_test.go
  pkg/services/event/notification.go
  pkg/services/event/notification_test.go
Labels: roci

#4784 MB 3930 Progress Bar Mobile Styling
  .loki/reference/chrome_iphone7_scenes_Landing_Status_Time_Line.png
  .loki/reference/chrome_laptop_scenes_Landing_Status_Time_Line.png
  src/scenes/Landing/MoveSummary.css
  src/scenes/Landing/MoveSummary.jsx
  src/scenes/Landing/StatusTimeline.jsx
  src/scenes/Landing/StatusTimeline.scss
  src/scenes/Landing/index.jsx
Labels: Pamplemoose

#4836 [MB-4339] added l5 segment to all service item cases
  pkg/edi/segment/l5.go
  pkg/edi/segment/l5_test.go
  pkg/services/invoice/ghc_payment_request_invoice_generator.go
Labels: A-Team

#4840 Primeapi: Linter code fixes to prime.yaml
  cmd/prime-api-client/prime/create_payment_request.go
  cmd/prime-api-client/prime/create_upload.go
  pkg/gen/primeapi/configure_mymove.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/mymove_api.go
  pkg/gen/primeapi/primeoperations/payment_request/create_payment_request.go
  pkg/gen/primeapi/primeoperations/payment_request/create_payment_request_parameters.go
  pkg/gen/primeapi/primeoperations/payment_request/create_payment_request_responses.go
  pkg/gen/primeapi/primeoperations/payment_request/create_payment_request_urlbuilder.go
  pkg/gen/primeapi/primeoperations/payment_request/create_upload.go
  pkg/gen/primeapi/primeoperations/payment_request/create_upload_parameters.go
  pkg/gen/primeapi/primeoperations/payment_request/create_upload_responses.go
  pkg/gen/primeapi/primeoperations/payment_request/create_upload_urlbuilder.go
  pkg/gen/primeclient/mymove_client.go
  pkg/gen/primeclient/payment_request/create_payment_request_parameters.go
  pkg/gen/primeclient/payment_request/create_payment_request_responses.go
  pkg/gen/primeclient/payment_request/create_upload_parameters.go
  pkg/gen/primeclient/payment_request/create_upload_responses.go
  pkg/gen/primeclient/payment_request/payment_request_client.go
  pkg/gen/primeclient/uploads/uploads_client.go
  pkg/gen/primemessages/update_payment_request_status.go
  pkg/gen/primemessages/upload.go
  pkg/handlers/primeapi/api.go
  pkg/handlers/primeapi/payment_request.go
  pkg/handlers/primeapi/payment_request_test.go
  pkg/handlers/primeapi/upload.go
  pkg/handlers/primeapi/upload_test.go
  swagger/prime.yaml
Labels: roci

#4844 Reduce CHROME_CONCURRENCY since we had timeouts in build
  .circleci/config.yml
Labels: A-Team

#4839 Update make bin/* commands to depend on source
  Makefile
Labels: A-Team

#4847 Supportapi: Linter code fixes to support.yaml
  cmd/prime-api-client/support/list_mto_payment_requests.go
  cmd/prime-api-client/support/update_payment_request_status.go
  pkg/gen/supportapi/configure_mymove.go
  pkg/gen/supportapi/embedded_spec.go
  pkg/gen/supportapi/supportoperations/mymove_api.go
  pkg/gen/supportapi/supportoperations/payment_request/list_m_t_o_payment_requests.go
  pkg/gen/supportapi/supportoperations/payment_request/list_m_t_o_payment_requests_parameters.go
  pkg/gen/supportapi/supportoperations/payment_request/list_m_t_o_payment_requests_responses.go
  pkg/gen/supportapi/supportoperations/payment_request/list_m_t_o_payment_requests_urlbuilder.go
  pkg/gen/supportapi/supportoperations/payment_request/update_payment_request_status.go
  pkg/gen/supportapi/supportoperations/payment_request/update_payment_request_status_parameters.go
  pkg/gen/supportapi/supportoperations/payment_request/update_payment_request_status_responses.go
  pkg/gen/supportapi/supportoperations/payment_request/update_payment_request_status_urlbuilder.go
  pkg/gen/supportclient/mymove_client.go
  pkg/gen/supportclient/payment_request/list_m_t_o_payment_requests_parameters.go
  pkg/gen/supportclient/payment_request/list_m_t_o_payment_requests_responses.go
  pkg/gen/supportclient/payment_request/payment_request_client.go
  pkg/gen/supportclient/payment_request/update_payment_request_status_parameters.go
  pkg/gen/supportclient/payment_request/update_payment_request_status_responses.go
  pkg/gen/supportmessages/move_orders.go
  pkg/gen/supportmessages/move_task_order.go
  pkg/gen/supportmessages/update_payment_request.go
  pkg/gen/supportmessages/upload.go
  pkg/handlers/supportapi/api.go
  pkg/handlers/supportapi/payment_request.go
  pkg/handlers/supportapi/payment_request_test.go
  swagger/support.yaml
Labels: roci

#4849 [MB-4107] Storybook components for OrdersTable and ProfileTable
  .loki/reference/chrome_iphone7_Customer_Components_OrdersTable_Basic.png
  .loki/reference/chrome_iphone7_Customer_Components_ProfileTable_Basic.png
  .loki/reference/chrome_laptop_Customer_Components_OrdersTable_Basic.png
  .loki/reference/chrome_laptop_Customer_Components_ProfileTable_Basic.png
  src/components/Customer/Review/OrdersTable/index.jsx
  src/components/Customer/Review/OrdersTable/index.stories.jsx
  src/components/Customer/Review/ProfileTable/index.jsx
  src/components/Customer/Review/ProfileTable/index.stories.jsx
  src/components/Customer/Review/Review.module.scss
  src/components/Customer/Review/TableDivider.jsx
  src/scenes/Review/Review.css
  src/scenes/Review/Summary.jsx
  src/shared/styles/_variables.scss
Labels: Pamplemoose

#4850 [MB-3920] Trigger event updateMTOServiceItemStatus Handler
  pkg/handlers/ghcapi/mto_service_items.go
  pkg/handlers/ghcapi/mto_service_items_test.go
Labels: roci

#4838 MB-4198 Document viewer long filenames overflow with ellipsis
  .loki/reference/chrome_iphone7_Components_Document_Viewer_Document_Viewer_Image_Viewer.png
  .loki/reference/chrome_iphone7_Components_Document_Viewer_Menu_Menu.png
  .loki/reference/chrome_laptop_Components_Document_Viewer_Document_Viewer_Image_Viewer.png
  .loki/reference/chrome_laptop_Components_Document_Viewer_Menu_Menu.png
  src/App/index.css
  src/components/DocumentViewer/DocumentViewer.jsx
  src/components/DocumentViewer/DocumentViewer.module.scss
  src/components/DocumentViewer/DocumentViewer.stories.jsx
  src/components/DocumentViewer/Menu/Menu.jsx
  src/components/DocumentViewer/Menu/Menu.module.scss
  src/components/DocumentViewer/Menu/Menu.stories.jsx
Labels: ttv

#4855 MB-4409 donald update cac
  migrations/app/migrations_manifest.txt
  migrations/app/secure/20200923204433_donald_cac.up.sql
Labels: ttv

#4853 Add FA1 and FA2 segments to edi headers
  pkg/edi/segment/fa1.go
  pkg/edi/segment/fa1_test.go
  pkg/services/invoice/ghc_payment_request_invoice_generator.go
Labels: A-Team

#4806 [MB-4232] Hide cancel buttons on orders page
  src/pages/MyMove/Orders.jsx
  src/pages/MyMove/Orders.test.jsx
  src/pages/MyMove/UploadOrders.css
  src/pages/MyMove/UploadOrders.jsx
  src/pages/MyMove/UploadOrders.test.jsx
  src/scenes/MyMove/getWorkflowRoutes.jsx
  src/shared/WizardPage/Form.jsx
  src/shared/WizardPage/index.jsx
Labels: Pamplemoose

#4846 MB-3938 Adds event trigger for CreateMTOServiceItem in GHC API
  pkg/handlers/ghcapi/mto_service_items.go
  pkg/handlers/ghcapi/mto_service_items_test.go
Labels: roci

#4854 [MB-4216] Signing and submitting a PPM routes to homepage
  cypress/integration/mymove/ppm.js
  src/scenes/Legalese/index.jsx
Labels: Pamplemoose

#4852 [MB-4333] Create prime-api-client command and support API endpoint for EDI generation
  cmd/generate-payment-request-edi/main.go
  cmd/prime-api-client/main.go
  cmd/prime-api-client/support/get_payment_request_edi.go
  pkg/gen/supportapi/configure_mymove.go
  pkg/gen/supportapi/embedded_spec.go
  pkg/gen/supportapi/supportoperations/mymove_api.go
  pkg/gen/supportapi/supportoperations/payment_request/get_payment_request_e_d_i.go
  pkg/gen/supportapi/supportoperations/payment_request/get_payment_request_e_d_i_parameters.go
  pkg/gen/supportapi/supportoperations/payment_request/get_payment_request_e_d_i_responses.go
  pkg/gen/supportapi/supportoperations/payment_request/get_payment_request_e_d_i_urlbuilder.go
  pkg/gen/supportclient/payment_request/get_payment_request_e_d_i_parameters.go
  pkg/gen/supportclient/payment_request/get_payment_request_e_d_i_responses.go
  pkg/gen/supportclient/payment_request/payment_request_client.go
  pkg/gen/supportmessages/payment_request_e_d_i.go
  pkg/handlers/supportapi/api.go
  pkg/handlers/supportapi/payment_request.go
  pkg/handlers/supportapi/payment_request_test.go
  pkg/services/invoice.go
  pkg/services/invoice/ghc_payment_request_invoice_generator.go
  pkg/services/invoice/ghc_payment_request_invoice_generator_test.go
  pkg/services/mocks/GHCPaymentRequestInvoiceGenerator.go
  swagger/support.yaml
Labels: A-Team

#4856 mb 4311 golden edi test file
  pkg/edi/invoice/testdata/expected_invoice.edi.golden
  pkg/services/invoice/ghc_payment_request_invoice_generator.go
  pkg/services/invoice/ghc_payment_request_invoice_generator_test.go
  pkg/testdatagen/make_payment_service_item.go
  pkg/testdatagen/make_payment_service_item_param.go
Labels: A-Team

#4860 MB-4234 Add an MTOAgentUpdater service object
  pkg/services/mocks/MTOAgentUpdater.go
  pkg/services/mto_agent.go
  pkg/services/mto_agent/mto_agent_service_test.go
  pkg/services/mto_agent/mto_agent_updater.go
  pkg/services/mto_agent/mto_agent_updater_test.go
  pkg/services/mto_agent/mto_agent_validators.go
  pkg/services/mto_agent/mto_agent_validators_test.go
Labels: roci

#4864 [MB-4419] Added precommit hook for spectral linter
  .pre-commit-config.yaml
  package.json
  scripts/README.md
  scripts/lint-yaml-with-spectral
  swagger/.spectral.yml
  swagger/support.yaml
  yarn.lock
Labels: roci

#4863 [MB-4374] update to change upload filename
  pkg/handlers/primeapi/upload.go
  pkg/handlers/primeapi/upload_test.go
  pkg/services/mocks/PaymentRequestUploadCreator.go
  pkg/services/payment_request.go
  pkg/services/payment_request/upload_creator.go
  pkg/services/payment_request/upload_creator_test.go
Labels: A-Team

#4866 MB-4236 Add code for UpdateMTOAgentHandler
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/mto_shipment/update_m_t_o_agent.go
  pkg/gen/primeapi/primeoperations/mto_shipment/update_m_t_o_agent_responses.go
  pkg/gen/primeclient/mto_shipment/mto_shipment_client.go
  pkg/gen/primeclient/mto_shipment/update_m_t_o_agent_responses.go
  pkg/gen/primemessages/m_t_o_agent.go
  pkg/handlers/primeapi/api.go
  pkg/handlers/primeapi/mto_agent.go
  pkg/handlers/primeapi/mto_agent_test.go
  pkg/handlers/primeapi/mto_shipment_address.go
  pkg/handlers/primeapi/payloads/model_to_payload.go
  pkg/models/mto_agents_test.go
  pkg/services/mto_agent/mto_agent_updater_test.go
  pkg/services/mto_agent/mto_agent_validators.go
  pkg/services/mto_agent/mto_agent_validators_test.go
  pkg/testdatagen/make_mto_agent.go
  swagger/prime.yaml
Labels: roci

#4861 [MB-2468] TOO approve and reject mto service items e2e cypress test
  cypress/integration/office/txo/tooFlows.js
  pkg/testdatagen/scenario/e2ebasic.go
  src/components/Office/RequestedServiceItemsTable/RequestedServiceItemsTable.jsx
  src/components/ServiceItemTableHasImg/index.jsx
Labels: ttv

#4874 [MB-4374] fix to redundant app name in path
  pkg/services/payment_request/upload_creator.go
  pkg/services/payment_request/upload_creator_test.go
Labels: A-Team

#4881 Update pre_test job to avoid running out of memory
  .circleci/config.yml
  package.json
Labels: A-Team

#4858 Add migration for BVS data Oct - Dec 2020
  migrations/app/migrations_manifest.txt
  migrations/app/secure/20200924184242_import_bvs_rates_oct_2020.up.sql
Labels: A-Team

#4875 [MB-3946] Notification handler for MoveTaskOrder
  pkg/services/event/event.go
  pkg/services/event/event_test.go
  pkg/services/event/notification.go
  pkg/services/event/notification_payloads.go
  swagger/prime.yaml
Labels: roci

#4879 [MB-4427] MS and CS service items should not error out when generating EDI
  pkg/services/invoice/ghc_payment_request_invoice_generator.go
  pkg/services/invoice/ghc_payment_request_invoice_generator_test.go
Labels: A-Team

#4885 [MB-3439] Added handler for MTOShipment Payload
  pkg/services/event/event_test.go
  pkg/services/event/notification.go
Labels: roci

#4889 Add memory logging to storybook and integration tests
  .circleci/config.yml
Labels: A-Team

#4884 Prime demo helper script
  scripts/README.md
  scripts/prime-api-demo
Labels: A-Team
