Repository transcom/mymove, pull requests merged in 2020-08, with the labels that each got.

#4501 MB-3326 Shipment Display Component Spacing
  .loki/reference/chrome_iphone7_TOO_TIO_Components_RequestedShipments_with_one_approved_shipment.png
  .loki/reference/chrome_iphone7_TOO_TIO_Components_RequestedShipments_with_one_shipment.png
  .loki/reference/chrome_iphone7_TOO_TIO_Components_RequestedShipments_with_two_approved_shipments.png
  .loki/reference/chrome_iphone7_TOO_TIO_Components_RequestedShipments_with_two_shipments.png
  .loki/reference/chrome_iphone7_TOO_TIO_Components_Shipment_Display_Approved_Shipment.png
  .loki/reference/chrome_iphone7_TOO_TIO_Components_Shipment_Display_HHG_Shipment.png
  .loki/reference/chrome_iphone7_TOO_TIO_Components_Shipment_Display_NTS_Shipment.png
  .loki/reference/chrome_iphone7_TOO_TIO_Components_Shipment_Display_Postal_Only_Destination.png
  .loki/reference/chrome_laptop_TOO_TIO_Components_RequestedShipments_with_one_approved_shipment.png
  .loki/reference/chrome_laptop_TOO_TIO_Components_RequestedShipments_with_one_shipment.png
  .loki/reference/chrome_laptop_TOO_TIO_Components_RequestedShipments_with_two_approved_shipments.png
  .loki/reference/chrome_laptop_TOO_TIO_Components_RequestedShipments_with_two_shipments.png
  .loki/reference/chrome_laptop_TOO_TIO_Components_Shipment_Display_Approved_Shipment.png
  .loki/reference/chrome_laptop_TOO_TIO_Components_Shipment_Display_HHG_Shipment.png
  .loki/reference/chrome_laptop_TOO_TIO_Components_Shipment_Display_NTS_Shipment.png
  .loki/reference/chrome_laptop_TOO_TIO_Components_Shipment_Display_Postal_Only_Destination.png
  src/components/Office/ShipmentDisplay/ShipmentDisplay.module.scss
Labels: ttv

#4532 MB-3526 Add case-sensitive-paths plugin to check for file name case mismatches
  .rescriptsrc
  case-sensitive-paths-rescripts.js
  package.json
  yarn.lock
Labels: A-Team

#4534 [MB-3534] Fix IE11 min-height flex bug
  src/components/DocumentViewer/sample.pdf
  src/components/Office/ReviewServiceItems/ReviewDetailsCard.module.scss
  src/components/Office/ReviewServiceItems/ServiceItemCard.module.scss
  src/pages/Office/index.jsx
  src/styles/office.scss
Labels: bug, ttv

#4531 MB-2942 SPIKE: Create mTLS webhook-client and support endpoint for testing
  Makefile
  cmd/webhook-client/connection.go
  cmd/webhook-client/main.go
  cmd/webhook-client/post_webhook_notify.go
  pkg/gen/supportapi/configure_mymove.go
  pkg/gen/supportapi/embedded_spec.go
  pkg/gen/supportapi/supportoperations/mymove_api.go
  pkg/gen/supportapi/supportoperations/webhook/post_webhook_notify.go
  pkg/gen/supportapi/supportoperations/webhook/post_webhook_notify_parameters.go
  pkg/gen/supportapi/supportoperations/webhook/post_webhook_notify_responses.go
  pkg/gen/supportapi/supportoperations/webhook/post_webhook_notify_urlbuilder.go
  pkg/gen/supportclient/mymove_client.go
  pkg/gen/supportclient/webhook/post_webhook_notify_parameters.go
  pkg/gen/supportclient/webhook/post_webhook_notify_responses.go
  pkg/gen/supportclient/webhook/webhook_client.go
  pkg/handlers/supportapi/api.go
  pkg/handlers/supportapi/webhook_notify.go
  swagger/support.yaml
Labels: roci

#4510 MB-2934 [PrimeAPI] Create subscriptions table
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20200803200704_create_subscriptions_table.up.sql
  pkg/models/webhook_subscription.go
  pkg/models/webhook_subscription_test.go
  pkg/testdatagen/constants.go
  pkg/testdatagen/make_webhook_subscription.go
  pkg/testdatagen/shared.go
Labels: roci

#4537 Fix propType spelling from post_code to postal_code
  src/components/Customer/HHGDetailsForm.jsx
Labels: Pamplemoose

#4519 [MB-2878] add contract years to rate engine tables
  cmd/ghc-pricing-parser/main.go
  pkg/parser/pricing/parse.go
  pkg/services/ghcimport/ghc_rateengine_importer.go
  pkg/services/ghcimport/ghc_rateengine_importer_test.go
  pkg/services/ghcimport/import_re_contract_years.go
  pkg/services/ghcimport/import_re_contract_years_test.go
  pkg/services/ghcimport/import_re_task_order_fees_test.go
Labels: A-Team

#4545 [MB-3521] Fix PPM document viewer route
  package.json
  src/App/index.jsx
  src/constants/userRoles.js
  src/pages/Office/index.jsx
  src/pages/Office/index.test.jsx
  src/shared/User/LoginButton.jsx
  src/shared/store.js
  src/store/auth/actions.js
  src/store/auth/actions.test.js
  src/store/auth/reducer.js
  src/store/auth/reducer.test.js
  src/testUtils.jsx
  yarn.lock
Labels: bug, ttv

#4549 Kim mb 3429 add draft to shipment
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20200804003845_add-draft-status-to-mto-shipments.up.sql
  migrations/app/schema/20200804194318_replace-default-status-on-shipment.up.sql
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/m_t_o_shipment.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/handlers/internalapi/mto_shipment.go
  pkg/handlers/primeapi/mto_shipment.go
  pkg/handlers/primeapi/mto_shipment_test.go
  pkg/handlers/supportapi/mto_shipment_test.go
  pkg/models/mto_shipments.go
  pkg/models/mto_shipments_test.go
  pkg/services/mto_shipment/mto_shipment_creator.go
  pkg/services/mto_shipment/mto_shipment_creator_test.go
  pkg/services/mto_shipment/mto_shipment_updater.go
  pkg/services/mto_shipment/mto_shipment_updater_test.go
  pkg/testdatagen/make_mto_shipment.go
  swagger/internal.yaml
Labels: Pamplemoose

#4535 [MB-2935] Create notifications table
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20200729012657_create_webhook_notifications_table.up.sql
  pkg/models/webhook_notification.go
  pkg/models/webhook_notification_test.go
  pkg/services/event/endpoint.go
  pkg/services/event/event.go
  pkg/services/event/event_test.go
  pkg/services/event/notification.go
  pkg/services/event/notification_payloads.go
Labels: roci

#4544 MB-1589 Add lookup function services schedule origin
  pkg/payment_request/service_param_value_lookups/service_param_value_lookups.go
  pkg/payment_request/service_param_value_lookups/services_schedule_origin_lookup.go
  pkg/payment_request/service_param_value_lookups/services_schedule_origin_lookup_test.go
Labels: A-Team

#4548 MB-3481 TXO sees multiple copies of basic service items
  pkg/services/move_task_order/move_task_order_creator.go
  pkg/services/move_task_order/move_task_order_creator_test.go
  pkg/testdatagen/make_mto_service_item.go
  pkg/testdatagen/scenario/e2ebasic.go
Labels: bug, ttv

#4562 [MB-1590] Services Schedule Destination Lookup
  pkg/payment_request/service_param_value_lookups/service_param_value_lookups.go
  pkg/payment_request/service_param_value_lookups/services_schedule_destination_lookup.go
  pkg/payment_request/service_param_value_lookups/services_schedule_destination_lookup_test.go
Labels: A-Team

#4566 MB-3591 Fix MTO shipment updater tests
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/handlers/supportapi/mto_shipment_test.go
Labels: bug, ttv

#4563 MB-3398 Add static uuid to the creation of a Document test record
  pkg/testdatagen/scenario/e2ebasic.go
Labels: roci

#4553 MB-3541 Add all GHC API Endpoints and Internal API Endpoints to map in events pkg
  pkg/services/event/endpoint.go
  pkg/services/event/event.go
  pkg/services/event/event_test.go
  pkg/services/event/ghc_endpoint.go
  pkg/services/event/internal_endpoint.go
  pkg/services/event/notification.go
  pkg/services/event/support_endpoint.go
Labels: roci

#4547 [MB-3452] Reviewed payment request shows success alert with review date
  .loki/reference/chrome_iphone7_TOO_TIO_Components_ReviewServiceItems_ReviewDetails_Payment_Authorized.png
  .loki/reference/chrome_iphone7_TOO_TIO_Components_ReviewServiceItems_ReviewDetails_Payment_Authorized_Rejected.png
  .loki/reference/chrome_iphone7_TOO_TIO_Components_ReviewServiceItems_ServiceItemCards_Accepted_Request_Complete.png
  .loki/reference/chrome_iphone7_TOO_TIO_Components_ReviewServiceItems_ServiceItemCards_Rejected_Request_Complete.png
  .loki/reference/chrome_iphone7_TOO_TIO_Components_ReviewServiceItems_With_Payment_Reviewed_Approved.png
  .loki/reference/chrome_iphone7_TOO_TIO_Components_ReviewServiceItems_With_Payment_Reviewed_Rejected.png
  .loki/reference/chrome_laptop_TOO_TIO_Components_ReviewServiceItems_ReviewDetails_Payment_Authorized.png
  .loki/reference/chrome_laptop_TOO_TIO_Components_ReviewServiceItems_ReviewDetails_Payment_Authorized_Rejected.png
  .loki/reference/chrome_laptop_TOO_TIO_Components_ReviewServiceItems_ServiceItemCards_Accepted_Request_Complete.png
  .loki/reference/chrome_laptop_TOO_TIO_Components_ReviewServiceItems_ServiceItemCards_Rejected_Request_Complete.png
  .loki/reference/chrome_laptop_TOO_TIO_Components_ReviewServiceItems_With_Payment_Reviewed_Approved.png
  .loki/reference/chrome_laptop_TOO_TIO_Components_ReviewServiceItems_With_Payment_Reviewed_Rejected.png
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/payment_request.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  src/components/Office/ReviewServiceItems/PaymentReviewed.jsx
  src/components/Office/ReviewServiceItems/PaymentReviewed.module.scss
  src/components/Office/ReviewServiceItems/PaymentReviewed.stories.jsx
  src/components/Office/ReviewServiceItems/ReviewServiceItems.jsx
  src/components/Office/ReviewServiceItems/ReviewServiceItems.module.scss
  src/components/Office/ReviewServiceItems/ReviewServiceItems.stories.jsx
  src/components/Office/ReviewServiceItems/ReviewServiceItems.test.jsx
  src/components/Office/ReviewServiceItems/ServiceItemCard.jsx
  src/components/Office/ReviewServiceItems/ServiceItemCard.module.scss
  src/components/Office/ReviewServiceItems/ServiceItemCard.stories.jsx
  src/pages/TIO/PaymentRequestReview.jsx
  src/shared/formatters.js
  src/shared/formatters.test.js
  src/types/moveOrder.js
  swagger/ghc.yaml
Labels: ttv

#4578 MB-3548 refactor service item lookups initializer
  pkg/payment_request/service_param_value_lookups/contract_code_lookup.go
  pkg/payment_request/service_param_value_lookups/contract_code_lookup_test.go
  pkg/payment_request/service_param_value_lookups/distance_zip3_lookup.go
  pkg/payment_request/service_param_value_lookups/distance_zip3_lookup_test.go
  pkg/payment_request/service_param_value_lookups/distance_zip5_lookup.go
  pkg/payment_request/service_param_value_lookups/distance_zip5_lookup_test.go
  pkg/payment_request/service_param_value_lookups/eia_fuel_price_lookup.go
  pkg/payment_request/service_param_value_lookups/eia_fuel_price_lookup_test.go
  pkg/payment_request/service_param_value_lookups/mto_available_to_prime_at_lookup_test.go
  pkg/payment_request/service_param_value_lookups/psi_domestic_linehaul_lookup.go
  pkg/payment_request/service_param_value_lookups/psi_domestic_linehaul_lookup_test.go
  pkg/payment_request/service_param_value_lookups/requested_pickup_date_lookup.go
  pkg/payment_request/service_param_value_lookups/requested_pickup_date_lookup_test.go
  pkg/payment_request/service_param_value_lookups/service_area_dest_lookup.go
  pkg/payment_request/service_param_value_lookups/service_area_dest_lookup_test.go
  pkg/payment_request/service_param_value_lookups/service_area_lookup.go
  pkg/payment_request/service_param_value_lookups/service_area_lookup_test.go
  pkg/payment_request/service_param_value_lookups/service_area_origin_lookup.go
  pkg/payment_request/service_param_value_lookups/service_area_origin_lookup_test.go
  pkg/payment_request/service_param_value_lookups/service_param_value_lookups.go
  pkg/payment_request/service_param_value_lookups/service_param_value_lookups_test.go
  pkg/payment_request/service_param_value_lookups/services_schedule_destination_lookup.go
  pkg/payment_request/service_param_value_lookups/services_schedule_destination_lookup_test.go
  pkg/payment_request/service_param_value_lookups/services_schedule_lookup.go
  pkg/payment_request/service_param_value_lookups/services_schedule_lookup_test.go
  pkg/payment_request/service_param_value_lookups/services_schedule_origin_lookup.go
  pkg/payment_request/service_param_value_lookups/services_schedule_origin_lookup_test.go
  pkg/payment_request/service_param_value_lookups/weight_actual_lookup.go
  pkg/payment_request/service_param_value_lookups/weight_actual_lookup_test.go
  pkg/payment_request/service_param_value_lookups/weight_billed_actual_lookup.go
  pkg/payment_request/service_param_value_lookups/weight_billed_actual_lookup_test.go
  pkg/payment_request/service_param_value_lookups/weight_estimated_lookup.go
  pkg/payment_request/service_param_value_lookups/weight_estimated_lookup_test.go
  pkg/payment_request/service_param_value_lookups/zip_address_lookup.go
  pkg/payment_request/service_param_value_lookups/zip_address_lookup_test.go
  pkg/payment_request/service_param_value_lookups/zip_dest_address_lookup.go
  pkg/payment_request/service_param_value_lookups/zip_dest_address_lookup_test.go
  pkg/payment_request/service_param_value_lookups/zip_pickup_address_lookup.go
  pkg/payment_request/service_param_value_lookups/zip_pickup_address_lookup_test.go
  pkg/services/payment_request/payment_request_creator.go
  pkg/testdatagen/scenario/e2ebasic.go
Labels: A-Team

#4567 [MB-3336] HHG Form validation
  .loki/reference/chrome_iphone7_Customer_Components_HHGDetailsForm_Basic.png
  .loki/reference/chrome_laptop_Customer_Components_HHGDetailsForm_Basic.png
  cypress/integration/mymove/hhg.js
  src/components/Customer/HHGDetailsForm.jsx
  src/components/form/AddressFields/AddressFields.jsx
  src/components/form/AddressFields/AddressFields.stories.jsx
  src/components/form/AddressFields/AddressFields.test.jsx
  src/components/form/ContactInfoFields/ContactInfoFields.jsx
  src/components/form/ContactInfoFields/ContactInfoFields.stories.jsx
  src/components/form/ContactInfoFields/ContactInfoFields.test.jsx
  src/components/form/fields/DatePickerInput.jsx
  src/components/form/fields/TextInput.jsx
  src/utils/formikValidators.js
Labels: Pamplemoose

#4595 Add serialize-javascript to resolutions so version with security advisory is not used
  package.json
  yarn.lock
Labels: A-Team

#4588 run ppmCloseout tests, but skip tests that rely on BVS
  cypress/integration/mymove/ppmCloseout.js
Labels: Pamplemoose

#4465 [MB-1245 MB-1246 MB-3406] Domestic Fuel Surcharge Pricer
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20200727192756_fuel_surcharge_database_changes.up.sql
  migrations/app/schema/20200730153642_add_ghc_diesel_fuel_price_records.up.sql
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/service_item_param_name.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/service_item_param_name.go
  pkg/models/mto_shipments.go
  pkg/models/service_item_param_key.go
  pkg/payment_request/service_param_value_lookups/actual_pickup_date_lookup.go
  pkg/payment_request/service_param_value_lookups/actual_pickup_date_lookup_test.go
  pkg/payment_request/service_param_value_lookups/distance_zip3_lookup.go
  pkg/payment_request/service_param_value_lookups/distance_zip3_lookup_test.go
  pkg/payment_request/service_param_value_lookups/distance_zip5_lookup.go
  pkg/payment_request/service_param_value_lookups/distance_zip5_lookup_test.go
  pkg/payment_request/service_param_value_lookups/fsc_weight_based_distance_multiplier_lookup.go
  pkg/payment_request/service_param_value_lookups/fsc_weight_based_distance_multiplier_lookup_test.go
  pkg/payment_request/service_param_value_lookups/psi_domestic_linehaul_lookup.go
  pkg/payment_request/service_param_value_lookups/psi_domestic_linehaul_lookup_test.go
  pkg/payment_request/service_param_value_lookups/service_param_value_lookups.go
  pkg/payment_request/service_param_value_lookups/service_param_value_lookups_test.go
  pkg/payment_request/service_param_value_lookups/weight_billed_actual_lookup_test.go
  pkg/services/ghc_rate_engine.go
  pkg/services/ghcrateengine/fuel_surcharge_pricer.go
  pkg/services/ghcrateengine/fuel_surcharge_pricer_test.go
  pkg/services/ghcrateengine/param_convert.go
  pkg/services/ghcrateengine/param_convert_test.go
  pkg/services/ghcrateengine/service_item_pricer.go
  pkg/services/mocks/FuelSurchargePricer.go
  pkg/testdatagen/scenario/e2ebasic.go
  swagger/ghc.yaml
  swagger/prime.yaml
Labels: A-Team

#4565 [MB-3571][MB-3572] Add TXO E2E tests
  Makefile
  cypress/.eslintrc
  cypress/integration/office/txo/tioFlows.js
  cypress/integration/office/txo/tooFlows.js
  cypress/support/commands.js
  docker-compose.circle.yml
  docker-compose.local.yml
  docker-compose.yml
  pkg/testdatagen/scenario/e2ebasic.go
  src/pages/TIO/PaymentRequestReview.jsx
Labels: ttv

#4600 [quick review] fix two broken links in PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: bug

#4596 [WIP]Adjust schemas to allow normalizing of nested entities of user
  src/components/Customer/HHGDetailsForm.jsx
  src/pages/MyMove/HHGShipmentSummary.jsx
  src/scenes/Review/Summary.jsx
  src/shared/Entities/modules/orders.js
  src/shared/Entities/modules/serviceMembers.js
  src/shared/Entities/schema.js
Labels: Pamplemoose

#4529 [MB-3508] React-Query boilerplate
  cypress/integration/office/homepage.js
  cypress/integration/office/txo/tooFlows.js
  package.json
  src/App/index.jsx
  src/constants/queryKeys.js
  src/hooks/queries.js
  src/hooks/queries.test.js
  src/pages/Office/PaymentRequestIndex/PaymentRequestIndex.jsx
  src/pages/Office/PaymentRequestIndex/PaymentRequestIndex.test.jsx
  src/pages/Office/PaymentRequestReview/PaymentRequestReview.jsx
  src/pages/Office/PaymentRequestReview/PaymentRequestReview.module.scss
  src/pages/Office/PaymentRequestReview/PaymentRequestReview.test.jsx
  src/pages/Office/TXOMoveInfo/TXOMoveInfo.jsx
  src/pages/Office/index.jsx
  src/pages/TIO/PaymentRequestReview.jsx
  src/scenes/Office/TIO/paymentRequestIndex.jsx
  src/services/ghcApi.js
  src/services/swaggerRequest.js
  src/services/swaggerRequest.test.js
  src/utils/api.js
  src/utils/api.test.js
  yarn.lock
Labels: ttv

#4610 [MB-2599] Pack Pricer
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20200812180333_add_contract_code_param_to_dpk.up.sql
  migrations/app/schema/20200812202513_convert_schedule_params_to_integer.up.sql
  pkg/services/ghc_rate_engine.go
  pkg/services/ghcrateengine/domestic_pack_pricer.go
  pkg/services/ghcrateengine/domestic_pack_pricer_test.go
  pkg/services/ghcrateengine/ghc_rate_engine_service_test.go
  pkg/services/ghcrateengine/pricer_query_helpers.go
  pkg/services/ghcrateengine/pricer_query_helpers_test.go
  pkg/services/ghcrateengine/service_item_pricer.go
  pkg/services/ghcrateengine/service_item_pricer_test.go
  pkg/services/mocks/DomesticPackPricer.go
Labels: A-Team

#4590 Kim mb 3523 fix submit certification payload
  pkg/handlers/internalapi/signed_certifications.go
  src/scenes/Legalese/index.jsx
  src/scenes/MyMove/getWorkflowRoutes.jsx
Labels: Pamplemoose

#4615 Return object instead of nil to fix access code error
  migrations/app/migrations_manifest.txt
  pkg/handlers/internalapi/access_code.go
  pkg/handlers/internalapi/access_code_test.go
Labels: Pamplemoose

#4599 [MB-3511] create internalapi update mto shipment endpoint
  pkg/gen/internalapi/configure_mymove.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalapi/internaloperations/mto_shipment/update_m_t_o_shipment.go
  pkg/gen/internalapi/internaloperations/mto_shipment/update_m_t_o_shipment_parameters.go
  pkg/gen/internalapi/internaloperations/mto_shipment/update_m_t_o_shipment_responses.go
  pkg/gen/internalapi/internaloperations/mto_shipment/update_m_t_o_shipment_urlbuilder.go
  pkg/gen/internalapi/internaloperations/mymove_api.go
  pkg/gen/internalmessages/m_t_o_shipment.go
  pkg/gen/internalmessages/m_t_o_shipment_status.go
  pkg/gen/internalmessages/update_shipment.go
  pkg/handlers/internalapi/api.go
  pkg/handlers/internalapi/internal/payloads/model_to_payload.go
  pkg/handlers/internalapi/internal/payloads/payload_to_model.go
  pkg/handlers/internalapi/mto_shipment.go
  pkg/handlers/internalapi/mto_shipment_test.go
  pkg/services/mto_shipment/mto_shipment_updater.go
  swagger/internal.yaml
Labels: Pamplemoose, moose

#4622 MB-3531 Remove webhook-client's dependency on swagger client
  cmd/webhook-client/connection.go
  cmd/webhook-client/db_webhook_notify.go
  cmd/webhook-client/main.go
  cmd/webhook-client/post_webhook_notify.go
  cmd/webhook-client/shared.go
  cmd/webhook-client/webhook_test.go
Labels: roci

#4598 MB-3619 Add queries to MoveTaskOrder page
  cypress/integration/office/txo/tooFlows.js
  src/constants/queryKeys.js
  src/hooks/queries.js
  src/hooks/queries.test.js
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.test.jsx
  src/pages/Office/TXOMoveInfo/TXOMoveInfo.jsx
  src/pages/Office/TXOMoveInfo/TXOMoveInfo.test.jsx
  src/pages/TOO/moveTaskOrder.jsx
  src/pages/TOO/moveTaskOrder.test.jsx
  src/scenes/Office/TOO/too.jsx
  src/services/ghcApi.js
  src/shared/Entities/modules/moveOrders.js
  src/shared/Entities/modules/moveTaskOrders.js
  src/shared/Entities/schema.js
Labels: ttv

#4636 MB-2110 TOO can view shipment weight details
  .loki/reference/chrome_iphone7_TOO_TIO_Components_ShipmentWeightDetails_With_Details.png
  .loki/reference/chrome_iphone7_TOO_TIO_Components_ShipmentWeightDetails_With_No_Details.png
  .loki/reference/chrome_laptop_TOO_TIO_Components_ShipmentWeightDetails_With_Details.png
  .loki/reference/chrome_laptop_TOO_TIO_Components_ShipmentWeightDetails_With_No_Details.png
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/m_t_o_shipment.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  src/components/Office/ShipmentWeightDetails/ShipmentWeightDetails.jsx
  src/components/Office/ShipmentWeightDetails/ShipmentWeightDetails.stories.jsx
  src/components/Office/ShipmentWeightDetails/ShipmentWeightDetails.test.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
  swagger/ghc.yaml
Labels: ttv

#4645 [MB-3659] Added table/column comments in DB for A-Team tables
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20200819211216_ateam_table_comments.up.sql
Labels: A-Team

#4647 [MB-3501] mto display requested service items
  .loki/reference/chrome_iphone7_Components_Tables_Service_Item_Tables.png
  .loki/reference/chrome_iphone7_TOO_TIO_Components_RequestedServiceItemsTable_Default.png
  .loki/reference/chrome_iphone7_TOO_TIO_Components_ShipmentContainer_MTO_Accessorial.png
  .loki/reference/chrome_laptop_Components_Tables_Service_Item_Tables.png
  .loki/reference/chrome_laptop_TOO_TIO_Components_RequestedServiceItemsTable_Default.png
  .loki/reference/chrome_laptop_TOO_TIO_Components_ShipmentContainer_MTO_Accessorial.png
  pkg/testdatagen/scenario/e2ebasic.go
  src/components/DataPoint/index.module.scss
  src/components/Office/RequestedServiceItemsTable.test.jsx
  src/components/Office/RequestedServiceItemsTable/RequestedServiceItemsTable.jsx
  src/components/Office/RequestedServiceItemsTable/RequestedServiceItemsTable.module.scss
  src/components/Office/RequestedServiceItemsTable/RequestedServiceItemsTable.stories.jsx
  src/components/Office/RequestedServiceItemsTable/RequestedServiceItemsTable.test.jsx
  src/components/Office/ShipmentContainer.stories.jsx
  src/components/Office/requestedServiceItemsTable.module.scss
  src/components/ServiceItemTableHasImg/index.jsx
  src/components/ServiceItemTableHasImg/index.module.scss
  src/components/ServiceItemTableHasImg/index.test.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.test.jsx
  src/stories/tables.stories.jsx
Labels: ttv

#4648 MB-2757 Add expected payload to webhook client and support endpoint
  cmd/webhook-client/db_webhook_notify.go
  cmd/webhook-client/main.go
  cmd/webhook-client/post_webhook_notify.go
  cmd/webhook-client/shared.go
  cmd/webhook-client/webhook_test.go
  pkg/gen/supportapi/embedded_spec.go
  pkg/gen/supportapi/supportoperations/webhook/post_webhook_notify.go
  pkg/gen/supportapi/supportoperations/webhook/post_webhook_notify_parameters.go
  pkg/gen/supportapi/supportoperations/webhook/post_webhook_notify_responses.go
  pkg/gen/supportclient/webhook/post_webhook_notify_parameters.go
  pkg/gen/supportclient/webhook/post_webhook_notify_responses.go
  pkg/handlers/supportapi/webhook_notify.go
  pkg/testdatagen/testdata/webhook_test_data.json
  swagger/support.yaml
Labels: roci

#4623 MB-3685 | misc small cypress improvements :)
  .circleci/config.yml
  .gitignore
  README.md
  cypress.json
  cypress/Dockerfile.cypress
  cypress/support/constants.js
  cypress/yarn.lock
  dangerfile.ts
  mocha-reporter-config.json
  package.json
  yarn.lock
Labels: dependencies

#4665 MB-3699 Add GHC styles to Customer App (and fix cypress scrolling issues)
  .loki/reference/chrome_iphone7_Customer_Components_HHGDetailsForm_Basic.png
  .loki/reference/chrome_laptop_Customer_Components_HHGDetailsForm_Basic.png
  cypress/support/index.js
  src/scenes/Landing/MoveSummary.jsx
  src/scenes/Landing/MoveSummary/PaymentRequestedSummary.jsx
  src/scenes/Moves/Ppm/AllowableExpenses.jsx
  src/scenes/Moves/Ppm/CustomerAgreementLegalese.js
  src/scenes/Moves/Ppm/PPMPaymentRequestActionBtns.jsx
  src/scenes/Moves/Ppm/TrailerCriteria.jsx
  src/scenes/Moves/Ppm/WeightTicketExamples.jsx
  src/scenes/MyMove/index.jsx
  src/scenes/Office/TIO/paymentRequestShow.jsx
  src/scenes/Review/SaveCancelButtons.jsx
  src/shared/AlertWithConfirmation/index.jsx
  src/shared/AlertWithConfirmation/index.test.jsx
  src/shared/AlertWithDeleteConfirmation/index.jsx
  src/shared/AlertWithDeleteConfirmation/index.test.jsx
  src/shared/ConfirmWithReasonButton/index.jsx
  src/shared/EditablePanel/index.jsx
  src/shared/WizardPage/Form.jsx
  src/shared/WizardPage/index.jsx
  src/styles/customer.scss
Labels: Pamplemoose

#4672 MB-3744 Add migration for BVS data Aug-Sept 2020
  migrations/app/migrations_manifest.txt
  migrations/app/secure/20200819005749_import_bvs_rates_aug_2020.up.sql
Labels: A-Team

#4685 MB-3559 Add event trigger to GHC Payment Request update endpoint
  pkg/handlers/apitests.go
  pkg/handlers/ghcapi/payment_request.go
  pkg/handlers/ghcapi/payment_request_test.go
  pkg/handlers/supportapi/payment_request_test.go
Labels: roci

#4676 [MB-3766] fetch mto accessorial service item details (dimensions/customer contact)
  .loki/reference/chrome_iphone7_Components_Tables_Service_Item_Tables.png
  .loki/reference/chrome_iphone7_TOO_TIO_Components_RequestedServiceItemsTable_Approved_Service_Items.png
  .loki/reference/chrome_iphone7_TOO_TIO_Components_RequestedServiceItemsTable_Default.png
  .loki/reference/chrome_iphone7_TOO_TIO_Components_RequestedServiceItemsTable_Rejected_Service_Items.png
  .loki/reference/chrome_iphone7_TOO_TIO_Components_ShipmentContainer_MTO_Accessorial.png
  .loki/reference/chrome_laptop_Components_Tables_Service_Item_Tables.png
  .loki/reference/chrome_laptop_TOO_TIO_Components_RequestedServiceItemsTable_Approved_Service_Items.png
  .loki/reference/chrome_laptop_TOO_TIO_Components_RequestedServiceItemsTable_Default.png
  .loki/reference/chrome_laptop_TOO_TIO_Components_RequestedServiceItemsTable_Rejected_Service_Items.png
  .loki/reference/chrome_laptop_TOO_TIO_Components_ShipmentContainer_MTO_Accessorial.png
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/customer_contact_type.go
  pkg/gen/ghcmessages/dimension_type.go
  pkg/gen/ghcmessages/m_t_o_service_item.go
  pkg/gen/ghcmessages/m_t_o_service_item_customer_contact.go
  pkg/gen/ghcmessages/m_t_o_service_item_customer_contacts.go
  pkg/gen/ghcmessages/m_t_o_service_item_dimension.go
  pkg/gen/ghcmessages/m_t_o_service_item_dimensions.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/mto_service_items.go
  pkg/models/mto_service_item_customer_contacts.go
  pkg/testdatagen/scenario/e2ebasic.go
  src/components/Office/RequestedServiceItemsTable/RequestedServiceItemsTable.jsx
  src/components/Office/RequestedServiceItemsTable/RequestedServiceItemsTable.stories.jsx
  src/components/Office/RequestedServiceItemsTable/RequestedServiceItemsTable.test.jsx
  src/components/Office/ServiceItemDetails/ServiceItemDetails.jsx
  src/components/Office/ServiceItemDetails/ServiceItemDetails.module.scss
  src/components/Office/ShipmentContainer.stories.jsx
  src/components/ServiceItemTableHasImg/index.jsx
  src/components/ServiceItemTableHasImg/index.module.scss
  src/components/ServiceItemTableHasImg/index.test.jsx
  src/constants/customerContactTypes.js
  src/constants/dimensionTypes.js
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
  src/stories/tables.stories.jsx
  src/types/moveOrder.js
  swagger/ghc.yaml
Labels: ttv

#4657 MB-3725 Add adr for using asdf to manage node, yarn, and golang development installs
  .spelling
  .tool-versions
  docs/adr/0056-use-asdf-to-manage-golang-versions-in-development.md
  docs/adr/index.md
  scripts/check-go-version
  scripts/prereqs
Labels: A-Team

#4699 MB-3830 Fix destination address lookup attempt
  pkg/payment_request/service_param_value_lookups/service_param_value_lookups.go
  pkg/payment_request/service_param_value_lookups/service_param_value_lookups_test.go
  pkg/testdatagen/scenario/e2ebasic.go
Labels: A-Team

#4701 MB-3443 Validate military time fields
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/mto_service_item/create_m_t_o_service_item.go
  pkg/gen/primeclient/mto_service_item/mto_service_item_client.go
  pkg/gen/primemessages/m_t_o_service_item_d_d_f_s_i_t.go
  pkg/services/mto_service_item/mto_service_item_creator.go
  pkg/services/mto_service_item/mto_service_item_creator_test.go
  swagger/prime.yaml
Labels: roci

#4714 MB-3443 Remove firstAvailableDelivery examples
  pkg/gen/primeapi/embedded_spec.go
  swagger/prime.yaml
Labels: roci

#4710 [MB-3767] Populate home screen data
  .loki/reference/chrome_iphone7_Customer_Components_Home_Basic.png
  .loki/reference/chrome_laptop_Customer_Components_Home_Basic.png
  cypress/integration/mymove/hhg.js
  src/components/Customer/Home/DocsUploaded/index.jsx
  src/components/Customer/Home/ShipmentList/ShipmentList.stories.jsx
  src/components/Customer/Home/ShipmentList/ShipmentList.test.jsx
  src/components/Customer/Home/ShipmentList/index.jsx
  src/components/Customer/Home/Step/Step.stories.jsx
  src/pages/MyMove/Home/index.jsx
  src/pages/MyMove/Home/index.stories.jsx
  src/pages/MyMove/Home/index.test.jsx
  src/scenes/Review/Review.jsx
  src/shared/Entities/modules/mtoShipments.js
  src/shared/Entities/schema.js
Labels: Pamplemoose
