Repository transcom/mymove, pull requests merged in 2020-01, with the labels that each got.

#3182 Authorization middleware
  cmd/milmove/serve.go
  pkg/auth/authentication/auth.go
  pkg/auth/authentication/auth_test.go
  pkg/auth/authentication/authgch_test.go
  pkg/auth/authentication/authghc.go
  pkg/auth/authentication/mocks/APIContext.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/internalapi/api.go
  pkg/handlers/internalapi/users_test.go
  pkg/models/roles/roles.go
  pkg/models/user_test.go
  pkg/testdatagen/scenario/e2ebasic.go
  swagger/ghc.yaml
  swagger/internal.yaml
Labels: roci

#3270 Extend pricing importer to include other international prices (tab 3d)
  pkg/services/ghcimport/ghc_rateengine_importer.go
  pkg/services/ghcimport/import_re_domestic_service_area_prices.go
  pkg/services/ghcimport/import_re_domestic_service_area_prices_test.go
  pkg/services/ghcimport/import_re_intl_other_prices.go
  pkg/services/ghcimport/import_re_intl_other_prices_test.go
  pkg/services/ghcimport/import_re_intl_prices.go
  pkg/services/ghcimport/import_re_intl_prices_test.go
  pkg/services/ghcimport/load_service_map.go
  pkg/services/ghcimport/load_service_map_test.go
Labels: A-Team

#3268 [MB-680] Add parser for sheet 2c Domestic Other Prices
  pkg/models/stage_pricing.go
  pkg/parser/pricing/fixtures/8_2c_domestic_other_prices_pack_golden.csv
  pkg/parser/pricing/fixtures/8_2c_domestic_other_prices_sit_golden.csv
  pkg/parser/pricing/parse.go
  pkg/parser/pricing/parse_domestic_linehaul_prices.go
  pkg/parser/pricing/parse_domestic_other_prices.go
  pkg/parser/pricing/parse_domestic_other_prices_test.go
  pkg/parser/pricing/parse_domestic_service_area_prices.go
  pkg/parser/pricing/parse_international_prices.go
  pkg/parser/pricing/parse_nonstandard_location_prices.go
  pkg/parser/pricing/parse_other_intl_prices.go
Labels: A-Team

#3223 MB-701: add progear as weight ticket option
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/create_weight_ticket_documents_payload.go
  pkg/gen/internalmessages/move_document_payload.go
  pkg/gen/internalmessages/vehicle_options.go
  src/scenes/Moves/Ppm/WeightTicket.jsx
  swagger/internal.yaml
Labels: roci

#3261 MB-700: update first progear question and add a second
  migrations/20191227144832_add_has_progear_to_personally_procured_moves.up.sql
  migrations_manifest.txt
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/create_personally_procured_move_payload.go
  pkg/gen/internalmessages/patch_personally_procured_move_payload.go
  pkg/gen/internalmessages/personally_procured_move_payload.go
  pkg/gen/internalmessages/update_personally_procured_move_payload.go
  pkg/handlers/internalapi/personally_procured_move.go
  pkg/models/personally_procured_move.go
  src/scenes/Moves/Ppm/Weight.jsx
  swagger/internal.yaml
Labels: roci

#3276 Include new Pro-Gear fields in Office Estimates Panel on PPM Tab
  pkg/gen/internalapi/embedded_spec.go
  pkg/handlers/internalapi/personally_procured_move.go
  src/scenes/Office/Ppm/PPMEstimatesPanel.jsx
  swagger/internal.yaml
Labels: roci

#3280 Remove spouse pro gear question
  src/scenes/Orders/Orders.jsx
  src/scenes/Review/EditOrders.jsx
Labels: roci

#3253 add audit logging to create payment request handler
  pkg/handlers/primeapi/payment_request.go
  pkg/handlers/primeapi/payment_request_test.go
  pkg/services/audit/audit.go
  pkg/services/audit/audit_test.go
Labels: A-Team

#3295 MB-608 ma add role name column to Roles table
  migrations/20200109025141_add_names_to_roles_table.up.sql
  migrations_manifest.txt
  pkg/auth/authentication/authgch_test.go
  pkg/models/roles/roles.go
Labels: roci

#3134 use SM dest duty station for calculating move cost: 169655057
  cypress/integration/mymove/ppm.js
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalapi/internaloperations/ppm/show_p_p_m_estimate_parameters.go
  pkg/gen/internalapi/internaloperations/ppm/show_p_p_m_estimate_urlbuilder.go
  pkg/gen/internalapi/internaloperations/ppm/show_p_p_m_incentive_parameters.go
  pkg/gen/internalapi/internaloperations/ppm/show_p_p_m_incentive_urlbuilder.go
  pkg/gen/internalapi/internaloperations/ppm/show_p_p_m_sit_estimate_parameters.go
  pkg/gen/internalapi/internaloperations/ppm/show_p_p_m_sit_estimate_urlbuilder.go
  pkg/handlers/internalapi/orders.go
  pkg/handlers/internalapi/personally_procured_move.go
  pkg/handlers/internalapi/personally_procured_move_estimate.go
  pkg/handlers/internalapi/personally_procured_move_estimate_test.go
  pkg/handlers/internalapi/personally_procured_move_incentive.go
  pkg/handlers/internalapi/personally_procured_move_incentive_test.go
  pkg/handlers/internalapi/personally_procured_move_shared.go
  pkg/handlers/internalapi/personally_procured_move_shared_test.go
  pkg/handlers/internalapi/personally_procured_move_sit_estimate.go
  pkg/handlers/internalapi/personally_procured_move_sit_estimate_test.go
  pkg/handlers/internalapi/personally_procured_move_test.go
  pkg/handlers/internalapi/service_members.go
  pkg/handlers/internalapi/users.go
  pkg/models/duty_station.go
  pkg/models/move.go
  pkg/models/move_test.go
  pkg/models/order.go
  pkg/models/order_test.go
  pkg/models/personally_procured_move.go
  pkg/models/personally_procured_move_test.go
  pkg/paperwork/shipment_summary.go
  pkg/paperwork/shipment_summary_test.go
  pkg/route/zip_locale.go
  pkg/route/zip_locale_test.go
  src/scenes/Landing/MoveSummary.jsx
  src/scenes/Moves/Ppm/PaymentReview/index.jsx
  src/scenes/Moves/Ppm/Weight.jsx
  src/scenes/Moves/Ppm/api.js
  src/scenes/Office/Ppm/StorageReimbursementCalculator.jsx
  src/scenes/Office/Ppm/api.js
  src/scenes/Review/EditDateAndLocation.jsx
  src/scenes/Review/EditWeight.jsx
  src/scenes/Review/PPMShipmentSummary.jsx
  src/scenes/Review/Summary.jsx
  swagger/internal.yaml
Labels: ttv

#3291 Add additional customer fields to MTO
  migrations/20200108170523_add_customer_columns.up.sql
  migrations_manifest.txt
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/customer.go
  pkg/handlers/ghcapi/customer_test.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/models/customer.go
  pkg/testdatagen/make_customer.go
  src/scenes/Office/TOO/customerDetails.jsx
  swagger/ghc.yaml
Labels: roci

#3297 Add entitlements fields to MTO view
  migrations/20200109170045_remove_entitlments_columns.up.sql
  migrations/20200109182812_add_authorized_weight_columns.up.sql
  migrations_manifest.txt
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/entitlements.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/entitlements.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/move_order_test.go
  pkg/handlers/primeapi/internal/payloads/model_to_payload.go
  pkg/models/ghc_entitlements.go
  pkg/models/ghc_entitlements_test.go
  pkg/testdatagen/make_entitlement.go
  pkg/testdatagen/make_move_order.go
  src/scenes/Office/TOO/customerDetails.jsx
  swagger/ghc.yaml
  swagger/prime.yaml
Labels: roci

#3284 Don't allow short haul moves in SM workflow
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalapi/internaloperations/ppm/show_p_p_m_estimate_responses.go
  pkg/gen/internalapi/internaloperations/ppm/show_p_p_m_incentive_responses.go
  pkg/gen/internalapi/internaloperations/ppm/show_p_p_m_sit_estimate_responses.go
  pkg/handlers/errors.go
  pkg/route/errors.go
  pkg/route/here_planner.go
  pkg/route/planner.go
  pkg/route/planner_test.go
  src/scenes/Moves/Ppm/Weight.jsx
  src/scenes/Moves/Ppm/Weight.test.js
  src/scenes/Review/EditWeight.jsx
  src/scenes/Review/PPMShipmentSummary.jsx
  swagger/internal.yaml
Labels: ttv

#3289 Create a new Pro-Gear Weight Section in Office PPM Tab
  cypress/integration/mymove/ppm.js
  cypress/integration/mymove/ppmCloseout.js
  cypress/integration/office/documentViewer.js
  migrations/20200108171243_rename_vehicle_options.up.sql
  migrations_manifest.txt
  pkg/db/utilities/utilities_test.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/create_weight_ticket_documents_payload.go
  pkg/gen/internalmessages/move_document_payload.go
  pkg/gen/internalmessages/vehicle_options.go
  pkg/gen/internalmessages/weight_ticket_set_type.go
  pkg/handlers/internalapi/move_documents.go
  pkg/handlers/internalapi/move_documents_test.go
  pkg/handlers/internalapi/weight_ticket_set_documents.go
  pkg/handlers/internalapi/weight_ticket_set_documents_test.go
  pkg/models/move_documents_extractor.go
  pkg/models/weight_ticket_set_document.go
  pkg/models/weight_ticket_set_document_test.go
  pkg/services/move_documents/weight_ticket_updater.go
  pkg/services/move_documents/weight_ticket_updater_test.go
  pkg/testdatagen/make_weight_ticket_set_document.go
  src/scenes/Moves/Ppm/PaymentReview/WeightTicketListItem.jsx
  src/scenes/Moves/Ppm/WeightTicket.jsx
  src/scenes/Moves/Ppm/WeightTicket.test.js
  src/scenes/Office/DocumentViewer/DocumentDetailPanel.jsx
  src/scenes/Office/MoveInfo.jsx
  src/scenes/Office/Ppm/NetWeightPanel.jsx
  src/scenes/Office/Ppm/WeightsPanel.jsx
  src/shared/Entities/modules/moveDocuments.js
  src/shared/Entities/modules/moveDocuments.test.js
  src/shared/Entities/modules/weightTicketSetDocuments.js
  src/shared/constants.js
  swagger/internal.yaml
Labels: roci

#3283 MB-714 Import data from xlsx sheet 2c Domestic Other Prices into rate engine tables
  pkg/services/ghcimport/fixtures/stage_ghc_pricing.sql
  pkg/services/ghcimport/ghc_rateengine_importer.go
  pkg/services/ghcimport/import_re_domestic_other_prices.go
  pkg/services/ghcimport/import_re_domestic_other_prices_test.go
Labels: A-Team

#3339 modify service param key enum
  migrations/20200115164752_modify_service_item_param_key_enum.up.sql
  migrations_manifest.txt
Labels: A-Team

#3334 Add auditing log for when MTO is made available to prime
  pkg/handlers/ghcapi/move_task_order.go
  pkg/handlers/ghcapi/move_task_order_test.go
  pkg/services/audit/audit.go
Labels: roci

#3292 Add importers for management, counseling services, task order fees, a…
  migrations/20200106225354_alter_factor_hundredths_type.up.sql
  migrations/20200114001528_create_alter_fk_on_shipment_type_prices.up.sql
  migrations/20200114010154_drop_shipment_type_tables.up.sql
  migrations_manifest.txt
  pkg/models/re_shipment_type.go
  pkg/models/re_shipment_type_price.go
  pkg/models/re_shipment_type_price_test.go
  pkg/models/re_shipment_type_test.go
  pkg/services/ghcimport/ghc_rateengine_importer.go
  pkg/services/ghcimport/ghc_rateengine_importer_test.go
  pkg/services/ghcimport/import_re_contract_years.go
  pkg/services/ghcimport/import_re_contract_years_test.go
  pkg/services/ghcimport/import_re_domestic_accessorial_prices.go
  pkg/services/ghcimport/import_re_domestic_accessorial_prices_test.go
  pkg/services/ghcimport/import_re_intl_accessorial_prices.go
  pkg/services/ghcimport/import_re_intl_accessorial_prices_test.go
  pkg/services/ghcimport/import_re_shipment_type_prices.go
  pkg/services/ghcimport/import_re_shipment_type_prices_test.go
  pkg/services/ghcimport/import_re_task_order_fees.go
  pkg/services/ghcimport/import_re_task_order_fees_test.go
  pkg/services/ghcimport/shared.go
  pkg/services/ghcimport/shared_test.go
Labels: A-Team

#3360 modify ADR approvers
  .github/CODEOWNERS
Labels: ttv

#3374 Uncomment e2e tests
  cypress/integration/mymove/ppmCloseout.js
Labels: ttv

#3324 TOO views requested shipments
  migrations/20200113173707_add_shipment_type_to_mto_shipments.up.sql
  migrations_manifest.txt
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/mto_shipment/list_m_t_o_shipments.go
  pkg/gen/ghcapi/ghcoperations/mto_shipment/list_m_t_o_shipments_parameters.go
  pkg/gen/ghcapi/ghcoperations/mto_shipment/list_m_t_o_shipments_responses.go
  pkg/gen/ghcapi/ghcoperations/mto_shipment/list_m_t_o_shipments_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/ghcmessages/m_t_o_shipment.go
  pkg/gen/ghcmessages/m_t_o_shipments.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/mto_shipments.go
  pkg/handlers/ghcapi/mto_shipments_test.go
  pkg/models/mto_shipments.go
  pkg/testdatagen/make_mto_shipment.go
  src/scenes/Office/TOO/customerDetails.jsx
  src/shared/Entities/modules/mtoShipments.js
  src/shared/Entities/schema.js
  swagger/ghc.yaml
Labels: roci

#3375 Log dev server output
  .gitignore
  Makefile
Labels: roci

#3341 MB-673 Make TIO office user to test
  pkg/testdatagen/scenario/e2ebasic.go
Labels: ttv

#3327 MB-676 Prime view mto service items
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/m_t_o_service_item.go
  pkg/gen/primemessages/m_t_o_service_items.go
  pkg/gen/primemessages/m_t_o_service_itemstatus.go
  pkg/gen/primemessages/move_task_order.go
  pkg/handlers/primeapi/internal/payloads/model_to_payload.go
  pkg/handlers/primeapi/move_task_order.go
  pkg/handlers/primeapi/move_task_order_test.go
  swagger/prime.yaml
Labels: ttv

#3227 Optionally create GHC models when a move is submitted.
  .envrc
  cmd/milmove/serve.go
  pkg/cli/featureflag.go
  pkg/handlers/internalapi/moves.go
  pkg/models/convert.go
  pkg/models/convert_test.go
Labels: roci

#3394 Update README.md
  README.md
Labels: roci

#3287 MB-695 Write API implementation that takes Proof of Service as input and puts metadata in database
  pkg/gen/primeapi/configure_mymove.go
  pkg/gen/primeapi/doc.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/mymove_api.go
  pkg/gen/primeapi/primeoperations/uploads/create_upload.go
  pkg/gen/primeapi/primeoperations/uploads/create_upload_parameters.go
  pkg/gen/primeapi/primeoperations/uploads/create_upload_responses.go
  pkg/gen/primeapi/primeoperations/uploads/create_upload_urlbuilder.go
  pkg/gen/primemessages/payment_request.go
  pkg/gen/primemessages/proof_of_service_docs.go
  pkg/gen/primemessages/upload.go
  pkg/handlers/primeapi/testdata/test.pdf
  pkg/handlers/primeapi/upload.go
  pkg/handlers/primeapi/upload_test.go
  pkg/models/payment_request.go
  pkg/models/proof_of_service_doc.go
  pkg/services/mocks/PaymentRequestUploadCreator.go
  pkg/services/payment_request.go
  pkg/services/payment_request/logger.go
  pkg/services/payment_request/payment_request_service_test.go
  pkg/services/payment_request/testdata/test.pdf
  pkg/services/payment_request/testdata/test.txt
  pkg/services/payment_request/upload_creator.go
  pkg/services/payment_request/upload_creator_test.go
  pkg/uploader/allowed_file_types.go
  pkg/uploader/allowed_file_types_test.go
  pkg/uploader/uploader.go
  swagger/prime.yaml
Labels: A-Team

#3299 MB-608 Assign roles to users via admin interface
  migrations/20200122221118_add_deleted_at_column_to_usersRoles_table.up.sql
  migrations_manifest.txt
  pkg/gen/adminapi/embedded_spec.go
  pkg/gen/adminmessages/office_user.go
  pkg/gen/adminmessages/office_user_role.go
  pkg/gen/adminmessages/office_user_update_payload.go
  pkg/gen/adminmessages/role.go
  pkg/handlers/adminapi/api.go
  pkg/handlers/adminapi/office_users.go
  pkg/handlers/adminapi/office_users_test.go
  pkg/models/users_roles.go
  pkg/services/users_roles.go
  pkg/services/users_roles/users_roles.go
  pkg/services/users_roles/users_roles_service_test.go
  pkg/services/users_roles/users_roles_test.go
  src/scenes/SystemAdmin/OfficeUsers/OfficeUserEdit.jsx
  src/scenes/SystemAdmin/OfficeUsers/OfficeUserList.jsx
  src/scenes/SystemAdmin/OfficeUsers/OfficeUserShow.jsx
  src/scenes/SystemAdmin/shared/RolesCheckboxes.jsx
  src/scenes/SystemAdmin/shared/rest_provider.js
  swagger/admin.yaml
Labels: roci

#3408 Prevent submitting move if resuming short haul move
  src/scenes/Moves/Ppm/Weight.jsx
  src/scenes/Review/PPMShipmentSummary.jsx
  src/scenes/Review/PPMShipmentSummary.test.jsx
  src/scenes/Review/Review.jsx
  src/shared/WizardPage/index.jsx
  src/shared/WizardPage/index.test.js
  src/shared/incentive.js
  src/shared/incentive.test.js
Labels: ttv

#3342 Clear session when attempting to load the devlocal user list
  cmd/milmove/serve.go
  pkg/auth/authentication/devlocal.go
Labels: roci

#3407 Revert "add audit logging to creating payment request"
  pkg/handlers/primeapi/payment_request.go
Labels: A-Team

#3335 Add Order details to MoveOrder table
  migrations/20200113183355_add-additional-move-order-fields.up.sql
  migrations_manifest.txt
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/move_order.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/models/convert.go
  pkg/models/move_order.go
  pkg/testdatagen/make_move_order.go
  src/scenes/Office/TOO/customerDetails.jsx
  swagger/ghc.yaml
Labels: roci

#3404 Add endpoint and service object for updating shipment status
  migrations/20200113173707_add_shipment_type_to_mto_shipments.up.sql
  migrations/20200121184927_add_status_to_mto_shipments.up.sql
  migrations_manifest.txt
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/mto_shipment/patch_m_t_o_shipment_status.go
  pkg/gen/ghcapi/ghcoperations/mto_shipment/patch_m_t_o_shipment_status_parameters.go
  pkg/gen/ghcapi/ghcoperations/mto_shipment/patch_m_t_o_shipment_status_responses.go
  pkg/gen/ghcapi/ghcoperations/mto_shipment/patch_m_t_o_shipment_status_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/ghcmessages/m_t_o_service_item.go
  pkg/gen/ghcmessages/m_t_o_shipment.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/mto_shipments.go
  pkg/handlers/ghcapi/mto_shipments_test.go
  pkg/models/mto_shipments.go
  pkg/models/mto_shipments_test.go
  pkg/services/mocks/MTOShipmentStatusUpdater.go
  pkg/services/mto_shipment.go
  pkg/services/mto_shipment/mto_shipment_service_test.go
  pkg/services/mto_shipment/mto_shipment_status_updater.go
  pkg/services/mto_shipment/mto_shipment_status_updater_test.go
  pkg/testdatagen/make_mto_shipment.go
  swagger/ghc.yaml
Labels: ttv

#3413 first part of database migration, add column mto_service_item_id to r…
  migrations/20200124172904_alter_table_payment_service_items_column_service_item_id.up.sql
  migrations_manifest.txt
Labels: A-Team

#3430 Create prime submit shipments endpoint
  go.mod
  pkg/gen/primeapi/configure_mymove.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/mto_shipment/update_m_t_o_shipment.go
  pkg/gen/primeapi/primeoperations/mto_shipment/update_m_t_o_shipment_parameters.go
  pkg/gen/primeapi/primeoperations/mto_shipment/update_m_t_o_shipment_responses.go
  pkg/gen/primeapi/primeoperations/mto_shipment/update_m_t_o_shipment_urlbuilder.go
  pkg/gen/primeapi/primeoperations/mymove_api.go
  pkg/gen/primemessages/m_t_o_shipment.go
  pkg/gen/primemessages/m_t_o_shipment_type.go
  pkg/gen/primemessages/m_t_o_shipments.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/mto_shipment.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/handlers/primeapi/api.go
  pkg/handlers/primeapi/internal/payloads/model_to_payload.go
  pkg/handlers/primeapi/mto_shipment.go
  pkg/handlers/primeapi/mto_shipment_test.go
  pkg/services/mocks/DomesticFuelSurchargePricer.go
  pkg/services/mocks/MTOShipmentFetcher.go
  pkg/services/mocks/MTOShipmentUpdater.go
  pkg/services/mocks/UserRoleAssociator.go
  pkg/services/move_task_order/move_task_order_service_test.go
  pkg/services/mto_shipment.go
  pkg/services/mto_shipment/mto_shipment_fetcher.go
  pkg/services/mto_shipment/mto_shipment_fetcher_test.go
  pkg/services/mto_shipment/mto_shipment_service_test.go
  pkg/services/mto_shipment/mto_shipment_updater.go
  pkg/services/mto_shipment/mto_shipment_updater_test.go
  swagger/prime.yaml
Labels: roci
