Repository transcom/mymove, pull requests merged in 2020-05, with the labels that each got.

#4026 MB-2496 fix storybook tests job and reenable
  scripts/run-storybook-tests
  scripts/start-storybook-tests
Labels: A-Team

#4020 Fix null dereference in moveTaskOrder payload creation
  pkg/handlers/primeapi/internal/payloads/model_to_payload.go
Labels: roci

#3965 [MB-2143] Add Inline form example for stacked tables
  .loki/reference/chrome_iphone7_Components_Button_active.png
  .loki/reference/chrome_iphone7_Components_Button_default.png
  .loki/reference/chrome_iphone7_Components_Button_disabled.png
  .loki/reference/chrome_iphone7_Components_Button_focus.png
  .loki/reference/chrome_iphone7_Components_Button_hover.png
  .loki/reference/chrome_iphone7_Components_Icon_Buttons_docs.png
  .loki/reference/chrome_iphone7_Components_Icon_Buttons_edit.png
  .loki/reference/chrome_iphone7_Components_StackedTable_default.png
  .loki/reference/chrome_iphone7_Components_StackedTable_with_buttons_to_edit.png
  .loki/reference/chrome_iphone7_Components_StackedTable_with_some_buttons_to_edit.png
  .loki/reference/chrome_iphone7_Components_Tables_Table_Elements.png
  .loki/reference/chrome_iphone7_Samples_Form_inline_first_name.png
  .loki/reference/chrome_laptop_Components_Button_active.png
  .loki/reference/chrome_laptop_Components_Button_default.png
  .loki/reference/chrome_laptop_Components_Button_disabled.png
  .loki/reference/chrome_laptop_Components_Button_focus.png
  .loki/reference/chrome_laptop_Components_Button_hover.png
  .loki/reference/chrome_laptop_Components_Icon_Buttons_docs.png
  .loki/reference/chrome_laptop_Components_Icon_Buttons_edit.png
  .loki/reference/chrome_laptop_Components_StackedTable_default.png
  .loki/reference/chrome_laptop_Components_StackedTable_with_buttons_to_edit.png
  .loki/reference/chrome_laptop_Components_StackedTable_with_some_buttons_to_edit.png
  .loki/reference/chrome_laptop_Components_Tables_Standard_Tables.png
  .loki/reference/chrome_laptop_Components_Tables_Table_Elements.png
  .loki/reference/chrome_laptop_Samples_Form_inline_first_name.png
  .storybook/addons.js
  dangerfile.ts
  package.json
  src/components/.eslintrc
  src/components/form/ErrorMessage.jsx
  src/components/form/ErrorMessage.test.jsx
  src/components/form/Form.jsx
  src/components/form/Form.test.jsx
  src/components/form/IconButtons.jsx
  src/components/form/IconButtons.test.jsx
  src/components/form/StackedTableRowForm.jsx
  src/components/form/StackedTableRowForm.module.scss
  src/components/form/StackedTableRowForm.test.jsx
  src/components/form/fields/TextInput.jsx
  src/components/form/fields/TextInput.test.jsx
  src/components/form/fields/index.js
  src/components/form/index.js
  src/config/.eslintrc
  src/constants/.eslintrc
  src/containers/.eslintrc
  src/helpers/.eslintrc
  src/layout/.eslintrc
  src/pages/.eslintrc
  src/shared/images/edit-24px.svg
  src/shared/styles/_custom.scss
  src/shared/styles/_overrides.scss
  src/stories/.eslintrc
  src/stories/buttons.stories.jsx
  src/stories/index.stories.jsx
  src/stories/samples.stories.jsx
  src/stories/stackedTable.stories.jsx
  yarn.lock
Labels: A-Team

#3971 MB-1655 create endpoints for Prime to create additional MTO shipments
  pkg/gen/primeapi/configure_mymove.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/mto_shipment/create_m_t_o_shipment.go
  pkg/gen/primeapi/primeoperations/mto_shipment/create_m_t_o_shipment_parameters.go
  pkg/gen/primeapi/primeoperations/mto_shipment/create_m_t_o_shipment_responses.go
  pkg/gen/primeapi/primeoperations/mto_shipment/create_m_t_o_shipment_urlbuilder.go
  pkg/gen/primeapi/primeoperations/mymove_api.go
  pkg/gen/primeclient/mto_shipment/create_m_t_o_shipment_parameters.go
  pkg/gen/primeclient/mto_shipment/create_m_t_o_shipment_responses.go
  pkg/gen/primeclient/mto_shipment/mto_shipment_client.go
  pkg/gen/primemessages/create_shipment_payload.go
  pkg/handlers/primeapi/api.go
  pkg/handlers/primeapi/internal/payloads/payload_to_model.go
  pkg/handlers/primeapi/mto_shipment.go
  pkg/handlers/primeapi/mto_shipment_test.go
  pkg/services/mocks/MTOServiceItemUpdater.go
  pkg/services/mocks/MTOShipmentCreator.go
  pkg/services/mto_shipment.go
  pkg/services/mto_shipment/mto_shipment_creator.go
  pkg/services/mto_shipment/mto_shipment_creator_test.go
  pkg/testdatagen/make_mto_service_item.go
  pkg/testdatagen/shared.go
  swagger/prime.yaml
Labels: A-Team

#4017 MB-2464 [JM] api test proof of service upload
  cmd/prime-api-client/create_payment_request_upload.go
  cmd/prime-api-client/main.go
  cmd/prime-api-client/shared.go
  pkg/handlers/primeapi/upload.go
Labels: A-Team

#4013 MB-2442 Connect move details to TOO queue skeleton
  src/scenes/Office/TOO/too.jsx
  src/scenes/Office/index.jsx
Labels: ttv

#4039 MB-2523 Add CreatedAt and UpdatedAt to MTOAgent model
  pkg/handlers/primeapi/internal/payloads/model_to_payload.go
Labels: roci

#4049 Update check-aws-vault-version to look for aws-vault 5.4
  scripts/check-aws-vault-version
Labels: A-Team

#4011 MB-2320 Prime API update shipment errors
  cmd/prime-api-client/main.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/mto_shipment/update_m_t_o_shipment.go
  pkg/gen/primeapi/primeoperations/mto_shipment/update_m_t_o_shipment_parameters.go
  pkg/gen/primeapi/primeoperations/mto_shipment/update_m_t_o_shipment_responses.go
  pkg/gen/primeapi/primeoperations/mto_shipment/update_m_t_o_shipment_urlbuilder.go
  pkg/gen/primeapi/primeoperations/mymove_api.go
  pkg/gen/primeclient/mto_shipment/mto_shipment_client.go
  pkg/gen/primeclient/mto_shipment/update_m_t_o_shipment_parameters.go
  pkg/gen/primeclient/mto_shipment/update_m_t_o_shipment_responses.go
  pkg/gen/primemessages/m_t_o_agent.go
  pkg/gen/primemessages/m_t_o_shipment.go
  pkg/gen/primemessages/validation_error.go
  pkg/handlers/errors.go
  pkg/handlers/primeapi/internal/payloads/model_to_payload.go
  pkg/handlers/primeapi/mto_shipment.go
  pkg/handlers/primeapi/mto_shipment_test.go
  pkg/handlers/supportapi/mto_shipment_test.go
  pkg/services/mto_shipment/mto_shipment_updater.go
  pkg/testdatagen/testdata/update_mto_shipment.json
  swagger/prime.yaml
Labels: roci

#3923 Kim mb 2187 weight estimates redux refactor
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/patch_personally_procured_move_payload.go
  pkg/handlers/internalapi/personally_procured_move.go
  pkg/handlers/internalapi/personally_procured_move_estimate.go
  src/scenes/Landing/MoveSummary.jsx
  src/scenes/Landing/MoveSummary/PpmMoveDetails.jsx
  src/scenes/Landing/MoveSummary/SubmittedPpmMoveDetails.jsx
  src/scenes/Landing/MoveSummary/SubmittedPpmMoveSummary.jsx
  src/scenes/Landing/index.jsx
  src/scenes/Moves/Ppm/PaymentReview/index.jsx
  src/scenes/Moves/Ppm/Weight.jsx
  src/scenes/Moves/Ppm/Weight.test.js
  src/scenes/Moves/Ppm/WeightTicket.jsx
  src/scenes/Moves/Ppm/api.js
  src/scenes/Moves/Ppm/ducks.js
  src/scenes/Moves/Ppm/ducks.test.js
  src/scenes/Review/EditWeight.jsx
  src/scenes/Review/PPMShipmentSummary.jsx
  src/shared/Entities/modules/ppms.js
  src/shared/Entities/schema.js
  src/shared/incentive.js
  swagger/internal.yaml
Labels: moose

#4055 remove un-needed setPendingPpmWeight
  src/scenes/Moves/Ppm/ducks.js
Labels: moose

#3905 Don't log filenames: MB-2190
  pkg/handlers/internalapi/uploads.go
  pkg/uploader/uploader.go
Labels: moose

#4050 [MB-1752] Import May 2020 discount rates
  migrations/app/migrations_manifest.txt
  migrations/app/secure/20200505194253_import_rates_may_2020.up.sql
Labels: A-Team

#4031 MB-1446 Requested service items table
  .loki/reference/chrome_iphone7_Components_Tables_Service_Item_Tables.png
  .loki/reference/chrome_iphone7_TOO_TIO_Components_RequestedServiceItemsTable_default.png
  .loki/reference/chrome_laptop_Components_Tables_Service_Item_Tables.png
  .loki/reference/chrome_laptop_TOO_TIO_Components_RequestedServiceItemsTable_default.png
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/m_t_o_service_item.go
  pkg/handlers/ghcapi/mto_service_items.go
  src/components/Office/RequestedServiceItemsTable.jsx
  src/components/Office/RequestedServiceItemsTable.test.jsx
  src/components/Office/requestedServiceItemsTable.module.scss
  src/components/ServiceItemTableHasImg/index.jsx
  src/components/ServiceItemTableHasImg/index.test.jsx
  src/pages/TOO/moveTaskOrder.jsx
  src/shared/Entities/modules/mtoServiceItems.js
  src/shared/styles/_custom.scss
  src/stories/requestedServiceItems.stories.jsx
  src/stories/tables.stories.jsx
  swagger/ghc.yaml
Labels: ttv

#4064 Remove validations requiring pickup and destination address on MTOShipment
  pkg/handlers/primeapi/internal/payloads/payload_to_model.go
  pkg/models/mto_shipments.go
  pkg/models/mto_shipments_test.go
Labels: roci

#4051 Add link to new how-to documentation and create wiki page with docs
  docs/frontend.md
Labels: A-Team

#4054 [MB-2521] Setup default lookups for ServiceItemParamKeys
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20200511185126_make_service_item_param_key_unique.up.sql
  pkg/models/service_item_param_key.go
  pkg/models/service_item_param_key_test.go
  pkg/payment_request/service_param_list_valid.go
  pkg/payment_request/service_param_list_valid_test.go
  pkg/payment_request/service_param_value_lookups/distance_zip3_lookup.go
  pkg/payment_request/service_param_value_lookups/not_implemented_lookup.go
  pkg/payment_request/service_param_value_lookups/service_area_origin_lookup.go
  pkg/payment_request/service_param_value_lookups/service_param_value_lookups.go
  pkg/payment_request/service_param_value_lookups/weight_actual_lookup.go
  pkg/payment_request/service_param_value_lookups/weight_billed_actual_lookup.go
  pkg/payment_request/service_param_value_lookups/weight_estimated_lookup.go
  pkg/payment_request/service_param_value_lookups/zip_dest_address_lookup.go
  pkg/payment_request/service_param_value_lookups/zip_pickup_address_lookup.go
  pkg/services/payment_request/payment_request_creator.go
  pkg/services/payment_request/payment_request_creator_test.go
  pkg/testdatagen/scenario/e2ebasic.go
Labels: A-Team

#4057 [MB-2549] Update prime and support swagger summary field to be a unique identifier
  cmd/prime-api-client/main.go
  cmd/prime-api-client/update_mto_shipment_status.go
  pkg/gen/primeapi/doc.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/move_task_order/fetch_m_t_o_updates.go
  pkg/gen/primeapi/primeoperations/move_task_order/get_move_task_order_customer.go
  pkg/gen/primeapi/primeoperations/move_task_order/update_m_t_o_post_counseling_information.go
  pkg/gen/primeapi/primeoperations/mto_service_item/create_m_t_o_service_item.go
  pkg/gen/primeapi/primeoperations/mto_shipment/create_m_t_o_shipment.go
  pkg/gen/primeapi/primeoperations/mto_shipment/update_m_t_o_shipment.go
  pkg/gen/primeapi/primeoperations/mymove_api.go
  pkg/gen/primeapi/primeoperations/payment_requests/create_payment_request.go
  pkg/gen/primeapi/primeoperations/uploads/create_upload.go
  pkg/gen/primeclient/move_task_order/move_task_order_client.go
  pkg/gen/primeclient/mto_service_item/mto_service_item_client.go
  pkg/gen/primeclient/mto_shipment/mto_shipment_client.go
  pkg/gen/primeclient/payment_requests/payment_requests_client.go
  pkg/gen/primeclient/uploads/uploads_client.go
  pkg/gen/supportapi/configure_mymove.go
  pkg/gen/supportapi/embedded_spec.go
  pkg/gen/supportapi/supportoperations/move_task_order/create_move_task_order.go
  pkg/gen/supportapi/supportoperations/move_task_order/get_move_task_order.go
  pkg/gen/supportapi/supportoperations/move_task_order/update_move_task_order_status.go
  pkg/gen/supportapi/supportoperations/mto_service_item/update_m_t_o_service_item_status.go
  pkg/gen/supportapi/supportoperations/mto_shipment/patch_m_t_o_shipment_status.go
  pkg/gen/supportapi/supportoperations/mto_shipment/patch_m_t_o_shipment_status_responses.go
  pkg/gen/supportapi/supportoperations/mto_shipment/update_m_t_o_shipment_status.go
  pkg/gen/supportapi/supportoperations/mto_shipment/update_m_t_o_shipment_status_parameters.go
  pkg/gen/supportapi/supportoperations/mto_shipment/update_m_t_o_shipment_status_responses.go
  pkg/gen/supportapi/supportoperations/mto_shipment/update_m_t_o_shipment_status_urlbuilder.go
  pkg/gen/supportapi/supportoperations/mymove_api.go
  pkg/gen/supportapi/supportoperations/payment_requests/update_payment_request_status.go
  pkg/gen/supportclient/move_task_order/move_task_order_client.go
  pkg/gen/supportclient/mto_service_item/mto_service_item_client.go
  pkg/gen/supportclient/mto_shipment/mto_shipment_client.go
  pkg/gen/supportclient/mto_shipment/patch_m_t_o_shipment_status_parameters.go
  pkg/gen/supportclient/mto_shipment/patch_m_t_o_shipment_status_responses.go
  pkg/gen/supportclient/mto_shipment/update_m_t_o_shipment_status_parameters.go
  pkg/gen/supportclient/mto_shipment/update_m_t_o_shipment_status_responses.go
  pkg/gen/supportclient/payment_requests/payment_requests_client.go
  pkg/gen/supportmessages/update_m_t_o_shipment_status.go
  pkg/handlers/primeapi/move_task_order.go
  pkg/handlers/supportapi/api.go
  pkg/handlers/supportapi/mto_shipment.go
  pkg/handlers/supportapi/mto_shipment_test.go
  swagger/prime.yaml
  swagger/support.yaml
Labels: roci

#4080 MB-2611 Create a prime api client call for Create MTO shipment
  cmd/prime-api-client/create_mto_shipment.go
  cmd/prime-api-client/main.go
Labels: A-Team

#4073 MB-1314 dockerfiles set non root user
  Dockerfile.migrations
  Dockerfile.migrations_local
  cmd/ecs-deploy/task_def.go
Labels: A-Team

#4042 [MB-2477] Add trace middleware to prime and support api
  cmd/milmove/serve.go
Labels: roci

#4068 [MB-2432] Remove unused getMoveTaskOrderCustomer endpoint
  pkg/gen/primeapi/configure_mymove.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/move_task_order/get_move_task_order_customer.go
  pkg/gen/primeapi/primeoperations/move_task_order/get_move_task_order_customer_parameters.go
  pkg/gen/primeapi/primeoperations/move_task_order/get_move_task_order_customer_responses.go
  pkg/gen/primeapi/primeoperations/move_task_order/get_move_task_order_customer_urlbuilder.go
  pkg/gen/primeapi/primeoperations/mymove_api.go
  pkg/gen/primeclient/move_task_order/get_move_task_order_customer_parameters.go
  pkg/gen/primeclient/move_task_order/get_move_task_order_customer_responses.go
  pkg/gen/primeclient/move_task_order/move_task_order_client.go
  swagger/prime.yaml
Labels: roci

#4059 MB-2476 update prime api endpoint paths
  cmd/prime-api-client/create_mto_service_item.go
  cmd/prime-api-client/main.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/mto_service_item/create_m_t_o_service_item.go
  pkg/gen/primeapi/primeoperations/mto_service_item/create_m_t_o_service_item_parameters.go
  pkg/gen/primeapi/primeoperations/mto_service_item/create_m_t_o_service_item_urlbuilder.go
  pkg/gen/primeapi/primeoperations/mto_shipment/create_m_t_o_shipment.go
  pkg/gen/primeapi/primeoperations/mto_shipment/create_m_t_o_shipment_parameters.go
  pkg/gen/primeapi/primeoperations/mto_shipment/create_m_t_o_shipment_responses.go
  pkg/gen/primeapi/primeoperations/mto_shipment/create_m_t_o_shipment_urlbuilder.go
  pkg/gen/primeapi/primeoperations/mymove_api.go
  pkg/gen/primeclient/mto_service_item/create_m_t_o_service_item_parameters.go
  pkg/gen/primeclient/mto_service_item/create_m_t_o_service_item_responses.go
  pkg/gen/primeclient/mto_service_item/mto_service_item_client.go
  pkg/gen/primeclient/mto_shipment/create_m_t_o_shipment_parameters.go
  pkg/gen/primeclient/mto_shipment/create_m_t_o_shipment_responses.go
  pkg/gen/primeclient/mto_shipment/mto_shipment_client.go
  pkg/gen/primemessages/create_shipment_payload.go
  pkg/handlers/primeapi/internal/payloads/payload_to_model.go
  pkg/handlers/primeapi/mto_service_item.go
  pkg/handlers/primeapi/mto_service_item_test.go
  pkg/handlers/primeapi/mto_shipment.go
  pkg/handlers/primeapi/mto_shipment_test.go
  swagger/prime.yaml
Labels: roci

#4087 MB-2528 Make responses using $ref more uniform
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/move_task_order/fetch_m_t_o_updates_responses.go
  pkg/gen/primeapi/primeoperations/move_task_order/update_m_t_o_post_counseling_information_responses.go
  pkg/gen/primeapi/primeoperations/mto_service_item/create_m_t_o_service_item_responses.go
  pkg/gen/primeapi/primeoperations/mto_shipment/update_m_t_o_shipment_responses.go
  pkg/gen/primeapi/primeoperations/payment_requests/create_payment_request_responses.go
  pkg/gen/primeapi/primeoperations/uploads/create_upload_responses.go
  pkg/gen/primeclient/move_task_order/fetch_m_t_o_updates_responses.go
  pkg/gen/primeclient/move_task_order/update_m_t_o_post_counseling_information_responses.go
  pkg/gen/primeclient/mto_service_item/create_m_t_o_service_item_responses.go
  pkg/gen/primeclient/mto_shipment/update_m_t_o_shipment_responses.go
  pkg/gen/primeclient/payment_requests/create_payment_request_responses.go
  pkg/gen/primeclient/uploads/create_upload_responses.go
  swagger/prime.yaml
Labels: roci

#4093 [MB-2533] Update fetch MTOs handler to return additional payment request data
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/payment_request.go
  pkg/gen/primemessages/payment_service_item.go
  pkg/gen/primemessages/payment_service_item_param.go
  pkg/gen/primemessages/payment_service_item_params.go
  pkg/gen/primemessages/payment_service_item_status.go
  pkg/gen/primemessages/payment_service_items.go
  pkg/gen/primemessages/service_item_param_name.go
  pkg/gen/primemessages/service_item_param_origin.go
  pkg/gen/primemessages/service_item_param_type.go
  pkg/handlers/primeapi/internal/payloads/model_to_payload.go
  pkg/handlers/primeapi/move_task_order.go
  pkg/handlers/primeapi/move_task_order_test.go
  pkg/models/service_item_param_key.go
  pkg/payment_request/service_param_value_lookups/distance_zip5_lookup_test.go
  pkg/payment_request/service_param_value_lookups/requested_pickup_date_lookup_test.go
  pkg/services/payment_request/payment_request_creator_test.go
  pkg/services/payment_request/upload_creator_test.go
  pkg/testdatagen/constants.go
  pkg/testdatagen/make_payment_request.go
  pkg/testdatagen/make_payment_service_item.go
  pkg/testdatagen/make_payment_service_item_param.go
  pkg/testdatagen/make_service_item_param_key.go
  pkg/testdatagen/shared.go
  swagger/prime.yaml
Labels: A-Team

#4102 MB-2564 Update the description for the create MTO shipment command
  cmd/prime-api-client/main.go
Labels: roci

#4091 MB-2557 alter tables to complete migration changes
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20200513151500_uploader_refactor_zero_down_alter_tables.up.sql
Labels: A-Team

#4070 [MB-2550] Change prime-api-client command names to match their operationId
  cmd/prime-api-client/main.go
  scripts/run-e2e-mtls-test-docker
Labels: roci

#4086 MB-2335 TOO customer info table
  .loki/reference/chrome_iphone7_TOO_TIO_Components_CustomerInfoTable_Customer_Info_Table.png
  .loki/reference/chrome_laptop_TOO_TIO_Components_CustomerInfoTable_Customer_Info_Table.png
  src/components/Office/CustomerInfoTable.jsx
  src/components/Office/CustomerInfoTable.test.jsx
  src/stories/customerInfoTable.stories.jsx
Labels: ttv

#4111 MB-2482 Remove OrderType and OrderTypeDetail from MoveOrder payload
  pkg/gen/supportapi/embedded_spec.go
  pkg/gen/supportmessages/move_order.go
  pkg/handlers/supportapi/internal/payloads/model_to_payload.go
  pkg/handlers/supportapi/internal/payloads/payload_to_model.go
  swagger/support.yaml
Labels: roci

#4112 MB-2554 Add in FOUO component to display in all pages for office app
  src/scenes/Office/index.jsx
Labels: ttv

#4106 [MB-2654] Make PriceCents nullable/pointer for Payment Service Item
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20200515202122_payment_service_item_nullable_price.up.sql
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/payment_service_item.go
  pkg/handlers/primeapi/internal/payloads/model_to_payload.go
  pkg/models/payment_service_item.go
  pkg/models/payment_service_item_test.go
  pkg/services/payment_request/payment_request_creator.go
  pkg/testdatagen/make_payment_service_item.go
  swagger/prime.yaml
Labels: A-Team

#4088 Kim mb 2546 show requested incentive and weight
  cypress/integration/mymove/landingPages.js
  cypress/integration/mymove/ppm.js
  src/scenes/Landing/MoveSummary.jsx
  src/scenes/Landing/MoveSummary/ApprovedMoveSummary.jsx
  src/scenes/Landing/MoveSummary/PpmMoveDetails.jsx
  src/scenes/Landing/MoveSummary/PpmMoveDetails.module.scss
  src/scenes/Landing/MoveSummary/SubmittedPpmMoveDetails.jsx
  src/scenes/Review/PPMShipmentSummary.jsx
  src/shared/ToolTip/IconWithTooltip.jsx
  src/shared/incentive.js
  src/shared/styles/colors.scss
  src/shared/styles/themes.scss
Labels: Pamplemoose

#4101 MB-2494 Use ClientError for Prime and Support API responses
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/move_task_order/fetch_m_t_o_updates_responses.go
  pkg/gen/primeapi/primeoperations/move_task_order/update_m_t_o_post_counseling_information_responses.go
  pkg/gen/primeapi/primeoperations/mto_service_item/create_m_t_o_service_item_responses.go
  pkg/gen/primeapi/primeoperations/mto_shipment/create_m_t_o_shipment_responses.go
  pkg/gen/primeapi/primeoperations/mto_shipment/update_m_t_o_shipment_responses.go
  pkg/gen/primeapi/primeoperations/payment_requests/create_payment_request_responses.go
  pkg/gen/primeapi/primeoperations/uploads/create_upload_responses.go
  pkg/gen/primeclient/move_task_order/fetch_m_t_o_updates_responses.go
  pkg/gen/primeclient/move_task_order/update_m_t_o_post_counseling_information_responses.go
  pkg/gen/primeclient/mto_service_item/create_m_t_o_service_item_responses.go
  pkg/gen/primeclient/mto_shipment/create_m_t_o_shipment_responses.go
  pkg/gen/primeclient/mto_shipment/update_m_t_o_shipment_responses.go
  pkg/gen/primeclient/payment_requests/create_payment_request_responses.go
  pkg/gen/primeclient/uploads/create_upload_responses.go
  pkg/gen/supportapi/embedded_spec.go
  pkg/gen/supportapi/supportoperations/move_task_order/create_move_task_order_responses.go
  pkg/gen/supportapi/supportoperations/move_task_order/get_move_task_order_responses.go
  pkg/gen/supportapi/supportoperations/move_task_order/update_move_task_order_status_responses.go
  pkg/gen/supportapi/supportoperations/mto_service_item/update_m_t_o_service_item_status_responses.go
  pkg/gen/supportapi/supportoperations/mto_shipment/update_m_t_o_shipment_status_responses.go
  pkg/gen/supportapi/supportoperations/payment_requests/update_payment_request_status_responses.go
  pkg/gen/supportclient/move_task_order/create_move_task_order_responses.go
  pkg/gen/supportclient/move_task_order/get_move_task_order_responses.go
  pkg/gen/supportclient/move_task_order/update_move_task_order_status_responses.go
  pkg/gen/supportclient/mto_service_item/update_m_t_o_service_item_status_responses.go
  pkg/gen/supportclient/mto_shipment/update_m_t_o_shipment_status_responses.go
  pkg/gen/supportclient/payment_requests/update_payment_request_status_responses.go
  pkg/gen/supportmessages/validation_error.go
  pkg/handlers/errors.go
  pkg/handlers/primeapi/internal/payloads/model_to_payload.go
  pkg/handlers/primeapi/move_task_order.go
  pkg/handlers/primeapi/mto_service_item.go
  pkg/handlers/primeapi/mto_shipment.go
  pkg/handlers/primeapi/payment_request.go
  pkg/handlers/supportapi/internal/payloads/model_to_payload.go
  pkg/handlers/supportapi/move_task_order.go
  pkg/handlers/supportapi/mto_service_item.go
  pkg/handlers/supportapi/mto_shipment.go
  pkg/handlers/supportapi/mto_shipment_test.go
  pkg/handlers/supportapi/payment_request.go
  swagger/prime.yaml
  swagger/support.yaml
Labels: roci

#4065 MB-2441 Shipment display component
  .loki/reference/chrome_iphone7_Components_Containers_all.png
  .loki/reference/chrome_iphone7_Components_Left_Nav_layout.png
  .loki/reference/chrome_iphone7_Samples_Form_personal_info.png
  .loki/reference/chrome_iphone7_TOO_TIO_Components_RequestedShipments_with_details.png
  .loki/reference/chrome_iphone7_TOO_TIO_Components_RequestedShipments_with_no_details.png
  .loki/reference/chrome_iphone7_TOO_TIO_Components_ShipmentContainer_Shipment_Container.png
  .loki/reference/chrome_iphone7_TOO_TIO_Components_ShipmentDisplay_with_one_shipment_requested.png
  .loki/reference/chrome_iphone7_TOO_TIO_Components_ShipmentDisplay_with_two_shipment_requested.png
  .loki/reference/chrome_laptop_Components_Containers_all.png
  .loki/reference/chrome_laptop_Components_Left_Nav_layout.png
  .loki/reference/chrome_laptop_Samples_Form_personal_info.png
  .loki/reference/chrome_laptop_TOO_TIO_Components_RequestedShipments_with_details.png
  .loki/reference/chrome_laptop_TOO_TIO_Components_RequestedShipments_with_no_details.png
  .loki/reference/chrome_laptop_TOO_TIO_Components_ShipmentContainer_Shipment_Container.png
  .loki/reference/chrome_laptop_TOO_TIO_Components_ShipmentDisplay_with_one_shipment_requested.png
  .loki/reference/chrome_laptop_TOO_TIO_Components_ShipmentDisplay_with_two_shipment_requested.png
  src/components/Office/RequestedShipments.jsx
  src/components/Office/RequestedShipments.test.jsx
  src/components/Office/ShipmentContainer.jsx
  src/components/Office/ShipmentContainer.test.jsx
  src/components/Office/ShipmentDisplay.jsx
  src/components/Office/ShipmentDisplay.module.scss
  src/components/Office/ShipmentDisplay.test.jsx
  src/components/Office/requestedShipments.module.scss
  src/pages/.eslintrc
  src/shared/constants.js
  src/shared/icon/chevron-down.svg
  src/shared/styles/_custom.scss
  src/stories/requestedShipments.stories.jsx
  src/stories/shipmentContainer.stories.jsx
  src/stories/shipmentDisplay.stories.jsx
Labels: ttv

#4095 Kim mb 2188 get ppm sit estimate redux refactor
  pkg/handlers/internalapi/personally_procured_move.go
  pkg/handlers/internalapi/personally_procured_move_sit_estimate.go
  pkg/rateengine/rateengine.go
  src/scenes/Moves/Ppm/api.js
  src/scenes/Moves/Ppm/ducks.js
  src/scenes/Moves/Ppm/ducks.test.js
  src/scenes/Office/Ppm/StorageReimbursementCalculator.jsx
  src/scenes/Review/EditDateAndLocation.jsx
  src/shared/Entities/modules/ppms.js
  src/shared/Entities/schema.js
Labels: Pamplemoose

#4096 MB-2646 static zip3 lat long mappings added
  pkg/route/zip3_locale.go
  pkg/route/zip3_locale_test.go
Labels: A-Team

#4107 Kim mb 2189 remove clear ppm sit estimate
  src/scenes/Moves/Ppm/ducks.js
  src/scenes/Moves/Ppm/ducks.test.js
Labels: Pamplemoose

#4133 MB-2441 Connect shipment display component to move details page
  src/components/Office/ShipmentDisplay.jsx
  src/components/Office/shipmentContainer.module.scss
  src/pages/TOO/moveDetails.jsx
  src/pages/TOO/moveDetails.test.jsx
  src/pages/TOO/too.scss
  src/shared/dates.js
Labels: ttv

#4139 MB-2335 Customer info table connect to move details
  src/components/Office/CustomerInfoTable.jsx
  src/pages/TOO/moveDetails.jsx
Labels: ttv

#3802 [MB-1753] zip-to-rate-area: Populate re_zip3s and re_zip5s_rate_areas tables
  pkg/models/re_zip3s.go
  pkg/services/ghcimport/fixtures/stage_ghc_pricing.sql
  pkg/services/ghcimport/fixtures/tariff400ng_zip3s_fixture.csv
  pkg/services/ghcimport/fixtures/tariff400ng_zip5_rate_areas_fixture.csv
  pkg/services/ghcimport/ghc_rateengine_importer.go
  pkg/services/ghcimport/import_re_domestic_other_prices_test.go
  pkg/services/ghcimport/import_re_domestic_service_area_prices_test.go
  pkg/services/ghcimport/import_re_domestic_service_area_test.go
  pkg/services/ghcimport/import_re_intl_prices_test.go
  pkg/services/ghcimport/import_re_rate_area_test.go
  pkg/services/ghcimport/map_zip_codes_to_re_rate_areas.go
  pkg/services/ghcimport/map_zip_codes_to_re_rate_areas_test.go
  pkg/services/ghcimport/zip3_to_rate_area_mappings.go
  pkg/services/ghcimport/zip5_to_rate_area_mappings.go
Labels: A-Team
