Repository transcom/mymove, pull requests merged in 2020-03, with the labels that each got.

#3617 MB-1720: add update shipments to prime client binary
  cmd/prime-api-client/connection.go
  cmd/prime-api-client/fetch_mtos.go
  cmd/prime-api-client/main.go
  cmd/prime-api-client/update_mto_shipment.go
Labels: roci

#3650 MB-1738 Convert Prime shipment endpoint to If-Match
  pkg/etag/etag.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/mto_shipment/update_m_t_o_shipment_parameters.go
  pkg/gen/primeclient/mto_shipment/update_m_t_o_shipment_parameters.go
  pkg/gen/primemessages/m_t_o_shipment.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/mto_shipment.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/handlers/primeapi/api.go
  pkg/handlers/primeapi/internal/payloads/model_to_payload.go
  pkg/handlers/primeapi/mto_shipment.go
  pkg/handlers/primeapi/mto_shipment_test.go
  pkg/services/mocks/MTOShipmentUpdater.go
  pkg/services/mto_shipment.go
  pkg/services/mto_shipment/mto_shipment_fetcher.go
  pkg/services/mto_shipment/mto_shipment_status_updater.go
  pkg/services/mto_shipment/mto_shipment_status_updater_test.go
  pkg/services/mto_shipment/mto_shipment_updater.go
  pkg/services/mto_shipment/mto_shipment_updater_test.go
  pkg/services/query/query_builder.go
  pkg/services/query/query_builder_test.go
  swagger/prime.yaml
Labels: ttv

#3660 MB-1793 Migration for donald cac
  migrations/app/migrations_manifest.txt
  migrations/app/secure/20200302220909_donald_cac.up.sql
Labels: ttv

#3659 MB-874: add if match to prime client
  cmd/prime-api-client/update_mto_shipment.go
Labels: roci

#3648 Add tests for the weights screen (icon and txt): MB-1797
  src/scenes/Moves/Ppm/Weight.jsx
  src/scenes/Moves/Ppm/Weight.test.js
Labels: moose

#3661 Add move locator to approved email: MB-1688
  pkg/assets/assets.go
  pkg/notifications/move_approved.go
  pkg/notifications/move_approved_test.go
  pkg/notifications/notification_test.go
  pkg/notifications/templates/move_approved_template.html
  pkg/notifications/templates/move_approved_template.txt
Labels: moose

#3662 MB-1776: abstract service object errors
  pkg/handlers/adminapi/upload_information.go
  pkg/handlers/ghcapi/move_task_order.go
  pkg/handlers/ghcapi/mto_shipment.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/handlers/primeapi/mto_shipment.go
  pkg/handlers/primeapi/mto_shipment_test.go
  pkg/services/errors.go
  pkg/services/move_order/move_order_fetcher.go
  pkg/services/move_task_order/move_task_order_fetcher.go
  pkg/services/mto_shipment.go
  pkg/services/mto_shipment/mto_shipment_fetcher.go
  pkg/services/mto_shipment/mto_shipment_fetcher_test.go
  pkg/services/mto_shipment/mto_shipment_updater.go
  pkg/services/mto_shipment/mto_shipment_updater_test.go
  pkg/services/office_user/customer/customer.go
  pkg/services/upload/upload_information_fetcher.go
Labels: roci

#3614 Mb 1563 tab navigation component
  .loki/.gitignore
  .loki/reference/chrome_iphone7_Button_with_some_emoji.png
  .loki/reference/chrome_iphone7_Button_with_text.png
  .loki/reference/chrome_iphone7_Welcome_to_Storybook.png
  .loki/reference/chrome_iphone7_components_TabNav.png
  .loki/reference/chrome_iphone7_scenes_Landing_StatusTimeline.png
  .loki/reference/chrome_laptop_Button_with_some_emoji.png
  .loki/reference/chrome_laptop_Button_with_text.png
  .loki/reference/chrome_laptop_Welcome_to_Storybook.png
  .loki/reference/chrome_laptop_components_TabNav.png
  .loki/reference/chrome_laptop_scenes_Landing_StatusTimeline.png
  .storybook/config.js
  .storybook/storybook.scss
  Makefile
  docs/README.md
  docs/how-to/run-loki-tests-against-storybook.md
  package.json
  src/components/.eslintrc
  src/components/TabNav/index.jsx
  src/components/TabNav/index.module.scss
  src/components/TabNav/index.test.jsx
  src/components/TabNavPanel/index.jsx
  src/components/TabNavPanel/index.test.jsx
  src/index.css
  src/index.js
  src/index.scss
  src/scenes/Moves/Ppm/Weight.module.scss
  src/scenes/SystemAdmin/Home.module.scss
  src/shared/styles/_basics.scss
  src/shared/styles/_mixins.scss
  src/shared/styles/_settings.scss
  src/shared/styles/_variables.scss
  src/stories/statusTimeLine.stories.jsx
  src/stories/tabNav.stories.jsx
  yarn.lock
Labels: A-Team

#3674 Add .loki to .dockerignore file
  .dockerignore
Labels: A-Team

#3642 Add PPM Type and PPM Estimated Weight to MTO after counseling
  cmd/prime-api-client/connection.go
  cmd/prime-api-client/fetch_mtos.go
  cmd/prime-api-client/main.go
  cmd/prime-api-client/update_mto_shipment.go
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20200226153948_add-ppm-type-and-estimated-weight-to-mto.up.sql
  pkg/gen/primeapi/configure_mymove.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/move_task_order/update_m_t_o_post_counseling_information.go
  pkg/gen/primeapi/primeoperations/move_task_order/update_m_t_o_post_counseling_information_parameters.go
  pkg/gen/primeapi/primeoperations/move_task_order/update_m_t_o_post_counseling_information_responses.go
  pkg/gen/primeapi/primeoperations/move_task_order/update_m_t_o_post_counseling_information_urlbuilder.go
  pkg/gen/primeapi/primeoperations/move_task_order/update_move_task_order_post_counseling_information.go
  pkg/gen/primeapi/primeoperations/move_task_order/update_move_task_order_post_counseling_information_responses.go
  pkg/gen/primeapi/primeoperations/mymove_api.go
  pkg/gen/primeclient/move_task_order/move_task_order_client.go
  pkg/gen/primeclient/move_task_order/update_m_t_o_post_counseling_information_parameters.go
  pkg/gen/primeclient/move_task_order/update_m_t_o_post_counseling_information_responses.go
  pkg/gen/primeclient/move_task_order/update_move_task_order_post_counseling_information_parameters.go
  pkg/gen/primeclient/move_task_order/update_move_task_order_post_counseling_information_responses.go
  pkg/gen/primemessages/move_task_order.go
  pkg/gen/primemessages/move_task_order_with_etag.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/move_task_order.go
  pkg/handlers/ghcapi/move_task_order_test.go
  pkg/handlers/ghcapi/mto_agent.go
  pkg/handlers/ghcapi/mto_agent_test.go
  pkg/handlers/ghcapi/payment_request_test.go
  pkg/handlers/primeapi/api.go
  pkg/handlers/primeapi/internal/payloads/model_to_payload.go
  pkg/handlers/primeapi/move_task_order.go
  pkg/handlers/primeapi/move_task_order_test.go
  pkg/models/move_task_order.go
  pkg/models/mto_agents.go
  pkg/models/mto_agents_test.go
  pkg/models/re_zip5_rate_areas.go
  pkg/models/re_zip5_rate_areas_test.go
  pkg/payment_request/service_param_list_valid_test.go
  pkg/services/mocks/MoveTaskOrderStatusUpdater.go
  pkg/services/mocks/MoveTaskOrderUpdater.go
  pkg/services/move_documents/weight_ticket_updater_test.go
  pkg/services/move_order.go
  pkg/services/move_task_order.go
  pkg/services/move_task_order/move_task_order_fetcher.go
  pkg/services/move_task_order/move_task_order_updater.go
  pkg/services/mto_shipment/mto_shipment_updater.go
  pkg/services/payment_request/payment_request_fetcher_test.go
  pkg/testdatagen/make_move_task_order.go
  pkg/testdatagen/make_mto_agent.go
  swagger/prime.yaml
Labels: roci

#3645 Add payment request number to each payment request
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20200227191708_add_payment_request_number.up.sql
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/payment_request.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/payment_request.go
  pkg/handlers/ghcapi/payment_request.go
  pkg/handlers/primeapi/internal/payloads/model_to_payload.go
  pkg/handlers/primeapi/payment_request.go
  pkg/handlers/primeapi/payment_request_test.go
  pkg/models/payment_request.go
  pkg/models/payment_request_test.go
  pkg/services/payment_request/payment_request_creator.go
  pkg/services/payment_request/payment_request_creator_test.go
  pkg/testdatagen/make_payment_request.go
  swagger/ghc.yaml
  swagger/prime.yaml
Labels: A-Team

#3669 Add moveLocator to move survey email: MB-1688
  pkg/notifications/move_reviewed.go
  pkg/notifications/move_reviewed_test.go
Labels: moose

#3672 Update email copy and add tests: MB-1688
  pkg/assets/assets.go
  pkg/notifications/move_payment_reminder.go
  pkg/notifications/move_payment_reminder_test.go
  pkg/notifications/move_submitted_test.go
  pkg/notifications/notification_test.go
  pkg/notifications/templates/move_payment_reminder_template.html
  pkg/notifications/templates/move_payment_reminder_template.txt
  pkg/notifications/templates/move_submitted_template.html
  pkg/notifications/templates/move_submitted_template.txt
Labels: moose

#3646 Add vehicle make and model to SM wizard's weight ticket screen
  cypress/integration/mymove/ppm.js
  cypress/integration/mymove/ppmCloseout.js
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/create_weight_ticket_documents_payload.go
  pkg/handlers/internalapi/move_documents.go
  pkg/handlers/internalapi/weight_ticket_set_documents.go
  pkg/handlers/internalapi/weight_ticket_set_documents_test.go
  pkg/models/move_document.go
  pkg/models/move_documents_extractor.go
  pkg/models/move_documents_extractor_test.go
  pkg/models/weight_ticket_set_document.go
  pkg/testdatagen/make_weight_ticket_set_document.go
  src/scenes/Moves/Ppm/PaymentReview/WeightTicketListItem.jsx
  src/scenes/Moves/Ppm/WeightTicket.jsx
  src/scenes/Moves/Ppm/WeightTicket.test.js
  src/shared/Entities/modules/weightTicketSetDocuments.js
  swagger/internal.yaml
Labels: moose

#3687 Update ppm info sheet pdf: MB-1303
  public/downloads/ppm_info_sheet.pdf
Labels: moose

#3693 Remove broken progear icon: MB-1918
  src/scenes/Moves/Ppm/PaymentReview/WeightTicketListItem.jsx
Labels: moose

#3703 Rename weight_ticket_set to pro_gear_weight
  pkg/handlers/internalapi/weight_ticket_set_documents.go
  pkg/handlers/internalapi/weight_ticket_set_documents_test.go
  pkg/models/move.go
  pkg/models/weight_ticket_set_document.go
Labels: moose

#3707 MB-1788: Created migration for ren cac access
  docs/how-to/use-mtls-with-cac.md
  migrations/app/migrations_manifest.txt
  migrations/app/secure/20200309224754_ren_cac.up.sql
Labels: roci

#3713 Fix prime-api-client broken by go upgrade to 1.14
  cmd/prime-api-client/connection.go
Labels: roci

#3710 Rename weight_ticket_set to vehicle_weight: MB-1528
  pkg/handlers/internalapi/weight_ticket_set_documents_test.go
  pkg/models/weight_ticket_set_document.go
Labels: moose

#3715 MB-1910 Adding optimistic locking to MTO status endpoint
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/move_task_order/update_move_task_order_parameters.go
  pkg/gen/ghcapi/ghcoperations/move_task_order/update_move_task_order_status_parameters.go
  pkg/gen/ghcapi/ghcoperations/move_task_order/update_move_task_order_status_responses.go
  pkg/gen/ghcapi/ghcoperations/mto_shipment/patch_m_t_o_shipment_status_responses.go
  pkg/gen/ghcmessages/m_t_o_shipment.go
  pkg/gen/ghcmessages/m_t_o_shipment_with_etag.go
  pkg/gen/ghcmessages/m_t_o_shipments.go
  pkg/gen/ghcmessages/move_task_order.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/move_task_order.go
  pkg/handlers/ghcapi/move_task_order_test.go
  pkg/handlers/ghcapi/mto_shipment.go
  pkg/handlers/primeapi/move_task_order.go
  pkg/handlers/primeapi/move_task_order_test.go
  pkg/services/mocks/MoveTaskOrderCreator.go
  pkg/services/mocks/MoveTaskOrderUpdater.go
  pkg/services/move_task_order.go
  pkg/services/move_task_order/move_task_order_updater.go
  swagger/ghc.yaml
Labels: ttv

#3716 Make MoveType in AccessCode model a non-pointer
  cmd/generate_access_codes/main.go
  pkg/handlers/adminapi/access_code_test.go
  pkg/handlers/internalapi/access_code_test.go
  pkg/models/access_code.go
  pkg/services/accesscode/access_code_claimer_test.go
  pkg/services/accesscode/access_code_fetcher_test.go
  pkg/services/accesscode/access_code_list_fetcher_test.go
  pkg/services/accesscode/access_code_validator_test.go
  pkg/services/query/query_builder_test.go
  pkg/testdatagen/make_access_code.go
  pkg/testdatagen/scenario/e2ebasic.go
Labels: A-Team

#3720 Change nullability of columns in client_certs table
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20200312145322_change_nullability_in_client_certs.up.sql
Labels: A-Team

#3711 Add navy to department indicator with some copy change
  cypress/integration/office/officeUserPPM.js
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/dept_indicator.go
  pkg/handlers/internalapi/office_test.go
  pkg/paperwork/forms.go
  swagger/internal.yaml
Labels: moose

#3705 Kim mb 705 office make model weight ticket review
  cypress/integration/office/documentViewer.js
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/move_document_payload.go
  pkg/gen/internalmessages/move_document_type.go
  src/scenes/Moves/Ppm/WeightTicket.jsx
  src/scenes/Office/DocumentViewer/DocumentDetailDisplay.jsx
  src/scenes/Office/DocumentViewer/DocumentDetailDisplay.test.jsx
  src/scenes/Office/DocumentViewer/DocumentDetailEdit.jsx
  src/scenes/Office/DocumentViewer/DocumentDetailPanel.jsx
  src/shared/DocumentViewer/DocumentDetailPanelView.jsx
  src/shared/DocumentViewer/DocumentDetailPanelView.test.jsx
  swagger/internal.yaml
Labels: moose

#3689 MB-60 document storybook practices
  .github/CODEOWNERS
  .spelling
  .storybook/config.js
  docs/frontend.md
  docs/how-to/run-loki-tests-against-storybook.md
  docs/how-to/run-storybook.md
Labels: A-Team

#3757 MB-1896: Fix weight ticket set document vet issues
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20200313204211_alter_weight_ticket_set_documents_nullability.up.sql
Labels: roci

#3760 MB-1886: Fix moving expense document vet issues
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20200316180737_alter_moving_expense_document_nullability.up.sql
Labels: roci

#3726 MB-1317 Prime API create mto service item domestic origin first day SIT
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20200306232322_service_item_dom_origin_sit_update.up.sql
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/mto_service_item/create_m_t_o_service_item.go
  pkg/gen/ghcmessages/m_t_o_service_item.go
  pkg/gen/primeapi/configure_mymove.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/mto_service_item/create_m_t_o_service_item.go
  pkg/gen/primeapi/primeoperations/mto_service_item/create_m_t_o_service_item_parameters.go
  pkg/gen/primeapi/primeoperations/mto_service_item/create_m_t_o_service_item_responses.go
  pkg/gen/primeapi/primeoperations/mto_service_item/create_m_t_o_service_item_urlbuilder.go
  pkg/gen/primeapi/primeoperations/mymove_api.go
  pkg/gen/primeclient/mto_service_item/create_m_t_o_service_item_parameters.go
  pkg/gen/primeclient/mto_service_item/create_m_t_o_service_item_responses.go
  pkg/gen/primeclient/mto_service_item/mto_service_item_client.go
  pkg/gen/primeclient/mymove_client.go
  pkg/gen/primemessages/m_t_o_service_item.go
  pkg/gen/primemessages/m_t_o_service_item_basic.go
  pkg/gen/primemessages/m_t_o_service_item_d_o_f_s_i_t.go
  pkg/gen/primemessages/m_t_o_service_item_model_type.go
  pkg/gen/primemessages/m_t_o_service_item_status.go
  pkg/gen/primemessages/m_t_o_service_items.go
  pkg/gen/primemessages/move_task_order.go
  pkg/gen/primemessages/re_service_code.go
  pkg/handlers/ghcapi/mto_service_items.go
  pkg/handlers/ghcapi/mto_service_items_test.go
  pkg/handlers/primeapi/api.go
  pkg/handlers/primeapi/internal/payloads/model_to_payload.go
  pkg/handlers/primeapi/internal/payloads/payload_to_model.go
  pkg/handlers/primeapi/move_task_order_test.go
  pkg/handlers/primeapi/mto_service_item.go
  pkg/handlers/primeapi/mto_service_item_test.go
  pkg/models/mto_service_items.go
  pkg/models/mto_service_items_test.go
  pkg/models/re_service.go
  pkg/services/errors.go
  pkg/services/ghcimport/load_service_map.go
  pkg/services/move_order/move_order_fetcher.go
  pkg/services/move_task_order/move_task_order_fetcher.go
  pkg/services/move_task_order/move_task_order_updater.go
  pkg/services/mto_service_item/mto_service_item_creator.go
  pkg/services/mto_service_item/mto_service_item_creator_test.go
  pkg/services/mto_shipment/mto_shipment_updater.go
  pkg/services/mto_shipment/mto_shipment_updater_test.go
  pkg/services/office_user/customer/customer.go
  pkg/services/payment_request/payment_request_creator.go
  pkg/services/upload/upload_information_fetcher.go
  pkg/testdatagen/make_mto_service_item.go
  swagger/ghc.yaml
  swagger/prime.yaml
Labels: ttv

#3737 Kim document detail edit tests
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/move_document_payload.go
  pkg/gen/internalmessages/move_document_status.go
  src/scenes/Office/DocumentViewer/DocumentDetailDisplay.jsx
  src/scenes/Office/DocumentViewer/DocumentDetailDisplay.test.jsx
  src/scenes/Office/DocumentViewer/DocumentDetailEdit.jsx
  src/scenes/Office/DocumentViewer/DocumentDetailEdit.test.jsx
  swagger/internal.yaml
Labels: moose

#3758 Return non-winning calculation from rate engine: MB-1605
  pkg/handlers/internalapi/personally_procured_move.go
  pkg/handlers/internalapi/personally_procured_move_estimate.go
  pkg/handlers/internalapi/personally_procured_move_incentive.go
  pkg/models/shipment_summary_worksheet.go
  pkg/models/shipment_summary_worksheet_test.go
  pkg/paperwork/shipment_summary.go
  pkg/paperwork/shipment_summary_test.go
  pkg/rateengine/rateengine.go
  pkg/rateengine/rateengine_test.go
Labels: moose

#3735 Changed nullability/types for some Customer columns
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20200313162229_change_nullability_in_customers.up.sql
  pkg/handlers/ghcapi/customer_test.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/primeapi/internal/payloads/model_to_payload.go
  pkg/models/customer.go
  pkg/models/customer_test.go
  pkg/services/converthelper/convert.go
  pkg/services/converthelper/convert_test.go
  pkg/services/move_order/move_order_fetcher_test.go
  pkg/services/office_user/customer/customer_test.go
  pkg/testdatagen/make_customer.go
Labels: A-Team

#3783 MB-1947: PreconditionFailed Error More Descriptive
  pkg/handlers/primeapi/mto_shipment.go
Labels: roci

#3734 MB-1885: Fix MTO model vet issues
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20200313212635_alter_move_task_orders_nullability.up.sql
  pkg/handlers/primeapi/internal/payloads/model_to_payload.go
  pkg/models/move_task_order.go
  pkg/services/move_task_order/move_task_order_updater.go
  pkg/testdatagen/make_move_task_order.go
Labels: roci

#3708 MB-1746 circleci job for loki
  .circleci/config.yml
  .dockerignore
  .loki/reference/chrome_iphone7_Components_Button_with_some_emoji.png
  .loki/reference/chrome_iphone7_Components_Button_with_text.png
  .loki/reference/chrome_iphone7_Global_Colors_all.png
  .loki/reference/chrome_iphone7_Global_Typography_Headers.png
  .loki/reference/chrome_iphone7_Global_Typography_Links.png
  .loki/reference/chrome_iphone7_Global_Typography_Text.png
  .loki/reference/chrome_iphone7_Welcome_to_Storybook.png
  .loki/reference/chrome_iphone7_components_TabNav.png
  .loki/reference/chrome_iphone7_scenes_Landing_StatusTimeline.png
  .loki/reference/chrome_laptop_Components_Button_with_some_emoji.png
  .loki/reference/chrome_laptop_Components_Button_with_text.png
  .loki/reference/chrome_laptop_Global_Colors_all.png
  .loki/reference/chrome_laptop_Global_Typography_Headers.png
  .loki/reference/chrome_laptop_Global_Typography_Links.png
  .loki/reference/chrome_laptop_Global_Typography_Text.png
  .loki/reference/chrome_laptop_Welcome_to_Storybook.png
  .loki/reference/chrome_laptop_components_TabNav.png
  .loki/reference/chrome_laptop_scenes_Landing_StatusTimeline.png
  Dockerfile.storybook
  Makefile
  docker-compose.storybook.yml
  docs/how-to/run-loki-tests-against-storybook.md
  docs/how-to/run-storybook.md
  package.json
  scripts/README.md
  scripts/run-storybook-tests
  scripts/start-storybook-tests
Labels: A-Team

#3785 Update loki tests after merge to master
  .loki/reference/chrome_iphone7_components_TabNav.png
  .loki/reference/chrome_laptop_components_TabNav.png
Labels: A-Team

#3768 MB-1895: Fix upload vetting issue
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20200316205857_alter_uploads_nullability.up.sql
Labels: roci

#3794 MB-1946: Remove prime tag from yaml
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/move_task_order/fetch_m_t_o_updates.go
  pkg/gen/primeapi/primeoperations/move_task_order/get_move_task_order_customer.go
  pkg/gen/primeapi/primeoperations/move_task_order/update_m_t_o_post_counseling_information.go
  pkg/gen/primeapi/primeoperations/mto_service_item/create_m_t_o_service_item.go
  pkg/gen/primeapi/primeoperations/mto_shipment/update_m_t_o_shipment.go
  pkg/gen/primeclient/move_task_order/move_task_order_client.go
  swagger/prime.yaml
Labels: roci

#3771 MB-1977 Fix bug to create default service items (CS, MS)
  pkg/models/validators.go
  pkg/models/validators_test.go
  pkg/services/move_task_order/move_task_order_creator.go
Labels: ttv

#3786 MB-1317 Prime API Client: Create MTOServiceItem Dom. Origin 1st Day SIT
  cmd/prime-api-client/create_mto_service_item.go
  cmd/prime-api-client/main.go
  cmd/prime-api-client/shared.go
  cmd/prime-api-client/update_mto_shipment.go
Labels: ttv

#3571 MB-1384 Transit times parser
  Makefile
  cmd/ghc-transit-time-parser/main.go
  docs/data/ghc-transit-time-import.md
  pkg/models/ghc_domestic_transit_times.go
  pkg/parser/transittime/fixtures/Appendix_C(i)_-_Transit_Time_Tables_Fake_Data.xlsx
  pkg/parser/transittime/logger.go
  pkg/parser/transittime/parse.go
  pkg/parser/transittime/parse_test.go
  pkg/parser/transittime/parse_transit_times.go
  pkg/parser/transittime/shared.go
Labels: ttv

#3774 Add pointOfContact to prime POST/PUT/PATCH endpoints
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/move_task_order/update_m_t_o_post_counseling_information.go
  pkg/gen/primeapi/primeoperations/mto_shipment/update_m_t_o_shipment_parameters.go
  pkg/gen/primeclient/move_task_order/update_m_t_o_post_counseling_information_responses.go
  pkg/gen/primemessages/create_payment_request_payload.go
  pkg/gen/primemessages/m_t_o_shipment.go
  pkg/gen/primemessages/move_task_orders.go
  pkg/handlers/primeapi/internal/payloads/model_to_payload.go
  pkg/handlers/primeapi/move_task_order.go
  pkg/handlers/primeapi/move_task_order_test.go
  pkg/handlers/primeapi/mto_shipment.go
  pkg/handlers/primeapi/payment_request.go
  pkg/handlers/primeapi/payment_request_test.go
  swagger/prime.yaml
Labels: roci

#3797 MB-1920: Update docker compose files to allow access to prime api
  docker-compose.local.yml
  docker-compose.yml
Labels: roci

#3732 Add optimistic locking to remaining GHC API endpoints
  docs/how-to/use-optimistic-locking.md
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/move_task_order/update_move_task_order_responses.go
  pkg/gen/ghcapi/ghcoperations/mto_service_item/update_m_t_o_service_item_parameters.go
  pkg/gen/ghcapi/ghcoperations/mto_service_item/update_m_t_o_service_item_responses.go
  pkg/gen/ghcapi/ghcoperations/mto_service_item/update_m_t_o_service_item_status.go
  pkg/gen/ghcapi/ghcoperations/mto_service_item/update_m_t_o_service_item_status_parameters.go
  pkg/gen/ghcapi/ghcoperations/mto_service_item/update_m_t_o_service_item_status_responses.go
  pkg/gen/ghcapi/ghcoperations/mto_service_item/update_m_t_o_service_item_status_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/mto_service_item/update_m_t_o_service_itemstatus.go
  pkg/gen/ghcapi/ghcoperations/mto_service_item/update_m_t_o_service_itemstatus_responses.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/ghcapi/ghcoperations/payment_requests/update_payment_request_parameters.go
  pkg/gen/ghcapi/ghcoperations/payment_requests/update_payment_request_responses.go
  pkg/gen/ghcapi/ghcoperations/payment_requests/update_payment_request_status_parameters.go
  pkg/gen/ghcapi/ghcoperations/payment_requests/update_payment_request_status_responses.go
  pkg/gen/ghcmessages/address.go
  pkg/gen/ghcmessages/customer.go
  pkg/gen/ghcmessages/duty_station.go
  pkg/gen/ghcmessages/entitlements.go
  pkg/gen/ghcmessages/m_t_o_agent.go
  pkg/gen/ghcmessages/m_t_o_service_item.go
  pkg/gen/ghcmessages/move_order.go
  pkg/gen/ghcmessages/payment_request.go
  pkg/gen/ghcmessages/update_payment_request_payload.go
  pkg/gen/ghcmessages/update_payment_request_status_payload.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/move_task_order/update_m_t_o_post_counseling_information_responses.go
  pkg/gen/primeclient/move_task_order/update_m_t_o_post_counseling_information_responses.go
  pkg/gen/primemessages/address.go
  pkg/gen/primemessages/customer.go
  pkg/gen/primemessages/duty_station.go
  pkg/gen/primemessages/entitlements.go
  pkg/gen/primemessages/m_t_o_service_item.go
  pkg/gen/primemessages/m_t_o_service_item_basic.go
  pkg/gen/primemessages/m_t_o_service_item_d_o_f_s_i_t.go
  pkg/gen/primemessages/move_order.go
  pkg/gen/primemessages/move_task_order.go
  pkg/gen/primemessages/move_task_order_with_etag.go
  pkg/gen/primemessages/move_task_orders.go
  pkg/gen/primemessages/payment_request.go
  pkg/gen/primemessages/service_item.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/move_task_order.go
  pkg/handlers/ghcapi/mto_shipment.go
  pkg/handlers/ghcapi/payment_request.go
  pkg/handlers/ghcapi/payment_request_test.go
  pkg/handlers/primeapi/internal/payloads/model_to_payload.go
  pkg/handlers/primeapi/move_task_order.go
  pkg/services/mocks/PaymentRequestStatusUpdater.go
  pkg/services/payment_request.go
  pkg/services/payment_request/payment_request_status_updater.go
  pkg/services/payment_request/payment_request_status_updater_test.go
  src/scenes/Office/TIO/paymentRequestShow.jsx
  src/scenes/Office/TOO/customerDetails.jsx
  src/shared/Entities/modules/moveTaskOrders.js
  src/shared/Entities/modules/paymentRequests.js
  swagger/ghc.yaml
  swagger/prime.yaml
Labels: ttv

#3782 [MB-1945] Change underscore param names in prime API to camelCase
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/move_task_order/update_m_t_o_post_counseling_information.go
  pkg/gen/primeclient/move_task_order/update_m_t_o_post_counseling_information_responses.go
  pkg/gen/primemessages/duty_station.go
  pkg/gen/primemessages/move_task_order.go
  pkg/gen/primemessages/validation_error.go
  swagger/prime.yaml
Labels: roci

#3792 Made locator not null in the DB; added validation in the model
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20200316170243_change_nullability_in_moves.up.sql
  pkg/handlers/internalapi/move_queue_items_test.go
  pkg/models/move.go
  pkg/models/move_test.go
Labels: A-Team

#3793 More specific obligation test checks
  pkg/paperwork/shipment_summary_test.go
Labels: moose

#3801 [MB-1386] Update ZIP to Rate Area for Tariff400ng
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20200319211333_add_missing_zip3s_to_tariff400ng_zip3s_table.up.sql
Labels: A-Team

#3806 Fix incorrect data associated with tariff400ng_zip3 with zip3 555
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20200320192057_correct_incorrect_state_and_rate_area_data_for_tariff_400ng_zip3_with_zip3_555.up.sql
Labels: A-Team

#3800 remove debug stmts from tests
  src/scenes/Landing/index.test.js
  src/scenes/SystemAdmin/shared/AdminPagination.test.js
Labels: moose

#3754 Update MTO Shipments releasing/receiving agent
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/m_t_o_agent.go
  pkg/gen/primemessages/m_t_o_agent_type.go
  pkg/gen/primemessages/m_t_o_agents.go
  pkg/gen/primemessages/m_t_o_shipment.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/primeapi/internal/payloads/model_to_payload.go
  pkg/handlers/primeapi/internal/payloads/payload_to_model.go
  pkg/handlers/primeapi/move_task_order.go
  pkg/handlers/primeapi/mto_shipment_test.go
  pkg/models/move_documents_extractor_test.go
  pkg/models/mto_agents.go
  pkg/models/mto_shipments.go
  pkg/models/mto_shipments_test.go
  pkg/services/converthelper/convert.go
  pkg/services/mto_shipment/mto_shipment_updater.go
  pkg/services/mto_shipment/mto_shipment_updater_test.go
  pkg/testdatagen/make_mto_shipment.go
  pkg/testdatagen/scenario/e2ebasic.go
  swagger/prime.yaml
Labels: roci

#3818 [MB-2001] Update tariff400ng_zip3s_fixture.csv to include missing Zip3s
  pkg/services/ghcimport/fixtures/tariff400ng_zip3s_fixture.csv
Labels: A-Team

#3824 [MB-1928] Fix duplicate zip5s pointing to different rate areas
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20200324150211_remove_duplicate_zip5s_with_different_rate_areas_in_tariff400ng_zip5_rate_areas_table.up.sql
Labels: A-Team

#3825 MB-53 Documentation Updates for USWDS 2.0
  .circleci/config.yml
  .eslintrc
  dangerfile.ts
  docs/frontend.md
  docs/how-to/run-storybook.md
  package.json
  scripts/run-storybook-tests
  src/components/.eslintrc
  src/config/.eslintrc
  src/constants/.eslintrc
  src/containers/.eslintrc
  src/helpers/.eslintrc
  src/layout/.eslintrc
  src/pages/.eslintrc
  src/shared/styles/_settings.scss
  src/stories/.eslintrc
  yarn.lock
Labels: A-Team

#3820 MB-1921: enable prime contractor to access prime api
  .envrc.local.template
  .spelling
  Makefile
  docker-compose.prime.yml
  docs/README.md
  docs/how-to/run-prime-docker.md
  docs/how-to/test-prime-api-local.md
  docs/how-to/test-prime-api-staging-experimental.md
  scripts/README.md
  scripts/run-prime-docker
Labels: roci

#3836 Update yarn.lock after merge to master
  yarn.lock
Labels: A-Team

#3837 MB-2090 Add verification check to ensure dependency lock files are not changed during build
  .circleci/config.yml
  scripts/check-generated-code
Labels: A-Team

#3805 MB-1999 Replace snake_case with camelCase in admin.yaml
  pkg/gen/adminapi/embedded_spec.go
  pkg/gen/adminmessages/access_code.go
  pkg/gen/adminmessages/address.go
  pkg/gen/adminmessages/admin_user.go
  pkg/gen/adminmessages/admin_user_create_payload.go
  pkg/gen/adminmessages/admin_user_update_payload.go
  pkg/gen/adminmessages/electronic_order.go
  pkg/gen/adminmessages/move.go
  pkg/gen/adminmessages/notification.go
  pkg/gen/adminmessages/office_user.go
  pkg/gen/adminmessages/office_user_create_payload.go
  pkg/gen/adminmessages/office_user_update_payload.go
  pkg/gen/adminmessages/organization.go
  pkg/gen/adminmessages/transportation_office.go
  pkg/gen/adminmessages/transportation_service_provider_performance.go
  pkg/gen/adminmessages/upload.go
  pkg/gen/adminmessages/upload_information.go
  pkg/gen/adminmessages/validation_error.go
  src/scenes/SystemAdmin/AccessCodes/AccessCodeList.jsx
  src/scenes/SystemAdmin/AdminUsers/AdminUserCreate.jsx
  src/scenes/SystemAdmin/AdminUsers/AdminUserEdit.jsx
  src/scenes/SystemAdmin/AdminUsers/AdminUserList.jsx
  src/scenes/SystemAdmin/AdminUsers/AdminUserShow.jsx
  src/scenes/SystemAdmin/ElectronicOrders/ElectronicOrderList.jsx
  src/scenes/SystemAdmin/Moves/MoveList.jsx
  src/scenes/SystemAdmin/Notifications/NotificationList.jsx
  src/scenes/SystemAdmin/OfficeUsers/OfficeUserCreate.jsx
  src/scenes/SystemAdmin/OfficeUsers/OfficeUserEdit.jsx
  src/scenes/SystemAdmin/OfficeUsers/OfficeUserList.jsx
  src/scenes/SystemAdmin/OfficeUsers/OfficeUserShow.jsx
  src/scenes/SystemAdmin/TSPPs/TSPPList.jsx
  src/scenes/SystemAdmin/TSPPs/TSPPShow.jsx
  src/scenes/SystemAdmin/Uploads/UploadShow.jsx
  swagger/admin.yaml
Labels: roci

#3819 Make ServiceMemberID a not null property on Notifications
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20200324155051_change_nullability_in_notifications.up.sql
  pkg/models/notifications.go
  pkg/models/notifications_test.go
Labels: A-Team

#3839 ADR-0044 New ADR to document camelCase style for API params
  .spelling
  docs/README.md
  docs/adr/0044-params-styling.md
  docs/adr/index.md
Labels: roci

#3842 Resolve model vet conflicts on Tariff 400ng Full Pack Rate Model
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20200326142555_change_nullability_in_tariff_400ng_full_pack_rate.up.sql
  pkg/handlers/internalapi/moves_test.go
  pkg/models/tariff400ng_full_pack_rate.go
  pkg/models/tariff400ng_full_pack_rate_test.go
Labels: A-Team
