Repository transcom/mymove, pull requests merged in 2021-11, with the labels that each got.

#7645 MB-9930 migrate from golint to revive
  .golangci.yml
  cmd/ecs-deploy/put_target.go
  cmd/ecs-deploy/task_def.go
  nix/default.nix
  pkg/cli/services.go
  pkg/handlers/primeapi/mto_service_item_test.go
  pkg/migrate/ListFiles.go
  pkg/migrate/ListFiles_test.go
  pkg/payment_request/service_param_value_lookups/service_param_value_lookups_test.go
  pkg/services/dbtools/table_from_slice_creator.go
  pkg/telemetry/init.go
  pkg/testdatagen/scenario/devseed.go
  pkg/testdatagen/scenario/e2ebasic.go
Labels: A-Team, ready-to-merge

#7632 [MB-8566] Edit MTO Shipment's Address (existing address)
  src/constants/routes.js
  src/pages/Office/index.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdate.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdateAddress.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdateAddress.test.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdateAddressForm.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdateAddressForm.test.jsx
  src/pages/PrimeUI/Shipment/Shipment.jsx
  src/services/primeApi.js
  src/shared/utils.js
  src/utils/formatters.js
Labels: Pamplemoose

#7646 [MB-9830] Prime simulator validate addtional day SIT payment request start end date params
  src/components/PrimeUI/CreatePaymentRequestForm/CreatePaymentRequestForm.jsx
  src/pages/PrimeUI/CreatePaymentRequest/CreatePaymentRequest.jsx
Labels: Pamplemoose

#7659 MB-9933 Prime User Banner
  src/pages/Office/index.jsx
  src/pages/PrimeUI/MoveTaskOrder/MoveDetails.jsx
  src/pages/PrimeUI/PrimeBanner/PrimeBanner.jsx
  src/pages/PrimeUI/PrimeBanner/PrimeBanner.module.scss
Labels: Pamplemoose

#7654 MB-9844 cleanup
  src/components/PrimeUI/CreatePaymentRequestForm/CreatePaymentRequestForm.jsx
  src/components/PrimeUI/CreatePaymentRequestForm/CreatePaymentRequestForm.test.jsx
  src/components/PrimeUI/CreateShipmentServiceItemForm/CreateShipmentServiceItemForm.jsx
  src/components/PrimeUI/Shipment/Shipment.jsx
  src/pages/PrimeUI/CreatePaymentRequest/CreatePaymentRequest.jsx
  src/pages/PrimeUI/CreatePaymentRequest/CreatePaymentRequest.test.jsx
  src/pages/PrimeUI/CreateServiceItem/CreateServiceItem.jsx
  src/pages/PrimeUI/MoveTaskOrder/MoveDetails.jsx
  src/pages/PrimeUI/Prime.module.scss
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdate.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdate.test.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdateAddress.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdateForm.jsx
Labels: Pamplemoose

#7650 [MB-9913] Prime simulator cypress user login and update required shipment info
  cypress.json
  cypress/cypress.json
  cypress/integration/office/primesimulator/primeSimulatorFlows.js
  cypress/support/commands.js
  cypress/support/constants.js
  docker-compose.yml
  pkg/testdatagen/scenario/e2ebasic.go
  src/pages/PrimeUI/MoveTaskOrder/MoveDetails.jsx
Labels: Pamplemoose

#7661 MB-10174 Turn on ATO go linter in pre commit
  .github/workflows/be-linter.yml
  .pre-commit-config.yaml
  scripts/README.md
  scripts/pre-commit-go-custom-linter
Labels: A-Team

#7652 MB-9792 add financial review flag for services counselor
  cypress/integration/office/servicescounseling/servicesCounselingFlows.js
  src/components/Office/FinancialReviewButton/FinancialReviewButton.jsx
  src/components/Office/FinancialReviewButton/FinancialReviewButton.module.scss
  src/components/Office/FinancialReviewButton/FinancialReviewButton.stories.jsx
  src/components/Office/FinancialReviewButton/FinancialReviewButton.test.jsx
  src/components/Office/FinancialReviewModal/FinancialReviewModal.jsx
  src/components/Office/FinancialReviewModal/FinancialReviewModal.module.scss
  src/components/Office/FinancialReviewModal/FinancialReviewModal.stories.jsx
  src/components/Office/FinancialReviewModal/FinancialReviewModal.test.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
  src/services/ghcApi.js
Labels: ttv

#7653 [MB-9796] Small query change to allow renaming the duty_stations table without downtime
  pkg/models/duty_station.go
Labels: ttv

#7695 MB-10191 add additional auth logging
  pkg/auth/authentication/auth.go
  pkg/auth/authentication/client_cert.go
  pkg/auth/authentication/login_gov.go
  pkg/auth/cookie.go
Labels: A-Team

#7701 [MB-9903] Change all instances of NTS-R to NTS-release
  cypress/integration/mymove/ntsr.js
  pkg/testdatagen/make_nts_shipment.go
  pkg/testdatagen/scenario/shared.go
  src/components/Customer/MtoShipmentForm/MtoShipmentForm.test.jsx
  src/components/Customer/modals/StorageInfoModal/StorageInfoModal.jsx
  src/components/Office/ServicesCounselingShipmentForm/ServicesCounselingShipmentForm.test.jsx
  src/components/ShipmentList/ShipmentList.module.scss
  src/components/ShipmentList/ShipmentList.test.jsx
  src/components/ShipmentList/index.jsx
  src/components/ShipmentTag/ShipmentTag.module.scss
  src/constants/shipments.js
  src/content/shipments.js
  src/pages/MyMove/SelectShipmentType.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.test.jsx
  src/shared/constants.js
Labels: roci

#7675 MB-8566 Duplicate name fields on page
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdateAddress.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdateAddressForm.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdateAddressForm.test.jsx
Labels: Pamplemoose, ready-to-merge

#7697 [MB-9935] Add NTS SAC and TAC to GHC orders definition and model to payload
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/order.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: roci, ready-to-merge

#7711 MB-9925 update appctx linter to match desired use
  pkg/appcontext-linter/appctx.go
  pkg/appcontext-linter/appctx_test.go
  pkg/ato-linter/ato.go
  testdata/src/appctx_linter_tests/appcontext.go
  testdata/src/appctx_linter_tests/appcontext/main.go
  testdata/src/appctx_linter_tests/db/main.go
  testdata/src/appctx_linter_tests/handlers/main.go
  testdata/src/appctx_linter_tests/migrate/main.go
  testdata/src/appctx_linter_tests/models/main.go
  testdata/src/appctx_linter_tests/testdatagen/main.go
  testdata/src/appctx_linter_tests/testingsuite/main.go
  testdata/src/github.com/README.md
Labels: A-Team

#7699 MB-9842 Add in the Prime API: prefix to server errors
  src/pages/PrimeUI/CreatePaymentRequest/CreatePaymentRequest.jsx
  src/pages/PrimeUI/CreatePaymentRequest/CreatePaymentRequest.test.jsx
  src/pages/PrimeUI/CreateServiceItem/CreateServiceItem.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdate.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdateAddress.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdateAddress.test.jsx
Labels: Pamplemoose, ready-to-merge

#7746 MB-10082: Creates AccountingCodes component
  src/components/Office/AccountingCodes/AccountingCodes.jsx
  src/components/Office/AccountingCodes/AccountingCodes.module.scss
  src/components/Office/AccountingCodes/AccountingCodes.stories.jsx
  src/components/Office/AccountingCodes/AccountingCodes.test.jsx
Labels: roci

#7747 MB-10097 (Frontend, SC) Service Counselor can't edit Customer Remarks
  src/components/Office/ServicesCounselingShipmentForm/ServicesCounselingShipmentForm.jsx
  src/components/Office/ServicesCounselingShipmentForm/ServicesCounselingShipmentForm.module.scss
  src/components/Office/ServicesCounselingShipmentForm/ServicesCounselingShipmentForm.stories.jsx
  src/components/Office/ServicesCounselingShipmentForm/ServicesCounselingShipmentForm.test.jsx
Labels: roci

#7713 [MB-9796] Create postal code to GBLOC mapping table
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20211109231452_create_zip_to_gbloc_table.up.sql
  pkg/models/postal_code_to_gbloc.go
  scripts/README.md
  scripts/zips-for-gbloc
Labels: ttv

#7731 MB-10390: Enable devauth for load test environment
  cmd/milmove/serve.go
  config/env/loadtest.app.env
  pkg/cli/devlocal.go
Labels: A-Team

#7721 [MB-9779] Add reweigh to Prime UI shipment details
  cypress/integration/office/primesimulator/primeSimulatorFlows.js
  src/components/PrimeUI/Shipment/Shipment.jsx
  src/components/PrimeUI/Shipment/Shipment.test.jsx
  src/pages/PrimeUI/MoveTaskOrder/MoveDetails.module.scss
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdateAddressForm.jsx
  src/pages/PrimeUI/Shipment/Shipment.jsx
  src/shared/formatters.js
  src/utils/shipmentDisplay.jsx
Labels: Pamplemoose

#7751 MB 10148 upload docs flow
  src/pages/PrimeUI/UploadPaymentRequestDocuments/UploadPaymentRequestDocuments.jsx
  src/pages/PrimeUI/UploadPaymentRequestDocuments/UploadPaymentRequestDocuments.test.jsx
Labels: Pamplemoose, ready-to-merge

#7712 MB-9925 Final appcontext linter fixes
  .pre-commit-config.yaml
  cmd/generate-test-data/main.go
  cmd/generate_access_codes/logger.go
  cmd/generate_access_codes/main.go
  cmd/milmove/serve.go
  cmd/model-vet/main.go
  cmd/webhook-client/db_connection.go
  cmd/webhook-client/webhook/webhook_test.go
  pkg/appcontext-linter/appctx.go
  pkg/appcontext/context.go
  pkg/auth/authentication/client_cert.go
  pkg/db/stats/pop_stats.go
  pkg/handlers/internalapi/personally_procured_move_estimate_test.go
  pkg/handlers/internalapi/personally_procured_move_incentive_test.go
  pkg/handlers/internalapi/personally_procured_move_test.go
  pkg/services/ppmservices/estimate_calculator_test.go
  pkg/telemetry/db.go
  pkg/telemetry/runtime.go
  pkg/testdatagen/make_move.go
  pkg/testdatagen/make_move_document.go
  pkg/testdatagen/make_personally_procured_move.go
  pkg/testdatagen/make_re_rate_area.go
  pkg/testdatagen/make_service_member.go
  pkg/testdatagen/scenario/bandwidth.go
  pkg/testdatagen/scenario/devseed.go
  pkg/testdatagen/scenario/e2ebasic.go
  pkg/testdatagen/scenario/estimate.go
  pkg/testdatagen/scenario/rateengine.go
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/shared.go
  testdata/src/appctx_linter_tests/handlers/main.go
Labels: A-Team, ready-to-merge

#7750 MB-10422: Always save integration test artifacts to help with debugging
  .circleci/config.yml
Labels: ready-to-merge

#7720 [MB-9796] Part 2: Schema changes for non installation locations
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20211112193224_support_noninstallation_locations.up.sql
  pkg/handlers/internalapi/duty_stations.go
  pkg/handlers/internalapi/duty_stations_test.go
  pkg/handlers/internalapi/moves_test.go
  pkg/handlers/internalapi/personally_procured_move_estimate_test.go
  pkg/handlers/internalapi/personally_procured_move_incentive_test.go
  pkg/handlers/internalapi/personally_procured_move_shared_test.go
  pkg/handlers/internalapi/personally_procured_move_sit_estimate_test.go
  pkg/handlers/internalapi/personally_procured_move_test.go
  pkg/models/duty_station.go
  pkg/models/duty_station_test.go
  pkg/models/order.go
  pkg/models/order_test.go
  pkg/notifications/move_payment_reminder_test.go
  pkg/paperwork/shipment_summary_test.go
  pkg/services/duty_stations/load_duty_stations.go
  pkg/services/ppmservices/estimate_calculator_test.go
  pkg/testdatagen/make_duty_station.go
Labels: ttv

#7732 MB-10081 counselor can manage nts shipments
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20211104212749_add_selected_tac_sac_to_mto_shipments.up.sql
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/create_m_t_o_shipment.go
  pkg/gen/ghcmessages/l_o_a_type.go
  pkg/gen/ghcmessages/m_t_o_shipment.go
  pkg/gen/ghcmessages/storage_facility.go
  pkg/gen/ghcmessages/update_shipment.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/internal/payloads/payload_to_model.go
  pkg/handlers/ghcapi/mto_shipment.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/models/mto_shipments.go
  pkg/models/mto_shipments_test.go
  pkg/services/mto_shipment/mto_shipment_creator.go
  pkg/services/mto_shipment/mto_shipment_creator_test.go
  pkg/services/mto_shipment/mto_shipment_updater.go
  pkg/services/mto_shipment/mto_shipment_updater_test.go
  pkg/testdatagen/make_mto_shipment.go
  pkg/testdatagen/make_storage_facility.go
  pkg/testdatagen/shared.go
  swagger-def/definitions/LOAType.yaml
  swagger-def/definitions/StorageFacility.yaml
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: roci

#7757 MB-9831 remove remaining logger interface from packages
  Makefile
  cmd/generate-payment-request-edi/logger.go
  cmd/generate-payment-request-edi/main.go
  cmd/generate-shipment-summary/logger.go
  cmd/generate-shipment-summary/main.go
  cmd/generate-test-data/logger.go
  cmd/generate-test-data/main.go
  cmd/milmove-tasks/process_edis.go
  cmd/milmove/gen_duty_stations_migration.go
  cmd/milmove/logger.go
  cmd/milmove/main_test.go
  cmd/milmove/migrate.go
  cmd/milmove/serve.go
  cmd/model-vet/main.go
  pkg/cli/cli_test.go
  pkg/cli/dbconn.go
  pkg/cli/gex_sftp.go
  pkg/cli/logger.go
  pkg/cli/logging.go
  pkg/cli/redis.go
  pkg/handlers/adminapi/admin_users.go
  pkg/handlers/adminapi/moves.go
  pkg/handlers/adminapi/office_users.go
  pkg/handlers/adminapi/users.go
  pkg/handlers/ghcapi/move_task_order.go
  pkg/handlers/ghcapi/mto_service_items.go
  pkg/handlers/ghcapi/payment_request.go
  pkg/handlers/ghcapi/payment_service_items.go
  pkg/handlers/primeapi/payment_request_test.go
  pkg/handlers/supportapi/payment_request.go
  pkg/iampostgres/iampostgres.go
  pkg/iampostgres/logger.go
  pkg/iws/logger.go
  pkg/iws/rbs_person_lookup.go
  pkg/server/logger.go
  pkg/server/server.go
  pkg/server/server_test.go
  pkg/server/std_logger.go
  pkg/services/audit/audit.go
  pkg/services/audit/audit_test.go
  pkg/services/audit/logger.go
  pkg/services/organization/logger.go
Labels: A-Team, ready-to-merge

#7765 [MB-10173] Add line about facility address to customer shipment remarks
  src/components/Customer/MtoShipmentForm/MtoShipmentForm.jsx
Labels: roci, ready-to-merge

#7772 [MB-9934] Return facility information for NTS shipments
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/storage_facility.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/services/mto_shipment/mto_shipment_creator_test.go
  pkg/services/mto_shipment/mto_shipment_fetcher.go
  pkg/services/mto_shipment/mto_shipment_updater_test.go
  pkg/testdatagen/make_mto_shipment.go
  pkg/testdatagen/make_storage_facility.go
  swagger-def/definitions/StorageFacility.yaml
  swagger/ghc.yaml
Labels: roci, ready-to-merge

#7779 MB-9679 Add Origin Duty Location Column to TIO Queue
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/queues/get_payment_requests_queue_parameters.go
  pkg/gen/ghcapi/ghcoperations/queues/get_payment_requests_queue_urlbuilder.go
  pkg/gen/ghcmessages/queue_payment_request.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/queues.go
  pkg/services/payment_request.go
  pkg/services/payment_request/payment_request_list_fetcher.go
  pkg/services/payment_request/payment_request_list_fetcher_test.go
  src/pages/Office/PaymentRequestQueue/PaymentRequestQueue.jsx
  src/pages/Office/PaymentRequestQueue/PaymentRequestQueue.test.jsx
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: ttv

#7773 MB-10083: Add AccountingCodes component to ServicesCounselingShipmentForm
  src/components/Office/AccountingCodes/AccountingCodes.jsx
  src/components/Office/AccountingCodes/AccountingCodes.stories.jsx
  src/components/Office/AccountingCodes/AccountingCodes.test.jsx
  src/components/Office/ServicesCounselingShipmentForm/ServicesCounselingShipmentForm.jsx
  src/components/Office/ServicesCounselingShipmentForm/ServicesCounselingShipmentForm.module.scss
  src/components/Office/ServicesCounselingShipmentForm/ServicesCounselingShipmentForm.stories.jsx
  src/components/Office/ServicesCounselingShipmentForm/ServicesCounselingShipmentForm.test.jsx
  src/pages/Office/ServicesCounselingAddShipment/ServicesCounselingAddShipment.jsx
  src/pages/Office/ServicesCounselingEditShipmentDetails/ServicesCounselingEditShipmentDetails.jsx
  src/types/accountingCodes.js
  src/utils/formatMtoShipment.js
  src/utils/formatMtoShipment.test.js
Labels: roci

#7763 MB-8561 Add functionality for tester to request crating and shuttling Service Items
  src/components/PrimeUI/CreateShipmentServiceItemForm/CreateShipmentServiceItemForm.jsx
  src/components/PrimeUI/CreateShipmentServiceItemForm/CreateShipmentServiceItemForm.test.jsx
  src/components/PrimeUI/CreateShipmentServiceItemForm/DestinationSITServiceItemForm.jsx
  src/components/PrimeUI/CreateShipmentServiceItemForm/DomesticCratingForm.jsx
  src/components/PrimeUI/CreateShipmentServiceItemForm/DomesticCratingForm.test.jsx
  src/components/PrimeUI/CreateShipmentServiceItemForm/OriginSITServiceItemForm.jsx
  src/components/PrimeUI/CreateShipmentServiceItemForm/ShuttleSITServiceItemForm.jsx
  src/components/PrimeUI/CreateShipmentServiceItemForm/ShuttleSitServiceItemForm.test.jsx
  src/components/PrimeUI/Shipment/Shipment.test.jsx
  src/constants/prime.js
  src/pages/PrimeUI/CreateServiceItem/CreateServiceItem.jsx
  src/pages/PrimeUI/CreateServiceItem/CreateServiceItem.test.jsx
Labels: Pamplemoose, ready-to-merge

#7775 MB-9939 (Storybook, SC) Update Orders edit form HHG & NTS TAC/SAC codes
  src/components/Customer/DodInfoForm/DodInfoForm.jsx
  src/components/Customer/NameForm/NameForm.jsx
  src/components/Customer/ServiceInfoForm/ServiceInfoForm.jsx
  src/components/DutyStationSearchBox/DutyStationSearchBox.jsx
  src/components/DutyStationSearchBox/DutyStationSearchBox.module.scss
  src/components/Modal/Modal.module.scss
  src/components/Modal/Modal.stories.jsx
  src/components/Office/AllowancesDetailForm/AllowancesDetailForm.jsx
  src/components/Office/AllowancesDetailForm/AllowancesDetailForm.module.scss
  src/components/Office/BillableWeight/EditBillableWeight/EditBillableWeight.jsx
  src/components/Office/EditMaxBillableWeightModal/EditMaxBillableWeightModal.jsx
  src/components/Office/OrdersDetailForm/OrdersDetailForm.jsx
  src/components/Office/OrdersDetailForm/OrdersDetailForm.module.scss
  src/components/Office/OrdersDetailForm/OrdersDetailForm.stories.jsx
  src/components/Office/OrdersDetailForm/OrdersDetailForm.test.jsx
  src/components/Office/RejectServiceItemModal/RejectServiceItemModal.jsx
  src/components/Office/ReviewSITExtensionModal/ReviewSITExtensionModal.jsx
  src/components/Office/ServicesCounselingShipmentForm/ServicesCounselingShipmentForm.module.scss
  src/components/Office/SubmitSITExtensionModal/SubmitSITExtensionModal.jsx
  src/components/PrimeUI/CreateShipmentServiceItemForm/DestinationSITServiceItemForm.jsx
  src/components/PrimeUI/CreateShipmentServiceItemForm/DomesticCratingForm.jsx
  src/components/PrimeUI/CreateShipmentServiceItemForm/DomesticCratingForm.test.jsx
  src/components/PrimeUI/CreateShipmentServiceItemForm/OriginSITServiceItemForm.jsx
  src/components/PrimeUI/CreateShipmentServiceItemForm/ShuttleSITServiceItemForm.jsx
  src/components/PrimeUI/CreateShipmentServiceItemForm/ShuttleSitServiceItemForm.test.jsx
  src/components/form/AddressFields/AddressFields.jsx
  src/components/form/BackupContactInfoFields/index.jsx
  src/components/form/ContactInfoFields/ContactInfoFields.jsx
  src/components/form/CustomerAltContactInfoFields/index.jsx
  src/components/form/CustomerContactInfoFields/index.jsx
  src/components/form/FormGroup.stories.jsx
  src/components/form/OptionalTag.jsx
  src/components/form/OptionalTag.module.scss
  src/components/form/fields/DatePickerInput.jsx
  src/components/form/fields/DropdownInput.jsx
  src/components/form/fields/MaskedTextField/MaskedTextField.jsx
  src/components/form/fields/MaskedTextField/MaskedTextField.stories.jsx
  src/components/form/fields/MaskedTextField/MaskedTextField.test.jsx
  src/components/form/fields/TextField/TextField.jsx
  src/components/form/fields/TextField/TextField.stories.jsx
  src/components/form/fields/TextField/TextField.test.jsx
  src/pages/Office/ServicesCounselingOrders/ServicesCounselingOrders.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdateForm.jsx
  src/shared/styles/_overrides.scss
  src/styles/form.module.scss
Labels: roci

#7734 [MB-10099] Validate facility info exists on moves with NTS-release shipment on service counselor submission
  pkg/services/move_task_order/move_task_order_updater.go
  pkg/services/move_task_order/move_task_order_updater_test.go
Labels: roci, ready-to-merge

#7785 [MB-10149] Pricing metadata changes for domestic NTS packing
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20211123155748_domestic_nts_packing_metadata.up.sql
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/service_item_param_name.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/re_service_code.go
  pkg/gen/primemessages/service_item_param_name.go
  pkg/gen/supportapi/embedded_spec.go
  pkg/gen/supportmessages/re_service_code.go
  pkg/models/re_service.go
  pkg/models/service_item_param_key.go
  pkg/services/ghcimport/fixtures/re_services_data.sql
  pkg/services/ghcimport/import_re_shipment_type_prices.go
  pkg/services/mto_shipment/mto_shipment_updater.go
  src/components/Office/ServiceItemCalculations/helpers.test.js
  src/components/Office/ServiceItemCalculations/serviceItemTestParams.js
  src/components/Office/ShipmentServiceItemsTable/ShipmentServiceItemsTable.jsx
  src/components/Office/ShipmentServiceItemsTable/ShipmentServiceItemsTable.test.jsx
  src/constants/serviceItems.js
  src/content/serviceItems.js
  swagger-def/definitions/ReServiceCode.yaml
  swagger-def/definitions/ServiceItemParamName.yaml
  swagger/ghc.yaml
  swagger/prime.yaml
  swagger/support.yaml
Labels: roci, ready-to-merge

#7787 MB-9780 prime tester can submit reweigh payload
  src/components/PrimeUI/CreateShipmentServiceItemForm/CreateShipmentServiceItemForm.test.jsx
  src/components/PrimeUI/Shipment/Shipment.jsx
  src/components/PrimeUI/Shipment/Shipment.test.jsx
  src/constants/routes.js
  src/pages/Office/index.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdateReweigh.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdateReweigh.test.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdateReweighForm.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdateReweighForm.test.jsx
  src/services/primeApi.js
Labels: Pamplemoose

#7778 [MB-10100] Add NTS TAC/SAC rows to orders display Storybook
  src/components/Office/DefinitionLists/OrdersList.jsx
  src/components/Office/DefinitionLists/OrdersList.stories.jsx
Labels: roci, ready-to-merge

#7786 [MB-10521] Use ReServiceCode constants instead of string literals
  pkg/edi/invoice/generator_test.go
  pkg/handlers/ghcapi/move_task_order_test.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/handlers/primeapi/mto_service_item_test.go
  pkg/handlers/primeapi/payloads/payload_to_model_test.go
  pkg/models/re_service.go
  pkg/payment_request/service_param_list_valid_test.go
  pkg/payment_request/service_param_value_lookups/actual_pickup_date_lookup_test.go
  pkg/payment_request/service_param_value_lookups/contract_code_lookup_test.go
  pkg/payment_request/service_param_value_lookups/distance_zip3_lookup_test.go
  pkg/payment_request/service_param_value_lookups/distance_zip_sit_dest_lookup_test.go
  pkg/payment_request/service_param_value_lookups/distance_zip_sit_origin_lookup_test.go
  pkg/payment_request/service_param_value_lookups/eia_fuel_price_lookup_test.go
  pkg/payment_request/service_param_value_lookups/number_days_sit_lookup_test.go
  pkg/payment_request/service_param_value_lookups/service_param_value_lookups_test.go
  pkg/payment_request/service_param_value_lookups/service_params_cache_test.go
  pkg/payment_request/service_param_value_lookups/zip_sit_origin_hhg_actual_address_lookup_test.go
  pkg/payment_request/service_param_value_lookups/zip_sit_origin_hhg_original_address_lookup_test.go
  pkg/services/event/notification_test.go
  pkg/services/ghcimport/ghc_rateengine_importer.go
  pkg/services/ghcimport/import_re_domestic_accessorial_prices.go
  pkg/services/ghcimport/import_re_domestic_accessorial_prices_test.go
  pkg/services/ghcimport/import_re_domestic_other_prices.go
  pkg/services/ghcimport/import_re_domestic_other_prices_test.go
  pkg/services/ghcimport/import_re_domestic_service_area_prices.go
  pkg/services/ghcimport/import_re_domestic_service_area_prices_test.go
  pkg/services/ghcimport/import_re_intl_accessorial_prices.go
  pkg/services/ghcimport/import_re_intl_accessorial_prices_test.go
  pkg/services/ghcimport/import_re_intl_other_prices.go
  pkg/services/ghcimport/import_re_intl_other_prices_test.go
  pkg/services/ghcimport/import_re_intl_prices.go
  pkg/services/ghcimport/import_re_intl_prices_test.go
  pkg/services/ghcimport/import_re_shipment_type_prices.go
  pkg/services/ghcimport/import_re_shipment_type_prices_test.go
  pkg/services/ghcimport/import_re_task_order_fees.go
  pkg/services/ghcimport/import_re_task_order_fees_test.go
  pkg/services/ghcimport/load_service_map.go
  pkg/services/ghcimport/load_service_map_test.go
  pkg/services/ghcrateengine/domestic_destination_pricer_test.go
  pkg/services/ghcrateengine/domestic_origin_pricer_test.go
  pkg/services/ghcrateengine/domestic_shorthaul_pricer_test.go
  pkg/services/move_task_order/move_task_order_creator_test.go
  pkg/services/move_task_order/move_task_order_updater_test.go
  pkg/services/mto_service_item/mto_service_item_creator_test.go
  pkg/services/mto_service_item/mto_service_item_validators.go
  pkg/services/mto_service_item/mto_service_item_validators_test.go
  pkg/services/payment_request/payment_request_creator_test.go
  pkg/testdatagen/scenario/e2ebasic.go
  pkg/testdatagen/scenario/shared.go
Labels: roci, ready-to-merge

#7800 MB-10086: Add shipment weight to NTS-release
  src/components/Office/ServicesCounselingShipmentForm/ServicesCounselingShipmentForm.jsx
  src/components/Office/ServicesCounselingShipmentForm/ServicesCounselingShipmentForm.test.jsx
  src/components/Office/ShipmentDisplay/ShipmentDisplay.jsx
  src/components/Office/ShipmentDisplay/ShipmentDisplay.test.jsx
  src/components/Office/ShipmentWeightInput/ShipmentWeightInput.jsx
  src/components/Office/ShipmentWeightInput/ShipmentWeightInput.module.scss
  src/components/Office/ShipmentWeightInput/ShipmentWeightInput.stories.jsx
  src/components/Office/ShipmentWeightInput/ShipmentWeightInput.test.jsx
  src/utils/formatMtoShipment.js
  src/utils/formatMtoShipment.test.js
Labels: roci

#7813 [MB-10471] bump up logging for audit service to Info from Debug
  pkg/services/audit/audit.go
Labels: Pamplemoose

#7741 MB-9936 Added SC order updating functionality to ghc.yaml
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/counseling_update_order_payload.go
  pkg/gen/ghcmessages/order.go
  pkg/gen/ghcmessages/update_order_payload.go
  pkg/handlers/ghcapi/orders_test.go
  pkg/services/order/order_updater.go
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: roci

#7808 Organize pr template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Pamplemoose
