Repository transcom/mymove, pull requests merged in 2021-07, with the labels that each got.

#6898 [MB-8062] Remove character limit from payment service item rejection reason db column
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20210629133827_remove_char_limit_payment_service_item_rejection_reason.up.sql
  pkg/handlers/ghcapi/payment_service_items_test.go
  src/components/Office/ReviewServiceItems/ServiceItemCard.module.scss
Labels: ttv

#6918 Bump storybook deps to 6.3.2: MB-8274
  package.json
  yarn.lock
Labels: Pamplemoose

#6900 MB-8417 Display customer and counselor remarks
  src/components/Office/RequestedShipments/RequestedShipments.jsx
  src/components/Office/RequestedShipments/RequestedShipments.test.jsx
  src/components/Office/ShipmentApprovalPreview.test.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.test.jsx
Labels: ttv

#6893 MB-8494 Add tests for Office User bulk upload
  src/components/Admin/ImportCsvButton/index.jsx
  src/components/Admin/ImportOfficeUserButton/index.jsx
  src/components/Admin/ImportOfficeUserButton/validation.js
  src/components/Admin/ImportOfficeUserButton/validation.test.js
  src/pages/Admin/OfficeUsers/OfficeUserList.jsx
Labels: roci

#6905 [MB-8312] New orders are included in the Move Details visual cue count
  src/pages/Office/ServicesCounselingEditShipmentDetails/ServicesCounselingEditShipmentDetails.test.jsx
  src/pages/Office/TXOMoveInfo/TXOMoveInfo.jsx
  src/pages/Office/TXOMoveInfo/TXOMoveInfo.test.jsx
Labels: ttv

#6923 [MB-8656] Convert GHC api shipment scheduled pickup date to be nullable to avoid zero date values on MTO page
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/m_t_o_shipment.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  src/components/Office/ShipmentDetails/ShipmentDetailsMain.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
  swagger/ghc.yaml
Labels: ttv

#6907 [MB-8611] Update FileUpload component to match MilMove styles
  src/components/FileUpload/FileUpload.jsx
  src/pages/MyMove/AmendOrders/AmendOrders.jsx
  src/pages/MyMove/AmendOrders/AmendOrders.module.scss
  src/shared/Uploader/index.css
Labels: A-Team

#6919 Fix bug that nullifies shipment ApprovedDate
  pkg/services/mto_shipment/mto_shipment_updater.go
  pkg/services/mto_shipment/mto_shipment_updater_test.go
Labels: bug

#6901 [MB-8204] Refactor TXO MTO fetch to not query for MoveTaskOrder
  cypress/integration/office/txo/tooFlows.js
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/ghcapi/ghcoperations/order/list_move_task_orders.go
  pkg/gen/ghcapi/ghcoperations/order/list_move_task_orders_parameters.go
  pkg/gen/ghcapi/ghcoperations/order/list_move_task_orders_responses.go
  pkg/gen/ghcapi/ghcoperations/order/list_move_task_orders_urlbuilder.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/orders.go
  pkg/services/event/ghc_endpoint.go
  pkg/services/mocks/MoveTaskOrderFetcher.go
  pkg/services/move_task_order.go
  pkg/services/move_task_order/move_task_order_fetcher.go
  pkg/services/move_task_order/move_task_order_fetcher_test.go
  src/constants/queryKeys.js
  src/hooks/queries.js
  src/hooks/queries.test.js
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.test.jsx
  src/services/ghcApi.js
  src/shared/Entities/modules/moveTaskOrders.js
  swagger/ghc.yaml
Labels: ttv

#6922 [MB-8344] Show alert on home screen after saving amending orders
  src/pages/MyMove/Home/index.jsx
  src/pages/MyMove/Home/index.test.jsx
Labels: A-Team

#6897 MB-8476 Wire up the Customer save button for uploading amended orders
  pkg/gen/internalapi/configure_mymove.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalapi/internaloperations/moves/submit_amended_orders.go
  pkg/gen/internalapi/internaloperations/moves/submit_amended_orders_parameters.go
  pkg/gen/internalapi/internaloperations/moves/submit_amended_orders_responses.go
  pkg/gen/internalapi/internaloperations/moves/submit_amended_orders_urlbuilder.go
  pkg/gen/internalapi/internaloperations/mymove_api.go
  pkg/gen/internalmessages/move_status.go
  pkg/handlers/internalapi/api.go
  pkg/handlers/internalapi/moves.go
  pkg/handlers/internalapi/moves_test.go
  pkg/models/move.go
  pkg/models/order.go
  pkg/services/move/move_router.go
  pkg/services/move/move_router_test.go
  pkg/testdatagen/scenario/devseed.go
  src/pages/MyMove/AmendOrders/AmendOrders.jsx
  src/pages/MyMove/AmendOrders/AmendOrders.test.jsx
  src/services/internalApi.js
  swagger/internal.yaml
Labels: Pamplemoose

#6908 [MB-8335] upload admended orders part2 (API changes)
  cmd/generate-test-data/main.go
  cmd/image-to-pdf/main.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalapi/internaloperations/orders/upload_amended_orders_parameters.go
  pkg/gen/internalapi/internaloperations/orders/upload_amended_orders_responses.go
  pkg/gen/internalmessages/orders.go
  pkg/gen/internalmessages/upload_payload.go
  pkg/handlers/ghcapi/move_task_order_test.go
  pkg/handlers/internalapi/orders.go
  pkg/handlers/internalapi/orders_test.go
  pkg/handlers/internalapi/personally_procured_move_attachments.go
  pkg/handlers/internalapi/personally_procured_move_attachments_test.go
  pkg/handlers/internalapi/uploads.go
  pkg/models/order.go
  pkg/models/order_test.go
  pkg/paperwork/paperwork_test.go
  pkg/services/invoice/store_invoice.go
  pkg/services/mocks/OrderUpdater.go
  pkg/services/order.go
  pkg/services/order/order_updater.go
  pkg/services/order/order_updater_test.go
  pkg/testdatagen/shared.go
  pkg/uploader/create_user_upload.go
  pkg/uploader/uploader.go
  pkg/uploader/user_uploader.go
  src/pages/MyMove/AmendOrders/AmendOrders.jsx
  src/services/internalApi.js
  swagger/internal.yaml
Labels: A-Team

#6935 Fix truncation in db_e2e_up
  Makefile
Labels: bug, ttv

#6921 Add estimated and actual weights to prime endpoints
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/m_t_o_service_item_shuttle.go
  pkg/gen/primemessages/update_m_t_o_service_item.go
  pkg/gen/primemessages/update_m_t_o_service_item_model_type.go
  pkg/gen/primemessages/update_m_t_o_service_item_s_i_t.go
  pkg/gen/primemessages/update_m_t_o_service_item_shuttle.go
  pkg/gen/supportapi/embedded_spec.go
  pkg/gen/supportmessages/m_t_o_service_item_shuttle.go
  pkg/handlers/primeapi/payloads/model_to_payload.go
  pkg/handlers/primeapi/payloads/payload_to_model.go
  pkg/handlers/supportapi/internal/payloads/model_to_payload.go
  pkg/services/mto_service_item/mto_service_item_creator_test.go
  pkg/services/mto_service_item/mto_service_item_updater_test.go
  pkg/services/mto_service_item/mto_service_item_validators.go
  pkg/services/mto_service_item/mto_service_item_validators_test.go
  pkg/services/validation.go
  swagger/prime.yaml
  swagger/support.yaml
Labels: roci

#6930 Prime API Documentation Updates: mtoShipment and createMTOShipment
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/move_task_order/fetch_m_t_o_updates.go
  pkg/gen/primeapi/primeoperations/mto_shipment/create_m_t_o_shipment.go
  pkg/gen/primeclient/move_task_order/move_task_order_client.go
  pkg/gen/primeclient/mto_shipment/mto_shipment_client.go
  swagger/prime.yaml
Labels: roci

#6958 [MB-8689] Bump storybook-related dependencies to 6.3.3
  package.json
  yarn.lock
Labels: A-Team

#6944 [MB-8664] log usage indicator for ISA 15 in 997, 824, and 858
  pkg/services/invoice/process_edi824.go
  pkg/services/invoice/process_edi997.go
  pkg/services/payment_request/payment_request_reviewed_processor.go
Labels: A-Team

#6960 [MB-8689] Update alpine from 3.12.3 to 3.12.7
  Dockerfile.migrations
  Dockerfile.migrations_local
  Dockerfile.reviewapp
  Dockerfile.tools
  Dockerfile.tools_local
Labels: A-Team

#6936 [MB-8332] Create folders for components without them in src/components/Office/
  src/components/Customer/Review/ShipmentCard/HHGShipmentCard/index.jsx
  src/components/Customer/Review/ShipmentCard/NTSRShipmentCard/index.jsx
  src/components/Customer/Review/ShipmentCard/NTSShipmentCard/index.jsx
  src/components/Customer/Review/ShipmentCard/PPMShipmentCard/index.jsx
  src/components/Office/ImportantShipmentDates/ImportantShipmentDates.jsx
  src/components/Office/ImportantShipmentDates/ImportantShipmentDates.test.jsx
  src/components/Office/ImportantShipmentDates/importantShipmentDates.module.scss
  src/components/Office/ImportantShipmentDates/importantShipmentDates.stories.jsx
  src/components/Office/RequestedShipments/RequestedShipments.jsx
  src/components/Office/ReviewServiceItems/ServiceItemCard.jsx
  src/components/Office/ShipmentApprovalPreview/ShipmentApprovalPreview.jsx
  src/components/Office/ShipmentApprovalPreview/ShipmentApprovalPreview.test.jsx
  src/components/Office/ShipmentApprovalPreview/shipmentApprovalPreview.module.scss
  src/components/Office/ShipmentApprovalPreview/shipmentApprovalPreview.stories.jsx
  src/components/Office/ShipmentContainer/ShipmentContainer.jsx
  src/components/Office/ShipmentContainer/ShipmentContainer.module.scss
  src/components/Office/ShipmentContainer/ShipmentContainer.stories.jsx
  src/components/Office/ShipmentContainer/ShipmentContainer.test.jsx
  src/components/Office/ShipmentDetails/ShipmentDetailsMain.jsx
  src/components/Office/ShipmentDisplay/ShipmentDisplay.jsx
  src/components/Office/ShipmentHeading/ShipmentHeading.jsx
  src/components/Office/ShipmentHeading/ShipmentHeading.test.jsx
  src/components/Office/ShipmentHeading/shipmentHeading.module.scss
  src/components/Office/ShipmentHeading/shipmentheading.stories.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
Labels: ttv

#6003 MB-6953 Remove MacOS version check in CAC scripts
  .pre-commit-config.yaml
  pkg/cli/cac.go
  scripts/cac-extract-cert
  scripts/cac-extract-fingerprint
  scripts/cac-extract-pubkey
  scripts/cac-extract-subject
  scripts/cac-extract-token-label
  scripts/cac-info
  scripts/cac-prereqs
  scripts/check-aws-vault-version
  scripts/check-chamber-version
  scripts/check-opensc-version
  scripts/prereqs
Labels: Pamplemoose

#6937 Felipe lee CAC Upload
  migrations/app/migrations_manifest.txt
  migrations/app/secure/20210706214857_felipe_cac.up.sql
Labels: Pamplemoose

#6969 [MB-8689] Bump storybook-related dependencies to 6.3.4
  package.json
  yarn.lock
Labels: A-Team

#6945 MB-8334 Counselors shouldn't be able to update shipment status
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/update_shipment.go
  pkg/handlers/ghcapi/internal/payloads/payload_to_model.go
  swagger/ghc.yaml
Labels: Pamplemoose

#6967 [MB-8670] Add interceptor reducer and basic test
  src/appReducer.js
  src/store/interceptor/reducer.js
  src/store/interceptor/reducer.test.js
Labels: Pamplemoose

#6959 [MB-8652] Adds estimated weight to the service item payload in the ghc api
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/m_t_o_service_item.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/primeapi/mto_service_item.go
  pkg/testdatagen/make_mto_service_item.go
  pkg/testdatagen/scenario/devseed.go
  swagger/ghc.yaml
Labels: ttv

#6970 MB-8287 return all service item details for update mto shipment
  pkg/services/mto_shipment/mto_shipment_updater.go
  pkg/services/mto_shipment/mto_shipment_updater_test.go
Labels: roci

#6972 [MB-8689] Update milmove-app hash to point to latest version
  .circleci/config.yml
  Dockerfile.local
  Dockerfile.migrations_local
  Dockerfile.reviewapp
  Dockerfile.tasks_local
  Dockerfile.tools_local
  Dockerfile.webhook_client
  Dockerfile.webhook_client_local
  Makefile
  scripts/gen-assets
  scripts/gen-server
  scripts/pre-commit-swagger-validate
Labels: A-Team

#6957 [MB-8505] Add Cypress test to cover the amended orders flow
  cypress/integration/mymove/orders.js
Labels: A-Team

#6968 [MB-8680] cleanup for UT and refactor to DRY up calling functions to create use…
  pkg/handlers/internalapi/orders_test.go
  pkg/handlers/internalapi/uploads.go
  pkg/services/order/order_updater.go
  pkg/uploader/create_user_upload.go
Labels: A-Team

#6971 MB-8517 additional address missing front end validation
  src/components/Customer/MtoShipmentForm/MtoShipmentForm.test.jsx
  src/components/Customer/MtoShipmentForm/getShipmentOptions.js
  src/components/Customer/MtoShipmentForm/validationSchemas.js
Labels: Pamplemoose

#6974 MB-8733 Fix Console Warning on Home Page
  src/pages/MyMove/Home/index.jsx
Labels: Pamplemoose

#6946 MB-8645 Remove image from crating sevice items
  src/components/Office/RejectServiceItemModal/RejectServiceItemModal.stories.jsx
  src/components/Office/RejectServiceItemModal/RejectServiceItemModal.test.jsx
  src/components/Office/RequestedServiceItemsTable/RequestedServiceItemsTable.jsx
  src/components/Office/RequestedServiceItemsTable/RequestedServiceItemsTable.stories.jsx
  src/components/Office/RequestedServiceItemsTable/RequestedServiceItemsTable.test.jsx
  src/components/Office/ServiceItemDetails/ServiceItemDetails.jsx
  src/components/Office/ServiceItemDetails/ServiceItemDetails.module.scss
  src/components/Office/ServiceItemDetails/ServiceItemDetails.test.jsx
  src/components/Office/ServiceItemsTable/ServiceItemsTable.jsx
  src/components/Office/ServiceItemsTable/ServiceItemsTable.module.scss
  src/components/Office/ServiceItemsTable/ServiceItemsTable.test.jsx
  src/components/ServiceItemTable/index.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
  src/stories/tables.stories.jsx
Labels: ttv

#6980 [MB-8689] Upgrade to go 1.16.5
  .circleci/config.yml
  .tool-versions
  Dockerfile.local
  Dockerfile.migrations_local
  Dockerfile.reviewapp
  Dockerfile.tasks_local
  Dockerfile.tools_local
  Dockerfile.webhook_client
  Dockerfile.webhook_client_local
  Makefile
  cypress/Dockerfile.cypress
  nix/default.nix
  scripts/gen-assets
  scripts/gen-server
  scripts/pre-commit-swagger-validate
  scripts/prereqs
Labels: A-Team

#6984 [MB-8746] Use default sort props in initial queue api request
  src/components/Table/TableQueue.jsx
Labels: ttv

#6985 MB-8507 move edit orders out of scenes
  src/components/Customer/EditOrdersForm/EditOrdersForm.jsx
  src/pages/MyMove/EditOrders.jsx
  src/scenes/MyMove/index.jsx
  src/types/index.js
  src/types/order.js
Labels: Pamplemoose

#6987 [MB-8757] Update golangci-lint to latest version
  .pre-commit-config.yaml
  pkg/iampostgres/iampostgres_test.go
  pkg/middleware/recovery.go
  pkg/paperwork/generator.go
  pkg/server/server_test.go
Labels: A-Team, needs-is3-review

#6990 MB-8508 refactor edit orders into a functional component
  src/pages/MyMove/EditOrders.jsx
Labels: Pamplemoose

#6997 [MB-8756] Update remaining pre-commit hooks
  .pre-commit-config.yaml
  .storybook/preview.js
  cypress/integration/mymove/serviceMemberProfile.js
  eslint-plugin-ato/.eslintrc
  eslint-plugin-ato/tests/no-unapproved-annotation.test.js
  scripts/generate-secure-migration
  scripts/pricing-import
  scripts/rds-snapshot-app-db
  scripts/upload-secure-migration
Labels: A-Team

#6983 [MB-8404] Shuttle service items display estimated weight on MTO page
  src/components/Office/RequestedServiceItemsTable/RequestedServiceItemsTable.jsx
  src/components/Office/RequestedServiceItemsTable/RequestedServiceItemsTable.stories.jsx
  src/components/Office/ReviewServiceItems/ReviewServiceItems.jsx
  src/components/Office/ServiceItemDetails/ServiceItemDetails.jsx
  src/components/Office/ServiceItemDetails/ServiceItemDetails.test.jsx
  src/components/Office/ServiceItemsTable/ServiceItemsTable.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
  src/types/serviceItemCard.js
  src/types/serviceItems.js
Labels: ttv

#6994 MB-8254 Pricing details domestic origin shuttle service
  src/components/Office/ServiceItemCalculations/ServiceItemCalculations.stories.jsx
  src/components/Office/ServiceItemCalculations/helpers.js
  src/components/Office/ServiceItemCalculations/helpers.test.js
  src/components/Office/ServiceItemCalculations/serviceItemTestParams.js
  src/constants/serviceItems.js
Labels: ttv

#6988 MB-8255 TIO can see pricing details for Dom. Destination Shuttle Service
  src/components/Office/PaymentRequestCard/PaymentRequestCard.jsx
  src/components/Office/PaymentRequestDetails/PaymentRequestDetails.jsx
  src/components/Office/ReviewServiceItems/ServiceItemCard.jsx
  src/components/Office/ServiceItemCalculations/ServiceItemCalculations.stories.jsx
  src/components/Office/ServiceItemCalculations/helpers.js
  src/components/Office/ServiceItemCalculations/helpers.test.js
  src/components/Office/ServiceItemCalculations/serviceItemTestParams.js
  src/components/ShipmentModificationTag/ShipmentModificationTag.jsx
  src/constants/serviceItems.js
Labels: ttv

#6998 [MB-1573] Implement lookup for CubicFeetCrating
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20210714221936_change_cubic_feet_crating_to_decimal.up.sql
  pkg/payment_request/service_param_value_lookups/cubic_feet_crating_lookup.go
  pkg/payment_request/service_param_value_lookups/cubic_feet_crating_lookup_test.go
  pkg/payment_request/service_param_value_lookups/service_param_value_lookups.go
Labels: A-Team

#6989 MB-2497 remove CanStandAlone parameter
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20210713232711_remove_can_stand_alone_parameter.up.sql
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/service_item_param_name.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/service_item_param_name.go
  pkg/models/service_item_param_key.go
  pkg/models/service_item_param_key_test.go
  pkg/services/payment_request/payment_request_creator_test.go
  pkg/testdatagen/testdata/webhook_test_data.json
  src/components/Office/ServiceItemCalculations/serviceItemTestParams.js
  swagger/ghc.yaml
  swagger/prime.yaml
Labels: A-Team

#6995 MB-8665 Move order validations to order_updater
  pkg/handlers/ghcapi/move_task_order_test.go
  pkg/models/move.go
  pkg/models/order.go
  pkg/models/order_test.go
  pkg/services/mocks/MTOServiceItemCreator.go
  pkg/services/move_task_order/move_task_order_updater.go
  pkg/services/move_task_order/move_task_order_updater_test.go
  pkg/services/mto_service_item.go
  pkg/services/mto_service_item/mto_service_item_creator.go
  pkg/services/mto_service_item/mto_service_item_creator_test.go
  pkg/services/order/order_updater.go
  pkg/services/order/order_updater_test.go
  pkg/services/order/validation.go
  pkg/services/query/query_builder.go
Labels: ttv

#6996 [MB-2610] Create destination and origin shuttling pricer
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/m_t_o_service_item_shuttle.go
  pkg/gen/supportapi/embedded_spec.go
  pkg/gen/supportmessages/m_t_o_service_item_shuttle.go
  pkg/payment_request/service_param_value_lookups/service_param_value_lookups_test.go
  pkg/payment_request/service_param_value_lookups/weight_actual_lookup.go
  pkg/payment_request/service_param_value_lookups/weight_actual_lookup_test.go
  pkg/payment_request/service_param_value_lookups/weight_billed_actual_lookup.go
  pkg/payment_request/service_param_value_lookups/weight_billed_actual_lookup_test.go
  pkg/payment_request/service_param_value_lookups/weight_estimated_lookup.go
  pkg/payment_request/service_param_value_lookups/weight_estimated_lookup_test.go
  pkg/services/ghc_rate_engine.go
  pkg/services/ghcrateengine/domestic_destination_shuttling_pricer.go
  pkg/services/ghcrateengine/domestic_destination_shuttling_pricer_test.go
  pkg/services/ghcrateengine/domestic_origin_shuttling_pricer.go
  pkg/services/ghcrateengine/domestic_origin_shuttling_pricer_test.go
  pkg/services/ghcrateengine/ghc_rate_engine_service_test.go
  pkg/services/ghcrateengine/pricer_helpers.go
  pkg/services/ghcrateengine/pricer_helpers_test.go
  pkg/services/ghcrateengine/pricer_query_helpers.go
  pkg/services/ghcrateengine/pricer_query_helpers_test.go
  pkg/services/ghcrateengine/service_item_pricer.go
  pkg/services/ghcrateengine/service_item_pricer_test.go
  pkg/services/mocks/DomesticDestinationShuttlingPricer.go
  pkg/services/mocks/DomesticOriginShuttlingPricer.go
  pkg/testdatagen/scenario/devseed.go
  swagger/prime.yaml
  swagger/support.yaml
Labels: A-Team

#6986 [MB-8641] Display counselor and customer remarks on Move Task Order view
  src/components/DataPoint/index.module.scss
  src/components/Office/ShipmentDetails/ShipmentDetails.module.scss
  src/components/Office/ShipmentDetails/ShipmentDetails.stories.jsx
  src/components/Office/ShipmentDetails/ShipmentDetailsMain.jsx
  src/components/Office/ShipmentRemarks/ShipmentRemarks.jsx
  src/components/Office/ShipmentRemarks/ShipmentRemarks.test.jsx
Labels: ttv

#7019 MB-8825 Add reason crating service items
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/m_t_o_service_item_domestic_crating.go
  pkg/handlers/primeapi/mto_service_item_test.go
  pkg/handlers/primeapi/payloads/model_to_payload.go
  pkg/handlers/primeapi/payloads/payload_to_model.go
  pkg/handlers/primeapi/payloads/payload_to_model_test.go
  pkg/handlers/primeapi/payloads/payloads_test.go
  swagger/prime.yaml
Labels: roci

#7030 MB-8673: Adds logic to interceptor reducer to handle events
  src/store/interceptor/reducer.js
  src/store/interceptor/reducer.test.js
Labels: Pamplemoose

#7036 [MB-8798] Fix deprecation warning for pdf files in the document viewer progress callback
  yarn.lock
Labels: ttv

#7037 [MB-7250] Add invoice support for origin/destination shuttle service
  pkg/services/invoice/ghc_payment_request_invoice_generator.go
  pkg/services/invoice/ghc_payment_request_invoice_generator_test.go
Labels: A-Team

#7041 MB-8801 add system error component
  src/components/SystemError/SystemError.stories.jsx
  src/components/SystemError/SystemError.test.jsx
  src/components/SystemError/index.jsx
Labels: Pamplemoose

#7045 [MB-7727] remove sftp connect
  Makefile
  cmd/fetch-from-syncada-via-sftp/logger.go
  cmd/fetch-from-syncada-via-sftp/main.go
  cmd/send-to-syncada-via-sftp/logger.go
  cmd/send-to-syncada-via-sftp/main.go
  pkg/cli/syncada_sftp.go
  pkg/cli/syncada_sftp_test.go
  pkg/handlers/supportapi/payment_request_test.go
  pkg/services/invoice/syncada_sftp_sender.go
  pkg/services/invoice/syncada_sftp_sender_test.go
  pkg/services/payment_request/payment_request_reviewed_processor_test.go
Labels: A-Team

#7025 MB-8796 Display SITPostalCode in MTO tab
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/m_t_o_service_item.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  src/components/Office/RejectServiceItemModal/RejectServiceItemModal.jsx
  src/components/Office/RequestedServiceItemsTable/RequestedServiceItemsTable.stories.jsx
  src/components/Office/RequestedServiceItemsTable/RequestedServiceItemsTable.test.jsx
  src/components/Office/ServiceItemDetails/ServiceItemDetails.jsx
  src/components/Office/ServiceItemDetails/ServiceItemDetails.test.jsx
  src/components/Office/ServiceItemsTable/ServiceItemsTable.test.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
  src/types/order.js
  src/types/serviceItems.js
  swagger/ghc.yaml
Labels: ttv

#7039 Enables Milmove system to handle repeated orders amendment cycles
  pkg/services/move/move_router.go
  pkg/services/move/move_router_test.go
Labels: ttv

#7027 [MB-8646] TOO is able to see crating details for MTO service items
  src/components/Office/RequestedServiceItemsTable/RequestedServiceItemsTable.test.jsx
  src/components/Office/ServiceItemDetails/ServiceItemDetails.jsx
  src/components/Office/ServiceItemDetails/ServiceItemDetails.test.jsx
  src/components/Office/ServiceItemsTable/ServiceItemsTable.test.jsx
Labels: ttv

#7048 [MB-8884] Uninstall dgrijalva/jwt-go and replace with golang-jwt/jwt module
  cmd/milmove/serve.go
  go.mod
  go.sum
  pkg/auth/authentication/login_gov.go
  pkg/dpsauth/auth.go
  pkg/dpsauth/cookie.go
  pkg/dpsauth/token.go
Labels: ttv

#7046 MB-8252 TIO can see pricing details for Domestic Crating
  pkg/handlers/ghcapi/mto_shipment.go
  pkg/testdatagen/scenario/devseed.go
  src/components/Office/ExpandableServiceItemRow/ExpandableServiceItemRow.jsx
  src/components/Office/PaymentRequestCard/PaymentRequestCard.jsx
  src/components/Office/PaymentRequestDetails/PaymentRequestDetails.jsx
  src/components/Office/ReviewServiceItems/ReviewServiceItems.jsx
  src/components/Office/ReviewServiceItems/ServiceItemCard.jsx
  src/components/Office/ServiceItemCalculations/ServiceItemCalculations.jsx
  src/components/Office/ServiceItemCalculations/ServiceItemCalculations.stories.jsx
  src/components/Office/ServiceItemCalculations/ServiceItemCalculations.test.jsx
  src/components/Office/ServiceItemCalculations/helpers.js
  src/components/Office/ServiceItemCalculations/helpers.test.js
  src/components/Office/ServiceItemCalculations/serviceItemTestParams.js
  src/constants/serviceItems.js
  src/content/serviceItems.js
  src/pages/Office/MovePaymentRequests/MovePaymentRequests.jsx
  src/pages/Office/PaymentRequestReview/PaymentRequestReview.jsx
Labels: ttv

#7047 MB-8577 Devseed refactor to better support sub-scenarios
  Makefile
  cmd/generate-test-data/main.go
  pkg/testdatagen/scenario/devseed.go
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/scenario/subscenarios.go
Labels: ttv

#7038 MB-8838 Updating setup documentation from an onboarding perspective
  README.md
Labels: Pamplemoose, roci

#7020 MB-8725 Update regular setup and nix setup documentation
  Makefile
  README.md
  nix/default.nix
  scripts/check-hosts-file
Labels: Pamplemoose

#7070 [MB-8801] System Error component style changes
  src/components/SystemError/SystemError.module.scss
  src/components/SystemError/SystemError.stories.jsx
  src/components/SystemError/SystemError.test.jsx
  src/components/SystemError/index.jsx
  src/stories/alerts.stories.jsx
Labels: Pamplemoose

#7079 MB-8857 Remove open in new window link from document viewer
  src/components/DocumentViewer/DocumentViewer.jsx
Labels: ttv

#7080 [MB-8806] Resolve flakey TOO Edit Allowances Cypress test
  cypress/integration/office/txo/tooFlows.js
Labels: ttv

#7069 MB-7432 Update fetchMTOUpdates query
  cmd/prime-api-client/main.go
  cmd/prime-api-client/prime/fetch_mto_updates_fast.go
  cmd/prime-api-client/utils/shared.go
  pkg/gen/primeapi/configure_mymove.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/move_task_order/fetch_m_t_o_updates_fast.go
  pkg/gen/primeapi/primeoperations/move_task_order/fetch_m_t_o_updates_fast_parameters.go
  pkg/gen/primeapi/primeoperations/move_task_order/fetch_m_t_o_updates_fast_responses.go
  pkg/gen/primeapi/primeoperations/move_task_order/fetch_m_t_o_updates_fast_urlbuilder.go
  pkg/gen/primeapi/primeoperations/mymove_api.go
  pkg/gen/primeclient/move_task_order/fetch_m_t_o_updates_fast_parameters.go
  pkg/gen/primeclient/move_task_order/fetch_m_t_o_updates_fast_responses.go
  pkg/gen/primeclient/move_task_order/move_task_order_client.go
  pkg/gen/primemessages/fetch_move_task_order.go
  pkg/gen/primemessages/fetch_move_task_orders.go
  pkg/handlers/primeapi/api.go
  pkg/handlers/primeapi/move_task_order.go
  pkg/handlers/primeapi/payloads/model_to_payload.go
  pkg/handlers/supportapi/move_task_order.go
  pkg/services/mocks/MoveTaskOrderFetcher.go
  pkg/services/move_task_order.go
  pkg/services/move_task_order/move_task_order_fetcher.go
  pkg/services/move_task_order/move_task_order_fetcher_test.go
  swagger/prime.yaml
Labels: roci

#7076 [MB-2612] Add dimensions for crating to lookups
  README.md
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20210726214608_add_dimension_param_keys.up.sql
  pkg/models/service_item_param_key.go
  pkg/payment_request/service_param_value_lookups/cubic_feet_crating_lookup.go
  pkg/payment_request/service_param_value_lookups/dimension_height_lookup.go
  pkg/payment_request/service_param_value_lookups/dimension_height_lookup_test.go
  pkg/payment_request/service_param_value_lookups/dimension_length_lookup.go
  pkg/payment_request/service_param_value_lookups/dimension_length_lookup_test.go
  pkg/payment_request/service_param_value_lookups/dimension_width_lookup.go
  pkg/payment_request/service_param_value_lookups/dimension_width_lookup_test.go
  pkg/payment_request/service_param_value_lookups/service_param_value_lookups.go
  pkg/unit/thousandth_inches.go
  pkg/unit/thousandth_inches_test.go
Labels: A-Team

#7092 Prime API Doc Review: Shuttling and Crating service items
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/m_t_o_service_item.go
  pkg/gen/primemessages/m_t_o_service_item_basic.go
  pkg/gen/primemessages/m_t_o_service_item_dest_s_i_t.go
  pkg/gen/primemessages/m_t_o_service_item_dimension.go
  pkg/gen/primemessages/m_t_o_service_item_domestic_crating.go
  pkg/gen/primemessages/m_t_o_service_item_origin_s_i_t.go
  pkg/gen/primemessages/m_t_o_service_item_shuttle.go
  pkg/gen/primemessages/m_t_o_service_item_status.go
  pkg/gen/primemessages/m_t_o_shipment.go
  pkg/handlers/primeapi/payloads/model_to_payload.go
  pkg/handlers/primeapi/payloads/payload_to_model.go
  pkg/handlers/primeapi/payloads/payload_to_model_test.go
  swagger/prime.yaml
Labels: roci

#7088 MB-8836 add prime get move by locator
  cmd/prime-api-client/prime/get_move_task_order.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/move_task_order/get_move_task_order.go
  pkg/gen/primeapi/primeoperations/move_task_order/get_move_task_order_parameters.go
  pkg/gen/primeapi/primeoperations/move_task_order/get_move_task_order_urlbuilder.go
  pkg/gen/primeapi/primeoperations/mymove_api.go
  pkg/gen/primeclient/move_task_order/get_move_task_order_parameters.go
  pkg/gen/primeclient/move_task_order/get_move_task_order_responses.go
  pkg/gen/primeclient/move_task_order/move_task_order_client.go
  pkg/handlers/ghcapi/move_task_order.go
  pkg/handlers/primeapi/move_task_order.go
  pkg/handlers/primeapi/move_task_order_test.go
  pkg/handlers/primeapi/payloads/model_to_payload_test.go
  pkg/handlers/supportapi/move_task_order.go
  pkg/services/mocks/MoveTaskOrderFetcher.go
  pkg/services/move_task_order.go
  pkg/services/move_task_order/move_task_order_fetcher.go
  pkg/services/move_task_order/move_task_order_fetcher_test.go
  pkg/services/move_task_order/move_task_order_updater.go
  swagger/prime.yaml
Labels: roci

#7096 [MB-8827] Upgrade to go 1.16.6
  .circleci/config.yml
  .tool-versions
  Dockerfile.local
  Dockerfile.migrations_local
  Dockerfile.reviewapp
  Dockerfile.tasks_local
  Dockerfile.tools_local
  Dockerfile.webhook_client
  Dockerfile.webhook_client_local
  Makefile
  README.md
  cypress/Dockerfile.cypress
  nix/default.nix
  scripts/gen-assets
  scripts/gen-server
  scripts/pre-commit-swagger-validate
  scripts/prereqs
Labels: A-Team

#7086 MB-8839 Next button link from shipment review page to agreement page
  src/pages/MyMove/Review/Review.test.jsx
  src/pages/MyMove/Review/index.jsx
  src/scenes/MyMove/getWorkflowRoutes.jsx
Labels: Pamplemoose

#7087 [MB-8256] TIO can see pricing details for domestic uncrating
  src/components/Office/ServiceItemCalculations/ServiceItemCalculations.stories.jsx
  src/components/Office/ServiceItemCalculations/ServiceItemCalculations.test.jsx
  src/components/Office/ServiceItemCalculations/helpers.js
  src/components/Office/ServiceItemCalculations/helpers.test.js
  src/components/Office/ServiceItemCalculations/serviceItemTestParams.js
  src/constants/serviceItems.js
Labels: ttv

#7090 MB-8942 Make query service obj error msgs more generic
  pkg/services/query/query_builder.go
  pkg/services/query/query_builder_test.go
Labels: Pamplemoose
