Repository transcom/mymove, pull requests merged in 2021-10, with the labels that each got.

#7484 [MB-9619] Modify CODEOWNERS & migrate PrimeUI components and pages outside of Office
  .github/CODEOWNERS
  src/components/PrimeUI/PrimeSimulatorListMoveCard/PrimeSimulatorListMoveCard.jsx
  src/components/PrimeUI/PrimeSimulatorListMoveCard/PrimeSimulatorListMoveCard.module.scss
  src/pages/Office/index.jsx
  src/pages/PrimeUI/PrimeSimulatorAvailableMoves/PrimeSimulatorAvailableMoves.jsx
  src/pages/PrimeUI/PrimeSimulatorAvailableMoves/PrimeSimulatorAvailableMoves.module.scss
Labels: roci, moose

#7476 MB-9285 Add move weights to MTO left nav
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.test.jsx
Labels: ttv

#7475 MB-9622 react select upgrade
  package.json
  src/components/DutyStationSearchBox/DutyStationSearchBox.jsx
  src/components/Table/Filters/MultiSelectCheckBoxFilter.module.scss
  yarn.lock
Labels: roci, dependencies

#7489 MB-9607 yellow alert should go away
  src/pages/Office/ReviewBillableWeight/ReviewBillableWeight.jsx
  src/pages/Office/ReviewBillableWeight/ReviewBillableWeight.test.jsx
Labels: Voltron

#7502 MB-9605 Reweigh remarks for shipment should not show if empty
  pkg/testdatagen/make_reweigh.go
  src/components/Office/BillableWeight/ShipmentCard/ShipmentCard.jsx
  src/components/Office/BillableWeight/ShipmentCard/ShipmentCard.module.scss
  src/components/Office/BillableWeight/ShipmentCard/ShipmentCard.test.jsx
Labels: Voltron

#7479 MB-9535 fix billable weight hint texts
  src/components/Office/BillableWeight/EditBillableWeight/EditBillableWeight.jsx
  src/components/Office/BillableWeight/EditBillableWeight/EditBillableWeight.test.jsx
  src/components/Office/BillableWeight/ShipmentCard/ShipmentCard.jsx
  src/components/Office/BillableWeight/ShipmentCard/ShipmentCard.stories.jsx
  src/pages/Office/ReviewBillableWeight/ReviewBillableWeight.jsx
Labels: Voltron

#7494 [MB-9611] Add SIT summary to SIT extension modals
  pkg/testdatagen/scenario/bandwidth.go
  pkg/testdatagen/scenario/shared.go
  src/components/DataTableWrapper/index.jsx
  src/components/Office/ImportantShipmentDates/ImportantShipmentDates.jsx
  src/components/Office/ReviewSITExtensionModal/ReviewSITExtensionModal.jsx
  src/components/Office/ReviewSITExtensionModal/ReviewSITExtensionModal.module.scss
  src/components/Office/ReviewSITExtensionModal/ReviewSITExtensionModal.stories.jsx
  src/components/Office/ReviewSITExtensionModal/ReviewSITExtensionModal.test.jsx
  src/components/Office/ShipmentAddresses/ShipmentAddresses.jsx
  src/components/Office/ShipmentDetails/ShipmentDetails.module.scss
  src/components/Office/ShipmentDetails/ShipmentDetailsMain.jsx
  src/components/Office/ShipmentRemarks/ShipmentRemarks.jsx
  src/components/Office/ShipmentSITExtensions/ShipmentSITExtensions.jsx
  src/components/Office/ShipmentSITExtensions/ShipmentSITExtensions.module.scss
  src/components/Office/ShipmentSITExtensions/ShipmentSITExtensions.test.jsx
  src/components/Office/ShipmentSITExtensions/ShipmentSITExtensionsTestParams.js
  src/components/Office/ShipmentWeightDetails/ShipmentWeightDetails.jsx
  src/components/Office/SubmitSITExtensionModal/SubmitSITExtensionModal.jsx
  src/components/Office/SubmitSITExtensionModal/SubmitSITExtensionModal.module.scss
  src/components/Office/SubmitSITExtensionModal/SubmitSITExtensionModal.stories.jsx
  src/components/Office/SubmitSITExtensionModal/SubmitSITExtensionModal.test.jsx
  src/stories/tables.stories.jsx
Labels: ttv, ready-to-merge

#7488 MB-9604 Bug yellow highlights for original and reweigh weights
  pkg/testdatagen/scenario/shared.go
  src/components/Office/BillableWeight/ShipmentCard/ShipmentCard.jsx
  src/components/Office/BillableWeight/ShipmentCard/ShipmentCard.module.scss
  src/components/Office/BillableWeight/ShipmentCard/ShipmentCard.test.jsx
  src/pages/Office/ReviewBillableWeight/ReviewBillableWeight.jsx
Labels: Voltron

#7509 [MB-9536] fix styling issues on editbillableweights
  src/components/Office/BillableWeight/EditBillableWeight/EditBillableWeight.module.scss
  src/components/Office/BillableWeight/ShipmentCard/ShipmentCard.module.scss
Labels: Voltron
