Repository transcom/mymove, pull requests merged in 2021-09, with the labels that each got.

#7273 MB-8953 Remove fetchMTOUpdates from the Prime API
  cmd/prime-api-client/main.go
  cmd/prime-api-client/prime/fetch_mto_updates.go
  cmd/prime-api-dev/main.go
  cmd/prime-api-dev/scripts/payment_requests.go
  pkg/gen/primeapi/configure_mymove.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/move_task_order/fetch_m_t_o_updates.go
  pkg/gen/primeapi/primeoperations/move_task_order/fetch_m_t_o_updates_parameters.go
  pkg/gen/primeapi/primeoperations/move_task_order/fetch_m_t_o_updates_responses.go
  pkg/gen/primeapi/primeoperations/move_task_order/fetch_m_t_o_updates_urlbuilder.go
  pkg/gen/primeapi/primeoperations/mymove_api.go
  pkg/gen/primeclient/move_task_order/fetch_m_t_o_updates_parameters.go
  pkg/gen/primeclient/move_task_order/fetch_m_t_o_updates_responses.go
  pkg/gen/primeclient/move_task_order/move_task_order_client.go
  pkg/gen/primemessages/move_task_orders.go
  pkg/handlers/primeapi/api.go
  pkg/handlers/primeapi/move_task_order.go
  pkg/handlers/primeapi/move_task_order_test.go
  pkg/handlers/primeapi/payloads/model_to_payload.go
  scripts/run-e2e-mtls-test-docker
  swagger/prime.yaml
Labels: roci

#7259 [MB-9257] Create EditBillableWeight storybook component"
  src/components/Office/BillableWeight/EditBillableWeight/EditBillableWeight.jsx
  src/components/Office/BillableWeight/EditBillableWeight/EditBillableWeight.module.scss
  src/components/Office/BillableWeight/EditBillableWeight/EditBillableWeight.stories.jsx
  src/components/Office/BillableWeight/EditBillableWeight/EditBillableWeight.test.jsx
  src/components/Office/BillableWeight/ShipmentCard/ShipmentCard.jsx
  src/components/Office/BillableWeight/ShipmentCard/ShipmentCard.module.scss
Labels: Voltron

#7217 Update prereqs script to support nix
  Makefile
  nix/default.nix
  scripts/check-bash-version
  scripts/check-chamber-version
  scripts/check-opensc-version
  scripts/prereqs
Labels: A-Team

#7290 MB-9315 clean up ContactInfo.test.jsx console logs
  src/pages/MyMove/Profile/ContactInfo.test.jsx
Labels: Pamplemoose

#7274 MB-9306 create prime update reweigh endpoint
  pkg/gen/primeapi/configure_mymove.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/mto_shipment/update_reweigh.go
  pkg/gen/primeapi/primeoperations/mto_shipment/update_reweigh_parameters.go
  pkg/gen/primeapi/primeoperations/mto_shipment/update_reweigh_responses.go
  pkg/gen/primeapi/primeoperations/mto_shipment/update_reweigh_urlbuilder.go
  pkg/gen/primeapi/primeoperations/mymove_api.go
  pkg/gen/primeclient/mto_shipment/mto_shipment_client.go
  pkg/gen/primeclient/mto_shipment/update_reweigh_parameters.go
  pkg/gen/primeclient/mto_shipment/update_reweigh_responses.go
  pkg/gen/primemessages/m_t_o_shipment.go
  pkg/gen/primemessages/reweigh.go
  pkg/gen/primemessages/reweigh_requester.go
  pkg/gen/primemessages/update_reweigh.go
  pkg/handlers/primeapi/api.go
  pkg/handlers/primeapi/move_task_order_test.go
  pkg/handlers/primeapi/payloads/model_to_payload.go
  pkg/handlers/primeapi/payloads/model_to_payload_test.go
  pkg/handlers/primeapi/payloads/payload_to_model.go
  pkg/handlers/primeapi/payloads/payload_to_model_test.go
  pkg/handlers/primeapi/reweigh.go
  pkg/handlers/primeapi/reweigh_test.go
  pkg/services/move_task_order/move_task_order_fetcher.go
  pkg/services/reweigh/reweigh_updater.go
  pkg/services/reweigh/reweigh_updater_test.go
  pkg/services/reweigh/validation.go
  pkg/services/reweigh/validation_test.go
  swagger/prime.yaml
Labels: roci

#7293 [MB-8787] Auto reweigh request check when prime updates shipment actual weight
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/mto_shipment.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/handlers/internalapi/api.go
  pkg/handlers/internalapi/mto_shipment_test.go
  pkg/handlers/primeapi/api.go
  pkg/handlers/primeapi/mto_shipment_test.go
  pkg/services/mocks/MoveWeights.go
  pkg/services/mocks/ShipmentReweighRequester.go
  pkg/services/move.go
  pkg/services/move/move_weights.go
  pkg/services/move/move_weights_test.go
  pkg/services/mto_shipment.go
  pkg/services/mto_shipment/mto_shipment_updater.go
  pkg/services/mto_shipment/mto_shipment_updater_test.go
  pkg/services/mto_shipment/shipment_reweigh_requester.go
  pkg/services/mto_shipment/shipment_reweigh_requester_test.go
Labels: ttv

#7278 MB-9323 TOO sees sit extension request history be
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/ghcapi/ghcoperations/shipment/approve_sit_extension.go
  pkg/gen/ghcapi/ghcoperations/shipment/approve_sit_extension_parameters.go
  pkg/gen/ghcapi/ghcoperations/shipment/approve_sit_extension_responses.go
  pkg/gen/ghcapi/ghcoperations/shipment/approve_sit_extension_urlbuilder.go
  pkg/gen/ghcmessages/approve_sit_extension.go
  pkg/gen/ghcmessages/m_t_o_shipment.go
  pkg/gen/ghcmessages/sit_extension.go
  pkg/gen/ghcmessages/sit_extensions.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/mto_shipment.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/testdatagen/make_sit_extension.go
  pkg/testdatagen/scenario/devseed.go
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/scenario/subscenarios.go
  pkg/testdatagen/shared.go
  swagger/ghc.yaml
Labels: ttv

#7305 [MB-9038] UpdateMTOShipment can review billable weight
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/m_t_o_shipment.go
  pkg/gen/ghcmessages/update_shipment.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/internal/payloads/payload_to_model.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/services/mto_shipment/mto_shipment_updater.go
  pkg/testdatagen/make_mto_shipment.go
  pkg/testdatagen/scenario/bandwidth.go
  swagger/ghc.yaml
Labels: Voltron

#7317 [MB-8898] Recalculate payment request service
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20210903211741_recalculation_payment_request.up.sql
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/payment_request.go
  pkg/gen/ghcmessages/payment_request_status.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/payment_request.go
  pkg/gen/primemessages/payment_request_status.go
  pkg/gen/supportapi/embedded_spec.go
  pkg/gen/supportapi/supportoperations/payment_request/update_payment_request_status.go
  pkg/gen/supportclient/payment_request/payment_request_client.go
  pkg/gen/supportmessages/payment_request.go
  pkg/gen/supportmessages/payment_request_status.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/payment_request_test.go
  pkg/handlers/primeapi/payloads/model_to_payload.go
  pkg/handlers/primeapi/payment_request_test.go
  pkg/handlers/supportapi/internal/payloads/model_to_payload.go
  pkg/handlers/supportapi/payment_request.go
  pkg/handlers/supportapi/payment_request_test.go
  pkg/models/payment_request.go
  pkg/models/payment_request_test.go
  pkg/models/service_param.go
  pkg/services/event/notification_payloads.go
  pkg/services/mocks/PaymentRequestRecalculator.go
  pkg/services/payment_request.go
  pkg/services/payment_request/payment_request_recalculator.go
  pkg/services/payment_request/payment_request_recalculator_test.go
  pkg/testdatagen/make_mto_service_item.go
  src/constants/paymentRequestStatus.js
  src/shared/constants.js
  src/shared/formatters.test.js
  swagger/ghc.yaml
  swagger/prime.yaml
  swagger/support.yaml
Labels: A-Team

#7324 MB-9396 Update react-admin to 3.18.0
  package.json
  src/pages/Admin/AdminUsers/AdminUserShow.jsx
  src/pages/Admin/Moves/MoveShow.jsx
  src/pages/Admin/OfficeUsers/OfficeUserShow.jsx
  src/pages/Admin/Users/UserShow.jsx
  src/pages/Admin/WebhookSubscriptions/WebhookSubscriptionShow.jsx
  yarn.lock
Labels: roci

#7285 [MB-9278] create service object to calculate billable weight for a shipment
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/m_t_o_shipment.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/services/mocks/ShipmentBillableWeightCalculator.go
  pkg/services/mto_shipment.go
  pkg/services/mto_shipment/shipment_billable_weight.go
  pkg/services/mto_shipment/shipment_billable_weight_test.go
  swagger/ghc.yaml
Labels: Voltron

#7297 MB 9119 incorporate components into billable weight page
  src/constants/routes.js
  src/pages/Office/DocumentViewerSidebar/DocumentViewerSidebar.module.scss
  src/pages/Office/MoveAllowances/MoveAllowances.jsx
  src/pages/Office/MoveDocumentWrapper/MoveDocumentWrapper.jsx
  src/pages/Office/Orders/Orders.jsx
  src/pages/Office/ReviewBillableWeight/ReviewBillableWeight.jsx
  src/pages/Office/ReviewBillableWeight/ReviewBillableWeight.test.jsx
  src/pages/Office/ServicesCounselingMoveAllowances/ServicesCounselingMoveAllowances.jsx
  src/pages/Office/ServicesCounselingMoveDocumentWrapper/ServicesCounselingMoveDocumentWrapper.jsx
  src/pages/Office/ServicesCounselingMoveDocumentWrapper/ServicesCounselingMoveDocumentWrapper.module.scss
  src/pages/Office/ServicesCounselingOrders/ServicesCounselingOrders.jsx
  src/styles/documentViewerWithSidebar.module.scss
Labels: Voltron

#7286 MB-8097 Swap to new integration cert variable and refactor SendToGex channel
  Makefile
  cmd/milmove-tasks/post_file_to_gex.go
  cmd/milmove-tasks/process_edis.go
  cmd/milmove/serve.go
  cmd/send-to-gex/main.go
  cmd/webhook-client/utils/connection.go
  pkg/cli/gex.go
  pkg/handlers/supportapi/payment_request.go
  pkg/payment_request/send_to_syncada.go
  pkg/payment_request/send_to_syncada_test.go
  pkg/services/invoice.go
  pkg/services/invoice/gex_sender_http.go
  pkg/services/invoice/gex_sender_http_test.go
  pkg/services/mocks/GexSender.go
  pkg/services/payment_request/payment_request_reviewed_processor_test.go
Labels: A-Team

#7337 Update hash for circleci-docker updates
  .circleci/config.yml
  Dockerfile.local
  Dockerfile.migrations_local
  Dockerfile.reviewapp
  Dockerfile.tasks_local
  Dockerfile.tools_local
  Dockerfile.webhook_client
  Dockerfile.webhook_client_local
  Makefile
  cypress/Dockerfile.cypress
  scripts/gen-assets
  scripts/gen-server
  scripts/pre-commit-swagger-validate
Labels: roci

#7364 MB-9248 Update documentation related to Swagger updates
  README.md
Labels: roci

#7342 MB-9361 Refactor service item updater
  pkg/handlers/ghcapi/mto_service_items.go
  pkg/handlers/ghcapi/mto_service_items_test.go
  pkg/handlers/supportapi/mto_service_item.go
  pkg/services/mocks/MTOServiceItemUpdater.go
  pkg/services/mto_service_item.go
  pkg/services/mto_service_item/mto_service_item_creator.go
  pkg/services/mto_service_item/mto_service_item_creator_test.go
  pkg/services/mto_service_item/mto_service_item_updater.go
  pkg/services/mto_service_item/mto_service_item_updater_test.go
  pkg/services/mto_service_item/validation.go
  pkg/services/order/excess_weight_risk_manager.go
  pkg/testdatagen/scenario/shared.go
Labels: ttv

#7359 [MB-9126] Max billable weights page
  src/components/Office/BillableWeight/EditBillableWeight/EditBillableWeight.jsx
  src/components/Office/BillableWeight/EditBillableWeight/EditBillableWeight.module.scss
  src/components/Office/WeightSummary/WeightSummary.jsx
  src/components/Office/WeightSummary/WeightSummary.module.scss
  src/components/Office/WeightSummary/WeightSummary.stories.jsx
  src/components/Office/WeightSummary/WeightSummary.test.jsx
  src/components/ShipmentList/index.jsx
  src/hooks/custom.js
  src/hooks/custom.test.js
  src/pages/Office/ReviewBillableWeight/ReviewBillableWeight.jsx
  src/pages/Office/ReviewBillableWeight/ReviewBillableWeight.test.jsx
  src/utils/shipmentIsOverweight.test.js
  src/utils/shipmentWeights.js
  src/utils/shipmentWeights.test.js
Labels: Voltron

#7363 [MB-9378] GHC API listMTOShipments handler provides SIT summary info
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/mto_shipment/list_m_t_o_shipments_responses.go
  pkg/gen/ghcmessages/m_t_o_service_item.go
  pkg/gen/ghcmessages/m_t_o_shipment.go
  pkg/gen/ghcmessages/s_i_t_status.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/mto_shipment.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/services/mocks/MTOShipmentFetcher.go
  pkg/services/mto_shipment.go
  pkg/services/mto_shipment/mto_shipment_fetcher.go
  pkg/services/mto_shipment/shipment_sit_status.go
  pkg/services/mto_shipment/shipment_sit_status_test.go
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/scenario/subscenarios.go
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: ttv

#7344 [MB-9309] reweigh lookup implemented for pricing
  pkg/payment_request/service_param_value_lookups/service_param_value_lookups.go
  pkg/payment_request/service_param_value_lookups/service_param_value_lookups_test.go
  pkg/payment_request/service_param_value_lookups/weight_reweigh_lookup.go
  pkg/payment_request/service_param_value_lookups/weight_reweigh_lookup_test.go
  pkg/testdatagen/make_service_param.go
Labels: A-Team

#7353 MB-9125 TIO get and update max billable weight remarks
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/ghcapi/ghcoperations/order/update_max_billable_weight_as_t_i_o.go
  pkg/gen/ghcapi/ghcoperations/order/update_max_billable_weight_as_t_i_o_parameters.go
  pkg/gen/ghcapi/ghcoperations/order/update_max_billable_weight_as_t_i_o_responses.go
  pkg/gen/ghcapi/ghcoperations/order/update_max_billable_weight_as_t_i_o_urlbuilder.go
  pkg/gen/ghcmessages/move.go
  pkg/gen/ghcmessages/order.go
  pkg/gen/ghcmessages/update_max_billable_weight_as_t_i_o_payload.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/orders.go
  pkg/handlers/ghcapi/orders_test.go
  pkg/services/event/ghc_endpoint.go
  pkg/services/mocks/ExcessWeightRiskManager.go
  pkg/services/order.go
  pkg/services/order/excess_weight_risk_manager.go
  pkg/services/order/excess_weight_risk_manager_test.go
  swagger-def/ghc.yaml
  swagger-def/tags/order.yaml
  swagger/ghc.yaml
Labels: Voltron

#7354 [MB-9418] Add support API endpoint for recalculating payment request
  cmd/prime-api-client/main.go
  cmd/prime-api-client/support/recalculate_payment_request.go
  pkg/gen/supportapi/configure_mymove.go
  pkg/gen/supportapi/embedded_spec.go
  pkg/gen/supportapi/supportoperations/mymove_api.go
  pkg/gen/supportapi/supportoperations/payment_request/recalculate_payment_request.go
  pkg/gen/supportapi/supportoperations/payment_request/recalculate_payment_request_parameters.go
  pkg/gen/supportapi/supportoperations/payment_request/recalculate_payment_request_responses.go
  pkg/gen/supportapi/supportoperations/payment_request/recalculate_payment_request_urlbuilder.go
  pkg/gen/supportclient/payment_request/payment_request_client.go
  pkg/gen/supportclient/payment_request/recalculate_payment_request_parameters.go
  pkg/gen/supportclient/payment_request/recalculate_payment_request_responses.go
  pkg/handlers/supportapi/api.go
  pkg/handlers/supportapi/payment_request.go
  pkg/handlers/supportapi/payment_request_test.go
  pkg/services/payment_request/payment_request_recalculator.go
  swagger-def/support.yaml
  swagger/support.yaml
Labels: A-Team

#7295 [MB-9089] Prime can issue partial invoices for SIT
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20210831214156_add_sit_pr_start_and_end_dates.up.sql
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/service_item_param_name.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/service_item.go
  pkg/gen/primemessages/service_item_param_name.go
  pkg/handlers/primeapi/allowed_payment_service_item_params.go
  pkg/handlers/primeapi/allowed_payment_service_item_params_test.go
  pkg/handlers/primeapi/payment_request.go
  pkg/handlers/primeapi/payment_request_test.go
  pkg/models/service_item_param_key.go
  pkg/services/payment_request/payment_request_creator.go
  swagger-def/ghc.yaml
  swagger-def/prime.yaml
  swagger/ghc.yaml
  swagger/prime.yaml
Labels: A-Team

#7352 [MB-9111] too can submit and auto-approve SIT extension for customer
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/ghcapi/ghcoperations/shipment/create_sit_extension_as_t_o_o.go
  pkg/gen/ghcapi/ghcoperations/shipment/create_sit_extension_as_t_o_o_parameters.go
  pkg/gen/ghcapi/ghcoperations/shipment/create_sit_extension_as_t_o_o_responses.go
  pkg/gen/ghcapi/ghcoperations/shipment/create_sit_extension_as_t_o_o_urlbuilder.go
  pkg/gen/ghcmessages/create_s_i_t_extension_as_t_o_o.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/internal/payloads/payload_to_model.go
  pkg/handlers/ghcapi/mto_shipment.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/services/mto_shipment/sit_extension_creator_as_too.go
  pkg/services/mto_shipment/sit_extension_creator_as_too_test.go
  pkg/services/sit_extension.go
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: ttv

#7366 [MB-9026] add components to the review shipment weights sidebar
  pkg/testdatagen/make_reweigh.go
  src/components/Office/BillableWeight/EditBillableWeight/EditBillableWeight.jsx
  src/components/Office/BillableWeight/ShipmentCard/ShipmentCard.jsx
  src/components/Office/BillableWeight/ShipmentCard/ShipmentCard.module.scss
  src/components/Office/WeightSummary/WeightSummary.module.scss
  src/pages/Office/DocumentViewerSidebar/DocumentViewerSidebar.jsx
  src/pages/Office/DocumentViewerSidebar/DocumentViewerSidebar.module.scss
  src/pages/Office/ReviewBillableWeight/ReviewBillableWeight.jsx
  src/pages/Office/ReviewBillableWeight/ReviewBillableWeight.module.scss
  src/pages/Office/ReviewBillableWeight/ReviewBillableWeight.test.jsx
Labels: Voltron

#7372 MB-9340 Add service to upload an excess weight record
  pkg/services/mocks/MoveExcessWeightUploader.go
  pkg/services/mocks/UploadCreator.go
  pkg/services/move.go
  pkg/services/move/excess_weight_uploader.go
  pkg/services/move/excess_weight_uploader_test.go
  pkg/services/move/validation.go
  pkg/services/move/validation_test.go
  pkg/services/upload.go
  pkg/services/upload/upload_creator.go
  pkg/services/upload/upload_creator_test.go
  pkg/services/upload/upload_information_fetcher_test.go
  pkg/services/upload/upload_service_test.go
  pkg/uploader/allowed_file_types.go
Labels: roci

#7374 MB-9319, MB-9321: Fix console warnings emitted by client tests
  src/components/form/BackupContactInfoFields/BackupContactInfoFields.test.jsx
  src/pages/MyMove/Profile/BackupContact.test.jsx
  src/pages/MyMove/Profile/BackupMailingAddress.test.jsx
Labels: Pamplemoose

#7375 MB-9322: Fix console warnings emitted by client tests
  src/components/form/fields/DutyStationInput.test.jsx
  src/pages/MyMove/Profile/DutyStation.test.jsx
Labels: Pamplemoose

#7376 MB-9316: Cleans up DodInfo client test
  src/pages/MyMove/Profile/DodInfo.test.jsx
Labels: Pamplemoose

#7377 MB-9318: Cleans up CreateOrEditMtoShipment client tests
  src/pages/MyMove/CreateOrEditMtoShipment.jsx
  src/pages/MyMove/CreateOrEditMtoShipment.test.jsx
Labels: Pamplemoose

#7380 MB-9433 make it clear that calculate billable weight needs shipment reweigh eager loaded
  cmd/send-to-gex/main.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/update_reweigh.go
  pkg/handlers/primeapi/reweigh_test.go
  pkg/models/reweigh.go
  pkg/models/reweigh_test.go
  pkg/models/validators.go
  pkg/models/validators_test.go
  pkg/services/mto_shipment/shipment_billable_weight.go
  pkg/services/mto_shipment/shipment_billable_weight_test.go
  swagger-def/prime.yaml
  swagger/prime.yaml
Labels: Voltron

#7379 MB-9015: remove MTOServiceItemShuttle.description and any references
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/m_t_o_service_item_shuttle.go
  pkg/gen/supportapi/embedded_spec.go
  pkg/gen/supportmessages/m_t_o_service_item_shuttle.go
  pkg/handlers/primeapi/payloads/model_to_payload.go
  pkg/handlers/primeapi/payloads/payload_to_model.go
  pkg/handlers/supportapi/internal/payloads/model_to_payload.go
  pkg/services/event/notification_test.go
  swagger-def/prime.yaml
  swagger-def/support.yaml
  swagger/prime.yaml
  swagger/support.yaml
Labels: roci

#7395 [MB-9026] display blank field in shipment card when theres no destination address
  pkg/testdatagen/scenario/shared.go
  src/components/Office/BillableWeight/ShipmentCard/ShipmentCard.jsx
  src/pages/Office/MovePaymentRequests/MovePaymentRequests.jsx
  src/pages/Office/MovePaymentRequests/MovePaymentRequests.test.jsx
Labels: Voltron

#7385 [MB-9029] review billable weights side bar navigation
  src/components/Office/BillableWeight/ShipmentCard/ShipmentCard.jsx
  src/pages/Office/ReviewBillableWeight/ReviewBillableWeight.jsx
  src/pages/Office/ReviewBillableWeight/ReviewBillableWeight.test.jsx
Labels: Voltron

#7409 MB-9313 Filter out shipments for reviewing billable weights
  src/pages/Office/MovePaymentRequests/MovePaymentRequests.jsx
  src/pages/Office/ReviewBillableWeight/ReviewBillableWeight.jsx
Labels: Voltron

#7396 MB-9305 Consolidate move routing logic
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/handlers/ghcapi/orders.go
  pkg/handlers/ghcapi/orders_test.go
  pkg/handlers/internalapi/api.go
  pkg/handlers/internalapi/orders_test.go
  pkg/services/mocks/MoveRouter.go
  pkg/services/mocks/MoveTaskOrderUpdater.go
  pkg/services/move.go
  pkg/services/move/move_router.go
  pkg/services/move/move_router_test.go
  pkg/services/move_task_order.go
  pkg/services/move_task_order/move_task_order_updater.go
  pkg/services/mto_service_item/mto_service_item_creator.go
  pkg/services/mto_service_item/mto_service_item_updater.go
  pkg/services/mto_service_item/shared.go
  pkg/services/mto_shipment/sit_extension_approver.go
  pkg/services/mto_shipment/sit_extension_approver_test.go
  pkg/services/mto_shipment/sit_extension_denier.go
  pkg/services/mto_shipment/sit_extension_denier_test.go
  pkg/services/order/excess_weight_risk_manager.go
  pkg/services/order/excess_weight_risk_manager_test.go
  pkg/services/order/order_updater.go
  pkg/services/order/order_updater_test.go
  pkg/services/order/shared.go
  pkg/testdatagen/make_sit_extension.go
  pkg/testdatagen/scenario/devseed.go
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/scenario/subscenarios.go
Labels: ttv

#7411 [MB-9388] TIO can edit a shipment's billable weight and remarks
  src/components/Office/BillableWeight/EditBillableWeight/EditBillableWeight.jsx
  src/components/Office/BillableWeight/EditBillableWeight/EditBillableWeight.test.jsx
  src/components/Office/BillableWeight/ShipmentCard/ShipmentCard.jsx
  src/components/Office/BillableWeight/ShipmentCard/ShipmentCard.test.jsx
  src/components/Office/WeightSummary/WeightSummary.jsx
  src/pages/Office/ReviewBillableWeight/ReviewBillableWeight.jsx
  src/pages/Office/ReviewBillableWeight/ReviewBillableWeight.test.jsx
  src/services/ghcApi.js
Labels: Voltron

#7414 [MB-9338] Update lookup for WeightBilled pricing parameter
  pkg/payment_request/service_param_value_lookups/service_param_value_lookups_test.go
  pkg/payment_request/service_param_value_lookups/weight_billed_lookup.go
  pkg/payment_request/service_param_value_lookups/weight_billed_lookup_test.go
Labels: A-Team

#7393 [MB-9264] Add Notifications for Max Billable Weight
  pkg/testdatagen/scenario/shared.go
  src/components/Office/BillableWeight/BillableWeightCard/BillableWeightCard.jsx
  src/components/Office/BillableWeight/BillableWeightCard/BillableWeightCard.module.scss
  src/pages/Office/MovePaymentRequests/MovePaymentRequests.jsx
  src/pages/Office/MovePaymentRequests/MovePaymentRequests.module.scss
  src/pages/Office/MovePaymentRequests/MovePaymentRequests.test.jsx
  src/pages/Office/ReviewBillableWeight/ReviewBillableWeight.jsx
  src/pages/Office/ReviewBillableWeight/ReviewBillableWeight.test.jsx
Labels: Voltron

#7365 MB-9014 email customer on auto reweigh
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/mto_shipment.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/handlers/internalapi/api.go
  pkg/handlers/internalapi/mto_shipment_test.go
  pkg/handlers/primeapi/api.go
  pkg/handlers/primeapi/mto_shipment_test.go
  pkg/models/mto_shipments.go
  pkg/notifications/reweigh_requested.go
  pkg/notifications/reweigh_requested_test.go
  pkg/services/mocks/MoveWeights.go
  pkg/services/move.go
  pkg/services/move/move_weights.go
  pkg/services/move/move_weights_test.go
  pkg/services/mto_shipment/mto_shipment_updater.go
  pkg/services/mto_shipment/mto_shipment_updater_test.go
Labels: Pamplemoose

#7417 [MB-9255] New handler and service for partial payment of SIT service items for TIO
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/ghcapi/ghcoperations/payment_requests/get_shipments_payment_s_i_t_balance.go
  pkg/gen/ghcapi/ghcoperations/payment_requests/get_shipments_payment_s_i_t_balance_parameters.go
  pkg/gen/ghcapi/ghcoperations/payment_requests/get_shipments_payment_s_i_t_balance_responses.go
  pkg/gen/ghcapi/ghcoperations/payment_requests/get_shipments_payment_s_i_t_balance_urlbuilder.go
  pkg/gen/ghcmessages/shipment_payment_s_i_t_balance.go
  pkg/gen/ghcmessages/shipments_payment_s_i_t_balance.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/payment_request.go
  pkg/handlers/ghcapi/payment_request_test.go
  pkg/services/mocks/ShipmentsPaymentSITBalance.go
  pkg/services/payment_request.go
  pkg/services/payment_request/payment_request_shipments_sit_balance.go
  pkg/services/payment_request/payment_request_shipments_sit_balance_test.go
  pkg/testdatagen/make_prime_upload.go
  pkg/testdatagen/make_proof_of_service_doc.go
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/scenario/subscenarios.go
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: ttv

#7418 Bump js-cookie version to 3.x: MB-9397
  package.json
  public/swagger-ui/admin.html
  public/swagger-ui/api.html
  public/swagger-ui/ghc.html
  public/swagger-ui/internal.html
  scripts/copy-swagger-ui
  yarn.lock
Labels: dependencies, Pamplemoose

#7410 [MB-8758] TOO can approve and deny SIT extensions (frontend)
  src/components/Office/ReviewSITExtensionModal/ReviewSITExtensionModal.jsx
  src/components/Office/ReviewSITExtensionModal/ReviewSITExtensionModal.module.scss
  src/components/Office/ReviewSITExtensionModal/ReviewSITExtensionModal.stories.jsx
  src/components/Office/ReviewSITExtensionModal/ReviewSITExtensionModal.test.jsx
  src/components/Office/ShipmentDetails/ShipmentDetails.jsx
  src/components/Office/ShipmentDetails/ShipmentDetailsMain.jsx
  src/components/Office/ShipmentSITExtensions/ShipmentSITExtensions.jsx
  src/components/Office/ShipmentSITExtensions/ShipmentSITExtensions.module.scss
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
  src/services/ghcApi.js
Labels: ttv

#7415 [MB-9425] Weight Summary Component Hookup
  src/components/Office/BillableWeight/EditBillableWeight/EditBillableWeight.test.jsx
  src/components/Office/BillableWeight/ShipmentCard/ShipmentCard.jsx
  src/components/Office/WeightSummary/WeightSummary.jsx
  src/components/Office/WeightSummary/WeightSummary.stories.jsx
  src/components/Office/WeightSummary/WeightSummary.test.jsx
  src/pages/Office/ReviewBillableWeight/ReviewBillableWeight.jsx
  src/pages/Office/ReviewBillableWeight/ReviewBillableWeight.test.jsx
Labels: Voltron

#7424 [MB-9288] Switch to gorilla mux
  cmd/milmove/serve.go
  cmd/milmove/spa_handler.go
  go.mod
  go.sum
Labels: enhancement

#7434 [MB-9339] Fix parameter associations for shuttle services
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20210923180711_fix_shuttle_params.up.sql
Labels: A-Team

#7368 MB-9243 Create default sit days allowance for new shipments
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20210917011433_add_default_sit_days_allowance_to_existing_hhg_shipments.up.sql
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/models/mto_shipments.go
  pkg/services/mto_shipment/mto_shipment_creator.go
  pkg/services/mto_shipment/mto_shipment_creator_test.go
  pkg/services/mto_shipment/mto_shipment_service_test.go
  pkg/services/mto_shipment/mto_shipment_updater_test.go
  pkg/services/mto_shipment/shipment_approver_test.go
  pkg/services/mto_shipment/shipment_router_test.go
  pkg/services/mto_shipment/validation_test.go
Labels: Pamplemoose

#7428 MB-9265 add yellow alerts for missing weights
  src/components/Office/BillableWeight/BillableWeightCard/BillableWeightCard.stories.jsx
  src/components/Office/BillableWeight/BillableWeightCard/BillableWeightCard.test.jsx
  src/components/Office/BillableWeight/ShipmentCard/ShipmentCard.jsx
  src/components/Office/WeightSummary/WeightSummary.jsx
  src/components/ShipmentList/ShipmentList.stories.jsx
  src/components/ShipmentList/ShipmentList.test.jsx
  src/components/ShipmentList/index.jsx
  src/pages/Office/ReviewBillableWeight/ReviewBillableWeight.jsx
  src/pages/Office/ReviewBillableWeight/ReviewBillableWeight.module.scss
  src/pages/Office/ReviewBillableWeight/ReviewBillableWeight.test.jsx
Labels: Voltron

#7433 [MB-8758] Use correct operation ID for SIT extension approve/deny
  src/services/ghcApi.js
Labels: ttv

#7416 MB-8063 Refactor handler for updating payment service item status to use service object
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/payment_service_items.go
  pkg/handlers/ghcapi/payment_service_items_test.go
  pkg/services/mocks/PaymentServiceItemStatusUpdater.go
  pkg/services/payment_service_item.go
  pkg/services/payment_service_item/payment_service_item_service_test.go
  pkg/services/payment_service_item/payment_service_item_status_updater.go
  pkg/services/payment_service_item/payment_service_item_status_updater_test.go
  pkg/services/payment_service_item/validation.go
Labels: ttv

#7432 MB-8841: Fixes Orders and OrdersInfoForm tests
  src/components/Customer/EditOrdersForm/EditOrdersForm.test.jsx
  src/components/Customer/OrdersInfoForm/OrdersInfoForm.test.jsx
  src/pages/MyMove/Orders.test.jsx
Labels: Pamplemoose

#7440 MB-9563: No need to ignore gosec G104
  .golangci.yml
  .pre-commit-config.yaml
  cmd/generate-deploy-notes/main.go
Labels: ready-to-merge

#7452 [MB-9417] Rework upload handling in recalculated payment requests
  pkg/services/payment_request/payment_request_recalculator.go
  pkg/services/payment_request/payment_request_recalculator_test.go
Labels: A-Team

#6862 Remove mdspell/markdown-spellcheck
  .pre-commit-config.yaml
  .spelling
  Makefile
  README.md
  package.json
Labels: ready-to-merge

#7441 [MB-9266] add tags to payment request page
  src/components/Office/BillableWeight/BillableWeightCard/BillableWeightCard.jsx
  src/components/Office/BillableWeight/BillableWeightCard/BillableWeightCard.test.jsx
  src/components/ShipmentList/ShipmentList.test.jsx
  src/components/ShipmentList/index.jsx
  src/pages/Office/MovePaymentRequests/MovePaymentRequests.jsx
  src/pages/Office/MovePaymentRequests/MovePaymentRequests.module.scss
  src/pages/Office/MovePaymentRequests/MovePaymentRequests.test.jsx
  src/pages/Office/ReviewBillableWeight/ReviewBillableWeight.jsx
Labels: Voltron

#7443 MB-9244 Include pending SIT extension requests in visual tag counts (office app)
  src/components/Office/TXOTabNav/TXOTabNav.jsx
  src/components/Office/TXOTabNav/TXOTabNav.test.jsx
  src/pages/Office/MoveDetails/MoveDetails.jsx
  src/pages/Office/MoveDetails/MoveDetails.test.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.test.jsx
  src/pages/Office/MoveTaskOrder/moveTaskOrderUnitTestData.js
  src/pages/Office/TXOMoveInfo/TXOMoveInfo.jsx
Labels: ttv

#7442 MB-9298 Update move status when pending sit extension is created
  pkg/handlers/primeapi/api.go
  pkg/handlers/primeapi/sit_extension_test.go
  pkg/services/sit_extension/sit_extension_creator.go
  pkg/services/sit_extension/sit_extension_creator_test.go
Labels: roci

#7462 Fix sit_extension_creator_test
  pkg/services/sit_extension/sit_extension_creator_test.go
Labels: roci, ready-to-merge

#7450 [MB-7416] TIO Review Payment Request Service Items Shows Days In SIT balance
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/shipment_payment_s_i_t_balance.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/services/payment_request.go
  pkg/services/payment_request/payment_request_shipments_sit_balance.go
  pkg/services/payment_request/payment_request_shipments_sit_balance_test.go
  pkg/testdatagen/scenario/shared.go
  src/components/Office/DaysInSITAllowance/DaysInSITAllowance.jsx
  src/components/Office/DaysInSITAllowance/DaysInSITAllowance.module.scss
  src/components/Office/DaysInSITAllowance/DaysInSITAllowance.stories.jsx
  src/components/Office/DaysInSITAllowance/DaysInSITAllowance.test.jsx
  src/components/Office/ReviewServiceItems/ReviewServiceItems.jsx
  src/components/Office/ReviewServiceItems/ServiceItemCard.jsx
  src/components/Office/ReviewServiceItems/ServiceItemCard.module.scss
  src/components/Office/ReviewServiceItems/ServiceItemCard.stories.jsx
  src/components/Office/ReviewServiceItems/ServiceItemCard.test.jsx
  src/constants/queryKeys.js
  src/hooks/queries.js
  src/hooks/queries.test.js
  src/pages/Office/PaymentRequestReview/PaymentRequestReview.jsx
  src/pages/Office/PaymentRequestReview/PaymentRequestReview.test.jsx
  src/services/ghcApi.js
  src/shared/Entities/schema.js
  src/types/serviceItems.js
  src/utils/formatters.js
  src/utils/formatters.test.js
  src/utils/shipmentDisplay.jsx
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: ttv

#7406 [MB-9339] Hook up repricing service to weight updates for reweigh
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/handlers/internalapi/api.go
  pkg/handlers/internalapi/mto_shipment_test.go
  pkg/handlers/primeapi/api.go
  pkg/handlers/primeapi/mto_shipment_test.go
  pkg/handlers/primeapi/reweigh_test.go
  pkg/services/mocks/PaymentRequestShipmentRecalculator.go
  pkg/services/mto_shipment/mto_shipment_updater.go
  pkg/services/mto_shipment/mto_shipment_updater_test.go
  pkg/services/mto_shipment/shipment_billable_weight_test.go
  pkg/services/mto_shipment/shipment_cancellation_requester_test.go
  pkg/services/mto_shipment/shipment_deleter_test.go
  pkg/services/mto_shipment/shipment_diversion_approver_test.go
  pkg/services/mto_shipment/shipment_diversion_requester_test.go
  pkg/services/mto_shipment/shipment_rejecter_test.go
  pkg/services/mto_shipment/sit_extension_approver_test.go
  pkg/services/mto_shipment/sit_extension_denier_test.go
  pkg/services/payment_request.go
  pkg/services/payment_request/payment_request_recalculator.go
  pkg/services/payment_request/payment_request_recalculator_test.go
  pkg/services/payment_request/payment_request_shipment_recalculate.go
  pkg/services/payment_request/payment_request_shipment_recalculate_test.go
  pkg/services/reweigh/reweigh_updater.go
  pkg/services/reweigh/reweigh_updater_test.go
  pkg/services/reweigh/validation.go
  pkg/services/reweigh/validation_test.go
  pkg/testdatagen/make_mto_service_item.go
  pkg/testdatagen/make_payment_request.go
Labels: A-Team, ready-to-merge

#7460 [MB-9261] enable disable buttons on review payment request page
  pkg/testdatagen/scenario/shared.go
  src/components/Office/BillableWeight/BillableWeightCard/BillableWeightCard.jsx
  src/components/Office/BillableWeight/BillableWeightCard/BillableWeightCard.test.jsx
  src/components/Office/PaymentRequestCard/PaymentRequestCard.jsx
  src/components/Office/PaymentRequestCard/PaymentRequestCard.module.scss
  src/components/Office/PaymentRequestCard/PaymentRequestCard.test.jsx
  src/components/Office/WeightSummary/WeightSummary.jsx
  src/pages/Office/MovePaymentRequests/MovePaymentRequests.jsx
  src/pages/Office/ReviewBillableWeight/ReviewBillableWeight.jsx
  src/pages/Office/ReviewBillableWeight/ReviewBillableWeight.test.jsx
Labels: Voltron

#7445 MB-9308 Update requestedPickupDate and requestedDeliveryDate on update shipment
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/update_shipment.go
  pkg/handlers/ghcapi/internal/payloads/payload_to_model.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: A-Team, ready-to-merge

#7459 [MB-9524] Edit billable weight validation
  src/components/Office/BillableWeight/EditBillableWeight/EditBillableWeight.jsx
  src/components/Office/BillableWeight/EditBillableWeight/EditBillableWeight.module.scss
  src/components/Office/BillableWeight/EditBillableWeight/EditBillableWeight.stories.jsx
  src/components/Office/BillableWeight/EditBillableWeight/EditBillableWeight.test.jsx
  src/components/form/fields/MaskedTextField.jsx
  src/pages/Office/ReviewBillableWeight/ReviewBillableWeight.jsx
Labels: Voltron

#7466 Add missing IDs to sit extension data for movetaskorder page component test.
  src/pages/Office/MoveTaskOrder/moveTaskOrderUnitTestData.js
Labels: ready-to-merge

#7463 MB-9256 update service items calculations UI
  pkg/testdatagen/scenario/shared.go
  src/components/Office/ServiceItemCalculations/ServiceItemCalculations.jsx
  src/components/Office/ServiceItemCalculations/ServiceItemCalculations.test.jsx
  src/components/Office/ServiceItemCalculations/helpers.js
  src/components/Office/ServiceItemCalculations/helpers.test.js
  src/components/Office/ServiceItemCalculations/serviceItemTestParams.js
  src/constants/serviceItems.js
Labels: Voltron

#7407 MB-7289 TOO sees total days remaining for shipments in SIT (front-end
  cypress/integration/office/txo/tooFlows.js
  pkg/testdatagen/scenario/e2ebasic.go
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/scenario/subscenarios.go
  src/components/Office/ShipmentDetails/ShipmentDetails.jsx
  src/components/Office/ShipmentDetails/ShipmentDetails.stories.jsx
  src/components/Office/ShipmentDetails/ShipmentDetailsMain.jsx
  src/components/Office/ShipmentSITExtensions/ShipmentSITExtensions.jsx
  src/components/Office/ShipmentSITExtensions/ShipmentSITExtensions.module.scss
  src/components/Office/ShipmentSITExtensions/ShipmentSITExtensions.stories.jsx
  src/components/Office/ShipmentSITExtensions/ShipmentSITExtensions.test.jsx
  src/components/Office/ShipmentSITExtensions/ShipmentSITExtensionsTestParams.js
  src/pages/Office/MoveTaskOrder/moveTaskOrderUnitTestData.js
  src/types/shipment.js
  src/types/sitStatusShape.js
Labels: ttv

#7419 [MB-9253] use new date params in number days sit lookup
  pkg/payment_request/service_param_value_lookups/number_days_sit_lookup.go
  pkg/payment_request/service_param_value_lookups/number_days_sit_lookup_test.go
  pkg/services/payment_request/payment_request_creator.go
Labels: A-Team, ready-to-merge

#7451 [MB-4727] TOO can submit and approve SIT extensions (frontend)
  pkg/handlers/ghcapi/internal/payloads/payload_to_model.go
  src/components/Office/ShipmentDetails/ShipmentDetails.jsx
  src/components/Office/ShipmentDetails/ShipmentDetailsMain.jsx
  src/components/Office/ShipmentSITExtensions/ShipmentSITExtensions.jsx
  src/components/Office/ShipmentSITExtensions/ShipmentSITExtensions.module.scss
  src/components/Office/SubmitSITExtensionModal/SubmitSITExtensionModal.jsx
  src/components/Office/SubmitSITExtensionModal/SubmitSITExtensionModal.module.scss
  src/components/Office/SubmitSITExtensionModal/SubmitSITExtensionModal.stories.jsx
  src/components/Office/SubmitSITExtensionModal/SubmitSITExtensionModal.test.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
  src/services/ghcApi.js
Labels: ttv, ready-to-merge

#7467 Update health check to only check https
  .circleci/config.yml
Labels: A-Team

#7474 MB-9602 TIO sees SIT Days Invoiced when reviewing SIT calculations
  src/components/Office/ReviewServiceItems/ServiceItemCard.jsx
  src/components/Office/ReviewServiceItems/ServiceItemCard.test.jsx
  src/components/Office/ServiceItemCalculations/helpers.test.js
  src/components/Office/ShipmentSITExtensions/ShipmentSITExtensions.test.jsx
  src/constants/serviceItems.js
Labels: ttv

#7477 MB-9625 Remove sandy and lynzt CAC access records
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20210930202639_remove_sandy_and_lynzt_cac_access.up.sql
Labels: A-Team, ready-to-merge

#7457 MB-9088 notify prime sit extension status
  pkg/handlers/ghcapi/mto_shipment.go
  pkg/services/event/event.go
  pkg/services/event/ghc_endpoint.go
Labels: roci
