Repository transcom/mymove, pull requests merged in 2021-04, with the labels that each got.

#6263 [MB-7055] Domestic destination pricing details
  src/components/Office/ServiceItemCalculations/ServiceItemCalculations.stories.jsx
  src/components/Office/ServiceItemCalculations/helpers.js
  src/components/Office/ServiceItemCalculations/helpers.test.js
  src/components/Office/ServiceItemCalculations/serviceItemTestParams.js
  src/constants/serviceItems.js
Labels: ttv

#6289 Rename PricingParam to PricingDisplayParam
  pkg/services/ghc_rate_engine.go
  pkg/services/ghcrateengine/counseling_services_pricer.go
  pkg/services/ghcrateengine/domestic_destination_additional_days_sit_pricer.go
  pkg/services/ghcrateengine/domestic_destination_first_day_sit_pricer.go
  pkg/services/ghcrateengine/domestic_destination_pricer.go
  pkg/services/ghcrateengine/domestic_destination_sit_delivery_pricer.go
  pkg/services/ghcrateengine/domestic_linehaul_pricer.go
  pkg/services/ghcrateengine/domestic_origin_additional_days_sit_pricer.go
  pkg/services/ghcrateengine/domestic_origin_first_day_sit_pricer.go
  pkg/services/ghcrateengine/domestic_origin_pricer.go
  pkg/services/ghcrateengine/domestic_origin_sit_pickup_pricer.go
  pkg/services/ghcrateengine/domestic_pack_pricer.go
  pkg/services/ghcrateengine/domestic_shorthaul_pricer.go
  pkg/services/ghcrateengine/domestic_unpack_pricer.go
  pkg/services/ghcrateengine/fuel_surcharge_pricer.go
  pkg/services/ghcrateengine/management_services_pricer.go
  pkg/services/ghcrateengine/pricer_helpers.go
  pkg/services/ghcrateengine/pricer_helpers_test.go
  pkg/services/mocks/CounselingServicesPricer.go
  pkg/services/mocks/DomesticDestinationAdditionalDaysSITPricer.go
  pkg/services/mocks/DomesticDestinationFirstDaySITPricer.go
  pkg/services/mocks/DomesticDestinationPricer.go
  pkg/services/mocks/DomesticDestinationSITDeliveryPricer.go
  pkg/services/mocks/DomesticLinehaulPricer.go
  pkg/services/mocks/DomesticOriginAdditionalDaysSITPricer.go
  pkg/services/mocks/DomesticOriginFirstDaySITPricer.go
  pkg/services/mocks/DomesticOriginPricer.go
  pkg/services/mocks/DomesticOriginSITPickupPricer.go
  pkg/services/mocks/DomesticPackPricer.go
  pkg/services/mocks/DomesticShorthaulPricer.go
  pkg/services/mocks/DomesticUnpackPricer.go
  pkg/services/mocks/FuelSurchargePricer.go
  pkg/services/mocks/ManagementServicesPricer.go
Labels: roci

#6244 WIP MB-5321 refactor duty station page to use formik
  src/components/Customer/CurrentDutyStationForm/CurrentDutyStationForm.jsx
  src/components/Customer/CurrentDutyStationForm/CurrentDutyStationForm.stories.jsx
  src/components/Customer/CurrentDutyStationForm/CurrentDutyStationForm.test.jsx
  src/pages/MyMove/Profile/DutyStation.css
  src/pages/MyMove/Profile/DutyStation.jsx
  src/pages/MyMove/Profile/DutyStation.test.jsx
  src/scenes/MyMove/getWorkflowRoutes.jsx
  src/scenes/ServiceMembers/DutyStation.jsx
  src/scenes/ServiceMembers/DutyStationSearchBox.jsx
Labels: Pamplemoose

#6266 Replace div with button and adjust styling
  src/components/Customer/Home/ShipmentList/ShipmentList.module.scss
  src/components/Customer/Home/ShipmentList/index.jsx
Labels: Pamplemoose

#6270 MB-7410-add-prime-command
  cmd/prime-api-client/main.go
  cmd/prime-api-client/support/create_webhook_notification.go
  pkg/handlers/supportapi/webhook_notification.go
Labels: roci

#6251 MB-7063 Add domestic unpacking
  src/components/Office/ServiceItemCalculations/ServiceItemCalculations.stories.jsx
  src/components/Office/ServiceItemCalculations/helpers.js
  src/components/Office/ServiceItemCalculations/helpers.test.js
  src/components/Office/ServiceItemCalculations/serviceItemTestParams.js
  src/constants/serviceItems.js
Labels: ttv

#6288 MB-7400 Add newly required fields to createMoveTaskOrder in Support API
  pkg/gen/supportapi/embedded_spec.go
  pkg/gen/supportmessages/dept_indicator.go
  pkg/gen/supportmessages/move_task_order.go
  pkg/gen/supportmessages/order.go
  pkg/gen/supportmessages/orders_type_detail.go
  pkg/gen/supportmessages/selected_move_type.go
  pkg/handlers/supportapi/internal/payloads/model_to_payload.go
  pkg/handlers/supportapi/move_task_order_test.go
  pkg/services/support/move_task_order/move_task_order_creator.go
  swagger/support.yaml
Labels: roci

#6299 Updated pricerDisplayParam to string
  pkg/services/ghc_rate_engine.go
  pkg/services/ghcrateengine/pricer_helpers.go
  pkg/services/ghcrateengine/pricer_helpers_test.go
Labels: roci

#6290 MB-7061 Add DDDSIT Calculations
  pkg/testdatagen/scenario/devseed.go
  src/components/Office/ServiceItemCalculations/ServiceItemCalculations.stories.jsx
  src/components/Office/ServiceItemCalculations/ServiceItemCalculations.test.jsx
  src/components/Office/ServiceItemCalculations/helpers.js
  src/components/Office/ServiceItemCalculations/helpers.test.js
  src/components/Office/ServiceItemCalculations/serviceItemTestParams.js
  src/constants/serviceItems.js
Labels: ttv

#6294 [MB-7055] Split origin and destination price function back into two
  src/components/Office/ServiceItemCalculations/helpers.js
Labels: ttv

#6307 MB-7444 Bump storybook dependencies
  package.json
  yarn.lock
Labels: A-Team, dependencies

#6283 [MB-7406] Adds metrics for EDI processing
  cmd/fetch-from-syncada-via-sftp/main.go
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20210331135106_rename_edi_processing_table.up.sql
  pkg/models/edi_errors.go
  pkg/models/edi_errors_test.go
  pkg/models/edi_processing.go
  pkg/models/edi_processing_test.go
  pkg/models/edi_type.go
  pkg/models/validators.go
  pkg/services/invoice.go
  pkg/services/invoice/process_edi997.go
  pkg/services/invoice/syncada_sftp_reader.go
  pkg/services/invoice/syncada_sftp_reader_test.go
  pkg/services/mocks/EDI997Processor.go
  pkg/services/mocks/SyncadaFileProcessor.go
  pkg/services/payment_request/payment_request_reviewed_processor.go
  pkg/services/payment_request/payment_request_reviewed_processor_test.go
Labels: A-Team

#6277 [MB-7060] Domestic origin SIT pickup payment service item calculations
  pkg/testdatagen/scenario/devseed.go
  src/components/Office/ExpandableServiceItemRow/ExpandableServiceItemRow.jsx
  src/components/Office/ServiceItemCalculations/ServiceItemCalculations.module.scss
  src/components/Office/ServiceItemCalculations/ServiceItemCalculations.stories.jsx
  src/components/Office/ServiceItemCalculations/helpers.js
  src/components/Office/ServiceItemCalculations/helpers.test.js
  src/components/Office/ServiceItemCalculations/serviceItemTestParams.js
  src/constants/serviceItems.js
Labels: ttv

#6269 MB-4935 refactor selected move type component logic
  src/pages/MyMove/SelectShipmentType.jsx
  src/pages/MyMove/SelectShipmentType.module.scss
  src/pages/MyMove/SelectShipmentType.test.jsx
  src/scenes/MyMove/getWorkflowRoutes.jsx
  src/utils/shipmentInfo.js
  src/utils/shipmentInfo.test.js
Labels: Pamplemoose

#6279 [MB-6944] process an EDI824 file
  pkg/edi/edi824/edi.go
  pkg/edi/segment/gs.go
  pkg/edi/segment/gs_test.go
  pkg/services/invoice/process_edi824.go
  pkg/services/invoice/process_edi824_test.go
  pkg/services/invoice/process_edi997.go
  pkg/services/invoice/process_edi997_test.go
  pkg/services/mocks/EDI824Processor.go
  pkg/services/mocks/EDI997Processor.go
Labels: A-Team

#6297 MB-7211 update create mto service item error handling
  pkg/services/mto_service_item/mto_service_item_creator.go
  pkg/services/mto_service_item/mto_service_item_creator_test.go
  pkg/testdatagen/scenario/devseed.go
Labels: roci

#6291 MB-7049 refactor remove wizard page from the review page
  src/pages/MyMove/Review/Review.module.scss
  src/pages/MyMove/Review/Review.test.jsx
  src/pages/MyMove/Review/index.jsx
  src/scenes/MyMove/getWorkflowRoutes.jsx
Labels: Pamplemoose

#6295 [MB-7059] Domestic destination additional day SIT service item param calculations
  src/components/Office/ServiceItemCalculations/ServiceItemCalculations.stories.jsx
  src/components/Office/ServiceItemCalculations/helpers.js
  src/components/Office/ServiceItemCalculations/helpers.test.js
  src/components/Office/ServiceItemCalculations/serviceItemTestParams.js
  src/constants/serviceItems.js
Labels: ttv

#6282 [MB-7057] TIO sees pricing details domestic dest 1st day sit
  src/constants/serviceItems.js
Labels: ttv

#6265 MB-4739 TOO tag requested shipments move details page
  src/pages/Office/MoveDetails/MoveDetails.jsx
  src/pages/Office/MoveDetails/MoveDetails.test.jsx
  src/pages/Office/TXOMoveInfo/TXOTab.module.scss
Labels: ttv

#6261 [MB-7220] Read EDI responses in ProcessReviewedPaymentRequests endpoint
  pkg/cli/syncada_sftp.go
  pkg/edi/segment/gs.go
  pkg/edi/segment/gs_test.go
  pkg/edi/segment/isa.go
  pkg/edi/segment/isa_test.go
  pkg/gen/supportapi/embedded_spec.go
  pkg/gen/supportmessages/process_reviewed_payment_requests.go
  pkg/handlers/supportapi/payment_request.go
  pkg/handlers/supportapi/payment_request_test.go
  pkg/services/invoice/syncada_sftp_reader.go
  pkg/services/invoice/syncada_sftp_reader_test.go
  scripts/prime-api-demo
  swagger/support.yaml
Labels: A-Team

#6315 MB-6943 controlling the send to syncada
  cmd/milmove-tasks/process_edis.go
  pkg/cli/gex.go
  pkg/payment_request/send_to_syncada.go
Labels: A-Team

#6308 MB-7444 Bump testing-library dependencies
  package.json
  yarn.lock
Labels: A-Team, dependencies

#6323 [MB-7558] Add success logging for EDIs processing
  pkg/edi/edi824/edi.go
  pkg/edi/edi824/parser.go
  pkg/payment_request/send_to_syncada.go
  pkg/services/invoice/process_edi824.go
  pkg/services/invoice/process_edi997.go
  pkg/services/payment_request/payment_request_reviewed_processor.go
Labels: A-Team

#6316 [MB-7404] As the job runner, I need to call the EDI response processor service
  cmd/fetch-from-syncada-via-sftp/main.go
  cmd/milmove-tasks/process_edis.go
Labels: A-Team

#6264 [MB-5366] Annotate unchecked errors part 2
  cmd/milmove/main_test.go
  pkg/handlers/supportapi/payment_request_test.go
  pkg/services/invoice/ghc_payment_request_invoice_generator_test.go
  pkg/services/payment_request/payment_request_reviewed_processor_test.go
Labels: Pamplemoose

#6325 [MB-7558] quick clean-up to log message
  pkg/services/invoice/process_edi824.go
Labels: A-Team

#6322 MB-7112 Add service counseling Move statuses
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20210405214216_update_move_status_comment_with_miro_link.up.sql
  migrations/app/schema/20210405224456_add_service_counseling_completed_at_to_moves.up.sql
  pkg/models/move.go
  src/shared/constants.js
Labels: ttv

#6324 MB-6836 Update MS pricer to return display param
  pkg/services/ghcrateengine/management_services_pricer.go
  pkg/services/ghcrateengine/management_services_pricer_test.go
  pkg/services/ghcrateengine/pricer_formatters.go
  pkg/services/ghcrateengine/pricer_formatters_test.go
  pkg/services/ghcrateengine/service_item_pricer_test.go
Labels: roci

#6341 [MB-6831] Added pricer display params to domestic linehaul
  pkg/services/ghcrateengine/domestic_destination_sit_delivery_pricer_test.go
  pkg/services/ghcrateengine/domestic_linehaul_pricer.go
  pkg/services/ghcrateengine/domestic_linehaul_pricer_test.go
  pkg/services/ghcrateengine/domestic_origin_sit_pickup_pricer_test.go
  pkg/services/ghcrateengine/ghc_rate_engine_service_test.go
  pkg/services/ghcrateengine/management_services_pricer_test.go
  pkg/services/ghcrateengine/pricer_formatters.go
  pkg/services/ghcrateengine/pricer_formatters_test.go
  pkg/services/ghcrateengine/pricer_helpers_test.go
  pkg/unit/millicents.go
  pkg/unit/millicents_test.go
Labels: A-Team

#6345 MB-6825 update pricer for domestic unpacking (DUPK)
  pkg/services/ghcrateengine/domestic_unpack_pricer.go
  pkg/services/ghcrateengine/domestic_unpack_pricer_test.go
  pkg/services/ghcrateengine/ghc_rate_engine_service_test.go
Labels: roci

#6361 [MB-6828] Adding Pricer Params to Domestic Destination Pricer
  pkg/services/ghcrateengine/domestic_destination_pricer.go
  pkg/services/ghcrateengine/domestic_destination_pricer_test.go
  pkg/services/ghcrateengine/ghc_rate_engine_service_test.go
Labels: roci

#6360 MB-6829 Domestic Origin Pricer Params
  pkg/services/ghcrateengine/domestic_origin_pricer.go
  pkg/services/ghcrateengine/domestic_origin_pricer_test.go
Labels: roci

#6354 [MB-7422] Send all moves to service counseling
  .envrc
  config/env/exp.app.env
  config/env/prd.app.env
  config/env/stg.app.env
  pkg/cli/featureflag.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/move_status.go
  pkg/handlers/ghcapi/move_task_order_test.go
  pkg/handlers/ghcapi/order_test.go
  pkg/handlers/internalapi/api.go
  pkg/handlers/internalapi/moves.go
  pkg/handlers/internalapi/moves_test.go
  pkg/handlers/internalapi/office_test.go
  pkg/handlers/internalapi/personally_procured_move_test.go
  pkg/handlers/internalapi/service_members_test.go
  pkg/models/move.go
  pkg/models/move_test.go
  pkg/models/order_test.go
  pkg/models/shipment_summary_worksheet_test.go
  pkg/services/mocks/MoveStatusRouter.go
  pkg/services/move.go
  pkg/services/move/move_status_router.go
  pkg/services/paperwork/form_creator_test.go
  pkg/testdatagen/scenario/devseed.go
  pkg/testdatagen/scenario/e2ebasic.go
  swagger/internal.yaml
Labels: ttv

#6370 [MB-6902] save pricer params in paymentrequestcreator
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/service_item_param_name.go
  pkg/gen/primemessages/service_item_param_origin.go
  pkg/services/ghc_rate_engine.go
  pkg/services/ghcrateengine/pricer_helpers.go
  pkg/services/ghcrateengine/pricer_helpers_test.go
  pkg/services/ghcrateengine/service_item_pricer.go
  pkg/services/ghcrateengine/service_item_pricer_test.go
  pkg/services/mocks/ServiceItemPricer.go
  pkg/services/payment_request/payment_request_creator.go
  pkg/services/payment_request/payment_request_creator_test.go
  swagger/prime.yaml
Labels: A-Team

#6371 [MB-7383] Services Counselor can edit move contact info (storybook)
  src/components/Office/CustomerContactInfoForm/CustomerContactInfoForm.jsx
  src/components/Office/CustomerContactInfoForm/CustomerContactInfoForm.module.scss
  src/components/Office/CustomerContactInfoForm/CustomerContactInfoForm.stories.jsx
  src/components/Office/CustomerContactInfoForm/CustomerContactInfoForm.test.jsx
  src/components/form/CustomerAltContactInfoFields/CustomerAltContactInfoFields.stories.jsx
  src/components/form/CustomerAltContactInfoFields/CustomerAltContactInfoFields.test.jsx
  src/components/form/CustomerAltContactInfoFields/index.jsx
  src/components/form/CustomerContactInfoFields/index.jsx
Labels: ttv

#6344 [MB-7407] Record EDI 858 generation errors in database
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20210409170358_make_icn_column_nullable.up.sql
  pkg/models/edi_errors.go
  pkg/models/edi_errors_test.go
  pkg/services/invoice/process_edi824.go
  pkg/services/invoice/process_edi997.go
  pkg/services/payment_request/payment_request_reviewed_processor.go
  pkg/services/payment_request/payment_request_reviewed_processor_test.go
Labels: A-Team

#6372 MB-7423 Skeleton services counseling move details page
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/move_task_order/update_m_t_o_status_service_counseling_completed.go
  pkg/gen/ghcapi/ghcoperations/move_task_order/update_m_t_o_status_service_counseling_completed_parameters.go
  pkg/gen/ghcapi/ghcoperations/move_task_order/update_m_t_o_status_service_counseling_completed_responses.go
  pkg/gen/ghcapi/ghcoperations/move_task_order/update_m_t_o_status_service_counseling_completed_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/ghcmessages/move.go
  pkg/gen/ghcmessages/move_task_order.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/move_task_order.go
  pkg/handlers/ghcapi/move_task_order_test.go
  pkg/services/event/ghc_endpoint.go
  pkg/services/mocks/MoveTaskOrderUpdater.go
  pkg/services/move_task_order.go
  pkg/services/move_task_order/move_task_order_updater.go
  pkg/services/move_task_order/move_task_order_updater_test.go
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.module.scss
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.test.jsx
  src/pages/Office/ServicesCounselingMoveInfo/ServicesCounselingMoveInfo.jsx
  src/pages/Office/ServicesCounselingMoveInfo/ServicesCounselingMoveInfo.test.jsx
  src/pages/Office/ServicesCounselingMoveInfo/ServicesCounselingTab.module.scss
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.jsx
  src/pages/Office/index.jsx
  src/pages/Office/index.test.jsx
  src/services/ghcApi.js
  swagger/ghc.yaml
Labels: ttv

#6280 [MB-7489] Custom eslint plugin for CATO
  .eslintrc
  .eslintrc.js
  dangerfile.ts
  eslint-plugin-ato/index.js
  eslint-plugin-ato/no-explicit-eslint-disable.js
  eslint-plugin-ato/no-unapproved-annotation.js
  eslint-plugin-ato/package.json
  eslint-plugin-ato/tests/no-explicit-eslint-disable.test.js
  eslint-plugin-ato/tests/no-unapproved-annotation.test.js
  package.json
  src/pages/Admin/Users/UserShow.jsx
  yarn.lock
Labels: Pamplemoose

#6355 [MB-7520] Services counseling move queue skeleton
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/move_task_order/update_m_t_o_status_service_counseling_completed.go
  pkg/gen/ghcapi/ghcoperations/move_task_order/update_m_t_o_status_service_counseling_completed_parameters.go
  pkg/gen/ghcapi/ghcoperations/move_task_order/update_m_t_o_status_service_counseling_completed_responses.go
  pkg/gen/ghcapi/ghcoperations/move_task_order/update_m_t_o_status_service_counseling_completed_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/ghcapi/ghcoperations/queues/get_services_counseling_queue.go
  pkg/gen/ghcapi/ghcoperations/queues/get_services_counseling_queue_parameters.go
  pkg/gen/ghcapi/ghcoperations/queues/get_services_counseling_queue_responses.go
  pkg/gen/ghcapi/ghcoperations/queues/get_services_counseling_queue_urlbuilder.go
  pkg/gen/ghcmessages/move.go
  pkg/gen/ghcmessages/move_status.go
  pkg/gen/ghcmessages/move_task_order.go
  pkg/gen/ghcmessages/queue_move.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/move_task_order.go
  pkg/handlers/ghcapi/move_task_order_test.go
  pkg/handlers/ghcapi/queues.go
  pkg/handlers/ghcapi/queues_test.go
  pkg/services/event/ghc_endpoint.go
  pkg/services/mocks/MoveTaskOrderUpdater.go
  pkg/services/move_task_order.go
  pkg/services/move_task_order/move_task_order_updater.go
  pkg/services/move_task_order/move_task_order_updater_test.go
  pkg/services/order/order_fetcher.go
  pkg/testdatagen/make_office_user.go
  pkg/testdatagen/make_order.go
  pkg/testdatagen/scenario/devseed.go
  src/components/LeftNav/index.module.scss
  src/components/Office/ShipmentContainer.module.scss
  src/constants/moves.js
  src/constants/queryKeys.js
  src/constants/queues.js
  src/hooks/queries.js
  src/pages/Office/MoveDetails/MoveDetails.jsx
  src/pages/Office/MoveQueue/MoveQueue.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.module.scss
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.test.jsx
  src/pages/Office/ServicesCounselingMoveInfo/ServicesCounselingMoveInfo.jsx
  src/pages/Office/ServicesCounselingMoveInfo/ServicesCounselingMoveInfo.test.jsx
  src/pages/Office/ServicesCounselingMoveInfo/ServicesCounselingTab.module.scss
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.jsx
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.module.scss
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.test.jsx
  src/pages/Office/index.jsx
  src/pages/Office/index.test.jsx
  src/services/ghcApi.js
  src/shared/formatters.js
  swagger/ghc.yaml
Labels: ttv

#6359 [MB-7607] Add deleteFromSyncada param to support-reviewed-payment-requests
  pkg/gen/supportapi/embedded_spec.go
  pkg/gen/supportmessages/process_reviewed_payment_requests.go
  pkg/handlers/supportapi/payment_request.go
  pkg/handlers/supportapi/payment_request_test.go
  scripts/prime-api-demo
  swagger/support.yaml
Labels: A-Team

#6342 MB-7465 Create a ContactInfoDisplay component to be used on the new Profile page
  src/components/Customer/Profile/ContactInfoDisplay/ContactInfoDisplay.jsx
  src/components/Customer/Profile/ContactInfoDisplay/ContactInfoDisplay.module.scss
  src/components/Customer/Profile/ContactInfoDisplay/ContactInfoDisplay.stories.jsx
  src/components/Customer/Profile/ContactInfoDisplay/ContactInfoDisplay.test.jsx
  src/styles/descriptionList.module.scss
  src/testUtils.jsx
Labels: Pamplemoose

#6356 Kim mb 7561 fix errcheck violations
  .golangci.yml
  cmd/milmove-tasks/connect_to_gex_via_sftp.go
  cmd/webhook-client/webhook/webhook.go
  pkg/cli/vault_test.go
  pkg/logging/log.go
  pkg/models/move.go
  pkg/models/move_test.go
  pkg/models/order_test.go
  pkg/models/payment_request_to_interchange_control_number_test.go
  pkg/services/invoice/process_edi824_test.go
  pkg/services/invoice/process_edi997_test.go
  pkg/services/move_task_order/move_task_order_updater.go
  pkg/services/mto_service_item/mto_service_item_creator.go
Labels: Pamplemoose

#6339 Kim mb 5882 profile icon link
  src/constants/routes.js
  src/containers/LoginButton/LoginButton.jsx
  src/containers/LoginButton/LoginButton.module.scss
  src/containers/LoginButton/LoginButton.test.jsx
  src/icons.js
  src/shared/Header/MyMove/index.jsx
  src/shared/Header/MyMove/index.scss
  src/stories/icons.stories.jsx
Labels: Pamplemoose

#6343 MB-6837-update-counseling-service-pricer-display-param
  pkg/services/ghcrateengine/counseling_services_pricer.go
  pkg/services/ghcrateengine/counseling_services_pricer_test.go
Labels: roci

#6357 [MB-6830] update to shorthaul pricer to return rate engine params
  pkg/models/shipment_summary_worksheet.go
  pkg/services/ghcrateengine/domestic_destination_pricer.go
  pkg/services/ghcrateengine/domestic_linehaul_pricer.go
  pkg/services/ghcrateengine/domestic_origin_pricer.go
  pkg/services/ghcrateengine/domestic_pack_pricer.go
  pkg/services/ghcrateengine/domestic_shorthaul_pricer.go
  pkg/services/ghcrateengine/domestic_shorthaul_pricer_test.go
  pkg/services/ghcrateengine/domestic_unpack_pricer.go
  pkg/services/ghcrateengine/ghc_rate_engine_service_test.go
  pkg/services/ghcrateengine/pricer_formatters.go
  pkg/services/ghcrateengine/pricer_formatters_test.go
  pkg/services/ghcrateengine/service_item_pricer.go
  pkg/unit/cents.go
Labels: A-Team

#6396 MB-7669 Allow SC Completed Moves to be approved
  cypress/integration/mymove/ppm.js
  pkg/handlers/ghcapi/move_task_order_test.go
  pkg/handlers/internalapi/moves_test.go
  pkg/handlers/supportapi/move_task_order_test.go
  pkg/services/move_task_order/move_task_order_updater.go
  pkg/services/move_task_order/move_task_order_updater_test.go
Labels: bug, ttv

#6402 [MB-6834] Add pricer params for SIT First Day pricers
  pkg/services/ghcrateengine/counseling_services_pricer_test.go
  pkg/services/ghcrateengine/domestic_destination_additional_days_sit_pricer_test.go
  pkg/services/ghcrateengine/domestic_destination_first_day_sit_pricer_test.go
  pkg/services/ghcrateengine/domestic_destination_pricer_test.go
  pkg/services/ghcrateengine/domestic_destination_sit_delivery_pricer_test.go
  pkg/services/ghcrateengine/domestic_linehaul_pricer_test.go
  pkg/services/ghcrateengine/domestic_origin_additional_days_sit_pricer_test.go
  pkg/services/ghcrateengine/domestic_origin_first_day_sit_pricer_test.go
  pkg/services/ghcrateengine/domestic_origin_pricer_test.go
  pkg/services/ghcrateengine/domestic_origin_sit_pickup_pricer_test.go
  pkg/services/ghcrateengine/domestic_pack_pricer_test.go
  pkg/services/ghcrateengine/domestic_unpack_pricer_test.go
  pkg/services/ghcrateengine/ghc_rate_engine_service_test.go
  pkg/services/ghcrateengine/management_services_pricer_test.go
  pkg/services/ghcrateengine/pricer_helpers.go
  pkg/services/ghcrateengine/pricer_helpers_test.go
  pkg/services/ghcrateengine/pricer_query_helpers_test.go
Labels: A-Team

#6417 [MB-6826] Add pricing params for Dest and Origin SIT Addl' days
  pkg/services/ghcrateengine/domestic_destination_additional_days_sit_pricer_test.go
  pkg/services/ghcrateengine/domestic_origin_additional_days_sit_pricer_test.go
  pkg/services/ghcrateengine/pricer_helpers.go
  pkg/services/ghcrateengine/pricer_helpers_test.go
Labels: A-Team

#6381 MB-7635 Initial refactoring of MoveRouter
  pkg/handlers/internalapi/api.go
  pkg/handlers/internalapi/moves.go
  pkg/handlers/internalapi/moves_test.go
  pkg/services/mocks/MoveRouter.go
  pkg/services/move.go
  pkg/services/move/move_router.go
  pkg/services/move/move_router_test.go
  pkg/services/move/move_status_router.go
Labels: ttv

#6424 MB-7585 Use PaymentRequestNumber instead of ReferenceID for looking up 824
  pkg/services/invoice/process_edi824.go
  pkg/services/invoice/process_edi824_test.go
Labels: A-Team

#6433 MB-4137 Allow counseling queue to sort by Requested Move Date
  pkg/services/order/order_fetcher.go
  pkg/services/order/order_fetcher_test.go
  pkg/testdatagen/make_move.go
  pkg/testdatagen/make_mto_shipment.go
Labels: roci

#6423 [MB -7717] Mitigate remaining staticcheck errors
  .golangci.yml
  pkg/migrate/ReadInSQL_test.go
  pkg/migrate/SplitStatements_test.go
  pkg/server/server_test.go
  pkg/services/invoice/process_edi824.go
  pkg/services/invoice/process_edi997.go
  pkg/services/user/user_updater.go
Labels: Pamplemoose

#6405 [MB-7411] Display service item calculations when reviewing a payment request
  src/components/Office/ExpandableServiceItemRow/ExpandableServiceItemRow.jsx
  src/components/Office/PaymentRequestCard/PaymentRequestCard.jsx
  src/components/Office/PaymentRequestDetails/PaymentRequestDetails.jsx
  src/components/Office/PaymentRequestDetails/PaymentRequestDetails.test.jsx
  src/components/Office/ReviewServiceItems/ReviewServiceItems.jsx
  src/components/Office/ReviewServiceItems/ReviewServiceItems.stories.jsx
  src/components/Office/ReviewServiceItems/ReviewServiceItems.test.jsx
  src/components/Office/ReviewServiceItems/ServiceItemCard.jsx
  src/components/Office/ReviewServiceItems/ServiceItemCard.module.scss
  src/components/Office/ReviewServiceItems/ServiceItemCard.stories.jsx
  src/components/Office/ReviewServiceItems/ServiceItemCard.test.jsx
  src/pages/Office/PaymentRequestReview/PaymentRequestReview.jsx
Labels: ttv

#6435 [MB-6835] Add pricer params for added unit test and updates for displaying pricing param
  pkg/services/ghcrateengine/domestic_destination_sit_delivery_pricer_test.go
  pkg/services/ghcrateengine/domestic_origin_sit_pickup_pricer_test.go
  pkg/services/ghcrateengine/pricer_helpers.go
  pkg/services/ghcrateengine/pricer_helpers_test.go
Labels: A-Team

#6419 MB-7648 filter list by requested move date
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20210414214012_add_index_to_requested_pickup_date_on_mto_shipments_table.up.sql
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/queue_move.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/queues.go
  pkg/services/order.go
  pkg/services/order/order_fetcher.go
  pkg/services/order/order_fetcher_test.go
  pkg/testdatagen/make_move.go
  swagger/ghc.yaml
Labels: roci

#6421 MB-413-admin-can-add-sc-role-to-officeuser
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20210407223734_add_service_counselor_role.up.sql
  pkg/handlers/ghcapi/queues_test.go
  pkg/models/roles/roles.go
Labels: roci

#6438 MB-7641 Add submitted at filter
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20210415231923_add_index_on_submitted_at_in_moves_table.up.sql
  pkg/handlers/ghcapi/queues.go
  pkg/services/order.go
  pkg/services/order/order_fetcher.go
  pkg/services/order/order_fetcher_test.go
  pkg/testdatagen/make_move.go
Labels: roci

#6437 MB-7633 Update fetchMTOUpdates to return origin duty station
  pkg/services/move_task_order/move_task_order_fetcher.go
  pkg/services/move_task_order/move_task_order_fetcher_test.go
Labels: roci

#6420 MB-7361 Services counseling move allowances details
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20210412213134_add_entitlments_columns.up.sql
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/entitlements.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/orders_test.go
  pkg/models/ghc_entitlements.go
  pkg/testdatagen/make_entitlement.go
  src/components/Office/AllowancesTable/AllowancesTable.jsx
  src/components/Office/AllowancesTable/AllowancesTable.stories.jsx
  src/components/Office/AllowancesTable/AllowancesTable.test.jsx
  src/pages/Office/MoveDetails/MoveDetails.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.module.scss
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.test.jsx
  src/pages/Office/ServicesCounselingMoveInfo/ServicesCounselingTab.module.scss
  src/pages/Office/TXOMoveInfo/TXOTab.module.scss
  swagger/ghc.yaml
Labels: ttv

#6434 [MB-7721] [Bug] fix to ProcessAndLockReviewedPR to use the tx inside the transaction …
  cmd/generate-payment-request-edi/main.go
  pkg/handlers/supportapi/api.go
  pkg/handlers/supportapi/payment_request.go
  pkg/handlers/supportapi/payment_request_test.go
  pkg/services/invoice.go
  pkg/services/invoice/ghc_payment_request_invoice_generator.go
  pkg/services/invoice/ghc_payment_request_invoice_generator_test.go
  pkg/services/mocks/GHCPaymentRequestInvoiceGenerator.go
  pkg/services/payment_request/payment_request_creator.go
  pkg/services/payment_request/payment_request_reviewed_processor.go
  pkg/services/payment_request/payment_request_reviewed_processor_test.go
Labels: A-Team

#6416 [MB-3170] Services counselor can view move contact info, update headings in move details and MTO pages
  cypress/integration/office/txo/tooFlows.js
  src/components/Office/AllowancesTable/AllowancesTable.jsx
  src/components/Office/CustomerInfo.jsx
  src/components/Office/CustomerInfoTable.jsx
  src/components/Office/CustomerInfoTable.test.jsx
  src/components/Office/DetailsTable/DetailsTable.jsx
  src/components/Office/DetailsTable/DetailsTable.module.scss
  src/components/Office/OrdersTable/OrdersTable.jsx
  src/components/Office/RequestedServiceItemsTable/RequestedServiceItemsTable.jsx
  src/components/Office/RequestedShipments/RequestedShipments.jsx
  src/components/Office/ShipmentHeading.jsx
  src/components/Office/ShipmentHeading.test.jsx
  src/pages/Office/MoveDetails/MoveDetails.test.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.test.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.test.jsx
  src/pages/Office/ServicesCounselingMoveInfo/ServicesCounselingMoveInfo.test.jsx
Labels: ttv

#6404 MB-7562 update links on home and review for profile
  src/components/Customer/Review/ProfileTable/index.jsx
  src/components/Customer/Review/ServiceInfoDisplay/ServiceInfoDisplay.stories.jsx
  src/pages/MyMove/Home/index.jsx
Labels: Pamplemoose

#6418 [MB-7376] Add Price Difference in Cents and Fuel Surcharge Multiplier Service Item Param Keys for FSC surcharge price
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20210414170143_add_FSC_service_item_param_keys.up.sql
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/service_item_param_name.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/service_item_param_name.go
  pkg/models/service_item_param_key.go
  swagger/ghc.yaml
  swagger/prime.yaml
Labels: A-Team

#6373 [MB-7526] Custom go linter for ATO
  cmd/ato-linter/main.go
  go.mod
  go.sum
  pkg/ato-linter/ato.go
  pkg/ato-linter/ato_test.go
  testdata/src/linter_tests/ato.go
Labels: Pamplemoose

#6427 [MB-7623] Switch the connection for the Job Runner to use HTTPS to GEX
  cmd/milmove-tasks/post_file_to_gex.go
  cmd/milmove-tasks/process_edis.go
  cmd/milmove/serve.go
  cmd/send-to-gex/main.go
  config/env/exp.process-edis.env
  config/env/prd.process-edis.env
  config/env/stg.process-edis.env
  pkg/cli/gex.go
  pkg/handlers/supportapi/payment_request.go
  pkg/payment_request/send_to_syncada.go
  pkg/services/invoice.go
  pkg/services/invoice/gex_sender_http.go
  pkg/services/invoice/gex_sender_http_test.go
  pkg/services/mocks/GexSender.go
  pkg/services/payment_request/payment_request_reviewed_processor.go
  pkg/services/payment_request/payment_request_reviewed_processor_test.go
Labels: A-Team

#6441 [MB-7624] update SFTP reader to user GEX env vars
  cmd/fetch-from-syncada-via-sftp/main.go
  cmd/milmove-tasks/process_edis.go
  pkg/cli/gex_sftp.go
  pkg/cli/gex_sftp_test.go
  pkg/handlers/supportapi/payment_request.go
  pkg/services/invoice.go
  pkg/services/invoice/ghc_payment_request_invoice_generator_test.go
  pkg/services/invoice/syncada_sftp_reader.go
  pkg/services/mocks/SyncadaSFTPReader.go
Labels: A-Team

#6448 Revert "Revert "[MB-7623] Switch the connection for the Job Runner to use HTTPS to GEX""
  cmd/milmove-tasks/post_file_to_gex.go
  cmd/milmove-tasks/process_edis.go
  cmd/milmove/serve.go
  cmd/send-to-gex/main.go
  config/env/exp.process-edis.env
  config/env/prd.process-edis.env
  config/env/stg.process-edis.env
  pkg/cli/gex.go
  pkg/handlers/supportapi/payment_request.go
  pkg/payment_request/send_to_syncada.go
  pkg/services/invoice.go
  pkg/services/invoice/gex_sender_http.go
  pkg/services/invoice/gex_sender_http_test.go
  pkg/services/mocks/GexSender.go
  pkg/services/payment_request/payment_request_reviewed_processor.go
  pkg/services/payment_request/payment_request_reviewed_processor_test.go
Labels: A-Team

#6450 MB-7571-add-services-counselor-checkbox-for-OfficeUser
  src/scenes/SystemAdmin/shared/RolesCheckboxes.jsx
Labels: roci

#6397 MB-6662 post move submission state for editing contact information
  src/components/Customer/Review/ServiceInfoDisplay/ServiceInfoDisplay.jsx
  src/components/Customer/Review/ServiceInfoDisplay/ServiceInfoDisplay.module.scss
  src/components/Customer/Review/ServiceInfoDisplay/ServiceInfoDisplay.stories.jsx
  src/components/Customer/Review/ServiceInfoDisplay/ServiceInfoDisplay.test.jsx
  src/pages/MyMove/Profile/Profile.jsx
  src/pages/MyMove/Profile/Profile.test.jsx
  src/scenes/Review/EditProfile.jsx
Labels: Pamplemoose

#6238 Adds annotation for G101 linter suppression
  pkg/cli/syncada_sftp.go
Labels: A-Team

#6463 [MB-7725] Colocate all #nosec instances to be with annotation
  pkg/auth/cookie.go
  pkg/cli/auth.go
  pkg/cli/dps.go
  pkg/cli/gex.go
  pkg/cli/syncada_sftp.go
  pkg/storage/storage.go
Labels: Pamplemoose

#6464 Add annotation for G101 linter suppression
  pkg/cli/gex_sftp.go
Labels: needs-is3-review

#6467 MB-7626 Clarify log messages for those less familiar with EDI formats
  cmd/milmove-tasks/process_edis.go
Labels: A-Team

#6407 MB-5883 Create page for Service Member to edit all contact info
  src/components/Customer/BackupContactForm/index.jsx
  src/components/Customer/ContactInfoForm/index.jsx
  src/components/Customer/EditContactInfoForm/EditContactInfoForm.jsx
  src/components/Customer/EditContactInfoForm/EditContactInfoForm.module.scss
  src/components/Customer/EditContactInfoForm/EditContactInfoForm.stories.jsx
  src/components/Customer/EditContactInfoForm/EditContactInfoForm.test.jsx
  src/components/form/BackupContactInfoFields/BackupContactInfoFields.stories.jsx
  src/components/form/BackupContactInfoFields/BackupContactInfoFields.test.jsx
  src/components/form/BackupContactInfoFields/index.jsx
  src/constants/routes.js
  src/pages/MyMove/Profile/EditContactInfo.jsx
  src/pages/MyMove/Profile/EditContactInfo.test.jsx
  src/pages/MyMove/Profile/Profile.jsx
  src/scenes/MyMove/index.jsx
  src/scenes/Review/EditBackupContact.jsx
  src/scenes/Review/EditContactInfo.jsx
  src/types/customerShapes.js
  src/utils/validation.js
Labels: Pamplemoose

#6460 [MB-7547] add EDI_ERROR to support API
  pkg/gen/supportapi/embedded_spec.go
  pkg/gen/supportapi/supportoperations/payment_request/update_payment_request_status.go
  pkg/gen/supportclient/payment_request/payment_request_client.go
  pkg/gen/supportmessages/payment_request_status.go
  pkg/handlers/supportapi/payment_request.go
  swagger/support.yaml
Labels: A-Team

#6474 MB-7625 Swap channels to correct variables
  pkg/cli/gex.go
Labels: A-Team

#6451 Add annotation regarding use of child-process
  dangerfile.ts
Labels: Pamplemoose, needs-is3-review

#6476 MB-7626 Skip processing response files if SEND_TO_SYNCADA is false
  cmd/milmove-tasks/process_edis.go
Labels: A-Team

#6479 MB-5883 Update Profile to pass secondaryTelephone to ContactInfoDisplay
  src/pages/MyMove/Profile/Profile.jsx
Labels: Pamplemoose

#6461 MB-3164 service counselor login
  pkg/auth/authentication/devlocal.go
  pkg/handlers/ghcapi/queues.go
  pkg/handlers/ghcapi/queues_test.go
  pkg/testdatagen/make_office_user.go
  pkg/testdatagen/scenario/devseed.go
  pkg/testdatagen/scenario/e2ebasic.go
  src/constants/userRoles.js
  src/pages/Office/index.jsx
  src/pages/Office/index.test.jsx
  src/pages/SelectApplication/SelectApplication.jsx
  src/pages/SelectApplication/SelectApplication.test.jsx
Labels: roci

#6462 [MB-7546] Update PRToInterchangeControlNumber to have an EDIType Field
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20210419195440_add_editype_to_paymentRequestToInterchange_table.up.sql
  pkg/models/edi_errors_test.go
  pkg/models/payment_request_to_interchange_control_number.go
  pkg/models/payment_request_to_interchange_control_number_test.go
  pkg/services/invoice/ghc_payment_request_invoice_generator.go
  pkg/services/invoice/process_edi824.go
  pkg/services/invoice/process_edi824_test.go
  pkg/services/invoice/process_edi997.go
  pkg/services/invoice/process_edi997_test.go
  pkg/testdatagen/make_payment_request_to_interchange_control_number.go
Labels: A-Team

#6465 [MB-6832] Add Fuel Surcharge pricer params
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20210420200150_change_fsc_param_to_decimal.up.sql
  pkg/services/ghc_rate_engine.go
  pkg/services/ghcrateengine/fuel_surcharge_pricer.go
  pkg/services/ghcrateengine/fuel_surcharge_pricer_test.go
  pkg/services/mocks/FuelSurchargePricer.go
Labels: A-Team

#6486 MB-7942 Update SM patch api to only update orders if move is in draft
  pkg/handlers/internalapi/service_members.go
  pkg/handlers/internalapi/service_members_test.go
Labels: Pamplemoose

#6469 [MB-7667] Add GBLOC to creation of new devlocal office users
  pkg/auth/authentication/devlocal.go
  pkg/auth/authentication/devlocal_test.go
  pkg/testdatagen/make_role.go
  pkg/testdatagen/shared.go
Labels: ttv

#6487 MB-7946 Fix Crash Editing Service Info Before Orders are Uploaded
  src/components/Customer/Review/ServiceInfoDisplay/ServiceInfoDisplay.jsx
  src/components/Customer/Review/ServiceInfoDisplay/ServiceInfoDisplay.stories.jsx
  src/components/Customer/Review/ServiceInfoDisplay/ServiceInfoDisplay.test.jsx
  src/pages/MyMove/Profile/EditServiceInfo.jsx
  src/pages/MyMove/Profile/Profile.jsx
  src/pages/MyMove/Profile/Profile.test.jsx
  src/store/entities/selectors.js
Labels: Pamplemoose

#6472 [MB-7529] Add ApprovedAt field to service item updater
  pkg/services/mto_shipment/mto_shipment_updater.go
  pkg/services/mto_shipment/mto_shipment_updater_test.go
Labels: ttv

#6478 [MB-7937] update health check request message log
  cmd/milmove/serve.go
Labels: A-Team

#6470 [MB-7724] Fix remaining FE lint errors
  eslint-plugin-ato/no-unapproved-annotation.js
  src/components/DataPoint/index.jsx
  src/components/Office/OrdersDetailForm/OrdersDetailForm.test.jsx
  src/pages/SelectApplication/SelectApplication.jsx
  src/pages/SelectApplication/SelectApplication.test.jsx
  src/registerServiceWorker.js
Labels: Pamplemoose

#6484 [MB-7724] Eslint-plugin-ato checks for eslint-disable-line usage
  eslint-plugin-ato/no-unapproved-annotation.js
  eslint-plugin-ato/tests/no-unapproved-annotation.test.js
Labels: Pamplemoose

#6480 MB-7649 Edit allowances backend
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20210420195709_adding_progear_and_spouse_entitlments.up.sql
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/update_order_payload.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/orders.go
  pkg/handlers/ghcapi/orders_test.go
  pkg/models/ghc_entitlements.go
  pkg/models/ghc_entitlements_test.go
  pkg/models/order.go
  pkg/services/order/order_updater.go
  pkg/services/order/order_updater_test.go
  pkg/testdatagen/make_entitlement.go
  swagger/ghc.yaml
Labels: ttv

#6515 [MB-7652] Service item calculations should show first three digits of ZIP3 fields
  src/components/Office/ServiceItemCalculations/ServiceItemCalculations.test.jsx
  src/components/Office/ServiceItemCalculations/helpers.js
  src/components/Office/ServiceItemCalculations/helpers.test.js
Labels: ttv

#6514 [MB-7522] Remove puppeteer benchmarking code, node dependencies, gitignore paths
  .gitignore
  package.json
  puppeteer/benchmarking.js
  puppeteer/config.json
  puppeteer/constants.js
  puppeteer/scenarios.js
  yarn.lock
Labels: ttv

#6519 MB-5827 Update Error Comment and Turn On the FE Custom Linter
  .eslintrc.js
  .github/workflows/front-end-linter.yml
  eslint-plugin-ato/no-unapproved-annotation.js
  src/testUtils.jsx
Labels: Pamplemoose

#6530 MB-7736 failed gex connection should not mark payment reqeust status as edi error
  pkg/payment_request/send_to_syncada.go
  pkg/payment_request/send_to_syncada_test.go
  pkg/services/payment_request/payment_request_reviewed_processor.go
  pkg/services/payment_request/payment_request_reviewed_processor_test.go
Labels: A-Team

#6541 [MB-5824]Truss-IS3 as code owners of cATO related files
  .github/CODEOWNERS
  dangerfile.ts
Labels: Pamplemoose

#6528 [MB-7741] Special case for DDDSIT TIO calculations less than 50 miles different ZIP3
  src/components/Office/ServiceItemCalculations/ServiceItemCalculations.stories.jsx
  src/components/Office/ServiceItemCalculations/helpers.js
  src/components/Office/ServiceItemCalculations/helpers.test.js
  src/components/Office/ServiceItemCalculations/serviceItemTestParams.js
  src/constants/shipments.js
Labels: ttv

#6543 [MB-3539] Remove references to "IsCanceled" as related to Moves/Move Task Orders
  cmd/prime-api-dev/scripts/payment_requests.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/move_task_order.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/move_task_order.go
  pkg/gen/supportapi/embedded_spec.go
  pkg/gen/supportmessages/move_task_order.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/move_task_order_test.go
  pkg/handlers/primeapi/payloads/model_to_payload.go
  pkg/handlers/supportapi/internal/payloads/model_to_payload.go
  swagger/ghc.yaml
  swagger/prime.yaml
  swagger/support.yaml
Labels: A-Team

#6534 MB-7735 update date filter to use time stamp
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/queues/get_payment_requests_queue_parameters.go
  pkg/gen/ghcapi/ghcoperations/queues/get_payment_requests_queue_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/queues/get_services_counseling_queue_parameters.go
  pkg/gen/ghcapi/ghcoperations/queues/get_services_counseling_queue_urlbuilder.go
  pkg/handlers/ghcapi/queues.go
  pkg/handlers/ghcapi/queues_test.go
  pkg/services/order.go
  pkg/services/order/order_fetcher.go
  pkg/services/order/order_fetcher_test.go
  pkg/services/payment_request.go
  pkg/services/payment_request/payment_request_list_fetcher.go
  src/components/Table/Filters/DateSelectFilter.jsx
  src/components/Table/Filters/DateSelectFilter.test.jsx
  src/pages/Office/PaymentRequestQueue/PaymentRequestQueue.jsx
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.jsx
  src/shared/dates.js
  src/shared/dates.test.js
  swagger/ghc.yaml
Labels: roci

#6529 MB-7947 Allow Admins to update an office user's Transportation Office
  cypress/integration/admin/officeUsers.js
  pkg/gen/adminapi/embedded_spec.go
  pkg/gen/adminmessages/office_user_update_payload.go
  pkg/handlers/adminapi/office_users.go
  pkg/handlers/adminapi/office_users_test.go
  pkg/handlers/adminapi/offices.go
  pkg/services/office_user/office_user_fetcher_test.go
  pkg/services/office_user/office_user_updater.go
  pkg/services/office_user/office_user_updater_test.go
  src/pages/Admin/OfficeUsers/OfficeUserEdit.jsx
  swagger/admin.yaml
Labels: roci
