Repository transcom/mymove, pull requests merged in 2021-06, with the labels that each got.

#6706 MB-8146 Allow order updates for counselor and TOO
  cypress/integration/office/txo/tooFlows.js
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/ghcapi/ghcoperations/order/counseling_update_allowance.go
  pkg/gen/ghcapi/ghcoperations/order/counseling_update_allowance_parameters.go
  pkg/gen/ghcapi/ghcoperations/order/counseling_update_allowance_responses.go
  pkg/gen/ghcapi/ghcoperations/order/counseling_update_allowance_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/order/counseling_update_order.go
  pkg/gen/ghcapi/ghcoperations/order/counseling_update_order_parameters.go
  pkg/gen/ghcapi/ghcoperations/order/counseling_update_order_responses.go
  pkg/gen/ghcapi/ghcoperations/order/counseling_update_order_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/order/update_allowance_responses.go
  pkg/gen/ghcapi/ghcoperations/order/update_order_responses.go
  pkg/gen/ghcmessages/counseling_update_allowance_payload.go
  pkg/gen/ghcmessages/counseling_update_order_payload.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/orders.go
  pkg/handlers/ghcapi/orders_test.go
  pkg/models/order_test.go
  pkg/services/event/ghc_endpoint.go
  pkg/services/mocks/OrderUpdater.go
  pkg/services/order.go
  pkg/services/order/order_updater.go
  pkg/services/order/order_updater_test.go
  pkg/testdatagen/make_move.go
  pkg/testdatagen/make_office_user.go
  src/pages/Office/ServicesCounselingMoveAllowances/ServicesCounselingMoveAllowances.jsx
  src/pages/Office/ServicesCounselingOrders/ServicesCounselingOrders.jsx
  src/services/ghcApi.js
  swagger/ghc.yaml
Labels: bug, ttv

#6708 [MB-8027] UpdateMTOShipment should not be able to update addresses
  pkg/fakedata_approved/fakedata_approved.go
  pkg/handlers/primeapi/api_test.go
  pkg/handlers/primeapi/move_task_order_test.go
  pkg/handlers/primeapi/mto_shipment.go
  pkg/handlers/primeapi/mto_shipment_test.go
  pkg/services/mto_shipment/mto_shipment_updater.go
  pkg/testdatagen/make_mto_agent.go
  pkg/testdatagen/make_mto_shipment.go
Labels: roci

#6713 [MB-7971] Disable submit move button when shipments are soft deleted
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.test.jsx
Labels: Pamplemoose

#6676 [MB-8182] Migration to remove CACs for Abigail, Suz, Ren, Kim, and Garrett
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20210521220916_remove_old_cac_certs.up.sql
Labels: A-Team

#6717 MB-8173 Add secondary pickup address to customer return info
  pkg/handlers/apitests.go
  pkg/handlers/internalapi/internal/payloads/model_to_payload.go
  pkg/handlers/internalapi/mto_shipment_test.go
  pkg/handlers/primeapi/api_test.go
Labels: Pamplemoose

#6719 MB-8176 return additional destination addresses to customer
  pkg/handlers/internalapi/internal/payloads/model_to_payload.go
  pkg/handlers/internalapi/mto_shipment_test.go
Labels: Pamplemoose

#6736 MB-8226 Change Wording on the Review Page
  src/pages/MyMove/Review/index.jsx
Labels: Pamplemoose

#6720 MB-8223: Design and copy changes to Move 101 page
  src/components/Customer/MilmoveCard/MilmoveCard.jsx
  src/components/Customer/MilmoveCard/MilmoveCard.module.scss
  src/components/Customer/MilmoveCard/MilmoveCard.stories.jsx
  src/icons.js
  src/images/hhg-shipment.jpg
  src/images/move-counselor.jpg
  src/images/moving-truck.jpg
  src/images/ppm-shipment.png
  src/pages/MyMove/MovingInfo.jsx
  src/pages/MyMove/MovingInfo.module.scss
  src/pages/MyMove/MovingInfo.stories.jsx
  src/pages/MyMove/MovingInfo.test.jsx
  src/stories/icons.stories.jsx
Labels: Pamplemoose

#6742 MB-7695 Services Counselor can view the secondary destination address
  pkg/handlers/ghcapi/mto_shipment.go
  src/components/Office/RequestedShipments/RequestedShipments.jsx
  src/components/Office/ShipmentApprovalPreview.jsx
  src/components/Office/ShipmentDisplay/ShipmentDisplay.jsx
  src/components/Office/ShipmentDisplay/ShipmentDisplay.stories.jsx
  src/components/Office/ShipmentDisplay/ShipmentDisplay.test.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.test.jsx
Labels: roci

#6737 [MB-7686] Move details and Move Task Order shipment diversion tags
  pkg/testdatagen/scenario/devseed.go
  pkg/testdatagen/scenario/shared.go
  src/components/Office/RequestedShipments/RequestedShipments.jsx
  src/components/Office/ShipmentApprovalPreview.jsx
  src/components/Office/ShipmentApprovalPreview.test.jsx
  src/components/Office/ShipmentContainer.stories.jsx
  src/components/Office/ShipmentDisplay/ShipmentDisplay.jsx
  src/components/Office/ShipmentDisplay/ShipmentDisplay.module.scss
  src/components/Office/ShipmentDisplay/ShipmentDisplay.stories.jsx
  src/components/Office/ShipmentDisplay/ShipmentDisplay.test.jsx
  src/components/Office/ShipmentHeading.jsx
  src/components/Office/ShipmentHeading.test.jsx
  src/components/Office/shipmentApprovalPreview.module.scss
  src/components/Office/shipmentHeading.module.scss
  src/components/Office/shipmentheading.stories.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
  src/types/order.js
Labels: ttv

#6732 MB-8154 Update customer api endpoints to allow setting/editing secondary pickup address
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/create_shipment.go
  pkg/gen/internalmessages/update_shipment.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/handlers/internalapi/internal/payloads/payload_to_model.go
  pkg/handlers/internalapi/mto_shipment_test.go
  pkg/services/mto_shipment/mto_shipment_creator.go
  pkg/services/mto_shipment/mto_shipment_creator_test.go
  swagger/internal.yaml
Labels: Pamplemoose

#6743 MB-8237 log user activation and deactivation
  pkg/handlers/adminapi/admin_users.go
  pkg/handlers/adminapi/office_users.go
  pkg/handlers/adminapi/users.go
  pkg/services/audit/audit.go
  pkg/services/audit/audit_test.go
Labels: roci

#6726 MB-6464 generalize filters
  pkg/handlers/adminapi/access_code.go
  pkg/handlers/adminapi/access_code_test.go
  pkg/handlers/adminapi/moves.go
  pkg/handlers/adminapi/moves_test.go
  pkg/handlers/adminapi/notifications.go
  pkg/handlers/adminapi/office_users.go
  pkg/handlers/adminapi/offices.go
  pkg/handlers/adminapi/query_filters.go
  pkg/handlers/adminapi/query_filters_test.go
  pkg/handlers/adminapi/transportation_service_provider_performances.go
  pkg/handlers/adminapi/transportation_service_provider_performances_test.go
  pkg/handlers/adminapi/users.go
Labels: roci

#6722 [MB-3669] use zip3 when determining line haul vs short haul
  pkg/payment_request/service_param_value_lookups/distance_zip3_lookup.go
  pkg/payment_request/service_param_value_lookups/distance_zip3_lookup_test.go
  pkg/payment_request/service_param_value_lookups/distance_zip5_lookup.go
  pkg/payment_request/service_param_value_lookups/distance_zip5_lookup_test.go
Labels: A-Team

#6744 MB-8270 TOO can approve diversion requested shipment via api
  pkg/services/mto_shipment/mto_shipment_updater.go
  pkg/services/mto_shipment/mto_shipment_updater_test.go
  pkg/services/mto_shipment/shipment_router.go
  pkg/services/mto_shipment/shipment_router_test.go
Labels: ttv

#6735 [MB-8239] Admin can pass in nil for user active status
  pkg/gen/adminapi/adminoperations/users/update_user_responses.go
  pkg/gen/adminapi/embedded_spec.go
  pkg/gen/adminmessages/user_update_payload.go
  pkg/handlers/adminapi/payloads/payload_to_model.go
  pkg/handlers/adminapi/users.go
  pkg/handlers/adminapi/users_test.go
  pkg/services/user/user_updater_test.go
  pkg/testdatagen/make_user.go
  src/scenes/SystemAdmin/shared/rest_provider.js
  swagger/admin.yaml
Labels: roci

#6772 MB-8159 see additional destination addresses on review page
  pkg/models/move.go
  pkg/services/mto_shipment/mto_shipment_creator.go
  src/components/Customer/Review/ShipmentCard/DeliveryDisplay.jsx
  src/components/Customer/Review/ShipmentCard/HHGShipmentCard/index.jsx
  src/components/Customer/Review/ShipmentCard/HHGShipmentCard/index.test.jsx
  src/components/Customer/Review/ShipmentCard/NTSRShipmentCard/index.jsx
  src/components/Customer/Review/ShipmentCard/NTSRShipmentCard/index.test.jsx
  src/components/Customer/Review/ShipmentCard/ShipmentCard.stories.jsx
  src/components/Customer/Review/Summary/index.jsx
  src/types/customerShapes.js
Labels: Pamplemoose

#6766 [MB-8342] Add uploaded_amended_orders_id to orders table
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20210608162156_add_uploaded_amended_orders_id_to_orders.up.sql
  pkg/models/order.go
  pkg/models/order_test.go
Labels: A-Team

#6785 MB-8012 Update createMTOShipments to allow only one agent of each type
  pkg/services/mto_shipment/mto_shipment_creator.go
  pkg/services/mto_shipment/mto_shipment_creator_test.go
Labels: roci

#6780 MB-8148 Show roles not deleted
  pkg/models/user.go
  pkg/models/user_test.go
  pkg/testdatagen/make_office_user.go
  pkg/testdatagen/make_role.go
  pkg/testdatagen/make_user.go
  pkg/testdatagen/shared.go
Labels: ttv

#6771 MB-7698, MB-7697 TOO can view additional addresses
  src/components/Customer/Review/ShipmentCard/PPMShipmentCard/index.jsx
  src/components/Customer/Review/ShipmentCard/ShipmentCard.module.scss
  src/components/Office/DefinitionLists/ShipmentInfoList.jsx
  src/components/Office/DefinitionLists/ShipmentInfoList.stories.jsx
  src/components/Office/DefinitionLists/ShipmentInfoList.test.jsx
  src/components/Office/RequestedShipments/RequestedShipments.jsx
  src/components/Office/RequestedShipments/RequestedShipments.test.jsx
  src/components/Office/ShipmentApprovalPreview.jsx
  src/components/Office/ShipmentApprovalPreview.test.jsx
  src/components/Office/ShipmentDetails/ShipmentDetails.jsx
  src/components/Office/ShipmentDetails/ShipmentDetails.module.scss
  src/components/Office/ShipmentDetails/ShipmentDetails.stories.jsx
  src/components/Office/ShipmentDetails/ShipmentDetailsMain.jsx
  src/components/Office/ShipmentDetails/ShipmentDetailsSidebar.jsx
  src/components/Office/ShipmentDetails/ShipmentDetailsSidebar.test.jsx
  src/components/Office/ShipmentDisplay/ShipmentDisplay.jsx
  src/components/Office/ShipmentDisplay/ShipmentDisplay.module.scss
  src/components/Office/ShipmentDisplay/ShipmentDisplay.stories.jsx
  src/components/Office/ShipmentDisplay/ShipmentDisplay.test.jsx
  src/components/Office/shipmentApprovalPreview.module.scss
  src/containers/SimpleSection/SimpleSection.jsx
  src/containers/SimpleSection/SimpleSection.module.scss
  src/containers/SimpleSection/SimpleSection.stories.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
  src/styles/descriptionList.module.scss
  src/types/agent.js
  src/types/shipment.js
  src/utils/shipmentDisplay.jsx
  src/utils/shipmentDisplay.test.jsx
Labels: roci

#6787 MB-8158 Add Secondary Pickup Addresses to the Shipment Card Displays
  src/components/Customer/Review/ShipmentCard/HHGShipmentCard/index.jsx
  src/components/Customer/Review/ShipmentCard/HHGShipmentCard/index.test.jsx
  src/components/Customer/Review/ShipmentCard/NTSRShipmentCard/index.test.jsx
  src/components/Customer/Review/ShipmentCard/NTSShipmentCard/index.jsx
  src/components/Customer/Review/ShipmentCard/NTSShipmentCard/index.test.jsx
  src/components/Customer/Review/ShipmentCard/PickupDisplay.jsx
  src/components/Customer/Review/ShipmentCard/ShipmentCard.stories.jsx
  src/components/Customer/Review/Summary/index.jsx
Labels: Pamplemoose

#6793 MB-8155 Add secondary destination address to customer `MtoShipmentForm`
  src/components/Customer/MtoShipmentForm/MtoShipmentForm.jsx
  src/components/Customer/MtoShipmentForm/MtoShipmentForm.stories.jsx
  src/components/Customer/MtoShipmentForm/MtoShipmentForm.test.jsx
  src/utils/formatMtoShipment.js
  src/utils/formatMtoShipment.test.js
Labels: Pamplemoose

#6794 MB-8284 fix flaky e2e test for services counselor
  cypress/integration/office/servicescounseling/servicesCounselingFlows.js
  pkg/testdatagen/scenario/e2ebasic.go
Labels: ttv

#6768 MB-8247 add orders link for orders amendment flow (front end)
  src/components/Customer/Home/Step/Step.module.scss
  src/components/Customer/Home/Step/Step.stories.jsx
  src/components/Customer/Home/Step/index.jsx
  src/pages/MyMove/Home/index.jsx
  src/pages/MyMove/Home/index.test.jsx
Labels: A-Team

#6786 [MB-4149] Upgrade xlsx to version 2.x
  cmd/ghc-pricing-parser/main.go
  cmd/ghc-transit-time-parser/main.go
  go.mod
  go.sum
  pkg/parser/pricing/parse.go
  pkg/parser/pricing/parse_access_and_add_prices.go
  pkg/parser/pricing/parse_management_counseling_transition_prices.go
  pkg/parser/pricing/parse_nonstandard_location_prices.go
  pkg/parser/pricing/parse_test.go
  pkg/parser/pricing/shared.go
  pkg/parser/transittime/parse.go
  pkg/parser/transittime/parse_test.go
  pkg/parser/transittime/shared.go
  pkg/tools/tools.go
Labels: A-Team

#6776 [MB-7683] TOO can send request for shipment diversion to GHC Prime
  pkg/handlers/ghcapi/mto_shipment.go
  src/components/Office/ShipmentAddresses/ShipmentAddresses.jsx
  src/components/Office/ShipmentAddresses/ShipmentAddresses.module.scss
  src/components/Office/ShipmentAddresses/ShipmentAddresses.test.jsx
  src/components/Office/ShipmentDetails/ShipmentDetails.jsx
  src/components/Office/ShipmentDetails/ShipmentDetailsMain.jsx
  src/components/Office/ShipmentHeading.jsx
  src/components/Office/ShipmentHeading.test.jsx
  src/constants/shipments.js
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
Labels: ttv

#6767 MB-8330 Add endpoint for approving shipment
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/ghcapi/ghcoperations/shipment/approve_shipment.go
  pkg/gen/ghcapi/ghcoperations/shipment/approve_shipment_diversion.go
  pkg/gen/ghcapi/ghcoperations/shipment/approve_shipment_diversion_parameters.go
  pkg/gen/ghcapi/ghcoperations/shipment/approve_shipment_diversion_responses.go
  pkg/gen/ghcapi/ghcoperations/shipment/approve_shipment_diversion_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/shipment/approve_shipment_parameters.go
  pkg/gen/ghcapi/ghcoperations/shipment/approve_shipment_responses.go
  pkg/gen/ghcapi/ghcoperations/shipment/approve_shipment_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/shipment/reject_shipment.go
  pkg/gen/ghcapi/ghcoperations/shipment/reject_shipment_parameters.go
  pkg/gen/ghcapi/ghcoperations/shipment/reject_shipment_responses.go
  pkg/gen/ghcapi/ghcoperations/shipment/reject_shipment_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/shipment/request_shipment_cancellation.go
  pkg/gen/ghcapi/ghcoperations/shipment/request_shipment_cancellation_parameters.go
  pkg/gen/ghcapi/ghcoperations/shipment/request_shipment_cancellation_responses.go
  pkg/gen/ghcapi/ghcoperations/shipment/request_shipment_cancellation_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/shipment/request_shipment_diversion.go
  pkg/gen/ghcapi/ghcoperations/shipment/request_shipment_diversion_parameters.go
  pkg/gen/ghcapi/ghcoperations/shipment/request_shipment_diversion_responses.go
  pkg/gen/ghcapi/ghcoperations/shipment/request_shipment_diversion_urlbuilder.go
  pkg/gen/ghcmessages/reject_shipment.go
  pkg/handlers/contexts.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/mto_shipment.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/handlers/internalapi/api.go
  pkg/handlers/internalapi/moves.go
  pkg/handlers/mocks/HandlerContext.go
  pkg/services/event/event.go
  pkg/services/event/ghc_endpoint.go
  pkg/services/mocks/MoveRouter.go
  pkg/services/mocks/ShipmentApprover.go
  pkg/services/mocks/ShipmentCancellationRequester.go
  pkg/services/mocks/ShipmentDiversionApprover.go
  pkg/services/mocks/ShipmentDiversionRequester.go
  pkg/services/mocks/ShipmentRejecter.go
  pkg/services/mocks/ShipmentRouter.go
  pkg/services/move.go
  pkg/services/move/move_router.go
  pkg/services/mto_shipment.go
  pkg/services/mto_shipment/shipment_approver.go
  pkg/services/mto_shipment/shipment_approver_test.go
  pkg/services/mto_shipment/shipment_cancellation_requester.go
  pkg/services/mto_shipment/shipment_cancellation_requester_test.go
  pkg/services/mto_shipment/shipment_diversion_approver.go
  pkg/services/mto_shipment/shipment_diversion_approver_test.go
  pkg/services/mto_shipment/shipment_diversion_requester.go
  pkg/services/mto_shipment/shipment_diversion_requester_test.go
  pkg/services/mto_shipment/shipment_rejecter.go
  pkg/services/mto_shipment/shipment_rejecter_test.go
  pkg/services/mto_shipment/shipment_router.go
  pkg/services/mto_shipment/shipment_router_test.go
  swagger/ghc.yaml
Labels: ttv

#6795 MMDM-2790 migration to remove shimona cac access
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20210611202542_remove_shimona_cac.up.sql
Labels: ttv

#6802 Upload ronolibert CAC
  migrations/app/migrations_manifest.txt
  migrations/app/secure/20210614144532_ronolibert_cac.up.sql
Labels: Pamplemoose

#6805 Update shipment tests
  pkg/services/mto_shipment/shipment_approver_test.go
  pkg/services/mto_shipment/shipment_cancellation_requester_test.go
  pkg/services/mto_shipment/shipment_diversion_approver_test.go
  pkg/services/mto_shipment/shipment_diversion_requester_test.go
  pkg/services/mto_shipment/shipment_rejecter_test.go
  pkg/services/mto_shipment/shipment_router_test.go
Labels: ttv

#6803 MB-8372 add csv import button to admin app
  cypress/integration/admin/officeUsers.js
  package.json
  src/pages/Admin/OfficeUsers/OfficeUserList.jsx
  yarn.lock
Labels: roci

#6813 [MB-8174] Update devseed data for multiple pickup addresses
  pkg/testdatagen/make_mto_shipment.go
  pkg/testdatagen/scenario/devseed.go
Labels: Pamplemoose

#6821 MB-8227 Copy Changes for Shipment Details
  src/components/Customer/MtoShipmentForm/MtoShipmentForm.jsx
  src/components/Customer/MtoShipmentForm/MtoShipmentForm.test.jsx
  src/content/shipments.js
Labels: Pamplemoose

#6820 MB-8211: Copy and design changes to review shipments page
  src/components/Customer/Review/AddShipmentModal/index.jsx
  src/components/Customer/Review/AddShipmentModal/index.module.scss
  src/components/Customer/Review/Review.stories.jsx
  src/components/Customer/Review/Summary/Summary.module.scss
  src/components/Customer/Review/Summary/index.jsx
  src/components/Customer/Review/Summary/index.test.jsx
  src/components/Customer/modals/CustomerModals.stories.jsx
Labels: Pamplemoose

#6812 MB-8177 Update devseed data for multiple addresses
  Makefile
  pkg/handlers/internalapi/mto_shipment_test.go
  pkg/handlers/primeapi/mto_shipment_test.go
  pkg/services/move_task_order/move_task_order_hide_non_fake_test.go
  pkg/services/mto_shipment/mto_shipment_creator_test.go
  pkg/services/mto_shipment/mto_shipment_updater_test.go
  pkg/testdatagen/make_mto_shipment.go
  pkg/testdatagen/make_service_member.go
  pkg/testdatagen/scenario/devseed.go
Labels: Pamplemoose

#6811 [MB-7680] TOO can identify newest orders uploaded in TOO UI
  pkg/testdatagen/scenario/devseed.go
  src/components/DocumentViewer/Content/Content.test.jsx
  src/components/DocumentViewer/DocumentViewer.jsx
  src/components/DocumentViewer/DocumentViewer.module.scss
  src/components/DocumentViewer/DocumentViewer.stories.jsx
  src/components/DocumentViewer/DocumentViewer.test.jsx
  src/components/DocumentViewer/Menu/Menu.jsx
  src/components/DocumentViewer/Menu/Menu.module.scss
  src/components/DocumentViewer/Menu/Menu.stories.jsx
  src/components/DocumentViewer/Menu/Menu.test.jsx
Labels: ttv

#6830 [MB-8385] Upgrade xlsx to version 3.x
  cmd/ghc-pricing-parser/main.go
  cmd/ghc-transit-time-parser/main.go
  go.mod
  go.sum
  pkg/parser/pricing/parse.go
  pkg/parser/pricing/parse_access_and_add_prices.go
  pkg/parser/pricing/parse_domestic_linehaul_prices.go
  pkg/parser/pricing/parse_domestic_other_prices.go
  pkg/parser/pricing/parse_domestic_service_area_prices.go
  pkg/parser/pricing/parse_international_prices.go
  pkg/parser/pricing/parse_management_counseling_transition_prices.go
  pkg/parser/pricing/parse_nonstandard_location_prices.go
  pkg/parser/pricing/parse_other_intl_prices.go
  pkg/parser/pricing/parse_price_escalation_discount.go
  pkg/parser/pricing/parse_service_areas.go
  pkg/parser/pricing/parse_test.go
  pkg/parser/pricing/shared.go
  pkg/parser/transittime/parse.go
  pkg/parser/transittime/parse_test.go
  pkg/parser/transittime/parse_transit_times.go
  pkg/parser/transittime/shared.go
Labels: A-Team

#6823 [MB-7581] Add AddAmendedOrders endpoint/handler/service
  pkg/gen/internalapi/configure_mymove.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalapi/internaloperations/mymove_api.go
  pkg/gen/internalapi/internaloperations/orders/upload_amended_orders.go
  pkg/gen/internalapi/internaloperations/orders/upload_amended_orders_parameters.go
  pkg/gen/internalapi/internaloperations/orders/upload_amended_orders_responses.go
  pkg/gen/internalapi/internaloperations/orders/upload_amended_orders_urlbuilder.go
  pkg/handlers/internalapi/api.go
  pkg/handlers/internalapi/orders.go
  pkg/services/event/internal_endpoint.go
  pkg/services/mocks/OrderUpdater.go
  pkg/services/order.go
  pkg/services/order/order_updater.go
  swagger/internal.yaml
Labels: A-Team

#6824 MB-3728 update interface for future refactoring
  pkg/handlers/ghcapi/mto_shipment.go
  pkg/handlers/internalapi/mto_shipment.go
  pkg/handlers/internalapi/mto_shipment_test.go
  pkg/handlers/primeapi/mto_shipment.go
  pkg/handlers/primeapi/mto_shipment_test.go
  pkg/services/mocks/MTOShipmentUpdater.go
  pkg/services/mto_shipment.go
  pkg/services/mto_shipment/mto_shipment_updater.go
  pkg/services/mto_shipment/mto_shipment_updater_test.go
Labels: roci

#6827 [MB-2352] Service object should match the API to Service Object pattern in the API
  pkg/handlers/primeapi/api.go
  pkg/handlers/primeapi/upload.go
  pkg/handlers/primeapi/upload_test.go
Labels: A-Team

#6826 [MB-8336] Customer can see list of documents after uploading new orders (back-end)
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/orders.go
  pkg/handlers/internalapi/orders.go
  pkg/models/service_member.go
  swagger/internal.yaml
Labels: A-Team

#6788 [MB-8331] Create page for uploading amended orders
  src/constants/routes.js
  src/pages/MyMove/AmendOrders/AmendOrders.jsx
  src/pages/MyMove/AmendOrders/AmendOrders.test.jsx
  src/pages/MyMove/Home/index.jsx
  src/scenes/MyMove/index.jsx
Labels: A-Team

#6833 MB-8310 Set diverted shipments to SUBMITTED status, and move to APPROVALS REQUESTED
  pkg/handlers/ghcapi/mto_shipment.go
  pkg/services/mto_shipment/mto_shipment_creator.go
  pkg/services/mto_shipment/mto_shipment_creator_test.go
  pkg/services/mto_shipment/mto_shipment_updater.go
  pkg/services/mto_shipment/mto_shipment_updater_test.go
Labels: roci

#6831 MB-8373 add parsing functionality to admin app
  cypress/fixtures/officeUsers.csv
  cypress/integration/admin/officeUsers.js
  src/components/Admin/ImportCsvButton/index.jsx
  src/constants/userRoles.js
  src/pages/Admin/OfficeUsers/OfficeUserList.jsx
  src/scenes/SystemAdmin/shared/RolesCheckboxes.jsx
  src/scenes/SystemAdmin/shared/rest_provider.js
Labels: roci

#6839 MB-8414 Prime API: Update moveTaskOrder and fetchMTOUpdates descriptions
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/move_task_order/fetch_m_t_o_updates.go
  pkg/gen/primeclient/move_task_order/move_task_order_client.go
  swagger/prime.yaml
Labels: roci

#6810 MB-3728 refactor validator pattern
  pkg/handlers/primeapi/api.go
  pkg/handlers/primeapi/mto_agent_test.go
  pkg/services/mocks/MTOAgentUpdater.go
  pkg/services/mto_agent.go
  pkg/services/mto_agent/mto_agent_creator.go
  pkg/services/mto_agent/mto_agent_updater.go
  pkg/services/mto_agent/mto_agent_updater_test.go
  pkg/services/mto_agent/rules.go
  pkg/services/mto_agent/rules_test.go
  pkg/services/mto_agent/validate/mto_agent_rules.go
  pkg/services/mto_agent/validate/mto_agent_rules_test.go
  pkg/services/mto_agent/validate/mto_agent_validate_service_test.go
  pkg/services/mto_agent/validate/mto_agent_validator.go
  pkg/services/mto_agent/validate/mto_agent_validator_test.go
  pkg/services/mto_agent/validation.go
  pkg/services/mto_agent/validation_test.go
  pkg/testingsuite/pop_suite.go
Labels: roci

#6865 [MB-8311] Set move status to approvals requested when customer uploads amended orders
  pkg/services/mocks/MoveRouter.go
  pkg/services/move.go
  pkg/services/move/move_router.go
  pkg/services/move/move_router_test.go
Labels: ttv

#6876 MB-8493-add-search-to-offices-page
  cypress/integration/admin/offices.js
  src/pages/Admin/Offices/OfficeList.jsx
  src/scenes/SystemAdmin/Home.jsx
Labels: roci

#6877 use latest milmove-cypress image: MB-8273
  cypress/Dockerfile.cypress
Labels: Pamplemoose

#6863 MB-8172 Verify that adding additional pickup addresses works end to end
  cypress/integration/mymove/hhg.js
  cypress/integration/mymove/nts.js
  src/components/Customer/MtoShipmentForm/MtoShipmentForm.jsx
Labels: Pamplemoose

#6867 MB-7679 TOO is notified of newly uploaded orders in TOO UI
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20210622184646_add_amended_orders_acknowledgement_timestamp.up.sql
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/order.go
  pkg/gen/ghcmessages/update_order_payload.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/orders.go
  pkg/handlers/ghcapi/orders_test.go
  pkg/models/order.go
  pkg/services/mocks/MoveRouter.go
  pkg/services/mocks/MoveTaskOrderUpdater.go
  pkg/services/move.go
  pkg/services/move/move_router.go
  pkg/services/move_task_order.go
  pkg/services/move_task_order/move_task_order_updater.go
  pkg/services/order/order_updater.go
  pkg/testdatagen/scenario/bandwidth.go
  pkg/testdatagen/scenario/devseed.go
  src/components/Office/AllowancesDetailForm/AllowancesDetailForm.jsx
  src/components/Office/DetailsPanel/DetailsPanel.jsx
  src/components/Office/DetailsPanel/DetailsPanel.module.scss
  src/components/Office/DetailsPanel/DetailsPanel.stories.jsx
  src/components/Office/DetailsPanel/DetailsPanel.test.jsx
  src/components/Office/OrdersDetailForm/OrdersDetailForm.jsx
  src/components/Office/OrdersDetailForm/OrdersDetailForm.module.scss
  src/components/Office/OrdersDetailForm/OrdersDetailForm.stories.jsx
  src/components/form/CustomerContactInfoFields/index.jsx
  src/components/form/fields/CheckboxField.jsx
  src/components/form/fields/CheckboxField.test.jsx
  src/components/form/fields/index.js
  src/hooks/queries.js
  src/hooks/queries.test.js
  src/pages/Office/MoveDetails/MoveDetails.jsx
  src/pages/Office/MoveDetails/MoveDetails.test.jsx
  src/pages/Office/MoveDocumentWrapper/MoveDocumentWrapper.jsx
  src/pages/Office/Orders/Orders.jsx
  swagger/ghc.yaml
Labels: ttv

#6851 MB-8175 verify that adding addtional destination address works end to end
  cypress/integration/mymove/hhg.js
  cypress/integration/mymove/ntsr.js
  src/components/Customer/MtoShipmentForm/MtoShipmentForm.jsx
Labels: Pamplemoose

#6864 MB-8224: Copy changes for Select Shipment Type screen
  cypress/integration/mymove/hhg.js
  src/pages/MyMove/SelectShipmentType.jsx
  src/pages/MyMove/SelectShipmentType.stories.jsx
  src/pages/MyMove/SelectShipmentType.test.jsx
Labels: Pamplemoose

#6849 MB-8345 Use new shipment endpoints
  cypress/integration/office/txo/tooFlows.js
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/mto_shipment/patch_m_t_o_shipment_status.go
  pkg/gen/ghcapi/ghcoperations/mto_shipment/patch_m_t_o_shipment_status_parameters.go
  pkg/gen/ghcapi/ghcoperations/mto_shipment/patch_m_t_o_shipment_status_responses.go
  pkg/gen/ghcapi/ghcoperations/mto_shipment/patch_m_t_o_shipment_status_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/ghcmessages/m_t_o_shipment.go
  pkg/gen/ghcmessages/patch_m_t_o_shipment_status.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/mto_shipment.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/services/event/event_test.go
  pkg/services/event/ghc_endpoint.go
  pkg/services/mto_shipment/shipment_diversion_approver_test.go
  pkg/services/mto_shipment/shipment_router.go
  pkg/services/mto_shipment/shipment_router_test.go
  pkg/testdatagen/scenario/devseed.go
  pkg/testdatagen/scenario/shared.go
  src/components/Office/RequestedShipments/RequestedShipments.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
  src/services/ghcApi.js
  src/shared/Entities/modules/mtoShipments.js
  swagger/ghc.yaml
Labels: ttv

#6845 [MB-8415] Edit orders review amended orders sets move status to approved
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/order/update_order_responses.go
  pkg/handlers/ghcapi/api_test.go
  pkg/handlers/ghcapi/mto_service_items_test.go
  pkg/handlers/ghcapi/orders.go
  pkg/handlers/ghcapi/orders_test.go
  pkg/handlers/supportapi/mto_service_item_test.go
  pkg/services/mocks/MoveRouter.go
  pkg/services/move.go
  pkg/services/move/move_router.go
  pkg/services/move/move_router_test.go
  pkg/services/mto_service_item/mto_service_item_updater.go
  pkg/services/mto_service_item/mto_service_item_updater_test.go
  pkg/services/order/order_updater_test.go
  pkg/testdatagen/make_move.go
  pkg/testdatagen/make_order.go
  pkg/testdatagen/shared.go
  src/components/Office/OrdersDetailForm/OrdersDetailForm.module.scss
  src/components/Office/OrdersDetailForm/OrdersDetailForm.test.jsx
  src/hooks/queries.test.js
  src/pages/Office/MoveDocumentWrapper/MoveDocumentWrapper.test.jsx
  swagger/ghc.yaml
Labels: ttv

#6868 MB-8142 858 fixes
  pkg/edi/invoice/generator.go
  pkg/edi/invoice/generator_test.go
  pkg/edi/segment/c3.go
  pkg/edi/segment/c3_test.go
  pkg/edi/segment/hl.go
  pkg/services/invoice/ghc_payment_request_invoice_generator.go
  pkg/services/invoice/ghc_payment_request_invoice_generator_test.go
Labels: A-Team

#6892 WIP: Bump storybook deps to 6.3.1: MB-8273
  package.json
  yarn.lock
Labels: Pamplemoose

#6882 [MB-1284] Clean up output for GHC pricing parser
  cmd/ghc-pricing-parser/logger.go
  cmd/ghc-pricing-parser/main.go
  go.mod
  go.sum
  pkg/parser/pricing/parse.go
  pkg/parser/pricing/parse_access_and_add_prices.go
  pkg/parser/pricing/parse_domestic_linehaul_prices.go
  pkg/parser/pricing/parse_domestic_other_prices.go
  pkg/parser/pricing/parse_domestic_service_area_prices.go
  pkg/parser/pricing/parse_international_prices.go
  pkg/parser/pricing/parse_management_counseling_transition_prices.go
  pkg/parser/pricing/parse_nonstandard_location_prices.go
  pkg/parser/pricing/parse_other_intl_prices.go
  pkg/parser/pricing/parse_price_escalation_discount.go
  pkg/parser/pricing/parse_service_areas.go
  pkg/parser/pricing/parse_test.go
  pkg/parser/pricing/shared.go
  pkg/services/ghcimport/ghc_rateengine_importer.go
Labels: A-Team

#6875 [MB-8101] implement new uploads table design
  src/components/UploadsTable/UploadsTable.jsx
  src/components/UploadsTable/UploadsTable.module.scss
  src/components/UploadsTable/UploadsTable.stories.jsx
  src/components/UploadsTable/UploadsTable.test.jsx
  src/icons.js
  src/stories/icons.stories.jsx
Labels: A-Team

#6840 [MB-8101] customer can see uploaded files for amended orders
  pkg/handlers/internalapi/orders.go
  src/pages/MyMove/AmendOrders/AmendOrders.jsx
  src/store/entities/selectors.js
  src/types/customerShapes.js
Labels: A-Team

#6894 MB-8631 Add estimated and actual weights to mto service items
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20210628223755_add_actual_and_estimated_weight_to_mto_service_items.up.sql
  pkg/models/mto_service_items.go
Labels: roci

#6878 Bump node to v14: MB-8607
  .circleci/config.yml
  .github/workflows/analyze-bundle.yml
  .github/workflows/front-end-linter.yml
  .github/workflows/happo-tests-master.yml
  .github/workflows/happo-tests.yml
  .node-version
  .pre-commit-config.yaml
  Dockerfile.local
  Dockerfile.migrations_local
  Dockerfile.reviewapp
  Dockerfile.tasks_local
  Dockerfile.tools_local
  Dockerfile.webhook_client
  Dockerfile.webhook_client_local
  Makefile
  README.md
  cypress/Dockerfile.cypress
  package.json
  scripts/check-node-version
  scripts/gen-assets
  scripts/gen-server
  scripts/pre-commit-swagger-validate
  scripts/prereqs
  yarn.lock
Labels: Pamplemoose
