Repository transcom/mymove, pull requests merged in 2021-08, with the labels that each got.

#7091 [MB-2504] SystemError on error office queue page
  src/components/SystemError/SystemError.module.scss
  src/components/SystemError/index.jsx
  src/pages/Office/Office.module.scss
  src/pages/Office/ServicesCounselingMoveInfo/ServicesCounselingMoveInfo.jsx
  src/pages/Office/ServicesCounselingMoveInfo/ServicesCounselingMoveInfo.test.jsx
  src/pages/Office/TXOMoveInfo/TXOMoveInfo.jsx
  src/pages/Office/TXOMoveInfo/TXOMoveInfo.test.jsx
  src/pages/Office/index.jsx
  src/pages/Office/index.test.jsx
  src/services/ghcApi.js
  src/services/swaggerRequest.js
  src/store/interceptor/actions.js
  src/store/interceptor/actions.test.js
  src/store/interceptor/reducer.js
  src/store/interceptor/reducer.test.js
Labels: Pamplemoose

#7097 MB-8950 Storybook weight display component
  src/components/Office/WeightDisplay/WeightDisplay.jsx
  src/components/Office/WeightDisplay/WeightDisplay.module.scss
  src/components/Office/WeightDisplay/WeightDisplay.stories.jsx
  src/components/Office/WeightDisplay/WeightDisplay.test.jsx
  src/shared/styles/colors.scss
Labels: ttv

#7106 MB-7432 Rename fetchMTOUpdatesFast to listMoves
  cmd/prime-api-client/main.go
  cmd/prime-api-client/prime/list_moves.go
  pkg/gen/primeapi/configure_mymove.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/move_task_order/fetch_m_t_o_updates_fast_responses.go
  pkg/gen/primeapi/primeoperations/move_task_order/list_moves.go
  pkg/gen/primeapi/primeoperations/move_task_order/list_moves_parameters.go
  pkg/gen/primeapi/primeoperations/move_task_order/list_moves_responses.go
  pkg/gen/primeapi/primeoperations/move_task_order/list_moves_urlbuilder.go
  pkg/gen/primeapi/primeoperations/mymove_api.go
  pkg/gen/primeclient/move_task_order/fetch_m_t_o_updates_fast_parameters.go
  pkg/gen/primeclient/move_task_order/fetch_m_t_o_updates_fast_responses.go
  pkg/gen/primeclient/move_task_order/list_moves_parameters.go
  pkg/gen/primeclient/move_task_order/list_moves_responses.go
  pkg/gen/primeclient/move_task_order/move_task_order_client.go
  pkg/gen/primemessages/list_move.go
  pkg/gen/primemessages/list_moves.go
  pkg/handlers/primeapi/api.go
  pkg/handlers/primeapi/move_task_order.go
  pkg/handlers/primeapi/payloads/model_to_payload.go
  swagger/prime.yaml
Labels: roci

#7083 MB-8774 refactor edit orders paage to use formik
  src/components/Customer/EditOrdersForm/EditOrdersForm.jsx
  src/components/Customer/EditOrdersForm/EditOrdersForm.stories.jsx
  src/components/Customer/EditOrdersForm/EditOrdersForm.test.jsx
  src/constants/routes.js
  src/pages/MyMove/EditOrders.jsx
  src/pages/MyMove/EditOrders.test.jsx
  src/scenes/MyMove/index.jsx
Labels: Pamplemoose

#7105 [MB-8856] refactor prime api demo script
  scripts/README.md
  scripts/pricing-acceptance
  scripts/prime-api-demo
Labels: A-Team

#7108 [MB-7253] Add invoice support for domestic crating/uncrating
  pkg/edi/segment/l0.go
  pkg/edi/segment/l0_test.go
  pkg/edi/segment/l1.go
  pkg/edi/segment/l1_test.go
  pkg/services/invoice/ghc_payment_request_invoice_generator.go
  pkg/services/invoice/ghc_payment_request_invoice_generator_test.go
Labels: A-Team

#7121 MB-8952 Update fetchMTOUpdates to reflect it is deprecated
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/move_task_order/fetch_m_t_o_updates.go
  pkg/gen/primeclient/move_task_order/move_task_order_client.go
  swagger/prime.yaml
Labels: roci

#7093 [MB-2615] Pricers for domestic crating and uncrating
  pkg/services/ghc_rate_engine.go
  pkg/services/ghcrateengine/domestic_crating_pricer.go
  pkg/services/ghcrateengine/domestic_crating_pricer_test.go
  pkg/services/ghcrateengine/domestic_uncrating_pricer.go
  pkg/services/ghcrateengine/domestic_uncrating_pricer_test.go
  pkg/services/ghcrateengine/pricer_helpers.go
  pkg/services/ghcrateengine/pricer_helpers_test.go
  pkg/services/ghcrateengine/service_item_pricer.go
  pkg/services/ghcrateengine/service_item_pricer_test.go
  pkg/testdatagen/scenario/shared.go
  src/components/Office/ServiceItemCalculations/ServiceItemCalculations.test.jsx
  src/components/Office/ServiceItemCalculations/helpers.js
  src/components/Office/ServiceItemCalculations/helpers.test.js
  src/components/Office/ServiceItemCalculations/serviceItemTestParams.js
  src/constants/serviceItems.js
Labels: A-Team

#7116 MB-8901 Return 403 when user is not admin
  pkg/auth/authentication/auth.go
  pkg/auth/authentication/auth_test.go
Labels: bug, ttv

#7139 [MB-9035] Remove readOnly from PaymentRequestID
  pkg/gen/supportapi/embedded_spec.go
  pkg/gen/supportmessages/process_reviewed_payment_requests.go
  swagger/support.yaml
Labels: A-Team

#7137 [MB-9023] Fix 500 when creating payment requests for domestic crating and uncrating
  pkg/payment_request/service_param_value_lookups/service_param_value_lookups.go
  pkg/services/mocks/DomesticCratingPricer.go
  pkg/services/mocks/DomesticUncratingPricer.go
Labels: A-Team

#7134 Update webpack bundle diff lib with increase input over zero
  .github/workflows/analyze-bundle.yml
  src/README.md
Labels: ttv

#7118 [MB-8941] Reweighs and excess weight database models
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20210802205220_create_reweighs_table_excess_weights_columns.up.sql
  pkg/models/move.go
  pkg/models/mto_shipments.go
  pkg/models/mto_shipments_test.go
  pkg/models/reweigh.go
  pkg/models/reweigh_test.go
  pkg/testdatagen/make_reweigh.go
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/scenario/subscenarios.go
  pkg/testdatagen/shared.go
Labels: ttv

#7135 [MB-4699] Show weight summaries on MTO page
  src/components/Office/WeightDisplay/WeightDisplay.jsx
  src/components/Office/WeightDisplay/WeightDisplay.module.scss
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.module.scss
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.test.jsx
Labels: ttv

#7138 MB-4704 Add endpoint to request reweigh
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/ghcapi/ghcoperations/shipment/request_shipment_reweigh.go
  pkg/gen/ghcapi/ghcoperations/shipment/request_shipment_reweigh_parameters.go
  pkg/gen/ghcapi/ghcoperations/shipment/request_shipment_reweigh_responses.go
  pkg/gen/ghcapi/ghcoperations/shipment/request_shipment_reweigh_urlbuilder.go
  pkg/gen/ghcmessages/reweigh.go
  pkg/gen/ghcmessages/reweigh_requester.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/mto_shipment.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/services/event/event.go
  pkg/services/event/ghc_endpoint.go
  pkg/services/mocks/ShipmentReweighRequester.go
  pkg/services/mto_shipment.go
  pkg/services/mto_shipment/shipment_reweigh_requester.go
  pkg/services/mto_shipment/shipment_reweigh_requester_test.go
  pkg/services/mto_shipment/validation.go
  pkg/testdatagen/make_reweigh.go
  swagger/ghc.yaml
Labels: ttv

#7164 [MB-9081] Add GEX environment variables to TLS environments
  config/env/demo.app-client-tls.env
  config/env/exp.app-client-tls.env
  config/env/exp.post-file-to-gex.env
  config/env/exp.process-edis.env
  config/env/stg.app-client-tls-niprnet.env
  config/env/stg.app-client-tls.env
  config/env/stg.post-file-to-gex.env
  config/env/stg.process-edis.env
Labels: bug, A-Team

#7172 MB-9083 fix parsing of edi files with carriage returns
  pkg/edi/edi.go
  pkg/edi/edi824/logger.go
  pkg/edi/edi824/parser.go
  pkg/edi/edi824/parser_test.go
  pkg/edi/edi997/logger.go
  pkg/edi/edi997/parser.go
  pkg/edi/edi997/parser_test.go
  pkg/edi/edi_test.go
Labels: A-Team

#7153 [MB-8856] change from fetch-mto-updates-fast to list-moves
  scripts/pricing-acceptance
Labels: A-Team

#7173 Override location of opensc when using nix
  .envrc
  scripts/cac-prereqs
Labels: A-Team

#7144 MB-8937 ADR: Use `openapi` to compile API specs
  docs/adr/0063-use-openapi-to-compile-api-specs.md
  docs/adr/index.md
Labels: roci

#7171 [MB-8949] make estimated weight optional for payment requests
  pkg/payment_request/service_param_list_valid.go
  pkg/payment_request/service_param_value_lookups/weight_billed_actual_lookup.go
  pkg/payment_request/service_param_value_lookups/weight_billed_actual_lookup_test.go
  pkg/payment_request/service_param_value_lookups/weight_estimated_lookup.go
  pkg/payment_request/service_param_value_lookups/weight_estimated_lookup_test.go
  pkg/services/payment_request/payment_request_creator.go
Labels: A-Team

#7165 MB-9009 Show diversion requested on Move Details
  src/components/Office/ShipmentDisplay/ShipmentDisplay.jsx
  src/pages/Office/MoveDetails/MoveDetails.jsx
Labels: bug, ttv

#7178 [MB-7543] CAT II: eslint no-case-declarations
  cypress/.eslintrc
  src/scenes/.eslintrc
  src/scenes/SystemAdmin/shared/rest_provider.js
  src/shared/.eslintrc
Labels: A-Team

#7166 [MB-7692] CAT II: consistent-return finding
  cypress/.eslintrc
  package.json
  src/scenes/.eslintrc
  src/scenes/Moves/Ppm/DateAndLocation.jsx
  src/scenes/Moves/Ppm/PPMPaymentRequestActionBtns.jsx
  src/scenes/Moves/Ppm/Weight.jsx
  src/scenes/Moves/Ppm/WeightTicket.jsx
  src/scenes/Office/Ppm/PPMEstimatesPanel.jsx
  src/scenes/PpmLanding/PPMStatusTimeline.js
  src/scenes/Review/EditDateAndLocation.jsx
  src/scenes/Review/EditWeight.jsx
  src/scenes/ServiceMembers/DutyStationSearchBox.jsx
  src/scenes/SystemAdmin/shared/RolesCheckboxes.jsx
  src/shared/.eslintrc
  src/shared/Alert/index.jsx
  src/shared/AlertWithConfirmation/index.jsx
  src/shared/AlertWithDeleteConfirmation/index.jsx
  src/shared/ConfirmWithReasonButton/index.jsx
  src/shared/JsonSchemaForm/index.jsx
  src/shared/JsonSchemaForm/validator.js
  src/shared/Swagger/request.js
  src/shared/Uploader/index.jsx
  src/shared/WizardPage/Form.jsx
  src/shared/dates.js
  src/shared/formatters.js
  src/shared/utils.js
  yarn.lock
Labels: A-Team

#7179 [MB-8979] Add a sidebar to the payment request tab
  src/pages/Office/MovePaymentRequests/MovePaymentRequests.jsx
  src/pages/Office/MovePaymentRequests/MovePaymentRequests.test.jsx
Labels: Voltron

#7182 [MB-8981] Billable weight card component
  src/components/Office/BillableWeightCard/BillableWeightCard.jsx
  src/components/Office/BillableWeightCard/BillableWeightCard.module.scss
  src/components/Office/BillableWeightCard/BillableWeightCard.stories.jsx
  src/components/Office/BillableWeightCard/BillableWeightCard.test.jsx
Labels: Voltron

#7183 [MB-9062] add contract code to FSC for the purposes of displaying on the EDI
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20210812163307_add_contract_code_FSC.up.sql
Labels: A-Team

#7177 [MB-4703] TOO MTO page edit max billable weight modal
  src/components/Office/EditMaxBillableWeightModal/EditMaxBillableWeightModal.jsx
  src/components/Office/EditMaxBillableWeightModal/EditMaxBillableWeightModal.module.scss
  src/components/Office/EditMaxBillableWeightModal/EditMaxBillableWeightModal.stories.jsx
  src/components/Office/EditMaxBillableWeightModal/EditMaxBillableWeightModal.test.jsx
  src/components/Office/WeightDisplay/WeightDisplay.jsx
  src/pages/Office/MoveAllowances/MoveAllowances.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
Labels: ttv

#7169 [MB-4742] Add risk of excess weight tag to MTO page
  pkg/testdatagen/scenario/bandwidth.go
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/scenario/subscenarios.go
  src/components/Office/WeightDisplay/WeightDisplay.module.scss
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.test.jsx
  src/utils/hasRiskOfExcess.js
  src/utils/hasRiskOfExcess.test.js
Labels: ttv

#7193 [MB-9025] Create ReviewBillableWeight page
  src/pages/Office/ReviewBillableWeight/ReviewBillableWeight.jsx
  src/pages/Office/ReviewBillableWeight/ReviewBillableWeight.test.jsx
  src/pages/Office/TXOMoveInfo/TXOMoveInfo.jsx
  src/pages/Office/TXOMoveInfo/TXOMoveInfo.test.jsx
Labels: Voltron

#7197 MB-8946 Clean up profile name test console msgs
  src/pages/MyMove/Profile/Name.test.jsx
Labels: Pamplemoose

#7188 [MB-7699] CAT II Fix react/no-access-state-in-setstate finding
  cypress/.eslintrc
  src/scenes/.eslintrc
  src/scenes/Moves/Ppm/PaymentReview/DocumentsUploaded.js
  src/scenes/Moves/Ppm/WeightTicket.jsx
  src/scenes/Office/Ppm/PaymentsPanel.jsx
  src/scenes/Office/QueueTable.jsx
  src/shared/.eslintrc
  src/shared/EditablePanel/index.jsx
  src/shared/ToolTip/IconWithTooltip.jsx
  src/shared/Uploader/index.jsx
Labels: A-Team

#7200 MB-8771 Display Reweigh tags in MTO tab
  pkg/testdatagen/scenario/shared.go
  src/components/Office/ShipmentDetails/ShipmentDetailsMain.jsx
  src/components/Office/ShipmentWeightDetails/ShipmentWeightDetails.jsx
  src/components/Office/ShipmentWeightDetails/ShipmentWeightDetails.module.scss
  src/components/Office/ShipmentWeightDetails/ShipmentWeightDetails.test.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.test.jsx
Labels: ttv

#7202 MB-8945: Clean up MtoShipmentForm log pollution
  src/utils/formatMtoShipment.js
Labels: Pamplemoose

#7203 MB-9012 Email customer when TOO requests a reweigh
  pkg/assets/assets.go
  pkg/handlers/ghcapi/mto_shipment.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/notifications/reweigh_requested.go
  pkg/notifications/reweigh_requested_test.go
  pkg/notifications/templates/reweigh_requested_template.html
  pkg/notifications/templates/reweigh_requested_template.txt
Labels: Pamplemoose

#7210 [MB-4698] TOO sees reweigh weight in Shipment weight section if it is lower than prime actual weight value
  pkg/testdatagen/scenario/shared.go
  src/components/Office/ShipmentWeightDetails/ShipmentWeightDetails.jsx
  src/components/Office/ShipmentWeightDetails/ShipmentWeightDetails.test.jsx
  src/utils/returnLowestValue.js
  src/utils/returnLowestValue.test.js
Labels: ttv

#7207 [MB-9027] Add DocumentViewerSidebar component to storybook
  src/pages/Office/DocumentViewerSidebar/DocumentViewerSidebar.jsx
  src/pages/Office/DocumentViewerSidebar/DocumentViewerSidebar.module.scss
  src/pages/Office/DocumentViewerSidebar/DocumentViewerSidebar.stories.jsx
  src/pages/Office/DocumentViewerSidebar/DocumentViewerSidebar.test.jsx
Labels: Voltron

#7208 MB-8983 Create Devseed Data for Reweighs
  pkg/testdatagen/make_reweigh.go
  pkg/testdatagen/scenario/devseed.go
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/scenario/subscenarios.go
Labels: Voltron

#7206 [MB-9034] create shipment cards in storybook and use in the billableweightcard component
  src/components/Customer/Home/ShipmentList/ShipmentList.stories.jsx
  src/components/Customer/Home/Step/Step.stories.jsx
  src/components/Office/BillableWeightCard/BillableWeightCard.jsx
  src/components/Office/BillableWeightCard/BillableWeightCard.module.scss
  src/components/Office/BillableWeightCard/BillableWeightCard.stories.jsx
  src/components/Office/BillableWeightCard/BillableWeightCard.test.jsx
  src/components/ShipmentList/ShipmentList.module.scss
  src/components/ShipmentList/ShipmentList.stories.jsx
  src/components/ShipmentList/ShipmentList.test.jsx
  src/components/ShipmentList/index.jsx
  src/icons.js
  src/pages/MyMove/Home/index.jsx
Labels: Voltron

#7213 MB-8923 remove DCRTSA service code from prime and support api
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/m_t_o_service_item_domestic_crating.go
  pkg/gen/primemessages/m_t_o_service_item_model_type.go
  pkg/gen/primemessages/re_service_code.go
  pkg/gen/supportapi/embedded_spec.go
  pkg/gen/supportmessages/m_t_o_service_item_domestic_crating.go
  pkg/gen/supportmessages/m_t_o_service_item_model_type.go
  pkg/gen/supportmessages/re_service_code.go
  pkg/handlers/primeapi/mto_service_item_test.go
  pkg/handlers/primeapi/payloads/model_to_payload.go
  pkg/handlers/supportapi/internal/payloads/model_to_payload.go
  swagger/prime.yaml
  swagger/support.yaml
Labels: roci

#7215 MB-9016 remove type from prime api crating payloads and responses
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/dimension_type.go
  pkg/gen/primemessages/m_t_o_service_item_dimension.go
  pkg/gen/supportapi/embedded_spec.go
  pkg/gen/supportmessages/dimension_type.go
  pkg/gen/supportmessages/m_t_o_service_item_dimension.go
  pkg/handlers/primeapi/payloads/model_to_payload.go
  pkg/handlers/supportapi/internal/payloads/model_to_payload.go
  swagger/prime.yaml
  swagger/support.yaml
Labels: roci

#7212 [MB-9073] Shipment estimated weight update qualifies move for excess weight and approvals requested status
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/move.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/internal/payloads/notes
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/handlers/internalapi/api.go
  pkg/handlers/internalapi/mto_shipment_test.go
  pkg/handlers/primeapi/api.go
  pkg/handlers/primeapi/mto_shipment_test.go
  pkg/models/entitlements.go
  pkg/services/mocks/MoveWeights.go
  pkg/services/move.go
  pkg/services/move/move_weights.go
  pkg/services/move/move_weights_test.go
  pkg/services/mto_shipment/mto_shipment_updater.go
  pkg/services/mto_shipment/mto_shipment_updater_test.go
  pkg/testdatagen/scenario/bandwidth.go
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/scenario/subscenarios.go
  swagger/ghc.yaml
Labels: ttv

#7201 MB-9074 TOO sees tags if max billable weight needs updating on MTO tab
  .storybook/preview.js
  src/components/Office/TXOTabNav/TXOTabNav.jsx
  src/components/Office/TXOTabNav/TXOTabNav.stories.jsx
  src/components/Office/TXOTabNav/TXOTabNav.test.jsx
  src/pages/Office/MoveDetails/MoveDetails.jsx
  src/pages/Office/MovePaymentRequests/MovePaymentRequests.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.test.jsx
  src/pages/Office/TXOMoveInfo/TXOMoveInfo.jsx
  src/pages/Office/TXOMoveInfo/TXOMoveInfo.test.jsx
  src/pages/Office/TXOMoveInfo/TXOTab.module.scss
  src/utils/handleScroll.js
  src/utils/handleScroll.test.js
Labels: ttv

#7260 MB-7234 Removing fields from WebhookNotification payload
  cmd/webhook-client/webhook/payloads.go
Labels: roci

#7252 MB-9092 Allow TOO to acknowledge excess weight
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20210824170712_add_excess_weight_acknowledged_at_to_moves.up.sql
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/ghcapi/ghcoperations/order/acknowledge_excess_weight_risk.go
  pkg/gen/ghcapi/ghcoperations/order/acknowledge_excess_weight_risk_parameters.go
  pkg/gen/ghcapi/ghcoperations/order/acknowledge_excess_weight_risk_responses.go
  pkg/gen/ghcapi/ghcoperations/order/acknowledge_excess_weight_risk_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/order/update_billable_weight.go
  pkg/gen/ghcapi/ghcoperations/order/update_billable_weight_parameters.go
  pkg/gen/ghcapi/ghcoperations/order/update_billable_weight_responses.go
  pkg/gen/ghcapi/ghcoperations/order/update_billable_weight_urlbuilder.go
  pkg/gen/ghcmessages/move.go
  pkg/gen/ghcmessages/update_billable_weight_payload.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/orders.go
  pkg/handlers/ghcapi/orders_test.go
  pkg/handlers/internalapi/api.go
  pkg/models/move.go
  pkg/services/event/ghc_endpoint.go
  pkg/services/mocks/ExcessWeightRiskManager.go
  pkg/services/order.go
  pkg/services/order/excess_weight_risk_manager.go
  pkg/services/order/excess_weight_risk_manager_test.go
  pkg/testdatagen/scenario/shared.go
  src/pages/Office/MoveDetails/MoveDetails.jsx
  src/pages/Office/MoveDetails/MoveDetails.test.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
  src/services/ghcApi.js
  swagger/ghc.yaml
Labels: ttv

#7236 MB-7285 e2e test coverage for Enabling Crating & Shuttling
  cypress/integration/office/txo/tioFlows.js
  pkg/testdatagen/scenario/e2ebasic.go
  src/components/Office/ServiceItemCalculations/serviceItemTestParams.js
Labels: ttv

#7245 MB-9263 integrate components into payment requests page
  src/components/Office/BillableWeight/BillableWeightCard/BillableWeightCard.jsx
  src/components/Office/BillableWeight/BillableWeightCard/BillableWeightCard.module.scss
  src/components/Office/BillableWeight/BillableWeightCard/BillableWeightCard.stories.jsx
  src/components/Office/BillableWeight/BillableWeightCard/BillableWeightCard.test.jsx
  src/components/ShipmentList/index.jsx
  src/components/ShipmentTag/ShipmentTag.module.scss
  src/constants/routes.js
  src/constants/shipments.js
  src/hooks/queries.js
  src/pages/Office/MovePaymentRequests/MovePaymentRequests.jsx
  src/pages/Office/MovePaymentRequests/MovePaymentRequests.test.jsx
  src/pages/Office/TXOMoveInfo/TXOMoveInfo.jsx
Labels: Voltron

#7242 MB-9241: Clean up miscellaneous console messages
  src/layout/LogoutOnInactivity.test.jsx
  src/services/swaggerRequest.test.js
  src/utils/formatters.test.js
Labels: Pamplemoose

#7270 Updating versions of pre-commit hooks
  .pre-commit-config.yaml
Labels: A-Team
