Repository transcom/mymove, pull requests merged in 2021-05, with the labels that each got.

#6542 [MB-7733] Generalize office tables into definition lists and a DetailsPanel wrapper component
  src/components/Office/AllowancesTable/AllowancesTable.jsx
  src/components/Office/AllowancesTable/AllowancesTable.stories.jsx
  src/components/Office/AllowancesTable/AllowancesTable.test.jsx
  src/components/Office/CustomerInfo.jsx
  src/components/Office/CustomerInfoTable.jsx
  src/components/Office/CustomerInfoTable.test.jsx
  src/components/Office/DefinitionLists/AllowancesList.jsx
  src/components/Office/DefinitionLists/AllowancesList.stories.jsx
  src/components/Office/DefinitionLists/AllowancesList.test.jsx
  src/components/Office/DefinitionLists/CustomerInfoList.jsx
  src/components/Office/DefinitionLists/CustomerInfoList.stories.jsx
  src/components/Office/DefinitionLists/CustomerInfoList.test.jsx
  src/components/Office/DefinitionLists/OfficeDefinitionLists.module.scss
  src/components/Office/DefinitionLists/OrdersList.jsx
  src/components/Office/DefinitionLists/OrdersList.stories.jsx
  src/components/Office/DefinitionLists/OrdersList.test.jsx
  src/components/Office/DetailsPanel/DetailsPanel.jsx
  src/components/Office/DetailsPanel/DetailsPanel.module.scss
  src/components/Office/DetailsPanel/DetailsPanel.stories.jsx
  src/components/Office/DetailsPanel/DetailsPanel.test.jsx
  src/components/Office/DetailsTable/DetailsTable.jsx
  src/components/Office/DetailsTable/DetailsTable.module.scss
  src/components/Office/OrdersTable/OrdersTable.jsx
  src/components/Office/OrdersTable/OrdersTable.test.jsx
  src/components/Office/ShipmentApprovalPreview.jsx
  src/components/Office/ShipmentApprovalPreview.test.jsx
  src/pages/Office/MoveDetails/MoveDetails.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
  src/utils/branchRankFormatters.js
  src/utils/branchRankFormatters.test.js
Labels: ttv

#6560 [MB-8034] Fix remaining lint errors in pkg directory
  pkg/auth/authentication/auth_test.go
  pkg/auth/authentication/login_gov.go
  pkg/certs/certs_test.go
  pkg/cli/cli_test.go
  pkg/handlers/adminapi/api_test.go
  pkg/handlers/ghcapi/api_test.go
  pkg/handlers/internalapi/api_test.go
  pkg/handlers/internalapi/backup_contacts.go
  pkg/handlers/internalapi/backup_contacts_test.go
  pkg/handlers/internalapi/generic_move_documents.go
  pkg/handlers/internalapi/generic_move_documents_test.go
  pkg/handlers/internalapi/move_documents.go
  pkg/handlers/internalapi/move_documents_test.go
  pkg/handlers/internalapi/moves.go
  pkg/handlers/internalapi/moving_expense_documents.go
  pkg/handlers/internalapi/moving_expense_documents_test.go
  pkg/handlers/internalapi/office.go
  pkg/handlers/internalapi/orders.go
  pkg/handlers/internalapi/personally_procured_move.go
  pkg/handlers/internalapi/personally_procured_move_attachments.go
  pkg/handlers/internalapi/personally_procured_move_attachments_test.go
  pkg/handlers/internalapi/weight_ticket_set_documents.go
  pkg/handlers/primeapi/api_test.go
  pkg/handlers/supportapi/api_test.go
  pkg/migrate/SplitStatements_test.go
  pkg/models/reimbursement_test.go
  pkg/models/upload_test.go
  pkg/models/user_test.go
  pkg/paperwork/forms_test.go
  pkg/paperwork/generator_test.go
  pkg/paperwork/paperwork_test.go
  pkg/parser/pricing/parse_test.go
  pkg/payment_request/service_param_value_lookups/distance_zip5_lookup_test.go
  pkg/services/dbtools/table_from_slice_creator_test.go
  pkg/services/event/event_test.go
  pkg/services/invoice/ghc_payment_request_invoice_generator_test.go
  pkg/storage/storage.go
  pkg/testdatagen/shared.go
Labels: Pamplemoose

#6517 [MB-7545] Turn on ato-linter for BE
  .github/workflows/be-linter.yml
Labels: Pamplemoose

#6422 [MB-247] Refactor Header components
  cypress/integration/mymove/homepage.js
  cypress/integration/office/documentViewer.js
  cypress/integration/office/homepage.js
  src/components/MilMoveHeader/CustomerUserInfo.jsx
  src/components/MilMoveHeader/LoggedOutUserInfo.jsx
  src/components/MilMoveHeader/MilMoveHeader.stories.jsx
  src/components/MilMoveHeader/MilMoveHeader.test.jsx
  src/components/MilMoveHeader/OfficeUserInfo.jsx
  src/components/MilMoveHeader/index.jsx
  src/components/MilMoveHeader/index.module.scss
  src/containers/Headers/CustomerLoggedInHeader.jsx
  src/containers/Headers/CustomerLoggedInHeader.test.jsx
  src/containers/Headers/LoggedOutHeader.jsx
  src/containers/Headers/LoggedOutHeader.test.jsx
  src/containers/Headers/OfficeLoggedInHeader.jsx
  src/containers/Headers/OfficeLoggedInHeader.test.jsx
  src/pages/Office/index.jsx
  src/pages/Office/index.test.jsx
  src/pages/SignIn/SignIn.jsx
  src/scenes/MyMove/index.jsx
  src/scenes/MyMove/index.test.js
  src/scenes/Office/office.scss
  src/shared/Header/MyMove/index.jsx
  src/shared/Header/MyMove/index.scss
  src/shared/Header/Office/index.css
  src/shared/Header/Office/index.jsx
  src/shared/images/icon-dot-gov.svg
  src/shared/images/icon-https.svg
  src/shared/images/us-flag.png
  src/styles/customer.scss
Labels: Pamplemoose

#6532 MB-7718-improve-office-user-tests
  pkg/handlers/adminapi/office_users_test.go
Labels: roci

#6567 MB-8003-migration-cancel-and-diverted-shipment
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20210503211133_cancelled_and_diverted_statuses.up.sql
  pkg/models/mto_shipments.go
  pkg/models/mto_shipments_test.go
Labels: roci

#6575 [MB-7386] Add counselor remarks to MTO Shipment
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20210504104241_add_counselor_remarks_to_mto_shipments.up.sql
  pkg/models/mto_shipments.go
  pkg/testdatagen/make_mto_shipment.go
  pkg/testdatagen/scenario/devseed.go
Labels: Pamplemoose

#6570 [MB-7549] Add a way for the database to store information about which duty stations require services counseling
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20210504162959_add_provides_services_counseling.up.sql
  pkg/models/duty_station.go
Labels: A-Team

#6582 MB-7927 Services Counselor must confirm before submitting move
  src/components/Office/RequestShipmentCancellationModal/RequestShipmentCancellationModal.test.jsx
  src/components/Office/SubmitMoveConfirmationModal/SubmitMoveConfirmationModal.jsx
  src/components/Office/SubmitMoveConfirmationModal/SubmitMoveConfirmationModal.stories.jsx
  src/components/Office/SubmitMoveConfirmationModal/SubmitMoveConfirmationModal.test.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.test.jsx
Labels: ttv

#6533 MB-7957 fix bug that bails if one payment request send fails
  cmd/milmove-tasks/process_edis.go
  pkg/handlers/supportapi/payment_request.go
  pkg/services/mocks/PaymentRequestReviewedProcessor.go
  pkg/services/payment_request.go
  pkg/services/payment_request/payment_request_reviewed_processor.go
  pkg/services/payment_request/payment_request_reviewed_processor_test.go
Labels: A-Team

#6577 MB-7358 Add orders details for Services Counselor
  src/components/Office/DefinitionLists/ServicesCounselingOrdersList.jsx
  src/components/Office/DefinitionLists/ServicesCounselingOrdersList.test.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.test.jsx
Labels: ttv

#6586 [MB-7551] Populate the database with the duty stations that require services counseling
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20210505203801_populate_duty_station_services_counseling.up.sql
  pkg/testdatagen/scenario/devseed.go
Labels: A-Team

#6595 MB-3538 Switch from `Count` to `Exists` for ref ID uniqueness check
  pkg/models/move.go
Labels: Pamplemoose

#6576 MB-7684-diverted-shipments
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/create_m_t_o_shipment.go
  pkg/gen/primemessages/m_t_o_shipment.go
  pkg/gen/supportapi/embedded_spec.go
  pkg/gen/supportmessages/m_t_o_shipment.go
  pkg/gen/supportmessages/update_m_t_o_shipment_status.go
  pkg/handlers/primeapi/payloads/model_to_payload.go
  pkg/handlers/primeapi/payloads/payload_to_model.go
  pkg/services/mto_shipment/mto_shipment_updater.go
  pkg/services/mto_shipment/mto_shipment_updater_test.go
  swagger/prime.yaml
  swagger/support.yaml
Labels: roci

#6597 Fix openapi validation errors in load testing ghc parser
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/customer/get_customer_responses.go
  pkg/gen/ghcapi/ghcoperations/ghc_documents/get_document_responses.go
  pkg/gen/ghcapi/ghcoperations/move/get_move_responses.go
  pkg/gen/ghcapi/ghcoperations/move_task_order/delete_move_task_order_responses.go
  pkg/gen/ghcapi/ghcoperations/move_task_order/get_entitlements_responses.go
  pkg/gen/ghcapi/ghcoperations/move_task_order/get_move_task_order_responses.go
  pkg/gen/ghcapi/ghcoperations/move_task_order/update_m_t_o_status_service_counseling_completed_responses.go
  pkg/gen/ghcapi/ghcoperations/move_task_order/update_move_task_order_responses.go
  pkg/gen/ghcapi/ghcoperations/move_task_order/update_move_task_order_status_responses.go
  pkg/gen/ghcapi/ghcoperations/mto_agent/fetch_m_t_o_agent_list_responses.go
  pkg/gen/ghcapi/ghcoperations/mto_service_item/delete_m_t_o_service_item_responses.go
  pkg/gen/ghcapi/ghcoperations/mto_service_item/get_m_t_o_service_item_responses.go
  pkg/gen/ghcapi/ghcoperations/mto_service_item/list_m_t_o_service_items_responses.go
  pkg/gen/ghcapi/ghcoperations/mto_service_item/update_m_t_o_service_item_responses.go
  pkg/gen/ghcapi/ghcoperations/mto_service_item/update_m_t_o_service_item_status_responses.go
  pkg/gen/ghcapi/ghcoperations/mto_shipment/list_m_t_o_shipments_responses.go
  pkg/gen/ghcapi/ghcoperations/mto_shipment/patch_m_t_o_shipment_status_responses.go
  pkg/gen/ghcapi/ghcoperations/order/get_order_responses.go
  pkg/gen/ghcapi/ghcoperations/order/list_move_task_orders_responses.go
  pkg/gen/ghcapi/ghcoperations/order/update_order_responses.go
  pkg/gen/ghcapi/ghcoperations/payment_requests/get_payment_request_responses.go
  pkg/gen/ghcapi/ghcoperations/payment_requests/get_payment_requests_for_move_responses.go
  pkg/gen/ghcapi/ghcoperations/payment_requests/update_payment_request_status_responses.go
  pkg/gen/ghcapi/ghcoperations/payment_service_item/update_payment_service_item_status_responses.go
  pkg/gen/ghcapi/ghcoperations/queues/get_moves_queue_responses.go
  pkg/gen/ghcapi/ghcoperations/queues/get_payment_requests_queue_responses.go
  pkg/gen/ghcapi/ghcoperations/queues/get_services_counseling_queue_responses.go
  pkg/gen/ghcapi/ghcoperations/tac/tac_validation_responses.go
  pkg/handlers/ghcapi/mto_service_items.go
  pkg/handlers/ghcapi/payment_request.go
  pkg/handlers/ghcapi/payment_service_items.go
  swagger/ghc.yaml
Labels: ttv

#6602 MB-8073 Update Zap.Object names to make parsing logs easier
  pkg/services/invoice/syncada_sftp_reader.go
  pkg/services/payment_request/payment_request_reviewed_processor.go
Labels: A-Team

#6569 MB-7687 tio can see shipment details
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/m_t_o_shipment.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  src/components/Office/PaymentRequestCard/PaymentRequestCard.jsx
  src/components/Office/PaymentRequestCard/PaymentRequestCard.stories.jsx
  src/components/Office/PaymentRequestCard/PaymentRequestCard.test.jsx
  src/components/Office/PaymentRequestDetails/PaymentRequestDetails.jsx
  src/components/Office/PaymentRequestDetails/PaymentRequestDetails.module.scss
  src/components/Office/PaymentRequestDetails/PaymentRequestDetails.stories.jsx
  src/components/Office/PaymentRequestDetails/PaymentRequestDetails.test.jsx
  src/components/Office/ReviewServiceItems/ReviewServiceItems.stories.jsx
  src/components/Office/ReviewServiceItems/ServiceItemCard.jsx
  src/components/Office/ReviewServiceItems/ServiceItemCard.module.scss
  src/components/Office/ReviewServiceItems/ServiceItemCard.stories.jsx
  src/components/Office/ReviewServiceItems/ServiceItemCard.test.jsx
  src/hooks/queries.js
  src/hooks/queries.test.js
  src/pages/Office/MovePaymentRequests/MovePaymentRequests.jsx
  src/pages/Office/MovePaymentRequests/MovePaymentRequests.test.jsx
  src/pages/Office/PaymentRequestReview/PaymentRequestReview.jsx
  src/pages/Office/PaymentRequestReview/PaymentRequestReview.test.jsx
  src/utils/shipmentDisplay.jsx
  src/utils/shipmentDisplay.test.jsx
  swagger/ghc.yaml
Labels: roci

#6593 Fixed lint errors and enabled ato-linter in cmd directory
  .github/workflows/be-linter.yml
  cmd/milmove/main_test.go
  cmd/milmove/serve.go
Labels: needs-is3-review

#6616 Fix date format
  src/components/Office/ReviewServiceItems/ReviewServiceItems.stories.jsx
  src/components/Office/ReviewServiceItems/ServiceItemCard.jsx
  src/components/Office/ReviewServiceItems/ServiceItemCard.stories.jsx
Labels: roci

#6583 [MB-7550] route moves to services counseling
  .envrc
  config/env/exp.app.env
  config/env/prd.app.env
  config/env/review.app.env
  config/env/stg.app.env
  pkg/cli/featureflag.go
  pkg/handlers/internalapi/moves_test.go
  pkg/services/move/move_router.go
  pkg/services/move/move_router_test.go
Labels: A-Team

#6617 [MB-8087] Upgrade to go 1.16.4
  .circleci/config.yml
  .github/workflows/be-linter.yml
  .github/workflows/go-auto-approve.yml
  .pre-commit-config.yaml
  .tool-versions
  Dockerfile.local
  Dockerfile.migrations_local
  Dockerfile.reviewapp
  Dockerfile.tasks_local
  Dockerfile.tools_local
  Dockerfile.webhook_client
  Dockerfile.webhook_client_local
  Makefile
  cypress/Dockerfile.cypress
  cypress/support/index.js
  go.mod
  nix/default.nix
  pkg/services/mocks/SFTPClient.go
  scripts/check-go-version
  scripts/gen-assets
  scripts/gen-server
  scripts/pre-commit-swagger-validate
  scripts/prereqs
Labels: A-Team

#6615 [MB-7392] Add soft deletion indicator to MTO Shipments
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20210512164642_add_deleted_at_to_mto_shipments_table.up.sql
  pkg/models/mto_shipments.go
Labels: ttv

#6609 [MB-7926] Services Counselor can't update Authorized weight (backend)
  pkg/handlers/ghcapi/orders.go
  pkg/handlers/ghcapi/orders_test.go
Labels: ttv

#6603 MB-8054 trace id as response header
  pkg/middleware/context_logger.go
  pkg/middleware/trace.go
Labels: Pamplemoose

#6626 MB-8020 Bugfix: Change updateMTOShipment from PUT to PATCH
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/mto_shipment/update_m_t_o_shipment.go
  pkg/gen/primeapi/primeoperations/mymove_api.go
  pkg/gen/primeclient/mto_shipment/mto_shipment_client.go
  pkg/gen/primeclient/mto_shipment/update_m_t_o_shipment_responses.go
  pkg/handlers/primeapi/mto_shipment_test.go
  swagger/prime.yaml
Labels: roci

#6610 MB-7425 Bugfix - Omit empty customer contact fields for DDASIT, DDDSIT
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/mto_service_item/create_m_t_o_service_item.go
  pkg/gen/primeclient/mto_service_item/mto_service_item_client.go
  pkg/gen/primemessages/m_t_o_service_item_dest_s_i_t.go
  pkg/handlers/primeapi/mto_service_item.go
  pkg/handlers/primeapi/mto_service_item_test.go
  pkg/handlers/primeapi/payloads/model_to_payload.go
  pkg/handlers/primeapi/payloads/payload_to_model.go
  swagger/prime.yaml
Labels: roci

#6634 MB-8021 Explain shipment fields in Prime API documentation
  cmd/prime-api-dev/scripts/payment_requests.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/address.go
  pkg/gen/primemessages/create_m_t_o_shipment.go
  pkg/gen/primemessages/m_t_o_agent.go
  pkg/gen/primemessages/m_t_o_agent_type.go
  pkg/gen/primemessages/m_t_o_agents.go
  pkg/gen/primemessages/m_t_o_shipment.go
  pkg/gen/primemessages/m_t_o_shipment_type.go
  pkg/gen/primemessages/m_t_o_shipments.go
  pkg/gen/primemessages/update_m_t_o_shipment_status.go
  pkg/handlers/primeapi/mto_shipment_test.go
  pkg/handlers/primeapi/payloads/model_to_payload.go
  pkg/handlers/primeapi/payloads/payload_to_model.go
  swagger/prime.yaml
Labels: roci

#6621 MB-8077 Speed up models tests
  go.mod
  go.sum
  pkg/handlers/ordersapi/post_revision.go
  pkg/handlers/ordersapi/post_revision_to_orders.go
  pkg/handlers/primeapi/move_task_order_test.go
  pkg/models/address_test.go
  pkg/models/admin_user_test.go
  pkg/models/backup_contact_test.go
  pkg/models/distance_calculation_test.go
  pkg/models/document_test.go
  pkg/models/dps_users_test.go
  pkg/models/duty_station_test.go
  pkg/models/electronic_order.go
  pkg/models/electronic_order_test.go
  pkg/models/electronic_orders_revision.go
  pkg/models/electronic_orders_revision_test.go
  pkg/models/fuel_eia_diesel_price_test.go
  pkg/models/models_test.go
  pkg/models/move.go
  pkg/models/move_document_test.go
  pkg/models/move_test.go
  pkg/models/mto_agents_test.go
  pkg/models/order_test.go
  pkg/models/organization_test.go
  pkg/models/payment_request_to_interchange_control_number_test.go
  pkg/models/prime_upload_test.go
  pkg/models/queue_test.go
  pkg/models/reimbursement_test.go
  pkg/models/service_member_test.go
  pkg/models/tariff400ng_item_rate_test.go
  pkg/models/traffic_distribution_list_test.go
  pkg/models/transportation_service_provider_performance_test.go
  pkg/models/upload_test.go
  pkg/models/user_test.go
  pkg/models/user_upload_test.go
  pkg/models/webhook_notification_test.go
  pkg/notifications/move_approved_test.go
  pkg/services/move_task_order/move_task_order_fetcher_test.go
  pkg/services/mto_shipment/mto_shipment_updater_test.go
  pkg/testdatagen/make_address.go
  pkg/testdatagen/make_office_user.go
  pkg/testdatagen/make_payment_request.go
  pkg/testdatagen/make_service_member.go
  pkg/testdatagen/make_user.go
Labels: ttv

#6624 [MB-7254] Create randomized moves for services counseling in db dev seed
  pkg/fakedata_approved/fakedata_approved.go
  pkg/testdatagen/scenario/devseed.go
Labels: ttv

#6620 MB-7342 TIO can see shipment modification tag
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/m_t_o_shipment.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  src/components/Office/PaymentRequestCard/PaymentRequestCard.jsx
  src/components/Office/PaymentRequestCard/PaymentRequestCard.stories.jsx
  src/components/Office/PaymentRequestDetails/PaymentRequestDetails.jsx
  src/components/Office/PaymentRequestDetails/PaymentRequestDetails.module.scss
  src/components/Office/PaymentRequestDetails/PaymentRequestDetails.stories.jsx
  src/components/Office/PaymentRequestDetails/PaymentRequestDetails.test.jsx
  src/components/Office/ReviewServiceItems/ServiceItemCard.jsx
  src/components/Office/ReviewServiceItems/ServiceItemCard.module.scss
  src/components/Office/ReviewServiceItems/ServiceItemCard.stories.jsx
  src/components/Office/ReviewServiceItems/ServiceItemCard.test.jsx
  src/components/ShipmentModificationTag/ShipmentModificationTag.jsx
  src/components/ShipmentModificationTag/ShipmentModificationTag.module.scss
  src/components/ShipmentModificationTag/ShipmentModificationTag.stories.jsx
  src/components/ShipmentModificationTag/ShipmentModificationTag.test.jsx
  src/constants/shipments.js
  src/pages/Office/MovePaymentRequests/MovePaymentRequests.jsx
  src/pages/Office/PaymentRequestReview/PaymentRequestReview.jsx
  src/pages/Office/PaymentRequestReview/PaymentRequestReview.test.jsx
  src/utils/shipmentDisplay.jsx
  src/utils/shipmentDisplay.test.jsx
  swagger/ghc.yaml
Labels: roci

#6630 [MB-4004] Fix bugs in our custom SQL parser/splitter
  pkg/migrate/ReadInSQL.go
  pkg/migrate/SplitStatements.go
  pkg/migrate/SplitStatements_test.go
  pkg/migrate/fixtures/commentWithMultipleQuotes.sql
  pkg/migrate/fixtures/copyFromStdinQuotes.sql
  pkg/migrate/fixtures/copyFromStdinSemicolons.sql
Labels: A-Team

#6635 MB-8073 update payment request to interchange control number constraint
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20210514045435_update_payment_request_to_interchange_control_numbers_constraint.up.sql
  pkg/services/invoice/process_edi824.go
  pkg/services/invoice/process_edi997.go
  pkg/services/invoice/process_edi997_test.go
Labels: A-Team

#6631 MB-7950 add shipments to sc move details page
  src/components/Office/RequestedShipments/RequestedShipments.jsx
  src/components/Office/RequestedShipments/RequestedShipments.module.scss
  src/components/Office/ShipmentApprovalPreview.jsx
  src/components/Office/ShipmentDisplay/ShipmentDisplay.jsx
  src/constants/routes.js
  src/pages/Office/MoveDetails/MoveDetails.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.module.scss
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.test.jsx
  src/styles/shipmentCards.module.scss
Labels: Pamplemoose

#6647 MB-8135 updateMTOShipment won't blank out addresses
  pkg/handlers/primeapi/mto_shipment_test.go
  pkg/handlers/primeapi/payloads/payload_to_model.go
  pkg/services/mto_shipment/mto_shipment_updater.go
Labels: roci

#6596 MB-8053 open tracing adr
  .spelling
  docs/adr/0061-use-opentelemetry-for-distributed-tracing.md
  docs/adr/index.md
Labels: Pamplemoose

#6659 MB-8147 Update SC move details to default to dest duty station zip
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.test.jsx
Labels: Pamplemoose

#6654 [MB-7129] TOO cannot order Prime Counseling for a move with services counseling
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/move_task_order_test.go
  src/components/Office/RequestedShipments/RequestedShipments.jsx
  src/components/Office/RequestedShipments/RequestedShipments.module.scss
  src/components/Office/RequestedShipments/RequestedShipments.stories.jsx
  src/components/Office/RequestedShipments/RequestedShipments.test.jsx
Labels: ttv

#6662 MB-8022 MTOShipments - Improve null date display
  cmd/prime-api-dev/scripts/payment_requests.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/m_t_o_shipment.go
  pkg/handlers/primeapi/move_task_order.go
  pkg/handlers/primeapi/mto_shipment.go
  pkg/handlers/primeapi/mto_shipment_test.go
  pkg/handlers/primeapi/payloads/model_to_payload.go
  pkg/handlers/primeapi/payloads/payload_to_model.go
  swagger/prime.yaml
Labels: roci

#6658 MB-7388 Allow Counselor to soft delete shipment
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/move_task_order/delete_move_task_order.go
  pkg/gen/ghcapi/ghcoperations/move_task_order/delete_move_task_order_parameters.go
  pkg/gen/ghcapi/ghcoperations/move_task_order/delete_move_task_order_responses.go
  pkg/gen/ghcapi/ghcoperations/move_task_order/delete_move_task_order_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/mto_service_item/delete_m_t_o_service_item.go
  pkg/gen/ghcapi/ghcoperations/mto_service_item/delete_m_t_o_service_item_parameters.go
  pkg/gen/ghcapi/ghcoperations/mto_service_item/delete_m_t_o_service_item_responses.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/ghcapi/ghcoperations/shipment/delete_shipment.go
  pkg/gen/ghcapi/ghcoperations/shipment/delete_shipment_parameters.go
  pkg/gen/ghcapi/ghcoperations/shipment/delete_shipment_responses.go
  pkg/gen/ghcapi/ghcoperations/shipment/delete_shipment_urlbuilder.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/mto_shipment.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/services/event/event.go
  pkg/services/event/ghc_endpoint.go
  pkg/services/mocks/ShipmentDeleter.go
  pkg/services/mto_shipment.go
  pkg/services/mto_shipment/shipment_deleter.go
  pkg/services/mto_shipment/shipment_deleter_test.go
  pkg/testdatagen/make_mto_shipment.go
  swagger/ghc.yaml
Labels: ttv

#6660 [MB-8098] prevent GHC api handler from updating PR status to unapproved statuses
  pkg/handlers/ghcapi/payment_request.go
  pkg/handlers/ghcapi/payment_request_test.go
Labels: A-Team

#6611 MB-7387 services counselor is able to edit shipment details
  src/components/Customer/MtoShipmentForm/getShipmentOptions.js
  src/components/Office/ServicesCounselingShipmentForm/ServicesCounselingShipmentForm.jsx
  src/components/Office/ServicesCounselingShipmentForm/ServicesCounselingShipmentForm.module.scss
  src/components/Office/ServicesCounselingShipmentForm/ServicesCounselingShipmentForm.stories.jsx
  src/components/Office/ServicesCounselingShipmentForm/ServicesCounselingShipmentForm.test.jsx
  src/components/Office/ShipmentDisplay/ShipmentDisplay.jsx
  src/constants/routes.js
  src/hooks/queries.js
  src/hooks/queries.test.js
  src/pages/Office/ServicesCounselingEditShipmentDetails/ServicesCounselingEditShipmentDetails.jsx
  src/pages/Office/ServicesCounselingEditShipmentDetails/ServicesCounselingEditShipmentDetails.test.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.test.jsx
  src/pages/Office/index.jsx
  src/pages/Office/index.test.jsx
  src/services/ghcApi.js
  src/types/officeShapes.js
  src/utils/formatMtoShipment.js
Labels: Pamplemoose

#6669 [MB-8067] Load testing SC & TOO Move Details orders, shipments, and service item APIs
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/mto_service_item/list_m_t_o_service_items_responses.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/internal/payloads/notes
  pkg/handlers/ghcapi/mto_service_items.go
  pkg/handlers/ghcapi/mto_service_items_test.go
  pkg/handlers/ghcapi/queues_test.go
  swagger/ghc.yaml
Labels: ttv

#6667 [MB-7381] Services counselor can edit move contact info
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/customer.go
  pkg/gen/ghcmessages/update_customer_payload.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/internal/payloads/payload_to_model.go
  pkg/services/office_user/customer/customer_updater.go
  src/components/Office/CustomerContactInfoForm/CustomerContactInfoForm.jsx
  src/pages/Office/CustomerInfo/CustomerInfo.jsx
  src/pages/Office/CustomerInfo/CustomerInfo.module.scss
  src/pages/Office/CustomerInfo/CustomerInfo.test.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
  src/pages/Office/ServicesCounselingMoveInfo/ServicesCounselingMoveInfo.jsx
  src/services/ghcApi.js
  src/utils/formattedCustomerName.js
  src/utils/formattedCustomerName.test.js
  swagger/ghc.yaml
Labels: ttv

#6672 [MB-7596] Return error on nil OriginDutyStation
  pkg/services/move/move_router.go
  pkg/services/move/move_router_test.go
Labels: A-Team

#6608 MB-3171 Add endpoint for services counselor to edit an HHG shipment
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/mto_shipment/update_m_t_o_shipment.go
  pkg/gen/ghcapi/ghcoperations/mto_shipment/update_m_t_o_shipment_parameters.go
  pkg/gen/ghcapi/ghcoperations/mto_shipment/update_m_t_o_shipment_responses.go
  pkg/gen/ghcapi/ghcoperations/mto_shipment/update_m_t_o_shipment_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/ghcmessages/m_t_o_shipment.go
  pkg/gen/ghcmessages/update_shipment.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/internal/payloads/payload_to_model.go
  pkg/handlers/ghcapi/mto_shipment.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/services/event/ghc_endpoint.go
  pkg/services/mocks/MTOShipmentUpdater.go
  pkg/services/mto_shipment.go
  pkg/services/mto_shipment/mto_shipment_updater.go
  pkg/services/mto_shipment/mto_shipment_updater_test.go
  swagger/ghc.yaml
Labels: Pamplemoose

#6670 Roc MB-3173 counselor add shipment
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/mto_shipment/create_m_t_o_shipment.go
  pkg/gen/ghcapi/ghcoperations/mto_shipment/create_m_t_o_shipment_parameters.go
  pkg/gen/ghcapi/ghcoperations/mto_shipment/create_m_t_o_shipment_responses.go
  pkg/gen/ghcapi/ghcoperations/mto_shipment/create_m_t_o_shipment_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/ghcmessages/create_m_t_o_shipment.go
  pkg/gen/ghcmessages/m_t_o_shipment.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/m_t_o_shipment.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/internal/payloads/payload_to_model.go
  pkg/handlers/ghcapi/mto_shipment.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/handlers/ghcapi/queues_test.go
  pkg/handlers/primeapi/move_task_order_test.go
  pkg/handlers/primeapi/payloads/model_to_payload.go
  swagger/ghc.yaml
  swagger/prime.yaml
Labels: Pamplemoose

#6679 Revert "[MB-8067] Load testing SC & TOO Move Details orders, shipments, and service item APIs"
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/mto_service_item/list_m_t_o_service_items_responses.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/internal/payloads/notes
  pkg/handlers/ghcapi/mto_service_items.go
  pkg/handlers/ghcapi/mto_service_items_test.go
  pkg/handlers/ghcapi/queues_test.go
  swagger/ghc.yaml
Labels: ttv

#6685 MB-8050 Add link/button for services counselors to add an HHG shipment
  src/components/Office/ServicesCounselingShipmentForm/ServicesCounselingShipmentForm.jsx
  src/constants/routes.js
  src/pages/Office/CustomerInfo/CustomerInfo.jsx
  src/pages/Office/ServicesCounselingMoveAllowances/ServicesCounselingMoveAllowances.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.test.jsx
  src/pages/Office/ServicesCounselingMoveDocumentWrapper/ServicesCounselingMoveDocumentWrapper.jsx
  src/pages/Office/ServicesCounselingMoveInfo/ServicesCounselingMoveInfo.jsx
  src/pages/Office/ServicesCounselingOrders/ServicesCounselingOrders.jsx
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.jsx
  src/pages/Office/index.jsx
Labels: Pamplemoose

#6687 MB-8189 Update services counseling edit shipment URL
  src/constants/routes.js
  src/pages/Office/index.test.jsx
Labels: Pamplemoose

#6689 MB-8203 show existing agents
  src/components/Office/ServicesCounselingShipmentForm/ServicesCounselingShipmentForm.jsx
  src/components/Office/ServicesCounselingShipmentForm/ServicesCounselingShipmentForm.test.jsx
Labels: Pamplemoose

#6665 MB-8074 fix duplicate 997 processing
  cmd/milmove-tasks/process_edis.go
  pkg/services/invoice/process_edi997.go
  pkg/services/invoice/process_edi997_test.go
  pkg/services/invoice/syncada_sftp_reader.go
Labels: A-Team

#6698 MB-8236 Add ReDocly's OpenAPI CLI tool
  .redocly.yaml
  package.json
  swagger/index.html
  swagger/redoc/prime.html
  swagger/redoc/support.html
  yarn.lock
Labels: roci

#6558 MB-7989 Refactor MTOAgent validators
  pkg/services/errors.go
  pkg/services/mto_agent/mto_agent_creator.go
  pkg/services/mto_agent/mto_agent_creator_test.go
  pkg/services/mto_agent/mto_agent_updater.go
  pkg/services/mto_agent/mto_agent_updater_test.go
  pkg/services/mto_agent/mto_agent_validators.go
  pkg/services/mto_agent/mto_agent_validators_test.go
  pkg/services/mto_agent/validate/mto_agent_rules.go
  pkg/services/mto_agent/validate/mto_agent_rules_test.go
  pkg/services/mto_agent/validate/mto_agent_validate_service_test.go
  pkg/services/mto_agent/validate/mto_agent_validator.go
  pkg/services/mto_agent/validate/mto_agent_validator_test.go
  pkg/services/mto_service_item/mto_service_item_validators.go
  pkg/services/validation.go
Labels: roci

#6695 [MB-7971] Disable submit move when there are no shipments
  pkg/testdatagen/scenario/devseed.go
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.test.jsx
Labels: Pamplemoose

#6690 fix yaml for load testing
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/create_service_member_payload.go
  pkg/gen/internalmessages/patch_service_member_payload.go
  swagger/internal.yaml
Labels: A-Team

#6686 MB-7956 Update create item and crate with DCRT service item
  pkg/testdatagen/make_mto_service_item.go
  pkg/testdatagen/scenario/bandwidth.go
  pkg/testdatagen/scenario/devseed.go
  pkg/testdatagen/scenario/e2ebasic.go
  pkg/testdatagen/shared.go
Labels: roci

#6702 [MB-7535] Remove linter checks in dangerjs
  dangerfile.ts
Labels: Pamplemoose, needs-is3-review

#6699 [MB-8084] Services Counselor sees a success/fail message after editing move contact info
  src/pages/Office/CustomerInfo/CustomerInfo.jsx
  src/pages/Office/CustomerInfo/CustomerInfo.test.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.test.jsx
  src/pages/Office/ServicesCounselingMoveInfo/ServicesCounselingMoveInfo.jsx
  src/types/alert.js
Labels: ttv

#6707 [MB-3175] Services Counselor can delete/remove a shipment before submitting to the TOO (front-end)
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/m_t_o_shipment.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  src/components/Office/ServicesCounseling/SCRequestShipmentCancellationModal/SCRequestShipmentCancellationModal.jsx
  src/components/Office/ServicesCounseling/SCRequestShipmentCancellationModal/SCRequestShipmentCancellationModal.stories.jsx
  src/components/Office/ServicesCounseling/SCRequestShipmentCancellationModal/SCRequestShipmentCancellationModal.test.jsx
  src/components/Office/ServicesCounselingShipmentForm/ServicesCounselingShipmentForm.jsx
  src/components/Office/ServicesCounselingShipmentForm/ServicesCounselingShipmentForm.module.scss
  src/pages/Office/MoveDetails/MoveDetails.jsx
  src/pages/Office/MoveDetails/MoveDetails.test.jsx
  src/pages/Office/ServicesCounselingEditShipmentDetails/ServicesCounselingEditShipmentDetails.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
  src/services/ghcApi.js
  swagger/ghc.yaml
Labels: ttv

#6696 [MB-8071] Load testing updates for GHC api requests for modifying orders, allowances, and customers
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/backup_contact.go
  pkg/gen/ghcmessages/update_allowance_payload.go
  pkg/gen/ghcmessages/update_order_payload.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/internal/payloads/payload_to_model.go
  pkg/handlers/ghcapi/queues_test.go
  swagger/ghc.yaml
Labels: ttv

#6703 MB-8088 Cypress test services counselor flow
  cypress/integration/office/homepage.js
  cypress/integration/office/servicescounseling/servicesCounselingFlows.js
  cypress/support/commands.js
  cypress/support/constants.js
  pkg/testdatagen/scenario/devseed.go
  pkg/testdatagen/scenario/e2ebasic.go
  pkg/testdatagen/scenario/shared.go
Labels: ttv
