Repository transcom/mymove, pull requests merged in 2021-03, with the labels that each got.

#6016 MB-6579 Create show details page for web hook subscriptions
  cypress/integration/admin/moves.js
  cypress/integration/admin/webhookSubscriptions.js
  pkg/gen/adminapi/embedded_spec.go
  src/pages/Admin/WebhookSubscriptions/WebhookSubscriptionShow.jsx
  src/pages/Admin/WebhookSubscriptions/WebhookSubscriptionsList.jsx
  src/scenes/SystemAdmin/Home.jsx
  swagger/admin.yaml
Labels: roci

#6021 MB-5490 Backend changes for CANCELLATION_REQUESTED shipment status
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20210301215522_add_cancellation_requested_shipment_status.up.sql
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/mto_shipment/patch_m_t_o_shipment_status_parameters.go
  pkg/gen/ghcmessages/m_t_o_shipment.go
  pkg/gen/ghcmessages/m_t_o_shipment_status.go
  pkg/gen/ghcmessages/patch_m_t_o_shipment_status.go
  pkg/gen/ghcmessages/patch_m_t_o_shipment_status_payload.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/handlers/supportapi/mto_shipment_test.go
  pkg/models/mto_shipments.go
  pkg/models/mto_shipments_test.go
  pkg/services/mto_shipment/mto_shipment_updater.go
  pkg/services/mto_shipment/mto_shipment_updater_test.go
  swagger/ghc.yaml
Labels: roci

#6029 Em mb 6580 add create page round 2
  cypress/integration/admin/webhookSubscriptions.js
  src/pages/Admin/WebhookSubscriptions/WebhookSubscriptionCreate.jsx
  src/pages/Admin/WebhookSubscriptions/WebhookSubscriptionShow.jsx
  src/scenes/SystemAdmin/Home.jsx
  src/shared/constants.js
Labels: roci

#6005 Kim mb 6716 show tac validation warning
  pkg/handlers/ghcapi/api.go
  src/components/Office/OrdersDetailForm/OrdersDetailForm.jsx
  src/components/Office/OrdersDetailForm/OrdersDetailForm.test.jsx
  src/components/form/StackedTableRowForm.test.jsx
  src/components/form/fields/TextInput.jsx
  src/components/form/fields/TextInput.test.jsx
  src/pages/Office/MoveOrders/MoveOrders.jsx
  src/pages/Office/MoveOrders/MoveOrders.test.jsx
  src/services/ghcApi.js
Labels: Pamplemoose

#6037 Remove old automerge label from dependabot config
  .github/dependabot.yml
Labels: A-Team

#6035 [MB-6926] Update docker hash to match latest image
  .circleci/config.yml
  Dockerfile.local
  Dockerfile.migrations_local
  Dockerfile.tasks_local
  Dockerfile.tools_local
  cypress/Dockerfile.cypress
  docker-compose.circle.yml
  scripts/gen-assets
  scripts/gen-server
  scripts/pre-commit-swagger-validate
Labels: A-Team

#6030 [MB-6578] UpdateWebhookSubscription endpoint
  pkg/gen/adminapi/adminoperations/mymove_api.go
  pkg/gen/adminapi/adminoperations/webhook_subscriptions/update_webhook_subscription.go
  pkg/gen/adminapi/adminoperations/webhook_subscriptions/update_webhook_subscription_parameters.go
  pkg/gen/adminapi/adminoperations/webhook_subscriptions/update_webhook_subscription_responses.go
  pkg/gen/adminapi/adminoperations/webhook_subscriptions/update_webhook_subscription_urlbuilder.go
  pkg/gen/adminapi/configure_mymove.go
  pkg/gen/adminapi/embedded_spec.go
  pkg/gen/adminmessages/create_webhook_subscription.go
  pkg/gen/adminmessages/webhook_subscription.go
  pkg/handlers/adminapi/api.go
  pkg/handlers/adminapi/payloads/payload_to_model.go
  pkg/handlers/adminapi/webhook_subscriptions.go
  pkg/handlers/adminapi/webhook_subscriptions_test.go
  pkg/services/mocks/WebhookSubscriptionUpdater.go
  pkg/services/webhook_subscription.go
  pkg/services/webhook_subscription/webhook_subscription_fetcher.go
  pkg/services/webhook_subscription/webhook_subscription_updater.go
  pkg/services/webhook_subscription/webhook_subscription_updater_test.go
  swagger/admin.yaml
Labels: roci

#6031 MB-6935 Set access code flag in auth context
  cmd/milmove/serve.go
  pkg/auth/authentication/auth_test.go
Labels: bug, ttv

#6047 Regenerate yarn.lock after storybook updates
  yarn.lock
Labels: A-Team

#6020 MB-6917 Add PaymentServiceItemParams to GHC API
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/payment_request_test.go
  pkg/services/payment_request/payment_request_list_fetcher.go
  pkg/testdatagen/scenario/devseed.go
Labels: ttv

#6028 Kim mb 6520 tac format validation
  src/components/Office/OrdersDetailForm/OrdersDetailForm.jsx
  src/components/form/fields/TextInput.jsx
  src/pages/Office/MoveOrders/MoveOrders.jsx
  src/pages/Office/MoveOrders/MoveOrders.test.jsx
Labels: Pamplemoose

#6034 [MB-6909] Create AK1 EDI Segment for the 997 EDI Response
  pkg/edi/segment/ak1.go
  pkg/edi/segment/ak1_test.go
Labels: A-Team

#6052 MB 6520 Fix Crash For Trying To Validate Undefined TACs
  src/pages/Office/MoveOrders/MoveOrders.jsx
Labels: Pamplemoose

#6033 MB-6752 Admin UI: Add userId field to Admin & Office Users pages
  cypress/integration/admin/adminUsers.js
  cypress/integration/admin/officeUsers.js
  pkg/gen/adminapi/embedded_spec.go
  pkg/gen/adminmessages/office_user.go
  pkg/handlers/adminapi/office_users.go
  src/pages/Admin/.eslintrc
  src/pages/Admin/AdminUsers/AdminUserCreate.jsx
  src/pages/Admin/AdminUsers/AdminUserEdit.jsx
  src/pages/Admin/AdminUsers/AdminUserList.jsx
  src/pages/Admin/AdminUsers/AdminUserShow.jsx
  src/pages/Admin/Moves/MoveList.jsx
  src/pages/Admin/OfficeUsers/OfficeUserCreate.jsx
  src/pages/Admin/OfficeUsers/OfficeUserEdit.jsx
  src/pages/Admin/OfficeUsers/OfficeUserList.jsx
  src/pages/Admin/OfficeUsers/OfficeUserShow.jsx
  src/pages/Admin/Users/UserEdit.jsx
  src/scenes/SystemAdmin/Home.jsx
  swagger/admin.yaml
Labels: roci

#6057 [MB-6910] Created AK2 EDI segment
  pkg/edi/segment/ak2.go
  pkg/edi/segment/ak2_test.go
Labels: A-Team

#6059 MB-6931 Add request cancellation modal
  src/components/Office/RequestShipmentCancellationModal/RequestShipmentCancellationModal.jsx
  src/components/Office/RequestShipmentCancellationModal/RequestShipmentCancellationModal.stories.jsx
  src/components/Office/RequestShipmentCancellationModal/RequestShipmentCancellationModal.test.jsx
  src/shared/styles/_overrides.scss
  src/shared/styles/colors.scss
Labels: roci

#6050 MB-6620 make iampostpostgres tests less flaky
  pkg/cli/dbconn.go
  pkg/iampostgres/iampostgres.go
  pkg/iampostgres/iampostgres_test.go
Labels: Pamplemoose

#6036 MB-6901 Approve Move after TOO approves Shipment
  pkg/services/mto_service_item/mto_service_item_creator.go
  pkg/services/mto_service_item/mto_service_item_creator_test.go
  pkg/services/mto_shipment/mto_shipment_updater.go
  pkg/services/mto_shipment/mto_shipment_updater_test.go
Labels: ttv

#6061 Benchmarking tool save reports and break out naming by measurement
  .gitignore
  puppeteer/benchmarking.js
  puppeteer/constants.js
  puppeteer/scenarios.js
Labels: ttv

#6051 Mb-6535 fl update tac endpoint to use db
  pkg/handlers/ghcapi/tac.go
  pkg/handlers/ghcapi/tac_test.go
  pkg/models/transportation_accounting_code.go
  pkg/testdatagen/make_transportation_accounting_code.go
  pkg/testdatagen/shared.go
Labels: Pamplemoose

#6058 [MB-6926] Update node to 12.21.0 to match version in docker image
  .github/workflows/analyze-bundle.yml
  .github/workflows/happo-tests-master.yml
  .github/workflows/happo-tests.yml
  .node-version
  .pre-commit-config.yaml
  README.md
  scripts/prereqs
Labels: A-Team

#6032 Use inmemory filesystem for postgres test db
  Makefile
Labels: A-Team

#6077 [MB-6921] Write scheduled task to connect to GEX via SFTP to verify connection
  cmd/milmove-tasks/connect_to_gex_via_sftp.go
  cmd/milmove-tasks/main.go
  pkg/services/invoice/syncada_sftp_sender.go
Labels: A-Team

#6023 Collect coverage report in circleci server_test job
  .circleci/config.yml
  Makefile
  scripts/run-server-test
  scripts/run-server-test-in-circle-container
Labels: A-Team

#6084 [MB-6913] Adding segment for AK5
  pkg/edi/segment/ak5.go
  pkg/edi/segment/ak5_test.go
Labels: A-Team

#6079 MB-6928 Get ServiceItemParams for payment request
  pkg/handlers/ghcapi/payment_request_test.go
  pkg/services/payment_request/payment_request_fetcher.go
Labels: ttv

#6083 MB-6930 Add 'Request Cancellation' Button to MTO page
  cypress/integration/office/txo/tooFlows.js
  src/components/Office/ShipmentHeading.jsx
  src/components/Office/shipmentHeading.module.scss
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
  src/shared/constants.js
Labels: roci

#6094 [MB-6949] Add BGN EDI segment and tests
  pkg/edi/segment/bgn.go
  pkg/edi/segment/bgn_test.go
Labels: A-Team

#6099 [MB-6950] Add OTI segment and tests
  pkg/edi/segment/oti.go
  pkg/edi/segment/oti_test.go
Labels: A-Team

#6100 [MB-6951] Add TED segment and tests
  pkg/edi/segment/ted.go
  pkg/edi/segment/ted_test.go
Labels: A-Team

#6082 [MB-3498] Adds the LeftNav component w/ shipments to the Move Task Order page
  src/components/LeftNav/index.module.scss
  src/components/Office/RejectServiceItemModal/RejectServiceItemModal.jsx
  src/components/Office/RejectServiceItemModal/RejectServiceItemModal.test.jsx
  src/components/Office/RequestedServiceItemsTable/RequestedServiceItemsTable.jsx
  src/components/Office/RequestedServiceItemsTable/RequestedServiceItemsTable.test.jsx
  src/components/ServiceItemTableHasImg/index.jsx
  src/components/ServiceItemTableHasImg/index.test.jsx
  src/constants/moves.js
  src/constants/serviceItems.js
  src/constants/shipments.js
  src/content/shipments.js
  src/hooks/queries.js
  src/hooks/queries.test.js
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.test.jsx
Labels: ttv

#6067 [MB-6911] create AK3 EDI segment
  pkg/edi/segment/ak3.go
  pkg/edi/segment/ak3_test.go
Labels: A-Team

#6106 MB-7007 Update configuration of auto-approve plugin
  .github/workflows/auto-approve.yml
  .github/workflows/go-auto-approve.yml
Labels: A-Team

#6101 [MB-6914] Create AK9 EDI segment
  pkg/edi/segment/ak9.go
  pkg/edi/segment/ak9_test.go
Labels: A-Team

#6113 [MB-7068] fix typo in AK3 test
  pkg/edi/segment/ak3_test.go
Labels: A-Team

#6097 Kim mb 6449 home page header fields from orders
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/orders.go
  pkg/handlers/internalapi/orders.go
  pkg/handlers/internalapi/orders_test.go
  pkg/models/order.go
  pkg/models/order_test.go
  pkg/models/service_member.go
  pkg/models/service_member_test.go
  src/pages/MyMove/Home/index.jsx
  swagger/internal.yaml
Labels: Pamplemoose

#6112 MB-7007 Upgrade circleci-docker based images to latest version
  Dockerfile.local
  Dockerfile.migrations_local
  Dockerfile.tasks_local
  Dockerfile.tools_local
  Dockerfile.webhook_client
  Dockerfile.webhook_client_local
  Makefile
  cypress/Dockerfile.cypress
  docker-compose.circle.yml
  scripts/gen-assets
  scripts/gen-server
  scripts/pre-commit-swagger-validate
Labels: A-Team

#6095 [MB-6594] TOO sees missing info indicator on Move Details left nav
  pkg/testdatagen/scenario/devseed.go
  src/components/LeftNav/LeftNav.stories.jsx
  src/components/Office/AllowancesTable/AllowancesTable.jsx
  src/components/Office/CustomerInfoTable.jsx
  src/components/Office/MoveDetailTable.module.scss
  src/components/Office/OrdersTable/OrdersTable.jsx
  src/components/Office/OrdersTable/OrdersTable.module.scss
  src/components/Office/OrdersTable/OrdersTable.stories.jsx
  src/components/Office/OrdersTable/OrdersTable.test.jsx
  src/pages/Office/MoveDetails/MoveDetails.jsx
  src/pages/Office/MoveDetails/MoveDetails.test.jsx
  src/shared/formatters.js
Labels: ttv

#6102 MB-6843 Storybook service item calculations
  src/components/Office/ServiceItemCalculations/ServiceItemCalculations.jsx
  src/components/Office/ServiceItemCalculations/ServiceItemCalculations.module.scss
  src/components/Office/ServiceItemCalculations/ServiceItemCalculations.stories.jsx
  src/components/Office/ServiceItemCalculations/ServiceItemCalculations.test.jsx
  src/icons.js
Labels: ttv

#6096 MB-5501-cancel-shipment
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/m_t_o_shipment.go
  pkg/gen/supportapi/embedded_spec.go
  pkg/gen/supportmessages/update_m_t_o_shipment_status.go
  pkg/handlers/supportapi/mto_shipment_test.go
  swagger/prime.yaml
  swagger/support.yaml
Labels: roci

#6115 [MB-6908] As the Job Runner, I want a new MilMove Task so I can run asynchronously
  cmd/milmove-tasks/main.go
  cmd/milmove-tasks/process_edis.go
  pkg/services/payment_request/payment_request_reviewed_processor.go
Labels: A-Team

#6080 MB-6838 disable fields on edit profile after move submitted
  pkg/handlers/internalapi/service_members.go
  pkg/handlers/internalapi/service_members_test.go
  src/components/Customer/Review/ServiceInfoTable/ServiceInfoTable.module.scss
  src/components/Customer/Review/ServiceInfoTable/index.jsx
  src/components/Customer/Review/ServiceInfoTable/index.stories.jsx
  src/scenes/Review/EditProfile.jsx
  src/store/entities/selectors.js
Labels: Pamplemoose

#6105 MB-4667 Update SM duty station when TOO updates order origin duty station
  pkg/services/order/order_updater.go
  pkg/services/order/order_updater_test.go
Labels: Pamplemoose

#6103 [MB-6182] Customer can edit duty station and rank and it reflects on TOO interface
  cypress/integration/office/officeUserPPM.js
  pkg/handlers/internalapi/orders.go
  pkg/handlers/internalapi/service_members.go
  pkg/handlers/internalapi/service_members_test.go
  pkg/models/order.go
  pkg/models/service_member.go
  src/scenes/Office/OrdersPanel.jsx
Labels: Pamplemoose

#6118 MB-6932 Add shipment cancellation alert to TXO Move Task Order page
  src/components/Office/ShipmentContainer.jsx
  src/components/Office/ShipmentHeading.jsx
  src/components/Office/ShipmentHeading.test.jsx
  src/containers/FlashGridContainer/FlashGridContainer.jsx
  src/containers/FlashGridContainer/FlashGridContainer.test.jsx
  src/containers/FlashMessage/FlashMessage.jsx
  src/containers/FlashMessage/FlashMessage.test.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.test.jsx
  src/pages/Office/TXOMoveInfo/TXOTab.module.scss
  src/store/flash/actions.js
  src/store/flash/actions.test.js
  src/store/flash/reducer.js
  src/store/flash/reducer.test.js
Labels: roci, ttv

#6128 Fix broken service member test
  pkg/handlers/internalapi/service_members_test.go
Labels: Pamplemoose

#6092 [MB-6904] lock rows for job runner
  pkg/services/mocks/PaymentRequestReviewedProcessor.go
  pkg/services/payment_request.go
  pkg/services/payment_request/payment_request_reviewed_processor.go
  pkg/services/payment_request/payment_request_reviewed_processor_test.go
Labels: A-Team

#6126 [MB-7074] Improve logging for webhook-client
  cmd/webhook-client/webhook/webhook.go
  config/env/exp.app-webhook-client.env
Labels: roci

#6137 Add calls to clearAllCookies to avoid Cypress timeout
  cypress/integration/admin/webhookSubscriptions.js
  cypress/integration/office/officeUserPPM.js
Labels: A-Team

#6117 [MB-6915] Parse EDI 997
  pkg/edi/edi997/edi.go
  pkg/edi/edi997/logger.go
  pkg/edi/edi997/parser.go
  pkg/edi/edi997/parser_test.go
  pkg/edi/segment/ak3.go
  pkg/edi/segment/ak3_test.go
  pkg/edi/segment/ak5.go
  pkg/edi/segment/ak5_test.go
  pkg/edi/segment/ak9.go
Labels: A-Team

#6104 [MB-6663] Update BX04 to use payment request number
  pkg/services/invoice/ghc_payment_request_invoice_generator.go
  pkg/services/invoice/ghc_payment_request_invoice_generator_test.go
Labels: A-Team

#6157 MB-7173 Update FlashMessage to only set heading attr if title is not empty
  src/containers/FlashMessage/FlashMessage.jsx
Labels: roci

#6151 [MB-6422] Rank and Duty station should read from the Orders table on the Review page
  src/components/Customer/Review/Summary/index.jsx
  src/components/Customer/Review/Summary/index.test.jsx
  src/scenes/Review/EditProfile.jsx
Labels: Pamplemoose

#6152 [MB-7065] DangerJS allow eslint-disable with rules
  dangerfile.ts
  package.json
Labels: Pamplemoose

#6116 MB-3799 notifications system should shutdown gracefully
  cmd/webhook-client/webhook/webhook.go
  cmd/webhook-client/webhook_notify.go
  go.mod
  go.sum
Labels: roci

#6144 MB-7097 Admin API: Add optimistic locking to Webhook Subscriptions
  pkg/gen/adminapi/adminoperations/webhook_subscriptions/update_webhook_subscription_parameters.go
  pkg/gen/adminapi/adminoperations/webhook_subscriptions/update_webhook_subscription_responses.go
  pkg/gen/adminapi/embedded_spec.go
  pkg/gen/adminmessages/webhook_subscription.go
  pkg/handlers/adminapi/payloads/model_to_payload.go
  pkg/handlers/adminapi/payloads/payload_to_model.go
  pkg/handlers/adminapi/webhook_subscriptions.go
  pkg/handlers/adminapi/webhook_subscriptions_test.go
  pkg/services/mocks/WebhookSubscriptionUpdater.go
  pkg/services/webhook_subscription.go
  pkg/services/webhook_subscription/webhook_subscription_updater.go
  pkg/services/webhook_subscription/webhook_subscription_updater_test.go
  src/scenes/SystemAdmin/Home.jsx
  src/scenes/SystemAdmin/shared/rest_provider.js
  swagger/admin.yaml
Labels: roci

#6141 [MB-4745] Add payment requests needing approval count to Payment requests tab
  src/constants/paymentRequestStatus.js
  src/pages/Office/MovePaymentRequests/MovePaymentRequests.jsx
  src/pages/Office/MovePaymentRequests/MovePaymentRequests.test.jsx
  src/pages/Office/TXOMoveInfo/TXOMoveInfo.jsx
Labels: ttv

#6159 MB-6581-add-webhook-subscription-page
  cypress/integration/admin/webhookSubscriptions.js
  src/pages/Admin/WebhookSubscriptions/WebhookSubscriptionEdit.jsx
  src/scenes/SystemAdmin/Home.jsx
Labels: roci

#6162 MB-7022 create storybook component for backup contact
  src/components/form/BackupContactInfoFields/BackupContactInfoFields.stories.jsx
  src/components/form/BackupContactInfoFields/BackupContactInfoFields.test.jsx
  src/components/form/BackupContactInfoFields/index.jsx
Labels: Pamplemoose

#6131 MB-6840 Update SM Affiliation/Rank when Order Branch/Grade are updated
  pkg/services/order/order_updater.go
  pkg/services/order/order_updater_test.go
Labels: Pamplemoose

#6172 Webhook subscription edit page: make name a string
  src/pages/Admin/WebhookSubscriptions/WebhookSubscriptionEdit.jsx
Labels: roci

#6138 [MB-4741] Updates unapproved service item tag count navbar on move details and mto pages
  cypress/integration/office/txo/tooFlows.js
  pkg/testdatagen/scenario/devseed.go
  src/components/Office/PaymentRequestCard/PaymentRequestCard.jsx
  src/components/Office/RequestedShipments/RequestedShipments.jsx
  src/constants/moves.js
  src/hooks/queries.js
  src/hooks/queries.test.js
  src/pages/Office/MoveDetails/MoveDetails.jsx
  src/pages/Office/MoveDetails/MoveDetails.test.jsx
  src/pages/Office/MovePaymentRequests/MovePaymentRequests.jsx
  src/pages/Office/MovePaymentRequests/MovePaymentRequests.test.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.test.jsx
  src/pages/Office/TXOMoveInfo/TXOMoveInfo.jsx
  yarn.lock
Labels: ttv

#6153 [MB-6946] Create new model and table for EDI response processing info
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20210318162232_create_edi_processing_table.up.sql
  pkg/models/edi_processing.go
  pkg/models/edi_processing_test.go
Labels: A-Team

#6142 [MB-4740] TOO cannot approve Move without updating Orders information
  pkg/testdatagen/make_order.go
  pkg/testdatagen/scenario/devseed.go
  src/components/Office/RequestedShipments/RequestedShipments.jsx
  src/components/Office/RequestedShipments/RequestedShipments.test.jsx
  src/pages/Office/MoveDetails/MoveDetails.jsx
  src/pages/Office/MoveDetails/MoveDetails.test.jsx
Labels: ttv

#6160 MB-6933 Hook up Request Cancellation button to modal and alert
  cypress/integration/office/txo/tooFlows.js
  src/components/Office/RequestShipmentCancellationModal/RequestShipmentCancellationModal.jsx
  src/components/Office/RequestShipmentCancellationModal/RequestShipmentCancellationModal.test.jsx
  src/components/Office/ShipmentHeading.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.test.jsx
  src/shared/constants.js
Labels: roci

#6145 MB-7019 create storybook component for contact info fieldset
  src/components/form/ServiceMemberContactInfoFields/ServiceMemberContactInfoFields.stories.jsx
  src/components/form/ServiceMemberContactInfoFields/ServiceMemberContactInfoFields.test.jsx
  src/components/form/ServiceMemberContactInfoFields/index.jsx
  src/components/form/fields/CheckboxField.jsx
  src/components/form/fields/CheckboxField.test.jsx
Labels: Pamplemoose

#6170 Refactored Syncada SFTP client config
  cmd/fetch-from-syncada-via-sftp/main.go
  pkg/cli/syncada_sftp.go
  pkg/cli/syncada_sftp_test.go
  pkg/services/invoice.go
  pkg/services/mocks/SFTPClient.go
  pkg/services/mocks/SFTPFile.go
  pkg/services/mocks/SyncadaFileProcessor.go
  pkg/services/mocks/SyncadaSFTPReader.go
Labels: A-Team

#6168 [MB-6664] Replace the GCN with the ICN
  pkg/edi/invoice/generator_test.go
  pkg/services/invoice/ghc_payment_request_invoice_generator.go
  pkg/services/invoice/ghc_payment_request_invoice_generator_test.go
Labels: A-Team

#6171 MB-7015 Prevent Move approval if Order is invalid
  cypress/integration/admin/webhookSubscriptions.js
  cypress/integration/office/officeUserPPM.js
  cypress/integration/office/txo/tooFlows.js
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/move_task_order/update_move_task_order_responses.go
  pkg/gen/ghcapi/ghcoperations/move_task_order/update_move_task_order_status_responses.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/ghcapi/ghcoperations/order/get_order.go
  pkg/gen/ghcapi/ghcoperations/order/get_order_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/order/list_move_task_orders.go
  pkg/gen/ghcapi/ghcoperations/order/list_move_task_orders_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/order/update_order.go
  pkg/gen/ghcapi/ghcoperations/order/update_order_responses.go
  pkg/gen/ghcapi/ghcoperations/order/update_order_urlbuilder.go
  pkg/handlers/ghcapi/move_task_order.go
  pkg/handlers/ghcapi/move_task_order_test.go
  pkg/handlers/ghcapi/order_test.go
  pkg/handlers/ghcapi/orders.go
  pkg/handlers/internalapi/orders_test.go
  pkg/handlers/supportapi/move_task_order_test.go
  pkg/models/move.go
  pkg/models/order.go
  pkg/models/order_test.go
  pkg/services/move_task_order/move_task_order_updater.go
  pkg/testdatagen/make_order.go
  pkg/testdatagen/scenario/devseed.go
  pkg/testdatagen/scenario/e2ebasic.go
  scripts/prime-api-demo
  swagger/ghc.yaml
Labels: ttv

#6180 MB-7098 Upgrade to golang 1.15.10
  .circleci/config.yml
  .tool-versions
  Dockerfile.local
  Dockerfile.migrations_local
  Dockerfile.tasks_local
  Dockerfile.tools_local
  Dockerfile.webhook_client
  Dockerfile.webhook_client_local
  Makefile
  cypress/Dockerfile.cypress
  scripts/gen-assets
  scripts/gen-server
  scripts/pre-commit-swagger-validate
  scripts/prereqs
Labels: A-Team

#6191 use pull_request_target
  .github/workflows/analyze-bundle.yml
Labels: A-Team

#6200 adding pull_request_target to 2 other flows useing GH secrets
  .github/workflows/auto-approve.yml
  .github/workflows/go-auto-approve.yml
Labels: A-Team

#6179 MB-5844 Update updateMTOServiceItem to use ID from path
  pkg/handlers/primeapi/mto_service_item.go
  pkg/handlers/primeapi/mto_service_item_test.go
  pkg/handlers/primeapi/payloads/payload_to_model.go
Labels: roci

#6229 [MB-7026] Parse EDI 824
  pkg/edi/edi824/edi.go
  pkg/edi/edi824/logger.go
  pkg/edi/edi824/parser.go
  pkg/edi/edi824/parser_test.go
Labels: A-Team

#6218 [MB-7053] Add domestic shorthaul support to service items calculator
  src/components/Office/ServiceItemCalculations/ServiceItemCalculations.stories.jsx
  src/components/Office/ServiceItemCalculations/helpers.js
  src/constants/serviceItems.js
Labels: ttv

#6216 Add domestic packing
  src/components/Office/ServiceItemCalculations/ServiceItemCalculations.stories.jsx
  src/components/Office/ServiceItemCalculations/ServiceItemCalculations.test.jsx
  src/components/Office/ServiceItemCalculations/helpers.js
  src/components/Office/ServiceItemCalculations/helpers.test.js
  src/components/Office/ServiceItemCalculations/serviceItemTestParams.js
  src/constants/serviceItems.js
Labels: ttv

#6230 [MB-7056] DOFSIT payment service item calculations
  src/components/Office/ServiceItemCalculations/ServiceItemCalculations.stories.jsx
  src/components/Office/ServiceItemCalculations/ServiceItemCalculations.test.jsx
  src/components/Office/ServiceItemCalculations/helpers.js
  src/components/Office/ServiceItemCalculations/helpers.test.js
  src/components/Office/ServiceItemCalculations/serviceItemTestParams.js
  src/constants/serviceItems.js
Labels: ttv

#6220 MB-7058 Pricing details domestic origin addl sit
  src/components/Office/ServiceItemCalculations/ServiceItemCalculations.stories.jsx
  src/components/Office/ServiceItemCalculations/ServiceItemCalculations.test.jsx
  src/components/Office/ServiceItemCalculations/helpers.js
  src/components/Office/ServiceItemCalculations/helpers.test.js
  src/components/Office/ServiceItemCalculations/serviceItemTestParams.js
  src/constants/serviceItems.js
Labels: ttv

#6223 MB-6665 migration model for saving ICN
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20210323204715_add_payment_request_to_interchange_control_number.up.sql
  pkg/models/payment_request_to_interchange_control_number.go
  pkg/models/payment_request_to_interchange_control_number_test.go
  pkg/services/invoice/ghc_payment_request_invoice_generator.go
  pkg/services/invoice/ghc_payment_request_invoice_generator_test.go
  pkg/testdatagen/make_payment_request_to_interchange_control_number.go
  pkg/testdatagen/shared.go
Labels: A-Team

#6163 [MB-6905, MB-6945] Add service to read files from Syncada via SFTP
  Makefile
  cmd/fetch-from-syncada-via-sftp/logger.go
  cmd/fetch-from-syncada-via-sftp/main.go
  pkg/cli/syncada_sftp.go
  pkg/cli/syncada_sftp_test.go
  pkg/services/invoice.go
  pkg/services/invoice/sftp_client_wrapper.go
  pkg/services/invoice/syncada_sftp_reader.go
  pkg/services/invoice/syncada_sftp_reader_test.go
  pkg/services/mocks/DomesticFuelSurchargePricer.go
  pkg/services/mocks/DomesticServiceAreaPricer.go
  pkg/services/mocks/SFTPClient.go
  pkg/services/mocks/SFTPFiler.go
  pkg/services/mocks/SyncadaFileProcessor.go
  pkg/services/mocks/SyncadaSFTPReader.go
Labels: A-Team

#6226 [MB-7054] TIO can see pricing details for Domestic origin price
  pkg/testdatagen/scenario/devseed.go
  src/components/Office/ServiceItemCalculations/ServiceItemCalculations.stories.jsx
  src/components/Office/ServiceItemCalculations/ServiceItemCalculations.test.jsx
  src/components/Office/ServiceItemCalculations/helpers.js
  src/components/Office/ServiceItemCalculations/helpers.test.js
  src/components/Office/ServiceItemCalculations/serviceItemTestParams.js
  src/constants/serviceItems.js
Labels: ttv

#6228 Mb 5319 fl update address fields to accept field validators
  src/components/form/AddressFields/AddressFields.jsx
  src/components/form/AddressFields/AddressFields.stories.jsx
  src/components/form/AddressFields/AddressFields.test.jsx
  src/components/form/fields/TextField.jsx
Labels: Pamplemoose

#6192 TTV base pricing details work
  cmd/generate-test-data/main.go
  pkg/testdatagen/scenario/devseed.go
  pkg/testdatagen/scenario/logger.go
  src/components/Office/ExpandableServiceItemRow/ExpandableServiceItemRow.jsx
  src/components/Office/ExpandableServiceItemRow/ExpandableServiceItemRow.module.scss
  src/components/Office/PaymentRequestDetails/PaymentRequestDetails.jsx
  src/components/Office/PaymentRequestDetails/PaymentRequestDetails.module.scss
  src/components/Office/ServiceItemCalculations/ServiceItemCalculations.jsx
  src/components/Office/ServiceItemCalculations/ServiceItemCalculations.stories.jsx
  src/components/Office/ServiceItemCalculations/ServiceItemCalculations.test.jsx
  src/components/Office/ServiceItemCalculations/helpers.js
  src/components/Office/ServiceItemCalculations/helpers.test.js
  src/components/Office/ServiceItemCalculations/serviceItemTestParams.js
  src/constants/serviceItems.js
  src/utils/formatters.js
  src/utils/formatters.test.js
Labels: ttv

#6241 Fixed copy/paste error in Management Services pricer test
  pkg/services/ghcrateengine/management_services_pricer_test.go
Labels: A-Team

#6250 MB-7327 Add y18n to resoultions to avoid high security warning
  package.json
  yarn.lock
Labels: A-Team

#6237 MB-3148 Add createMTOAgent endpoint to Prime API
  pkg/gen/primeapi/configure_mymove.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/mto_shipment/create_m_t_o_agent.go
  pkg/gen/primeapi/primeoperations/mto_shipment/create_m_t_o_agent_parameters.go
  pkg/gen/primeapi/primeoperations/mto_shipment/create_m_t_o_agent_responses.go
  pkg/gen/primeapi/primeoperations/mto_shipment/create_m_t_o_agent_urlbuilder.go
  pkg/gen/primeapi/primeoperations/mymove_api.go
  pkg/gen/primeclient/mto_shipment/create_m_t_o_agent_parameters.go
  pkg/gen/primeclient/mto_shipment/create_m_t_o_agent_responses.go
  pkg/gen/primeclient/mto_shipment/mto_shipment_client.go
  pkg/handlers/primeapi/api.go
  pkg/handlers/primeapi/mto_agent.go
  pkg/handlers/primeapi/mto_agent_test.go
  pkg/services/mto_agent.go
  pkg/services/mto_agent/mto_agent_creator.go
  pkg/services/mto_agent/mto_agent_creator_test.go
  pkg/services/mto_agent/mto_agent_validators.go
  swagger/prime.yaml
Labels: roci

#6249 Kim mb 5322 formik backup contact
  cypress/integration/mymove/serviceMemberProfile.js
  src/components/Customer/BackupContactForm/BackupContactForm.stories.jsx
  src/components/Customer/BackupContactForm/BackupContactForm.test.jsx
  src/components/Customer/BackupContactForm/index.jsx
  src/components/form/BackupContactInfoFields/BackupContactInfoFields.stories.jsx
  src/components/form/BackupContactInfoFields/BackupContactInfoFields.test.jsx
  src/components/form/BackupContactInfoFields/index.jsx
  src/components/form/CustomerContactInfoFields/index.jsx
  src/components/form/fields/MaskedTextField.jsx
  src/pages/MyMove/Profile/BackupContact.jsx
  src/pages/MyMove/Profile/BackupContact.test.jsx
  src/scenes/MyMove/getWorkflowRoutes.jsx
  src/scenes/ServiceMembers/BackupContact.css
  src/scenes/ServiceMembers/BackupContact.jsx
Labels: Pamplemoose

#6240 MB-5319 fl refactor res address page to use formik
  cypress/integration/mymove/serviceMemberProfile.js
  cypress/integration/mymove/utilities/customer.js
  src/components/Customer/ResidentialAddressForm/ResidentialAddressForm.jsx
  src/components/Customer/ResidentialAddressForm/ResidentialAddressForm.stories.jsx
  src/components/Customer/ResidentialAddressForm/ResidentialAddressForm.test.jsx
  src/pages/MyMove/Profile/ResidentialAddress.jsx
  src/pages/MyMove/Profile/ResidentialAddress.test.jsx
  src/scenes/MyMove/getWorkflowRoutes.jsx
  src/scenes/ServiceMembers/ResidentialAddress.jsx
  src/types/address.js
Labels: Pamplemoose

#6243 MB-5320 refactor sm backup address to use formik
  cypress/integration/mymove/serviceMemberProfile.js
  cypress/integration/mymove/utilities/customer.js
  src/components/Customer/BackupMailingAddressForm/BackupMailingAddressForm.jsx
  src/components/Customer/BackupMailingAddressForm/BackupMailingAddressForm.stories.jsx
  src/components/Customer/BackupMailingAddressForm/BackupMailingAddressForm.test.jsx
  src/pages/MyMove/Profile/BackupMailingAddress.jsx
  src/pages/MyMove/Profile/BackupMailingAddress.test.jsx
  src/scenes/MyMove/getWorkflowRoutes.jsx
  src/scenes/ServiceMembers/BackupMailingAddress.jsx
Labels: Pamplemoose

#6089 [MB-6947] EDI Error Tables Database Migration
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20210330000000_create-edi-errors-tables.up.sql
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/payment_request_status.go
  pkg/gen/ghcmessages/payment_service_item_status.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/payment_request_status.go
  pkg/gen/primemessages/payment_service_item_status.go
  pkg/models/edi_errors.go
  pkg/models/edi_errors_test.go
  pkg/models/payment_request.go
  pkg/models/payment_request_test.go
  pkg/models/payment_service_item.go
  pkg/models/payment_service_item_test.go
  pkg/models/validators.go
  swagger/ghc.yaml
  swagger/prime.yaml
Labels: A-Team
