Repository transcom/mymove, pull requests merged in 2022-04, with the labels that each got.

#8367 MB-11939 - Ignore columns in move history triggers
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20220331190115_create_move_history_triggers_with_ignored_columns.up.sql
Labels: Pamplemoose, ready-to-merge

#8368 MB-12098 Remove Column Name Column Value parsing from Payload
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/move_audit_history.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/move_history_test.go
  pkg/models/audit_history.go
  pkg/services/move_history/move_history_fetcher_test.go
  src/constants/historyLogUIDisplayName.js
  src/constants/historyLogUIDisplayName.test.js
  src/pages/Office/MoveHistory/MoveHistory.test.jsx
  src/pages/Office/MoveHistory/MoveHistoryDetailsSelector.jsx
  src/pages/Office/MoveHistory/MoveHistoryDetailsSelector.test.jsx
  src/pages/Office/MoveHistory/PlainTextDetails.jsx
  src/pages/Office/MoveHistory/PlainTextDetails.test.jsx
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: Pamplemoose

#8376 MB-11316 document when a too cancels a shipment
  src/constants/historyLogUIDisplayName.js
  src/constants/historyLogUIDisplayName.test.js
  src/pages/Office/MoveHistory/MoveHistoryDetailsSelector.jsx
  src/pages/Office/MoveHistory/MoveHistoryDetailsSelector.test.jsx
  src/pages/Office/MoveHistory/PlainTextDetails.jsx
  src/pages/Office/MoveHistory/PlainTextDetails.test.jsx
Labels: Pamplemoose

#8380 MB-11324 document when a shipment is flagged for diversion
  src/constants/historyLogUIDisplayName.js
  src/constants/historyLogUIDisplayName.test.js
  src/pages/Office/MoveHistory/MoveHistoryDetailsSelector.test.jsx
  src/pages/Office/MoveHistory/PlainTextDetails.test.jsx
Labels: Pamplemoose

#8327 [MB-11991] Upgrade to go 1.18
  .circleci/config.yml
  .github/workflows/go-auto-approve.yml
  .go-version
  .golangci.yml
  .pre-commit-config.yaml
  .tool-versions
  Dockerfile.local
  Dockerfile.migrations_local
  Dockerfile.reviewapp
  Dockerfile.tasks_local
  Dockerfile.tools_local
  Dockerfile.webhook_client
  Dockerfile.webhook_client_dp3
  Dockerfile.webhook_client_local
  Makefile
  README.md
  cmd/milmove/serve.go
  cypress/Dockerfile.cypress
  go.mod
  go.sum
  nix/default.nix
  pkg/models/shipment_summary_worksheet.go
  pkg/server/server.go
  scripts/gen-assets
  scripts/gen-server
  scripts/pre-commit-swagger-validate
  scripts/run-e2e-test-docker
Labels: needs-is3-review, ready-to-merge, roci

#8369 [MB-11595] Cypress customer PPM review page
  cypress/integration/milmove/ppms/review.js
  cypress/integration/mymove/utilities/customer.js
  cypress/support/ppmShared.js
  pkg/models/move.go
  pkg/models/order_test.go
  pkg/testdatagen/scenario/e2ebasic.go
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/scenario/subscenarios.go
  src/pages/MyMove/Agreement.jsx
  src/pages/MyMove/Agreement.test.jsx
  src/pages/MyMove/Review/Review.jsx
  src/pages/MyMove/Review/Review.test.jsx
  src/utils/shipments.js
  src/utils/shipments.test.js
Labels: A-Team

#8364 MB-11350 Allow customers to edit PPM shipments
  cypress/integration/mymove/homepage.js
  pkg/handlers/internalapi/internal/payloads/model_to_payload.go
  pkg/handlers/internalapi/internal/payloads/payload_to_model.go
  pkg/handlers/internalapi/mto_shipment_test.go
  pkg/models/models.go
  pkg/models/ppm_shipment.go
  pkg/services/ppmshipment/ppm_shipment_creator_test.go
  pkg/services/ppmshipment/rules.go
  pkg/services/ppmshipment/rules_test.go
  pkg/services/ppmshipment/validation.go
  pkg/services/ppmshipment/validation_test.go
  pkg/testdatagen/make_mto_shipment.go
  pkg/testdatagen/make_ppm_shipment.go
  pkg/testdatagen/make_service_member.go
  pkg/testdatagen/scenario/e2ebasic.go
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/scenario/subscenarios.go
  pkg/testdatagen/shared.go
  src/components/Customer/Home/Step/Step.stories.jsx
  src/components/Office/BillableWeight/BillableWeightCard/BillableWeightCard.jsx
  src/components/ShipmentList/ShipmentList.jsx
  src/components/ShipmentList/ShipmentList.stories.jsx
  src/components/ShipmentList/ShipmentList.test.jsx
  src/pages/MyMove/Home/index.jsx
Labels: A-Team

#8384 MB-12136 Shipment Approved Event
  src/constants/historyLogUIDisplayName.js
  src/constants/historyLogUIDisplayName.test.js
  src/pages/Office/MoveHistory/MoveHistoryDetailsSelector.test.jsx
  src/pages/Office/MoveHistory/PlainTextDetails.test.jsx
Labels: Pamplemoose

#8394 MB-11322 document service item status
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/move_audit_history.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/services/move_history/move_history_fetcher.go
  pkg/services/move_history/move_history_fetcher_test.go
  pkg/testdatagen/make_audit_history.go
  src/constants/historyLogUIDisplayName.js
  src/constants/historyLogUIDisplayName.test.js
  src/pages/Office/MoveHistory/MoveHistory.jsx
  src/pages/Office/MoveHistory/MoveHistoryDetailsSelector.jsx
  src/pages/Office/MoveHistory/MoveHistoryDetailsSelector.test.jsx
  src/pages/Office/MoveHistory/PlainTextDetails.jsx
  src/pages/Office/MoveHistory/PlainTextDetails.test.jsx
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: Pamplemoose

#8347 MB-12031 Add ADR for fake data generators and factories
  docs/adr/0068-use-fake-data-factories-with-fake-data-generators-to-create-test-data.md
  docs/adr/index.md
Labels: A-Team

#8372 MB-11673 Add Delete Shipment
  docs/adr/0038-soft-delete.md
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20220406190158_update_ppm_shipment_for_delete.up.sql
  migrations/app/schema/20220412195727_add_deletedAt_to_storage_facilities_and_mto_agents.up.sql
  pkg/assets/assets.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/shipment/delete_shipment_responses.go
  pkg/gen/internalapi/configure_mymove.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalapi/internaloperations/mto_shipment/delete_shipment.go
  pkg/gen/internalapi/internaloperations/mto_shipment/delete_shipment_parameters.go
  pkg/gen/internalapi/internaloperations/mto_shipment/delete_shipment_responses.go
  pkg/gen/internalapi/internaloperations/mto_shipment/delete_shipment_urlbuilder.go
  pkg/gen/internalapi/internaloperations/mymove_api.go
  pkg/handlers/ghcapi/mto_shipment.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/handlers/internalapi/api.go
  pkg/handlers/internalapi/mto_shipment.go
  pkg/handlers/internalapi/mto_shipment_test.go
  pkg/models/mto_agents.go
  pkg/models/ppm_shipment.go
  pkg/models/storage_facility.go
  pkg/services/mto_shipment/shipment_deleter.go
  pkg/testdatagen/make_ppm_shipment.go
  swagger-def/ghc.yaml
  swagger-def/internal.yaml
  swagger/ghc.yaml
  swagger/internal.yaml
Labels: A-Team

#8375 MB-11601 delete shipment
  cypress/integration/mymove/homepage.js
  cypress/integration/mymove/nts.js
  cypress/integration/mymove/ntsr.js
  cypress/integration/office/servicescounseling/servicesCounselingNTS.js
  cypress/integration/office/servicescounseling/servicesCounselingNTSR.js
  cypress/support/ppmShared.js
  src/components/ConfirmationModals/DestructiveShipmentConfirmationModal.jsx
  src/components/ConfirmationModals/DestructiveShipmentConfirmationModal.stories.jsx
  src/components/ConfirmationModals/DestructiveShipmentConfirmationModal.test.jsx
  src/components/Customer/Home/Step/Step.module.scss
  src/components/Customer/Review/Review.stories.jsx
  src/components/Customer/Review/ShipmentCard/HHGShipmentCard/HHGShipmentCard.jsx
  src/components/Customer/Review/ShipmentCard/HHGShipmentCard/HHGShipmentCard.test.jsx
  src/components/Customer/Review/ShipmentCard/NTSRShipmentCard/NTSRShipmentCard.jsx
  src/components/Customer/Review/ShipmentCard/NTSRShipmentCard/NTSRShipmentCard.test.jsx
  src/components/Customer/Review/ShipmentCard/NTSShipmentCard/NTSShipmentCard.jsx
  src/components/Customer/Review/ShipmentCard/NTSShipmentCard/NTSShipmentCard.test.jsx
  src/components/Customer/Review/ShipmentCard/PPMShipmentCard/PPMShipmentCard.jsx
  src/components/Customer/Review/ShipmentCard/PPMShipmentCard/PPMShipmentCard.test.jsx
  src/components/Customer/Review/ShipmentCard/ShipmentCard.module.scss
  src/components/Customer/Review/ShipmentCard/ShipmentCard.stories.jsx
  src/components/Customer/Review/Summary/Summary.jsx
  src/components/Customer/Review/Summary/Summary.test.jsx
  src/components/MigratedModal/MigratedModal.module.scss
  src/components/Office/ServicesCounseling/SCRequestShipmentCancellationModal/SCRequestShipmentCancellationModal.jsx
  src/components/Office/ServicesCounseling/SCRequestShipmentCancellationModal/SCRequestShipmentCancellationModal.stories.jsx
  src/components/Office/ShipmentForm/ShipmentForm.jsx
  src/components/ShipmentList/ShipmentList.jsx
  src/components/ShipmentList/ShipmentList.module.scss
  src/components/ShipmentList/ShipmentList.stories.jsx
  src/components/ShipmentList/ShipmentList.test.jsx
  src/containers/FlashMessage/FlashMessage.jsx
  src/pages/MyMove/Home/index.jsx
  src/pages/MyMove/Home/index.stories.jsx
  src/pages/MyMove/Home/index.test.jsx
  src/pages/MyMove/Review/Review.jsx
  src/pages/MyMove/Review/Review.test.jsx
  src/sagas/entities.js
  src/sagas/entities.test.js
  src/services/internalApi.js
  src/shared/Entities/actions.js
  src/shared/Entities/reducer.js
  src/store/entities/actions.js
Labels: A-Team

#8431 Added filter for mto_service_items
  pkg/services/move_history/move_history_fetcher.go
  pkg/services/move_history/move_history_fetcher_test.go
Labels: Pamplemoose

#8397 MB 11782 - Added acknowledgeExcessWeightRisk
  src/constants/historyLogUIDisplayName.js
  src/constants/historyLogUIDisplayName.test.js
Labels: Pamplemoose

#8410 [ MB-11317 ] Add orders and orders_logs to query with tests
  pkg/handlers/ghcapi/move_history_test.go
  pkg/services/move_history/move_history_fetcher.go
  pkg/services/move_history/move_history_fetcher_test.go
Labels: Pamplemoose, ready-to-merge

#8407 MB-11326 Add functionality for labeled data in the move history
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20220412203950_create_move_history_trigger_for_entitlements.up.sql
  pkg/services/move_history/move_history_fetcher.go
  pkg/services/move_history/move_history_fetcher_test.go
  src/constants/historyLogUIDisplayName.js
  src/pages/Office/MoveHistory/LabeledDetails.jsx
  src/pages/Office/MoveHistory/LabeledDetails.test.jsx
  src/pages/Office/MoveHistory/MoveHistoryDetailsSelector.jsx
  src/pages/Office/MoveHistory/MoveHistoryDetailsSelector.test.jsx
Labels: Pamplemoose, ready-to-merge

#8419 MB-11992 cypress delete shipment
  cypress/integration/milmove/ppms/entireShipment.js
  cypress/integration/milmove/ppms/review.js
  cypress/integration/mymove/homepage.js
  cypress/integration/mymove/utilities/customer.js
  cypress/support/ppmShared.js
  pkg/services/ppmshipment/ppm_shipment_updater_test.go
  pkg/testdatagen/make_ppm_shipment.go
  pkg/testdatagen/scenario/e2ebasic.go
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/scenario/subscenarios.go
Labels: A-Team

#8448 replace cypress uses of waitFor with wait
  cypress/integration/office/homepage.js
  cypress/integration/office/servicescounseling/servicesCounselingFlows.js
  cypress/integration/office/servicescounseling/servicesCounselingNTS.js
  cypress/integration/office/servicescounseling/servicesCounselingNTSR.js
  cypress/integration/office/txo/tioFlows.js
  cypress/integration/office/txo/tooFlowsNTS.js
  cypress/integration/office/txo/tooFlowsNTSR.js
Labels: A-Team

#8440 MB-12244 - Refactor move history event mapping
  src/constants/historyLogUIDisplayName.js
  src/constants/historyLogUIDisplayName.test.js
  src/constants/moveHistoryEventTemplate.js
  src/constants/moveHistoryEventTemplate.test.js
  src/constants/moveHistoryOperations.js
  src/pages/Office/MoveHistory/MoveHistory.jsx
  src/pages/Office/MoveHistory/MoveHistory.test.jsx
  src/pages/Office/MoveHistory/MoveHistoryDetailsSelector.jsx
  src/pages/Office/MoveHistory/MoveHistoryDetailsSelector.test.jsx
  src/pages/Office/MoveHistory/PlainTextDetails.jsx
  src/pages/Office/MoveHistory/PlainTextDetails.test.jsx
Labels: Pamplemoose

#8456 change waitFor to wait in tio flows test
  cypress/integration/office/txo/tioFlows.js
Labels: ready-to-merge, A-Team

#8452 MB-12245 merge formatters files
  src/components/DocumentViewer/DocumentViewer.jsx
  src/components/DocumentViewer/Menu/Menu.jsx
  src/components/Office/BillableWeight/ShipmentCard/ShipmentCard.jsx
  src/components/Office/BillableWeight/ShipmentCard/ShipmentCard.test.jsx
  src/components/Office/DaysInSITAllowance/DaysInSITAllowance.jsx
  src/components/Office/DefinitionLists/OrdersList.jsx
  src/components/Office/ExpandableServiceItemRow/ExpandableServiceItemRow.jsx
  src/components/Office/PaymentRequestCard/PaymentRequestCard.jsx
  src/components/Office/PaymentRequestDetails/PaymentRequestDetails.jsx
  src/components/Office/RejectServiceItemModal/RejectServiceItemModal.jsx
  src/components/Office/RequestedShipments/RequestedShipments.jsx
  src/components/Office/ReviewServiceItems/AuthorizePayment.jsx
  src/components/Office/ReviewServiceItems/PaymentReviewed.jsx
  src/components/Office/ReviewServiceItems/ReviewAccountingCodes.jsx
  src/components/Office/ReviewServiceItems/ReviewDetailsCard.jsx
  src/components/Office/ReviewServiceItems/ReviewServiceItems.jsx
  src/components/Office/ReviewServiceItems/ReviewServiceItems.test.jsx
  src/components/Office/ReviewServiceItems/ServiceItemCard.jsx
  src/components/Office/ServiceItemCalculations/helpers.js
  src/components/Office/ServiceItemsTable/ServiceItemsTable.jsx
  src/components/Office/ShipmentSITDisplay/ShipmentSITDisplay.jsx
  src/components/PrimeUI/Shipment/Shipment.jsx
  src/components/PrimeUI/Shipment/Shipment.test.jsx
  src/pages/MyMove/Agreement.jsx
  src/pages/Office/MoveHistory/MoveHistory.jsx
  src/pages/Office/MoveQueue/MoveQueue.jsx
  src/pages/Office/Orders/Orders.jsx
  src/pages/Office/PaymentRequestQueue/PaymentRequestQueue.jsx
  src/pages/Office/ReviewBillableWeight/ReviewBillableWeight.test.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
  src/pages/Office/ServicesCounselingOrders/ServicesCounselingOrders.jsx
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.jsx
  src/pages/PrimeUI/AvailableMoves/AvailableMovesQueue.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdate.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdateForm.jsx
  src/scenes/Moves/Ppm/PaymentReview/WeightTicketListItem.jsx
  src/scenes/Moves/Ppm/WeightTicket.jsx
  src/scenes/Office/DocumentViewer/DocumentDetailDisplay.jsx
  src/scenes/Office/MoveInfo.jsx
  src/scenes/Office/OrdersPanel.jsx
  src/scenes/Office/OrdersViewerPanel.js
  src/scenes/Office/Ppm/PaymentsPanel.jsx
  src/scenes/Office/queueTableColumns.js
  src/scenes/PpmLanding/StatusTimeline.jsx
  src/scenes/Review/PPMShipmentSummary.jsx
  src/scenes/Review/ServiceMemberSummary.jsx
  src/shared/EditablePanel/index.jsx
  src/shared/formatters.js
  src/shared/formatters.test.js
  src/utils/formatMtoShipment.js
  src/utils/formatters.js
  src/utils/formatters.test.js
Labels: Pamplemoose, ready-to-merge

#8437 [MB-12187] use validation pattern in webhook subscription service
  pkg/handlers/adminapi/webhook_subscriptions.go
  pkg/services/mocks/WebhookSubscriptionCreator.go
  pkg/services/webhook_subscription.go
  pkg/services/webhook_subscription/validation.go
  pkg/services/webhook_subscription/validation_test.go
  pkg/services/webhook_subscription/webhook_subscription_creator.go
  pkg/services/webhook_subscription/webhook_subscription_creator_test.go
Labels: ttv, ready-to-merge

#8396 [MB-12047][MB-11556] Service Counselor can add required PPM fields to move
  cypress/integration/office/servicescounseling/servicesCounselingNTS.js
  cypress/integration/office/servicescounseling/servicesCounselingNTSR.js
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/counseling_update_order_payload.go
  pkg/services/order/order_updater.go
  pkg/services/order/order_updater_test.go
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/scenario/subscenarios.go
  src/components/Office/DefinitionLists/OrdersList.jsx
  src/components/Office/DefinitionLists/OrdersList.stories.jsx
  src/components/Office/DefinitionLists/OrdersList.test.jsx
  src/pages/Office/MoveDetails/MoveDetails.jsx
  src/pages/Office/Orders/Orders.jsx
  src/pages/Office/Orders/ordersFormValidationSchema.js
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.test.jsx
  src/pages/Office/ServicesCounselingOrders/ServicesCounselingOrders.jsx
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: ready-to-merge, roci

#8462 MB-11321 - Add 'create standard service item' move history event
  src/constants/moveHistoryEventTemplate.js
  src/constants/moveHistoryEventTemplate.test.js
  src/pages/Office/MoveHistory/MoveHistory.test.jsx
Labels: Pamplemoose

#8459 [MB-12077] Make ServiceItem fields that are unused in responses optional
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/m_t_o_service_item.go
  swagger-def/definitions/MTOServiceItem.yaml
  swagger/ghc.yaml
Labels: ttv, ready-to-merge

#8458 MB-12245 merge formatters files methods that need extra work
  src/components/Customer/DodInfoForm/DodInfoForm.jsx
  src/components/Customer/ServiceInfoForm/ServiceInfoForm.jsx
  src/components/Office/OrdersDetailForm/OrdersDetailForm.stories.jsx
  src/components/Office/OrdersDetailForm/OrdersDetailForm.test.jsx
  src/components/Office/ServiceItemDetails/ServiceItemDetails.jsx
  src/components/Office/ShipmentForm/ShipmentForm.jsx
  src/components/Office/SubmitSITExtensionModal/SubmitSITExtensionModal.jsx
  src/pages/MyMove/EditOrders.jsx
  src/pages/MyMove/Orders.jsx
  src/pages/Office/MoveAllowances/MoveAllowances.jsx
  src/pages/Office/Orders/Orders.jsx
  src/pages/Office/ServicesCounselingMoveAllowances/ServicesCounselingMoveAllowances.jsx
  src/pages/Office/ServicesCounselingOrders/ServicesCounselingOrders.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdateForm.jsx
  src/scenes/Moves/Ppm/Weight.jsx
  src/scenes/Office/Ppm/PPMEstimatesPanel.jsx
  src/scenes/Office/QueueTable.jsx
  src/scenes/PpmLanding/MoveSummary/PpmMoveDetails.jsx
  src/scenes/Review/EditWeight.jsx
  src/scenes/Review/PPMShipmentSummary.jsx
  src/shared/formatters.js
  src/shared/formatters.test.js
  src/utils/formatters.js
  src/utils/formatters.test.js
  src/utils/incentives.js
  src/utils/serviceItems.js
  src/utils/serviceItems.test.js
Labels: Pamplemoose, ready-to-merge

#8445 [MB-12157] Remove deleted shipments from internal handlers
  cypress/integration/office/documentViewer.js
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20220420162556_create_indexes_for_mto_shipments_deleted_at.up.sql
  pkg/db/utilities/utilities.go
  pkg/db/utilities/utilities_test.go
  pkg/gen/internalapi/configure_mymove.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalapi/internaloperations/entitlements/validate_entitlement.go
  pkg/gen/internalapi/internaloperations/entitlements/validate_entitlement_parameters.go
  pkg/gen/internalapi/internaloperations/entitlements/validate_entitlement_responses.go
  pkg/gen/internalapi/internaloperations/entitlements/validate_entitlement_urlbuilder.go
  pkg/gen/internalapi/internaloperations/mymove_api.go
  pkg/handlers/internalapi/api.go
  pkg/handlers/internalapi/entitlements.go
  pkg/handlers/internalapi/entitlements_test.go
  pkg/handlers/internalapi/moves_test.go
  pkg/handlers/internalapi/personally_procured_move_test.go
  pkg/handlers/internalapi/service_members.go
  pkg/models/move.go
  pkg/models/move_test.go
  pkg/models/order.go
  pkg/models/order_test.go
  pkg/models/ppm_shipment.go
  pkg/models/service_member.go
  pkg/models/service_member_test.go
  pkg/services/move_task_order/move_task_order_fetcher.go
  pkg/services/move_task_order/move_task_order_fetcher_test.go
  pkg/services/mto_shipment/mto_shipment_address_updater.go
  pkg/services/mto_shipment/mto_shipment_fetcher.go
  pkg/services/mto_shipment/mto_shipment_fetcher_test.go
  pkg/services/mto_shipment/mto_shipment_updater.go
  pkg/services/mto_shipment/shipment_approver.go
  pkg/services/mto_shipment/shipment_cancellation_requester.go
  pkg/services/mto_shipment/shipment_deleter.go
  pkg/services/mto_shipment/shipment_diversion_approver.go
  pkg/services/mto_shipment/shipment_diversion_requester.go
  pkg/services/mto_shipment/shipment_rejecter.go
  pkg/services/mto_shipment/shipment_reweigh_requester.go
  pkg/services/mto_shipment/sit_extension_approver.go
  pkg/services/mto_shipment/sit_extension_creator_as_too.go
  pkg/services/mto_shipment/sit_extension_denier.go
  pkg/testdatagen/make_order.go
  pkg/testdatagen/make_user_upload.go
  src/services/internalApi.js
  swagger-def/internal.yaml
  swagger/internal.yaml
Labels: A-Team

#8464 MB-11943 - Add 'create basic service item' move history event
  pkg/services/move_history/move_history_fetcher.go
  src/constants/moveHistoryEventTemplate.js
  src/constants/moveHistoryEventTemplate.test.js
Labels: Pamplemoose

#8370 MB-11697-estimator-service-object
  pkg/handlers/internalapi/api.go
  pkg/handlers/internalapi/mto_shipment_test.go
  pkg/services/ppmservices/estimate_calculator.go
  pkg/services/ppmshipment.go
  pkg/services/ppmshipment/ppm_estimator.go
  pkg/services/ppmshipment/ppm_estimator_test.go
  pkg/services/ppmshipment/ppm_shipment_updater.go
  pkg/services/ppmshipment/ppm_shipment_updater_test.go
  pkg/services/ppmshipment/rules.go
  pkg/services/ppmshipment/rules_test.go
  pkg/testdatagen/scenario/shared.go
Labels: A-Team

#8470 MB-11318 document when a too edits or updates allowances
  src/constants/historyLogUIDisplayName.js
  src/constants/moveHistoryEventTemplate.js
  src/constants/moveHistoryOperations.js
  src/pages/Office/MoveHistory/LabeledDetails.jsx
  src/pages/Office/MoveHistory/LabeledDetails.test.jsx
Labels: Pamplemoose, ready-to-merge

#8460 MB-12245 merge formatters files remove unused functions
  src/components/Office/ExpandableServiceItemRow/ExpandableServiceItemRow.jsx
  src/components/Office/PaymentRequestCard/PaymentRequestCard.jsx
  src/components/Office/ServiceItemCalculations/helpers.js
  src/scenes/Moves/Ppm/PaymentReview/index.jsx
  src/scenes/Moves/Ppm/utility.js
  src/scenes/Office/DocumentViewer/DocumentDetailPanel.jsx
  src/scenes/Office/Ppm/ExpensesPanel.jsx
  src/scenes/Office/Ppm/PaymentsPanel.jsx
  src/scenes/Office/Ppm/StoragePanel.js
  src/scenes/PpmLanding/MoveSummary/PpmMoveDetails.jsx
  src/scenes/PpmLanding/MoveSummary/SubmittedPpmMoveDetails.jsx
  src/scenes/Review/EditDateAndLocation.jsx
  src/scenes/Review/EditWeight.jsx
  src/scenes/Review/PPMShipmentSummary.jsx
  src/shared/EditablePanel/index.jsx
  src/shared/formatters.js
  src/utils/formatters.js
  src/utils/formatters.test.js
Labels: Pamplemoose, ready-to-merge

#8457 MB-11128 complete ppm
  cypress/integration/mymove/homepage.js
  cypress/support/ppmShared.js
  pkg/testdatagen/scenario/devseed.go
  pkg/testdatagen/scenario/e2ebasic.go
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/scenario/subscenarios.go
  src/components/Customer/Home/Helper/Helper.stories.jsx
  src/components/PPMSummaryList/PPMSummaryList.jsx
  src/components/PPMSummaryList/PPMSummaryList.module.scss
  src/components/PPMSummaryList/PPMSummaryList.stories.jsx
  src/components/PPMSummaryList/PPMSummaryList.test.jsx
  src/constants/routes.js
  src/constants/shipments.js
  src/pages/MyMove/Home/Home.module.scss
  src/pages/MyMove/Home/HomeHelpers.jsx
  src/pages/MyMove/Home/index.jsx
  src/pages/MyMove/Home/index.stories.jsx
  src/pages/MyMove/Home/index.test.jsx
  src/types/customerShapes.js
Labels: A-Team

#8474 MB-11661 - Convert prime api handlers
  pkg/handlers/primeapi/move_task_order.go
  pkg/handlers/primeapi/mto_agent.go
  pkg/handlers/primeapi/mto_service_item.go
  pkg/handlers/primeapi/mto_shipment.go
  pkg/handlers/primeapi/mto_shipment_address.go
  pkg/handlers/primeapi/payment_request.go
  pkg/handlers/primeapi/reweigh.go
  pkg/handlers/primeapi/sit_extension.go
  pkg/handlers/primeapi/upload.go
Labels: Pamplemoose

#8435 [MB-10787] Adjust endpoint to allow SC to approve a PPM-only move
  pkg/handlers/ghcapi/move_task_order.go
  pkg/handlers/ghcapi/move_task_order_test.go
  pkg/services/move/move_router.go
  pkg/services/move/move_router_test.go
  pkg/services/move_task_order/move_task_order_fetcher.go
  pkg/services/move_task_order/move_task_order_updater.go
  pkg/services/move_task_order/move_task_order_updater_test.go
Labels: ready-to-merge, roci

#8476 MB-12225 cypress complete ppm entry
  cypress/integration/milmove/ppms/entireShipment.js
  cypress/integration/milmove/ppms/navigateToUploadDocs.js
  cypress/integration/mymove/utilities/customer.js
  pkg/testdatagen/scenario/e2ebasic.go
  pkg/testdatagen/scenario/shared.go
  src/components/PPMSummaryList/PPMSummaryList.test.jsx
Labels: A-Team

#8438 MB-11600 Block incomplete PPMs on frontend
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/p_p_m_shipment.go
  src/components/ShipmentList/ShipmentList.jsx
  src/components/ShipmentList/ShipmentList.module.scss
  src/components/ShipmentList/ShipmentList.stories.jsx
  src/components/ShipmentList/ShipmentList.test.jsx
  src/pages/MyMove/Home/Home.module.scss
  src/pages/MyMove/Home/index.jsx
  src/pages/MyMove/Home/index.stories.jsx
  src/pages/MyMove/Home/index.test.jsx
  src/utils/shipments.js
  swagger-def/internal.yaml
  swagger/internal.yaml
Labels: A-Team

#8477 Convert estimated incentive units from int32 to cents
  pkg/gen/internalapi/embedded_spec.go
  pkg/handlers/internalapi/internal/payloads/model_to_payload.go
  pkg/handlers/internalapi/internal/payloads/payload_to_model.go
  pkg/handlers/internalapi/mto_shipment_test.go
  pkg/models/ppm_shipment.go
  pkg/services/ppmshipment.go
  pkg/services/ppmshipment/ppm_estimator.go
  pkg/services/ppmshipment/ppm_estimator_test.go
  pkg/services/ppmshipment/rules_test.go
  pkg/services/ppmshipment/validation.go
  pkg/testdatagen/make_ppm_shipment.go
  pkg/testdatagen/scenario/shared.go
  swagger-def/internal.yaml
  swagger/internal.yaml
Labels: A-Team

#8441 MB-11813 Add service object orchestration ADR
  docs/adr/0033-service-object-layer.md
  docs/adr/0069-use-orchestrator-service-objects.md
  docs/adr/index.md
Labels: A-Team

#8486 MB-11317 Fix flaky test by commenting out time assertion and revisit later
  pkg/services/move_history/move_history_fetcher_test.go
Labels: Pamplemoose

#8482 MB-12019 create move history record for too reweigh request
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20220425211936_create_move_history_triggers_for_reweighs.up.sql
  pkg/services/move_history/move_history_fetcher.go
  pkg/services/move_history/move_history_fetcher_test.go
  src/constants/moveHistoryEventTemplate.js
  src/constants/moveHistoryEventTemplate.test.js
Labels: Pamplemoose, ready-to-merge

#8468 [MB-11863] Allow TOO to see moves with PPM shipments in their queue
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20220426195320_update_move_to_gbloc_view_for_ppm_shipments.up.sql
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/queues_test.go
  pkg/models/move_to_gblocs.go
  pkg/services/order/order_fetcher_test.go
Labels: ready-to-merge, roci

#8481 MB-11572 prime ppm counseling
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20220422162922_add_prime_counseling_completed_at.up.sql
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/move_task_order/update_m_t_o_post_counseling_information.go
  pkg/gen/primeapi/primeoperations/move_task_order/update_m_t_o_post_counseling_information_parameters.go
  pkg/gen/primeapi/primeoperations/move_task_order/update_m_t_o_post_counseling_information_responses.go
  pkg/gen/primeclient/move_task_order/update_m_t_o_post_counseling_information_parameters.go
  pkg/gen/primeclient/move_task_order/update_m_t_o_post_counseling_information_responses.go
  pkg/gen/primemessages/m_t_o_shipment.go
  pkg/gen/primemessages/m_t_o_shipment_type.go
  pkg/gen/primemessages/move_task_order.go
  pkg/gen/primemessages/p_p_m_shipment.go
  pkg/gen/primemessages/p_p_m_shipment_status.go
  pkg/handlers/primeapi/move_task_order.go
  pkg/handlers/primeapi/move_task_order_test.go
  pkg/handlers/primeapi/payloads/model_to_payload.go
  pkg/models/move.go
  pkg/services/mocks/MoveTaskOrderUpdater.go
  pkg/services/move_task_order.go
  pkg/services/move_task_order/move_task_order_updater.go
  pkg/services/move_task_order/move_task_order_updater_test.go
  swagger-def/definitions/PPMShipment.yaml
  swagger-def/definitions/PPMShipmentStatus.yaml
  swagger-def/prime.yaml
  swagger/prime.yaml
Labels: ready-to-merge, roci

#8527 MB-12365 Update listMTOShipments to return associated ppm shipments
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/m_t_o_shipment.go
  pkg/gen/ghcmessages/p_p_m_shipment.go
  pkg/gen/ghcmessages/p_p_m_shipment_status.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/services/mto_shipment/mto_shipment_fetcher.go
  pkg/services/mto_shipment/mto_shipment_fetcher_test.go
  swagger-def/definitions/MTOShipment.yaml
  swagger/ghc.yaml
Labels: ready-to-merge, roci
