Repository transcom/mymove, pull requests merged in 2022-10, with the labels that each got.

#9258 MB-13654 eval report page two save draft
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20220926162626_add_additional_eval_report_fields.up.sql
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/evaluation_report.go
  pkg/handlers/ghcapi/evaluation_report_test.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/internal/payloads/payload_to_model.go
  pkg/models/evaluation_report.go
  src/components/Office/EvaluationForm/EvaluationForm.jsx
  src/components/Office/EvaluationForm/EvaluationForm.test.jsx
  src/components/Office/EvaluationReportTable/EvaluationReportTable.jsx
  src/components/Office/EvaluationViolationsForm/EvaluationViolationsForm.jsx
  src/components/Office/EvaluationViolationsForm/EvaluationViolationsForm.test.jsx
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: ttv

#9240 [MB-11290] (User Story) Document when a services counselor updates and saves allowances
  pkg/services/query/sql_scripts/move_history_fetcher.sql
  src/constants/MoveHistory/Database/FieldMappings.js
  src/constants/MoveHistory/Database/Tables.js
  src/constants/MoveHistory/EventTemplates/index.js
  src/constants/MoveHistory/EventTemplates/updateAllowance.test.js
  src/constants/MoveHistory/EventTemplates/updateAllowanceCounseling.js
  src/constants/MoveHistory/EventTemplates/updateAllowanceCounseling.test.js
  src/constants/MoveHistory/EventTemplates/updateAllowanceServiceMemberBranch.js
  src/constants/MoveHistory/EventTemplates/updateAllowanceServiceMemberBranch.test.js
  src/pages/Office/MoveHistory/LabeledDetails.test.jsx
Labels: Pamplemoose

#9280 MB-13976 Replace 'Finish Later' with 'Return To Homepage' in PPM closeout forms.
  src/components/Customer/PPM/Closeout/AboutForm/AboutForm.jsx
  src/components/Customer/PPM/Closeout/AboutForm/AboutForm.test.jsx
  src/components/Customer/PPM/Closeout/ExpenseForm/ExpenseForm.jsx
  src/components/Customer/PPM/Closeout/ExpenseForm/ExpenseForm.test.jsx
  src/components/Customer/PPM/Closeout/FinalCloseoutForm/FinalCloseoutForm.jsx
  src/components/Customer/PPM/Closeout/FinalCloseoutForm/FinalCloseoutForm.test.jsx
  src/components/Customer/PPM/Closeout/ProGearForm/ProGearForm.jsx
  src/components/Customer/PPM/Closeout/ProGearForm/ProGearForm.test.jsx
  src/components/Customer/PPM/Closeout/WeightTicketForm/WeightTicketForm.jsx
  src/components/Customer/PPM/Closeout/WeightTicketForm/WeightTicketForm.test.jsx
  src/pages/MyMove/PPM/Closeout/About/About.test.jsx
  src/pages/MyMove/PPM/Closeout/Expenses/Expenses.test.jsx
  src/pages/MyMove/PPM/Closeout/FinalCloseout/FinalCloseout.test.jsx
  src/pages/MyMove/PPM/Closeout/ProGear/ProGear.test.jsx
  src/pages/MyMove/PPM/Closeout/Review/Review.jsx
  src/pages/MyMove/PPM/Closeout/Review/Review.test.jsx
  src/pages/MyMove/PPM/Closeout/WeightTickets/WeightTickets.test.jsx
Labels: A-Team

#9285 MB-14175 - Start move history details refactor
  src/constants/MoveHistory/EventTemplates/ApproveShipment/approveShipment.jsx
  src/constants/MoveHistory/EventTemplates/ApproveShipment/approveShipment.test.jsx
  src/constants/MoveHistory/EventTemplates/index.js
  src/constants/MoveHistory/TemplateManager.js
  src/pages/Office/MoveHistory/MoveHistoryDetailsSelector.jsx
Labels: Pamplemoose

#9277 MB-14156: global scroll to top
  src/App/index.jsx
  src/components/NotificationScrollToTop.jsx
  src/components/ScrollToTop.jsx
  src/containers/FlashGridContainer/FlashGridContainer.jsx
  src/containers/FlashGridContainer/FlashGridContainer.test.jsx
  src/pages/MyMove/Agreement.jsx
  src/pages/MyMove/AmendOrders/AmendOrders.jsx
  src/pages/MyMove/Home/index.jsx
  src/pages/MyMove/MovingInfo.jsx
  src/pages/MyMove/Orders.jsx
  src/pages/MyMove/PPM/Booking/Advance/Advance.jsx
  src/pages/MyMove/PPM/Booking/DateAndLocation/DateAndLocation.jsx
  src/pages/MyMove/PPM/Booking/EstimatedIncentive/EstimatedIncentive.jsx
  src/pages/MyMove/PPM/Booking/EstimatedWeightsProGear/EstimatedWeightsProGear.jsx
  src/pages/MyMove/PPM/Closeout/About/About.jsx
  src/pages/MyMove/PPM/Closeout/FinalCloseout/FinalCloseout.jsx
  src/pages/MyMove/PPM/Closeout/ProGear/ProGear.jsx
  src/pages/MyMove/PPM/Closeout/Review/Review.jsx
  src/pages/MyMove/PPM/Closeout/WeightTickets/WeightTickets.jsx
  src/pages/MyMove/Profile/BackupContact.jsx
  src/pages/MyMove/Profile/BackupMailingAddress.jsx
  src/pages/MyMove/Profile/ContactInfo.jsx
  src/pages/MyMove/Profile/DodInfo.jsx
  src/pages/MyMove/Profile/DutyLocation.jsx
  src/pages/MyMove/Profile/EditContactInfo.jsx
  src/pages/MyMove/Profile/EditServiceInfo.jsx
  src/pages/MyMove/Profile/Name.jsx
  src/pages/MyMove/Profile/ResidentialAddress.jsx
  src/pages/MyMove/Review/Review.jsx
  src/pages/MyMove/SelectShipmentType.jsx
  src/pages/MyMove/UploadOrders.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
  src/shared/WizardPage/Form.jsx
  src/shared/WizardPage/index.jsx
Labels: A-Team, ready-to-merge

#9270 [MB-13817] Fix missing "create report" button on first login
  pkg/handlers/authentication/auth.go
  pkg/handlers/authentication/auth_test.go
Labels: ttv, ready-to-merge

#9268 [MB-2746] Generate QAE report pdfs
  pkg/assets/assets.go
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/doc.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/evaluation_reports/download_evaluation_report.go
  pkg/gen/ghcapi/ghcoperations/evaluation_reports/download_evaluation_report_parameters.go
  pkg/gen/ghcapi/ghcoperations/evaluation_reports/download_evaluation_report_responses.go
  pkg/gen/ghcapi/ghcoperations/evaluation_reports/download_evaluation_report_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/evaluation_report.go
  pkg/handlers/ghcapi/evaluation_report_test.go
  pkg/models/service_member.go
  pkg/paperwork/evaluation_report.go
  pkg/paperwork/evaluation_report_form_creator.go
  pkg/paperwork/evaluation_report_form_creator_test.go
  pkg/paperwork/evaluation_report_test.go
  pkg/paperwork/forms.go
  pkg/paperwork/formtemplates/PublicSans-Bold.ttf
  pkg/paperwork/formtemplates/PublicSans-Regular.ttf
  pkg/paperwork/formtemplates/arrowright.png
  pkg/services/mocks/OrderFetcher.go
  pkg/services/order.go
  src/components/Office/EvaluationReportTable/EvaluationReportTable.jsx
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: ttv, ready-to-merge

#9312 MB-13859-weight-ticket-status-and-reason-cleanPR
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20221006031146_add_status_and_reason_to_weight_ticket.up.sql
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/moving_expense.go
  pkg/gen/ghcmessages/p_p_m_document_status_reason.go
  pkg/gen/ghcmessages/weight_ticket.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/moving_expense.go
  pkg/gen/internalmessages/p_p_m_document_status_reason.go
  pkg/gen/internalmessages/weight_ticket.go
  pkg/handlers/internalapi/internal/payloads/model_to_payload.go
  pkg/models/weight_ticket.go
  pkg/models/weight_ticket_test.go
  swagger-def/definitions/MovingExpense.yaml
  swagger-def/definitions/PPMDocumentStatus.yaml
  swagger-def/definitions/PPMDocumentStatusReason.yaml
  swagger-def/internal.yaml
  swagger/ghc.yaml
  swagger/internal.yaml
Labels: A-Team

#9232 MB-13461 submit report violations
  src/components/Office/CustomerSupportRemarkText/CustomerSupportRemarkText.module.scss
  src/components/Office/EvaluationViolationsForm/EvaluationViolationsForm.jsx
  src/components/Office/EvaluationViolationsForm/EvaluationViolationsForm.module.scss
  src/components/Office/EvaluationViolationsForm/EvaluationViolationsForm.stories.jsx
  src/components/Office/EvaluationViolationsForm/EvaluationViolationsForm.test.jsx
  src/pages/Office/EvaluationViolations/EvaluationViolations.jsx
  src/pages/Office/EvaluationViolations/EvaluationViolations.test.jsx
  src/pages/Office/TXOMoveInfo/TXOMoveInfo.jsx
Labels: ttv

#9310 MB-13944 - Future-proof move history server tests
  pkg/services/move_history/move_history_fetcher_test.go
Labels: Pamplemoose

#9308 MB-12436 - Display deleted values in move history details
  src/pages/Office/MoveHistory/LabeledDetails.jsx
  src/pages/Office/MoveHistory/LabeledDetails.test.jsx
Labels: Pamplemoose

#9321 MB-14217: Disable happo for stories with .play functionality
  src/components/Customer/PPM/Booking/DateAndLocationForm/DateAndLocationForm.stories.jsx
  src/components/Customer/PPM/Booking/EstimatedWeightsProGearForm/EstimatedWeightsProGearForm.stories.jsx
  src/components/Customer/PPM/Closeout/AboutForm/AboutForm.stories.jsx
  src/components/Customer/PPM/Closeout/FinalCloseoutForm/FinalCloseoutForm.stories.jsx
Labels: A-Team

#9295 [MB-14162] User story document when a too updates allowances branch
  src/constants/MoveHistory/EventTemplates/index.js
  src/constants/MoveHistory/EventTemplates/updateAllowance.test.js
  src/constants/MoveHistory/EventTemplates/updateAllowanceServiceMemberByCounselor.js
  src/constants/MoveHistory/EventTemplates/updateAllowanceServiceMemberByCounselor.test.js
  src/constants/MoveHistory/EventTemplates/updateAllowances/updateAllowance.jsx
  src/constants/MoveHistory/EventTemplates/updateAllowances/updateAllowance.test.jsx
  src/constants/MoveHistory/EventTemplates/updateAllowances/updateAllowanceServiceMemberByTOO.jsx
  src/constants/MoveHistory/EventTemplates/updateAllowances/updateAllowanceServiceMemberByTOO.test.jsx
Labels: Pamplemoose

#9313 [MB-12602] Modifying the move history sql query to retrieve service member information
  pkg/services/move_history/move_history_fetcher_test.go
  pkg/services/query/sql_scripts/move_history_fetcher.sql
Labels: Pamplemoose

#9330 MB-14234: Fix non-deterministic PPM approval date causing Happo diffs
  src/pages/MyMove/Home/index.stories.jsx
Labels: A-Team

#9341 MB-14227: independent session managers for each app
  cmd/milmove/serve.go
  pkg/auth/cookie.go
  pkg/auth/cookie_test.go
  pkg/auth/session.go
  pkg/auth/session_test.go
  pkg/handlers/adminapi/office_users.go
  pkg/handlers/adminapi/office_users_test.go
  pkg/handlers/adminapi/users.go
  pkg/handlers/adminapi/users_test.go
  pkg/handlers/apitests.go
  pkg/handlers/authentication/auth.go
  pkg/handlers/authentication/auth_test.go
  pkg/handlers/authentication/devlocal.go
  pkg/handlers/authentication/devlocal_test.go
  pkg/handlers/config.go
  pkg/handlers/internalapi/service_members.go
  pkg/handlers/responders.go
  pkg/handlers/routing/routing_init.go
  pkg/handlers/routing/routing_init_test.go
  pkg/middleware/recovery.go
  pkg/services/mocks/UserSessionRevocation.go
  pkg/services/user.go
  pkg/services/user/user_session_revocation.go
  pkg/services/user/user_session_revocation_test.go
  pkg/testdatagen/make_client_cert.go
Labels: ready-to-merge

#9329 [MB-11806] secondary addresses displayed in move history table
  pkg/services/move_history/move_history_fetcher_test.go
  pkg/services/query/sql_scripts/move_history_fetcher.sql
  src/constants/MoveHistory/Database/AddressTypes.js
  src/constants/MoveHistory/Database/FieldMappings.js
  src/constants/MoveHistory/EventTemplates/createMTOShipmentAddresses.js
  src/constants/MoveHistory/EventTemplates/createMTOShipmentAddresses.test.js
  src/constants/MoveHistory/EventTemplates/updateMTOServiceItemAddress.js
  src/constants/MoveHistory/EventTemplates/updateMTOShipmentAddresses.js
  src/constants/MoveHistory/EventTemplates/updateMTOShipmentAddresses.test.js
Labels: Pamplemoose

#9331 [MB-11217] Office users can see order info submitted by customers
  src/constants/MoveHistory/Database/FieldMappings.js
  src/constants/MoveHistory/EventTemplates/CreateOrders/createEntitlements.jsx
  src/constants/MoveHistory/EventTemplates/CreateOrders/createEntitlements.test.jsx
  src/constants/MoveHistory/EventTemplates/CreateOrders/createMoves.jsx
  src/constants/MoveHistory/EventTemplates/CreateOrders/createMoves.test.jsx
  src/constants/MoveHistory/EventTemplates/CreateOrders/createOrders.jsx
  src/constants/MoveHistory/EventTemplates/CreateOrders/createOrders.test.jsx
  src/constants/MoveHistory/EventTemplates/createOrders.js
  src/constants/MoveHistory/EventTemplates/createOrders.test.js
  src/constants/MoveHistory/EventTemplates/index.js
Labels: Pamplemoose

#9314 [MB-11571] Filter GBLOCs: NAVY, TVCB and USCG for PPM Closeout
  pkg/services/order/order_fetcher.go
  pkg/services/order/order_fetcher_test.go
  pkg/testdatagen/make_office_user.go
Labels: A-Team, ready-to-merge

#9361 MB-12744 QAE/CSR Search Form Fix and Styling Updates
  cypress/integration/office/qaecsr/moveSearchFlows.js
  pkg/testdatagen/scenario/shared.go
  src/components/MoveSearchForm/MoveSearchForm.jsx
  src/components/MoveSearchForm/MoveSearchForm.module.scss
  src/components/Table/SearchResultsTable.jsx
  src/components/Table/SearchResultsTable.module.scss
  src/components/form/fields/TextField/TextField.jsx
  src/components/form/fields/TextField/TextField.test.jsx
  src/pages/Office/QAECSRMoveSearch/QAECSRMoveSearch.jsx
  src/pages/Office/QAECSRMoveSearch/QAECSRMoveSearch.module.scss
Labels: ttv

#9337 MB-13491 Allow/handle no destination address for both HHG and NTSR using destination duty location zip
  src/components/ConfirmationModals/EvaluationReportConfirmationModal.jsx
  src/components/Office/DefinitionLists/NTSRShipmentInfoList.jsx
  src/components/Office/DefinitionLists/ShipmentInfoList.jsx
  src/components/Office/DefinitionLists/ShipmentInfoListSelector.jsx
  src/components/Office/EvaluationForm/EvaluationForm.jsx
  src/components/Office/EvaluationReportPreview/EvaluationReportPreview.jsx
  src/components/Office/EvaluationReportShipmentDisplay/EvaluationReportShipmentDisplay.jsx
  src/components/Office/EvaluationReportShipmentInfo/EvaluationReportShipmentInfo.jsx
  src/components/Office/EvaluationReportTable/EvaluationReportShipmentInfo.jsx
  src/components/Office/EvaluationReportTable/EvaluationReportTable.jsx
  src/components/Office/EvaluationReportTable/ShipmentEvaluationReports.jsx
  src/components/Office/EvaluationViolationsForm/EvaluationViolationsForm.jsx
  src/pages/Office/EvaluationReport/EvaluationReport.jsx
  src/pages/Office/EvaluationReports/EvaluationReports.jsx
  src/pages/Office/EvaluationViolations/EvaluationViolations.jsx
  src/pages/Office/TXOMoveInfo/TXOMoveInfo.jsx
  src/pages/Office/TXOMoveInfo/TXOMoveInfo.test.jsx
Labels: ttv

#9365 MB-14280 - Refactor create mto service item templates
  src/constants/MoveHistory/EventTemplates/CreateMTOServiceItem/createMTOServiceItem.jsx
  src/constants/MoveHistory/EventTemplates/CreateMTOServiceItem/createMTOServiceItem.test.jsx
  src/constants/MoveHistory/EventTemplates/CreateMTOServiceItem/createMTOServiceItemCustomerContacts.jsx
  src/constants/MoveHistory/EventTemplates/CreateMTOServiceItem/createMTOServiceItemCustomerContacts.test.jsx
  src/constants/MoveHistory/EventTemplates/CreateMTOServiceItem/createMTOServiceItemDimensions.jsx
  src/constants/MoveHistory/EventTemplates/CreateMTOServiceItem/createMTOServiceItemDimensions.test.jsx
  src/constants/MoveHistory/EventTemplates/CreateMTOServiceItem/createMTOServiceItemUpdateMoveStatus.jsx
  src/constants/MoveHistory/EventTemplates/CreateMTOServiceItem/createMTOServiceItemUpdateMoveStatus.test.jsx
  src/constants/MoveHistory/EventTemplates/CreateMTOServiceItem/updateMTOServiceItemAddress.jsx
  src/constants/MoveHistory/EventTemplates/CreateMTOServiceItem/updateMTOServiceItemAddress.test.jsx
  src/constants/MoveHistory/EventTemplates/createMTOServiceItem.js
  src/constants/MoveHistory/EventTemplates/createMTOServiceItem.test.js
  src/constants/MoveHistory/EventTemplates/createMTOServiceItemCustomerContacts.js
  src/constants/MoveHistory/EventTemplates/createMTOServiceItemCustomerContacts.test.js
  src/constants/MoveHistory/EventTemplates/createMTOServiceItemDimensions.js
  src/constants/MoveHistory/EventTemplates/createMTOServiceItemUpdateMoveStatus.js
  src/constants/MoveHistory/EventTemplates/createMTOServiceItemUpdateMoveStatus.test.js
  src/constants/MoveHistory/EventTemplates/index.js
  src/constants/MoveHistory/EventTemplates/updateMTOServiceItemAddress.js
Labels: Pamplemoose

#9371 [MB-12401] removed clientQuery from move history request
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/move_audit_history.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/move_history_test.go
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: Pamplemoose

#9376 MB-13792 Minor qaecsr cleanup
  cypress/integration/office/qaecsr/qaeFlows.js
  src/components/Office/EvaluationReportPreview/EvaluationReportPreview.jsx
  src/components/Office/EvaluationViolationsForm/EvaluationViolationsForm.jsx
  src/pages/Office/EvaluationViolations/EvaluationViolations.jsx
  src/pages/Office/TXOMoveInfo/TXOMoveInfo.jsx
  src/types/reportViolation.js
Labels: ttv

#9328 Add usage of status and reason in service object + related tests
  pkg/handlers/internalapi/weight_ticket_test.go
  pkg/services/weight_ticket/rules.go
  pkg/services/weight_ticket/rules_test.go
  pkg/services/weight_ticket/weight_ticket_creator.go
  pkg/services/weight_ticket/weight_ticket_updater.go
  pkg/services/weight_ticket/weight_ticket_updater_test.go
  pkg/testdatagen/make_weight_ticket.go
Labels: A-Team, ready-to-merge

#9377 MB-13792 Cleanup selected/preview violations styling
  src/components/Office/EvaluationReportPreview/EvaluationReportPreview.jsx
  src/components/Office/EvaluationReportPreview/EvaluationReportPreview.module.scss
  src/components/Office/EvaluationViolationsForm/SelectedViolation/SelectedViolation.jsx
  src/components/Office/EvaluationViolationsForm/SelectedViolation/SelectedViolation.test.jsx
Labels: ttv

#9363 MB-10689 customer can upload receipts details on expenses screen
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20221014194001_rename_weighing_fees_to_weighing_fee.up.sql
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/moving_expense_type.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/moving_expense_type.go
  pkg/handlers/internalapi/internal/payloads/model_to_payload.go
  pkg/models/moving_expense.go
  src/components/Customer/PPM/Closeout/ExpenseForm/ExpenseForm.jsx
  src/pages/MyMove/PPM/Closeout/Expenses/Expenses.jsx
  src/pages/MyMove/PPM/Closeout/Expenses/Expenses.test.jsx
  src/pages/MyMove/PPM/Closeout/Review/Review.jsx
  src/scenes/Office/Ppm/ducks.test.js
  src/services/internalApi.js
  src/shared/utils.js
  src/utils/shipments.js
  swagger-def/definitions/MovingExpenseType.yaml
  swagger-def/internal.yaml
  swagger/ghc.yaml
  swagger/internal.yaml
Labels: A-Team

#9397 Removing the orders.*.move.mil TLS healthcheck
  .circleci/config.yml
Labels: infra, security, help wanted

#9352 [MB-14038] Manage go-swagger in a better way
  .circleci/config.yml
  .pre-commit-config.yaml
  Dockerfile.local
  Dockerfile.migrations_local
  Dockerfile.reviewapp
  Dockerfile.tasks_local
  Dockerfile.tools_local
  Dockerfile.webhook_client
  Dockerfile.webhook_client_dp3
  Dockerfile.webhook_client_local
  Makefile
  go.mod
  go.sum
  nix/default.nix
  pkg/tools/tools.go
  scripts/README.md
  scripts/gen-assets
  scripts/gen-server
  scripts/pre-commit-swagger-validate
  scripts/run-e2e-mtls-test-docker
  scripts/run-e2e-test-docker
Labels: ttv, ready-to-merge

#9343 MB-14201: forbidden landing page
  .air.conf
  Makefile
  cypress/integration/admin/homepage.js
  pkg/auth/cookie.go
  pkg/handlers/authentication/auth.go
  pkg/handlers/authentication/auth_test.go
  pkg/handlers/authentication/devlocal_test.go
  src/App/index.jsx
  src/containers/PrivateRoute.jsx
  src/containers/PrivateRoute.test.jsx
  src/pages/InvalidPermissions/InvalidPermissions.jsx
  src/pages/InvalidPermissions/InvalidPermissions.module.scss
  src/pages/Office/index.jsx
  src/scenes/MyMove/index.jsx
  src/scenes/SystemAdmin/index.jsx
  src/scenes/SystemAdmin/shared/LoginButton.jsx
  src/scenes/SystemAdmin/shared/LoginButton.module.scss
  src/scenes/SystemAdmin/shared/LogoutButton.jsx
  src/scenes/SystemAdmin/shared/SignIn.jsx
  src/scenes/SystemAdmin/shared/SignIn.module.scss
  src/shared/constants.js
Labels: ready-to-merge

#9351 [MB-13333] Add backend file upload support for PPM document spreadsheets
  cypress/fixtures/constructedWeight.xlsx
  cypress/integration/milmove/ppms/weightTickets.js
  cypress/support/ppmCustomerShared.js
  go.mod
  go.sum
  pkg/gen/internalapi/configure_mymove.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalapi/internaloperations/mymove_api.go
  pkg/gen/internalapi/internaloperations/ppm/create_p_p_m_upload.go
  pkg/gen/internalapi/internaloperations/ppm/create_p_p_m_upload_parameters.go
  pkg/gen/internalapi/internaloperations/ppm/create_p_p_m_upload_responses.go
  pkg/gen/internalapi/internaloperations/ppm/create_p_p_m_upload_urlbuilder.go
  pkg/handlers/internalapi/api.go
  pkg/handlers/internalapi/uploads.go
  pkg/handlers/internalapi/uploads_test.go
  pkg/handlers/internalapi/weight_ticket_test.go
  pkg/services/mto_shipment/mto_shipment_fetcher.go
  pkg/services/order/order_updater.go
  pkg/services/ppmshipment/ppm_shipment_fetcher.go
  pkg/services/ppmshipment/ppm_shipment_fetcher_test.go
  pkg/storage/storage.go
  pkg/testdatagen/make_weight_ticket.go
  pkg/testdatagen/scenario/e2ebasic.go
  pkg/testdatagen/scenario/shared.go
  pkg/uploader/allowed_file_types.go
  pkg/uploader/allowed_file_types_test.go
  pkg/uploader/create_user_upload.go
  pkg/uploader/prime_uploader_test.go
  pkg/uploader/uploader.go
  pkg/uploader/uploader_test.go
  pkg/uploader/user_uploader_test.go
  src/pages/MyMove/PPM/Closeout/WeightTickets/WeightTickets.jsx
  src/services/internalApi.js
  swagger-def/internal.yaml
  swagger/internal.yaml
Labels: A-Team, ready-to-merge

#9360 [MB-11224] (User Story) Office users can see creation and updates to the customer profile
  pkg/services/query/sql_scripts/move_history_fetcher.sql
  src/constants/MoveHistory/Database/AddressTypes.js
  src/constants/MoveHistory/Database/FieldMappings.js
  src/constants/MoveHistory/EventTemplates/CreateMTOServiceItem/updateMTOServiceItemAddress.test.jsx
  src/constants/MoveHistory/EventTemplates/CreateServiceMember/createServiceMember.jsx
  src/constants/MoveHistory/EventTemplates/CreateServiceMember/createServiceMember.test.jsx
  src/constants/MoveHistory/EventTemplates/PatchServiceMember/patchServiceMember.jsx
  src/constants/MoveHistory/EventTemplates/PatchServiceMember/patchServiceMember.test.jsx
  src/constants/MoveHistory/EventTemplates/UpdateAddress/createAddress.jsx
  src/constants/MoveHistory/EventTemplates/UpdateAddress/createAddress.test.jsx
  src/constants/MoveHistory/EventTemplates/UpdateAddress/updateAddress.jsx
  src/constants/MoveHistory/EventTemplates/UpdateAddress/updateAddress.test.jsx
  src/constants/MoveHistory/EventTemplates/UpdateAllowances/updateAllowance.jsx
  src/constants/MoveHistory/EventTemplates/UpdateAllowances/updateAllowance.test.jsx
  src/constants/MoveHistory/EventTemplates/UpdateAllowances/updateAllowanceServiceMemberByTOO.jsx
  src/constants/MoveHistory/EventTemplates/UpdateAllowances/updateAllowanceServiceMemberByTOO.test.jsx
  src/constants/MoveHistory/EventTemplates/createMTOShipmentAddresses.js
  src/constants/MoveHistory/EventTemplates/createMTOShipmentAddresses.test.js
  src/constants/MoveHistory/EventTemplates/index.js
  src/constants/MoveHistory/EventTemplates/updateMTOShipmentAddresses.js
  src/constants/MoveHistory/EventTemplates/updateMTOShipmentAddresses.test.js
  src/constants/MoveHistory/UIDisplay/Operations.js
Labels: Pamplemoose

#9398 [MB-14154] Fix login.gov sign out
  pkg/handlers/authentication/auth.go
  pkg/handlers/authentication/auth_test.go
  pkg/handlers/authentication/login_gov.go
Labels: ttv, ready-to-merge

#9422 [MB-14323, MB-14296, MB-14208] audit history table migrations
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20221020202612_create-and-modify-move-history-triggers-for-multiple-tables.up.sql
  pkg/services/move_history/move_history_fetcher_test.go
  src/constants/MoveHistory/EventTemplates/CreateOrders/createOrders.jsx
  src/constants/MoveHistory/EventTemplates/UpdateAllowances/updateAllowanceServiceMemberByTOO.jsx
  src/constants/MoveHistory/EventTemplates/UpdateAllowances/updateAllowanceServiceMemberByTOO.test.jsx
  src/constants/MoveHistory/EventTemplates/updateAllowanceServiceMemberByCounselor.js
  src/constants/MoveHistory/EventTemplates/updateAllowanceServiceMemberByCounselor.test.js
Labels: Pamplemoose

#9378 MB-13985 more violation dates
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20221007190815_add_evaluation_violation_delivery_date.up.sql
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/evaluation_report.go
  pkg/handlers/ghcapi/evaluation_report_test.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/internal/payloads/payload_to_model.go
  pkg/models/evaluation_report.go
  pkg/paperwork/evaluation_report.go
  src/components/Office/EvaluationViolationsForm/EvaluationViolationsForm.jsx
  src/pages/Office/EvaluationViolations/EvaluationViolations.jsx
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: ttv

#9434 MB-13855 Adds closeout enum value and makes it available to use
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20221021145115_ppm_closeout_status.up.sql
  pkg/models/ppm_shipment.go
  pkg/services/mto_shipment/validation_test.go
Labels: ttv

#9423 MB-14310: Update go version to 1.19.2
  .circleci/config.yml
  .go-version
  .tool-versions
  Dockerfile.local
  Dockerfile.migrations_local
  Dockerfile.reviewapp
  Dockerfile.tasks_local
  Dockerfile.tools_local
  Dockerfile.webhook_client
  Dockerfile.webhook_client_dp3
  Dockerfile.webhook_client_local
  Makefile
  README.md
  nix/default.nix
  pkg/assets/assets.go
  scripts/gen-assets
  scripts/run-e2e-mtls-test-docker
  scripts/run-e2e-test-docker
Labels: A-Team

#9439 [MB-14319] Refactor and rename updateAllowancesCounseling and updateAllowancesByServiceMember
  src/constants/MoveHistory/EventTemplates/UpdateAllowances/updateAllowanceByCounselor.jsx
  src/constants/MoveHistory/EventTemplates/UpdateAllowances/updateAllowanceByCounselor.test.jsx
  src/constants/MoveHistory/EventTemplates/UpdateServiceMember/updateServiceMemberByCounselor.jsx
  src/constants/MoveHistory/EventTemplates/UpdateServiceMember/updateServiceMemberByCounselor.test.jsx
  src/constants/MoveHistory/EventTemplates/UpdateServiceMember/updateServiceMemberByTOO.jsx
  src/constants/MoveHistory/EventTemplates/UpdateServiceMember/updateServiceMemberByTOO.test.jsx
  src/constants/MoveHistory/EventTemplates/index.js
  src/constants/MoveHistory/EventTemplates/updateAllowanceCounseling.test.js
  src/constants/MoveHistory/EventTemplates/updateAllowanceServiceMemberByCounselor.test.js
Labels: Pamplemoose

#9413 [MB-12340] changed test assertion to fall within 2000 microsecond range
  pkg/services/move_history/move_history_fetcher_test.go
Labels: Pamplemoose

#9437 [MB-14345] refactored template and now includes shipment ID
  src/constants/MoveHistory/EventTemplates/DeleteShipment/deleteShipment.jsx
  src/constants/MoveHistory/EventTemplates/DeleteShipment/deleteShipment.test.jsx
  src/constants/MoveHistory/EventTemplates/UpdateOrders/updateOrder.jsx
  src/constants/MoveHistory/EventTemplates/UpdateOrders/updateOrder.test.jsx
  src/constants/MoveHistory/EventTemplates/deleteShipment.test.js
  src/constants/MoveHistory/EventTemplates/index.js
Labels: Pamplemoose

#9442 [MB-14348] refactored template and testing
  src/constants/MoveHistory/EventTemplates/UpdateMTOServiceItem/updateMTOServiceItem.jsx
  src/constants/MoveHistory/EventTemplates/UpdateMTOServiceItem/updateMTOServiceItem.test.jsx
  src/constants/MoveHistory/EventTemplates/index.js
  src/constants/MoveHistory/EventTemplates/updateMTOServiceItem.js
  src/constants/MoveHistory/EventTemplates/updateMTOServiceItem.test.js
Labels: Pamplemoose

#9455 [MB-14294] Migrate from go-bindata to Go's built-in embed feature
  .circleci/config.yml
  .golangci.yml
  Dockerfile.local
  Dockerfile.migrations_local
  Dockerfile.reviewapp
  Dockerfile.tasks_local
  Dockerfile.tools_local
  Dockerfile.webhook_client
  Dockerfile.webhook_client_dp3
  Dockerfile.webhook_client_local
  Makefile
  cmd/generate-shipment-summary/main.go
  pkg/assets/assets.go
  pkg/assets/assets_test.go
  pkg/assets/notifications/templates/move_approved_template.html
  pkg/assets/notifications/templates/move_approved_template.txt
  pkg/assets/notifications/templates/move_canceled_template.html
  pkg/assets/notifications/templates/move_canceled_template.txt
  pkg/assets/notifications/templates/move_payment_reminder_template.html
  pkg/assets/notifications/templates/move_payment_reminder_template.txt
  pkg/assets/notifications/templates/move_reviewed_template.html
  pkg/assets/notifications/templates/move_reviewed_template.txt
  pkg/assets/notifications/templates/move_submitted_template.html
  pkg/assets/notifications/templates/move_submitted_template.txt
  pkg/assets/notifications/templates/reweigh_requested_template.html
  pkg/assets/notifications/templates/reweigh_requested_template.txt
  pkg/assets/notifications/templates/user_account_modified_template.html
  pkg/assets/notifications/templates/user_account_modified_template.txt
  pkg/assets/paperwork/formtemplates/PublicSans-Bold.ttf
  pkg/assets/paperwork/formtemplates/PublicSans-Regular.ttf
  pkg/assets/paperwork/formtemplates/arrowright.png
  pkg/assets/paperwork/formtemplates/shipment_summary_worksheet_page1.png
  pkg/assets/paperwork/formtemplates/shipment_summary_worksheet_page2.png
  pkg/assets/paperwork/formtemplates/shipment_summary_worksheet_page3.png
  pkg/notifications/move_approved.go
  pkg/notifications/move_canceled.go
  pkg/notifications/move_payment_reminder.go
  pkg/notifications/move_reviewed.go
  pkg/notifications/move_submitted.go
  pkg/notifications/reweigh_requested.go
  pkg/notifications/user_account_modified.go
  pkg/paperwork/evaluation_report_form_creator.go
  pkg/paperwork/formtemplates/form1203template.png
  pkg/paperwork/shipment_summary_worksheet.go
  pkg/services/paperwork/form_creator_test.go
  scripts/README.md
  scripts/gen-assets
  scripts/run-e2e-mtls-test-docker
  scripts/run-e2e-test-docker
  scripts/run-server-test
Labels: ttv, ready-to-merge

#9438 [Mb-14208, MB-12009] Track uploads and deletions of orders and amended orders files on move history table
  pkg/services/move_history/move_history_fetcher_test.go
  pkg/services/query/sql_scripts/move_history_fetcher.sql
  src/constants/MoveHistory/Database/Tables.js
  src/constants/MoveHistory/EventTemplates/CreateUpload/createUpload.jsx
  src/constants/MoveHistory/EventTemplates/CreateUpload/createUpload.test.jsx
  src/constants/MoveHistory/EventTemplates/DeleteUpload/deleteUpload.jsx
  src/constants/MoveHistory/EventTemplates/DeleteUpload/deleteUpload.test.jsx
  src/constants/MoveHistory/EventTemplates/UploadAmendedOrders/uploadAmendedOrders.jsx
  src/constants/MoveHistory/EventTemplates/UploadAmendedOrders/uploadAmendedOrders.test.jsx
  src/constants/MoveHistory/EventTemplates/index.js
  src/constants/MoveHistory/EventTemplates/uploadAmendedOrders.js
  src/constants/MoveHistory/UIDisplay/Operations.js
Labels: Pamplemoose

#9467 [MB-14370] requestShipmentReweigh template and testing refactor
  src/constants/MoveHistory/EventTemplates/RequestShipmentReweigh/requestShipmentReweigh.jsx
  src/constants/MoveHistory/EventTemplates/RequestShipmentReweigh/requestShipmentReweigh.test.jsx
  src/constants/MoveHistory/EventTemplates/index.js
  src/constants/MoveHistory/EventTemplates/requestShipmentReweigh.js
  src/constants/MoveHistory/EventTemplates/requestShipmentReweigh.test.js
Labels: Pamplemoose

#9465 [MB-14361] acknowledgeExcessWeightRisk refactored template and test
  src/constants/MoveHistory/EventTemplates/AcknowledgeExcessWeightRisk/acknowledgeExcessWeightRisk.jsx
  src/constants/MoveHistory/EventTemplates/AcknowledgeExcessWeightRisk/acknowledgeExcessWeightRisk.test.jsx
  src/constants/MoveHistory/EventTemplates/acknowledgeExcessWeightRisk.test.js
  src/constants/MoveHistory/EventTemplates/index.js
Labels: Pamplemoose

#9472 [ on-call ] Upgrade PSQL to 12.11 for the application
  Makefile
Labels: enhancement, infra, security, ready-to-merge, help wanted

#9409 MB-14207-Display-Scheduled-Delivery-Date
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/m_t_o_shipment.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/testdatagen/scenario/subscenarios.go
  src/types/shipment.js
  swagger-def/definitions/MTOShipment.yaml
  swagger/ghc.yaml
Labels: ttv

#9471 [MB-14375] submitMoveForApproval refactor
  src/constants/MoveHistory/EventTemplates/SubmitMoveForApproval/submitMoveForApproval.jsx
  src/constants/MoveHistory/EventTemplates/SubmitMoveForApproval/submitMoveForApproval.test.jsx
  src/constants/MoveHistory/EventTemplates/index.js
Labels: Pamplemoose

#9474 [MB-14381] setFinancialReviewFlag refactor and now capturing remarks
  src/constants/MoveHistory/Database/FieldMappings.js
  src/constants/MoveHistory/EventTemplates/SetFinancialReviewFlag/setFinancialReviewFlag.jsx
  src/constants/MoveHistory/EventTemplates/SetFinancialReviewFlag/setFinancialReviewFlag.test.jsx
  src/constants/MoveHistory/EventTemplates/index.js
  src/constants/MoveHistory/EventTemplates/setFinancialReviewFlag.js
  src/constants/MoveHistory/EventTemplates/setFinancialReviewFlag.test.js
Labels: Pamplemoose

#9464 MB-14312 Create testdatagen for PPM closeout migration
  pkg/testdatagen/scenario/devseed.go
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/scenario/subscenarios.go
Labels: ttv

#9477 Update golangci-lint to version 1.50.1
  .pre-commit-config.yaml
Labels: dependencies, ttv, ready-to-merge

#9476 MB-14316 Violations and serious incident cells show no data until radio buttons are selected
  src/components/Office/EvaluationReportTable/EvaluationReportTable.jsx
  src/components/Office/EvaluationReportTable/EvaluationReportTable.test.jsx
Labels: ttv
