Repository transcom/mymove, pull requests merged in 2022-11, with the labels that each got.

#9478 [MB-13851] Manage PPM shipment customer homepage payment submitted
  pkg/testdatagen/scenario/shared.go
  src/components/PPMSummaryList/PPMSummaryList.jsx
  src/components/PPMSummaryList/PPMSummaryList.module.scss
  src/components/PPMSummaryList/PPMSummaryList.stories.jsx
  src/components/PPMSummaryList/PPMSummaryList.test.jsx
  src/pages/MyMove/Home/index.stories.jsx
Labels: A-Team, ready-to-merge

#9479 MB-14291 KPI dates in report preview
  cypress/integration/office/qaecsr/qaeFlows.js
  src/components/Office/DefinitionLists/EvaluationReportList.jsx
  src/components/Office/DefinitionLists/EvaluationReportViolationsList.jsx
  src/components/Office/DefinitionLists/EvaluationReportViolationsList.module.scss
  src/components/Office/EvaluationReportPreview/EvaluationReportPreview.jsx
  src/components/Office/EvaluationReportPreview/EvaluationReportPreview.module.scss
  src/components/Office/EvaluationReportPreview/PreviewRow/PreviewRow.jsx
  src/components/Office/EvaluationReportPreview/PreviewRow/PreviewRow.module.scss
  src/components/Office/EvaluationReportPreview/PreviewRow/PreviewRow.test.jsx
  src/components/Office/EvaluationViolationsForm/EvaluationViolationsForm.jsx
  src/components/Office/EvaluationViolationsForm/EvaluationViolationsForm.module.scss
Labels: ttv

#9492 Display Submission Date in Report Preview Modal
  src/components/Office/EvaluationReportPreview/EvaluationReportPreview.jsx
Labels: ttv

#9489 [MB-14296](User Story) Office users can see creation and updates to the backup contact information in the customer profile
  pkg/services/query/sql_scripts/move_history_fetcher.sql
  src/constants/MoveHistory/Database/FieldMappings.js
  src/constants/MoveHistory/Database/Tables.js
  src/constants/MoveHistory/EventTemplates/CreateServiceMemberBackupContact/createServiceMemberBackupContact.jsx
  src/constants/MoveHistory/EventTemplates/CreateServiceMemberBackupContact/createServiceMemberBackupContact.test.jsx
  src/constants/MoveHistory/EventTemplates/UpdateServiceMemberBackupContact/updateServiceMemberBackupContact.jsx
  src/constants/MoveHistory/EventTemplates/UpdateServiceMemberBackupContact/updateServiceMemberBackupContact.test.jsx
  src/constants/MoveHistory/EventTemplates/index.js
  src/constants/MoveHistory/UIDisplay/Operations.js
Labels: Pamplemoose

#9504 MB-14390 Delete Report Bug
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20221028220508_remove_deleted_at_column_from_evaluation_reports.up.sql
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/evaluation_reports/delete_evaluation_report.go
  pkg/gen/ghcapi/ghcoperations/evaluation_reports/delete_evaluation_report_responses.go
  pkg/models/evaluation_report.go
  pkg/services/evaluation_report/evaluation_report_creator_test.go
  pkg/services/evaluation_report/evaluation_report_deleter.go
  pkg/services/evaluation_report/evaluation_report_deleter_test.go
  pkg/services/evaluation_report/evaluation_report_fetcher.go
  pkg/services/evaluation_report/evaluation_report_fetcher_test.go
  pkg/services/evaluation_report/evaluation_report_updater.go
  pkg/services/evaluation_report/evaluation_report_updater_test.go
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: ttv

#9481 [MB-14391] createStandardServiceItem refactor
  src/constants/MoveHistory/EventTemplates/ApproveShipment/createStandardServiceItem.jsx
  src/constants/MoveHistory/EventTemplates/ApproveShipment/createStandardServiceItem.test.jsx
  src/constants/MoveHistory/EventTemplates/createStandardServiceItem.js
  src/constants/MoveHistory/EventTemplates/createStandardServiceItem.test.js
  src/constants/MoveHistory/EventTemplates/index.js
Labels: Pamplemoose

#9484 [MB-14393] request shipment diversion refactor
  src/constants/MoveHistory/EventTemplates/RequestShipmentDiversion/requestShipmentDiversion.jsx
  src/constants/MoveHistory/EventTemplates/RequestShipmentDiversion/requestShipmentDiversion.test.jsx
  src/constants/MoveHistory/EventTemplates/index.js
  src/constants/MoveHistory/EventTemplates/requestShipmentDiversion.js
Labels: Pamplemoose

#9490 [MB-14394] approveShipment refactor
  src/constants/MoveHistory/EventTemplates/ApproveShipment/approveShipment.jsx
  src/constants/MoveHistory/EventTemplates/ApproveShipment/approveShipment.test.jsx
  src/pages/Office/MoveHistory/MoveHistory.test.jsx
Labels: Pamplemoose

#9466 MB-14362 convert backend tests to use transactions
  pkg/dates/calculators_test.go
  pkg/db/dberr/dberr_test.go
  pkg/db/dberr/errors_test.go
  pkg/services/ghcimport/ghc_rateengine_importer_test.go
  pkg/services/tsp/transportation_service_provider_performance_fetcher_test.go
  pkg/services/tsp/transportation_service_provider_performance_list_fetcher_test.go
  pkg/testingsuite/pop_suite_test.go
Labels: ready-to-merge, spark

#9395 MB-13330-progear-form-nt
  src/components/Customer/PPM/Closeout/ProGearForm/ProGearForm.jsx
  src/components/Customer/PPM/Closeout/ProGearForm/ProGearForm.module.scss
  src/components/Customer/PPM/Closeout/ProGearForm/ProGearForm.test.jsx
  src/components/Customer/PPM/Closeout/WeightTicketForm/WeightTicketForm.jsx
  src/components/Customer/PPM/Closeout/WeightTicketForm/WeightTicketForm.module.scss
  src/components/Customer/PPM/Closeout/WeightTicketUpload/WeightTicketUpload.jsx
  src/components/Customer/PPM/Closeout/WeightTicketUpload/WeightTicketUpload.module.scss
  src/components/form/fields/MaskedTextField/MaskedTextField.jsx
  src/pages/MyMove/PPM/Closeout/ProGear/ProGear.jsx
Labels: A-Team

#9453 MB-14264: relocate w2 address on about page and integration
  .storybook/storybook.scss
  cypress/support/ppmCustomerShared.js
  pkg/handlers/internalapi/internal/payloads/payload_to_model.go
  pkg/handlers/internalapi/mto_shipment_test.go
  pkg/services/mto_shipment/mto_shipment_fetcher.go
  pkg/services/ppmshipment/ppm_shipment_updater.go
  pkg/services/ppmshipment/ppm_shipment_updater_test.go
  pkg/services/ppmshipment/validation.go
  src/components/Customer/PPM/Closeout/AboutForm/AboutForm.jsx
  src/components/Customer/PPM/Closeout/AboutForm/AboutForm.module.scss
  src/components/Customer/PPM/Closeout/AboutForm/AboutForm.stories.jsx
  src/components/Customer/PPM/Closeout/AboutForm/AboutForm.test.jsx
  src/components/Customer/PPM/Closeout/ExpenseForm/ExpenseForm.jsx
  src/components/Customer/PPM/Closeout/ExpenseForm/ExpenseForm.module.scss
  src/components/Customer/PPM/Closeout/FinalCloseoutForm/FinalCloseoutForm.jsx
  src/components/Customer/PPM/Closeout/FinalCloseoutForm/FinalCloseoutForm.module.scss
  src/components/Customer/PPM/Closeout/FinalCloseoutForm/FinalCloseoutForm.stories.jsx
  src/components/Customer/PPM/Closeout/FinalCloseoutForm/FinalCloseoutForm.test.jsx
  src/components/Customer/PPM/PPM.module.scss
  src/pages/MyMove/PPM/Closeout/About/About.jsx
  src/pages/MyMove/PPM/Closeout/About/About.test.jsx
Labels: A-Team, ready-to-merge

#9491 [MB-14395] create basic service item refactor
  src/constants/MoveHistory/EventTemplates/UpdateMoveTaskOrderStatus/createBasicServiceItem.jsx
  src/constants/MoveHistory/EventTemplates/UpdateMoveTaskOrderStatus/createBasicServiceItem.test.jsx
  src/constants/MoveHistory/EventTemplates/createBasicServiceItem.test.js
  src/constants/MoveHistory/EventTemplates/index.js
Labels: Pamplemoose

#9496 [MB-14400] request shipment cancellation refactor
  src/constants/MoveHistory/EventTemplates/RequestShipmentCancellation/requestShipmentCancellation.jsx
  src/constants/MoveHistory/EventTemplates/RequestShipmentCancellation/requestShipmentCancellation.test.jsx
  src/constants/MoveHistory/EventTemplates/index.js
  src/constants/MoveHistory/EventTemplates/requestShipmentCancellation.js
  src/constants/MoveHistory/EventTemplates/requestShipmentCancellation.test.js
  src/pages/Office/MoveHistory/MoveHistoryDetailsSelector.test.jsx
Labels: Pamplemoose

#9497 [MB-14401 update mto shipment status refactor
  src/constants/MoveHistory/EventTemplates/UpdateMTOShipmentStatus/updateMTOShipmentStatus.jsx
  src/constants/MoveHistory/EventTemplates/UpdateMTOShipmentStatus/updateMTOShipmentStatus.test.jsx
  src/constants/MoveHistory/EventTemplates/index.js
  src/constants/MoveHistory/EventTemplates/updateMTOShipmentStatus.js
  src/constants/MoveHistory/EventTemplates/updateMTOShipmentStatus.test.js
Labels: Pamplemoose

#9436 MB-8289 Refactor RequestedShipments Tests
  src/components/Office/RequestedShipments/RequestedShipments.test.jsx
Labels: ready-to-merge, spark

#9510 [MB-14411] Refactor updateMTOReviewedBillableWeightsAt
  src/constants/MoveHistory/EventTemplates/UpdateMTOReviewedBillableWeightAt/updateMTOReviewedBillableWeightsAt.jsx
  src/constants/MoveHistory/EventTemplates/UpdateMTOReviewedBillableWeightAt/updateMTOReviewedBillableWeightsAt.test.jsx
  src/constants/MoveHistory/EventTemplates/index.js
  src/constants/MoveHistory/EventTemplates/updateMTOReviewedBillableWeightsAt.test.js
Labels: Pamplemoose

#9493 [MB-14356] Refactor updateBillableWeight templates
  src/constants/MoveHistory/Database/FieldMappings.js
  src/constants/MoveHistory/Database/WeightFields.js
  src/constants/MoveHistory/EventTemplates/CreateOrders/createEntitlements.test.jsx
  src/constants/MoveHistory/EventTemplates/UpdateAllowances/updateAllowance.test.jsx
  src/constants/MoveHistory/EventTemplates/UpdateAllowances/updateAllowanceByCounselor.test.jsx
  src/constants/MoveHistory/EventTemplates/UpdateBillableWeight/updateBillableWeight.jsx
  src/constants/MoveHistory/EventTemplates/UpdateBillableWeight/updateBillableWeight.test.jsx
  src/constants/MoveHistory/EventTemplates/UpdateBillableWeight/updateBillableWeightAsTIO.jsx
  src/constants/MoveHistory/EventTemplates/UpdateBillableWeight/updateBillableWeightAsTIO.test.jsx
  src/constants/MoveHistory/EventTemplates/UpdateBillableWeight/updateBillableWeightRemarksAsTIO.jsx
  src/constants/MoveHistory/EventTemplates/UpdateBillableWeight/updateBillableWeightRemarksAsTIO.test.jsx
  src/constants/MoveHistory/EventTemplates/index.js
  src/constants/MoveHistory/EventTemplates/updateBillableWeight.js
  src/constants/MoveHistory/EventTemplates/updateBillableWeightAsTIO.js
  src/constants/MoveHistory/EventTemplates/updateBillableWeightAsTIO.test.js
  src/constants/MoveHistory/EventTemplates/updateBillableWeightRemarksAsTIO.js
  src/constants/MoveHistory/EventTemplates/updateBillableWeightRemarksAsTIO.test.js
  src/pages/Office/MoveHistory/LabeledDetails.jsx
Labels: Pamplemoose

#9495 [MB-14399] update move task order status refactor
  src/constants/MoveHistory/EventTemplates/UpdateMoveTaskOrderStatus/updateMoveTaskOrderStatus.jsx
  src/constants/MoveHistory/EventTemplates/UpdateMoveTaskOrderStatus/updateMoveTaskOrderStatus.test.jsx
  src/constants/MoveHistory/EventTemplates/index.js
  src/constants/MoveHistory/EventTemplates/updateMoveTaskOrderStatus.js
  src/constants/MoveHistory/EventTemplates/updateMoveTaskOrderStatus.test.js
Labels: Pamplemoose

#9507 [MB-14417] update service item status refactor
  src/constants/MoveHistory/Database/FieldMappings.js
  src/constants/MoveHistory/EventTemplates/UpdateServiceItemStatus/updateServiceItemStatus.jsx
  src/constants/MoveHistory/EventTemplates/UpdateServiceItemStatus/updateServiceItemStatus.test.jsx
  src/constants/MoveHistory/EventTemplates/index.js
  src/constants/MoveHistory/EventTemplates/updateServiceItemStatus.js
  src/constants/MoveHistory/EventTemplates/updateServiceItemStatus.test.js
Labels: Pamplemoose

#9511 [MB-14449] Remove details type from refactor templates
  src/constants/MoveHistory/EventTemplates/CreateMTOServiceItem/createMTOServiceItemUpdateMoveStatus.test.jsx
  src/constants/MoveHistory/EventTemplates/CreateMTOShipment/createMTOShipment.jsx
  src/constants/MoveHistory/EventTemplates/CreateMTOShipment/createMTOShipment.test.jsx
  src/constants/MoveHistory/EventTemplates/UpdateMTOShipment/updateMTOShipment.test.jsx
  src/constants/MoveHistory/EventTemplates/UpdateOrders/updateOrder.test.jsx
Labels: Pamplemoose

#9226 MB-6682 create and use new 404 page design
  pkg/handlers/routing/routing_init.go
  pkg/handlers/spa_handler.go
  pkg/handlers/spa_handler_test.go
  src/components/NotFound/NotFound.jsx
  src/components/NotFound/NotFound.module.scss
  src/components/NotFound/NotFound.test.jsx
  src/pages/MyMove/Home/Home.module.scss
  src/pages/Office/index.jsx
  src/pages/Office/index.test.jsx
  src/scenes/MyMove/index.test.js
Labels: infra, ready-to-merge

#9530 Fix ready to merge label since master has been renamed to main
  .mergify.yml
Labels: infra, ready-to-merge

#9537 Adds loader-utils to our resolutions in the package.json
  package.json
  yarn.lock
Labels: dependencies, infra

#9532 [ on-call, MB-13659 ] Update branch names in GH actions and Swagger files and CircleCI config
  .circleci/config.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/analyze-bundle.yml
  .github/workflows/front-end-linter.yml
  .github/workflows/happo-tests-master.yml
  .github/workflows/happo-tests.yml
  CONTRIBUTING.md
  CONTRIBUTORS.md
  README.md
  cmd/generate-deploy-notes/main.go
  dangerfile.ts
  pkg/gen/adminapi/doc.go
  pkg/gen/adminapi/embedded_spec.go
  pkg/gen/ordersapi/doc.go
  pkg/gen/ordersapi/embedded_spec.go
  pkg/gen/restapi/doc.go
  pkg/gen/restapi/embedded_spec.go
  scripts/ensure-go-test-coverage
  swagger-def/admin.yaml
  swagger-def/orders.yaml
  swagger/admin.yaml
  swagger/api.yaml
  swagger/orders.yaml
Labels: enhancement, infra, security, ready-to-merge, help wanted, bug

#9534 Revert PR #9390 (upgrade to Pop 6.0.8)
  go.mod
  go.sum
  pkg/testingsuite/pop_suite.go
  pkg/testingsuite/pop_suite_test.go
Labels: ttv

#9519 [MB-14403] create payment request refactor
  src/constants/MoveHistory/EventTemplates/CreatePaymentRequest/createPaymentRequest.jsx
  src/constants/MoveHistory/EventTemplates/CreatePaymentRequest/createPaymentRequest.test.jsx
  src/constants/MoveHistory/EventTemplates/createPaymentRequest.js
  src/constants/MoveHistory/EventTemplates/createPaymentRequest.test.js
  src/constants/MoveHistory/EventTemplates/index.js
  src/pages/Office/MoveHistory/LabeledPaymentRequestDetails.jsx
  src/pages/Office/MoveHistory/LabeledPaymentRequestDetails.test.jsx
  src/pages/Office/MoveHistory/MoveHistoryDetailsSelector.test.jsx
Labels: Pamplemoose

#9535 [MB-14416] refactored template and testing
  src/constants/MoveHistory/EventTemplates/UpdateReweigh/updateReweighWeight.jsx
  src/constants/MoveHistory/EventTemplates/UpdateReweigh/updateReweighWeight.test.jsx
  src/constants/MoveHistory/EventTemplates/index.js
  src/constants/MoveHistory/EventTemplates/updateReweighWeight.js
  src/constants/MoveHistory/EventTemplates/updateReweighWeight.test.js
Labels: Pamplemoose

#9520 [MB-14404] proof of service upload refactor
  src/constants/MoveHistory/EventTemplates/CreateUpload/proofOfServiceDocUpload.jsx
  src/constants/MoveHistory/EventTemplates/CreateUpload/proofOfServiceDocUpload.test.jsx
  src/constants/MoveHistory/EventTemplates/index.js
  src/constants/MoveHistory/EventTemplates/proofOfServiceDocUpload.js
  src/constants/MoveHistory/EventTemplates/proofOfServiceDocUpload.test.js
Labels: Pamplemoose

#9542 [MB-14402] createMtoShipmentAgent refactor
  src/constants/MoveHistory/EventTemplates/UpdateMTOShipment/createMTOShipmentAgent.jsx
  src/constants/MoveHistory/EventTemplates/UpdateMTOShipment/createMTOShipmentAgent.test.jsx
  src/constants/MoveHistory/EventTemplates/createMTOShipmentAgent.js
  src/constants/MoveHistory/EventTemplates/createMTOShipmentAgent.test.js
  src/constants/MoveHistory/EventTemplates/index.js
Labels: Pamplemoose

#9536 [MB-14406] null event refactor
  src/constants/MoveHistory/EventTemplates/NullEvent/undefined.jsx
  src/constants/MoveHistory/EventTemplates/NullEvent/undefined.test.jsx
  src/constants/MoveHistory/EventTemplates/undefined.test.js
  src/constants/MoveHistory/TemplateManager.js
Labels: Pamplemoose

#9541 [MB-14414] update mto status service counseling completed refactor
  src/constants/MoveHistory/EventTemplates/UpdateMTOStatusServiceCounselingCompleted/updateMTOStatusServiceCounselingCompleted.jsx
  src/constants/MoveHistory/EventTemplates/UpdateMTOStatusServiceCounselingCompleted/updateMTOStatusServiceCounselingCompleted.test.jsx
  src/constants/MoveHistory/EventTemplates/index.js
  src/constants/MoveHistory/EventTemplates/updateMTOStatusServiceCounselingCompleted.test.js
Labels: Pamplemoose

#9518 MB-14448 Fix flaky QAE cypress tests
  cypress/integration/office/qaecsr/qaeFlows.js
Labels: ttv

#9546 MB-14347 Add closeout office column to moves
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20221104180553_add_closeout_office_move_association.up.sql
  pkg/models/move.go
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/scenario/subscenarios.go
Labels: ttv

#9374 MB-8333 use shipment router in shipment creator
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/handlers/internalapi/api.go
  pkg/handlers/internalapi/mto_shipment_test.go
  pkg/handlers/primeapi/api.go
  pkg/handlers/primeapi/mto_shipment_test.go
  pkg/services/mto_shipment/shipment_router.go
  pkg/services/orchestrators/shipment/shipment_creator.go
  pkg/services/orchestrators/shipment/shipment_creator_test.go
Labels: ready-to-merge, spark

#9545 MB-12540: Integration tests for PPM expense submission
  cypress/integration/milmove/ppms/expenses.js
  src/pages/MyMove/PPM/Closeout/Expenses/Expenses.jsx
  src/pages/MyMove/PPM/Closeout/Expenses/Expenses.test.jsx
Labels: A-Team

#9543 [MB-14461] Create a getMtoShipment label util to for move history events
  src/constants/MoveHistory/EventTemplates/CreateMTOServiceItem/createMTOServiceItem.jsx
  src/constants/MoveHistory/EventTemplates/CreateMTOServiceItem/createMTOServiceItemDimensions.jsx
  src/constants/MoveHistory/EventTemplates/CreateMTOShipment/createMTOShipment.jsx
  src/constants/MoveHistory/EventTemplates/UpdateAddress/createAddress.jsx
  src/constants/MoveHistory/EventTemplates/UpdateAddress/updateAddress.jsx
  src/constants/MoveHistory/EventTemplates/UpdateMTOServiceItem/updateMTOServiceItem.jsx
  src/constants/MoveHistory/EventTemplates/UpdateMTOShipment/updateMTOShipment.jsx
  src/constants/MoveHistory/EventTemplates/UpdateMTOShipmentStatus/updateMTOShipmentStatus.jsx
  src/constants/MoveHistory/EventTemplates/UpdateReweigh/updateReweighWeight.jsx
  src/constants/MoveHistory/EventTemplates/UpdateServiceItemStatus/updateServiceItemStatus.jsx
  src/constants/MoveHistory/EventTemplates/createStandardServiceItem.js
  src/constants/MoveHistory/EventTemplates/updateMTOShipmentAgent.js
  src/utils/formatMtoShipment.js
  src/utils/formatMtoShipment.test.js
Labels: Pamplemoose

#9544 [MB-14412] Refactor updateMtoShipment template and tests
  src/constants/MoveHistory/EventTemplates/UpdateMTOShipment/createPaymentRequestShipmentUpdate.jsx
  src/constants/MoveHistory/EventTemplates/UpdateMTOShipment/createPaymentRequestShipmentUpdate.test.jsx
  src/constants/MoveHistory/EventTemplates/UpdateMTOShipment/createReweighRequestWeightUpdate.jsx
  src/constants/MoveHistory/EventTemplates/UpdateMTOShipment/createReweighRequestWeightUpdate.test.jsx
  src/constants/MoveHistory/EventTemplates/UpdateMTOShipment/updateMTOShipmentAgent.jsx
  src/constants/MoveHistory/EventTemplates/UpdateMTOShipment/updateMTOShipmentAgent.test.jsx
  src/constants/MoveHistory/EventTemplates/UpdateMTOShipment/updateMTOShipmentDeprecatePaymentRequest.jsx
  src/constants/MoveHistory/EventTemplates/UpdateMTOShipment/updateMTOShipmentDeprecatePaymentRequest.test.jsx
  src/constants/MoveHistory/EventTemplates/UpdateMTOShipment/updateMTOShipmentPrimeEstimatedExcessWeight.jsx
  src/constants/MoveHistory/EventTemplates/UpdateMTOShipment/updateMTOShipmentPrimeEstimatedExcessWeight.test.jsx
  src/constants/MoveHistory/EventTemplates/createPaymentRequestShipmentUpdate.test.js
  src/constants/MoveHistory/EventTemplates/createReweightRequestWeightUpdate.test.js
  src/constants/MoveHistory/EventTemplates/index.js
  src/constants/MoveHistory/EventTemplates/updateMTOShipmentAgent.js
  src/constants/MoveHistory/EventTemplates/updateMTOShipmentAgent.test.js
  src/constants/MoveHistory/EventTemplates/updateMTOShipmentDeprecatePaymentRequest.test.js
  src/constants/MoveHistory/EventTemplates/updateMTOShipmentPrimeEstimatedExcessWeight.test.js
Labels: Pamplemoose

#9547 [MB-14415] updatePaymentRequestStatus refactor
  src/constants/MoveHistory/EventTemplates/UpdatePaymentRequestStatus/updatePaymentRequestStatus.jsx
  src/constants/MoveHistory/EventTemplates/UpdatePaymentRequestStatus/updatePaymentRequestStatus.test.jsx
  src/constants/MoveHistory/EventTemplates/index.js
Labels: Pamplemoose

#9553 [MB-14419] update payment request job runner refactor
  src/constants/MoveHistory/EventTemplates/UpdatePaymentRequestJobRunner/updatePaymentRequestJobRunner.jsx
  src/constants/MoveHistory/EventTemplates/UpdatePaymentRequestJobRunner/updatePaymentRequestJobRunner.test.jsx
  src/constants/MoveHistory/EventTemplates/index.js
  src/constants/MoveHistory/EventTemplates/updatePaymentRequestJobRunner.js
  src/constants/MoveHistory/EventTemplates/updatePaymentRequestJobRunner.test.js
  src/constants/paymentRequestStatus.js
  src/utils/formatters.test.js
Labels: Pamplemoose

#9505 MB-14427: Add address service object
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/handlers/internalapi/api.go
  pkg/handlers/internalapi/internal/payloads/payload_to_model.go
  pkg/handlers/internalapi/mto_shipment_test.go
  pkg/handlers/primeapi/api.go
  pkg/handlers/primeapi/mto_shipment_test.go
  pkg/models/ppm_shipment.go
  pkg/services/address.go
  pkg/services/address/address_creator.go
  pkg/services/address/address_creator_test.go
  pkg/services/address/address_service_test.go
  pkg/services/address/address_updater.go
  pkg/services/address/address_updater_test.go
  pkg/services/address/rules.go
  pkg/services/address/validation.go
  pkg/services/ppmshipment/ppm_shipment_updater.go
  pkg/services/ppmshipment/ppm_shipment_updater_test.go
  pkg/services/ppmshipment/validation.go
Labels: A-Team, ready-to-merge

#9344 MB-8674 Move transaction logic to service object
  pkg/handlers/internalapi/internal/payloads/payload_to_model.go
  pkg/handlers/internalapi/moves.go
  pkg/handlers/internalapi/moves_test.go
  pkg/handlers/internalapi/office_test.go
  pkg/handlers/internalapi/personally_procured_move_test.go
  pkg/handlers/internalapi/service_members_test.go
  pkg/models/shipment_summary_worksheet_test.go
  pkg/services/mocks/MoveRouter.go
  pkg/services/move.go
  pkg/services/move/move_router.go
  pkg/services/move/move_router_test.go
  pkg/services/paperwork/form_creator_test.go
  pkg/testdatagen/scenario/e2ebasic.go
  pkg/testdatagen/scenario/shared.go
Labels: ready-to-merge, spark

#9562 MB-14424: Fixes issue with non-deterministic date causing Happo diffs
  src/pages/MyMove/Home/index.stories.jsx
Labels: A-Team

#9564 [MB-14359] Consolidate sql templates under assets package
  .github/CODEOWNERS
  pkg/assets/assets.go
  pkg/assets/sql_scripts/.README.md
  pkg/assets/sql_scripts/move_history_fetcher.sql
  pkg/services/query/query_sql.go
  pkg/services/query/sql_scripts/test_empty.sql
Labels: Pamplemoose

#9578 MB-14409 - Remove update move task order endpoint
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/move_task_order/update_move_task_order.go
  pkg/gen/ghcapi/ghcoperations/move_task_order/update_move_task_order_parameters.go
  pkg/gen/ghcapi/ghcoperations/move_task_order/update_move_task_order_responses.go
  pkg/gen/ghcapi/ghcoperations/move_task_order/update_move_task_order_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  src/constants/MoveHistory/EventTemplates/index.js
  src/constants/MoveHistory/EventTemplates/updateMoveTaskOrder.js
  src/pages/Office/MoveHistory/MoveHistoryDetailsSelector.test.jsx
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: Pamplemoose

#9540 MB-14315 Display Observed Pickup & Delivery Date as optional
  src/components/Office/EvaluationForm/EvaluationForm.jsx
  src/components/Office/EvaluationForm/EvaluationForm.module.scss
Labels: ttv

#9502 [MB-14168] backend handler and service object for creating and updating progear
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/pro_gear_weight_ticket.go
  pkg/gen/internalapi/configure_mymove.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalapi/internaloperations/mymove_api.go
  pkg/gen/internalapi/internaloperations/ppm/create_pro_gear_weight_ticket.go
  pkg/gen/internalapi/internaloperations/ppm/create_pro_gear_weight_ticket_parameters.go
  pkg/gen/internalapi/internaloperations/ppm/create_pro_gear_weight_ticket_responses.go
  pkg/gen/internalapi/internaloperations/ppm/create_pro_gear_weight_ticket_urlbuilder.go
  pkg/gen/internalapi/internaloperations/ppm/update_pro_gear_weight_ticket.go
  pkg/gen/internalapi/internaloperations/ppm/update_pro_gear_weight_ticket_parameters.go
  pkg/gen/internalapi/internaloperations/ppm/update_pro_gear_weight_ticket_responses.go
  pkg/gen/internalapi/internaloperations/ppm/update_pro_gear_weight_ticket_urlbuilder.go
  pkg/gen/internalmessages/pro_gear_weight_ticket.go
  pkg/gen/internalmessages/update_pro_gear_weight_ticket.go
  pkg/handlers/internalapi/api.go
  pkg/handlers/internalapi/internal/payloads/model_to_payload.go
  pkg/handlers/internalapi/internal/payloads/payload_to_model.go
  pkg/handlers/internalapi/progear_weight_ticket.go
  pkg/handlers/internalapi/progear_weight_ticket_test.go
  pkg/services/mocks/ProgearCreator.go
  pkg/services/mocks/ProgearUpdater.go
  pkg/services/mocks/ProgearWeightTicketCreator.go
  pkg/services/mocks/ProgearWeightTicketUpdater.go
  pkg/services/mto_shipment/mto_shipment_fetcher.go
  pkg/services/progear_weight_ticket.go
  pkg/services/progear_weight_ticket/progear_weight_ticket_creator.go
  pkg/services/progear_weight_ticket/progear_weight_ticket_creator_test.go
  pkg/services/progear_weight_ticket/progear_weight_ticket_service_test.go
  pkg/services/progear_weight_ticket/progear_weight_ticket_updater.go
  pkg/services/progear_weight_ticket/progear_weight_ticket_updater_test.go
  pkg/services/progear_weight_ticket/rules.go
  pkg/services/progear_weight_ticket/rules_test.go
  pkg/services/progear_weight_ticket/validation.go
  pkg/services/progear_weight_ticket/validation_test.go
  swagger-def/definitions/ProGearWeightTicket.yaml
  swagger-def/internal.yaml
  swagger/ghc.yaml
  swagger/internal.yaml
Labels: A-Team, ready-to-merge

#9565 MB-13897 Fix race conditions in GHC rate engine importer
  cmd/ghc-pricing-parser/main.go
  pkg/parser/pricing/parse.go
  pkg/services/ghcimport/ghc_rateengine_importer.go
Labels: infra

#9568 [MB-14458] move history should show full address after updating a single field
  src/constants/MoveHistory/EventTemplates/UpdateAddress/createAddress.test.jsx
  src/constants/MoveHistory/EventTemplates/UpdateAddress/updateAddress.jsx
  src/constants/MoveHistory/EventTemplates/UpdateAddress/updateAddress.test.jsx
Labels: Pamplemoose

#9579 [MB-14459] Move history should show correct labels for different orders type
  src/constants/MoveHistory/Database/DateFields.js
  src/constants/MoveHistory/Database/FieldMappings.js
  src/constants/MoveHistory/EventTemplates/UpdateOrders/updateOrder.jsx
  src/constants/MoveHistory/EventTemplates/UpdateOrders/updateOrder.test.jsx
Labels: Pamplemoose

#9531 MB-13877 factory.BuildUser added as new version of testdatagen.makeUser
  pkg/appcontext-linter/appctx.go
  pkg/db/utilities/utilities_test.go
  pkg/factory/shared.go
  pkg/factory/shared_test.go
  pkg/factory/traits.go
  pkg/factory/user_factory.go
  pkg/factory/user_factory_test.go
  pkg/handlers/adminapi/users_test.go
  pkg/handlers/authentication/auth_test.go
  pkg/handlers/internalapi/service_members_test.go
  pkg/handlers/routing/routing_init_test.go
  pkg/models/service_member_test.go
  pkg/models/user_test.go
  pkg/services/admin_user/admin_user_creator_test.go
  pkg/services/move_history/move_history_fetcher_test.go
  pkg/services/office_user/office_user_creator_test.go
  pkg/services/user/user_updater_test.go
Labels: spark

#9596 [MB-14421] Service member can delete uploaded orders
  pkg/handlers/internalapi/uploads_test.go
  pkg/storage/s3.go
  pkg/uploader/uploader.go
  pkg/uploader/uploader_test.go
Labels: Pamplemoose

#9589 MB-14508 - Finish template refactoring
  src/constants/MoveHistory/EventTemplates/ApproveShipment/createStandardServiceItem.jsx
  src/constants/MoveHistory/EventTemplates/ApproveShipment/createStandardServiceItem.test.jsx
  src/constants/MoveHistory/EventTemplates/CreatePaymentRequest/createPaymentRequest.jsx
  src/constants/MoveHistory/EventTemplates/UpdateMTOShipment/updateMTOShipment.jsx
  src/constants/MoveHistory/EventTemplates/UpdateReweigh/createPaymentRequest.jsx
  src/constants/MoveHistory/EventTemplates/UpdateReweigh/createPaymentRequest.test.jsx
  src/constants/MoveHistory/EventTemplates/UpdateReweigh/updatePaymentRequest.jsx
  src/constants/MoveHistory/EventTemplates/UpdateReweigh/updatePaymentRequest.test.jsx
  src/constants/MoveHistory/EventTemplates/index.js
  src/constants/MoveHistory/TemplateManager.js
  src/constants/MoveHistory/UIDisplay/DetailsTypes.js
  src/constants/MoveHistory/UIDisplay/HistoryLogShape.js
  src/pages/Office/MoveHistory/LabeledDetails.jsx
  src/pages/Office/MoveHistory/LabeledPaymentRequestDetails.jsx
  src/pages/Office/MoveHistory/LabeledPaymentRequestDetails.test.jsx
  src/pages/Office/MoveHistory/MoveHistory.jsx
  src/pages/Office/MoveHistory/MoveHistoryDetailsSelector.jsx
  src/pages/Office/MoveHistory/MoveHistoryDetailsSelector.test.jsx
Labels: Pamplemoose

#9560 [MB-14371] Upgrade to go 1.19.3
  .circleci/config.yml
  .go-version
  .tool-versions
  Dockerfile.local
  Dockerfile.migrations_local
  Dockerfile.reviewapp
  Dockerfile.tasks_local
  Dockerfile.tools_local
  Dockerfile.webhook_client
  Dockerfile.webhook_client_dp3
  Dockerfile.webhook_client_local
  Makefile
  README.md
  nix/default.nix
  scripts/run-e2e-mtls-test-docker
  scripts/run-e2e-test-docker
Labels: ttv, ready-to-merge

#9611 MB-14477 - Fix swagger error for current address etag
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/update_customer_payload.go
  pkg/handlers/ghcapi/customer_test.go
  pkg/handlers/ghcapi/internal/payloads/payload_to_model.go
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: Pamplemoose

#9612 [MB-14464] Update milmove-cypress hash to latest one, now with Cypress 8.5.0
  .circleci/config.yml
  cypress/Dockerfile.cypress
Labels: ttv

#9587 [ MB-14300 ] - Performance Improvements to Move History Fetcher
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20221114184433_add_table_name_index_audit_history.up.sql
  pkg/assets/sql_scripts/move_history_fetcher.sql
Labels: Pamplemoose

#9625 [MB-14480] Move history should only show one entry for excess weight notification dismissal
  src/constants/MoveHistory/EventTemplates/AcknowledgeExcessWeightRisk/acknowledgeExcessWeightRisk.jsx
  src/constants/MoveHistory/EventTemplates/AcknowledgeExcessWeightRisk/acknowledgeExcessWeightRisk.test.jsx
Labels: Pamplemoose

#9512 MB-8291 Refactor RequestedShipments Component
  src/components/Office/RequestedShipments/ApprovedRequestedShipments.jsx
  src/components/Office/RequestedShipments/ApprovedRequestedShipments.stories.jsx
  src/components/Office/RequestedShipments/RequestedShipments.test.jsx
  src/components/Office/RequestedShipments/SubmittedRequestedShipments.jsx
  src/components/Office/RequestedShipments/SubmittedRequestedShipments.stories.jsx
  src/pages/Office/MoveDetails/MoveDetails.jsx
  src/pages/Office/MoveDetails/MoveDetails.test.jsx
Labels: ready-to-merge, spark

#9586 [MB-14452] Add W-2 disclaimer on About My PPM page
  src/pages/MyMove/PPM/Closeout/About/About.jsx
  src/pages/MyMove/PPM/Closeout/About/About.test.jsx
  src/pages/MyMove/PPM/Closeout/Closeout.module.scss
Labels: A-Team, ready-to-merge

#9605 MB-14446: Add W-2 info to review screen
  pkg/testdatagen/scenario/e2ebasic.go
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/scenario/subscenarios.go
  src/components/Customer/PPM/Closeout/ReviewItems/ReviewItems.jsx
  src/components/Customer/PPM/Closeout/ReviewItems/ReviewItems.module.scss
  src/utils/ppmCloseout.jsx
Labels: A-Team, ready-to-merge

#9615 [MB-14483] displaying shipment labels for destination SIT service items
  pkg/assets/sql_scripts/move_history_fetcher.sql
  src/constants/MoveHistory/Database/DateFields.js
  src/constants/MoveHistory/Database/FieldMappings.js
  src/constants/MoveHistory/EventTemplates/CreateMTOServiceItem/createMTOServiceItemCustomerContacts.jsx
  src/constants/MoveHistory/EventTemplates/CreateMTOServiceItem/createMTOServiceItemCustomerContacts.test.jsx
Labels: Pamplemoose

#9634 [MB-14533] capture updates to customer information
  src/constants/MoveHistory/EventTemplates/UpdateCustomer/updateCustomer.jsx
  src/constants/MoveHistory/EventTemplates/UpdateCustomer/updateCustomer.test.jsx
  src/constants/MoveHistory/EventTemplates/UpdateServiceMemberBackupContact/updateServiceMemberBackupContact.jsx
  src/constants/MoveHistory/EventTemplates/UpdateServiceMemberBackupContact/updateServiceMemberBackupContact.test.jsx
  src/constants/MoveHistory/EventTemplates/index.js
  src/constants/MoveHistory/UIDisplay/Operations.js
Labels: Pamplemoose

#9624 [MB-14525] Normalize serialized json timestamp fractional second precision in orders audit log test
  pkg/services/move_history/move_history_fetcher_test.go
  pkg/testdatagen/make_re_service.go
Labels: A-Team, ready-to-merge

#9637 [ MB-14478 ] Move history shows creation of MTO agent in move history table and hides deletion when the shipment is deleted
  pkg/assets/sql_scripts/move_history_fetcher.sql
  pkg/services/move_history/move_history_fetcher_test.go
  src/constants/MoveHistory/EventTemplates/DeleteShipment/deleteShipment.jsx
  src/constants/MoveHistory/EventTemplates/UpdateMTOShipment/createMTOShipmentAgent.jsx
  src/constants/MoveHistory/EventTemplates/UpdateMTOShipment/createMTOShipmentAgent.test.jsx
  src/constants/MoveHistory/EventTemplates/UpdateMTOShipment/updateMTOShipmentAgent.jsx
  src/constants/MoveHistory/EventTemplates/UpdateMTOShipment/updateMTOShipmentAgent.test.jsx
  src/utils/formatters.js
Labels: Pamplemoose

#9640 MB-14486 Update react-admin usage of react-router to use latest version
  src/pages/InvalidPermissions/InvalidPermissions.jsx
  src/pages/SignIn/SignIn.jsx
  src/scenes/SystemAdmin/CustomRoutes.jsx
  src/scenes/SystemAdmin/Home.jsx
Labels: ttv

#9643 [MB-14483] including service item name
  pkg/assets/sql_scripts/move_history_fetcher.sql
  src/constants/MoveHistory/EventTemplates/CreateMTOServiceItem/createMTOServiceItemCustomerContacts.test.jsx
Labels: Pamplemoose

#9590 [MB-14210] Adding ppm closeout param to backend
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/queues/get_services_counseling_queue_parameters.go
  pkg/gen/ghcapi/ghcoperations/queues/get_services_counseling_queue_urlbuilder.go
  pkg/handlers/ghcapi/queues.go
  pkg/services/order.go
  pkg/services/order/order_fetcher.go
  pkg/services/order/order_fetcher_test.go
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: ttv, ready-to-merge

#9566 MB-13883 turn on the flag to audit race conditions during build and test time
  scripts/run-server-test
Labels: infra

#9552 MB-14377 remove FE references to selectedMoveType
  src/components/Customer/MtoShipmentForm/MtoShipmentForm.jsx
  src/components/Customer/MtoShipmentForm/MtoShipmentForm.stories.jsx
  src/components/Customer/MtoShipmentForm/MtoShipmentForm.test.jsx
  src/components/Customer/MtoShipmentForm/getShipmentOptions.js
  src/components/Office/ShipmentForm/ShipmentForm.jsx
  src/components/Office/ShipmentForm/ShipmentForm.stories.jsx
  src/components/Office/ShipmentForm/ShipmentForm.test.jsx
  src/pages/MyMove/CreateOrEditMtoShipment.jsx
  src/pages/MyMove/CreateOrEditMtoShipment.test.jsx
  src/pages/MyMove/SelectShipmentType.jsx
  src/pages/Office/EditShipmentDetails/EditShipmentDetails.jsx
  src/pages/Office/ServicesCounselingAddShipment/ServicesCounselingAddShipment.jsx
  src/pages/Office/ServicesCounselingEditShipmentDetails/ServicesCounselingEditShipmentDetails.jsx
  src/scenes/MyMove/getWorkflowRoutes.jsx
  src/scenes/MyMove/getWorkflowRoutes.test.js
  src/scenes/MyMove/index.jsx
  src/scenes/PpmLanding/index.jsx
  src/scenes/Review/ProfileReview.jsx
  src/store/entities/selectors.js
Labels: ready-to-merge, spark

#9621 MB-14492 replace makeUser with factory.BuildUser
  pkg/testdatagen/scenario/shared.go
Labels: ready-to-merge, spark

#9658 MB-14433-Removed prop injection from page components and deleted the base path prop.
  src/pages/Admin/AdminUsers/AdminUserCreate.jsx
  src/pages/Admin/AdminUsers/AdminUserEdit.jsx
  src/pages/Admin/AdminUsers/AdminUserList.jsx
  src/pages/Admin/AdminUsers/AdminUserShow.jsx
  src/pages/Admin/Moves/MoveEdit.jsx
  src/pages/Admin/Moves/MoveList.jsx
  src/pages/Admin/Moves/MoveShow.jsx
  src/pages/Admin/OfficeUsers/OfficeUserCreate.jsx
  src/pages/Admin/OfficeUsers/OfficeUserEdit.jsx
  src/pages/Admin/OfficeUsers/OfficeUserList.jsx
  src/pages/Admin/OfficeUsers/OfficeUserShow.jsx
  src/pages/Admin/Offices/OfficeList.jsx
  src/pages/Admin/Users/UserEdit.jsx
  src/pages/Admin/Users/UserList.jsx
  src/pages/Admin/Users/UserShow.jsx
  src/pages/Admin/WebhookSubscriptions/WebhookSubscriptionCreate.jsx
  src/pages/Admin/WebhookSubscriptions/WebhookSubscriptionEdit.jsx
  src/pages/Admin/WebhookSubscriptions/WebhookSubscriptionShow.jsx
  src/pages/Admin/WebhookSubscriptions/WebhookSubscriptionsList.jsx
Labels: ttv

#9567 Add installation of diffutils to fix Ventura when running the go linter
  Brewfile.local
  nix/default.nix
Labels: infra
