Repository transcom/mymove, pull requests merged in 2022-03, with the labels that each got.

#8217 MB-10118 add sidebar menu item that shows total items of missing information
  cypress/integration/office/servicescounseling/servicesCounselingFlows.js
  src/components/LeftNav/LeftNav.jsx
  src/components/LeftNav/LeftNav.module.scss
  src/components/LeftNav/LeftNav.stories.jsx
  src/components/LeftNav/LeftNav.test.jsx
  src/components/LeftNav/index.jsx
  src/components/LeftNavSection/LeftNavSection.jsx
  src/components/LeftNavSection/LeftNavSection.stories.jsx
  src/components/LeftNavSection/LeftNavSection.test.jsx
  src/components/LeftNavTag/LeftNavTag.jsx
  src/components/LeftNavTag/LeftNavTag.module.scss
  src/components/LeftNavTag/LeftNavTag.stories.jsx
  src/components/LeftNavTag/LeftNavTag.test.jsx
  src/pages/Office/MoveDetails/MoveDetails.jsx
  src/pages/Office/MoveDetails/MoveDetails.test.jsx
  src/pages/Office/MovePaymentRequests/MovePaymentRequests.jsx
  src/pages/Office/MovePaymentRequests/MovePaymentRequests.module.scss
  src/pages/Office/MovePaymentRequests/MovePaymentRequests.test.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.test.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.test.jsx
  src/pages/Office/ServicesCounselingMoveInfo/ServicesCounselingTab.module.scss
  src/pages/Office/TXOMoveInfo/TXOTab.module.scss
Labels: roci, ready-to-merge

#8200 MB-10673 Add callout to est weight display if any shipments are non GHC
  src/components/Office/WeightDisplay/WeightDisplay.module.scss
  src/components/Office/WeightDisplay/WeightDisplay.stories.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.test.jsx
  src/pages/Office/MoveTaskOrder/moveTaskOrderUnitTestData.js
Labels: roci

#8210 MB-11074: Use storage facility address for NTS and NTS-release in billable weight review
  src/components/Office/BillableWeight/ShipmentCard/ShipmentCard.jsx
  src/components/Office/BillableWeight/ShipmentCard/ShipmentCard.stories.jsx
  src/components/Office/BillableWeight/ShipmentCard/ShipmentCard.test.jsx
  src/pages/Office/ReviewBillableWeight/ReviewBillableWeight.jsx
Labels: ready-to-merge

#8114 [MB-11454] PO9 - History and Audit Logging POC
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20220201170324_audit_trigger.up.sql
  migrations/app/schema/20220201202113_add_audit_trigger_tables.up.sql
  pkg/audit/context.go
  pkg/auth/authentication/auth.go
  pkg/auth/authentication/devlocal.go
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/move/get_move_history.go
  pkg/gen/ghcapi/ghcoperations/move/get_move_history_parameters.go
  pkg/gen/ghcapi/ghcoperations/move/get_move_history_responses.go
  pkg/gen/ghcapi/ghcoperations/move/get_move_history_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/ghcmessages/move_audit_histories.go
  pkg/gen/ghcmessages/move_audit_history.go
  pkg/gen/ghcmessages/move_audit_history_item.go
  pkg/gen/ghcmessages/move_audit_history_items.go
  pkg/gen/ghcmessages/move_history.go
  pkg/handlers/contexts.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/move.go
  pkg/handlers/ghcapi/move_history.go
  pkg/handlers/ghcapi/move_history_test.go
  pkg/handlers/ghcapi/move_task_order.go
  pkg/handlers/internalapi/orders.go
  pkg/handlers/internalapi/service_members.go
  pkg/handlers/mocks/HandlerContext.go
  pkg/handlers/primeapi/mto_service_item.go
  pkg/middleware/openapi.go
  pkg/migrate/Exec.go
  pkg/models/audit_history.go
  pkg/models/move_history.go
  pkg/models/service_member.go
  pkg/services/mocks/MoveHistoryFetcher.go
  pkg/services/move/move_fetcher.go
  pkg/services/move_history.go
  pkg/services/move_history/move_history_fetcher.go
  pkg/services/move_history/move_history_fetcher_alt2.go
  pkg/services/move_history/move_history_fetcher_test.go
  pkg/services/move_history/move_history_service_test.go
  src/constants/queryKeys.js
  src/hooks/queries.js
  src/pages/Office/MoveHistory/MoveHistory.jsx
  src/pages/Office/TXOMoveInfo/TXOMoveInfo.jsx
  src/services/ghcApi.js
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: Pamplemoose, ready-to-merge

#8214 MB-11553 Add ability to create PPM Shipments
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/create_p_p_m_shipment.go
  pkg/gen/internalmessages/create_shipment.go
  pkg/handlers/internalapi/api.go
  pkg/handlers/internalapi/internal/payloads/payload_to_model.go
  pkg/handlers/internalapi/mto_shipment.go
  pkg/handlers/internalapi/mto_shipment_test.go
  pkg/services/mocks/PPMShipmentCreator.go
  pkg/services/ppmshipment.go
  swagger-def/internal.yaml
  swagger/internal.yaml
Labels: A-Team

#8209 MB-11596 : Add cypress test for PPM booking -dates and location page
  .circleci/config.yml
  cypress/integration/milmove/ppms/dateAndLocation.js
  src/components/Customer/PPMBooking/DateAndLocationForm/DateAndLocationForm.jsx
  src/utils/validation.js
Labels: A-Team

#8227 [MB-10957] Copy old duty station ID values to new duty location columns
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20220228192535_copy_values_to_new_duty_location_cols.up.sql
Labels: ttv

#8233 Make filter more specific to see if it helps
  .circleci/config.yml
Labels: ready-to-merge

#8230 Explicitly define deps for bin/* targets in Makefile
  Makefile
Labels: ready-to-merge

#8224 [MB-10351] Update ShipmentDisplay stories to use error and warning props that more accurately reflect usage in the app
  src/components/Office/ShipmentDisplay/ShipmentDisplay.stories.jsx
Labels: roci, Pamplemoose, ready-to-merge

#8225 MB-11478: Service item calculations use ReferenceDate, label change for NTS-release
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/service_item_param_name.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/service_item_param_name.go
  src/components/Office/ExpandableServiceItemRow/ExpandableServiceItemRow.jsx
  src/components/Office/ReviewServiceItems/ServiceItemCard.jsx
  src/components/Office/ServiceItemCalculations/ServiceItemCalculations.jsx
  src/components/Office/ServiceItemCalculations/ServiceItemCalculations.stories.jsx
  src/components/Office/ServiceItemCalculations/ServiceItemCalculations.test.jsx
  src/components/Office/ServiceItemCalculations/helpers.js
  src/components/Office/ServiceItemCalculations/helpers.test.js
  src/components/Office/ServiceItemCalculations/serviceItemTestParams.js
  src/constants/serviceItems.js
  swagger-def/definitions/ServiceItemParamName.yaml
  swagger/ghc.yaml
  swagger/prime.yaml
Labels: roci

#8226 [MB-10712] Payment request cache fixes and optimizations
  pkg/payment_request/service_param_list_fetcher.go
  pkg/payment_request/service_param_list_fetcher_test.go
  pkg/payment_request/service_param_value_lookups/service_param_value_lookups.go
  pkg/payment_request/service_param_value_lookups/service_params_cache_test.go
  pkg/services/payment_request/payment_request_creator.go
Labels: roci, ready-to-merge

#8234 MB-10118 Fix count that appears in the left nav for the services counselor
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.test.jsx
Labels: roci, Pamplemoose, ready-to-merge

#8235 Error if CircleCI parallelism setting is larger than glob in e2e tests
  .circleci/config.yml
Labels: ready-to-merge

#8185 MB-11554: Update PPMs
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/create_p_p_m_shipment.go
  pkg/gen/internalmessages/p_p_m_shipment.go
  pkg/gen/internalmessages/update_p_p_m_shipment.go
  pkg/gen/internalmessages/update_shipment.go
  pkg/handlers/internalapi/api.go
  pkg/handlers/internalapi/internal/payloads/payload_to_model.go
  pkg/handlers/internalapi/mto_shipment.go
  pkg/handlers/internalapi/mto_shipment_test.go
  pkg/models/ppm_shipment.go
  pkg/services/ppmshipment.go
  pkg/services/ppmshipment/ppm_shipment_updater.go
  pkg/services/ppmshipment/ppm_shipment_updater_test.go
  pkg/services/ppmshipment/rules.go
  pkg/services/ppmshipment/rules_test.go
  pkg/services/ppmshipment/validation.go
  pkg/services/ppmshipment/validation_test.go
  pkg/services/validation.go
  swagger-def/internal.yaml
  swagger/internal.yaml
Labels: A-Team

#8241 Fix mock issue when running db_dev_e2e_populate
  pkg/testdatagen/scenario/shared.go
Labels: roci, ready-to-merge

#8240 [ MB-11826 ] Fix flaky Cypress tests
  Makefile
  cypress/.eslintrc
  cypress/integration/office/servicescounseling/servicesCounselingFlows.js
  cypress/integration/office/txo/tooFlows.js
  package.json
  yarn.lock
Labels: bug, wip, Pamplemoose, ready-to-merge

#8246 [MB-11847] Update all opentelemetry dependencies
  go.mod
  go.sum
  pkg/telemetry/init.go
Labels: roci, dependencies, ready-to-merge

#8244 [MB-11847] Upgrade to go 1.17.7
  .circleci/config.yml
  .go-version
  .tool-versions
  Dockerfile.local
  Dockerfile.migrations_local
  Dockerfile.reviewapp
  Dockerfile.tasks_local
  Dockerfile.tools_local
  Dockerfile.webhook_client
  Dockerfile.webhook_client_dp3
  Dockerfile.webhook_client_local
  Makefile
  README.md
  cypress/Dockerfile.cypress
  nix/default.nix
  scripts/gen-assets
  scripts/gen-server
  scripts/pre-commit-swagger-validate
  scripts/run-e2e-test-docker
Labels: roci, ready-to-merge

#8176 [MB-11630] Remove validation for Prime UI forms for address
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdate.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdateAddress.jsx
Labels: Pamplemoose, ready-to-merge

#8252 MB-11210: Affiliation/Branch type other for customer onboarding
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/affiliation.go
  pkg/gen/ghcmessages/branch.go
  pkg/gen/ghcmessages/counseling_update_allowance_payload.go
  pkg/gen/ghcmessages/order.go
  pkg/gen/ghcmessages/update_allowance_payload.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/affiliation.go
  pkg/gen/ordersapi/embedded_spec.go
  pkg/gen/ordersmessages/affiliation.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/orders_test.go
  pkg/handlers/ordersapi/post_revision_test.go
  pkg/handlers/ordersapi/post_revision_to_orders_test.go
  pkg/services/order/order_updater.go
  pkg/services/order/order_updater_test.go
  src/content/serviceMemberAgencies.js
  swagger-def/definitions/Affiliation.yaml
  swagger-def/ghc.yaml
  swagger-def/orders.yaml
  swagger/ghc.yaml
  swagger/internal.yaml
  swagger/orders.yaml
Labels: ttv

#8260 [MB-11847] Update all pre-commit hooks; fix any issues that were flagged
  .pre-commit-config.yaml
  README.md
  docs/adr/0048-frontend-file-org.md
  docs/adr/0061-use-opentelemetry-for-distributed-tracing.md
  docs/adr/0065-use-office-app-for-prime-ui.md
  docs/adr/index.md
  pkg/services/move/move_router.go
  pkg/services/move/move_router_test.go
  pkg/services/paperwork/form_creator.go
  pkg/services/paperwork/form_creator_test.go
  scripts/check-gopath
  scripts/gen-server
Labels: roci, ready-to-merge

#8255 [ MB-11574 ] Refactor GHC API handlers
  pkg/handlers/ghcapi/customer.go
  pkg/handlers/ghcapi/documents.go
  pkg/handlers/ghcapi/move_task_order.go
  pkg/handlers/ghcapi/mto_agent.go
  pkg/handlers/ghcapi/mto_service_items.go
  pkg/handlers/ghcapi/mto_shipment.go
  pkg/handlers/ghcapi/orders.go
  pkg/handlers/ghcapi/payment_request.go
  pkg/handlers/ghcapi/payment_service_items.go
  pkg/handlers/ghcapi/queues.go
  pkg/handlers/ghcapi/tac.go
Labels: enhancement, Pamplemoose, ready-to-merge

#8216 MB-10675 Add EstimatedWeightsProGear page
  pkg/models/models.go
  pkg/testdatagen/make_entitlement.go
  pkg/testdatagen/make_personally_procured_move.go
  pkg/testdatagen/make_ppm_shipment.go
  pkg/testdatagen/make_transportation_service_provider.go
  pkg/testdatagen/make_weight_ticket_set_document.go
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/scenario/subscenarios.go
  pkg/testdatagen/shared.go
  src/components/Customer/PPMBooking/EstimatedWeightsProGearForm/EstimatedWeightsProGearForm.jsx
  src/components/Customer/PPMBooking/EstimatedWeightsProGearForm/EstimatedWeightsProGearForm.test.jsx
  src/components/Customer/PPMBooking/PPMBooking.module.scss
  src/components/form/fields/MaskedTextField/MaskedTextField.jsx
  src/pages/MyMove/CreateOrEditMtoShipment.test.jsx
  src/pages/MyMove/PPMBooking/DateAndLocation/DateAndLocation.jsx
  src/pages/MyMove/PPMBooking/DateAndLocation/DateAndLocation.module.scss
  src/pages/MyMove/PPMBooking/DateAndLocation/DateAndLocation.test.jsx
  src/pages/MyMove/PPMBooking/EstimatedIncentive/EstimatedIncentive.jsx
  src/pages/MyMove/PPMBooking/EstimatedIncentive/EstimatedIncentive.module.scss
  src/pages/MyMove/PPMBooking/EstimatedWeightsProGear/EstimatedWeightsProGear.jsx
  src/pages/MyMove/PPMBooking/EstimatedWeightsProGear/EstimatedWeightsProGear.test.jsx
  src/pages/MyMove/PPMBooking/PPMBooking.module.scss
  src/scenes/MyMove/index.jsx
  src/styles/form.module.scss
  src/types/customerShapes.js
Labels: A-Team

#8269 [MB-11847] Update yarn.lock
  yarn.lock
Labels: roci, ready-to-merge

#8242 [MB-10957] Read from new duty location columns
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20220308211442_update_origin_duty_location_to_gbloc_view.up.sql
  pkg/handlers/ghcapi/queues.go
  pkg/models/duty_location.go
  pkg/models/move.go
  pkg/models/order.go
  pkg/models/queue.go
  pkg/models/service_member.go
  pkg/models/shipment_summary_worksheet.go
  pkg/models/shipment_summary_worksheet_test.go
  pkg/notifications/move_payment_reminder.go
  pkg/notifications/move_payment_reminder_test.go
  pkg/paperwork/shipment_summary.go
  pkg/paperwork/shipment_summary_test.go
  pkg/services/duty_stations/load_duty_stations.go
  pkg/services/order.go
  pkg/services/order/order_fetcher.go
  pkg/services/payment_request/payment_request_list_fetcher.go
Labels: ttv, ready-to-merge

#8265 [ MB-11660 ] Refactor Internal API handlers
  pkg/handlers/internalapi/access_code.go
  pkg/handlers/internalapi/addresses.go
  pkg/handlers/internalapi/backup_contacts.go
  pkg/handlers/internalapi/calendar.go
  pkg/handlers/internalapi/documents.go
  pkg/handlers/internalapi/dps_auth_cookie_url.go
  pkg/handlers/internalapi/duty_locations.go
  pkg/handlers/internalapi/duty_stations.go
  pkg/handlers/internalapi/entitlements.go
  pkg/handlers/internalapi/generic_move_documents.go
  pkg/handlers/internalapi/move_documents.go
  pkg/handlers/internalapi/move_queue_items.go
  pkg/handlers/internalapi/moves.go
  pkg/handlers/internalapi/moving_expense_documents.go
  pkg/handlers/internalapi/mto_shipment.go
  pkg/handlers/internalapi/office.go
  pkg/handlers/internalapi/orders.go
  pkg/handlers/internalapi/personally_procured_move.go
  pkg/handlers/internalapi/personally_procured_move_attachments.go
  pkg/handlers/internalapi/personally_procured_move_estimate.go
  pkg/handlers/internalapi/personally_procured_move_incentive.go
  pkg/handlers/internalapi/personally_procured_move_sit_estimate.go
  pkg/handlers/internalapi/postal_codes.go
  pkg/handlers/internalapi/service_members.go
  pkg/handlers/internalapi/signed_certifications.go
  pkg/handlers/internalapi/transportation_offices.go
  pkg/handlers/internalapi/uploads.go
  pkg/handlers/internalapi/users.go
  pkg/handlers/internalapi/weight_ticket_set_documents.go
Labels: enhancement, Pamplemoose, ready-to-merge

#8254 [MB-11486] Add assertions around details on customer reviewing NTS shipment info
  cypress/integration/mymove/nts.js
Labels: roci, ready-to-merge

#8251 MB-11597: Cypress test for estimated weights and progear
  cypress/integration/milmove/ppms/dateAndLocation.js
  cypress/integration/milmove/ppms/estimatedWeightsProgear.js
  pkg/testdatagen/scenario/e2ebasic.go
  pkg/testdatagen/scenario/subscenarios.go
Labels: A-Team

#8272 [ MB-11902 ] Update descriptions for documentation
  pkg/gen/adminapi/adminoperations/mymove_api.go
  pkg/gen/adminapi/doc.go
  pkg/gen/adminapi/embedded_spec.go
  pkg/gen/ghcapi/doc.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/internalapi/doc.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalapi/internaloperations/mymove_api.go
  pkg/gen/ordersapi/doc.go
  pkg/gen/ordersapi/embedded_spec.go
  pkg/gen/ordersapi/ordersoperations/mymove_api.go
  pkg/gen/primeapi/doc.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/mymove_api.go
  pkg/gen/supportapi/doc.go
  pkg/gen/supportapi/embedded_spec.go
  pkg/gen/supportapi/supportoperations/mymove_api.go
  swagger-def/admin.yaml
  swagger-def/ghc.yaml
  swagger-def/info/admin_description.md
  swagger-def/info/ghc_description.md
  swagger-def/info/internal_description.md
  swagger-def/info/orders_description.md
  swagger-def/info/prime_description.md
  swagger-def/info/support_description.md
  swagger-def/internal.yaml
  swagger-def/orders.yaml
  swagger-def/prime.yaml
  swagger-def/support.yaml
  swagger/admin.yaml
  swagger/ghc.yaml
  swagger/internal.yaml
  swagger/orders.yaml
  swagger/prime.yaml
  swagger/support.yaml
Labels: ready-to-merge

#8264 [MB-11696] PPM modify pricer param lookups to not require MTO service items
  pkg/payment_request/service_param_value_lookups/contract_code_lookup_test.go
  pkg/payment_request/service_param_value_lookups/distance_zip3_lookup.go
  pkg/payment_request/service_param_value_lookups/distance_zip3_lookup_test.go
  pkg/payment_request/service_param_value_lookups/distance_zip5_lookup.go
  pkg/payment_request/service_param_value_lookups/distance_zip5_lookup_test.go
  pkg/payment_request/service_param_value_lookups/eia_fuel_price_lookup_test.go
  pkg/payment_request/service_param_value_lookups/lookup_query_helpers_test.go
  pkg/payment_request/service_param_value_lookups/number_days_sit_lookup_test.go
  pkg/payment_request/service_param_value_lookups/service_area_lookup_test.go
  pkg/payment_request/service_param_value_lookups/service_params_cache_test.go
  pkg/payment_request/service_param_value_lookups/services_schedule_lookup_test.go
  pkg/payment_request/service_param_value_lookups/sit_schedule_lookup_test.go
  pkg/testdatagen/make_re_contract.go
  pkg/testdatagen/make_re_domestic_service_area.go
  pkg/testdatagen/make_re_zip3.go
  pkg/testdatagen/make_service_param.go
Labels: A-Team

#8278 MB-11799 Remove commented out unit tests
  pkg/services/move_history/move_history_fetcher_test.go
Labels: Pamplemoose, ready-to-merge

#8270 [MB-11580] Add helper function to get history log display name
  src/constants/historyLogUIDisplayName.js
  src/constants/historyLogUIDisplayName.test.js
Labels: Pamplemoose, ready-to-merge

#8257 MB-10677-Advance-DB
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20220304192644_archive-reimbursements-table.up.sql
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/p_p_m_shipment.go
  pkg/handlers/internalapi/internal/payloads/model_to_payload.go
  pkg/handlers/internalapi/mto_shipment_test.go
  pkg/handlers/internalapi/office_test.go
  pkg/models/ppm_shipment.go
  pkg/models/reimbursement.go
  swagger-def/internal.yaml
  swagger/internal.yaml
Labels: A-Team

#8271 [ MB-11794 ] Update fetch query to show TOO approves move details
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/move_audit_history.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/models/audit_history.go
  pkg/services/move_history/move_history_fetcher.go
  pkg/services/move_history/move_history_fetcher_test.go
  pkg/testdatagen/make_audit_history.go
  pkg/testdatagen/shared.go
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: Pamplemoose, ready-to-merge

#8276 [MB-10957] Start writing to renamed duty location fields
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20220308221248_fix_duty_station_triggers.up.sql
  pkg/models/order.go
  pkg/models/service_member.go
Labels: ttv, ready-to-merge

#8259 MB-11337 integrate move history table
  src/components/Office/TXOTabNav/TXOTabNav.jsx
  src/constants/historyLogUIDisplayName.js
  src/hooks/queries.js
  src/pages/Office/MoveHistory/ModifiedBy.jsx
  src/pages/Office/MoveHistory/ModifiedBy.module.scss
  src/pages/Office/MoveHistory/ModifiedBy.test.jsx
  src/pages/Office/MoveHistory/MoveHistory.jsx
  src/pages/Office/MoveHistory/MoveHistory.module.scss
  src/pages/Office/MoveHistory/MoveHistory.test.jsx
  src/pages/Office/TXOMoveInfo/TXOMoveInfo.test.jsx
Labels: Pamplemoose, ready-to-merge

#8277 [MB-11487] Add assertions around details on customer reviewing NTS-release shipment info
  cypress/integration/mymove/ntsr.js
Labels: roci, ready-to-merge

#8280 [MB-11940] Adding Cypress tests for NTS-release as SC
  cypress/integration/office/servicescounseling/servicesCounselingNTS.js
  cypress/integration/office/servicescounseling/servicesCounselingNTSR.js
  pkg/testdatagen/scenario/e2ebasic.go
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/scenario/subscenarios.go
  src/components/Office/DefinitionLists/NTSRShipmentInfoList.jsx
Labels: roci, ready-to-merge

#8275 MB-11037: Advance Form for PPM booking on storybook
  src/components/Customer/PPMBooking/Advance/AdvanceForm.jsx
  src/components/Customer/PPMBooking/Advance/AdvanceForm.stories.jsx
  src/components/Customer/PPMBooking/Advance/AdvanceForm.test.jsx
  src/components/form/fields/MaskedTextField/MaskedTextField.jsx
  src/components/form/fields/MaskedTextField/MaskedTextField.module.scss
  src/utils/incentives.js
  src/utils/incentives.test.js
Labels: A-Team

#8295 [MB-11938] Update all opentelemetry dependencies to 1.5.0
  go.mod
  go.sum
Labels: roci, dependencies, ready-to-merge

#8282 [MB-10956] Duty Station Renaming Cleanup Part 1: Remove Order.NewDutyStation
  pkg/handlers/ghcapi/move_history_test.go
  pkg/models/order.go
  pkg/models/order_test.go
  pkg/models/service_member.go
  pkg/models/service_member_test.go
  pkg/services/support/move_task_order/move_task_order_creator.go
  pkg/testdatagen/make_order.go
  pkg/testdatagen/shared.go
Labels: ttv, ready-to-merge

#8316 [MB-11938] Update all opentelemetry dependencies
  go.mod
  go.sum
Labels: roci, dependencies, ready-to-merge

#8302 [MB-11991] Update pre-commit to 2.17.0; fix hook URLs to remove deprecated git protocol
  .circleci/config.yml
  .pre-commit-config.yaml
  Dockerfile.local
  Dockerfile.migrations_local
  Dockerfile.reviewapp
  Dockerfile.tasks_local
  Dockerfile.tools_local
  Dockerfile.webhook_client
  Dockerfile.webhook_client_dp3
  Dockerfile.webhook_client_local
  Makefile
  cypress/Dockerfile.cypress
  scripts/gen-assets
  scripts/gen-server
  scripts/pre-commit-swagger-validate
  scripts/run-e2e-test-docker
Labels: roci, ready-to-merge

#8314 [MB-12007] Remove CAC access for jacquelineIO, jaynawallaceTRUSS
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20220321142756_remove_cac_jacquelineio_jaynawallacetruss.up.sql
Labels: roci

#8319 MB-11984 - Stop auto-approving moves when updating orders
  pkg/handlers/ghcapi/orders_test.go
  pkg/services/order/order_updater.go
  pkg/services/order/order_updater_test.go
Labels: Pamplemoose

#8325 MB-11972 - Upgrade alpine from 3.14.4 to 3.15.2
  Dockerfile.e2e
  Dockerfile.migrations
  Dockerfile.migrations_local
  Dockerfile.reviewapp
  Dockerfile.tools
  Dockerfile.tools_local
Labels: dependencies, Pamplemoose, ready-to-merge

#8283 [MB-10956] Duty Station Renaming Cleanup Part 2: Clean up database
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20220315231205_duty_station_rename_cleanup.up.sql
Labels: ttv, ready-to-merge

#8329 MB-11804 - Add comment for audit_history.client_query
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20220323190113_add_comment_for_audit_history_client_query_column.up.sql
Labels: Pamplemoose, ready-to-merge

#8312 [MB-11038] Update customer review page to use new PPMShipment card and data
  pkg/models/move.go
  src/components/Customer/Review/AddShipmentModal/AddShipmentModal.jsx
  src/components/Customer/Review/AddShipmentModal/AddShipmentModal.module.scss
  src/components/Customer/Review/OrdersTable/OrdersTable.jsx
  src/components/Customer/Review/OrdersTable/OrdersTable.stories.jsx
  src/components/Customer/Review/OrdersTable/index.stories.jsx
  src/components/Customer/Review/ProfileTable/ProfileTable.jsx
  src/components/Customer/Review/ProfileTable/ProfileTable.stories.jsx
  src/components/Customer/Review/ProfileTable/index.stories.jsx
  src/components/Customer/Review/Review.module.scss
  src/components/Customer/Review/Review.stories.jsx
  src/components/Customer/Review/ShipmentCard/DeliveryDisplay.jsx
  src/components/Customer/Review/ShipmentCard/HHGShipmentCard/HHGShipmentCard.jsx
  src/components/Customer/Review/ShipmentCard/HHGShipmentCard/HHGShipmentCard.test.jsx
  src/components/Customer/Review/ShipmentCard/NTSRShipmentCard/NTSRShipmentCard.jsx
  src/components/Customer/Review/ShipmentCard/NTSRShipmentCard/NTSRShipmentCard.test.jsx
  src/components/Customer/Review/ShipmentCard/NTSShipmentCard/NTSShipmentCard.jsx
  src/components/Customer/Review/ShipmentCard/NTSShipmentCard/NTSShipmentCard.test.jsx
  src/components/Customer/Review/ShipmentCard/PPMShipmentCard/PPMShipmentCard.jsx
  src/components/Customer/Review/ShipmentCard/PPMShipmentCard/PPMShipmentCard.test.jsx
  src/components/Customer/Review/ShipmentCard/PPMShipmentCard/index.jsx
  src/components/Customer/Review/ShipmentCard/PPMShipmentCard/index.test.jsx
  src/components/Customer/Review/ShipmentCard/PickupDisplay.jsx
  src/components/Customer/Review/ShipmentCard/ShipmentCard.module.scss
  src/components/Customer/Review/ShipmentCard/ShipmentCard.stories.jsx
  src/components/Customer/Review/ShipmentCard/index.jsx
  src/components/Customer/Review/Summary/Summary.jsx
  src/components/Customer/Review/Summary/Summary.module.scss
  src/components/Customer/Review/Summary/Summary.test.jsx
  src/components/Customer/modals/CustomerModals.stories.jsx
  src/pages/MyMove/Review/Review.jsx
  src/pages/MyMove/Review/Review.test.jsx
  src/scenes/MyMove/getWorkflowRoutes.jsx
  src/scenes/Review/Edit.jsx
  src/shared/styles/_mixins.scss
  src/types/customerShapes.js
Labels: A-Team

#8341 [ MB-12041 ] Refactor AuditableAppCtx
  pkg/handlers/contexts.go
  pkg/handlers/internalapi/uploads.go
  pkg/handlers/mocks/HandlerContext.go
Labels: bug, Pamplemoose

#8304 [ MB-11958 ] Refactor CreateUploadHandler & fix tests
  pkg/handlers/contexts.go
  pkg/handlers/internalapi/uploads.go
  pkg/uploader/uploader.go
Labels: bug, Pamplemoose, ready-to-merge

#8315 MB-11970 hide deleted shipments
  pkg/handlers/internalapi/mto_shipment.go
  pkg/services/mto_shipment/mto_shipment_fetcher.go
  pkg/services/query/query_builder.go
  src/components/Customer/Review/Summary/Summary.jsx
Labels: ttv

#8346 MB-11579 framework for formatting history data details
  src/constants/historyLogUIDisplayName.js
  src/pages/Office/MoveHistory/MoveHistory.jsx
  src/pages/Office/MoveHistory/MoveHistoryDetailsSelector.jsx
  src/pages/Office/MoveHistory/MoveHistoryDetailsSelector.test.jsx
  src/pages/Office/MoveHistory/PlainTextDetails.jsx
  src/pages/Office/MoveHistory/PlainTextDetails.test.jsx
Labels: Pamplemoose

#8348 [ MB-12050 ] Refactor GHCAPI handlers for AuditableAppContextFromRequestWithErrors
  pkg/apperror/errors.go
  pkg/handlers/ghcapi/customer.go
  pkg/handlers/ghcapi/documents.go
  pkg/handlers/ghcapi/move.go
  pkg/handlers/ghcapi/move_history.go
  pkg/handlers/ghcapi/move_task_order.go
  pkg/handlers/ghcapi/mto_agent.go
  pkg/handlers/ghcapi/mto_service_items.go
  pkg/handlers/ghcapi/mto_shipment.go
  pkg/handlers/ghcapi/orders.go
  pkg/handlers/ghcapi/payment_request.go
  pkg/handlers/ghcapi/payment_service_items.go
  pkg/handlers/ghcapi/queues.go
  pkg/handlers/ghcapi/tac.go
Labels: Pamplemoose, ready-to-merge

#8324 [MB-8450] Edit office app config do that refetching data on window refocus is disabled
  src/App/index.jsx
Labels: roci, ready-to-merge

#8321 MB-10714: Initial Refactor ppm cypress
  cypress/integration/milmove/ppms/dateAndLocation.js
  cypress/integration/milmove/ppms/entireShipment.js
  cypress/integration/milmove/ppms/estimatedIncentive.js
  cypress/integration/milmove/ppms/estimatedWeightsProgear.js
  cypress/support/ppmShared.js
  pkg/testdatagen/scenario/e2ebasic.go
Labels: A-Team

#8313 MB-11598 cypress ppm estimated incentive
  cypress/integration/milmove/ppms/dateAndLocation.js
  cypress/integration/milmove/ppms/entireShipment.js
  cypress/integration/milmove/ppms/estimatedIncentive.js
  cypress/integration/milmove/ppms/estimatedWeightsProgear.js
  cypress/support/ppmShared.js
  pkg/testdatagen/scenario/e2ebasic.go
  pkg/testdatagen/scenario/shared.go
Labels: A-Team

#8339 [ MB-11798 ] add shipment id to query
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/move_audit_history.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/models/audit_history.go
  pkg/services/move_history/move_history_fetcher.go
  pkg/services/move_history/move_history_fetcher_test.go
  pkg/testdatagen/make_audit_history.go
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: Pamplemoose, ready-to-merge

#8351 [ MB-12057 ] Refactor InternalAPI and PrimeAPI to use new Auditable*WithErrors method
  pkg/handlers/internalapi/access_code.go
  pkg/handlers/internalapi/addresses.go
  pkg/handlers/internalapi/backup_contacts.go
  pkg/handlers/internalapi/calendar.go
  pkg/handlers/internalapi/documents.go
  pkg/handlers/internalapi/dps_auth_cookie_url.go
  pkg/handlers/internalapi/duty_locations.go
  pkg/handlers/internalapi/entitlements.go
  pkg/handlers/internalapi/generic_move_documents.go
  pkg/handlers/internalapi/move_documents.go
  pkg/handlers/internalapi/move_queue_items.go
  pkg/handlers/internalapi/moves.go
  pkg/handlers/internalapi/moving_expense_documents.go
  pkg/handlers/internalapi/mto_shipment.go
  pkg/handlers/primeapi/mto_service_item.go
Labels: Pamplemoose

#8349 [MB-11962] e2e tests for TIO/NTS -R
  cypress/integration/office/txo/tioFlows.js
  pkg/testdatagen/scenario/e2ebasic.go
Labels: ttv

#8358 [MB-12057] refactor internal and prime api handlers with new app context pattern
  pkg/handlers/internalapi/office.go
  pkg/handlers/internalapi/orders.go
  pkg/handlers/internalapi/personally_procured_move.go
  pkg/handlers/internalapi/personally_procured_move_attachments.go
  pkg/handlers/internalapi/personally_procured_move_estimate.go
  pkg/handlers/internalapi/personally_procured_move_incentive.go
  pkg/handlers/internalapi/personally_procured_move_sit_estimate.go
  pkg/handlers/internalapi/postal_codes.go
  pkg/handlers/internalapi/service_members.go
  pkg/handlers/internalapi/signed_certifications.go
  pkg/handlers/internalapi/transportation_offices.go
  pkg/handlers/internalapi/uploads.go
  pkg/handlers/internalapi/users.go
  pkg/handlers/internalapi/weight_ticket_set_documents.go
Labels: Pamplemoose, ready-to-merge

#8338 MB-11643 Clear sacType and tacType
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/update_shipment.go
  pkg/handlers/ghcapi/internal/payloads/payload_to_model.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/services/mto_shipment/mto_shipment_updater.go
  pkg/services/mto_shipment/mto_shipment_updater_test.go
  src/components/Office/AccountingCodeSection/AccountingCodeSection.jsx
  src/components/Office/ShipmentForm/ShipmentForm.jsx
  src/components/Office/ShipmentForm/ShipmentForm.test.jsx
  src/utils/formatMtoShipment.js
  swagger-def/definitions/LOATypeNullable.yaml
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: roci, ready-to-merge

#8317 MB-11814-advance-backend
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20220321233308_add_advance_requested.up.sql
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/p_p_m_shipment.go
  pkg/gen/internalmessages/update_p_p_m_shipment.go
  pkg/handlers/converters.go
  pkg/handlers/converters_strfmt.go
  pkg/handlers/internalapi/internal/payloads/model_to_payload.go
  pkg/handlers/internalapi/internal/payloads/payload_to_model.go
  pkg/models/ppm_shipment.go
  pkg/services/ppmshipment/ppm_shipment_updater.go
  pkg/services/ppmshipment/rules.go
  pkg/services/ppmshipment/rules_test.go
  pkg/services/ppmshipment/validation.go
  pkg/services/ppmshipment/validation_test.go
  pkg/services/validation.go
  swagger-def/internal.yaml
  swagger/internal.yaml
Labels: A-Team

#8345 MB-11502 Add E2E tests for NTS Workflow, Prime + Ext Vendor for the TOO
  cypress/integration/office/txo/tooFlows.js
  cypress/integration/office/txo/tooFlowsNTS.js
  package.json
  pkg/testdatagen/scenario/e2ebasic.go
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/scenario/subscenarios.go
  src/components/Office/ShipmentAddresses/ShipmentAddresses.jsx
  yarn.lock
Labels: roci

#8303 MB-10676 Advance Page - frontend
  cypress/integration/milmove/ppms/estimatedIncentive.js
  pkg/handlers/internalapi/internal/payloads/payload_to_model.go
  pkg/handlers/internalapi/mto_shipment_test.go
  pkg/models/models.go
  pkg/testdatagen/scenario/e2ebasic.go
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/scenario/subscenarios.go
  src/pages/MyMove/PPMBooking/Advance/Advance.jsx
  src/pages/MyMove/PPMBooking/Advance/Advance.test.jsx
  src/scenes/MyMove/index.jsx
Labels: A-Team

#8359 [MB-10956] part 5: Remove sort by destination duty station in backend
  pkg/handlers/ghcapi/orders_test.go
  pkg/services/order/order_fetcher.go
  pkg/services/order/order_fetcher_test.go
Labels: ttv, ready-to-merge

#8360 MB-11599 add cypress tests for ppm advance
  cypress/integration/milmove/ppms/advances.js
  cypress/integration/milmove/ppms/dateAndLocation.js
  cypress/integration/milmove/ppms/entireShipment.js
  cypress/integration/milmove/ppms/estimatedIncentive.js
  cypress/integration/milmove/ppms/estimatedWeightsProgear.js
  cypress/support/ppmShared.js
Labels: A-Team, ready-to-merge

#8363 MB-12058 Remove usages of AuditableAppContextFromRequest
  pkg/handlers/contexts.go
  pkg/handlers/mocks/HandlerContext.go
Labels: Pamplemoose, ready-to-merge
