Repository transcom/mymove, pull requests merged in 2022-05, with the labels that each got.

#8538 KC-MB 11875
  src/constants/moveHistoryEventTemplate.js
  src/constants/moveHistoryEventTemplate.test.js
  src/constants/moveHistoryOperations.js
  src/pages/Office/MoveHistory/MoveHistoryDetailsSelector.jsx
  src/pages/Office/MoveHistory/MoveHistoryDetailsSelector.test.jsx
Labels: Pamplemoose

#8529 [ MB-12368 ] TIO should be able to edit Billable Weight
  src/pages/Office/ReviewBillableWeight/ReviewBillableWeight.jsx
  src/services/ghcApi.js
Labels: Pamplemoose, ready-to-merge, bug

#8483 MB-11319 document when the too updates the shipment details
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20220426181840_create_move_history_trigger_for_mto_agents.up.sql
  pkg/services/move_history/move_history_fetcher.go
  pkg/services/move_history/move_history_fetcher_test.go
  src/constants/historyLogUIDisplayName.js
  src/constants/moveHistoryEventTemplate.js
  src/constants/moveHistoryEventTemplate.test.js
  src/pages/Office/MoveHistory/LabeledDetails.jsx
  src/pages/Office/MoveHistory/MoveHistoryDetailsSelector.jsx
  src/utils/formatters.js
Labels: Pamplemoose, ready-to-merge

#8549 MB-12224 - Refactor history updateMoveTaskOrderStatusEvent
  src/constants/moveHistoryEventTemplate.js
  src/constants/moveHistoryEventTemplate.test.js
Labels: Pamplemoose, bug

#8531 Mb 12310 Convert mto_service_item and mto_agent tests
  pkg/services/mto_agent/mto_agent_creator_test.go
  pkg/services/mto_agent/mto_agent_updater_test.go
  pkg/services/mto_service_item/mto_service_item_creator_test.go
  pkg/services/mto_service_item/mto_service_item_updater_test.go
  pkg/services/mto_service_item/mto_service_item_validators_test.go
  pkg/testdatagen/make_mto_agent.go
  pkg/testdatagen/make_mto_service_item.go
Labels: spark

#8552 MB-10401 - Update financial liability paragraph for correct PPM Info
  src/scenes/Legalese/legaleseText.js
Labels: A-Team

#8490 MB-12037: Add scroll to top and clean up navigation
  src/pages/MyMove/PPMBooking/Advance/Advance.jsx
  src/pages/MyMove/PPMBooking/Advance/Advance.test.jsx
  src/pages/MyMove/PPMBooking/DateAndLocation/DateAndLocation.jsx
  src/pages/MyMove/PPMBooking/DateAndLocation/DateAndLocation.test.jsx
  src/pages/MyMove/PPMBooking/EstimatedIncentive/EstimatedIncentive.jsx
  src/pages/MyMove/PPMBooking/EstimatedIncentive/EstimatedIncentive.test.jsx
  src/pages/MyMove/PPMBooking/EstimatedWeightsProGear/EstimatedWeightsProGear.jsx
  src/pages/MyMove/PPMBooking/EstimatedWeightsProGear/EstimatedWeightsProGear.test.jsx
Labels: A-Team

#8518 [ MB-11406 ] Document TIO updates shipment billable weight
  src/constants/historyLogUIDisplayName.js
  src/constants/moveHistoryEventTemplate.js
  src/constants/moveHistoryEventTemplate.test.js
  src/constants/moveHistoryOperations.js
  src/pages/Office/MoveHistory/LabeledDetails.jsx
  src/pages/Office/MoveHistory/LabeledDetails.module.scss
  src/pages/Office/MoveHistory/LabeledDetails.test.jsx
  src/pages/Office/MoveHistory/MoveHistory.jsx
  src/pages/Office/MoveHistory/MoveHistory.module.scss
  src/pages/Office/MoveHistory/MoveHistoryDetailsSelector.jsx
  src/pages/Office/MoveHistory/MoveHistoryDetailsSelector.test.jsx
Labels: Pamplemoose, ready-to-merge

#8560 MB-11319 add shipment type
  pkg/services/move_history/move_history_fetcher.go
  src/constants/moveHistoryEventTemplate.js
  src/constants/moveHistoryEventTemplate.test.js
  src/pages/Office/MoveHistory/LabeledDetails.test.jsx
Labels: Pamplemoose

#8558 MB-11663 update support api handlers
  pkg/handlers/supportapi/move_task_order.go
  pkg/handlers/supportapi/mto_service_item.go
  pkg/handlers/supportapi/mto_shipment.go
  pkg/handlers/supportapi/payment_request.go
  pkg/handlers/supportapi/webhook_notification.go
Labels: Pamplemoose

#8554 MB-12178 - Add generic handling for unknown history events
  src/constants/historyLogUIDisplayName.js
  src/constants/moveHistoryEventTemplate.js
  src/constants/moveHistoryEventTemplate.test.js
Labels: Pamplemoose

#8551 MB-12152: Update status on submit
  pkg/handlers/internalapi/moves.go
  pkg/handlers/internalapi/moves_test.go
  pkg/services/move/move_router.go
  pkg/services/move/move_router_test.go
Labels: A-Team

#8485 [MB-11731] PPM estimated incentive call pricer lookups
  pkg/etag/etag.go
  pkg/handlers/internalapi/api.go
  pkg/handlers/internalapi/mto_shipment.go
  pkg/handlers/internalapi/mto_shipment_test.go
  pkg/payment_request/mocks/Helper.go
  pkg/payment_request/payment_request_helper.go
  pkg/payment_request/service_param_list_fetcher.go
  pkg/payment_request/service_param_value_lookups/actual_pickup_date_lookup_test.go
  pkg/payment_request/service_param_value_lookups/contract_code_lookup_test.go
  pkg/payment_request/service_param_value_lookups/cubic_feet_billed_lookup_test.go
  pkg/payment_request/service_param_value_lookups/cubic_feet_crating_lookup_test.go
  pkg/payment_request/service_param_value_lookups/dimension_height_lookup_test.go
  pkg/payment_request/service_param_value_lookups/dimension_length_lookup_test.go
  pkg/payment_request/service_param_value_lookups/dimension_width_lookup_test.go
  pkg/payment_request/service_param_value_lookups/distance_zip3_lookup_test.go
  pkg/payment_request/service_param_value_lookups/distance_zip5_lookup_test.go
  pkg/payment_request/service_param_value_lookups/distance_zip_sit_dest_lookup_test.go
  pkg/payment_request/service_param_value_lookups/distance_zip_sit_origin_lookup_test.go
  pkg/payment_request/service_param_value_lookups/eia_fuel_price_lookup_test.go
  pkg/payment_request/service_param_value_lookups/mto_available_to_prime_at_lookup_test.go
  pkg/payment_request/service_param_value_lookups/number_days_sit_lookup.go
  pkg/payment_request/service_param_value_lookups/number_days_sit_lookup_test.go
  pkg/payment_request/service_param_value_lookups/reference_date_lookup_test.go
  pkg/payment_request/service_param_value_lookups/requested_pickup_date_lookup_test.go
  pkg/payment_request/service_param_value_lookups/service_area_lookup_test.go
  pkg/payment_request/service_param_value_lookups/service_param_value_lookups.go
  pkg/payment_request/service_param_value_lookups/service_param_value_lookups_test.go
  pkg/payment_request/service_param_value_lookups/service_params_cache_test.go
  pkg/payment_request/service_param_value_lookups/services_schedule_lookup_test.go
  pkg/payment_request/service_param_value_lookups/sit_schedule_lookup_test.go
  pkg/payment_request/service_param_value_lookups/weight_billed_lookup.go
  pkg/payment_request/service_param_value_lookups/weight_billed_lookup_test.go
  pkg/payment_request/service_param_value_lookups/weight_estimated_lookup_test.go
  pkg/payment_request/service_param_value_lookups/weight_original_lookup_test.go
  pkg/payment_request/service_param_value_lookups/weight_reweigh_lookup_test.go
  pkg/payment_request/service_param_value_lookups/zip_address_lookup_test.go
  pkg/payment_request/service_param_value_lookups/zip_sit_origin_hhg_actual_address_lookup_test.go
  pkg/payment_request/service_param_value_lookups/zip_sit_origin_hhg_original_address_lookup_test.go
  pkg/services/ghcrateengine/fuel_surcharge_pricer.go
  pkg/services/ghcrateengine/fuel_surcharge_pricer_test.go
  pkg/services/ghcrateengine/service_item_pricer.go
  pkg/services/mocks/PPMEstimator.go
  pkg/services/mto_shipment/mto_shipment_updater.go
  pkg/services/payment_request/payment_request_creator.go
  pkg/services/ppmservices.go
  pkg/services/ppmshipment.go
  pkg/services/ppmshipment/ppm_estimator.go
  pkg/services/ppmshipment/ppm_estimator_test.go
  pkg/services/ppmshipment/ppm_shipment_updater.go
  pkg/services/ppmshipment/ppm_shipment_updater_test.go
  pkg/testdatagen/make_ghc_diesel_fuel_price.go
  pkg/testdatagen/make_re_domestic_other_price.go
  pkg/testdatagen/make_re_domestic_service_area_price.go
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/shared.go
  src/pages/MyMove/PPMBooking/Advance/Advance.jsx
  src/pages/MyMove/PPMBooking/EstimatedWeightsProGear/EstimatedWeightsProGear.jsx
Labels: A-Team

#8535 Deprecate old estimate incentive code
  pkg/gen/internalapi/configure_mymove.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalapi/internaloperations/mymove_api.go
  pkg/gen/internalapi/internaloperations/ppm/update_personally_procured_move_estimate.go
  pkg/gen/internalapi/internaloperations/ppm/update_personally_procured_move_estimate_parameters.go
  pkg/gen/internalapi/internaloperations/ppm/update_personally_procured_move_estimate_responses.go
  pkg/gen/internalapi/internaloperations/ppm/update_personally_procured_move_estimate_urlbuilder.go
  pkg/handlers/internalapi/api.go
  pkg/handlers/internalapi/personally_procured_move.go
  pkg/handlers/internalapi/personally_procured_move_estimate.go
  pkg/handlers/internalapi/personally_procured_move_estimate_test.go
  pkg/handlers/internalapi/personally_procured_move_sit_estimate.go
  pkg/handlers/internalapi/personally_procured_move_sit_estimate_test.go
  pkg/handlers/internalapi/personally_procured_move_test.go
  pkg/services/event/internal_endpoint.go
  pkg/services/mocks/EstimateCalculator.go
  pkg/services/ppmservices.go
  pkg/services/ppmservices/estimate_calculator.go
  pkg/services/ppmservices/estimate_calculator_test.go
  pkg/services/ppmservices/ppmservices_service_test.go
  swagger-def/internal.yaml
  swagger/internal.yaml
Labels: A-Team

#8574 MB-12178 - Handle unidentified move history events (round 2)
  src/constants/historyLogUIDisplayName.js
  src/constants/moveHistoryEventTemplate.js
  src/constants/moveHistoryEventTemplate.test.js
Labels: Pamplemoose, ready-to-merge

#8536 MB-12322: Create ShipmentCustomerSIT sub-component (for Office add/edit PPM)
  src/components/Office/ShipmentCustomerSIT/ShipmentCustomerSIT.jsx
  src/components/Office/ShipmentCustomerSIT/ShipmentCustomerSIT.stories.jsx
  src/components/Office/ShipmentCustomerSIT/ShipmentCustomerSIT.test.jsx
Labels: ready-to-merge, roci

#8530 MB-12315 Convert adminapi tests to run in transaction
  pkg/handlers/adminapi/admin_users_test.go
  pkg/handlers/adminapi/api_test.go
  pkg/handlers/adminapi/electronic_orders_test.go
  pkg/handlers/adminapi/moves_test.go
  pkg/handlers/adminapi/notifications_test.go
  pkg/handlers/adminapi/office_users_test.go
  pkg/handlers/adminapi/offices_test.go
  pkg/handlers/adminapi/organizations_test.go
  pkg/handlers/adminapi/transportation_service_provider_performances_test.go
  pkg/handlers/adminapi/upload_information_test.go
  pkg/handlers/adminapi/users_test.go
  pkg/handlers/adminapi/webhook_subscriptions_test.go
Labels: spark

#8553 MB-12246 add `qae_csr` role
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20220428174000_add_qae_csr_role.up.sql
  pkg/auth/authentication/devlocal.go
  pkg/auth/authentication/devlocal_test.go
  pkg/models/roles/roles.go
  pkg/services/move_history/move_history_fetcher.go
  pkg/testdatagen/make_role.go
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/scenario/subscenarios.go
  src/constants/userRoles.js
  src/pages/Office/index.jsx
  src/pages/SelectApplication/SelectApplication.jsx
  src/pages/SelectApplication/SelectApplication.test.jsx
Labels: ttv

#8565 MB-11880 Add history log for when MilMove deprecates a old payment request
  src/constants/moveHistoryEventTemplate.js
  src/constants/moveHistoryEventTemplate.test.js
  src/pages/Office/MoveHistory/MoveHistoryDetailsSelector.jsx
Labels: Pamplemoose

#8559 MB-12120 Update shipment service objects to be managed by an orchestrator service object
  pkg/handlers/internalapi/api.go
  pkg/handlers/internalapi/mto_shipment.go
  pkg/handlers/internalapi/mto_shipment_test.go
  pkg/services/mocks/PPMShipmentUpdater.go
  pkg/services/mocks/ShipmentCreator.go
  pkg/services/mocks/ShipmentUpdater.go
  pkg/services/mto_shipment/mto_shipment_creator.go
  pkg/services/mto_shipment/mto_shipment_creator_test.go
  pkg/services/orchestrators/shipment/rules.go
  pkg/services/orchestrators/shipment/rules_test.go
  pkg/services/orchestrators/shipment/shipment_creator.go
  pkg/services/orchestrators/shipment/shipment_creator_test.go
  pkg/services/orchestrators/shipment/shipment_service_test.go
  pkg/services/orchestrators/shipment/shipment_updater.go
  pkg/services/orchestrators/shipment/shipment_updater_test.go
  pkg/services/orchestrators/shipment/validation.go
  pkg/services/orchestrators/shipment/validation_test.go
  pkg/services/ppmshipment.go
  pkg/services/ppmshipment/ppm_shipment_creator.go
  pkg/services/ppmshipment/ppm_shipment_creator_test.go
  pkg/services/ppmshipment/ppm_shipment_updater_test.go
  pkg/services/ppmshipment/validation.go
  pkg/services/ppmshipment/validation_test.go
  pkg/services/shipment_orchestrator.go
  src/pages/MyMove/PPMBooking/Advance/Advance.jsx
  src/pages/MyMove/PPMBooking/Advance/Advance.test.jsx
  src/pages/MyMove/PPMBooking/EstimatedWeightsProGear/EstimatedWeightsProGear.jsx
  src/pages/MyMove/PPMBooking/EstimatedWeightsProGear/EstimatedWeightsProGear.test.jsx
Labels: A-Team

#8592 [ MB-12420 ] Add the UpdateMTOReviewedBillableWeightsAt event
  src/constants/moveHistoryEventTemplate.js
  src/constants/moveHistoryEventTemplate.test.js
  src/constants/moveHistoryOperations.js
Labels: Pamplemoose, ready-to-merge

#8584 MB-11408, MB-11876, MB-12017 payment requests and gex
  src/constants/moveHistoryEventTemplate.js
  src/constants/moveHistoryEventTemplate.test.js
Labels: Pamplemoose, ready-to-merge

#8573 MB-11862 sc can view ppm
  cypress/integration/milmove/ppms/advances.js
  cypress/integration/milmove/ppms/dateAndLocation.js
  cypress/integration/milmove/ppms/entireShipment.js
  cypress/integration/milmove/ppms/estimatedIncentive.js
  cypress/integration/milmove/ppms/estimatedWeightsProgear.js
  cypress/integration/milmove/ppms/navigateToUploadDocs.js
  cypress/integration/milmove/ppms/review.js
  cypress/integration/office/ppms/viewShipment.js
  cypress/support/ppmCustomerShared.js
  cypress/support/ppmOfficeShared.js
  pkg/testdatagen/scenario/e2ebasic.go
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/scenario/subscenarios.go
  src/components/Office/DefinitionLists/PPMShipmentInfoList.jsx
  src/components/Office/DefinitionLists/PPMShipmentInfoList.stories.jsx
  src/components/Office/DefinitionLists/ShipmentInfoList.jsx
  src/components/Office/DefinitionLists/ShipmentInfoListSelector.jsx
  src/components/Office/DefinitionLists/ShipmentInfoListSelector.test.jsx
  src/components/Office/ShipmentDisplay/ShipmentDisplay.jsx
  src/components/Office/ShipmentDisplay/ShipmentDisplay.stories.jsx
  src/components/Office/ShipmentDisplay/ShipmentDisplayTestData.js
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
  src/types/shipment.js
Labels: ready-to-merge, roci

#8564 [ MB-12368 ] Add Cypress test for Max Billable Weight updates
  cypress/.eslintrc
  cypress/integration/office/txo/tio-update-max-billable-weight.js
  src/components/Office/BillableWeight/EditBillableWeight/EditBillableWeight.jsx
Labels: Pamplemoose

#8596 [ MB-12470 ] Display internal system modifications as MilMove
  src/pages/Office/MoveHistory/ModifiedBy.jsx
  src/pages/Office/MoveHistory/ModifiedBy.test.jsx
Labels: Pamplemoose

#8575 [MB-12327] GHC API can create PPM shipments
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20220502194223_add_sit_fields_to_ppm_shipments.up.sql
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/create_m_t_o_shipment.go
  pkg/gen/ghcmessages/create_p_p_m_shipment.go
  pkg/gen/ghcmessages/m_t_o_shipment_type.go
  pkg/gen/ghcmessages/p_p_m_shipment.go
  pkg/gen/ghcmessages/s_i_t_location_type.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/p_p_m_shipment.go
  pkg/gen/primemessages/s_i_t_location_type.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/internal/payloads/payload_to_model.go
  pkg/handlers/ghcapi/mto_shipment.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/handlers/internalapi/api.go
  pkg/handlers/internalapi/mto_shipment_test.go
  pkg/models/ppm_shipment.go
  pkg/services/orchestrators/shipment/shipment_creator.go
  pkg/services/orchestrators/shipment/shipment_creator_test.go
  pkg/services/ppmshipment/ppm_shipment_creator.go
  pkg/services/ppmshipment/ppm_shipment_creator_test.go
  swagger-def/definitions/MTOShipmentType.yaml
  swagger-def/definitions/PPMShipment.yaml
  swagger-def/definitions/SITLocationType.yaml
  swagger-def/ghc.yaml
  swagger/ghc.yaml
  swagger/prime.yaml
Labels: ready-to-merge, roci

#8621 MB-11407 - Document when a TIO updates max billable weight
  src/constants/historyLogUIDisplayName.js
  src/constants/moveHistoryEventTemplate.js
  src/constants/moveHistoryEventTemplate.test.js
  src/constants/moveHistoryOperations.js
Labels: Pamplemoose, ready-to-merge

#8632 Update pre-commit hooks and fix any issues that arise
  .pre-commit-config.yaml
  cmd/prime-api-client/utils/shared.go
  pkg/dates/calendar_test.go
  pkg/models/fuel_eia_diesel_price_test.go
  pkg/services/mto_shipment/mto_shipment_creator.go
Labels: ready-to-merge, roci

#8597 MB-12323 [Storybook] Create PPM Weight sub-component
  src/components/Office/ShipmentWeight/ShipmentWeight.jsx
  src/components/Office/ShipmentWeight/ShipmentWeight.stories.jsx
  src/components/Office/ShipmentWeight/ShipmentWeight.test.jsx
Labels: ready-to-merge, roci

#8622 MB-11662 convert all handlers in admin api
  pkg/handlers/adminapi/admin_users.go
  pkg/handlers/adminapi/electronic_orders.go
  pkg/handlers/adminapi/moves.go
  pkg/handlers/adminapi/notifications.go
  pkg/handlers/adminapi/office_users.go
  pkg/handlers/adminapi/offices.go
  pkg/handlers/adminapi/organizations.go
  pkg/handlers/adminapi/transportation_service_provider_performances.go
  pkg/handlers/adminapi/upload_information.go
  pkg/handlers/adminapi/users.go
  pkg/handlers/adminapi/webhook_subscriptions.go
Labels: Pamplemoose

#8626 [ MB-12515 ] Add ADR about Move History Events
  docs/adr/0071-move-history-events.md
  docs/adr/index.md
Labels: enhancement, Pamplemoose

#8595 MB-12269 Add new PPMShipment fields to track actual final values
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20220511200357_add_actual_final_value_fields_for_zips_and_advances_to_ppm_shipments.up.sql
  pkg/models/ppm_shipment.go
Labels: A-Team

#8603 MB-12168: Remove soft warning and add hard error at 60%
  cypress/integration/milmove/ppms/advances.js
  pkg/services/ppmshipment/rules.go
  pkg/services/ppmshipment/rules_test.go
  src/components/Customer/PPMBooking/Advance/AdvanceForm.jsx
  src/components/Customer/PPMBooking/Advance/AdvanceForm.test.jsx
  src/constants/shipments.js
  src/pages/MyMove/PPMBooking/Advance/Advance.jsx
  src/pages/MyMove/PPMBooking/Advance/Advance.test.jsx
  src/utils/formatters.js
  src/utils/formatters.test.js
  src/utils/incentives.js
  src/utils/incentives.test.js
Labels: A-Team

#8604 MB-12270 Use new PPM zip and advance fields in service objects and API
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/p_p_m_shipment.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/p_p_m_shipment.go
  pkg/gen/internalmessages/s_i_t_location_type.go
  pkg/gen/internalmessages/update_p_p_m_shipment.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/p_p_m_shipment.go
  pkg/handlers/apitests.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/handlers/internalapi/internal/payloads/model_to_payload.go
  pkg/handlers/internalapi/internal/payloads/payload_to_model.go
  pkg/handlers/internalapi/mto_shipment_test.go
  pkg/handlers/primeapi/payloads/model_to_payload.go
  pkg/services/ppmshipment/ppm_estimator.go
  pkg/services/ppmshipment/ppm_estimator_test.go
  pkg/services/ppmshipment/rules.go
  pkg/services/ppmshipment/validation.go
  pkg/services/ppmshipment/validation_test.go
  pkg/testdatagen/make_ppm_shipment.go
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/scenario/subscenarios.go
  swagger-def/definitions/PPMShipment.yaml
  swagger-def/internal.yaml
  swagger/ghc.yaml
  swagger/internal.yaml
  swagger/prime.yaml
Labels: A-Team

#8639 Converted query package and all tests to transactions
  pkg/services/query/query_builder_test.go
Labels: spark

#8640 MB-11420 Add migration to back-fill renamed advance cols w/existing data
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20220519011504_backfill_replacement_ppm_shipments_advance_requested_fields.up.sql
Labels: A-Team

#8658 MB-12491 Converts pkg/services/move and all its tests to use transactions
  pkg/services/move/excess_weight_uploader_test.go
  pkg/services/move/move_router_test.go
  pkg/services/move/move_service_test.go
Labels: spark

#8641 MB-12018 document prime upload proof of service document
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20220518203808_create_move_history_trigger_for_proof_of_service_docs.up.sql
  pkg/services/move_history/move_history_fetcher.go
Labels: Pamplemoose, ready-to-merge

#8666 MB-12018 Create new proof of service document upload event
  src/constants/MoveHistory/Database/Tables.js
  src/constants/MoveHistory/EventTemplates/index.js
  src/constants/MoveHistory/EventTemplates/proofOfServiceDocUpload.js
  src/constants/MoveHistory/EventTemplates/proofOfServiceDocUpload.test.js
Labels: Pamplemoose, ready-to-merge

#8647 MB-12328 Edit PPM Shipment Office
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/update_p_p_m_shipment.go
  pkg/gen/ghcmessages/update_shipment.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/update_p_p_m_shipment.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/internal/payloads/payload_to_model.go
  pkg/handlers/ghcapi/mto_shipment.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/handlers/internalapi/api.go
  pkg/handlers/internalapi/internal/payloads/model_to_payload.go
  pkg/handlers/internalapi/internal/payloads/payload_to_model.go
  pkg/handlers/internalapi/mto_shipment_test.go
  pkg/handlers/primeapi/api.go
  pkg/handlers/primeapi/mto_shipment.go
  pkg/handlers/primeapi/mto_shipment_test.go
  pkg/handlers/primeapi/payloads/model_to_payload.go
  pkg/models/ppm_shipment.go
  pkg/services/mocks/MTOShipmentUpdater.go
  pkg/services/mto_shipment.go
  pkg/services/mto_shipment/mto_shipment_updater.go
  pkg/services/mto_shipment/mto_shipment_updater_test.go
  pkg/services/mto_shipment/validation.go
  pkg/services/mto_shipment/validation_test.go
  pkg/services/orchestrators/shipment/shipment_updater.go
  pkg/services/orchestrators/shipment/shipment_updater_test.go
  pkg/services/ppmshipment/ppm_estimator.go
  pkg/services/ppmshipment/ppm_estimator_test.go
  pkg/services/ppmshipment/ppm_shipment_creator_test.go
  pkg/services/ppmshipment/ppm_shipment_updater_test.go
  pkg/services/ppmshipment/rules.go
  pkg/services/ppmshipment/rules_test.go
  pkg/services/ppmshipment/validation.go
  pkg/services/ppmshipment/validation_test.go
  pkg/testdatagen/make_ppm_shipment.go
  swagger-def/ghc.yaml
  swagger-def/internal.yaml
  swagger/ghc.yaml
  swagger/internal.yaml
Labels: ready-to-merge, roci

#8633 MB-12516 Removed awardqueue
  pkg/awardqueue/awardqueue.go
  pkg/awardqueue/awardqueue_test.go
Labels: spark

#8598 [MB-12257] Move search by locator and DOD id for QAE/CSR users
  cypress/integration/office/qaecsr/moveSearch.js
  cypress/support/commands.js
  cypress/support/constants.js
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/move/search_moves.go
  pkg/gen/ghcapi/ghcoperations/move/search_moves_parameters.go
  pkg/gen/ghcapi/ghcoperations/move/search_moves_responses.go
  pkg/gen/ghcapi/ghcoperations/move/search_moves_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/ghcmessages/search_move.go
  pkg/gen/ghcmessages/search_moves.go
  pkg/gen/ghcmessages/search_moves_result.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/move.go
  pkg/handlers/ghcapi/move_test.go
  pkg/handlers/ghcapi/mto_shipment.go
  pkg/services/mocks/MoveSearcher.go
  pkg/services/move.go
  pkg/services/move/move_searcher.go
  pkg/services/move/move_searcher_test.go
  pkg/testdatagen/scenario/e2ebasic.go
  pkg/testdatagen/scenario/shared.go
  src/components/Table/SearchResultsTable.jsx
  src/components/Table/SearchResultsTable.module.scss
  src/components/Table/SearchResultsTable.test.jsx
  src/components/Table/TableQueue.jsx
  src/constants/queryKeys.js
  src/constants/routes.js
  src/hooks/queries.js
  src/pages/Office/QAECSRMoveSearch/QAECSRMoveSearch.jsx
  src/pages/Office/QAECSRMoveSearch/QAECSRMoveSearch.module.scss
  src/pages/Office/QAECSRMoveSearch/QAECSRMoveSearch.stories.jsx
  src/pages/Office/QAECSRMoveSearch/QAECSRMoveSearch.test.jsx
  src/pages/Office/index.jsx
  src/services/ghcApi.js
  src/shared/Entities/schema.js
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: ttv

#8657 Adding prime actual weight
  src/constants/MoveHistory/Database/FieldMappings.js
  src/pages/Office/MoveHistory/LabeledDetails.test.jsx
Labels: Pamplemoose

#8602 [MB-12416] Allow < min values for weight and distance on PPM shipments
  pkg/payment_request/service_param_value_lookups/service_param_value_lookups_test.go
  pkg/payment_request/service_param_value_lookups/weight_billed_lookup.go
  pkg/payment_request/service_param_value_lookups/weight_billed_lookup_test.go
  pkg/services/ghc_rate_engine.go
  pkg/services/ghcrateengine/domestic_destination_pricer.go
  pkg/services/ghcrateengine/domestic_destination_pricer_test.go
  pkg/services/ghcrateengine/domestic_linehaul_pricer.go
  pkg/services/ghcrateengine/domestic_linehaul_pricer_test.go
  pkg/services/ghcrateengine/domestic_nts_pack_pricer.go
  pkg/services/ghcrateengine/domestic_origin_pricer.go
  pkg/services/ghcrateengine/domestic_origin_pricer_test.go
  pkg/services/ghcrateengine/domestic_pack_pricer.go
  pkg/services/ghcrateengine/domestic_unpack_pricer.go
  pkg/services/ghcrateengine/domestic_unpack_pricer_test.go
  pkg/services/ghcrateengine/fuel_surcharge_pricer.go
  pkg/services/ghcrateengine/fuel_surcharge_pricer_test.go
  pkg/services/ghcrateengine/pricer_helpers.go
  pkg/services/ghcrateengine/pricer_helpers_test.go
  pkg/services/mocks/DomesticDestinationPricer.go
  pkg/services/mocks/DomesticLinehaulPricer.go
  pkg/services/mocks/DomesticNTSPackPricer.go
  pkg/services/mocks/DomesticOriginPricer.go
  pkg/services/mocks/DomesticPackPricer.go
  pkg/services/mocks/DomesticUnpackPricer.go
  pkg/services/mocks/FuelSurchargePricer.go
  src/pages/MyMove/PPMBooking/EstimatedWeightsProGear/EstimatedWeightsProGear.jsx
Labels: A-Team

#8638 MB-12249-fix-secondary-zip-bug
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/create_p_p_m_shipment.go
  pkg/gen/internalmessages/update_p_p_m_shipment.go
  pkg/handlers/converters_strfmt.go
  pkg/handlers/internalapi/internal/payloads/payload_to_model.go
  pkg/handlers/internalapi/mto_shipment_test.go
  swagger-def/internal.yaml
  swagger/internal.yaml
Labels: ready-to-merge, A-Team

#8687 [MB-12614] Customer created HHG shipments should be in the SUBMITTED status for approval
  pkg/handlers/internalapi/internal/payloads/payload_to_model.go
  pkg/handlers/internalapi/mto_shipment_test.go
  pkg/services/ppmshipment/ppm_estimator.go
Labels: A-Team

#8688 MB-11344 Added lbs to prime actual weight
  src/constants/MoveHistory/Database/WeightFields.js
  src/pages/Office/MoveHistory/LabeledDetails.test.jsx
Labels: Pamplemoose, ready-to-merge

#8684 MB-12620 Change PPM advance requested reads to use new columns
  cypress/integration/milmove/ppms/advances.js
  cypress/integration/office/ppms/viewShipment.js
  cypress/support/ppmCustomerShared.js
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/p_p_m_shipment.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/p_p_m_shipment.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/p_p_m_shipment.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/internal/payloads/payload_to_model.go
  pkg/handlers/internalapi/internal/payloads/model_to_payload.go
  pkg/handlers/internalapi/mto_shipment_test.go
  pkg/handlers/primeapi/payloads/model_to_payload.go
  src/components/Customer/PPM/Booking/Advance/AdvanceForm.jsx
  src/components/Customer/PPM/Booking/Advance/AdvanceForm.stories.jsx
  src/components/Customer/PPM/Booking/Advance/AdvanceForm.test.jsx
  src/components/Customer/Review/ShipmentCard/PPMShipmentCard/PPMShipmentCard.jsx
  src/components/Customer/Review/ShipmentCard/PPMShipmentCard/PPMShipmentCard.test.jsx
  src/components/Office/DefinitionLists/PPMShipmentInfoList.jsx
  src/components/Office/DefinitionLists/PPMShipmentInfoList.stories.jsx
  src/components/Office/DefinitionLists/ShipmentInfoListSelector.test.jsx
  src/components/Office/ShipmentDisplay/ShipmentDisplay.jsx
  src/components/Office/ShipmentDisplay/ShipmentDisplayTestData.js
  src/components/Office/ShipmentIncentiveAdvance/ShipmentIncentiveAdvance.jsx
  src/components/Office/ShipmentIncentiveAdvance/ShipmentIncentiveAdvance.stories.jsx
  src/components/Office/ShipmentIncentiveAdvance/ShipmentIncentiveAdvance.test.jsx
  src/components/PPMSummaryList/PPMSummaryList.stories.jsx
  src/components/PPMSummaryList/PPMSummaryList.test.jsx
  src/components/ShipmentList/ShipmentList.stories.jsx
  src/components/ShipmentList/ShipmentList.test.jsx
  src/pages/MyMove/Home/index.stories.jsx
  src/pages/MyMove/Home/index.test.jsx
  src/pages/MyMove/PPMBooking/Advance/Advance.jsx
  src/pages/MyMove/PPMBooking/Advance/Advance.test.jsx
  src/pages/MyMove/Profile/EditServiceInfo.test.jsx
  src/pages/MyMove/Review/Review.test.jsx
  src/types/customerShapes.js
  src/types/shipment.js
  src/utils/shipments.js
  src/utils/shipments.test.js
  swagger-def/definitions/PPMShipment.yaml
  swagger/ghc.yaml
  swagger/internal.yaml
  swagger/prime.yaml
Labels: A-Team

#8689 [MB-12229] Prime simulator: Prime can complete counseling
  src/components/PrimeUI/Shipment/Shipment.jsx
  src/components/PrimeUI/Shipment/Shipment.test.jsx
  src/pages/PrimeUI/MoveTaskOrder/MoveDetails.jsx
  src/pages/PrimeUI/MoveTaskOrder/MoveDetails.test.jsx
  src/services/primeApi.js
Labels: roci
