Repository transcom/mymove, pull requests merged in 2022-09, with the labels that each got.

#9105 MB-11277: Cypress tests for PPM office flow
  cypress/integration/office/ppms/addShipment.js
  cypress/integration/office/ppms/happyPathFlows.js
  cypress/support/ppmOfficeShared.js
  cypress/support/ppmShipmentFixture.js
  pkg/testdatagen/scenario/e2ebasic.go
  pkg/testdatagen/scenario/subscenarios.go
Labels: A-Team, ready-to-merge

#9118 MB-13351 Update ppm shipments and signed certification tables
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20220824133409_add_w2_address_final_incentive_to_ppm_shipment.up.sql
  migrations/app/schema/20220826142534_associate_signed_certifications_with_ppms.up.sql
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/p_p_m_shipment.go
  pkg/gen/ghcmessages/update_p_p_m_shipment.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/create_signed_certification_payload.go
  pkg/gen/internalmessages/p_p_m_shipment.go
  pkg/gen/internalmessages/ppm_id.go
  pkg/gen/internalmessages/signed_certification_payload.go
  pkg/gen/internalmessages/update_p_p_m_shipment.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/internal/payloads/payload_to_model.go
  pkg/handlers/internalapi/internal/payloads/model_to_payload.go
  pkg/handlers/internalapi/internal/payloads/payload_to_model.go
  pkg/handlers/internalapi/mto_shipment_test.go
  pkg/models/ppm_shipment.go
  pkg/models/signed_certification.go
  pkg/services/ppmshipment/validation.go
  pkg/services/ppmshipment/validation_test.go
  swagger-def/definitions/PPMShipment.yaml
  swagger-def/definitions/PpmID.yaml
  swagger-def/ghc.yaml
  swagger-def/internal.yaml
  swagger/ghc.yaml
  swagger/internal.yaml
Labels: A-Team

#9143 MB-12822 Selected Violations
  src/components/Office/EvaluationViolationsForm/EvaluationViolationsForm.jsx
  src/components/Office/EvaluationViolationsForm/EvaluationViolationsForm.module.scss
  src/components/Office/EvaluationViolationsForm/EvaluationViolationsForm.stories.jsx
  src/components/Office/EvaluationViolationsForm/EvaluationViolationsForm.test.jsx
  src/components/Office/EvaluationViolationsForm/SelectedViolation/SelectedViolation.jsx
  src/components/Office/EvaluationViolationsForm/SelectedViolation/SelectedViolation.module.scss
  src/components/Office/EvaluationViolationsForm/SelectedViolation/SelectedViolation.stories.jsx
  src/components/Office/EvaluationViolationsForm/SelectedViolation/SelectedViolation.test.jsx
  src/components/Office/ViolationsAccordion/ViolationsAccordion.jsx
  src/pages/Office/EvaluationViolations/EvaluationViolations.jsx
  src/pages/Office/EvaluationViolations/EvaluationViolations.module.scss
  src/pages/Office/EvaluationViolations/EvaluationViolations.test.jsx
Labels: ttv

#9135 [ MB-11968 ] Add some documentation to local sign-in
  pkg/handlers/authentication/devlocal.go
Labels: enhancement, Pamplemoose, ready-to-merge

#9106 MB-13352 Add PPM final closeout page
  cypress/integration/milmove/ppms/finalCloseout.js
  cypress/integration/milmove/ppms/progear.js
  cypress/support/ppmCustomerShared.js
  pkg/testdatagen/scenario/e2ebasic.go
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/scenario/subscenarios.go
  src/components/Customer/PPM/Closeout/FinalCloseoutForm/FinalCloseoutForm.jsx
  src/components/Customer/PPM/Closeout/FinalCloseoutForm/FinalCloseoutForm.module.scss
  src/components/Customer/PPM/Closeout/FinalCloseoutForm/FinalCloseoutForm.stories.jsx
  src/components/Customer/PPM/Closeout/FinalCloseoutForm/FinalCloseoutForm.test.jsx
  src/pages/MyMove/PPM/Closeout/FinalCloseout/FinalCloseout.jsx
  src/pages/MyMove/PPM/Closeout/FinalCloseout/FinalCloseout.module.scss
  src/pages/MyMove/PPM/Closeout/FinalCloseout/FinalCloseout.test.jsx
  src/pages/MyMove/PPM/Closeout/Review/Review.jsx
  src/pages/MyMove/PPM/Closeout/Review/Review.test.jsx
  src/scenes/MyMove/index.jsx
  src/types/shipment.js
  src/utils/ppmCloseout.jsx
  src/utils/ppmCloseout.test.jsx
  src/utils/shipments.test.js
  src/utils/test/factories/document.js
  src/utils/test/factories/movingExpense.js
  src/utils/test/factories/ppmShipment.js
  src/utils/test/factories/proGear.js
  src/utils/test/factories/proGearWeightTicket.js
  src/utils/test/factories/upload.js
  src/utils/test/factories/weightTicket.js
Labels: A-Team

#9162 MB-13757: Adds .skip to flaky integration tests
  .circleci/config.yml
  cypress/integration/office/qaecsr/csrFlows.js
  cypress/integration/office/qaecsr/qaeEvaluationReportFlow.js
  cypress/integration/office/servicescounseling/servicesCounselingFlows.js
  cypress/integration/office/txo/tioFlows.js
  cypress/integration/office/txo/tooFlows.js
Labels: A-Team

#9154 Update references to api.demo.dp3.us.chain.der.p7b after rename
  config/env/demo.app-client-tls.env
  config/env/demo.app.env
  config/tls/README.md
Labels: ready-to-merge

#9123 [ MB-11965 ] - Create new event template for move status change
  src/constants/MoveHistory/EventTemplates/createMTOServiceItemUpdateMoveStatus.js
  src/constants/MoveHistory/EventTemplates/createMTOServiceItemUpdateMoveStatus.test.js
  src/constants/MoveHistory/EventTemplates/index.js
Labels: Pamplemoose, ready-to-merge

#9163 [ MB-12015 ] Documenting Prime reweighs in move history table
  src/constants/MoveHistory/Database/FieldMappings.js
  src/constants/MoveHistory/Database/WeightFields.js
  src/constants/MoveHistory/EventTemplates/index.js
  src/constants/MoveHistory/EventTemplates/updateReweighWeight.js
  src/constants/MoveHistory/EventTemplates/updateReweighWeight.test.js
Labels: Pamplemoose, ready-to-merge

#9145 [MB-13507] Changed AOA language for Customer PPM Form
  src/components/Customer/PPM/Booking/Advance/AdvanceForm.jsx
Labels: A-Team

#9170 Adding ability to cancel shipments as GHC Prime in the Simulator UI
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdate.jsx
  src/services/primeApi.js
Labels: enhancement, Pamplemoose, ready-to-merge, help wanted

#9166 MB-13647: Display correct trip number when modifying or adding a weight ticket
  src/components/Customer/PPM/Closeout/WeightTicketForm/WeightTicketForm.jsx
  src/components/Customer/PPM/Closeout/WeightTicketForm/WeightTicketForm.stories.jsx
  src/components/Customer/PPM/Closeout/WeightTicketForm/WeightTicketForm.test.jsx
  src/pages/MyMove/PPM/Closeout/WeightTickets/WeightTickets.jsx
  src/pages/MyMove/PPM/Closeout/WeightTickets/WeightTickets.test.jsx
Labels: A-Team, ready-to-merge

#9175 Saving the previous and current coverage files for Server tests only
  .circleci/config.yml
Labels: enhancement, Pamplemoose, help wanted, bug

#9134 [ MB-11968 ] Fix the GBLOC scripts
  scripts/ds-for-gbloc
  scripts/to-for-gbloc
Labels: enhancement, Pamplemoose, bug

#9186 [MB-12016] Document when the System flags excess weight if total estimated weight > 90% weight allowance
  src/constants/MoveHistory/EventTemplates/index.js
  src/constants/MoveHistory/EventTemplates/updateMTOShipmentPrimeEstimatedExcessWeight.js
  src/constants/MoveHistory/EventTemplates/updateMTOShipmentPrimeEstimatedExcessWeight.test.js
Labels: Pamplemoose

#9165 MB-13462 kpi based dates added to Violations Form
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20220909181518_update_pws_violations_table_additionaldataelem.up.sql
  src/components/Office/EvaluationViolationsForm/EvaluationViolationsForm.jsx
  src/components/Office/EvaluationViolationsForm/EvaluationViolationsForm.module.scss
  src/components/Office/EvaluationViolationsForm/EvaluationViolationsForm.test.jsx
  src/components/Office/ViolationsAccordion/ViolationsAccordion.jsx
  src/components/form/fields/DatePickerInput.jsx
  src/components/form/fields/DatePickerInput.module.scss
Labels: ttv

#9173 MB-12761 Add serious incident section to violations form
  src/components/Office/EvaluationForm/EvaluationForm.stories.jsx
  src/components/Office/EvaluationViolationsForm/EvaluationViolationsForm.jsx
  src/components/Office/EvaluationViolationsForm/EvaluationViolationsForm.module.scss
  src/components/Office/EvaluationViolationsForm/EvaluationViolationsForm.test.jsx
Labels: ttv

#9144 [MB-13532] Prime can update shipment with scheduled and actual delivery dates
  cypress/integration/office/primesimulator/primeSimulatorFlows.js
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20220901162926_add_scheduled_actual_delivery_dates.up.sql
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/m_t_o_shipment.go
  pkg/gen/primemessages/update_m_t_o_shipment.go
  pkg/handlers/primeapi/mto_shipment_test.go
  pkg/handlers/primeapi/payloads/model_to_payload.go
  pkg/handlers/primeapi/payloads/payload_to_model.go
  pkg/models/mto_shipments.go
  pkg/services/mto_shipment/mto_shipment_updater.go
  pkg/services/mto_shipment/mto_shipment_updater_test.go
  src/components/PrimeUI/Shipment/Shipment.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdate.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdateForm.jsx
  swagger-def/prime.yaml
  swagger/prime.yaml
Labels: ttv, ready-to-merge

#9153 MB-13718 convert tests to use transactions
  pkg/parser/transittime/parse_test.go
  pkg/parser/transittime/shared_test.go
  pkg/payment_request/send_to_syncada_test.go
  pkg/route/dtod_planner_test.go
  pkg/route/dtod_zip5_distance_mock_test.go
  pkg/route/dtod_zip5_distance_test.go
  pkg/route/here_planner_test.go
  pkg/route/hhg_planner_test.go
  pkg/route/rand_mcnally_distance_test.go
  pkg/server/server_test.go
  pkg/services/fuelprice/diesel_fuel_price_storer_test.go
  pkg/services/ghcdieselfuelprice/ghc_diesel_fuel_price_fetcher_test.go
  pkg/services/ghcdieselfuelprice/ghc_diesel_fuel_price_storer_test.go
  pkg/services/mto_shipment/shipment_approver_test.go
Labels: ready-to-merge, spark

#9200 Make the psql-wrapper script more user friendly
  scripts/psql-wrapper
Labels: Pamplemoose, ready-to-merge, help wanted, bug

#9204 Let's also prefix pg_dump to use Brew and Nix
  scripts/psql-schema
Labels: enhancement, Pamplemoose, ready-to-merge, bug

#9192 MB-12577 Refactor SQL query
  go.mod
  go.sum
  pkg/services/move_history/move_history_fetcher.go
  pkg/services/query/query_fetcher.go
  pkg/services/query/sql_scripts/move_history_fetcher.sql
Labels: Pamplemoose, ready-to-merge

#9207 [ MB-12577 ] Adding a simple doc for the new QueryFetcher service
  .github/CODEOWNERS
  pkg/services/query/sql_scripts/README.md
Labels: enhancement, Pamplemoose, ready-to-merge, help wanted

#9214 Make sure files exist before attempting to copy;
  .circleci/config.yml
Labels: Pamplemoose, ready-to-merge, help wanted, bug

#9212 Temporarily revert #9192;
  go.mod
  go.sum
  pkg/services/move_history/move_history_fetcher.go
  pkg/services/query/query_fetcher.go
  pkg/services/query/sql_scripts/move_history_fetcher.sql
Labels: Pamplemoose, ready-to-merge, bug

#9190 [MB-13702]Added error msg when 0 is entered in advance amount office & added test
  src/components/Office/ShipmentForm/ShipmentForm.test.jsx
  src/components/Office/ShipmentForm/ppmShipmentSchema.js
  src/components/Office/ShipmentIncentiveAdvance/ShipmentIncentiveAdvance.stories.jsx
Labels: A-Team

#9217 [ MB-13923 ] Reworking SQL templating
  pkg/services/move_history/move_history_fetcher.go
  pkg/services/query/query_sql.go
  pkg/services/query/sql_scripts/move_history_fetcher.sql
  pkg/services/query/sql_scripts/test_empty.sql
Labels: Pamplemoose

#8958 Add PopTestSuite#PreloadData, use suite.T().Cleanup
  pkg/handlers/ghcapi/customer_support_remarks_test.go
  pkg/handlers/ghcapi/evaluation_report_test.go
  pkg/handlers/ghcapi/move_test.go
  pkg/handlers/ghcapi/mto_agent_test.go
  pkg/handlers/ghcapi/mto_service_items_test.go
  pkg/handlers/ghcapi/payment_request_test.go
  pkg/handlers/ghcapi/tac_test.go
  pkg/handlers/primeapi/move_task_order_test.go
  pkg/handlers/primeapi/mto_shipment_test.go
  pkg/handlers/primeapi/payloads/model_to_payload_test.go
  pkg/handlers/primeapi/upload_test.go
  pkg/handlers/supportapi/move_task_order_test.go
  pkg/iws/iws_test.go
  pkg/notifications/user_account_modified_test.go
  pkg/payment_request/service_param_value_lookups/zip_address_lookup_test.go
  pkg/services/move/move_router_test.go
  pkg/services/mto_service_item/mto_service_item_creator_test.go
  pkg/services/mto_shipment/shipment_router_test.go
  pkg/testingsuite/pop_suite.go
  pkg/testingsuite/pop_suite_test.go
  pkg/testingsuite/pop_suite_txn.go
Labels: spark

#9213 [MB-12715] Update PPM shipment Prime API docs
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/moving_expense.go
  pkg/gen/ghcmessages/p_p_m_shipment.go
  pkg/gen/ghcmessages/p_p_m_shipment_status.go
  pkg/gen/ghcmessages/weight_ticket.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/moving_expense.go
  pkg/gen/internalmessages/p_p_m_shipment.go
  pkg/gen/internalmessages/p_p_m_shipment_status.go
  pkg/gen/internalmessages/weight_ticket.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/create_p_p_m_shipment.go
  pkg/gen/primemessages/m_t_o_shipment_type.go
  pkg/gen/primemessages/p_p_m_shipment.go
  pkg/gen/primemessages/p_p_m_shipment_status.go
  pkg/gen/primemessages/update_p_p_m_shipment.go
  pkg/handlers/primeapi/mto_shipment_test.go
  pkg/handlers/primeapi/payloads/payload_to_model.go
  swagger-def/definitions/MovingExpense.yaml
  swagger-def/definitions/PPMShipment.yaml
  swagger-def/definitions/PPMShipmentStatus.yaml
  swagger-def/internal.yaml
  swagger-def/prime.yaml
  swagger/ghc.yaml
  swagger/internal.yaml
  swagger/prime.yaml
Labels: A-Team, ready-to-merge

#9222 MB-13927 - Add jest-preview for client test debugging
  package.json
  src/setupTests.js
  yarn.lock
Labels: Pamplemoose

#9216 MB-6682 Extract out the Not Found component
  src/components/NotFound/NotFound.jsx
  src/components/NotFound/NotFound.stories.jsx
  src/components/NotFound/NotFound.test.jsx
  src/scenes/MyMove/index.jsx
  src/scenes/MyMove/index.test.js
Labels: infra, ready-to-merge

#9205 [MB-13870] Update go to 1.19.1
  .circleci/config.yml
  .github/workflows/go-auto-approve.yml
  .go-version
  .tool-versions
  Dockerfile.local
  Dockerfile.migrations_local
  Dockerfile.reviewapp
  Dockerfile.tasks_local
  Dockerfile.tools_local
  Dockerfile.webhook_client
  Dockerfile.webhook_client_dp3
  Dockerfile.webhook_client_local
  Makefile
  README.md
  cmd/ecs-deploy/put_target.go
  cmd/ecs-deploy/task_def.go
  cmd/generate-deploy-notes/main.go
  cmd/health-checker/main.go
  cmd/milmove/gen.go
  cmd/milmove/main_test.go
  cmd/milmove/migrate.go
  cmd/milmove/serve.go
  cmd/model-vet/main.go
  cmd/send-to-gex/main.go
  cmd/tls-checker/main.go
  cmd/webhook-client/utils/connection.go
  go.mod
  nix/default.nix
  pkg/certs/certs.go
  pkg/cli/dbconn.go
  pkg/cli/logging.go
  pkg/handlers/authentication/auth.go
  pkg/handlers/internalapi/moves.go
  pkg/iws/rbs_person_lookup.go
  pkg/middleware/limit_body_size_test.go
  pkg/middleware/middleware_test.go
  pkg/middleware/recovery_test.go
  pkg/middleware/trace_test.go
  pkg/middleware/valid_methods_static_test.go
  pkg/paperwork/generator_test.go
  pkg/parser/pricing/parse_test.go
  pkg/route/here_planner.go
  pkg/server/server_test.go
  pkg/services/fuelprice/diesel_fuel_price_storer.go
  pkg/services/ghcdieselfuelprice/ghc_diesel_fuel_price_fetcher.go
  pkg/services/ghcimport/ghc_rateengine_importer_test.go
  pkg/testdatagen/scenario/bandwidth.go
  scripts/gen-assets
  scripts/gen-server
  scripts/pre-commit-swagger-validate
  scripts/run-e2e-mtls-test-docker
  scripts/run-e2e-test-docker
Labels: Pamplemoose

#9242 MB-13995 - Fix flaky server test TestGHCInvoiceSuite
  pkg/services/invoice/ghc_payment_request_invoice_generator_test.go
  pkg/testdatagen/make_duty_location.go
Labels: Pamplemoose, ready-to-merge

#9229 MB-13885 update SQL Query to fix flaky EDI tests running on local machines
  pkg/services/invoice/ghc_payment_request_invoice_generator.go
Labels: ready-to-merge, spark

#9221 [MB-11540] add USCG and NAVY GBLOCs and Processing PPMs USMC Transpo Office
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20220920143839_add_gbloc_for_navy_and_coast_guard.up.sql
Labels: A-Team

#9251 [ MB-11273 ] Display MTO agent when shipment created
  src/constants/MoveHistory/EventTemplates/createMTOShipmentAgent.js
  src/constants/MoveHistory/EventTemplates/createMTOShipmentAgent.test.js
  src/pages/Office/MoveHistory/LabeledDetails.jsx
Labels: Pamplemoose

#9230 Mb 13703 move details page scroll bug nt
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
Labels: A-Team

#9219 MB-13654 Save draft of violations on eval reports
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20220919160852_create_report_violations_table.up.sql
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/ghcapi/ghcoperations/report_violations/associate_report_violations.go
  pkg/gen/ghcapi/ghcoperations/report_violations/associate_report_violations_parameters.go
  pkg/gen/ghcapi/ghcoperations/report_violations/associate_report_violations_responses.go
  pkg/gen/ghcapi/ghcoperations/report_violations/associate_report_violations_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/report_violations/get_report_violations_by_report_id.go
  pkg/gen/ghcapi/ghcoperations/report_violations/get_report_violations_by_report_id_parameters.go
  pkg/gen/ghcapi/ghcoperations/report_violations/get_report_violations_by_report_id_responses.go
  pkg/gen/ghcapi/ghcoperations/report_violations/get_report_violations_by_report_id_urlbuilder.go
  pkg/gen/ghcmessages/associate_report_violations.go
  pkg/gen/ghcmessages/report_violation.go
  pkg/gen/ghcmessages/report_violations.go
  pkg/handlers/authentication/permissions.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/report_violations.go
  pkg/handlers/ghcapi/report_violations_test.go
  pkg/models/pws_violation.go
  pkg/models/pws_violation_test.go
  pkg/models/report_violation.go
  pkg/models/report_violation_test.go
  pkg/services/mocks/ReportViolationFetcher.go
  pkg/services/mocks/ReportViolationsCreator.go
  pkg/services/report_violation.go
  pkg/services/report_violation/report_violation_creator.go
  pkg/services/report_violation/report_violation_creator_test.go
  pkg/services/report_violation/report_violation_fetcher.go
  pkg/services/report_violation/report_violation_fetcher_test.go
  pkg/services/report_violation/report_violation_service_test.go
  pkg/testdatagen/make_pws_violation.go
  pkg/testdatagen/make_report_violation.go
  pkg/testdatagen/shared.go
  src/components/Office/EvaluationViolationsForm/EvaluationViolationsForm.jsx
  src/components/Office/EvaluationViolationsForm/EvaluationViolationsForm.test.jsx
  src/components/Office/EvaluationViolationsForm/SelectedViolation/SelectedViolation.jsx
  src/components/Office/EvaluationViolationsForm/SelectedViolation/SelectedViolation.test.jsx
  src/components/Office/QaeReportHeader/QaeReportHeader.jsx
  src/constants/permissions.js
  src/constants/queryKeys.js
  src/hooks/queries.js
  src/hooks/queries.test.js
  src/pages/Office/EvaluationViolations/EvaluationViolations.jsx
  src/services/ghcApi.js
  src/types/index.js
  src/types/reportViolation.js
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: ttv

#9201 [MB-13908] Update golangci-lint config
  .github/CODEOWNERS
  .golangci.yml
  cmd/milmove/serve.go
Labels: ttv, ready-to-merge

#9252 MB-14008 - Remove IconButtons console error
  src/components/form/IconButtons.jsx
Labels: Pamplemoose, ready-to-merge

#9250 [ MB-11281 ] Enable destination type to be displayed in Move history table
  src/constants/MoveHistory/Database/FieldMappings.js
  src/constants/MoveHistory/Database/OptionFields.js
  src/constants/MoveHistory/EventTemplates/updateMTOShipment.js
  src/pages/Office/MoveHistory/LabeledDetails.jsx
  src/pages/Office/MoveHistory/LabeledDetails.test.jsx
Labels: Pamplemoose

#9255 MB-13850 Add helper text for when PPM closeout is complete
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/scenario/subscenarios.go
  src/components/Customer/Home/Helper/Helper.stories.jsx
  src/pages/MyMove/Home/Home.module.scss
  src/pages/MyMove/Home/HomeHelpers.jsx
  src/pages/MyMove/Home/index.jsx
  src/pages/MyMove/Home/index.stories.jsx
  src/pages/MyMove/Home/index.test.jsx
Labels: A-Team, ready-to-merge

#9265 MB-11293: Document when Service Councilor submits the move.
  src/constants/MoveHistory/EventTemplates/index.js
  src/constants/MoveHistory/EventTemplates/updateMTOStatusServiceCounselingCompleted.js
  src/constants/MoveHistory/EventTemplates/updateMTOStatusServiceCounselingCompleted.test.js
  src/constants/MoveHistory/UIDisplay/Operations.js
Labels: Pamplemoose

#9233 MB-12189 Set up FE data factories and implement duty locations
  .eslintrc.js
  package.json
  src/components/Customer/CurrentDutyLocationForm/CurrentDutyLocationForm.test.jsx
  src/components/DutyLocationSearchBox/DutyLocationSearchBox.test.jsx
  src/pages/MyMove/Profile/DutyLocation.test.jsx
  src/utils/test/factories/address.js
  src/utils/test/factories/base.js
  src/utils/test/factories/discovery/factory.js
  src/utils/test/factories/discovery/factory.test.js
  src/utils/test/factories/discovery/subfactory.js
  src/utils/test/factories/dutyLocation.js
  src/utils/test/factories/helpers.js
  src/utils/test/factories/transportationOffice.js
  yarn.lock
Labels: A-Team

#9231 MB-12426 Convert tests to use transactions
  pkg/parser/pricing/parse_access_and_add_prices_test.go
  pkg/parser/pricing/parse_domestic_other_prices_test.go
  pkg/parser/pricing/parse_international_prices_test.go
  pkg/parser/pricing/parse_management_counseling_transition_prices_test.go
  pkg/parser/pricing/parse_nonstandard_location_prices_test.go
  pkg/parser/pricing/parse_price_escalation_discount_test.go
  pkg/rateengine/nonlinehaul_test.go
  pkg/rateengine/rateengine_test.go
  pkg/services/ghcimport/ghc_rateengine_importer_test.go
  pkg/services/ghcimport/import_re_contract_test.go
  pkg/services/ghcimport/import_re_contract_years_test.go
  pkg/services/ghcimport/import_re_domestic_accessorial_prices_test.go
  pkg/services/ghcimport/import_re_domestic_linehaul_prices_test.go
  pkg/services/ghcimport/import_re_domestic_other_prices_test.go
  pkg/services/ghcimport/import_re_domestic_service_area_prices_test.go
  pkg/services/ghcimport/import_re_domestic_service_area_test.go
  pkg/services/ghcimport/import_re_intl_accessorial_prices_test.go
  pkg/services/ghcimport/import_re_intl_other_prices_test.go
  pkg/services/ghcimport/import_re_intl_prices_test.go
  pkg/services/ghcimport/import_re_rate_area_test.go
  pkg/services/ghcimport/import_re_shipment_type_prices_test.go
  pkg/services/ghcimport/import_re_task_order_fees_test.go
  pkg/services/ghcimport/load_service_map_test.go
  pkg/services/ghcimport/map_zip_codes_to_re_rate_areas_test.go
  pkg/services/ghcimport/shared_test.go
  pkg/services/invoice/ghc_payment_request_invoice_generator_test.go
  pkg/services/invoice/process_edi824_test.go
  pkg/services/invoice/process_edi997_test.go
  pkg/services/invoice/syncada_sftp_reader_test.go
  pkg/services/invoice/syncada_sftp_sender_test.go
  pkg/services/payment_request/payment_request_creator_test.go
  pkg/services/payment_request/payment_request_fetcher_test.go
  pkg/services/payment_request/payment_request_list_fetcher_test.go
  pkg/services/payment_request/payment_request_recalculator_test.go
  pkg/services/payment_request/payment_request_reviewed_fetcher_test.go
  pkg/services/payment_request/payment_request_shipment_recalculate_test.go
  pkg/services/payment_request/payment_request_shipments_sit_balance_test.go
  pkg/services/payment_request/payment_request_status_updater_test.go
  pkg/services/payment_request/upload_creator_test.go
Labels: ready-to-merge, spark

#9266 [MB-13353 Add W2 address form final incentive screen
  src/components/Customer/PPM/Closeout/FinalCloseoutForm/FinalCloseoutForm.jsx
  src/components/Customer/PPM/Closeout/W2AddressForm/W2AddressForm.jsx
  src/components/Customer/PPM/Closeout/W2AddressForm/W2AddressForm.module.scss
  src/components/Customer/PPM/Closeout/W2AddressForm/W2AddressForm.stories.jsx
  src/components/Customer/PPM/Closeout/W2AddressForm/W2AddressForm.test.jsx
  src/types/address.js
Labels: A-Team

#9256 [MB-13490] PPM closeout expenses detail page
  cypress/integration/milmove/ppms/expenses.js
  cypress/integration/milmove/ppms/finalCloseout.js
  cypress/support/ppmCustomerShared.js
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/p_p_m_shipment.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/p_p_m_shipment.go
  pkg/handlers/internalapi/internal/payloads/model_to_payload.go
  pkg/testdatagen/scenario/e2ebasic.go
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/scenario/subscenarios.go
  src/components/Customer/PPM/Closeout/ExpenseForm/ExpenseForm.jsx
  src/components/Customer/PPM/Closeout/ExpenseForm/ExpenseForm.module.scss
  src/components/Customer/PPM/Closeout/ExpenseForm/ExpenseForm.stories.jsx
  src/components/Customer/PPM/Closeout/ExpenseForm/ExpenseForm.test.jsx
  src/constants/ppmExpenseTypes.js
  src/pages/MyMove/PPM/Closeout/Expenses/Expenses.jsx
  src/pages/MyMove/PPM/Closeout/Expenses/Expenses.module.scss
  src/pages/MyMove/PPM/Closeout/Expenses/Expenses.test.jsx
  src/pages/MyMove/PPM/Closeout/Review/Review.jsx
  src/pages/MyMove/PPM/Closeout/Review/Review.test.jsx
  src/scenes/MyMove/index.jsx
  src/store/entities/selectors.js
  src/types/shipment.js
  src/utils/ppmCloseout.jsx
  src/utils/ppmCloseout.test.jsx
  src/utils/test/factories/movingExpense.js
  swagger-def/definitions/PPMShipment.yaml
  swagger/ghc.yaml
  swagger/internal.yaml
Labels: A-Team, ready-to-merge
