Repository transcom/mymove, pull requests merged in 2022-01, with the labels that each got.

#7958 Add migration to regrant permissions to crud user
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20211222193432_regrant_access_to_views_for_crud.up.sql
Labels: A-Team

#7971 MB-10561: create new ranking for: E-9 Special Senior Enlisted
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/grade.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/service_member_rank.go
  pkg/gen/ordersapi/embedded_spec.go
  pkg/gen/ordersmessages/rank.go
  pkg/gen/supportapi/embedded_spec.go
  pkg/gen/supportmessages/rank.go
  pkg/models/entitlements.go
  pkg/models/service_member_rank.go
  pkg/models/shipment_summary_worksheet.go
  pkg/models/shipment_summary_worksheet_test.go
  pkg/paperwork/forms.go
  src/components/Customer/Review/Review.stories.jsx
  src/components/Customer/Review/Summary/index.jsx
  src/constants/orders.js
  src/pages/MyMove/EditOrders.jsx
  src/services/internalApi.js
  swagger-def/ghc.yaml
  swagger-def/internal.yaml
  swagger-def/orders.yaml
  swagger-def/support.yaml
  swagger/ghc.yaml
  swagger/internal.yaml
  swagger/orders.yaml
  swagger/support.yaml
Labels: A-Team

#7978 MB-10436: Create AccountingCodesModal
  src/components/Office/AccountingCodeSection/AccountingCodeSection.jsx
  src/components/Office/AccountingCodeSection/AccountingCodeSection.module.scss
  src/components/Office/AccountingCodeSection/AccountingCodeSection.test.jsx
  src/components/Office/AccountingCodes/AccountingCodes.jsx
  src/components/Office/AccountingCodesModal/AccountingCodesModal.jsx
  src/components/Office/AccountingCodesModal/AccountingCodesModal.module.scss
  src/components/Office/AccountingCodesModal/AccountingCodesModal.stories.jsx
  src/components/Office/AccountingCodesModal/AccountingCodesModal.test.jsx
  src/components/Office/ShipmentAccountingCodes/ShipmentAccountingCodes.jsx
  src/components/Office/ShipmentAccountingCodes/ShipmentAccountingCodes.module.scss
  src/components/Office/ShipmentAccountingCodes/ShipmentAccountingCodes.stories.jsx
  src/components/Office/ShipmentAccountingCodes/ShipmentAccountingCodes.test.jsx
  src/components/Office/ShipmentForm/ShipmentForm.jsx
Labels: roci, Pamplemoose

#7975 MB-10426 too preview modal should display shipment details
  src/components/Office/DefinitionLists/NTSRShipmentInfoList.jsx
  src/components/Office/DefinitionLists/ShipmentDefinitionLists.module.scss
  src/components/Office/DefinitionLists/ShipmentInfoList.jsx
  src/components/Office/DefinitionLists/ShipmentInfoListSelector.jsx
  src/components/Office/DefinitionLists/ShipmentInfoListSelector.test.jsx
  src/components/Office/RequestedShipments/RequestedShipments.jsx
  src/components/Office/RequestedShipments/RequestedShipments.test.jsx
  src/components/Office/ShipmentApprovalPreview/ShipmentApprovalPreview.jsx
  src/components/Office/ShipmentApprovalPreview/ShipmentApprovalPreview.test.jsx
  src/components/Office/ShipmentDisplay/ShipmentDisplay.jsx
Labels: roci, Pamplemoose

#7967 Use ntsRecordedWeight for ShipmentWeightInput
  src/components/Office/ShipmentForm/ShipmentForm.jsx
  src/components/Office/ShipmentWeightInput/ShipmentWeightInput.jsx
  src/components/Office/ShipmentWeightInput/ShipmentWeightInput.stories.jsx
  src/components/Office/ShipmentWeightInput/ShipmentWeightInput.test.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.test.jsx
  src/utils/formatMtoShipment.js
  src/utils/formatMtoShipment.test.js
  src/utils/formatters.js
  src/utils/formatters.test.js
Labels: roci, Pamplemoose

#7968 [MB-10642] Migrate Step component stories to use component decorator and story args
  src/components/Customer/Home/Step/Step.module.scss
  src/components/Customer/Home/Step/Step.stories.jsx
Labels: A-Team

#7977 MB-10537 (Part 1) Remove outdated duty station data
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20211229190325_delete_incorrect_duty_stations.up.sql
Labels: ttv

#7998 MB-10430 display info in move task order tab shipment sidebar
  pkg/testdatagen/scenario/shared.go
  src/components/Office/DefinitionLists/NTSRShipmentInfoList.jsx
  src/components/Office/ShipmentDetails/ShipmentDetails.jsx
  src/components/Office/ShipmentDetails/ShipmentDetails.module.scss
  src/components/Office/ShipmentDetails/ShipmentDetails.stories.jsx
  src/components/Office/ShipmentDetails/ShipmentDetailsSidebar.jsx
  src/components/Office/ShipmentDetails/ShipmentDetailsSidebar.test.jsx
  src/components/Office/ShipmentDisplay/ShipmentDisplay.jsx
  src/components/Office/ShipmentDisplay/ShipmentDisplay.stories.jsx
  src/containers/SimpleSection/SimpleSection.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
  src/types/order.js
  src/utils/shipmentDisplay.jsx
  src/utils/shipmentDisplay.test.jsx
Labels: roci, Pamplemoose, ready-to-merge

#8010 [MB-10620] Prevent notifications for a shipment assigned to an external vendor
  pkg/services/event/event_test.go
  pkg/services/event/notification.go
  pkg/services/event/notification_test.go
Labels: roci, ready-to-merge

#8011 MB-10429 Display Pickup address/facility address on Move Task Order tab for NTS
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/scenario/subscenarios.go
  src/components/Office/ShipmentAddresses/ShipmentAddresses.jsx
  src/components/Office/ShipmentAddresses/ShipmentAddresses.test.jsx
  src/components/Office/ShipmentContainer/ShipmentContainer.stories.jsx
  src/components/Office/ShipmentDetails/ShipmentDetailsMain.jsx
  src/types/shipment.js
Labels: roci

#8021 [MB-11012] Fixes bug where NTS shipment turns into HHG when editing as a SC
  src/components/Office/OrdersDetailForm/OrdersDetailForm.stories.jsx
  src/pages/Office/ServicesCounselingAddShipment/ServicesCounselingAddShipment.jsx
  src/pages/Office/ServicesCounselingEditShipmentDetails/ServicesCounselingEditShipmentDetails.jsx
  src/types/order.js
Labels: bug, roci, ready-to-merge

#8012 [MB-10434] Add EditFacilityInfoModal to Storybook
  src/components/Office/EditFacilityInfoModal/EditFacilityInfoModal.jsx
  src/components/Office/EditFacilityInfoModal/EditFacilityInfoModal.module.scss
  src/components/Office/EditFacilityInfoModal/EditFacilityInfoModal.stories.jsx
  src/components/Office/EditFacilityInfoModal/EditFacilityInfoModal.test.jsx
  src/components/Office/ReviewSITExtensionModal/ReviewSITExtensionModal.module.scss
  src/types/shipment.js
  yarn.lock
Labels: roci, Pamplemoose, ready-to-merge

#8016 MB-10783 allow the too to update shipments
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/m_t_o_agent.go
  pkg/services/mto_shipment/mto_shipment_updater.go
  pkg/services/mto_shipment/mto_shipment_updater_test.go
  src/utils/formatMtoShipment.js
  src/utils/formatMtoShipment.test.js
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: roci, Pamplemoose

#8017 [MB-10537] Part 2: Update existing duty locations
  cypress/integration/mymove/orders.js
  cypress/integration/office/txo/tooFlows.js
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20220112013152_update_duty_locations.up.sql
Labels: ttv

#8013 add storage facility and nts recorded date to notifications payload t…
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/address.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/address.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/address.go
  pkg/gen/primemessages/m_t_o_shipment.go
  pkg/gen/primemessages/storage_facility.go
  pkg/gen/primemessages/update_m_t_o_shipment.go
  pkg/gen/supportapi/embedded_spec.go
  pkg/gen/supportmessages/webhook_notification.go
  pkg/handlers/primeapi/payloads/model_to_payload.go
  pkg/services/event/event_test.go
  pkg/services/event/notification.go
  pkg/services/move_task_order/move_task_order_updater_test.go
  pkg/testdatagen/make_mto_shipment.go
  swagger-def/definitions/Address.yaml
  swagger-def/prime.yaml
  swagger-def/support.yaml
  swagger/ghc.yaml
  swagger/internal.yaml
  swagger/prime.yaml
  swagger/support.yaml
Labels: Pamplemoose, ready-to-merge

#8026 [MB-10537] Part 3: Insert new duty locations
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20220113172826_create_new_duty_locations.up.sql
Labels: ttv

#8025 MB-10433 Don't show estimated weight for NTSR
  src/components/Office/ShipmentDetails/ShipmentDetailsMain.jsx
  src/components/Office/ShipmentWeightDetails/ShipmentWeightDetails.jsx
  src/components/Office/ShipmentWeightDetails/ShipmentWeightDetails.module.scss
  src/components/Office/ShipmentWeightDetails/ShipmentWeightDetails.stories.jsx
  src/components/Office/ShipmentWeightDetails/ShipmentWeightDetails.test.jsx
Labels: roci, Pamplemoose

#8029 [MB-11011] Fix inability of a SC to create an NTS-Release shipment
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/create_m_t_o_shipment.go
  pkg/handlers/ghcapi/internal/payloads/payload_to_model.go
  pkg/handlers/internalapi/internal/payloads/payload_to_model.go
  pkg/handlers/internalapi/mto_shipment_test.go
  pkg/services/mto_shipment/mto_shipment_creator.go
  pkg/services/mto_shipment/mto_shipment_creator_test.go
  pkg/testdatagen/make_mto_shipment.go
  pkg/testdatagen/make_nts_shipment.go
  src/components/Office/DefinitionLists/NTSRShipmentInfoList.jsx
  src/components/Office/DefinitionLists/NTSRShipmentInfoList.stories.jsx
  src/components/Office/DefinitionLists/NTSRShipmentInfoList.test.jsx
  src/components/Office/RequestedShipments/RequestedShipments.jsx
  src/components/Office/ShipmentDisplay/ShipmentDisplay.jsx
  src/components/Office/ShipmentDisplay/ShipmentDisplay.stories.jsx
  src/pages/Office/MoveDetails/MoveDetails.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
  src/types/shipment.js
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: roci, ready-to-merge

#8028 Add where clause to filter out test user email from devlocal service member users list
  pkg/models/user.go
  pkg/models/user_test.go
Labels: A-Team

#8030 [MB-9276] Prime API totalWeight entitlement should include dependents if authorized
  pkg/handlers/converters.go
  pkg/handlers/primeapi/payloads/model_to_payload.go
  pkg/handlers/primeapi/payloads/model_to_payload_test.go
  pkg/handlers/supportapi/internal/payloads/model_to_payload.go
  pkg/handlers/supportapi/internal/payloads/model_to_payload_test.go
  pkg/models/ghc_entitlements.go
Labels: A-Team

#8042 MB-10660-add-commas-to-weight-display
  pkg/notifications/move_submitted.go
  pkg/notifications/move_submitted_test.go
  src/components/Customer/MtoShipmentForm/MtoShipmentForm.jsx
  src/pages/MyMove/Home/index.jsx
  src/utils/formatters.js
  src/utils/formatters.test.js
Labels: A-Team

#8048 Fix potential nil pointer error in SC queue
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
Labels: roci, ready-to-merge

#8050 MB-11015 Upgrade storybook versions
  package.json
  yarn.lock
Labels: A-Team, dependencies

#8040 MB-9872: weight allowances
  src/components/Customer/MtoShipmentForm/MtoShipmentForm.jsx
  src/components/Customer/MtoShipmentForm/MtoShipmentForm.test.jsx
  src/pages/MyMove/CreateOrEditMtoShipment.jsx
  src/pages/MyMove/Home/index.jsx
  src/pages/MyMove/Home/index.test.jsx
Labels: A-Team

#8072 MB-11015 upgrade node fetch due to yarn audit
  package.json
  swagger/ghc.yaml
  swagger/internal.yaml
  yarn.lock
Labels: A-Team

#8000 MB-10966 Update to latest version of milmove-cypress image
  .circleci/config.yml
  Dockerfile.local
  Dockerfile.migrations_local
  Dockerfile.reviewapp
  Dockerfile.tasks_local
  Dockerfile.tools_local
  Dockerfile.webhook_client
  Dockerfile.webhook_client_dp3
  Dockerfile.webhook_client_local
  Makefile
  cypress/Dockerfile.cypress
  package.json
  scripts/gen-assets
  scripts/gen-server
  scripts/pre-commit-swagger-validate
  scripts/run-e2e-test-docker
  yarn.lock
Labels: A-Team

#8059 MB-11015 Upgrade storybook versions to 6.4.14
  package.json
  yarn.lock
Labels: A-Team, dependencies

#8084 MB-9872: Refactor to standardize weight allowance
  src/components/Customer/MtoShipmentForm/MtoShipmentForm.jsx
  src/pages/MyMove/MovingInfo.jsx
  src/pages/MyMove/MovingInfo.test.jsx
Labels: A-Team

#8046 MB-10529: Add Accounting Codes section to TIO payment authorization
  src/components/Office/ReviewServiceItems/ReviewAccountingCodes.jsx
  src/components/Office/ReviewServiceItems/ReviewAccountingCodes.module.scss
  src/components/Office/ReviewServiceItems/ReviewAccountingCodes.stories.jsx
  src/components/Office/ReviewServiceItems/ReviewAccountingCodes.test.jsx
  src/components/Office/ReviewServiceItems/ReviewDetailsCard.jsx
  src/components/Office/ReviewServiceItems/ReviewServiceItems.jsx
  src/components/Office/ReviewServiceItems/ReviewServiceItems.stories.jsx
  src/pages/Office/PaymentRequestReview/PaymentRequestReview.jsx
  src/pages/Office/PaymentRequestReview/PaymentRequestReview.test.jsx
  src/pages/Office/TXOMoveInfo/TXOMoveInfo.jsx
  src/types/serviceItems.js
Labels: roci, Pamplemoose

#8073 [MB-7998] Customer weight allowance includes dependents when updating rank or dependents
  pkg/models/order.go
  pkg/models/order_test.go
  src/components/Customer/EditOrdersForm/EditOrdersForm.stories.jsx
  src/components/Customer/MtoShipmentForm/MtoShipmentForm.jsx
  src/pages/MyMove/EditOrders.jsx
  src/pages/MyMove/EditOrders.test.jsx
  src/pages/MyMove/MovingInfo.jsx
  src/pages/MyMove/MovingInfo.test.jsx
  src/pages/MyMove/Profile/EditServiceInfo.jsx
  src/pages/MyMove/Profile/EditServiceInfo.test.jsx
  src/pages/MyMove/Profile/Profile.jsx
Labels: A-Team

#8074 MB-11015 Upgrade to latest cypress docker image
  .circleci/config.yml
  cypress/Dockerfile.cypress
Labels: A-Team

#8089 [MB-10776] Update ADR Links for 0066
  docs/adr/0066-use-custom-nullable-types-for-patch-requests.md
Labels: roci, Pamplemoose, ready-to-merge

#8051 MB-10672 FE external vendor tag and hide checkbox on external vendor shipments
  pkg/testdatagen/scenario/subscenarios.go
  src/components/Office/ShipmentDisplay/ShipmentDisplay.jsx
  src/components/Office/ShipmentDisplay/ShipmentDisplay.stories.jsx
  src/components/Office/ShipmentDisplay/ShipmentDisplay.test.jsx
  src/components/Office/ShipmentDisplay/ShipmentDisplayTestData.js
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
Labels: roci

#8069 [MB-11026] Use entitlements table for SIT entitlement
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/mto_shipment.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/handlers/internalapi/orders.go
  pkg/payment_request/service_param_value_lookups/number_days_sit_lookup.go
  pkg/payment_request/service_param_value_lookups/number_days_sit_lookup_test.go
  pkg/payment_request/service_param_value_lookups/service_param_value_lookups.go
  pkg/services/mocks/ShipmentSITStatus.go
  pkg/services/mto_shipment.go
  pkg/services/mto_shipment/shipment_sit_status.go
  pkg/services/mto_shipment/shipment_sit_status_test.go
  pkg/testdatagen/make_entitlement.go
Labels: ttv

#8082 [MB-11206] Remove etag from storage facility address on shipment form update
  src/utils/formatMtoShipment.js
  src/utils/formatMtoShipment.test.js
Labels: roci, Pamplemoose, ready-to-merge

#8068 [MB-10570] Prevent the prime from seeing external-vendor NTS and NTS-Release shipments
  pkg/handlers/ghcapi/move_task_order_test.go
  pkg/handlers/primeapi/move_task_order.go
  pkg/handlers/primeapi/move_task_order_test.go
  pkg/handlers/primeapi/mto_shipment.go
  pkg/handlers/primeapi/mto_shipment_test.go
  pkg/services/move_task_order.go
  pkg/services/move_task_order/move_task_order_fetcher.go
  pkg/services/move_task_order/move_task_order_fetcher_test.go
  pkg/services/move_task_order/move_task_order_updater.go
  pkg/services/move_task_order/move_task_order_updater_test.go
  pkg/services/mto_agent/rules.go
  pkg/services/mto_agent/rules_test.go
  pkg/services/mto_shipment/mto_shipment_address_updater.go
  pkg/services/mto_shipment/mto_shipment_address_updater_test.go
  pkg/services/mto_shipment/validation.go
  pkg/services/mto_shipment/validation_test.go
  pkg/services/reweigh/rules.go
  pkg/services/reweigh/rules_test.go
  pkg/services/sit_extension/sit_extension_creator.go
  pkg/services/sit_extension/sit_extension_creator_test.go
Labels: roci, ready-to-merge

#8090 MB-11245 Remove CAC access for carterjones, monfresh, ronolibert, and shkeating
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20220126235958_remove_cac_access_carterjones_monfresh_ronolibert_and_shkeating.up.sql
Labels: A-Team

#8094 [MB-11016] Add back dummy package-lock.json to clear dependabot security alerts
  package-lock.json
Labels: A-Team

#8038 [MB-10435] Storage facility edit modal implementation
  src/components/Office/EditFacilityInfoModal/EditFacilityInfoModal.jsx
  src/components/Office/EditFacilityInfoModal/EditFacilityInfoModal.module.scss
  src/components/Office/ShipmentDetails/ShipmentDetails.jsx
  src/components/Office/ShipmentDetails/ShipmentDetailsSidebar.jsx
  src/components/Office/ShipmentDetails/ShipmentDetailsSidebar.module.scss
  src/components/Office/ShipmentDetails/ShipmentDetailsSidebar.test.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
  src/utils/formatMtoShipment.js
Labels: roci, Pamplemoose, ready-to-merge

#8047 [MB-10525] backend returns failure if create payment request called for external shipment
  pkg/services/payment_request/payment_request_creator.go
  pkg/services/payment_request/payment_request_creator_test.go
Labels: Pamplemoose, ready-to-merge

#8075 MB-11181-update-format-weights-import
  src/components/Office/AllowancesDetailForm/AllowancesDetailForm.jsx
  src/components/Office/BillableWeight/BillableWeightCard/BillableWeightCard.jsx
  src/components/Office/BillableWeight/BillableWeightCard/BillableWeightCard.test.jsx
  src/components/Office/BillableWeight/EditBillableWeight/EditBillableWeight.jsx
  src/components/Office/BillableWeight/EditBillableWeight/EditBillableWeight.test.jsx
  src/components/Office/BillableWeight/ShipmentCard/ShipmentCard.jsx
  src/components/Office/BillableWeight/ShipmentCard/ShipmentCard.test.jsx
  src/components/Office/DefinitionLists/AllowancesList.jsx
  src/components/Office/DefinitionLists/NTSRShipmentInfoList.jsx
  src/components/Office/EditMaxBillableWeightModal/EditMaxBillableWeightModal.jsx
  src/components/Office/ServiceItemCalculations/helpers.js
  src/components/Office/ServiceItemDetails/ServiceItemDetails.jsx
  src/components/Office/ShipmentForm/ShipmentForm.jsx
  src/components/Office/ShipmentWeightDetails/ShipmentWeightDetails.jsx
  src/components/Office/WeightDisplay/WeightDisplay.jsx
  src/components/Office/WeightSummary/WeightSummary.jsx
  src/components/Office/WeightSummary/WeightSummary.test.jsx
  src/components/ShipmentList/ShipmentList.test.jsx
  src/components/ShipmentList/index.jsx
  src/pages/Office/ReviewBillableWeight/ReviewBillableWeight.test.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdateForm.jsx
  src/scenes/Office/Ppm/WeightsPanel.jsx
  src/shared/formatters.js
  src/shared/formatters.test.js
Labels: A-Team
