Repository transcom/mymove, pull requests merged in 2022-02, with the labels that each got.

#8111 [MB-11016] Update rickar/cal holiday workday library to v2
  go.mod
  go.sum
  pkg/dates/calculators.go
  pkg/dates/calendar.go
  pkg/models/validators.go
Labels: A-Team

#8076 MB-11140: PPM DB ADR
  docs/adr/0067-ppm-db-design.md
  docs/adr/index.md
Labels: A-Team

#8108 MB-11054: Creates ServiceOrderNumberModal, adds it to ShipmentDetails
  src/components/Office/ServiceOrderNumberModal/ServiceOrderNumberModal.jsx
  src/components/Office/ServiceOrderNumberModal/ServiceOrderNumberModal.stories.jsx
  src/components/Office/ServiceOrderNumberModal/ServiceOrderNumberModal.test.jsx
  src/components/Office/ShipmentDetails/ShipmentDetails.jsx
  src/components/Office/ShipmentDetails/ShipmentDetails.stories.jsx
  src/components/Office/ShipmentDetails/ShipmentDetailsSidebar.jsx
  src/components/Office/ShipmentDetails/ShipmentDetailsSidebar.test.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
Labels: roci, Pamplemoose

#8101 [MB-11219] Adjust addresses used in pricing services for NTS and NTS-Release shipments
  pkg/payment_request/service_param_value_lookups/service_param_value_lookups.go
  pkg/payment_request/service_param_value_lookups/service_param_value_lookups_test.go
  pkg/testdatagen/make_mto_service_item.go
Labels: roci, ready-to-merge

#8096 [MB-10776] add nullable string for SACs (HHG & NTS) and NTS TAC fields
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/counseling_update_order_payload.go
  pkg/gen/ghcmessages/update_order_payload.go
  pkg/handlers/ghcapi/orders_test.go
  pkg/handlers/internalapi/office_test.go
  pkg/models/order.go
  pkg/services/order/order_updater.go
  pkg/services/order/order_updater_test.go
  pkg/swagger/nullable/string.go
  swagger-def/definitions/NullableString.yaml
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: Pamplemoose

#8110 [MB-10876] Edit SIT allowance as Services Counselor and TOO
  cypress/integration/office/servicescounseling/servicesCounselingFlows.js
  cypress/integration/office/txo/tooFlows.js
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/counseling_update_allowance_payload.go
  pkg/gen/ghcmessages/update_allowance_payload.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/orders_test.go
  pkg/services/order/order_updater.go
  src/components/Office/AllowancesDetailForm/AllowancesDetailForm.jsx
  src/components/Office/AllowancesDetailForm/AllowancesDetailForm.stories.jsx
  src/pages/Office/MoveAllowances/MoveAllowances.jsx
  src/pages/Office/MoveAllowances/MoveAllowances.test.jsx
  src/pages/Office/ServicesCounselingMoveAllowances/ServicesCounselingMoveAllowances.jsx
  src/pages/Office/ServicesCounselingMoveAllowances/ServicesCounselingMoveAllowances.test.jsx
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: ttv

#8106 [MB-10959] Upgrade eslint airbnb to v19 and fix linting errors
  .eslintrc.js
  package.json
  src/components/Customer/MtoShipmentForm/MtoShipmentForm.jsx
  src/components/CustomerRemarksAgentsDetails/index.jsx
  src/components/DocumentViewer/DocumentViewer.jsx
  src/components/MigratedModal/MigratedModal.stories.jsx
  src/components/Office/ServiceItemCalculations/ServiceItemCalculations.jsx
  src/components/Office/ServiceItemCalculations/helpers.js
  src/components/Office/ShipmentForm/ShipmentForm.jsx
  src/components/PrimeUI/CreatePaymentRequestForm/CreatePaymentRequestForm.jsx
  src/components/form/fields/DutyStationInput.test.jsx
  src/constants/serviceItems.js
  src/content/serviceItems.js
  src/layout/LogoutOnInactivity.jsx
  src/pages/MyMove/Home/index.jsx
  src/pages/Office/MovePaymentRequests/MovePaymentRequests.jsx
  src/pages/Office/ReviewBillableWeight/ReviewBillableWeight.jsx
  src/pages/Office/ServicesCounselingEditShipmentDetails/ServicesCounselingEditShipmentDetails.jsx
  src/pages/Office/index.jsx
  src/store/auth/reducer.js
  src/store/flash/reducer.js
  src/store/interceptor/reducer.js
  src/store/onboarding/reducer.js
  yarn.lock
Labels: A-Team, ready-to-merge

#8102 MB-11057 Don't show billable weights warning flags for NTSR
  src/components/ShipmentList/ShipmentList.test.jsx
  src/components/ShipmentList/index.jsx
Labels: roci, Pamplemoose, ready-to-merge

#8100 MB-10670 ppm db migration model
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20220127234422_create_ppm_shipments_table.up.sql
  migrations/app/schema/20220203001924_add_ppm_to_mto_shipments_shipment_type_enum_values.up.sql
  pkg/models/mto_shipments.go
  pkg/models/ppm_shipment.go
  pkg/services/mto_shipment/mto_shipment_creator_test.go
Labels: A-Team

#8118 [MB-10958] Rename duty_station_names table to duty_location_names
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20220204213113_rename_duty_station_names.up.sql
  pkg/models/duty_location.go
  pkg/models/duty_station_names.go
  pkg/models/duty_station_test.go
Labels: ttv

#8107 [MB-11072] Add external vendor weight summary to payment requests page
  src/components/Office/BillableWeight/BillableWeightCard/BillableWeightCard.jsx
  src/components/Office/BillableWeight/BillableWeightCard/BillableWeightCard.test.jsx
  src/components/Office/ExternalVendorWeightSummary/ExternalVendorWeightSummary.jsx
  src/components/Office/ExternalVendorWeightSummary/ExternalVendorWeightSummary.module.scss
  src/components/Office/ExternalVendorWeightSummary/ExternalVendorWeightSummary.stories.jsx
  src/components/Office/ExternalVendorWeightSummary/ExternalVendorWeightSummary.test.jsx
Labels: roci, Pamplemoose, ready-to-merge

#8109 MB-10671 FE, TOO When shipment card has missing info, the checkbox is disabled
  src/components/Office/RequestedShipments/RequestedShipments.jsx
  src/components/Office/ShipmentDisplay/ShipmentDisplay.jsx
  src/components/Office/ShipmentDisplay/ShipmentDisplay.stories.jsx
  src/components/Office/ShipmentDisplay/ShipmentDisplay.test.jsx
Labels: roci, ready-to-merge

#8116 MB-10437 Link edit accounting codes modal to edit link on shipment sidebar of move task order page
  src/components/Office/AccountingCodesModal/AccountingCodesModal.jsx
  src/components/Office/AccountingCodesModal/AccountingCodesModal.stories.jsx
  src/components/Office/AccountingCodesModal/AccountingCodesModal.test.jsx
  src/components/Office/ShipmentDetails/ShipmentDetails.jsx
  src/components/Office/ShipmentDetails/ShipmentDetails.stories.jsx
  src/components/Office/ShipmentDetails/ShipmentDetailsSidebar.jsx
  src/components/Office/ShipmentDetails/ShipmentDetailsSidebar.test.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.test.jsx
Labels: roci, ready-to-merge

#8135 MB-11460: Support local swagger binary
  Makefile
  scripts/gen-server
  scripts/pre-commit-swagger-validate
Labels: ready-to-merge

#8088 MB-11055 Calculate RequiredDeliveryDate for NTS shipments
  pkg/handlers/primeapi/mto_shipment.go
  pkg/handlers/primeapi/mto_shipment_test.go
  pkg/services/mto_shipment/mto_shipment_updater.go
  pkg/services/mto_shipment/mto_shipment_updater_test.go
  pkg/services/mto_shipment/shipment_approver.go
  pkg/services/mto_shipment/shipment_approver_test.go
Labels: roci, Pamplemoose, ready-to-merge

#8121 [MB-11261] Archive ppm data
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20220204201618_archive_ppm_data.up.sql
  pkg/testdatagen/make_signed_certification.go
  pkg/testdatagen/scenario/e2ebasic.go
  pkg/testdatagen/scenario/shared.go
Labels: A-Team

#8139 [MB-10909] Require delivery address for NTS-release on shipment form
  src/components/Office/ShipmentForm/ShipmentForm.jsx
  src/components/Office/ShipmentForm/ShipmentForm.test.jsx
Labels: roci, Pamplemoose, ready-to-merge

#8140 MB-10908: Adds TAC validation to TXO and Service Counselor edit orders pages
  src/pages/Office/Orders/Orders.jsx
  src/pages/Office/Orders/Orders.test.jsx
  src/pages/Office/ServicesCounselingOrders/ServicesCounselingOrders.jsx
  src/pages/Office/ServicesCounselingOrders/ServicesCounselingOrders.test.jsx
  src/reducers/tacValidation.js
  src/reducers/tacValidation.test.js
Labels: roci, Pamplemoose

#8129 [MB-10661] create nullable types for PATCH requests
  pkg/swagger/nullable/bool.go
  pkg/swagger/nullable/bool_test.go
  pkg/swagger/nullable/float.go
  pkg/swagger/nullable/float_test.go
  pkg/swagger/nullable/int.go
  pkg/swagger/nullable/int_test.go
  pkg/swagger/nullable/string_test.go
  swagger-def/definitions/NullableBool.yaml
  swagger-def/definitions/NullableFloat.yaml
  swagger-def/definitions/NullableInt.yaml
Labels: ttv

#8148 [MB-11460] Allow swagger version matching to work with or without the leading 'v'
  scripts/gen-server
  scripts/pre-commit-swagger-validate
Labels: ready-to-merge

#8122 Update pre commit hadolint hook
  .pre-commit-config.yaml
Labels: A-Team

#8134 [MB-11010] PPM booking dates and location form storybook
  package.json
  src/components/Customer/PPMBooking/DatesAndLocation/DatesAndLocation.jsx
  src/components/Customer/PPMBooking/DatesAndLocation/DatesAndLocation.module.scss
  src/components/Customer/PPMBooking/DatesAndLocation/DatesAndLocation.stories.jsx
  src/components/Customer/PPMBooking/DatesAndLocation/DatesAndLocation.test.jsx
  src/types/customerShapes.js
  src/utils/validation.js
  yarn.lock
Labels: A-Team

#8141 [MB-11220] Pricing on NTS-Release shipments should use ActualPickupDate
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20220207230521_adjust_pricing_params_for_ntsr.up.sql
  pkg/handlers/supportapi/payment_request_test.go
  pkg/models/service_item_param_key.go
  pkg/payment_request/service_param_value_lookups/actual_pickup_date_lookup.go
  pkg/payment_request/service_param_value_lookups/actual_pickup_date_lookup_test.go
  pkg/payment_request/service_param_value_lookups/reference_date_lookup.go
  pkg/payment_request/service_param_value_lookups/reference_date_lookup_test.go
  pkg/payment_request/service_param_value_lookups/requested_pickup_date_lookup.go
  pkg/payment_request/service_param_value_lookups/requested_pickup_date_lookup_test.go
  pkg/payment_request/service_param_value_lookups/service_param_value_lookups.go
  pkg/services/ghcrateengine/domestic_crating_pricer.go
  pkg/services/ghcrateengine/domestic_crating_pricer_test.go
  pkg/services/ghcrateengine/domestic_destination_additional_days_sit_pricer.go
  pkg/services/ghcrateengine/domestic_destination_additional_days_sit_pricer_test.go
  pkg/services/ghcrateengine/domestic_destination_first_day_sit_pricer.go
  pkg/services/ghcrateengine/domestic_destination_first_day_sit_pricer_test.go
  pkg/services/ghcrateengine/domestic_destination_pricer.go
  pkg/services/ghcrateengine/domestic_destination_pricer_test.go
  pkg/services/ghcrateengine/domestic_destination_shuttling_pricer.go
  pkg/services/ghcrateengine/domestic_destination_shuttling_pricer_test.go
  pkg/services/ghcrateengine/domestic_destination_sit_delivery_pricer.go
  pkg/services/ghcrateengine/domestic_destination_sit_delivery_pricer_test.go
  pkg/services/ghcrateengine/domestic_linehaul_pricer.go
  pkg/services/ghcrateengine/domestic_linehaul_pricer_test.go
  pkg/services/ghcrateengine/domestic_nts_pack_pricer.go
  pkg/services/ghcrateengine/domestic_nts_pack_pricer_test.go
  pkg/services/ghcrateengine/domestic_origin_additional_days_sit_pricer.go
  pkg/services/ghcrateengine/domestic_origin_additional_days_sit_pricer_test.go
  pkg/services/ghcrateengine/domestic_origin_first_day_sit_pricer.go
  pkg/services/ghcrateengine/domestic_origin_first_day_sit_pricer_test.go
  pkg/services/ghcrateengine/domestic_origin_pricer.go
  pkg/services/ghcrateengine/domestic_origin_pricer_test.go
  pkg/services/ghcrateengine/domestic_origin_shuttling_pricer.go
  pkg/services/ghcrateengine/domestic_origin_shuttling_pricer_test.go
  pkg/services/ghcrateengine/domestic_origin_sit_pickup_pricer.go
  pkg/services/ghcrateengine/domestic_origin_sit_pickup_pricer_test.go
  pkg/services/ghcrateengine/domestic_pack_pricer.go
  pkg/services/ghcrateengine/domestic_pack_pricer_test.go
  pkg/services/ghcrateengine/domestic_shorthaul_pricer.go
  pkg/services/ghcrateengine/domestic_shorthaul_pricer_test.go
  pkg/services/ghcrateengine/domestic_uncrating_pricer.go
  pkg/services/ghcrateengine/domestic_uncrating_pricer_test.go
  pkg/services/ghcrateengine/domestic_unpack_pricer.go
  pkg/services/ghcrateengine/domestic_unpack_pricer_test.go
  pkg/services/ghcrateengine/fuel_surcharge_pricer_test.go
  pkg/services/ghcrateengine/param_convert_test.go
  pkg/services/ghcrateengine/pricer_helpers.go
  pkg/services/ghcrateengine/pricer_helpers_test.go
  pkg/services/ghcrateengine/pricer_query_helpers.go
  pkg/services/invoice/ghc_payment_request_invoice_generator_test.go
  pkg/services/payment_request/payment_request_creator_test.go
  pkg/services/payment_request/payment_request_reviewed_processor_test.go
  pkg/testdatagen/make_mto_service_item.go
  pkg/testdatagen/make_service_param.go
  pkg/testdatagen/scenario/e2ebasic.go
  pkg/testdatagen/scenario/shared.go
Labels: roci, ready-to-merge

#8128 MB-11455 : start of swagger fixes
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/move_status.go
  pkg/gen/ghcmessages/queue_move.go
  pkg/gen/ghcmessages/queue_move_status.go
  pkg/gen/ghcmessages/queue_payment_request.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalapi/internaloperations/users/is_logged_in_user.go
  pkg/gen/internalapi/internaloperations/users/is_logged_in_user_responses.go
  pkg/gen/internalmessages/duty_location_payload.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/queues_test.go
  pkg/handlers/internalapi/duty_locations.go
  pkg/handlers/internalapi/duty_locations_test.go
  pkg/handlers/internalapi/internal/payloads/model_to_payload.go
  pkg/handlers/primeapi/move_task_order_test.go
  pkg/handlers/primeapi/payloads/model_to_payload.go
  pkg/services/order/order_fetcher.go
  src/types/user.js
  swagger-def/definitions/DutyLocationPayload.yaml
  swagger-def/ghc.yaml
  swagger-def/internal.yaml
  swagger/ghc.yaml
  swagger/internal.yaml
Labels: ready-to-merge

#8126 MB-11349 Add Testdatagen Data For PPMShipments - Customer Flow
  pkg/models/mto_shipments.go
  pkg/models/ppm_shipment.go
  pkg/testdatagen/make_ppm_shipment.go
  pkg/testdatagen/scenario/devseed.go
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/scenario/subscenarios.go
  pkg/testdatagen/shared.go
Labels: A-Team

#8142 Mb 11028 backend dates location nt
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20220208225215_add_draft_to_ppm_shipment_status.up.sql
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/m_t_o_shipment_type.go
  pkg/models/ppm_shipment.go
  pkg/services/mto_shipment/mto_shipment_creator.go
  pkg/services/mto_shipment/mto_shipment_creator_test.go
  pkg/services/ppmshipment.go
  pkg/services/ppmshipment/ppm_shipment_creator.go
  pkg/services/ppmshipment/ppm_shipment_creator_test.go
  pkg/services/ppmshipment/ppm_shipment_service_test.go
  pkg/services/ppmshipment/rules.go
  pkg/services/ppmshipment/rules_test.go
  pkg/services/ppmshipment/validation.go
  pkg/services/ppmshipment/validation_test.go
  pkg/testdatagen/make_mto_shipment.go
  swagger-def/internal.yaml
  swagger/internal.yaml
Labels: A-Team

#8186 [MB-10646] Increase width to accommodate NTS-r shipments
  src/components/ShipmentList/ShipmentList.module.scss
Labels: roci, ready-to-merge

#8179 MB-11359 (FE, TOO) TOO can request service items for ext moved shipments
  cypress/integration/office/txo/tooFlows.js
  src/components/Office/RequestedShipments/RequestedShipments.jsx
  src/components/Office/RequestedShipments/RequestedShipments.stories.jsx
  src/components/Office/RequestedShipments/RequestedShipments.test.jsx
  src/components/Office/RequestedShipments/RequestedShipmentsTestData.js
Labels: roci

#8177 [MB-10669] PPM booking dates location page integration
  src/components/Customer/EditContactInfoForm/EditContactInfoForm.module.scss
  src/components/Customer/PPMBooking/DateAndLocationForm/DateAndLocationForm.jsx
  src/components/Customer/PPMBooking/DateAndLocationForm/DateAndLocationForm.module.scss
  src/components/Customer/PPMBooking/DateAndLocationForm/DateAndLocationForm.stories.jsx
  src/components/Customer/PPMBooking/DateAndLocationForm/DateAndLocationForm.test.jsx
  src/constants/routes.js
  src/pages/MyMove/CreateOrEditMtoShipment.jsx
  src/pages/MyMove/CreateOrEditMtoShipment.test.jsx
  src/pages/MyMove/Home/index.jsx
  src/pages/MyMove/Home/index.test.jsx
  src/pages/MyMove/PPMBooking/DateAndLocation.jsx
  src/pages/MyMove/PPMBooking/DateAndLocation.module.scss
  src/pages/MyMove/PPMBooking/DateAndLocation.test.jsx
  src/styles/form.module.scss
  src/utils/validation.js
Labels: A-Team

#8193 [MB-10970] Update remarks section helper text for NTS-Release shipments
  src/components/Customer/MtoShipmentForm/MtoShipmentForm.jsx
  src/components/Customer/MtoShipmentForm/MtoShipmentForm.test.jsx
Labels: roci, ready-to-merge

#8191 [MB-11329] Fix issue where NTS-Release shipments don't appear in TOO queue
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/services/order/order_fetcher.go
  pkg/services/order/order_fetcher_test.go
Labels: roci, ready-to-merge

#8189 [MB-10663] Add alert message to TOO's viewing external vendor shipments
  src/components/Office/ShipmentForm/ShipmentForm.jsx
  src/components/Office/ShipmentForm/ShipmentForm.stories.jsx
  src/components/Office/ShipmentForm/ShipmentForm.test.jsx
Labels: roci, Pamplemoose, ready-to-merge

#8197 MB-11608 Update ppm shipment to have more required fields
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20220218230224_update_ppm_shipments_to_have_more_required_fields.up.sql
  pkg/models/ppm_shipment.go
  pkg/services/ppmshipment/ppm_shipment_creator_test.go
  pkg/services/ppmshipment/rules.go
  pkg/services/ppmshipment/rules_test.go
  pkg/testdatagen/make_ppm_shipment.go
  pkg/testdatagen/scenario/devseed.go
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/scenario/subscenarios.go
Labels: A-Team

#8194 MB-11074: Updates to ShipmentCard subcomponent in billable weight review flow
  src/components/Office/BillableWeight/ShipmentCard/ShipmentCard.jsx
  src/components/Office/BillableWeight/ShipmentCard/ShipmentCard.stories.jsx
  src/components/Office/BillableWeight/ShipmentCard/ShipmentCard.test.jsx
Labels: roci

#8202 MB-11032: Estimated Pro Gear can be 0
  src/components/Customer/PPMBooking/EstimatedWeightsProGearForm/EstimatedWeightsProGearForm.jsx
Labels: A-Team

#8198 MB-10354 List external vendor shipments last
  pkg/services/mto_shipment/mto_shipment_fetcher.go
  pkg/services/mto_shipment/mto_shipment_fetcher_test.go
  src/components/Office/DefinitionLists/ShipmentInfoList.jsx
  src/components/Office/DefinitionLists/ShipmentInfoListSelector.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.test.jsx
Labels: roci, ready-to-merge

#8201 [ MB-7952, MB-11694 ] Sign out should sign users out of MM and login.gov
  src/containers/Headers/CustomerLoggedInHeader.jsx
  src/containers/Headers/OfficeLoggedInHeader.jsx
  src/scenes/SystemAdmin/shared/Menu.jsx
Labels: security

#8206 MB-11553 Add PPM shipment to mto shipments payload
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/m_t_o_shipment.go
  pkg/gen/internalmessages/p_p_m_shipment.go
  pkg/gen/internalmessages/p_p_m_shipment_status.go
  pkg/handlers/apitests.go
  pkg/handlers/internalapi/internal/payloads/model_to_payload.go
  pkg/handlers/internalapi/mto_shipment_test.go
  pkg/handlers/primeapi/mto_shipment_test.go
  pkg/testdatagen/make_ppm_shipment.go
  pkg/testdatagen/shared.go
  swagger-def/internal.yaml
  swagger/internal.yaml
Labels: A-Team

#8205 MB-11592 make ntsr shipment weight conditional
  src/components/Customer/MtoShipmentForm/getShipmentOptions.js
  src/components/Office/ShipmentForm/ShipmentForm.jsx
  src/components/Office/ShipmentWeightInput/ShipmentWeightInput.jsx
  src/components/Office/ShipmentWeightInput/ShipmentWeightInput.stories.jsx
  src/components/Office/ShipmentWeightInput/ShipmentWeightInput.test.jsx
Labels: roci, ready-to-merge

#8213 MB-11013 - Make Vendor conditional in ShipmentForm
  src/components/Office/ShipmentForm/ShipmentForm.jsx
  src/components/Office/ShipmentForm/ShipmentForm.stories.jsx
  src/components/Office/ShipmentForm/ShipmentForm.test.jsx
Labels: roci, ready-to-merge

#8171 [MB-10957] Add new columns for duty station rename
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20220214222638_create_new_cols_for_duty_station_to_location_rename.up.sql
Labels: ttv

#8215 MB-11671 Change 'Shipment Weight' wording for NTSR
  src/components/Office/DefinitionLists/NTSRShipmentInfoList.jsx
  src/components/Office/ShipmentForm/ShipmentForm.test.jsx
  src/components/Office/ShipmentWeightInput/ShipmentWeightInput.jsx
  src/components/Office/ShipmentWeightInput/ShipmentWeightInput.test.jsx
Labels: roci, ready-to-merge
