Repository transcom/mymove, pull requests merged in 2023-12, with the labels that each got.

#11616 Stop immediate trdm call
  cmd/milmove/serve.go
  pkg/trdm/last_table_update.go
  pkg/trdm/last_table_update_test.go
Labels: Mountain Movers

#11635 B-18115 updating prime sim sit extension
  playwright/tests/office/primesimulator/primeSimulatorFlows.spec.js
  src/components/PrimeUI/CreateSITExtensionRequestForm/CreateSITExtensionRequestForm.jsx
  src/components/PrimeUI/CreateSITExtensionRequestForm/CreateSITExtensionRequestForm.test.jsx
  src/components/PrimeUI/Shipment/Shipment.jsx
  src/constants/routes.js
  src/pages/Office/index.jsx
  src/pages/PrimeUI/CreateSITExtensionRequest/CreateSITExtensionRequest.jsx
  src/pages/PrimeUI/CreateSITExtensionRequest/CreateSITExtensionRequest.test.jsx
  src/pages/PrimeUI/MoveTaskOrder/MoveDetails.jsx
  src/services/primeApi.js
Labels: ByteSize M&Ms

#11629 B-18342 Fix for DDDSIT sit departure date formatting with UTC
  src/components/Office/ServiceItemDetails/ServiceItemDetails.jsx
Labels: Mountain Movers

#11630 B 17849 restrict records returned by prime simulator
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/ghcapi/ghcoperations/queues/list_prime_moves.go
  pkg/gen/ghcapi/ghcoperations/queues/list_prime_moves_parameters.go
  pkg/gen/ghcapi/ghcoperations/queues/list_prime_moves_responses.go
  pkg/gen/ghcapi/ghcoperations/queues/list_prime_moves_urlbuilder.go
  pkg/gen/ghcmessages/list_prime_move.go
  pkg/gen/ghcmessages/list_prime_moves.go
  pkg/gen/ghcmessages/list_prime_moves_result.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/queues.go
  pkg/handlers/ghcapi/queues_test.go
  pkg/services/mocks/MoveTaskOrderFetcher.go
  pkg/services/move_task_order.go
  pkg/services/move_task_order/move_task_order_fetcher.go
  pkg/services/move_task_order/move_task_order_fetcher_test.go
  src/hooks/queries.js
  src/pages/PrimeUI/AvailableMoves/AvailableMovesQueue.jsx
  src/pages/PrimeUI/AvailableMoves/AvailableMovesQueue.test.jsx
  src/services/ghcApi.js
  swagger-def/ghc.yaml
  swagger-def/prime.yaml
  swagger/ghc.yaml
  swagger/prime.yaml
Labels: G-Unit

#11632 deprecate trdm
  .envrc
  cmd/milmove/serve.go
  pkg/cli/trdm.go
  pkg/models/trdm_get_table_request.go
  pkg/models/trdm_get_table_response.go
  pkg/models/trdm_last_table_update_request.go
  pkg/models/trdm_last_table_update_response.go
  pkg/parser/loa/fixtures/Bad Line Of Accounting.txt
  pkg/parser/loa/fixtures/Line Of Accounting.txt
  pkg/parser/loa/parse.go
  pkg/parser/loa/parse_test.go
  pkg/parser/tac/fixtures/Bad Transportation Account.txt
  pkg/parser/tac/fixtures/Transportation Account.txt
  pkg/parser/tac/parse.go
  pkg/parser/tac/parse_test.go
  pkg/trdm/api_gateway.go
  pkg/trdm/get_table.go
  pkg/trdm/get_table_test.go
  pkg/trdm/last_table_update.go
  pkg/trdm/last_table_update_test.go
  pkg/trdm/trdm.go
  pkg/trdm/trdm_test.go
Labels: Mountain Movers

#11638 B 18031 prime UI update sit service items
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/m_t_o_service_item_origin_s_i_t.go
  pkg/gen/primemessages/update_m_t_o_service_item_model_type.go
  pkg/gen/primemessages/update_m_t_o_service_item_s_i_t.go
  pkg/gen/primev2api/embedded_spec.go
  pkg/gen/primev2messages/m_t_o_service_item_origin_s_i_t.go
  pkg/handlers/primeapi/payloads/model_to_payload.go
  pkg/handlers/primeapi/payloads/payload_to_model.go
  src/components/form/AddressFields/AddressFields.jsx
  src/constants/routes.js
  src/constants/serviceItems.js
  src/pages/Office/index.jsx
  src/pages/PrimeUI/MoveTaskOrder/MoveDetails.jsx
  src/pages/PrimeUI/MoveTaskOrder/MoveDetails.module.scss
  src/pages/PrimeUI/MoveTaskOrder/MoveDetails.test.jsx
  src/pages/PrimeUI/UpdateServiceItems/PrimeUIUpdateDestSITForm.jsx
  src/pages/PrimeUI/UpdateServiceItems/PrimeUIUpdateDestSITForm.test.jsx
  src/pages/PrimeUI/UpdateServiceItems/PrimeUIUpdateOriginSITForm.jsx
  src/pages/PrimeUI/UpdateServiceItems/PrimeUIUpdateOriginSITForm.test.jsx
  src/pages/PrimeUI/UpdateServiceItems/PrimeUIUpdateSITForms.module.scss
  src/pages/PrimeUI/UpdateServiceItems/PrimeUIUpdateSitServiceItem.jsx
  src/pages/PrimeUI/UpdateServiceItems/PrimeUpdateSitServiceItem.test.jsx
  src/services/primeApi.js
  swagger-def/definitions/prime/MTOServiceItemOriginSIT.yaml
  swagger-def/prime.yaml
  swagger/prime.yaml
  swagger/prime_v2.yaml
Labels: Mountain Movers

#11642 B 17984 update payment reminder email
  pkg/notifications/move_payment_reminder.go
  pkg/notifications/move_payment_reminder_test.go
Labels: ByteSize M&Ms

#11641 B-18032: Allow an Update for an approved service item
  pkg/services/mto_service_item/mto_service_item_validators.go
Labels: Mountain Movers

#11637 B 18342 correct date formats for sit related items
  src/components/Office/DefinitionLists/ShipmentInfoList.jsx
  src/components/Office/ServiceItemCalculations/helpers.js
  src/components/Office/ServiceItemDetails/ServiceItemDetails.jsx
  src/components/Office/ShipmentDetails/ShipmentDetailsMain.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.test.jsx
Labels: Mountain Movers

#11636 B-18162 add violations to pws_violations table
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20231208213618_update_pws_violations_qae.up.sql
Labels: G-Unit

#11649 B-17956: Fix "Total days used" to not exceed "total days of SIT approved".
  src/components/Office/ReviewSITExtensionModal/ReviewSITExtensionModal.jsx
  src/components/Office/ShipmentSITDisplay/ShipmentSITDisplay.jsx
  src/components/Office/SubmitSITExtensionModal/SubmitSITExtensionModal.jsx
Labels: ByteSize M&Ms

#11644 added check for sc when approving ppm with bad allowances
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.module.scss
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.test.jsx
Labels: G-Unit

#11646 B 17926: New download orders Prime api for ghc counseling
  .circleci/config.yml
  go.mod
  go.sum
  pkg/gen/primeapi/configure_mymove.go
  pkg/gen/primeapi/doc.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/move_task_order/download_move_order.go
  pkg/gen/primeapi/primeoperations/move_task_order/download_move_order_parameters.go
  pkg/gen/primeapi/primeoperations/move_task_order/download_move_order_responses.go
  pkg/gen/primeapi/primeoperations/move_task_order/download_move_order_urlbuilder.go
  pkg/gen/primeapi/primeoperations/mymove_api.go
  pkg/gen/primeclient/move_task_order/download_move_order_parameters.go
  pkg/gen/primeclient/move_task_order/download_move_order_responses.go
  pkg/gen/primeclient/move_task_order/move_task_order_client.go
  pkg/handlers/primeapi/api.go
  pkg/handlers/primeapi/move_task_order.go
  pkg/handlers/primeapi/move_task_order_test.go
  swagger-def/.spectral.yml
  swagger-def/prime.yaml
  swagger/prime.yaml
Labels: Scrummy Bears

#11650 B 18331 add ppm closeout office to move details
  pkg/handlers/authentication/permissions.go
  src/components/Office/RequestedShipments/ApprovedRequestedShipments.jsx
  src/components/Office/RequestedShipments/RequestedShipments.test.jsx
  src/components/Office/RequestedShipments/RequestedShipmentsTestData.js
  src/components/Office/RequestedShipments/SubmittedRequestedShipments.jsx
  src/pages/Office/MoveDetails/MoveDetails.jsx
Labels: G-Unit

#11651 B-18179 removed unused get move dates endpoint
  pkg/gen/internalapi/configure_mymove.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalapi/internaloperations/moves/show_move_dates_summary.go
  pkg/gen/internalapi/internaloperations/moves/show_move_dates_summary_parameters.go
  pkg/gen/internalapi/internaloperations/moves/show_move_dates_summary_responses.go
  pkg/gen/internalapi/internaloperations/moves/show_move_dates_summary_urlbuilder.go
  pkg/gen/internalapi/internaloperations/mymove_api.go
  pkg/handlers/internalapi/api.go
  pkg/handlers/internalapi/move_dates.go
  pkg/handlers/internalapi/moves.go
  pkg/handlers/internalapi/moves_test.go
  pkg/handlers/internalapi/personally_procured_move_incentive.go
  src/shared/Entities/modules/moves.js
  swagger-def/internal.yaml
  swagger/internal.yaml
Labels: G-Unit

#11660 B-17956 Fix "Total days used" to not exceed "total days of SIT approved".
  pkg/services/mto_shipment/shipment_sit_status.go
  pkg/services/mto_shipment/shipment_sit_status_test.go
  playwright/tests/office/txo/sitUpdates.spec.js
  src/components/Office/ShipmentSITDisplay/ShipmentSITDisplay.jsx
Labels: ByteSize M&Ms

#11652 B 17950 convert to customer expense
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20231211202108_add_member_expense_flags.up.sql
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/deny_s_i_t_extension.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/mto_shipment.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/models/mto_service_items.go
  pkg/models/sit_duration_update.go
  pkg/models/sit_duration_update_test.go
  pkg/payment_request/service_param_value_lookups/number_days_sit_lookup.go
  pkg/services/mocks/MTOServiceItemUpdater.go
  pkg/services/mocks/SITExtensionDenier.go
  pkg/services/mto_service_item.go
  pkg/services/mto_service_item/mto_service_item_updater.go
  pkg/services/mto_service_item/mto_service_item_updater_test.go
  pkg/services/mto_shipment.go
  pkg/services/payment_request/payment_request_shipments_sit_balance.go
  pkg/services/sit_extension.go
  pkg/services/sit_extension/sit_extension_denier.go
  pkg/services/sit_extension/sit_extension_denier_test.go
  pkg/services/sit_status/shipment_sit_status.go
  pkg/services/sit_status/shipment_sit_status_test.go
  pkg/services/sit_status/sit_status_service_test.go
  playwright/tests/office/txo/sitUpdates.spec.js
  src/components/Office/ReviewSITExtensionModal/ReviewSITExtensionModal.jsx
  src/components/Office/ReviewSITExtensionModal/ReviewSITExtensionModal.module.scss
  src/components/Office/ReviewSITExtensionModal/ReviewSITExtensionModal.test.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: ByteSize M&Ms

#11654 B-18165 Add advance details to Move history
  src/constants/MoveHistory/Database/BooleanFields.js
  src/constants/MoveHistory/Database/FieldMappings.js
  src/constants/MoveHistory/Database/MonetaryFields.js
  src/constants/MoveHistory/EventTemplates/UpdateMTOShipment/UpdateMTOShipmentPPMDetails.test.jsx
  src/pages/Office/MoveHistory/LabeledDetails.jsx
Labels: G-Unit

#11655 B 18028 create sit delivery prime api end point
  pkg/gen/primeapi/configure_mymove.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/mto_shipment/update_s_i_t_delivery_request.go
  pkg/gen/primeapi/primeoperations/mto_shipment/update_s_i_t_delivery_request_parameters.go
  pkg/gen/primeapi/primeoperations/mto_shipment/update_s_i_t_delivery_request_responses.go
  pkg/gen/primeapi/primeoperations/mto_shipment/update_s_i_t_delivery_request_urlbuilder.go
  pkg/gen/primeapi/primeoperations/mymove_api.go
  pkg/gen/primeclient/mto_shipment/mto_shipment_client.go
  pkg/gen/primeclient/mto_shipment/update_s_i_t_delivery_request_parameters.go
  pkg/gen/primeclient/mto_shipment/update_s_i_t_delivery_request_responses.go
  pkg/gen/primemessages/s_i_t_delivery_update.go
  pkg/gen/primemessages/s_i_t_status.go
  pkg/handlers/primeapi/api.go
  pkg/handlers/primeapi/mto_shipment.go
  pkg/handlers/primeapi/mto_shipment_test.go
  pkg/handlers/primeapi/payloads/model_to_payload.go
  pkg/services/mocks/ShipmentSITStatus.go
  pkg/services/mto_shipment.go
  pkg/services/sit_status/shipment_sit_status.go
  pkg/services/sit_status/shipment_sit_status_test.go
  swagger-def/definitions/prime/SITDeliveryUpdate.yaml
  swagger-def/definitions/prime/SITStatus.yaml
  swagger-def/prime.yaml
  swagger/prime.yaml
Labels: Scrummy Bears

#11670 B-17950 - AMW - added confirmation modal for customer expense
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/deny_s_i_t_extension.go
  pkg/handlers/ghcapi/mto_shipment.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/models/mto_service_items.go
  pkg/models/sit_duration_update.go
  pkg/models/sit_duration_update_test.go
  pkg/services/mocks/MTOServiceItemUpdater.go
  pkg/services/mocks/SITExtensionDenier.go
  pkg/services/mto_service_item.go
  pkg/services/mto_service_item/mto_service_item_updater.go
  pkg/services/mto_service_item/mto_service_item_updater_test.go
  pkg/services/sit_extension.go
  pkg/services/sit_extension/sit_extension_denier.go
  pkg/services/sit_extension/sit_extension_denier_test.go
  playwright/tests/office/txo/sitUpdates.spec.js
  src/components/Office/ReviewSITExtensionModal/ConfirmCustomerExpenseModal/ConfirmCustomerExpenseModal.jsx
  src/components/Office/ReviewSITExtensionModal/ReviewSITExtensionModal.jsx
  src/components/Office/ReviewSITExtensionModal/ReviewSITExtensionModal.module.scss
  src/components/Office/ReviewSITExtensionModal/ReviewSITExtensionModal.test.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: ByteSize M&Ms

#11648 B 18003 okta looping error fix
  pkg/handlers/authentication/auth.go
  pkg/handlers/authentication/auth_test.go
  pkg/handlers/authentication/okta_auth_code_flow.go
  pkg/handlers/authentication/okta_auth_code_flow_test.go
  src/components/OktaLogoutBanner/OktaLogoutBanner.module.scss
  src/components/OktaLogoutBanner/OktaLogoutBanner.stories.jsx
  src/components/OktaLogoutBanner/OktaLogoutBanner.test.jsx
  src/components/OktaLogoutBanner/index.jsx
  src/pages/Office/index.jsx
  src/pages/Office/index.test.jsx
  src/pages/PrimeUI/UpdateServiceItems/PrimeUIUpdateServiceItems.jsx
  src/scenes/SystemAdmin/index.jsx
Labels: Mountain Movers

#11668 B 18259
  .eslintrc.js
  pkg/factory/mto_service_item_factory.go
  pkg/factory/mto_service_item_factory_test.go
  pkg/testdatagen/testharness/dispatch.go
  pkg/testdatagen/testharness/make_move.go
  playwright/tests/office/primesimulator/primeSimulatorFlows.spec.js
  playwright/tests/utils/testharness.js
  src/components/PrimeUI/CreatePaymentRequestForm/CreatePaymentRequestForm.jsx
Labels: Mountain Movers

#11669 B-17964 Removed "move reviewed" files.
  .circleci/config.yml
  Makefile
  cmd/ecs-deploy/put_target.go
  cmd/ecs-deploy/task_def.go
  cmd/milmove-tasks/main.go
  cmd/milmove-tasks/send_post_move_survey_email.go
  migrations/app/schema/20200827155542_add_db_comments.up.sql
  pkg/assets/notifications/templates/move_reviewed_template.html
  pkg/assets/notifications/templates/move_reviewed_template.txt
  pkg/factory/notification_factory_test.go
  pkg/gen/adminapi/embedded_spec.go
  pkg/gen/adminmessages/notification.go
  pkg/models/notifications.go
  pkg/notifications/move_reviewed.go
  pkg/notifications/move_reviewed_test.go
  scripts/deploy-app-tasks
  swagger-def/admin.yaml
  swagger/admin.yaml
Labels: ByteSize M&Ms

#11665 B-18155-Update-SIT-service-item-addresss-on-shipment-address-update
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/mto_shipment/update_m_t_o_shipment_address.go
  pkg/gen/primeclient/mto_shipment/mto_shipment_client.go
  pkg/services/mto_shipment/mto_shipment_address_updater.go
  pkg/services/mto_shipment/mto_shipment_address_updater_test.go
  swagger-def/prime.yaml
  swagger/prime.yaml
Labels: Mountain Movers

#11672 B 17951 add convert to customer expense if sit is set to expire within 30 days
  playwright/tests/office/txo/sitUpdates.spec.js
  src/components/Office/ConvertSITToCustomerExpenseModal/ConvertSITToCustomerExpenseModal.jsx
  src/components/Office/ConvertSITToCustomerExpenseModal/ConvertSITToCustomerExpenseModal.module.scss
  src/components/Office/ConvertSITToCustomerExpenseModal/ConvertSITToCustomerExpenseModal.stories.jsx
  src/components/Office/ConvertSITToCustomerExpenseModal/ConvertSITToCustomerExpenseModal.test.jsx
  src/components/Office/ShipmentDetails/ShipmentDetailsMain.jsx
  src/components/Office/ShipmentSITDisplay/ShipmentSITDisplay.jsx
  src/components/Office/ShipmentSITDisplay/ShipmentSITDisplay.test.jsx
  src/components/Office/ShipmentSITDisplay/ShipmentSITDisplayTestParams.js
Labels: ByteSize M&Ms

#11679 B-18110 Update Rank and Address Labels
  playwright/tests/my/mymove/onboarding.spec.js
  playwright/tests/utils/my/waitForCustomerPage.js
  src/components/Customer/DodInfoForm/DodInfoForm.jsx
  src/components/Customer/DodInfoForm/DodInfoForm.test.jsx
  src/components/Customer/EditContactInfoForm/EditContactInfoForm.jsx
  src/components/Customer/Profile/ContactInfoDisplay/ContactInfoDisplay.jsx
  src/components/Customer/Profile/ContactInfoDisplay/ContactInfoDisplay.test.jsx
  src/components/Customer/ResidentialAddressForm/ResidentialAddressForm.jsx
  src/components/Customer/Review/ProfileTable/ProfileTable.jsx
  src/components/Customer/Review/ServiceInfoDisplay/ServiceInfoDisplay.jsx
  src/components/Customer/Review/ServiceInfoDisplay/ServiceInfoDisplay.test.jsx
  src/components/Office/AllowancesDetailForm/AllowancesDetailForm.jsx
  src/components/Office/DefinitionLists/AllowancesList.jsx
  src/components/form/AddressFields/AddressFields.stories.jsx
  src/constants/MoveHistory/Database/FieldMappings.js
  src/constants/MoveHistory/EventTemplates/UpdateAddress/createAddress.test.jsx
  src/constants/MoveHistory/EventTemplates/UpdateAddress/updateAddress.test.jsx
  src/pages/MyMove/Profile/EditContactInfo.test.jsx
  src/pages/MyMove/Profile/ResidentialAddress.test.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.test.jsx
Labels: Mountain Movers

#11685 B-17993 Recalculate sit dates after edit updates
  pkg/handlers/primeapi/mto_shipment.go
  pkg/services/mocks/ShipmentSITStatus.go
  pkg/services/mto_shipment.go
  pkg/services/payment_request/payment_request_shipments_sit_balance.go
  pkg/services/payment_request/payment_request_shipments_sit_balance_test.go
  pkg/services/sit_status/shipment_sit_status.go
  pkg/services/sit_status/shipment_sit_status_test.go
  src/components/Office/SubmitSITExtensionModal/SubmitSITExtensionModal.jsx
Labels: ByteSize M&Ms

#11675 B-17918: remove old PPM INTERNAL APIs - SET A
  pkg/gen/internalapi/configure_mymove.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalapi/internaloperations/mymove_api.go
  pkg/gen/internalapi/internaloperations/ppm/create_personally_procured_move.go
  pkg/gen/internalapi/internaloperations/ppm/create_personally_procured_move_parameters.go
  pkg/gen/internalapi/internaloperations/ppm/create_personally_procured_move_responses.go
  pkg/gen/internalapi/internaloperations/ppm/create_personally_procured_move_urlbuilder.go
  pkg/gen/internalapi/internaloperations/ppm/index_personally_procured_moves.go
  pkg/gen/internalapi/internaloperations/ppm/index_personally_procured_moves_parameters.go
  pkg/gen/internalapi/internaloperations/ppm/index_personally_procured_moves_responses.go
  pkg/gen/internalapi/internaloperations/ppm/index_personally_procured_moves_urlbuilder.go
  pkg/gen/internalapi/internaloperations/ppm/show_personally_procured_move.go
  pkg/gen/internalapi/internaloperations/ppm/show_personally_procured_move_parameters.go
  pkg/gen/internalapi/internaloperations/ppm/show_personally_procured_move_responses.go
  pkg/gen/internalapi/internaloperations/ppm/show_personally_procured_move_urlbuilder.go
  pkg/gen/internalapi/internaloperations/ppm/update_personally_procured_move.go
  pkg/gen/internalapi/internaloperations/ppm/update_personally_procured_move_parameters.go
  pkg/gen/internalapi/internaloperations/ppm/update_personally_procured_move_responses.go
  pkg/gen/internalapi/internaloperations/ppm/update_personally_procured_move_urlbuilder.go
  pkg/handlers/authentication/auth.go
  pkg/handlers/internalapi/api.go
  pkg/handlers/internalapi/personally_procured_move.go
  pkg/services/event/internal_endpoint.go
  src/scenes/Moves/Ppm/DateAndLocation.jsx
  src/scenes/Moves/Ppm/PPMPaymentRequestIntro.jsx
  src/scenes/Moves/Ppm/PPMPaymentRequestIntro.module.scss
  src/scenes/Moves/Ppm/PaymentReview/index.jsx
  src/scenes/Moves/Ppm/Weight.jsx
  src/scenes/Moves/Ppm/Weight.module.scss
  src/scenes/Moves/Ppm/Weight.test.js
  src/scenes/Moves/Ppm/api.js
  src/scenes/MyMove/getWorkflowRoutes.jsx
  src/scenes/MyMove/getWorkflowRoutes.test.js
  src/scenes/MyMove/index.jsx
  src/scenes/PpmLanding/index.jsx
  src/scenes/PpmLanding/index.test.js
  src/scenes/Review/EditDateAndLocation.jsx
  src/scenes/Review/EditWeight.css
  src/scenes/Review/EditWeight.jsx
  src/services/internalApi.js
  src/shared/Entities/modules/ppms.js
  swagger-def/internal.yaml
  swagger/internal.yaml
Labels: Scrummy Bears

#11678 B-17918: remove old PPM INTERNAL APIs - SET B
  pkg/gen/internalapi/configure_mymove.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalapi/internaloperations/mymove_api.go
  pkg/gen/internalapi/internaloperations/ppm/create_p_p_m_attachments.go
  pkg/gen/internalapi/internaloperations/ppm/create_p_p_m_attachments_parameters.go
  pkg/gen/internalapi/internaloperations/ppm/create_p_p_m_attachments_responses.go
  pkg/gen/internalapi/internaloperations/ppm/create_p_p_m_attachments_urlbuilder.go
  pkg/gen/internalapi/internaloperations/ppm/request_p_p_m_expense_summary.go
  pkg/gen/internalapi/internaloperations/ppm/request_p_p_m_expense_summary_parameters.go
  pkg/gen/internalapi/internaloperations/ppm/request_p_p_m_expense_summary_responses.go
  pkg/gen/internalapi/internaloperations/ppm/request_p_p_m_expense_summary_urlbuilder.go
  pkg/gen/internalmessages/expense_summary_payload.go
  pkg/handlers/authentication/auth.go
  pkg/handlers/internalapi/personally_procured_move.go
  pkg/services/event/internal_endpoint.go
  src/scenes/Office/MoveInfo.jsx
  src/scenes/Office/MoveInfo.test.js
  src/scenes/Office/Ppm/ExpensesPanel.jsx
  src/scenes/Office/Ppm/PaymentsPanel.css
  src/scenes/Office/Ppm/PaymentsPanel.jsx
  src/scenes/Office/Ppm/PaymentsPanel.test.js
  src/scenes/Office/Ppm/api.js
  src/scenes/Office/Ppm/ducks.js
  src/shared/Entities/modules/ppms.js
  swagger-def/internal.yaml
  swagger/internal.yaml
Labels: Scrummy Bears

#11686 B-18173 Move history tracking for PPM weight docs
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20231226174935_create_ppm_documents_triggers.up.sql
  pkg/assets/sql_scripts/move_history_fetcher.sql
  src/constants/MoveHistory/Database/BooleanFields.js
  src/constants/MoveHistory/Database/FieldMappings.js
  src/constants/MoveHistory/Database/Tables.js
  src/constants/MoveHistory/Database/WeightFields.js
  src/constants/MoveHistory/EventTemplates/UpdateWeightTicket/UpdateWeightTicket.jsx
  src/constants/MoveHistory/EventTemplates/UpdateWeightTicket/UpdateWeightTicket.test.jsx
  src/constants/MoveHistory/EventTemplates/index.js
  src/constants/MoveHistory/UIDisplay/Operations.js
Labels: G-Unit

#11676 B-18156: Service items address updates when shipment update
  pkg/services/mto_shipment/mto_shipment_updater.go
Labels: Mountain Movers

#11677 B 17854 prime api recalculate authorized end date
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/mto_shipment/update_s_i_t_delivery_request_responses.go
  pkg/gen/primeclient/mto_shipment/update_s_i_t_delivery_request_responses.go
  pkg/handlers/primeapi/mto_shipment.go
  pkg/handlers/primeapi/mto_shipment_test.go
  pkg/services/mocks/ShipmentSITStatus.go
  pkg/services/mto_shipment.go
  pkg/services/sit_status/shipment_sit_status.go
  pkg/services/sit_status/shipment_sit_status_test.go
  swagger-def/prime.yaml
  swagger/prime.yaml
Labels: Scrummy Bears

#11681 added the visible field for SIT Departure Date on the SIT dashboard a…
  pkg/services/sit_status/shipment_sit_status.go
  pkg/services/sit_status/shipment_sit_status_test.go
  playwright/tests/office/txo/sitUpdates.spec.js
  src/components/Office/ConvertSITToCustomerExpenseModal/ConvertSITToCustomerExpenseModal.jsx
  src/components/Office/DefinitionLists/PPMShipmentInfoList.test.jsx
  src/components/Office/DefinitionLists/ShipmentInfoList.jsx
  src/components/Office/ReviewSITExtensionModal/ReviewSITExtensionModal.jsx
  src/components/Office/ShipmentSITDisplay/ShipmentSITDisplay.jsx
  src/components/Office/ShipmentSITDisplay/ShipmentSITDisplay.test.jsx
  src/components/Office/SubmitSITExtensionModal/SubmitSITExtensionModal.jsx
  src/components/PrimeUI/Shipment/Shipment.jsx
Labels: ByteSize M&Ms

#11689 B-18108 prime sim add shipment id when diversion box is checked
  src/pages/PrimeUI/Shipment/PrimeUIShipmentCreate.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentCreateForm.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentCreateForm.test.jsx
Labels: Mountain Movers

#11680 B-18268
  src/components/Office/ShipmentForm/ShipmentForm.jsx
  src/components/Office/ShipmentForm/ShipmentForm.test.jsx
  src/constants/routes.js
  src/pages/Office/PPM/ReviewDocuments/ReviewDocuments.jsx
  src/pages/Office/PPM/ReviewDocuments/ReviewDocuments.test.jsx
  src/pages/Office/index.jsx
  src/pages/Office/index.test.jsx
Labels: Mountain Movers

#11692 B-11810 Fixed remaining rank label
  src/components/Customer/ServiceInfoForm/ServiceInfoForm.jsx
  src/components/Customer/ServiceInfoForm/ServiceInfoForm.test.jsx
  src/pages/MyMove/Profile/EditServiceInfo.test.jsx
Labels: Mountain Movers

#11697 B17951 - rename "Office remarks" label and underlying code.
  src/components/Office/ConvertSITToCustomerExpenseModal/ConvertSITToCustomerExpenseModal.jsx
  src/components/Office/ConvertSITToCustomerExpenseModal/ConvertSITToCustomerExpenseModal.test.jsx
Labels: ByteSize M&Ms
