Repository transcom/mymove, pull requests merged in 2023-03, with the labels that each got.

#10160 MB-14506: update files to use Zaptest New Logger update to new zaptest logger
  pkg/auth/auth_test.go
  pkg/handlers/spa_handler_test.go
Labels: ready-to-merge, spark

#10105 [MB-14989] Improve error handling for editing/adding ppm shipments as an office user
  src/components/Office/ShipmentForm/ShipmentForm.jsx
  src/components/Office/ShipmentForm/ShipmentForm.test.jsx
  src/pages/Office/ServicesCounselingEditShipmentDetails/ServicesCounselingEditShipmentDetails.test.jsx
Labels: ttv, ready-to-merge

#10169 [MB-15297] Upgrade to go 1.20.1
  .circleci/config.yml
  .github/workflows/go-auto-approve.yml
  .go-version
  .pre-commit-config.yaml
  .tool-versions
  Dockerfile.local
  Dockerfile.migrations_local
  Dockerfile.reviewapp
  Dockerfile.tasks_local
  Dockerfile.tools_local
  Dockerfile.webhook_client
  Dockerfile.webhook_client_dp3
  Dockerfile.webhook_client_local
  Makefile
  go.mod
  nix/default.nix
Labels: dependencies, ttv, ready-to-merge

#10151 update text in handlers
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/ppm_document_test.go
  pkg/handlers/internalapi/internal/payloads/model_to_payload.go
  pkg/handlers/internalapi/progear_weight_ticket.go
  pkg/models/ppm_shipment.go
  pkg/services/mto_shipment/mto_shipment_fetcher.go
  pkg/services/mto_shipment/mto_shipment_fetcher_test.go
  pkg/services/ppmshipment/ppm_document_fetcher.go
  pkg/services/ppmshipment/ppm_document_fetcher_test.go
  pkg/services/ppmshipment/ppm_shipment_fetcher.go
  pkg/services/ppmshipment/ppm_shipment_fetcher_test.go
  pkg/services/ppmshipment/ppm_shipment_router.go
  pkg/services/ppmshipment/ppm_shipment_router_test.go
Labels: A-Team

#10187 [ MB-15049 ] Modifying the query to include weight tickets on the ppmShipment object
  src/hooks/queries.js
  src/hooks/queries.test.jsx
Labels: Pamplemoose, ready-to-merge

#10185 [MB-15297] Update to go 1.20.1 again but with old base image
  .circleci/config.yml
  .github/workflows/go-auto-approve.yml
  .go-version
  .pre-commit-config.yaml
  .tool-versions
  Dockerfile.local
  Dockerfile.migrations_local
  Dockerfile.reviewapp
  Dockerfile.tasks_local
  Dockerfile.tools_local
  Dockerfile.webhook_client
  Dockerfile.webhook_client_dp3
  Dockerfile.webhook_client_local
  Makefile
  go.mod
  nix/default.nix
Labels: dependencies, ttv, ready-to-merge

#10173 MB-15277: add requested move date for NTS-release shipments
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/queues_test.go
  pkg/services/order/order_fetcher.go
Labels: ready-to-merge, Huckleberry

#10149 MB-15167 - Add weight displays to review shipment weights
  src/components/Customer/PPM/Closeout/FinalCloseoutForm/FinalCloseoutForm.jsx
  src/hooks/custom.js
  src/pages/MyMove/PPM/Closeout/Review/Review.jsx
  src/pages/Office/MoveDetails/MoveDetails.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
  src/pages/Office/ServicesCounselingMoveInfo/ServicesCounselingMoveInfo.test.jsx
  src/pages/Office/ServicesCounselingReviewShipmentWeights/ServicesCounselingReviewShipmentWeights.jsx
  src/pages/Office/ServicesCounselingReviewShipmentWeights/ServicesCounselingReviewShipmentWeights.module.scss
  src/pages/Office/ServicesCounselingReviewShipmentWeights/ServicesCounselingReviewShipmentWeights.test.jsx
  src/utils/ppmCloseout.jsx
  src/utils/ppmCloseout.test.jsx
  src/utils/shipmentWeights.js
  src/utils/shipmentWeights.test.js
Labels: Pamplemoose

#10195 [MB-15313] Update all opentelemetry dependencies and address API changes
  go.mod
  go.sum
  pkg/telemetry/db.go
Labels: dependencies, ttv, ready-to-merge

#10194 MB-15067 fix flaky SendToGex test
  pkg/payment_request/send_to_syncada_test.go
Labels: ready-to-merge, spark

#10189 [MB-15057] Include actual delivery date in payload
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/m_t_o_shipment.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  swagger-def/definitions/MTOShipment.yaml
  swagger/ghc.yaml
Labels: Pamplemoose

#10181 [MB-15055] Check excess weight should include ppm weight
  pkg/services/move/move_weights.go
  pkg/services/move/move_weights_test.go
Labels: Pamplemoose

#10207 MB-15345 add factory.BuildOrganization
  pkg/factory/organization_factory.go
  pkg/factory/organization_factory_test.go
  pkg/factory/shared.go
  pkg/handlers/adminapi/organizations_test.go
  pkg/services/admin_user/admin_user_creator_test.go
Labels: ready-to-merge, spark

#10122 [MB-15153] Create create edit net weight component
  src/components/Office/PPM/EditNetWeights/EditPPMNetWeight.jsx
  src/components/Office/PPM/EditNetWeights/EditPPMNetWeight.module.scss
  src/components/Office/PPM/EditNetWeights/EditPPMNetWeight.test.jsx
  src/components/Office/PPM/EditNetWeights/EditPPMNetWeights.stories.jsx
Labels: Pamplemoose, ready-to-merge

#10217 MB-15175 - Modify weight calculations
  src/components/Customer/PPM/Closeout/FinalCloseoutForm/FinalCloseoutForm.jsx
  src/components/Office/PPM/EditNetWeights/EditPPMNetWeight.jsx
  src/hooks/custom.js
  src/pages/MyMove/PPM/Closeout/Review/Review.jsx
  src/pages/Office/ServicesCounselingReviewShipmentWeights/ServicesCounselingReviewShipmentWeights.jsx
  src/utils/shipmentWeights.js
  src/utils/shipmentWeights.test.js
Labels: Pamplemoose

#10208 [ MB-15049 ] Create weights moved table component
  src/components/Office/PPM/ReviewShipmentWeightsTable/ReviewShipmentWeightsTable.jsx
  src/components/Office/PPM/ReviewShipmentWeightsTable/ReviewShipmentWeightsTable.module.scss
  src/components/Office/PPM/ReviewShipmentWeightsTable/ReviewShipmentWeightsTable.stories.jsx
  src/components/Office/PPM/ReviewShipmentWeightsTable/ReviewShipmentWeightsTable.test.jsx
  src/components/Office/PPM/ReviewShipmentWeightsTable/helpers.jsx
  src/components/Office/PPM/ReviewShipmentWeightsTable/helpers.test.jsx
  src/components/Table/utils.js
  src/hooks/queries.js
  src/hooks/queries.test.jsx
  src/shared/styles/colors.scss
  src/utils/formatters.js
Labels: Pamplemoose

#10235 [ MB-15049 ] Fixed incorrect import of weight ticket weight function
  src/components/Office/PPM/ReviewShipmentWeightsTable/helpers.jsx
Labels: Pamplemoose, ready-to-merge

#10226 MB-15284: Fix issue where office app was setting dates to the zero value
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/m_t_o_shipment.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/mto_shipment.go
  swagger-def/definitions/MTOShipment.yaml
  swagger/ghc.yaml
Labels: ready-to-merge, Huckleberry

#10206 [MB-15375] migration for removing net weight column from ppm shipments table
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20230306200756_remove_net_weight_column_from_ppm_shipments_table.up.sql
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/p_p_m_shipment.go
  pkg/gen/ghcmessages/update_p_p_m_shipment.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/p_p_m_shipment.go
  pkg/gen/internalmessages/update_p_p_m_shipment.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/p_p_m_shipment.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/internal/payloads/payload_to_model.go
  pkg/handlers/internalapi/internal/payloads/model_to_payload.go
  pkg/handlers/internalapi/internal/payloads/payload_to_model.go
  pkg/handlers/internalapi/mto_shipment_test.go
  pkg/handlers/internalapi/personally_procured_move.go
  pkg/handlers/primeapi/payloads/model_to_payload.go
  pkg/models/ppm_shipment.go
  pkg/services/ppmshipment/validation.go
  pkg/services/weight_ticket/weight_ticket_updater.go
  src/components/Office/DefinitionLists/PPMShipmentInfoList.stories.jsx
  src/components/Office/DefinitionLists/ShipmentInfoListSelector.test.jsx
  src/components/Office/EvaluationReportPreview/EvaluationReportPreview.test.jsx
  src/components/Office/ShipmentDisplay/ShipmentDisplayTestData.js
  src/components/PrimeUI/Shipment/Shipment.jsx
  src/components/PrimeUI/Shipment/Shipment.test.jsx
  src/pages/Office/ServicesCounselingEditShipmentDetails/ServicesCounselingEditShipmentDetails.test.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.test.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdate.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdate.test.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdatePPMForm.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdatePPMForm.test.jsx
  src/store/entities/selectors.test.js
  src/types/shipment.js
  swagger-def/definitions/PPMShipment.yaml
  swagger-def/ghc.yaml
  swagger-def/internal.yaml
  swagger-def/prime.yaml
  swagger/ghc.yaml
  swagger/internal.yaml
  swagger/prime.yaml
Labels: Pamplemoose

#10244 Revert "Bump webpack from 5.75.0 to 5.76.0"
  yarn.lock
Labels: dependencies, ttv

#10204 MB-8032 Add min value validation to prime estimated and actual weights in shipment create/update
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/create_m_t_o_shipment.go
  pkg/gen/primemessages/m_t_o_shipment.go
  pkg/gen/primemessages/update_m_t_o_shipment.go
  pkg/handlers/primeapi/mto_shipment_test.go
  pkg/handlers/primeapi/payloads/model_to_payload.go
  pkg/handlers/primeapi/payloads/payload_to_model.go
  pkg/models/mto_shipments.go
  pkg/models/mto_shipments_test.go
  swagger-def/prime.yaml
  swagger/prime.yaml
Labels: ttv, ready-to-merge

#10209 [MB-15310] Only allow prime to make payment requests for approved service items
  pkg/handlers/primeapi/payment_request_test.go
  pkg/services/payment_request/payment_request_creator.go
  pkg/services/payment_request/payment_request_creator_test.go
  pkg/testdatagen/make_mto_service_item.go
Labels: ttv, ready-to-merge

#10245 MB-14964 - Fix review shipment weights queries
  src/hooks/queries.js
  src/pages/Office/ServicesCounselingReviewShipmentWeights/ServicesCounselingReviewShipmentWeights.jsx
  src/pages/Office/ServicesCounselingReviewShipmentWeights/ServicesCounselingReviewShipmentWeights.test.jsx
Labels: Pamplemoose

#10182 MB-14619 factory.BuildServiceMember added as new version of testdatagen.MakeServiceMember
  pkg/db/utilities/utilities_test.go
  pkg/factory/service_member_factory.go
  pkg/factory/service_member_factory_test.go
  pkg/factory/shared.go
  pkg/handlers/adminapi/upload_information_test.go
  pkg/handlers/ghcapi/customer_test.go
  pkg/handlers/ghcapi/queues_test.go
  pkg/handlers/ghcapi/tac_test.go
  pkg/handlers/internalapi/backup_contacts_test.go
  pkg/handlers/internalapi/documents_test.go
  pkg/handlers/internalapi/move_queue_items_test.go
  pkg/handlers/internalapi/moves_test.go
  pkg/handlers/internalapi/moving_expense_test.go
  pkg/handlers/internalapi/mto_shipment_test.go
  pkg/handlers/internalapi/office_test.go
  pkg/handlers/internalapi/personally_procured_move_incentive_test.go
  pkg/handlers/internalapi/personally_procured_move_test.go
  pkg/handlers/internalapi/progear_weight_ticket_test.go
  pkg/handlers/internalapi/service_members_test.go
  pkg/handlers/internalapi/uploads_test.go
  pkg/handlers/internalapi/weight_ticket_test.go
  pkg/handlers/supportapi/move_task_order_test.go
  pkg/models/backup_contact_test.go
  pkg/models/document_test.go
  pkg/models/order_test.go
  pkg/models/service_member_test.go
  pkg/models/user_test.go
  pkg/notifications/move_payment_reminder_test.go
  pkg/notifications/move_reviewed_test.go
  pkg/services/move_task_order/move_task_order_hide_non_fake_test.go
  pkg/services/moving_expense/moving_expense_creator_test.go
  pkg/services/moving_expense/moving_expense_deleter_test.go
  pkg/services/moving_expense/moving_expense_updater_test.go
  pkg/services/office_user/customer/customer_test.go
  pkg/services/progear_weight_ticket/progear_weight_ticket_creator_test.go
  pkg/services/progear_weight_ticket/progear_weight_ticket_deleter_test.go
  pkg/services/progear_weight_ticket/progear_weight_ticket_updater_test.go
  pkg/services/weight_ticket/weight_ticket_creator_test.go
  pkg/services/weight_ticket/weight_ticket_deleter_test.go
  pkg/services/weight_ticket/weight_ticket_updater_test.go
  pkg/testdatagen/scenario/e2ebasic.go
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/testharness/make_office_user.go
Labels: ready-to-merge, spark

#10227 [MB-14339 & MB-14336] PPM processor can approve/reject/edit fields in pro-gear weight tickets
  src/components/Office/PPM/ReviewProGear/ReviewProGear.jsx
  src/components/Office/PPM/ReviewProGear/ReviewProGear.module.scss
  src/components/Office/PPM/ReviewProGear/ReviewProGear.stories.jsx
  src/components/Office/PPM/ReviewProGear/ReviewProGear.test.jsx
  src/pages/Office/PPM/ReviewDocuments/ReviewDocuments.jsx
  src/pages/Office/PPM/ReviewDocuments/ReviewDocuments.test.jsx
  src/services/ghcApi.js
Labels: A-Team, ready-to-merge

#10205 MB-14292 MB-14337 Service counselor can review expenses
  src/pages/Office/PPM/ReviewDocuments/ReviewDocuments.test.jsx
Labels: A-Team

#10253 MB-15343 add and implement factory.BuildBackupContact
  pkg/factory/backup_contact_factory.go
  pkg/factory/backup_contact_factory_test.go
  pkg/factory/shared.go
  pkg/handlers/internalapi/backup_contacts_test.go
  pkg/models/service_member_test.go
  pkg/services/move_history/move_history_fetcher_test.go
  pkg/services/move_task_order/move_task_order_hide_non_fake_test.go
Labels: ready-to-merge, spark

#10267 Remove ra-data-simple-rest and instance
  package.json
  src/scenes/SystemAdmin/Home.test.jsx
  yarn.lock
Labels: dependencies, ttv

#10258 [MB-15173] Incorporate weights moved/weights moved by customer shipment list components to display shipment level weights
  src/components/Office/PPM/ReviewShipmentWeightsTable/ReviewShipmentWeightsTable.jsx
  src/components/Office/PPM/ReviewShipmentWeightsTable/ReviewShipmentWeightsTable.module.scss
  src/components/Table/Table.jsx
  src/pages/Office/MoveTaskOrder/moveTaskOrderUnitTestData.js
  src/pages/Office/ServicesCounselingReviewShipmentWeights/ServicesCounselingReviewShipmentWeights.jsx
  src/pages/Office/ServicesCounselingReviewShipmentWeights/ServicesCounselingReviewShipmentWeights.module.scss
  src/pages/Office/ServicesCounselingReviewShipmentWeights/ServicesCounselingReviewShipmentWeights.test.jsx
  src/utils/shipmentWeights.test.js
Labels: Pamplemoose, ready-to-merge

#10260 [MB-15132] adding review shipment weights button to move details page
  src/components/Office/DetailsPanel/DetailsPanel.jsx
  src/components/Office/DetailsPanel/DetailsPanel.stories.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.test.jsx
Labels: Pamplemoose

#10270 MB-14757 add and implement factory.BuildDocument
  pkg/db/utilities/utilities_test.go
  pkg/factory/document_factory.go
  pkg/factory/document_factory_test.go
  pkg/factory/shared.go
  pkg/handlers/adminapi/upload_information_test.go
  pkg/handlers/ghcapi/orders_test.go
  pkg/handlers/internalapi/moves_test.go
  pkg/handlers/internalapi/uploads_test.go
  pkg/handlers/supportapi/move_task_order_test.go
  pkg/models/moving_expense_test.go
  pkg/models/user_upload_test.go
  pkg/paperwork/generator_test.go
  pkg/services/move/move_router_test.go
  pkg/services/moving_expense/moving_expense_deleter_test.go
  pkg/services/moving_expense/moving_expense_updater_test.go
  pkg/services/mto_service_item/mto_service_item_updater_test.go
  pkg/services/order/excess_weight_risk_manager_test.go
  pkg/services/order/order_updater_test.go
  pkg/services/progear_weight_ticket/progear_weight_ticket_deleter_test.go
  pkg/services/progear_weight_ticket/progear_weight_ticket_updater_test.go
  pkg/services/weight_ticket/weight_ticket_deleter_test.go
  pkg/services/weight_ticket/weight_ticket_updater_test.go
  pkg/testdatagen/scenario/bandwidth.go
  pkg/testdatagen/scenario/shared.go
  pkg/uploader/user_uploader_test.go
Labels: ready-to-merge, spark

#10271 [MB-15134] Added conditional rendering for review documents link
  src/components/Office/PPM/ReviewShipmentWeightsTable/ReviewShipmentWeightsTable.test.jsx
  src/components/Office/PPM/ReviewShipmentWeightsTable/helpers.jsx
Labels: Pamplemoose

#10288 MB-14758: BuildUserUpload instead of MakeUserUpload
  pkg/factory/shared.go
  pkg/factory/user_upload_factory.go
  pkg/factory/user_upload_factory_test.go
  pkg/handlers/adminapi/upload_information_test.go
  pkg/handlers/ghcapi/orders_test.go
  pkg/handlers/ghcapi/progear_weight_ticket_test.go
  pkg/handlers/internalapi/progear_weight_ticket_test.go
  pkg/handlers/internalapi/uploads_test.go
  pkg/handlers/internalapi/weight_ticket_test.go
  pkg/models/order_test.go
  pkg/models/service_member_test.go
  pkg/services/move/move_router_test.go
  pkg/services/move_history/move_history_fetcher_test.go
  pkg/services/moving_expense/moving_expense_deleter_test.go
  pkg/services/moving_expense/moving_expense_updater_test.go
  pkg/services/mto_service_item/mto_service_item_updater_test.go
  pkg/services/mto_shipment/mto_shipment_fetcher_test.go
  pkg/services/order/excess_weight_risk_manager_test.go
  pkg/services/ppmshipment/ppm_document_fetcher_test.go
  pkg/services/progear_weight_ticket/progear_weight_ticket_deleter_test.go
  pkg/services/progear_weight_ticket/progear_weight_ticket_updater_test.go
  pkg/services/upload/upload_information_fetcher_test.go
  pkg/services/weight_ticket/weight_ticket_deleter_test.go
  pkg/services/weight_ticket/weight_ticket_fetcher_test.go
  pkg/services/weight_ticket/weight_ticket_updater_test.go
  pkg/testdatagen/scenario/bandwidth.go
  pkg/testdatagen/scenario/shared.go
Labels: ready-to-merge, spark

#10286 [ office-hours ] Updating the browsers list database
  yarn.lock
Labels: enhancement, Pamplemoose, dependencies, help wanted

#10280 [MB-14343] Playwright tests for SC Pro-gear and Expenses Review
  pkg/testdatagen/testharness/dispatch.go
  pkg/testdatagen/testharness/make_move.go
  playwright/tests/office/servicescounseling/servicesCounselingMovingExpenses.spec.js
  playwright/tests/office/servicescounseling/servicesCounselingProGearTickets.spec.js
  playwright/tests/utils/testharness.js
  yarn.lock
Labels: A-Team, ready-to-merge

#10281 [MB-15174] render weight warning on review shipment weights page
  src/pages/Office/ServicesCounselingReviewShipmentWeights/ServicesCounselingReviewShipmentWeights.jsx
  src/pages/Office/ServicesCounselingReviewShipmentWeights/ServicesCounselingReviewShipmentWeights.module.scss
  src/pages/Office/ServicesCounselingReviewShipmentWeights/ServicesCounselingReviewShipmentWeights.test.jsx
Labels: Pamplemoose

#10078 [ MB-15224 ] Specifying golang version for golangci-lint environment creation
  .circleci/config.yml
  .pre-commit-config.yaml
  Dockerfile.local
  Dockerfile.migrations_local
  Dockerfile.reviewapp
  Dockerfile.tasks_local
  Dockerfile.tools_local
  Dockerfile.webhook_client
  Dockerfile.webhook_client_dp3
  Dockerfile.webhook_client_local
  Makefile
  nix/default.nix
Labels: Pamplemoose, ready-to-merge

#10228 [ MB-15054 ] Edit Net Weight for Service Counselors
  src/components/Office/PPM/EditNetWeights/EditPPMNetWeight.jsx
  src/components/Office/PPM/EditNetWeights/EditPPMNetWeight.module.scss
  src/components/Office/PPM/EditNetWeights/EditPPMNetWeight.test.jsx
  src/components/Office/PPM/ReviewWeightTicket/ReviewWeightTicket.jsx
  src/components/Office/PPM/ReviewWeightTicket/ReviewWeightTicket.stories.jsx
  src/components/Office/PPM/ReviewWeightTicket/ReviewWeightTicket.test.jsx
  src/pages/Office/PPM/ReviewDocuments/ReviewDocuments.jsx
  src/pages/Office/PPM/ReviewDocuments/ReviewDocuments.test.jsx
Labels: Pamplemoose

#10257 [ office-hours ] Adding a new secure migration for @rogeruiz updated CAC
  migrations/app/migrations_manifest.txt
  migrations/app/secure/20230314155457_rogeruiz_cac_update.up.sql
Labels: Pamplemoose, infra, security, ready-to-merge, help wanted

#10282 MB-15344 add and implement factory.BuildExtendedServiceMember
  pkg/factory/service_member_factory.go
  pkg/factory/service_member_factory_test.go
  pkg/factory/shared.go
  pkg/handlers/ghcapi/customer_test.go
  pkg/handlers/internalapi/orders_test.go
  pkg/handlers/internalapi/service_members_test.go
  pkg/handlers/internalapi/users_test.go
  pkg/services/invoice/ghc_payment_request_invoice_generator_test.go
  pkg/services/office_user/customer/customer_updater_test.go
  pkg/services/payment_request/payment_request_reviewed_processor_test.go
  pkg/testdatagen/scenario/bandwidth.go
  pkg/testdatagen/scenario/e2ebasic.go
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/testharness/make_customer.go
  pkg/testdatagen/testharness/make_move.go
Labels: ready-to-merge, spark

#10320 [ MB-12170 ] Changes to edit net weight component
  src/components/Office/PPM/EditNetWeights/EditPPMNetWeight.jsx
  src/components/Office/PPM/EditNetWeights/EditPPMNetWeight.test.jsx
Labels: Pamplemoose, ready-to-merge

#10319 [ MB-15061 ] Add link and overweight alert banner to Review documents page
  src/pages/Office/DocumentViewerSidebar/DocumentViewerSidebar.jsx
  src/pages/Office/DocumentViewerSidebar/DocumentViewerSidebar.test.jsx
  src/pages/Office/PPM/ReviewDocuments/ReviewDocuments.jsx
  src/pages/Office/PPM/ReviewDocuments/ReviewDocuments.module.scss
  src/pages/Office/PPM/ReviewDocuments/ReviewDocuments.test.jsx
  src/utils/test/factories/ppmShipment.js
Labels: Pamplemoose, ready-to-merge

#10308 [MB-15456] Office user can see guidance when there is an empty weight ticket
  src/components/Office/PPM/ReviewWeightTicket/ReviewWeightTicket.jsx
  src/components/Office/PPM/ReviewWeightTicket/ReviewWeightTicket.stories.jsx
  src/components/Office/PPM/ReviewWeightTicket/ReviewWeightTicket.test.jsx
  src/components/form/fields/MaskedTextField/MaskedTextField.module.scss
Labels: A-Team, ready-to-merge

#10330 [ MB-12170 ] Edit PPM net weight query invalidation clarification
  src/components/Office/PPM/EditNetWeights/EditPPMNetWeight.jsx
Labels: Pamplemoose, ready-to-merge

#10333 [MB-15314] Update the caniuse-lite version
  yarn.lock
Labels: dependencies, ttv

#10323 MB-15564 Fix the link in the readme
  README.md
Labels: bug

#10287 [MB-15459] Update office hint text for missing weight tickets
  playwright/tests/my/milmove/ppms/customerPpmTestFixture.js
  src/components/Customer/PPM/Closeout/WeightTicketForm/WeightTicketForm.jsx
  src/components/Customer/PPM/Closeout/WeightTicketForm/WeightTicketForm.test.jsx
  src/components/Customer/PPM/Closeout/WeightTicketUpload/WeightTicketUpload.jsx
  src/components/Customer/PPM/Closeout/WeightTicketUpload/WeightTicketUpload.module.scss
  src/components/Customer/PPM/Closeout/WeightTicketUpload/WeightTicketUpload.test.jsx
Labels: A-Team

#10334 [ MB-14968 ] Modified edit net weight component to reference totalWeight instead of authorizedWeight
  src/components/Office/PPM/ReviewWeightTicket/ReviewWeightTicket.jsx
  src/components/Office/PPM/ReviewWeightTicket/ReviewWeightTicket.stories.jsx
  src/components/Office/PPM/ReviewWeightTicket/ReviewWeightTicket.test.jsx
  src/pages/Office/PPM/ReviewDocuments/ReviewDocuments.test.jsx
Labels: Pamplemoose, ready-to-merge

#10322 MB-15355 replace MakeDefaultUserUpload
  pkg/handlers/ghcapi/documents_test.go
  pkg/handlers/internalapi/documents_test.go
  pkg/handlers/internalapi/uploads_test.go
  pkg/models/user_upload_test.go
  pkg/services/upload/upload_information_fetcher_test.go
Labels: ready-to-merge, spark

#10331 [ MB-15434 ] Include ppm shipments in weight calculations
  src/components/Office/PPM/ReviewShipmentWeightsTable/helpers.jsx
  src/hooks/custom.js
  src/hooks/queries.js
  src/hooks/queries.test.jsx
  src/pages/Office/MovePaymentRequests/MovePaymentRequests.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
  src/pages/Office/ReviewBillableWeight/ReviewBillableWeight.jsx
Labels: Pamplemoose, ready-to-merge

#10251 MB-15451: refactor pop transaction tests
  pkg/testingsuite/pop_suite.go
  pkg/testingsuite/pop_suite_txn.go
  scripts/run-server-test
Labels: ready-to-merge, spark

#10342 MB-15584: Handle nil values for dates
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/update_shipment.go
  pkg/handlers/internalapi/internal/payloads/payload_to_model.go
  pkg/handlers/internalapi/mto_shipment_test.go
  swagger-def/internal.yaml
  swagger/internal.yaml
Labels: ready-to-merge, Huckleberry

#10340 MB-15059 - Add review weights playwright test
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/testharness/dispatch.go
  pkg/testdatagen/testharness/make_move.go
  playwright/tests/office/servicescounseling/servicesCounselingTestFixture.js
  playwright/tests/office/servicescounseling/servicesCounselingWeightTickets.spec.js
  playwright/tests/utils/testharness.js
Labels: Pamplemoose

#10305 MB-15424 Change routing for a PPM when the postal code or origin duty station is in a different GBLOC
  pkg/services/order/order_fetcher.go
  pkg/services/order/order_fetcher_test.go
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/testharness/make_move.go
Labels: ttv

#10351 Add closeout office to new playwright test
  pkg/testdatagen/testharness/make_move.go
Labels: ready-to-merge

#10190 [ MB- 15032 ] Store origin duty location gbloc on orders table
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20230223225426_store_origin_duty_gbloc.up.sql
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/orders.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/payment_request_test.go
  pkg/handlers/ghcapi/queues_test.go
  pkg/handlers/internalapi/moving_expense_test.go
  pkg/handlers/internalapi/orders.go
  pkg/handlers/internalapi/orders_test.go
  pkg/handlers/internalapi/progear_weight_ticket_test.go
  pkg/handlers/internalapi/service_members.go
  pkg/handlers/internalapi/service_members_test.go
  pkg/handlers/internalapi/weight_ticket_test.go
  pkg/models/move.go
  pkg/models/order.go
  pkg/models/origin_duty_location_to_gbloc.go
  pkg/models/postal_code_to_gbloc.go
  pkg/models/postal_code_to_gbloc_test.go
  pkg/models/service_member.go
  pkg/services/order/order_fetcher.go
  pkg/services/order/order_fetcher_test.go
  pkg/services/order/order_updater.go
  pkg/services/order/order_updater_test.go
  pkg/services/payment_request/payment_request_list_fetcher_test.go
  pkg/testdatagen/make_move.go
  pkg/testdatagen/make_mto_shipment.go
  pkg/testdatagen/make_order.go
  pkg/testdatagen/make_service_member.go
  swagger-def/internal.yaml
  swagger/internal.yaml
Labels: Huckleberry

#10335 [MB-8371] allow customer to remove secondary addresses
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20230324203740_add_secondary_address_radio_states.up.sql
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/m_t_o_shipment.go
  pkg/gen/internalmessages/update_shipment.go
  pkg/handlers/internalapi/internal/payloads/model_to_payload.go
  pkg/handlers/internalapi/internal/payloads/payload_to_model.go
  pkg/handlers/internalapi/mto_shipment_test.go
  pkg/handlers/primeapi/payloads/payload_to_model.go
  pkg/models/mto_shipments.go
  pkg/services/mto_shipment/mto_shipment_updater.go
  pkg/services/mto_shipment/mto_shipment_updater_test.go
  pkg/testdatagen/make_mto_shipment.go
  playwright/tests/my/mymove/hhg.spec.js
  src/components/Customer/MtoShipmentForm/MtoShipmentForm.jsx
  src/components/Customer/MtoShipmentForm/MtoShipmentForm.test.jsx
  src/utils/formatMtoShipment.js
  src/utils/formatMtoShipment.test.js
  swagger-def/internal.yaml
  swagger/internal.yaml
Labels: ttv, ready-to-merge

#10341 MB-15494 remove appCtx from test setup functions
  pkg/handlers/internalapi/moving_expense_test.go
  pkg/handlers/internalapi/mto_shipment_test.go
  pkg/handlers/internalapi/progear_weight_ticket_test.go
  pkg/handlers/internalapi/weight_ticket_test.go
Labels: ready-to-merge, spark

#10306 MB-15529 playwright wait for navigation
  playwright/tests/my/milmove/ppms/customerPpmTestFixture.js
  playwright/tests/office/qaecsr/csrFlows.spec.js
  playwright/tests/office/qaecsr/qaeFlows.spec.js
  playwright/tests/office/txo/tioFlows.spec.js
  playwright/tests/office/txo/tioUpdateMaxBillableWeight.spec.js
  playwright/tests/office/txo/tooFlows.spec.js
  playwright/tests/utils/customerTest.js
  playwright/tests/utils/officeTest.js
  scripts/run-e2e-test
Labels: ready-to-merge

#10349 Remove SAC code spill over
  src/components/Office/PaymentRequestDetails/PaymentRequestDetails.jsx
  src/components/Office/ReviewServiceItems/ReviewAccountingCodes.jsx
  src/components/Office/ReviewServiceItems/ReviewAccountingCodes.module.scss
  src/styles/descriptionList.module.scss
Labels: ttv

#10297 MB-14759: implement factory.BuildOrder
  pkg/factory/duty_location_factory.go
  pkg/factory/duty_location_factory_test.go
  pkg/factory/order_factory.go
  pkg/factory/order_factory_test.go
  pkg/factory/service_member_factory_test.go
  pkg/factory/shared.go
  pkg/factory/shared_test.go
Labels: ready-to-merge, spark

#10361 MB-15611: add factory for OriginDutyLocationGBLOC and use in BuildOrders
  pkg/factory/duty_location_factory.go
  pkg/factory/duty_location_factory_test.go
  pkg/factory/order_factory.go
  pkg/factory/order_factory_test.go
  pkg/factory/postal_code_to_gbloc_factory.go
  pkg/factory/postal_code_to_gbloc_factory_test.go
  pkg/factory/shared.go
  pkg/handlers/ghcapi/queues_test.go
  pkg/handlers/internalapi/orders_test.go
  pkg/handlers/internalapi/service_members_test.go
  pkg/models/postal_code_to_gbloc_test.go
  pkg/services/order/order_fetcher_test.go
  pkg/services/order/order_updater_test.go
Labels: ready-to-merge, spark

#10352 MB-15580: convert pkg/testdatagen/scenario to BuildOrders
  pkg/factory/duty_location_factory.go
  pkg/testdatagen/scenario/e2ebasic.go
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/testharness/dispatch.go
Labels: ready-to-merge, spark

#10362 [ MB-14981 ] Add orders type to getMTO endpoint in the prime api
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/create_m_t_o_shipment.go
  pkg/gen/primemessages/order.go
  pkg/gen/primemessages/orders_type.go
  pkg/handlers/primeapi/payloads/model_to_payload.go
  pkg/handlers/primeapi/payloads/model_to_payload_test.go
  swagger-def/definitions/OrdersType.yaml
  swagger-def/ghc.yaml
  swagger-def/internal.yaml
  swagger-def/prime.yaml
  swagger/ghc.yaml
  swagger/internal.yaml
  swagger/prime.yaml
Labels: ready-to-merge, Huckleberry

#10374 [MB-14962] gbloc output for prime
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/order.go
  pkg/handlers/primeapi/payloads/model_to_payload.go
  pkg/handlers/primeapi/payloads/model_to_payload_test.go
  swagger-def/prime.yaml
  swagger/prime.yaml
Labels: Huckleberry
