Repository transcom/mymove, pull requests merged in 2023-04, with the labels that each got.

#10372 [ MB-15652 ] Change default closeout office in devseed to KKFA gbloc
  pkg/testdatagen/scenario/shared.go
  playwright/tests/my/milmove/ppms/review.spec.js
Labels: ready-to-merge, Huckleberry

#10368 MB-15568 Re enable DTOD by Turning Off Mocking for Staging
  config/env/stg.app.env
Labels: do not merge, bug

#10373 [MB-15623] Refactor SIT uses of React Query mutations
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
Labels: Pamplemoose, ready-to-merge

#10366 MB-15094 replace MakeOrder functions with BuildOrder
  pkg/handlers/adminapi/upload_information_test.go
  pkg/handlers/ghcapi/move_task_order_test.go
  pkg/handlers/ghcapi/orders_test.go
  pkg/handlers/internalapi/moves_test.go
  pkg/handlers/internalapi/mto_shipment_test.go
  pkg/handlers/internalapi/office_test.go
  pkg/handlers/internalapi/orders_test.go
  pkg/handlers/internalapi/personally_procured_move_incentive_test.go
  pkg/handlers/internalapi/personally_procured_move_shared_test.go
  pkg/handlers/internalapi/personally_procured_move_test.go
  pkg/handlers/internalapi/service_members_test.go
  pkg/handlers/internalapi/users_test.go
  pkg/models/move_test.go
  pkg/models/order_test.go
  pkg/models/personally_procured_move_test.go
  pkg/models/queue_test.go
  pkg/models/service_member_test.go
  pkg/paperwork/generator_test.go
  pkg/paperwork/shipment_summary_test.go
  pkg/services/event/event_test.go
  pkg/services/event/notification_test.go
  pkg/services/invoice/ghc_payment_request_invoice_generator_test.go
  pkg/services/move/move_router_test.go
  pkg/services/move_task_order/move_task_order_creator_test.go
  pkg/services/move_task_order/move_task_order_updater_test.go
  pkg/services/order/order_fetcher_test.go
  pkg/services/order/order_updater_test.go
Labels: ready-to-merge, spark

#10359 MB-15597: BuildMove initial spike
  pkg/factory/move_factory.go
  pkg/factory/move_factory_test.go
  pkg/factory/order_factory.go
  pkg/factory/order_factory_test.go
  pkg/factory/shared.go
  pkg/handlers/adminapi/upload_information_test.go
  pkg/handlers/ghcapi/move_task_order_test.go
  pkg/handlers/ghcapi/move_test.go
  pkg/handlers/ghcapi/queues_test.go
  pkg/models/order_test.go
  pkg/services/move/move_router_test.go
  pkg/services/mto_shipment/shipment_router_test.go
Labels: ready-to-merge, spark

#10393 [MB-15674] Non-PPM shipments are not visible if the move does not have pro-gear
  src/pages/Office/MoveTaskOrder/moveTaskOrderUnitTestData.js
  src/pages/Office/ServicesCounselingReviewShipmentWeights/ServicesCounselingReviewShipmentWeights.jsx
  src/pages/Office/ServicesCounselingReviewShipmentWeights/ServicesCounselingReviewShipmentWeights.test.jsx
Labels: Pamplemoose, ready-to-merge

#10392 :closed_lock_with_key: CAC cert for Katy
  migrations/app/migrations_manifest.txt
  migrations/app/secure/20230404195728_katyc_cac_access.up.sql
Labels: ready-to-merge

#10394 [MB-14513] Fix Upload Search
  src/scenes/SystemAdmin/Uploads/UploadShow.jsx
Labels: ttv

#10298 MB-15488 Add fields to `ppm_shipments` table to store references to AOA and Payment packets
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20230403135359_add_fields_to_ppm_shipments_for_aoa_and_payment_packets.up.sql
  pkg/handlers/converters_strfmt.go
  pkg/handlers/internalapi/internal/payloads/payload_to_model.go
  pkg/models/ppm_shipment.go
  pkg/models/ppm_shipment_test.go
  pkg/models/validators.go
  pkg/models/validators_test.go
  pkg/services/move/move_router_test.go
  pkg/testdatagen/make_ppm_shipment.go
  pkg/testdatagen/make_weight_ticket.go
  pkg/testdatagen/shared.go
  pkg/testdatagen/testdata/aoa-packet.pdf
  pkg/testdatagen/testdata/payment-packet.pdf
Labels: A-Team, ready-to-merge

#10312 MB-15488 add generic ppm shipment fetcher service object
  pkg/services/ppmshipment.go
  pkg/services/ppmshipment/ppm_shipment_fetcher.go
  pkg/services/ppmshipment/ppm_shipment_fetcher_test.go
  pkg/testdatagen/make_ppm_shipment.go
Labels: A-Team, ready-to-merge

#10382 MB-15488 Add new make function to create a weight ticket with constructed weights
  pkg/factory/user_upload_factory.go
  pkg/testdatagen/make_user_upload.go
  pkg/testdatagen/make_weight_ticket.go
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/testdata/empty-weight-ticket.png
  pkg/testdatagen/testdata/filled-out-orders.pdf
  pkg/testdatagen/testdata/full-weight-ticket.png
  pkg/testdatagen/testdata/ssw-old.pdf
  pkg/testdatagen/testdata/wa-vehicle-registration.pdf
Labels: A-Team, ready-to-merge

#10395 MB-15092: BuildMTOShipment initial spike
  pkg/factory/mto_shipment_factory.go
  pkg/factory/mto_shipment_factory_test.go
  pkg/factory/shared.go
Labels: ready-to-merge, spark

#10381 MB-15084: Add submitted date for TOO
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20230405164241_add_date_sent_for_service_item_approvals_to_moves.up.sql
  pkg/factory/move_factory.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/queues/get_moves_queue_parameters.go
  pkg/gen/ghcapi/ghcoperations/queues/get_moves_queue_urlbuilder.go
  pkg/gen/ghcmessages/move.go
  pkg/gen/ghcmessages/queue_move.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/queues.go
  pkg/models/move.go
  pkg/services/move/move_router.go
  pkg/services/move/move_router_test.go
  pkg/services/order.go
  pkg/services/order/order_fetcher.go
  pkg/services/order/order_fetcher_test.go
  pkg/testdatagen/make_move.go
  src/pages/Office/MoveQueue/MoveQueue.jsx
  src/pages/Office/MoveQueue/MoveQueue.test.jsx
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: ready-to-merge, Huckleberry

#10421 [ MB-15334 ]Adding SITDestinationFinalAddress to getMoveTastOrder endpoint
  pkg/handlers/primeapi/move_task_order_test.go
  pkg/services/move_task_order/move_task_order_fetcher.go
  pkg/services/move_task_order/move_task_order_fetcher_test.go
Labels: ready-to-merge, Huckleberry

#10438 MB-15135 Ensure ppm document overview contains all docs
  pkg/testdatagen/scenario/shared.go
  src/components/Office/PPM/ReviewDocumentsSidePanel/ReviewDocumentsSidePanel.test.jsx
  src/pages/Office/PPM/ReviewDocuments/ReviewDocuments.jsx
  src/pages/Office/PPM/ReviewDocuments/ReviewDocuments.test.jsx
Labels: A-Team

#10459 [MB-15407] Replace current mailing address with pickup
  playwright/tests/my/mymove/onboarding.spec.js
  playwright/tests/utils/waitForPage.js
  src/components/Customer/EditContactInfoForm/EditContactInfoForm.jsx
  src/components/Customer/Profile/ContactInfoDisplay/ContactInfoDisplay.jsx
  src/components/Customer/Profile/ContactInfoDisplay/ContactInfoDisplay.test.jsx
  src/components/Customer/ResidentialAddressForm/ResidentialAddressForm.jsx
  src/components/Customer/ResidentialAddressForm/ResidentialAddressForm.module.scss
  src/components/Customer/ResidentialAddressForm/ResidentialAddressForm.test.jsx
  src/components/Customer/Review/ProfileTable/ProfileTable.jsx
  src/components/form/AddressFields/AddressFields.stories.jsx
  src/constants/MoveHistory/Database/FieldMappings.js
  src/constants/MoveHistory/EventTemplates/UpdateAddress/createAddress.test.jsx
  src/constants/MoveHistory/EventTemplates/UpdateAddress/updateAddress.test.jsx
  src/pages/MyMove/Profile/EditContactInfo.test.jsx
  src/pages/MyMove/Profile/ResidentialAddress.test.jsx
  src/scenes/Review/ServiceMemberSummary.jsx
Labels: A-Team

#10461 MB-15739 Replace MakeMTOShipment func calls in pkg/testdatagen/*
  pkg/factory/mto_shipment_factory.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/handlers/internalapi/moves_test.go
  pkg/handlers/primeapi/move_task_order_test.go
  pkg/handlers/primeapi/mto_agent_test.go
  pkg/handlers/primeapi/mto_shipment_address_test.go
  pkg/handlers/primeapi/mto_shipment_test.go
  pkg/payment_request/service_param_value_lookups/eia_fuel_price_lookup_test.go
  pkg/services/invoice/ghc_payment_request_invoice_generator_test.go
  pkg/services/move/move_router_test.go
  pkg/services/move/move_weights_test.go
  pkg/services/move_task_order/move_task_order_fetcher_test.go
  pkg/services/move_task_order/move_task_order_updater_test.go
  pkg/services/mto_agent/mto_agent_creator_test.go
  pkg/services/mto_shipment/mto_shipment_updater_test.go
  pkg/services/mto_shipment/shipment_approver_test.go
  pkg/services/mto_shipment/shipment_cancellation_requester_test.go
  pkg/services/mto_shipment/shipment_diversion_approver_test.go
  pkg/services/mto_shipment/shipment_diversion_requester_test.go
  pkg/services/mto_shipment/shipment_reweigh_requester_test.go
  pkg/services/mto_shipment/shipment_sit_status_test.go
  pkg/services/reweigh/rules_test.go
  pkg/services/sit_extension/sit_extension_creator_test.go
  pkg/testdatagen/scenario/bandwidth.go
  pkg/testdatagen/scenario/e2ebasic.go
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/scenario/subscenarios.go
  pkg/testdatagen/testharness/make_move.go
Labels: ready-to-merge, spark

#10422 [MB-15120] PPM Processor can confirm approval/rejection of PPM Document Sets
  playwright/tests/office/servicescounseling/servicesCounselingMovingExpenses.spec.js
  playwright/tests/office/servicescounseling/servicesCounselingProGearTickets.spec.js
  playwright/tests/office/servicescounseling/servicesCounselingWeightTickets.spec.js
  src/components/Office/PPM/ReviewDocumentsSidePanel/ReviewDocumentsSidePanel.jsx
  src/components/Office/PPM/ReviewDocumentsSidePanel/ReviewDocumentsSidePanel.stories.jsx
  src/components/Office/PPM/ReviewDocumentsSidePanel/ReviewDocumentsSidePanel.test.jsx
  src/components/Office/ShipmentDisplay/ShipmentDisplay.jsx
  src/components/Office/ShipmentDisplay/ShipmentDisplay.stories.jsx
  src/components/Office/ShipmentDisplay/ShipmentDisplay.test.jsx
  src/components/Office/ShipmentDisplay/ShipmentDisplayTestData.js
  src/pages/Office/PPM/ReviewDocuments/ReviewDocuments.jsx
  src/pages/Office/PPM/ReviewDocuments/ReviewDocuments.test.jsx
  src/services/ghcApi.js
Labels: A-Team, ready-to-merge

#10480 MB-15749: Implement BuildNotification and convert use
  pkg/factory/notification_factory.go
  pkg/factory/notification_factory_test.go
  pkg/factory/shared.go
  pkg/handlers/adminapi/notifications_test.go
Labels: ready-to-merge, spark

#10420 MB-15706 Fix custom linter tests
  eslint-plugin-ato/no-unapproved-annotation.js
  eslint-plugin-ato/tests/no-unapproved-annotation.test.js
Labels: ready-to-merge, bug

#10436 MB-15707 Fix linter errors in shared and scenes
  src/scenes/Moves/Ppm/WeightTicket.jsx
  src/scenes/Review/EditDateAndLocation.jsx
  src/shared/AlertWithDeleteConfirmation/index.jsx
  src/shared/ConfirmWithReasonButton/index.jsx
  src/shared/JsonSchemaForm/reduxFieldNormalizer.js
  src/shared/LoadingPlaceholder/index.jsx
  src/shared/ReduxHelpers/index.js
  src/shared/utils.js
Labels: ready-to-merge, bug

#10437 MB-15704 turn on linters in shared and scenes
  src/scenes/.eslintrc
  src/shared/.eslintrc
Labels: ready-to-merge

#10490 MB-15665 Remove selected move type
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20230413135123_remove_selected_move_type_from_moves.up.sql
  pkg/factory/move_factory.go
  pkg/factory/move_factory_test.go
  pkg/factory/mto_shipment_factory_test.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/move_payload.go
  pkg/gen/internalmessages/selected_move_type.go
  pkg/gen/supportapi/embedded_spec.go
  pkg/gen/supportmessages/move_task_order.go
  pkg/gen/supportmessages/selected_move_type.go
  pkg/handlers/ghcapi/queues_test.go
  pkg/handlers/internalapi/moves.go
  pkg/handlers/internalapi/office_test.go
  pkg/handlers/internalapi/orders.go
  pkg/handlers/internalapi/personally_procured_move_test.go
  pkg/handlers/primeapi/payloads/model_to_payload_test.go
  pkg/handlers/supportapi/internal/payloads/model_to_payload.go
  pkg/handlers/supportapi/move_task_order_test.go
  pkg/models/move.go
  pkg/models/move_test.go
  pkg/models/personally_procured_move_test.go
  pkg/models/shipment_summary_worksheet_test.go
  pkg/services/order/order_fetcher.go
  pkg/services/order/order_fetcher_test.go
  pkg/services/paperwork/form_creator_test.go
  pkg/services/payment_request/payment_request_list_fetcher_test.go
  pkg/services/support/move_task_order/move_task_order_creator.go
  pkg/testdatagen/make_move.go
  pkg/testdatagen/make_payment_request.go
  pkg/testdatagen/scenario/e2ebasic.go
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/scenario/subscenarios.go
  pkg/testdatagen/testharness/make_move.go
  src/components/Customer/Review/Summary/Summary.test.jsx
  src/pages/MyMove/SelectShipmentType.test.jsx
  src/scenes/MyMove/getWorkflowRoutes.test.js
  src/scenes/PpmLanding/index.jsx
  swagger-def/internal.yaml
  swagger-def/support.yaml
  swagger/internal.yaml
  swagger/support.yaml
Labels: ready-to-merge, spark

#10481 MB-15750 build signed certification
  pkg/factory/shared.go
  pkg/factory/signed_certification_factory.go
  pkg/factory/signed_certification_factory_test.go
  pkg/handlers/internalapi/moves_test.go
  pkg/handlers/internalapi/office_test.go
  pkg/handlers/internalapi/personally_procured_move_test.go
  pkg/handlers/internalapi/service_members_test.go
  pkg/handlers/internalapi/signed_certifications_test.go
  pkg/models/shipment_summary_worksheet_test.go
  pkg/models/signed_certification_test.go
  pkg/services/move/move_router_test.go
  pkg/services/paperwork/form_creator_test.go
  pkg/services/ppmshipment/ppm_shipment_fetcher_test.go
  pkg/testdatagen/make_ppm_shipment.go
  pkg/testdatagen/scenario/e2ebasic.go
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/testharness/make_move.go
Labels: ready-to-merge, spark

#10447 MB-15653 Update prime name and contract number
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20230413164702_add_uniqueness_constraint_to_contractor_type.up.sql
  migrations/app/secure/20230412175236_update_prime_name_and_contract_number.up.sql
  pkg/factory/contractor_factory.go
  pkg/handlers/primeapi/upload.go
  pkg/models/contractor.go
  pkg/models/move.go
  pkg/testdatagen/make_contractor.go
  pkg/testdatagen/make_move.go
  pkg/testdatagen/make_prime_upload.go
  pkg/testdatagen/make_webhook_subscription.go
  playwright/tests/office/txo/tioFlows.spec.js
Labels: ttv

#10451 MB-15488 Add gotenberg-related service objects
  .envrc
  pkg/db/utilities/utilities_test.go
  pkg/factory/upload_factory.go
  pkg/factory/upload_factory_test.go
  pkg/handlers/adminapi/upload_information_test.go
  pkg/handlers/ghcapi/documents_test.go
  pkg/handlers/internalapi/api.go
  pkg/handlers/internalapi/documents_test.go
  pkg/handlers/internalapi/uploads_test.go
  pkg/models/prime_upload_test.go
  pkg/models/upload_test.go
  pkg/models/user_upload_test.go
  pkg/models/validators_test.go
  pkg/notifications/notification_sender.go
  pkg/paperwork/generator.go
  pkg/paperwork/generator_test.go
  pkg/services/mocks/PDFMerger.go
  pkg/services/mocks/UserUploadToPDFConverter.go
  pkg/services/paperwork.go
  pkg/services/paperwork/paperwork_service_test.go
  pkg/services/paperwork/pdf_merger.go
  pkg/services/paperwork/pdf_merger_test.go
  pkg/services/paperwork/shared.go
  pkg/services/paperwork/shared_test.go
  pkg/services/paperwork/user_upload_to_pdf_converter.go
  pkg/services/paperwork/user_upload_to_pdf_converter_test.go
  pkg/services/payment_request/upload_creator_test.go
  pkg/storage/test/s3.go
  pkg/testdatagen/make_upload.go
  pkg/testdatagen/testdata/empty-weight-ticket.pdf
  pkg/testdatagen/testdata/full-weight-ticket.pdf
  pkg/uploader/allowed_file_types.go
  pkg/uploader/allowed_file_types_test.go
  pkg/uploader/prime_uploader_test.go
  pkg/uploader/uploader_test.go
  pkg/uploader/user_uploader_test.go
Labels: A-Team, ready-to-merge

#10492 MB-15756 build customer support remark
  pkg/factory/customer_support_remark_factory.go
  pkg/factory/customer_support_remark_factory_test.go
  pkg/factory/shared.go
  pkg/handlers/ghcapi/customer_support_remarks_test.go
  pkg/services/customer_support_remarks/customer_support_remarks_deleter_test.go
  pkg/services/customer_support_remarks/customer_support_remarks_fetcher_test.go
  pkg/services/customer_support_remarks/customer_support_remarks_updater_test.go
  pkg/testdatagen/make_customer_support_remark.go
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/scenario/subscenarios.go
Labels: ready-to-merge, spark

#10494 [MB-15646] Add spreadsheet file types to gitignore prior to pricing import work
  .gitignore
Labels: ttv

#10508 Add CAC migration to get access to support APIs
  migrations/app/migrations_manifest.txt
  migrations/app/secure/20230420144546_ronak_cac.up.sql
Labels: ready-to-merge

#10493 MB-15096 factory.BuildMTOServiceItemDimension added as new version of testdatagen.MakeMTOServiceItemDimension
  pkg/factory/mto_service_item_dimension_factory.go
  pkg/factory/mto_service_item_dimension_test.go
  pkg/factory/shared.go
  pkg/payment_request/service_param_value_lookups/cubic_feet_billed_lookup_test.go
  pkg/payment_request/service_param_value_lookups/cubic_feet_crating_lookup_test.go
  pkg/payment_request/service_param_value_lookups/dimension_height_lookup_test.go
  pkg/payment_request/service_param_value_lookups/dimension_length_lookup_test.go
  pkg/payment_request/service_param_value_lookups/dimension_width_lookup_test.go
  pkg/payment_request/service_param_value_lookups/service_params_cache_test.go
  pkg/services/event/notification_test.go
Labels: ready-to-merge, spark

#10491 [ MB-15729 ] Fix for errors in edi process when there is no associated transportation office for a duty location
  pkg/factory/duty_location_factory.go
  pkg/factory/duty_location_factory_test.go
  pkg/handlers/supportapi/payment_request_test.go
  pkg/models/duty_location.go
  pkg/models/duty_location_test.go
  pkg/services/invoice/ghc_payment_request_invoice_generator.go
  pkg/services/invoice/ghc_payment_request_invoice_generator_test.go
Labels: ready-to-merge, Huckleberry

#10504 MB-15671 Replace MakeMove helpers
  pkg/factory/move_factory.go
  pkg/factory/move_factory_test.go
  pkg/factory/mto_shipment_factory.go
  pkg/factory/shared.go
  pkg/factory/shared_test.go
  pkg/handlers/ghcapi/move_task_order_test.go
  pkg/handlers/ghcapi/payment_request_test.go
  pkg/handlers/ghcapi/queues_test.go
  pkg/models/move_test.go
  pkg/services/move/move_router_test.go
  pkg/services/move_task_order/move_task_order_updater_test.go
  pkg/services/mto_shipment/mto_shipment_updater_test.go
  pkg/services/order/order_fetcher_test.go
  pkg/services/payment_request/payment_request_list_fetcher_test.go
  pkg/testdatagen/scenario/e2ebasic.go
  pkg/testdatagen/scenario/shared.go
Labels: ready-to-merge, spark

#10510 MB-15761 factory.BuildWebhookNotification added as new version of testdatagen.MakeWebhookNotification
  cmd/webhook-client/webhook/webhook_test.go
  pkg/factory/shared.go
  pkg/factory/webhook_notification_factory.go
  pkg/factory/webhook_notification_factory_test.go
Labels: ready-to-merge, spark

#10513 MB-15713 build service param factory
  pkg/factory/mto_service_item_factory.go
  pkg/factory/re_service_factory.go
  pkg/factory/re_service_factory_test.go
  pkg/factory/service_param_factory.go
  pkg/factory/service_param_factory_test.go
  pkg/factory/shared.go
  pkg/payment_request/service_param_list_fetcher_test.go
  pkg/payment_request/service_param_list_valid_test.go
  pkg/payment_request/service_param_value_lookups/contract_code_lookup_test.go
  pkg/payment_request/service_param_value_lookups/distance_zip_lookup_test.go
  pkg/payment_request/service_param_value_lookups/eia_fuel_price_lookup_test.go
  pkg/payment_request/service_param_value_lookups/service_params_cache_test.go
  pkg/services/payment_request/payment_request_creator_test.go
  pkg/testdatagen/make_service_param.go
Labels: ready-to-merge

#10534 Fixing the fresh-brew URLs in this repo too
  scripts/setup
Labels: dependencies, ready-to-merge, help wanted, bug

#10533 MB-15272 Fix loading of a user's details
  pkg/handlers/adminapi/office_users.go
  pkg/handlers/adminapi/office_users_test.go
Labels: ttv

#10518 [MB-15669] Update Text Seen By Customer
  playwright/tests/office/servicescounseling/servicesCounselingTestFixture.js
  src/components/Customer/Footer/index.jsx
  src/pages/SignIn/SignIn.jsx
  src/scenes/Legalese/legaleseText.js
Labels: A-Team, ready-to-merge

#10496 MB-15488 Add AOA and payment packet service objects
  pkg/services/mocks/AOAPacketCreator.go
  pkg/services/mocks/PaymentPacketCreator.go
  pkg/services/ppmshipment.go
  pkg/services/ppmshipment/aoa_packet_creator.go
  pkg/services/ppmshipment/aoa_packet_creator_test.go
  pkg/services/ppmshipment/payment_packet_creator.go
  pkg/services/ppmshipment/payment_packet_creator_test.go
  pkg/services/ppmshipment/ppm_shipment_fetcher.go
  pkg/services/ppmshipment/ppm_shipment_fetcher_test.go
  pkg/services/ppmshipment/ppm_shipment_service_test.go
  pkg/testdatagen/make_order.go
  pkg/testdatagen/make_ppm_shipment.go
Labels: A-Team, ready-to-merge

#10537 MB-15466-new-updateMTOPostCounselingInformation-branch
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/move_task_order/update_m_t_o_post_counseling_information.go
  pkg/gen/primeclient/move_task_order/move_task_order_client.go
  pkg/gen/primemessages/move_task_order.go
  swagger-def/prime.yaml
  swagger/prime.yaml
Labels: Huckleberry

#10516 MB-15760 BuildEvaluationReport factory
  pkg/factory/evaluation_report_factory_test.go
  pkg/factory/evaulation_report_factory.go
  pkg/factory/shared.go
  pkg/handlers/ghcapi/evaluation_report_test.go
  pkg/handlers/ghcapi/report_violations_test.go
  pkg/models/evaluation_report_test.go
  pkg/paperwork/evaluation_report_form_creator_test.go
  pkg/services/evaluation_report/evaluation_report_deleter_test.go
  pkg/services/evaluation_report/evaluation_report_fetcher_test.go
  pkg/services/evaluation_report/evaluation_report_updater_test.go
  pkg/services/report_violation/report_violation_creator_test.go
  pkg/testdatagen/scenario/subscenarios.go
Labels: ready-to-merge, spark

#10495 [MB-15479] Rewrite zip code validation service to avoid 400ng tables
  pkg/apperror/errors.go
  pkg/handlers/errors.go
  pkg/handlers/internalapi/api.go
  pkg/handlers/internalapi/postal_codes.go
  pkg/handlers/internalapi/postal_codes_test.go
  pkg/route/errors.go
  pkg/route/here_planner.go
  pkg/route/here_planner_test.go
  pkg/route/zip3_locale.go
  pkg/route/zip_locale.go
  pkg/services/mocks/PostalCodeValidator.go
  pkg/services/postal_code.go
  pkg/services/postal_codes/postal_code_validator.go
  pkg/services/postal_codes/postal_code_validator_test.go
  pkg/testdatagen/make_re_zip5_rate_area.go
  pkg/testdatagen/shared.go
Labels: ttv, ready-to-merge

#10505 [MB-15593] Refactor `SubmitSITExtensionsModal.jsx` component
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/create_approved_s_i_t_duration_update.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/create_s_i_t_extension.go
  pkg/models/sit_duration_update.go
  pkg/models/sit_duration_update_test.go
  src/components/Office/ShipmentDetails/ShipmentDetailsMain.jsx
  src/components/Office/ShipmentSITDisplay/ShipmentSITDisplay.jsx
  src/components/Office/SubmitSITExtensionModal/SubmitSITExtensionModal.jsx
  src/components/Office/SubmitSITExtensionModal/SubmitSITExtensionModal.module.scss
  src/components/Office/SubmitSITExtensionModal/SubmitSITExtensionModal.stories.jsx
  src/components/Office/SubmitSITExtensionModal/SubmitSITExtensionModal.test.jsx
  src/components/form/fields/DatePickerInput.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
  swagger-def/ghc.yaml
  swagger-def/prime.yaml
  swagger/ghc.yaml
  swagger/prime.yaml
Labels: Pamplemoose

#10545 [MB-15679] Fix Admin office user export path resource causing not found error
  src/pages/Admin/OfficeUsers/OfficeUserList.jsx
Labels: ttv, ready-to-merge

#10547 MB-15488 fix (tests): fix flaky tests that were comparing pdf byte slices
  pkg/services/paperwork/pdf_merger_test.go
  pkg/services/paperwork/shared_test.go
  pkg/services/paperwork/user_upload_to_pdf_converter_test.go
  pkg/services/ppmshipment/aoa_packet_creator_test.go
  pkg/services/ppmshipment/payment_packet_creator_test.go
Labels: A-Team

#10520 MB-15705 Add Custom FE Linter Tests to the FE linter workflow
  .github/workflows/front-end-linter.yml
Labels: ready-to-merge

#10503 [MB-15587] Bump pre-commit
  .circleci/config.yml
  .pre-commit-config.yaml
  Dockerfile.local
  Dockerfile.migrations_local
  Dockerfile.reviewapp
  Dockerfile.tasks_local
  Dockerfile.tools_local
  Dockerfile.webhook_client
  Dockerfile.webhook_client_dp3
  Dockerfile.webhook_client_local
  Makefile
  nix/default.nix
Labels: dependencies

#10485 MB-15588 Add eslint jsx-a11y to the src linter
  .eslintrc.js
Labels: ready-to-merge

#10539 MB-15728: Implement and use BuildRealMTOServiceItemWithAllDeps
  pkg/factory/mto_service_item_factory.go
  pkg/factory/mto_service_item_factory_test.go
  pkg/handlers/primeapi/payment_request_test.go
  pkg/services/payment_request/payment_request_creator_test.go
  pkg/services/payment_request/payment_request_recalculator_test.go
  pkg/testdatagen/make_mto_service_item.go
  pkg/testdatagen/make_payment_request.go
Labels: ready-to-merge

#10551 MB-15813 add and implement BuildMTOAgent
  pkg/factory/mto_agent_factory.go
  pkg/factory/mto_agent_factory_test.go
  pkg/factory/shared.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/handlers/primeapi/mto_agent_test.go
  pkg/handlers/primeapi/mto_shipment_test.go
  pkg/services/event/notification_test.go
  pkg/services/move_history/move_history_fetcher_test.go
  pkg/services/move_task_order/move_task_order_hide_non_fake_test.go
  pkg/services/mto_shipment/mto_shipment_fetcher_test.go
  pkg/services/mto_shipment/mto_shipment_updater_test.go
  pkg/testdatagen/scenario/bandwidth.go
  pkg/testdatagen/scenario/e2ebasic.go
  pkg/testdatagen/scenario/shared.go
Labels: ready-to-merge, spark

#10544 MB-15820: Explicitly call accessibility tests because of flakiness
  playwright/tests/office/servicescounseling/servicesCounselingTestFixture.js
  playwright/tests/utils/baseTest.js
  playwright/tests/utils/customerTest.js
  playwright/tests/utils/waitForPage.js
Labels: ready-to-merge

#10546 MB-15748: Remove Unused Testdatagen Make Functions
  pkg/handlers/ghcapi/move_test.go
  pkg/handlers/ghcapi/transportation_offices_test.go
  pkg/handlers/internalapi/moves_test.go
  pkg/handlers/internalapi/moving_expense_test.go
  pkg/handlers/internalapi/progear_weight_ticket_test.go
  pkg/handlers/internalapi/users_test.go
  pkg/handlers/internalapi/weight_ticket_test.go
  pkg/handlers/primeapi/move_task_order_test.go
  pkg/models/order_test.go
  pkg/services/invoice/ghc_payment_request_invoice_generator_test.go
  pkg/services/move/move_router_test.go
  pkg/services/move_task_order/move_task_order_fetcher_test.go
  pkg/services/ppmshipment/ppm_estimator_test.go
  pkg/services/signed_certification/signed_certification_creator_test.go
  pkg/services/transportation_office/transportation_office_fetcher_test.go
  pkg/services/user/user_updater_test.go
  pkg/testdatagen/make_address.go
  pkg/testdatagen/make_admin_user.go
  pkg/testdatagen/make_backup_contact.go
  pkg/testdatagen/make_contractor.go
  pkg/testdatagen/make_document.go
  pkg/testdatagen/make_duty_location.go
  pkg/testdatagen/make_move.go
  pkg/testdatagen/make_notification.go
  pkg/testdatagen/make_office_user.go
  pkg/testdatagen/make_order.go
  pkg/testdatagen/make_organization.go
  pkg/testdatagen/make_re_service.go
  pkg/testdatagen/make_role.go
  pkg/testdatagen/make_service_member.go
  pkg/testdatagen/make_signed_certification.go
  pkg/testdatagen/make_transportation_office.go
  pkg/testdatagen/make_upload.go
  pkg/testdatagen/make_user_upload.go
  pkg/testdatagen/make_webhook_notification.go
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/testharness/make_move.go
Labels: ready-to-merge, spark

#10484 MB-15709 build payment request
  pkg/factory/payment_request_factory.go
  pkg/factory/payment_request_factory_test.go
  pkg/factory/shared.go
  pkg/handlers/ghcapi/payment_request_test.go
  pkg/handlers/ghcapi/queues_test.go
  pkg/handlers/primeapi/mto_service_item_test.go
  pkg/handlers/primeapi/upload_test.go
  pkg/handlers/supportapi/payment_request_test.go
  pkg/models/payment_service_item_test.go
  pkg/models/webhook_notification_test.go
  pkg/payment_request/service_param_value_lookups/distance_zip_lookup_test.go
  pkg/payment_request/service_param_value_lookups/distance_zip_sit_dest_lookup_test.go
  pkg/payment_request/service_param_value_lookups/distance_zip_sit_origin_lookup_test.go
  pkg/payment_request/service_param_value_lookups/eia_fuel_price_lookup_test.go
  pkg/payment_request/service_param_value_lookups/mto_available_to_prime_at_lookup_test.go
  pkg/payment_request/service_param_value_lookups/number_days_sit_lookup_test.go
  pkg/payment_request/service_param_value_lookups/service_area_lookup_test.go
  pkg/payment_request/service_param_value_lookups/service_param_value_lookups_test.go
  pkg/payment_request/service_param_value_lookups/service_params_cache_test.go
  pkg/payment_request/service_param_value_lookups/services_schedule_lookup_test.go
  pkg/payment_request/service_param_value_lookups/sit_schedule_lookup_test.go
  pkg/payment_request/service_param_value_lookups/zip_address_lookup_test.go
  pkg/payment_request/service_param_value_lookups/zip_sit_origin_hhg_actual_address_lookup_test.go
  pkg/payment_request/service_param_value_lookups/zip_sit_origin_hhg_original_address_lookup_test.go
  pkg/services/event/event_test.go
  pkg/services/invoice/ghc_payment_request_invoice_generator_test.go
  pkg/services/invoice/process_edi824_test.go
  pkg/services/invoice/process_edi997_test.go
  pkg/services/move_history/move_history_fetcher_test.go
  pkg/services/mto_service_item/mto_service_item_updater_test.go
  pkg/services/mto_service_item/mto_service_item_validators_test.go
  pkg/services/payment_request/payment_request_fetcher_test.go
  pkg/services/payment_request/payment_request_list_fetcher_test.go
  pkg/services/payment_request/payment_request_recalculator_test.go
  pkg/services/payment_request/payment_request_reviewed_fetcher_test.go
  pkg/services/payment_request/payment_request_reviewed_processor_test.go
  pkg/services/payment_request/payment_request_shipments_sit_balance_test.go
  pkg/services/payment_request/payment_request_status_updater_test.go
  pkg/services/payment_request/upload_creator_test.go
  pkg/testdatagen/make_payment_request.go
  pkg/testdatagen/scenario/bandwidth.go
  pkg/testdatagen/scenario/e2ebasic.go
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/testharness/make_move.go
Labels: ready-to-merge

#10543 MB-15752 add and implement BuildPPMShipment
  pkg/db/utilities/utilities_test.go
  pkg/factory/duty_location_factory.go
  pkg/factory/ppm_shipment_factory.go
  pkg/factory/ppm_shipment_factory_test.go
  pkg/factory/shared.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/handlers/internalapi/moves_test.go
  pkg/handlers/internalapi/moving_expense_test.go
  pkg/handlers/internalapi/mto_shipment_test.go
  pkg/handlers/internalapi/progear_weight_ticket_test.go
  pkg/handlers/internalapi/uploads_test.go
  pkg/handlers/internalapi/weight_ticket_test.go
  pkg/handlers/primeapi/move_task_order_test.go
  pkg/handlers/primeapi/mto_shipment_test.go
  pkg/models/moving_expense_test.go
  pkg/payment_request/service_param_value_lookups/distance_zip_lookup_test.go
  pkg/services/move/move_router_test.go
  pkg/services/move/move_weights_test.go
  pkg/services/move_task_order/move_task_order_updater_test.go
  pkg/services/moving_expense/moving_expense_creator_test.go
  pkg/services/moving_expense/moving_expense_deleter_test.go
  pkg/services/moving_expense/moving_expense_updater_test.go
  pkg/services/mto_shipment/mto_shipment_fetcher_test.go
  pkg/services/mto_shipment/shipment_approver_test.go
  pkg/services/mto_shipment/shipment_deleter_test.go
  pkg/services/mto_shipment/shipment_router_test.go
  pkg/services/mto_shipment/validation_test.go
  pkg/services/orchestrators/shipment/shipment_updater_test.go
  pkg/services/order/order_fetcher_test.go
  pkg/services/ppmshipment/aoa_packet_creator_test.go
  pkg/services/ppmshipment/ppm_estimator_test.go
  pkg/services/ppmshipment/ppm_shipment_fetcher_test.go
  pkg/services/ppmshipment/ppm_shipment_router_test.go
  pkg/services/ppmshipment/ppm_shipment_updater_test.go
  pkg/services/progear_weight_ticket/progear_weight_ticket_creator_test.go
  pkg/services/progear_weight_ticket/progear_weight_ticket_deleter_test.go
  pkg/services/progear_weight_ticket/progear_weight_ticket_updater_test.go
  pkg/services/weight_ticket/weight_ticket_creator_test.go
  pkg/services/weight_ticket/weight_ticket_deleter_test.go
  pkg/services/weight_ticket/weight_ticket_updater_test.go
  pkg/testdatagen/make_ppm_shipment.go
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/scenario/subscenarios.go
  pkg/testdatagen/shared.go
  pkg/testdatagen/testharness/make_move.go
Labels: ready-to-merge, spark

#10541 MB-15819 Refactor the EditMaxBillableWeightModal to use Modal and not Migrated Modal
  src/components/Office/EditMaxBillableWeightModal/EditMaxBillableWeightModal.jsx
  src/components/Office/EditMaxBillableWeightModal/EditMaxBillableWeightModal.module.scss
  src/components/Office/EditMaxBillableWeightModal/EditMaxBillableWeightModal.stories.jsx
  src/components/Office/EditMaxBillableWeightModal/EditMaxBillableWeightModal.test.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
Labels: ready-to-merge

#10559 MB-15612 - Add sit duration backend validation
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/services/sit_extension/approved_sit_duration_update_creator.go
  pkg/services/sit_extension/approved_sit_duration_update_creator_test.go
  pkg/services/sit_extension/rules.go
  pkg/services/sit_extension/rules_test.go
  pkg/services/sit_extension/sit_extension_approver.go
  pkg/services/sit_extension/sit_extension_approver_test.go
  pkg/services/sit_extension/sit_extension_denier.go
  pkg/services/sit_extension/sit_extension_denier_test.go
Labels: Pamplemoose

#10560 MB-15710 add and implement BuildProofOfServiceDoc
  pkg/factory/proof_of_service_doc_factory.go
  pkg/factory/proof_of_service_doc_factory_test.go
  pkg/factory/shared.go
  pkg/models/prime_upload_test.go
  pkg/services/move_history/move_history_fetcher_test.go
  pkg/services/payment_request/payment_request_fetcher_test.go
  pkg/services/payment_request/payment_request_recalculator_test.go
  pkg/services/payment_request/payment_request_shipment_recalculate_test.go
  pkg/testdatagen/make_proof_of_service_doc.go
  pkg/testdatagen/scenario/e2ebasic.go
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/testharness/make_move.go
  pkg/uploader/prime_uploader_test.go
Labels: ready-to-merge, spark

#10567 MB-15855 cleanup build ppm shipment usage
  pkg/factory/ppm_shipment_factory.go
  pkg/handlers/internalapi/moving_expense_test.go
  pkg/handlers/internalapi/progear_weight_ticket_test.go
  pkg/handlers/internalapi/weight_ticket_test.go
  pkg/services/invoice/ghc_payment_request_invoice_generator_test.go
  pkg/services/order/order_fetcher_test.go
  pkg/services/ppmshipment/ppm_shipment_creator_test.go
  pkg/testdatagen/make_evaluation_report.go
  pkg/testdatagen/make_move.go
  pkg/testdatagen/make_mto_agent.go
  pkg/testdatagen/make_mto_service_item.go
  pkg/testdatagen/make_mto_shipment.go
  pkg/testdatagen/make_payment_request.go
  pkg/testdatagen/make_personally_procured_move.go
  pkg/testdatagen/make_ppm_shipment.go
  pkg/testdatagen/make_reweigh.go
  pkg/testdatagen/make_signed_certification.go
  pkg/testdatagen/make_sit_duration_update.go
  pkg/testdatagen/scenario/e2ebasic.go
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/shared.go
  pkg/testdatagen/testharness/make_move.go
Labels: ready-to-merge

#10564 Update PR Template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ready-to-merge
