Repository transcom/mymove, pull requests merged in 2023-07, with the labels that each got.

#10984 [MB-16449] Fix the Total Segment Count displayed in the SE segment
  pkg/edi/invoice/generator.go
  pkg/services/invoice/ghc_payment_request_invoice_generator.go
  pkg/services/invoice/ghc_payment_request_invoice_generator_test.go
Labels: ready-to-merge

#10989 [ MB-16408 ] Updating comment
  pkg/services/move_task_order/move_task_order_fetcher.go
Labels: enhancement, Pamplemoose, ready-to-merge

#10931 [MB-16358] Service for shipment destination address change requests
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/mto_shipment/create_non_s_i_t_address_update_request.go
  pkg/gen/primeclient/mto_shipment/mto_shipment_client.go
  pkg/gen/primemessages/create_non_s_i_t_address_update_request.go
  pkg/handlers/primeapi/mto_shipment_test.go
  pkg/handlers/primeapi/payloads/payload_to_model.go
  pkg/services/shipment_address_update/shipment_address_update_requester.go
  pkg/services/shipment_address_update/shipment_address_update_requester_test.go
  pkg/services/shipment_address_update/shipment_address_update_service_test.go
  swagger-def/prime.yaml
  swagger/prime.yaml
Labels: ttv, ready-to-merge

#10918 MB-16296-service-area-dest-uses-final-destination
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20230614233341_add_SITServiceAreaDest_param_key.up.sql
  migrations/app/schema/20230614233641_add_SITServiceAreaDest_param_for_DDDSIT_service_item.up.sql
  migrations/app/schema/20230623204052_delete_ServiceAreaDest_param_for_DDDSIT_service_item.up.sql
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/service_item_param_name.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/service_item_param_name.go
  pkg/models/service_item_param_key.go
  pkg/payment_request/service_param_value_lookups/service_param_value_lookups.go
  pkg/services/ghcrateengine/domestic_destination_sit_delivery_pricer.go
  pkg/services/ghcrateengine/domestic_destination_sit_delivery_pricer_test.go
  src/components/Office/ServiceItemCalculations/helpers.js
  src/components/Office/ServiceItemCalculations/serviceItemTestParams.js
  src/constants/serviceItems.js
  swagger-def/definitions/ServiceItemParamName.yaml
  swagger/ghc.yaml
  swagger/prime.yaml
Labels: Huckleberry

#10945 [ MB-15891 ] Validate postal code on change in residential address form
  src/components/Customer/BackupAddressForm/BackupAddressForm.jsx
  src/components/Customer/ResidentialAddressForm/ResidentialAddressForm.jsx
  src/components/Customer/ResidentialAddressForm/ResidentialAddressForm.test.jsx
  src/components/form/AddressFields/AddressFields.jsx
  src/components/form/AddressFields/AddressFields.test.jsx
  src/pages/MyMove/Profile/ResidentialAddress.jsx
Labels: ready-to-merge, Huckleberry

#10991 storybook updates
  .storybook/main.js
  package.json
  yarn.lock
Labels: dependencies

#10992 [ MB-16350, MB-16395 ] Adding DOSFSC and DDSFSC test data
  pkg/factory/mto_service_item_factory.go
Labels: Pamplemoose

#11012 [ MB-16350 ] Adding payment request DOSFSC DDSFSC to testharness
  pkg/testdatagen/testharness/make_move.go
  playwright/tests/office/txo/tooFlows.spec.js
Labels: Pamplemoose, wip

#11018 [ MB-16408 ] Show correct remarks from Office
  pkg/handlers/primeapi/payloads/model_to_payload.go
  pkg/handlers/primeapi/payloads/model_to_payload_test.go
Labels: Pamplemoose, ready-to-merge, bug

#11021 [ MB-16350 ] DOSFSC and DDSFSC move with unapproved SIT service items
  pkg/testdatagen/testharness/make_move.go
Labels: Pamplemoose

#11022 [ MB-16350 ] DOSFSC and DDSFSC move with approved SIT service items
  pkg/testdatagen/testharness/make_move.go
Labels: Pamplemoose, ready-to-merge

#11024 [GHC] :bug: Fix Null GBLOC in Support API
  pkg/services/support/move_task_order/move_task_order_creator.go
Labels: ready-to-merge

#11034 [ MB-5055 ] soft deletion of mto agents
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/m_t_o_agent.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/m_t_o_agent.go
  pkg/handlers/ghcapi/mto_shipment.go
  pkg/handlers/primeapi/mto_shipment.go
  pkg/models/move.go
  pkg/services/mto_agent/mto_agent_creator.go
  pkg/services/mto_shipment/mto_shipment_creator.go
  pkg/services/mto_shipment/mto_shipment_creator_test.go
  pkg/services/mto_shipment/mto_shipment_fetcher.go
  pkg/services/mto_shipment/mto_shipment_updater.go
  pkg/services/mto_shipment/mto_shipment_updater_test.go
  src/components/Customer/MtoShipmentForm/MtoShipmentForm.test.jsx
  src/utils/formatMtoShipment.js
  swagger-def/definitions/MTOAgent.yaml
  swagger-def/internal.yaml
  swagger/ghc.yaml
  swagger/internal.yaml
Labels: ready-to-merge, Huckleberry

#11035 [MB-16405] Preview and Post MTO Modal Display Domestic Linehaul on TOO Approval Bug
  src/components/Office/ShipmentApprovalPreview/ShipmentApprovalPreview.jsx
  src/components/Office/ShipmentApprovalPreview/ShipmentApprovalPreview.test.jsx
  src/components/Office/ShipmentApprovalPreview/shipmentApprovalPreview.stories.jsx
  src/components/Office/ShipmentServiceItemsTable/ShipmentServiceItemsTable.jsx
  src/components/Office/ShipmentServiceItemsTable/ShipmentServiceItemsTable.test.jsx
  src/components/Office/ShipmentServiceItemsTable/shipmentServiceItemsTable.stories.jsx
Labels: A-Team, ready-to-merge

#11033 MB-16343 add fsc to sit service item bundles
  pkg/factory/re_service_factory.go
  pkg/factory/re_service_factory_test.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/mto_service_item/create_m_t_o_service_item.go
  pkg/gen/primeclient/mto_service_item/mto_service_item_client.go
  pkg/handlers/ghcapi/mto_service_items.go
  pkg/handlers/primeapi/payloads/model_to_payload.go
  pkg/handlers/primeapi/payloads/payload_to_model.go
  pkg/handlers/supportapi/internal/payloads/model_to_payload.go
  pkg/models/mto_service_items.go
  pkg/payment_request/service_param_value_lookups/service_param_value_lookups.go
  pkg/services/move_task_order/move_task_order_fetcher.go
  pkg/services/mto_service_item/mto_service_item_creator.go
  pkg/services/mto_service_item/mto_service_item_creator_test.go
  pkg/testdatagen/scenario/shared.go
  swagger-def/prime.yaml
  swagger/prime.yaml
Labels: Pamplemoose, ready-to-merge

#11049 MB-16351 add sit fsc details on TOO view
  src/components/Office/ServiceItemDetails/ServiceItemDetails.jsx
Labels: Pamplemoose, ready-to-merge

#11052 Add logging to service member handler.
  pkg/handlers/internalapi/service_members.go
Labels: ready-to-merge

#10982 MB-16266 Add address change details to TOO response data
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/m_t_o_shipment.go
  pkg/gen/ghcmessages/shipment_address_update.go
  pkg/gen/ghcmessages/shipment_address_update_status.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/services/mto_shipment/mto_shipment_fetcher.go
  pkg/services/mto_shipment/mto_shipment_fetcher_test.go
  swagger-def/definitions/MTOShipment.yaml
  swagger/ghc.yaml
Labels: ttv, ready-to-merge

#11044 MB-16395 - Create sit bundles
  pkg/factory/mto_service_item_factory.go
  pkg/factory/mto_service_item_factory_test.go
  pkg/services/payment_request/payment_request_creator_test.go
  pkg/services/payment_request/payment_request_recalculator_test.go
  pkg/testdatagen/testharness/dispatch.go
  pkg/testdatagen/testharness/make_move.go
  playwright/tests/office/txo/sitUpdates.spec.js
  playwright/tests/utils/testharness.js
Labels: Pamplemoose

#11058 MB-16353 - Add sit fuel surcharge to payment request test data
  pkg/testdatagen/testharness/make_move.go
Labels: Pamplemoose, ready-to-merge

#10966 MB-16181: Add authz checks for the create mtoShipment endpoint
  pkg/handlers/internalapi/mto_shipment_test.go
  pkg/services/mto_shipment/mto_shipment_creator.go
  pkg/services/mto_shipment/mto_shipment_creator_test.go
Labels: A-Team

#11042 MB-16469: Add shared definitions
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/payment_service_item_param.go
  swagger-def/definitions/PaymentRequestStatus.yaml
  swagger-def/definitions/PaymentServiceItemParam.yaml
  swagger-def/definitions/PaymentServiceItemParams.yaml
  swagger-def/definitions/PaymentServiceItemStatus.yaml
  swagger-def/definitions/prime/Customer.yaml
  swagger-def/definitions/prime/DutyLocation.yaml
  swagger-def/definitions/prime/Entitlements.yaml
  swagger-def/definitions/prime/MTOAgent.yaml
  swagger-def/definitions/prime/MTOAgentType.yaml
  swagger-def/definitions/prime/MTOAgents.yaml
  swagger-def/definitions/prime/MTOServiceItem.yaml
  swagger-def/definitions/prime/MTOServiceItemBasic.yaml
  swagger-def/definitions/prime/MTOServiceItemDestSIT.yaml
  swagger-def/definitions/prime/MTOServiceItemDimension.yaml
  swagger-def/definitions/prime/MTOServiceItemDomesticCrating.yaml
  swagger-def/definitions/prime/MTOServiceItemModelType.yaml
  swagger-def/definitions/prime/MTOServiceItemOriginSIT.yaml
  swagger-def/definitions/prime/MTOServiceItemShuttle.yaml
  swagger-def/definitions/prime/MTOServiceItemStatus.yaml
  swagger-def/definitions/prime/MTOShipmentType.yaml
  swagger-def/definitions/prime/MTOShipmentWithoutServiceItems.yaml
  swagger-def/definitions/prime/MTOShipmentsWithoutServiceObjects.yaml
  swagger-def/definitions/prime/MoveTaskOrder.yaml
  swagger-def/definitions/prime/Order.yaml
  swagger-def/definitions/prime/PPMShipment.yaml
  swagger-def/definitions/prime/PaymentRequest.yaml
  swagger-def/definitions/prime/PaymentRequests.yaml
  swagger-def/definitions/prime/PaymentServiceItem.yaml
  swagger-def/definitions/prime/PaymentServiceItems.yaml
  swagger-def/definitions/prime/ProofOfServiceDoc.yaml
  swagger-def/definitions/prime/ProofOfServiceDocs.yaml
  swagger-def/definitions/prime/Reweigh.yaml
  swagger-def/definitions/prime/ReweighRequester.yaml
  swagger-def/definitions/prime/ServiceRequestDocument.yaml
  swagger-def/definitions/prime/ServiceRequestDocuments.yaml
  swagger-def/definitions/prime/SitAddressUpdate.yaml
  swagger-def/definitions/prime/SitAddressUpdateStatus.yaml
  swagger-def/definitions/prime/SitAddressUpdates.yaml
  swagger-def/ghc.yaml
  swagger-def/prime.yaml
  swagger-def/support.yaml
  swagger/ghc.yaml
  swagger/prime.yaml
  swagger/support.yaml
Labels: ready-to-merge, Huckleberry

#11043 [ MB-14242, MB-16543 ] Update office shipment form to display destination type if dest address is unknown
  playwright/tests/office/servicescounseling/servicesCounselingFlows.spec.js
  playwright/tests/office/txo/tooFlowsNTSR.spec.js
  src/components/Office/ShipmentForm/ShipmentForm.jsx
  src/components/Office/ShipmentForm/ShipmentForm.test.jsx
  src/pages/Office/EditShipmentDetails/EditShipmentDetails.jsx
  src/pages/Office/ServicesCounselingEditShipmentDetails/ServicesCounselingEditShipmentDetails.jsx
Labels: ready-to-merge, Huckleberry

#11023 [MB-16267] Show destination address change request alerts to TOO
  pkg/testdatagen/testharness/dispatch.go
  pkg/testdatagen/testharness/make_move.go
  src/components/LeftNav/LeftNav.stories.jsx
  src/components/Office/DefinitionLists/ShipmentInfoList.jsx
  src/components/Office/DefinitionLists/ShipmentInfoList.stories.jsx
  src/components/Office/DefinitionLists/ShipmentInfoList.test.jsx
  src/components/Office/RequestedShipments/ApprovedRequestedShipments.jsx
  src/components/Office/RequestedShipments/ApprovedRequestedShipments.stories.jsx
  src/components/Office/TXOTabNav/TXOTabNav.jsx
  src/components/Office/TXOTabNav/TXOTabNav.test.jsx
  src/constants/shipments.js
  src/pages/Office/MoveDetails/MoveDetails.jsx
  src/pages/Office/MoveDetails/MoveDetails.test.jsx
  src/pages/Office/TXOMoveInfo/TXOMoveInfo.jsx
  src/utils/displayFlags.js
Labels: ttv, ready-to-merge

#11068 MB-16478 - Fix brittle service item tests
  playwright/tests/office/txo/tooFlows.spec.js
Labels: Pamplemoose

#11020 create a new endpoint for review address update
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/ghcapi/ghcoperations/shipment/review_shipment_address_update.go
  pkg/gen/ghcapi/ghcoperations/shipment/review_shipment_address_update_parameters.go
  pkg/gen/ghcapi/ghcoperations/shipment/review_shipment_address_update_responses.go
  pkg/gen/ghcapi/ghcoperations/shipment/review_shipment_address_update_urlbuilder.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/mto_shipment.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/services/mocks/ShipmentAddressUpdateRequester.go
  pkg/services/move/move_router.go
  pkg/services/shipment_address_update.go
  pkg/services/shipment_address_update/shipment_address_update_requester.go
  pkg/services/shipment_address_update/shipment_address_update_requester_test.go
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: ttv

#11080 MB-16422 create DDSFSC pricer
  pkg/factory/mto_service_item_factory.go
  pkg/payment_request/service_param_value_lookups/weight_billed_lookup.go
  pkg/services/ghc_rate_engine.go
  pkg/services/ghcrateengine/domestic_destination_sit_fuel_surcharge_pricer.go
  pkg/services/ghcrateengine/domestic_destination_sit_fuel_surcharge_pricer_test.go
  pkg/services/ghcrateengine/service_item_pricer.go
  pkg/services/mocks/DomesticDestinationSITFuelSurchargePricer.go
  pkg/services/mto_service_item/mto_service_item_updater.go
  pkg/services/mto_service_item/mto_service_item_updater_test.go
  pkg/testdatagen/scenario/shared.go
Labels: Pamplemoose, ready-to-merge

#11053 Use asdf for node
  .github/workflows/analyze-bundle.yml
  .github/workflows/front-end-linter.yml
  .github/workflows/happo-tests-main.yml
  .github/workflows/happo-tests.yml
  .tool-versions
  Brewfile.local
  Makefile
  fresh-brew.local
  scripts/check-go-version
  scripts/check-node-version
Labels: ready-to-merge

#11050 MB-16500: switch to chi routing, set up per host routing, use chi middleware for opentelemetry
  cmd/milmove/serve.go
  go.mod
  go.sum
  pkg/auth/cookie.go
  pkg/auth/cookie_test.go
  pkg/auth/hostname_detector.go
  pkg/auth/hostname_detector_test.go
  pkg/handlers/authentication/auth_test.go
  pkg/handlers/routing/adminapi_test/swagger_test.go
  pkg/handlers/routing/base_routing_suite.go
  pkg/handlers/routing/ghcapi_test/customer_test.go
  pkg/handlers/routing/ghcapi_test/swagger_test.go
  pkg/handlers/routing/internalapi_test/moves_test.go
  pkg/handlers/routing/internalapi_test/swagger_test.go
  pkg/handlers/routing/primeapi_test/move_task_orders_test.go
  pkg/handlers/routing/primeapi_test/moves_test.go
  pkg/handlers/routing/primeapi_test/swagger_test.go
  pkg/handlers/routing/routing_init.go
  pkg/handlers/routing/routing_init_test.go
  pkg/handlers/routing/supportapi_test/supportapi_test.go
  pkg/handlers/routing/supportapi_test/swagger_test.go
  pkg/handlers/routing/supportapi_test/testharness_test.go
  pkg/handlers/spa_handler.go
  pkg/handlers/testharnessapi/api.go
  pkg/handlers/testharnessapi/api_test.go
  pkg/middleware/no_cache.go
  pkg/middleware/no_cache_test.go
  pkg/middleware/valid_methods_static.go
  pkg/middleware/valid_methods_static_test.go
  pkg/storage/filesystem.go
  pkg/telemetry/init.go
  pkg/telemetry/middleware.go
  pkg/telemetry/request.go
  scripts/copy-swagger-ui
Labels: ready-to-merge

#11084 storybook 7.1.0 update
  package.json
  yarn.lock
Labels: dependencies, ready-to-merge

#11103 Fix review app deployment
  Dockerfile.reviewapp
Labels: ready-to-merge

#11093 MB-16581 Display additional information on customer home page
  src/pages/MyMove/Home/HomeHelpers.jsx
Labels: ttv, ready-to-merge

#11116 [ MB-16422 ] Updating test function names to include SIT
  pkg/services/ghcrateengine/domestic_destination_sit_fuel_surcharge_pricer_test.go
Labels: Pamplemoose, ready-to-merge

#11079 [MB-10466] Same Service Items are being requested for payment-Prime bug
  pkg/services/payment_request/payment_request_creator.go
  pkg/services/payment_request/payment_request_creator_test.go
  pkg/services/payment_request/rules.go
  pkg/services/payment_request/rules_test.go
Labels: A-Team, ready-to-merge

#11087 [MB-16355] adding origin and destination fsc
  pkg/testdatagen/scenario/shared.go
  src/components/Office/ServiceItemCalculations/helpers.js
  src/components/Office/ServiceItemCalculations/helpers.test.js
  src/components/Office/ServiceItemCalculations/serviceItemTestParams.js
  src/constants/serviceItems.js
Labels: Pamplemoose, ready-to-merge

#11110 [ MB-16421 ] Adding DOSFSC pricer
  pkg/factory/mto_service_item_factory.go
  pkg/payment_request/service_param_value_lookups/weight_billed_lookup.go
  pkg/services/ghc_rate_engine.go
  pkg/services/ghcrateengine/domestic_origin_sit_fuel_surcharge_pricer.go
  pkg/services/ghcrateengine/domestic_origin_sit_fuel_surcharge_pricer_test.go
  pkg/services/ghcrateengine/service_item_pricer.go
  pkg/services/mocks/DomesticOriginSITFuelSurchargePricer.go
  pkg/services/mto_service_item/mto_service_item_updater.go
  pkg/testdatagen/scenario/shared.go
Labels: Pamplemoose, ready-to-merge

#11118 MB-16569 - Update golang to 1.20.6
  .circleci/config.yml
  .github/workflows/go-auto-approve.yml
  .go-version
  .tool-versions
  Dockerfile.local
  Dockerfile.migrations_local
  Dockerfile.reviewapp
  Dockerfile.tasks_local
  Dockerfile.tools_local
  Dockerfile.webhook_client
  Dockerfile.webhook_client_dp3
  Dockerfile.webhook_client_local
  Makefile
  nix/default.nix
Labels: Pamplemoose, dependencies, do not merge

#11091 MB-16448 update language in customer onboarding screens
  playwright/tests/my/mymove/nts.spec.js
  src/components/Customer/BackupContactForm/index.jsx
  src/components/Customer/Home/Contact/index.jsx
  src/components/Customer/MtoShipmentForm/MtoShipmentForm.jsx
  src/components/Customer/PPM/Booking/Advance/AdvanceForm.jsx
  src/components/Customer/PPM/Booking/EstimatedIncentiveDetails/EstimatedIncentiveDetails.jsx
  src/components/Customer/PPM/Booking/EstimatedIncentiveDetails/EstimatedIncentiveDetails.test.jsx
  src/components/Customer/PPM/Booking/EstimatedWeightsProGearForm/EstimatedWeightsProGearForm.jsx
  src/components/Customer/SubmitMoveForm/SubmitMoveForm.jsx
  src/components/Customer/SubmitMoveForm/SubmitMoveForm.test.jsx
  src/components/form/BackupContactInfoFields/BackupContactInfoFields.stories.jsx
  src/pages/MyMove/Agreement.test.jsx
  src/pages/MyMove/Home/HomeHelpers.jsx
  src/pages/MyMove/Home/index.jsx
  src/pages/MyMove/MovingInfo.jsx
  src/pages/MyMove/Profile/Profile.jsx
  src/pages/MyMove/Profile/Profile.test.jsx
  src/pages/MyMove/Review/Review.jsx
  src/pages/MyMove/SelectShipmentType.jsx
  src/pages/MyMove/SelectShipmentType.test.jsx
Labels: ttv

#11060 [ MB-16480 ] Update error page contact information
  src/shared/SomethingWentWrong/index.jsx
Labels: enhancement, Pamplemoose, ready-to-merge

#11099 [MB-16382] Adds an authz check when creating a pro gear weight ticket
  pkg/handlers/internalapi/progear_weight_ticket.go
  pkg/handlers/internalapi/progear_weight_ticket_test.go
  pkg/handlers/routing/internalapi_test/progear_weight_tickets_test.go
  pkg/services/progear_weight_ticket/progear_weight_ticket_creator.go
  pkg/services/progear_weight_ticket/progear_weight_ticket_creator_test.go
Labels: A-Team

#11124 [MB-16480] Adding unit tests for error page
  src/shared/SomethingWentWrong/index.jsx
  src/shared/SomethingWentWrong/index.test.js
Labels: enhancement, Pamplemoose, ready-to-merge

#11113 MB-16063: request count and local otel update
  .circleci/config.yml
  cmd/ecs-deploy/task_def.go
  cmd/milmove/serve.go
  config/telemetry/collector-config.dev.yaml
  config/telemetry/grafana.ini
  config/telemetry/otelcol-config-extras.yml
  config/telemetry/otelcol-config.yml
  config/telemetry/otelcol-observability.yml
  config/telemetry/prometheus-config.yaml
  config/telemetry/provisioning/dashboards/general.yaml
  config/telemetry/provisioning/dashboards/general/Opentelemetry Collector Data Flow.json
  config/telemetry/provisioning/dashboards/general/demo-dashboard.json
  config/telemetry/provisioning/dashboards/general/opentelemetry-collector.json
  config/telemetry/provisioning/dashboards/general/spanmetrics-dashboard.json
  config/telemetry/provisioning/datasources/default.yaml
  config/telemetry/provisioning/datasources/jaeger.yaml
  docker-compose.telemetry.yml
  pkg/cli/dbconn.go
  pkg/handlers/authentication/client_cert.go
  pkg/handlers/routing/base_routing_suite.go
  pkg/handlers/routing/primeapi_test/telemetry_test.go
  pkg/handlers/routing/routing_init.go
  pkg/middleware/openapi.go
  pkg/middleware/request_logger.go
  pkg/middleware/trace.go
  pkg/middleware/trace_test.go
  pkg/telemetry/context.go
  pkg/telemetry/db_test.go
  pkg/telemetry/init.go
  pkg/telemetry/init_test.go
  pkg/telemetry/metrictest/memory.go
  pkg/telemetry/middleware.go
  pkg/telemetry/middleware_test.go
  pkg/telemetry/milmove_data.go
  pkg/telemetry/milmove_data_test.go
  pkg/telemetry/request.go
  pkg/telemetry/request_test.go
Labels: ready-to-merge

#11102 MB-16477: Update Initial SIT delivery address shown in edit service item modal
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
Labels: Pamplemoose, ready-to-merge
