Repository transcom/mymove, pull requests merged in 2023-01, with the labels that each got.

#9736 MB-14700: Cypress test + increase readability of Final Incentive
  cypress/integration/milmove/ppms/entireShipmentCloseout.js
  cypress/support/ppmCustomerShared.js
  pkg/services/ppmshipment/ppm_estimator.go
  pkg/services/ppmshipment/ppm_estimator_test.go
  pkg/services/ppmshipment/validation.go
  pkg/services/weight_ticket/weight_ticket_updater.go
  pkg/testdatagen/scenario/shared.go
Labels: A-Team, ready-to-merge

#9673 MB-14575 Remove the acceptance_test job from the config.yml and the makefile
  .circleci/config.yml
  Makefile
Labels: ready-to-merge

#9817 [MB-14747] [MB-14709] Update customer and office move APIs to save ppm closeout location
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/move/update_closeout_office.go
  pkg/gen/ghcapi/ghcoperations/move/update_closeout_office_parameters.go
  pkg/gen/ghcapi/ghcoperations/move/update_closeout_office_responses.go
  pkg/gen/ghcapi/ghcoperations/move/update_closeout_office_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/ghcmessages/move.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalapi/internaloperations/moves/patch_move_parameters.go
  pkg/gen/internalapi/internaloperations/moves/patch_move_responses.go
  pkg/gen/internalmessages/move_payload.go
  pkg/gen/internalmessages/patch_move_payload.go
  pkg/handlers/authentication/permissions.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/move.go
  pkg/handlers/ghcapi/move_test.go
  pkg/handlers/internalapi/api.go
  pkg/handlers/internalapi/moves.go
  pkg/handlers/internalapi/moves_test.go
  pkg/services/mocks/TransportationOfficesFetcher.go
  pkg/services/move.go
  pkg/services/move/closeout_office_updater.go
  pkg/services/move/move_fetcher.go
  pkg/services/transportation_office.go
  pkg/services/transportation_office/transportation_office_fetcher.go
  src/services/ghcApi.js
  swagger-def/ghc.yaml
  swagger-def/internal.yaml
  swagger/ghc.yaml
  swagger/internal.yaml
Labels: ttv

#9795 MB-13828-progear-office-handler-complete-NT
  pkg/handlers/ghcapi/progear_weight_ticket.go
  pkg/handlers/ghcapi/progear_weight_ticket_test.go
Labels: A-Team

#9774 Updated Go dependencies that don't have formal releases
  go.mod
  go.sum
Labels: dependencies, ttv, ready-to-merge

#9827 MB-14738 Create Transportation Office Search Service Object
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20230104003529_transportation_offices_name_index.up.sql
  pkg/handlers/ghcapi/tranportation_offices.go
  pkg/handlers/ghcapi/transportation_offices_test.go
  pkg/handlers/internalapi/transportation_offices.go
  pkg/services/mocks/TransportationOfficesFetcher.go
  pkg/services/transportation_office.go
  pkg/services/transportation_office/transportation_office_fetcher.go
  pkg/services/transportation_office/transportation_office_fetcher_test.go
Labels: ttv

#9832 Deleted some old generated mock files
  pkg/services/mocks/EvaluationReportListFetcher.go
  pkg/services/mocks/ProgearCreator.go
  pkg/services/mocks/ProgearUpdater.go
Labels: ready-to-merge

#9797 MB-14785: Replace makeAddress calls with BuildAddress
  pkg/factory/shared.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/handlers/ghcapi/queues_test.go
  pkg/handlers/internalapi/moves_test.go
  pkg/handlers/internalapi/mto_shipment_test.go
  pkg/handlers/internalapi/orders_test.go
  pkg/handlers/primeapi/move_task_order_test.go
  pkg/handlers/primeapi/mto_service_item_test.go
  pkg/handlers/primeapi/mto_shipment_address_test.go
  pkg/handlers/primeapi/mto_shipment_test.go
  pkg/handlers/primeapi/payment_request_test.go
  pkg/models/distance_calculation_test.go
  pkg/models/service_member_test.go
  pkg/payment_request/service_param_value_lookups/distance_zip_lookup_test.go
  pkg/payment_request/service_param_value_lookups/distance_zip_sit_dest_lookup_test.go
  pkg/payment_request/service_param_value_lookups/distance_zip_sit_origin_lookup_test.go
  pkg/payment_request/service_param_value_lookups/service_area_lookup_test.go
  pkg/payment_request/service_param_value_lookups/service_param_value_lookups_test.go
  pkg/payment_request/service_param_value_lookups/services_schedule_lookup_test.go
  pkg/payment_request/service_param_value_lookups/sit_schedule_lookup_test.go
  pkg/payment_request/service_param_value_lookups/zip_sit_origin_hhg_actual_address_lookup_test.go
  pkg/payment_request/service_param_value_lookups/zip_sit_origin_hhg_original_address_lookup_test.go
  pkg/route/here_planner_test.go
  pkg/services/address/address_updater_test.go
  pkg/services/event/notification_test.go
  pkg/services/move_history/move_history_fetcher_test.go
  pkg/services/move_task_order/move_task_order_hide_non_fake_test.go
  pkg/services/move_task_order/move_task_order_updater_test.go
  pkg/services/mto_service_item/mto_service_item_creator_test.go
  pkg/services/mto_service_item/mto_service_item_updater_test.go
  pkg/services/mto_shipment/mto_shipment_address_updater_test.go
  pkg/services/mto_shipment/mto_shipment_fetcher_test.go
  pkg/services/mto_shipment/mto_shipment_updater_test.go
  pkg/services/mto_shipment/shipment_approver_test.go
  pkg/services/order/order_fetcher_test.go
  pkg/services/order/order_updater_test.go
  pkg/services/payment_request/payment_request_creator_test.go
  pkg/services/payment_request/payment_request_recalculator_test.go
  pkg/services/ppmshipment/ppm_shipment_updater_test.go
  pkg/testdatagen/scenario/e2ebasic.go
  pkg/testdatagen/scenario/shared.go
  pkg/testingsuite/pop_suite_test.go
Labels: ready-to-merge, spark

#9809 [MB-14368] add doc viewer to ppm review docs page
  .circleci/config.yml
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/ppm/get_weight_tickets.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/mto_shipment.go
  pkg/testdatagen/testdata/test.xls
  src/components/DocumentViewer/Content/ContentArea.stories.jsx
  src/components/DocumentViewer/DocumentViewer.test.jsx
  src/components/DocumentViewer/sample.xls
  src/constants/queryKeys.js
  src/hooks/queries.js
  src/pages/Office/PPM/ReviewDocuments/ReviewDocuments.jsx
  src/pages/Office/PPM/ReviewDocuments/ReviewDocuments.module.scss
  src/pages/Office/PPM/ReviewDocuments/ReviewDocuments.test.jsx
  src/services/ghcApi.js
  swagger-def/ghc.yaml
  swagger/ghc.yaml
  yarn.lock
Labels: A-Team

#9791 MB-14539 factory build transportation office
  pkg/factory/address_factory.go
  pkg/factory/admin_user_factory.go
  pkg/factory/entitlement_factory.go
  pkg/factory/office_phone_line_factory.go
  pkg/factory/office_phone_line_factory_test.go
  pkg/factory/shared.go
  pkg/factory/tariff_factory.go
  pkg/factory/transportation_office_factory.go
  pkg/factory/transportation_office_factory_test.go
  pkg/factory/user_factory.go
  pkg/handlers/adminapi/office_users_test.go
  pkg/handlers/adminapi/offices_test.go
  pkg/migrate/Exec_test.go
  pkg/services/office_user/office_user_creator_test.go
  pkg/services/office_user/office_user_updater_test.go
  pkg/services/order/order_fetcher_test.go
  pkg/services/query/query_builder_test.go
  pkg/testdatagen/scenario/shared.go
Labels: spark

#9864 [MB-14368] Fix typo to allow client to call endpoint
  src/services/ghcApi.js
Labels: ready-to-merge

#9805 MB-13827 update ghc expense update handler to fully handle updates
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/moving_expense.go
  pkg/handlers/ghcapi/moving_expense_test.go
  pkg/handlers/ghcapi/weight_ticket_test.go
  pkg/handlers/internalapi/api.go
  pkg/handlers/internalapi/moving_expense_test.go
  pkg/services/moving_expense/moving_expense_updater.go
  pkg/services/moving_expense/moving_expense_updater_test.go
  pkg/services/moving_expense/rules.go
  pkg/services/moving_expense/rules_test.go
  pkg/services/moving_expense/validation_test.go
  pkg/services/progear_weight_ticket/progear_weight_ticket_updater_test.go
  pkg/services/progear_weight_ticket/rules.go
  pkg/services/progear_weight_ticket/rules_test.go
  pkg/services/progear_weight_ticket/validation_test.go
  pkg/services/weight_ticket/rules.go
  pkg/services/weight_ticket/rules_test.go
  pkg/services/weight_ticket/weight_ticket_creator.go
  pkg/services/weight_ticket/weight_ticket_updater_test.go
  pkg/testdatagen/make_ppm_shipment.go
Labels: A-Team

#9865 [MB-14546] Service counselor defaults to correct queue based on GBLOC
  cypress/integration/office/homepage.js
  src/constants/routes.js
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.jsx
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.test.jsx
  src/pages/Office/index.jsx
Labels: ttv, ready-to-merge

#9824 [MB-14732] DutyLocationSearchBoxComponent refactor
  src/components/Customer/EditOrdersForm/EditOrdersForm.test.jsx
  src/components/Customer/OrdersInfoForm/OrdersInfoForm.test.jsx
  src/components/Customer/ServiceInfoForm/ServiceInfoForm.test.jsx
  src/components/LocationSearchBox/LocationSearchBox.jsx
  src/components/LocationSearchBox/LocationSearchBox.module.scss
  src/components/LocationSearchBox/LocationSearchBox.stories.jsx
  src/components/LocationSearchBox/LocationSearchBox.test.jsx
  src/components/LocationSearchBox/api.js
  src/components/LocationSearchBox/api.test.js
  src/components/form/fields/DutyLocationInput.jsx
  src/components/form/fields/DutyLocationInput.test.jsx
  src/pages/MyMove/Orders.test.jsx
  src/pages/MyMove/Profile/DutyLocation.css
  src/scenes/Office/OrdersPanel.jsx
  src/scenes/Office/OrdersViewerPanel.js
  src/scenes/Review/EditProfile.jsx
Labels: ttv

#9840 Mb 14733 customer can see closeout office on ppm shipment review card
  cypress/integration/milmove/ppms/review.js
  pkg/models/move.go
  pkg/testdatagen/scenario/shared.go
  src/components/Customer/Review/ShipmentCard/PPMShipmentCard/PPMShipmentCard.jsx
  src/components/Customer/Review/ShipmentCard/PPMShipmentCard/PPMShipmentCard.test.jsx
  src/components/Customer/Review/Summary/Summary.jsx
  src/types/customerShapes.js
  src/utils/shipmentDisplay.jsx
Labels: ttv, ready-to-merge

#9875 [MB-13528] fixing ppm routing
  cypress/integration/milmove/ppms/entireShipmentCloseout.js
  cypress/support/ppmCustomerShared.js
  src/pages/MyMove/PPM/Closeout/About/About.jsx
  src/pages/MyMove/PPM/Closeout/About/About.test.jsx
Labels: Pamplemoose, bug

#9852 MB-14842: Proof of Concept of playwright, running playwright in CI
  .circleci/config.yml
  .eslintrc.js
  .gitignore
  package.json
  pkg/appcontext-linter/appctx.go
  pkg/handlers/config.go
  pkg/handlers/routing/routing_init.go
  pkg/handlers/testharnessapi/api.go
  pkg/testdatagen/make_admin_user.go
  pkg/testdatagen/make_duty_location.go
  pkg/testdatagen/make_notification.go
  pkg/testdatagen/make_office_user.go
  pkg/testdatagen/scenario/e2ebasic.go
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/shared.go
  pkg/testdatagen/testharness/dispatch.go
  pkg/testdatagen/testharness/make_customer.go
  pkg/testdatagen/testharness/make_move.go
  pkg/testdatagen/testharness/make_office_user.go
  playwright.config.js
  playwright/tests/admin/adminUsers.spec.js
  playwright/tests/admin/homepage.spec.js
  playwright/tests/admin/moves.spec.js
  playwright/tests/admin/officeUsers.spec.js
  playwright/tests/admin/offices.spec.js
  playwright/tests/admin/users.spec.js
  playwright/tests/admin/webhookSubscriptions.spec.js
  playwright/tests/my/mymove/hhg.spec.js
  playwright/tests/my/mymove/nts.spec.js
  playwright/tests/my/mymove/ntsr.spec.js
  playwright/tests/my/mymove/onboarding.spec.js
  playwright/tests/my/mymove/orders.spec.js
  playwright/tests/my/static/staticHosting.spec.js
  playwright/tests/office/documentViewer.spec.js
  playwright/tests/office/homepage.spec.js
  playwright/tests/office/officeCSRFProtect.spec.js
  playwright/tests/office/primesimulator/primeSimulatorFlows.spec.js
  playwright/tests/utils/adminTest.js
  playwright/tests/utils/baseTest.js
  playwright/tests/utils/customerTest.js
  playwright/tests/utils/officeTest.js
  playwright/tests/utils/signIn.js
  playwright/tests/utils/testharness.js
  src/setupProxy.js
  testdata/src/appctx_linter_tests/testharness/main.go
  yarn.lock
Labels: ready-to-merge

#9843 [ MB-11857 ] Removing move management line item for ppm only moves
  pkg/models/move.go
  pkg/models/move_test.go
  pkg/services/move_task_order/move_task_order_updater.go
  pkg/testdatagen/scenario/e2ebasic.go
  src/components/Office/RequestedShipments/ApprovedRequestedShipments.jsx
  src/components/Office/RequestedShipments/ApprovedRequestedShipments.stories.jsx
  src/components/Office/RequestedShipments/RequestedShipments.test.jsx
  src/components/Office/RequestedShipments/RequestedShipmentsTestData.js
  src/components/Office/RequestedShipments/SubmittedRequestedShipments.jsx
  src/constants/serviceItems.js
  src/pages/Office/MoveDetails/MoveDetails.jsx
  src/utils/serviceItems.js
  src/utils/serviceItems.test.js
  src/utils/shipments.js
  src/utils/shipments.test.js
Labels: Pamplemoose

#9866 MB-11915 customer select closeout office
  cypress/integration/milmove/ppms/advances.js
  cypress/integration/milmove/ppms/entireShipmentOnboarding.js
  cypress/integration/milmove/ppms/estimatedIncentive.js
  cypress/integration/milmove/ppms/estimatedWeightsProgear.js
  cypress/integration/milmove/ppms/review.js
  cypress/support/ppmCustomerShared.js
  pkg/testdatagen/scenario/shared.go
  src/components/Customer/PPM/Booking/DateAndLocationForm/DateAndLocationForm.jsx
  src/components/Customer/PPM/Booking/DateAndLocationForm/DateAndLocationForm.test.jsx
  src/components/LocationSearchBox/LocationSearchBox.jsx
  src/components/form/fields/DutyLocationInput.jsx
  src/pages/MyMove/CreateOrEditMtoShipment.jsx
  src/pages/MyMove/PPM/Booking/DateAndLocation/DateAndLocation.jsx
  src/pages/MyMove/PPM/Booking/DateAndLocation/DateAndLocation.test.jsx
  src/services/internalApi.js
Labels: ttv

#9874 MB-14734 Add closeout office information to shipment card for SCs
  pkg/handlers/authentication/permissions.go
  pkg/testdatagen/scenario/shared.go
  src/components/Office/DefinitionLists/PPMShipmentInfoList.jsx
  src/components/Office/DefinitionLists/PPMShipmentInfoList.test.jsx
  src/components/Office/ShipmentDisplay/ShipmentDisplay.jsx
  src/constants/permissions.js
  src/hooks/queries.js
  src/hooks/queries.test.js
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.test.jsx
Labels: ttv

#9884 [MB-11916] services counselor can add and edit closeout office
  cypress/integration/office/ppms/addShipment.js
  cypress/integration/office/ppms/happyPathFlows.js
  src/components/Customer/EditOrdersForm/EditOrdersForm.test.jsx
  src/components/Customer/OrdersInfoForm/OrdersInfoForm.test.jsx
  src/components/Customer/ServiceInfoForm/ServiceInfoForm.test.jsx
  src/components/LocationSearchBox/LocationSearchBox.jsx
  src/components/LocationSearchBox/LocationSearchBox.module.scss
  src/components/Office/ShipmentForm/ShipmentForm.jsx
  src/components/Office/ShipmentForm/ShipmentForm.test.jsx
  src/components/Office/ShipmentForm/ppmShipmentSchema.js
  src/components/form/fields/CloseoutOfficeInput.jsx
  src/pages/Office/EditShipmentDetails/EditShipmentDetails.jsx
  src/pages/Office/ServicesCounselingAddShipment/ServicesCounselingAddShipment.jsx
  src/pages/Office/ServicesCounselingEditShipmentDetails/ServicesCounselingEditShipmentDetails.jsx
  src/pages/Office/ServicesCounselingEditShipmentDetails/ServicesCounselingEditShipmentDetails.test.jsx
  src/services/ghcApi.js
  src/types/transportationOffice.js
  src/utils/formatMtoShipment.js
Labels: ttv

#9883 [MB-14608] Storybook: Create a document set review panel
  src/components/Office/PPM/ReviewDocumentsSidePanel/ReviewDocumentsSidePanel.jsx
  src/components/Office/PPM/ReviewDocumentsSidePanel/ReviewDocumentsSidePanel.module.scss
  src/components/Office/PPM/ReviewDocumentsSidePanel/ReviewDocumentsSidePanel.stories.jsx
  src/constants/ppms.js
  src/hooks/queries.js
  src/pages/Office/PPM/ReviewDocuments/ReviewDocuments.jsx
  src/pages/Office/PPM/ReviewDocuments/ReviewDocuments.test.jsx
Labels: A-Team, ready-to-merge

#9924 MB-14936 Update Camp Lejeune (USMC) transportation office to no longer provide PPM Closeout
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20230120165432_update_camp_lejeune_closeout_value.up.sql
Labels: ttv

#9914 [ MB-13764, MB-15006, MB-14736 ] Updating the GEX URL in only Staging to test new GEX HTTPS connection
  .envrc
  cmd/milmove-tasks/process_edis.go
  config/env/demo.app-client-tls.env
  config/env/demo.app.env
  config/env/exp.app-client-tls.env
  config/env/exp.app.env
  config/env/exp.process-edis.env
  config/env/prd.app.env
  config/env/prd.post-file-to-gex.env
  config/env/prd.process-edis.env
  config/env/stg.app-client-tls.env
  config/env/stg.app.env
  config/env/stg.post-file-to-gex.env
  config/env/stg.process-edis.env
  pkg/cli/gex.go
  pkg/services/invoice/gex_sender_http.go
Labels: infra, help wanted

#9826 MB-14803 Uploader with extended params
  pkg/factory/shared.go
  pkg/factory/upload_factory.go
  pkg/factory/upload_factory_test.go
  pkg/handlers/primeapi/payloads/model_to_payload_test.go
  pkg/services/payment_request/payment_request_fetcher_test.go
  pkg/testdatagen/make_upload.go
Labels: ready-to-merge, spark

#9889 [MB-14913] Update nodejs to 16.19.0
  .circleci/config.yml
  .github/workflows/analyze-bundle.yml
  .github/workflows/front-end-linter.yml
  .github/workflows/happo-tests-master.yml
  .github/workflows/happo-tests.yml
  .node-version
  Dockerfile.local
  Dockerfile.migrations_local
  Dockerfile.reviewapp
  Dockerfile.tasks_local
  Dockerfile.tools_local
  Dockerfile.webhook_client
  Dockerfile.webhook_client_dp3
  Dockerfile.webhook_client_local
  Makefile
  cypress/Dockerfile.cypress
  nix/default.nix
  scripts/run-e2e-mtls-test-docker
  scripts/run-e2e-test-docker
Labels: dependencies, ttv, ready-to-merge

#9936 MB-15034 Replace deepcopy package
  go.mod
  go.sum
  pkg/services/mto_shipment/mto_shipment_updater.go
  pkg/services/ppmshipment/ppm_shipment_new_submitter.go
  pkg/services/ppmshipment/ppm_shipment_updated_submitter.go
Labels: spark

#9950 MB-15042-ppm-document-endpoint
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/ghcapi/ghcoperations/ppm/get_p_p_m_documents.go
  pkg/gen/ghcapi/ghcoperations/ppm/get_p_p_m_documents_parameters.go
  pkg/gen/ghcapi/ghcoperations/ppm/get_p_p_m_documents_responses.go
  pkg/gen/ghcapi/ghcoperations/ppm/get_p_p_m_documents_urlbuilder.go
  pkg/gen/ghcmessages/p_p_m_documents.go
  pkg/gen/ghcmessages/pro_gear_weight_tickets.go
  swagger-def/definitions/MovingExpenses.yaml
  swagger-def/definitions/PPMDocuments.yaml
  swagger-def/definitions/ProGearWeightTickets.yaml
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: A-Team

#9952 MB-15044 Rename the file for the GitHub Action Happo
  .github/workflows/happo-tests-main.yml
Labels: infra

#9963 MB-14342 Add tags to reviewed shipment cards for SC
  src/components/Office/ShipmentDisplay/ShipmentDisplay.jsx
  src/components/Office/ShipmentDisplay/ShipmentDisplay.module.scss
  src/components/Office/ShipmentDisplay/ShipmentDisplay.stories.jsx
  src/components/Office/ShipmentDisplay/ShipmentDisplay.test.jsx
Labels: A-Team
