Repository transcom/mymove, pull requests merged in 2023-09, with the labels that each got.

#11311 MB-15951: Add field to UI and office API
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/m_t_o_service_item.go
  pkg/gen/ghcmessages/s_i_t_status.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/services/mto_shipment.go
  pkg/services/mto_shipment/shipment_sit_status.go
  src/components/Office/ShipmentSITDisplay/ShipmentSITDisplay.jsx
  src/components/Office/ShipmentSITDisplay/ShipmentSITDisplay.stories.jsx
  src/components/Office/ShipmentSITDisplay/ShipmentSITDisplay.test.jsx
  src/components/Office/ShipmentSITDisplay/ShipmentSITDisplayTestParams.js
  src/shared/constants.js
  src/types/sitStatusShape.js
  swagger-def/definitions/MTOServiceItem.yaml
  swagger-def/definitions/SITStatus.yaml
  swagger/ghc.yaml
Labels: ready-to-merge, Huckleberry

#11324 [ MB-16671 ] Use sit origin hhg original address for origin sit service area payment
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20230829211437_add_origin_SIT_original_address_param_keys.up.sql
  migrations/app/schema/20230829211504_add_origin_SIT_original_address_params_for_origin_SIT_service_items.up.sql
  migrations/app/schema/20230829211555_delete_former_address_params_for_origin_SIT_service_items.up.sql
  pkg/factory/mto_service_item_factory.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/service_item_param_name.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/service_item_param_name.go
  pkg/gen/primev2api/embedded_spec.go
  pkg/gen/primev2messages/service_item_param_name.go
  pkg/models/service_item_param_key.go
  pkg/payment_request/service_param_value_lookups/service_param_value_lookups.go
  pkg/services/ghcrateengine/domestic_origin_additional_days_sit_pricer.go
  pkg/services/ghcrateengine/domestic_origin_additional_days_sit_pricer_test.go
  pkg/services/ghcrateengine/domestic_origin_first_day_sit_pricer.go
  pkg/services/ghcrateengine/domestic_origin_first_day_sit_pricer_test.go
  pkg/services/ghcrateengine/domestic_origin_sit_pickup_pricer.go
  pkg/services/ghcrateengine/domestic_origin_sit_pickup_pricer_test.go
  pkg/services/payment_request/payment_request_creator.go
  pkg/services/payment_request/payment_request_recalculator.go
  pkg/services/payment_request/payment_request_recalculator_test.go
  src/components/Office/ServiceItemCalculations/helpers.js
  src/components/Office/ServiceItemCalculations/helpers.test.js
  src/components/Office/ServiceItemCalculations/serviceItemTestParams.js
  src/constants/serviceItems.js
  swagger-def/definitions/ServiceItemParamName.yaml
  swagger/ghc.yaml
  swagger/prime.yaml
  swagger/prime_v2.yaml
Labels: ready-to-merge, Huckleberry

#11310 MB-16327 Duty location updates
  cmd/load-spreadsheet-data/duty_location_data.py
  cmd/load-spreadsheet-data/load-duty-locations.py
  cmd/load-spreadsheet-data/load-transportation-offices.py
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20230809180036_update_transportation_offices.up.sql
  migrations/app/schema/20230810180036_update_duty_locations.up.sql
  playwright/tests/office/txo/tooFlows.spec.js
Labels: A-Team

#11334 MB-16977 update documentation for creating DDASIT payment requests
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/payment_request/create_payment_request.go
  pkg/gen/primeclient/payment_request/payment_request_client.go
  swagger-def/prime.yaml
  swagger/prime.yaml
Labels: Pamplemoose, ready-to-merge

#11316 [MB-16989] Label/prefix service item dates
  pkg/factory/mto_service_item_factory.go
  src/components/Office/ServiceItemsTable/ServiceItemsTable.jsx
  src/components/Office/ServiceItemsTable/ServiceItemsTable.test.jsx
  src/utils/dates.js
  src/utils/dates.test.js
Labels: ttv

#11325 MB-17001 - Fix pricer operations order
  pkg/services/ghcrateengine/domestic_crating_pricer_test.go
  pkg/services/ghcrateengine/domestic_destination_additional_days_sit_pricer_test.go
  pkg/services/ghcrateengine/domestic_destination_first_day_sit_pricer_test.go
  pkg/services/ghcrateengine/domestic_destination_pricer.go
  pkg/services/ghcrateengine/domestic_destination_pricer_test.go
  pkg/services/ghcrateengine/domestic_destination_shuttling_pricer_test.go
  pkg/services/ghcrateengine/domestic_destination_sit_delivery_pricer_test.go
  pkg/services/ghcrateengine/domestic_linehaul_pricer.go
  pkg/services/ghcrateengine/domestic_linehaul_pricer_test.go
  pkg/services/ghcrateengine/domestic_nts_pack_pricer_test.go
  pkg/services/ghcrateengine/domestic_origin_additional_days_sit_pricer_test.go
  pkg/services/ghcrateengine/domestic_origin_first_day_sit_pricer_test.go
  pkg/services/ghcrateengine/domestic_origin_pricer.go
  pkg/services/ghcrateengine/domestic_origin_pricer_test.go
  pkg/services/ghcrateengine/domestic_origin_shuttling_pricer_test.go
  pkg/services/ghcrateengine/domestic_origin_sit_pickup_pricer_test.go
  pkg/services/ghcrateengine/domestic_pack_pricer_test.go
  pkg/services/ghcrateengine/domestic_shorthaul_pricer.go
  pkg/services/ghcrateengine/domestic_shorthaul_pricer_test.go
  pkg/services/ghcrateengine/domestic_uncrating_pricer_test.go
  pkg/services/ghcrateengine/domestic_unpack_pricer_test.go
  pkg/services/ghcrateengine/pricer_helpers.go
  pkg/services/ghcrateengine/pricer_helpers_test.go
  pkg/services/payment_request/payment_request_creator_test.go
  pkg/services/payment_request/payment_request_recalculator_test.go
  playwright/tests/my/milmove/ppms/entireShipmentCloseout.spec.js
  playwright/tests/office/ppms/addShipment.spec.js
  playwright/tests/office/ppms/happyPathFlows.spec.js
Labels: Pamplemoose, ready-to-merge

#11328 Expose EDI Error details for payment requests in the logs
  pkg/models/edi_errors.go
  pkg/services/invoice/process_edi824.go
Labels: ttv, ready-to-merge

#11354 Disable unused service worker registration
  src/index.jsx
  src/registerServiceWorker.js
Labels: ready-to-merge

#11339 NT-MB-10843-bug-fix-portrait-orientation
  src/pages/SignIn/SignIn.jsx
  src/pages/SignIn/SignIn.module.scss
  src/styles/_officeLayoutRules.scss
  src/styles/signinImports.scss
Labels: Huckleberry

#11370 Add logging to EDI 824 processing to reveal OTI acknowledgement code
  pkg/services/invoice/process_edi824.go
  pkg/services/invoice/process_edi824_test.go
Labels: ttv

#11356 [MB-16988 and MB-16987] Display SIT Entry on 1st day SIT and Departure Date on SIT destination delivery service items
  src/components/Office/RequestedServiceItemsTable/RequestedServiceItemsTable.stories.jsx
  src/components/Office/RequestedServiceItemsTable/RequestedServiceItemsTable.test.jsx
  src/components/Office/ServiceItemDetails/ServiceItemDetails.jsx
  src/components/Office/ServiceItemsTable/ServiceItemsTable.test.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
  src/shared/dates.js
Labels: ttv

#11368 Update flipt to same as deployed version: v1.26.1
  docker-compose.feature_flag.yml
Labels: ready-to-merge

#11359 Add the milmove_trace_id to client logs
  pkg/handlers/client_log_collector.go
  scripts/server-dev
  src/App/index.jsx
  src/index.jsx
  src/services/swaggerRequest.js
  src/shared/Swagger/request.js
  src/utils/milmoveLog.js
Labels: ready-to-merge

#11355 [MB-16990] Update RequestedServiceItemsTable stories
  src/components/Office/RequestedServiceItemsTable/RequestedServiceItemsTable.stories.jsx
  src/components/Office/RequestedServiceItemsTable/RequestedServiceItemsTable.test.jsx
  src/components/Office/ServiceItemDetails/ServiceItemDetails.jsx
  src/components/Office/ServiceItemsTable/ServiceItemsTable.test.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
  src/shared/dates.js
Labels: ready-to-merge

#11385 MB-16476: Add deprecated and error statuses to TIO queue
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/queues/get_payment_requests_queue_parameters.go
  src/constants/queues.js
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: ready-to-merge, Huckleberry

#11361 Try to fix GHA spurious notifications
  .github/workflows/analyze-bundle.yml
  .github/workflows/front-end-linter.yml
  .github/workflows/happo-tests-main.yml
  .github/workflows/happo-tests.yml
Labels: ready-to-merge

#11362 [ MB-16759 ] Removing the departure date validation check in the number days SIT for additional days SIT service items
  pkg/payment_request/service_param_value_lookups/number_days_sit_lookup.go
  pkg/payment_request/service_param_value_lookups/number_days_sit_lookup_test.go
Labels: ready-to-merge, Huckleberry

#11375 update-country-code-from-unitedstates-to-us
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20230911195043_update_addresses_table_column_country.up.sql
Labels: Huckleberry

#11384 [MB-16997] TIO needs clearer view of SIT start and end dates for payment request review
  src/components/Office/DaysInSITAllowance/DaysInSITAllowance.jsx
  src/components/Office/DaysInSITAllowance/DaysInSITAllowance.stories.jsx
  src/components/Office/DaysInSITAllowance/DaysInSITAllowance.test.jsx
Labels: Pamplemoose, ready-to-merge

#11405 Revert "update-country-code-from-unitedstates-to-us"
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20230911195043_update_addresses_table_column_country.up.sql
Labels: ready-to-merge

#11372 [ MB-16998 ] Data model updates for pending billed start date
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/shipment_payment_s_i_t_balance.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/services/payment_request.go
  pkg/services/payment_request/payment_request_shipments_sit_balance.go
  src/components/Office/DaysInSITAllowance/DaysInSITAllowance.jsx
  src/components/Office/DaysInSITAllowance/DaysInSITAllowance.stories.jsx
  src/components/Office/DaysInSITAllowance/DaysInSITAllowance.test.jsx
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: Pamplemoose

#11388 MB-17046 EDI testharness data function
  pkg/factory/line_of_accounting_factory.go
  pkg/factory/line_of_accounting_factory_test.go
  pkg/factory/transportation_accounting_code_factory.go
  pkg/models/line_of_accounting_test.go
  pkg/services/invoice/ghc_payment_request_invoice_generator_test.go
  pkg/testdatagen/testharness/dispatch.go
  pkg/testdatagen/testharness/make_move.go
Labels: ttv, ready-to-merge

#11418 Update logic for how button is rendered
  src/components/Office/PaymentRequestCard/PaymentRequestCard.jsx
Labels: ready-to-merge, Huckleberry

#11422 chore: :passport_control: Remove DB and Design codeowner locks
  .github/CODEOWNERS
Labels: ready-to-merge

#11424 E-04430-Okta-Profile-Edit
  .circleci/config.yml
  yarn.lock
Labels: needs-is3-review

#11369 MB-16978 EDI LOA for Coast Guard SMs should include 'HS' household goods code
  pkg/services/invoice/ghc_payment_request_invoice_generator.go
  pkg/services/invoice/ghc_payment_request_invoice_generator_test.go
  pkg/testdatagen/testharness/dispatch.go
  pkg/testdatagen/testharness/make_move.go
Labels: ttv, ready-to-merge

#11433 [MB-17008] Add left zero padding to LOA L1 segment values to meet 6 char validation
  pkg/services/invoice/ghc_payment_request_invoice_generator.go
  pkg/services/invoice/ghc_payment_request_invoice_generator_test.go
Labels: ready-to-merge

#11420 Update LOA A3 Mapping
  pkg/factory/line_of_accounting_factory.go
  pkg/services/invoice/ghc_payment_request_invoice_generator.go
  pkg/services/invoice/ghc_payment_request_invoice_generator_test.go
Labels: ready-to-merge

#11419 [MB-17026] An EDI 824 response with accepted status should not update the PR status to EDI Error
  pkg/services/invoice/process_edi824.go
  pkg/services/invoice/process_edi824_test.go
Labels: ttv, ready-to-merge

#11437 [MB-16789] reject service items when pricing type changes
  pkg/services/shipment_address_update/shipment_address_update_requester.go
  pkg/services/shipment_address_update/shipment_address_update_requester_test.go
Labels: ready-to-merge

#11464 MB-16790 Regenerate service items when address change updates pricing
  pkg/factory/mto_service_item_factory.go
  pkg/services/shipment_address_update/shipment_address_update_requester.go
  pkg/services/shipment_address_update/shipment_address_update_requester_test.go
Labels: ready-to-merge
