Repository transcom/mymove, pull requests merged in 2023-08, with the labels that each got.

#11098 [MB-16182] Auth added to update mto shipments endpoint
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalapi/internaloperations/mto_shipment/update_m_t_o_shipment.go
  pkg/handlers/internalapi/mto_shipment_test.go
  pkg/handlers/routing/internalapi_test/mto_shipments_test.go
  pkg/services/move/move_weights_test.go
  pkg/services/mto_shipment/mto_shipment_fetcher.go
  pkg/services/mto_shipment/mto_shipment_fetcher_test.go
  pkg/services/mto_shipment/mto_shipment_updater_test.go
  pkg/services/mto_shipment/shipment_approver_test.go
  pkg/services/mto_shipment/shipment_cancellation_requester_test.go
  pkg/services/mto_shipment/shipment_deleter_test.go
  pkg/services/mto_shipment/shipment_diversion_approver_test.go
  pkg/services/mto_shipment/shipment_diversion_requester_test.go
  pkg/services/mto_shipment/shipment_rejecter_test.go
  pkg/services/mto_shipment/shipment_reweigh_requester_test.go
  pkg/services/sit_extension/sit_extension_approver_test.go
  pkg/services/sit_extension/sit_extension_denier_test.go
  swagger-def/internal.yaml
  swagger/internal.yaml
Labels: A-Team, ready-to-merge

#11128 [MB-16384] Authz check for Moving Expense creation endpoint
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalapi/internaloperations/ppm/create_moving_expense_responses.go
  pkg/handlers/internalapi/moving_expense.go
  pkg/handlers/internalapi/moving_expense_test.go
  pkg/handlers/routing/internalapi_test/moving_expense_test.go
  pkg/services/moving_expense/moving_expense_creator.go
  pkg/services/moving_expense/moving_expense_creator_test.go
  swagger-def/internal.yaml
  swagger/internal.yaml
Labels: A-Team

#11129 MB-16575: Update logic for determining if retiree or separatee and add test
  src/components/Customer/MtoShipmentForm/MtoShipmentForm.jsx
  src/components/Customer/MtoShipmentForm/MtoShipmentForm.test.jsx
Labels: ready-to-merge, Huckleberry

#11125 MB-16570: Dependabot Updates
  package.json
  yarn.lock
Labels: Pamplemoose, ready-to-merge

#11101 MB-13922: show payment requests docs
  pkg/models/prime_upload.go
  pkg/services/payment_request/payment_request_list_fetcher.go
  src/pages/Office/ReviewBillableWeight/ReviewBillableWeight.jsx
  src/pages/Office/ReviewBillableWeight/ReviewBillableWeight.test.jsx
Labels: ready-to-merge, Huckleberry

#11086 [MB-13917] BUG: Redirect TIOs back to the payment request page from view orders and allowances view
  playwright/tests/office/txo/tioFlows.spec.js
  src/components/Office/PaymentRequestCard/PaymentRequestCard.jsx
  src/components/Office/PaymentRequestCard/PaymentRequestCard.test.jsx
  src/pages/Office/MoveAllowances/MoveAllowances.jsx
  src/pages/Office/Orders/Orders.jsx
Labels: ready-to-merge

#11134 MB-15211 - Update idle timer to better use inbuilt tools
  src/layout/LogoutOnInactivity.jsx
  src/layout/LogoutOnInactivity.test.jsx
Labels: Pamplemoose

#11154 [MB-13917] pass from value to View Orders link on view allowances page
  playwright/tests/office/txo/tioFlows.spec.js
  src/pages/Office/MoveAllowances/MoveAllowances.jsx
Labels: A-Team, ready-to-merge

#11111 [MB-16270] TOO destination address change review request modal
  pkg/factory/address_factory.go
  pkg/factory/shipment_address_update_factory.go
  pkg/factory/shipment_address_update_factory_test.go
  pkg/testdatagen/testharness/dispatch.go
  pkg/testdatagen/testharness/make_move.go
  src/components/Hint/Hint.stories.jsx
  src/components/Office/AddressUpdatePreview/AddressUpdatePreview.jsx
  src/components/Office/AddressUpdatePreview/AddressUpdatePreview.module.scss
  src/components/Office/AddressUpdatePreview/AddressUpdatePreview.stories.jsx
  src/components/Office/AddressUpdatePreview/AddressUpdatePreview.test.jsx
  src/components/Office/ShipmentAddressUpdateReviewRequestModal/ShipmentAddressUpdateReviewRequestModal.jsx
  src/components/Office/ShipmentAddressUpdateReviewRequestModal/ShipmentAddressUpdateReviewRequestModal.module.scss
  src/components/Office/ShipmentAddressUpdateReviewRequestModal/ShipmentAddressUpdateReviewRequestModal.stories.jsx
  src/components/Office/ShipmentAddressUpdateReviewRequestModal/ShipmentAddressUpdateReviewRequestModal.test.jsx
  src/components/Office/ShipmentForm/ShipmentForm.jsx
  src/types/index.js
  src/types/shipment.js
  src/utils/shipmentDisplay.jsx
  src/utils/shipmentDisplay.test.jsx
Labels: ttv

#11121 [MB-16289] FE: Display all uploaded documents during counseling
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/testharness/dispatch.go
  pkg/testdatagen/testharness/make_move.go
  playwright/tests/office/servicescounseling/servicesCounselingFlows.spec.js
  playwright/tests/utils/testharness.js
  src/pages/Office/ServicesCounselingMoveDocumentWrapper/ServicesCounselingMoveDocumentWrapper.jsx
  src/pages/Office/ServicesCounselingMoveDocumentWrapper/ServicesCounselingMoveDocumentWrapper.test.jsx
Labels: A-Team, ready-to-merge

#11115 [ MB-16172 ] Payment service item review should show same information as SIT Dashboard
  pkg/handlers/ghcapi/payment_request_test.go
  pkg/services/mto_shipment/shipment_sit_status.go
  pkg/services/payment_request/payment_request_shipments_sit_balance.go
  pkg/services/payment_request/payment_request_shipments_sit_balance_test.go
  src/components/Office/DaysInSITAllowance/DaysInSITAllowance.jsx
  src/utils/formatters.js
  src/utils/formatters.test.js
Labels: ready-to-merge, Huckleberry

#11172 MB-16448 corrections
  playwright/tests/utils/my/waitForCustomerPage.js
  src/content/shipments.js
  src/pages/MyMove/Home/HomeHelpers.jsx
  src/pages/MyMove/SelectShipmentType.jsx
Labels: ttv

#11181 MB-16581 content change
  src/pages/MyMove/Home/HomeHelpers.jsx
Labels: ttv, ready-to-merge

#11019 MB-16237: Convert to aws-sdk-go-v2
  cmd/ecs-deploy/put_target.go
  cmd/ecs-deploy/task_def.go
  cmd/ecs-deploy/task_def_test.go
  cmd/generate-payment-request-edi/main.go
  cmd/generate-shipment-summary/main.go
  cmd/generate-test-data/main.go
  cmd/ghc-pricing-parser/main.go
  cmd/ghc-transit-time-parser/main.go
  cmd/milmove-tasks/process_edis.go
  cmd/milmove-tasks/save_ghc_fuel_price_data.go
  cmd/milmove-tasks/send_payment_reminder_email.go
  cmd/milmove-tasks/send_post_move_survey_email.go
  cmd/milmove/gen_duty_stations_migration.go
  cmd/milmove/migrate.go
  cmd/milmove/serve.go
  cmd/model-vet/main.go
  cmd/webhook-client/main.go
  go.mod
  go.sum
  pkg/cli/aws.go
  pkg/cli/aws_test.go
  pkg/cli/dbconn.go
  pkg/cli/dbconn_test.go
  pkg/cli/email.go
  pkg/cli/storage.go
  pkg/iampostgres/iampostgres.go
  pkg/iampostgres/iampostgres_test.go
  pkg/iampostgres/rdsutilservice.go
  pkg/migrate/Builder.go
  pkg/migrate/ListFiles.go
  pkg/migrate/ListFiles_test.go
  pkg/notifications/notification_sender.go
  pkg/storage/s3.go
  pkg/storage/storage.go
Labels: dependencies, ready-to-merge

#11175 [MB-16540] Announcement + DangerJS check for future deprecated devseed scenario files
  Dockerfile.reviewapp
  Makefile
  dangerfile.ts
  docker-compose.mtls.yml
Labels: Pamplemoose, ready-to-merge

#11159 [MB-16271] TOO can approve or reject address change and add remarks
  src/components/Office/ShipmentAddressUpdateReviewRequestModal/ShipmentAddressUpdateReviewRequestModal.jsx
  src/components/Office/ShipmentAddressUpdateReviewRequestModal/ShipmentAddressUpdateReviewRequestModal.stories.jsx
  src/components/Office/ShipmentAddressUpdateReviewRequestModal/ShipmentAddressUpdateReviewRequestModal.test.jsx
  src/components/Office/ShipmentForm/ShipmentForm.jsx
  src/components/Office/ShipmentForm/ShipmentForm.module.scss
  src/components/Office/ShipmentForm/ShipmentForm.test.jsx
  src/services/ghcApi.js
  src/shared/Alert/index.css
  src/shared/Alert/index.jsx
  src/types/shipment.js
Labels: ttv

#11192 MB-16579 - Add selective dependency resolution for semver
  package.json
  yarn.lock
Labels: Pamplemoose, dependencies

#11174 MB-16587: update move submission email
  pkg/assets/notifications/templates/move_submitted_template.html
  pkg/assets/notifications/templates/move_submitted_template.txt
  pkg/notifications/move_submitted.go
  pkg/notifications/move_submitted_test.go
Labels: ready-to-merge, Huckleberry

#11197 [ MB-16540 ] Fixing the rendering of the Danger message around `devseed` Scenarios
  dangerfile.ts
Labels: Pamplemoose, ready-to-merge, bug

#11171 [MB-16383] authz check for update progear endpoint
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalapi/internaloperations/ppm/update_pro_gear_weight_ticket_responses.go
  pkg/handlers/internalapi/progear_weight_ticket.go
  pkg/handlers/internalapi/progear_weight_ticket_test.go
  pkg/handlers/routing/internalapi_test/progear_weight_tickets_test.go
  pkg/services/progear_weight_ticket/progear_weight_ticket_deleter_test.go
  pkg/services/progear_weight_ticket/progear_weight_ticket_updater.go
  pkg/services/progear_weight_ticket/progear_weight_ticket_updater_test.go
  swagger-def/internal.yaml
  swagger/internal.yaml
Labels: A-Team

#11186 MB 16329 playwright testing for too approving delivery address change for hhg
  playwright/tests/office/txo/tooFlows.spec.js
  playwright/tests/utils/testharness.js
Labels: ttv

#11187 [MB-15435] bug fix for tio review error
  pkg/testdatagen/scenario/shared.go
  src/components/Office/BillableWeight/BillableWeightCard/BillableWeightCard.jsx
  src/components/Office/BillableWeight/BillableWeightCard/BillableWeightCard.test.jsx
Labels: Pamplemoose, bug

#10898 MB-9411 Switch SFTP Connection to use private key refactor
  Makefile
  cmd/milmove-tasks/connect_to_gex_via_sftp.go
  pkg/cli/gex_sftp.go
  pkg/cli/gex_sftp_test.go
  pkg/handlers/supportapi/payment_request.go
  pkg/services/invoice/syncada_sftp_sender.go
  pkg/services/invoice/syncada_sftp_sender_test.go
Labels: ready-to-merge

#11184 MB-9411 Switch sftp connection to use private key
  Makefile
  pkg/cli/gex_sftp.go
  pkg/cli/gex_sftp_test.go
Labels: ready-to-merge

#11133 [MB-10466] REFINE Same Service Items are being requested for payment-Prime bug
  pkg/handlers/primeapi/move_task_order_test.go
  pkg/handlers/primeapiv2/move_task_order_test.go
  pkg/services/move_task_order/move_task_order_fetcher.go
  pkg/services/payment_request/payment_request_creator_test.go
  pkg/services/payment_request/payment_request_recalculator_test.go
  pkg/services/payment_request/rules.go
  pkg/services/payment_request/rules_test.go
  pkg/testdatagen/scenario/shared.go
Labels: A-Team, ready-to-merge

#11204 [ MB-15435 ] Generating UUIDs to avoid collisions
  pkg/testdatagen/scenario/shared.go
Labels: ready-to-merge, help wanted, bug

#11202 MB-9411 switch sftp connection to use private key logger refactor
  cmd/milmove-tasks/connect_to_gex_via_sftp.go
  cmd/milmove-tasks/process_edis.go
  pkg/cli/gex_sftp.go
  pkg/cli/logging.go
  pkg/handlers/supportapi/payment_request.go
  pkg/services/invoice/syncada_sftp_sender.go
Labels: ready-to-merge

#11205 MB-16592: Ensure adding shipment only shows retirement language when applicable
  playwright/tests/office/servicescounseling/servicesCounselingTestFixture.js
  src/pages/Office/ServicesCounselingAddShipment/ServicesCounselingAddShipment.jsx
Labels: ready-to-merge, Huckleberry

#11190 MB-16800: Add feature flags capability
  .air.toml
  Makefile
  cmd/milmove/serve.go
  config/env/demo.app-client-tls.env
  config/env/demo.app.env
  config/env/exp.app-client-tls.env
  config/env/exp.app.env
  config/env/loadtest.app-client-tls.env
  config/env/loadtest.app.env
  config/env/prd.app-client-tls.env
  config/env/prd.app.env
  config/env/review.app.env
  config/env/stg.app-client-tls.env
  config/env/stg.app.env
  config/flipt/config.yaml
  config/flipt/storage/development.features.yaml
  docker-compose.feature_flag.yml
  go.mod
  go.sum
  pkg/cli/feature_flag.go
  pkg/gen/internalapi/configure_mymove.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalapi/internaloperations/feature_flags/feature_flag_for_user.go
  pkg/gen/internalapi/internaloperations/feature_flags/feature_flag_for_user_parameters.go
  pkg/gen/internalapi/internaloperations/feature_flags/feature_flag_for_user_responses.go
  pkg/gen/internalapi/internaloperations/feature_flags/feature_flag_for_user_urlbuilder.go
  pkg/gen/internalapi/internaloperations/mymove_api.go
  pkg/gen/internalmessages/feature_flag.go
  pkg/handlers/apitests.go
  pkg/handlers/authentication/auth.go
  pkg/handlers/authentication/devlocal.go
  pkg/handlers/config.go
  pkg/handlers/health.go
  pkg/handlers/health_test.go
  pkg/handlers/internalapi/api.go
  pkg/handlers/internalapi/feature_flag.go
  pkg/handlers/internalapi/feature_flag_test.go
  pkg/handlers/routing/routing_init.go
  pkg/services/feature_flag.go
  pkg/services/featureflag/env_fetcher.go
  pkg/services/featureflag/env_fetcher_test.go
  pkg/services/featureflag/flipt_fetcher.go
  pkg/services/featureflag/flipt_fetcher_test.go
  pkg/services/featureflag/new_fetcher.go
  pkg/services/featureflag/testdata/flipt_system_multi_variant.yaml
  pkg/services/featureflag/testdata/flipt_user_boolean_variant.yaml
  pkg/services/featureflag/testdata/flipt_user_disabled_variant.yaml
  pkg/services/featureflag/testdata/flipt_user_multi_variant.yaml
  pkg/services/mocks/FeatureFlagFetcher.go
  scripts/README.md
  scripts/server-dev
  src/components/FeatureFlag/FeatureFlag.jsx
  src/components/FeatureFlag/FeatureFlag.test.jsx
  src/pages/Admin/FeatureFlags/FeatureFlagEvaluate.jsx
  src/scenes/SystemAdmin/Home.jsx
  src/services/internalApi.js
  swagger-def/definitions/FeatureFlag.yaml
  swagger-def/internal.yaml
  swagger/internal.yaml
Labels: ready-to-merge

#11163 [MB-16548] Import TRDM data
  migrations/app/migrations_manifest.txt
  migrations/app/secure/20230804161700_import_trdm_part_1.up.sql
  migrations/app/secure/20230807175944_import_trdm_part_2.up.sql
  migrations/app/secure/20230807180000_import_trdm_part_3.up.sql
  pkg/migrate/Exec.go
  pkg/migrate/Exec_test.go
  pkg/migrate/SplitStatements.go
  pkg/migrate/fixtures/copyFromStdinComments.sql
  pkg/migrate/fixtures/copyFromStdinKeywords.sql
Labels: ttv, ready-to-merge

#11213 Revert "[MB-16548] Import TRDM data"
  migrations/app/migrations_manifest.txt
  migrations/app/secure/20230804161700_import_trdm_part_1.up.sql
  migrations/app/secure/20230807175944_import_trdm_part_2.up.sql
  migrations/app/secure/20230807180000_import_trdm_part_3.up.sql
  pkg/migrate/Exec.go
  pkg/migrate/Exec_test.go
  pkg/migrate/SplitStatements.go
  pkg/migrate/fixtures/copyFromStdinComments.sql
  pkg/migrate/fixtures/copyFromStdinKeywords.sql
Labels: ttv, ready-to-merge

#11215 [MB-9454] convert edi 824 error condition to verify move referenceID instead of…
  pkg/services/invoice/process_edi824.go
  pkg/services/invoice/process_edi824_test.go
Labels: ttv

#11201 MB-16794 & MB-16679 add or modify content in various areas
  src/components/Customer/Home/Step/Step.stories.jsx
  src/pages/MyMove/Home/index.jsx
  src/pages/MyMove/MovingInfo.jsx
  src/pages/MyMove/SelectShipmentType.jsx
Labels: ttv, ready-to-merge

#11217 [MB-16548] Import TRDM Data Part 1: The Gritty Reboot
  migrations/app/migrations_manifest.txt
  migrations/app/secure/20230804161700_import_trdm_part_1.up.sql
  migrations/app/secure/20230807175944_import_trdm_part_2.up.sql
  migrations/app/secure/20230807180000_import_trdm_part_3.up.sql
  pkg/migrate/Exec.go
  pkg/migrate/Exec_test.go
  pkg/migrate/SplitStatements.go
  pkg/migrate/fixtures/copyFromStdinComments.sql
  pkg/migrate/fixtures/copyFromStdinKeywords.sql
  scripts/ecs-run-app-migrations-container
Labels: ttv, ready-to-merge

#11183 MB-13754: Working client logging
  .circleci/config.yml
  .envrc
  Makefile
  cmd/milmove/serve.go
  config/env/demo.app.env
  config/env/exp.app.env
  config/env/loadtest.app.env
  config/env/stg.app.env
  package.json
  pkg/cli/services.go
  pkg/handlers/client_log_collector.go
  pkg/handlers/client_log_collector_test.go
  pkg/handlers/routing/routing_init.go
  src/App/index.jsx
  src/components/FeatureFlag/FeatureFlag.jsx
  src/components/Office/CustomerSupportRemarkForm/CustomerSupportRemarkForm.jsx
  src/components/Office/EvaluationForm/EvaluationForm.jsx
  src/components/Office/QAEReportTable/ShipmentQAEReportHeader.jsx
  src/components/Office/QAEViolationsForm/QAEViolationsForm.jsx
  src/pages/Admin/FeatureFlags/FeatureFlagEvaluate.jsx
  src/pages/Office/EvaluationReports/EvaluationReports.jsx
  src/pages/Office/MoveAllowances/MoveAllowances.jsx
  src/pages/Office/MovePaymentRequests/MovePaymentRequests.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
  src/pages/Office/Orders/Orders.jsx
  src/pages/Office/ReviewBillableWeight/ReviewBillableWeight.jsx
  src/pages/Office/ServicesCounselingMoveAllowances/ServicesCounselingMoveAllowances.jsx
  src/pages/Office/ServicesCounselingOrders/ServicesCounselingOrders.jsx
  src/pages/Office/index.jsx
  src/registerServiceWorker.js
  src/scenes/MyMove/index.jsx
  src/scenes/PpmLanding/PPMStatusTimeline.js
  src/scenes/SystemAdmin/Home.jsx
  src/scenes/SystemAdmin/index.jsx
  src/services/swaggerRequest.js
  src/setupProxy.js
  src/shared/ConfirmWithReasonButton/index.jsx
  src/shared/JsonSchemaForm/JsonSchemaField.js
  src/shared/JsonSchemaForm/index.jsx
  src/shared/Swagger/api.js
  src/shared/Swagger/request.js
  src/shared/WizardPage/utils.js
  src/shared/constants.js
  src/shared/reduxLogger.js
  src/utils/batchOtelExporter.js
  src/utils/batchOtelExporter.test.js
  src/utils/featureFlags.js
  src/utils/milmoveLog.js
  src/utils/milmoveLog.test.js
  src/utils/otelLogger.js
  src/utils/otelLogger.test.js
  yarn.lock
Labels: ready-to-merge

#11212 MB-16088: Make estimated weight actually optional shuttle service items during payment requests
  pkg/payment_request/service_param_value_lookups/weight_billed_lookup.go
  pkg/payment_request/service_param_value_lookups/weight_billed_lookup_test.go
  pkg/payment_request/service_param_value_lookups/weight_estimated_lookup.go
  pkg/payment_request/service_param_value_lookups/weight_estimated_lookup_test.go
Labels: ready-to-merge, Huckleberry

#11221 [MB-16878] modify EDI 997 AK4 parser to expect fewer than 6 values
  pkg/edi/segment/ak4.go
  pkg/edi/segment/ak4_test.go
  pkg/services/invoice/process_edi997_test.go
Labels: ttv

#11235 [ MB-16540 ] Better developer experience for testharness data scenarios
  pkg/handlers/testharnessapi/api.go
  src/containers/LoginButton/LoginButton.jsx
  src/containers/LoginButton/LoginButton.test.jsx
  src/pages/SignIn/SignIn.jsx
Labels: enhancement, Pamplemoose, good first issue, ready-to-merge

#11222 [ MB-15562 ] More resilient client code
  src/pages/Office/MovePaymentRequests/MovePaymentRequests.jsx
  src/pages/Office/ServicesCounselingMoveInfo/ServicesCounselingMoveInfo.jsx
  src/pages/Office/TXOMoveInfo/TXOMoveInfo.jsx
Labels: Pamplemoose, help wanted, bug

#11236 MB-16879 Add SIT FSCs to invoice generator
  pkg/services/invoice/ghc_payment_request_invoice_generator.go
  pkg/services/invoice/ghc_payment_request_invoice_generator_test.go
Labels: Pamplemoose, ready-to-merge

#11229 [MB-16426] update prime simulator to include ability request sit address change request
  src/constants/routes.js
  src/pages/Office/index.jsx
  src/pages/PrimeUI/MoveTaskOrder/MoveDetails.jsx
  src/pages/PrimeUI/MoveTaskOrder/MoveDetails.module.scss
  src/pages/PrimeUI/UpdateServiceItems/PrimeUIRequestSITDestAddressChangeForm.jsx
  src/pages/PrimeUI/UpdateServiceItems/PrimeUIRequestSITDestAddressChangeForm.test.jsx
  src/pages/PrimeUI/UpdateServiceItems/PrimeUIUpdateServiceItems.jsx
  src/pages/PrimeUI/UpdateServiceItems/PrimeUIUpdateServiceItems.test.jsx
  src/services/primeApi.js
Labels: Pamplemoose, ready-to-merge

#11243 Improving the `scripts/server-dev` documentation slightly
  scripts/README.md
Labels: enhancement, Pamplemoose, help wanted

#11209 MB-16387 Fix submit ppm docs endpoint authz gap
  pkg/factory/ppm_shipment_factory.go
  pkg/factory/ppm_shipment_factory_test.go
  pkg/handlers/internalapi/api.go
  pkg/handlers/internalapi/ppm_shipment.go
  pkg/handlers/internalapi/ppm_shipment_test.go
  pkg/handlers/routing/internalapi_test/ppm_shipment_test.go
  pkg/services/moving_expense/moving_expense_creator.go
  pkg/services/moving_expense/moving_expense_creator_test.go
  pkg/services/ppmshipment/ppm_shipment_fetcher.go
  pkg/services/ppmshipment/ppm_shipment_fetcher_test.go
  pkg/services/ppmshipment/ppm_shipment_new_submitter.go
  pkg/services/ppmshipment/ppm_shipment_new_submitter_test.go
  pkg/services/ppmshipment/ppm_shipment_router_test.go
  pkg/services/ppmshipment/ppm_shipment_updated_submitter_test.go
  pkg/services/progear_weight_ticket/progear_weight_ticket_creator.go
  pkg/services/progear_weight_ticket/progear_weight_ticket_creator_test.go
Labels: A-Team

#11246 MB-16910 - Add function to calculate contract escalated price
  pkg/services/ghcrateengine/pricer_helpers.go
  pkg/services/ghcrateengine/pricer_helpers_test.go
Labels: Pamplemoose, ready-to-merge

#11162 [MB-16549] Update 858 generate to include additional FA2 segments
  pkg/edi/invoice/generator_test.go
  pkg/edi/segment/fa2.go
  pkg/edi/segment/fa2_test.go
  pkg/models/line_of_accounting.go
  pkg/services/invoice/gex_sender_http_test.go
  pkg/services/invoice/ghc_payment_request_invoice_generator.go
  pkg/services/invoice/ghc_payment_request_invoice_generator_test.go
Labels: ttv, ready-to-merge

#11247 [ MB-16909 ] Refactoring Pricer for Domestic Destination (DDP) to use new calculated contract escalated price
  pkg/services/ghcrateengine/domestic_destination_pricer.go
  pkg/services/ghcrateengine/domestic_destination_pricer_test.go
Labels: Pamplemoose, help wanted

#11237 [MB-16593] - Add BuildPaymentServiceItemParams call to testharness function
  pkg/testdatagen/testharness/make_move.go
Labels: Pamplemoose, ready-to-merge

#11228 MB-16893 allow zero value for AK9 Accepted Transaction Sets
  pkg/edi/segment/ak9.go
  pkg/edi/segment/ak9_test.go
Labels: ttv, ready-to-merge

#11245 [MB-16907] Add auth check to move task order fetcher service
  pkg/handlers/primeapi/payment_request_test.go
  pkg/services/move_task_order/move_task_order_fetcher.go
  pkg/services/move_task_order/move_task_order_fetcher_test.go
Labels: A-Team, ready-to-merge

#11251 MB-16916 - Round add_days_sit escalated price to nearest cent
  pkg/services/ghcrateengine/domestic_destination_additional_days_sit_pricer_test.go
  pkg/services/ghcrateengine/domestic_origin_additional_days_sit_pricer_test.go
  pkg/services/ghcrateengine/pricer_helpers.go
  pkg/services/ghcrateengine/pricer_helpers_test.go
  pkg/services/payment_request/payment_request_recalculator_test.go
Labels: Pamplemoose

#11252 [MB-16914] Add helper function to domestic pack unpack pricer
  pkg/services/ghcrateengine/pricer_helpers.go
  pkg/services/ghcrateengine/pricer_helpers_test.go
Labels: Pamplemoose, ready-to-merge

#11256 [MB-16917] Add helper function to domestic pickup delivery sit pricer
  pkg/services/ghcrateengine/domestic_destination_sit_delivery_pricer_test.go
  pkg/services/ghcrateengine/domestic_origin_sit_pickup_pricer_test.go
  pkg/services/ghcrateengine/pricer_helpers.go
  pkg/services/ghcrateengine/pricer_helpers_test.go
Labels: Pamplemoose, ready-to-merge

#11257 MB-16915 Add helper function to domestic first day sit pricer
  pkg/services/ghcrateengine/domestic_destination_first_day_sit_pricer_test.go
  pkg/services/ghcrateengine/domestic_origin_first_day_sit_pricer_test.go
  pkg/services/ghcrateengine/pricer_helpers.go
  pkg/services/ghcrateengine/pricer_helpers_test.go
Labels: Pamplemoose, ready-to-merge

#11259 MB-16919 - Round domestic crating
  pkg/services/ghcrateengine/domestic_destination_pricer.go
  pkg/services/ghcrateengine/domestic_destination_pricer_test.go
  pkg/services/ghcrateengine/pricer_helpers.go
  pkg/services/ghcrateengine/pricer_helpers_test.go
Labels: Pamplemoose

#11263 MB-16912: Update domestic origin pricer to use new escalated pricing func
  pkg/services/ghcrateengine/domestic_origin_pricer.go
  pkg/services/ghcrateengine/domestic_origin_pricer_test.go
  pkg/services/ghcrateengine/pricer_helpers.go
Labels: Pamplemoose, A-Team, ready-to-merge

#11258 [MB-16913]-Add helper function to domestic shorthaul pricer
  pkg/services/ghcrateengine/domestic_shorthaul_pricer.go
  pkg/services/ghcrateengine/domestic_shorthaul_pricer_test.go
Labels: A-Team, ready-to-merge

#11264 [MB-16918] Add helper function to domestic shuttling pricer
  pkg/services/ghcrateengine/domestic_destination_shuttling_pricer_test.go
  pkg/services/ghcrateengine/domestic_origin_shuttling_pricer_test.go
  pkg/services/ghcrateengine/pricer_helpers.go
  pkg/services/ghcrateengine/pricer_helpers_test.go
Labels: Pamplemoose, ready-to-merge

#11267 MB-16956: Add fields for sit service items
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20230822201206_add_fields_for_sit_to_mto_service_items.up.sql
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/m_t_o_service_item_dest_s_i_t.go
  pkg/gen/primemessages/update_m_t_o_service_item_s_i_t.go
  pkg/gen/primev2api/embedded_spec.go
  pkg/gen/primev2messages/m_t_o_service_item_dest_s_i_t.go
  pkg/handlers/primeapi/move_task_order_test.go
  pkg/handlers/primeapi/mto_service_item_test.go
  pkg/handlers/primeapi/payloads/model_to_payload.go
  pkg/handlers/primeapi/payloads/payload_to_model.go
  pkg/handlers/primeapi/payloads/payload_to_model_test.go
  pkg/handlers/primeapiv2/move_task_order_test.go
  pkg/handlers/primeapiv2/payloads/model_to_payload.go
  pkg/models/mto_service_items.go
  pkg/services/mto_service_item/mto_service_item_validators.go
  pkg/services/mto_service_item/mto_service_item_validators_test.go
  swagger-def/definitions/prime/MTOServiceItemDestSIT.yaml
  swagger-def/prime.yaml
  swagger/prime.yaml
  swagger/prime_v2.yaml
Labels: ready-to-merge, Huckleberry

#11286 Update Mayport postal code.
  migrations/app/migrations_manifest.txt
  migrations/app/secure/20230828180000_update_mayport_zip.up.sql
Labels: ready-to-merge

#11288 MB-16816 - Standardize messages for escalated price errors
  pkg/services/ghcrateengine/domestic_destination_pricer.go
  pkg/services/ghcrateengine/domestic_destination_pricer_test.go
  pkg/services/ghcrateengine/domestic_destination_shuttling_pricer_test.go
  pkg/services/ghcrateengine/domestic_origin_shuttling_pricer_test.go
  pkg/services/ghcrateengine/domestic_shorthaul_pricer.go
  pkg/services/ghcrateengine/domestic_shorthaul_pricer_test.go
  pkg/services/ghcrateengine/pricer_helpers.go
  pkg/services/ghcrateengine/pricer_helpers_test.go
Labels: Pamplemoose

#11271 [MB-16924] Update `lines_of_accounting.loa_trnsn_id` values
  cmd/load-spreadsheet-data/load-updated-loa-trnsn-ids.py
  migrations/app/migrations_manifest.txt
  migrations/app/secure/20230824200422_update_loa_trnsn_ids.up.sql
  pkg/factory/line_of_accounting_factory.go
Labels: ttv, ready-to-merge

#11298 MB-16943 Different zip, same bpc distance
  pkg/models/re_zip3s.go
  pkg/models/re_zip3s_test.go
  pkg/route/hhg_planner.go
  pkg/route/hhg_planner_test.go
  pkg/testdatagen/testharness/dispatch.go
  pkg/testdatagen/testharness/make_move.go
Labels: ttv, ready-to-merge

#11297 Upgrade all otel dependencies, fix after API changes
  go.mod
  go.sum
  pkg/telemetry/metrictest/memory.go
Labels: ready-to-merge

#11274 MB-16796 Correct issue where name and date data don't populate on the legal agreement
  src/pages/MyMove/Home/index.jsx
  src/pages/MyMove/Home/index.test.jsx
Labels: ttv
