Repository transcom/mymove, pull requests merged in 2023-02, with the labels that each got.

#9913 [ on-call ] Updating the CircleCI badge with a new API token
  README.md
Labels: enhancement, help wanted, bug

#9947 MB-15062: improve playwright local dev
  .circleci/config.yml
  playwright.config.js
  src/components/Table/Filters/DateSelectFilter.jsx
  src/shared/dates.js
  src/shared/dates.test.js
Labels: ready-to-merge

#9991 [ office-hours, MB-14876 ] Adding @rogeruiz CAC to STG and PRD
  migrations/app/migrations_manifest.txt
  migrations/app/secure/20230201162639_rogeruiz_cac.up.sql
  scripts/generate-secure-migration
Labels: enhancement, needs-is3-review, infra, help wanted

#9977 MB-15017 convert office ppm tests to playwright
  pkg/testdatagen/scenario/e2ebasic.go
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/scenario/subscenarios.go
  pkg/testdatagen/testharness/dispatch.go
  pkg/testdatagen/testharness/make_move.go
  playwright/tests/office/ppms/addShipment.spec.js
  playwright/tests/office/ppms/happyPathFlows.spec.js
  playwright/tests/office/ppms/scPpmTestFixture.js
  playwright/tests/office/ppms/viewShipment.spec.js
  playwright/tests/office/servicescounseling/servicesCounselingTestFixture.js
  playwright/tests/utils/testharness.js
Labels: ready-to-merge

#9989 MB-15106: Add documentation for params object
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/service_item.go
  swagger-def/prime.yaml
  swagger/prime.yaml
Labels: ready-to-merge

#9972 MB-14805 Add PPM Document fetcher service
  pkg/db/utilities/utilities.go
  pkg/db/utilities/utilities_test.go
  pkg/models/ppm_shipment.go
  pkg/services/mocks/PPMDocumentFetcher.go
  pkg/services/ppmshipment.go
  pkg/services/ppmshipment/ppm_document_fetcher.go
  pkg/services/ppmshipment/ppm_document_fetcher_test.go
Labels: A-Team

#9927 [MB-14914] Update nodejs to 18.x
  .circleci/config.yml
  .github/workflows/analyze-bundle.yml
  .github/workflows/front-end-linter.yml
  .github/workflows/happo-tests-main.yml
  .github/workflows/happo-tests.yml
  .node-version
  Dockerfile.local
  Dockerfile.migrations_local
  Dockerfile.reviewapp
  Dockerfile.tasks_local
  Dockerfile.tools_local
  Dockerfile.webhook_client
  Dockerfile.webhook_client_dp3
  Dockerfile.webhook_client_local
  Makefile
  cypress/Dockerfile.cypress
  dangerfile.ts
  nix/default.nix
  scripts/run-e2e-mtls-test-docker
  scripts/run-e2e-test
  scripts/run-e2e-test-docker
Labels: dependencies, ttv, ready-to-merge

#10003 [ MB-15098 ] Adding Prime Certificates migration
  migrations/app/migrations_manifest.txt
  migrations/app/secure/20230202193449_add_daycos_and_movehq_certs.up.sql
Labels: infra, help wanted, Huckleberry

#10015 [ spike ] Adding PropagateTags to the EcsParameters
  cmd/ecs-deploy/put_target.go
Labels: enhancement, infra, ready-to-merge, bug

#10016 [ MB-14736 ] Updating the GEX URL to GEXA
  config/env/demo.app-client-tls.env
  config/env/demo.app.env
  config/env/exp.app-client-tls.env
  config/env/exp.app.env
  config/env/exp.process-edis.env
  config/env/prd.app.env
  config/env/prd.post-file-to-gex.env
  config/env/prd.process-edis.env
  config/env/stg.app-client-tls.env
  config/env/stg.app.env
  config/env/stg.post-file-to-gex.env
  config/env/stg.process-edis.env
  pkg/cli/gex.go
  pkg/services/invoice/gex_sender_http.go
Labels: infra, help wanted, bug

#9942 [ office-hours, MB-14891, MB-15073 ] Adding better logging when working with certificates for the Prime API
  pkg/certs/certs.go
  pkg/handlers/authentication/client_cert.go
Labels: enhancement, infra, ready-to-merge

#9965 MB-14824 Add alerts when review items not complete
  src/components/Customer/PPM/Closeout/ReviewItems/ReviewItems.jsx
  src/components/Customer/PPM/Closeout/ReviewItems/ReviewItems.module.scss
  src/pages/MyMove/PPM/Closeout/Review/Review.jsx
  src/pages/MyMove/PPM/Closeout/Review/Review.test.jsx
  src/utils/ppmCloseout.jsx
Labels: ttv

#10017 [ MB-14736 ] Updating from GEXA to GEXB for HTTPS
  config/env/demo.app-client-tls.env
  config/env/demo.app.env
  config/env/exp.app-client-tls.env
  config/env/exp.app.env
  config/env/exp.process-edis.env
  config/env/prd.app.env
  config/env/prd.post-file-to-gex.env
  config/env/prd.process-edis.env
  config/env/stg.app-client-tls.env
  config/env/stg.app.env
  config/env/stg.post-file-to-gex.env
  config/env/stg.process-edis.env
  pkg/cli/gex.go
  pkg/services/invoice/gex_sender_http.go
Labels: infra, bug

#9997 MB-15121: Enable DTOD_USE_MOCK for local dev, needed for playwright
  .circleci/config.yml
  .envrc
  pkg/route/dtod_zip5_distance_mock.go
Labels: ready-to-merge

#9978 MB-14881-Customer-Gets-Clearer-Guidance-While-Completing-Steps-In-Their-PPM
  src/components/Customer/PPM/Closeout/ReviewItems/ReviewItems.jsx
  src/components/Customer/PPM/Closeout/ReviewItems/ReviewItems.test.jsx
  src/pages/MyMove/PPM/Closeout/Review/Review.jsx
  src/pages/MyMove/PPM/Closeout/Review/Review.test.jsx
  src/utils/ppmCloseout.jsx
Labels: ttv, ready-to-merge

#9885 MB-14540 factory.BuildDutyLocation added as new version of testdatagen.MakeDutyLocation
  pkg/factory/address_factory.go
  pkg/factory/duty_location_factory.go
  pkg/factory/duty_location_factory_test.go
  pkg/factory/shared.go
  pkg/factory/tariff_factory.go
  pkg/handlers/ghcapi/orders_test.go
  pkg/handlers/ghcapi/queues_test.go
  pkg/handlers/internalapi/moves_test.go
  pkg/handlers/internalapi/orders_test.go
  pkg/handlers/internalapi/service_members_test.go
  pkg/handlers/internalapi/transportation_offices_test.go
  pkg/handlers/supportapi/move_task_order_test.go
  pkg/models/duty_location.go
  pkg/models/duty_location_test.go
  pkg/models/order_test.go
  pkg/models/service_member_test.go
  pkg/models/shipment_summary_worksheet_test.go
  pkg/paperwork/shipment_summary_test.go
  pkg/services/move/move_router_test.go
  pkg/services/move/move_searcher_test.go
  pkg/services/move_history/move_history_fetcher_test.go
  pkg/services/order/order_fetcher_test.go
  pkg/services/order/order_updater_test.go
  pkg/services/paperwork/form_creator_test.go
  pkg/services/payment_request/payment_request_list_fetcher_test.go
  pkg/services/query/query_builder_test.go
  pkg/testdatagen/scenario/shared.go
Labels: ready-to-merge, spark

#10026 MB-15157: Change playwright worker default based on arch
  playwright.config.js
Labels: ready-to-merge

#10000 MB-15122: convert admin integration tests to playwright
  .circleci/config.yml
  cypress/integration/admin/adminUsers.js
  cypress/integration/admin/homepage.js
  cypress/integration/admin/moves.js
  cypress/integration/admin/officeUsers.js
  cypress/integration/admin/offices.js
  cypress/integration/admin/users.js
  cypress/integration/admin/webhookSubscriptions.js
Labels: ready-to-merge

#9966 MB-15033: convert customer ppm tests to playwright
  cmd/generate-test-data/main.go
  pkg/handlers/authentication/devlocal.go
  pkg/models/duty_location_test.go
  pkg/models/payment_service_item_test.go
  pkg/models/user.go
  pkg/testdatagen/make_duty_location.go
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/testharness/dispatch.go
  pkg/testdatagen/testharness/make_move.go
  pkg/testingsuite/pop_suite.go
  playwright/fixtures/constructedWeight.xls
  playwright/fixtures/constructedWeight.xlsx
  playwright/fixtures/sampleWeightTicket.jpg
  playwright/fixtures/trailerOwnership.pdf
  playwright/tests/my/milmove/ppms/about.spec.js
  playwright/tests/my/milmove/ppms/advances.spec.js
  playwright/tests/my/milmove/ppms/customerPpmTestFixture.js
  playwright/tests/my/milmove/ppms/dateAndLocation.spec.js
  playwright/tests/my/milmove/ppms/entireShipmentCloseout.spec.js
  playwright/tests/my/milmove/ppms/entireShipmentOnboarding.spec.js
  playwright/tests/my/milmove/ppms/estimatedIncentive.spec.js
  playwright/tests/my/milmove/ppms/estimatedWeightsProgear.spec.js
  playwright/tests/my/milmove/ppms/expenses.spec.js
  playwright/tests/my/milmove/ppms/finalCloseout.spec.js
  playwright/tests/my/milmove/ppms/navigateToUploadDocs.spec.js
  playwright/tests/my/milmove/ppms/progear.spec.js
  playwright/tests/my/milmove/ppms/review.spec.js
  playwright/tests/my/milmove/ppms/weightTickets.spec.js
  playwright/tests/office/ppms/ppmTestFixture.js
  playwright/tests/utils/baseTest.js
  playwright/tests/utils/customerTest.js
  playwright/tests/utils/testharness.js
Labels: ready-to-merge

#10034 [MB-15162] Fix various pre-commit issues
  .pre-commit-config.yaml
  pkg/middleware/context_logger_test.go
  pkg/middleware/valid_methods_static_test.go
  pkg/services/ppmshipment/ppm_shipment_updater_test.go
  pkg/storage/storage.go
  testdata/src/ato_linter_tests/nosec.go
Labels: ttv, ready-to-merge

#10018 Add PPM Documents handler and tests.
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/moving_expenses.go
  pkg/gen/ghcmessages/p_p_m_documents.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/ppm_document.go
  pkg/handlers/ghcapi/ppm_document_test.go
  swagger-def/definitions/PPMDocuments.yaml
  swagger/ghc.yaml
Labels: A-Team

#9981 [MB-14903] backend deletion of ppm closeout line items
  pkg/gen/internalapi/configure_mymove.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalapi/internaloperations/mymove_api.go
  pkg/gen/internalapi/internaloperations/ppm/delete_moving_expense.go
  pkg/gen/internalapi/internaloperations/ppm/delete_moving_expense_parameters.go
  pkg/gen/internalapi/internaloperations/ppm/delete_moving_expense_responses.go
  pkg/gen/internalapi/internaloperations/ppm/delete_moving_expense_urlbuilder.go
  pkg/gen/internalapi/internaloperations/ppm/delete_pro_gear_weight_ticket.go
  pkg/gen/internalapi/internaloperations/ppm/delete_pro_gear_weight_ticket_parameters.go
  pkg/gen/internalapi/internaloperations/ppm/delete_pro_gear_weight_ticket_responses.go
  pkg/gen/internalapi/internaloperations/ppm/delete_pro_gear_weight_ticket_urlbuilder.go
  pkg/gen/internalapi/internaloperations/ppm/delete_weight_ticket.go
  pkg/gen/internalapi/internaloperations/ppm/delete_weight_ticket_parameters.go
  pkg/gen/internalapi/internaloperations/ppm/delete_weight_ticket_responses.go
  pkg/gen/internalapi/internaloperations/ppm/delete_weight_ticket_urlbuilder.go
  pkg/handlers/internalapi/api.go
  pkg/handlers/internalapi/moving_expense.go
  pkg/handlers/internalapi/moving_expense_test.go
  pkg/handlers/internalapi/progear_weight_ticket.go
  pkg/handlers/internalapi/progear_weight_ticket_test.go
  pkg/handlers/internalapi/weight_ticket.go
  pkg/handlers/internalapi/weight_ticket_test.go
  pkg/models/moving_expense.go
  pkg/models/progear_weight_ticket.go
  pkg/models/weight_ticket.go
  pkg/services/mocks/MovingExpenseDeleter.go
  pkg/services/mocks/ProgearWeightTicketDeleter.go
  pkg/services/mocks/WeightTicketDeleter.go
  pkg/services/moving_expense.go
  pkg/services/moving_expense/moving_expense_deleter.go
  pkg/services/moving_expense/moving_expense_deleter_test.go
  pkg/services/mto_shipment/mto_shipment_fetcher.go
  pkg/services/ppmshipment/ppm_estimator.go
  pkg/services/ppmshipment/ppm_shipment_fetcher.go
  pkg/services/progear_weight_ticket.go
  pkg/services/progear_weight_ticket/progear_weight_ticket_deleter.go
  pkg/services/progear_weight_ticket/progear_weight_ticket_deleter_test.go
  pkg/services/weight_ticket.go
  pkg/services/weight_ticket/weight_ticket_deleter.go
  pkg/services/weight_ticket/weight_ticket_deleter_test.go
  swagger-def/internal.yaml
  swagger/internal.yaml
Labels: ttv, ready-to-merge

#9998 [MB-14811] Disregard rejected weight tickets in new weight calculations
  pkg/services/ppmshipment/ppm_estimator.go
  pkg/services/ppmshipment/ppm_estimator_test.go
Labels: ready-to-merge

#10004 MB-15126: Extend playwright office tests fixtures vs major beforeEach setup
  Makefile
  playwright/tests/office/ppms/addShipment.spec.js
  playwright/tests/office/ppms/happyPathFlows.spec.js
  playwright/tests/office/ppms/scPpmTestFixture.js
  playwright/tests/office/ppms/viewShipment.spec.js
  playwright/tests/office/servicescounseling/servicesCounselingFlows.spec.js
  playwright/tests/office/servicescounseling/servicesCounselingNTS.spec.js
  playwright/tests/office/servicescounseling/servicesCounselingNTSR.spec.js
  playwright/tests/office/servicescounseling/servicesCounselingQueueFilters.spec.js
  playwright/tests/office/servicescounseling/servicesCounselingTestFixture.js
  playwright/tests/utils/testharness.js
Labels: ready-to-merge

#9908 [MB-14185] Advance request status updates
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/p_p_m_advance_status.go
  pkg/gen/ghcmessages/p_p_m_shipment.go
  pkg/gen/ghcmessages/update_p_p_m_shipment.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/p_p_m_advance_status.go
  pkg/gen/internalmessages/p_p_m_shipment.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/internal/payloads/payload_to_model.go
  pkg/services/ppmshipment/ppm_shipment_updater.go
  pkg/services/ppmshipment/ppm_shipment_updater_test.go
  src/components/Office/ShipmentForm/ShipmentForm.test.jsx
  src/components/Office/ShipmentForm/ppmShipmentSchema.js
  src/components/Office/ShipmentIncentiveAdvance/ShipmentIncentiveAdvance.jsx
  src/components/Office/ShipmentIncentiveAdvance/ShipmentIncentiveAdvance.stories.jsx
  src/components/Office/ShipmentIncentiveAdvance/ShipmentIncentiveAdvance.test.jsx
  src/utils/formatMtoShipment.js
  swagger-def/definitions/PPMAdvanceStatus.yaml
  swagger-def/ghc.yaml
  swagger/ghc.yaml
  swagger/internal.yaml
Labels: Pamplemoose

#10022 MB-14703: Fail if the number of spectral lint errors increases
  scripts/ensure-spectral-lint
Labels: ready-to-merge

#10035 MB-15064, MB-15001 - Updating Prime API Swagger
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/mto_service_item/update_m_t_o_service_item.go
  pkg/gen/primeapi/primeoperations/payment_request/create_payment_request.go
  pkg/gen/primeclient/mto_service_item/mto_service_item_client.go
  pkg/gen/primeclient/payment_request/payment_request_client.go
  swagger-def/prime.yaml
  swagger/prime.yaml
Labels: Huckleberry

#10019 MB-14184 - Add advance request status field
  src/components/Office/DefinitionLists/NTSRShipmentInfoList.jsx
  src/components/Office/DefinitionLists/NTSRShipmentInfoList.stories.jsx
  src/components/Office/DefinitionLists/NTSRShipmentInfoList.test.jsx
  src/components/Office/DefinitionLists/NTSShipmentInfoList.jsx
  src/components/Office/DefinitionLists/NTSShipmentInfoList.stories.jsx
  src/components/Office/DefinitionLists/NTSShipmentInfoList.test.jsx
  src/components/Office/DefinitionLists/PPMShipmentInfoList.jsx
  src/components/Office/DefinitionLists/PPMShipmentInfoList.stories.jsx
  src/components/Office/DefinitionLists/ShipmentInfoList.jsx
  src/components/Office/DefinitionLists/ShipmentInfoListSelector.jsx
  src/components/Office/EvaluationReportShipmentDisplay/EvaluationReportShipmentDisplay.jsx
  src/components/Office/RequestedShipments/SubmittedRequestedShipments.jsx
  src/components/Office/ShipmentDisplay/ShipmentDisplay.jsx
  src/components/Office/ShipmentDisplay/ShipmentDisplay.stories.jsx
  src/components/Office/ShipmentForm/ppmShipmentSchema.js
  src/components/Office/ShipmentIncentiveAdvance/ShipmentIncentiveAdvance.jsx
  src/constants/ppms.js
  src/pages/Office/MoveDetails/MoveDetails.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.test.jsx
  src/utils/displayFlags.js
  src/utils/displayFlags.test.js
Labels: Pamplemoose, ready-to-merge

#10005 [ spike ] Adding some helpful messaging to check-deployed-commit CI script
  scripts/check-deployed-commit
Labels: enhancement, good first issue, infra

#9943 MB-14541 factory build officeuser
  pkg/factory/office_user_factory.go
  pkg/factory/office_user_factory_test.go
  pkg/factory/role_factory.go
  pkg/factory/role_factory_test.go
  pkg/factory/shared.go
  pkg/factory/user_factory.go
  pkg/factory/user_factory_test.go
  pkg/handlers/adminapi/office_users_test.go
  pkg/handlers/authentication/auth_test.go
  pkg/handlers/authentication/devlocal_test.go
  pkg/handlers/ghcapi/customer_support_remarks_test.go
  pkg/handlers/ghcapi/customer_test.go
  pkg/handlers/ghcapi/evaluation_report_test.go
  pkg/handlers/ghcapi/move_history_test.go
  pkg/handlers/ghcapi/move_task_order_test.go
  pkg/handlers/ghcapi/move_test.go
  pkg/handlers/ghcapi/moving_expense_test.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/handlers/ghcapi/orders_test.go
  pkg/handlers/ghcapi/payment_request_test.go
  pkg/handlers/ghcapi/ppm_document_test.go
  pkg/handlers/ghcapi/progear_weight_ticket_test.go
  pkg/handlers/ghcapi/queues_test.go
  pkg/handlers/ghcapi/tac_test.go
  pkg/handlers/ghcapi/weight_ticket_test.go
  pkg/handlers/internalapi/move_queue_items_test.go
  pkg/handlers/internalapi/moving_expense_test.go
  pkg/handlers/internalapi/mto_shipment_test.go
  pkg/handlers/internalapi/office_test.go
  pkg/handlers/internalapi/personally_procured_move_incentive_test.go
  pkg/handlers/internalapi/ppm_shipment_test.go
  pkg/handlers/internalapi/progear_weight_ticket_test.go
  pkg/handlers/internalapi/transportation_offices_test.go
  pkg/handlers/internalapi/weight_ticket_test.go
  pkg/models/customer_support_remarks_test.go
  pkg/models/evaluation_report_test.go
  pkg/models/user_test.go
  pkg/notifications/reweigh_requested_test.go
  pkg/services/customer_support_remarks/customer_support_remarks_creator_test.go
  pkg/services/customer_support_remarks/customer_support_remarks_fetcher_test.go
  pkg/services/evaluation_report/evaluation_report_creator_test.go
  pkg/services/evaluation_report/evaluation_report_deleter_test.go
  pkg/services/evaluation_report/evaluation_report_fetcher_test.go
  pkg/services/evaluation_report/evaluation_report_updater_test.go
  pkg/services/move_history/move_history_fetcher_test.go
  pkg/services/mto_shipment/mto_shipment_updater_test.go
  pkg/services/mto_shipment/validation_test.go
  pkg/services/office_user/office_user_fetcher_test.go
  pkg/services/office_user/office_user_updater_test.go
  pkg/services/order/order_fetcher_test.go
  pkg/services/payment_request/payment_request_list_fetcher_test.go
  pkg/services/query/query_builder_test.go
  pkg/services/upload/upload_information_fetcher_test.go
  pkg/services/user/user_updater_test.go
  pkg/services/users_roles/users_roles_test.go
  pkg/testdatagen/scenario/bandwidth.go
  pkg/testdatagen/scenario/e2ebasic.go
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/scenario/subscenarios.go
  pkg/testdatagen/testharness/make_office_user.go
Labels: ready-to-merge, spark

#9921 MB-14969 factory.BuildContractor added as new version of testdatagen.MakeContractor
  pkg/factory/constants.go
  pkg/factory/contractor_factory.go
  pkg/factory/contractor_factory_test.go
  pkg/factory/shared.go
  pkg/handlers/adminapi/webhook_subscriptions_test.go
  pkg/handlers/internalapi/office_test.go
  pkg/handlers/internalapi/orders_test.go
  pkg/handlers/internalapi/personally_procured_move_test.go
  pkg/handlers/primeapi/upload_test.go
  pkg/handlers/supportapi/move_task_order_test.go
  pkg/models/move_test.go
  pkg/models/personally_procured_move_test.go
  pkg/models/prime_upload_test.go
  pkg/models/queue_test.go
  pkg/services/move_task_order/move_task_order_creator_test.go
  pkg/services/payment_request/payment_request_recalculator_test.go
  pkg/services/payment_request/payment_request_shipment_recalculate_test.go
  pkg/services/payment_request/upload_creator_test.go
  pkg/services/webhook_subscription/webhook_subscription_creator_test.go
  pkg/uploader/prime_uploader_test.go
Labels: ready-to-merge, spark

#10068 [ MB-15214 ] Fix duplicate entries issue in db_dev_e2e_populate
  pkg/testdatagen/scenario/shared.go
Labels: Pamplemoose

#10056 MB-15083: Add requested pickup date column for TOO queue
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/queues/get_moves_queue_parameters.go
  pkg/gen/ghcapi/ghcoperations/queues/get_moves_queue_urlbuilder.go
  pkg/handlers/ghcapi/queues.go
  src/pages/Office/MoveQueue/MoveQueue.jsx
  src/pages/Office/MoveQueue/MoveQueue.test.jsx
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: ready-to-merge, Huckleberry

#9956 [MB-15041] Update to use new base docker image
  .circleci/config.yml
  Dockerfile.local
  Dockerfile.migrations_local
  Dockerfile.reviewapp
  Dockerfile.tasks_local
  Dockerfile.tools_local
  Dockerfile.webhook_client
  Dockerfile.webhook_client_dp3
  Dockerfile.webhook_client_local
  Makefile
Labels: dependencies, ttv, ready-to-merge

#10067 [ MB-14692, MB-14723 ] Swagger Admin updates for responses stanza
  swagger-def/admin.yaml
Labels: enhancement, ready-to-merge

#10064 [ MB-14692, MB-14723 ] Reordering the defintions stanza for Admin Swagger
  swagger-def/.spectral.yml
  swagger-def/admin.yaml
  swagger/admin.yaml
Labels: enhancement, ready-to-merge

#10087 [MB-14979]-FE: The usePPMShipmentDocsQueries query is updated to reflect the new API endpoint
  src/constants/queryKeys.js
  src/hooks/queries.js
  src/pages/Office/PPM/ReviewDocuments/ReviewDocuments.jsx
  src/pages/Office/PPM/ReviewDocuments/ReviewDocuments.test.jsx
  src/services/ghcApi.js
Labels: A-Team

#10079 MB-15226: Fix CircleCI playwright runner to respect path
  .circleci/config.yml
Labels: ready-to-merge

#10051 MB-15093 add factory.BuildStorageFacility
  pkg/factory/shared.go
  pkg/factory/storage_facility_factory.go
  pkg/factory/storage_facility_factory_test.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/handlers/primeapi/mto_shipment_test.go
  pkg/paperwork/evaluation_report_test.go
  pkg/payment_request/service_param_value_lookups/service_param_value_lookups_test.go
  pkg/services/move_task_order/move_task_order_updater_test.go
  pkg/services/mto_shipment/mto_shipment_creator_test.go
  pkg/services/mto_shipment/mto_shipment_fetcher_test.go
  pkg/services/mto_shipment/mto_shipment_updater_test.go
  pkg/services/mto_shipment/shipment_approver_test.go
  pkg/services/payment_request/payment_request_creator_test.go
  pkg/testdatagen/scenario/e2ebasic.go
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/scenario/subscenarios.go
  pkg/testdatagen/testharness/make_move.go
Labels: ready-to-merge, spark

#10080 MB-15227: fix playwright prime simulator
  .circleci/config.yml
  playwright/tests/office/primesimulator/primeSimulatorFlows.spec.js
Labels: ready-to-merge

#10052 MB-15020 Remove unnecessary weight ticket fetcher (service & api endpoint)
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/ghcapi/ghcoperations/ppm/get_weight_tickets.go
  pkg/gen/ghcapi/ghcoperations/ppm/get_weight_tickets_parameters.go
  pkg/gen/ghcapi/ghcoperations/ppm/get_weight_tickets_responses.go
  pkg/gen/ghcapi/ghcoperations/ppm/get_weight_tickets_urlbuilder.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/weight_ticket.go
  pkg/handlers/ghcapi/weight_ticket_test.go
  pkg/services/mocks/WeightTicketFetcher.go
  pkg/services/weight_ticket.go
  pkg/services/weight_ticket/weight_ticket_fetcher.go
  pkg/services/weight_ticket/weight_ticket_fetcher_test.go
  src/services/ghcApi.js
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: A-Team, ready-to-merge

#10086 MB-15228: devlocal multi role and testharness
  pkg/factory/role_factory.go
  pkg/handlers/authentication/devlocal.go
  pkg/handlers/authentication/devlocal_test.go
  pkg/handlers/routing/routing_init.go
  pkg/handlers/testharnessapi/api.go
  pkg/handlers/testharnessapi/api_test.go
  pkg/testdatagen/testharness/dispatch.go
  playwright/tests/utils/officeTest.js
Labels: ready-to-merge

#10076 MB-13864 weight tickets overview integration
  src/components/Office/PPM/ReviewDocumentsSidePanel/ReviewDocumentsSidePanel.jsx
  src/components/Office/PPM/ReviewDocumentsSidePanel/ReviewDocumentsSidePanel.module.scss
  src/components/Office/PPM/ReviewDocumentsSidePanel/ReviewDocumentsSidePanel.stories.jsx
  src/components/Office/PPM/ReviewDocumentsSidePanel/ReviewDocumentsSidePanel.test.jsx
  src/pages/Office/PPM/ReviewDocuments/ReviewDocuments.jsx
  src/pages/Office/PPM/ReviewDocuments/ReviewDocuments.test.jsx
Labels: A-Team

#10099 add secure migration to update dspencer cac
  migrations/app/migrations_manifest.txt
  migrations/app/secure/20230216145923_dspencer_cac.up.sql
Labels: ready-to-merge

#9683 MB-14606 fix prereqs and cac prereqs scripts for nix users
  .envrc
  scripts/cac-prereqs
  scripts/prereqs
Labels: A-Team

#10101 MB-15083: Show requested pickup date for PPM shipments in both the TOO and service counselor queues
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/services/order/order_fetcher.go
Labels: ready-to-merge, Huckleberry

#10055 [MB-15158] weight_tickets table migration
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20230216192945_add_adjusted_net_weight_and_net_weight_remarks_to_weight_ticket_table.up.sql
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/update_weight_ticket.go
  pkg/gen/ghcmessages/weight_ticket.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/update_weight_ticket.go
  pkg/gen/internalmessages/weight_ticket.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/internal/payloads/payload_to_model.go
  pkg/handlers/ghcapi/weight_ticket_test.go
  pkg/handlers/internalapi/internal/payloads/model_to_payload.go
  pkg/handlers/internalapi/internal/payloads/payload_to_model.go
  pkg/handlers/internalapi/weight_ticket_test.go
  pkg/models/weight_ticket.go
  pkg/models/weight_ticket_test.go
  pkg/services/weight_ticket/rules.go
  pkg/services/weight_ticket/rules_test.go
  pkg/services/weight_ticket/weight_ticket_updater.go
  pkg/services/weight_ticket/weight_ticket_updater_test.go
  src/types/shipment.js
  swagger-def/definitions/WeightTicket.yaml
  swagger-def/ghc.yaml
  swagger-def/internal.yaml
  swagger/ghc.yaml
  swagger/internal.yaml
Labels: Pamplemoose

#10096 [ office-hours ] Updating client certificate generator
  cmd/milmove/gen_certs_migration.go
Labels: enhancement, infra, security, ready-to-merge, help wanted, bug

#10073 MB-15047 - Add routing for review shipment weights
  src/constants/routes.js
  src/hooks/queries.js
  src/hooks/queries.test.jsx
  src/pages/Office/ServicesCounselingMoveInfo/ServicesCounselingMoveInfo.jsx
  src/pages/Office/ServicesCounselingMoveInfo/ServicesCounselingMoveInfo.test.jsx
  src/pages/Office/ServicesCounselingReviewShipmentWeights/ServicesCounselingReviewShipmentWeights.jsx
Labels: Pamplemoose

#10104 MB-14216: Adds SC weight ticket review integration test
  pkg/testdatagen/testharness/dispatch.go
  pkg/testdatagen/testharness/make_move.go
  playwright/tests/office/servicescounseling/servicesCounselingTestFixture.js
  playwright/tests/office/servicescounseling/servicesCounselingWeightTickets.spec.js
  playwright/tests/utils/testharness.js
Labels: ready-to-merge

#10115 MB-13864 update ppm doc review to handle different doc types without errors
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/scenario/subscenarios.go
  src/components/Office/PPM/ReviewWeightTicket/ReviewWeightTicket.jsx
  src/pages/Office/PPM/ReviewDocuments/ReviewDocuments.jsx
  src/pages/Office/PPM/ReviewDocuments/ReviewDocuments.test.jsx
  src/utils/test/factories/upload.js
  src/utils/test/factories/weightTicket.js
Labels: A-Team

#10098 MB-15201 Remove unnecessary findCustomization calls
  pkg/factory/admin_user_factory.go
  pkg/factory/duty_location_factory.go
  pkg/factory/office_phone_line_factory.go
  pkg/factory/transportation_office_factory.go
Labels: ready-to-merge, spark

#10108 Fix Precondition fail in About and filter out deleted items
  pkg/services/ppmshipment/ppm_shipment_fetcher.go
  pkg/services/ppmshipment/ppm_shipment_fetcher_test.go
  src/pages/MyMove/PPM/Closeout/About/About.jsx
  src/pages/MyMove/PPM/Closeout/About/About.test.jsx
Labels: ttv, ready-to-merge

#10061 [ MB-14692, MB-14723 ] Updating the Admin API metadata
  pkg/gen/adminapi/doc.go
  pkg/gen/adminapi/embedded_spec.go
  pkg/gen/adminapi/server.go
  swagger-def/admin.yaml
  swagger/admin.yaml
Labels: enhancement, ready-to-merge

#10065 MB-14966 factory.BuildServiceItemParamKey added as new version of testdatagen.MakeServiceItemParamKey
  pkg/factory/service_item_param_key_factory.go
  pkg/factory/service_item_param_key_factory_test.go
  pkg/factory/shared.go
  pkg/payment_request/service_param_list_fetcher_test.go
  pkg/payment_request/service_param_list_valid_test.go
  pkg/payment_request/service_param_value_lookups/contract_code_lookup_test.go
  pkg/payment_request/service_param_value_lookups/distance_zip_lookup_test.go
  pkg/payment_request/service_param_value_lookups/eia_fuel_price_lookup_test.go
  pkg/payment_request/service_param_value_lookups/service_params_cache_test.go
  pkg/services/ghcrateengine/pricer_helpers_test.go
  pkg/services/ghcrateengine/service_item_pricer_test.go
  pkg/services/payment_request/payment_request_creator_test.go
Labels: ready-to-merge, spark

#10095 MB-14179-Delete-Line-Items-PPM
  src/pages/MyMove/PPM/Closeout/Review/Review.jsx
  src/pages/MyMove/PPM/Closeout/Review/Review.test.jsx
  src/services/internalApi.js
Labels: ttv

#10114 [ MB-14939 ] Clarifying diversion logic for approving mto-shipments
  src/components/Office/RequestedShipments/SubmittedRequestedShipments.jsx
Labels: Pamplemoose

#10102 [MB-15104] Update PPM Status after Reviewing Documents
  pkg/services/mocks/PPMShipmentReviewDocuments.go
  pkg/services/mocks/PPMShipmentRouter.go
  pkg/services/ppmshipment.go
  pkg/services/ppmshipment/ppm_shipment_review_documents.go
  pkg/services/ppmshipment/ppm_shipment_review_documents_test.go
  pkg/services/ppmshipment/ppm_shipment_router.go
  pkg/services/ppmshipment/ppm_shipment_router_test.go
Labels: ready-to-merge

#10089 [MB-15163] Initial attempt to write e2e test for line item deletion
  playwright/tests/my/milmove/ppms/customerPpmTestFixture.js
  playwright/tests/my/milmove/ppms/entireShipmentCloseout.spec.js
Labels: ttv

#10133 [ MB-15306 ] Modified logic in shipment form submit handler to fix bugs:
  src/components/Office/ShipmentForm/ShipmentForm.jsx
Labels: Pamplemoose

#10130 MB-14967 Add factory.BuildReService
  pkg/factory/re_service_factory.go
  pkg/factory/re_service_factory_test.go
  pkg/factory/shared.go
Labels: ready-to-merge, spark

#10103 [GHC Prime Conference] :memo: Clear up confusing documentation
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/move_task_order/update_m_t_o_post_counseling_information.go
  pkg/gen/primeclient/move_task_order/move_task_order_client.go
  swagger-def/prime.yaml
  swagger/prime.yaml
Labels: Huckleberry

#10136 [ MB-14692, MB-14723 ] Updating consumes and produces all path stanzas
  pkg/gen/adminapi/embedded_spec.go
  swagger-def/admin.yaml
  swagger/admin.yaml
Labels: enhancement, ready-to-merge

#10110 [ MB-14692, MB-14723 ] Apply readOnly where it makes sense for the Admin API
  pkg/gen/adminapi/embedded_spec.go
  pkg/gen/adminmessages/admin_user.go
  pkg/gen/adminmessages/electronic_order.go
  pkg/gen/adminmessages/move.go
  pkg/gen/adminmessages/notification.go
  pkg/gen/adminmessages/office_user.go
  pkg/gen/adminmessages/organization.go
  pkg/gen/adminmessages/role.go
  pkg/gen/adminmessages/transportation_office.go
  pkg/gen/adminmessages/transportation_service_provider_performance.go
  pkg/gen/adminmessages/upload.go
  pkg/gen/adminmessages/user.go
  pkg/gen/adminmessages/webhook_subscription.go
  pkg/handlers/adminapi/admin_users.go
  pkg/handlers/adminapi/electronic_orders.go
  pkg/handlers/adminapi/moves.go
  pkg/handlers/adminapi/notifications.go
  pkg/handlers/adminapi/office_users.go
  pkg/handlers/adminapi/organizations.go
  pkg/handlers/adminapi/users.go
  swagger-def/admin.yaml
  swagger/admin.yaml
Labels: enhancement, infra, ready-to-merge, bug

#10111 [ MB-14692, MB-14723 ] Going from snakecase to kebobcase
  pkg/gen/adminapi/adminoperations/admin_users/create_admin_user.go
  pkg/gen/adminapi/adminoperations/admin_users/create_admin_user_urlbuilder.go
  pkg/gen/adminapi/adminoperations/admin_users/get_admin_user.go
  pkg/gen/adminapi/adminoperations/admin_users/get_admin_user_urlbuilder.go
  pkg/gen/adminapi/adminoperations/admin_users/index_admin_users.go
  pkg/gen/adminapi/adminoperations/admin_users/index_admin_users_urlbuilder.go
  pkg/gen/adminapi/adminoperations/admin_users/update_admin_user.go
  pkg/gen/adminapi/adminoperations/admin_users/update_admin_user_urlbuilder.go
  pkg/gen/adminapi/adminoperations/electronic_order/get_electronic_orders_totals.go
  pkg/gen/adminapi/adminoperations/electronic_order/get_electronic_orders_totals_urlbuilder.go
  pkg/gen/adminapi/adminoperations/electronic_order/index_electronic_orders.go
  pkg/gen/adminapi/adminoperations/electronic_order/index_electronic_orders_urlbuilder.go
  pkg/gen/adminapi/adminoperations/mymove_api.go
  pkg/gen/adminapi/adminoperations/office_users/create_office_user.go
  pkg/gen/adminapi/adminoperations/office_users/create_office_user_urlbuilder.go
  pkg/gen/adminapi/adminoperations/office_users/get_office_user.go
  pkg/gen/adminapi/adminoperations/office_users/get_office_user_urlbuilder.go
  pkg/gen/adminapi/adminoperations/office_users/index_office_users.go
  pkg/gen/adminapi/adminoperations/office_users/index_office_users_urlbuilder.go
  pkg/gen/adminapi/adminoperations/office_users/update_office_user.go
  pkg/gen/adminapi/adminoperations/office_users/update_office_user_urlbuilder.go
  pkg/gen/adminapi/adminoperations/transportation_service_provider_performances/get_t_s_p_p.go
  pkg/gen/adminapi/adminoperations/transportation_service_provider_performances/get_t_s_p_p_urlbuilder.go
  pkg/gen/adminapi/adminoperations/transportation_service_provider_performances/index_t_s_p_ps.go
  pkg/gen/adminapi/adminoperations/transportation_service_provider_performances/index_t_s_p_ps_urlbuilder.go
  pkg/gen/adminapi/adminoperations/webhook_subscriptions/create_webhook_subscription.go
  pkg/gen/adminapi/adminoperations/webhook_subscriptions/create_webhook_subscription_urlbuilder.go
  pkg/gen/adminapi/adminoperations/webhook_subscriptions/get_webhook_subscription.go
  pkg/gen/adminapi/adminoperations/webhook_subscriptions/get_webhook_subscription_urlbuilder.go
  pkg/gen/adminapi/adminoperations/webhook_subscriptions/index_webhook_subscriptions.go
  pkg/gen/adminapi/adminoperations/webhook_subscriptions/index_webhook_subscriptions_urlbuilder.go
  pkg/gen/adminapi/adminoperations/webhook_subscriptions/update_webhook_subscription.go
  pkg/gen/adminapi/adminoperations/webhook_subscriptions/update_webhook_subscription_urlbuilder.go
  pkg/gen/adminapi/embedded_spec.go
  pkg/handlers/adminapi/webhook_subscriptions.go
  pkg/handlers/adminapi/webhook_subscriptions_test.go
  pkg/handlers/authentication/auth_test.go
  pkg/services/audit/audit_test.go
  playwright/tests/admin/adminUsers.spec.js
  playwright/tests/admin/officeUsers.spec.js
  src/scenes/SystemAdmin/Home.jsx
  swagger-def/admin.yaml
  swagger/admin.yaml
Labels: enhancement, ready-to-merge

#10062 [ MB-14692, MB-14723 ] Duplicating tags at the root stanza
  pkg/gen/adminapi/embedded_spec.go
  swagger-def/admin.yaml
  swagger/admin.yaml
Labels: enhancement, ready-to-merge

#10132 [MB-15056] PPM final incentive should re-calculate after updating net weight
  pkg/services/ppmshipment/ppm_estimator.go
  pkg/services/ppmshipment/ppm_estimator_test.go
Labels: Pamplemoose

#10150 MB-15283:deleted shipments are not considered for the TOO queue
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/services/order/order_fetcher.go
Labels: ready-to-merge, Huckleberry

#10171 [ on-call ] Removing old environment constants
  pkg/cli/environment.go
  pkg/cli/session.go
Labels: infra, ready-to-merge, bug

#10174 Added scenarios to devseed data generation for excess weights
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/scenario/subscenarios.go
Labels: Pamplemoose

#10177 MB-14723 fully turn on spectral linting for admin api
  .pre-commit-config.yaml
Labels: enhancement, ready-to-merge
