Repository transcom/mymove, pull requests merged in 2023-11, with the labels that each got.

#11517 B-17748 TOO SIT Entry Date Edit with Correct Service Codes and Audit Log
  pkg/handlers/ghcapi/mto_service_items.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/handlers/ghcapi/payment_request_test.go
  pkg/services/mto_shipment/shipment_sit_status.go
  pkg/services/mto_shipment/shipment_sit_status_test.go
  pkg/services/payment_request/payment_request_shipments_sit_balance.go
  pkg/services/payment_request/payment_request_shipments_sit_balance_test.go
  pkg/services/sit_entry_date_update/sit_entry_date_updater.go
  pkg/services/sit_entry_date_update/sit_entry_date_updater_test.go
  src/components/Office/EditSitEntryDateModal/EditSitEntryDateModal.jsx
  src/components/Office/RequestedServiceItemsTable/RequestedServiceItemsTable.test.jsx
  src/components/Office/ServiceItemDetails/ServiceItemDetails.jsx
  src/components/Office/ServiceItemsTable/ServiceItemsTable.jsx
  src/components/Office/ServiceItemsTable/ServiceItemsTable.module.scss
  src/components/Office/ServiceItemsTable/ServiceItemsTable.test.jsx
  src/components/Office/ShipmentSITDisplay/ShipmentSITDisplay.jsx
  src/components/Office/ShipmentSITDisplay/ShipmentSITDisplay.test.jsx
  src/components/Office/ShipmentSITDisplay/ShipmentSITDisplayTestParams.js
  src/constants/MoveHistory/EventTemplates/UpdateSITEntryDate/updateSitEntryDate.jsx
  src/constants/MoveHistory/EventTemplates/UpdateSITEntryDate/updateSitEntryDate.test.jsx
  src/constants/MoveHistory/EventTemplates/index.js
  src/constants/MoveHistory/UIDisplay/Operations.js
  src/constants/serviceItems.js
  src/pages/Office/MoveHistory/LabeledDetailsWithToolTip.jsx
  src/pages/Office/MoveHistory/LabeledDetailsWithToolTip.test.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.test.jsx
  src/pages/Office/MoveTaskOrder/moveTaskOrderUnitTestData.js
  src/shared/SomethingWentWrong/index.jsx
  src/shared/ToolTip/ToolTip.module.scss
Labels: Mountain Movers

#11509 B 17650 reject unchanged sit request
  pkg/handlers/primeapi/move_task_order_test.go
  pkg/handlers/primeapi/mto_service_item_test.go
  pkg/services/mto_service_item/mto_service_item_updater_test.go
  pkg/services/mto_service_item/mto_service_item_validators.go
  pkg/services/mto_service_item/mto_service_item_validators_test.go
Labels: Mountain Movers

#11529 B-17661 update ShipmentDetailsMain to pass null if requestedPickupDate value
  src/components/Office/ShipmentDetails/ShipmentDetailsMain.jsx
Labels: Scrum Team G

#11533 B-17490 Add Deliveries Table to Database
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20231027204028_add_deliveries_table.up.sql
Labels: Mountain Movers

#11534 B-17662 Add "return to move" link to profile page
  src/pages/MyMove/Profile/Profile.jsx
  src/pages/MyMove/Profile/Profile.test.jsx
Labels: Scrum Team H

#11537 B-17796 Partial PPM Move Not Showing In SC's Closeout Queue
  pkg/handlers/ghcapi/queues.go
  pkg/models/move.go
  pkg/models/move_test.go
  pkg/services/move_task_order/move_task_order_updater.go
  pkg/services/move_task_order/move_task_order_updater_test.go
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/testharness/dispatch.go
  pkg/testdatagen/testharness/make_move.go
  playwright/tests/office/primesimulator/primeSimulatorFlows.spec.js
  playwright/tests/office/servicescounseling/servicesCounselingFlows.spec.js
  playwright/tests/office/servicescounseling/servicesCounselingTestFixture.js
  playwright/tests/utils/office/officeTest.js
  playwright/tests/utils/testharness.js
Labels: ByteSize M&Ms

#11540 B-17477 Add and update weight fields in MTO Shipment Weight
  src/components/Office/ShipmentDetails/ShipmentDetailsMain.jsx
  src/components/Office/ShipmentWeightDetails/ShipmentWeightDetails.jsx
  src/components/Office/ShipmentWeightDetails/ShipmentWeightDetails.test.jsx
Labels: Scrum Team G

#11541 B 17680 Full / Partial PPM Text Not Showing in Closeout Table
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/handlers/internalapi/api.go
  pkg/handlers/internalapi/mto_shipment_test.go
  pkg/handlers/primeapi/api.go
  pkg/handlers/primeapi/mto_shipment_test.go
  pkg/models/move.go
  pkg/services/mocks/MoveTaskOrderUpdater.go
  pkg/services/move_task_order.go
  pkg/services/move_task_order/move_task_order_updater.go
  pkg/services/move_task_order/move_task_order_updater_test.go
  pkg/services/mto_shipment/shipment_deleter.go
  pkg/services/mto_shipment/shipment_deleter_test.go
  pkg/services/orchestrators/shipment/shipment_creator.go
  pkg/services/orchestrators/shipment/shipment_creator_test.go
Labels: ByteSize M&Ms

#11536 B-17574-Partial-Payments
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20231102162954_delete_partial_payments_column.up.sql
  pkg/models/payment_request.go
Labels: Mountain Movers

#11528 B-17754 Added re-rendering action, and the count flag behavior.
  src/components/Office/ShipmentDetails/ShipmentDetailsMain.jsx
  src/pages/Office/MoveDetails/MoveDetails.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
Labels: Scrum Team G

#11558 B-17678 Update DocumentViewer to return to zeroth index when files change
  src/components/DocumentViewer/DocumentViewer.jsx
Labels: Scrum Team G

#11557 B 17664 remove vendor panel on ppm shipments
  src/components/Office/ShipmentForm/ShipmentForm.jsx
  src/components/Office/ShipmentForm/ShipmentForm.test.jsx
Labels: Scrummy Bears

#11551 B 17788 get table rest
  cmd/milmove/serve.go
  pkg/models/trdm_get_table_request.go
  pkg/models/trdm_get_table_response.go
  pkg/models/trdm_last_table_update_response.go
  pkg/trdm/api_gateway.go
  pkg/trdm/get_table.go
  pkg/trdm/get_table_test.go
  pkg/trdm/last_table_update.go
  pkg/trdm/last_table_update_test.go
  pkg/trdm/trdm.go
  pkg/trdm/trdm_test.go
Labels: Mountain Movers

#11542 B-17690-Fix-Progear-Allowance
  pkg/handlers/internalapi/move_dates.go
  pkg/handlers/internalapi/orders.go
  pkg/models/entitlements.go
  pkg/models/entitlements_test.go
  pkg/models/ghc_entitlements.go
  pkg/notifications/move_submitted.go
  pkg/services/move/move_weights.go
Labels: G-Unit

#11559 B 17657 too can view updated sit params on sit resubmission
  src/components/Office/ServiceItemsTable/ResubmittedServiceItemDetails.test.jsx
  src/components/Office/ServiceItemsTable/ServiceItemsTable.jsx
  src/components/Office/ServiceItemsTable/resubmittedServiceItemUnitTestData.js
  src/constants/sitUpdates.js
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.test.jsx
  src/pages/Office/MoveTaskOrder/moveTaskOrderUnitTestData.js
  src/shared/ToolTip/ToolTip.module.scss
Labels: Mountain Movers

#11571 Update Certificate Authority
  config/tls/dod-sw-ca-66.pem
Labels: Mountain Movers

#11572 added josiah
  .github/CODEOWNERS
Labels: Mountain Movers

#11575 Update CA 66 file
  .envrc
  config/tls/dod-sw-ca-66.pem
Labels: Mountain Movers

#11569 E 04372 trdm
  .envrc
  cmd/milmove/serve.go
  go.mod
  go.sum
  pkg/cli/trdm.go
  pkg/factory/x509_cert_factory.go
  pkg/models/mocks/SoapCaller.go
  pkg/models/trdm_get_table_request.go
  pkg/models/trdm_get_table_response.go
  pkg/models/trdm_last_table_update_request.go
  pkg/models/trdm_last_table_update_response.go
  pkg/parser/tac/fixtures/Transportation Account.txt
  pkg/parser/tac/parse_test.go
  pkg/server/server.go
  pkg/testdatagen/shared.go
  pkg/trdm/api_gateway.go
  pkg/trdm/get_table.go
  pkg/trdm/get_table_test.go
  pkg/trdm/last_table_update.go
  pkg/trdm/last_table_update_test.go
  pkg/trdm/trdm.go
  pkg/trdm/trdm_test.go
Labels: Mountain Movers

#11560 B-17477 Revert some changes in ShipmentWeightDetails to fix bug
  src/components/Office/ShipmentDetails/ShipmentDetailsMain.jsx
  src/components/Office/ShipmentWeightDetails/ShipmentWeightDetails.jsx
  src/components/Office/ShipmentWeightDetails/ShipmentWeightDetails.test.jsx
Labels: G-Unit

#11570 B 17814 rename military bases
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20231116162824_update_addresses_table_with_new_base_names.up.sql
  playwright/tests/my/mymove/onboarding.spec.js
Labels: Mountain Movers

#11547 B 17615 weight ticket designator for payment request uploads
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20231109142950_add-weight-ticket-boolean-to-uploads-table.up.sql
  pkg/factory/proof_of_service_doc_factory.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/proof_of_service_doc.go
  pkg/gen/ghcmessages/upload.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/upload.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/payment_request/create_upload.go
  pkg/gen/primeapi/primeoperations/payment_request/create_upload_parameters.go
  pkg/gen/primeclient/payment_request/create_upload_parameters.go
  pkg/gen/primeclient/payment_request/payment_request_client.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload_test.go
  pkg/handlers/ghcapi/internal/payloads/payloads_test.go
  pkg/handlers/primeapi/upload.go
  pkg/handlers/primeapi/upload_test.go
  pkg/models/proof_of_service_doc.go
  pkg/services/mocks/PaymentRequestUploadCreator.go
  pkg/services/payment_request.go
  pkg/services/payment_request/upload_creator.go
  pkg/services/payment_request/upload_creator_test.go
  src/pages/PrimeUI/UploadPaymentRequestDocuments/UploadPaymentRequestDocuments.jsx
  src/pages/PrimeUI/UploadPaymentRequestDocuments/UploadPaymentRequestDocuments.test.jsx
  src/services/primeApi.js
  swagger-def/definitions/Upload.yaml
  swagger-def/definitions/prime/ProofOfServiceDoc.yaml
  swagger-def/ghc.yaml
  swagger-def/prime.yaml
  swagger/ghc.yaml
  swagger/internal.yaml
  swagger/prime.yaml
Labels: Mountain Movers

#11544 B-17677: tooltip for incomplete ppm shipment on summary page
  src/components/Customer/Review/IncompleteShipmentModal/IncompleteShipmentModal.jsx
  src/components/Customer/Review/IncompleteShipmentModal/IncompleteShipmentModal.module.scss
  src/components/Customer/Review/IncompleteShipmentModal/IncompleteShipmentModal.stories.jsx
  src/components/Customer/Review/IncompleteShipmentModal/IncompleteShipmentModal.test.jsx
  src/components/Customer/Review/IncompleteShipmentToolTip/IncompleteShipmentToolTip.jsx
  src/components/Customer/Review/IncompleteShipmentToolTip/IncompleteShipmentToolTip.module.scss
  src/components/Customer/Review/Review.stories.jsx
  src/components/Customer/Review/ShipmentCard/HHGShipmentCard/HHGShipmentCard.jsx
  src/components/Customer/Review/ShipmentCard/HHGShipmentCard/HHGShipmentCard.test.jsx
  src/components/Customer/Review/ShipmentCard/NTSRShipmentCard/NTSRShipmentCard.jsx
  src/components/Customer/Review/ShipmentCard/NTSRShipmentCard/NTSRShipmentCard.test.jsx
  src/components/Customer/Review/ShipmentCard/NTSShipmentCard/NTSShipmentCard.jsx
  src/components/Customer/Review/ShipmentCard/NTSShipmentCard/NTSShipmentCard.test.jsx
  src/components/Customer/Review/ShipmentCard/PPMShipmentCard/PPMShipmentCard.jsx
  src/components/Customer/Review/ShipmentCard/PPMShipmentCard/PPMShipmentCard.test.jsx
  src/components/Customer/Review/ShipmentCard/ShipmentCard.stories.jsx
  src/components/Customer/Review/Summary/Summary.jsx
  src/components/ShipmentList/ShipmentList.jsx
  src/utils/shipmentDisplay.jsx
  src/utils/shipmentDisplay.test.jsx
Labels: Scrummy Bears

#11582 updated trdm environment
  cmd/milmove/serve.go
Labels: Mountain Movers

#11576 B-17836 Add Space Force to Branch of Service
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/affiliation.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/affiliation.go
  pkg/gen/ordersapi/embedded_spec.go
  pkg/gen/ordersmessages/affiliation.go
  pkg/models/service_member.go
  playwright/tests/my/mymove/onboarding.spec.js
  src/constants/orders.js
  src/constants/queues.js
  src/content/serviceMemberAgencies.js
  src/scenes/Office/queueTableColumns.js
  swagger-def/definitions/Affiliation.yaml
  swagger/ghc.yaml
  swagger/internal.yaml
  swagger/orders.yaml
Labels: ByteSize M&Ms

#11556 B 17588 enable prime to add partial weight
  pkg/handlers/primeapi/allowed_payment_service_item_params.go
Labels: Mountain Movers

#11586 B 17588 prime sim updates
  src/components/PrimeUI/CreatePaymentRequestForm/CreatePaymentRequestForm.jsx
  src/components/PrimeUI/CreatePaymentRequestForm/CreatePaymentRequestForm.module.scss
  src/components/PrimeUI/CreatePaymentRequestForm/CreatePaymentRequestForm.test.jsx
  src/components/PrimeUI/ServiceItem/ServiceItem.jsx
  src/components/PrimeUI/ServiceItem/ServiceItem.test.jsx
  src/constants/serviceItems.js
  src/pages/PrimeUI/CreatePaymentRequest/CreatePaymentRequest.jsx
Labels: Mountain Movers

#11592 Increasing TRDM timeout
  cmd/milmove/serve.go
Labels: Mountain Movers

#11593 reverting trdm tls to default
  cmd/milmove/serve.go
Labels: Mountain Movers

#11594 removed early body closing
  pkg/trdm/api_gateway.go
Labels: Mountain Movers

#11595 more detailed logging
  pkg/trdm/last_table_update.go
Labels: Mountain Movers

#11591 B-17615 isWeightTicket Optional Param & Prev PR
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20231122171913_add_weight_ticket_boolean_to_uploads_table.up.sql
  pkg/factory/proof_of_service_doc_factory.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/proof_of_service_doc.go
  pkg/gen/ghcmessages/upload.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/upload.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/payment_request/create_upload.go
  pkg/gen/primeapi/primeoperations/payment_request/create_upload_parameters.go
  pkg/gen/primeclient/payment_request/create_upload_parameters.go
  pkg/gen/primeclient/payment_request/payment_request_client.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload_test.go
  pkg/handlers/ghcapi/internal/payloads/payloads_test.go
  pkg/handlers/primeapi/upload.go
  pkg/handlers/primeapi/upload_test.go
  pkg/models/proof_of_service_doc.go
  pkg/services/mocks/PaymentRequestUploadCreator.go
  pkg/services/payment_request.go
  pkg/services/payment_request/upload_creator.go
  pkg/services/payment_request/upload_creator_test.go
  src/pages/PrimeUI/UploadPaymentRequestDocuments/UploadPaymentRequestDocuments.jsx
  src/pages/PrimeUI/UploadPaymentRequestDocuments/UploadPaymentRequestDocuments.test.jsx
  src/services/primeApi.js
  swagger-def/definitions/Upload.yaml
  swagger-def/ghc.yaml
  swagger-def/prime.yaml
  swagger/ghc.yaml
  swagger/internal.yaml
  swagger/prime.yaml
Labels: Mountain Movers

#11581 B-17828-Prime API Doc Updates for SIT
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/payment_request/create_payment_request.go
  pkg/gen/primeclient/payment_request/payment_request_client.go
  swagger-def/prime.yaml
  swagger/prime.yaml
Labels: Mountain Movers

#11597 B-17615 migration file changes
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20231122171913_add_weight_ticket_boolean_to_uploads_table.up.sql
  migrations/app/schema/20231127152248_remove_not_null_constraint_from_is_weight_ticket_column.up.sql
Labels: Mountain Movers

#11598 adding error stack trace
  pkg/trdm/last_table_update.go
Labels: Mountain Movers

#11568 B 17842 New Department Indicators on Orders View/Edit Page
  migrations/app/schema/20200827155542_add_db_comments.up.sql
  pkg/factory/order_factory.go
  pkg/factory/order_factory_test.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/dept_indicator.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/dept_indicator.go
  pkg/gen/supportapi/embedded_spec.go
  pkg/gen/supportmessages/dept_indicator.go
  pkg/handlers/internalapi/orders_test.go
  pkg/handlers/supportapi/move_task_order_test.go
  pkg/paperwork/forms.go
  pkg/services/invoice/ghc_payment_request_invoice_generator.go
  pkg/services/invoice/ghc_payment_request_invoice_generator_test.go
  pkg/testdatagen/make_order.go
  pkg/testdatagen/scenario/e2ebasic.go
  playwright/tests/office/servicescounseling/servicesCounselingFlows.spec.js
  playwright/tests/office/txo/tooFlows.spec.js
  playwright/tests/utils/office/officeTest.js
  src/constants/MoveHistory/Database/OptionFields.js
  src/constants/departmentIndicators.js
  src/constants/orders.js
  src/pages/Office/MoveAllowances/MoveAllowances.test.jsx
  src/pages/Office/MoveDocumentWrapper/MoveDocumentWrapper.test.jsx
  src/pages/Office/MoveHistory/LabeledDetails.test.jsx
  src/pages/Office/MoveTaskOrder/moveTaskOrderUnitTestData.js
  src/pages/Office/Orders/Orders.test.jsx
  src/pages/Office/PaymentRequestQueue/PaymentRequestQueue.test.jsx
  src/pages/Office/ReviewBillableWeight/ReviewBillableWeight.test.jsx
  src/pages/Office/ServicesCounselingMoveAllowances/ServicesCounselingMoveAllowances.test.jsx
  src/pages/Office/ServicesCounselingMoveDocumentWrapper/ServicesCounselingMoveDocumentWrapper.test.jsx
  src/pages/Office/ServicesCounselingOrders/ServicesCounselingOrders.test.jsx
  swagger-def/ghc.yaml
  swagger-def/internal.yaml
  swagger-def/support.yaml
  swagger/ghc.yaml
  swagger/internal.yaml
  swagger/support.yaml
Labels: ByteSize M&Ms

#11601 refactor how tget data out of date is calculated
  pkg/trdm/last_table_update.go
  pkg/trdm/last_table_update_test.go
Labels: Mountain Movers

#11587 B 17814 Removing references to Fort Benning and removing incorrect link between Fort Walker and Fort Benning.
  migrations/app/schema/20231116162824_update_addresses_table_with_new_base_names.up.sql
  pkg/edi/invoice/generator_test.go
  pkg/factory/duty_location_factory.go
  pkg/factory/duty_location_factory_test.go
  pkg/factory/order_factory_test.go
  pkg/handlers/ghcapi/queues_test.go
  pkg/handlers/internalapi/moves_test.go
  pkg/handlers/internalapi/service_members_test.go
  pkg/models/shipment_summary_worksheet.go
  pkg/models/shipment_summary_worksheet_test.go
  pkg/services/invoice/ghc_payment_request_invoice_generator_test.go
  pkg/services/order/order_fetcher_test.go
  pkg/services/payment_request/payment_request_creator_test.go
  pkg/services/payment_request/payment_request_recalculator_test.go
  pkg/testdatagen/make_duty_location.go
  pkg/testdatagen/testharness/make_move.go
  yarn.lock
Labels: Mountain Movers

#11561 B-17812 fix label shifting on error
  src/components/Customer/PPM/PPM.module.scss
  src/components/form/fields/MaskedTextField/MaskedTextField.module.scss
  src/styles/form.module.scss
Labels: G-Unit

#11600 B-17900: Add weight billed field to additional serviceitems
  src/components/PrimeUI/CreatePaymentRequestForm/CreatePaymentRequestForm.jsx
  src/components/PrimeUI/CreatePaymentRequestForm/CreatePaymentRequestForm.test.jsx
Labels: Mountain Movers

#11602 B-17657 TOO Viewing Updating Parameters - Fix issue I-12140 tooltip displaying same info for service items
  src/components/Office/ServiceItemsTable/ServiceItemsTable.jsx
Labels: Mountain Movers

#11603 increased TRDM logging and removed deprecated func
  pkg/trdm/get_table.go
  pkg/trdm/get_table_test.go
  pkg/trdm/last_table_update.go
  pkg/trdm/last_table_update_test.go
Labels: Mountain Movers

#11605 Refactored to pass our latest update for tget data to retrieve
  pkg/trdm/last_table_update.go
  pkg/trdm/last_table_update_test.go
Labels: Mountain Movers

#11608 B17814 fix fort walker rename
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20231116162824_update_addresses_table_with_new_base_names.up.sql
  migrations/app/schema/20231128203410_update_addresses_and_duty_locations_for_base_renames.up.sql
Labels: Mountain Movers

#11609 B17814 Update orders table to reference renamed duty locations before deleting old base names from duty_locations table
  migrations/app/schema/20231128203410_update_addresses_and_duty_locations_for_base_renames.up.sql
Labels: Mountain Movers

#11583 B 17850 error message
  src/components/Customer/BackupContactForm/BackupContactForm.test.jsx
  src/components/Customer/ContactInfoForm/ContactInfoForm.test.jsx
  src/components/Office/CustomerContactInfoForm/CustomerContactInfoForm.jsx
  src/shared/JsonSchemaForm/JsonSchemaField.js
  src/shared/JsonSchemaForm/validations.test.js
  src/utils/validation.js
Labels: G-Unit

#11610 Break trdm into week based requests
  pkg/models/trdm_get_table_request.go
  pkg/trdm/get_table.go
  pkg/trdm/get_table_test.go
  pkg/trdm/last_table_update.go
  pkg/trdm/last_table_update_test.go
Labels: Mountain Movers

#11611 Revert "Merge pull request #11610 from transcom/break-trdm-into-week-…
  pkg/models/trdm_get_table_request.go
  pkg/trdm/get_table.go
  pkg/trdm/get_table_test.go
  pkg/trdm/last_table_update.go
  pkg/trdm/last_table_update_test.go
Labels: Mountain Movers

#11585 B 17827 move history logs Destination SIT address changes
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20231120140417_create_sit_address_updates_trigger.up.sql
  pkg/assets/sql_scripts/move_history_fetcher.sql
  src/constants/MoveHistory/Database/FieldMappings.js
  src/constants/MoveHistory/Database/Tables.js
  src/constants/MoveHistory/EventTemplates/CreateSITRequest/CreateSITAddressUpdateRequest.jsx
  src/constants/MoveHistory/EventTemplates/CreateSITRequest/CreateSITAddressUpdateRequest.test.jsx
  src/constants/MoveHistory/EventTemplates/UpdateSITAddress/ApproveSITAddressUpdate.jsx
  src/constants/MoveHistory/EventTemplates/UpdateSITAddress/ApproveSITAddressUpdate.test.jsx
  src/constants/MoveHistory/EventTemplates/UpdateSITAddress/CreateSITAddressUpdate.jsx
  src/constants/MoveHistory/EventTemplates/UpdateSITAddress/CreateSITAddressUpdate.test.jsx
  src/constants/MoveHistory/EventTemplates/UpdateSITAddress/RejectSITAddressUpdate.jsx
  src/constants/MoveHistory/EventTemplates/UpdateSITAddress/RejectSITAddressUpdate.test.jsx
  src/constants/MoveHistory/EventTemplates/index.js
  src/constants/MoveHistory/UIDisplay/Operations.js
  src/constants/sitUpdates.js
  src/utils/formatSITData.js
  src/utils/formatSITData.test.js
Labels: G-Unit

#11604 B 17781 billing sit fsc
  pkg/models/mto_service_items.go
  pkg/services/mto_service_item/mto_service_item_updater.go
  pkg/services/sit_address_update/sit_address_update_request_approver.go
  pkg/testdatagen/testharness/dispatch.go
  pkg/testdatagen/testharness/make_move.go
  playwright/tests/office/txo/sitUpdates.spec.js
  playwright/tests/utils/office/officeTest.js
  playwright/tests/utils/testharness.js
Labels: ByteSize M&Ms

#11612 Added weight billed to DDSFSC
  pkg/handlers/primeapi/allowed_payment_service_item_params.go
  src/components/PrimeUI/CreatePaymentRequestForm/CreatePaymentRequestForm.jsx
Labels: Mountain Movers
