Repository transcom/mymove, pull requests merged in 2023-06, with the labels that each got.

#10787 [MB-15809] TOO can view sit delivery address section in modal
  src/components/Office/ServiceItemUpdateModal/ReviewSitAddressChange.jsx
  src/components/Office/ServiceItemUpdateModal/ServiceItemUpdateModal.jsx
  src/components/Office/ServiceItemUpdateModal/ServiceItemUpdateModal.module.scss
  src/components/Office/ServiceItemUpdateModal/ServiceItemUpdateModal.stories.jsx
  src/components/Office/ServiceItemUpdateModal/ServiceItemUpdateModal.test.jsx
  src/components/Office/ServiceItemUpdateModal/ServiceItemUpdateModalTestParams.js
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
  src/utils/serviceItems.js
  src/utils/serviceItems.test.js
Labels: Pamplemoose

#10803 [MB-15876] tracking untracked files
  pkg/services/mocks/SITAddressUpdateRequestApprover.go
  pkg/services/mocks/SITAddressUpdateRequestRejector.go
Labels: Pamplemoose

#10804 MB-15974: update storybook dependencies
  package.json
  yarn.lock
Labels: dependencies, A-Team

#10819 MB-16193 Create a swagger endpoint for creating a service request document upload
  pkg/gen/primeapi/configure_mymove.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/mto_service_item/create_service_request_document_upload.go
  pkg/gen/primeapi/primeoperations/mto_service_item/create_service_request_document_upload_parameters.go
  pkg/gen/primeapi/primeoperations/mto_service_item/create_service_request_document_upload_responses.go
  pkg/gen/primeapi/primeoperations/mto_service_item/create_service_request_document_upload_urlbuilder.go
  pkg/gen/primeapi/primeoperations/mymove_api.go
  pkg/gen/primeclient/mto_service_item/create_service_request_document_upload_parameters.go
  pkg/gen/primeclient/mto_service_item/create_service_request_document_upload_responses.go
  pkg/gen/primeclient/mto_service_item/mto_service_item_client.go
  swagger-def/prime.yaml
  swagger/prime.yaml
Labels: enhancement

#10828 MB-16168: fix crud auth failure by implementing driver.DriverContext
  pkg/cli/dbconn.go
  pkg/iampostgres/iampostgres.go
  pkg/iampostgres/iampostgres_test.go
  pkg/testingsuite/pop_suite.go
  pkg/testingsuite/pop_suite_txn.go
Labels: ready-to-merge

#10830 Re-enabling the prime API in the production env
  config/env/prd.app-client-tls.env
Labels: Huckleberry

#10840 [MB-16230] Added new secure migration for fixing the escalation in the pricing data
  migrations/app/migrations_manifest.txt
  migrations/app/secure/20230605145747_fix_pricing_data_escalation.up.sql
Labels: ttv

#10805 MB-15974 - upgrades react-router and react-router-dom versions
  package.json
  src/constants/routes.js
  src/pages/Office/ServicesCounselingMoveInfo/ServicesCounselingMoveInfo.test.jsx
  src/pages/Office/index.test.jsx
  yarn.lock
Labels: dependencies, A-Team

#10839 [ MB-16244 ] Addition of reweighs to query for updated-since params in list prime moves
  pkg/services/move_task_order/move_task_order_fetcher.go
  pkg/services/move_task_order/move_task_order_fetcher_test.go
Labels: ready-to-merge, Huckleberry

#10855 [ DEMO Prep ] Adding reason field to the Prime UI for destination SIT service items
  src/components/PrimeUI/CreateShipmentServiceItemForm/DestinationSITServiceItemForm.jsx
Labels: ready-to-merge

#10829 [MB-16218] service request documents uploader
  pkg/factory/service_request_document_factory.go
  pkg/factory/service_request_document_factory_test.go
  pkg/factory/service_request_document_upload_factory.go
  pkg/factory/service_request_document_upload_factory_test.go
  pkg/factory/shared.go
  pkg/handlers/ghcapi/mto_service_items_test.go
  pkg/models/invoice_test.go
  pkg/models/service_request_document_upload.go
  pkg/models/service_request_document_upload_test.go
  pkg/unit/dollars_test.go
  pkg/uploader/service_request_uploader.go
  pkg/uploader/service_request_uploader_test.go
Labels: ready-to-merge

#10858 fix: send psql `stdout`/`stderr` to `/dev/null` when checking the db connection
  scripts/wait-for-db
Labels: A-Team

#10864 For now, test coverage reduction will not fail the build
  scripts/ensure-go-test-coverage
  scripts/ensure-js-test-coverage
Labels: ready-to-merge

#10807 MB-15880: Approve/Reject SIT Address Update Request in Modal
  src/components/Office/ServiceItemUpdateModal/ReviewSitAddressChange.jsx
  src/components/Office/ServiceItemUpdateModal/ServiceItemUpdateModal.test.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
  src/services/ghcApi.js
Labels: Pamplemoose, ready-to-merge

#10863 [MB-16188] contractor remarks now required
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/create_s_i_t_address_update_request.go
  pkg/handlers/primeapi/payloads/payload_to_model.go
  pkg/handlers/primeapi/payloads/payload_to_model_test.go
  pkg/handlers/primeapi/sit_service_item_address_update_test.go
  swagger-def/prime.yaml
  swagger/prime.yaml
Labels: Pamplemoose, ready-to-merge, bug

#10806 [ MB-16199 ] Ensure service items have an origin and final destination address
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/mto_service_items_test.go
  pkg/handlers/primeapi/api.go
  pkg/handlers/primeapi/mto_service_item_test.go
  pkg/handlers/supportapi/api.go
  pkg/handlers/supportapi/mto_service_item_test.go
  pkg/services/move_history/move_history_fetcher_test.go
  pkg/services/mto_service_item/mto_service_item_updater.go
  pkg/services/mto_service_item/mto_service_item_updater_test.go
  pkg/services/sit_address_update/approved_sit_address_update_creator_test.go
  pkg/services/sit_address_update/sit_address_update_request_approver_test.go
  pkg/testdatagen/scenario/devseed.go
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/scenario/subscenarios.go
Labels: Pamplemoose, bug

#10879 MB-16229 remove unneeded TIO permissions
  pkg/handlers/authentication/auth_test.go
  pkg/handlers/authentication/permissions.go
Labels: A-Team, ready-to-merge

#10844 MBN-16222 Add handler for proof of service document upload
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20230612172652_alter_service_request_documents_table_change_contstraints.up.sql
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/m_t_o_service_item.go
  pkg/gen/primemessages/m_t_o_service_item_basic.go
  pkg/gen/primemessages/m_t_o_service_item_dest_s_i_t.go
  pkg/gen/primemessages/m_t_o_service_item_domestic_crating.go
  pkg/gen/primemessages/m_t_o_service_item_origin_s_i_t.go
  pkg/gen/primemessages/m_t_o_service_item_shuttle.go
  pkg/gen/primemessages/service_request_document.go
  pkg/gen/primemessages/service_request_documents.go
  pkg/handlers/primeapi/api.go
  pkg/handlers/primeapi/payloads/model_to_payload.go
  pkg/handlers/primeapi/payloads/payload_to_model.go
  pkg/handlers/primeapi/service_request_document_upload.go
  pkg/handlers/primeapi/service_request_document_upload_test.go
  pkg/models/mto_service_items.go
  swagger-def/prime.yaml
  swagger/prime.yaml
Labels: ready-to-merge

#10789 MB-16154: modify distance zip sit dest param
  pkg/payment_request/service_param_value_lookups/distance_zip_sit_dest_lookup_test.go
  pkg/payment_request/service_param_value_lookups/service_param_value_lookups.go
  pkg/testdatagen/scenario/shared.go
Labels: ready-to-merge, Huckleberry

#10842 MB-16162: add param for original zip
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20230605164714_add_ZipSITDestHHGOriginalAddress_param_key.up.sql
  migrations/app/schema/20230605164754_add_ZipSITDestHHGOriginalAddress_param_for_DDDSIT_service_item.up.sql
  migrations/app/schema/20230605174844_delete_ZipDestAddress_for_DDDSIT_service_item.up.sql
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/service_item_param_name.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/service_item_param_name.go
  pkg/models/service_item_param_key.go
  pkg/payment_request/service_param_value_lookups/service_param_value_lookups.go
  pkg/services/ghcrateengine/domestic_destination_sit_delivery_pricer.go
  pkg/services/ghcrateengine/domestic_destination_sit_delivery_pricer_test.go
  pkg/services/ghcrateengine/pricer_helpers.go
  pkg/services/ghcrateengine/pricer_helpers_test.go
  src/components/Office/ServiceItemCalculations/helpers.js
  src/components/Office/ServiceItemCalculations/serviceItemTestParams.js
  src/constants/serviceItems.js
  swagger-def/definitions/ServiceItemParamName.yaml
  swagger/ghc.yaml
  swagger/prime.yaml
Labels: ready-to-merge, Huckleberry

#10877 MB-16297: Update the SITScheduleDest param to look at the final destination address
  pkg/payment_request/service_param_value_lookups/service_param_value_lookups.go
  pkg/payment_request/service_param_value_lookups/sit_schedule_lookup_test.go
Labels: ready-to-merge, Huckleberry

#10875 MB-16198 - Restrict sit address updates to DDDSIT
  pkg/services/sit_address_update/approved_sit_address_update_creator.go
  pkg/services/sit_address_update/approved_sit_address_update_creator_test.go
  pkg/services/sit_address_update/rules.go
  pkg/services/sit_address_update/rules_test.go
  pkg/services/sit_address_update/sit_address_update_request_creator.go
  pkg/services/sit_address_update/sit_address_update_request_creator_test.go
Labels: Pamplemoose

#10886 [MB-16340] Calculating the Required Delivery Date for the same ZIP 5s should enforce a 1 mile minimum
  pkg/route/hhg_planner.go
  pkg/route/hhg_planner_test.go
Labels: ready-to-merge

#10857 MB-16221: add middleware to internal api to ensure users are service members
  pkg/handlers/authentication/auth.go
  pkg/handlers/authentication/auth_test.go
  pkg/handlers/routing/routing_init.go
Labels: A-Team, ready-to-merge

#10884 [MB-16227] Set a nil destination address for an HHG to new duty station location address
  pkg/services/mto_shipment/mto_shipment_creator.go
  pkg/services/mto_shipment/mto_shipment_creator_test.go
  pkg/services/mto_shipment/mto_shipment_updater.go
  playwright/tests/my/mymove/hhg.spec.js
Labels: ttv, ready-to-merge

#10896 MB-16168: more auth failure fixes and logging
  pkg/iampostgres/iampostgres.go
  pkg/iampostgres/rdsutilservice.go
Labels: ready-to-merge

#10906 MB-16357 populate SITDestinationFinalAddress when TOO approves DDDSIT
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/mto_service_items_test.go
  pkg/handlers/primeapi/api.go
  pkg/handlers/primeapi/mto_service_item_test.go
  pkg/handlers/supportapi/api.go
  pkg/handlers/supportapi/mto_service_item_test.go
  pkg/services/move_history/move_history_fetcher_test.go
  pkg/services/mto_service_item/mto_service_item_updater.go
  pkg/services/mto_service_item/mto_service_item_updater_test.go
  pkg/services/sit_address_update/approved_sit_address_update_creator_test.go
  pkg/services/sit_address_update/sit_address_update_request_approver_test.go
  pkg/testdatagen/scenario/shared.go
Labels: Pamplemoose, ready-to-merge

#10866 [MB-16228] Add migration to populate mto_shipments table for shipments without a destination address
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20230609214930_populate_existing_mto_shipments_without_destination_address_to_use_destination_duty_location_address.up.sql
Labels: ready-to-merge

#10914 [MB-16236] Added/removed resolutions to force newer versions
  package.json
  yarn.lock
Labels: dependencies

#10913 MB-16346: update order for task orders requirements
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20230614181842_add_columns_for_task_order_compliance.up.sql
  migrations/app/schema/20230614205339_populate_orders_with_task_order_compliance_data.up.sql
  pkg/factory/order_factory.go
  pkg/handlers/internalapi/orders.go
  pkg/handlers/internalapi/orders_test.go
  pkg/models/order.go
  pkg/models/order_test.go
  pkg/models/service_member.go
  pkg/models/service_member_test.go
  pkg/services/support/move_task_order/move_task_order_creator.go
  pkg/testdatagen/make_order.go
Labels: ready-to-merge, Huckleberry

#10934 Update typo
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/service_item.go
  swagger-def/prime.yaml
  swagger/prime.yaml
Labels: ready-to-merge

#10929 [ MB-15560 ] Adding expired devlocal certs for local testing purposes
  .pre-commit-config.yaml
  config/tls/devlocal-mtls-expired.cer
  config/tls/devlocal-mtls-expired.key
Labels: ready-to-merge, Huckleberry

#10930 MB-16219 create seed data for address change
  pkg/factory/move_factory.go
  pkg/factory/shared.go
  pkg/factory/shipment_address_update_factory.go
  pkg/factory/shipment_address_update_factory_test.go
  pkg/testdatagen/scenario/devseed.go
  pkg/testdatagen/scenario/subscenarios.go
Labels: ttv

#10935 Fix approve icon for Service Item Table
  src/components/Office/ServiceItemsTable/ServiceItemsTable.jsx
  src/components/Office/ServiceItemsTable/ServiceItemsTable.test.jsx
Labels: enhancement, Pamplemoose, bug

#10950 [MB-16412] Add orders nil checks in EDI 858 generation and additional logging fo…
  pkg/services/invoice/ghc_payment_request_invoice_generator.go
  pkg/services/payment_request/payment_request_reviewed_processor.go
Labels: ttv

#10880 [ MB-16199 ] Updating test harness scenarios
  pkg/testdatagen/testharness/make_move.go
  playwright/tests/office/txo/tooFlows.spec.js
Labels: enhancement, Pamplemoose, ready-to-merge

#10951 [MB-16412] hoist nil check to cover multiple edi sections where orders GBLOC omi…
  pkg/services/invoice/ghc_payment_request_invoice_generator.go
  pkg/services/invoice/ghc_payment_request_invoice_generator_test.go
Labels: ttv

#10916 MB-16029, MB-16381 - Edit sit in any status
  Makefile
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/s_i_t_status.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/services/mto_shipment.go
  pkg/services/mto_shipment/shipment_sit_status.go
  pkg/services/mto_shipment/shipment_sit_status_test.go
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/testharness/dispatch.go
  pkg/testdatagen/testharness/make_move.go
  playwright/tests/utils/testharness.js
  src/components/Office/ReviewSITExtensionModal/ReviewSITExtensionModal.jsx
  src/components/Office/ReviewSITExtensionModal/ReviewSITExtensionModal.test.jsx
  src/components/Office/ShipmentSITDisplay/ShipmentSITDisplay.jsx
  src/components/Office/ShipmentSITDisplay/ShipmentSITDisplay.test.jsx
  src/components/Office/ShipmentSITDisplay/ShipmentSITDisplayTestParams.js
  src/components/Office/SubmitSITExtensionModal/SubmitSITExtensionModal.jsx
  src/types/sitStatusShape.js
  swagger-def/definitions/SITStatus.yaml
  swagger/ghc.yaml
Labels: Pamplemoose

#10905 [MB-15939] Update GHC API to Retrieve Documents Stored by Prime for Service Items
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/m_t_o_service_item.go
  pkg/gen/ghcmessages/service_request_document.go
  pkg/gen/ghcmessages/service_request_documents.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/mto_service_items.go
  pkg/handlers/ghcapi/mto_service_items_test.go
  pkg/handlers/ghcapi/mto_shipment.go
  pkg/services/move_task_order/move_task_order_fetcher.go
  pkg/services/move_task_order/move_task_order_fetcher_test.go
  swagger-def/definitions/MTOServiceItem.yaml
  swagger-def/definitions/ServiceRequestDocument.yaml
  swagger-def/definitions/ServiceRequestDocuments.yaml
  swagger/ghc.yaml
Labels: A-Team, ready-to-merge

#10944 MB-16399 update SITDestinationFinalAddress with approved sit address update
  pkg/handlers/primeapi/api.go
  pkg/handlers/primeapi/sit_service_item_address_update_test.go
  pkg/services/sit_address_update/sit_address_update_request_creator.go
  pkg/services/sit_address_update/sit_address_update_request_creator_test.go
Labels: Pamplemoose

#10917 [MB-16348] backend adding date of contact for service items
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20230614231637_add_date_of_contact_column_to_mto_service_item_customer_contacts_table.up.sql
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/m_t_o_service_item_customer_contact.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/mto_service_item/create_m_t_o_service_item.go
  pkg/gen/primeclient/mto_service_item/mto_service_item_client.go
  pkg/gen/primemessages/m_t_o_service_item_dest_s_i_t.go
  pkg/gen/primemessages/update_m_t_o_service_item_s_i_t.go
  pkg/gen/supportapi/embedded_spec.go
  pkg/gen/supportmessages/m_t_o_service_item_dest_s_i_t.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/primeapi/move_task_order_test.go
  pkg/handlers/primeapi/mto_service_item_test.go
  pkg/handlers/primeapi/payloads/model_to_payload.go
  pkg/handlers/primeapi/payloads/payload_to_model.go
  pkg/handlers/primeapi/payloads/payload_to_model_test.go
  pkg/handlers/supportapi/internal/payloads/model_to_payload.go
  pkg/models/mto_service_item_customer_contacts.go
  pkg/models/mto_service_item_customer_contacts_test.go
  pkg/services/event/notification_test.go
  pkg/services/move_history/move_history_fetcher_test.go
  pkg/services/mto_service_item/mto_service_item_creator_test.go
  pkg/services/mto_service_item/mto_service_item_updater_test.go
  pkg/services/mto_service_item/mto_service_item_validators.go
  pkg/services/mto_service_item/mto_service_item_validators_test.go
  pkg/testdatagen/make_mto_service_item_customer_contact.go
  pkg/testdatagen/scenario/e2ebasic.go
  pkg/testdatagen/scenario/shared.go
  src/components/PrimeUI/CreateShipmentServiceItemForm/DestinationSITServiceItemForm.jsx
  swagger-def/definitions/MTOServiceItemCustomerContact.yaml
  swagger-def/prime.yaml
  swagger-def/support.yaml
  swagger/ghc.yaml
  swagger/prime.yaml
  swagger/support.yaml
Labels: enhancement, Pamplemoose, ready-to-merge

#10961 [ MB-16381, MB-16029 ] Fixing bug around SIT Status
  src/components/Office/ShipmentSITDisplay/ShipmentSITDisplay.jsx
Labels: Pamplemoose, ready-to-merge, bug

#10959 MB-16219 Allow address customization in shipment_address_update
  pkg/factory/shared.go
  pkg/factory/shipment_address_update_factory.go
Labels: ttv

#10957 MB-16219 Set available to prime in shipment address update traits
  pkg/factory/shipment_address_update_factory.go
  pkg/factory/shipment_address_update_factory_test.go
Labels: ttv, ready-to-merge

#10938 MB-16416: Add auth integration tests
  pkg/auth/session.go
  pkg/factory/admin_user_factory.go
  pkg/factory/client_cert_factory.go
  pkg/factory/client_cert_factory_test.go
  pkg/factory/office_user_factory.go
  pkg/factory/service_member_factory.go
  pkg/factory/user_factory.go
  pkg/handlers/authentication/auth.go
  pkg/handlers/authentication/auth_test.go
  pkg/handlers/authentication/client_cert.go
  pkg/handlers/authentication/login_gov.go
  pkg/handlers/routing/adminapi_test/admin_users_test.go
  pkg/handlers/routing/adminapi_test/adminapi_test.go
  pkg/handlers/routing/base_routing_suite.go
  pkg/handlers/routing/ghcapi_test/customer_test.go
  pkg/handlers/routing/ghcapi_test/ghcapi_test.go
  pkg/handlers/routing/internalapi_test/internal_api_test.go
  pkg/handlers/routing/internalapi_test/logged_in_test.go
  pkg/handlers/routing/internalapi_test/moves_test.go
  pkg/handlers/routing/primeapi_test/moves_test.go
  pkg/handlers/routing/primeapi_test/primeapi_test.go
  pkg/handlers/routing/routing_init_test.go
  pkg/notifications/client_cert_modified_test.go
  pkg/testdatagen/make_client_cert.go
  pkg/testdatagen/scenario/shared.go
Labels: ready-to-merge

#10915 MB-16119 Create new endpoint, definitions, handler, payload to model, and model to payload, mock service obj, error cases, etc. for Non SIT address changes
  pkg/gen/primeapi/configure_mymove.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/mto_shipment/create_non_s_i_t_address_update_request.go
  pkg/gen/primeapi/primeoperations/mto_shipment/create_non_s_i_t_address_update_request_parameters.go
  pkg/gen/primeapi/primeoperations/mto_shipment/create_non_s_i_t_address_update_request_responses.go
  pkg/gen/primeapi/primeoperations/mto_shipment/create_non_s_i_t_address_update_request_urlbuilder.go
  pkg/gen/primeapi/primeoperations/mto_shipment/update_m_t_o_shipment_address.go
  pkg/gen/primeapi/primeoperations/mymove_api.go
  pkg/gen/primeclient/mto_shipment/create_non_s_i_t_address_update_request_parameters.go
  pkg/gen/primeclient/mto_shipment/create_non_s_i_t_address_update_request_responses.go
  pkg/gen/primeclient/mto_shipment/mto_shipment_client.go
  pkg/gen/primemessages/create_non_s_i_t_address_update_request.go
  pkg/gen/primemessages/shipment_address_update.go
  pkg/handlers/primeapi/api.go
  pkg/handlers/primeapi/mto_shipment.go
  pkg/handlers/primeapi/mto_shipment_test.go
  pkg/handlers/primeapi/payloads/model_to_payload.go
  pkg/handlers/primeapi/payloads/payload_to_model.go
  pkg/services/mocks/ShipmentAddressUpdateRequester.go
  pkg/services/shipment_address_update.go
  pkg/services/shipment_address_update/shipment_address_update_requester.go
  swagger-def/definitions/ShipmentAddressUpdate.yaml
  swagger-def/prime.yaml
  swagger/prime.yaml
Labels: ttv, ready-to-merge

#10960 [MB-16120] Prime shipment address update
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/m_t_o_shipment_without_service_items.go
  pkg/gen/primemessages/shipment_address_update.go
  pkg/gen/primemessages/shipment_address_update_status.go
  pkg/handlers/primeapi/payloads/model_to_payload.go
  pkg/services/move_task_order/move_task_order_fetcher.go
  pkg/services/move_task_order/move_task_order_fetcher_test.go
  swagger-def/definitions/ShipmentAddressUpdate.yaml
  swagger-def/definitions/ShipmentAddressUpdateStatus.yaml
  swagger-def/prime.yaml
  swagger/prime.yaml
Labels: ttv, ready-to-merge

#10932 update FE to account for new dateOfContact field
  src/components/Office/RequestedServiceItemsTable/RequestedServiceItemsTable.stories.jsx
  src/components/Office/RequestedServiceItemsTable/RequestedServiceItemsTable.test.jsx
  src/components/Office/ServiceItemDetails/ServiceItemDetails.jsx
  src/components/Office/ServiceItemDetails/ServiceItemDetails.test.jsx
  src/components/Office/ServiceItemUpdateModal/ServiceItemUpdateModal.test.jsx
  src/components/Office/ServiceItemUpdateModal/ServiceItemUpdateModalTestParams.js
  src/components/Office/ServiceItemsTable/ServiceItemsTable.test.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
  src/types/serviceItems.js
Labels: Pamplemoose, ready-to-merge

#10912 [MB-16137] Integrate new service item card
  playwright/tests/office/txo/tioFlows.spec.js
  src/components/Office/ReviewServiceItems/NewReviewServiceItems.jsx
  src/components/Office/ReviewServiceItems/NewReviewServiceItems.module.scss
  src/components/Office/ReviewServiceItems/NewReviewServiceItems.stories.jsx
  src/components/Office/ReviewServiceItems/NewReviewServiceItems.test.jsx
  src/components/Office/ReviewServiceItems/NewServiceItemCard.jsx
  src/components/Office/ReviewServiceItems/NewServiceItemCard.module.scss
  src/components/Office/ReviewServiceItems/NewServiceItemCard.stories.jsx
  src/components/Office/ReviewServiceItems/NewServiceItemCard.test.jsx
  src/components/Office/ReviewServiceItems/ReviewServiceItems.jsx
  src/components/Office/ReviewServiceItems/ReviewServiceItems.stories.jsx
  src/components/Office/ReviewServiceItems/ReviewServiceItems.test.jsx
  src/components/Office/ReviewServiceItems/ServiceItemCard.jsx
  src/components/Office/ReviewServiceItems/ServiceItemCard.module.scss
  src/components/Office/ReviewServiceItems/ServiceItemCard.stories.jsx
  src/components/Office/ReviewServiceItems/ServiceItemCard.test.jsx
  src/pages/Office/PaymentRequestReview/PaymentRequestReview.jsx
  src/pages/Office/PaymentRequestReview/PaymentRequestReview.test.jsx
Labels: A-Team

#10974 [MB-16418] In review request modal, address should be formatted with line breaks
  src/components/Office/ServiceItemUpdateModal/ReviewSitAddressChange.jsx
  src/components/Office/ServiceItemUpdateModal/ServiceItemUpdateModal.test.jsx
Labels: Pamplemoose, ready-to-merge

#10980 MB-16349 add SIT FSC migrations
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20230628220338_add_sit_fsc_reservice_and_service_params.up.sql
  pkg/models/re_service.go
Labels: Pamplemoose, ready-to-merge

#10958 [ MB-16105 ] Display additional MTO Compliance info to office UI
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/order.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/services/move/move_fetcher.go
  pkg/services/move/move_fetcher_test.go
  playwright/tests/office/txo/tooFlows.spec.js
  src/components/Office/FinancialReviewButton/FinancialReviewButton.module.scss
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
  src/pages/Office/TXOMoveInfo/TXOTab.module.scss
  src/types/order.js
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: ready-to-merge, Huckleberry

#10973 [ MB-13693 ] Update SIT Display to show properly
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/s_i_t_status.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/services/mto_shipment.go
  pkg/services/mto_shipment/shipment_sit_status.go
  pkg/services/mto_shipment/shipment_sit_status_test.go
  pkg/testdatagen/testharness/dispatch.go
  pkg/testdatagen/testharness/make_move.go
  playwright/tests/utils/testharness.js
  src/components/Office/ReviewSITExtensionModal/ReviewSITExtensionModal.jsx
  src/components/Office/ReviewSITExtensionModal/ReviewSITExtensionModal.stories.jsx
  src/components/Office/ReviewSITExtensionModal/ReviewSITExtensionModal.test.jsx
  src/components/Office/ShipmentDetails/ShipmentDetailsMain.jsx
  src/components/Office/ShipmentSITDisplay/ShipmentSITDisplay.jsx
  src/components/Office/ShipmentSITDisplay/ShipmentSITDisplayTestParams.js
  src/components/Office/SubmitSITExtensionModal/SubmitSITExtensionModal.jsx
  src/components/Office/SubmitSITExtensionModal/SubmitSITExtensionModal.stories.jsx
  src/components/Office/SubmitSITExtensionModal/SubmitSITExtensionModal.test.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
  src/types/sitStatusShape.js
  swagger-def/definitions/SITStatus.yaml
  swagger/ghc.yaml
Labels: Pamplemoose, bug

#10979 [ MB-16408 ] Getting SIT Address Status updates from existing endpoint
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/m_t_o_service_item_dest_s_i_t.go
  pkg/gen/primemessages/sit_address_update.go
  pkg/gen/primemessages/sit_address_updates.go
  pkg/handlers/primeapi/payloads/model_to_payload.go
  pkg/services/move_task_order/move_task_order_fetcher.go
  swagger-def/prime.yaml
  swagger/prime.yaml
Labels: Pamplemoose, ready-to-merge

#10919 MB-16179 fix internal api upload amended orders authz issue
  cmd/milmove/serve.go
  pkg/handlers/internalapi/orders.go
  pkg/handlers/internalapi/orders_test.go
  pkg/handlers/routing/base_routing_suite.go
  pkg/handlers/routing/internalapi_test/orders_test.go
  pkg/handlers/routing/routing_init.go
  pkg/services/order/order_updater.go
  pkg/services/order/order_updater_test.go
Labels: A-Team
