Repository transcom/mymove, pull requests merged in 2023-05, with the labels that each got.

#10568 MB-15712 add and implement BuildPrimeUpload
  pkg/factory/prime_upload_factory.go
  pkg/factory/prime_upload_factory_test.go
  pkg/factory/shared.go
  pkg/factory/user_upload_factory.go
  pkg/services/payment_request/payment_request_fetcher_test.go
  pkg/services/payment_request/payment_request_recalculator_test.go
  pkg/services/payment_request/payment_request_shipment_recalculate_test.go
  pkg/testdatagen/make_prime_upload.go
  pkg/testdatagen/make_proof_of_service_doc.go
  pkg/testdatagen/scenario/bandwidth.go
  pkg/testdatagen/scenario/e2ebasic.go
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/testharness/make_move.go
Labels: ready-to-merge, spark

#10580 MB-15888: WeightTicket factory and tests
  pkg/factory/shared.go
  pkg/factory/weight_ticket_factory.go
  pkg/factory/weight_ticket_factory_test.go
  pkg/handlers/ghcapi/ppm_document_test.go
  pkg/handlers/internalapi/uploads_test.go
  pkg/handlers/internalapi/weight_ticket_test.go
  pkg/services/mto_shipment/mto_shipment_fetcher_test.go
  pkg/services/ppmshipment/ppm_estimator_test.go
  pkg/services/ppmshipment/ppm_shipment_fetcher_test.go
  pkg/services/ppmshipment/ppm_shipment_router_test.go
  pkg/services/weight_ticket/weight_ticket_fetcher_test.go
  pkg/services/weight_ticket/weight_ticket_updater_test.go
  pkg/testdatagen/make_ppm_shipment.go
  pkg/testdatagen/make_weight_ticket.go
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/testharness/make_move.go
Labels: ready-to-merge

#10540 [MB-15068] show fadd details received from ghc prime
  pkg/services/mto_service_item/mto_service_item_creator.go
  pkg/services/mto_service_item/mto_service_item_creator_test.go
  src/components/Office/RequestedServiceItemsTable/RequestedServiceItemsTable.test.jsx
  src/components/Office/ServiceItemDetails/ServiceItemDetails.jsx
  src/components/Office/ServiceItemDetails/ServiceItemDetails.test.jsx
  src/components/Office/ServiceItemsTable/ServiceItemsTable.test.jsx
Labels: Pamplemoose

#10532 [MB-13567] SC/TOO can add and edit the secondary addresses for HHG shipments
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/mto_shipment/update_m_t_o_shipment.go
  pkg/gen/ghcmessages/m_t_o_shipment.go
  pkg/gen/ghcmessages/update_shipment.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/internal/payloads/payload_to_model.go
  playwright/tests/office/servicescounseling/servicesCounselingFlows.spec.js
  src/components/Office/DefinitionLists/NTSShipmentInfoList.jsx
  src/components/Office/DefinitionLists/NTSShipmentInfoList.test.jsx
  src/components/Office/DefinitionLists/ShipmentInfoList.jsx
  src/components/Office/DefinitionLists/ShipmentInfoList.test.jsx
  src/components/Office/ShipmentForm/ShipmentForm.jsx
  src/components/Office/ShipmentForm/ShipmentForm.module.scss
  src/components/Office/ShipmentForm/ShipmentForm.test.jsx
  swagger-def/definitions/MTOShipment.yaml
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: A-Team

#10583 MB-13693 - Add sit display conditions and tests, fix end date.
  src/components/Office/ShipmentDetails/ShipmentDetails.stories.jsx
  src/components/Office/ShipmentDetails/ShipmentDetailsMain.jsx
  src/components/Office/ShipmentDetails/ShipmentDetailsMain.test.jsx
  src/components/Office/ShipmentSITDisplay/ShipmentSITDisplay.jsx
  src/components/Office/ShipmentSITDisplay/ShipmentSITDisplayTestParams.js
  src/hooks/custom.js
Labels: ready-to-merge

#10582 MB-15887 Implement BuildPPMShipmentReadyForFinalCustomerCloseOut
  Makefile
  pkg/factory/ppm_shipment_factory.go
  pkg/factory/ppm_shipment_factory_test.go
  pkg/factory/user_upload_factory.go
  pkg/handlers/internalapi/ppm_shipment_test.go
  pkg/services/ppmshipment/ppm_shipment_fetcher_test.go
  pkg/services/ppmshipment/ppm_shipment_new_submitter_test.go
  pkg/services/ppmshipment/ppm_shipment_router_test.go
  pkg/services/ppmshipment/ppm_shipment_updated_submitter_test.go
  pkg/testdatagen/make_ppm_shipment.go
  pkg/testdatagen/make_signed_certification.go
  scripts/psql-wrapper
  scripts/wait-for-db
Labels: ready-to-merge

#10558 [MB-15837] Remove remaining tariff400ng tables and code references
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20230427142553_drop_400ng_zip_tables.up.sql
  pkg/factory/address_factory.go
  pkg/factory/duty_location_factory.go
  pkg/factory/shared.go
  pkg/factory/tariff_factory.go
  pkg/factory/tariff_factory_test.go
  pkg/models/tariff400ng_full_pack_rate.go
  pkg/models/tariff400ng_full_unpack_rate.go
  pkg/models/tariff400ng_item.go
  pkg/models/tariff400ng_item_rate.go
  pkg/models/tariff400ng_linehaul_rate.go
  pkg/models/tariff400ng_service_area.go
  pkg/models/tariff400ng_shorthaul_rate.go
  pkg/models/tariff400ng_zip3.go
  pkg/models/tariff400ng_zip3_test.go
  pkg/models/tariff400ng_zip5_rate_area.go
  pkg/models/tariff400ng_zip5_rate_area_test.go
  pkg/rateengine/linehaul.go
  pkg/rateengine/linehaul_test.go
  pkg/rateengine/nonlinehaul.go
  pkg/rateengine/nonlinehaul_test.go
  pkg/rateengine/pricers.go
  pkg/rateengine/pricers_test.go
  pkg/rateengine/rateengine.go
  pkg/rateengine/rateengine_test.go
  pkg/testdatagen/make_address.go
  pkg/testdatagen/make_duty_location.go
  pkg/testdatagen/make_tariff400ng_item.go
  pkg/testdatagen/make_tariff400ng_item_rate.go
  pkg/testdatagen/make_tariff400ng_service_area.go
  pkg/testdatagen/make_tariff400ng_zip3.go
  pkg/testdatagen/shared.go
  src/shared/AppContext/index.jsx
  src/shared/Entities/reducer.js
  src/shared/Entities/schema.js
Labels: ttv, ready-to-merge

#10563 MB-8104 Enable DTOD for prod
  config/env/prd.app.env
Labels: ready-to-merge

#10585 MB-15890 add and implement BuildSITDurationUpdate
  pkg/factory/shared.go
  pkg/factory/sit_duration_update_factory.go
  pkg/factory/sit_duration_update_factory_test.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/handlers/primeapi/move_task_order_test.go
  pkg/payment_request/service_param_value_lookups/number_days_sit_lookup_test.go
  pkg/services/move/move_router_test.go
  pkg/services/mto_shipment/mto_shipment_fetcher_test.go
  pkg/services/sit_extension/rules_test.go
  pkg/services/sit_extension/sit_extension_approver_test.go
  pkg/services/sit_extension/sit_extension_denier_test.go
  pkg/testdatagen/make_sit_duration_update.go
  pkg/testdatagen/scenario/shared.go
Labels: ready-to-merge, spark

#10588 MB-15925 build progear weight ticket
  pkg/factory/progear_weight_ticket_factory.go
  pkg/factory/progear_weight_ticket_factory_test.go
  pkg/factory/shared.go
  pkg/handlers/ghcapi/ppm_document_test.go
  pkg/handlers/ghcapi/progear_weight_ticket_test.go
  pkg/handlers/internalapi/progear_weight_ticket_test.go
  pkg/handlers/internalapi/uploads_test.go
  pkg/services/ppmshipment/ppm_document_fetcher_test.go
  pkg/services/ppmshipment/ppm_shipment_fetcher_test.go
  pkg/services/ppmshipment/ppm_shipment_router_test.go
  pkg/services/progear_weight_ticket/progear_weight_ticket_updater_test.go
  pkg/testdatagen/make_ppm_shipment.go
  pkg/testdatagen/make_progear_weight_ticket.go
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/testharness/make_move.go
Labels: ready-to-merge, spark

#10552 [MB-15533] Allow prime to update FADD fields
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/update_m_t_o_service_item_s_i_t.go
  pkg/handlers/primeapi/mto_service_item_test.go
  pkg/handlers/primeapi/payloads/payload_to_model.go
  pkg/services/mto_service_item/mto_service_item_updater.go
  pkg/services/mto_service_item/mto_service_item_updater_test.go
  pkg/services/mto_service_item/mto_service_item_validators.go
  pkg/services/mto_service_item/mto_service_item_validators_test.go
  swagger-def/prime.yaml
  swagger/prime.yaml
Labels: A-Team

#10584 MB-15926 implement build moving expense
  pkg/db/utilities/utilities_test.go
  pkg/factory/moving_expense_factory.go
  pkg/factory/moving_expense_factory_test.go
  pkg/factory/shared.go
  pkg/handlers/ghcapi/moving_expense_test.go
  pkg/handlers/ghcapi/ppm_document_test.go
  pkg/handlers/internalapi/moving_expense_test.go
  pkg/handlers/internalapi/uploads_test.go
  pkg/services/ppmshipment/ppm_document_fetcher_test.go
  pkg/services/ppmshipment/ppm_shipment_fetcher_test.go
  pkg/services/ppmshipment/ppm_shipment_router_test.go
  pkg/testdatagen/make_moving_expenses.go
  pkg/testdatagen/make_ppm_shipment.go
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/testharness/make_move.go
Labels: ready-to-merge

#10589 MB-15722 factory.BuildPaymentRequestToInterchangeControlNumber added as new version of testdatagen.MakePaymentRequestToInterchangeControlNumber
  pkg/factory/payment_request_interchange_control_number_factory.go
  pkg/factory/payment_request_interchange_control_number_factory_test.go
  pkg/factory/shared.go
  pkg/services/invoice/process_edi824_test.go
  pkg/services/invoice/process_edi997_test.go
  pkg/testdatagen/make_payment_request_to_interchange_control_number.go
Labels: ready-to-merge, spark

#10448 [MB-15768] Use non hard-coded contract code
  pkg/payment_request/service_param_value_lookups/actual_pickup_date_lookup_test.go
  pkg/payment_request/service_param_value_lookups/contract_code_lookup_test.go
  pkg/payment_request/service_param_value_lookups/cubic_feet_billed_lookup_test.go
  pkg/payment_request/service_param_value_lookups/cubic_feet_crating_lookup_test.go
  pkg/payment_request/service_param_value_lookups/dimension_height_lookup_test.go
  pkg/payment_request/service_param_value_lookups/dimension_length_lookup_test.go
  pkg/payment_request/service_param_value_lookups/dimension_width_lookup_test.go
  pkg/payment_request/service_param_value_lookups/distance_zip_lookup_test.go
  pkg/payment_request/service_param_value_lookups/distance_zip_sit_dest_lookup_test.go
  pkg/payment_request/service_param_value_lookups/distance_zip_sit_origin_lookup_test.go
  pkg/payment_request/service_param_value_lookups/eia_fuel_price_lookup_test.go
  pkg/payment_request/service_param_value_lookups/mto_available_to_prime_at_lookup_test.go
  pkg/payment_request/service_param_value_lookups/number_days_sit_lookup_test.go
  pkg/payment_request/service_param_value_lookups/reference_date_lookup_test.go
  pkg/payment_request/service_param_value_lookups/requested_pickup_date_lookup_test.go
  pkg/payment_request/service_param_value_lookups/service_area_lookup_test.go
  pkg/payment_request/service_param_value_lookups/service_param_value_lookups.go
  pkg/payment_request/service_param_value_lookups/service_param_value_lookups_test.go
  pkg/payment_request/service_param_value_lookups/service_params_cache_test.go
  pkg/payment_request/service_param_value_lookups/services_schedule_lookup_test.go
  pkg/payment_request/service_param_value_lookups/sit_schedule_lookup_test.go
  pkg/payment_request/service_param_value_lookups/zip_address_lookup_test.go
  pkg/payment_request/service_param_value_lookups/zip_sit_origin_hhg_actual_address_lookup_test.go
  pkg/payment_request/service_param_value_lookups/zip_sit_origin_hhg_original_address_lookup_test.go
  pkg/services/ghcrateengine/pricer_helpers_test.go
  pkg/services/ghcrateengine/shared.go
  pkg/services/payment_request/payment_request_creator_test.go
  pkg/services/ppmshipment/ppm_estimator.go
  pkg/testdatagen/make_re_contract_year.go
Labels: ttv, ready-to-merge

#10587 MB-15930: convert make ppm shipment variants
  pkg/factory/order_factory.go
  pkg/factory/postal_code_to_gbloc_factory.go
  pkg/factory/ppm_shipment_factory.go
  pkg/factory/ppm_shipment_factory_test.go
  pkg/handlers/ghcapi/moving_expense_test.go
  pkg/handlers/ghcapi/ppm_document_test.go
  pkg/handlers/ghcapi/weight_ticket_test.go
  pkg/handlers/internalapi/ppm_shipment_test.go
  pkg/services/order/order_fetcher_test.go
  pkg/services/postal_codes/postal_code_validator_test.go
  pkg/services/ppmshipment/payment_packet_creator_test.go
  pkg/services/ppmshipment/ppm_document_fetcher_test.go
  pkg/services/ppmshipment/ppm_estimator_test.go
  pkg/services/ppmshipment/ppm_shipment_fetcher_test.go
  pkg/services/ppmshipment/ppm_shipment_review_documents_test.go
  pkg/services/ppmshipment/ppm_shipment_router_test.go
  pkg/services/ppmshipment/ppm_shipment_updated_submitter_test.go
  pkg/testdatagen/make_backup_contact.go
  pkg/testdatagen/make_contractor.go
  pkg/testdatagen/make_document.go
  pkg/testdatagen/make_duty_location.go
  pkg/testdatagen/make_entitlement.go
  pkg/testdatagen/make_evaluation_report.go
  pkg/testdatagen/make_move.go
  pkg/testdatagen/make_moving_expenses.go
  pkg/testdatagen/make_mto_shipment.go
  pkg/testdatagen/make_order.go
  pkg/testdatagen/make_payment_service_item.go
  pkg/testdatagen/make_postal_code_to_gbloc.go
  pkg/testdatagen/make_ppm_shipment.go
  pkg/testdatagen/make_progear_weight_ticket.go
  pkg/testdatagen/make_report_violation.go
  pkg/testdatagen/make_service_member.go
  pkg/testdatagen/make_signed_certification.go
  pkg/testdatagen/make_user_upload.go
  pkg/testdatagen/make_webhook_subscription.go
  pkg/testdatagen/make_weight_ticket.go
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/scenario/subscenarios.go
  pkg/testdatagen/shared.go
Labels: ready-to-merge

#10570 [ MB-15335 ] Create sit destination final address when creating DDFSIT service item
  pkg/handlers/primeapi/payloads/payload_to_model.go
  pkg/handlers/primeapi/payloads/payload_to_model_test.go
  pkg/services/mto_service_item/mto_service_item_creator.go
  pkg/services/mto_service_item/mto_service_item_creator_test.go
  pkg/services/mto_service_item/mto_service_item_validators.go
  pkg/services/mto_service_item/mto_service_item_validators_test.go
Labels: ready-to-merge, Huckleberry

#10581 [MB-14975] Change calculation for total # days remaining
  src/components/Office/ShipmentSITDisplay/ShipmentSITDisplay.jsx
  src/components/Office/ShipmentSITDisplay/ShipmentSITDisplay.test.jsx
  src/components/Office/ShipmentSITDisplay/ShipmentSITDisplayTestParams.js
  src/components/Office/SubmitSITExtensionModal/SubmitSITExtensionModal.jsx
Labels: Pamplemoose, ready-to-merge

#10603 [MB-15068] updating fadd text
  src/components/Office/RequestedServiceItemsTable/RequestedServiceItemsTable.test.jsx
  src/components/Office/ServiceItemDetails/ServiceItemDetails.jsx
  src/components/Office/ServiceItemsTable/ServiceItemsTable.test.jsx
Labels: Pamplemoose

#10604 [MB-15791] add initial sit destination address column
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20230503233423_adding_sit_destination_initial_address_column.up.sql
Labels: Pamplemoose

#10605 [MB-15962] Fix SITDisplayDetails storybook renderings
  src/components/Office/ShipmentDetails/ShipmentDetails.stories.jsx
  src/components/Office/SubmitSITExtensionModal/SubmitSITExtensionModal.stories.jsx
Labels: Pamplemoose

#10609 [MB-15719] Change the logic behind validation of prime-provided estimated weight
  pkg/handlers/primeapi/mto_shipment.go
  pkg/handlers/primeapi/mto_shipment_test.go
Labels: A-Team

#10579 [ MB-15594 ] Refactoring review SIT modal
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/approve_s_i_t_extension.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/mto_shipment.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/services/mocks/SITExtensionApprover.go
  pkg/services/sit_extension.go
  pkg/services/sit_extension/sit_extension_approver.go
  pkg/services/sit_extension/sit_extension_approver_test.go
  src/components/Office/ReviewSITExtensionModal/ReviewSITExtensionModal.jsx
  src/components/Office/ReviewSITExtensionModal/ReviewSITExtensionModal.module.scss
  src/components/Office/ReviewSITExtensionModal/ReviewSITExtensionModal.stories.jsx
  src/components/Office/ReviewSITExtensionModal/ReviewSITExtensionModal.test.jsx
  src/components/Office/ShipmentDetails/ShipmentDetailsMain.jsx
  src/components/Office/ShipmentSITDisplay/ShipmentSITDisplay.jsx
  src/components/Office/ShipmentSITDisplay/ShipmentSITDisplay.module.scss
  src/components/Office/SubmitSITExtensionModal/SubmitSITExtensionModal.jsx
  src/components/Office/SubmitSITExtensionModal/SubmitSITExtensionModal.test.jsx
  src/components/form/fields/DatePickerInput.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
  src/shared/dates.js
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: Pamplemoose

#10608 MB-15953-Remove authorized weight from the office orders
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/update_allowance_payload.go
  pkg/handlers/ghcapi/orders_test.go
  pkg/services/order/order_updater.go
  pkg/services/order/order_updater_test.go
  playwright/tests/office/qaecsr/csrFlows.spec.js
  src/components/Office/AllowancesDetailForm/AllowancesDetailForm.jsx
  src/components/Office/DefinitionLists/AllowancesList.jsx
  src/components/Office/DefinitionLists/AllowancesList.test.jsx
  src/pages/Office/MoveAllowances/MoveAllowances.jsx
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: ttv

#10602 MB-15520 allow TOO to to view documents and disable 'Review service items' button when needed for TOO
  pkg/handlers/authentication/permissions.go
  src/components/Office/PaymentRequestCard/PaymentRequestCard.jsx
  src/components/Office/PaymentRequestCard/PaymentRequestCard.test.jsx
  src/constants/permissions.js
Labels: ttv, ready-to-merge

#10607 [MB-15792] create sit destination address change table
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20230504204015_creating_SIT_destination_address_update_table.up.sql
Labels: Pamplemoose

#10626 MB-15999: Convert last usage of MakeMTOAgent to factory and remove it
  pkg/testdatagen/make_mto_agent.go
  pkg/testdatagen/testharness/make_move.go
Labels: ready-to-merge

#10628 MB-16000: Ensure roles/permissions returns empty list for swagger
  pkg/handlers/internalapi/users.go
  pkg/handlers/internalapi/users_test.go
Labels: ready-to-merge

#10619 MB-15610 - Add sit playwright tests
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/testharness/dispatch.go
  pkg/testdatagen/testharness/make_move.go
  playwright/tests/admin/adminUsers.spec.js
  playwright/tests/admin/moves.spec.js
  playwright/tests/admin/officeUsers.spec.js
  playwright/tests/admin/users.spec.js
  playwright/tests/admin/webhookSubscriptions.spec.js
  playwright/tests/office/servicescounseling/servicesCounselingTestFixture.js
  playwright/tests/office/txo/sitUpdates.spec.js
  playwright/tests/office/txo/tooFlows.spec.js
  playwright/tests/utils/adminTest.js
  playwright/tests/utils/customerTest.js
  playwright/tests/utils/officeTest.js
  playwright/tests/utils/testharness.js
  playwright/tests/utils/waitForAdminPage.js
  playwright/tests/utils/waitForCustomerPage.js
  playwright/tests/utils/waitForOfficePage.js
  playwright/tests/utils/waitForPage.js
Labels: Pamplemoose

#10611 [MB-15793] create sit address update model + update mtoServiceItem model
  pkg/models/mto_service_items.go
  pkg/models/sit_address_updates.go
  pkg/models/sit_address_updates_test.go
Labels: Pamplemoose, ready-to-merge

#10620 [MB-15811] Adding test harness data
  pkg/factory/mto_service_item_factory.go
  pkg/factory/mto_service_item_factory_test.go
  pkg/factory/shared.go
  pkg/factory/sit_address_update_factory.go
  pkg/factory/sit_address_update_factory_test.go
  pkg/testdatagen/scenario/devseed.go
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/scenario/subscenarios.go
  pkg/testdatagen/testharness/dispatch.go
  pkg/testdatagen/testharness/make_move.go
Labels: Pamplemoose, ready-to-merge

#10618 [MB-14973] Fix the current days in SIT number and the total days remaining
  src/components/Office/ReviewSITExtensionModal/ReviewSITExtensionModal.jsx
  src/components/Office/ShipmentSITDisplay/ShipmentSITDisplay.jsx
  src/components/Office/ShipmentSITDisplay/ShipmentSITDisplay.test.jsx
  src/components/Office/SubmitSITExtensionModal/SubmitSITExtensionModal.jsx
Labels: Pamplemoose, ready-to-merge

#10634 MB-16012 loadtest verify
  .circleci/config.yml
Labels: ready-to-merge

#10652 MB-16054 fix bundle diff running out of memory on GHA
  .github/workflows/analyze-bundle.yml
Labels: ready-to-merge

#10637 Organize playwright utils
  playwright/tests/admin/adminUsers.spec.js
  playwright/tests/admin/homepage.spec.js
  playwright/tests/admin/moves.spec.js
  playwright/tests/admin/officeUsers.spec.js
  playwright/tests/admin/offices.spec.js
  playwright/tests/admin/users.spec.js
  playwright/tests/admin/webhookSubscriptions.spec.js
  playwright/tests/my/milmove/ppms/customerPpmTestFixture.js
  playwright/tests/my/mymove/hhg.spec.js
  playwright/tests/my/mymove/nts.spec.js
  playwright/tests/my/mymove/ntsr.spec.js
  playwright/tests/my/mymove/onboarding.spec.js
  playwright/tests/my/mymove/orders.spec.js
  playwright/tests/office/documentViewer.spec.js
  playwright/tests/office/homepage.spec.js
  playwright/tests/office/officeCSRFProtect.spec.js
  playwright/tests/office/ppms/ppmTestFixture.js
  playwright/tests/office/primesimulator/primeSimulatorFlows.spec.js
  playwright/tests/office/qaecsr/csrFlows.spec.js
  playwright/tests/office/qaecsr/moveSearchFlows.spec.js
  playwright/tests/office/qaecsr/qaeFlows.spec.js
  playwright/tests/office/servicescounseling/servicesCounselingTestFixture.js
  playwright/tests/office/txo/sitUpdates.spec.js
  playwright/tests/office/txo/tioFlows.spec.js
  playwright/tests/office/txo/tioUpdateMaxBillableWeight.spec.js
  playwright/tests/office/txo/tooFlows.spec.js
  playwright/tests/office/txo/tooFlowsNTS.spec.js
  playwright/tests/office/txo/tooFlowsNTSR.spec.js
  playwright/tests/office/txo/tooTestFixture.js
  playwright/tests/utils/admin/adminTest.js
  playwright/tests/utils/admin/waitForAdminPage.js
  playwright/tests/utils/my/customerTest.js
  playwright/tests/utils/my/waitForCustomerPage.js
  playwright/tests/utils/office/officeTest.js
  playwright/tests/utils/office/waitForOfficePage.js
Labels: Pamplemoose

#8631 [ MB-16007 ] Open Telemetry improvements for AWS XRay
  cmd/ecs-deploy/task_def.go
  cmd/milmove/serve.go
  go.mod
  go.sum
  pkg/cli/telemetry.go
  pkg/handlers/health.go
  pkg/middleware/context_logger.go
  pkg/middleware/openapi.go
  pkg/middleware/trace.go
  pkg/middleware/trace_test.go
  pkg/telemetry/db.go
  pkg/telemetry/db_test.go
  pkg/telemetry/init.go
  pkg/telemetry/init_test.go
  pkg/telemetry/milmove_data.go
  pkg/telemetry/milmove_data_test.go
  pkg/telemetry/runtime.go
  pkg/telemetry/telemetry_test.go
  pkg/trace/context.go
  pkg/trace/context_test.go
Labels: ready-to-merge

#10654 MB-16056: Switch to official github webpack bundlesize compare action
  .github/workflows/analyze-bundle.yml
Labels: ready-to-merge

#10657 [MB-15792] adding created and updated at columns to sit_address_updates table
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20230512200539_add_created_and_updated_at_columns_to_sit_address_update_table.up.sql
  pkg/factory/sit_address_update_factory.go
  pkg/factory/sit_address_update_factory_test.go
  pkg/models/mto_service_items.go
  pkg/models/sit_address_updates.go
  pkg/models/sit_address_updates_test.go
  pkg/testdatagen/scenario/subscenarios.go
Labels: Pamplemoose

#10665 MB-16074: Use latest github/webpack-bundlesize-compare-action, truncate comment
  .github/workflows/analyze-bundle.yml
Labels: ready-to-merge

#10663 MB-15996 use Reference ID instead of payment request in BX EDI segment
  pkg/services/invoice/ghc_payment_request_invoice_generator.go
  pkg/services/invoice/ghc_payment_request_invoice_generator_test.go
Labels: ttv, ready-to-merge

#10666 MB-16075: Try FE Bundle cancel in progress per job
  .github/workflows/analyze-bundle.yml
Labels: ready-to-merge

#10660 MB-16065: Fix searchable_full_name function to reference public.f_unaccent
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20230515145532_fix_searchable_full_name.up.sql
Labels: ready-to-merge

#10646 MB-16003 Add move locator code to N9 reference header
  pkg/edi/invoice/generator.go
  pkg/edi/invoice/generator_test.go
  pkg/edi/segment/n9.go
  pkg/services/invoice/ghc_payment_request_invoice_generator.go
  pkg/services/invoice/ghc_payment_request_invoice_generator_test.go
Labels: ttv

#10668 MB-15873 - Add office sit address updates endpoint data
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/m_t_o_service_item.go
  pkg/gen/ghcmessages/s_i_t_address_update.go
  pkg/gen/ghcmessages/s_i_t_address_updates.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/mto_service_items.go
  pkg/handlers/ghcapi/mto_service_items_test.go
  pkg/testdatagen/testharness/make_move.go
  swagger-def/definitions/MTOServiceItem.yaml
  swagger-def/definitions/SITAddressUpdate.yaml
  swagger-def/definitions/SITAddressUpdates.yaml
  swagger/ghc.yaml
Labels: Pamplemoose

#10664 [MB-15973] Upgrade Storybook (and associated dependencies) to v7
  .storybook/main.js
  package.json
  src/components/Office/DaysInSITAllowance/DaysInSITAllowance.stories.jsx
  src/components/Office/EditMaxBillableWeightModal/EditMaxBillableWeightModal.stories.jsx
  src/components/Office/OrdersDetailForm/OrdersDetailForm.stories.jsx
  src/components/Office/PaymentRequestCard/PaymentRequestCard.stories.jsx
  src/components/Office/ShipmentDetails/ShipmentDetails.stories.jsx
  src/components/Office/ShipmentSITDisplay/ShipmentSITDisplay.stories.jsx
  src/components/Office/SubmitSITExtensionModal/SubmitSITExtensionModal.stories.jsx
  src/components/Office/WeightDisplay/WeightDisplay.stories.jsx
  yarn.lock
Labels: dependencies

#10693 MB-16096: workaround for otel memory leak
  cmd/milmove/serve.go
  pkg/middleware/request_logger.go
  pkg/middleware/request_logger_test.go
  pkg/telemetry/request.go
  pkg/telemetry/request_test.go
Labels: ready-to-merge

#10667 MB-16076 Prevent error in Admin UI when user has no roles
  playwright/tests/admin/officeUsers.spec.js
  src/pages/Admin/OfficeUsers/OfficeUserEdit.jsx
  src/pages/Admin/OfficeUsers/OfficeUserShow.jsx
Labels: ready-to-merge

#10697 [MB-15973] Upgrades playwright and @playwright/test to 1.33
  package.json
  playwright.config.js
  yarn.lock
Labels: dependencies

#10701 [MB-8471] Prime is able to create a payment request for different move
  pkg/services/payment_request/payment_request_creator.go
  pkg/services/payment_request/payment_request_creator_test.go
  pkg/services/payment_request/rules.go
  pkg/services/payment_request/rules_test.go
Labels: A-Team, ready-to-merge

#10687 [MB-16004] Add DOD ID number to EDI N9 reference header
  pkg/edi/invoice/generator.go
  pkg/edi/invoice/generator_test.go
  pkg/edi/segment/n9.go
  pkg/factory/service_member_factory.go
  pkg/services/invoice/ghc_payment_request_invoice_generator.go
  pkg/services/invoice/ghc_payment_request_invoice_generator_test.go
Labels: ttv

#10695 MB-16057: otel collector version and config
  cmd/ecs-deploy/task_def.go
  scripts/ecs-deploy-service-container
Labels: ready-to-merge

#10681 MB-15708: update service items
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/m_t_o_service_item_origin_s_i_t.go
  pkg/handlers/primeapi/move_task_order_test.go
  pkg/handlers/primeapi/payloads/model_to_payload.go
  pkg/services/move_task_order/move_task_order_fetcher.go
  swagger-def/prime.yaml
  swagger/prime.yaml
Labels: Huckleberry

#10702 MB-15708 update payment requests
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/payment_request.go
  pkg/gen/primemessages/proof_of_service_doc.go
  pkg/gen/primemessages/proof_of_service_docs.go
  pkg/handlers/primeapi/move_task_order_test.go
  pkg/handlers/primeapi/payloads/model_to_payload.go
  pkg/services/move_task_order/move_task_order_fetcher.go
  swagger-def/prime.yaml
  swagger/prime.yaml
Labels: Huckleberry

#10691 MB-16082: Try to have only one server gathering db table stats
  pkg/telemetry/milmove_data.go
Labels: ready-to-merge

#10688 MB-15874: show edit/review requests link, yellow alert and yellow tag for SIT address change request
  src/components/Office/ServiceItemsTable/ServiceItemsTable.jsx
  src/components/Office/ServiceItemsTable/ServiceItemsTable.test.jsx
  src/components/Office/TXOTabNav/TXOTabNav.jsx
  src/constants/sitUpdates.js
  src/pages/Office/MoveDetails/MoveDetails.jsx
  src/pages/Office/MoveDetails/MoveDetails.test.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.test.jsx
  src/pages/Office/MoveTaskOrder/moveTaskOrderUnitTestData.js
  src/pages/Office/TXOMoveInfo/TXOMoveInfo.jsx
Labels: Pamplemoose, ready-to-merge

#10698 MB-15882 add endpoint for creating an approved SITAddressUpdate
  pkg/factory/sit_address_update_factory.go
  pkg/factory/sit_address_update_factory_test.go
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/mto_service_item/create_s_i_t_address_update.go
  pkg/gen/ghcapi/ghcoperations/mto_service_item/create_s_i_t_address_update_parameters.go
  pkg/gen/ghcapi/ghcoperations/mto_service_item/create_s_i_t_address_update_responses.go
  pkg/gen/ghcapi/ghcoperations/mto_service_item/create_s_i_t_address_update_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/ghcapi/ghcoperations/shipment/create_approved_s_i_t_duration_update.go
  pkg/gen/ghcapi/ghcoperations/shipment/create_approved_s_i_t_duration_update_urlbuilder.go
  pkg/gen/ghcmessages/create_s_i_t_address_update.go
  pkg/handlers/authentication/permissions.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/internal/payloads/payload_to_model.go
  pkg/handlers/ghcapi/mto_service_items.go
  pkg/handlers/ghcapi/mto_service_items_test.go
  pkg/services/mocks/ApprovedSITAddressUpdateCreator.go
  pkg/services/mto_service_item/mto_service_item_updater.go
  pkg/services/mto_service_item/mto_service_item_validators.go
  pkg/services/mto_service_item/mto_service_item_validators_test.go
  pkg/services/sit_address_update.go
  pkg/services/sit_address_update/approved_sit_address_update_creator.go
  pkg/services/sit_address_update/approved_sit_address_update_creator_test.go
  pkg/services/sit_address_update/rules.go
  pkg/services/sit_address_update/rules_test.go
  pkg/services/sit_address_update/sit_address_update_service_test.go
  pkg/services/sit_address_update/validation.go
  pkg/services/sit_address_update/validation_test.go
  pkg/testdatagen/scenario/shared.go
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: Pamplemoose, ready-to-merge

#10724 [MB-15973] Removes playwright dependency, upgrades @playwright/test version
  package.json
  yarn.lock
Labels: dependencies

#10685 [MB-15720] Estimated weights prime service object updates
  pkg/handlers/primeapi/mto_shipment.go
  pkg/services/mto_shipment/mto_shipment_updater.go
  pkg/services/mto_shipment/mto_shipment_updater_test.go
  pkg/services/mto_shipment/rules.go
  pkg/services/mto_shipment/rules_test.go
  pkg/services/mto_shipment/validation.go
  pkg/services/mto_shipment/validation_test.go
Labels: A-Team, ready-to-merge

#10727 [MB-16086] Make PrimeEstimatedWeight Optional for Creating a Shuttle Service Item
  pkg/services/mto_service_item/mto_service_item_creator.go
  pkg/services/mto_service_item/mto_service_item_creator_test.go
  pkg/services/mto_shipment/mto_shipment_creator.go
  pkg/services/mto_shipment/mto_shipment_creator_test.go
Labels: A-Team

#10703 MB-15513 Fix prime shipment type and add to existing test
  src/pages/PrimeUI/Shipment/PrimeUIShipmentCreateForm.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentCreateForm.test.jsx
Labels: ttv

#10699 MB-16107: Use AWS ECS metadata v4
  cmd/milmove/serve.go
  pkg/ecs/task_metadata.go
  pkg/ecs/task_metadata_test.go
Labels: ready-to-merge

#10710 MB-7933 Create segment for SAC/SDN when it is present
  pkg/edi/invoice/generator.go
  pkg/edi/invoice/generator_test.go
  pkg/edi/segment/fa2.go
  pkg/edi/segment/fa2_test.go
  pkg/services/invoice/ghc_payment_request_invoice_generator.go
  pkg/services/invoice/ghc_payment_request_invoice_generator_test.go
Labels: ttv

#10725 MB-15875 prime service item address change check
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/mto_service_item/update_m_t_o_service_item.go
  pkg/gen/primeclient/mto_service_item/mto_service_item_client.go
  pkg/models/sit_address_updates.go
  pkg/models/sit_address_updates_test.go
  pkg/services/mto_service_item/mto_service_item_updater_test.go
  pkg/services/mto_service_item/mto_service_item_validators.go
  pkg/services/mto_service_item/mto_service_item_validators_test.go
  pkg/testdatagen/scenario/shared.go
  swagger-def/prime.yaml
  swagger/prime.yaml
Labels: Pamplemoose, ready-to-merge

#10686 MB- 15179-Reason-required-For-All- SIT
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/m_t_o_service_item_dest_s_i_t.go
  pkg/handlers/primeapi/move_task_order_test.go
  pkg/handlers/primeapi/mto_service_item_test.go
  pkg/handlers/primeapi/mto_shipment_test.go
  pkg/handlers/primeapi/payloads/model_to_payload.go
  pkg/handlers/primeapi/payloads/payload_to_model.go
  pkg/handlers/primeapi/payloads/payload_to_model_test.go
  swagger-def/prime.yaml
  swagger/prime.yaml
Labels: Huckleberry

#10746 [ MB-15963 ] Displaying SIT display correctly
  src/components/Office/ShipmentDetails/ShipmentDetailsMain.jsx
  src/components/Office/ShipmentDetails/ShipmentDetailsMain.test.jsx
  src/components/Office/ShipmentSITDisplay/ShipmentSITDisplayTestParams.js
  src/constants/serviceItems.js
Labels: Pamplemoose, bug

#10759 MB-16138: Fix race condition in here planner
  pkg/route/here_planner.go
Labels: ready-to-merge

#10696 MB-5790 replace usage of here planner with ghc planner for required delivery date
  cmd/generate-shipment-summary/main.go
  cmd/milmove/serve.go
  pkg/handlers/config.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/handlers/internalapi/api.go
  pkg/handlers/internalapi/move_dates.go
  pkg/handlers/internalapi/moves.go
  pkg/handlers/internalapi/moves_test.go
  pkg/handlers/internalapi/personally_procured_move_incentive.go
  pkg/handlers/primeapi/api.go
  pkg/handlers/primeapi/mto_shipment_test.go
  pkg/handlers/supportapi/api.go
  pkg/paperwork/shipment_summary.go
  pkg/paperwork/shipment_summary_test.go
  pkg/services/duty_stations/load_duty_stations.go
  pkg/services/mto_shipment/mto_shipment_updater.go
  pkg/services/mto_shipment/mto_shipment_updater_test.go
  pkg/services/mto_shipment/shipment_approver_test.go
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/testharness/make_move.go
Labels: ttv

#10744 [MB-15483] Create a new order type for "Local Move"
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20230522153040_add_local_move_orders_type_comment.up.sql
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/orders_type.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/orders_type.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/orders_type.go
  pkg/gen/supportapi/embedded_spec.go
  pkg/gen/supportmessages/orders_type.go
  src/components/Customer/EditOrdersForm/EditOrdersForm.stories.jsx
  src/components/Customer/EditOrdersForm/EditOrdersForm.test.jsx
  src/components/Customer/OrdersInfoForm/OrdersInfoForm.stories.jsx
  src/components/Customer/OrdersInfoForm/OrdersInfoForm.test.jsx
  src/constants/orders.js
  src/pages/MyMove/Orders.test.jsx
  src/pages/Office/ServicesCounselingOrders/ServicesCounselingOrders.test.jsx
  swagger-def/definitions/OrdersType.yaml
  swagger-def/support.yaml
  swagger/ghc.yaml
  swagger/internal.yaml
  swagger/prime.yaml
  swagger/support.yaml
Labels: A-Team, ready-to-merge

#10645 [ MB-15948 ] Customer contact fields optional for destination service items
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20230516170511_create_service_items_customer_contacts_join_table.up.sql
  pkg/assets/sql_scripts/move_history_fetcher.sql
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/mto_service_item/create_m_t_o_service_item.go
  pkg/gen/primeclient/mto_service_item/mto_service_item_client.go
  pkg/handlers/ghcapi/mto_service_items.go
  pkg/handlers/ghcapi/mto_service_items_test.go
  pkg/handlers/primeapi/move_task_order_test.go
  pkg/handlers/primeapi/mto_service_item_test.go
  pkg/handlers/primeapi/payloads/payload_to_model.go
  pkg/handlers/primeapi/payloads/payload_to_model_test.go
  pkg/models/mto_service_item_customer_contacts.go
  pkg/models/mto_service_item_customer_contacts_test.go
  pkg/models/mto_service_items.go
  pkg/models/mto_service_items_test.go
  pkg/models/service_items_customer_contacts.go
  pkg/services/event/notification_test.go
  pkg/services/move_task_order/move_task_order_fetcher.go
  pkg/services/move_task_order/move_task_order_fetcher_test.go
  pkg/services/mto_service_item/mto_service_item_creator.go
  pkg/services/mto_service_item/mto_service_item_creator_test.go
  pkg/services/mto_service_item/mto_service_item_updater.go
  pkg/services/mto_service_item/mto_service_item_updater_test.go
  pkg/services/mto_service_item/mto_service_item_validators.go
  pkg/services/mto_service_item/mto_service_item_validators_test.go
  pkg/testdatagen/make_mto_service_item_customer_contact.go
  pkg/testdatagen/scenario/e2ebasic.go
  pkg/testdatagen/scenario/shared.go
  src/components/PrimeUI/CreateShipmentServiceItemForm/DestinationSITServiceItemForm.jsx
  swagger-def/prime.yaml
  swagger/prime.yaml
Labels: ready-to-merge, Huckleberry

#10768 [MB-15974] Upgrades storybook and related dependencies to 7.0.17
  package.json
  yarn.lock
Labels: dependencies

#10767 sit destination original address validation
  pkg/services/mto_service_item/mto_service_item_validators.go
  pkg/services/mto_service_item/mto_service_item_validators_test.go
Labels: Pamplemoose, ready-to-merge

#10769 [ on-call ] Cleaning up the CircleCI configuration file
  .circleci/config.yml
Labels: enhancement, ready-to-merge

#10649 [MB-15876] Prime API endpoint to create a SIT address change request
  .circleci/config.yml
  pkg/factory/sit_address_update_factory_test.go
  pkg/gen/primeapi/configure_mymove.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/mymove_api.go
  pkg/gen/primeapi/primeoperations/sit_address_update/create_s_i_t_address_update_request.go
  pkg/gen/primeapi/primeoperations/sit_address_update/create_s_i_t_address_update_request_parameters.go
  pkg/gen/primeapi/primeoperations/sit_address_update/create_s_i_t_address_update_request_responses.go
  pkg/gen/primeapi/primeoperations/sit_address_update/create_s_i_t_address_update_request_urlbuilder.go
  pkg/gen/primeclient/mymove_client.go
  pkg/gen/primeclient/sit_address_update/create_s_i_t_address_update_request_parameters.go
  pkg/gen/primeclient/sit_address_update/create_s_i_t_address_update_request_responses.go
  pkg/gen/primeclient/sit_address_update/sit_address_update_client.go
  pkg/gen/primemessages/create_s_i_t_address_update_request.go
  pkg/gen/primemessages/sit_address_update.go
  pkg/gen/primemessages/sit_address_update_status.go
  pkg/handlers/ghcapi/mto_service_items.go
  pkg/handlers/ghcapi/mto_service_items_test.go
  pkg/handlers/primeapi/api.go
  pkg/handlers/primeapi/payloads/model_to_payload.go
  pkg/handlers/primeapi/payloads/model_to_payload_test.go
  pkg/handlers/primeapi/payloads/payload_to_model.go
  pkg/handlers/primeapi/payloads/payload_to_model_test.go
  pkg/handlers/primeapi/sit_service_item_address_update.go
  pkg/handlers/primeapi/sit_service_item_address_update_test.go
  pkg/models/mto_service_items.go
  pkg/models/sit_address_updates.go
  pkg/services/mocks/ApprovedSITAddressUpdateRequestCreator.go
  pkg/services/mto_service_item/mto_service_item_updater_test.go
  pkg/services/sit_address_update.go
  pkg/services/sit_address_update/approved_sit_address_update_creator.go
  pkg/services/sit_address_update/approved_sit_address_update_creator_test.go
  pkg/services/sit_address_update/rules.go
  pkg/services/sit_address_update/rules_test.go
  pkg/services/sit_address_update/sit_address_update_request_approver.go
  pkg/services/sit_address_update/sit_address_update_request_approver_test.go
  pkg/services/sit_address_update/sit_address_update_request_creator.go
  pkg/services/sit_address_update/sit_address_update_request_creator_test.go
  pkg/services/sit_address_update/sit_address_update_request_rejector.go
  pkg/services/sit_address_update/sit_address_update_request_rejector_test.go
  swagger-def/prime.yaml
  swagger/prime.yaml
Labels: Pamplemoose

#10728 MB-15796: TOO can view review request service item update modal
  src/components/Office/RequestedServiceItemsTable/RequestedServiceItemsTable.jsx
  src/components/Office/ServiceItemUpdateModal/ServiceItemUpdateModal.module.scss
  src/components/Office/ServiceItemsTable/ServiceItemsTable.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
  src/utils/shipmentDisplay.jsx
  src/utils/shipmentDisplay.test.jsx
Labels: Pamplemoose

#10648 [MB-15883, MB-15796] [FE] Create/reuse modal to edit the SIT address for the SIT service item
  .circleci/config.yml
  pkg/services/sit_address_update/approved_sit_address_update_creator.go
  src/components/Modal/Modal.jsx
  src/components/Office/RequestedServiceItemsTable/RequestedServiceItemsTable.jsx
  src/components/Office/ServiceItemUpdateModal/EditSitAddressChangeForm.jsx
  src/components/Office/ServiceItemUpdateModal/ServiceItemUpdateModal.jsx
  src/components/Office/ServiceItemUpdateModal/ServiceItemUpdateModal.module.scss
  src/components/Office/ServiceItemUpdateModal/ServiceItemUpdateModal.stories.jsx
  src/components/Office/ServiceItemUpdateModal/ServiceItemUpdateModal.test.jsx
  src/components/Office/ServiceItemUpdateModal/ServiceItemUpdateModalTestParams.js
  src/components/Office/ServiceItemsTable/ServiceItemsTable.jsx
  src/components/Office/ServiceItemsTable/ServiceItemsTable.test.jsx
  src/components/Office/SubmitSITExtensionModal/SubmitSITExtensionModal.stories.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
  src/services/ghcApi.js
  src/types/serviceItems.js
  src/utils/shipmentDisplay.jsx
  src/utils/shipmentDisplay.test.jsx
Labels: Pamplemoose
