Repository transcom/mymove, pull requests merged in 2024-02, with the labels that each got.

#11860 B 17919 int
  migrations/app/secure/20240124155759_20240124-homesafeconnect-cert.up.sql
  playwright/tests/my/milmove/ppms/customerPpmTestFixture.js
  src/components/Customer/PPM/Booking/DateAndLocationForm/DateAndLocationForm.jsx
  src/components/Customer/PPM/Booking/DateAndLocationForm/DateAndLocationForm.test.jsx
  src/pages/MyMove/PPM/Booking/DateAndLocation/DateAndLocation.jsx
  src/pages/MyMove/PPM/Booking/DateAndLocation/DateAndLocation.test.jsx
Labels: Scrummy Bears, INTEGRATION

#11903 B 18088 int helpdesk url update
  src/pages/InvalidPermissions/InvalidPermissions.jsx
  src/pages/Office/ServicesCounselingMoveInfo/ServicesCounselingMoveInfo.jsx
  src/pages/Office/ServicesCounselingMoveInfo/ServicesCounselingMoveInfo.test.jsx
  src/pages/Office/TXOMoveInfo/TXOMoveInfo.jsx
  src/pages/Office/TXOMoveInfo/TXOMoveInfo.test.jsx
  src/pages/Office/index.jsx
Labels: G-Unit, INTEGRATION

#11852 B-17927 - INTEGRATION - Prime Simulator Enhancements For New Move Order Document Download API
  go.mod
  src/pages/PrimeUI/MoveTaskOrder/MoveDetails.jsx
  src/pages/PrimeUI/MoveTaskOrder/MoveDetails.module.scss
  src/pages/PrimeUI/MoveTaskOrder/MoveDetails.test.jsx
  src/services/primeApi.js
  src/services/swaggerRequest.js
  src/shared/constants.js
Labels: INTEGRATION

#11908 B 18491 update endpoint for updateMTOServiceItem INT
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/mto_service_item/update_m_t_o_service_item.go
  pkg/gen/primeclient/mto_service_item/mto_service_item_client.go
  pkg/services/mto_service_item/mto_service_item_validators.go
  pkg/services/mto_service_item/mto_service_item_validators_test.go
  swagger-def/prime.yaml
  swagger/prime.yaml
Labels: Mountain Movers, INTEGRATION

#11907 B-18325-INT Update duty_location_names to remove references to old names
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240201201343_update_duty_location_names.up.sql
Labels: G-Unit, INTEGRATION

#11897 INT B-18314-adding-multi-move-data-to-dashboard
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/internal_move.go
  pkg/handlers/internalapi/moves.go
  pkg/models/move.go
  src/pages/MyMove/Multi-Moves/MultiMovesLandingPage.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesLandingPage.test.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesMoveContainer/MultiMovesMoveContainer.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesMoveInfoList/MultiMovesInfoList.test.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesMoveInfoList/MultiMovesMoveInfoList.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesTestData.js
  src/sagas/onboarding.js
  src/sagas/onboarding.test.js
  src/services/internalApi.js
  src/shared/Entities/modules/moves.js
  src/shared/Entities/modules/oktaUser.js
  src/shared/Entities/reducer.js
  src/shared/Entities/schema.js
  src/store/entities/selectors.js
  swagger-def/internal.yaml
  swagger/internal.yaml
Labels: Mountain Movers, INTEGRATION

#11911 B 18313 int updates
  src/pages/MyMove/Profile/Profile.jsx
  src/pages/MyMove/Profile/Profile.module.scss
  src/pages/MyMove/Profile/Profile.test.jsx
Labels: Mountain Movers, INTEGRATION

#11896 B 18058 aoa customer UI notification
  pkg/handlers/internalapi/internal/payloads/model_to_payload.go
  playwright/tests/my/milmove/ppms/customerPpmTestFixture.js
  src/pages/MyMove/Home/index.jsx
  src/pages/MyMove/Home/index.test.jsx
Labels: Scrummy Bears, INTEGRATION

#11895 kickback on B-17958 identify/create calculation values 1 - 6
  pkg/services/ppm_closeout/ppm_closeout.go
  pkg/services/ppm_closeout/ppm_closeout_test.go
Labels: ByteSize M&Ms, INTEGRATION

#11916 B 18492 Prime API sitAddressUpdate Deprecation Documentation Updates
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/sit_address_update/create_s_i_t_address_update_request.go
  pkg/gen/primeclient/sit_address_update/sit_address_update_client.go
  swagger-def/prime.yaml
  swagger/prime.yaml
Labels: Mountain Movers, INTEGRATION

#11919 B 18492 prime sit address update deprecation doc updates
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/sit_address_update/create_s_i_t_address_update_request.go
  pkg/gen/primeclient/sit_address_update/sit_address_update_client.go
  swagger-def/prime.yaml
  swagger/prime.yaml
Labels: Mountain Movers

#11821 B 18111 pay grade and duty location flow changes MAIN
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/order_pay_grade.go
  pkg/handlers/internalapi/orders.go
  pkg/handlers/internalapi/orders_test.go
  pkg/handlers/internalapi/service_members_test.go
  playwright/tests/my/mymove/onboarding.spec.js
  playwright/tests/my/mymove/orders.spec.js
  src/components/Customer/DodInfoForm/DodInfoForm.jsx
  src/components/Customer/DodInfoForm/DodInfoForm.test.jsx
  src/components/Customer/EditOrdersForm/EditOrdersForm.jsx
  src/components/Customer/EditOrdersForm/EditOrdersForm.test.jsx
  src/components/Customer/OrdersInfoForm/OrdersInfoForm.jsx
  src/components/Customer/OrdersInfoForm/OrdersInfoForm.stories.jsx
  src/components/Customer/OrdersInfoForm/OrdersInfoForm.test.jsx
  src/constants/customerStates.js
  src/constants/routes.js
  src/pages/MyMove/EditOrders.jsx
  src/pages/MyMove/Orders.jsx
  src/pages/MyMove/Orders.test.jsx
  src/pages/MyMove/Profile/ContactInfo.jsx
  src/pages/MyMove/Profile/ContactInfo.test.jsx
  src/pages/MyMove/Profile/DodInfo.jsx
  src/pages/MyMove/Profile/DodInfo.test.jsx
  src/pages/MyMove/Profile/ResidentialAddress.jsx
  src/pages/MyMove/Profile/ResidentialAddress.test.jsx
  src/scenes/MyMove/getWorkflowRoutes.jsx
  src/scenes/MyMove/getWorkflowRoutes.test.js
  src/scenes/Office/OrdersViewerPanel.js
  src/store/entities/selectors.js
  src/store/entities/selectors.test.js
  src/utils/customer.js
  swagger-def/internal.yaml
  swagger/internal.yaml
Labels: Mountain Movers

#11894 B 18085 identify create values 7 12 integration Kickback
  pkg/services/ppm_closeout/ppm_closeout.go
  pkg/services/ppm_closeout/ppm_closeout_test.go
Labels: ByteSize M&Ms, INTEGRATION

#11927 MAIN - B 17971 and b 17972 too submission to prime email
  pkg/assets/notifications/templates/move_issued_to_prime_template.html
  pkg/assets/notifications/templates/move_issued_to_prime_template.txt
  pkg/notifications/move_issued_to_prime_test.go
Labels: ByteSize M&Ms, MAIN

#11928 B 17856
  pkg/gen/primeapi/configure_mymove.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/mto_shipment/update_s_i_t_delivery_request.go
  pkg/gen/primeapi/primeoperations/mto_shipment/update_s_i_t_delivery_request_parameters.go
  pkg/gen/primeapi/primeoperations/mto_shipment/update_s_i_t_delivery_request_responses.go
  pkg/gen/primeapi/primeoperations/mto_shipment/update_s_i_t_delivery_request_urlbuilder.go
  pkg/gen/primeapi/primeoperations/mymove_api.go
  pkg/gen/primeclient/mto_shipment/mto_shipment_client.go
  pkg/gen/primeclient/mto_shipment/update_s_i_t_delivery_request_parameters.go
  pkg/gen/primeclient/mto_shipment/update_s_i_t_delivery_request_responses.go
  pkg/gen/primemessages/s_i_t_delivery_update.go
  pkg/gen/primemessages/s_i_t_status.go
  pkg/handlers/primeapi/api.go
  pkg/handlers/primeapi/mto_shipment.go
  pkg/handlers/primeapi/mto_shipment_test.go
  pkg/handlers/primeapi/payloads/model_to_payload.go
  pkg/services/mocks/ShipmentSITStatus.go
  pkg/services/mto_shipment.go
  pkg/services/sit_status/shipment_sit_status.go
  pkg/services/sit_status/shipment_sit_status_test.go
  swagger-def/definitions/prime/SITDeliveryUpdate.yaml
  swagger-def/definitions/prime/SITStatus.yaml
  swagger-def/prime.yaml
  swagger/prime.yaml
Labels: Scrummy Bears, MAIN

#11934 B-18184 Removed PersonallyProcuredMoves Incentive endpoint, and handler method
  pkg/gen/internalapi/configure_mymove.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalapi/internaloperations/mymove_api.go
  pkg/gen/internalapi/internaloperations/ppm/show_p_p_m_incentive.go
  pkg/gen/internalapi/internaloperations/ppm/show_p_p_m_incentive_parameters.go
  pkg/gen/internalapi/internaloperations/ppm/show_p_p_m_incentive_responses.go
  pkg/gen/internalapi/internaloperations/ppm/show_p_p_m_incentive_urlbuilder.go
  pkg/handlers/internalapi/api.go
  pkg/handlers/internalapi/personally_procured_move_incentive.go
  swagger-def/internal.yaml
  swagger/internal.yaml
Labels: G-Unit

#11923 MAIN B-18475-shipment-dest-address-update-with-sit-updates
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240206173201_update_shipment_address_update_table_sit_and_distance_columns.up.sql
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/shipment_address_update.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/shipment_address_update.go
  pkg/gen/primev2api/embedded_spec.go
  pkg/gen/primev2messages/shipment_address_update.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload_test.go
  pkg/models/shipment_address_updates.go
  pkg/services/mto_shipment/mto_shipment_fetcher.go
  pkg/services/shipment_address_update/shipment_address_update_requester.go
  pkg/services/shipment_address_update/shipment_address_update_requester_test.go
  swagger-def/definitions/ShipmentAddressUpdate.yaml
  swagger/ghc.yaml
  swagger/prime.yaml
  swagger/prime_v2.yaml
Labels: Mountain Movers

#11910 show actual move date for ppm
  src/components/Office/ShipmentDetails/ShipmentDetailsMain.jsx
  src/components/Office/ShipmentDetails/ShipmentDetailsMain.test.jsx
Labels: ByteSize M&Ms, INTEGRATION

#11925 MAIN - B 18161 update email customer submitted moves
  pkg/assets/notifications/templates/move_submitted_template.html
  pkg/assets/notifications/templates/move_submitted_template.txt
  pkg/notifications/move_submitted.go
  pkg/notifications/move_submitted_test.go
Labels: ByteSize M&Ms, MAIN

#11953 B-18193 API Fix Delete Weight Ticket
  pkg/handlers/internalapi/weight_ticket.go
  pkg/handlers/internalapi/weight_ticket_test.go
  pkg/services/mocks/WeightTicketDeleter.go
  pkg/services/weight_ticket.go
  pkg/services/weight_ticket/weight_ticket_deleter.go
  pkg/services/weight_ticket/weight_ticket_deleter_test.go
Labels: G-Unit, MAIN

#11945 B-18191 moved progear weight ticket delete query out of handler and into service
  pkg/handlers/internalapi/progear_weight_ticket.go
  pkg/handlers/internalapi/progear_weight_ticket_test.go
  pkg/services/mocks/ProgearWeightTicketDeleter.go
  pkg/services/progear_weight_ticket.go
  pkg/services/progear_weight_ticket/progear_weight_ticket_deleter.go
  pkg/services/progear_weight_ticket/progear_weight_ticket_deleter_test.go
Labels: G-Unit, MAIN

#11776 B 18027 - STAGING -- create service layer to create download payload (Part 2: with resolution to correct deployment issue in STAGING)
  pkg/handlers/primeapi/api.go
  pkg/handlers/primeapi/move_task_order.go
  pkg/handlers/primeapi/move_task_order_test.go
  pkg/models/document.go
  pkg/paperwork/generator.go
  pkg/services/mocks/PrimeDownloadMoveUploadPDFGenerator.go
  pkg/services/paperwork.go
  pkg/services/paperwork/paperwork_service_test.go
  pkg/services/paperwork/prime_download_user_upload_to_pdf_converter.go
  pkg/services/paperwork/prime_download_user_upload_to_pdf_converter_test.go
Labels: Scrummy Bears, MAIN

#11779 B-18192 move query logic from handler to service object
  pkg/handlers/internalapi/moving_expense.go
  pkg/handlers/internalapi/moving_expense_test.go
  pkg/services/mocks/MovingExpenseDeleter.go
  pkg/services/moving_expense.go
  pkg/services/moving_expense/moving_expense_deleter.go
  pkg/services/moving_expense/moving_expense_deleter_test.go
Labels: G-Unit, MAIN

#11958 B-18650
  config/tls/Certificates_PKCS7_v5.13_DoD.der.p7b
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240207173709_updateTransportationOffices.up.sql
Labels: Mountain Movers, INTEGRATION

#11956 B-18194 add auth check to weight ticket update
  pkg/services/weight_ticket/weight_ticket_updater.go
  pkg/services/weight_ticket/weight_ticket_updater_test.go
Labels: G-Unit, MAIN

#11922 INT B-18316 remove rank & duty_location from service_member table
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240205165638_remove_rank_and_duty_location_columns_from_service_members_table.up.sql
Labels: Mountain Movers, INTEGRATION

#11926 MAIN B-18386-Multi-Moves-Landing-Page-Component-Creation
  src/components/ButtonDropdownMenu/ButtonDropdownMenu.jsx
  src/components/ButtonDropdownMenu/ButtonDropdownMenu.module.scss
  src/components/ButtonDropdownMenu/ButtonDropdownMenu.stories.jsx
  src/components/ButtonDropdownMenu/ButtonDropdownMenu.test.jsx
  src/components/Office/ShipmentContainer/ShipmentContainer.jsx
  src/constants/routes.js
  src/pages/MyMove/Multi-Moves/MultiMovesLandingPage.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesLandingPage.module.scss
  src/pages/MyMove/Multi-Moves/MultiMovesLandingPage.test.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesMoveContainer/MultiMovesMoveContainer.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesMoveContainer/MultiMovesMoveContainer.module.scss
  src/pages/MyMove/Multi-Moves/MultiMovesMoveContainer/MultiMovesMoveContainer.stories.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesMoveContainer/MultiMovesMoveContainer.test.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesMoveHeader/MultiMovesMoveHeader.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesMoveHeader/MultiMovesMoveHeader.module.scss
  src/pages/MyMove/Multi-Moves/MultiMovesMoveHeader/MultiMovesMoveHeader.stories.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesMoveHeader/MultiMovesMoveHeader.test.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesMoveInfoList/MultiMovesInfoList.stories.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesMoveInfoList/MultiMovesInfoList.test.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesMoveInfoList/MultiMovesMoveInfoList.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesMoveInfoList/MultiMovesMoveInfoList.module.scss
  src/pages/MyMove/Multi-Moves/MultiMovesTestData.js
  src/scenes/MyMove/index.jsx
  src/shared/constants.js
Labels: Mountain Movers, MAIN

#11924 MAIN B-18411-UI-shipment-address-update-review-screen-updates
  src/components/Office/AddressUpdatePreview/AddressUpdatePreview.jsx
  src/components/Office/AddressUpdatePreview/AddressUpdatePreview.test.jsx
  src/components/Office/ShipmentAddressUpdateReviewRequestModal/ShipmentAddressUpdateReviewRequestModal.jsx
Labels: Mountain Movers, MAIN

#11769 B-18182 remove old personally procured move handler and code
  pkg/gen/internalapi/configure_mymove.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalapi/internaloperations/mymove_api.go
  pkg/gen/internalapi/internaloperations/ppm/patch_personally_procured_move.go
  pkg/gen/internalapi/internaloperations/ppm/patch_personally_procured_move_parameters.go
  pkg/gen/internalapi/internaloperations/ppm/patch_personally_procured_move_responses.go
  pkg/gen/internalapi/internaloperations/ppm/patch_personally_procured_move_urlbuilder.go
  pkg/gen/internalapi/internaloperations/ppm/request_p_p_m_payment.go
  pkg/gen/internalapi/internaloperations/ppm/request_p_p_m_payment_parameters.go
  pkg/gen/internalapi/internaloperations/ppm/request_p_p_m_payment_responses.go
  pkg/gen/internalapi/internaloperations/ppm/request_p_p_m_payment_urlbuilder.go
  pkg/gen/internalapi/internaloperations/ppm/submit_personally_procured_move.go
  pkg/gen/internalapi/internaloperations/ppm/submit_personally_procured_move_parameters.go
  pkg/gen/internalapi/internaloperations/ppm/submit_personally_procured_move_responses.go
  pkg/gen/internalapi/internaloperations/ppm/submit_personally_procured_move_urlbuilder.go
  pkg/gen/internalmessages/patch_personally_procured_move_payload.go
  pkg/gen/internalmessages/submit_personally_procured_move_payload.go
  pkg/handlers/internalapi/api.go
  pkg/handlers/internalapi/moves.go
  pkg/handlers/internalapi/personally_procured_move.go
  pkg/services/event/internal_endpoint.go
  src/services/internalApi.js
  src/shared/Entities/modules/ppms.js
  swagger-def/internal.yaml
  swagger/internal.yaml
Labels: G-Unit, MAIN

#11952 INT-B-18171 hal prime actions cause sit to be calculated
  src/constants/MoveHistory/Database/DateFields.js
  src/constants/MoveHistory/Database/FieldMappings.js
  src/constants/MoveHistory/Database/MonetaryFields.js
  src/constants/MoveHistory/Database/WeightFields.js
  src/constants/MoveHistory/EventTemplates/UpdateMTOShipment/UpdateMTOShipmentPPMDetails.test.jsx
  src/constants/MoveHistory/EventTemplates/UpdateMovingExpense/UpdateMovingExpense.test.jsx
  src/pages/Office/MoveHistory/LabeledDetails.test.jsx
Labels: G-Unit, INTEGRATION

#11946 18180 remove ppm estimated weight
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240112205201_remove_ppm_estimated_weight.up.sql
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/list_prime_move.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/list_move.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/primeapi/move_task_order_test.go
  pkg/handlers/primeapi/payloads/model_to_payload.go
  pkg/handlers/primeapiv2/move_task_order_test.go
  pkg/handlers/primeapiv2/payloads/model_to_payload.go
  pkg/handlers/supportapi/internal/payloads/model_to_payload.go
  pkg/handlers/supportapi/internal/payloads/payload_to_model.go
  pkg/models/move.go
  pkg/services/event/notification_payloads.go
  pkg/services/support/move_task_order/move_task_order_creator.go
  swagger-def/ghc.yaml
  swagger-def/prime.yaml
  swagger/ghc.yaml
  swagger/prime.yaml
Labels: G-Unit, MAIN

#11954 B-18088 helpdesk url update
  src/pages/InvalidPermissions/InvalidPermissions.jsx
  src/pages/Office/ServicesCounselingMoveInfo/ServicesCounselingMoveInfo.jsx
  src/pages/Office/ServicesCounselingMoveInfo/ServicesCounselingMoveInfo.test.jsx
  src/pages/Office/TXOMoveInfo/TXOMoveInfo.jsx
  src/pages/Office/TXOMoveInfo/TXOMoveInfo.test.jsx
  src/pages/Office/index.jsx
Labels: G-Unit, MAIN

#11963 B-18325 update duty_location_names table to get rid of old base names
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240201201343_update_duty_location_names.up.sql
Labels: G-Unit, MAIN

#11920 B 18490 update mto v2 final destination sit int
  config/tls/Certificates_PKCS7_v5.12_DoD.der.p7b
  config/tls/ECA_Root_CA_4.cer
  config/tls/IdenTrust-ECA-S23.cer
  config/tls/milmove-cert-bundle.p7b
  config/tls/mmb.gov.uat.homesafeconnect.com.cer
  migrations/app/migrations_manifest.txt
  migrations/app/secure/20240201174442_20240201_homesafe_prd_cert.up.sql
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/mto_shipment/update_m_t_o_shipment.go
  pkg/gen/primeclient/mto_shipment/mto_shipment_client.go
  pkg/gen/primev2api/configure_mymove.go
  pkg/gen/primev2api/embedded_spec.go
  pkg/gen/primev2api/primev2operations/mto_shipment/update_m_t_o_shipment.go
  pkg/gen/primev2api/primev2operations/mto_shipment/update_m_t_o_shipment_parameters.go
  pkg/gen/primev2api/primev2operations/mto_shipment/update_m_t_o_shipment_responses.go
  pkg/gen/primev2api/primev2operations/mto_shipment/update_m_t_o_shipment_urlbuilder.go
  pkg/gen/primev2api/primev2operations/mymove_api.go
  pkg/gen/primev2client/mto_shipment/mto_shipment_client.go
  pkg/gen/primev2client/mto_shipment/update_m_t_o_shipment_parameters.go
  pkg/gen/primev2client/mto_shipment/update_m_t_o_shipment_responses.go
  pkg/handlers/ghcapi/mto_shipment.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/handlers/internalapi/mto_shipment.go
  pkg/handlers/internalapi/mto_shipment_test.go
  pkg/handlers/primeapi/mto_shipment.go
  pkg/handlers/primeapiv2/api.go
  pkg/handlers/primeapiv2/mto_shipment.go
  pkg/services/mocks/MTOShipmentUpdater.go
  pkg/services/mocks/ShipmentUpdater.go
  pkg/services/mto_shipment.go
  pkg/services/mto_shipment/mto_shipment_updater.go
  pkg/services/mto_shipment/mto_shipment_updater_test.go
  pkg/services/orchestrators/shipment/shipment_updater.go
  pkg/services/orchestrators/shipment/shipment_updater_test.go
  pkg/services/shipment_orchestrator.go
  swagger-def/prime.yaml
  swagger-def/prime_v2.yaml
  swagger/prime.yaml
  swagger/prime_v2.yaml
Labels: Mountain Movers, INTEGRATION

#11959 B 18477
  src/components/Customer/Home/Step/Step.stories.jsx
  src/components/ShipmentList/ShipmentList.jsx
  src/components/ShipmentList/ShipmentList.stories.jsx
  src/components/ShipmentList/ShipmentList.test.jsx
  src/pages/Office/MovePaymentRequests/MovePaymentRequests.test.jsx
Labels: Mountain Movers, MAIN

#11984 B 18310 multi move feature flag main
  .envrc
  cmd/milmove/serve.go
  config/env/demo.app-client-tls.env
  config/env/demo.app.env
  config/env/exp.app-client-tls.env
  config/env/exp.app.env
  config/env/loadtest.app-client-tls.env
  config/env/loadtest.app.env
  config/env/prd.app-client-tls.env
  config/env/prd.app.env
  config/env/stg.app-client-tls.env
  config/env/stg.app.env
  pkg/handlers/config.go
  pkg/services/feature_flag.go
  src/utils/featureFlags.js
Labels: Mountain Movers, MAIN

#11983 B-18092 - STAGING - Add new flag Prime Download Move Order Docs API
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/move_task_order/download_move_order.go
  pkg/gen/primeapi/primeoperations/move_task_order/download_move_order_parameters.go
  pkg/gen/primeapi/primeoperations/move_task_order/download_move_order_urlbuilder.go
  pkg/gen/primeapi/primeoperations/mymove_api.go
  pkg/gen/primeclient/move_task_order/download_move_order_parameters.go
  pkg/gen/primeclient/move_task_order/download_move_order_responses.go
  pkg/gen/primeclient/move_task_order/move_task_order_client.go
  pkg/handlers/primeapi/move_task_order.go
  pkg/handlers/primeapi/move_task_order_test.go
  swagger-def/prime.yaml
  swagger/prime.yaml
Labels: Scrummy Bears

#11948 B 18449 remove unused ppm field signed certification
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240124153121_remove_ppmid_from_signedcertification_table.up.sql
  pkg/factory/signed_certification_factory.go
  pkg/factory/signed_certification_factory_test.go
  pkg/handlers/internalapi/internal/payloads/payload_to_model.go
  pkg/handlers/internalapi/signed_certifications.go
  pkg/handlers/internalapi/signed_certifications_test.go
  pkg/models/move.go
  pkg/models/shipment_summary_worksheet_test.go
  pkg/models/signed_certification.go
  pkg/models/signed_certification_test.go
  pkg/services/paperwork/form_creator_test.go
  pkg/services/ppmshipment/ppm_shipment_fetcher_test.go
  pkg/services/signed_certification/rules.go
  pkg/services/signed_certification/rules_test.go
  pkg/services/signed_certification/signed_certification_updater_test.go
Labels: G-Unit, MAIN

#11982 Flipt implementation main
  .envrc
  cmd/milmove/serve.go
  config/flipt/storage/development.features.yaml
  docker-compose.feature_flag.yml
  pkg/certs/certs.go
  pkg/handlers/config.go
  pkg/services/feature_flag.go
  src/pages/MyMove/Multi-Moves/MultiMovesLandingPage.jsx
  src/scenes/MyMove/index.jsx
  src/utils/featureFlags.js
Labels: Mountain Movers, MAIN

#11962 B 18059 int
  .circleci/config.yml
  .github/workflows/auto-approve.yml
  .github/workflows/go-auto-approve.yml
  src/components/Office/DefinitionLists/PPMShipmentInfoList.jsx
  src/components/Office/ShipmentDisplay/ShipmentDisplay.test.jsx
  src/components/Office/ShipmentDisplay/ShipmentDisplayTestData.js
Labels: Scrummy Bears, INTEGRATION

#11988 B-17927 - STAGING - Prime Simulator Enhancements For New Move Order Document Download API
  src/pages/PrimeUI/MoveTaskOrder/MoveDetails.jsx
  src/pages/PrimeUI/MoveTaskOrder/MoveDetails.module.scss
  src/pages/PrimeUI/MoveTaskOrder/MoveDetails.test.jsx
  src/services/primeApi.js
  src/services/swaggerRequest.js
  src/shared/constants.js
Labels: Scrummy Bears, MAIN

#11993 B-18185 remove personally procured move shared handler
  pkg/handlers/internalapi/personally_procured_move_shared.go
  pkg/handlers/internalapi/personally_procured_move_shared_test.go
Labels: G-Unit, MAIN

#11989 B 18171 hal prime actions cause sit to be calculated
  src/constants/MoveHistory/Database/DateFields.js
  src/constants/MoveHistory/Database/FieldMappings.js
  src/constants/MoveHistory/Database/MonetaryFields.js
  src/constants/MoveHistory/Database/WeightFields.js
  src/constants/MoveHistory/EventTemplates/UpdateMTOShipment/UpdateMTOShipmentPPMDetails.test.jsx
  src/constants/MoveHistory/EventTemplates/UpdateMovingExpense/UpdateMovingExpense.test.jsx
  src/pages/Office/MoveHistory/LabeledDetails.test.jsx
Labels: G-Unit, MAIN

#11981 B-18109
  src/hooks/custom.js
Labels: Mountain Movers, MAIN

#11964 B 18318 add seed data for multiple moves INT
  pkg/testdatagen/scenario/devseed.go
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/scenario/subscenarios.go
Labels: Mountain Movers, INTEGRATION

#11998 B-18733 - INTEGRATION - Prime Sim UI - Display Error Message Off response error
  .envrc
  cmd/milmove/gen_disable_certs_migration.go
  cmd/milmove/main.go
  cmd/milmove/serve.go
  go.mod
  go.sum
  migrations/app/migrations_manifest.txt
  migrations/app/secure/20240212150834_20240212_disable_homesafe_stg_cert.up.sql
  pkg/gen/internalapi/internaloperations/moves/get_all_moves_urlbuilder.go
  pkg/handlers/config.go
  pkg/services/feature_flag.go
  src/pages/PrimeUI/MoveTaskOrder/MoveDetails.jsx
  src/utils/featureFlags.js
Labels: Scrummy Bears, INTEGRATION

#12008 new makefile command multi_branch
  Makefile
Labels: ByteSize M&Ms, MAIN

#12000 B 18058 aoa customer notification (playwright test fixes)
  playwright/tests/my/milmove/ppms/customerPpmTestFixture.js
  playwright/tests/my/milmove/ppms/entireShipmentOnboarding.spec.js
  playwright/tests/my/milmove/ppms/navigateToUploadDocs.spec.js
Labels: Scrummy Bears, INTEGRATION

#11965 B 18318 add seed data for multiple moves MAIN
  pkg/testdatagen/scenario/devseed.go
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/scenario/subscenarios.go
Labels: Mountain Movers

#12015 B-17908-INT
  src/constants/MoveHistory/Database/FieldMappings.js
  src/constants/MoveHistory/EventTemplates/CreateMTOShipment/CreateMTOShipmentUpdateMoves.jsx
  src/constants/MoveHistory/EventTemplates/CreateMTOShipment/CreateMTOShipmentUpdateMoves.test.jsx
  src/constants/MoveHistory/EventTemplates/index.js
Labels: G-Unit, INTEGRATION

#11938 B 17975 customer submitted final ppm email
  pkg/assets/notifications/templates/ppm_packet_email_template.html
  pkg/assets/notifications/templates/ppm_packet_email_template.txt
  pkg/handlers/apitests.go
  pkg/handlers/internalapi/api_test.go
  pkg/handlers/internalapi/ppm_shipment.go
  pkg/handlers/routing/base_routing_suite.go
  pkg/models/ppm_shipment.go
  pkg/notifications/ppm_packet_email.go
  pkg/notifications/ppm_packet_email_test.go
  pkg/testdatagen/testharness/make_move.go
Labels: ByteSize M&Ms, MAIN

#12011 B 18645 move grade to orders from allowances int
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/counseling_update_order_payload.go
  pkg/gen/ghcmessages/update_order_payload.go
  pkg/services/order/order_updater.go
  pkg/services/order/order_updater_test.go
  playwright/tests/office/qaecsr/csrFlows.spec.js
  src/components/Office/AllowancesDetailForm/AllowancesDetailForm.jsx
  src/components/Office/AllowancesDetailForm/AllowancesDetailForm.test.jsx
  src/components/Office/DefinitionLists/AllowancesList.jsx
  src/components/Office/DefinitionLists/AllowancesList.test.jsx
  src/components/Office/DefinitionLists/OrdersList.jsx
  src/components/Office/DefinitionLists/OrdersList.stories.jsx
  src/components/Office/DefinitionLists/OrdersList.test.jsx
  src/components/Office/OrdersDetailForm/OrdersDetailForm.jsx
  src/components/Office/OrdersDetailForm/OrdersDetailForm.stories.jsx
  src/components/Office/OrdersDetailForm/OrdersDetailForm.test.jsx
  src/pages/Office/MoveAllowances/MoveAllowances.jsx
  src/pages/Office/MoveAllowances/MoveAllowances.test.jsx
  src/pages/Office/MoveDetails/MoveDetails.jsx
  src/pages/Office/Orders/Orders.jsx
  src/pages/Office/Orders/Orders.test.jsx
  src/pages/Office/ServicesCounselingMoveAllowances/ServicesCounselingMoveAllowances.jsx
  src/pages/Office/ServicesCounselingMoveAllowances/ServicesCounselingMoveAllowances.test.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.test.jsx
  src/pages/Office/ServicesCounselingOrders/ServicesCounselingOrders.jsx
  src/pages/Office/ServicesCounselingOrders/ServicesCounselingOrders.test.jsx
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: Mountain Movers, INTEGRATION

#12014 B 17984 update reminder email integration
  pkg/notifications/move_payment_reminder.go
  pkg/notifications/move_payment_reminder_test.go
Labels: ByteSize M&Ms, INTEGRATION

#12026 INT B-18653 Multi-Moves Routing & Enhancements
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/internal_move.go
  pkg/handlers/internalapi/moves.go
  pkg/handlers/internalapi/moves_test.go
  pkg/models/move.go
  src/components/ShipmentList/ShipmentList.jsx
  src/constants/routes.js
  src/pages/MyMove/Home/MoveHome.jsx
  src/pages/MyMove/Home/MoveHome.test.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesLandingPage.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesLandingPage.test.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesMoveContainer/MultiMovesMoveContainer.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesMoveInfoList/MultiMovesInfoList.test.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesMoveInfoList/MultiMovesMoveInfoList.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesTestData.js
  src/pages/MyMove/Orders.jsx
  src/pages/MyMove/Orders.test.jsx
  src/pages/MyMove/UploadOrders.jsx
  src/sagas/entities.js
  src/sagas/entities.test.js
  src/scenes/MyMove/index.jsx
  src/store/entities/actions.js
  swagger-def/internal.yaml
  swagger/internal.yaml
Labels: Mountain Movers, INTEGRATION

#12009 B-18448 Removed PersonallyProcuredMoves Fields from ShipmentSummaryWorksheet, Move model
  pkg/factory/mto_shipment_factory.go
  pkg/factory/ppm_shipment_factory.go
  pkg/handlers/internalapi/moves.go
  pkg/handlers/internalapi/uploads.go
  pkg/handlers/internalapi/users.go
  pkg/handlers/primeapi/payloads/model_to_payload_test.go
  pkg/handlers/primeapiv2/payloads/model_to_payload_test.go
  pkg/models/errors.go
  pkg/models/move.go
  pkg/models/order.go
  pkg/models/ppm_shipment.go
  pkg/models/service_member.go
  pkg/models/shipment_summary_worksheet.go
  pkg/models/weight_ticket.go
  pkg/services/move/move_router.go
  pkg/services/move/move_router_test.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet_test.go
  pkg/testdatagen/make_personally_procured_move.go
  pkg/testdatagen/scenario/e2ebasic.go
Labels: G-Unit, INTEGRATION

#12028 B 18560
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240207173709_updateTransportationOffices.up.sql
  migrations/app/schema/20240214213247_updateTransportationOfficesGbloc.up.sql
  pkg/services/order/order_fetcher.go
Labels: Mountain Movers, MAIN

#12013 B 18058 aoa customer notification step
  pkg/handlers/internalapi/internal/payloads/model_to_payload.go
  playwright/tests/my/milmove/ppms/customerPpmTestFixture.js
  playwright/tests/my/milmove/ppms/entireShipmentOnboarding.spec.js
  playwright/tests/my/milmove/ppms/navigateToUploadDocs.spec.js
  src/pages/MyMove/Home/index.jsx
  src/pages/MyMove/Home/index.test.jsx
Labels: Scrummy Bears, MAIN

#12036 INT B-18652-Multi-Move Dashboard Button Changes
  src/pages/MyMove/Multi-Moves/MultiMovesMoveContainer/MultiMovesMoveContainer.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesMoveContainer/MultiMovesMoveContainer.module.scss
  src/pages/MyMove/Multi-Moves/MultiMovesMoveContainer/MultiMovesMoveContainer.test.jsx
Labels: Mountain Movers, INTEGRATION

#12031 B 18429 ssw model to service object conversion
  cmd/generate-shipment-summary/main.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalapi/internaloperations/moves/show_shipment_summary_worksheet.go
  pkg/gen/internalapi/internaloperations/moves/show_shipment_summary_worksheet_parameters.go
  pkg/gen/internalapi/internaloperations/moves/show_shipment_summary_worksheet_urlbuilder.go
  pkg/gen/internalapi/internaloperations/mymove_api.go
  pkg/handlers/internalapi/api.go
  pkg/handlers/internalapi/moves.go
  pkg/models/ppm_shipment.go
  pkg/paperwork/shipment_summary.go
  pkg/paperwork/shipment_summary_test.go
  pkg/services/mocks/SSWPPMComputer.go
  pkg/services/paperwork/form_creator_test.go
  pkg/services/shipment_summary_worksheet.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet_service_test.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet_test.go
  swagger-def/internal.yaml
  swagger/internal.yaml
Labels: Scrummy Bears, MAIN

#11862 B 18317 multi move get all moves endpoint
  pkg/gen/internalapi/configure_mymove.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalapi/internaloperations/moves/get_all_moves.go
  pkg/gen/internalapi/internaloperations/moves/get_all_moves_parameters.go
  pkg/gen/internalapi/internaloperations/moves/get_all_moves_responses.go
  pkg/gen/internalapi/internaloperations/moves/get_all_moves_urlbuilder.go
  pkg/gen/internalapi/internaloperations/mymove_api.go
  pkg/gen/internalmessages/internal_move.go
  pkg/gen/internalmessages/moves_list.go
  pkg/handlers/internalapi/api.go
  pkg/handlers/internalapi/moves.go
  pkg/handlers/internalapi/moves_test.go
  pkg/models/move.go
  pkg/models/move_test.go
  swagger-def/internal.yaml
  swagger/internal.yaml
Labels: Mountain Movers, MAIN

#12041 MAIN B-18313 Multi-Moves Profile Validation & Create a Move Btn Functionality
  src/components/Customer/Profile/ContactInfoDisplay/ContactInfoDisplay.jsx
  src/components/Customer/Profile/OktaInfoDisplay/OktaInfoDisplay.jsx
  src/components/Customer/Review/ServiceInfoDisplay/ServiceInfoDisplay.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesLandingPage.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesLandingPage.test.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesMoveContainer/MultiMovesMoveContainer.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesMoveContainer/MultiMovesMoveContainer.stories.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesMoveContainer/MultiMovesMoveContainer.test.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesMoveInfoList/MultiMovesInfoList.test.jsx
  src/pages/MyMove/Profile/EditContactInfo.jsx
  src/pages/MyMove/Profile/EditContactInfo.test.jsx
  src/pages/MyMove/Profile/EditOktaInfo.jsx
  src/pages/MyMove/Profile/EditOktaInfo.test.jsx
  src/pages/MyMove/Profile/EditOrdersPayGradeAndOriginLocation.test.jsx
  src/pages/MyMove/Profile/EditServiceInfo.jsx
  src/pages/MyMove/Profile/EditServiceInfo.test.jsx
  src/pages/MyMove/Profile/Profile.jsx
  src/pages/MyMove/Profile/Profile.module.scss
  src/pages/MyMove/Profile/Profile.test.jsx
Labels: Mountain Movers, MAIN

#12040 MAIN B-18314 (merge after B-18313)
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/internal_move.go
  pkg/handlers/internalapi/moves.go
  pkg/models/move.go
  src/pages/MyMove/Multi-Moves/MultiMovesLandingPage.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesLandingPage.test.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesMoveContainer/MultiMovesMoveContainer.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesMoveInfoList/MultiMovesInfoList.test.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesMoveInfoList/MultiMovesMoveInfoList.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesTestData.js
  src/sagas/onboarding.js
  src/sagas/onboarding.test.js
  src/services/internalApi.js
  src/shared/Entities/modules/moves.js
  src/shared/Entities/modules/oktaUser.js
  src/shared/Entities/reducer.js
  src/shared/Entities/schema.js
  src/store/entities/selectors.js
  swagger-def/internal.yaml
  swagger/internal.yaml
Labels: Mountain Movers, MAIN

#12043 MAIN B-18653 (merge after B-18314)
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/internal_move.go
  pkg/handlers/internalapi/moves.go
  pkg/handlers/internalapi/moves_test.go
  pkg/models/move.go
  src/components/ShipmentList/ShipmentList.jsx
  src/constants/routes.js
  src/pages/MyMove/Home/MoveHome.jsx
  src/pages/MyMove/Home/MoveHome.test.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesLandingPage.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesLandingPage.test.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesMoveContainer/MultiMovesMoveContainer.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesMoveInfoList/MultiMovesInfoList.test.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesMoveInfoList/MultiMovesMoveInfoList.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesTestData.js
  src/pages/MyMove/Orders.test.jsx
  src/pages/MyMove/UploadOrders.jsx
  src/sagas/entities.js
  src/sagas/entities.test.js
  src/scenes/MyMove/index.jsx
  src/store/entities/actions.js
  swagger-def/internal.yaml
  swagger/internal.yaml
Labels: Mountain Movers, MAIN

#12057 B-17908-INT after rebase
  src/constants/MoveHistory/Database/FieldMappings.js
  src/constants/MoveHistory/EventTemplates/CreateMTOShipment/CreateMTOShipmentUpdateMoves.jsx
  src/constants/MoveHistory/EventTemplates/CreateMTOShipment/CreateMTOShipmentUpdateMoves.test.jsx
  src/constants/MoveHistory/EventTemplates/index.js
Labels: G-Unit, INTEGRATION

#12055 B 18840 int
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240223144515_add_pro_gear_weights_to_mto_shipments.up.sql
Labels: Scrummy Bears, INTEGRATION

#12054 B 18884 add sit delivery miles col to mto service item table int
  cmd/milmove/gen_disable_certs_migration.go
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240222154935_add_sit_delivery_miles_to_mto_service_items.up.sql
  migrations/app/secure/20240215151854_20240215_remove_expired_homesafe_prd_cert.up.sql
  pkg/models/mto_service_items.go
Labels: Mountain Movers, INTEGRATION

#12052 B 18896 redefine order audit table ignored columns int 2
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240222144140_redefine_order_audit_table_grade_col.up.sql
Labels: Mountain Movers, INTEGRATION

#12064 B 18645 move grade to orders from allowances int 2
  go.mod
  go.sum
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/counseling_update_order_payload.go
  pkg/gen/ghcmessages/update_order_payload.go
  pkg/services/order/order_updater.go
  pkg/services/order/order_updater_test.go
  playwright/tests/office/qaecsr/csrFlows.spec.js
  src/components/Office/AllowancesDetailForm/AllowancesDetailForm.jsx
  src/components/Office/AllowancesDetailForm/AllowancesDetailForm.test.jsx
  src/components/Office/DefinitionLists/AllowancesList.jsx
  src/components/Office/DefinitionLists/AllowancesList.test.jsx
  src/components/Office/DefinitionLists/OrdersList.jsx
  src/components/Office/DefinitionLists/OrdersList.stories.jsx
  src/components/Office/DefinitionLists/OrdersList.test.jsx
  src/components/Office/OrdersDetailForm/OrdersDetailForm.jsx
  src/components/Office/OrdersDetailForm/OrdersDetailForm.stories.jsx
  src/components/Office/OrdersDetailForm/OrdersDetailForm.test.jsx
  src/pages/Office/MoveAllowances/MoveAllowances.jsx
  src/pages/Office/MoveAllowances/MoveAllowances.test.jsx
  src/pages/Office/MoveDetails/MoveDetails.jsx
  src/pages/Office/Orders/Orders.jsx
  src/pages/Office/Orders/Orders.test.jsx
  src/pages/Office/ServicesCounselingMoveAllowances/ServicesCounselingMoveAllowances.jsx
  src/pages/Office/ServicesCounselingMoveAllowances/ServicesCounselingMoveAllowances.test.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.test.jsx
  src/pages/Office/ServicesCounselingOrders/ServicesCounselingOrders.jsx
  src/pages/Office/ServicesCounselingOrders/ServicesCounselingOrders.test.jsx
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: Mountain Movers, INTEGRATION

#12070 B-18796: Add County Column on Address Table
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240226183440_add_county_column_to_address_table.up.sql
Labels: Mountain Movers, INTEGRATION

#12048 created checkValidSitAddlDates and added to payment request creation
  pkg/services/payment_request/payment_request_creator.go
  pkg/services/payment_request/rules.go
  pkg/services/payment_request/rules_test.go
Labels: Mountain Movers, INTEGRATION

#12020 MAIN B-18316 (DO NOT MERGE BEFORE B-18457)
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240220145356_remove_rank_and_duty_location_columns_from_service_members_table.up.sql
Labels: Mountain Movers, MAIN

#12030 B 17984 update reminder email
  migrations/app/migrations_manifest.txt
  pkg/notifications/move_payment_reminder.go
  pkg/notifications/move_payment_reminder_test.go
Labels: ByteSize M&Ms, MAIN

#11937 B-18322 Update Requested pickup date
  src/components/Office/ImportantShipmentDates/ImportantShipmentDates.jsx
  src/components/Office/ImportantShipmentDates/ImportantShipmentDates.test.jsx
  src/components/Office/ShipmentDetails/ShipmentDetailsMain.jsx
  src/components/Office/ShipmentDetails/ShipmentDetailsMain.test.jsx
Labels: ByteSize M&Ms, MAIN

#12087 INT B-18820 update office users table
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240227180121_add_status_edipi_other_unique_id_and_rej_reason_to_office_users_table.up.sql
Labels: Mountain Movers, INTEGRATION

#12025 B-18645 main
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/counseling_update_order_payload.go
  pkg/gen/ghcmessages/update_order_payload.go
  pkg/services/order/order_updater.go
  pkg/services/order/order_updater_test.go
  playwright/tests/office/qaecsr/csrFlows.spec.js
  src/components/Office/AllowancesDetailForm/AllowancesDetailForm.jsx
  src/components/Office/AllowancesDetailForm/AllowancesDetailForm.test.jsx
  src/components/Office/DefinitionLists/AllowancesList.jsx
  src/components/Office/DefinitionLists/AllowancesList.test.jsx
  src/components/Office/DefinitionLists/OrdersList.jsx
  src/components/Office/DefinitionLists/OrdersList.stories.jsx
  src/components/Office/DefinitionLists/OrdersList.test.jsx
  src/components/Office/OrdersDetailForm/OrdersDetailForm.jsx
  src/components/Office/OrdersDetailForm/OrdersDetailForm.stories.jsx
  src/components/Office/OrdersDetailForm/OrdersDetailForm.test.jsx
  src/pages/Office/MoveAllowances/MoveAllowances.jsx
  src/pages/Office/MoveAllowances/MoveAllowances.test.jsx
  src/pages/Office/MoveDetails/MoveDetails.jsx
  src/pages/Office/Orders/Orders.jsx
  src/pages/Office/Orders/Orders.test.jsx
  src/pages/Office/ServicesCounselingMoveAllowances/ServicesCounselingMoveAllowances.jsx
  src/pages/Office/ServicesCounselingMoveAllowances/ServicesCounselingMoveAllowances.test.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.test.jsx
  src/pages/Office/ServicesCounselingOrders/ServicesCounselingOrders.jsx
  src/pages/Office/ServicesCounselingOrders/ServicesCounselingOrders.test.jsx
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: Mountain Movers

#12075 B-18060-INTEGRATION- Wire up AOA Packet download link - Customer/Office
  src/components/Office/DefinitionLists/PPMShipmentInfoList.jsx
  src/components/Office/DefinitionLists/PPMShipmentInfoList.test.jsx
  src/components/Office/DefinitionLists/ShipmentInfoListSelector.jsx
  src/components/Office/ShipmentDisplay/ShipmentDisplay.jsx
  src/pages/MyMove/Home/index.jsx
  src/pages/MyMove/Home/index.test.jsx
  src/services/ghcApi.js
  src/services/internalApi.js
  src/services/swaggerRequest.test.js
  src/shared/DownloadAOAErrorModal/DownloadAOAErrorModal.jsx
  src/shared/DownloadAOAErrorModal/DownloadAOAErrorModal.module.scss
  src/utils/download.js
  src/utils/download.test.js
Labels: Scrummy Bears, INTEGRATION

#12071 B 18794 trdm table and model int
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240223154843_us_post_region_city_trdm_table_creation.up.sql
  pkg/factory/shared.go
  pkg/factory/us_post_region_city_factory.go
  pkg/factory/us_post_region_city_factory_test.go
  pkg/models/us_post_region_city.go
  pkg/models/us_post_region_city_test.go
Labels: Mountain Movers, INTEGRATION

#12068 B-18883: Allow Update Of ServiceItem That Is Linked To A Payment Request
  pkg/services/mto_service_item/mto_service_item_validators.go
  pkg/services/mto_service_item/mto_service_item_validators_test.go
Labels: Mountain Movers, INTEGRATION

#12065 B 18448 int deprecate personally procured moves fields revised
  pkg/factory/mto_shipment_factory.go
  pkg/factory/ppm_shipment_factory.go
  pkg/handlers/internalapi/moves.go
  pkg/handlers/internalapi/uploads.go
  pkg/handlers/internalapi/users.go
  pkg/handlers/primeapi/payloads/model_to_payload_test.go
  pkg/handlers/primeapiv2/payloads/model_to_payload_test.go
  pkg/models/errors.go
  pkg/models/move.go
  pkg/models/order.go
  pkg/models/ppm_shipment.go
  pkg/models/service_member.go
  pkg/models/weight_ticket.go
  pkg/services/move/move_router.go
  pkg/services/move/move_router_test.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet_test.go
  pkg/testdatagen/make_personally_procured_move.go
  pkg/testdatagen/scenario/e2ebasic.go
  pkg/testdatagen/shared.go
Labels: G-Unit, INTEGRATION

#12085 B-17908
  src/constants/MoveHistory/Database/FieldMappings.js
  src/constants/MoveHistory/EventTemplates/CreateMTOShipment/CreateMTOShipmentUpdateMoves.jsx
  src/constants/MoveHistory/EventTemplates/CreateMTOShipment/CreateMTOShipmentUpdateMoves.test.jsx
  src/constants/MoveHistory/EventTemplates/index.js
Labels: G-Unit, MAIN

#12098 B 18522 I 12556 sit addl validation int
  src/services/primeApi.js
Labels: bug, Mountain Movers, INTEGRATION

#12101 revert listmoves and update getmove
  src/services/primeApi.js
Labels: bug, Mountain Movers, INTEGRATION

#12045 INT-B-18881 Add Search SC
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/move/search_moves.go
  pkg/services/move/move_searcher.go
  pkg/services/move/move_searcher_test.go
  playwright/tests/office/qaecsr/moveSearchFlows.spec.js
  src/components/Table/SearchResultsTable.jsx
  src/components/Table/SearchResultsTable.module.scss
  src/components/Table/Table.module.scss
  src/components/Table/TableQueue.jsx
  src/components/Table/TableQueue.module.scss
  src/constants/queues.js
  src/constants/routes.js
  src/hooks/queries.js
  src/pages/Office/QAECSRMoveSearch/QAECSRMoveSearch.jsx
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.jsx
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.module.scss
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.test.jsx
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: G-Unit, INTEGRATION

#12100 B:18796 Add County Column on Address Table
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240226183440_add_county_column_to_address_table.up.sql
Labels: Mountain Movers, MAIN

#12099 INT B-18680 Departure Date For Origin Sit Is Not Persisting
  .github/workflows/stale-issues-pull-requests.yml
  go.mod
  go.sum
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240220145356_remove_rank_and_duty_location_columns_from_service_members_table.up.sql
  pkg/handlers/primeapi/mto_service_item_test.go
  pkg/handlers/primeapi/payloads/payload_to_model.go
  pkg/handlers/primeapi/payloads/payload_to_model_test.go
  pkg/notifications/move_payment_reminder.go
  pkg/notifications/move_payment_reminder_test.go
  playwright/tests/office/txo/sitUpdates.spec.js
  src/components/Office/ConvertSITToCustomerExpenseModal/ConvertSITToCustomerExpenseModal.jsx
  src/components/Office/ImportantShipmentDates/ImportantShipmentDates.jsx
  src/components/Office/ImportantShipmentDates/ImportantShipmentDates.test.jsx
  src/components/Office/ReviewSITExtensionModal/ReviewSITExtensionModal.jsx
  src/components/Office/ShipmentDetails/ShipmentDetailsMain.jsx
  src/components/Office/ShipmentDetails/ShipmentDetailsMain.test.jsx
  src/components/Office/ShipmentSITDisplay/ShipmentSITDisplay.jsx
  src/components/Office/ShipmentSITDisplay/ShipmentSITDisplay.test.jsx
  src/components/Office/SubmitSITExtensionModal/SubmitSITExtensionModal.jsx
  src/constants/MoveHistory/Database/FieldMappings.js
  src/constants/MoveHistory/EventTemplates/index.js
Labels: ByteSize M&Ms, INTEGRATION

#12110 Int b 18680 departure date for origin sit is not persisting
  migrations/app/schema/20240220145356_remove_rank_and_duty_location_columns_from_service_members_table.up.sql
Labels: ByteSize M&Ms, INTEGRATION

#12115 MAIN B-18652 MultiMove add download and Go to Move button for each move
  src/pages/MyMove/Multi-Moves/MultiMovesMoveContainer/MultiMovesMoveContainer.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesMoveContainer/MultiMovesMoveContainer.module.scss
  src/pages/MyMove/Multi-Moves/MultiMovesMoveContainer/MultiMovesMoveContainer.test.jsx
Labels: Mountain Movers, MAIN

#12080 B-18896 redefine order audit table ignored columns
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240222144140_redefine_order_audit_table_grade_col.up.sql
Labels: Mountain Movers

#12114 MAIN B-18820 add status, edipi, otheruniqueid, rej reason, to office_users table
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240227180121_add_status_edipi_other_unique_id_and_rej_reason_to_office_users_table.up.sql
Labels: Mountain Movers, MAIN

#12090 Int b 19034
  pkg/handlers/ghcapi/ppm_document.go
  pkg/handlers/internalapi/ppm_shipment.go
Labels: ByteSize M&Ms, INTEGRATION

#12053 B-18434 -INT- PPM onboarding to use address instead of zip code
  pkg/factory/ppm_shipment_factory.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/p_p_m_shipment.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/create_p_p_m_shipment.go
  pkg/gen/internalmessages/p_p_m_shipment.go
  pkg/gen/internalmessages/update_p_p_m_shipment.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/handlers/internalapi/api.go
  pkg/handlers/internalapi/internal/payloads/model_to_payload.go
  pkg/handlers/internalapi/internal/payloads/payload_to_model.go
  pkg/handlers/internalapi/mto_shipment_test.go
  pkg/handlers/primeapi/api.go
  pkg/handlers/primeapi/mto_shipment_test.go
  pkg/handlers/primeapiv2/api.go
  pkg/handlers/primeapiv2/mto_shipment_test.go
  pkg/models/ppm_shipment.go
  pkg/notifications/ppm_packet_email.go
  pkg/notifications/ppm_packet_email_test.go
  pkg/services/mto_shipment/mto_shipment_fetcher.go
  pkg/services/ppmshipment/ppm_shipment_creator.go
  pkg/services/ppmshipment/ppm_shipment_creator_test.go
  pkg/services/ppmshipment/ppm_shipment_fetcher.go
  pkg/services/ppmshipment/ppm_shipment_fetcher_test.go
  pkg/services/ppmshipment/ppm_shipment_updater.go
  pkg/services/ppmshipment/ppm_shipment_updater_test.go
  pkg/services/ppmshipment/validation.go
  pkg/testdatagen/testharness/make_move.go
  playwright/tests/my/milmove/ppms/advances.spec.js
  playwright/tests/my/milmove/ppms/customerPpmTestFixture.js
  playwright/tests/my/milmove/ppms/dateAndLocation.spec.js
  playwright/tests/my/milmove/ppms/entireShipmentOnboarding.spec.js
  playwright/tests/my/milmove/ppms/estimatedIncentive.spec.js
  src/components/Customer/PPM/Booking/DateAndLocationForm/DateAndLocationForm.jsx
  src/components/Customer/PPM/Booking/DateAndLocationForm/DateAndLocationForm.stories.jsx
  src/components/Customer/PPM/Booking/DateAndLocationForm/DateAndLocationForm.test.jsx
  src/pages/MyMove/PPM/Booking/DateAndLocation/DateAndLocation.jsx
  src/pages/MyMove/PPM/Booking/DateAndLocation/DateAndLocation.test.jsx
  src/utils/validation.js
  swagger-def/definitions/PPMShipment.yaml
  swagger-def/internal.yaml
  swagger/ghc.yaml
  swagger/internal.yaml
Labels: Scrummy Bears, INTEGRATION
