Repository transcom/mymove, pull requests merged in 2024-03, with the labels that each got.

#12124 I 12575 INT Playwright SIT test failure fix
  pkg/testdatagen/testharness/make_move.go
Labels: INTEGRATION

#12125 I 12575 Playwright SIT test failure fix
  pkg/testdatagen/testharness/make_move.go
Labels: MAIN

#12119 B 18522 i 12556 fix loadtest prime sim
  config/env/loadtest.app.env
  src/services/primeApi.js
Labels: bug, Mountain Movers, MAIN

#11986 B-18312-MultiMove-Dashboard Routing-And-Playwright-Tests
  package.json
  playwright.config.js
  playwright/tests/globalSetup.js
  playwright/tests/my/milmove/ppms/about.spec.js
  playwright/tests/my/milmove/ppms/advances.spec.js
  playwright/tests/my/milmove/ppms/dateAndLocation.spec.js
  playwright/tests/my/milmove/ppms/entireShipmentCloseout.spec.js
  playwright/tests/my/milmove/ppms/entireShipmentOnboarding.spec.js
  playwright/tests/my/milmove/ppms/estimatedIncentive.spec.js
  playwright/tests/my/milmove/ppms/estimatedWeightsProgear.spec.js
  playwright/tests/my/milmove/ppms/expenses.spec.js
  playwright/tests/my/milmove/ppms/finalCloseout.spec.js
  playwright/tests/my/milmove/ppms/navigateToUploadDocs.spec.js
  playwright/tests/my/milmove/ppms/progear.spec.js
  playwright/tests/my/milmove/ppms/review.spec.js
  playwright/tests/my/milmove/ppms/weightTickets.spec.js
  playwright/tests/my/mymove/hhg.spec.js
  playwright/tests/my/mymove/nts.spec.js
  playwright/tests/my/mymove/ntsr.spec.js
  playwright/tests/my/mymove/onboarding.spec.js
  playwright/tests/my/mymove/orders.spec.js
  playwright/tests/my/mymove/uploads.spec.js
  playwright/tests/utils/my/waitForCustomerPage.js
  src/constants/routes.js
Labels: Mountain Movers, MAIN

#12127 B-18328 adjusted to accommodate showing the actual move date correctly - going into INT branch
  src/components/Office/ShipmentDetails/ShipmentDetailsMain.jsx
Labels: ByteSize M&Ms, INTEGRATION

#12128 B-18328 adjusted to accommodate showing the actual move date correctly - going into MAIN branch
  src/components/Office/ShipmentDetails/ShipmentDetailsMain.jsx
Labels: ByteSize M&Ms, MAIN

#12111 B 18840 int revised
  migrations/app/schema/20240223144515_add_pro_gear_weights_to_mto_shipments.up.sql
Labels: Scrummy Bears, INTEGRATION

#12123 MAIN B-18881 add search sc
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/move/search_moves.go
  pkg/services/move/move_searcher.go
  pkg/services/move/move_searcher_test.go
  playwright/tests/office/qaecsr/moveSearchFlows.spec.js
  src/components/Table/SearchResultsTable.jsx
  src/components/Table/SearchResultsTable.module.scss
  src/components/Table/Table.module.scss
  src/components/Table/TableQueue.jsx
  src/components/Table/TableQueue.module.scss
  src/constants/queues.js
  src/constants/routes.js
  src/hooks/queries.js
  src/pages/Office/QAECSRMoveSearch/QAECSRMoveSearch.jsx
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.jsx
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.module.scss
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.test.jsx
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: G-Unit, MAIN

#12105 kickback - B-17965 Send Email - Gov't Counselor Submission (Before TOO Approval)
  pkg/assets/notifications/templates/move_counseled_template.html
  pkg/assets/notifications/templates/move_counseled_template.txt
  pkg/handlers/ghcapi/move_task_order.go
  pkg/notifications/move_counseled_test.go
Labels: ByteSize M&Ms, INTEGRATION

#12126 MAIN B-18680 Departure Date For Origin Sit Is Not Persisting
  migrations/app/schema/20240220145356_remove_rank_and_duty_location_columns_from_service_members_table.up.sql
  pkg/handlers/primeapi/mto_service_item_test.go
  pkg/handlers/primeapi/payloads/payload_to_model.go
  pkg/handlers/primeapi/payloads/payload_to_model_test.go
  playwright/tests/office/txo/sitUpdates.spec.js
  src/components/Office/ConvertSITToCustomerExpenseModal/ConvertSITToCustomerExpenseModal.jsx
  src/components/Office/ReviewSITExtensionModal/ReviewSITExtensionModal.jsx
  src/components/Office/ShipmentSITDisplay/ShipmentSITDisplay.jsx
  src/components/Office/ShipmentSITDisplay/ShipmentSITDisplay.test.jsx
  src/components/Office/SubmitSITExtensionModal/SubmitSITExtensionModal.jsx
Labels: ByteSize M&Ms, MAIN

#12138 B 19035 update payment reminder email template integration
  pkg/assets/notifications/templates/move_payment_reminder_template.html
  pkg/assets/notifications/templates/move_payment_reminder_template.txt
  pkg/notifications/move_payment_reminder.go
  pkg/notifications/move_payment_reminder_test.go
Labels: ByteSize M&Ms, INTEGRATION

#12140 B 18794 trdm table and model main
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240223154843_us_post_region_city_trdm_table_creation.up.sql
  pkg/factory/shared.go
  pkg/factory/us_post_region_city_factory.go
  pkg/factory/us_post_region_city_factory_test.go
  pkg/models/us_post_region_city.go
  pkg/models/us_post_region_city_test.go
Labels: Mountain Movers, MAIN

#12130 B 17854 int sit authorized end date calculation
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240119005610_add_authorized_end_date_to_mto_services_items.up.sql
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/s_i_t_status.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/primeapi/mto_service_item.go
  pkg/models/mto_service_items.go
  pkg/services/mocks/MTOServiceItemUpdater.go
  pkg/services/mto_service_item.go
  pkg/services/mto_service_item/mto_service_item_updater.go
  pkg/services/mto_service_item/mto_service_item_updater_test.go
  pkg/services/mto_shipment.go
  pkg/services/sit_status/shipment_sit_status.go
  src/components/Office/ShipmentSITDisplay/ShipmentSITDisplay.jsx
  src/components/Office/ShipmentSITDisplay/ShipmentSITDisplay.test.jsx
  src/components/Office/ShipmentSITDisplay/ShipmentSITDisplayTestParams.js
  swagger-def/definitions/SITStatus.yaml
  swagger/ghc.yaml
Labels: Scrummy Bears, INTEGRATION

#12147 kickback - B-17965 Send Email - Gov't Counselor Submission (Before TOO Approval)
  pkg/assets/notifications/templates/move_counseled_template.html
  pkg/assets/notifications/templates/move_counseled_template.txt
  pkg/handlers/ghcapi/move_task_order.go
  pkg/notifications/move_counseled_test.go
Labels: ByteSize M&Ms, MAIN

#12166 B-18883: Allow Update Of ServiceItem That Is Linked To A Payment Request
  pkg/services/mto_service_item/mto_service_item_validators.go
  pkg/services/mto_service_item/mto_service_item_validators_test.go
Labels: Mountain Movers, MAIN

#12094 B 18188 int removed deprecated personally procured moves model and devseed data
  cmd/milmove-tasks/main.go
  cmd/milmove-tasks/send_payment_reminder_email.go
  migrations/app/migrations_manifest.txt
  package.json
  pkg/factory/move_factory.go
  pkg/factory/payment_request_interchange_control_number_factory.go
  pkg/factory/shared.go
  pkg/factory/shared_test.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/category_expense_summary.go
  pkg/gen/internalmessages/create_reimbursement.go
  pkg/gen/internalmessages/index_personally_procured_move_payload.go
  pkg/gen/internalmessages/move_dates_summary.go
  pkg/gen/internalmessages/move_payload.go
  pkg/gen/internalmessages/p_p_m_status.go
  pkg/gen/internalmessages/payment_methods_totals.go
  pkg/gen/internalmessages/personally_procured_move_payload.go
  pkg/gen/internalmessages/t_shirt_size.go
  pkg/handlers/internalapi/entitlements_test.go
  pkg/handlers/internalapi/move_queue_items_test.go
  pkg/handlers/internalapi/signed_certifications.go
  pkg/handlers/internalapi/signed_certifications_test.go
  pkg/models/move.go
  pkg/models/order.go
  pkg/models/order_test.go
  pkg/models/personally_procured_move.go
  pkg/models/personally_procured_move_test.go
  pkg/models/ppm_shipment.go
  pkg/models/queue.go
  pkg/models/queue_test.go
  pkg/models/service_member_test.go
  pkg/models/signed_certification_test.go
  pkg/notifications/move_payment_reminder_test.go
  pkg/services/move/move_router_test.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet.go
  pkg/testdatagen/make_personally_procured_move.go
  pkg/testdatagen/shared.go
  pkg/testdatagen/testharness/dispatch.go
  pkg/testdatagen/testharness/make_move.go
  swagger-def/internal.yaml
  swagger/internal.yaml
  yarn.lock
Labels: G-Unit, INTEGRATION

#12176 INT B-18652-Multi-Move Dashboard Button Changes 2
  src/pages/MyMove/Multi-Moves/MultiMovesMoveContainer/MultiMovesMoveContainer.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesMoveContainer/MultiMovesMoveContainer.module.scss
  src/pages/MyMove/Multi-Moves/MultiMovesMoveContainer/MultiMovesMoveContainer.test.jsx
Labels: Mountain Movers, INTEGRATION

#12146 B 19034 main
  pkg/handlers/ghcapi/ppm_document.go
  pkg/handlers/internalapi/ppm_shipment.go
Labels: ByteSize M&Ms, MAIN

#12179 INT B-17960 PPM Closeout Calculations Display - Hotfix
  migrations/app/migrations_manifest.txt
  src/components/Office/PPM/PPMHeaderSummary/HeaderSection.stories.jsx
  src/components/Office/PPM/PPMHeaderSummary/PPMHeaderSummary.stories.jsx
  src/components/Office/PPM/ReviewDocumentsSidePanel/ReviewDocumentsSidePanel.stories.jsx
  src/components/Office/PPM/ReviewExpense/ReviewExpense.stories.jsx
  src/components/Office/PPM/ReviewProGear/ReviewProGear.stories.jsx
  src/components/Office/PPM/ReviewWeightTicket/ReviewWeightTicket.stories.jsx
  src/components/Office/PPM/ppmTestData.js
Labels: ByteSize M&Ms, INTEGRATION

#12160 B 17960 PPM Closeout Calculations Breakout Display Main
  pkg/apperror/errors.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/m_t_o_shipment.go
  pkg/gen/ghcmessages/p_p_m_closeout.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/mto_shipment.go
  pkg/handlers/ghcapi/ppm_closeout.go
  pkg/handlers/ghcapi/ppm_closeout_test.go
  pkg/models/ppm_shipment.go
  pkg/services/ghcrateengine/shared.go
  pkg/services/mocks/PPMCloseoutFetcher.go
  pkg/services/ppm_closeout.go
  pkg/services/ppm_closeout/ppm_closeout.go
  pkg/services/ppm_closeout/ppm_closeout_service_test.go
  pkg/services/ppm_closeout/ppm_closeout_test.go
  pkg/services/ppmshipment/ppm_estimator.go
  pkg/testdatagen/testharness/dispatch.go
  pkg/testdatagen/testharness/make_move.go
  src/components/Office/PPM/PPMHeaderSummary/HeaderSection.jsx
  src/components/Office/PPM/PPMHeaderSummary/HeaderSection.module.scss
  src/components/Office/PPM/PPMHeaderSummary/PPMHeaderSummary.jsx
  src/components/Office/PPM/PPMHeaderSummary/PPMHeaderSummary.module.scss
  src/components/Office/PPM/PPMHeaderSummary/PPMHeaderSummary.stories.jsx
  src/components/Office/PPM/PPMHeaderSummary/PPMHeaderSummary.test.jsx
  src/components/Office/PPM/ReviewDocumentsSidePanel/ReviewDocumentsSidePanel.jsx
  src/components/Office/PPM/ReviewDocumentsSidePanel/ReviewDocumentsSidePanel.module.scss
  src/components/Office/PPM/ReviewDocumentsSidePanel/ReviewDocumentsSidePanel.stories.jsx
  src/components/Office/PPM/ReviewDocumentsSidePanel/ReviewDocumentsSidePanel.test.jsx
  src/components/Office/PPM/ReviewExpense/ReviewExpense.jsx
  src/components/Office/PPM/ReviewExpense/ReviewExpense.stories.jsx
  src/components/Office/PPM/ReviewExpense/ReviewExpense.test.jsx
  src/components/Office/PPM/ReviewProGear/ReviewProGear.jsx
  src/components/Office/PPM/ReviewProGear/ReviewProGear.stories.jsx
  src/components/Office/PPM/ReviewProGear/ReviewProGear.test.jsx
  src/components/Office/PPM/ReviewWeightTicket/ReviewWeightTicket.jsx
  src/components/Office/PPM/ReviewWeightTicket/ReviewWeightTicket.stories.jsx
  src/components/Office/PPM/ReviewWeightTicket/ReviewWeightTicket.test.jsx
  src/components/Office/PPM/ppmTestData.js
  src/constants/queryKeys.js
  src/hooks/queries.js
  src/pages/Office/DocumentViewerSidebar/DocumentViewerSidebar.module.scss
  src/pages/Office/PPM/ReviewDocuments/ReviewDocuments.jsx
  src/pages/Office/PPM/ReviewDocuments/ReviewDocuments.test.jsx
  src/services/ghcApi.js
  src/types/shipment.js
  swagger-def/definitions/MTOShipment.yaml
  swagger-def/definitions/PPMCloseout.yaml
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: ByteSize M&Ms, MAIN

#12183 INT-B-18637 create bb order type
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/queues/get_moves_queue_parameters.go
  pkg/gen/ghcapi/ghcoperations/queues/get_moves_queue_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/queues/get_payment_requests_queue_parameters.go
  pkg/gen/ghcapi/ghcoperations/queues/get_payment_requests_queue_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/queues/get_services_counseling_queue_parameters.go
  pkg/gen/ghcapi/ghcoperations/queues/get_services_counseling_queue_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/queues/list_prime_moves_parameters.go
  pkg/gen/ghcapi/ghcoperations/queues/list_prime_moves_urlbuilder.go
  pkg/gen/ghcmessages/orders_type.go
  pkg/gen/ghcmessages/queue_move.go
  pkg/gen/ghcmessages/queue_payment_request.go
  pkg/gen/ghcmessages/search_move.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/orders_type.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/orders_type.go
  pkg/gen/primev2api/embedded_spec.go
  pkg/gen/primev2messages/orders_type.go
  pkg/gen/supportapi/embedded_spec.go
  pkg/gen/supportmessages/orders_type.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/queues.go
  pkg/services/order.go
  pkg/services/payment_request.go
  src/components/CustomerHeader/index.jsx
  src/components/CustomerHeader/index.module.scss
  src/components/MilMoveHeader/index.jsx
  src/components/MilMoveHeader/index.module.scss
  src/components/Table/SearchResultsTable.jsx
  src/components/Table/SearchResultsTable.module.scss
  src/constants/orders.js
  src/containers/Headers/CustomerLoggedInHeader.jsx
  src/containers/Headers/CustomerLoggedInHeader.test.jsx
  src/pages/Office/MoveQueue/MoveQueue.jsx
  src/pages/Office/MoveQueue/MoveQueue.module.scss
  src/pages/Office/PaymentRequestQueue/PaymentRequestQueue.jsx
  src/pages/Office/PaymentRequestQueue/PaymentRequestQueue.module.scss
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.jsx
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.module.scss
  swagger-def/definitions/OrdersType.yaml
  swagger-def/ghc.yaml
  swagger-def/support.yaml
  swagger/ghc.yaml
  swagger/internal.yaml
  swagger/prime.yaml
  swagger/prime_v2.yaml
  swagger/support.yaml
Labels: G-Unit, INTEGRATION

#12195 INT B-18753 Move History Log for Service Counselor Approves
  pkg/assets/sql_scripts/move_history_fetcher.sql
  src/constants/MoveHistory/Database/StatusFields.js
  src/constants/MoveHistory/EventTemplates/FinishDocumentReview/finishDocumentReview.jsx
  src/constants/MoveHistory/EventTemplates/FinishDocumentReview/finishDocumentReview.test.jsx
  src/constants/MoveHistory/EventTemplates/UpdateMTOStatusServiceCounselingCompleted/updateMTOStatusServiceCounselingCompleted.jsx
  src/constants/MoveHistory/EventTemplates/UpdateMTOStatusServiceCounselingCompleted/updateMTOStatusServiceCounselingCompleted.test.jsx
  src/constants/MoveHistory/EventTemplates/UpdateMTOStatusServiceCounselingCompleted/updateMTOStatusServiceCounselingCompletedPPM.jsx
  src/constants/MoveHistory/EventTemplates/UpdateMTOStatusServiceCounselingCompleted/updateMTOStatusServiceCounselingCompletedPPM.test.jsx
  src/constants/MoveHistory/EventTemplates/index.js
  src/constants/MoveHistory/UIDisplay/Operations.js
  src/pages/Office/MoveHistory/LabeledDetails.jsx
Labels: ByteSize M&Ms, INTEGRATION

#12174 B 17854 sit authorized end date calculation
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240119005610_add_authorized_end_date_to_mto_services_items.up.sql
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/s_i_t_status.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/primeapi/mto_service_item.go
  pkg/models/mto_service_items.go
  pkg/services/mocks/MTOServiceItemUpdater.go
  pkg/services/mto_service_item.go
  pkg/services/mto_service_item/mto_service_item_updater.go
  pkg/services/mto_service_item/mto_service_item_updater_test.go
  pkg/services/mto_shipment.go
  pkg/services/sit_status/shipment_sit_status.go
  src/components/Office/ShipmentSITDisplay/ShipmentSITDisplay.jsx
  src/components/Office/ShipmentSITDisplay/ShipmentSITDisplay.test.jsx
  src/components/Office/ShipmentSITDisplay/ShipmentSITDisplayTestParams.js
  swagger-def/definitions/SITStatus.yaml
  swagger/ghc.yaml
Labels: Scrummy Bears, MAIN

#12204 B 19035 update payment reminder email template integration
  go.mod
  go.sum
  pkg/assets/notifications/templates/move_payment_reminder_template.html
  pkg/assets/notifications/templates/move_payment_reminder_template.txt
  pkg/factory/ppm_shipment_factory.go
  pkg/notifications/move_payment_reminder.go
  pkg/notifications/move_payment_reminder_test.go
Labels: ByteSize M&Ms, INTEGRATION

#12205 MAIN B-18753 Move History Log for Service Counselor Approves
  pkg/assets/sql_scripts/move_history_fetcher.sql
  src/constants/MoveHistory/Database/StatusFields.js
  src/constants/MoveHistory/EventTemplates/FinishDocumentReview/finishDocumentReview.jsx
  src/constants/MoveHistory/EventTemplates/FinishDocumentReview/finishDocumentReview.test.jsx
  src/constants/MoveHistory/EventTemplates/UpdateMTOStatusServiceCounselingCompleted/updateMTOStatusServiceCounselingCompleted.jsx
  src/constants/MoveHistory/EventTemplates/UpdateMTOStatusServiceCounselingCompleted/updateMTOStatusServiceCounselingCompleted.test.jsx
  src/constants/MoveHistory/EventTemplates/UpdateMTOStatusServiceCounselingCompleted/updateMTOStatusServiceCounselingCompletedPPM.jsx
  src/constants/MoveHistory/EventTemplates/UpdateMTOStatusServiceCounselingCompleted/updateMTOStatusServiceCounselingCompletedPPM.test.jsx
  src/constants/MoveHistory/EventTemplates/index.js
  src/constants/MoveHistory/UIDisplay/Operations.js
  src/pages/Office/MoveHistory/LabeledDetails.jsx
Labels: ByteSize M&Ms, MAIN

#12207 INTEGRATION-B-18434 - (part 2) Fix issue related to PPM update and MultiMove changes in INT
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240308181906_add_has_secondary_pickup_address_and_has_secondary_delivery_address_to_ppm_shipments.up.sql
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/p_p_m_shipment.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/p_p_m_shipment.go
  pkg/gen/internalmessages/update_p_p_m_shipment.go
  pkg/handlers/internalapi/internal/payloads/model_to_payload.go
  pkg/handlers/internalapi/internal/payloads/payload_to_model.go
  pkg/models/move.go
  pkg/models/ppm_shipment.go
  pkg/services/ppmshipment/ppm_shipment_creator.go
  pkg/services/ppmshipment/ppm_shipment_creator_test.go
  pkg/services/ppmshipment/validation.go
  pkg/services/ppmshipment/validation_test.go
  playwright/tests/my/milmove/ppms/customerPpmTestFixture.js
  playwright/tests/my/milmove/ppms/estimatedIncentive.spec.js
  swagger-def/definitions/PPMShipment.yaml
  swagger-def/internal.yaml
  swagger/ghc.yaml
  swagger/internal.yaml
Labels: Scrummy Bears, INTEGRATION

#12181 Create main-to-integration-sync.yml
  .github/workflows/main-to-integration-sync.yml
Labels: enhancement, help wanted, MAIN

#12184 B 18735 int auto check the move management box
  playwright/tests/office/txo/tooFlowsNTS.spec.js
  playwright/tests/office/txo/tooFlowsNTSR.spec.js
  playwright/tests/office/txo/tooTestFixture.js
  src/components/Office/RequestedShipments/RequestedShipments.test.jsx
  src/components/Office/RequestedShipments/SubmittedRequestedShipments.jsx
Labels: Scrummy Bears, INTEGRATION

#12121 INT B-18824 requested office users get single user endpoint
  pkg/gen/adminapi/adminoperations/mymove_api.go
  pkg/gen/adminapi/adminoperations/requested_office_users/get_requested_office_user.go
  pkg/gen/adminapi/adminoperations/requested_office_users/get_requested_office_user_parameters.go
  pkg/gen/adminapi/adminoperations/requested_office_users/get_requested_office_user_responses.go
  pkg/gen/adminapi/adminoperations/requested_office_users/get_requested_office_user_urlbuilder.go
  pkg/gen/adminapi/adminoperations/requested_office_users/index_requested_office_users.go
  pkg/gen/adminapi/configure_mymove.go
  pkg/gen/adminapi/embedded_spec.go
  pkg/handlers/adminapi/api.go
  pkg/handlers/adminapi/requested_office_users.go
  pkg/handlers/adminapi/requested_office_users_test.go
  pkg/services/requested_office_users.go
  pkg/services/requested_office_users/requested_office_user_fetcher.go
  pkg/services/requested_office_users/requested_office_user_fetcher_test.go
  swagger-def/admin.yaml
  swagger/admin.yaml
Labels: Mountain Movers, INTEGRATION

#12167 B 17906 int Prevent Customer Request after Authorized End Date
  pkg/handlers/primeapi/mto_service_item.go
  pkg/services/mto_service_item/mto_service_item_updater.go
  pkg/services/mto_service_item/mto_service_item_updater_test.go
  pkg/services/sit_extension/approved_sit_duration_update_creator.go
  src/components/Office/ShipmentSITDisplay/ShipmentSITDisplay.jsx
  src/components/Office/ShipmentSITDisplay/ShipmentSITDisplay.test.jsx
  src/components/Office/ShipmentSITDisplay/ShipmentSITDisplayTestParams.js
  src/components/Office/SubmitSITExtensionModal/SubmitSITExtensionModal.jsx
Labels: Scrummy Bears, INTEGRATION

#12210 B-17907 KICKBACK
  src/constants/MoveHistory/Database/FieldMappings.js
  src/constants/MoveHistory/EventTemplates/SubmitPPMShipmentDocumentation/SubmitPPMShipmentDocumentation.jsx
  src/constants/MoveHistory/EventTemplates/SubmitPPMShipmentDocumentation/SubmitPPMShipmentDocumentation.test.jsx
  src/constants/MoveHistory/EventTemplates/index.js
  src/constants/MoveHistory/UIDisplay/Operations.js
Labels: G-Unit, MAIN

#12182 INTEGRATION - BP-18060 - Wire up AOA packet link customer/office (PART 2 - FIX CUSTOMER ISSUE)
  .github/workflows/main-to-integration-sync.yml
  migrations/app/schema/20240206173201_update_shipment_address_update_table_sit_and_distance_columns.up.sql
  src/components/Office/DefinitionLists/PPMShipmentInfoList.jsx
  src/components/Office/DefinitionLists/PPMShipmentInfoList.test.jsx
  src/pages/MyMove/Home/MoveHome.jsx
  src/pages/MyMove/Home/MoveHome.test.jsx
  src/pages/MyMove/Home/index.jsx
  src/pages/MyMove/Home/index.test.jsx
  src/shared/AsyncPacketDownloadLink/AsyncPacketDownloadLink.jsx
  src/shared/AsyncPacketDownloadLink/AsyncPacketDownloadLink.module.scss
  src/shared/AsyncPacketDownloadLink/AsyncPacketDownloadLink.test.jsx
  src/utils/download.js
  src/utils/download.test.js
Labels: Scrummy Bears, INTEGRATION

#12216 MAIN - B-18434 - Zip to Address change for PPM onboarding (Customer)
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240308181906_add_has_secondary_pickup_address_and_has_secondary_delivery_address_to_ppm_shipments.up.sql
  pkg/factory/ppm_shipment_factory.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/p_p_m_shipment.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/create_p_p_m_shipment.go
  pkg/gen/internalmessages/p_p_m_shipment.go
  pkg/gen/internalmessages/update_p_p_m_shipment.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/handlers/internalapi/api.go
  pkg/handlers/internalapi/internal/payloads/model_to_payload.go
  pkg/handlers/internalapi/internal/payloads/payload_to_model.go
  pkg/handlers/internalapi/mto_shipment_test.go
  pkg/handlers/primeapi/api.go
  pkg/handlers/primeapi/mto_shipment_test.go
  pkg/handlers/primeapiv2/api.go
  pkg/handlers/primeapiv2/mto_shipment_test.go
  pkg/models/move.go
  pkg/models/ppm_shipment.go
  pkg/notifications/ppm_packet_email.go
  pkg/notifications/ppm_packet_email_test.go
  pkg/services/mto_shipment/mto_shipment_fetcher.go
  pkg/services/ppmshipment/ppm_shipment_creator.go
  pkg/services/ppmshipment/ppm_shipment_creator_test.go
  pkg/services/ppmshipment/ppm_shipment_fetcher.go
  pkg/services/ppmshipment/ppm_shipment_fetcher_test.go
  pkg/services/ppmshipment/ppm_shipment_updater.go
  pkg/services/ppmshipment/ppm_shipment_updater_test.go
  pkg/services/ppmshipment/validation.go
  pkg/services/ppmshipment/validation_test.go
  pkg/testdatagen/testharness/make_move.go
  playwright/tests/my/milmove/ppms/advances.spec.js
  playwright/tests/my/milmove/ppms/customerPpmTestFixture.js
  playwright/tests/my/milmove/ppms/dateAndLocation.spec.js
  playwright/tests/my/milmove/ppms/entireShipmentOnboarding.spec.js
  playwright/tests/my/milmove/ppms/estimatedIncentive.spec.js
  src/components/Customer/PPM/Booking/DateAndLocationForm/DateAndLocationForm.jsx
  src/components/Customer/PPM/Booking/DateAndLocationForm/DateAndLocationForm.stories.jsx
  src/components/Customer/PPM/Booking/DateAndLocationForm/DateAndLocationForm.test.jsx
  src/pages/MyMove/PPM/Booking/DateAndLocation/DateAndLocation.jsx
  src/pages/MyMove/PPM/Booking/DateAndLocation/DateAndLocation.test.jsx
  src/utils/validation.js
  swagger-def/definitions/PPMShipment.yaml
  swagger-def/internal.yaml
  swagger/ghc.yaml
  swagger/internal.yaml
Labels: Scrummy Bears, MAIN

#12198 B 18448 deprecate personally procured moves fields revised
  pkg/factory/mto_shipment_factory.go
  pkg/factory/ppm_shipment_factory.go
  pkg/handlers/internalapi/moves.go
  pkg/handlers/internalapi/uploads.go
  pkg/handlers/internalapi/users.go
  pkg/handlers/primeapi/payloads/model_to_payload_test.go
  pkg/handlers/primeapiv2/payloads/model_to_payload_test.go
  pkg/models/errors.go
  pkg/models/move.go
  pkg/models/order.go
  pkg/models/ppm_shipment.go
  pkg/models/service_member.go
  pkg/models/weight_ticket.go
  pkg/services/move/move_router.go
  pkg/services/move/move_router_test.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet_test.go
  pkg/testdatagen/make_personally_procured_move.go
  pkg/testdatagen/scenario/e2ebasic.go
  pkg/testdatagen/shared.go
Labels: G-Unit, MAIN

#12219 B 18735 auto check the move management box
  playwright/tests/office/txo/tooFlowsNTS.spec.js
  playwright/tests/office/txo/tooFlowsNTSR.spec.js
  playwright/tests/office/txo/tooTestFixture.js
  src/components/Office/RequestedShipments/RequestedShipments.test.jsx
  src/components/Office/RequestedShipments/SubmittedRequestedShipments.jsx
Labels: Scrummy Bears, MAIN

#12217 B-17960 Hotfix for Pro-Gear display
  src/components/Office/PPM/ReviewDocumentsSidePanel/ReviewDocumentsSidePanel.jsx
  src/types/shipment.js
Labels: ByteSize M&Ms, MAIN

#12096 MAIN - BP-18060 - Wire up AOA packet link customer/office
  src/components/Office/DefinitionLists/PPMShipmentInfoList.jsx
  src/components/Office/DefinitionLists/PPMShipmentInfoList.test.jsx
  src/components/Office/DefinitionLists/ShipmentInfoListSelector.jsx
  src/components/Office/ShipmentDisplay/ShipmentDisplay.jsx
  src/pages/MyMove/Home/MoveHome.jsx
  src/pages/MyMove/Home/MoveHome.test.jsx
  src/pages/MyMove/Home/index.jsx
  src/pages/MyMove/Home/index.test.jsx
  src/services/ghcApi.js
  src/services/internalApi.js
  src/services/swaggerRequest.test.js
  src/shared/AsyncPacketDownloadLink/AsyncPacketDownloadLink.jsx
  src/shared/AsyncPacketDownloadLink/AsyncPacketDownloadLink.module.scss
  src/shared/AsyncPacketDownloadLink/AsyncPacketDownloadLink.test.jsx
  src/shared/DownloadAOAErrorModal/DownloadAOAErrorModal.jsx
  src/shared/DownloadAOAErrorModal/DownloadAOAErrorModal.module.scss
Labels: Scrummy Bears, MAIN

#12194 B-18886-INT
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/customer.go
  pkg/gen/ghcmessages/update_customer_payload.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/internal/payloads/payload_to_model.go
  pkg/services/office_user/customer/customer_updater.go
  src/components/Office/CustomerContactInfoForm/CustomerContactInfoForm.jsx
  src/components/Office/CustomerContactInfoForm/CustomerContactInfoForm.test.jsx
  src/components/form/CustomerAltContactInfoFields/CustomerAltContactInfoFields.test.jsx
  src/components/form/CustomerAltContactInfoFields/index.jsx
  src/pages/Office/CustomerInfo/CustomerInfo.jsx
  src/pages/Office/CustomerInfo/CustomerInfo.test.jsx
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: G-Unit, INTEGRATION

#12212 INT-B-18637 p2
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/list_prime_move.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/services/move_task_order/move_task_order_fetcher.go
  src/components/MilMoveHeader/index.jsx
  src/containers/Headers/CustomerLoggedInHeader.jsx
  src/pages/MyMove/Home/Home.module.scss
  src/pages/MyMove/Home/MoveHome.jsx
  src/pages/MyMove/Home/index.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesMoveContainer/MultiMovesMoveContainer.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesMoveContainer/MultiMovesMoveContainer.module.scss
  src/pages/PrimeUI/AvailableMoves/AvailableMovesQueue.jsx
  src/pages/PrimeUI/AvailableMoves/AvailableMovesQueue.module.scss
  src/pages/PrimeUI/MoveTaskOrder/MoveDetails.jsx
  src/pages/PrimeUI/MoveTaskOrder/MoveDetails.module.scss
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: G-Unit, INTEGRATION

#12223 B 18393
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240229203552_add_to_ppm_advance_status_datatype.up.sql
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/p_p_m_advance_status.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/p_p_m_advance_status.go
  pkg/models/ppm_shipment.go
  pkg/services/ppmshipment/ppm_shipment_fetcher.go
  pkg/services/ppmshipment/ppm_shipment_updater.go
  src/constants/ppms.js
  swagger-def/definitions/PPMAdvanceStatus.yaml
  swagger/ghc.yaml
  swagger/internal.yaml
Labels: G-Unit, MAIN

#12117 MAIN B-18822 Admin API requested_office_users list
  pkg/factory/office_user_factory.go
  pkg/gen/adminapi/adminoperations/mymove_api.go
  pkg/gen/adminapi/adminoperations/requested_office_users/index_requested_office_users.go
  pkg/gen/adminapi/adminoperations/requested_office_users/index_requested_office_users_parameters.go
  pkg/gen/adminapi/adminoperations/requested_office_users/index_requested_office_users_responses.go
  pkg/gen/adminapi/adminoperations/requested_office_users/index_requested_office_users_urlbuilder.go
  pkg/gen/adminapi/configure_mymove.go
  pkg/gen/adminapi/embedded_spec.go
  pkg/gen/adminmessages/office_user.go
  pkg/handlers/adminapi/api.go
  pkg/handlers/adminapi/office_users.go
  pkg/handlers/adminapi/office_users_test.go
  pkg/handlers/adminapi/requested_office_users.go
  pkg/handlers/adminapi/requested_office_users_test.go
  pkg/models/office_user.go
  pkg/services/mocks/RequestedOfficeUserFetcher.go
  pkg/services/mocks/RequestedOfficeUserListFetcher.go
  pkg/services/requested_office_users.go
  pkg/services/requested_office_users/requested_office_user_list_fetcher_test.go
  pkg/services/requested_office_users/requested_office_user_service_test.go
  pkg/services/requested_office_users/requested_office_users_list_fetcher.go
  pkg/testdatagen/testharness/make_office_user.go
  swagger-def/admin.yaml
  swagger/admin.yaml
Labels: Mountain Movers, MAIN

#12215 INT B-18313 issue fixes and storybook updates
  src/pages/MyMove/Multi-Moves/MultiMovesLandingPage.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesLandingPage.test.jsx
Labels: Mountain Movers, INTEGRATION

#12171 B 18885 sit delivery miles calculation int
  .circleci/config.yml
  .envrc
  pkg/factory/mto_service_item_factory.go
  pkg/handlers/adminapi/api.go
  pkg/handlers/adminapi/moves_test.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/move_task_order_test.go
  pkg/handlers/ghcapi/mto_service_items_test.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/handlers/ghcapi/orders_test.go
  pkg/handlers/internalapi/api.go
  pkg/handlers/internalapi/mto_shipment_test.go
  pkg/handlers/primeapi/api.go
  pkg/handlers/primeapi/move_task_order_test.go
  pkg/handlers/primeapi/mto_service_item_test.go
  pkg/handlers/primeapi/mto_shipment_address_test.go
  pkg/handlers/primeapi/mto_shipment_test.go
  pkg/handlers/primeapi/sit_service_item_address_update_test.go
  pkg/handlers/primeapiv2/api.go
  pkg/handlers/primeapiv2/mto_service_item_test.go
  pkg/handlers/primeapiv2/mto_shipment_test.go
  pkg/handlers/supportapi/api.go
  pkg/handlers/supportapi/move_task_order_test.go
  pkg/handlers/supportapi/mto_service_item_test.go
  pkg/handlers/supportapi/mto_shipment_test.go
  pkg/models/mto_service_items.go
  pkg/services/move_history/move_history_fetcher_test.go
  pkg/services/move_task_order/move_task_order_updater_test.go
  pkg/services/mto_service_item/mto_service_item_creator.go
  pkg/services/mto_service_item/mto_service_item_creator_test.go
  pkg/services/mto_service_item/mto_service_item_updater.go
  pkg/services/mto_service_item/mto_service_item_updater_test.go
  pkg/services/mto_shipment/mto_shipment_address_updater.go
  pkg/services/mto_shipment/mto_shipment_address_updater_test.go
  pkg/services/mto_shipment/mto_shipment_updater.go
  pkg/services/mto_shipment/mto_shipment_updater_test.go
  pkg/services/mto_shipment/shipment_approver_test.go
  pkg/services/mto_shipment/shipment_deleter_test.go
  pkg/services/shipment_address_update/shipment_address_update_requester.go
  pkg/services/shipment_address_update/shipment_address_update_requester_test.go
  pkg/services/sit_address_update/sit_address_update_request_creator_test.go
  pkg/services/sit_extension/sit_extension_denier.go
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/testharness/make_move.go
Labels: Mountain Movers, INTEGRATION

#12159 B-18066-INTEGRATION
  cmd/generate-shipment-summary/main.go
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/ghcapi/ghcoperations/ppm/show_payment_packet.go
  pkg/gen/ghcapi/ghcoperations/ppm/show_payment_packet_parameters.go
  pkg/gen/ghcapi/ghcoperations/ppm/show_payment_packet_responses.go
  pkg/gen/ghcapi/ghcoperations/ppm/show_payment_packet_urlbuilder.go
  pkg/gen/internalapi/configure_mymove.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalapi/internaloperations/mymove_api.go
  pkg/gen/internalapi/internaloperations/ppm/show_payment_packet.go
  pkg/gen/internalapi/internaloperations/ppm/show_payment_packet_parameters.go
  pkg/gen/internalapi/internaloperations/ppm/show_payment_packet_responses.go
  pkg/gen/internalapi/internaloperations/ppm/show_payment_packet_urlbuilder.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/ppm_document.go
  pkg/handlers/ghcapi/ppm_document_test.go
  pkg/handlers/internalapi/api.go
  pkg/handlers/internalapi/ppm_shipment.go
  pkg/handlers/internalapi/ppm_shipment_test.go
  pkg/handlers/primeapi/api.go
  pkg/paperwork/generator.go
  pkg/services/mocks/PaymentPacketCreator.go
  pkg/services/paperwork/prime_download_user_upload_to_pdf_converter.go
  pkg/services/paperwork/prime_download_user_upload_to_pdf_converter_test.go
  pkg/services/ppmshipment.go
  pkg/services/ppmshipment/aoa_packet_creator_test.go
  pkg/services/ppmshipment/payment_packet_creator.go
  pkg/services/ppmshipment/payment_packet_creator_test.go
  pkg/services/ppmshipment/ppm_shipment_service_test.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet_test.go
  swagger-def/ghc.yaml
  swagger-def/internal.yaml
  swagger/ghc.yaml
  swagger/internal.yaml
Labels: Scrummy Bears, INTEGRATION

#12229 INT B-18629 Add Origin GBLOC To Move Screen (Backend)
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/order.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/orders_test.go
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: ByteSize M&Ms, INTEGRATION

#12196 Display PPM Origin and Destination address
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload_test.go
  src/components/Office/ShipmentAddresses/ShipmentAddresses.test.jsx
  src/components/Office/ShipmentDetails/ShipmentDetailsMain.jsx
  src/utils/shipmentDisplay.jsx
Labels: ByteSize M&Ms, INTEGRATION

#12203 B 18637 create bb order type
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/queues/get_moves_queue_parameters.go
  pkg/gen/ghcapi/ghcoperations/queues/get_moves_queue_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/queues/get_payment_requests_queue_parameters.go
  pkg/gen/ghcapi/ghcoperations/queues/get_payment_requests_queue_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/queues/get_services_counseling_queue_parameters.go
  pkg/gen/ghcapi/ghcoperations/queues/get_services_counseling_queue_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/queues/list_prime_moves_parameters.go
  pkg/gen/ghcapi/ghcoperations/queues/list_prime_moves_urlbuilder.go
  pkg/gen/ghcmessages/list_prime_move.go
  pkg/gen/ghcmessages/orders_type.go
  pkg/gen/ghcmessages/queue_move.go
  pkg/gen/ghcmessages/queue_payment_request.go
  pkg/gen/ghcmessages/search_move.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/orders_type.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/orders_type.go
  pkg/gen/primev2api/embedded_spec.go
  pkg/gen/primev2messages/orders_type.go
  pkg/gen/supportapi/embedded_spec.go
  pkg/gen/supportmessages/orders_type.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/queues.go
  pkg/services/move_task_order/move_task_order_fetcher.go
  pkg/services/order.go
  pkg/services/payment_request.go
  src/components/CustomerHeader/index.jsx
  src/components/CustomerHeader/index.module.scss
  src/components/MilMoveHeader/index.jsx
  src/components/MilMoveHeader/index.module.scss
  src/components/Table/SearchResultsTable.jsx
  src/components/Table/SearchResultsTable.module.scss
  src/constants/orders.js
  src/containers/Headers/CustomerLoggedInHeader.jsx
  src/containers/Headers/CustomerLoggedInHeader.test.jsx
  src/pages/MyMove/Home/Home.module.scss
  src/pages/MyMove/Home/MoveHome.jsx
  src/pages/MyMove/Home/index.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesMoveContainer/MultiMovesMoveContainer.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesMoveContainer/MultiMovesMoveContainer.module.scss
  src/pages/Office/MoveQueue/MoveQueue.jsx
  src/pages/Office/MoveQueue/MoveQueue.module.scss
  src/pages/Office/PaymentRequestQueue/PaymentRequestQueue.jsx
  src/pages/Office/PaymentRequestQueue/PaymentRequestQueue.module.scss
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.jsx
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.module.scss
  src/pages/PrimeUI/AvailableMoves/AvailableMovesQueue.jsx
  src/pages/PrimeUI/AvailableMoves/AvailableMovesQueue.module.scss
  src/pages/PrimeUI/MoveTaskOrder/MoveDetails.jsx
  src/pages/PrimeUI/MoveTaskOrder/MoveDetails.module.scss
  swagger-def/definitions/OrdersType.yaml
  swagger-def/ghc.yaml
  swagger-def/support.yaml
  swagger/ghc.yaml
  swagger/internal.yaml
  swagger/prime.yaml
  swagger/prime_v2.yaml
  swagger/support.yaml
Labels: G-Unit, MAIN

#12161 B-17908-INT KICKBACK (On pause, awaiting PO)
  src/constants/MoveHistory/Database/FieldMappings.js
  src/constants/MoveHistory/EventTemplates/SubmitMoveForApproval/SubmitMoveForApprovalMTOShipments.jsx
  src/constants/MoveHistory/EventTemplates/SubmitMoveForApproval/SubmitMoveForApprovalMTOShipments.test.jsx
  src/constants/MoveHistory/EventTemplates/SubmitMoveForApproval/SubmitMoveForApprovalPPMShipments.jsx
  src/constants/MoveHistory/EventTemplates/SubmitMoveForApproval/SubmitMoveForApprovalPPMShipments.test.jsx
  src/constants/MoveHistory/EventTemplates/index.js
  src/utils/formatPPMData.js
Labels: G-Unit, INTEGRATION

#12211 B 18188 removed personally procured moves model and devseed data
  cmd/milmove-tasks/main.go
  cmd/milmove-tasks/send_payment_reminder_email.go
  pkg/factory/move_factory.go
  pkg/factory/payment_request_interchange_control_number_factory.go
  pkg/factory/shared.go
  pkg/factory/shared_test.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/category_expense_summary.go
  pkg/gen/internalmessages/create_reimbursement.go
  pkg/gen/internalmessages/index_personally_procured_move_payload.go
  pkg/gen/internalmessages/move_dates_summary.go
  pkg/gen/internalmessages/move_payload.go
  pkg/gen/internalmessages/p_p_m_status.go
  pkg/gen/internalmessages/payment_methods_totals.go
  pkg/gen/internalmessages/personally_procured_move_payload.go
  pkg/gen/internalmessages/t_shirt_size.go
  pkg/handlers/internalapi/entitlements_test.go
  pkg/handlers/internalapi/move_queue_items_test.go
  pkg/handlers/internalapi/signed_certifications.go
  pkg/handlers/internalapi/signed_certifications_test.go
  pkg/models/move.go
  pkg/models/order.go
  pkg/models/order_test.go
  pkg/models/personally_procured_move.go
  pkg/models/personally_procured_move_test.go
  pkg/models/ppm_shipment.go
  pkg/models/queue.go
  pkg/models/queue_test.go
  pkg/models/service_member_test.go
  pkg/models/signed_certification_test.go
  pkg/notifications/move_payment_reminder_test.go
  pkg/services/move/move_router_test.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet.go
  pkg/testdatagen/make_personally_procured_move.go
  pkg/testdatagen/shared.go
  pkg/testdatagen/testharness/dispatch.go
  pkg/testdatagen/testharness/make_move.go
  swagger-def/internal.yaml
  swagger/internal.yaml
Labels: G-Unit, MAIN

#12222 B 18913 int
  config/flipt/storage/development.features.yaml
  pkg/notifications/prime_counseling_complete_test.go
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/scenario/subscenarios.go
  src/constants/routes.js
  src/pages/Office/CustomerOnboarding/CustomerName.jsx
  src/pages/Office/CustomerOnboarding/CustomerName.module.scss
  src/pages/Office/CustomerOnboarding/CustomerName.test.jsx
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.jsx
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.test.jsx
  src/pages/Office/index.jsx
  src/scenes/MyMove/index.jsx
  src/utils/featureFlags.js
Labels: Mountain Movers, INTEGRATION

#12200 B 18801 address factories and seed data main
  pkg/factory/address_factory.go
  pkg/factory/address_factory_test.go
  pkg/models/address.go
  pkg/models/us_post_region_city.go
  pkg/models/us_post_region_city_test.go
  scripts/db-truncate
Labels: Mountain Movers, MAIN

#12197 B:18520 Update Nav Links To Return To Move Page (Integration)(MERGE AFTER 18654)
  .circleci/config.yml
  config/env/loadtest.app.env
  config/env/stg.app.env
  playwright/tests/my/milmove/ppms/customerPpmTestFixture.js
  playwright/tests/my/milmove/ppms/entireShipmentCloseout.spec.js
  playwright/tests/my/milmove/ppms/navigateToUploadDocs.spec.js
  playwright/tests/my/mymove/hhg.spec.js
  playwright/tests/my/mymove/nts.spec.js
  playwright/tests/my/mymove/ntsr.spec.js
  playwright/tests/my/mymove/onboarding.spec.js
  playwright/tests/my/mymove/orders.spec.js
  playwright/tests/my/mymove/uploads.spec.js
  playwright/tests/utils/my/customerTest.js
  playwright/tests/utils/my/waitForCustomerPage.js
  src/appReducer.js
  src/components/Customer/Review/Summary/Summary.jsx
  src/components/MilMoveHeader/CustomerUserInfo.jsx
  src/containers/Headers/CustomerLoggedInHeader.jsx
  src/containers/requireCustomerState/requireCustomerState.jsx
  src/pages/MyMove/Agreement.jsx
  src/pages/MyMove/Home/MoveHome.jsx
  src/pages/MyMove/MovingInfo.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesMoveContainer/MultiMovesMoveContainer.jsx
  src/pages/MyMove/PPM/Booking/DateAndLocation/DateAndLocation.jsx
  src/pages/MyMove/PPM/Closeout/About/About.jsx
  src/pages/MyMove/PPM/Closeout/About/About.test.jsx
  src/pages/MyMove/PPM/Closeout/Expenses/Expenses.jsx
  src/pages/MyMove/PPM/Closeout/Expenses/Expenses.test.jsx
  src/pages/MyMove/PPM/Closeout/FinalCloseout/FinalCloseout.jsx
  src/pages/MyMove/PPM/Closeout/FinalCloseout/FinalCloseout.test.jsx
  src/pages/MyMove/PPM/Closeout/ProGear/ProGear.jsx
  src/pages/MyMove/PPM/Closeout/ProGear/ProGear.test.jsx
  src/pages/MyMove/PPM/Closeout/Review/Review.jsx
  src/pages/MyMove/PPM/Closeout/Review/Review.test.jsx
  src/pages/MyMove/PPM/Closeout/WeightTickets/WeightTickets.jsx
  src/pages/MyMove/PPM/Closeout/WeightTickets/WeightTickets.test.jsx
  src/pages/MyMove/Profile/EditContactInfo.jsx
  src/pages/MyMove/Profile/EditServiceInfo.test.jsx
  src/pages/MyMove/Profile/Profile.jsx
  src/pages/MyMove/Profile/Profile.test.jsx
  src/pages/MyMove/Review/Review.jsx
  src/pages/MyMove/Review/Review.test.jsx
  src/pages/MyMove/UploadOrders.jsx
  src/store/general/action.test.js
  src/store/general/actions.js
  src/store/general/reducer.js
  src/store/general/reducer.test.js
  src/store/general/selectors.js
  src/store/general/selectors.test.js
Labels: Mountain Movers, INTEGRATION

#12235 MAIN B-18629 Add Origin GBLOC To Move Screen (Backend)
  .circleci/config.yml
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/order.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/orders_test.go
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: ByteSize M&Ms, MAIN

#12148 B 19035 update payment reminder email template
  cmd/milmove-tasks/main.go
  cmd/milmove-tasks/send_payment_reminder_email.go
  pkg/assets/notifications/templates/move_payment_reminder_template.html
  pkg/assets/notifications/templates/move_payment_reminder_template.txt
  pkg/factory/ppm_shipment_factory.go
  pkg/notifications/move_payment_reminder.go
  pkg/notifications/move_payment_reminder_test.go
Labels: ByteSize M&Ms, MAIN

#12178 B 18821 int
  .circleci/config.yml
  .envrc
  docker-compose.ecs.yml
  docker-compose.mtls.yml
  docker-compose.prime.yml
  docker-compose.yml
Labels: Mountain Movers, INTEGRATION

#12226 B-18391
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/orders.go
  pkg/handlers/internalapi/orders.go
  pkg/models/order.go
  src/pages/MyMove/Home/MoveHome.jsx
  src/pages/MyMove/Home/index.jsx
  swagger-def/internal.yaml
  swagger/internal.yaml
Labels: G-Unit, MAIN

#12230 INT B-18825 Admin API Approve/Reject/Update requested office user
  .circleci/config.yml
  pkg/gen/adminapi/adminoperations/mymove_api.go
  pkg/gen/adminapi/adminoperations/requested_office_users/update_requested_office_user.go
  pkg/gen/adminapi/adminoperations/requested_office_users/update_requested_office_user_parameters.go
  pkg/gen/adminapi/adminoperations/requested_office_users/update_requested_office_user_responses.go
  pkg/gen/adminapi/adminoperations/requested_office_users/update_requested_office_user_urlbuilder.go
  pkg/gen/adminapi/configure_mymove.go
  pkg/gen/adminapi/embedded_spec.go
  pkg/gen/adminmessages/requested_office_user_update.go
  pkg/handlers/adminapi/api.go
  pkg/handlers/adminapi/requested_office_users.go
  pkg/handlers/adminapi/requested_office_users_test.go
  pkg/services/mocks/RequestedOfficeUserUpdater.go
  pkg/services/mocks/RoleAssociater.go
  pkg/services/requested_office_users.go
  pkg/services/requested_office_users/requested_office_user_fetcher.go
  pkg/services/requested_office_users/requested_office_user_fetcher_test.go
  pkg/services/requested_office_users/requested_office_user_updater.go
  pkg/services/requested_office_users/requested_office_user_updater_test.go
  pkg/services/roles.go
  pkg/services/roles/roles.go
  pkg/services/roles/roles_service_test.go
  pkg/services/roles/roles_test.go
  swagger-def/admin.yaml
  swagger/admin.yaml
Labels: Mountain Movers, INTEGRATION

#12238 B 18902 SH to LH and LH to SH INT
  .circleci/config.yml
  pkg/services/shipment_address_update/shipment_address_update_requester.go
  pkg/services/shipment_address_update/shipment_address_update_requester_test.go
Labels: Mountain Movers, INTEGRATION

#12247 B 18909 no approve button for rejected DSH or DLH service item
  src/components/Office/ServiceItemsTable/ServiceItemsTable.jsx
  src/components/Office/ServiceItemsTable/ServiceItemsTable.test.jsx
Labels: Mountain Movers, INTEGRATION

#12245 B-17908 KICKBACK
  src/constants/MoveHistory/Database/FieldMappings.js
  src/constants/MoveHistory/EventTemplates/SubmitMoveForApproval/SubmitMoveForApprovalMTOShipments.jsx
  src/constants/MoveHistory/EventTemplates/SubmitMoveForApproval/SubmitMoveForApprovalMTOShipments.test.jsx
  src/constants/MoveHistory/EventTemplates/SubmitMoveForApproval/SubmitMoveForApprovalPPMShipments.jsx
  src/constants/MoveHistory/EventTemplates/SubmitMoveForApproval/SubmitMoveForApprovalPPMShipments.test.jsx
  src/constants/MoveHistory/EventTemplates/index.js
  src/utils/formatPPMData.js
Labels: G-Unit, MAIN

#12241 B-18668 Adding elevated rights supervisor choice
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240226130347_create_privileges_table.up.sql
  pkg/factory/office_user_factory.go
  pkg/factory/ppm_shipment_factory.go
  pkg/factory/privilege_factory.go
  pkg/factory/shared.go
  pkg/factory/user_factory.go
  pkg/gen/adminapi/embedded_spec.go
  pkg/gen/adminmessages/office_user.go
  pkg/gen/adminmessages/office_user_create.go
  pkg/gen/adminmessages/office_user_privilege.go
  pkg/gen/adminmessages/office_user_update.go
  pkg/gen/adminmessages/privilege.go
  pkg/handlers/adminapi/api.go
  pkg/handlers/adminapi/office_users.go
  pkg/handlers/adminapi/office_users_test.go
  pkg/models/privileges.go
  pkg/models/privileges_test.go
  pkg/models/user.go
  pkg/models/user_test.go
  pkg/models/users_privileges.go
  pkg/services/mocks/UserPrivilegeAssociator.go
  pkg/services/move/move_router_test.go
  pkg/services/users_privileges.go
  pkg/services/users_privileges/users_privileges.go
  pkg/services/users_privileges/users_privileges_service_test.go
  pkg/services/users_privileges/users_privileges_test.go
  playwright/tests/admin/officeUsers.spec.js
  src/components/Admin/ImportOfficeUserButton/index.jsx
  src/components/Admin/ImportOfficeUserButton/validation.js
  src/constants/userPrivileges.js
  src/pages/Admin/OfficeUsers/OfficeUserCreate.jsx
  src/pages/Admin/OfficeUsers/OfficeUserEdit.jsx
  src/pages/Admin/OfficeUsers/OfficeUserList.jsx
  src/pages/Admin/OfficeUsers/OfficeUserShow.jsx
  src/scenes/SystemAdmin/shared/RolesCheckboxes.jsx
  src/scenes/SystemAdmin/shared/RolesPrivilegesCheckboxes.jsx
  src/scenes/SystemAdmin/shared/rest_provider.js
  swagger-def/admin.yaml
  swagger/admin.yaml
Labels: G-Unit, INTEGRATION

#12225 INT-B-18638
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/queues/list_prime_moves_parameters.go
  pkg/gen/ghcmessages/orders_type.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/orders_type.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/orders_type.go
  pkg/gen/primev2api/embedded_spec.go
  pkg/gen/primev2messages/orders_type.go
  pkg/gen/supportapi/embedded_spec.go
  pkg/gen/supportmessages/orders_type.go
  src/components/CustomerHeader/index.jsx
  src/components/Table/SearchResultsTable.jsx
  src/constants/orders.js
  src/pages/MyMove/Home/MoveHome.jsx
  src/pages/MyMove/Home/index.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesMoveContainer/MultiMovesMoveContainer.jsx
  src/pages/Office/MoveQueue/MoveQueue.jsx
  src/pages/Office/PaymentRequestQueue/PaymentRequestQueue.jsx
  src/pages/Office/PaymentRequestQueue/PaymentRequestQueue.module.scss
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.jsx
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.module.scss
  src/pages/PrimeUI/AvailableMoves/AvailableMovesQueue.jsx
  src/pages/PrimeUI/MoveTaskOrder/MoveDetails.jsx
  swagger-def/definitions/OrdersType.yaml
  swagger-def/ghc.yaml
  swagger-def/support.yaml
  swagger/ghc.yaml
  swagger/internal.yaml
  swagger/prime.yaml
  swagger/prime_v2.yaml
  swagger/support.yaml
Labels: G-Unit, INTEGRATION

#12246 B-18886
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/customer.go
  pkg/gen/ghcmessages/update_customer_payload.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/internal/payloads/payload_to_model.go
  pkg/services/office_user/customer/customer_updater.go
  src/components/Office/CustomerContactInfoForm/CustomerContactInfoForm.jsx
  src/components/Office/CustomerContactInfoForm/CustomerContactInfoForm.test.jsx
  src/components/form/CustomerAltContactInfoFields/CustomerAltContactInfoFields.test.jsx
  src/components/form/CustomerAltContactInfoFields/index.jsx
  src/pages/Office/CustomerInfo/CustomerInfo.jsx
  src/pages/Office/CustomerInfo/CustomerInfo.test.jsx
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: G-Unit, MAIN

#12237 B-18329 Remove N/A customer's address
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload_test.go
  src/components/Office/ShipmentAddresses/ShipmentAddresses.test.jsx
  src/components/Office/ShipmentDetails/ShipmentDetailsMain.jsx
  src/utils/shipmentDisplay.jsx
Labels: ByteSize M&Ms, MAIN

#12252 INT B-18821 fix
  .envrc
  pkg/cli/auth.go
Labels: Mountain Movers, INTEGRATION

#12233 B 17906 Prevent Customer Request after Authorized End Date
  pkg/handlers/primeapi/mto_service_item.go
  pkg/services/mto_service_item/mto_service_item_updater.go
  pkg/services/mto_service_item/mto_service_item_updater_test.go
  pkg/services/sit_extension/approved_sit_duration_update_creator.go
  src/components/Office/ShipmentSITDisplay/ShipmentSITDisplay.jsx
  src/components/Office/ShipmentSITDisplay/ShipmentSITDisplay.test.jsx
  src/components/Office/ShipmentSITDisplay/ShipmentSITDisplayTestParams.js
  src/components/Office/SubmitSITExtensionModal/SubmitSITExtensionModal.jsx
Labels: Scrummy Bears, MAIN

#12255 INT B-18679-Integration (Peer Review Fixes)
  pkg/factory/mto_shipment_factory.go
  pkg/services/move/move_searcher_test.go
  src/components/Table/SearchResultsTable.jsx
  src/components/Table/SearchResultsTable.module.scss
Labels: Scrummy Bears, INTEGRATION

#12220 MAIN - B-18679 - New QAE/CSR table columns
  pkg/factory/mto_shipment_factory.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/move/search_moves.go
  pkg/gen/ghcmessages/search_move.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/move.go
  pkg/handlers/ghcapi/move_test.go
  pkg/services/move.go
  pkg/services/move/move_searcher.go
  pkg/services/move/move_searcher_test.go
  src/components/Table/SearchResultsTable.jsx
  src/components/Table/SearchResultsTable.module.scss
  src/components/Table/SearchResultsTable.test.jsx
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: Scrummy Bears, MAIN

#12234 INT B-18826 Admin UI list requested office users
  pkg/handlers/adminapi/requested_office_users.go
  playwright/tests/admin/officeUsers.spec.js
  src/pages/Admin/RequestedOfficeUsers/RequestedOfficeUserList.jsx
  src/scenes/SystemAdmin/Home.jsx
Labels: Mountain Movers, INTEGRATION

#12256 INT closeout office space force bugfix - B-18497 B-18630
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/orders.go
  src/components/Customer/PPM/Booking/DateAndLocationForm/DateAndLocationForm.jsx
  src/components/Office/ShipmentForm/ShipmentForm.jsx
  src/pages/MyMove/Home/MoveHome.jsx
  src/pages/MyMove/PPM/Booking/DateAndLocation/DateAndLocation.jsx
  swagger-def/ghc.yaml
  swagger-def/internal.yaml
  swagger/ghc.yaml
  swagger/internal.yaml
Labels: ByteSize M&Ms, INTEGRATION

#12266 B 18885 i 12639 load test fix
  pkg/services/mto_service_item/mto_service_item_updater.go
Labels: Mountain Movers, INTEGRATION

#12190 B 19086 int
  go.mod
  go.sum
  pkg/assets/paperwork/formtemplates/SSWPDFTemplate.pdf
  pkg/services/shipment_summary_worksheet.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet_test.go
Labels: Scrummy Bears, INTEGRATION

#12268 B 18668 int
  pkg/handlers/adminapi/office_users.go
Labels: G-Unit, INTEGRATION

#12250 B 18065 int
  playwright/tests/my/milmove/ppms/customerPpmTestFixture.js
  src/components/Office/DefinitionLists/PPMShipmentInfoList.jsx
  src/components/Office/DefinitionLists/PPMShipmentInfoList.test.jsx
  src/components/Office/ShipmentDisplay/ShipmentDisplay.jsx
  src/components/PPMSummaryList/PPMSummaryList.jsx
  src/components/PPMSummaryList/PPMSummaryList.test.jsx
  src/pages/MyMove/Home/MoveHome.jsx
  src/pages/MyMove/Home/MoveHome.test.jsx
  src/pages/MyMove/Home/index.jsx
  src/pages/MyMove/Home/index.test.jsx
  src/services/ghcApi.js
  src/services/internalApi.js
  src/shared/AsyncPacketDownloadLink/AsyncPacketDownloadLink.jsx
  src/shared/DownloadPacketErrorModal/DownloadPacketErrorModal.jsx
  src/shared/DownloadPacketErrorModal/DownloadPacketErrorModal.module.scss
Labels: Scrummy Bears, INTEGRATION

#12254 INT-B-18637
  src/components/MilMoveHeader/index.jsx
  src/containers/Headers/CustomerLoggedInHeader.jsx
  src/pages/MyMove/Home/MoveHome.jsx
Labels: G-Unit, INTEGRATION

#12248 INT B-18915 create customer form for office users
  src/constants/routes.js
  src/pages/Office/CustomerOnboarding/CreateCustomerForm.jsx
  src/pages/Office/CustomerOnboarding/CreateCustomerForm.module.scss
  src/pages/Office/CustomerOnboarding/CreateCustomerForm.test.jsx
  src/pages/Office/CustomerOnboarding/CreateCustomerform.stories.jsx
  src/pages/Office/CustomerOnboarding/CustomerName.jsx
  src/pages/Office/CustomerOnboarding/CustomerName.test.jsx
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.jsx
  src/pages/Office/index.jsx
Labels: Mountain Movers, INTEGRATION

#12275 INT B-18913 fix
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.jsx
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.module.scss
Labels: Mountain Movers, INTEGRATION

#12264 INT B-18631 All shipment weight values displayed sc closeout
  pkg/testdatagen/testharness/dispatch.go
  pkg/testdatagen/testharness/make_move.go
  playwright/tests/office/servicescounseling/servicesCounselingWeightTickets.spec.js
  playwright/tests/utils/testharness.js
  src/components/Office/PPM/HHGWeightSummary/HHGWeightSummary.jsx
  src/components/Office/PPM/HHGWeightSummary/HHGWeightSummary.module.scss
  src/components/Office/PPM/HHGWeightSummary/HHGWeightSummary.test.jsx
  src/components/Office/PPM/ReviewWeightTicket/ReviewWeightTicket.jsx
Labels: ByteSize M&Ms, INTEGRATION

#12269 B 18404 sit service item info population int (DO NOT MERGE BEFORE B-18885)
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/m_t_o_service_item.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/mto_service_items.go
  playwright/tests/office/txo/sitUpdates.spec.js
  src/components/Office/RequestedServiceItemsTable/RequestedServiceItemsTable.jsx
  src/components/Office/RequestedServiceItemsTable/RequestedServiceItemsTable.test.jsx
  src/components/Office/ServiceItemDetails/ServiceItemDetails.jsx
  src/components/Office/ServiceItemDetails/ServiceItemDetails.test.jsx
  src/components/Office/ServiceItemsTable/ServiceItemsTable.jsx
  src/components/Office/ServiceItemsTable/ServiceItemsTable.test.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
  swagger-def/definitions/MTOServiceItem.yaml
  swagger/ghc.yaml
Labels: Mountain Movers, INTEGRATION

#12274 B 18637 create bb order type
  src/components/MilMoveHeader/index.jsx
  src/containers/Headers/CustomerLoggedInHeader.jsx
  src/pages/MyMove/Home/MoveHome.jsx
Labels: G-Unit, MAIN

#12240 INT B 18889 remove prime ability to update destination address for approved shipment outside correct endpoint
  pkg/handlers/primeapi/mto_shipment.go
  pkg/handlers/primeapi/mto_shipment_address.go
  pkg/handlers/primeapi/mto_shipment_address_test.go
  pkg/handlers/primeapi/mto_shipment_test.go
  pkg/testdatagen/scenario/e2ebasic.go
  pkg/testdatagen/testharness/make_move.go
  playwright/tests/office/primesimulator/primeSimulatorFlows.spec.js
Labels: Mountain Movers, INTEGRATION

#12279 B 17854 int Removal of automatic calculation of SIT Authorized End Date
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240319214733_remove_sit_authorized_end_date.up.sql
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/s_i_t_status.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/primeapi/mto_service_item.go
  pkg/models/mto_service_items.go
  pkg/services/mto_service_item/mto_service_item_updater.go
  pkg/services/mto_service_item/mto_service_item_updater_test.go
  pkg/services/mto_shipment.go
  pkg/services/sit_extension/approved_sit_duration_update_creator.go
  pkg/services/sit_status/shipment_sit_status.go
  src/components/Office/ShipmentSITDisplay/ShipmentSITDisplay.jsx
  src/components/Office/ShipmentSITDisplay/ShipmentSITDisplay.test.jsx
  src/components/Office/ShipmentSITDisplay/ShipmentSITDisplayTestParams.js
  src/components/Office/SubmitSITExtensionModal/SubmitSITExtensionModal.jsx
  swagger-def/definitions/SITStatus.yaml
  swagger/ghc.yaml
Labels: Scrummy Bears, INTEGRATION

#12273 INT B-18916 create customer and okta profile as office user (MERGE AFTER B-18915)
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/customer/create_customer_with_okta_option.go
  pkg/gen/ghcapi/ghcoperations/customer/create_customer_with_okta_option_parameters.go
  pkg/gen/ghcapi/ghcoperations/customer/create_customer_with_okta_option_responses.go
  pkg/gen/ghcapi/ghcoperations/customer/create_customer_with_okta_option_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/ghcmessages/backup_contact.go
  pkg/gen/ghcmessages/create_customer_payload.go
  pkg/gen/ghcmessages/created_customer.go
  pkg/handlers/authentication/okta/provider.go
  pkg/handlers/authentication/okta/provider_test.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/customer.go
  pkg/handlers/ghcapi/customer_test.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload_test.go
  pkg/models/okta_user_create.go
  pkg/models/okta_user_info.go
  src/pages/Office/CustomerOnboarding/CreateCustomerForm.jsx
  src/pages/Office/CustomerOnboarding/CreateCustomerForm.test.jsx
  src/services/ghcApi.js
  src/shared/Entities/schema.js
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: Mountain Movers, INTEGRATION

#12285 INT B-18913 fix numero dos
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.module.scss
Labels: Mountain Movers, INTEGRATION

#12291 B 17854 Removal of automatic calculation of SIT Authorized End Date
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240319214733_remove_sit_authorized_end_date.up.sql
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/s_i_t_status.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/primeapi/mto_service_item.go
  pkg/models/mto_service_items.go
  pkg/services/mto_service_item/mto_service_item_updater.go
  pkg/services/mto_service_item/mto_service_item_updater_test.go
  pkg/services/mto_shipment.go
  pkg/services/sit_extension/approved_sit_duration_update_creator.go
  pkg/services/sit_status/shipment_sit_status.go
  src/components/Office/ShipmentSITDisplay/ShipmentSITDisplay.jsx
  src/components/Office/ShipmentSITDisplay/ShipmentSITDisplay.test.jsx
  src/components/Office/ShipmentSITDisplay/ShipmentSITDisplayTestParams.js
  src/components/Office/SubmitSITExtensionModal/SubmitSITExtensionModal.jsx
  swagger-def/definitions/SITStatus.yaml
  swagger/ghc.yaml
Labels: Scrummy Bears, MAIN

#12262 B 18644 actual move date not future backend integration
  pkg/apperror/errors.go
  pkg/handlers/internalapi/mto_shipment.go
  pkg/services/ppmshipment/ppm_shipment_updater.go
  pkg/services/ppmshipment/ppm_shipment_updater_test.go
  pkg/services/ppmshipment/validation.go
  pkg/services/ppmshipment/validation_test.go
Labels: ByteSize M&Ms, INTEGRATION

#12257 INT-B-17922 - Deprecate INTERNAL PPM APIs
  pkg/gen/internalapi/configure_mymove.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalapi/internaloperations/mymove_api.go
  pkg/gen/internalapi/internaloperations/ppm/show_p_p_m_estimate.go
  pkg/gen/internalapi/internaloperations/ppm/show_p_p_m_estimate_parameters.go
  pkg/gen/internalapi/internaloperations/ppm/show_p_p_m_estimate_responses.go
  pkg/gen/internalapi/internaloperations/ppm/show_p_p_m_estimate_urlbuilder.go
  pkg/gen/internalapi/internaloperations/ppm/show_p_p_m_sit_estimate.go
  pkg/gen/internalapi/internaloperations/ppm/show_p_p_m_sit_estimate_parameters.go
  pkg/gen/internalapi/internaloperations/ppm/show_p_p_m_sit_estimate_responses.go
  pkg/gen/internalapi/internaloperations/ppm/show_p_p_m_sit_estimate_urlbuilder.go
  pkg/gen/internalmessages/p_p_m_sit_estimate.go
  pkg/handlers/authentication/auth.go
  pkg/services/event/internal_endpoint.go
  src/services/internalApi.js
  swagger-def/internal.yaml
  swagger/internal.yaml
Labels: Scrummy Bears, INTEGRATION

#12284 B 19157 int
  src/components/Statements/PrivacyAndPolicyStatement.jsx
Labels: Scrummy Bears, INTEGRATION

#12283 B 18670 int
  src/components/Office/ShipmentDetails/ShipmentDetailsMain.jsx
  src/components/Office/ShipmentWeightDetails/ShipmentWeightDetails.jsx
  src/components/Office/ShipmentWeightDetails/ShipmentWeightDetails.test.jsx
Labels: Scrummy Bears, INTEGRATION

#12253 INT B-18859 Prime Simulator Display HHG Pro Gear
  src/components/PrimeUI/Shipment/Shipment.jsx
  src/components/PrimeUI/Shipment/Shipment.test.jsx
  src/containers/Headers/CustomerLoggedInHeader.jsx
  src/pages/MyMove/Home/MoveHome.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdate.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdate.test.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdateForm.jsx
  src/services/primeApi.js
Labels: Scrummy Bears, INTEGRATION

#12300 INT B-17960 UI fixes
  pkg/apperror/errors.go
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/ghcapi/ghcoperations/ppm/get_p_p_m_actual_weight.go
  pkg/gen/ghcapi/ghcoperations/ppm/get_p_p_m_actual_weight_parameters.go
  pkg/gen/ghcapi/ghcoperations/ppm/get_p_p_m_actual_weight_responses.go
  pkg/gen/ghcapi/ghcoperations/ppm/get_p_p_m_actual_weight_urlbuilder.go
  pkg/gen/ghcmessages/p_p_m_actual_weight.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/ppm_closeout.go
  pkg/models/ppm_shipment.go
  pkg/services/mocks/PPMCloseoutFetcher.go
  pkg/services/ppm_closeout.go
  pkg/services/ppm_closeout/ppm_closeout.go
  src/components/Office/PPM/PPMHeaderSummary/HeaderSection.jsx
  src/components/Office/PPM/ReviewWeightTicket/ReviewWeightTicket.jsx
  src/components/Office/PPM/ReviewWeightTicket/ReviewWeightTicket.test.jsx
  src/constants/queryKeys.js
  src/hooks/queries.js
  src/pages/Office/PPM/ReviewDocuments/ReviewDocuments.jsx
  src/services/ghcApi.js
  src/utils/shipmentWeights.js
  swagger-def/definitions/PPMActualWeight.yaml
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: ByteSize M&Ms, INTEGRATION

#12306 MAIN B-17960 UI fixes
  .circleci/config.yml
  pkg/apperror/errors.go
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/ghcapi/ghcoperations/ppm/get_p_p_m_actual_weight.go
  pkg/gen/ghcapi/ghcoperations/ppm/get_p_p_m_actual_weight_parameters.go
  pkg/gen/ghcapi/ghcoperations/ppm/get_p_p_m_actual_weight_responses.go
  pkg/gen/ghcapi/ghcoperations/ppm/get_p_p_m_actual_weight_urlbuilder.go
  pkg/gen/ghcmessages/p_p_m_actual_weight.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/ppm_closeout.go
  pkg/models/ppm_shipment.go
  pkg/services/mocks/PPMCloseoutFetcher.go
  pkg/services/ppm_closeout.go
  pkg/services/ppm_closeout/ppm_closeout.go
  src/components/Office/PPM/PPMHeaderSummary/HeaderSection.jsx
  src/components/Office/PPM/ReviewWeightTicket/ReviewWeightTicket.jsx
  src/components/Office/PPM/ReviewWeightTicket/ReviewWeightTicket.test.jsx
  src/constants/queryKeys.js
  src/hooks/queries.js
  src/pages/Office/PPM/ReviewDocuments/ReviewDocuments.jsx
  src/services/ghcApi.js
  src/utils/shipmentWeights.js
  swagger-def/definitions/PPMActualWeight.yaml
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: ByteSize M&Ms, MAIN

#12309 I-12678 check payment requests table rather than payment service items table
  pkg/services/shipment_address_update/shipment_address_update_requester.go
Labels: Mountain Movers, INTEGRATION

#12301 INTEGRATION-B -19167 - Feature flags to hide/show specific shipment type - Customer UI
  .circleci/config.yml
  .envrc
  config/env/demo.app-client-tls.env
  config/env/demo.app.env
  config/env/exp.app-client-tls.env
  config/env/exp.app.env
  config/env/loadtest.app-client-tls.env
  config/env/loadtest.app.env
  config/env/prd.app-client-tls.env
  config/env/prd.app.env
  config/env/stg.app-client-tls.env
  config/env/stg.app.env
  config/flipt/storage/development.features.yaml
  src/components/Customer/Review/AddShipmentModal/AddShipmentModal.jsx
  src/components/Customer/Review/Summary/Summary.jsx
  src/components/Customer/Review/Summary/Summary.test.jsx
  src/components/Customer/modals/MoveInfoModal/MoveInfoModal.jsx
  src/components/Customer/modals/StorageInfoModal/StorageInfoModal.jsx
  src/pages/MyMove/MovingInfo.jsx
  src/pages/MyMove/MovingInfo.test.jsx
  src/pages/MyMove/SelectShipmentType.jsx
  src/pages/MyMove/SelectShipmentType.test.jsx
  src/shared/constants.js
Labels: Scrummy Bears, INTEGRATION

#12315 Added nil check for AdvanceAmountReceived MAIN-B-17960
  pkg/services/ppm_closeout/ppm_closeout.go
Labels: ByteSize M&Ms, MAIN

#12294 INT B-18829 Admin UI show requested office user overview page
  .circleci/config.yml
  pkg/handlers/adminapi/api.go
  pkg/handlers/adminapi/requested_office_users.go
  pkg/handlers/adminapi/requested_office_users_test.go
  src/pages/Admin/RequestedOfficeUsers/RequestedOfficeUserShow.jsx
  src/scenes/SystemAdmin/Home.jsx
Labels: Mountain Movers, INTEGRATION

#12317 INT-B-17960 UI fixes - AOA nil. check
  pkg/services/ppm_closeout/ppm_closeout.go
Labels: ByteSize M&Ms, INTEGRATION

#12302 INT B-18831 admin UI add approve reject buttons and rejection input on overview page of requested office user (MERGE AFTER B-18829)
  pkg/gen/adminapi/doc.go
  pkg/gen/adminapi/embedded_spec.go
  src/constants/routes.js
  src/pages/Admin/RequestedOfficeUsers/RequestedOfficeUserShow.jsx
  src/pages/Admin/RequestedOfficeUsers/RequestedOfficeUserShow.module.scss
  src/services/adminApi.js
  src/shared/Entities/schema.js
  swagger-def/admin.yaml
  swagger/admin.yaml
Labels: Mountain Movers, INTEGRATION

#12276 B 18633 actual move date not future frontend integration
  playwright/tests/my/milmove/ppms/customerPpmTestFixture.js
  playwright/tests/my/milmove/ppms/entireShipmentCloseout.spec.js
  playwright/tests/my/milmove/ppms/entireShipmentOnboarding.spec.js
  playwright/tests/my/milmove/ppms/estimatedIncentive.spec.js
  playwright/tests/my/milmove/ppms/estimatedWeightsProgear.spec.js
  playwright/tests/my/milmove/ppms/expenses.spec.js
  src/components/Customer/PPM/Closeout/AboutForm/AboutForm.jsx
  src/components/form/fields/DatePickerInput.jsx
Labels: ByteSize M&Ms, INTEGRATION

#12321 B 18902 i 12681 updating destination address
  pkg/services/mto_shipment/mto_shipment_updater.go
  pkg/services/shipment_address_update/shipment_address_update_requester.go
Labels: Mountain Movers, INTEGRATION

#12324 INT B-17960 - Add receipt total
  src/components/Office/PPM/ReviewDocumentsSidePanel/ReviewDocumentsSidePanel.jsx
  src/components/Office/PPM/ReviewDocumentsSidePanel/ReviewDocumentsSidePanel.module.scss
  src/components/Office/PPM/ReviewDocumentsSidePanel/ReviewDocumentsSidePanel.test.jsx
Labels: ByteSize M&Ms, INTEGRATION

#12322 B 18668 int fix import issue
  pkg/gen/adminapi/embedded_spec.go
  src/components/Admin/ImportOfficeUserButton/index.jsx
  src/components/Admin/ImportOfficeUserButton/validation.js
  src/scenes/SystemAdmin/shared/RolesPrivilegesCheckboxes.jsx
  swagger-def/admin.yaml
  swagger/admin.yaml
Labels: G-Unit, INTEGRATION

#12199 B 18823 ghc create requested office user int
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/ghcapi/ghcoperations/office_users/create_requested_office_user.go
  pkg/gen/ghcapi/ghcoperations/office_users/create_requested_office_user_parameters.go
  pkg/gen/ghcapi/ghcoperations/office_users/create_requested_office_user_responses.go
  pkg/gen/ghcapi/ghcoperations/office_users/create_requested_office_user_urlbuilder.go
  pkg/gen/ghcmessages/office_user.go
  pkg/gen/ghcmessages/office_user_create.go
  pkg/gen/ghcmessages/office_user_role.go
  pkg/gen/ghcmessages/role.go
  pkg/handlers/adminapi/api.go
  pkg/handlers/adminapi/office_users.go
  pkg/handlers/adminapi/office_users_test.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/office_users.go
  pkg/handlers/ghcapi/office_users_test.go
  pkg/handlers/routing/routing_init.go
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: Mountain Movers, INTEGRATION

#12316 B 19120 int
  src/components/Office/WeightSummary/WeightSummary.jsx
  src/components/Office/WeightSummary/WeightSummary.module.scss
  src/components/Office/WeightSummary/WeightSummary.test.jsx
  src/pages/Office/ReviewBillableWeight/ReviewBillableWeight.jsx
Labels: G-Unit, INTEGRATION

#12325 B-18855 Delivery out of SIT FSC Calculation Issue
  pkg/payment_request/service_param_value_lookups/weight_billed_lookup.go
  playwright/tests/office/txo/tooFlows.spec.js
Labels: ByteSize M&Ms, INTEGRATION

#12277 INT-B-18638
  src/components/MilMoveHeader/index.jsx
  src/containers/Headers/CustomerLoggedInHeader.jsx
Labels: G-Unit, INTEGRATION

#12328 B 19139 tac and loa invoice fix
  pkg/factory/line_of_accounting_factory.go
  pkg/factory/transportation_accounting_code_factory.go
  pkg/services/invoice/ghc_payment_request_invoice_generator.go
  pkg/services/invoice/ghc_payment_request_invoice_generator_test.go
Labels: Mountain Movers, MAIN

#12334 Fix silly wordage of gh action
  .github/workflows/main-to-integration-sync.yml
Labels: Mountain Movers, MAIN

#12332 INT | B-18497 B-18630 | closeout office shipment card
  src/components/Customer/PPM/Closeout/FinalCloseoutForm/FinalCloseoutForm.jsx
  src/components/Customer/Review/ShipmentCard/PPMShipmentCard/PPMShipmentCard.jsx
  src/utils/shipmentDisplay.jsx
Labels: ByteSize M&Ms, INTEGRATION

#12337 Remove int testing dummy sync
  .github/workflows/main-to-integration-sync.yml
Labels: Mountain Movers, MAIN

#12308 INT-B-19095
  src/components/Table/SearchResultsTable.jsx
  src/components/Table/SearchResultsTable.module.scss
  src/components/Table/SearchResultsTable.test.jsx
  src/components/Table/Table.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.module.scss
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.jsx
Labels: G-Unit, INTEGRATION

#12335 INT B-18642 add origin gbloc to move screen front end
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/move.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/services/move/move_fetcher.go
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/testharness/dispatch.go
  pkg/testdatagen/testharness/make_move.go
  playwright/tests/office/servicescounseling/servicesCounselingFlows.spec.js
  playwright/tests/office/txo/tioFlows.spec.js
  playwright/tests/office/txo/tooFlows.spec.js
  playwright/tests/utils/testharness.js
  src/components/CustomerHeader/CustomerHeader.test.jsx
  src/components/CustomerHeader/index.jsx
  src/hooks/queries.js
  src/hooks/queries.test.jsx
  src/pages/Office/EditShipmentDetails/EditShipmentDetails.jsx
  src/pages/Office/ServicesCounselingMoveInfo/ServicesCounselingMoveInfo.jsx
  src/pages/Office/TXOMoveInfo/TXOMoveInfo.jsx
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: ByteSize M&Ms, INTEGRATION

#12341 removing inactive annotation <no-unused-vars>
  playwright/tests/my/milmove/ppms/customerPpmTestFixture.js
Labels: G-Unit, INTEGRATION

#12297 INT B-18641 Display Backup Address to Office Users
  src/components/Office/DefinitionLists/CustomerInfoList.jsx
  src/components/Office/DefinitionLists/CustomerInfoList.stories.jsx
  src/components/Office/DefinitionLists/CustomerInfoList.test.jsx
  src/pages/Office/MoveDetails/MoveDetails.jsx
  src/pages/Office/MoveDetails/MoveDetails.test.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.test.jsx
Labels: Scrummy Bears, INTEGRATION

#12319 INT B-18832 admin UI add edit page for requested office users (MERGE AFTER B-18831)
  src/layout/AdminIdleTimeout.jsx
  src/pages/Admin/RequestedOfficeUsers/RequestedOfficeUserEdit.jsx
  src/pages/Admin/RequestedOfficeUsers/RequestedOfficeUserShow.jsx
  src/pages/Admin/RequestedOfficeUsers/RequestedOfficeUserShow.module.scss
  src/scenes/SystemAdmin/Home.jsx
  src/scenes/SystemAdmin/shared/form_validators.js
Labels: Mountain Movers, INTEGRATION

#12298 B 19157
  src/components/Statements/PrivacyAndPolicyStatement.jsx
Labels: Scrummy Bears, MAIN

#12338 INT B-18751 History Log PPM Shipment Created
  .github/workflows/main-to-integration-sync.yml
  src/constants/MoveHistory/EventTemplates/CreateMTOShipment/createMTOShipment.jsx
  src/constants/MoveHistory/EventTemplates/CreateMTOShipment/createMTOShipment.test.jsx
Labels: ByteSize M&Ms, INTEGRATION

#12351 B-19139-mount-support-api-INT
  pkg/cli/swagger.go
Labels: Mountain Movers, INTEGRATION

#12355 INT B-18642 GBLOC fix for USMC
  src/components/CustomerHeader/index.jsx
Labels: ByteSize M&Ms, INTEGRATION

#12278 B:18828 - Add Create Okta Account Logic to UpdateRequestedOfficeUser
  pkg/gen/adminapi/embedded_spec.go
  pkg/gen/adminmessages/okta_account_info_response.go
  pkg/gen/adminmessages/requested_office_user_update.go
  pkg/handlers/adminapi/requested_office_users.go
  pkg/handlers/adminapi/requested_office_users_test.go
  pkg/handlers/authentication/okta/provider.go
  pkg/handlers/authentication/okta/provider_test.go
  pkg/models/okta_account_creation.go
  swagger-def/admin.yaml
  swagger/admin.yaml
Labels: Mountain Movers

#12347 B 18520 update nav links to return to move page int2
  config/env/stg.app.env
Labels: Mountain Movers, INTEGRATION

#12331 INT B-19187 remove download button from multi move landing page
  src/pages/MyMove/Multi-Moves/MultiMovesMoveContainer/MultiMovesMoveContainer.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesMoveContainer/MultiMovesMoveContainer.test.jsx
Labels: Mountain Movers, INTEGRATION

#12354 INTEGRATION-B -19167 - Part 2 --Feature flags to hide/show specific shipment type - Customer UI
  .github/workflows/analyze-bundle.yml
  .github/workflows/front-end-linter.yml
  .github/workflows/go-auto-approve.yml
  .github/workflows/happo-tests-main.yml
  .github/workflows/happo-tests.yml
  .github/workflows/main-to-integration-sync.yml
  src/pages/MyMove/SelectShipmentType.jsx
  src/pages/MyMove/SelectShipmentType.test.jsx
  yarn.lock
Labels: Scrummy Bears, INTEGRATION

#12352 B-18851 FRA Update screen to reflect value in cents, not dollars
  playwright/tests/office/txo/tioFlows.spec.js
  src/components/Office/ServiceItemCalculations/helpers.js
  src/components/Office/ServiceItemCalculations/helpers.test.js
Labels: ByteSize M&Ms, INTEGRATION

#12363 mount support api under office router with prime sim
  pkg/handlers/routing/routing_init.go
Labels: Mountain Movers, INTEGRATION

#12365 B 19167 disable shipment type selection
  .circleci/config.yml
  .envrc
  config/env/demo.app-client-tls.env
  config/env/demo.app.env
  config/env/exp.app-client-tls.env
  config/env/exp.app.env
  config/env/loadtest.app-client-tls.env
  config/env/loadtest.app.env
  config/env/prd.app-client-tls.env
  config/env/prd.app.env
  config/env/stg.app-client-tls.env
  config/env/stg.app.env
  config/flipt/storage/development.features.yaml
  src/components/Customer/Review/AddShipmentModal/AddShipmentModal.jsx
  src/components/Customer/Review/Summary/Summary.jsx
  src/components/Customer/Review/Summary/Summary.test.jsx
  src/components/Customer/modals/MoveInfoModal/MoveInfoModal.jsx
  src/components/Customer/modals/StorageInfoModal/StorageInfoModal.jsx
  src/pages/MyMove/MovingInfo.jsx
  src/pages/MyMove/MovingInfo.test.jsx
  src/pages/MyMove/SelectShipmentType.jsx
  src/pages/MyMove/SelectShipmentType.test.jsx
  src/shared/constants.js
  src/utils/featureFlags.js
Labels: Scrummy Bears, MAIN

#12366 B-19139 update env vars
  config/env/demo.app.env
  config/env/exp.app.env
  config/env/loadtest.app.env
  config/env/prd.app.env
  config/env/stg.app.env
Labels: Mountain Movers, INTEGRATION

#12361 INT B-19237 customer cac registration
  .circleci/config.yml
  .envrc
  config/env/demo.app-client-tls.env
  config/env/demo.app.env
  config/env/exp.app-client-tls.env
  config/env/exp.app.env
  config/env/loadtest.app-client-tls.env
  config/env/loadtest.app.env
  config/env/prd.app-client-tls.env
  config/env/prd.app.env
  config/env/stg.app-client-tls.env
  config/env/stg.app.env
  config/flipt/storage/development.features.yaml
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240327210353_add_cac_verified_to_service_members_table.up.sql
  pkg/auth/session.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/service_member_payload.go
  pkg/handlers/authentication/auth.go
  pkg/handlers/authentication/devlocal.go
  pkg/handlers/internalapi/service_members.go
  pkg/models/service_member.go
  pkg/models/user.go
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/testharness/make_customer.go
  pkg/testdatagen/testharness/make_move.go
  src/scenes/MyMove/index.jsx
  src/shared/SmartCardRedirect/SmartCardRedirect.jsx
  src/shared/SmartCardRedirect/SmartCardRedirect.test.jsx
  src/shared/images/smart-card.png
  src/store/auth/selectors.js
  src/utils/featureFlags.js
  swagger-def/internal.yaml
  swagger/internal.yaml
Labels: Mountain Movers, INTEGRATION

#12349 INT-B-19148 Fix
  pkg/handlers/ghcapi/ppm_document.go
  pkg/handlers/ghcapi/ppm_document_test.go
  pkg/models/move.go
Labels: G-Unit, INTEGRATION

#12348 B 18798 county lookup on address creation int
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/address.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/address.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/address.go
  pkg/gen/primev2api/embedded_spec.go
  pkg/gen/primev2messages/address.go
  pkg/handlers/internalapi/addresses.go
  pkg/handlers/internalapi/addresses_test.go
  pkg/handlers/internalapi/internal/payloads/model_to_payload.go
  pkg/handlers/internalapi/internal/payloads/payload_to_model.go
  pkg/handlers/internalapi/mto_shipment_test.go
  pkg/handlers/internalapi/service_members_test.go
  pkg/handlers/primeapi/payloads/model_to_payload.go
  pkg/models/service_member.go
  pkg/models/us_post_region_city.go
  pkg/services/address/address_creator.go
  pkg/services/address/address_creator_test.go
  pkg/services/mto_service_item/mto_service_item_creator.go
  pkg/services/mto_shipment/mto_shipment_creator.go
  swagger-def/definitions/Address.yaml
  swagger/ghc.yaml
  swagger/internal.yaml
  swagger/prime.yaml
  swagger/prime_v2.yaml
Labels: Mountain Movers, INTEGRATION

#12372 Kickback B18855 I12705 Partial Deliveries are not recalculating
  pkg/payment_request/service_param_value_lookups/weight_billed_lookup.go
Labels: ByteSize M&Ms, INTEGRATION

#12364 INT B-18761 HL loading screen
  src/components/Table/TableQueue.jsx
Labels: ByteSize M&Ms, INTEGRATION

#12369 INT B-18755 move history update weight pro gear expense
  src/constants/MoveHistory/Database/FieldMappings.js
  src/constants/MoveHistory/EventTemplates/CreateMovingExpense/CreateMovingExpense.test.jsx
  src/constants/MoveHistory/EventTemplates/CreateUpload/CreatePPMUpload.jsx
  src/constants/MoveHistory/EventTemplates/CreateUpload/CreatePPMUpload.test.jsx
  src/constants/MoveHistory/EventTemplates/DeleteMovingExpense/DeleteMovingExpense.test.jsx
  src/constants/MoveHistory/EventTemplates/DeleteMovingExpense/DeleteMovingExpenseUserUploads.test.jsx
  src/constants/MoveHistory/EventTemplates/UpdateMovingExpense/UpdateMovingExpense.test.jsx
  src/constants/MoveHistory/EventTemplates/UpdateReweigh/updateReweighWeight.jsx
  src/constants/MoveHistory/EventTemplates/UpdateWeightTicket/updateWeightTicketProGear.jsx
  src/constants/MoveHistory/EventTemplates/UpdateWeightTicket/updateWeightTicketProGear.test.jsx
  src/pages/Office/MoveHistory/LabeledDetails.jsx
  src/utils/formatMtoShipment.js
Labels: ByteSize M&Ms, INTEGRATION

#12357 INT B-18836 send email when office account rejected
  pkg/assets/notifications/templates/office_account_rejected_template.html
  pkg/assets/notifications/templates/office_account_rejected_template.txt
  pkg/handlers/adminapi/requested_office_users.go
  pkg/notifications/office_account_rejected.go
Labels: Mountain Movers, INTEGRATION

#12375 MAIN B-19237 customer cac registration
  .circleci/config.yml
  .envrc
  config/env/demo.app-client-tls.env
  config/env/demo.app.env
  config/env/exp.app-client-tls.env
  config/env/exp.app.env
  config/env/loadtest.app-client-tls.env
  config/env/loadtest.app.env
  config/env/prd.app-client-tls.env
  config/env/prd.app.env
  config/env/stg.app-client-tls.env
  config/env/stg.app.env
  config/flipt/storage/development.features.yaml
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240327210353_add_cac_verified_to_service_members_table.up.sql
  pkg/auth/session.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/service_member_payload.go
  pkg/handlers/authentication/auth.go
  pkg/handlers/authentication/devlocal.go
  pkg/handlers/internalapi/service_members.go
  pkg/models/service_member.go
  pkg/models/user.go
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/testharness/make_customer.go
  pkg/testdatagen/testharness/make_move.go
  src/scenes/MyMove/index.jsx
  src/shared/SmartCardRedirect/SmartCardRedirect.jsx
  src/shared/SmartCardRedirect/SmartCardRedirect.test.jsx
  src/shared/images/smart-card.png
  src/store/auth/selectors.js
  src/utils/featureFlags.js
  swagger-def/internal.yaml
  swagger/internal.yaml
Labels: Mountain Movers, MAIN

#12340 B 19137 payment requests billable weight param changes int
  pkg/payment_request/service_param_value_lookups/weight_billed_lookup.go
  pkg/payment_request/service_param_value_lookups/weight_billed_lookup_test.go
Labels: Mountain Movers, INTEGRATION

#12379 INT B-18756 move history log delete weight pro gear expense
  .circleci/config.yml
  src/constants/MoveHistory/EventTemplates/CreateUpload/CreatePPMUpload.jsx
  src/constants/MoveHistory/EventTemplates/DeleteMovingExpense/DeleteMovingExpenseUserUploads.jsx
  src/constants/MoveHistory/EventTemplates/DeleteMovingExpense/DeleteMovingExpenseUserUploads.test.jsx
  src/constants/MoveHistory/EventTemplates/DeleteProGearWeightTicket/DeleteProGearWeightTicketUserUploads.jsx
  src/constants/MoveHistory/EventTemplates/DeleteProGearWeightTicket/DeleteProGearWeightTicketUserUploads.test.jsx
  src/constants/MoveHistory/EventTemplates/DeleteWeightTicket/DeleteWeightTicketUserUploads.jsx
  src/constants/MoveHistory/EventTemplates/DeleteWeightTicket/DeleteWeightTicketUserUploads.test.jsx
Labels: ByteSize M&Ms, INTEGRATION

#12378 B-19298 New Helpdesk Hyperlink
  src/pages/InvalidPermissions/InvalidPermissions.jsx
  src/pages/Office/ServicesCounselingMoveInfo/ServicesCounselingMoveInfo.jsx
  src/pages/Office/ServicesCounselingMoveInfo/ServicesCounselingMoveInfo.test.jsx
  src/pages/Office/TXOMoveInfo/TXOMoveInfo.jsx
  src/pages/Office/TXOMoveInfo/TXOMoveInfo.test.jsx
  src/pages/Office/index.jsx
  src/shared/DownloadAOAErrorModal/DownloadAOAErrorModal.jsx
  src/shared/SmartCardRedirect/SmartCardRedirect.jsx
  src/shared/SmartCardRedirect/SmartCardRedirect.test.jsx
  src/shared/SomethingWentWrong/index.jsx
  src/shared/SomethingWentWrong/index.test.js
Labels: G-Unit, MAIN
