Repository transcom/mymove, pull requests merged in 2024-06, with the labels that each got.

#12894 B 19988-INT-KB Add cols to track changes during PPM closeout
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240531154303_add_more_submitted_columns_to_ppm_document_tables.up.sql
Labels: G-Unit, INTEGRATION

#12899 B-19982-INT-KB Update submitted_ cols
  pkg/models/progear_weight_ticket.go
  pkg/models/weight_ticket.go
  pkg/services/moving_expense/moving_expense_updater.go
  pkg/services/progear_weight_ticket/progear_weight_ticket_updater.go
  pkg/services/progear_weight_ticket/progear_weight_ticket_updater_test.go
  pkg/services/weight_ticket/weight_ticket_updater.go
  pkg/services/weight_ticket/weight_ticket_updater_test.go
Labels: G-Unit, INTEGRATION

#12902 Main B-19300
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/p_p_m_closeout.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/models/ppm_shipment.go
  pkg/services/ppm_closeout/ppm_closeout.go
  pkg/services/ppmshipment/ppm_estimator.go
  src/components/Office/PPM/PPMHeaderSummary/HeaderSection.jsx
  src/components/Office/PPM/PPMHeaderSummary/HeaderSection.test.jsx
  src/components/Office/PPM/PPMHeaderSummary/PPMHeaderSummary.jsx
  src/components/Office/PPM/PPMHeaderSummary/PPMHeaderSummary.test.jsx
  src/components/Office/PPM/ppmTestData.js
  src/pages/Office/PPM/ReviewDocuments/ReviewDocuments.test.jsx
  src/types/shipment.js
  swagger-def/definitions/PPMCloseout.yaml
  swagger/ghc.yaml
Labels: ByteSize M&Ms, MAIN

#12912 I 12947 resolution int
  package.json
  yarn.lock
Labels: Mountain Movers, INTEGRATION

#12898 I-12947 set react file viewer to v1.2.2
  package.json
  yarn.lock
Labels: Mountain Movers, MAIN

#12901 B 19533 add spouse pro gear weights page MAIN
  src/components/Office/PPM/ReviewShipmentWeightsTable/ReviewShipmentWeightsTable.test.jsx
  src/components/Office/PPM/ReviewShipmentWeightsTable/helpers.jsx
  src/pages/MyMove/PPM/Closeout/ProGear/ProGear.jsx
  src/pages/MyMove/PPM/Closeout/ProGear/ProGear.test.jsx
  src/types/shipment.js
  src/utils/formatters.js
  src/utils/formatters.test.js
Labels: ByteSize M&Ms, MAIN

#12811 Resolve main to int conflicts
  .circleci/config.yml
  .envrc
  config/env/demo.app-client-tls.env
  config/env/demo.app.env
  config/env/exp.app-client-tls.env
  config/env/exp.app.env
  config/env/loadtest.app-client-tls.env
  config/env/loadtest.app.env
  config/env/prd.app-client-tls.env
  config/env/prd.app.env
  config/env/stg.app-client-tls.env
  config/env/stg.app.env
  go.mod
  go.sum
  pkg/handlers/routing/routing_init.go
Labels: Mountain Movers, INTEGRATION

#12909 B-19988-2-INT-KB
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240603040207_add_submitted_cols_to_moving_expenses.up.sql
Labels: G-Unit, INTEGRATION

#12814 B 19888 estimate price int
  pkg/handlers/adminapi/api.go
  pkg/handlers/adminapi/moves_test.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/move_task_order_test.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/handlers/ghcapi/orders_test.go
  pkg/handlers/internalapi/api.go
  pkg/handlers/internalapi/mto_shipment_test.go
  pkg/handlers/primeapi/api.go
  pkg/handlers/primeapi/move_task_order_test.go
  pkg/handlers/primeapi/mto_service_item_test.go
  pkg/handlers/primeapi/mto_shipment_test.go
  pkg/handlers/primeapiv2/api.go
  pkg/handlers/primeapiv2/mto_service_item_test.go
  pkg/handlers/primeapiv2/mto_shipment_test.go
  pkg/handlers/primeapiv3/api.go
  pkg/handlers/primeapiv3/mto_service_item_test.go
  pkg/handlers/primeapiv3/mto_shipment_test.go
  pkg/handlers/supportapi/api.go
  pkg/handlers/supportapi/move_task_order_test.go
  pkg/handlers/supportapi/mto_shipment_test.go
  pkg/models/mto_service_items.go
  pkg/services/move_history/move_history_fetcher_test.go
  pkg/services/move_task_order/move_task_order_updater_test.go
  pkg/services/mto_service_item/mto_service_item_creator.go
  pkg/services/mto_service_item/mto_service_item_creator_test.go
  pkg/services/mto_shipment/mto_shipment_updater_test.go
  pkg/services/mto_shipment/shipment_approver_test.go
  pkg/services/mto_shipment/shipment_deleter_test.go
  pkg/services/shipment_address_update/shipment_address_update_requester.go
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/testharness/make_move.go
Labels: Mountain Movers, INTEGRATION

#12842 B-19923: Admin Office User UI
  playwright/tests/admin/officeUsers.spec.js
  src/pages/Admin/OfficeUsers/OfficeUserCreate.jsx
  src/pages/Admin/OfficeUsers/OfficeUserEdit.jsx
  src/pages/Admin/RequestedOfficeUsers/RequestedOfficeUserEdit.jsx
Labels: Mountain Movers, MAIN

#12910 B 19997 int
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240530020648_adding_standalone_crate_service_param.up.sql
  migrations/app/schema/20240531050324_adding_standalone_crate_cap.up.sql
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/application_parameters/get_param.go
  pkg/gen/ghcapi/ghcoperations/application_parameters/get_param_parameters.go
  pkg/gen/ghcapi/ghcoperations/application_parameters/get_param_responses.go
  pkg/gen/ghcapi/ghcoperations/application_parameters/get_param_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/ghcmessages/application_parameters.go
  pkg/gen/ghcmessages/m_t_o_service_item.go
  pkg/gen/ghcmessages/service_item_param_name.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/service_item_param_name.go
  pkg/gen/primev2api/embedded_spec.go
  pkg/gen/primev2messages/service_item_param_name.go
  pkg/gen/primev3api/embedded_spec.go
  pkg/gen/primev3messages/service_item_param_name.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/application_parameters.go
  pkg/handlers/ghcapi/application_parameters_test.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/models/application_parameters.go
  pkg/models/service_item_param_key.go
  pkg/payment_request/service_param_value_lookups/service_param_value_lookups.go
  pkg/payment_request/service_param_value_lookups/standalone_crate_cap_lookup.go
  pkg/payment_request/service_param_value_lookups/standalone_crate_lookup.go
  pkg/services/ghc_rate_engine.go
  pkg/services/ghcrateengine/domestic_crating_pricer.go
  pkg/services/ghcrateengine/domestic_crating_pricer_test.go
  pkg/services/ghcrateengine/domestic_uncrating_pricer.go
  pkg/services/ghcrateengine/param_convert.go
  pkg/services/ghcrateengine/pricer_helpers.go
  pkg/services/ghcrateengine/pricer_helpers_test.go
  pkg/services/mocks/DomesticCratingPricer.go
  src/components/Office/ExpandableServiceItemRow/ExpandableServiceItemRow.jsx
  src/components/Office/ReviewServiceItems/ServiceItemCard.jsx
  src/components/Office/ServiceItemCalculations/helpers.js
  src/components/Office/ServiceItemCalculations/serviceItemTestParams.js
  src/components/Office/ServiceItemDetails/ServiceItemDetails.jsx
  src/constants/serviceItems.js
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
  src/pages/Office/PaymentRequestReview/PaymentRequestReview.jsx
  swagger-def/definitions/MTOServiceItem.yaml
  swagger-def/definitions/ServiceItemParamName.yaml
  swagger-def/ghc.yaml
  swagger/ghc.yaml
  swagger/prime.yaml
  swagger/prime_v2.yaml
  swagger/prime_v3.yaml
Labels: Scrummy Bears, INTEGRATION

#12895 Int b 19303 - Added "SIT Reimbursement" to "Incentive Factors" on PPM Closeout screen
  pkg/services/ppm_closeout/ppm_closeout.go
  src/components/Office/PPM/PPMHeaderSummary/HeaderSection.jsx
  src/components/Office/PPM/PPMHeaderSummary/HeaderSection.test.jsx
  src/components/Office/PPM/PPMHeaderSummary/PPMHeaderSummary.jsx
  src/components/Office/PPM/ReviewDocumentsSidePanel/ReviewDocumentsSidePanel.jsx
Labels: ByteSize M&Ms, INTEGRATION

#12911 B 19982-2-INT-KB
  pkg/models/moving_expense.go
  pkg/services/moving_expense/moving_expense_updater.go
  pkg/services/moving_expense/moving_expense_updater_test.go
Labels: G-Unit, INTEGRATION

#12826 INT B-20083
  .envrc
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/update_m_t_o_shipment.go
  pkg/gen/primev3api/embedded_spec.go
  pkg/gen/primev3messages/update_m_t_o_shipment.go
  pkg/handlers/primeapi/payloads/payload_to_model.go
  pkg/handlers/primeapiv2/payloads/payload_to_model.go
  pkg/handlers/primeapiv3/payloads/payload_to_model.go
  src/components/Office/PPM/ReviewExpense/ReviewExpense.stories.jsx
  src/components/Office/PPM/ReviewShipmentWeightsTable/ReviewShipmentWeightsTable.stories.jsx
  src/components/Office/PPM/ReviewShipmentWeightsTable/ReviewShipmentWeightsTable.test.jsx
  src/components/Office/PPM/ReviewShipmentWeightsTable/helpers.jsx
  src/pages/Office/ServicesCounselingReviewShipmentWeights/ServicesCounselingReviewShipmentWeights.jsx
  src/pages/Office/ServicesCounselingReviewShipmentWeights/ServicesCounselingReviewShipmentWeights.test.jsx
  swagger-def/prime.yaml
  swagger-def/prime_v2.yaml
  swagger-def/prime_v3.yaml
  swagger/prime.yaml
  swagger/prime_v3.yaml
  yarn.lock
Labels: ByteSize M&Ms, INTEGRATION

#12891 B 18546 Office user not alter order type for safety move
  src/components/Office/OrdersDetailForm/OrdersDetailForm.jsx
  src/components/Office/OrdersDetailForm/OrdersDetailForm.test.jsx
Labels: G-Unit, INTEGRATION

#12896 B 19827 int
  .circleci/config.yml
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240531153321_update_tio_role_name.up.sql
  pkg/factory/admin_user_factory_test.go
  pkg/factory/role_factory.go
  pkg/factory/role_factory_test.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/payment_request/create_upload.go
  pkg/gen/primeclient/payment_request/payment_request_client.go
  pkg/handlers/adminapi/office_users_test.go
  pkg/handlers/adminapi/requested_office_users_test.go
  pkg/models/roles/roles.go
  playwright/tests/admin/officeUsers.spec.js
  playwright/tests/office/homepage.spec.js
  src/components/Office/RequestAccountForm/RequestAccountForm.test.jsx
  src/components/form/OfficeAccountRequestFields/OfficeAccountRequestFields.jsx
  src/components/form/OfficeAccountRequestFields/OfficeAccountRequestFields.test.jsx
  src/constants/userRoles.js
  src/pages/Admin/OfficeUsers/OfficeUserCreate.jsx
  src/pages/Admin/OfficeUsers/OfficeUserEdit.jsx
  src/pages/Admin/RequestedOfficeUsers/RequestedOfficeUserEdit.jsx
  src/pages/Office/RequestAccount/RequestAccount.jsx
  src/utils/validation.js
  swagger-def/prime.yaml
  swagger/prime.yaml
Labels: Mountain Movers, INTEGRATION

#12913 B 19996 int
  src/components/Office/RequestedServiceItemsTable/RequestedServiceItemsTable.test.jsx
  src/components/Office/ReviewServiceItems/ServiceItemCard.jsx
  src/components/Office/ServiceItemsTable/ServiceItemsTable.jsx
Labels: Scrummy Bears, INTEGRATION

#12893 B 19845 int
  playwright/tests/my/milmove/ppms/customerPpmTestFixture.js
  playwright/tests/my/milmove/ppms/expenses.spec.js
  src/components/Customer/PPM/Closeout/ExpenseForm/ExpenseForm.jsx
  src/components/Customer/PPM/Closeout/ExpenseForm/ExpenseForm.test.jsx
  src/pages/MyMove/PPM/Closeout/Expenses/Expenses.jsx
  src/pages/MyMove/PPM/Closeout/Expenses/Expenses.test.jsx
  src/types/shipment.js
Labels: Scrummy Bears, INTEGRATION

#12930 B 19827
  .circleci/config.yml
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240531153321_update_tio_role_name.up.sql
  pkg/factory/admin_user_factory_test.go
  pkg/factory/role_factory.go
  pkg/factory/role_factory_test.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/payment_request/create_upload.go
  pkg/gen/primeclient/payment_request/payment_request_client.go
  pkg/handlers/adminapi/office_users_test.go
  pkg/handlers/adminapi/requested_office_users_test.go
  pkg/models/roles/roles.go
  playwright/tests/admin/officeUsers.spec.js
  playwright/tests/office/homepage.spec.js
  src/components/Office/RequestAccountForm/RequestAccountForm.test.jsx
  src/components/form/OfficeAccountRequestFields/OfficeAccountRequestFields.jsx
  src/components/form/OfficeAccountRequestFields/OfficeAccountRequestFields.test.jsx
  src/constants/userRoles.js
  src/pages/Admin/OfficeUsers/OfficeUserCreate.jsx
  src/pages/Admin/OfficeUsers/OfficeUserEdit.jsx
  src/pages/Admin/RequestedOfficeUsers/RequestedOfficeUserEdit.jsx
  src/pages/Office/RequestAccount/RequestAccount.jsx
  src/utils/validation.js
  swagger-def/prime.yaml
  swagger/prime.yaml
Labels: Mountain Movers, MAIN

#12919 INT- B-19713-UI-Address-PPM-Shipment-Card
  src/components/PPMSummaryList/PPMSummaryList.jsx
  src/components/PPMSummaryList/PPMSummaryList.module.scss
  src/components/PPMSummaryList/PPMSummaryList.test.jsx
  src/pages/MyMove/Home/MoveHome.test.jsx
  src/pages/MyMove/Home/index.test.jsx
  src/utils/test/factories/ppmShipment.js
Labels: Scrummy Bears, INTEGRATION

#12925 B 19889 UI estimatedprice int
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/m_t_o_service_item.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  src/components/Office/ServiceItemDetails/ServiceItemDetails.jsx
  src/components/Office/ServiceItemDetails/ServiceItemDetails.test.jsx
  src/components/Office/ServiceItemsTable/ServiceItemsTable.test.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
  src/types/serviceItems.js
  swagger-def/definitions/MTOServiceItem.yaml
  swagger/ghc.yaml
Labels: Mountain Movers, INTEGRATION

#12844 INT-B- 19933 Signed Certifications SSW
  go.mod
  go.sum
  migrations/app/migrations_manifest.txt
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/signed_certification_type.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/signed_certification_type.go
  pkg/gen/internalmessages/signed_certification_type_create.go
  pkg/handlers/adminapi/api.go
  pkg/handlers/adminapi/moves_test.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/move_task_order_test.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/handlers/ghcapi/orders_test.go
  pkg/handlers/ghcapi/ppm_document_test.go
  pkg/handlers/internalapi/api.go
  pkg/handlers/internalapi/mto_shipment_test.go
  pkg/handlers/primeapi/api.go
  pkg/handlers/primeapi/move_task_order_test.go
  pkg/handlers/primeapi/mto_shipment_test.go
  pkg/handlers/primeapiv2/api.go
  pkg/handlers/primeapiv2/mto_shipment_test.go
  pkg/handlers/primeapiv3/api.go
  pkg/handlers/primeapiv3/mto_shipment_test.go
  pkg/handlers/supportapi/api.go
  pkg/handlers/supportapi/move_task_order_test.go
  pkg/models/signed_certification.go
  pkg/models/signed_certification_test.go
  pkg/services/move_task_order/move_task_order_updater.go
  pkg/services/move_task_order/move_task_order_updater_test.go
  pkg/services/mto_shipment/shipment_deleter_test.go
  pkg/services/ppmshipment/ppm_shipment_review_documents.go
  pkg/services/ppmshipment/ppm_shipment_review_documents_test.go
  pkg/testdatagen/scenario/shared.go
  swagger-def/definitions/SignedCertificationType.yaml
  swagger-def/internal.yaml
  swagger/ghc.yaml
  swagger/internal.yaml
  yarn.lock
Labels: Scrummy Bears, INTEGRATION

#12933 INT B-20070 PPM Address Instructions
  src/components/Customer/PPM/Booking/DateAndLocationForm/DateAndLocationForm.jsx
Labels: Scrummy Bears, INTEGRATION

#12733 INT-B-19918 do not send safety emails
  pkg/handlers/ghcapi/move_task_order.go
  pkg/handlers/ghcapi/mto_shipment.go
  pkg/handlers/ghcapi/ppm_document.go
  pkg/handlers/internalapi/moves.go
  pkg/handlers/internalapi/office.go
  pkg/handlers/primeapi/move_task_order.go
  pkg/models/order.go
  pkg/services/mto_shipment/mto_shipment_updater.go
Labels: G-Unit, INTEGRATION

#12940 B 20164 int - V2
  src/components/Customer/PPM/Booking/EstimatedIncentiveDetails/EstimatedIncentiveDetails.jsx
  src/components/Customer/PPM/Booking/EstimatedIncentiveDetails/EstimatedIncentiveDetails.test.jsx
Labels: Scrummy Bears, INTEGRATION

#12941 INT B-19886 Hide Diversion Link for PPMs
  src/components/Office/ShipmentAddresses/ShipmentAddresses.jsx
  src/components/Office/ShipmentAddresses/ShipmentAddresses.test.jsx
Labels: Scrummy Bears, INTEGRATION

#12946 B-19988-add submitted_ cols to PPM document tables MERGE BEFORE 19982
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240506214039_add_submitted_columns_to_ppm_document_tables.up.sql
  migrations/app/schema/20240531154303_add_more_submitted_columns_to_ppm_document_tables.up.sql
  migrations/app/schema/20240603040207_add_submitted_cols_to_moving_expenses.up.sql
Labels: G-Unit, MAIN

#12938 B 19997 INT - V2
  migrations/app/schema/20240530020648_adding_standalone_crate_service_param.up.sql
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/service_item_param_name.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/service_item_param_name.go
  pkg/gen/primev2api/embedded_spec.go
  pkg/gen/primev2messages/service_item_param_name.go
  pkg/gen/primev3api/embedded_spec.go
  pkg/gen/primev3messages/service_item_param_name.go
  pkg/models/service_item_param_key.go
  pkg/services/ghcrateengine/domestic_crating_pricer_test.go
  pkg/services/ghcrateengine/domestic_uncrating_pricer_test.go
  pkg/services/ghcrateengine/pricer_helpers.go
  pkg/services/ghcrateengine/pricer_helpers_test.go
  src/components/Office/ServiceItemCalculations/helpers.js
  src/components/Office/ServiceItemDetails/ServiceItemDetails.jsx
  src/constants/serviceItems.js
  swagger-def/definitions/ServiceItemParamName.yaml
  swagger/ghc.yaml
  swagger/prime.yaml
  swagger/prime_v2.yaml
  swagger/prime_v3.yaml
Labels: Scrummy Bears, INTEGRATION

#12949 B-19178 excess weight bugfix
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/services/mto_shipment/shipment_approver.go
  pkg/services/mto_shipment/shipment_approver_test.go
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
Labels: G-Unit, MAIN

#12937 B 19830 int revised
  pkg/assets/paperwork/formtemplates/SSWPDFTemplate.pdf
  pkg/services/shipment_summary_worksheet.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet_test.go
Labels: Scrummy Bears, INTEGRATION

#12915 B-19824 add csr to roles table
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240522124339_add_csr_to_roles.up.sql
Labels: Mountain Movers, MAIN

#12916 B 19897 and b 19898 csr UI and backend main (MERGE AFTER)
  pkg/factory/role_factory.go
  pkg/handlers/authentication/devlocal.go
  pkg/handlers/authentication/devlocal_test.go
  pkg/handlers/authentication/permissions.go
  pkg/models/roles/roles.go
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/scenario/subscenarios.go
  playwright/tests/office/qaecsr/csrFlows.spec.js
  playwright/tests/utils/office/officeTest.js
  src/components/Office/CustomerSupportRemarkForm/CustomerSupportRemarkForm.test.jsx
  src/components/form/OfficeAccountRequestFields/OfficeAccountRequestFields.jsx
  src/components/form/OfficeAccountRequestFields/OfficeAccountRequestFields.test.jsx
  src/constants/queues.js
  src/constants/userRoles.js
  src/pages/Office/RequestAccount/RequestAccount.jsx
  src/pages/Office/index.jsx
  src/pages/Office/index.test.jsx
  src/pages/SelectApplication/SelectApplication.jsx
  src/pages/SelectApplication/SelectApplication.test.jsx
  src/utils/validation.js
Labels: Mountain Movers, MAIN

#12931 19782 shipment cancellation date validation Backend INT
  pkg/handlers/ghcapi/mto_shipment.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/services/mto_shipment/shipment_cancellation_requester.go
  pkg/services/mto_shipment/shipment_cancellation_requester_test.go
  pkg/testdatagen/testharness/make_move.go
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
Labels: ByteSize M&Ms, INTEGRATION

#12756 B-19975-INT Customer PPM Feedback
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/moving_expense.go
  pkg/gen/ghcmessages/pro_gear_weight_ticket.go
  pkg/gen/ghcmessages/submitted_moving_expense_type.go
  pkg/gen/ghcmessages/weight_ticket.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/moving_expense.go
  pkg/gen/internalmessages/pro_gear_weight_ticket.go
  pkg/gen/internalmessages/submitted_moving_expense_type.go
  pkg/gen/internalmessages/weight_ticket.go
  pkg/handlers/internalapi/internal/payloads/model_to_payload.go
  src/components/Customer/PPM/Closeout/FeedbackItems/FeedbackItems.jsx
  src/components/Customer/PPM/Closeout/FeedbackItems/FeedbackItems.module.scss
  src/components/Customer/PPM/Closeout/FeedbackItems/FeedbackItems.test.jsx
  src/components/PPMSummaryList/PPMSummaryList.jsx
  src/components/PPMSummaryList/PPMSummaryList.module.scss
  src/constants/ppmFeedback.js
  src/constants/routes.js
  src/pages/MyMove/Home/MoveHome.jsx
  src/pages/MyMove/PPM/Closeout/Feedback/Feedback.jsx
  src/pages/MyMove/PPM/Closeout/Feedback/Feedback.module.scss
  src/pages/MyMove/PPM/Closeout/Feedback/Feedback.test.jsx
  src/scenes/MyMove/index.jsx
  src/utils/ppmCloseout.jsx
  swagger-def/definitions/MovingExpense.yaml
  swagger-def/definitions/ProGearWeightTicket.yaml
  swagger-def/definitions/SubmittedMovingExpenseType.yaml
  swagger-def/definitions/WeightTicket.yaml
  swagger/ghc.yaml
  swagger/internal.yaml
Labels: G-Unit, INTEGRATION

#12934 B 20154 PPM Full Address on Review Documents Page
  pkg/handlers/ghcapi/mto_shipment.go
  src/components/Office/PPM/PPMHeaderSummary/HeaderSection.jsx
  src/components/Office/PPM/PPMHeaderSummary/HeaderSection.module.scss
  src/components/Office/PPM/PPMHeaderSummary/HeaderSection.test.jsx
  src/components/Office/PPM/PPMHeaderSummary/PPMHeaderSummary.jsx
  src/components/Office/PPM/PPMHeaderSummary/PPMHeaderSummary.test.jsx
Labels: Scrummy Bears, MAIN

#12962 INT B-19807 - kickback fix related values not updating after edit
  src/components/Office/PPM/PPMHeaderSummary/EditPPMHeaderSummaryModal.jsx
  src/components/Office/PPM/PPMHeaderSummary/EditPPMHeaderSummaryModal.stories.jsx
  src/components/Office/PPM/PPMHeaderSummary/EditPPMHeaderSummaryModal.test.jsx
  src/components/Office/PPM/PPMHeaderSummary/HeaderSection.jsx
  src/components/Office/PPM/PPMHeaderSummary/HeaderSection.module.scss
  src/components/Office/PPM/PPMHeaderSummary/PPMHeaderSummary.jsx
  src/hooks/queries.js
  src/utils/api.js
  src/utils/api.test.js
Labels: ByteSize M&Ms, INTEGRATION

#12948 B-19535-KB authorized weight updates to 110% of estimated weights
  pkg/services/mto_shipment/mto_shipment_updater.go
  pkg/services/mto_shipment/mto_shipment_updater_test.go
  pkg/services/mto_shipment/shipment_approver.go
  pkg/services/mto_shipment/shipment_approver_test.go
  src/components/Office/AllowancesDetailForm/AllowancesDetailForm.jsx
  src/components/Office/DefinitionLists/AllowancesList.jsx
  src/components/Office/DefinitionLists/AllowancesList.stories.jsx
  src/components/Office/DefinitionLists/AllowancesList.test.jsx
  src/components/Office/RequestedShipments/SubmittedRequestedShipments.jsx
  src/components/Office/ShipmentApprovalPreview/ShipmentApprovalPreview.jsx
  src/pages/Office/MoveDetails/MoveDetails.jsx
Labels: G-Unit, MAIN

#12947 B-19982 update customer PPM doc submission to use new cols
  pkg/models/moving_expense.go
  pkg/models/progear_weight_ticket.go
  pkg/models/weight_ticket.go
  pkg/services/moving_expense/moving_expense_updater.go
  pkg/services/moving_expense/moving_expense_updater_test.go
  pkg/services/progear_weight_ticket/progear_weight_ticket_updater.go
  pkg/services/progear_weight_ticket/progear_weight_ticket_updater_test.go
  pkg/services/weight_ticket/weight_ticket_updater.go
  pkg/services/weight_ticket/weight_ticket_updater_test.go
Labels: G-Unit, MAIN

#12958 B-18546 Office user not alter order type for safety move
  src/components/Office/OrdersDetailForm/OrdersDetailForm.jsx
  src/components/Office/OrdersDetailForm/OrdersDetailForm.test.jsx
Labels: G-Unit, MAIN

#12736 INT-B-20043
  pkg/handlers/ghcapi/move.go
  pkg/handlers/ghcapi/move_test.go
Labels: G-Unit, INTEGRATION

#12983 B 19997 int V3
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240530020648_adding_standalone_crate_service_param.up.sql
  migrations/app/schema/20240606195706_adding_uncapped_request_total.up.sql
Labels: Scrummy Bears, INTEGRATION

#12917 B 19899 admin app csr role main (MERGE AFTER)
  src/constants/userRoles.js
Labels: Mountain Movers, MAIN

#12980 INT-B-19980 Fixed issue with editable advance amount on PPM Closeout screen not updating "Remaining Incentive" value.
  pkg/services/ppm_closeout/ppm_closeout.go
Labels: ByteSize M&Ms, INTEGRATION

#12936 B:19826 - Rename Transportation Ordering Officer to Task Ordering Officer
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240603152949_update_too_role_name.up.sql
  pkg/factory/role_factory.go
  pkg/factory/role_factory_test.go
  pkg/gen/adminapi/embedded_spec.go
  pkg/gen/adminmessages/office_user_role.go
  pkg/gen/adminmessages/role.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/office_user_role.go
  pkg/gen/ghcmessages/role.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/m_t_o_shipment_without_service_items.go
  pkg/gen/primev2api/embedded_spec.go
  pkg/gen/primev2messages/m_t_o_shipment_without_service_items.go
  pkg/gen/primev3api/embedded_spec.go
  pkg/gen/primev3messages/m_t_o_shipment_without_service_items.go
  pkg/handlers/adminapi/office_users_test.go
  pkg/handlers/adminapi/requested_office_users_test.go
  pkg/handlers/authentication/devlocal.go
  pkg/handlers/ghcapi/office_users_test.go
  pkg/models/privileges.go
  pkg/models/roles/roles.go
  pkg/services/users_roles/users_roles.go
  playwright/tests/admin/officeUsers.spec.js
  playwright/tests/office/homepage.spec.js
  playwright/tests/office/txo/tooFlows.spec.js
  playwright/tests/utils/office/officeTest.js
  src/components/Office/RequestAccountForm/RequestAccountForm.test.jsx
  src/components/form/OfficeAccountRequestFields/OfficeAccountRequestFields.jsx
  src/components/form/OfficeAccountRequestFields/OfficeAccountRequestFields.test.jsx
  src/constants/userRoles.js
  src/pages/Admin/OfficeUsers/OfficeUserCreate.jsx
  src/pages/Admin/OfficeUsers/OfficeUserEdit.jsx
  src/pages/Admin/RequestedOfficeUsers/RequestedOfficeUserEdit.jsx
  src/pages/Office/RequestAccount/RequestAccount.jsx
  src/pages/Office/RequestAccount/RequestAccount.test.jsx
  src/utils/validation.js
  swagger-def/admin.yaml
  swagger-def/definitions/prime/MTOShipmentWithoutServiceItems.yaml
  swagger-def/definitions/prime/v2/MTOShipmentWithoutServiceItems.yaml
  swagger-def/definitions/prime/v3/MTOShipmentWithoutServiceItems.yaml
  swagger-def/ghc.yaml
  swagger/admin.yaml
  swagger/ghc.yaml
  swagger/prime.yaml
  swagger/prime_v2.yaml
  swagger/prime_v3.yaml
Labels: Mountain Movers, INTEGRATION

#12836 B-19551 PPM showing as INCOMPLETE when it's initially saved without a Closeout Office
  playwright/tests/my/milmove/ppms/customerPpmTestFixture.js
  playwright/tests/my/milmove/ppms/dateAndLocation.spec.js
  src/components/Customer/PPM/Booking/DateAndLocationForm/DateAndLocationForm.jsx
Labels: ByteSize M&Ms, INTEGRATION

#12987 B 19997
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240530020648_adding_standalone_crate_service_param.up.sql
  migrations/app/schema/20240531050324_adding_standalone_crate_cap.up.sql
  migrations/app/schema/20240606195706_adding_uncapped_request_total.up.sql
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/application_parameters/get_param.go
  pkg/gen/ghcapi/ghcoperations/application_parameters/get_param_parameters.go
  pkg/gen/ghcapi/ghcoperations/application_parameters/get_param_responses.go
  pkg/gen/ghcapi/ghcoperations/application_parameters/get_param_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/ghcmessages/application_parameters.go
  pkg/gen/ghcmessages/m_t_o_service_item.go
  pkg/gen/ghcmessages/service_item_param_name.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/service_item_param_name.go
  pkg/gen/primev2api/embedded_spec.go
  pkg/gen/primev2messages/service_item_param_name.go
  pkg/gen/primev3api/embedded_spec.go
  pkg/gen/primev3messages/service_item_param_name.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/application_parameters.go
  pkg/handlers/ghcapi/application_parameters_test.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/models/application_parameters.go
  pkg/models/service_item_param_key.go
  pkg/payment_request/service_param_value_lookups/service_param_value_lookups.go
  pkg/payment_request/service_param_value_lookups/standalone_crate_cap_lookup.go
  pkg/payment_request/service_param_value_lookups/standalone_crate_lookup.go
  pkg/services/ghc_rate_engine.go
  pkg/services/ghcrateengine/domestic_crating_pricer.go
  pkg/services/ghcrateengine/domestic_crating_pricer_test.go
  pkg/services/ghcrateengine/domestic_uncrating_pricer.go
  pkg/services/ghcrateengine/domestic_uncrating_pricer_test.go
  pkg/services/ghcrateengine/param_convert.go
  pkg/services/ghcrateengine/pricer_helpers.go
  pkg/services/ghcrateengine/pricer_helpers_test.go
  pkg/services/mocks/DomesticCratingPricer.go
  src/components/Office/ExpandableServiceItemRow/ExpandableServiceItemRow.jsx
  src/components/Office/ReviewServiceItems/ServiceItemCard.jsx
  src/components/Office/ServiceItemCalculations/helpers.js
  src/components/Office/ServiceItemCalculations/serviceItemTestParams.js
  src/constants/serviceItems.js
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
  src/pages/Office/PaymentRequestReview/PaymentRequestReview.jsx
  swagger-def/definitions/MTOServiceItem.yaml
  swagger-def/definitions/ServiceItemParamName.yaml
  swagger-def/ghc.yaml
  swagger/ghc.yaml
  swagger/prime.yaml
  swagger/prime_v2.yaml
  swagger/prime_v3.yaml
Labels: Scrummy Bears, MAIN

#12993 MAIN-B-19303 Added "SIT Reimbursement" to "Incentive Factors" on PPM Closeout screen
  pkg/services/ppm_closeout/ppm_closeout.go
  src/components/Office/PPM/PPMHeaderSummary/HeaderSection.jsx
  src/components/Office/PPM/PPMHeaderSummary/HeaderSection.test.jsx
  src/components/Office/PPM/PPMHeaderSummary/PPMHeaderSummary.jsx
  src/components/Office/PPM/ReviewDocumentsSidePanel/ReviewDocumentsSidePanel.jsx
Labels: ByteSize M&Ms, MAIN

#12978 B 19996
  src/components/Office/RequestedServiceItemsTable/RequestedServiceItemsTable.test.jsx
  src/components/Office/ReviewServiceItems/ServiceItemCard.jsx
  src/components/Office/ServiceItemsTable/ServiceItemsTable.jsx
Labels: Scrummy Bears, MAIN

#12833 MAIN B-19807 fe sc ability to edit departure aoa
  pkg/services/mto_shipment/rules.go
  pkg/services/mto_shipment/rules_test.go
  playwright/tests/office/servicescounseling/servicesCounselingFlows.spec.js
  src/components/Office/PPM/PPMHeaderSummary/EditPPMHeaderSummaryModal.jsx
  src/components/Office/PPM/PPMHeaderSummary/EditPPMHeaderSummaryModal.module.scss
  src/components/Office/PPM/PPMHeaderSummary/EditPPMHeaderSummaryModal.stories.jsx
  src/components/Office/PPM/PPMHeaderSummary/EditPPMHeaderSummaryModal.test.jsx
  src/components/Office/PPM/PPMHeaderSummary/HeaderSection.jsx
  src/components/Office/PPM/PPMHeaderSummary/HeaderSection.module.scss
  src/components/Office/PPM/PPMHeaderSummary/HeaderSection.test.jsx
  src/components/Office/PPM/PPMHeaderSummary/PPMHeaderSummary.jsx
  src/components/Office/PPM/PPMHeaderSummary/PPMHeaderSummary.module.scss
  src/components/Office/PPM/PPMHeaderSummary/PPMHeaderSummary.test.jsx
  src/components/Office/PPM/ReviewDocumentsSidePanel/ReviewDocumentsSidePanel.jsx
  src/components/Office/PPM/ReviewDocumentsSidePanel/ReviewDocumentsSidePanel.module.scss
  src/components/Office/PPM/ReviewExpense/ReviewExpense.jsx
  src/components/Office/PPM/ReviewExpense/ReviewExpense.module.scss
  src/components/Office/PPM/ReviewProGear/ReviewProGear.jsx
  src/components/Office/PPM/ReviewProGear/ReviewProGear.module.scss
  src/components/Office/PPM/ReviewWeightTicket/ReviewWeightTicket.jsx
  src/components/Office/PPM/ReviewWeightTicket/ReviewWeightTicket.module.scss
  src/hooks/queries.js
  src/pages/Office/PPM/ReviewDocuments/ReviewDocuments.jsx
  src/pages/Office/PPM/ReviewDocuments/ReviewDocuments.test.jsx
  src/utils/api.js
  src/utils/api.test.js
Labels: ByteSize M&Ms, MAIN

#12979 19782 shipment cancellation date validation be int quick fix
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/services/mto_shipment/shipment_approver.go
  pkg/services/mto_shipment/shipment_approver_test.go
  pkg/services/mto_shipment/shipment_cancellation_requester.go
Labels: ByteSize M&Ms, INTEGRATION

#12986 B 20173 add sit location to moving expenses
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240524214247_add_sit_location_moving_expenses.up.sql
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/moving_expense.go
  pkg/gen/ghcmessages/update_moving_expense.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/moving_expense.go
  pkg/gen/internalmessages/update_moving_expense.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/internal/payloads/payload_to_model.go
  pkg/handlers/internalapi/internal/payloads/model_to_payload.go
  pkg/handlers/internalapi/internal/payloads/payload_to_model.go
  pkg/models/moving_expense.go
  pkg/services/moving_expense/moving_expense_updater.go
  pkg/services/moving_expense/moving_expense_updater_test.go
  src/pages/MyMove/PPM/Closeout/Expenses/Expenses.jsx
  src/pages/MyMove/PPM/Closeout/Expenses/Expenses.test.jsx
  swagger-def/definitions/MovingExpense.yaml
  swagger-def/ghc.yaml
  swagger-def/internal.yaml
  swagger/ghc.yaml
  swagger/internal.yaml
Labels: Scrummy Bears, MAIN

#12977 B 19830 ssw text
  pkg/assets/paperwork/formtemplates/SSWPDFTemplate.pdf
  pkg/services/shipment_summary_worksheet.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet_test.go
Labels: Scrummy Bears, MAIN

#12972 B 20204 int
  src/components/Office/ServiceItemCalculations/helpers.js
Labels: Scrummy Bears, INTEGRATION

#12975 B 19888 estimate price main
  pkg/handlers/adminapi/api.go
  pkg/handlers/adminapi/moves_test.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/move_task_order_test.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/handlers/ghcapi/orders_test.go
  pkg/handlers/internalapi/api.go
  pkg/handlers/internalapi/mto_shipment_test.go
  pkg/handlers/primeapi/api.go
  pkg/handlers/primeapi/move_task_order_test.go
  pkg/handlers/primeapi/mto_service_item_test.go
  pkg/handlers/primeapi/mto_shipment_test.go
  pkg/handlers/primeapiv2/api.go
  pkg/handlers/primeapiv2/mto_service_item_test.go
  pkg/handlers/primeapiv2/mto_shipment_test.go
  pkg/handlers/primeapiv3/api.go
  pkg/handlers/primeapiv3/mto_service_item_test.go
  pkg/handlers/primeapiv3/mto_shipment_test.go
  pkg/handlers/supportapi/api.go
  pkg/handlers/supportapi/move_task_order_test.go
  pkg/handlers/supportapi/mto_shipment_test.go
  pkg/models/mto_service_items.go
  pkg/services/move_history/move_history_fetcher_test.go
  pkg/services/move_task_order/move_task_order_updater_test.go
  pkg/services/mto_service_item/mto_service_item_creator.go
  pkg/services/mto_service_item/mto_service_item_creator_test.go
  pkg/services/mto_shipment/mto_shipment_updater_test.go
  pkg/services/mto_shipment/shipment_approver_test.go
  pkg/services/mto_shipment/shipment_deleter_test.go
  pkg/services/shipment_address_update/shipment_address_update_requester.go
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/testharness/make_move.go
Labels: Mountain Movers, MAIN

#12924 Int b 19925 sorting branch param to uppercase
  pkg/services/move/move_searcher.go
  pkg/services/order/order_fetcher.go
Labels: Mountain Movers, INTEGRATION

#12999 B 20164 int
  src/components/Customer/PPM/Booking/EstimatedIncentiveDetails/EstimatedIncentiveDetails.stories.jsx
Labels: Scrummy Bears, INTEGRATION

#12990 MAIN-B-20083
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/update_m_t_o_shipment.go
  pkg/gen/primev3api/embedded_spec.go
  pkg/gen/primev3messages/update_m_t_o_shipment.go
  pkg/handlers/primeapi/payloads/payload_to_model.go
  pkg/handlers/primeapiv2/payloads/payload_to_model.go
  pkg/handlers/primeapiv3/payloads/payload_to_model.go
  src/components/Office/PPM/ReviewShipmentWeightsTable/ReviewShipmentWeightsTable.stories.jsx
  src/components/Office/PPM/ReviewShipmentWeightsTable/ReviewShipmentWeightsTable.test.jsx
  src/components/Office/PPM/ReviewShipmentWeightsTable/helpers.jsx
  src/pages/Office/ServicesCounselingReviewShipmentWeights/ServicesCounselingReviewShipmentWeights.jsx
  src/pages/Office/ServicesCounselingReviewShipmentWeights/ServicesCounselingReviewShipmentWeights.test.jsx
  swagger-def/prime.yaml
  swagger-def/prime_v2.yaml
  swagger-def/prime_v3.yaml
  swagger/prime.yaml
  swagger/prime_v3.yaml
Labels: ByteSize M&Ms, MAIN

#12796 B 20164
  migrations/app/migrations_manifest.txt
  pkg/services/ppm_closeout/ppm_closeout.go
  pkg/services/ppm_closeout/ppm_closeout_test.go
  pkg/services/ppmshipment/ppm_estimator.go
  pkg/services/ppmshipment/ppm_estimator_test.go
  src/components/Customer/PPM/Booking/EstimatedIncentiveDetails/EstimatedIncentiveDetails.jsx
  src/components/Customer/PPM/Booking/EstimatedIncentiveDetails/EstimatedIncentiveDetails.stories.jsx
  src/components/Customer/PPM/Booking/EstimatedIncentiveDetails/EstimatedIncentiveDetails.test.jsx
  src/pages/MyMove/PPM/Booking/EstimatedIncentive/EstimatedIncentive.test.jsx
Labels: Scrummy Bears, MAIN

#12944 INT B-19979 Diversion Reason in Prime API and UI
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/m_t_o_shipment_without_service_items.go
  pkg/gen/primev2api/embedded_spec.go
  pkg/gen/primev2messages/m_t_o_shipment_without_service_items.go
  pkg/gen/primev3api/embedded_spec.go
  pkg/gen/primev3messages/m_t_o_shipment_without_service_items.go
  pkg/handlers/primeapi/payloads/model_to_payload.go
  pkg/handlers/primeapiv2/payloads/model_to_payload.go
  pkg/handlers/primeapiv3/payloads/model_to_payload.go
  src/components/PrimeUI/Shipment/Shipment.jsx
  src/components/PrimeUI/Shipment/Shipment.test.jsx
  swagger-def/definitions/prime/MTOShipmentWithoutServiceItems.yaml
  swagger-def/definitions/prime/v2/MTOShipmentWithoutServiceItems.yaml
  swagger-def/definitions/prime/v3/MTOShipmentWithoutServiceItems.yaml
  swagger/prime.yaml
  swagger/prime_v2.yaml
  swagger/prime_v3.yaml
Labels: Scrummy Bears, INTEGRATION

#12992 INT - B-19794 SC-ability-to-open-PPM-after-Closeout
  pkg/services/ppm_closeout/ppm_closeout.go
  playwright/tests/office/servicescounseling/servicesCounselingFlows.spec.js
  src/components/Office/PPM/PPMHeaderSummary/HeaderSection.jsx
  src/components/Office/PPM/PPMHeaderSummary/PPMHeaderSummary.jsx
  src/components/Office/PPM/ReviewDocumentsSidePanel/ReviewDocumentsSidePanel.jsx
  src/components/Office/PPM/ReviewDocumentsSidePanel/ReviewDocumentsSidePanel.test.jsx
  src/components/Office/PPM/ReviewExpense/ReviewExpense.jsx
  src/components/Office/PPM/ReviewExpense/ReviewExpense.test.jsx
  src/components/Office/PPM/ReviewProGear/ReviewProGear.jsx
  src/components/Office/PPM/ReviewProGear/ReviewProGear.test.jsx
  src/components/Office/PPM/ReviewWeightTicket/ReviewWeightTicket.jsx
  src/components/Office/PPM/ReviewWeightTicket/ReviewWeightTicket.test.jsx
  src/components/Office/ShipmentDisplay/ShipmentDisplay.jsx
  src/components/Office/ShipmentDisplay/ShipmentDisplay.test.jsx
  src/constants/routes.js
  src/pages/Office/PPM/ReviewDocuments/ReviewDocuments.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
  src/pages/Office/ServicesCounselingMoveInfo/ServicesCounselingMoveInfo.jsx
  src/pages/Office/ServicesCounselingMoveInfo/ServicesCounselingMoveInfo.test.jsx
Labels: ByteSize M&Ms, INTEGRATION

#12960 B-19934 SSW Display Signed Certifications
  pkg/services/ppmshipment/aoa_packet_creator_test.go
  pkg/services/shipment_summary_worksheet.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet_test.go
Labels: Scrummy Bears, INTEGRATION

#12970 B 19895 tio queue payment requested int
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/queues.go
  pkg/models/payment_request.go
  playwright/tests/office/txo/tioFlows.spec.js
  src/constants/queues.js
  src/pages/Office/PaymentRequestQueue/PaymentRequestQueue.jsx
  src/pages/Office/PaymentRequestQueue/PaymentRequestQueue.test.jsx
Labels: Mountain Movers, INTEGRATION

#12950 B 19825 rename qaecsr to qae int
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240530084720_rename_qae_csr_to_just_qae.up.sql
  pkg/factory/role_factory.go
  pkg/factory/role_factory_test.go
  pkg/handlers/adminapi/office_users_test.go
  pkg/handlers/adminapi/requested_office_users_test.go
  pkg/handlers/authentication/auth_test.go
  pkg/handlers/authentication/devlocal.go
  pkg/handlers/authentication/devlocal_test.go
  pkg/handlers/authentication/permissions.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/handlers/ghcapi/office_users_test.go
  pkg/models/roles/roles.go
  pkg/services/evaluation_report/evaluation_report_fetcher_test.go
  pkg/services/move/move_searcher_test.go
  pkg/services/query/query_builder_test.go
  pkg/testdatagen/scenario/e2ebasic.go
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/scenario/subscenarios.go
  playwright/tests/office/qaecsr/csrFlows.spec.js
  playwright/tests/office/qaecsr/moveSearchFlows.spec.js
  playwright/tests/office/qaecsr/qaeFlows.spec.js
  playwright/tests/office/txo/tooFlows.spec.js
  playwright/tests/utils/office/officeTest.js
  src/components/Office/CustomerSupportRemarkForm/CustomerSupportRemarkForm.test.jsx
  src/components/Office/EvaluationForm/EvaluationForm.test.jsx
  src/components/Office/EvaluationReportPreview/EvaluationReportPreview.test.jsx
  src/components/Office/QAEViolationsForm/QAEViolationsForm.stories.jsx
  src/components/Office/QAEViolationsForm/QAEViolationsForm.test.jsx
  src/components/Office/RequestAccountForm/RequestAccountForm.test.jsx
  src/components/form/OfficeAccountRequestFields/OfficeAccountRequestFields.jsx
  src/components/form/OfficeAccountRequestFields/OfficeAccountRequestFields.test.jsx
  src/constants/queryKeys.js
  src/constants/queues.js
  src/constants/routes.js
  src/constants/userRoles.js
  src/hooks/queries.js
  src/pages/Office/EvaluationViolations/EvaluationViolations.test.jsx
  src/pages/Office/RequestAccount/RequestAccount.jsx
  src/pages/Office/RequestAccount/RequestAccount.test.jsx
  src/pages/Office/index.jsx
  src/pages/Office/index.test.jsx
  src/pages/SelectApplication/SelectApplication.jsx
  src/pages/SelectApplication/SelectApplication.test.jsx
  src/utils/validation.js
Labels: Mountain Movers, INTEGRATION

#12998 INT-B-19918-2 do not send safety emails
  pkg/handlers/ghcapi/mto_shipment.go
Labels: G-Unit, INTEGRATION

#12989 INT-B-19230-SIT-PPM
  src/components/Office/ShipmentCustomerSIT/ShipmentCustomerSIT.jsx
  src/components/Office/ShipmentForm/ShipmentForm.jsx
  src/components/Office/ShipmentForm/ppmShipmentSchema.js
  src/pages/Office/ServicesCounselingEditShipmentDetails/ServicesCounselingEditShipmentDetails.test.jsx
Labels: Scrummy Bears, INTEGRATION

#12991 B 19884 I-12960 authenticate non cac users
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/customer.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  src/components/DocumentViewer/Content/Content.jsx
  src/components/Office/CustomerContactInfoForm/CustomerContactInfoForm.jsx
  src/components/Office/CustomerContactInfoForm/CustomerContactInfoForm.test.jsx
  src/pages/Office/CreateMoveCustomerInfo/CreateMoveCustomerInfo.jsx
  src/pages/Office/CreateMoveCustomerInfo/CreateMoveCustomerInfo.test.jsx
  src/pages/Office/CustomerInfo/CustomerInfo.jsx
  src/pages/Office/CustomerInfo/CustomerInfo.test.jsx
  src/utils/formatters.js
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: Mountain Movers, MAIN

#12976 B 19889 UI estimatedprice main
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/m_t_o_service_item.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  src/components/Office/ServiceItemDetails/ServiceItemDetails.jsx
  src/components/Office/ServiceItemDetails/ServiceItemDetails.test.jsx
  src/components/Office/ServiceItemsTable/ServiceItemsTable.test.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
  src/types/serviceItems.js
  swagger-def/definitions/MTOServiceItem.yaml
  swagger/ghc.yaml
Labels: Mountain Movers, MAIN

#12974 B-20229 refactor fuel pricer
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240604203456_add_effective_expiraton_date_ghc_fuel.up.sql
  pkg/handlers/primeapi/payment_request_test.go
  pkg/models/ghc_diesel_fuel_price.go
  pkg/payment_request/service_param_value_lookups/eia_fuel_price_lookup.go
  pkg/payment_request/service_param_value_lookups/eia_fuel_price_lookup_test.go
  pkg/services/ghcdieselfuelprice/ghc_diesel_fuel_price_storer.go
  pkg/services/ghcdieselfuelprice/ghc_diesel_fuel_price_storer_test.go
  pkg/services/payment_request/payment_request_recalculator_test.go
  pkg/services/ppm_closeout/ppm_closeout_test.go
  pkg/services/ppmshipment/ppm_estimator_test.go
  pkg/testdatagen/make_ghc_diesel_fuel_price.go
  scripts/run-server-test
Labels: Mountain Movers, INTEGRATION

#12735 B-20043
  pkg/handlers/ghcapi/move.go
  pkg/handlers/ghcapi/move_test.go
Labels: G-Unit, MAIN

#12982 MAIN - B-19065 fix-current-bug-delete-docs
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalapi/internaloperations/uploads/delete_upload_parameters.go
  pkg/gen/internalapi/internaloperations/uploads/delete_upload_urlbuilder.go
  pkg/handlers/internalapi/uploads.go
  src/pages/MyMove/PPM/Closeout/Expenses/Expenses.jsx
  src/pages/MyMove/PPM/Closeout/ProGear/ProGear.jsx
  src/pages/MyMove/PPM/Closeout/WeightTickets/WeightTickets.jsx
  src/services/internalApi.js
  swagger-def/internal.yaml
  swagger/internal.yaml
Labels: ByteSize M&Ms, MAIN

#13011 B 19825 rename qaecsr to qae main
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240530084720_rename_qae_csr_to_just_qae.up.sql
  pkg/factory/role_factory.go
  pkg/factory/role_factory_test.go
  pkg/handlers/adminapi/office_users_test.go
  pkg/handlers/adminapi/requested_office_users_test.go
  pkg/handlers/authentication/auth_test.go
  pkg/handlers/authentication/devlocal.go
  pkg/handlers/authentication/devlocal_test.go
  pkg/handlers/authentication/permissions.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/handlers/ghcapi/office_users_test.go
  pkg/models/roles/roles.go
  pkg/services/evaluation_report/evaluation_report_fetcher_test.go
  pkg/services/move/move_searcher_test.go
  pkg/services/query/query_builder_test.go
  pkg/testdatagen/scenario/e2ebasic.go
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/scenario/subscenarios.go
  playwright/tests/office/qaecsr/csrFlows.spec.js
  playwright/tests/office/qaecsr/moveSearchFlows.spec.js
  playwright/tests/office/qaecsr/qaeFlows.spec.js
  playwright/tests/office/txo/tooFlows.spec.js
  playwright/tests/utils/office/officeTest.js
  src/components/Office/CustomerSupportRemarkForm/CustomerSupportRemarkForm.test.jsx
  src/components/Office/EvaluationForm/EvaluationForm.test.jsx
  src/components/Office/EvaluationReportPreview/EvaluationReportPreview.test.jsx
  src/components/Office/QAEViolationsForm/QAEViolationsForm.stories.jsx
  src/components/Office/QAEViolationsForm/QAEViolationsForm.test.jsx
  src/components/Office/RequestAccountForm/RequestAccountForm.test.jsx
  src/components/form/OfficeAccountRequestFields/OfficeAccountRequestFields.jsx
  src/components/form/OfficeAccountRequestFields/OfficeAccountRequestFields.test.jsx
  src/constants/queryKeys.js
  src/constants/queues.js
  src/constants/routes.js
  src/constants/userRoles.js
  src/hooks/queries.js
  src/pages/Office/EvaluationViolations/EvaluationViolations.test.jsx
  src/pages/Office/RequestAccount/RequestAccount.jsx
  src/pages/Office/RequestAccount/RequestAccount.test.jsx
  src/pages/Office/index.jsx
  src/pages/Office/index.test.jsx
  src/pages/SelectApplication/SelectApplication.jsx
  src/pages/SelectApplication/SelectApplication.test.jsx
  src/utils/validation.js
Labels: Mountain Movers, MAIN

#12953 INT-B-20198
  pkg/edi/invoice/generator.go
  pkg/edi/invoice/generator_test.go
  pkg/services/invoice/ghc_payment_request_invoice_generator.go
  pkg/services/invoice/ghc_payment_request_invoice_generator_test.go
Labels: G-Unit, INTEGRATION

#13014 INT- B-19713-UI-Address-PPM-Shipment-Card
  go.mod
  go.sum
  migrations/app/migrations_manifest.txt
  src/components/PPMSummaryList/PPMSummaryList.stories.jsx
  yarn.lock
Labels: Scrummy Bears, INTEGRATION

#13002 MAIN- B-19713-UI-Address-PPM-Shipment-Card
  src/components/PPMSummaryList/PPMSummaryList.jsx
  src/components/PPMSummaryList/PPMSummaryList.module.scss
  src/components/PPMSummaryList/PPMSummaryList.stories.jsx
  src/components/PPMSummaryList/PPMSummaryList.test.jsx
  src/pages/MyMove/Home/MoveHome.test.jsx
  src/pages/MyMove/Home/index.test.jsx
  src/utils/test/factories/ppmShipment.js
Labels: Scrummy Bears, MAIN

#12732 B-18545 safety queue and labels
  pkg/services/move/move_searcher.go
  pkg/services/office_user/customer/customer_searcher.go
  pkg/services/office_user/customer/customer_searcher_test.go
  pkg/services/order/order_fetcher.go
  pkg/services/order/order_fetcher_test.go
  pkg/services/payment_request/payment_request_list_fetcher.go
  pkg/services/payment_request/payment_request_list_fetcher_test.go
  pkg/services/users_privileges/users_privileges_test.go
  src/constants/orders.js
Labels: G-Unit, MAIN

#13024 B 19895 tio queue payment requested main
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/queues.go
  pkg/models/payment_request.go
  playwright/tests/office/txo/tioFlows.spec.js
  src/constants/queues.js
  src/pages/Office/PaymentRequestQueue/PaymentRequestQueue.jsx
  src/pages/Office/PaymentRequestQueue/PaymentRequestQueue.test.jsx
Labels: Mountain Movers, MAIN

#12734 B 19918 do not send safety emails
  pkg/handlers/ghcapi/move_task_order.go
  pkg/handlers/ghcapi/mto_shipment.go
  pkg/handlers/ghcapi/ppm_document.go
  pkg/handlers/internalapi/moves.go
  pkg/handlers/internalapi/office.go
  pkg/handlers/primeapi/move_task_order.go
  pkg/models/order.go
  pkg/services/mto_shipment/mto_shipment_updater.go
Labels: G-Unit, MAIN

#12939 B-19728-INT customer upload additional docs
  .circleci/config.yml
  .envrc
  config/env/demo.app-client-tls.env
  config/env/demo.app.env
  config/env/exp.app-client-tls.env
  config/env/exp.app.env
  config/env/loadtest.app-client-tls.env
  config/env/loadtest.app.env
  config/env/prd.app-client-tls.env
  config/env/prd.app.env
  config/env/stg.app-client-tls.env
  config/env/stg.app.env
  config/flipt/storage/development.features.yaml
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240529181303_add_additional_documents_id_col_to_moves.up.sql
  pkg/factory/shared.go
  pkg/gen/internalapi/configure_mymove.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalapi/internaloperations/moves/upload_additional_documents.go
  pkg/gen/internalapi/internaloperations/moves/upload_additional_documents_parameters.go
  pkg/gen/internalapi/internaloperations/moves/upload_additional_documents_responses.go
  pkg/gen/internalapi/internaloperations/moves/upload_additional_documents_urlbuilder.go
  pkg/gen/internalapi/internaloperations/mymove_api.go
  pkg/gen/internalapi/internaloperations/uploads/delete_upload_parameters.go
  pkg/gen/internalapi/internaloperations/uploads/delete_upload_urlbuilder.go
  pkg/gen/internalmessages/move_payload.go
  pkg/handlers/internalapi/api.go
  pkg/handlers/internalapi/moves.go
  pkg/handlers/internalapi/moves_test.go
  pkg/handlers/internalapi/uploads.go
  pkg/models/move.go
  pkg/services/move.go
  pkg/services/move/additional_documents_uploader.go
  pkg/services/move/additional_documents_uploader_test.go
  pkg/services/order/order_updater.go
  src/constants/routes.js
  src/pages/MyMove/AdditionalDocuments/AdditionalDocuments.jsx
  src/pages/MyMove/AdditionalDocuments/AdditionalDocuments.test.jsx
  src/pages/MyMove/Home/MoveHome.jsx
  src/scenes/MyMove/index.jsx
  src/services/internalApi.js
  swagger-def/definitions/AdditionalDocuments.yaml
  swagger-def/internal.yaml
  swagger/internal.yaml
Labels: G-Unit, INTEGRATION

#12957 B:19826 - Rename Transportation Ordering Officer to Task Ordering Officer(READY)
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240603152949_update_too_role_name.up.sql
  pkg/factory/role_factory.go
  pkg/factory/role_factory_test.go
  pkg/gen/adminapi/embedded_spec.go
  pkg/gen/adminmessages/office_user_role.go
  pkg/gen/adminmessages/role.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/office_user_role.go
  pkg/gen/ghcmessages/role.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/m_t_o_shipment_without_service_items.go
  pkg/gen/primev2api/embedded_spec.go
  pkg/gen/primev2messages/m_t_o_shipment_without_service_items.go
  pkg/gen/primev3api/embedded_spec.go
  pkg/gen/primev3messages/m_t_o_shipment_without_service_items.go
  pkg/handlers/adminapi/office_users_test.go
  pkg/handlers/adminapi/requested_office_users_test.go
  pkg/handlers/authentication/devlocal.go
  pkg/handlers/ghcapi/office_users_test.go
  pkg/models/privileges.go
  pkg/models/roles/roles.go
  pkg/services/users_roles/users_roles.go
  playwright/tests/admin/officeUsers.spec.js
  playwright/tests/office/homepage.spec.js
  playwright/tests/office/txo/tooFlows.spec.js
  playwright/tests/utils/office/officeTest.js
  src/components/Office/RequestAccountForm/RequestAccountForm.test.jsx
  src/components/form/OfficeAccountRequestFields/OfficeAccountRequestFields.jsx
  src/components/form/OfficeAccountRequestFields/OfficeAccountRequestFields.test.jsx
  src/constants/userRoles.js
  src/pages/Admin/OfficeUsers/OfficeUserCreate.jsx
  src/pages/Admin/OfficeUsers/OfficeUserEdit.jsx
  src/pages/Admin/RequestedOfficeUsers/RequestedOfficeUserEdit.jsx
  src/pages/Office/RequestAccount/RequestAccount.jsx
  src/pages/Office/RequestAccount/RequestAccount.test.jsx
  src/utils/validation.js
  swagger-def/admin.yaml
  swagger-def/definitions/prime/MTOShipmentWithoutServiceItems.yaml
  swagger-def/definitions/prime/v2/MTOShipmentWithoutServiceItems.yaml
  swagger-def/definitions/prime/v3/MTOShipmentWithoutServiceItems.yaml
  swagger-def/ghc.yaml
  swagger/admin.yaml
  swagger/ghc.yaml
  swagger/prime.yaml
  swagger/prime_v2.yaml
  swagger/prime_v3.yaml
Labels: Mountain Movers, MAIN

#13003 B 19890 expand tac lookup int
  cmd/generate-payment-request-edi/main.go
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/lines_of_accounting/request_line_of_accounting.go
  pkg/gen/ghcapi/ghcoperations/lines_of_accounting/request_line_of_accounting_parameters.go
  pkg/gen/ghcapi/ghcoperations/lines_of_accounting/request_line_of_accounting_responses.go
  pkg/gen/ghcapi/ghcoperations/lines_of_accounting/request_line_of_accounting_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/ghcmessages/fetch_line_of_accounting_payload.go
  pkg/gen/ghcmessages/line_of_accounting.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/lines_of_accounting.go
  pkg/handlers/ghcapi/lines_of_accounting_test.go
  pkg/handlers/supportapi/api.go
  pkg/handlers/supportapi/payment_request_test.go
  pkg/services/invoice/ghc_payment_request_invoice_generator.go
  pkg/services/invoice/ghc_payment_request_invoice_generator_test.go
  pkg/services/line_of_accounting.go
  pkg/services/line_of_accounting/line_of_accounting_fetcher.go
  pkg/services/line_of_accounting/line_of_accounting_fetcher_test.go
  pkg/services/mocks/LineOfAccountingFetcher.go
  pkg/services/mocks/TransportationAccountingCodeFetcher.go
  pkg/services/payment_request/payment_request_reviewed_processor.go
  pkg/services/payment_request/payment_request_reviewed_processor_test.go
  pkg/services/transportation_accounting_code.go
  pkg/services/transportation_accounting_code/transportation_accounting_code_fetcher.go
  pkg/services/transportation_accounting_code/transportation_accounting_code_fetcher_test.go
  swagger-def/definitions/LineOfAccounting.yaml
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: Mountain Movers, INTEGRATION

#13039 B-20107: Refactor Backup Info Panel
  src/scenes/Office/BackupInfoPanel.jsx
  src/shared/Entities/modules/serviceMembers.js
Labels: Mountain Movers, INTEGRATION

#13038 MAIN B-20070 PPM Instructions
  src/components/Customer/PPM/Booking/DateAndLocationForm/DateAndLocationForm.jsx
Labels: Scrummy Bears, MAIN

#13037 INT B-20110 refactor CustomerInfoPanel to use Formik
  src/scenes/Office/CustomerInfoPanel.jsx
Labels: Mountain Movers, INTEGRATION

#13041 INT B-20108 refactor SignatureForm to use Formik
  src/scenes/Legalese/SignatureForm.css
  src/scenes/Legalese/SignatureForm.jsx
Labels: Mountain Movers, INTEGRATION

#13005 B 19894 too queue moves int
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/queues/get_moves_queue_parameters.go
  pkg/handlers/ghcapi/queues.go
  pkg/handlers/ghcapi/queues_test.go
  pkg/services/move/move_searcher.go
  pkg/services/order/order_fetcher.go
  pkg/services/order/order_fetcher_test.go
  pkg/testdatagen/testharness/make_move.go
  playwright/tests/office/txo/tooFlows.spec.js
  playwright/tests/office/txo/tooFlowsNTS.spec.js
  playwright/tests/office/txo/tooFlowsNTSR.spec.js
  src/constants/queues.js
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: Mountain Movers, INTEGRATION

#13046 INT B-20111 refactor OrdersPanel to use Formik
  src/scenes/Office/OrdersPanel.jsx
  src/shared/Entities/modules/moves.js
  src/utils/featureFlags.js
Labels: Mountain Movers, INTEGRATION

#13045 INT. B-20109 refactor DocumentUploader to use Formik
  src/shared/DocumentViewer/DocumentUploader.css
  src/shared/DocumentViewer/DocumentUploader.jsx
Labels: Mountain Movers, INTEGRATION

#13044 INT B-20104 refactor WizardFormPage to use Formik
  src/shared/WizardPage/Form.jsx
Labels: Mountain Movers, INTEGRATION

#13042 INT B-20106 refactor AccountingPanel to use Formik
  src/scenes/Office/AccountingPanel.jsx
Labels: Mountain Movers, INTEGRATION

#13015 INT B-17272, B-19828, B-19829 backend okta response check customer app
  pkg/handlers/authentication/auth.go
  pkg/handlers/authentication/auth_test.go
  scripts/run-server-test
  src/components/OktaErrorBanner/OktaErrorBanner.jsx
  src/components/OktaErrorBanner/OktaErrorBanner.module.scss
  src/components/OktaErrorBanner/OktaErrorBanner.stories.jsx
  src/components/OktaErrorBanner/OktaErrorBanner.test.jsx
  src/pages/Office/index.jsx
  src/scenes/MyMove/index.jsx
  src/scenes/MyMove/index.test.js
Labels: Mountain Movers, INTEGRATION

#13043 B 19925 sorting branch param to uppercase
  pkg/services/move/move_searcher.go
  pkg/services/order/order_fetcher.go
  pkg/services/payment_request/payment_request_list_fetcher.go
Labels: Mountain Movers, MAIN

#13047 INT B-20112 refactor OrdersViewerPanel to use Formik
  src/scenes/Office/OrdersInfo.jsx
  src/scenes/Office/OrdersViewerPanel.js
  src/store/entities/selectors.js
Labels: Mountain Movers, INTEGRATION

#13034 B 19845 UI weight stored
  playwright/tests/my/milmove/ppms/customerPpmTestFixture.js
  playwright/tests/my/milmove/ppms/expenses.spec.js
  src/components/Customer/PPM/Closeout/ExpenseForm/ExpenseForm.jsx
  src/components/Customer/PPM/Closeout/ExpenseForm/ExpenseForm.test.jsx
  src/pages/MyMove/PPM/Closeout/Expenses/Expenses.jsx
  src/pages/MyMove/PPM/Closeout/Expenses/Expenses.test.jsx
  src/types/shipment.js
Labels: Scrummy Bears, MAIN

#13036 MAIN B-19866 Hide Diversion Link for PPMs
  src/components/Office/ShipmentAddresses/ShipmentAddresses.jsx
  src/components/Office/ShipmentAddresses/ShipmentAddresses.test.jsx
Labels: Scrummy Bears, MAIN

#13050 B 19894 too queue moves main
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/queues/get_moves_queue_parameters.go
  pkg/handlers/ghcapi/queues.go
  pkg/handlers/ghcapi/queues_test.go
  pkg/services/move/move_searcher.go
  pkg/services/order/order_fetcher.go
  pkg/services/order/order_fetcher_test.go
  pkg/testdatagen/testharness/make_move.go
  playwright/tests/office/txo/tooFlows.spec.js
  playwright/tests/office/txo/tooFlowsNTS.spec.js
  playwright/tests/office/txo/tooFlowsNTSR.spec.js
  src/constants/queues.js
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: Mountain Movers, MAIN

#13049 B-20108: Refactor Address Form
  src/shared/Address/index.jsx
  src/shared/Address/index.module.scss
  src/shared/Address/index.test.js
Labels: Mountain Movers, INTEGRATION

#13052 MAIN B-20110 refactor CustomerInfoPanel to use Formik
  src/scenes/Office/CustomerInfoPanel.jsx
Labels: Mountain Movers, MAIN

#13051 MAIN B-17272, B-19828, B-19829 backend okta response check customer app
  pkg/handlers/authentication/auth.go
  pkg/handlers/authentication/auth_test.go
  scripts/run-server-test
  src/components/OktaErrorBanner/OktaErrorBanner.jsx
  src/components/OktaErrorBanner/OktaErrorBanner.module.scss
  src/components/OktaErrorBanner/OktaErrorBanner.stories.jsx
  src/components/OktaErrorBanner/OktaErrorBanner.test.jsx
  src/pages/Office/index.jsx
  src/scenes/MyMove/index.jsx
  src/scenes/MyMove/index.test.js
Labels: Mountain Movers, MAIN

#12984 B 20010 int Add FF for HQ role
  .circleci/config.yml
  .envrc
  config/env/demo.app-client-tls.env
  config/env/demo.app.env
  config/env/exp.app-client-tls.env
  config/env/exp.app.env
  config/env/loadtest.app-client-tls.env
  config/env/loadtest.app.env
  config/env/prd.app-client-tls.env
  config/env/prd.app.env
  config/env/stg.app-client-tls.env
  config/env/stg.app.env
  config/flipt/storage/development.features.yaml
  pkg/handlers/authentication/devlocal.go
  pkg/handlers/authentication/permissions.go
  src/components/Office/RequestAccountForm/RequestAccountForm.test.jsx
  src/components/form/OfficeAccountRequestFields/OfficeAccountRequestFields.jsx
  src/constants/userRoles.js
  src/pages/Office/RequestAccount/RequestAccount.jsx
  src/scenes/SystemAdmin/shared/RolesPrivilegesCheckboxes.jsx
Labels: Scrummy Bears, INTEGRATION

#13040 MAIN B-19979 diversion reason for prime
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/m_t_o_shipment_without_service_items.go
  pkg/gen/primev2api/embedded_spec.go
  pkg/gen/primev2messages/m_t_o_shipment_without_service_items.go
  pkg/gen/primev3api/embedded_spec.go
  pkg/gen/primev3messages/m_t_o_shipment_without_service_items.go
  pkg/handlers/primeapi/payloads/model_to_payload.go
  pkg/handlers/primeapiv2/payloads/model_to_payload.go
  pkg/handlers/primeapiv3/payloads/model_to_payload.go
  src/components/PrimeUI/Shipment/Shipment.jsx
  src/components/PrimeUI/Shipment/Shipment.test.jsx
  swagger-def/definitions/prime/MTOShipmentWithoutServiceItems.yaml
  swagger-def/definitions/prime/v2/MTOShipmentWithoutServiceItems.yaml
  swagger-def/definitions/prime/v3/MTOShipmentWithoutServiceItems.yaml
  swagger/prime.yaml
  swagger/prime_v2.yaml
  swagger/prime_v3.yaml
Labels: Scrummy Bears, MAIN

#13022 B 20211 int remove coast guard ff
  .circleci/config.yml
  .envrc
  config/env/demo.app-client-tls.env
  config/env/demo.app.env
  config/env/exp.app-client-tls.env
  config/env/exp.app.env
  config/env/loadtest.app-client-tls.env
  config/env/loadtest.app.env
  config/env/prd.app-client-tls.env
  config/env/prd.app.env
  config/env/stg.app-client-tls.env
  config/env/stg.app.env
  config/flipt/storage/development.features.yaml
  migrations/app/migrations_manifest.txt
  migrations/app/secure/20240611185048_drop_unique_constraint_emplid.up.sql
  src/components/Customer/DodInfoForm/DodInfoForm.jsx
  src/components/Customer/DodInfoForm/DodInfoForm.stories.jsx
  src/components/Customer/DodInfoForm/DodInfoForm.test.jsx
  src/components/Customer/Review/ServiceInfoDisplay/ServiceInfoDisplay.jsx
  src/components/Customer/Review/ServiceInfoDisplay/ServiceInfoDisplay.stories.jsx
  src/components/Customer/Review/ServiceInfoDisplay/ServiceInfoDisplay.test.jsx
  src/components/Customer/ServiceInfoForm/ServiceInfoForm.jsx
  src/components/Customer/ServiceInfoForm/ServiceInfoForm.stories.jsx
  src/components/Customer/ServiceInfoForm/ServiceInfoForm.test.jsx
  src/pages/MyMove/Profile/DodInfo.jsx
  src/pages/MyMove/Profile/EditServiceInfo.jsx
  src/pages/MyMove/Profile/Profile.jsx
Labels: G-Unit, INTEGRATION

#13061 INT I-13010 server_test flaky test fix
  pkg/services/office_user/customer/customer_searcher_test.go
Labels: Mountain Movers, INTEGRATION

#13063 MAIN I-13010 server_test flaky test fix
  pkg/services/office_user/customer/customer_searcher_test.go
Labels: Mountain Movers, MAIN

#12988 19782 shipment cancellation date validation be main
  pkg/handlers/ghcapi/mto_shipment.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/services/mto_shipment/shipment_cancellation_requester.go
  pkg/services/mto_shipment/shipment_cancellation_requester_test.go
  pkg/testdatagen/testharness/make_move.go
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
Labels: ByteSize M&Ms, MAIN

#13067 B-20204 Formatter fixed
  src/components/Office/ServiceItemCalculations/helpers.js
Labels: Scrummy Bears, MAIN

#13064 MAIN B-20109, B-20111, and B-20112 refactor DocumentUploader, OrdersPanel and OrdersViewer
  src/scenes/Office/OrdersInfo.jsx
  src/scenes/Office/OrdersPanel.jsx
  src/scenes/Office/OrdersViewerPanel.js
  src/shared/DocumentViewer/DocumentUploader.css
  src/shared/DocumentViewer/DocumentUploader.jsx
  src/shared/Entities/modules/moves.js
  src/store/entities/selectors.js
  src/utils/featureFlags.js
Labels: Mountain Movers, MAIN

#13068 INT I-13010 server test flaky test round two
  pkg/services/office_user/customer/customer_searcher.go
  pkg/services/office_user/customer/customer_searcher_test.go
  src/pages/Office/ServicesCounselingEditShipmentDetails/ServicesCounselingEditShipmentDetails.test.jsx
Labels: Mountain Movers, INTEGRATION

#13019 B-19763 I-12974 mileage does not updated to correspond with zip code when destination address is updated
  pkg/payment_request/service_param_value_lookups/distance_zip_lookup.go
  pkg/payment_request/service_param_value_lookups/distance_zip_lookup_test.go
  pkg/payment_request/service_param_value_lookups/eia_fuel_price_lookup.go
  pkg/payment_request/service_param_value_lookups/eia_fuel_price_lookup_test.go
  pkg/payment_request/service_param_value_lookups/service_param_value_lookups.go
  pkg/payment_request/service_param_value_lookups/service_param_value_lookups_test.go
  pkg/services/payment_request/payment_request_creator.go
  pkg/services/payment_request/payment_request_creator_test.go
  pkg/services/ppm_closeout/ppm_closeout.go
  pkg/services/ppmshipment/aoa_packet_creator_test.go
  pkg/services/ppmshipment/ppm_estimator.go
  pkg/services/ppmshipment/ppm_estimator_test.go
  pkg/testdatagen/scenario/subscenarios.go
  src/components/Customer/PPM/Booking/DateAndLocationForm/DateAndLocationForm.test.jsx
  src/pages/Office/ServicesCounselingEditShipmentDetails/ServicesCounselingEditShipmentDetails.test.jsx
Labels: ByteSize M&Ms, INTEGRATION

#13073 MAIN I-13010 server test flaky test round two
  pkg/services/office_user/customer/customer_searcher.go
  pkg/services/office_user/customer/customer_searcher_test.go
  src/pages/Office/ServicesCounselingEditShipmentDetails/ServicesCounselingEditShipmentDetails.test.jsx
Labels: Mountain Movers, MAIN

#13072 MAIN-B-19230-SIT-PPM
  src/components/Office/ShipmentCustomerSIT/ShipmentCustomerSIT.jsx
  src/components/Office/ShipmentForm/ShipmentForm.jsx
  src/components/Office/ShipmentForm/ppmShipmentSchema.js
  src/pages/Office/ServicesCounselingEditShipmentDetails/ServicesCounselingEditShipmentDetails.test.jsx
Labels: Scrummy Bears, MAIN

#13069 B-19975-KB-INT
  src/pages/MyMove/PPM/Closeout/Feedback/Feedback.jsx
Labels: G-Unit, INTEGRATION

#13071 B 19926 loa lookup UI int
  pkg/handlers/ghcapi/lines_of_accounting.go
  pkg/handlers/ghcapi/lines_of_accounting_test.go
  src/components/Office/OrdersDetailForm/OrdersDetailForm.jsx
  src/components/Office/OrdersDetailForm/OrdersDetailForm.stories.jsx
  src/components/Office/OrdersDetailForm/OrdersDetailForm.test.jsx
  src/pages/Office/Orders/Orders.jsx
  src/pages/Office/Orders/Orders.test.jsx
  src/pages/Office/ServicesCounselingOrders/ServicesCounselingOrders.jsx
  src/pages/Office/ServicesCounselingOrders/ServicesCounselingOrders.test.jsx
  src/reducers/loaValidation.js
  src/reducers/loaValidation.test.js
  src/services/ghcApi.js
  src/types/lineOfAccounting.js
Labels: Mountain Movers, INTEGRATION

#13048 Int b 19980
  pkg/services/ppm_closeout/ppm_closeout.go
Labels: ByteSize M&Ms, INTEGRATION

#13070 B-19891 TAC LOA Invalid DB INT
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240613192433_move_valid_loa_for_tac_col_to_lines_of_accounting_table.up.sql
  package.json
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/line_of_accounting.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/models/line_of_accounting.go
  pkg/payment_request/service_param_value_lookups/eia_fuel_price_lookup.go
  pkg/payment_request/service_param_value_lookups/eia_fuel_price_lookup_test.go
  pkg/payment_request/service_param_value_lookups/service_param_value_lookups.go
  pkg/services/line_of_accounting/line_of_accounting_fetcher.go
  pkg/services/line_of_accounting/line_of_accounting_fetcher_test.go
  swagger-def/definitions/LineOfAccounting.yaml
  swagger/ghc.yaml
  yarn.lock
Labels: Mountain Movers, INTEGRATION

#13076 B-19763 fixed logic to the code that was changed works
  pkg/payment_request/service_param_value_lookups/distance_zip_lookup.go
Labels: ByteSize M&Ms, INTEGRATION

#13023 B 20211 remove coast guard ff
  .circleci/config.yml
  .envrc
  config/env/demo.app-client-tls.env
  config/env/demo.app.env
  config/env/exp.app-client-tls.env
  config/env/exp.app.env
  config/env/loadtest.app-client-tls.env
  config/env/loadtest.app.env
  config/env/prd.app-client-tls.env
  config/env/prd.app.env
  config/env/stg.app-client-tls.env
  config/env/stg.app.env
  config/flipt/storage/development.features.yaml
  migrations/app/migrations_manifest.txt
  migrations/app/secure/20240611185048_drop_unique_constraint_emplid.up.sql
  src/components/Customer/DodInfoForm/DodInfoForm.jsx
  src/components/Customer/DodInfoForm/DodInfoForm.stories.jsx
  src/components/Customer/DodInfoForm/DodInfoForm.test.jsx
  src/components/Customer/Review/ServiceInfoDisplay/ServiceInfoDisplay.jsx
  src/components/Customer/Review/ServiceInfoDisplay/ServiceInfoDisplay.stories.jsx
  src/components/Customer/Review/ServiceInfoDisplay/ServiceInfoDisplay.test.jsx
  src/components/Customer/ServiceInfoForm/ServiceInfoForm.jsx
  src/components/Customer/ServiceInfoForm/ServiceInfoForm.stories.jsx
  src/components/Customer/ServiceInfoForm/ServiceInfoForm.test.jsx
  src/pages/MyMove/Profile/DodInfo.jsx
  src/pages/MyMove/Profile/EditServiceInfo.jsx
  src/pages/MyMove/Profile/Profile.jsx
Labels: G-Unit, MAIN

#13079 B 19890 expand tac lookup main
  cmd/generate-payment-request-edi/main.go
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/lines_of_accounting/request_line_of_accounting.go
  pkg/gen/ghcapi/ghcoperations/lines_of_accounting/request_line_of_accounting_parameters.go
  pkg/gen/ghcapi/ghcoperations/lines_of_accounting/request_line_of_accounting_responses.go
  pkg/gen/ghcapi/ghcoperations/lines_of_accounting/request_line_of_accounting_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/ghcmessages/fetch_line_of_accounting_payload.go
  pkg/gen/ghcmessages/line_of_accounting.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/lines_of_accounting.go
  pkg/handlers/ghcapi/lines_of_accounting_test.go
  pkg/handlers/supportapi/api.go
  pkg/handlers/supportapi/payment_request_test.go
  pkg/services/invoice/ghc_payment_request_invoice_generator.go
  pkg/services/invoice/ghc_payment_request_invoice_generator_test.go
  pkg/services/line_of_accounting.go
  pkg/services/line_of_accounting/line_of_accounting_fetcher.go
  pkg/services/line_of_accounting/line_of_accounting_fetcher_test.go
  pkg/services/mocks/LineOfAccountingFetcher.go
  pkg/services/mocks/TransportationAccountingCodeFetcher.go
  pkg/services/payment_request/payment_request_reviewed_processor.go
  pkg/services/payment_request/payment_request_reviewed_processor_test.go
  pkg/services/transportation_accounting_code.go
  pkg/services/transportation_accounting_code/transportation_accounting_code_fetcher.go
  pkg/services/transportation_accounting_code/transportation_accounting_code_fetcher_test.go
  swagger-def/definitions/LineOfAccounting.yaml
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: Mountain Movers, MAIN

#13086 B-19926 split hhg and nts loas
  src/components/Office/OrdersDetailForm/OrdersDetailForm.jsx
  src/components/Office/OrdersDetailForm/OrdersDetailForm.stories.jsx
  src/components/Office/OrdersDetailForm/OrdersDetailForm.test.jsx
  src/pages/Office/Orders/Orders.jsx
  src/pages/Office/Orders/Orders.test.jsx
  src/pages/Office/ServicesCounselingOrders/ServicesCounselingOrders.jsx
  src/pages/Office/ServicesCounselingOrders/ServicesCounselingOrders.test.jsx
Labels: enhancement, Mountain Movers, INTEGRATION

#13054 INT B-20080 Incorrect GBLOC in Search Results
  pkg/services/move/move_searcher.go
Labels: Scrummy Bears, INTEGRATION

#13082 B-19891 TAC LOA Invalid DB MAIN
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240613192433_move_valid_loa_for_tac_col_to_lines_of_accounting_table.up.sql
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/line_of_accounting.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/lines_of_accounting.go
  pkg/handlers/ghcapi/lines_of_accounting_test.go
  pkg/models/line_of_accounting.go
  pkg/services/line_of_accounting/line_of_accounting_fetcher.go
  pkg/services/line_of_accounting/line_of_accounting_fetcher_test.go
  swagger-def/definitions/LineOfAccounting.yaml
  swagger/ghc.yaml
Labels: Mountain Movers, MAIN

#13053 INT - B-19776 & B-19778 Add-status-filter-closeout
  pkg/factory/ppm_shipment_factory.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/queues/get_services_counseling_queue_parameters.go
  pkg/gen/ghcapi/ghcoperations/queues/get_services_counseling_queue_urlbuilder.go
  pkg/gen/ghcmessages/p_p_m_status.go
  pkg/gen/ghcmessages/queue_move.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/queues.go
  pkg/services/order.go
  pkg/services/order/order_fetcher.go
  pkg/services/order/order_fetcher_test.go
  playwright/tests/office/servicescounseling/servicesCounselingQueueFilters.spec.js
  src/constants/queues.js
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.jsx
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.test.jsx
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: ByteSize M&Ms, INTEGRATION

#13087 B-19975-MAIN Customer feedback
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/moving_expense.go
  pkg/gen/ghcmessages/pro_gear_weight_ticket.go
  pkg/gen/ghcmessages/submitted_moving_expense_type.go
  pkg/gen/ghcmessages/weight_ticket.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/moving_expense.go
  pkg/gen/internalmessages/pro_gear_weight_ticket.go
  pkg/gen/internalmessages/submitted_moving_expense_type.go
  pkg/gen/internalmessages/weight_ticket.go
  pkg/handlers/internalapi/internal/payloads/model_to_payload.go
  src/components/Customer/PPM/Closeout/FeedbackItems/FeedbackItems.jsx
  src/components/Customer/PPM/Closeout/FeedbackItems/FeedbackItems.module.scss
  src/components/Customer/PPM/Closeout/FeedbackItems/FeedbackItems.test.jsx
  src/components/PPMSummaryList/PPMSummaryList.jsx
  src/components/PPMSummaryList/PPMSummaryList.module.scss
  src/constants/ppmFeedback.js
  src/constants/routes.js
  src/pages/MyMove/Home/MoveHome.jsx
  src/pages/MyMove/PPM/Closeout/Feedback/Feedback.jsx
  src/pages/MyMove/PPM/Closeout/Feedback/Feedback.module.scss
  src/pages/MyMove/PPM/Closeout/Feedback/Feedback.test.jsx
  src/scenes/MyMove/index.jsx
  src/utils/ppmCloseout.jsx
  swagger-def/definitions/MovingExpense.yaml
  swagger-def/definitions/ProGearWeightTicket.yaml
  swagger-def/definitions/SubmittedMovingExpenseType.yaml
  swagger-def/definitions/WeightTicket.yaml
  swagger/ghc.yaml
  swagger/internal.yaml
Labels: G-Unit, MAIN

#13027 INT B-20011 B-20013 B-20014 HQ Role Queues, Searching, and Permissions
  pkg/gen/ghcapi/embedded_spec.go
  pkg/handlers/authentication/devlocal.go
  pkg/handlers/authentication/permissions.go
  pkg/handlers/ghcapi/customer.go
  pkg/handlers/ghcapi/queues.go
  pkg/services/office_user/customer/customer_searcher.go
  pkg/services/office_user/customer/customer_searcher_test.go
  src/components/MoveSearchForm/MoveSearchForm.jsx
  src/components/Table/SearchResultsTable.jsx
  src/constants/routes.js
  src/pages/Office/HeadquartersQueues/HeadquartersQueues.jsx
  src/pages/Office/HeadquartersQueues/HeadquartersQueues.module.scss
  src/pages/Office/HeadquartersQueues/HeadquartersQueues.test.jsx
  src/pages/Office/index.jsx
  src/pages/Office/index.test.jsx
  src/utils/validation.js
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: Scrummy Bears, INTEGRATION

#13088 removed comments to sync with main
  playwright/tests/my/milmove/ppms/dateAndLocation.spec.js
  src/components/Customer/PPM/Booking/DateAndLocationForm/DateAndLocationForm.jsx
Labels: ByteSize M&Ms, INTEGRATION

#13084 B19551 PPM closeout field
  pkg/testdatagen/scenario/subscenarios.go
  playwright/tests/my/milmove/ppms/customerPpmTestFixture.js
  playwright/tests/my/milmove/ppms/dateAndLocation.spec.js
  playwright/tests/office/primesimulator/primeSimulatorFlows.spec.js
  src/components/Customer/PPM/Booking/DateAndLocationForm/DateAndLocationForm.jsx
  src/components/Customer/PPM/Booking/DateAndLocationForm/DateAndLocationForm.test.jsx
  src/components/LocationSearchBox/LocationSearchBox.jsx
  src/components/Office/RequestedShipments/SubmittedRequestedShipments.jsx
  src/components/Office/ShipmentCustomerSIT/ShipmentCustomerSIT.test.jsx
  src/components/Office/ShipmentForm/ShipmentForm.test.jsx
  src/components/form/fields/DutyLocationInput.jsx
  src/pages/MyMove/PPM/Booking/DateAndLocation/DateAndLocation.test.jsx
  src/pages/Office/ServicesCounselingEditShipmentDetails/ServicesCounselingEditShipmentDetails.test.jsx
Labels: ByteSize M&Ms, MAIN

#13098 MAIN B-20104, B-20105, B-20106 remove Form/WizardForm, SignatureForm, and AccountingPanel
  src/pages/Office/ServicesCounselingEditShipmentDetails/ServicesCounselingEditShipmentDetails.test.jsx
  src/scenes/Legalese/SignatureForm.css
  src/scenes/Legalese/SignatureForm.jsx
  src/scenes/Office/AccountingPanel.jsx
  src/shared/WizardPage/Form.jsx
Labels: Mountain Movers, MAIN

#13081 B-20108: Refactor Address Form
  src/scenes/Office/BackupInfoPanel.jsx
  src/shared/Address/index.jsx
  src/shared/Address/index.module.scss
  src/shared/Address/index.test.js
Labels: Mountain Movers, MAIN

#13033 B 19941 int
  pkg/testdatagen/testharness/dispatch.go
  pkg/testdatagen/testharness/make_move.go
  playwright/tests/office/txo/tooFlows.spec.js
  playwright/tests/utils/testharness.js
  src/components/Office/ImportantShipmentDates/ImportantShipmentDates.jsx
  src/components/Office/ImportantShipmentDates/ImportantShipmentDates.test.jsx
  src/components/Office/RequestShipmentDiversionModal/RequestShipmentDiversionModal.jsx
  src/components/Office/RequestShipmentDiversionModal/RequestShipmentDiversionModal.test.jsx
  src/components/Office/ShipmentDetails/ShipmentDetailsMain.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
  src/utils/validation.js
Labels: Scrummy Bears, INTEGRATION

#13106 B-20011/13/14 INT Feature Flag Capitalization Fix
  src/pages/Office/index.jsx
Labels: Scrummy Bears, INTEGRATION

#13103 B 20250 incorrect gbloc prime int
  go.mod
  go.sum
  package.json
  pkg/handlers/primeapi/payloads/model_to_payload.go
  pkg/handlers/primeapiv2/payloads/model_to_payload.go
  pkg/handlers/primeapiv3/payloads/model_to_payload.go
  pkg/testdatagen/scenario/subscenarios.go
  yarn.lock
Labels: ByteSize M&Ms, INTEGRATION

#13060 B 19751 int
  pkg/handlers/authentication/permissions.go
  playwright/tests/office/txo/sitUpdates.spec.js
  src/components/Office/ReviewSITExtensionModal/ReviewSITExtensionModal.jsx
  src/components/Office/ShipmentForm/ShipmentForm.jsx
  src/components/Office/SubmitSITExtensionModal/SubmitSITExtensionModal.jsx
  src/constants/permissions.js
  src/constants/routes.js
  src/pages/Office/AddShipment/AddShipment.jsx
  src/pages/Office/AddShipment/AddShipment.test.jsx
  src/pages/Office/MoveDetails/MoveDetails.jsx
  src/pages/Office/index.jsx
  src/pages/Office/index.test.jsx
Labels: Scrummy Bears, INTEGRATION

#13083 B 20199 int
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet_test.go
Labels: Scrummy Bears, INTEGRATION

#12971 MAIN - B-19794 SC-ability-to-open-PPM-after-Closeout
  pkg/services/ppm_closeout/ppm_closeout.go
  playwright/tests/office/servicescounseling/servicesCounselingFlows.spec.js
  src/components/Office/PPM/PPMHeaderSummary/HeaderSection.jsx
  src/components/Office/PPM/PPMHeaderSummary/PPMHeaderSummary.jsx
  src/components/Office/PPM/ReviewDocumentsSidePanel/ReviewDocumentsSidePanel.jsx
  src/components/Office/PPM/ReviewDocumentsSidePanel/ReviewDocumentsSidePanel.test.jsx
  src/components/Office/PPM/ReviewExpense/ReviewExpense.jsx
  src/components/Office/PPM/ReviewExpense/ReviewExpense.test.jsx
  src/components/Office/PPM/ReviewProGear/ReviewProGear.jsx
  src/components/Office/PPM/ReviewProGear/ReviewProGear.test.jsx
  src/components/Office/PPM/ReviewWeightTicket/ReviewWeightTicket.jsx
  src/components/Office/PPM/ReviewWeightTicket/ReviewWeightTicket.test.jsx
  src/components/Office/ShipmentDisplay/ShipmentDisplay.jsx
  src/components/Office/ShipmentDisplay/ShipmentDisplay.test.jsx
  src/constants/routes.js
  src/pages/Office/PPM/ReviewDocuments/ReviewDocuments.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
  src/pages/Office/ServicesCounselingMoveInfo/ServicesCounselingMoveInfo.jsx
  src/pages/Office/ServicesCounselingMoveInfo/ServicesCounselingMoveInfo.test.jsx
Labels: ByteSize M&Ms, MAIN

#13101 B-20107: Refactor Backup Info Panel
  src/shared/Entities/modules/serviceMembers.js
Labels: Mountain Movers, MAIN

#13120 INT B-20131-Storybook Fix
  src/components/Office/PPM/PPMHeaderSummary/EditPPMHeaderSummaryModal.stories.jsx
Labels: ByteSize M&Ms, INTEGRATION

#13008 MAIN - B-20131 sc edit full address
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/update_p_p_m_shipment.go
  pkg/handlers/ghcapi/internal/payloads/payload_to_model.go
  playwright/tests/office/servicescounseling/servicesCounselingFlows.spec.js
  src/components/Office/PPM/PPMHeaderSummary/EditPPMHeaderSummaryModal.jsx
  src/components/Office/PPM/PPMHeaderSummary/EditPPMHeaderSummaryModal.module.scss
  src/components/Office/PPM/PPMHeaderSummary/EditPPMHeaderSummaryModal.stories.jsx
  src/components/Office/PPM/PPMHeaderSummary/EditPPMHeaderSummaryModal.test.jsx
  src/components/Office/PPM/PPMHeaderSummary/HeaderSection.jsx
  src/components/Office/PPM/PPMHeaderSummary/PPMHeaderSummary.jsx
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: ByteSize M&Ms, MAIN

#13122 INT-B-19779 - Show MTO Service Price for Counseling and Move Management
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/mto_service_items.go
  pkg/handlers/ghcapi/mto_service_items_test.go
  src/components/Office/ServiceItemDetails/ServiceItemDetails.jsx
  src/components/Office/ServiceItemDetails/ServiceItemDetails.test.jsx
  src/components/Office/ServiceItemsTable/ServiceItemsTable.test.jsx
Labels: ByteSize M&Ms, INTEGRATION

#13108 INT B-20249 incorrect gbloc prime api
  pkg/handlers/primeapi/payloads/model_to_payload.go
  pkg/handlers/primeapi/payloads/model_to_payload_test.go
  pkg/handlers/primeapiv2/payloads/model_to_payload.go
  pkg/handlers/primeapiv2/payloads/model_to_payload_test.go
  pkg/handlers/primeapiv3/payloads/model_to_payload.go
  pkg/handlers/primeapiv3/payloads/model_to_payload_test.go
  pkg/services/move_task_order/move_task_order_fetcher.go
Labels: ByteSize M&Ms, INTEGRATION

#13026 MAIN - B-19776-B-19778-add-status-filter-closeout
  pkg/factory/ppm_shipment_factory.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/queues/get_services_counseling_queue_parameters.go
  pkg/gen/ghcapi/ghcoperations/queues/get_services_counseling_queue_urlbuilder.go
  pkg/gen/ghcmessages/p_p_m_status.go
  pkg/gen/ghcmessages/queue_move.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/queues.go
  pkg/services/order.go
  pkg/services/order/order_fetcher.go
  pkg/services/order/order_fetcher_test.go
  playwright/tests/office/servicescounseling/servicesCounselingQueueFilters.spec.js
  src/constants/queues.js
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.jsx
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.test.jsx
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: ByteSize M&Ms, MAIN

#13129 MAIN-B-19980 - Fixed GCC/Gross Incentive Storage SIT Calculations
  pkg/services/ppm_closeout/ppm_closeout.go
  src/components/Office/PPM/PPMHeaderSummary/PPMHeaderSummary.jsx
Labels: ByteSize M&Ms, MAIN

#13128 B 20250 incorrect gbloc prime main
  pkg/handlers/primeapi/payloads/model_to_payload.go
  pkg/handlers/primeapiv2/payloads/model_to_payload.go
  pkg/handlers/primeapiv3/payloads/model_to_payload.go
Labels: ByteSize M&Ms, MAIN

#13090 B-20235-INT Make feedback review button available when docs kicked back
  Dockerfile.e2e
  Dockerfile.migrations
  Dockerfile.migrations_local
  Dockerfile.reviewapp
  Dockerfile.tools
  Dockerfile.tools_local
  src/components/PPMSummaryList/PPMSummaryList.jsx
  src/components/PPMSummaryList/PPMSummaryList.test.jsx
Labels: G-Unit, INTEGRATION

#13113 B-19728 Customer can upload supporting docs
  .circleci/config.yml
  .envrc
  config/env/demo.app-client-tls.env
  config/env/demo.app.env
  config/env/exp.app-client-tls.env
  config/env/exp.app.env
  config/env/loadtest.app-client-tls.env
  config/env/loadtest.app.env
  config/env/prd.app-client-tls.env
  config/env/prd.app.env
  config/env/stg.app-client-tls.env
  config/env/stg.app.env
  config/flipt/storage/development.features.yaml
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240529181303_add_additional_documents_id_col_to_moves.up.sql
  pkg/factory/shared.go
  pkg/gen/internalapi/configure_mymove.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalapi/internaloperations/moves/upload_additional_documents.go
  pkg/gen/internalapi/internaloperations/moves/upload_additional_documents_parameters.go
  pkg/gen/internalapi/internaloperations/moves/upload_additional_documents_responses.go
  pkg/gen/internalapi/internaloperations/moves/upload_additional_documents_urlbuilder.go
  pkg/gen/internalapi/internaloperations/mymove_api.go
  pkg/gen/internalapi/internaloperations/uploads/delete_upload_parameters.go
  pkg/gen/internalapi/internaloperations/uploads/delete_upload_urlbuilder.go
  pkg/gen/internalmessages/move_payload.go
  pkg/handlers/internalapi/api.go
  pkg/handlers/internalapi/moves.go
  pkg/handlers/internalapi/moves_test.go
  pkg/handlers/internalapi/uploads.go
  pkg/models/move.go
  pkg/services/move.go
  pkg/services/move/additional_documents_uploader.go
  pkg/services/move/additional_documents_uploader_test.go
  pkg/services/order/order_updater.go
  src/constants/routes.js
  src/pages/MyMove/AdditionalDocuments/AdditionalDocuments.jsx
  src/pages/MyMove/AdditionalDocuments/AdditionalDocuments.test.jsx
  src/pages/MyMove/Home/MoveHome.jsx
  src/scenes/MyMove/index.jsx
  src/services/internalApi.js
  swagger-def/definitions/AdditionalDocuments.yaml
  swagger-def/internal.yaml
  swagger/internal.yaml
Labels: G-Unit, MAIN

#13118 B-20080 INT (Part #2) - Add Marine Corps to Move Search Filter
  src/components/Table/SearchResultsTable.jsx
  src/constants/queues.js
  src/pages/Office/HeadquartersQueues/HeadquartersQueues.jsx
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.jsx
Labels: Scrummy Bears, INTEGRATION

#13134 B19763 b19762 main
  pkg/payment_request/service_param_value_lookups/distance_zip_lookup.go
  pkg/payment_request/service_param_value_lookups/distance_zip_lookup_test.go
  pkg/payment_request/service_param_value_lookups/eia_fuel_price_lookup.go
  pkg/payment_request/service_param_value_lookups/eia_fuel_price_lookup_test.go
  pkg/payment_request/service_param_value_lookups/service_param_value_lookups.go
  pkg/payment_request/service_param_value_lookups/service_param_value_lookups_test.go
  pkg/services/payment_request/payment_request_creator.go
  pkg/services/payment_request/payment_request_creator_test.go
  pkg/services/ppm_closeout/ppm_closeout.go
  pkg/services/ppmshipment/aoa_packet_creator_test.go
  pkg/services/ppmshipment/ppm_estimator.go
  pkg/services/ppmshipment/ppm_estimator_test.go
  pkg/testdatagen/scenario/subscenarios.go
  src/components/Customer/PPM/Booking/DateAndLocationForm/DateAndLocationForm.test.jsx
  src/pages/Office/ServicesCounselingEditShipmentDetails/ServicesCounselingEditShipmentDetails.test.jsx
Labels: ByteSize M&Ms, MAIN

#13109 MAIN B-20249 incorrect gbloc prime api
  pkg/handlers/primeapi/payloads/model_to_payload.go
  pkg/handlers/primeapi/payloads/model_to_payload_test.go
  pkg/handlers/primeapiv2/payloads/model_to_payload.go
  pkg/handlers/primeapiv2/payloads/model_to_payload_test.go
  pkg/handlers/primeapiv3/payloads/model_to_payload.go
  pkg/handlers/primeapiv3/payloads/model_to_payload_test.go
  pkg/services/move_task_order/move_task_order_fetcher.go
Labels: ByteSize M&Ms, MAIN

#13112 B-19723-INT Office viewers can view EMPLID
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/customer.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  src/components/CustomerHeader/CustomerHeader.test.jsx
  src/components/CustomerHeader/index.jsx
  src/components/Office/DefinitionLists/CustomerInfoList.jsx
  src/components/Office/DefinitionLists/CustomerInfoList.test.jsx
  src/pages/Office/MoveDetails/MoveDetails.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: G-Unit, INTEGRATION

#13124 B 20046 update prime email content int2
  pkg/assets/notifications/templates/move_counseled_template.html
  pkg/assets/notifications/templates/move_counseled_template.txt
  pkg/assets/notifications/templates/move_submitted_template.html
  pkg/assets/notifications/templates/move_submitted_template.txt
  pkg/notifications/move_counseled_test.go
  pkg/notifications/move_submitted_test.go
Labels: ByteSize M&Ms, INTEGRATION

#13135 Fix flaky happy path with edits and backs test in PPM closeout flow
  playwright/tests/my/milmove/ppms/customerPpmTestFixture.js
Labels: Mountain Movers, INTEGRATION

#13110 B19228 MAIN 20240618 - Fix sidebar text spilling paste the page on MTO page
  src/components/Office/ShipmentDetails/ShipmentDetails.module.scss
  src/components/Office/ShipmentDetails/ShipmentDetailsSidebar.jsx
  src/components/Office/ShipmentDetails/ShipmentDetailsSidebar.module.scss
Labels: ByteSize M&Ms, MAIN
