Repository transcom/mymove, pull requests merged in 2024-01, with the labels that each got.

#11683 B 17991 add convert to customer api value
  migrations/app/schema/20231211202108_add_member_expense_flags.up.sql
  pkg/factory/mto_service_item_factory.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/m_t_o_service_item.go
  pkg/gen/ghcmessages/m_t_o_service_item_single.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/models/mto_service_items.go
  pkg/services/mto_service_item/mto_service_item_updater.go
  src/types/serviceItems.js
  swagger-def/definitions/MTOServiceItem.yaml
  swagger-def/definitions/MTOServiceItemSingle.yaml
  swagger/ghc.yaml
Labels: ByteSize M&Ms

#11693 B-18412 Remove edit & review request buttons/links on MTO for DDDSIT service item
  playwright/tests/office/txo/sitUpdates.spec.js
  src/components/Office/RequestedServiceItemsTable/RequestedServiceItemsTable.jsx
  src/components/Office/ServiceItemUpdateModal/EditSitAddressChangeForm.jsx
  src/components/Office/ServiceItemUpdateModal/ReviewSitAddressChange.jsx
  src/components/Office/ServiceItemUpdateModal/ServiceItemUpdateModal.jsx
  src/components/Office/ServiceItemUpdateModal/ServiceItemUpdateModal.module.scss
  src/components/Office/ServiceItemUpdateModal/ServiceItemUpdateModal.stories.jsx
  src/components/Office/ServiceItemUpdateModal/ServiceItemUpdateModal.test.jsx
  src/components/Office/ServiceItemUpdateModal/ServiceItemUpdateModalTestParams.js
  src/components/Office/ServiceItemsTable/ServiceItemsTable.jsx
  src/components/Office/ServiceItemsTable/ServiceItemsTable.test.jsx
  src/constants/sitUpdates.js
  src/pages/Office/MoveDetails/MoveDetails.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.test.jsx
  src/services/ghcApi.js
Labels: Mountain Movers

#11671 B 18163 ppm closeout rep should not adjust net shipment weight when customer is over their allowance
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20231211213232_add_allowable_weight.up.sql
  mymove.code-workspace
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/update_weight_ticket.go
  pkg/gen/ghcmessages/weight_ticket.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/update_weight_ticket.go
  pkg/gen/internalmessages/weight_ticket.go
  pkg/handlers/ghcapi/internal/payloads/payload_to_model.go
  pkg/models/weight_ticket.go
  pkg/models/weight_ticket_test.go
  pkg/services/weight_ticket/weight_ticket_updater.go
  pkg/services/weight_ticket/weight_ticket_updater_test.go
  playwright/tests/office/servicescounseling/servicesCounselingWeightTickets.spec.js
  src/components/Office/PPM/EditNetWeights/EditPPMNetWeight.jsx
  src/components/Office/PPM/EditNetWeights/EditPPMNetWeight.test.jsx
  src/components/Office/PPM/ReviewWeightTicket/ReviewWeightTicket.jsx
  src/components/Office/PPM/ReviewWeightTicket/ReviewWeightTicket.test.jsx
  src/pages/Office/PPM/ReviewDocuments/ReviewDocuments.jsx
  src/pages/Office/PPM/ReviewDocuments/ReviewDocuments.test.jsx
  src/shared/utils.js
  src/utils/formatters.js
  src/utils/shipmentWeights.js
  src/utils/test/factories/weightTicket.js
  swagger-def/definitions/WeightTicket.yaml
  swagger-def/ghc.yaml
  swagger-def/internal.yaml
  swagger/ghc.yaml
  swagger/internal.yaml
Labels: G-Unit

#11709 B-17953 Update status after converting to customer expense
  .circleci/config.yml
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20231211202108_add_customer_expense_flags.up.sql
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/ghcapi/ghcoperations/shipment/update_s_i_t_service_item_customer_expense.go
  pkg/gen/ghcapi/ghcoperations/shipment/update_s_i_t_service_item_customer_expense_parameters.go
  pkg/gen/ghcapi/ghcoperations/shipment/update_s_i_t_service_item_customer_expense_responses.go
  pkg/gen/ghcapi/ghcoperations/shipment/update_s_i_t_service_item_customer_expense_urlbuilder.go
  pkg/gen/ghcmessages/m_t_o_service_item.go
  pkg/gen/ghcmessages/m_t_o_service_item_single.go
  pkg/gen/ghcmessages/s_i_t_status.go
  pkg/gen/ghcmessages/update_s_i_t_service_item_customer_expense.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/mto_shipment.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/models/mto_service_items.go
  pkg/services/event/ghc_endpoint.go
  pkg/services/mocks/MTOServiceItemUpdater.go
  pkg/services/mto_service_item.go
  pkg/services/mto_service_item/mto_service_item_updater.go
  pkg/services/mto_service_item/mto_service_item_updater_test.go
  pkg/services/sit_extension/sit_extension_denier.go
  playwright/tests/office/txo/sitUpdates.spec.js
  src/components/Office/ConvertSITToCustomerExpenseModal/ConvertSITToCustomerExpenseModal.jsx
  src/components/Office/ConvertSITToCustomerExpenseModal/ConvertSITToCustomerExpenseModal.test.jsx
  src/components/Office/ShipmentDetails/ShipmentDetails.jsx
  src/components/Office/ShipmentDetails/ShipmentDetailsMain.jsx
  src/components/Office/ShipmentSITDisplay/ShipmentSITDisplay.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
  src/services/ghcApi.js
  swagger-def/definitions/MTOServiceItem.yaml
  swagger-def/definitions/MTOServiceItemSingle.yaml
  swagger-def/definitions/SITStatus.yaml
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: ByteSize M&Ms

#11696 B-18414 Shipment Destination Address on Dest SIT service items on creation/approval
  pkg/services/mto_service_item/mto_service_item_creator.go
  pkg/services/mto_service_item/mto_service_item_creator_test.go
  pkg/services/mto_service_item/mto_service_item_updater.go
  pkg/services/mto_service_item/mto_service_item_updater_test.go
Labels: Mountain Movers

#11716 fix label
  src/components/Customer/Review/ProfileTable/ProfileTable.jsx
Labels: Mountain Movers

#11698 B-18413 prime sim sit address change and dest sit form changes
  playwright/tests/office/primesimulator/primeSimulatorFlows.spec.js
  src/components/PrimeUI/CreateShipmentServiceItemForm/DestinationSITServiceItemForm.jsx
  src/components/PrimeUI/CreateShipmentServiceItemForm/DestinationSITServiceItemForm.test.jsx
  src/components/PrimeUI/Shipment/Shipment.jsx
  src/components/PrimeUI/Shipment/Shipment.test.jsx
  src/constants/routes.js
  src/pages/Office/index.jsx
  src/pages/PrimeUI/CreatePaymentRequest/CreatePaymentRequest.test.jsx
  src/pages/PrimeUI/MoveTaskOrder/MoveDetails.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdateDestinationAddress.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdateDestinationAddress.test.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdateDestinationAddressForm.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdateDestinationAddressForm.test.jsx
  src/pages/PrimeUI/UpdateServiceItems/PrimeUIRequestSITDestAddressChangeForm.jsx
  src/pages/PrimeUI/UpdateServiceItems/PrimeUIRequestSITDestAddressChangeForm.test.jsx
  src/pages/PrimeUI/UpdateServiceItems/PrimeUIUpdateServiceItems.jsx
  src/pages/PrimeUI/UpdateServiceItems/PrimeUIUpdateServiceItems.test.jsx
  src/services/primeApi.js
Labels: Mountain Movers

#11704 B 18050 ppm ssw form pdf replacement - PDFCPU Update 0.6.0
  go.mod
  go.sum
  pkg/paperwork/evaluation_report_form_creator_test.go
  pkg/paperwork/generator.go
  pkg/paperwork/generator_test.go
  pkg/paperwork/paperwork_test.go
Labels: Scrummy Bears

#11712 B-18172 H&AL Prime Create PPM
  src/constants/MoveHistory/EventTemplates/CreateMTOShipment/createMTOShipmentPPMDetails.jsx
  src/constants/MoveHistory/EventTemplates/CreateMTOShipment/createMTOShipmentPPMDetails.test.jsx
  src/constants/MoveHistory/EventTemplates/index.js
Labels: G-Unit

#11706 B-18174 Added ppm pro gear weight ticket to history
  src/constants/MoveHistory/Database/BooleanFields.js
  src/constants/MoveHistory/Database/FieldMappings.js
  src/constants/MoveHistory/Database/Tables.js
  src/constants/MoveHistory/EventTemplates/UpdateWeightTicket/updateWeightTicketProGear.jsx
  src/constants/MoveHistory/EventTemplates/UpdateWeightTicket/updateWeightTicketProGear.test.jsx
  src/constants/MoveHistory/EventTemplates/index.js
  src/constants/MoveHistory/UIDisplay/Operations.js
Labels: G-Unit

#11721 B 18170 H&AL Prime delete PPM shipment
  src/constants/MoveHistory/EventTemplates/DeleteShipment/DeleteShipmentPPM.jsx
  src/constants/MoveHistory/EventTemplates/DeleteShipment/DeleteShipmentPPM.test.jsx
  src/constants/MoveHistory/EventTemplates/index.js
  src/constants/MoveHistory/UIDisplay/Operations.js
Labels: G-Unit

#11714 B-18415 GHC API Remove Now Unused Endpoints and Tech Debt
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/mto_service_item/approve_s_i_t_address_update.go
  pkg/gen/ghcapi/ghcoperations/mto_service_item/approve_s_i_t_address_update_parameters.go
  pkg/gen/ghcapi/ghcoperations/mto_service_item/approve_s_i_t_address_update_responses.go
  pkg/gen/ghcapi/ghcoperations/mto_service_item/approve_s_i_t_address_update_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/mto_service_item/create_s_i_t_address_update.go
  pkg/gen/ghcapi/ghcoperations/mto_service_item/create_s_i_t_address_update_parameters.go
  pkg/gen/ghcapi/ghcoperations/mto_service_item/create_s_i_t_address_update_responses.go
  pkg/gen/ghcapi/ghcoperations/mto_service_item/create_s_i_t_address_update_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/mto_service_item/reject_s_i_t_address_update.go
  pkg/gen/ghcapi/ghcoperations/mto_service_item/reject_s_i_t_address_update_parameters.go
  pkg/gen/ghcapi/ghcoperations/mto_service_item/reject_s_i_t_address_update_responses.go
  pkg/gen/ghcapi/ghcoperations/mto_service_item/reject_s_i_t_address_update_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/mto_service_item/update_m_t_o_service_item.go
  pkg/gen/ghcapi/ghcoperations/mto_service_item/update_m_t_o_service_item_parameters.go
  pkg/gen/ghcapi/ghcoperations/mto_service_item/update_m_t_o_service_item_responses.go
  pkg/gen/ghcapi/ghcoperations/mto_service_item/update_m_t_o_service_item_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/ghcmessages/create_s_i_t_address_update.go
  pkg/gen/ghcmessages/patch_s_i_t_address_update_status.go
  pkg/handlers/authentication/permissions.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/internal/payloads/payload_to_model.go
  pkg/handlers/ghcapi/mto_service_items.go
  pkg/handlers/ghcapi/mto_service_items_test.go
  pkg/services/mto_service_item/mto_service_item_validators.go
  pkg/services/sit_address_update.go
  pkg/services/sit_address_update/approved_sit_address_update_creator.go
  pkg/services/sit_address_update/approved_sit_address_update_creator_test.go
  pkg/services/sit_address_update/sit_address_update_request_approver.go
  pkg/services/sit_address_update/sit_address_update_request_approver_test.go
  pkg/services/sit_address_update/sit_address_update_request_rejector.go
  pkg/services/sit_address_update/sit_address_update_request_rejector_test.go
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: Mountain Movers

#11702 B-18418 Fixed visibility of delete shipment on moves that are already approved
  src/components/Office/ShipmentForm/ShipmentForm.jsx
Labels: G-Unit

#11718 B-18437 TOO can now delete shipments
  pkg/handlers/ghcapi/mto_shipment.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/services/mto_shipment/rules.go
  pkg/services/mto_shipment/rules_test.go
  pkg/services/mto_shipment/shipment_deleter_test.go
Labels: G-Unit

#11703 B-18175 add ppm expense updates to move history
  pkg/assets/sql_scripts/move_history_fetcher.sql
  src/constants/MoveHistory/Database/DateFields.js
  src/constants/MoveHistory/Database/FieldMappings.js
  src/constants/MoveHistory/Database/MonetaryFields.js
  src/constants/MoveHistory/Database/Tables.js
  src/constants/MoveHistory/EventTemplates/UpdateMovingExpense/UpdateMovingExpense.jsx
  src/constants/MoveHistory/EventTemplates/UpdateMovingExpense/UpdateMovingExpense.test.jsx
  src/constants/MoveHistory/EventTemplates/index.js
  src/constants/MoveHistory/UIDisplay/Operations.js
  src/pages/Office/MoveHistory/LabeledDetails.jsx
  src/utils/formatMtoShipment.js
Labels: G-Unit

#11699 B 18411 add dest sit info on shipment dest address review screen
  src/components/Office/AddressUpdatePreview/AddressUpdatePreview.jsx
  src/components/Office/AddressUpdatePreview/AddressUpdatePreview.stories.jsx
  src/components/Office/AddressUpdatePreview/AddressUpdatePreview.test.jsx
  src/components/Office/ShipmentAddressUpdateReviewRequestModal/ShipmentAddressUpdateReviewRequestModal.jsx
  src/components/Office/ShipmentAddressUpdateReviewRequestModal/ShipmentAddressUpdateReviewRequestModal.test.jsx
  src/components/Office/ShipmentForm/ShipmentForm.test.jsx
Labels: Mountain Movers

#11722 B-18033: Add createSitAddressUpdateRequest logic to createNonSitAddressUpdateRequest
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/mto_shipment/create_non_s_i_t_address_update_request.go
  pkg/gen/primeclient/mto_shipment/mto_shipment_client.go
  pkg/services/shipment_address_update/shipment_address_update_requester.go
  pkg/services/shipment_address_update/shipment_address_update_requester_test.go
  swagger-def/prime.yaml
  swagger/prime.yaml
Labels: Mountain Movers

#11728 added resolution for follow-redirects
  package.json
  yarn.lock
Labels: security

#11684 B 18112 update source of duty location and pay grade information in profile to show values from orders table
  .circleci/config.yml
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/create_update_orders.go
  pkg/gen/internalmessages/order_pay_grade.go
  pkg/handlers/internalapi/orders.go
  src/components/Customer/DodInfoForm/DodInfoForm.jsx
  src/components/Customer/DodInfoForm/DodInfoForm.stories.jsx
  src/components/Customer/DodInfoForm/DodInfoForm.test.jsx
  src/components/Customer/Review/ProfileTable/ProfileTable.jsx
  src/components/Customer/Review/ProfileTable/ProfileTable.stories.jsx
  src/components/Customer/Review/ServiceInfoDisplay/ServiceInfoDisplay.jsx
  src/components/Customer/Review/ServiceInfoDisplay/ServiceInfoDisplay.stories.jsx
  src/components/Customer/Review/ServiceInfoDisplay/ServiceInfoDisplay.test.jsx
  src/components/Customer/Review/Summary/Summary.jsx
  src/components/Customer/ServiceInfoForm/ServiceInfoForm.jsx
  src/components/Customer/ServiceInfoForm/ServiceInfoForm.stories.jsx
  src/components/Customer/ServiceInfoForm/ServiceInfoForm.test.jsx
  src/components/CustomerHeader/CustomerHeader.test.jsx
  src/components/CustomerHeader/index.jsx
  src/components/Office/AllowancesDetailForm/AllowancesDetailForm.jsx
  src/components/Office/AllowancesDetailForm/AllowancesDetailForm.test.jsx
  src/components/Office/EvaluationReportMoveInfo/EvaluationReportMoveInfo.jsx
  src/components/Office/EvaluationReportPreview/EvaluationReportPreview.jsx
  src/components/Office/EvaluationReportShipmentInfo/EvaluationReportShipmentInfo.jsx
  src/components/Office/RequestedShipments/RequestedShipmentsTestData.js
  src/constants/MoveHistory/Database/OptionFields.js
  src/constants/MoveHistory/EventTemplates/ApproveShipmentDiversion/approveShipmentDiversion.test.jsx
  src/constants/MoveHistory/EventTemplates/UpdateMTOStatusServiceCounselingCompleted/updateMTOStatusServiceCounselingCompleted.test.jsx
  src/constants/orders.js
  src/pages/MyMove/Profile/DodInfo.jsx
  src/pages/MyMove/Profile/EditOktaInfo.test.jsx
  src/pages/MyMove/Profile/EditOrdersPayGradeAndOriginLocation.test.jsx
  src/pages/MyMove/Profile/EditServiceInfo.jsx
  src/pages/MyMove/Profile/EditServiceInfo.test.jsx
  src/pages/MyMove/Profile/Profile.jsx
  src/pages/Office/MoveAllowances/MoveAllowances.jsx
  src/pages/Office/MoveAllowances/MoveAllowances.test.jsx
  src/pages/Office/ServicesCounselingMoveAllowances/ServicesCounselingMoveAllowances.jsx
  src/pages/Office/ServicesCounselingMoveAllowances/ServicesCounselingMoveAllowances.test.jsx
  src/scenes/Review/EditProfile.jsx
  src/shared/ComboButton/dropdown.test.js
  src/utils/branchRankFormatters.js
  src/utils/milmoveLog.test.js
  swagger-def/internal.yaml
  swagger/internal.yaml
Labels: Mountain Movers

#11732 B-18156 Fixes
  pkg/services/mto_shipment/mto_shipment_updater.go
  pkg/services/shipment_address_update/shipment_address_update_requester.go
Labels: Mountain Movers

#11740 B18438 create ppm closeout get endpoint
  .circleci/config.yml
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/ghcapi/ghcoperations/ppm/get_p_p_m_closeout.go
  pkg/gen/ghcapi/ghcoperations/ppm/get_p_p_m_closeout_parameters.go
  pkg/gen/ghcapi/ghcoperations/ppm/get_p_p_m_closeout_responses.go
  pkg/gen/ghcapi/ghcoperations/ppm/get_p_p_m_closeout_urlbuilder.go
  pkg/gen/ghcmessages/p_p_m_closeout.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/ppm_closeout.go
  pkg/handlers/ghcapi/ppm_closeout_test.go
  pkg/models/ppm_shipment.go
  pkg/services/ppm_closeout.go
  pkg/services/ppm_closeout/ppm_closeout.go
  swagger-def/definitions/PPMCloseout.yaml
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: ByteSize M&Ms

#11741 B-18332 Update Reweigh Email Template
  pkg/assets/notifications/templates/reweigh_requested_template.html
  pkg/assets/notifications/templates/reweigh_requested_template.txt
  pkg/notifications/reweigh_requested.go
  pkg/notifications/reweigh_requested_test.go
Labels: ByteSize M&Ms

#11736 B-18269 Added actual weight field
  src/components/Office/BillableWeight/ShipmentCard/ShipmentCard.jsx
  src/pages/Office/ReviewBillableWeight/ReviewBillableWeight.jsx
Labels: Mountain Movers

#11744 B-18467: Update service item destination address in updateShipmentDestinationAddress endpoint
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/mto_shipment/update_shipment_destination_address.go
  pkg/gen/primeclient/mto_shipment/mto_shipment_client.go
  pkg/services/shipment_address_update/shipment_address_update_requester.go
  pkg/services/shipment_address_update/shipment_address_update_requester_test.go
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdateDestinationAddress.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdateDestinationAddress.test.jsx
  src/services/primeApi.js
  swagger-def/prime.yaml
  swagger/prime.yaml
Labels: Mountain Movers

#11748 B-17958 identify create calculations ppm closeout 1-6
  pkg/services/ppm_closeout/ppm_closeout.go
  pkg/services/ppm_closeout/ppm_closeout_service_test.go
Labels: ByteSize M&Ms

#11762 B-18033-Fix-for-I-12339-Use--Current-Address-On-Shipment-Address-Change
  pkg/services/shipment_address_update/shipment_address_update_requester.go
Labels: Mountain Movers

#11760 B-18332 Added new email content updates
  pkg/assets/notifications/templates/reweigh_requested_template.html
  pkg/assets/notifications/templates/reweigh_requested_template.txt
  pkg/notifications/reweigh_requested.go
  pkg/notifications/reweigh_requested_test.go
Labels: ByteSize M&Ms

#11753 B 18310 multi move feature flag
  .envrc
  cmd/milmove/serve.go
  config/env/demo.app-client-tls.env
  config/env/demo.app.env
  config/env/exp.app-client-tls.env
  config/env/exp.app.env
  config/env/loadtest.app-client-tls.env
  config/env/loadtest.app.env
  config/env/prd.app-client-tls.env
  config/env/prd.app.env
  config/env/stg.app-client-tls.env
  config/env/stg.app.env
  pkg/handlers/config.go
  pkg/services/feature_flag.go
  src/utils/featureFlags.js
Labels: Mountain Movers

#11743 B-18180 removed unused ppm estimated weight
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240112205201_remove_ppm_estimated_weight.up.sql
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/primeapi/move_task_order_test.go
  pkg/handlers/primeapi/payloads/model_to_payload.go
  pkg/handlers/primeapiv2/move_task_order_test.go
  pkg/handlers/primeapiv2/payloads/model_to_payload.go
  pkg/handlers/supportapi/internal/payloads/model_to_payload.go
  pkg/handlers/supportapi/internal/payloads/payload_to_model.go
  pkg/models/move.go
  pkg/services/event/notification_payloads.go
  pkg/services/support/move_task_order/move_task_order_creator.go
Labels: G-Unit

#11793 B 17975 customer submitted final ppm email
  .circleci/config.yml
  pkg/assets/notifications/templates/ppm_packet_email_template.html
  pkg/assets/notifications/templates/ppm_packet_email_template.txt
  pkg/handlers/apitests.go
  pkg/handlers/internalapi/api_test.go
  pkg/handlers/internalapi/ppm_shipment.go
  pkg/handlers/routing/base_routing_suite.go
  pkg/models/ppm_shipment.go
  pkg/notifications/ppm_packet_email.go
  pkg/notifications/ppm_packet_email_test.go
  pkg/testdatagen/testharness/make_move.go
Labels: ByteSize M&Ms

#11771 B-17971 & B-17972 - Update TOO Submission To Prime Email
  pkg/assets/notifications/templates/move_issued_to_prime_template.html
  pkg/assets/notifications/templates/move_issued_to_prime_template.txt
  pkg/notifications/move_issued_to_prime_test.go
Labels: ByteSize M&Ms

#11805 Int b 18329 remove na from address
  src/components/Office/ShipmentAddresses/ShipmentAddresses.jsx
  src/utils/shipmentDisplay.jsx
Labels: ByteSize M&Ms, INTEGRATION

#11811 INT B-18309-Multi-Moves-Landing-Page-Component-Creation
  src/components/ButtonDropdownMenu/ButtonDropdownMenu.jsx
  src/components/ButtonDropdownMenu/ButtonDropdownMenu.module.scss
  src/components/ButtonDropdownMenu/ButtonDropdownMenu.stories.jsx
  src/components/ButtonDropdownMenu/ButtonDropdownMenu.test.jsx
  src/components/Office/ShipmentContainer/ShipmentContainer.jsx
  src/constants/routes.js
  src/pages/MyMove/Multi-Moves/MultiMovesLandingPage.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesLandingPage.module.scss
  src/pages/MyMove/Multi-Moves/MultiMovesLandingPage.test.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesMoveContainer/MultiMovesMoveContainer.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesMoveContainer/MultiMovesMoveContainer.module.scss
  src/pages/MyMove/Multi-Moves/MultiMovesMoveContainer/MultiMovesMoveContainer.stories.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesMoveContainer/MultiMovesMoveContainer.test.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesMoveHeader/MultiMovesMoveHeader.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesMoveHeader/MultiMovesMoveHeader.module.scss
  src/pages/MyMove/Multi-Moves/MultiMovesMoveHeader/MultiMovesMoveHeader.stories.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesMoveHeader/MultiMovesMoveHeader.test.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesMoveInfoList/MultiMovesInfoList.stories.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesMoveInfoList/MultiMovesInfoList.test.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesMoveInfoList/MultiMovesMoveInfoList.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesMoveInfoList/MultiMovesMoveInfoList.module.scss
  src/pages/MyMove/Multi-Moves/MultiMovesTestData.js
  src/scenes/MyMove/index.jsx
  src/shared/constants.js
Labels: Mountain Movers, INTEGRATION

#11803 B-18326 Update the Estimated Weight - B-18327 Remove Fields - B-18322 Update Requested pickup date
  src/components/Office/ImportantShipmentDates/ImportantShipmentDates.jsx
  src/components/Office/ImportantShipmentDates/ImportantShipmentDates.test.jsx
  src/components/Office/ShipmentDetails/ShipmentDetailsMain.jsx
Labels: ByteSize M&Ms, INTEGRATION

#11785 B-17965 Send Email - Gov't Counselor Submission (Before TOO Approval)
  pkg/assets/notifications/templates/move_counseled_template.html
  pkg/assets/notifications/templates/move_counseled_template.txt
  pkg/handlers/ghcapi/move_task_order.go
  pkg/handlers/ghcapi/move_task_order_test.go
  pkg/notifications/move_counseled.go
  pkg/notifications/move_counseled_test.go
Labels: ByteSize M&Ms, INTEGRATION

#11823 B 18477 integration
  src/components/Customer/Home/Step/Step.stories.jsx
  src/components/ShipmentList/ShipmentList.jsx
  src/components/ShipmentList/ShipmentList.stories.jsx
  src/components/ShipmentList/ShipmentList.test.jsx
  src/pages/Office/MovePaymentRequests/MovePaymentRequests.test.jsx
Labels: Mountain Movers, INTEGRATION

#11735 B 18429 SSW Model to Service Object Conversion - INT
  cmd/generate-shipment-summary/main.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalapi/internaloperations/moves/show_shipment_summary_worksheet.go
  pkg/gen/internalapi/internaloperations/moves/show_shipment_summary_worksheet_parameters.go
  pkg/gen/internalapi/internaloperations/moves/show_shipment_summary_worksheet_urlbuilder.go
  pkg/gen/internalapi/internaloperations/mymove_api.go
  pkg/handlers/internalapi/api.go
  pkg/handlers/internalapi/moves.go
  pkg/models/ppm_shipment.go
  pkg/paperwork/shipment_summary.go
  pkg/paperwork/shipment_summary_test.go
  pkg/services/mocks/SSWPPMComputer.go
  pkg/services/paperwork/form_creator_test.go
  pkg/services/shipment_summary_worksheet.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet_service_test.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet_test.go
  swagger-def/internal.yaml
  swagger/internal.yaml
Labels: Scrummy Bears

#11826 B 18192 int moving expense api delete
  pkg/handlers/internalapi/moving_expense.go
  pkg/handlers/internalapi/moving_expense_test.go
  pkg/services/mocks/MovingExpenseDeleter.go
  pkg/services/moving_expense.go
  pkg/services/moving_expense/moving_expense_deleter.go
  pkg/services/moving_expense/moving_expense_deleter_test.go
Labels: G-Unit, INTEGRATION

#11829 B 18111 pay grade and duty location flow changes integration
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/order_pay_grade.go
  pkg/handlers/internalapi/orders.go
  pkg/handlers/internalapi/orders_test.go
  pkg/handlers/internalapi/service_members_test.go
  playwright/tests/my/mymove/onboarding.spec.js
  playwright/tests/my/mymove/orders.spec.js
  src/components/Customer/DodInfoForm/DodInfoForm.jsx
  src/components/Customer/DodInfoForm/DodInfoForm.test.jsx
  src/components/Customer/EditOrdersForm/EditOrdersForm.jsx
  src/components/Customer/EditOrdersForm/EditOrdersForm.test.jsx
  src/components/Customer/OrdersInfoForm/OrdersInfoForm.jsx
  src/components/Customer/OrdersInfoForm/OrdersInfoForm.stories.jsx
  src/components/Customer/OrdersInfoForm/OrdersInfoForm.test.jsx
  src/constants/customerStates.js
  src/constants/routes.js
  src/pages/MyMove/EditOrders.jsx
  src/pages/MyMove/Orders.jsx
  src/pages/MyMove/Orders.test.jsx
  src/pages/MyMove/Profile/ContactInfo.jsx
  src/pages/MyMove/Profile/ContactInfo.test.jsx
  src/pages/MyMove/Profile/DodInfo.jsx
  src/pages/MyMove/Profile/DodInfo.test.jsx
  src/pages/MyMove/Profile/ResidentialAddress.jsx
  src/pages/MyMove/Profile/ResidentialAddress.test.jsx
  src/scenes/MyMove/getWorkflowRoutes.jsx
  src/scenes/MyMove/getWorkflowRoutes.test.js
  src/scenes/Office/OrdersViewerPanel.js
  src/store/entities/selectors.js
  src/store/entities/selectors.test.js
  src/utils/customer.js
  swagger-def/internal.yaml
  swagger/internal.yaml
Labels: Mountain Movers, INTEGRATION

#11831 B-18194-INT add auth check to weight ticket update
  pkg/services/weight_ticket/weight_ticket_updater.go
  pkg/services/weight_ticket/weight_ticket_updater_test.go
Labels: G-Unit, INTEGRATION

#11838 INT B-18386 Enhancements
  src/pages/MyMove/Multi-Moves/MultiMovesLandingPage.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesTestData.js
  src/shared/constants.js
  src/utils/featureFlags.js
Labels: Mountain Movers, INTEGRATION

#11819 B 18182 int remove old personally procured move
  pkg/gen/internalapi/configure_mymove.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalapi/internaloperations/mymove_api.go
  pkg/gen/internalapi/internaloperations/ppm/patch_personally_procured_move.go
  pkg/gen/internalapi/internaloperations/ppm/patch_personally_procured_move_parameters.go
  pkg/gen/internalapi/internaloperations/ppm/patch_personally_procured_move_responses.go
  pkg/gen/internalapi/internaloperations/ppm/patch_personally_procured_move_urlbuilder.go
  pkg/gen/internalapi/internaloperations/ppm/request_p_p_m_payment.go
  pkg/gen/internalapi/internaloperations/ppm/request_p_p_m_payment_parameters.go
  pkg/gen/internalapi/internaloperations/ppm/request_p_p_m_payment_responses.go
  pkg/gen/internalapi/internaloperations/ppm/request_p_p_m_payment_urlbuilder.go
  pkg/gen/internalapi/internaloperations/ppm/submit_personally_procured_move.go
  pkg/gen/internalapi/internaloperations/ppm/submit_personally_procured_move_parameters.go
  pkg/gen/internalapi/internaloperations/ppm/submit_personally_procured_move_responses.go
  pkg/gen/internalapi/internaloperations/ppm/submit_personally_procured_move_urlbuilder.go
  pkg/gen/internalmessages/patch_personally_procured_move_payload.go
  pkg/gen/internalmessages/submit_personally_procured_move_payload.go
  pkg/handlers/internalapi/api.go
  pkg/handlers/internalapi/moves.go
  pkg/handlers/internalapi/personally_procured_move.go
  pkg/services/event/internal_endpoint.go
  src/services/internalApi.js
  src/shared/Entities/modules/ppms.js
  swagger-def/internal.yaml
  swagger/internal.yaml
Labels: G-Unit, INTEGRATION

#11850 B 18480 int
  src/pages/Office/ReviewBillableWeight/ReviewBillableWeight.jsx
Labels: Mountain Movers, INTEGRATION

#11824 B-18193-INT API Fix Delete Weight Ticket
  pkg/handlers/internalapi/weight_ticket.go
  pkg/handlers/internalapi/weight_ticket_test.go
  pkg/services/mocks/WeightTicketDeleter.go
  pkg/services/weight_ticket.go
  pkg/services/weight_ticket/weight_ticket_deleter.go
  pkg/services/weight_ticket/weight_ticket_deleter_test.go
Labels: G-Unit, INTEGRATION

#11855 B 18161 int update email customer submitted moves
  migrations/app/migrations_manifest.txt
  pkg/assets/notifications/templates/move_submitted_template.html
  pkg/assets/notifications/templates/move_submitted_template.txt
  pkg/notifications/move_submitted.go
  pkg/notifications/move_submitted_test.go
Labels: ByteSize M&Ms, INTEGRATION

#11810 INT B-18411-UI-shipment-address-update-review-screen-updates-v2
  src/components/Office/AddressUpdatePreview/AddressUpdatePreview.jsx
  src/components/Office/AddressUpdatePreview/AddressUpdatePreview.test.jsx
  src/components/Office/ShipmentAddressUpdateReviewRequestModal/ShipmentAddressUpdateReviewRequestModal.jsx
Labels: Mountain Movers, INTEGRATION

#11795 B 18086 identify create values 13 17
  pkg/apperror/errors.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/p_p_m_closeout.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/ppm_closeout.go
  pkg/handlers/ghcapi/ppm_closeout_test.go
  pkg/services/ghcrateengine/shared.go
  pkg/services/mocks/PPMCloseoutFetcher.go
  pkg/services/ppm_closeout.go
  pkg/services/ppm_closeout/ppm_closeout.go
  pkg/services/ppm_closeout/ppm_closeout_service_test.go
  pkg/services/ppm_closeout/ppm_closeout_test.go
  pkg/services/ppmshipment/ppm_estimator.go
  swagger-def/definitions/PPMCloseout.yaml
  swagger/ghc.yaml
Labels: ByteSize M&Ms, INTEGRATION

#11847 B-18184 -INT removed deprecated ppm incentive endpoint
  migrations/app/migrations_manifest.txt
  pkg/gen/internalapi/configure_mymove.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalapi/internaloperations/mymove_api.go
  pkg/gen/internalapi/internaloperations/ppm/show_p_p_m_incentive.go
  pkg/gen/internalapi/internaloperations/ppm/show_p_p_m_incentive_parameters.go
  pkg/gen/internalapi/internaloperations/ppm/show_p_p_m_incentive_responses.go
  pkg/gen/internalapi/internaloperations/ppm/show_p_p_m_incentive_urlbuilder.go
  pkg/handlers/internalapi/api.go
  pkg/handlers/internalapi/personally_procured_move_incentive.go
  swagger-def/internal.yaml
  swagger/internal.yaml
Labels: G-Unit, INTEGRATION

#11813 B-18184 Removed Deprecated PPM Incentive endpoint
  pkg/gen/internalapi/configure_mymove.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalapi/internaloperations/mymove_api.go
  pkg/gen/internalapi/internaloperations/ppm/show_p_p_m_incentive.go
  pkg/gen/internalapi/internaloperations/ppm/show_p_p_m_incentive_parameters.go
  pkg/gen/internalapi/internaloperations/ppm/show_p_p_m_incentive_responses.go
  pkg/gen/internalapi/internaloperations/ppm/show_p_p_m_incentive_urlbuilder.go
  pkg/handlers/internalapi/api.go
  pkg/handlers/internalapi/personally_procured_move_incentive.go
  swagger-def/internal.yaml
  swagger/internal.yaml
Labels: G-Unit

#11845 B 18185 int removed personally procured move shared handler
  pkg/handlers/internalapi/personally_procured_move_shared.go
  pkg/handlers/internalapi/personally_procured_move_shared_test.go
Labels: G-Unit, INTEGRATION

#11848 B 18428 ssw form pdf work int
  cmd/generate-shipment-summary/main.go
  pkg/assets/paperwork/formtemplates/SSWPDFTemplate.pdf
  pkg/assets/paperwork/formtemplates/shipment_summary_worksheet_page1.png
  pkg/assets/paperwork/formtemplates/shipment_summary_worksheet_page2.png
  pkg/assets/paperwork/formtemplates/shipment_summary_worksheet_page3.png
  pkg/handlers/internalapi/moves.go
  pkg/paperwork/generator.go
  pkg/paperwork/shipment_summary_worksheet.go
  pkg/services/mocks/SSWPPMComputer.go
  pkg/services/shipment_summary_worksheet.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet_test.go
Labels: Scrummy Bears, INTEGRATION

#11884 INT-B-18180 removed ppm estimated weight
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/list_prime_move.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/list_move.go
  swagger-def/ghc.yaml
  swagger-def/prime.yaml
  swagger/ghc.yaml
  swagger/prime.yaml
Labels: G-Unit, INTEGRATION

#11877 B 18085 identify create values 7 12 integration
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/p_p_m_closeout.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/ppm_closeout_test.go
  pkg/models/ppm_shipment.go
  pkg/services/ppm_closeout/ppm_closeout.go
  pkg/services/ppm_closeout/ppm_closeout_test.go
  pkg/services/ppmshipment/ppm_estimator.go
  pkg/testdatagen/testharness/dispatch.go
  pkg/testdatagen/testharness/make_move.go
  swagger-def/definitions/PPMCloseout.yaml
  swagger/ghc.yaml
Labels: INTEGRATION

#11837 B-18312-multi-move-dashboard(MERGE-AFTER-B18310)(Merge-AFTER-B18309)(INTEGRATION)
  playwright/tests/my/milmove/ppms/about.spec.js
  playwright/tests/my/milmove/ppms/advances.spec.js
  playwright/tests/my/milmove/ppms/dateAndLocation.spec.js
  playwright/tests/my/milmove/ppms/entireShipmentCloseout.spec.js
  playwright/tests/my/milmove/ppms/entireShipmentOnboarding.spec.js
  playwright/tests/my/milmove/ppms/estimatedIncentive.spec.js
  playwright/tests/my/milmove/ppms/estimatedWeightsProgear.spec.js
  playwright/tests/my/milmove/ppms/expenses.spec.js
  playwright/tests/my/milmove/ppms/finalCloseout.spec.js
  playwright/tests/my/milmove/ppms/navigateToUploadDocs.spec.js
  playwright/tests/my/milmove/ppms/progear.spec.js
  playwright/tests/my/milmove/ppms/review.spec.js
  playwright/tests/my/milmove/ppms/weightTickets.spec.js
  playwright/tests/my/mymove/hhg.spec.js
  playwright/tests/my/mymove/nts.spec.js
  playwright/tests/my/mymove/ntsr.spec.js
  playwright/tests/my/mymove/onboarding.spec.js
  playwright/tests/my/mymove/orders.spec.js
  playwright/tests/my/mymove/uploads.spec.js
  playwright/tests/utils/my/customerTest.js
  playwright/tests/utils/my/waitForCustomerPage.js
  src/constants/routes.js
  src/pages/MyMove/Multi-Moves/MultiMovesLandingPage.jsx
  src/scenes/MyMove/index.jsx
Labels: Mountain Movers, INTEGRATION

#11859 INT B-18313 Multi-Moves Profile Validation & Create a Move Btn Functionality INTEGRATION (PUSH AFTER B-18312)
  src/components/Customer/Profile/ContactInfoDisplay/ContactInfoDisplay.jsx
  src/components/Customer/Profile/OktaInfoDisplay/OktaInfoDisplay.jsx
  src/components/Customer/Review/ServiceInfoDisplay/ServiceInfoDisplay.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesLandingPage.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesLandingPage.test.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesMoveContainer/MultiMovesMoveContainer.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesMoveContainer/MultiMovesMoveContainer.test.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesMoveInfoList/MultiMovesInfoList.test.jsx
  src/pages/MyMove/Profile/EditContactInfo.jsx
  src/pages/MyMove/Profile/EditContactInfo.test.jsx
  src/pages/MyMove/Profile/EditOktaInfo.jsx
  src/pages/MyMove/Profile/EditOktaInfo.test.jsx
  src/pages/MyMove/Profile/EditOrdersPayGradeAndOriginLocation.test.jsx
  src/pages/MyMove/Profile/EditServiceInfo.jsx
  src/pages/MyMove/Profile/EditServiceInfo.test.jsx
  src/pages/MyMove/Profile/Profile.jsx
  src/pages/MyMove/Profile/Profile.module.scss
  src/pages/MyMove/Profile/Profile.test.jsx
Labels: Mountain Movers, INTEGRATION

#11846 B 17854 calculate authorized end date in updateMTOServiceItem Prime API
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240119005610_add_authorized_end_date_to_mto_services_items.up.sql
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/s_i_t_status.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/primeapi/mto_service_item.go
  pkg/models/mto_service_items.go
  pkg/services/mocks/MTOServiceItemUpdater.go
  pkg/services/mto_service_item.go
  pkg/services/mto_service_item/mto_service_item_updater.go
  pkg/services/mto_service_item/mto_service_item_updater_test.go
  pkg/services/mto_shipment.go
  pkg/services/sit_status/shipment_sit_status.go
  src/components/Office/ShipmentSITDisplay/ShipmentSITDisplay.jsx
  src/components/Office/ShipmentSITDisplay/ShipmentSITDisplay.test.jsx
  src/components/Office/ShipmentSITDisplay/ShipmentSITDisplayTestParams.js
  swagger-def/definitions/SITStatus.yaml
  swagger/ghc.yaml
Labels: Scrummy Bears, INTEGRATION

#11854 INT-B-18449 removed deprecated ppmid from signedcertification model
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240124153121_remove_ppmid_from_signedcertification_table.up.sql
  pkg/factory/signed_certification_factory.go
  pkg/factory/signed_certification_factory_test.go
  pkg/handlers/internalapi/internal/payloads/payload_to_model.go
  pkg/handlers/internalapi/signed_certifications.go
  pkg/handlers/internalapi/signed_certifications_test.go
  pkg/models/move.go
  pkg/models/signed_certification.go
  pkg/models/signed_certification_test.go
  pkg/services/ppmshipment/ppm_shipment_fetcher_test.go
  pkg/services/signed_certification/rules.go
  pkg/services/signed_certification/rules_test.go
  pkg/services/signed_certification/signed_certification_updater_test.go
Labels: G-Unit, INTEGRATION

#11843 B 18186-INT remove ppm code completer
  migrations/app/migrations_manifest.txt
  pkg/gen/internalapi/configure_mymove.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalapi/internaloperations/mymove_api.go
  pkg/gen/internalapi/internaloperations/office/approve_p_p_m.go
  pkg/gen/internalapi/internaloperations/office/approve_p_p_m_parameters.go
  pkg/gen/internalapi/internaloperations/office/approve_p_p_m_responses.go
  pkg/gen/internalapi/internaloperations/office/approve_p_p_m_urlbuilder.go
  pkg/gen/internalmessages/approve_personally_procured_move_payload.go
  pkg/gen/internalmessages/create_personally_procured_move_payload.go
  pkg/gen/internalmessages/p_p_m_incentive.go
  pkg/gen/internalmessages/update_personally_procured_move_payload.go
  pkg/handlers/authentication/auth.go
  pkg/handlers/internalapi/api.go
  pkg/handlers/internalapi/office.go
  pkg/handlers/internalapi/office_test.go
  pkg/services/event/internal_endpoint.go
  src/appReducer.js
  src/shared/Entities/modules/ppms.js
  swagger-def/internal.yaml
  swagger/internal.yaml
Labels: G-Unit, INTEGRATION

#11889 kickback B-18322 Update Requested pickup date
  pkg/gen/ghcapi/embedded_spec.go
  src/components/Office/ImportantShipmentDates/ImportantShipmentDates.jsx
  src/components/Office/ImportantShipmentDates/ImportantShipmentDates.test.jsx
  src/components/Office/ShipmentDetails/ShipmentDetailsMain.jsx
  swagger/ghc.yaml
Labels: ByteSize M&Ms, INTEGRATION

#11876 B-18109 I-12397 diverted shipments int
  src/hooks/custom.js
Labels: Mountain Movers, INTEGRATION

#11866 B 18317 multi move get all moves endpoint (Integration)
  pkg/gen/internalapi/configure_mymove.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalapi/internaloperations/moves/get_all_moves.go
  pkg/gen/internalapi/internaloperations/moves/get_all_moves_parameters.go
  pkg/gen/internalapi/internaloperations/moves/get_all_moves_responses.go
  pkg/gen/internalapi/internaloperations/moves/get_all_moves_urlbuilder.go
  pkg/gen/internalapi/internaloperations/mymove_api.go
  pkg/gen/internalmessages/internal_move.go
  pkg/gen/internalmessages/moves_list.go
  pkg/handlers/internalapi/api.go
  pkg/handlers/internalapi/moves.go
  pkg/handlers/internalapi/moves_test.go
  pkg/models/move.go
  pkg/models/move_test.go
  swagger-def/internal.yaml
  swagger/internal.yaml
Labels: Mountain Movers, INTEGRATION
