Repository transcom/mymove, pull requests merged in 2024-07, with the labels that each got.

#13144 B 19724 int
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/customer/search_customers.go
  pkg/gen/ghcapi/ghcoperations/move/search_moves.go
  pkg/gen/ghcapi/ghcoperations/queues/get_moves_queue_parameters.go
  pkg/gen/ghcapi/ghcoperations/queues/get_moves_queue_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/queues/get_payment_requests_queue_parameters.go
  pkg/gen/ghcapi/ghcoperations/queues/get_payment_requests_queue_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/queues/get_services_counseling_queue_parameters.go
  pkg/gen/ghcapi/ghcoperations/queues/get_services_counseling_queue_urlbuilder.go
  pkg/gen/ghcmessages/search_customer.go
  pkg/gen/ghcmessages/search_move.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/move.go
  pkg/handlers/ghcapi/move_test.go
  pkg/handlers/ghcapi/queues.go
  pkg/services/customer.go
  pkg/services/move.go
  pkg/services/move/move_searcher.go
  pkg/services/office_user/customer/customer_searcher.go
  pkg/services/order.go
  pkg/services/order/order_fetcher.go
  pkg/services/payment_request.go
  pkg/services/payment_request/payment_request_list_fetcher.go
  pkg/services/payment_request/payment_request_list_fetcher_test.go
  src/components/Table/SearchResultsTable.jsx
  src/components/Table/SearchResultsTable.test.jsx
  src/pages/Office/MoveQueue/MoveQueue.jsx
  src/pages/Office/MoveQueue/MoveQueue.test.jsx
  src/pages/Office/PaymentRequestQueue/PaymentRequestQueue.jsx
  src/pages/Office/PaymentRequestQueue/PaymentRequestQueue.test.jsx
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.jsx
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.test.jsx
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: G-Unit, INTEGRATION

#13170 B-20305: FSC Weight Based Distance Multiplier On Reweigh
  pkg/payment_request/service_param_value_lookups/weight_billed_lookup.go
Labels: Mountain Movers, INTEGRATION

#13171 B-20334 I-13046 Remove extra spaces from LOA string MAIN
  src/pages/Office/Orders/Orders.jsx
  src/pages/Office/Orders/Orders.test.jsx
  src/pages/Office/ServicesCounselingOrders/ServicesCounselingOrders.jsx
  src/pages/Office/ServicesCounselingOrders/ServicesCounselingOrders.test.jsx
Labels: Mountain Movers, MAIN

#13177 B-20312 Update shipment pickup verbiage INT
  go.mod
  go.sum
  src/components/Customer/MtoShipmentForm/MtoShipmentForm.jsx
  src/components/Customer/MtoShipmentForm/MtoShipmentForm.test.jsx
Labels: Mountain Movers, INTEGRATION

#13178 B20270-INT-Customer can view uploaded docs
  playwright/fixtures/amendedOrders.pdf
  playwright/fixtures/secondOrders.pdf
  playwright/fixtures/trustedAgent.pdf
  playwright/tests/my/mymove/additionalDocs.spec.js
  playwright/tests/my/mymove/orders.spec.js
  src/components/Customer/EditOrdersForm/EditOrdersForm.jsx
  src/components/UploadsTable/UploadsTable.jsx
  src/pages/MyMove/AdditionalDocuments/AdditionalDocuments.jsx
  src/pages/MyMove/AmendOrders/AmendOrders.jsx
Labels: ByteSize M&Ms, INTEGRATION

#13188 B 20303 int
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/customer.go
  pkg/gen/primev2api/embedded_spec.go
  pkg/gen/primev2messages/customer.go
  pkg/gen/primev3api/embedded_spec.go
  pkg/gen/primev3messages/customer.go
  pkg/handlers/primeapi/payloads/model_to_payload.go
  pkg/handlers/primeapiv2/payloads/model_to_payload.go
  pkg/handlers/primeapiv3/payloads/model_to_payload.go
  swagger-def/definitions/prime/Customer.yaml
  swagger/prime.yaml
  swagger/prime_v2.yaml
  swagger/prime_v3.yaml
Labels: G-Unit, INTEGRATION

#13173 Main b 19872
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/move.go
  pkg/gen/ghcmessages/move_payload.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload_test.go
  pkg/handlers/ghcapi/move.go
  pkg/handlers/ghcapi/move_task_order.go
  pkg/handlers/ghcapi/orders.go
  pkg/services/move/move_fetcher.go
  src/components/Office/ServicesCounselingTabNav/ServicesCounselingTabNav.jsx
  src/components/Office/ServicesCounselingTabNav/ServicesCounselingTabNav.module.scss
  src/components/Office/ServicesCounselingTabNav/ServicesCounselingTabNav.test.jsx
  src/components/Office/TXOTabNav/TXOTabNav.jsx
  src/components/Office/TXOTabNav/TXOTabNav.module.scss
  src/components/Office/TXOTabNav/TXOTabNav.test.jsx
  src/constants/routes.js
  src/hooks/queries.js
  src/pages/Office/ServicesCounselingMoveInfo/ServicesCounselingMoveInfo.jsx
  src/pages/Office/ServicesCounselingMoveInfo/ServicesCounselingMoveInfo.test.jsx
  src/pages/Office/SupportingDocuments/SupportingDocuments.jsx
  src/pages/Office/SupportingDocuments/SupportingDocuments.test.jsx
  src/pages/Office/TXOMoveInfo/TXOMoveInfo.jsx
  src/pages/Office/TXOMoveInfo/TXOMoveInfo.test.jsx
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: ByteSize M&Ms, MAIN

#13189 INT B-19789 fe office user ability to manage docs
  go.mod
  go.sum
  package.json
  pkg/gen/ghcapi/embedded_spec.go
  pkg/handlers/authentication/permissions.go
  pkg/handlers/ghcapi/documents.go
  playwright/tests/office/servicescounseling/servicesCounselingFlows.spec.js
  src/components/ConfirmationModals/DeleteDocumentFileConfirmationModal.jsx
  src/components/ConfirmationModals/DeleteDocumentFileConfirmationModal.module.scss
  src/components/ConfirmationModals/DeleteDocumentFileConfirmationModal.stories.jsx
  src/components/ConfirmationModals/DeleteDocumentFileConfirmationModal.test.jsx
  src/components/DocumentViewer/DocumentViewer.jsx
  src/components/DocumentViewerFileManager/DocumentViewerFileManager.jsx
  src/components/DocumentViewerFileManager/DocumentViewerFileManager.module.scss
  src/components/DocumentViewerFileManager/DocumentViewerFileManager.stories.jsx
  src/components/DocumentViewerFileManager/DocumentViewerFileManager.test.jsx
  src/components/UploadsTable/UploadsTable.jsx
  src/constants/permissions.js
  src/hooks/queries.js
  src/hooks/queries.test.jsx
  src/pages/Office/MoveDocumentWrapper/MoveDocumentWrapper.jsx
  src/pages/Office/MoveDocumentWrapper/MoveDocumentWrapper.test.jsx
  src/pages/Office/Orders/Orders.jsx
  src/pages/Office/Orders/Orders.test.jsx
  src/pages/Office/ServicesCounselingMoveDocumentWrapper/ServicesCounselingMoveDocumentWrapper.jsx
  src/pages/Office/ServicesCounselingMoveDocumentWrapper/ServicesCounselingMoveDocumentWrapper.test.jsx
  src/pages/Office/ServicesCounselingMoveInfo/ServicesCounselingMoveInfo.jsx
  src/pages/Office/ServicesCounselingOrders/ServicesCounselingOrders.jsx
  src/pages/Office/ServicesCounselingOrders/ServicesCounselingOrders.test.jsx
  src/pages/Office/SupportingDocuments/SupportingDocuments.jsx
  src/pages/Office/SupportingDocuments/SupportingDocuments.test.jsx
  src/pages/Office/TXOMoveInfo/TXOMoveInfo.jsx
  src/services/ghcApi.js
  src/shared/constants.js
  src/styles/documentViewerWithSidebar.module.scss
  swagger-def/ghc.yaml
  swagger/ghc.yaml
  yarn.lock
Labels: ByteSize M&Ms, INTEGRATION

#13175 B 19935 int
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240628181051_drop_ppm_postal_code_fields.up.sql
  migrations/app/schema/20240628185537_update_move_to_gbloc_to_use_ppm_address.up.sql
Labels: Scrummy Bears, INTEGRATION

#13176 B 19772 change closeout queue filter be int
  pkg/services/order/order_fetcher.go
  pkg/services/order/order_fetcher_test.go
Labels: ByteSize M&Ms, INTEGRATION

#13131 B 20289 int
  cmd/generate-shipment-summary/main.go
  pkg/handlers/ghcapi/ppm_document.go
  pkg/handlers/ghcapi/ppm_document_test.go
  pkg/handlers/internalapi/ppm_shipment.go
  pkg/handlers/internalapi/ppm_shipment_test.go
  pkg/services/mocks/AOAPacketCreator.go
  pkg/services/mocks/SSWPPMComputer.go
  pkg/services/ppmshipment.go
  pkg/services/ppmshipment/aoa_packet_creator.go
  pkg/services/ppmshipment/aoa_packet_creator_test.go
  pkg/services/ppmshipment/payment_packet_creator.go
  pkg/services/ppmshipment/payment_packet_creator_test.go
  pkg/services/shipment_summary_worksheet.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet_test.go
Labels: Scrummy Bears, INTEGRATION

#13182 INT B-20011-13-14 (Follow Up)
  .envrc
  src/pages/Office/HeadquartersQueues/HeadquartersQueues.jsx
  src/pages/Office/MoveQueue/MoveQueue.jsx
  src/pages/Office/PaymentRequestQueue/PaymentRequestQueue.jsx
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.jsx
Labels: Scrummy Bears, INTEGRATION

#13201 B-19686 Tertiary destination address bugfix
  go.mod
  go.sum
  src/pages/MyMove/PPM/Booking/DateAndLocation/DateAndLocation.jsx
Labels: G-Unit, INTEGRATION

#13204 B 19772 change closeout queue filter be main
  pkg/services/order/order_fetcher.go
  pkg/services/order/order_fetcher_test.go
Labels: ByteSize M&Ms, MAIN

#13158 B 20076 int
  pkg/payment_request/service_param_value_lookups/weight_billed_lookup_test.go
  pkg/services/mto_shipment/mto_shipment_updater.go
  pkg/services/mto_shipment/shipment_approver.go
  pkg/services/mto_shipment/shipment_billable_weight.go
  pkg/testdatagen/scenario/e2ebasic.go
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/testharness/make_move.go
  playwright/tests/office/txo/tioUpdateMaxBillableWeight.spec.js
  src/components/Office/BillableWeight/BillableWeightCard/BillableWeightCard.jsx
  src/components/Office/BillableWeight/BillableWeightCard/BillableWeightCard.test.jsx
  src/components/Office/BillableWeight/ShipmentCard/ShipmentCard.jsx
  src/components/Office/BillableWeight/ShipmentCard/ShipmentCard.test.jsx
  src/components/Office/WeightSummary/WeightSummary.jsx
  src/components/ShipmentList/ShipmentList.jsx
  src/constants/shipments.js
  src/hooks/custom.js
  src/hooks/custom.test.js
  src/pages/Office/MovePaymentRequests/MovePaymentRequests.jsx
  src/pages/Office/MovePaymentRequests/MovePaymentRequests.test.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.module.scss
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.test.jsx
  src/pages/Office/MoveTaskOrder/moveTaskOrderUnitTestData.js
  src/pages/Office/ReviewBillableWeight/ReviewBillableWeight.jsx
  src/pages/Office/ReviewBillableWeight/ReviewBillableWeight.test.jsx
  src/pages/Office/ServicesCounselingReviewShipmentWeights/ServicesCounselingReviewShipmentWeights.test.jsx
  src/utils/shipmentWeights.js
  src/utils/shipmentWeights.test.js
Labels: Scrummy Bears, INTEGRATION

#13126 Main b 19788 backend - office user ability to manage docs
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240625144828_add_to_update_type_enum.up.sql
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/ghc_documents/create_document.go
  pkg/gen/ghcapi/ghcoperations/ghc_documents/create_document_parameters.go
  pkg/gen/ghcapi/ghcoperations/ghc_documents/create_document_responses.go
  pkg/gen/ghcapi/ghcoperations/ghc_documents/create_document_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/move/upload_additional_documents.go
  pkg/gen/ghcapi/ghcoperations/move/upload_additional_documents_parameters.go
  pkg/gen/ghcapi/ghcoperations/move/upload_additional_documents_responses.go
  pkg/gen/ghcapi/ghcoperations/move/upload_additional_documents_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/ghcapi/ghcoperations/order/upload_amended_orders.go
  pkg/gen/ghcapi/ghcoperations/order/upload_amended_orders_parameters.go
  pkg/gen/ghcapi/ghcoperations/order/upload_amended_orders_responses.go
  pkg/gen/ghcapi/ghcoperations/order/upload_amended_orders_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/uploads/delete_upload.go
  pkg/gen/ghcapi/ghcoperations/uploads/delete_upload_parameters.go
  pkg/gen/ghcapi/ghcoperations/uploads/delete_upload_responses.go
  pkg/gen/ghcapi/ghcoperations/uploads/delete_upload_urlbuilder.go
  pkg/gen/ghcmessages/invalid_request_response_payload.go
  pkg/gen/ghcmessages/order.go
  pkg/gen/ghcmessages/post_document_payload.go
  pkg/gen/ghcmessages/upload.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/upload.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/documents.go
  pkg/handlers/ghcapi/documents_test.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/move.go
  pkg/handlers/ghcapi/move_test.go
  pkg/handlers/ghcapi/orders.go
  pkg/handlers/ghcapi/orders_test.go
  pkg/handlers/ghcapi/uploads.go
  pkg/handlers/internalapi/internal/payloads/model_to_payload.go
  pkg/handlers/internalapi/moves.go
  pkg/handlers/internalapi/uploads.go
  pkg/models/upload.go
  pkg/models/upload_test.go
  pkg/models/user_upload.go
  pkg/services/mocks/OrderUpdater.go
  pkg/services/move.go
  pkg/services/move/additional_documents_uploader.go
  pkg/services/move/additional_documents_uploader_test.go
  pkg/services/order.go
  pkg/services/order/order_updater.go
  pkg/uploader/create_user_upload.go
  pkg/uploader/user_uploader.go
  swagger-def/definitions/Upload.yaml
  swagger-def/ghc.yaml
  swagger/ghc.yaml
  swagger/internal.yaml
Labels: ByteSize M&Ms, MAIN

#13205 B20270-MAIN-Customer can view uploaded docs
  playwright/fixtures/amendedOrders.pdf
  playwright/fixtures/secondOrders.pdf
  playwright/fixtures/trustedAgent.pdf
  playwright/tests/my/mymove/additionalDocs.spec.js
  playwright/tests/my/mymove/orders.spec.js
  src/components/Customer/EditOrdersForm/EditOrdersForm.jsx
  src/components/UploadsTable/UploadsTable.jsx
  src/pages/MyMove/AdditionalDocuments/AdditionalDocuments.jsx
  src/pages/MyMove/AmendOrders/AmendOrders.jsx
Labels: ByteSize M&Ms, MAIN

#13166 B 20290 int add amount reimbursement
  go.mod
  go.sum
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240624215947_add_sit_reimburseable_amount.up.sql
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/moving_expense.go
  pkg/gen/ghcmessages/update_moving_expense.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/moving_expense.go
  pkg/gen/internalmessages/update_moving_expense.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/internal/payloads/payload_to_model.go
  pkg/handlers/internalapi/internal/payloads/model_to_payload.go
  pkg/handlers/internalapi/internal/payloads/payload_to_model.go
  pkg/models/moving_expense.go
  pkg/services/moving_expense/moving_expense_updater.go
  pkg/services/moving_expense/moving_expense_updater_test.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet.go
  src/components/Office/PPM/ReviewDocumentsSidePanel/ReviewDocumentsSidePanel.jsx
  src/components/Office/PPM/ReviewExpense/ReviewExpense.jsx
  src/components/Office/PPM/ReviewExpense/ReviewExpense.test.jsx
  src/components/Office/PPM/SitCost/SitCost.jsx
  swagger-def/definitions/MovingExpense.yaml
  swagger-def/ghc.yaml
  swagger-def/internal.yaml
  swagger/ghc.yaml
  swagger/internal.yaml
Labels: Scrummy Bears, INTEGRATION

#13159 B19774 MAIN 20240627
  src/components/Office/ShipmentCustomerSIT/ShipmentCustomerSIT.jsx
  src/components/Office/ShipmentForm/ShipmentForm.jsx
  src/components/Office/ShipmentForm/ppmShipmentSchema.js
  src/components/Office/ShipmentWeight/ShipmentWeight.jsx
  src/pages/Office/ServicesCounselingEditShipmentDetails/ServicesCounselingEditShipmentDetails.test.jsx
Labels: ByteSize M&Ms, MAIN

#13035 B-19726-INT Add EMPLID to SC Customer create
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/customer/create_customer_with_okta_option.go
  pkg/gen/ghcapi/ghcoperations/customer/create_customer_with_okta_option_responses.go
  pkg/gen/ghcmessages/create_customer_payload.go
  pkg/handlers/ghcapi/customer.go
  pkg/handlers/ghcapi/customer_test.go
  pkg/handlers/ghcapi/orders.go
  pkg/models/service_member.go
  src/pages/Office/CustomerOnboarding/CreateCustomerForm.jsx
  src/pages/Office/CustomerOnboarding/CreateCustomerForm.test.jsx
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: G-Unit, INTEGRATION

#13153 MAIN B-19789 frontend - office user ability to manage docs
  pkg/gen/ghcapi/embedded_spec.go
  pkg/handlers/authentication/permissions.go
  pkg/handlers/ghcapi/documents.go
  playwright/tests/office/servicescounseling/servicesCounselingFlows.spec.js
  src/components/ConfirmationModals/DeleteDocumentFileConfirmationModal.jsx
  src/components/ConfirmationModals/DeleteDocumentFileConfirmationModal.module.scss
  src/components/ConfirmationModals/DeleteDocumentFileConfirmationModal.stories.jsx
  src/components/ConfirmationModals/DeleteDocumentFileConfirmationModal.test.jsx
  src/components/DocumentViewer/DocumentViewer.jsx
  src/components/DocumentViewerFileManager/DocumentViewerFileManager.jsx
  src/components/DocumentViewerFileManager/DocumentViewerFileManager.module.scss
  src/components/DocumentViewerFileManager/DocumentViewerFileManager.stories.jsx
  src/components/DocumentViewerFileManager/DocumentViewerFileManager.test.jsx
  src/components/UploadsTable/UploadsTable.jsx
  src/constants/permissions.js
  src/hooks/queries.js
  src/hooks/queries.test.jsx
  src/pages/Office/MoveDocumentWrapper/MoveDocumentWrapper.jsx
  src/pages/Office/MoveDocumentWrapper/MoveDocumentWrapper.test.jsx
  src/pages/Office/Orders/Orders.jsx
  src/pages/Office/Orders/Orders.test.jsx
  src/pages/Office/ServicesCounselingMoveDocumentWrapper/ServicesCounselingMoveDocumentWrapper.jsx
  src/pages/Office/ServicesCounselingMoveDocumentWrapper/ServicesCounselingMoveDocumentWrapper.test.jsx
  src/pages/Office/ServicesCounselingMoveInfo/ServicesCounselingMoveInfo.jsx
  src/pages/Office/ServicesCounselingOrders/ServicesCounselingOrders.jsx
  src/pages/Office/ServicesCounselingOrders/ServicesCounselingOrders.test.jsx
  src/pages/Office/SupportingDocuments/SupportingDocuments.jsx
  src/pages/Office/SupportingDocuments/SupportingDocuments.test.jsx
  src/pages/Office/TXOMoveInfo/TXOMoveInfo.jsx
  src/services/ghcApi.js
  src/shared/constants.js
  src/styles/documentViewerWithSidebar.module.scss
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: ByteSize M&Ms, MAIN

#13160 B-20012 INT - GBLOC Switching for HQ User
  package.json
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/queues/get_moves_queue_parameters.go
  pkg/gen/ghcapi/ghcoperations/queues/get_moves_queue_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/queues/get_payment_requests_queue_parameters.go
  pkg/gen/ghcapi/ghcoperations/queues/get_payment_requests_queue_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/queues/get_services_counseling_queue_parameters.go
  pkg/gen/ghcapi/ghcoperations/queues/get_services_counseling_queue_urlbuilder.go
  pkg/handlers/ghcapi/queues.go
  pkg/services/order.go
  pkg/services/order/order_fetcher.go
  pkg/services/order/order_fetcher_test.go
  pkg/services/payment_request.go
  pkg/services/payment_request/payment_request_list_fetcher.go
  playwright/tests/my/mymove/additionalDocs.spec.js
  src/components/ButtonDropdown/ButtonDropdown.jsx
  src/components/Office/GblocSwitcher/GblocSwitcher.jsx
  src/components/Office/GblocSwitcher/GblocSwitcher.module.scss
  src/components/Office/GblocSwitcher/GblocSwitcher.stories.jsx
  src/components/Office/GblocSwitcher/SelectedGblocContext.js
  src/components/Office/GblocSwitcher/SelectedGblocProvider.jsx
  src/components/Table/TableQueue.jsx
  src/constants/queues.js
  src/containers/Headers/OfficeLoggedInHeader.jsx
  src/containers/Headers/OfficeLoggedInHeader.test.jsx
  src/hooks/queries.js
  src/layout/LogoutOnInactivity.jsx
  src/pages/Office/HeadquartersQueues/HeadquartersQueues.test.jsx
  src/pages/Office/index.jsx
  src/services/ghcApi.js
  src/testUtils.jsx
  swagger-def/ghc.yaml
  swagger/ghc.yaml
  yarn.lock
Labels: Scrummy Bears, INTEGRATION

#13206 B-20305: FSC Weight Based Distance Multiplier On Reweigh
  pkg/payment_request/service_param_value_lookups/weight_billed_lookup.go
Labels: Mountain Movers, MAIN

#13125 B-20072
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/ghcapi/ghcoperations/queues/get_moves_queue_parameters.go
  pkg/gen/ghcapi/ghcoperations/queues/get_moves_queue_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/queues/get_services_counseling_origin_list.go
  pkg/gen/ghcapi/ghcoperations/queues/get_services_counseling_origin_list_parameters.go
  pkg/gen/ghcapi/ghcoperations/queues/get_services_counseling_origin_list_responses.go
  pkg/gen/ghcapi/ghcoperations/queues/get_services_counseling_origin_list_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/queues/get_services_counseling_queue_parameters.go
  pkg/gen/ghcapi/ghcoperations/queues/get_services_counseling_queue_urlbuilder.go
  pkg/gen/ghcmessages/location.go
  pkg/gen/ghcmessages/locations.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/queues.go
  pkg/handlers/ghcapi/queues_test.go
  pkg/models/privileges.go
  pkg/services/mocks/OrderFetcher.go
  pkg/services/order.go
  pkg/services/order/order_fetcher.go
  pkg/services/order/order_fetcher_test.go
  src/components/Table/Filters/MultiSelectTypeAheadCheckBoxFilter.module.scss
  src/components/Table/Filters/MultiSelectTypeAheadCheckboxFilter.test.jsx
  src/components/Table/Filters/MutliSelectTypeAheadCheckboxFilter.jsx
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.jsx
  src/pages/Office/index.jsx
  src/services/ghcApi.js
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: Scrummy Bears, MAIN

#13209 B 20079
  src/components/Office/WeightSummary/WeightSummary.jsx
  src/components/Office/WeightSummary/WeightSummary.test.jsx
Labels: Scrummy Bears, MAIN

#13208 B 20069
  playwright/tests/office/txo/tioFlows.spec.js
  src/components/Office/BillableWeight/BillableWeightCard/BillableWeightCard.jsx
  src/components/Office/BillableWeight/BillableWeightCard/BillableWeightCard.test.jsx
  src/components/ShipmentList/ShipmentList.jsx
  src/components/ShipmentList/ShipmentList.test.jsx
  src/shared/ToolTip/ToolTip.jsx
Labels: Scrummy Bears, MAIN

#13220 B 20076 int V2
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
Labels: Scrummy Bears, INTEGRATION

#13222 B 20289 int
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet_test.go
Labels: Scrummy Bears, INTEGRATION

#13154 B 20076 MAIN
  pkg/payment_request/service_param_value_lookups/weight_billed_lookup_test.go
  pkg/services/mto_shipment/mto_shipment_updater.go
  pkg/services/mto_shipment/shipment_approver.go
  pkg/services/mto_shipment/shipment_billable_weight.go
  pkg/testdatagen/scenario/e2ebasic.go
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/testharness/make_move.go
  playwright/tests/office/txo/tioUpdateMaxBillableWeight.spec.js
  src/components/Office/BillableWeight/BillableWeightCard/BillableWeightCard.jsx
  src/components/Office/BillableWeight/BillableWeightCard/BillableWeightCard.test.jsx
  src/components/Office/BillableWeight/ShipmentCard/ShipmentCard.jsx
  src/components/Office/BillableWeight/ShipmentCard/ShipmentCard.test.jsx
  src/components/Office/WeightSummary/WeightSummary.jsx
  src/components/ShipmentList/ShipmentList.jsx
  src/constants/shipments.js
  src/hooks/custom.js
  src/hooks/custom.test.js
  src/pages/Office/MovePaymentRequests/MovePaymentRequests.jsx
  src/pages/Office/MovePaymentRequests/MovePaymentRequests.test.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.module.scss
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.test.jsx
  src/pages/Office/MoveTaskOrder/moveTaskOrderUnitTestData.js
  src/pages/Office/ReviewBillableWeight/ReviewBillableWeight.jsx
  src/pages/Office/ReviewBillableWeight/ReviewBillableWeight.test.jsx
  src/pages/Office/ServicesCounselingReviewShipmentWeights/ServicesCounselingReviewShipmentWeights.test.jsx
  src/utils/shipmentWeights.js
  src/utils/shipmentWeights.test.js
Labels: Scrummy Bears, MAIN

#13210 B 19886 int2
  package.json
  src/components/Office/PPM/ReviewExpense/ReviewExpense.jsx
  yarn.lock
Labels: Scrummy Bears, INTEGRATION

#13223 B 20289 ssw weight
  cmd/generate-shipment-summary/main.go
  pkg/handlers/ghcapi/ppm_document.go
  pkg/handlers/ghcapi/ppm_document_test.go
  pkg/handlers/internalapi/ppm_shipment.go
  pkg/handlers/internalapi/ppm_shipment_test.go
  pkg/services/mocks/AOAPacketCreator.go
  pkg/services/mocks/SSWPPMComputer.go
  pkg/services/ppmshipment.go
  pkg/services/ppmshipment/aoa_packet_creator.go
  pkg/services/ppmshipment/aoa_packet_creator_test.go
  pkg/services/ppmshipment/payment_packet_creator.go
  pkg/services/ppmshipment/payment_packet_creator_test.go
  pkg/services/shipment_summary_worksheet.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet_test.go
Labels: Scrummy Bears, MAIN

#13183 INT-B-20078: Office Queue Pill Button Filters
  go.mod
  go.sum
  migrations/app/migrations_manifest.txt
  package.json
  playwright/tests/office/servicescounseling/servicesCounselingQueueFilters.spec.js
  playwright/tests/office/txo/sitUpdates.spec.js
  playwright/tests/office/txo/tooFlows.spec.js
  playwright/tests/office/txo/tooFlowsNTS.spec.js
  playwright/tests/office/txo/tooFlowsNTSR.spec.js
  src/components/Table/Filters/MultiSelectCheckBoxFilter.jsx
  src/components/Table/Filters/MultiSelectCheckBoxFilter.module.scss
  src/components/Table/Filters/MultiSelectCheckBoxFilter.test.jsx
  src/components/Table/Filters/MultiSelectTypeAheadCheckboxFilter.test.jsx
  src/components/Table/Filters/MutliSelectTypeAheadCheckboxFilter.jsx
  src/components/Table/Filters/SelectFilter.jsx
  src/components/Table/Filters/TextBoxFilter.jsx
  src/components/Table/TableQueue.jsx
  src/components/Table/TableQueue.module.scss
  src/components/Table/TableQueue.test.jsx
  src/components/Table/utils.js
  src/components/Table/utils.test.js
  src/containers/Headers/OfficeLoggedInHeader.jsx
  src/containers/Headers/OfficeLoggedInHeader.test.jsx
  src/pages/Office/HeadquartersQueues/HeadquartersQueues.jsx
  src/pages/Office/MoveHistory/MoveHistory.jsx
  src/pages/Office/MoveQueue/MoveQueue.jsx
  src/pages/Office/PaymentRequestQueue/PaymentRequestQueue.jsx
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.jsx
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.test.jsx
  src/pages/PrimeUI/AvailableMoves/AvailableMovesQueue.jsx
  yarn.lock
Labels: Scrummy Bears, INTEGRATION

#13211 B-19724-INT-KB bugfix for sort on dodid customer search
  pkg/services/office_user/customer/customer_searcher.go
Labels: G-Unit, INTEGRATION

#13187 B-20303 - update prime api with emplid
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/customer.go
  pkg/gen/primev2api/embedded_spec.go
  pkg/gen/primev2messages/customer.go
  pkg/gen/primev3api/embedded_spec.go
  pkg/gen/primev3messages/customer.go
  pkg/handlers/primeapi/payloads/model_to_payload.go
  pkg/handlers/primeapiv2/payloads/model_to_payload.go
  pkg/handlers/primeapiv3/payloads/model_to_payload.go
  swagger-def/definitions/prime/Customer.yaml
  swagger/prime.yaml
  swagger/prime_v2.yaml
  swagger/prime_v3.yaml
Labels: G-Unit, MAIN

#13232 B 20012 INT GBLOC Endpoint Followup
  go.mod
  go.sum
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/ghcapi/ghcoperations/transportation_office/get_transportation_offices_g_b_l_o_cs.go
  pkg/gen/ghcapi/ghcoperations/transportation_office/get_transportation_offices_g_b_l_o_cs_parameters.go
  pkg/gen/ghcapi/ghcoperations/transportation_office/get_transportation_offices_g_b_l_o_cs_responses.go
  pkg/gen/ghcapi/ghcoperations/transportation_office/get_transportation_offices_g_b_l_o_cs_urlbuilder.go
  pkg/gen/ghcmessages/g_b_l_o_cs.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/tranportation_offices.go
  pkg/handlers/ghcapi/transportation_offices_test.go
  pkg/models/transportation_office.go
  pkg/services/mocks/TransportationOfficesFetcher.go
  pkg/services/transportation_office.go
  pkg/services/transportation_office/transportation_office_fetcher.go
  src/components/Office/GblocSwitcher/GblocSwitcher.jsx
  src/constants/queryKeys.js
  src/constants/queues.js
  src/hooks/queries.js
  src/services/ghcApi.js
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: Scrummy Bears, INTEGRATION

#13233 B-20235
  src/components/PPMSummaryList/PPMSummaryList.jsx
  src/components/PPMSummaryList/PPMSummaryList.test.jsx
Labels: G-Unit, MAIN

#13231 B 19886 int3
  src/components/Office/PPM/ReviewExpense/ReviewExpense.jsx
  src/pages/Office/PPM/ReviewDocuments/ReviewDocuments.jsx
  src/pages/Office/PPM/ReviewDocuments/ReviewDocuments.module.scss
Labels: Scrummy Bears, INTEGRATION

#13238 B-20312 Update shipment pickup verbiage MAIN
  src/components/Customer/MtoShipmentForm/MtoShipmentForm.jsx
  src/components/Customer/MtoShipmentForm/MtoShipmentForm.test.jsx
Labels: Mountain Movers, MAIN

#13217 MAIN B-19780 Export Queue To CSV
  package.json
  pkg/services/office_user/customer/customer_searcher.go
  src/components/Table/TableCSVExportButton.jsx
  src/components/Table/TableCSVExportButton.stories.jsx
  src/components/Table/TableCSVExportButton.test.jsx
  src/components/Table/TableQueue.jsx
  src/components/Table/TableQueue.module.scss
  src/components/Table/TableQueue.test.jsx
  src/pages/Office/HeadquartersQueues/HeadquartersQueues.jsx
  src/pages/Office/MoveQueue/MoveQueue.jsx
  src/pages/Office/PaymentRequestQueue/PaymentRequestQueue.jsx
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.jsx
  yarn.lock
Labels: Scrummy Bears, MAIN

#13191 B 20256 int prevent prime users from accessing pptas
  .circleci/config.yml
  cmd/milmove/gen_certs_migration.go
  config/env/demo.app-client-tls.env
  config/env/exp.app-client-tls.env
  config/env/loadtest.app-client-tls.env
  config/env/prd.app-client-tls.env
  config/env/review.app.env
  config/env/stg.app-client-tls.env
  docker-compose.local.yml
  docker-compose.mtls.yml
  docker-compose.mtls_local.yml
  docker-compose.prime.yml
  docker-compose.yml
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240607134224_allow_pptas_client.up.sql
  migrations/app/secure/20240711181909_josephdoye_cn_cac.up.sql
  migrations/app/secure/20240711204446_mai_cac.up.sql
  pkg/cli/hosts.go
  pkg/cli/services.go
  pkg/factory/client_cert_factory.go
  pkg/gen/adminapi/embedded_spec.go
  pkg/gen/adminmessages/client_certificate.go
  pkg/gen/adminmessages/client_certificate_create.go
  pkg/gen/adminmessages/client_certificate_update.go
  pkg/gen/pptasapi/doc.go
  pkg/gen/pptasapi/embedded_spec.go
  pkg/gen/pptasapi/pptasoperations/moves/list_moves_urlbuilder.go
  pkg/gen/pptasapi/pptasoperations/mymove_api.go
  pkg/gen/pptasclient/mymove_client.go
  pkg/handlers/adminapi/client_certs.go
  pkg/handlers/apitests.go
  pkg/handlers/authentication/auth.go
  pkg/handlers/authentication/auth_test.go
  pkg/handlers/pptasapi/api.go
  pkg/handlers/routing/base_routing_suite.go
  pkg/handlers/routing/pptasapi_test/pptasapi_test.go
  pkg/handlers/routing/pptasapi_test/swagger_test.go
  pkg/handlers/routing/routing_init.go
  pkg/models/client_cert.go
  pkg/services/clientcert/client_cert_updater.go
  public/swagger-ui/pptas.html
  src/pages/Admin/ClientCerts/ClientCertCreate.jsx
  src/pages/Admin/ClientCerts/ClientCertEdit.jsx
  src/pages/Admin/ClientCerts/ClientCertList.jsx
  src/pages/Admin/ClientCerts/ClientCertShow.jsx
  src/setupProxy.js
  swagger-def/admin.yaml
  swagger-def/info/pptas_description.md
  swagger-def/pptas.yaml
  swagger/admin.yaml
  swagger/pptas.yaml
Labels: G-Unit, INTEGRATION

#13254 INT B-20078 #2 Linter Fix
  go.mod
  go.sum
  src/components/Table/TableQueue.test.jsx
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.test.jsx
Labels: Scrummy Bears, INTEGRATION

#13249 B 20080 INT #3 - Storybook fix
  src/components/Office/GblocSwitcher/GblocSwitcher.jsx
  src/components/Office/GblocSwitcher/GblocSwitcher.stories.jsx
  src/containers/Headers/OfficeLoggedInHeader.test.jsx
Labels: Scrummy Bears, INTEGRATION

#13250 MAIN-B-20078: Office Queue Pill Button Filters
  playwright/tests/office/servicescounseling/servicesCounselingQueueFilters.spec.js
  playwright/tests/office/txo/sitUpdates.spec.js
  playwright/tests/office/txo/tooFlows.spec.js
  playwright/tests/office/txo/tooFlowsNTS.spec.js
  playwright/tests/office/txo/tooFlowsNTSR.spec.js
  src/components/Table/Filters/MultiSelectCheckBoxFilter.jsx
  src/components/Table/Filters/MultiSelectCheckBoxFilter.module.scss
  src/components/Table/Filters/MultiSelectCheckBoxFilter.test.jsx
  src/components/Table/Filters/MultiSelectTypeAheadCheckboxFilter.test.jsx
  src/components/Table/Filters/MutliSelectTypeAheadCheckboxFilter.jsx
  src/components/Table/Filters/SelectFilter.jsx
  src/components/Table/Filters/TextBoxFilter.jsx
  src/components/Table/TableQueue.jsx
  src/components/Table/TableQueue.module.scss
  src/components/Table/TableQueue.test.jsx
  src/components/Table/utils.js
  src/components/Table/utils.test.js
  src/containers/Headers/OfficeLoggedInHeader.jsx
  src/containers/Headers/OfficeLoggedInHeader.test.jsx
  src/pages/Office/HeadquartersQueues/HeadquartersQueues.jsx
  src/pages/Office/MoveHistory/MoveHistory.jsx
  src/pages/Office/MoveQueue/MoveQueue.jsx
  src/pages/Office/PaymentRequestQueue/PaymentRequestQueue.jsx
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.jsx
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.test.jsx
  src/pages/PrimeUI/AvailableMoves/AvailableMovesQueue.jsx
  yarn.lock
Labels: Scrummy Bears, MAIN

#13257 B 20290 int storybook
  src/components/Office/PPM/ReviewExpense/ReviewExpense.jsx
Labels: Scrummy Bears, INTEGRATION

#13148 MAIN - B-20080 - Wrong GBLOC in Search Results & Marine Corps in Search Results Filter
  pkg/services/move/move_searcher.go
  src/components/Office/GblocSwitcher/GblocSwitcher.jsx
  src/components/Office/GblocSwitcher/GblocSwitcher.stories.jsx
  src/components/Table/SearchResultsTable.jsx
  src/components/Table/utils.js
  src/constants/queues.js
  src/containers/Headers/OfficeLoggedInHeader.test.jsx
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.jsx
Labels: Scrummy Bears, MAIN

#13247 B 20290 add amount reimbursement
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240624215947_add_sit_reimburseable_amount.up.sql
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/moving_expense.go
  pkg/gen/ghcmessages/update_moving_expense.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/moving_expense.go
  pkg/gen/internalmessages/update_moving_expense.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/internal/payloads/payload_to_model.go
  pkg/handlers/internalapi/internal/payloads/model_to_payload.go
  pkg/handlers/internalapi/internal/payloads/payload_to_model.go
  pkg/models/moving_expense.go
  pkg/services/moving_expense/moving_expense_updater.go
  pkg/services/moving_expense/moving_expense_updater_test.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet.go
  src/components/Office/PPM/ReviewDocumentsSidePanel/ReviewDocumentsSidePanel.jsx
  src/components/Office/PPM/ReviewExpense/ReviewExpense.jsx
  src/components/Office/PPM/ReviewExpense/ReviewExpense.test.jsx
  src/components/Office/PPM/SitCost/SitCost.jsx
  swagger-def/definitions/MovingExpense.yaml
  swagger-def/ghc.yaml
  swagger-def/internal.yaml
  swagger/ghc.yaml
  swagger/internal.yaml
Labels: Scrummy Bears, MAIN

#13271 B 20557 payment request status updates int
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/payment_request.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  src/components/Office/PaymentRequestCard/PaymentRequestCard.jsx
  src/components/Office/PaymentRequestCard/PaymentRequestCard.test.jsx
  src/types/order.js
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: Mountain Movers, INTEGRATION

#13269 B 20497 int
  pkg/services/requested_office_users/requested_office_user_updater.go
  pkg/services/requested_office_users/requested_office_user_updater_test.go
Labels: Mountain Movers, INTEGRATION

#13277 B-20291: Customer "Review your request" Page Errors
  src/components/Customer/Review/Summary/Summary.jsx
Labels: Mountain Movers, INTEGRATION

#13264 INT B-20608 Update CAC validation page with approved text and sign out button
  pkg/handlers/authentication/auth.go
  pkg/handlers/authentication/auth_test.go
  pkg/handlers/authentication/okta_auth_code_flow.go
  pkg/handlers/authentication/okta_auth_code_flow_test.go
  pkg/handlers/routing/routing_init.go
  src/shared/SmartCardRedirect/SmartCardRedirect.jsx
  src/shared/SmartCardRedirect/SmartCardRedirect.module.scss
  src/shared/SmartCardRedirect/SmartCardRedirect.test.jsx
  src/utils/api.js
Labels: Mountain Movers, INTEGRATION

#13265 B 20493 int
  pkg/handlers/ghcapi/tranportation_offices.go
  pkg/handlers/internalapi/transportation_offices.go
  pkg/services/mocks/TransportationOfficesFetcher.go
  pkg/services/transportation_office.go
  pkg/services/transportation_office/transportation_office_fetcher.go
  pkg/services/transportation_office/transportation_office_fetcher_test.go
Labels: Mountain Movers, INTEGRATION

#13093 B 19724 add emplid to office queues
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/customer/search_customers.go
  pkg/gen/ghcapi/ghcoperations/move/search_moves.go
  pkg/gen/ghcapi/ghcoperations/queues/get_moves_queue_parameters.go
  pkg/gen/ghcapi/ghcoperations/queues/get_moves_queue_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/queues/get_payment_requests_queue_parameters.go
  pkg/gen/ghcapi/ghcoperations/queues/get_payment_requests_queue_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/queues/get_services_counseling_queue_parameters.go
  pkg/gen/ghcapi/ghcoperations/queues/get_services_counseling_queue_urlbuilder.go
  pkg/gen/ghcmessages/customer.go
  pkg/gen/ghcmessages/search_customer.go
  pkg/gen/ghcmessages/search_move.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/move.go
  pkg/handlers/ghcapi/move_test.go
  pkg/handlers/ghcapi/queues.go
  pkg/services/customer.go
  pkg/services/move.go
  pkg/services/move/move_searcher.go
  pkg/services/office_user/customer/customer_searcher.go
  pkg/services/order.go
  pkg/services/order/order_fetcher.go
  pkg/services/payment_request.go
  pkg/services/payment_request/payment_request_list_fetcher.go
  pkg/services/payment_request/payment_request_list_fetcher_test.go
  src/components/Table/SearchResultsTable.jsx
  src/components/Table/SearchResultsTable.test.jsx
  src/pages/Office/MoveQueue/MoveQueue.jsx
  src/pages/Office/MoveQueue/MoveQueue.test.jsx
  src/pages/Office/PaymentRequestQueue/PaymentRequestQueue.jsx
  src/pages/Office/PaymentRequestQueue/PaymentRequestQueue.test.jsx
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.jsx
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.test.jsx
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: G-Unit, MAIN

#13273 INT B-20488 - Services Counselor Order Upload
  playwright/tests/office/servicescounseling/servicesCounselingFlows.spec.js
  playwright/tests/office/servicescounseling/servicesCounselingTestFixture.js
  playwright/tests/utils/office/waitForOfficePage.js
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.test.jsx
  src/shared/constants.js
Labels: ByteSize M&Ms, INTEGRATION

#13285 INT B-20463 update weight and expense tickets to pull data from multi moves
  pkg/models/move.go
  src/pages/MyMove/PPM/Closeout/ProGear/ProGear.jsx
  src/pages/MyMove/PPM/Closeout/ProGear/ProGear.test.jsx
  src/pages/MyMove/PPM/Closeout/Review/Review.jsx
  src/pages/MyMove/PPM/Closeout/Review/Review.test.jsx
  src/pages/MyMove/PPM/Closeout/WeightTickets/WeightTickets.jsx
  src/pages/MyMove/PPM/Closeout/WeightTickets/WeightTickets.test.jsx
  src/store/entities/selectors.js
Labels: Mountain Movers, INTEGRATION

#13286 B-20319 Trip Values INT
  src/components/Office/PPM/EditNetWeights/EditPPMNetWeight.jsx
  src/components/Office/PPM/ReviewWeightTicket/ReviewWeightTicket.jsx
  src/pages/Office/PPM/ReviewDocuments/ReviewDocuments.jsx
  src/pages/Office/PPM/ReviewDocuments/ReviewDocuments.test.jsx
  src/utils/test/factories/weightTicket.js
Labels: Mountain Movers, INTEGRATION

#13289 INT B-20273 add and update indexes for move history
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240722134633_update_move_history_indexes.up.sql
  src/pages/MyMove/PPM/Booking/DateAndLocation/DateAndLocation.test.jsx
Labels: Mountain Movers, INTEGRATION

#13308 INT B-20463 playwright fixes
  playwright/tests/my/milmove/ppms/customerPpmTestFixture.js
  playwright/tests/my/milmove/ppms/entireShipmentCloseout.spec.js
  playwright/tests/my/milmove/ppms/expenses.spec.js
  playwright/tests/my/milmove/ppms/finalCloseout.spec.js
  playwright/tests/my/milmove/ppms/progear.spec.js
Labels: Mountain Movers, INTEGRATION

#13307 B 20493 int
  pkg/handlers/ghcapi/tranportation_offices.go
  pkg/handlers/internalapi/transportation_offices.go
Labels: Mountain Movers, INTEGRATION

#13315 INT B-20608 add and
  src/shared/SmartCardRedirect/SmartCardRedirect.jsx
Labels: Mountain Movers, INTEGRATION

#13293 B-20803 duplicate fee MM - INT
  src/components/Office/RequestedShipments/RequestedShipments.test.jsx
  src/components/Office/RequestedShipments/SubmittedRequestedShipments.jsx
Labels: Mountain Movers, INTEGRATION

#13290 B 20281 int
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.test.jsx
Labels: G-Unit, INTEGRATION

#13266 B 20165 tio fix page width int
  src/pages/Office/ReviewBillableWeight/ReviewBillableWeight.jsx
  src/pages/Office/ReviewBillableWeight/ReviewBillableWeight.module.scss
Labels: ByteSize M&Ms, INTEGRATION

#13311 B-20462 Enforce N9 1W Character Limit INT
  pkg/models/service_member.go
  pkg/services/invoice/ghc_payment_request_invoice_generator.go
  pkg/services/invoice/ghc_payment_request_invoice_generator_test.go
Labels: Mountain Movers, INTEGRATION

#13297 INT - B-20454 - db and model for boat shipment
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240716161148_create_boat_shipment_table.up.sql
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/m_t_o_shipment_type.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/m_t_o_shipment_type.go
  pkg/gen/primev2api/embedded_spec.go
  pkg/gen/primev2messages/m_t_o_shipment_type.go
  pkg/gen/primev3api/embedded_spec.go
  pkg/gen/primev3messages/m_t_o_shipment_type.go
  pkg/models/boat_shipment.go
  pkg/models/boat_shipment_test.go
  swagger-def/definitions/BoatShipment.yaml
  swagger-def/definitions/MTOShipmentType.yaml
  swagger-def/definitions/prime/MTOShipmentType.yaml
  swagger-def/definitions/prime/v2/MTOShipmentType.yaml
  swagger-def/definitions/prime/v3/MTOShipmentType.yaml
  swagger/ghc.yaml
  swagger/prime.yaml
  swagger/prime_v2.yaml
  swagger/prime_v3.yaml
Labels: ByteSize M&Ms, INTEGRATION

#13280 B 20744 int Fix error when Customer doesn't select SIT Expected
  pkg/handlers/ghcapi/ppm_shipment.go
  pkg/services/moving_expense/moving_expense_updater.go
Labels: Scrummy Bears, INTEGRATION

#13312 INT B-20684 858 60 char limit on location names
  pkg/services/invoice/ghc_payment_request_invoice_generator.go
  pkg/services/invoice/ghc_payment_request_invoice_generator_test.go
Labels: Mountain Movers, INTEGRATION

#13260 B-20527-INT Add moves.assigned cols, create queue management FF
  .circleci/config.yml
  .envrc
  config/env/demo.app-client-tls.env
  config/env/demo.app.env
  config/env/exp.app-client-tls.env
  config/env/exp.app.env
  config/env/loadtest.app-client-tls.env
  config/env/loadtest.app.env
  config/env/prd.app-client-tls.env
  config/env/prd.app.env
  config/env/stg.app-client-tls.env
  config/env/stg.app.env
  config/flipt/storage/development.features.yaml
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240718021218_add_assigned_cols_to_moves.up.sql
  pkg/models/move.go
Labels: G-Unit, INTEGRATION

#13302 B-20528-INT Return assignee office users in queue payload
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/available_office_user.go
  pkg/gen/ghcmessages/available_office_users.go
  pkg/gen/ghcmessages/queue_moves_result.go
  pkg/gen/ghcmessages/queue_payment_requests_result.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/queues.go
  pkg/handlers/ghcapi/queues_test.go
  pkg/services/mocks/OfficeUserFetcherPop.go
  pkg/services/office_user.go
  pkg/services/office_user/office_user_fetcher.go
  pkg/services/office_user/office_user_fetcher_test.go
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: G-Unit, INTEGRATION

#13299 B 19730 int add state to us_post_region_cities
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240719222007_add_state_to_us_post_region_cities.up.sql
Labels: Scrummy Bears, INTEGRATION

#13294 B 20686 int
  src/components/Office/PaymentRequestCard/PaymentRequestCard.jsx
  src/components/Office/PaymentRequestCard/PaymentRequestCard.test.jsx
  src/content/serviceItems.js
Labels: Scrummy Bears, INTEGRATION

#13313 B-20291:Customer review page errors int
  src/components/Customer/Review/Summary/Summary.jsx
  src/components/Customer/Review/Summary/Summary.test.jsx
Labels: Mountain Movers, INTEGRATION

#13281 B-20647-INT add sac 80 character limit
  pkg/handlers/ghcapi/orders.go
  pkg/services/order/order_updater.go
  src/components/Office/OrdersDetailForm/OrdersDetailForm.jsx
Labels: Scrummy Bears, INTEGRATION

#13324 MAIN B-20463
  pkg/models/move.go
  playwright/tests/my/milmove/ppms/customerPpmTestFixture.js
  playwright/tests/my/milmove/ppms/entireShipmentCloseout.spec.js
  playwright/tests/my/milmove/ppms/expenses.spec.js
  playwright/tests/my/milmove/ppms/finalCloseout.spec.js
  playwright/tests/my/milmove/ppms/progear.spec.js
  src/pages/MyMove/PPM/Closeout/ProGear/ProGear.jsx
  src/pages/MyMove/PPM/Closeout/ProGear/ProGear.test.jsx
  src/pages/MyMove/PPM/Closeout/Review/Review.jsx
  src/pages/MyMove/PPM/Closeout/Review/Review.test.jsx
  src/pages/MyMove/PPM/Closeout/WeightTickets/WeightTickets.jsx
  src/pages/MyMove/PPM/Closeout/WeightTickets/WeightTickets.test.jsx
  src/store/entities/selectors.js
Labels: Mountain Movers, MAIN

#13270 B 19045 INT - Hide Request Diversion and Request Cancellation when Cancellation Requested
  src/components/Office/ShipmentAddresses/ShipmentAddresses.jsx
  src/components/Office/ShipmentAddresses/ShipmentAddresses.test.jsx
  src/components/Office/ShipmentHeading/ShipmentHeading.jsx
  src/components/Office/ShipmentHeading/ShipmentHeading.test.jsx
Labels: Scrummy Bears, INTEGRATION

#13288 B-20281 SC defects
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.test.jsx
Labels: G-Unit, MAIN

#13279 B 19919 INT - Diversion Tags for Billable Weights and Review Weights
  src/components/Office/BillableWeight/BillableWeightCard/BillableWeightCard.jsx
  src/components/Office/BillableWeight/BillableWeightCard/BillableWeightCard.module.scss
  src/components/Office/BillableWeight/BillableWeightCard/BillableWeightCard.test.jsx
  src/components/ShipmentModificationTag/ShipmentModificationTag.module.scss
  src/pages/Office/DocumentViewerSidebar/DocumentViewerSidebar.jsx
  src/pages/Office/DocumentViewerSidebar/DocumentViewerSidebar.module.scss
  src/pages/Office/ReviewBillableWeight/ReviewBillableWeight.jsx
  src/pages/Office/ReviewBillableWeight/ReviewBillableWeight.module.scss
  src/pages/Office/ReviewBillableWeight/ReviewBillableWeight.test.jsx
Labels: Scrummy Bears, INTEGRATION

#13262 B 20695 int
  src/components/Customer/PPM/Booking/EstimatedWeightsProGearForm/EstimatedWeightsProGearForm.jsx
  src/components/Customer/PPM/Booking/EstimatedWeightsProGearForm/EstimatedWeightsProGearForm.test.jsx
  src/components/Customer/PPM/Closeout/ExpenseForm/ExpenseForm.jsx
  src/components/Customer/PPM/Closeout/ExpenseForm/ExpenseForm.test.jsx
  src/pages/MyMove/PPM/Closeout/Expenses/Expenses.test.jsx
Labels: Scrummy Bears, INTEGRATION

#13272 MAIN B-20488 - Services Counselor Order Upload
  playwright/tests/office/servicescounseling/servicesCounselingFlows.spec.js
  playwright/tests/office/servicescounseling/servicesCounselingTestFixture.js
  playwright/tests/utils/office/waitForOfficePage.js
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.test.jsx
  src/shared/constants.js
Labels: ByteSize M&Ms, MAIN

#13323 INT B-19819 unique DODID when creating a customer
  .envrc
  config/env/demo.app-client-tls.env
  config/env/demo.app.env
  config/env/exp.app-client-tls.env
  config/env/exp.app.env
  config/env/loadtest.app-client-tls.env
  config/env/loadtest.app.env
  config/env/prd.app-client-tls.env
  config/env/prd.app.env
  config/env/stg.app-client-tls.env
  config/env/stg.app.env
  config/flipt/storage/development.features.yaml
  pkg/cli/feature_flag.go
  pkg/handlers/ghcapi/customer.go
  pkg/handlers/ghcapi/customer_test.go
  src/pages/Office/CustomerOnboarding/CreateCustomerForm.jsx
  src/pages/Office/MoveDocumentWrapper/MoveDocumentWrapper.test.jsx
Labels: Mountain Movers, INTEGRATION

#13331 B-20557 Payment Request Status Updates MAIN
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/payment_request.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  src/components/Office/PaymentRequestCard/PaymentRequestCard.jsx
  src/components/Office/PaymentRequestCard/PaymentRequestCard.test.jsx
  src/types/order.js
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: Mountain Movers, MAIN

#13326 MAIN B-20273 add and update indexes for move history
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240722134633_update_move_history_indexes.up.sql
  src/pages/MyMove/PPM/Booking/DateAndLocation/DateAndLocation.test.jsx
Labels: Mountain Movers, MAIN

#13335 I 13110 int 2
  playwright/tests/office/txo/tooFlows.spec.js
  playwright/tests/utils/office/officeTest.js
Labels: Scrummy Bears, INTEGRATION

#13332 MAIN B-20608 cac validation page redirect
  pkg/handlers/authentication/auth.go
  pkg/handlers/authentication/auth_test.go
  pkg/handlers/authentication/okta_auth_code_flow.go
  pkg/handlers/authentication/okta_auth_code_flow_test.go
  pkg/handlers/routing/routing_init.go
  src/shared/SmartCardRedirect/SmartCardRedirect.jsx
  src/shared/SmartCardRedirect/SmartCardRedirect.module.scss
  src/shared/SmartCardRedirect/SmartCardRedirect.test.jsx
  src/utils/api.js
Labels: Mountain Movers, MAIN

#13321 I-13110 Flaky Tests
  package.json
  playwright.config.js
  playwright/tests/admin/adminUsers.spec.js
  playwright/tests/admin/officeUsers.spec.js
  playwright/tests/admin/webhookSubscriptions.spec.js
  playwright/tests/my/milmove/ppms/advances.spec.js
  playwright/tests/my/milmove/ppms/customerPpmTestFixture.js
  playwright/tests/my/milmove/ppms/dateAndLocation.spec.js
  playwright/tests/my/milmove/ppms/entireShipmentOnboarding.spec.js
  playwright/tests/my/milmove/ppms/estimatedWeightsProgear.spec.js
  playwright/tests/my/milmove/ppms/expenses.spec.js
  playwright/tests/office/officeCSRFProtect.spec.js
  playwright/tests/office/ppms/addShipment.spec.js
  playwright/tests/office/ppms/happyPathFlows.spec.js
  playwright/tests/office/ppms/ppmTestFixture.js
  playwright/tests/office/primesimulator/primeSimulatorFlows.spec.js
  playwright/tests/office/qaecsr/csrFlows.spec.js
  playwright/tests/office/qaecsr/moveSearchFlows.spec.js
  playwright/tests/office/qaecsr/qaeFlows.spec.js
  playwright/tests/office/servicescounseling/servicesCounselingFlows.spec.js
  playwright/tests/office/servicescounseling/servicesCounselingMovingExpenses.spec.js
  playwright/tests/office/servicescounseling/servicesCounselingQueueFilters.spec.js
  playwright/tests/office/servicescounseling/servicesCounselingTestFixture.js
  playwright/tests/office/txo/sitUpdates.spec.js
  playwright/tests/office/txo/tioFlows.spec.js
  playwright/tests/office/txo/tioUpdateMaxBillableWeight.spec.js
  playwright/tests/office/txo/tooFlows.spec.js
  playwright/tests/office/txo/tooFlowsNTS.spec.js
  playwright/tests/office/txo/tooFlowsNTSR.spec.js
  playwright/tests/office/txo/tooTestFixture.js
  playwright/tests/utils/baseTest.js
  playwright/tests/utils/my/customerTest.js
  playwright/tests/utils/office/officeTest.js
  src/components/Office/BillableWeight/BillableWeightCard/BillableWeightCard.jsx
  yarn.lock
Labels: Scrummy Bears, MAIN

#13336 B20538 MAIN fix customer search
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/search_customer.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: ByteSize M&Ms, MAIN

#13333 B-20803 Duplicate Move Management Fee MAIN
  src/components/Office/RequestedShipments/RequestedShipments.test.jsx
  src/components/Office/RequestedShipments/SubmittedRequestedShipments.jsx
Labels: Mountain Movers, MAIN

#13338 B 20256 int prevent prime users from accessing pptas
  migrations/app/migrations_manifest.txt
  migrations/app/secure/20240726185252_mai_do_cac.up.sql
  migrations/app/secure/20240726190401_joseph_doye_cn_cac.up.sql
Labels: G-Unit, INTEGRATION

#13327 B 20287 int
  src/components/Office/DefinitionLists/PPMShipmentInfoList.jsx
  src/components/Office/DefinitionLists/PPMShipmentInfoList.test.jsx
  src/pages/MyMove/Home/MoveHome.jsx
  src/pages/MyMove/Home/MoveHome.test.jsx
Labels: Scrummy Bears, INTEGRATION

#13322 INT-B-20286: Partial PPM labeling change in Weight review
  src/components/Office/PPM/ReviewShipmentWeightsTable/ReviewShipmentWeightsTable.test.jsx
  src/components/Office/PPM/ReviewShipmentWeightsTable/helpers.jsx
Labels: Scrummy Bears, INTEGRATION

#13345 B 20256 int prevent prime users from accessing pptas
  migrations/app/migrations_manifest.txt
  migrations/app/secure/20240726185252_mai_do_cac.up.sql
  migrations/app/secure/20240726190401_joseph_doye_cn_cac.up.sql
Labels: G-Unit, INTEGRATION

#13346 B 20462 enforce n9 char limit main
  pkg/models/service_member.go
  pkg/services/invoice/ghc_payment_request_invoice_generator.go
  pkg/services/invoice/ghc_payment_request_invoice_generator_test.go
Labels: Mountain Movers, MAIN

#13348 MAIN B-20684 858 60 char limit on location names (MERGE AFTER B-20462)
  pkg/services/invoice/ghc_payment_request_invoice_generator.go
  pkg/services/invoice/ghc_payment_request_invoice_generator_test.go
Labels: Mountain Movers, MAIN

#13296 MAIN - B-20454 - db and model for boat shipment
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240716161148_create_boat_shipment_table.up.sql
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/m_t_o_shipment_type.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/m_t_o_shipment_type.go
  pkg/gen/primev2api/embedded_spec.go
  pkg/gen/primev2messages/m_t_o_shipment_type.go
  pkg/gen/primev3api/embedded_spec.go
  pkg/gen/primev3messages/m_t_o_shipment_type.go
  pkg/models/boat_shipment.go
  pkg/models/boat_shipment_test.go
  swagger-def/definitions/BoatShipment.yaml
  swagger-def/definitions/MTOShipmentType.yaml
  swagger-def/definitions/prime/MTOShipmentType.yaml
  swagger-def/definitions/prime/v2/MTOShipmentType.yaml
  swagger-def/definitions/prime/v3/MTOShipmentType.yaml
  swagger/ghc.yaml
  swagger/prime.yaml
  swagger/prime_v2.yaml
  swagger/prime_v3.yaml
Labels: ByteSize M&Ms, MAIN

#13337 B20446-INT-payment requests doc viewer
  src/components/Office/PaymentRequestCard/PaymentRequestCard.jsx
  src/components/Office/PaymentRequestCard/PaymentRequestCard.test.jsx
Labels: ByteSize M&Ms, INTEGRATION

#13276 B-20291: Customer "Review your request" Page Errors
  src/components/Customer/Review/Summary/Summary.jsx
  src/components/Customer/Review/Summary/Summary.test.jsx
Labels: Mountain Movers, MAIN

#13350 B 20673 int
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240725190050_update_payment_request_status_tpps_received.up.sql
  pkg/factory/payment_request_factory_test.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/payment_request.go
  pkg/gen/ghcmessages/payment_request_status.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/payment_request_status.go
  pkg/gen/primev2api/embedded_spec.go
  pkg/gen/primev2messages/payment_request_status.go
  pkg/gen/primev3api/embedded_spec.go
  pkg/gen/primev3messages/payment_request_status.go
  pkg/gen/supportapi/embedded_spec.go
  pkg/gen/supportapi/supportoperations/payment_request/update_payment_request_status.go
  pkg/gen/supportclient/payment_request/payment_request_client.go
  pkg/gen/supportmessages/payment_request_status.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/payment_request_test.go
  pkg/handlers/supportapi/payment_request.go
  pkg/models/payment_request.go
  pkg/models/payment_request_test.go
  pkg/services/invoice/process_edi997.go
  pkg/services/invoice/process_edi997_test.go
  pkg/services/payment_request/payment_request_list_fetcher.go
  pkg/services/payment_request/payment_request_list_fetcher_test.go
  pkg/services/shipment_address_update/shipment_address_update_requester.go
  src/components/Office/PaymentRequestCard/PaymentRequestCard.jsx
  src/components/Office/PaymentRequestCard/PaymentRequestCard.test.jsx
  src/constants/MoveHistory/EventTemplates/UpdatePaymentRequest/updatePaymentRequest.test.jsx
  src/constants/MoveHistory/EventTemplates/UpdatePaymentRequest/updatePaymentRequestJobRunner.test.jsx
  src/constants/paymentRequestStatus.js
  src/shared/constants.js
  src/utils/formatters.test.js
  swagger-def/definitions/PaymentRequestStatus.yaml
  swagger-def/ghc.yaml
  swagger-def/support.yaml
  swagger/ghc.yaml
  swagger/prime.yaml
  swagger/prime_v2.yaml
  swagger/prime_v3.yaml
  swagger/support.yaml
Labels: Mountain Movers, INTEGRATION

#13357 B-20695 MAIN
  src/components/Customer/PPM/Booking/EstimatedWeightsProGearForm/EstimatedWeightsProGearForm.jsx
  src/components/Customer/PPM/Booking/EstimatedWeightsProGearForm/EstimatedWeightsProGearForm.test.jsx
  src/components/Customer/PPM/Closeout/ExpenseForm/ExpenseForm.jsx
  src/components/Customer/PPM/Closeout/ExpenseForm/ExpenseForm.test.jsx
  src/pages/MyMove/PPM/Closeout/Expenses/Expenses.test.jsx
Labels: Scrummy Bears, MAIN

#13360 MAIN B-19819 unique DODID when creating a customer
  .envrc
  config/env/demo.app-client-tls.env
  config/env/demo.app.env
  config/env/exp.app-client-tls.env
  config/env/exp.app.env
  config/env/loadtest.app-client-tls.env
  config/env/loadtest.app.env
  config/env/prd.app-client-tls.env
  config/env/prd.app.env
  config/env/stg.app-client-tls.env
  config/env/stg.app.env
  config/flipt/storage/development.features.yaml
  pkg/cli/feature_flag.go
  pkg/handlers/ghcapi/customer.go
  pkg/handlers/ghcapi/customer_test.go
  src/pages/Office/CustomerOnboarding/CreateCustomerForm.jsx
  src/pages/Office/MoveDocumentWrapper/MoveDocumentWrapper.test.jsx
Labels: Mountain Movers, MAIN

#13359 INT B-20294 CSS fixes for ppm packet download tag
  src/components/CustomerHeader/index.module.scss
  src/components/Office/ShipmentDisplay/ShipmentDisplay.jsx
  src/components/Office/ShipmentDisplay/ShipmentDisplay.module.scss
  src/components/ShipmentList/ShipmentList.jsx
  src/components/ShipmentList/ShipmentList.module.scss
Labels: Mountain Movers, INTEGRATION

#13352 B 20495 move search and customer search trailing space int
  src/components/Table/SearchResultsTable.jsx
Labels: Mountain Movers, INTEGRATION

#13347 INT B-20591 prime can update destination address for NTSR shipment
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/mto_shipment/update_shipment_destination_address.go
  pkg/gen/primeclient/mto_shipment/mto_shipment_client.go
  pkg/handlers/primeapi/mto_shipment.go
  pkg/services/shipment_address_update/shipment_address_update_requester.go
  pkg/services/shipment_address_update/shipment_address_update_requester_test.go
  pkg/testdatagen/testharness/dispatch.go
  pkg/testdatagen/testharness/make_move.go
  playwright/tests/office/txo/tooFlows.spec.js
  playwright/tests/utils/testharness.js
  src/components/Office/DefinitionLists/NTSRShipmentInfoList.jsx
  src/components/Office/DefinitionLists/NTSRShipmentInfoList.test.jsx
  src/components/Office/ShipmentForm/ShipmentForm.jsx
  src/components/Office/ShipmentForm/ShipmentForm.module.scss
  src/components/Office/ShipmentForm/ShipmentForm.test.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdateDestinationAddressForm.jsx
  swagger-def/prime.yaml
  swagger/prime.yaml
Labels: Mountain Movers, INTEGRATION

#13364 B 20647 add sac 80 character limit
  pkg/handlers/ghcapi/orders.go
  pkg/services/order/order_updater.go
  src/components/Office/OrdersDetailForm/OrdersDetailForm.jsx
Labels: Scrummy Bears, MAIN

#13242 B-19723 Office viewers can view EMPLID
  src/components/CustomerHeader/CustomerHeader.test.jsx
  src/components/CustomerHeader/index.jsx
  src/components/Office/DefinitionLists/CustomerInfoList.jsx
  src/components/Office/DefinitionLists/CustomerInfoList.test.jsx
  src/pages/Office/MoveDetails/MoveDetails.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
Labels: G-Unit, MAIN

#13369 B20446 INT 02 payment requests doc viewer
  pkg/testdatagen/testharness/dispatch.go
  pkg/testdatagen/testharness/make_move.go
  playwright/tests/office/qaecsr/csrFlows.spec.js
  playwright/tests/utils/testharness.js
Labels: ByteSize M&Ms, INTEGRATION

#13241 B-19726 Add EMPLID to SC Customer create
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/customer/create_customer_with_okta_option_responses.go
  pkg/gen/ghcmessages/create_customer_payload.go
  pkg/handlers/ghcapi/customer.go
  pkg/handlers/ghcapi/customer_test.go
  pkg/handlers/ghcapi/orders.go
  pkg/models/service_member.go
  src/pages/Office/CustomerOnboarding/CreateCustomerForm.jsx
  src/pages/Office/CustomerOnboarding/CreateCustomerForm.test.jsx
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: G-Unit, MAIN

#13353  B 20256 int prevent prime users from acessing pptas migrations
  migrations/app/migrations_manifest.txt
  migrations/app/secure/20240729162353_joseph_doye_cn_cac.up.sql
  migrations/app/secure/20240729164930_mai_do_cac.up.sql
Labels: G-Unit, INTEGRATION

#13261 B-20527 Add moves.assigned cols, create queue management FF
  .circleci/config.yml
  .envrc
  config/env/demo.app-client-tls.env
  config/env/demo.app.env
  config/env/exp.app-client-tls.env
  config/env/exp.app.env
  config/env/loadtest.app-client-tls.env
  config/env/loadtest.app.env
  config/env/prd.app-client-tls.env
  config/env/prd.app.env
  config/env/stg.app-client-tls.env
  config/env/stg.app.env
  config/flipt/storage/development.features.yaml
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240718021218_add_assigned_cols_to_moves.up.sql
  pkg/models/move.go
Labels: G-Unit, MAIN

#13301 B-20528 return office users for assignment in office queue payloads
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/available_office_user.go
  pkg/gen/ghcmessages/available_office_users.go
  pkg/gen/ghcmessages/queue_moves_result.go
  pkg/gen/ghcmessages/queue_payment_requests_result.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/queues.go
  pkg/handlers/ghcapi/queues_test.go
  pkg/services/mocks/OfficeUserFetcherPop.go
  pkg/services/office_user.go
  pkg/services/office_user/office_user_fetcher.go
  pkg/services/office_user/office_user_fetcher_test.go
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: G-Unit, MAIN

#13371 Main b 20437 gbloc to prime
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240719192106_add_destination_gbloc_to_orders.up.sql
  pkg/factory/order_factory.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/order.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/order.go
  pkg/gen/primev2api/embedded_spec.go
  pkg/gen/primev2messages/order.go
  pkg/gen/primev3api/embedded_spec.go
  pkg/gen/primev3messages/order.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/orders.go
  pkg/handlers/internalapi/orders.go
  pkg/handlers/primeapi/payloads/model_to_payload.go
  pkg/handlers/primeapiv2/payloads/model_to_payload.go
  pkg/handlers/primeapiv3/payloads/model_to_payload.go
  pkg/models/order.go
  pkg/models/order_test.go
  pkg/models/service_member.go
  pkg/models/service_member_test.go
  pkg/services/move_task_order/move_task_order_fetcher.go
  pkg/services/order/order_updater.go
  pkg/testdatagen/scenario/shared.go
  swagger-def/definitions/prime/Order.yaml
  swagger-def/definitions/prime/v2/Order.yaml
  swagger-def/definitions/prime/v3/Order.yaml
  swagger-def/ghc.yaml
  swagger/ghc.yaml
  swagger/prime.yaml
  swagger/prime_v2.yaml
  swagger/prime_v3.yaml
Labels: ByteSize M&Ms, MAIN

#13368 B 20165 tio fix page width main
  src/pages/Office/ReviewBillableWeight/ReviewBillableWeight.jsx
  src/pages/Office/ReviewBillableWeight/ReviewBillableWeight.module.scss
Labels: ByteSize M&Ms, MAIN
