Repository transcom/mymove, pull requests merged in 2024-08, with the labels that each got.

#13366 B 20728
  src/pages/MyMove/SelectShipmentType.test.jsx
  src/utils/shipmentInfo.js
  src/utils/shipmentInfo.test.js
Labels: Scrummy Bears, MAIN

#13374 B 20673
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240725190050_update_payment_request_status_tpps_received.up.sql
  pkg/factory/payment_request_factory_test.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/payment_request.go
  pkg/gen/ghcmessages/payment_request_status.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/payment_request_status.go
  pkg/gen/primev2api/embedded_spec.go
  pkg/gen/primev2messages/payment_request_status.go
  pkg/gen/primev3api/embedded_spec.go
  pkg/gen/primev3messages/payment_request_status.go
  pkg/gen/supportapi/embedded_spec.go
  pkg/gen/supportapi/supportoperations/payment_request/update_payment_request_status.go
  pkg/gen/supportclient/payment_request/payment_request_client.go
  pkg/gen/supportmessages/payment_request_status.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/payment_request_test.go
  pkg/handlers/supportapi/payment_request.go
  pkg/models/payment_request.go
  pkg/models/payment_request_test.go
  pkg/services/invoice/process_edi997.go
  pkg/services/invoice/process_edi997_test.go
  pkg/services/payment_request/payment_request_list_fetcher.go
  pkg/services/payment_request/payment_request_list_fetcher_test.go
  pkg/services/shipment_address_update/shipment_address_update_requester.go
  src/components/Office/PaymentRequestCard/PaymentRequestCard.jsx
  src/components/Office/PaymentRequestCard/PaymentRequestCard.test.jsx
  src/constants/MoveHistory/EventTemplates/UpdatePaymentRequest/updatePaymentRequest.test.jsx
  src/constants/MoveHistory/EventTemplates/UpdatePaymentRequest/updatePaymentRequestJobRunner.test.jsx
  src/constants/paymentRequestStatus.js
  src/shared/constants.js
  src/utils/formatters.test.js
  swagger-def/definitions/PaymentRequestStatus.yaml
  swagger-def/ghc.yaml
  swagger-def/support.yaml
  swagger/ghc.yaml
  swagger/prime.yaml
  swagger/prime_v2.yaml
  swagger/prime_v3.yaml
  swagger/support.yaml
Labels: Mountain Movers, MAIN

#13354 added secure migrations.
  migrations/app/migrations_manifest.txt
  migrations/app/secure/20240729162353_joseph_doye_cn_cac.up.sql
  migrations/app/secure/20240729164930_mai_do_cac.up.sql
Labels: G-Unit, MAIN

#13330 INT B-20316 Actual Pro Gear Weights in PrimeV3
  pkg/gen/primev3api/embedded_spec.go
  pkg/gen/primev3messages/m_t_o_shipment_without_service_items.go
  pkg/handlers/primeapiv3/payloads/model_to_payload.go
  swagger-def/definitions/prime/v3/MTOShipmentWithoutServiceItems.yaml
  swagger/prime_v3.yaml
Labels: Scrummy Bears, INTEGRATION

#13362 B 20744 Fix error when Customer doesn't select SIT Expected
  pkg/handlers/ghcapi/ppm_shipment.go
  pkg/services/moving_expense/moving_expense_updater.go
Labels: Scrummy Bears, MAIN

#13351 INT B-20651 Prime Counseling Completed in Move History
  src/constants/MoveHistory/EventTemplates/UpdateMTOPostCounselingInformation/updateMTOStatusPrimeCounselingCompleted.jsx
  src/constants/MoveHistory/EventTemplates/UpdateMTOPostCounselingInformation/updateMTOStatusPrimeCounselingCompleted.test.jsx
  src/constants/MoveHistory/EventTemplates/UpdateMTOPostCounselingInformation/updateMTOStatusPrimeCounselingCompletedPPM.jsx
  src/constants/MoveHistory/EventTemplates/UpdateMTOPostCounselingInformation/updateMTOStatusPrimeCounselingCompletedPPM.test.jsx
  src/constants/MoveHistory/EventTemplates/index.js
  src/constants/MoveHistory/UIDisplay/Operations.js
Labels: Scrummy Bears, INTEGRATION

#13325 B 20620 mobile home db model int
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240723184614_create_mobile_home.up.sql
  migrations/app/schema/20240731151118_alter_mto_shipment_type_motorhome.up.sql
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/create_m_t_o_shipment.go
  pkg/gen/ghcmessages/create_mobile_home.go
  pkg/gen/ghcmessages/m_t_o_shipment_type.go
  pkg/gen/ghcmessages/mobile_home.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/m_t_o_shipment_type.go
  pkg/gen/primev2api/embedded_spec.go
  pkg/gen/primev2messages/m_t_o_shipment_type.go
  pkg/gen/primev3api/embedded_spec.go
  pkg/gen/primev3messages/m_t_o_shipment_type.go
  pkg/models/mobile_home.go
  pkg/models/mobile_home_test.go
  pkg/models/mto_shipments.go
  pkg/paperwork/evaluation_report.go
  pkg/services/mto_shipment/mto_shipment_creator_test.go
  pkg/services/mto_shipment/mto_shipment_updater.go
  pkg/services/mto_shipment/rules_test.go
  src/components/Office/ShipmentContainer/ShipmentContainer.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesMoveContainer/MultiMovesMoveContainer.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesTestData.js
  src/shared/constants.js
  swagger-def/definitions/MTOShipmentType.yaml
  swagger-def/definitions/MobileHome.yaml
  swagger-def/definitions/prime/MTOShipmentType.yaml
  swagger-def/definitions/prime/v2/MTOShipmentType.yaml
  swagger-def/definitions/prime/v3/MTOShipmentType.yaml
  swagger-def/ghc.yaml
  swagger/ghc.yaml
  swagger/prime.yaml
  swagger/prime_v2.yaml
  swagger/prime_v3.yaml
Labels: ByteSize M&Ms, INTEGRATION

#13373 B-20550
  pkg/services/invoice/ghc_payment_request_invoice_generator.go
  pkg/services/invoice/ghc_payment_request_invoice_generator_test.go
Labels: Mountain Movers, MAIN

#13381 INT B-20447 Customer Search Sorting Fixes
  pkg/services/office_user/customer/customer_searcher.go
Labels: ByteSize M&Ms, INTEGRATION

#13387 align int to main (emplid)
  migrations/app/migrations_manifest.txt
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/customer.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: G-Unit, INTEGRATION

#13379 MAIN B-20294 CSS fixes for ppm packet download tag
  src/components/CustomerHeader/index.module.scss
  src/components/Office/ShipmentDisplay/ShipmentDisplay.jsx
  src/components/Office/ShipmentDisplay/ShipmentDisplay.module.scss
  src/components/ShipmentList/ShipmentList.jsx
  src/components/ShipmentList/ShipmentList.module.scss
Labels: Mountain Movers, MAIN

#13380 INT B-20113 refactor edit profile redux form
  src/constants/routes.js
  src/scenes/MyMove/index.jsx
  src/scenes/Review/EditProfile.jsx
Labels: Mountain Movers, INTEGRATION

#13363 B 20740 and B 20296 INT
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/p_p_m_s_i_t_estimated_cost.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/ppm_shipment.go
  pkg/handlers/ghcapi/ppm_shipment_test.go
  pkg/models/ppm_shipment.go
  pkg/services/mocks/PPMEstimator.go
  pkg/services/ppmshipment.go
  pkg/services/ppmshipment/ppm_estimator.go
  src/components/Office/PPM/ReviewExpense/ReviewExpense.jsx
  src/components/Office/PPM/SitCost/SitCost.jsx
  src/components/Office/PPM/SitCost/SitCost.module.scss
  src/components/Office/PPM/SitCost/SitCost.test.jsx
  src/components/Office/PPM/SitCostBreakdown/SitCostBreakdown.jsx
  src/components/Office/PPM/SitCostBreakdown/SitCostBreakdown.module.scss
  src/components/Office/PPM/SitCostBreakdown/SitCostBreakdown.test.jsx
  swagger-def/definitions/PPMSITEstimatedCost.yaml
  swagger/ghc.yaml
Labels: Scrummy Bears, INTEGRATION

#13378 INT B-20882 rejected sit resubmission for all sit service items
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/mto_service_item/update_m_t_o_service_item.go
  pkg/gen/primeclient/mto_service_item/mto_service_item_client.go
  pkg/gen/primemessages/update_m_t_o_service_item_model_type.go
  pkg/gen/primemessages/update_m_t_o_service_item_s_i_t.go
  pkg/handlers/primeapi/mto_service_item_test.go
  pkg/services/move_task_order/move_task_order_fetcher.go
  pkg/services/mto_service_item/mto_service_item_updater.go
  pkg/services/mto_service_item/mto_service_item_updater_test.go
  pkg/services/mto_service_item/mto_service_item_validators.go
  pkg/services/mto_service_item/mto_service_item_validators_test.go
  swagger-def/prime.yaml
  swagger/prime.yaml
Labels: Mountain Movers, INTEGRATION

#13384 D-01309-INT bugfix for integration error with secure migration
  config/flipt/storage/development.features.yaml
  migrations/app/secure/20240729162353_joseph_doye_cn_cac.up.sql
  migrations/app/secure/20240729164930_mai_do_cac.up.sql
Labels: bug, G-Unit, INTEGRATION

#13377 B 20686
  src/components/Office/PaymentRequestCard/PaymentRequestCard.jsx
  src/components/Office/PaymentRequestCard/PaymentRequestCard.test.jsx
  src/content/serviceItems.js
Labels: Scrummy Bears, MAIN

#13391 B20449-INT-nts ntsr missing shipment num
  src/components/Customer/Review/Summary/Summary.jsx
Labels: ByteSize M&Ms, INTEGRATION

#13398 INT Add missing feature flag items for boat shipment
  .circleci/config.yml
  config/flipt/storage/development.features.yaml
  pkg/handlers/ghcapi/mto_shipment.go
  pkg/handlers/internalapi/moves.go
  pkg/handlers/internalapi/mto_shipment.go
  pkg/handlers/primeapi/move_task_order.go
  pkg/handlers/primeapiv2/move_task_order.go
  pkg/handlers/primeapiv3/move_task_order.go
Labels: ByteSize M&Ms, INTEGRATION

#13394 B 19730
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240719222007_add_state_to_us_post_region_cities.up.sql
Labels: Scrummy Bears, MAIN

#13392 B20449-MAIN-nts ntsr missing shipment num
  src/components/Customer/Review/Summary/Summary.jsx
Labels: ByteSize M&Ms, MAIN

#13388 INT B-20685 Overflow/Dynamic Styling
  src/components/CUIHeader/CUIHeader.jsx
  src/components/CustomerHeader/index.module.scss
  src/pages/Office/MoveQueue/MoveQueue.module.scss
  src/pages/Office/PaymentRequestQueue/PaymentRequestQueue.module.scss
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.module.scss
  src/pages/PrimeUI/AvailableMoves/AvailableMovesQueue.module.scss
  src/pages/SignIn/SignIn.module.scss
  src/scenes/SystemAdmin/Home.jsx
  src/scenes/SystemAdmin/Home.module.scss
  src/scenes/SystemAdmin/index.jsx
  src/scenes/SystemAdmin/index.scss
Labels: Scrummy Bears, INTEGRATION

#13395 B-19687-INT Modal issue workaround
  src/components/Office/DefinitionLists/NTSRShipmentInfoList.jsx
  src/components/Office/DefinitionLists/NTSShipmentInfoList.jsx
  src/components/Office/DefinitionLists/PPMShipmentInfoList.jsx
  src/components/Office/DefinitionLists/ShipmentInfoList.jsx
Labels: G-Unit, INTEGRATION

#13401 INT B-20652 boat shipment customer flow
  pkg/handlers/internalapi/moves.go
  pkg/services/orchestrators/shipment/shipment_updater.go
  playwright/tests/my/mymove/boat.spec.js
  playwright/tests/utils/my/waitForCustomerPage.js
  src/components/Customer/BoatShipment/BoatShipmentConfirmationModal/BoatShipmentConfirmationModal.jsx
  src/components/Customer/BoatShipment/BoatShipmentForm/BoatShipmentForm.jsx
  src/components/Customer/BoatShipment/BoatShipmentForm/BoatShipmentForm.module.scss
  src/components/Customer/BoatShipment/BoatShipmentForm/BoatShipmentForm.stories.jsx
  src/components/Customer/BoatShipment/BoatShipmentForm/BoatShipmentForm.test.jsx
  src/components/Customer/MtoShipmentForm/MtoShipmentForm.jsx
  src/components/Customer/MtoShipmentForm/getShipmentOptions.js
  src/components/Customer/Review/Summary/Summary.jsx
  src/components/Customer/modals/BoatInfoModal/BoatInfoModal.jsx
  src/components/Office/ShipmentContainer/ShipmentContainer.jsx
  src/components/ShipmentList/ShipmentList.jsx
  src/components/ShipmentTag/ShipmentTag.module.scss
  src/constants/routes.js
  src/constants/shipments.js
  src/content/shipments.js
  src/pages/MyMove/Boat/BoatShipmentCreate/BoatShipmentCreate.jsx
  src/pages/MyMove/Boat/BoatShipmentCreate/BoatShipmentCreate.test.jsx
  src/pages/MyMove/Boat/BoatShipmentLocationInfo/BoatShipmentLocationInfo.jsx
  src/pages/MyMove/Boat/BoatShipmentLocationInfo/BoatShipmentLocationInfo.test.jsx
  src/pages/MyMove/CreateOrEditMtoShipment.jsx
  src/pages/MyMove/Home/MoveHome.jsx
  src/pages/MyMove/PPM/Booking/DateAndLocation/DateAndLocation.jsx
  src/pages/MyMove/SelectShipmentType.jsx
  src/scenes/MyMove/index.jsx
  src/shared/constants.js
  src/shared/styles/colors.scss
  src/types/shipment.js
  src/utils/formatMtoShipment.js
  src/utils/shipmentInfo.js
Labels: ByteSize M&Ms, INTEGRATION

#13383 B-20495: Move Search and Customer Search Trailing Space
  src/components/Table/SearchResultsTable.jsx
Labels: Mountain Movers, MAIN

#13407 removed redux-form from jsonschema and unused code
  src/shared/JsonSchemaForm/JsonSchemaField.js
  src/shared/JsonSchemaForm/index.css
  src/shared/JsonSchemaForm/index.jsx
  src/shared/JsonSchemaForm/index.test.js
  src/shared/JsonSchemaForm/reduxFieldNormalizer.js
  src/shared/JsonSchemaForm/validations.test.js
  src/shared/JsonSchemaForm/validator.js
Labels: Mountain Movers, INTEGRATION

#13410 MAIN B-20591 prime can update destination address for NTSR shipment
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/mto_shipment/update_shipment_destination_address.go
  pkg/gen/primeclient/mto_shipment/mto_shipment_client.go
  pkg/handlers/primeapi/mto_shipment.go
  pkg/services/shipment_address_update/shipment_address_update_requester.go
  pkg/services/shipment_address_update/shipment_address_update_requester_test.go
  pkg/testdatagen/testharness/dispatch.go
  pkg/testdatagen/testharness/make_move.go
  playwright/tests/office/txo/tooFlows.spec.js
  playwright/tests/utils/testharness.js
  src/components/Office/DefinitionLists/NTSRShipmentInfoList.jsx
  src/components/Office/DefinitionLists/NTSRShipmentInfoList.test.jsx
  src/components/Office/ShipmentForm/ShipmentForm.jsx
  src/components/Office/ShipmentForm/ShipmentForm.module.scss
  src/components/Office/ShipmentForm/ShipmentForm.test.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdateDestinationAddressForm.jsx
  swagger-def/prime.yaml
  swagger/prime.yaml
Labels: Mountain Movers, MAIN

#13411 MAIN B-20882 rejected sit resubmission for all sit service items (DO NOT MERGE UNTIL POA)
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/mto_service_item/update_m_t_o_service_item.go
  pkg/gen/primeclient/mto_service_item/mto_service_item_client.go
  pkg/gen/primemessages/update_m_t_o_service_item_model_type.go
  pkg/gen/primemessages/update_m_t_o_service_item_s_i_t.go
  pkg/handlers/primeapi/mto_service_item_test.go
  pkg/services/move_task_order/move_task_order_fetcher.go
  pkg/services/mto_service_item/mto_service_item_updater.go
  pkg/services/mto_service_item/mto_service_item_updater_test.go
  pkg/services/mto_service_item/mto_service_item_validators.go
  pkg/services/mto_service_item/mto_service_item_validators_test.go
  swagger-def/prime.yaml
  swagger/prime.yaml
Labels: do not merge, Mountain Movers, MAIN

#13406 B20446 int kb1 payment requests doc viewer
  src/pages/Office/PaymentRequestReview/PaymentRequestReview.jsx
  src/pages/Office/PaymentRequestReview/PaymentRequestReview.test.jsx
Labels: ByteSize M&Ms, INTEGRATION

#13403 INT B-20447 FIX: Customer Search Sorting Tweaks
  pkg/handlers/ghcapi/customer_test.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/models/service_member.go
  pkg/services/customer.go
  pkg/services/mocks/CustomerSearcher.go
  pkg/services/office_user/customer/customer_searcher.go
Labels: ByteSize M&Ms, INTEGRATION

#13416 INT B-20448 - payment request search
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/move/search_moves.go
  pkg/gen/ghcmessages/search_move.go
  pkg/handlers/ghcapi/move.go
  pkg/services/move.go
  pkg/services/move/move_searcher.go
  src/components/MoveSearchForm/MoveSearchForm.jsx
  src/components/MoveSearchForm/MoveSearchForm.test.jsx
  src/components/Table/SearchResultsTable.jsx
  src/pages/Office/HeadquartersQueues/HeadquartersQueues.jsx
  src/pages/Office/HeadquartersQueues/HeadquartersQueues.test.jsx
  src/pages/Office/MoveQueue/MoveQueue.jsx
  src/pages/Office/MoveQueue/MoveQueue.test.jsx
  src/pages/Office/PaymentRequestQueue/PaymentRequestQueue.jsx
  src/pages/Office/PaymentRequestQueue/PaymentRequestQueue.test.jsx
  src/pages/Office/QAECSRMoveSearch/QAECSRMoveSearch.jsx
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: ByteSize M&Ms, INTEGRATION

#13408 B 20116 app reducer redux form int
  src/appReducer.js
Labels: Mountain Movers, INTEGRATION

#13404 B 20620 mobile home db model main
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240801135811_create_mobile_home.up.sql
  migrations/app/schema/20240801135833_alter_mto_shipment_type_motorhome.up.sql
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/create_m_t_o_shipment.go
  pkg/gen/ghcmessages/create_mobile_home.go
  pkg/gen/ghcmessages/m_t_o_shipment_type.go
  pkg/gen/ghcmessages/mobile_home.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/m_t_o_shipment_type.go
  pkg/gen/primev2api/embedded_spec.go
  pkg/gen/primev2messages/m_t_o_shipment_type.go
  pkg/gen/primev3api/embedded_spec.go
  pkg/gen/primev3messages/m_t_o_shipment_type.go
  pkg/models/mobile_home.go
  pkg/models/mobile_home_test.go
  pkg/models/mto_shipments.go
  pkg/paperwork/evaluation_report.go
  pkg/services/mto_shipment/mto_shipment_creator_test.go
  pkg/services/mto_shipment/mto_shipment_updater.go
  pkg/services/mto_shipment/rules_test.go
  src/components/Office/ShipmentContainer/ShipmentContainer.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesMoveContainer/MultiMovesMoveContainer.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesTestData.js
  src/shared/constants.js
  swagger-def/definitions/MTOShipmentType.yaml
  swagger-def/definitions/MobileHome.yaml
  swagger-def/definitions/prime/MTOShipmentType.yaml
  swagger-def/definitions/prime/v2/MTOShipmentType.yaml
  swagger-def/definitions/prime/v3/MTOShipmentType.yaml
  swagger-def/ghc.yaml
  swagger/ghc.yaml
  swagger/prime.yaml
  swagger/prime_v2.yaml
  swagger/prime_v3.yaml
Labels: ByteSize M&Ms, MAIN

#13390 B20446-MAIN-payment requests doc viewer
  pkg/testdatagen/testharness/dispatch.go
  pkg/testdatagen/testharness/make_move.go
  playwright/tests/office/qaecsr/csrFlows.spec.js
  playwright/tests/utils/testharness.js
  src/components/Office/PaymentRequestCard/PaymentRequestCard.jsx
  src/components/Office/PaymentRequestCard/PaymentRequestCard.test.jsx
  src/pages/Office/PaymentRequestReview/PaymentRequestReview.jsx
  src/pages/Office/PaymentRequestReview/PaymentRequestReview.test.jsx
Labels: ByteSize M&Ms, MAIN

#13397 B 20287
  src/components/Office/DefinitionLists/PPMShipmentInfoList.jsx
  src/components/Office/DefinitionLists/PPMShipmentInfoList.test.jsx
  src/pages/MyMove/Home/MoveHome.jsx
  src/pages/MyMove/Home/MoveHome.test.jsx
Labels: Scrummy Bears, MAIN

#13422 MAIN B-20113 refactor edit profile redux form
  src/constants/routes.js
  src/scenes/MyMove/index.jsx
  src/scenes/Review/EditProfile.jsx
Labels: Mountain Movers, MAIN

#13412 MAIN - B-20282 prime sim edit button style fix
  src/pages/PrimeUI/MoveTaskOrder/MoveDetails.jsx
  src/pages/PrimeUI/MoveTaskOrder/MoveDetails.module.scss
Labels: ByteSize M&Ms, MAIN

#13405 INT B-20879 SIT panel & SIT extension fixes and calculation fixes
  playwright/tests/office/txo/sitUpdates.spec.js
  src/components/Office/ReviewSITExtensionModal/ReviewSITExtensionModal.jsx
  src/components/Office/ReviewSITExtensionModal/ReviewSITExtensionModal.module.scss
  src/components/Office/ReviewSITExtensionModal/ReviewSITExtensionModal.test.jsx
  src/components/Office/ShipmentSITDisplay/ShipmentSITDisplay.jsx
  src/components/Office/ShipmentSITDisplay/ShipmentSITDisplay.test.jsx
  src/components/Office/SubmitSITExtensionModal/SubmitSITExtensionModal.jsx
  src/components/Office/SubmitSITExtensionModal/SubmitSITExtensionModal.test.jsx
  src/utils/sitFormatters.jsx
  src/utils/sitFormatters.module.scss
  src/utils/sitFormatters.test.jsx
Labels: Mountain Movers, INTEGRATION

#13431 Main playwright ppm happy path issue fix
  migrations/app/schema/20240801135833_alter_mto_shipment_type_motorhome.up.sql
  playwright/tests/my/milmove/ppms/customerPpmTestFixture.js
Labels: ByteSize M&Ms, MAIN

#13396 B 20723 int
  pkg/handlers/ghcapi/mto_shipment.go
  pkg/services/mto_shipment/shipment_billable_weight.go
Labels: Scrummy Bears, INTEGRATION

#13399 B 20606 nts loa UI int
  pkg/testdatagen/scenario/devseed.go
  pkg/testdatagen/scenario/subscenarios.go
  pkg/testdatagen/testharness/dispatch.go
  pkg/testdatagen/testharness/make_move.go
  playwright/tests/office/servicescounseling/servicesCounselingNTS.spec.js
  playwright/tests/office/txo/tooFlowsNTS.spec.js
  playwright/tests/utils/testharness.js
  src/components/Office/OrdersDetailForm/OrdersDetailForm.jsx
  src/components/Office/OrdersDetailForm/OrdersDetailForm.stories.jsx
  src/components/Office/OrdersDetailForm/OrdersDetailForm.test.jsx
  src/pages/Office/Orders/Orders.jsx
  src/pages/Office/Orders/Orders.test.jsx
  src/pages/Office/ServicesCounselingOrders/ServicesCounselingOrders.jsx
  src/pages/Office/ServicesCounselingOrders/ServicesCounselingOrders.test.jsx
  src/reducers/loaValidation.js
  src/reducers/loaValidation.test.js
  src/services/ghcApi.js
Labels: Mountain Movers, INTEGRATION

#13418 INT B-20898 sit entry date & FADD validation on update and creation
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/mto_service_item/create_m_t_o_service_item.go
  pkg/gen/primeclient/mto_service_item/mto_service_item_client.go
  pkg/handlers/primeapi/mto_service_item.go
  pkg/handlers/primeapi/mto_service_item_test.go
  pkg/handlers/primeapiv2/mto_service_item_test.go
  pkg/handlers/primeapiv3/mto_service_item_test.go
  pkg/services/mto_service_item/mto_service_item_creator.go
  pkg/services/mto_service_item/mto_service_item_creator_test.go
  pkg/services/mto_service_item/mto_service_item_validators.go
  pkg/services/mto_service_item/mto_service_item_validators_test.go
  swagger-def/prime.yaml
  swagger/prime.yaml
Labels: Mountain Movers, INTEGRATION

#13428 Add counseling_transportation_office_id column to moves table
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240807212737_add_counseling_transportation_office_id_to_moves.up.sql
  pkg/models/move.go
Labels: G-Unit, INTEGRATION

#13382 B-20767 EDI Error Display Int
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/payment_request.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/payment_request.go
  pkg/services/payment_request/payment_request_list_fetcher.go
  src/components/Office/PaymentRequestCard/PaymentRequestCard.jsx
  src/components/Office/PaymentRequestCard/PaymentRequestCard.module.scss
  src/components/Office/PaymentRequestCard/PaymentRequestCard.test.jsx
  src/types/order.js
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: Mountain Movers, INTEGRATION

#13436 B20285-INT-tio review weights crash
  src/pages/Office/ReviewBillableWeight/ReviewBillableWeight.jsx
Labels: ByteSize M&Ms, INTEGRATION

#13414 B 20256 int prevent prime users from accessing pptas update
  cmd/pptas-api-client/main.go
  cmd/pptas-api-client/pptas/list_moves.go
  cmd/pptas-api-client/utils/connection.go
  cmd/pptas-api-client/utils/shared.go
Labels: G-Unit, INTEGRATION

#13342 INT-B-20477
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240729185147_add_cancel_to_ppm_status_enum.up.sql
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/move/move_canceler.go
  pkg/gen/ghcapi/ghcoperations/move/move_canceler_parameters.go
  pkg/gen/ghcapi/ghcoperations/move/move_canceler_responses.go
  pkg/gen/ghcapi/ghcoperations/move/move_canceler_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/ghcmessages/p_p_m_shipment_status.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/p_p_m_shipment_status.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/p_p_m_shipment_status.go
  pkg/gen/primev2api/embedded_spec.go
  pkg/gen/primev2messages/p_p_m_shipment_status.go
  pkg/gen/primev3api/embedded_spec.go
  pkg/gen/primev3messages/p_p_m_shipment_status.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/move.go
  pkg/services/move.go
  pkg/services/move/move_canceler.go
  pkg/services/move/move_canceler_test.go
  swagger-def/definitions/PPMShipmentStatus.yaml
  swagger-def/ghc.yaml
  swagger/ghc.yaml
  swagger/internal.yaml
  swagger/prime.yaml
  swagger/prime_v2.yaml
  swagger/prime_v3.yaml
Labels: G-Unit, INTEGRATION

#13447 B20285-MAIN-tio review weights crash
  migrations/app/migrations_manifest.txt
  src/pages/Office/ReviewBillableWeight/ReviewBillableWeight.jsx
Labels: ByteSize M&Ms, MAIN

#13258 B-19687 Services Counselor Tertiary Address
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/create_m_t_o_shipment.go
  pkg/gen/ghcmessages/m_t_o_shipment.go
  pkg/gen/ghcmessages/update_p_p_m_shipment.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/internal/payloads/payload_to_model.go
  src/components/Customer/MtoShipmentForm/getShipmentOptions.js
  src/components/Office/DefinitionLists/NTSRShipmentInfoList.jsx
  src/components/Office/DefinitionLists/NTSRShipmentInfoList.stories.jsx
  src/components/Office/DefinitionLists/NTSRShipmentInfoList.test.jsx
  src/components/Office/DefinitionLists/NTSShipmentInfoList.jsx
  src/components/Office/DefinitionLists/NTSShipmentInfoList.stories.jsx
  src/components/Office/DefinitionLists/NTSShipmentInfoList.test.jsx
  src/components/Office/DefinitionLists/PPMShipmentInfoList.jsx
  src/components/Office/DefinitionLists/ShipmentInfoList.jsx
  src/components/Office/DefinitionLists/ShipmentInfoList.stories.jsx
  src/components/Office/DefinitionLists/ShipmentInfoList.test.jsx
  src/components/Office/ShipmentForm/ShipmentForm.jsx
  src/components/Office/ShipmentForm/ShipmentForm.test.jsx
  src/components/Office/ShipmentForm/ppmShipmentSchema.js
  src/pages/Office/MoveDetails/MoveDetails.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
  src/utils/formatMtoShipment.js
  src/utils/formatMtoShipment.test.js
  swagger-def/definitions/MTOShipment.yaml
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: G-Unit, MAIN

#13457 B 20606 nts loa UI int
  playwright/tests/office/servicescounseling/servicesCounselingNTS.spec.js
  playwright/tests/office/txo/tooFlowsNTS.spec.js
Labels: Mountain Movers, INTEGRATION

#13432 B 20066 int
  pkg/paperwork/forms.go
Labels: Scrummy Bears, INTEGRATION

#13459 B-20767 EDI Error Display MAIN
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/payment_request.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/payment_request.go
  pkg/services/payment_request/payment_request_list_fetcher.go
  src/components/Office/PaymentRequestCard/PaymentRequestCard.jsx
  src/components/Office/PaymentRequestCard/PaymentRequestCard.module.scss
  src/components/Office/PaymentRequestCard/PaymentRequestCard.test.jsx
  src/types/order.js
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: Mountain Movers, MAIN

#13417 B 20740 and B 20296 ppm sit breakdown
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/p_p_m_s_i_t_estimated_cost.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/ppm_shipment.go
  pkg/handlers/ghcapi/ppm_shipment_test.go
  pkg/models/ppm_shipment.go
  pkg/services/mocks/PPMEstimator.go
  pkg/services/moving_expense/moving_expense_updater.go
  pkg/services/ppmshipment.go
  pkg/services/ppmshipment/ppm_estimator.go
  src/components/Office/PPM/ReviewExpense/ReviewExpense.jsx
  src/components/Office/PPM/SitCost/SitCost.jsx
  src/components/Office/PPM/SitCost/SitCost.module.scss
  src/components/Office/PPM/SitCost/SitCost.test.jsx
  src/components/Office/PPM/SitCostBreakdown/SitCostBreakdown.jsx
  src/components/Office/PPM/SitCostBreakdown/SitCostBreakdown.module.scss
  src/components/Office/PPM/SitCostBreakdown/SitCostBreakdown.test.jsx
  swagger-def/definitions/PPMSITEstimatedCost.yaml
  swagger/ghc.yaml
Labels: Scrummy Bears, MAIN

#13443 INT B-20879 & I-13189 calculation fixes
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/services/payment_request/payment_request_shipments_sit_balance_test.go
  pkg/services/sit_status/shipment_sit_status.go
  pkg/services/sit_status/shipment_sit_status_test.go
  src/utils/sitFormatters.jsx
  src/utils/sitFormatters.test.jsx
Labels: Mountain Movers, INTEGRATION

#12622 B 19181 create pptas api
  .envrc
  .gitignore
  .pre-commit-config.yaml
  .redocly.yaml
  Makefile
  cmd/milmove/serve.go
  pkg/auth/cookie.go
  pkg/cli/hosts.go
  pkg/cli/services.go
  pkg/cli/swagger.go
  pkg/gen/pptasapi/configure_mymove.go
  pkg/gen/pptasapi/doc.go
  pkg/gen/pptasapi/embedded_spec.go
  pkg/gen/pptasapi/pptasoperations/moves/list_moves.go
  pkg/gen/pptasapi/pptasoperations/moves/list_moves_parameters.go
  pkg/gen/pptasapi/pptasoperations/moves/list_moves_responses.go
  pkg/gen/pptasapi/pptasoperations/moves/list_moves_urlbuilder.go
  pkg/gen/pptasapi/pptasoperations/mymove_api.go
  pkg/gen/pptasapi/server.go
  pkg/gen/pptasclient/moves/list_moves_parameters.go
  pkg/gen/pptasclient/moves/list_moves_responses.go
  pkg/gen/pptasclient/moves/moves_client.go
  pkg/gen/pptasclient/mymove_client.go
  pkg/gen/pptasmessages/client_error.go
  pkg/gen/pptasmessages/list_move.go
  pkg/gen/pptasmessages/list_moves.go
  pkg/handlers/apitests.go
  pkg/handlers/pptasapi/api.go
  pkg/handlers/pptasapi/internal/payloads/model_to_payload.go
  pkg/handlers/pptasapi/moves.go
  pkg/handlers/routing/base_routing_suite.go
  pkg/handlers/routing/routing_init.go
  pkg/services/move.go
  public/swagger-ui/pptas.html
  scripts/gen-server
  swagger-def/definitions/ListMove.yaml
  swagger-def/definitions/ListMoves.yaml
  swagger-def/definitions/MoveStatus.yaml
  swagger-def/info/pptas_description.md
  swagger-def/pptas.yaml
  swagger-def/responses/ServerError.yaml
  swagger-def/tags/pptas_tags.yaml
  swagger/pptas.yaml
  swagger/redoc/pptas.html
Labels: G-Unit, MAIN

#13463 B-20639 B-20606 Fix migration script
  migrations/app/schema/20240731125005_retroactively_update_approve_at_column_based_on_available_to_prime.up.sql
Labels: Mountain Movers, INTEGRATION

#13440 B-20873-INT update FetchOfficeUsersByRoleAndGbloc to FetchOfficeUsersByRoleAndOffice
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/available_office_user.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/queues.go
  pkg/handlers/ghcapi/queues_test.go
  pkg/services/mocks/OfficeUserFetcherPop.go
  pkg/services/office_user.go
  pkg/services/office_user/office_user_fetcher.go
  pkg/services/office_user/office_user_fetcher_test.go
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: G-Unit, INTEGRATION

#13415 B 20256 main prevent prime users from accessing pptas
  .circleci/config.yml
  cmd/milmove/gen_certs_migration.go
  cmd/pptas-api-client/main.go
  cmd/pptas-api-client/pptas/list_moves.go
  cmd/pptas-api-client/utils/connection.go
  cmd/pptas-api-client/utils/shared.go
  config/env/demo.app-client-tls.env
  config/env/exp.app-client-tls.env
  config/env/loadtest.app-client-tls.env
  config/env/prd.app-client-tls.env
  config/env/review.app.env
  config/env/stg.app-client-tls.env
  docker-compose.local.yml
  docker-compose.mtls.yml
  docker-compose.mtls_local.yml
  docker-compose.prime.yml
  docker-compose.yml
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240607134224_allow_pptas_client.up.sql
  migrations/app/secure/20240729162353_joseph_doye_cn_cac.up.sql
  migrations/app/secure/20240729164930_mai_do_cac.up.sql
  pkg/cli/hosts.go
  pkg/cli/services.go
  pkg/factory/client_cert_factory.go
  pkg/gen/adminapi/embedded_spec.go
  pkg/gen/adminmessages/client_certificate.go
  pkg/gen/adminmessages/client_certificate_create.go
  pkg/gen/adminmessages/client_certificate_update.go
  pkg/gen/pptasapi/doc.go
  pkg/gen/pptasapi/embedded_spec.go
  pkg/gen/pptasapi/pptasoperations/moves/list_moves_urlbuilder.go
  pkg/gen/pptasapi/pptasoperations/mymove_api.go
  pkg/gen/pptasclient/mymove_client.go
  pkg/handlers/adminapi/client_certs.go
  pkg/handlers/apitests.go
  pkg/handlers/authentication/auth.go
  pkg/handlers/authentication/auth_test.go
  pkg/handlers/pptasapi/api.go
  pkg/handlers/routing/base_routing_suite.go
  pkg/handlers/routing/pptasapi_test/pptasapi_test.go
  pkg/handlers/routing/pptasapi_test/swagger_test.go
  pkg/handlers/routing/routing_init.go
  pkg/models/client_cert.go
  pkg/services/clientcert/client_cert_updater.go
  public/swagger-ui/pptas.html
  src/pages/Admin/ClientCerts/ClientCertCreate.jsx
  src/pages/Admin/ClientCerts/ClientCertEdit.jsx
  src/pages/Admin/ClientCerts/ClientCertList.jsx
  src/pages/Admin/ClientCerts/ClientCertShow.jsx
  src/setupProxy.js
  swagger-def/admin.yaml
  swagger-def/info/pptas_description.md
  swagger-def/pptas.yaml
  swagger/admin.yaml
  swagger/pptas.yaml
Labels: do not merge, G-Unit, MAIN

#13449 removed reduxt-form and unused jsonschema code
  src/shared/JsonSchemaForm/JsonSchemaField.js
  src/shared/JsonSchemaForm/index.css
  src/shared/JsonSchemaForm/index.jsx
  src/shared/JsonSchemaForm/index.test.js
  src/shared/JsonSchemaForm/reduxFieldNormalizer.js
  src/shared/JsonSchemaForm/validations.test.js
  src/shared/JsonSchemaForm/validator.js
Labels: Mountain Movers, MAIN

#13400 MAIN B-20652 boat shipment customer flow
  pkg/handlers/internalapi/moves.go
  pkg/services/orchestrators/shipment/shipment_updater.go
  playwright/tests/my/mymove/boat.spec.js
  playwright/tests/utils/my/waitForCustomerPage.js
  src/components/Customer/BoatShipment/BoatShipmentConfirmationModal/BoatShipmentConfirmationModal.jsx
  src/components/Customer/BoatShipment/BoatShipmentForm/BoatShipmentForm.jsx
  src/components/Customer/BoatShipment/BoatShipmentForm/BoatShipmentForm.module.scss
  src/components/Customer/BoatShipment/BoatShipmentForm/BoatShipmentForm.stories.jsx
  src/components/Customer/BoatShipment/BoatShipmentForm/BoatShipmentForm.test.jsx
  src/components/Customer/MtoShipmentForm/MtoShipmentForm.jsx
  src/components/Customer/MtoShipmentForm/getShipmentOptions.js
  src/components/Customer/Review/Summary/Summary.jsx
  src/components/Customer/modals/BoatInfoModal/BoatInfoModal.jsx
  src/components/Office/ShipmentContainer/ShipmentContainer.jsx
  src/components/ShipmentList/ShipmentList.jsx
  src/components/ShipmentTag/ShipmentTag.module.scss
  src/constants/routes.js
  src/constants/shipments.js
  src/content/shipments.js
  src/pages/MyMove/Boat/BoatShipmentCreate/BoatShipmentCreate.jsx
  src/pages/MyMove/Boat/BoatShipmentCreate/BoatShipmentCreate.test.jsx
  src/pages/MyMove/Boat/BoatShipmentLocationInfo/BoatShipmentLocationInfo.jsx
  src/pages/MyMove/Boat/BoatShipmentLocationInfo/BoatShipmentLocationInfo.test.jsx
  src/pages/MyMove/CreateOrEditMtoShipment.jsx
  src/pages/MyMove/Home/MoveHome.jsx
  src/pages/MyMove/PPM/Booking/DateAndLocation/DateAndLocation.jsx
  src/pages/MyMove/SelectShipmentType.jsx
  src/scenes/MyMove/index.jsx
  src/shared/constants.js
  src/shared/styles/colors.scss
  src/types/shipment.js
  src/utils/formatMtoShipment.js
  src/utils/shipmentInfo.js
Labels: ByteSize M&Ms, MAIN

#13465 MAIN - B-20288: Estimated/Actual Departure date labels for Office PPMShipmentInfo/SSW
  pkg/assets/paperwork/formtemplates/SSWPDFTemplate.pdf
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet_test.go
  src/components/Office/DefinitionLists/PPMShipmentInfoList.jsx
  src/components/Office/DefinitionLists/PPMShipmentInfoList.test.jsx
Labels: Scrummy Bears, MAIN

#13455 MAIN B-20685 Admin Overflow and Wounded Warrior Wrap Styling
  src/components/CUIHeader/CUIHeader.jsx
  src/components/CustomerHeader/index.module.scss
  src/pages/Office/MoveQueue/MoveQueue.module.scss
  src/pages/Office/PaymentRequestQueue/PaymentRequestQueue.module.scss
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.module.scss
  src/pages/PrimeUI/AvailableMoves/AvailableMovesQueue.module.scss
  src/pages/SignIn/SignIn.module.scss
  src/scenes/SystemAdmin/Home.jsx
  src/scenes/SystemAdmin/Home.module.scss
  src/scenes/SystemAdmin/index.jsx
  src/scenes/SystemAdmin/index.scss
Labels: Scrummy Bears, MAIN

#13452 MAIN B-19919 - Diversion Tags for Payment Requests
  src/components/Office/BillableWeight/BillableWeightCard/BillableWeightCard.jsx
  src/components/Office/BillableWeight/BillableWeightCard/BillableWeightCard.module.scss
  src/components/Office/BillableWeight/BillableWeightCard/BillableWeightCard.test.jsx
  src/components/ShipmentModificationTag/ShipmentModificationTag.module.scss
  src/pages/Office/DocumentViewerSidebar/DocumentViewerSidebar.jsx
  src/pages/Office/DocumentViewerSidebar/DocumentViewerSidebar.module.scss
  src/pages/Office/ReviewBillableWeight/ReviewBillableWeight.jsx
  src/pages/Office/ReviewBillableWeight/ReviewBillableWeight.module.scss
  src/pages/Office/ReviewBillableWeight/ReviewBillableWeight.test.jsx
Labels: Scrummy Bears, MAIN

#13450 B 20116 app reducer redux form main
  src/appReducer.js
Labels: Mountain Movers, MAIN

#13451 B 20062 remove redux form dependency main
  package.json
  yarn.lock
Labels: Mountain Movers, MAIN

#13434 B-20671 Parse TPPS Paid Invoice Report INT
  .pre-commit-config.yaml
  cmd/milmove-tasks/process_edis.go
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240802161708_tpps_paid_invoice_table.up.sql
  pkg/cli/gex_sftp.go
  pkg/edi/tpps_paid_invoice_report/parser.go
  pkg/edi/tpps_paid_invoice_report/parser_test.go
  pkg/edi/tpps_paid_invoice_report/tpps_data.go
  pkg/models/edi_errors_test.go
  pkg/models/edi_processing_test.go
  pkg/models/edi_type.go
  pkg/models/payment_request_to_interchange_control_number_test.go
  pkg/models/tpps_paid_invoice_report.go
  pkg/models/tpps_paid_invoice_report_test.go
  pkg/services/invoice/fixtures/tpps_paid_invoice_report_testfile.csv
  pkg/services/invoice/process_tpps_paid_invoice_report.go
  pkg/services/invoice/process_tpps_paid_invoice_report_test.go
Labels: Mountain Movers, INTEGRATION

#13441 INT B-20791 refactor evaluation report to a route
  src/components/Office/DefinitionLists/EvaluationReportViolationsList.module.scss
  src/components/Office/EvaluationReportView/EvaluationReportView.jsx
  src/components/Office/EvaluationReportView/EvaluationReportView.module.scss
  src/components/Office/EvaluationReportView/EvaluationReportView.test.jsx
  src/components/Office/QAEReportTable/QAEReportTable.jsx
  src/constants/routes.js
  src/pages/Office/EvaluationReports/EvaluationReports.module.scss
  src/pages/Office/TXOMoveInfo/TXOMoveInfo.jsx
Labels: Mountain Movers, INTEGRATION

#13469 MAIN B-20898 sit entry date & FADD validation on update and creation
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/mto_service_item/create_m_t_o_service_item.go
  pkg/gen/primeclient/mto_service_item/mto_service_item_client.go
  pkg/handlers/primeapi/mto_service_item.go
  pkg/handlers/primeapi/mto_service_item_test.go
  pkg/handlers/primeapiv2/mto_service_item_test.go
  pkg/handlers/primeapiv3/mto_service_item_test.go
  pkg/services/mto_service_item/mto_service_item_creator.go
  pkg/services/mto_service_item/mto_service_item_creator_test.go
  pkg/services/mto_service_item/mto_service_item_validators.go
  pkg/services/mto_service_item/mto_service_item_validators_test.go
  swagger-def/prime.yaml
  swagger/prime.yaml
Labels: Mountain Movers, MAIN

#13460 INT B-20450 boat customer shipment card
  .gitlab-ci.yml
  pkg/services/move/move_router.go
  pkg/services/mto_shipment/mto_shipment_creator.go
  playwright/tests/my/mymove/boat.spec.js
  src/components/Customer/BoatShipment/BoatShipmentConfirmationModal/BoatShipmentConfirmationModal.jsx
  src/components/Customer/BoatShipment/BoatShipmentConfirmationModal/BoatShipmentConfirmationModal.stories.jsx
  src/components/Customer/BoatShipment/BoatShipmentConfirmationModal/BoatShipmentConfirmationModal.test.jsx
  src/components/Customer/BoatShipment/BoatShipmentForm/BoatShipmentForm.jsx
  src/components/Customer/MtoShipmentForm/MtoShipmentForm.jsx
  src/components/Customer/Review/ShipmentCard/BoatShipmentCard/BoatShipmentCard.jsx
  src/components/Customer/Review/ShipmentCard/BoatShipmentCard/BoatShipmentCard.test.jsx
  src/components/Customer/Review/Summary/Summary.jsx
  src/components/Customer/Review/Summary/Summary.test.jsx
  src/components/DocumentViewerFileManager/DocumentViewerFileManager.jsx
  src/components/DocumentViewerFileManager/DocumentViewerFileManager.stories.jsx
  src/components/Office/ShipmentContainer/ShipmentContainer.jsx
  src/components/ShipmentList/ShipmentList.jsx
  src/components/ShipmentList/ShipmentList.module.scss
  src/constants/shipments.js
  src/pages/MyMove/Boat/BoatShipmentCreate/BoatShipmentCreate.jsx
  src/pages/MyMove/Boat/BoatShipmentCreate/BoatShipmentCreate.test.jsx
  src/pages/MyMove/CreateOrEditMtoShipment.jsx
  src/pages/MyMove/SelectShipmentType.jsx
  src/shared/constants.js
  src/shared/styles/_custom.scss
  src/shared/styles/colors.scss
  src/types/shipment.js
  src/utils/formatMtoShipment.js
  src/utils/shipments.js
Labels: ByteSize M&Ms, INTEGRATION

#13446 INT B-20792 add gsr_appeals table
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240812183447_add_gsr_appeals_table.up.sql
  pkg/models/gsr_appeals.go
  pkg/models/gsr_appeals_test.go
Labels: Mountain Movers, INTEGRATION

#13471 Revert "B 20256 main prevent prime users from accessing pptas"
  .circleci/config.yml
  cmd/milmove/gen_certs_migration.go
  cmd/pptas-api-client/main.go
  cmd/pptas-api-client/pptas/list_moves.go
  cmd/pptas-api-client/utils/connection.go
  cmd/pptas-api-client/utils/shared.go
  config/env/demo.app-client-tls.env
  config/env/exp.app-client-tls.env
  config/env/loadtest.app-client-tls.env
  config/env/prd.app-client-tls.env
  config/env/review.app.env
  config/env/stg.app-client-tls.env
  docker-compose.local.yml
  docker-compose.mtls.yml
  docker-compose.mtls_local.yml
  docker-compose.prime.yml
  docker-compose.yml
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240607134224_allow_pptas_client.up.sql
  migrations/app/schema/20240814144527_remove_allow_pptas_client.up.sql
  migrations/app/secure/20240729162353_joseph_doye_cn_cac.up.sql
  migrations/app/secure/20240729164930_mai_do_cac.up.sql
  pkg/cli/hosts.go
  pkg/cli/services.go
  pkg/factory/client_cert_factory.go
  pkg/gen/adminapi/embedded_spec.go
  pkg/gen/adminmessages/client_certificate.go
  pkg/gen/adminmessages/client_certificate_create.go
  pkg/gen/adminmessages/client_certificate_update.go
  pkg/gen/pptasapi/doc.go
  pkg/gen/pptasapi/embedded_spec.go
  pkg/gen/pptasapi/pptasoperations/moves/list_moves_urlbuilder.go
  pkg/gen/pptasapi/pptasoperations/mymove_api.go
  pkg/gen/pptasclient/mymove_client.go
  pkg/handlers/adminapi/client_certs.go
  pkg/handlers/apitests.go
  pkg/handlers/authentication/auth.go
  pkg/handlers/authentication/auth_test.go
  pkg/handlers/pptasapi/api.go
  pkg/handlers/routing/base_routing_suite.go
  pkg/handlers/routing/pptasapi_test/pptasapi_test.go
  pkg/handlers/routing/pptasapi_test/swagger_test.go
  pkg/handlers/routing/routing_init.go
  pkg/models/client_cert.go
  pkg/services/clientcert/client_cert_updater.go
  public/swagger-ui/pptas.html
  src/pages/Admin/ClientCerts/ClientCertCreate.jsx
  src/pages/Admin/ClientCerts/ClientCertEdit.jsx
  src/pages/Admin/ClientCerts/ClientCertList.jsx
  src/pages/Admin/ClientCerts/ClientCertShow.jsx
  src/setupProxy.js
  swagger-def/admin.yaml
  swagger-def/info/pptas_description.md
  swagger-def/pptas.yaml
  swagger/admin.yaml
  swagger/pptas.yaml
Labels: G-Unit, MAIN

#13473 Revert "B 19181 create pptas api"
  .envrc
  .gitignore
  .pre-commit-config.yaml
  .redocly.yaml
  Makefile
  cmd/milmove/serve.go
  pkg/auth/cookie.go
  pkg/cli/hosts.go
  pkg/cli/services.go
  pkg/cli/swagger.go
  pkg/gen/pptasapi/configure_mymove.go
  pkg/gen/pptasapi/doc.go
  pkg/gen/pptasapi/embedded_spec.go
  pkg/gen/pptasapi/pptasoperations/moves/list_moves.go
  pkg/gen/pptasapi/pptasoperations/moves/list_moves_parameters.go
  pkg/gen/pptasapi/pptasoperations/moves/list_moves_responses.go
  pkg/gen/pptasapi/pptasoperations/moves/list_moves_urlbuilder.go
  pkg/gen/pptasapi/pptasoperations/mymove_api.go
  pkg/gen/pptasapi/server.go
  pkg/gen/pptasclient/moves/list_moves_parameters.go
  pkg/gen/pptasclient/moves/list_moves_responses.go
  pkg/gen/pptasclient/moves/moves_client.go
  pkg/gen/pptasclient/mymove_client.go
  pkg/gen/pptasmessages/client_error.go
  pkg/gen/pptasmessages/list_move.go
  pkg/gen/pptasmessages/list_moves.go
  pkg/handlers/apitests.go
  pkg/handlers/pptasapi/api.go
  pkg/handlers/pptasapi/internal/payloads/model_to_payload.go
  pkg/handlers/pptasapi/moves.go
  pkg/handlers/routing/base_routing_suite.go
  pkg/handlers/routing/routing_init.go
  pkg/services/move.go
  public/swagger-ui/pptas.html
  scripts/gen-server
  swagger-def/definitions/ListMove.yaml
  swagger-def/definitions/ListMoves.yaml
  swagger-def/definitions/MoveStatus.yaml
  swagger-def/info/pptas_description.md
  swagger-def/pptas.yaml
  swagger-def/responses/ServerError.yaml
  swagger-def/tags/pptas_tags.yaml
  swagger/pptas.yaml
  swagger/redoc/pptas.html
Labels: G-Unit, MAIN

#13472 MAIN B-20879 SIT panel & SIT extension fixes and calculation fixes
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/services/payment_request/payment_request_shipments_sit_balance_test.go
  pkg/services/sit_status/shipment_sit_status.go
  pkg/services/sit_status/shipment_sit_status_test.go
  playwright/tests/office/txo/sitUpdates.spec.js
  src/components/Office/ReviewSITExtensionModal/ReviewSITExtensionModal.jsx
  src/components/Office/ReviewSITExtensionModal/ReviewSITExtensionModal.module.scss
  src/components/Office/ReviewSITExtensionModal/ReviewSITExtensionModal.test.jsx
  src/components/Office/ShipmentSITDisplay/ShipmentSITDisplay.jsx
  src/components/Office/ShipmentSITDisplay/ShipmentSITDisplay.test.jsx
  src/components/Office/SubmitSITExtensionModal/SubmitSITExtensionModal.jsx
  src/components/Office/SubmitSITExtensionModal/SubmitSITExtensionModal.test.jsx
  src/utils/sitFormatters.jsx
  src/utils/sitFormatters.module.scss
  src/utils/sitFormatters.test.jsx
Labels: Mountain Movers, MAIN

#13454 MAIN B-20651 - Prime Counseling Completed in Move History
  src/constants/MoveHistory/EventTemplates/UpdateMTOPostCounselingInformation/updateMTOStatusPrimeCounselingCompleted.jsx
  src/constants/MoveHistory/EventTemplates/UpdateMTOPostCounselingInformation/updateMTOStatusPrimeCounselingCompleted.test.jsx
  src/constants/MoveHistory/EventTemplates/UpdateMTOPostCounselingInformation/updateMTOStatusPrimeCounselingCompletedPPM.jsx
  src/constants/MoveHistory/EventTemplates/UpdateMTOPostCounselingInformation/updateMTOStatusPrimeCounselingCompletedPPM.test.jsx
  src/constants/MoveHistory/EventTemplates/index.js
  src/constants/MoveHistory/UIDisplay/Operations.js
Labels: Scrummy Bears, MAIN

#13474 INT B-19226 - Customer onboarding required fields fixes
  src/components/Customer/ContactInfoForm/index.jsx
  src/components/Customer/EditContactInfoForm/EditContactInfoForm.jsx
  src/components/Customer/EditOrdersForm/EditOrdersForm.jsx
  src/components/Customer/EditOrdersForm/EditOrdersForm.test.jsx
  src/components/Customer/OrdersInfoForm/OrdersInfoForm.jsx
  src/components/Customer/OrdersInfoForm/OrdersInfoForm.test.jsx
  src/components/form/CustomerAltContactInfoFields/index.jsx
  src/components/form/CustomerContactInfoFields/index.jsx
  src/styles/form.module.scss
  src/utils/validation.js
Labels: ByteSize M&Ms

#13478 B 20066 space force pdf
  pkg/paperwork/forms.go
Labels: Scrummy Bears, MAIN

#13482 B-20723 / B-20726
  pkg/handlers/ghcapi/mto_shipment.go
  pkg/services/mto_shipment/shipment_billable_weight.go
Labels: Scrummy Bears, MAIN

#13421 B 20709 int
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240807140736_add_locked_price_cents_to_mto_service_items.up.sql
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/m_t_o_service_item.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/m_t_o_service_item.go
  pkg/gen/primemessages/m_t_o_service_item_basic.go
  pkg/gen/primemessages/m_t_o_service_item_dest_s_i_t.go
  pkg/gen/primemessages/m_t_o_service_item_domestic_crating.go
  pkg/gen/primemessages/m_t_o_service_item_origin_s_i_t.go
  pkg/gen/primemessages/m_t_o_service_item_shuttle.go
  pkg/gen/primev2api/embedded_spec.go
  pkg/gen/primev2messages/m_t_o_service_item.go
  pkg/gen/primev2messages/m_t_o_service_item_basic.go
  pkg/gen/primev2messages/m_t_o_service_item_dest_s_i_t.go
  pkg/gen/primev2messages/m_t_o_service_item_domestic_crating.go
  pkg/gen/primev2messages/m_t_o_service_item_origin_s_i_t.go
  pkg/gen/primev2messages/m_t_o_service_item_shuttle.go
  pkg/gen/primev3api/embedded_spec.go
  pkg/gen/primev3messages/m_t_o_service_item.go
  pkg/gen/primev3messages/m_t_o_service_item_basic.go
  pkg/gen/primev3messages/m_t_o_service_item_dest_s_i_t.go
  pkg/gen/primev3messages/m_t_o_service_item_domestic_crating.go
  pkg/gen/primev3messages/m_t_o_service_item_origin_s_i_t.go
  pkg/gen/primev3messages/m_t_o_service_item_shuttle.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/move_task_order_test.go
  pkg/models/mto_service_items.go
  pkg/services/move_task_order/move_task_order_updater_test.go
  pkg/services/mto_service_item/mto_service_item_creator.go
  pkg/services/mto_service_item/mto_service_item_creator_test.go
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
  swagger-def/definitions/MTOServiceItem.yaml
  swagger-def/definitions/prime/MTOServiceItem.yaml
  swagger/ghc.yaml
  swagger/prime.yaml
  swagger/prime_v2.yaml
  swagger/prime_v3.yaml
Labels: Scrummy Bears, INTEGRATION

#13490 MAIN B-20791 refactor evaluation report to a route
  src/components/Office/DefinitionLists/EvaluationReportViolationsList.module.scss
  src/components/Office/EvaluationReportView/EvaluationReportView.jsx
  src/components/Office/EvaluationReportView/EvaluationReportView.module.scss
  src/components/Office/EvaluationReportView/EvaluationReportView.test.jsx
  src/components/Office/QAEReportTable/QAEReportTable.jsx
  src/constants/routes.js
  src/pages/Office/EvaluationReports/EvaluationReports.module.scss
  src/pages/Office/TXOMoveInfo/TXOMoveInfo.jsx
Labels: Mountain Movers, MAIN

#13487 https://www13.v1host.com/USTRANSCOM38/assetdetail.v1?number=B-20440
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240806230447_add_rotation_to_uploads.up.sql
  package.json
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/ghcapi/ghcoperations/uploads/get_upload.go
  pkg/gen/ghcapi/ghcoperations/uploads/get_upload_parameters.go
  pkg/gen/ghcapi/ghcoperations/uploads/get_upload_responses.go
  pkg/gen/ghcapi/ghcoperations/uploads/get_upload_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/uploads/update_upload.go
  pkg/gen/ghcapi/ghcoperations/uploads/update_upload_parameters.go
  pkg/gen/ghcapi/ghcoperations/uploads/update_upload_responses.go
  pkg/gen/ghcapi/ghcoperations/uploads/update_upload_urlbuilder.go
  pkg/gen/ghcmessages/upload.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/upload.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/upload_with_omissions.go
  pkg/gen/primev2api/embedded_spec.go
  pkg/gen/primev2messages/upload_with_omissions.go
  pkg/gen/primev3api/embedded_spec.go
  pkg/gen/primev3messages/upload_with_omissions.go
  pkg/gen/supportapi/embedded_spec.go
  pkg/gen/supportmessages/upload_with_omissions.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/uploads.go
  pkg/models/upload.go
  pkg/services/mocks/UploadUpdater.go
  pkg/services/upload.go
  pkg/services/upload/upload_updater.go
  src/components/DocumentViewer/Content/Content.jsx
  src/components/DocumentViewer/Content/Content.module.scss
  src/components/DocumentViewer/Content/Content.test.jsx
  src/components/DocumentViewer/DocumentViewer.jsx
  src/constants/queryKeys.js
  src/pages/Office/MoveDocumentWrapper/MoveDocumentWrapper.jsx
  src/pages/Office/ServicesCounselingOrders/ServicesCounselingOrders.jsx
  src/pages/Office/SupportingDocuments/SupportingDocuments.test.jsx
  src/services/ghcApi.js
  swagger-def/definitions/Upload.yaml
  swagger-def/definitions/UploadWithOmissions.yaml
  swagger-def/ghc.yaml
  swagger/ghc.yaml
  swagger/internal.yaml
  swagger/prime.yaml
  swagger/prime_v2.yaml
  swagger/prime_v3.yaml
  swagger/support.yaml
  yarn.lock
Labels: ByteSize M&Ms, INTEGRATION

#13520 Revert changes due to issues with react-file-viewer PR needing to be done first
  package.json
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/ghcapi/ghcoperations/uploads/get_upload.go
  pkg/gen/ghcapi/ghcoperations/uploads/get_upload_parameters.go
  pkg/gen/ghcapi/ghcoperations/uploads/get_upload_responses.go
  pkg/gen/ghcapi/ghcoperations/uploads/get_upload_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/uploads/update_upload.go
  pkg/gen/ghcapi/ghcoperations/uploads/update_upload_parameters.go
  pkg/gen/ghcapi/ghcoperations/uploads/update_upload_responses.go
  pkg/gen/ghcapi/ghcoperations/uploads/update_upload_urlbuilder.go
  pkg/gen/ghcmessages/upload.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/upload.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/upload_with_omissions.go
  pkg/gen/primev2api/embedded_spec.go
  pkg/gen/primev2messages/upload_with_omissions.go
  pkg/gen/primev3api/embedded_spec.go
  pkg/gen/primev3messages/upload_with_omissions.go
  pkg/gen/supportapi/embedded_spec.go
  pkg/gen/supportmessages/upload_with_omissions.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/uploads.go
  pkg/models/upload.go
  pkg/services/mocks/UploadUpdater.go
  pkg/services/upload.go
  pkg/services/upload/upload_updater.go
  src/components/DocumentViewer/Content/Content.jsx
  src/components/DocumentViewer/Content/Content.module.scss
  src/components/DocumentViewer/Content/Content.test.jsx
  src/components/DocumentViewer/DocumentViewer.jsx
  src/constants/queryKeys.js
  src/pages/Office/MoveDocumentWrapper/MoveDocumentWrapper.jsx
  src/pages/Office/ServicesCounselingOrders/ServicesCounselingOrders.jsx
  src/pages/Office/SupportingDocuments/SupportingDocuments.test.jsx
  src/services/ghcApi.js
  swagger-def/definitions/Upload.yaml
  swagger-def/definitions/UploadWithOmissions.yaml
  swagger-def/ghc.yaml
  swagger/ghc.yaml
  swagger/internal.yaml
  swagger/prime.yaml
  swagger/prime_v2.yaml
  swagger/prime_v3.yaml
  swagger/support.yaml
  yarn.lock
Labels: ByteSize M&Ms, INTEGRATION

#13505 B-20915
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240819164156_update_pws_violations_pt3.up.sql
Labels: Mountain Movers, INTEGRATION

#13503 INT B-20706 MilMove Administrator Updates (Super Admin)
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240815182944_add_super_column_to_admin_users.up.sql
  pkg/gen/adminapi/adminoperations/mymove_api.go
  pkg/gen/adminapi/adminoperations/user/get_logged_in_admin_user.go
  pkg/gen/adminapi/adminoperations/user/get_logged_in_admin_user_parameters.go
  pkg/gen/adminapi/adminoperations/user/get_logged_in_admin_user_responses.go
  pkg/gen/adminapi/adminoperations/user/get_logged_in_admin_user_urlbuilder.go
  pkg/gen/adminapi/configure_mymove.go
  pkg/gen/adminapi/embedded_spec.go
  pkg/gen/adminmessages/admin_user.go
  pkg/gen/adminmessages/admin_user_create.go
  pkg/gen/adminmessages/admin_user_update.go
  pkg/handlers/adminapi/admin_users.go
  pkg/handlers/adminapi/api.go
  pkg/handlers/adminapi/user.go
  pkg/handlers/adminapi/user_test.go
  pkg/models/admin_user.go
  pkg/services/admin_user/admin_user_updater.go
  src/App/index.jsx
  src/appReducer.js
  src/pages/Admin/AdminUsers/AdminUserEdit.jsx
  src/pages/Admin/AdminUsers/AdminUserList.jsx
  src/pages/Admin/AdminUsers/AdminUserShow.jsx
  src/pages/Admin/OfficeUsers/OfficeUserEdit.jsx
  src/sagas/auth.js
  src/sagas/auth.test.js
  src/scenes/SystemAdmin/index.jsx
  src/scenes/SystemAdmin/shared/RolesPrivilegesCheckboxes.jsx
  src/shared/Entities/actions.js
  src/shared/Entities/reducer.js
  src/shared/Entities/schema.js
  src/shared/Swagger/api.js
  src/shared/store.js
  src/store/entities/selectors.js
  src/utils/api.js
  swagger-def/admin.yaml
  swagger/admin.yaml
Labels: Mountain Movers, INTEGRATION

#13486 B 20753 int
  pkg/services/mto_service_item/mto_service_item_creator.go
  pkg/testdatagen/testharness/make_move.go
  playwright/tests/office/txo/tooFlows.spec.js
  playwright/tests/office/txo/tooFlowsNTS.spec.js
  playwright/tests/office/txo/tooFlowsNTSR.spec.js
  playwright/tests/utils/testharness.js
  src/components/Customer/MtoShipmentForm/getShipmentOptions.js
  src/components/Office/ShipmentForm/ShipmentForm.jsx
  src/components/Office/ShipmentForm/ShipmentForm.test.jsx
Labels: Scrummy Bears, INTEGRATION

#13501 B-20293: MTO Page Shipment Header Missing Values
  src/components/Office/ShipmentHeading/ShipmentHeading.jsx
  src/components/Office/ShipmentHeading/ShipmentHeading.test.jsx
Labels: Mountain Movers, INTEGRATION

#13528 Int b 20477 2
  go.mod
  go.sum
  pkg/handlers/ghcapi/move.go
Labels: G-Unit, INTEGRATION

#13522 B 20919 sit date retention int
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/s_i_t_service_item_grouping.go
  pkg/gen/ghcmessages/s_i_t_service_item_groupings.go
  pkg/gen/ghcmessages/s_i_t_status.go
  pkg/gen/ghcmessages/s_i_t_summary.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/handlers/ghcapi/payment_request_test.go
  pkg/models/re_service.go
  pkg/services/mocks/ShipmentSITStatus.go
  pkg/services/mto_shipment.go
  pkg/services/payment_request/payment_request_shipments_sit_balance.go
  pkg/services/sit_status/shipment_sit_status.go
  pkg/services/sit_status/shipment_sit_status_test.go
  playwright/tests/office/txo/sitUpdates.spec.js
  src/components/Office/ShipmentSITDisplay/ShipmentSITDisplay.jsx
  src/components/Office/ShipmentSITDisplay/ShipmentSITDisplay.test.jsx
  src/components/Office/ShipmentSITDisplay/ShipmentSITDisplayTestParams.js
  swagger-def/definitions/SITServiceItemGrouping.yaml
  swagger-def/definitions/SITServiceItemGroupings.yaml
  swagger-def/definitions/SITStatus.yaml
  swagger-def/definitions/SITSummary.yaml
  swagger/ghc.yaml
Labels: Mountain Movers, INTEGRATION

#13510 B-20674 TPPS Paid Info INT
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240815195730_add_fk_to_tpps_paid_invoice_reports.up.sql
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/payment_request.go
  pkg/gen/ghcmessages/payment_service_item.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/models/payment_request.go
  pkg/services/invoice/process_tpps_paid_invoice_report_test.go
  pkg/services/payment_request/payment_request_list_fetcher.go
  src/components/Office/ExpandableServiceItemRow/ExpandableServiceItemRow.jsx
  src/components/Office/PaymentRequestCard/PaymentRequestCard.jsx
  src/components/Office/PaymentRequestCard/PaymentRequestCard.test.jsx
  src/components/Office/PaymentRequestDetails/PaymentRequestDetails.jsx
  src/components/Office/PaymentRequestDetails/PaymentRequestDetails.test.jsx
  src/types/order.js
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: Mountain Movers, INTEGRATION

#13529 INT B-20793 Add GSR role and base (QAE) traits in office/admin app
  .circleci/config.yml
  .envrc
  config/env/demo.app-client-tls.env
  config/env/demo.app.env
  config/env/exp.app-client-tls.env
  config/env/exp.app.env
  config/env/loadtest.app-client-tls.env
  config/env/loadtest.app.env
  config/env/prd.app-client-tls.env
  config/env/prd.app.env
  config/env/stg.app-client-tls.env
  config/env/stg.app.env
  config/flipt/storage/development.features.yaml
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240820151043_add_gsr_role.up.sql
  pkg/factory/role_factory.go
  pkg/factory/role_factory_test.go
  pkg/handlers/adminapi/requested_office_users.go
  pkg/handlers/authentication/devlocal.go
  pkg/handlers/authentication/devlocal_test.go
  pkg/handlers/authentication/permissions.go
  pkg/models/roles/roles.go
  src/components/form/OfficeAccountRequestFields/OfficeAccountRequestFields.jsx
  src/constants/routes.js
  src/constants/userRoles.js
  src/pages/Office/RequestAccount/RequestAccount.jsx
  src/pages/Office/RequestAccount/RequestAccount.module.scss
  src/pages/Office/index.jsx
  src/pages/Office/index.test.jsx
  src/pages/SelectApplication/SelectApplication.jsx
  src/utils/validation.js
Labels: Mountain Movers, INTEGRATION

#13498 INT B-20727 Estimated Weight for NTSR in Prime UI
  src/components/PrimeUI/Shipment/Shipment.jsx
  src/components/PrimeUI/Shipment/Shipment.test.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdate.jsx
Labels: Scrummy Bears, INTEGRATION

#13537 B-20873-INT Issue fix
  pkg/services/office_user/office_user_fetcher.go
Labels: G-Unit, INTEGRATION

#13540 B 20915
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240806151051_update_pws_violations.up.sql
  migrations/app/schema/20240816200315_update_pws_violations_pt2.up.sql
  migrations/app/schema/20240819164156_update_pws_violations_pt3.up.sql
Labels: Mountain Movers, MAIN

#13536 INT-B-20941-ssw-duplicate-state-zip
  pkg/factory/duty_location_factory.go
  pkg/factory/duty_location_factory_test.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet_test.go
Labels: Scrummy Bears, INTEGRATION

#13521 INT B-20603 backend boat office api
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/create_boat_shipment.go
  pkg/gen/ghcmessages/create_m_t_o_shipment.go
  pkg/gen/ghcmessages/update_boat_shipment.go
  pkg/gen/ghcmessages/update_shipment.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/internal/payloads/payload_to_model.go
  pkg/handlers/ghcapi/mto_shipment.go
  pkg/services/boat_shipment/boat_shipment_updater_test.go
  pkg/services/boat_shipment/rules.go
  pkg/services/boat_shipment/rules_test.go
  pkg/services/boat_shipment/validation.go
  src/components/Office/ShipmentContainer/ShipmentContainer.jsx
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: ByteSize M&Ms, INTEGRATION

#13538 B 20939 int
  cmd/generate-shipment-summary/main.go
  pkg/assets/paperwork/formtemplates/SSWPDFTemplate.pdf
  pkg/services/mocks/SSWPPMComputer.go
  pkg/services/ppmshipment/aoa_packet_creator.go
  pkg/services/shipment_summary_worksheet.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet_test.go
Labels: Scrummy Bears, INTEGRATION

#13527 B-20671 Parse TPPS Paid Invoice INT Part 2
  pkg/edi/tpps_paid_invoice_report/parser.go
  pkg/services/invoice/fixtures/tpps_paid_invoice_report_testfile_tpps_pickup_dir.csv
  pkg/services/invoice/process_edi824_test.go
  pkg/services/invoice/process_tpps_paid_invoice_report.go
  pkg/services/invoice/process_tpps_paid_invoice_report_test.go
Labels: Mountain Movers, INTEGRATION

#13549 20903 - Add counseling_transportation_office_id column to moves table
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240807212737_add_counseling_transportation_office_id_to_moves.up.sql
  pkg/models/move.go
Labels: G-Unit, MAIN

#13548 INT B-19226 Change forms to indicate "required" fields instead of "optional" ones
  src/components/Customer/BackupContactForm/BackupContactForm.test.jsx
  src/components/Customer/BoatShipment/BoatShipmentForm/BoatShipmentForm.test.jsx
  src/components/Customer/ContactInfoForm/ContactInfoForm.test.jsx
  src/components/Customer/ContactInfoForm/index.jsx
  src/components/Customer/DodInfoForm/DodInfoForm.test.jsx
  src/components/Customer/EditContactInfoForm/EditContactInfoForm.jsx
  src/components/Customer/EditOrdersForm/EditOrdersForm.jsx
  src/components/Customer/EditOrdersForm/EditOrdersForm.test.jsx
  src/components/Customer/MtoShipmentForm/MtoShipmentForm.jsx
  src/components/Customer/NameForm/NameForm.jsx
  src/components/Customer/NameForm/NameForm.test.jsx
  src/components/Customer/OrdersInfoForm/OrdersInfoForm.jsx
  src/components/Customer/OrdersInfoForm/OrdersInfoForm.test.jsx
  src/components/Customer/PPM/Booking/DateAndLocationForm/DateAndLocationForm.jsx
  src/components/Customer/PPM/Booking/DateAndLocationForm/DateAndLocationForm.test.jsx
  src/components/Customer/PPM/Closeout/AboutForm/AboutForm.jsx
  src/components/Customer/PPM/Closeout/ExpenseForm/ExpenseForm.jsx
  src/components/Customer/PPM/Closeout/FinalCloseoutForm/FinalCloseoutForm.test.jsx
  src/components/Customer/ServiceInfoForm/ServiceInfoForm.jsx
  src/components/Customer/ServiceInfoForm/ServiceInfoForm.test.jsx
  src/components/LocationSearchBox/LocationSearchBox.jsx
  src/components/Office/AddOrdersForm/AddOrdersForm.jsx
  src/components/Office/BillableWeight/EditBillableWeight/EditBillableWeight.jsx
  src/components/Office/BillableWeight/EditBillableWeight/EditBillableWeight.test.jsx
  src/components/Office/OrdersDetailForm/OrdersDetailForm.jsx
  src/components/Office/OrdersDetailForm/OrdersDetailForm.stories.jsx
  src/components/Office/PPM/PPMHeaderSummary/EditPPMHeaderSummaryModal.test.jsx
  src/components/Office/ServiceOrderNumberModal/ServiceOrderNumberModal.test.jsx
  src/components/Office/ShipmentWeightInput/ShipmentWeightInput.test.jsx
  src/components/Office/StorageFacilityInfo/StorageFacilityInfo.test.jsx
  src/components/form/AddressFields/AddressFields.jsx
  src/components/form/ContactInfoFields/ContactInfoFields.jsx
  src/components/form/CustomerAltContactInfoFields/index.jsx
  src/components/form/CustomerContactInfoFields/index.jsx
  src/components/form/OfficeAccountRequestFields/OfficeAccountRequestFields.jsx
  src/components/form/RequiredTag.jsx
  src/components/form/RequiredTag.module.scss
  src/components/form/fields/DatePickerInput.jsx
  src/components/form/fields/DropdownInput.jsx
  src/components/form/fields/DutyLocationInput.jsx
  src/components/form/fields/DutyLocationInput.test.jsx
  src/components/form/fields/MaskedTextField/MaskedTextField.jsx
  src/components/form/fields/TextField/TextField.jsx
  src/pages/Office/CustomerOnboarding/CreateCustomerForm.jsx
  src/pages/Office/Orders/Orders.jsx
  src/pages/Office/ServicesCounselingOrders/ServicesCounselingOrders.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdateAddressForm.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdateAddressForm.test.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdateDestinationAddressForm.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdateDestinationAddressForm.test.jsx
  src/utils/validation.js
Labels: ByteSize M&Ms, INTEGRATION

#13557 I 13243 int
  pkg/services/mto_shipment/mto_shipment_creator.go
  pkg/services/mto_shipment/mto_shipment_creator_test.go
Labels: Scrummy Bears, INTEGRATION

#13544 MAIN-B-20286: Partial PPM labeling change in Weight review
  src/components/Office/PPM/ReviewShipmentWeightsTable/ReviewShipmentWeightsTable.test.jsx
  src/components/Office/PPM/ReviewShipmentWeightsTable/helpers.jsx
Labels: Scrummy Bears, MAIN

#13507 INT-B-20824 - CLOSEOUT COMPLETE status for PPM on CONFIRM document review
  pkg/handlers/ghcapi/ppm_document_test.go
  pkg/services/ppmshipment/ppm_shipment_router.go
  pkg/services/ppmshipment/ppm_shipment_router_test.go
Labels: Scrummy Bears, INTEGRATION

#13552 B 20753
  pkg/services/mto_service_item/mto_service_item_creator.go
  pkg/services/mto_shipment/mto_shipment_creator.go
  pkg/services/mto_shipment/mto_shipment_creator_test.go
  pkg/testdatagen/testharness/make_move.go
  playwright/tests/office/txo/tooFlows.spec.js
  playwright/tests/office/txo/tooFlowsNTS.spec.js
  playwright/tests/office/txo/tooFlowsNTSR.spec.js
  playwright/tests/utils/testharness.js
  src/components/Customer/MtoShipmentForm/getShipmentOptions.js
  src/components/Office/ShipmentForm/ShipmentForm.jsx
  src/components/Office/ShipmentForm/ShipmentForm.test.jsx
Labels: Scrummy Bears, MAIN

#13502 B-20530-INT Office user assign/unassign functionality
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/move/delete_assigned_office_user.go
  pkg/gen/ghcapi/ghcoperations/move/delete_assigned_office_user_parameters.go
  pkg/gen/ghcapi/ghcoperations/move/delete_assigned_office_user_responses.go
  pkg/gen/ghcapi/ghcoperations/move/delete_assigned_office_user_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/move/update_assigned_office_user.go
  pkg/gen/ghcapi/ghcoperations/move/update_assigned_office_user_parameters.go
  pkg/gen/ghcapi/ghcoperations/move/update_assigned_office_user_responses.go
  pkg/gen/ghcapi/ghcoperations/move/update_assigned_office_user_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/ghcmessages/assign_office_user_body.go
  pkg/gen/ghcmessages/assigned_office_user.go
  pkg/gen/ghcmessages/move.go
  pkg/gen/ghcmessages/queue_move.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/move.go
  pkg/handlers/ghcapi/move_test.go
  pkg/services/move.go
  pkg/services/move/assigned_office_user_updater.go
  src/services/ghcApi.js
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: G-Unit, INTEGRATION

#13556 B 20967 sit panel data fields int
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/handlers/ghcapi/payment_request_test.go
  pkg/services/mocks/ShipmentSITStatus.go
  pkg/services/mto_service_item/mto_service_item_updater_test.go
  pkg/services/mto_shipment.go
  pkg/services/payment_request/payment_request_shipments_sit_balance.go
  pkg/services/payment_request/payment_request_shipments_sit_balance_test.go
  pkg/services/sit_status/shipment_sit_status.go
  pkg/services/sit_status/shipment_sit_status_test.go
  pkg/testdatagen/testharness/dispatch.go
  pkg/testdatagen/testharness/make_move.go
  playwright/tests/office/txo/sitUpdates.spec.js
  playwright/tests/utils/testharness.js
  src/components/Office/ShipmentSITDisplay/ShipmentSITDisplay.jsx
  src/components/Office/ShipmentSITDisplay/ShipmentSITDisplay.test.jsx
Labels: Mountain Movers, INTEGRATION

#13543 B-20440 & B-20438 Zoom Rotate and Save Rotation Capabilities for Office Users
  config-overrides.js
  package.json
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/ghcapi/ghcoperations/uploads/get_upload.go
  pkg/gen/ghcapi/ghcoperations/uploads/get_upload_parameters.go
  pkg/gen/ghcapi/ghcoperations/uploads/get_upload_responses.go
  pkg/gen/ghcapi/ghcoperations/uploads/get_upload_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/uploads/update_upload.go
  pkg/gen/ghcapi/ghcoperations/uploads/update_upload_parameters.go
  pkg/gen/ghcapi/ghcoperations/uploads/update_upload_responses.go
  pkg/gen/ghcapi/ghcoperations/uploads/update_upload_urlbuilder.go
  pkg/gen/ghcmessages/upload.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/upload.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/upload_with_omissions.go
  pkg/gen/primev2api/embedded_spec.go
  pkg/gen/primev2messages/upload_with_omissions.go
  pkg/gen/primev3api/embedded_spec.go
  pkg/gen/primev3messages/upload_with_omissions.go
  pkg/gen/supportapi/embedded_spec.go
  pkg/gen/supportmessages/upload_with_omissions.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/uploads.go
  pkg/models/upload.go
  pkg/services/mocks/UploadUpdater.go
  pkg/services/upload.go
  pkg/services/upload/upload_updater.go
  src/components/DocumentViewer/Content/Content.jsx
  src/components/DocumentViewer/Content/Content.module.scss
  src/components/DocumentViewer/Content/Content.test.jsx
  src/components/DocumentViewer/DocumentViewer.jsx
  src/components/DocumentViewer/DocumentViewer.test.jsx
  src/constants/queryKeys.js
  src/pages/Office/MoveDocumentWrapper/MoveDocumentWrapper.jsx
  src/pages/Office/MoveDocumentWrapper/MoveDocumentWrapper.test.jsx
  src/pages/Office/ServicesCounselingMoveDocumentWrapper/ServicesCounselingMoveDocumentWrapper.jsx
  src/pages/Office/ServicesCounselingMoveDocumentWrapper/ServicesCounselingMoveDocumentWrapper.test.jsx
  src/pages/Office/ServicesCounselingOrders/ServicesCounselingOrders.jsx
  src/pages/Office/SupportingDocuments/SupportingDocuments.test.jsx
  src/services/ghcApi.js
  swagger-def/definitions/Upload.yaml
  swagger-def/definitions/UploadWithOmissions.yaml
  swagger-def/ghc.yaml
  swagger/ghc.yaml
  swagger/internal.yaml
  swagger/prime.yaml
  swagger/prime_v2.yaml
  swagger/prime_v3.yaml
  swagger/support.yaml
  yarn.lock
Labels: ByteSize M&Ms, INTEGRATION

#13562 INT B-18553 deprecate updateMTOShipment v1 prime endpoint
  cmd/prime-api-client/main.go
  cmd/prime-api-client/prime/update_mto_shipment.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/mto_shipment/update_m_t_o_shipment.go
  pkg/gen/primeapi/primeoperations/mto_shipment/update_m_t_o_shipment_parameters.go
  pkg/gen/primeapi/primeoperations/mto_shipment/update_m_t_o_shipment_responses.go
  pkg/gen/primeclient/mto_shipment/mto_shipment_client.go
  pkg/gen/primeclient/mto_shipment/update_m_t_o_shipment_parameters.go
  pkg/gen/primeclient/mto_shipment/update_m_t_o_shipment_responses.go
  pkg/handlers/primeapi/api.go
  pkg/handlers/primeapi/mto_shipment.go
  pkg/handlers/primeapi/mto_shipment_test.go
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdate.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdate.test.jsx
  src/services/primeApi.js
  swagger-def/prime.yaml
  swagger/prime.yaml
Labels: Mountain Movers, INTEGRATION

#13571 B-20440 and B-20438 follow up
  package.json
  yarn.lock
Labels: ByteSize M&Ms, INTEGRATION

#13569 INT B-18552 deprecate prime v1 createMTOShipment endpoint
  cmd/prime-api-client/main.go
  cmd/prime-api-client/prime/create_mto_shipment.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/mto_shipment/create_m_t_o_shipment.go
  pkg/gen/primeapi/primeoperations/mto_shipment/create_m_t_o_shipment_parameters.go
  pkg/gen/primeapi/primeoperations/mto_shipment/create_m_t_o_shipment_responses.go
  pkg/gen/primeclient/mto_shipment/create_m_t_o_shipment_parameters.go
  pkg/gen/primeclient/mto_shipment/create_m_t_o_shipment_responses.go
  pkg/gen/primeclient/mto_shipment/mto_shipment_client.go
  pkg/handlers/primeapi/api.go
  pkg/handlers/primeapi/mto_shipment.go
  pkg/handlers/primeapi/mto_shipment_test.go
  src/services/primeApi.js
  swagger-def/prime.yaml
  swagger/prime.yaml
Labels: Mountain Movers, INTEGRATION

#13564 INT B-20622 mobile home office api
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/create_m_t_o_shipment.go
  pkg/gen/ghcmessages/create_mobile_home.go
  pkg/gen/ghcmessages/create_mobile_home_shipment.go
  pkg/gen/ghcmessages/update_mobile_home_shipment.go
  pkg/gen/ghcmessages/update_shipment.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/internal/payloads/payload_to_model.go
  pkg/handlers/ghcapi/mto_shipment.go
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: ByteSize M&Ms, INTEGRATION

#13555 INT-B-20477
  pkg/models/ppm_shipment.go
  pkg/services/move/move_canceler.go
  pkg/services/move/move_router_test.go
Labels: G-Unit, INTEGRATION

#13553 B 20724 int
  pkg/services/mto_shipment/rules.go
Labels: Scrummy Bears, INTEGRATION

#13439 B-20873 update FetchOfficeUsersByRoleAndGbloc to FetchOfficeUsersByRoleAndOffice
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/available_office_user.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/queues.go
  pkg/handlers/ghcapi/queues_test.go
  pkg/services/mocks/OfficeUserFetcherPop.go
  pkg/services/office_user.go
  pkg/services/office_user/office_user_fetcher.go
  pkg/services/office_user/office_user_fetcher_test.go
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: G-Unit, MAIN

#13567 INT-B-19226 onboarding required fields fix for boat shipments
  src/components/Customer/BoatShipment/BoatShipmentForm/BoatShipmentForm.jsx
Labels: ByteSize M&Ms, INTEGRATION

#13554 B-20758 TPPS Paid Payment Request Status Update INT
  pkg/services/invoice/process_edi824.go
  pkg/services/invoice/process_tpps_paid_invoice_report.go
  pkg/services/invoice/process_tpps_paid_invoice_report_test.go
Labels: Mountain Movers, INTEGRATION

#13561 MAIN - B -19815- Office date validation/ alert - HHG, NTS, NTSR
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/calendar/is_date_weekend_holiday.go
  pkg/gen/ghcapi/ghcoperations/calendar/is_date_weekend_holiday_parameters.go
  pkg/gen/ghcapi/ghcoperations/calendar/is_date_weekend_holiday_responses.go
  pkg/gen/ghcapi/ghcoperations/calendar/is_date_weekend_holiday_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/ghcmessages/is_date_weekend_holiday_info.go
  pkg/gen/internalapi/configure_mymove.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalapi/internaloperations/calendar/is_date_weekend_holiday.go
  pkg/gen/internalapi/internaloperations/calendar/is_date_weekend_holiday_parameters.go
  pkg/gen/internalapi/internaloperations/calendar/is_date_weekend_holiday_responses.go
  pkg/gen/internalapi/internaloperations/calendar/is_date_weekend_holiday_urlbuilder.go
  pkg/gen/internalapi/internaloperations/mymove_api.go
  pkg/gen/internalmessages/is_date_weekend_holiday_info.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/calendar.go
  pkg/handlers/ghcapi/calendar_test.go
  pkg/handlers/internalapi/api.go
  pkg/handlers/internalapi/calendar.go
  pkg/handlers/internalapi/calendar_test.go
  pkg/services/calendar.go
  pkg/services/calendar/calendar_service_test.go
  pkg/services/calendar/date_selection_checker.go
  pkg/services/calendar/date_selection_checker_test.go
  pkg/services/mocks/DateSelectionChecker.go
  src/components/Customer/MtoShipmentForm/MtoShipmentForm.jsx
  src/components/Customer/MtoShipmentForm/MtoShipmentForm.test.jsx
  src/components/Office/ShipmentForm/ShipmentForm.jsx
  src/components/Office/ShipmentForm/ShipmentForm.test.jsx
  src/services/ghcApi.js
  src/services/internalApi.js
  src/utils/calendar.js
  swagger-def/ghc.yaml
  swagger-def/internal.yaml
  swagger/ghc.yaml
  swagger/internal.yaml
Labels: Scrummy Bears, MAIN

#13582 B 20967 sit panel data fields int
  pkg/services/payment_request/payment_request_shipments_sit_balance_test.go
  pkg/services/sit_status/shipment_sit_status.go
  playwright/tests/office/txo/sitUpdates.spec.js
Labels: Mountain Movers, INTEGRATION

#13573 INT B-20946 SSW max obligation calculation correction
  pkg/services/ppm_closeout/ppm_closeout.go
  pkg/services/ppmshipment/ppm_estimator.go
  pkg/services/ppmshipment/ppm_estimator_test.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet_test.go
  playwright/tests/office/ppms/happyPathFlows.spec.js
Labels: Mountain Movers, INTEGRATION

#13589 B 20997 int add pptas under prime simulator
  pkg/handlers/routing/routing_init.go
Labels: G-Unit, INTEGRATION

#13585 MAIN B-20792 add gsr_appeals table
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240812183447_add_gsr_appeals_table.up.sql
  pkg/models/gsr_appeals.go
  pkg/models/gsr_appeals_test.go
Labels: Mountain Movers, MAIN

#13586 MAIN B-18553 deprecate updateMTOShipment v1 prime endpoint
  cmd/prime-api-client/main.go
  cmd/prime-api-client/prime/update_mto_shipment.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/mto_shipment/update_m_t_o_shipment.go
  pkg/gen/primeapi/primeoperations/mto_shipment/update_m_t_o_shipment_parameters.go
  pkg/gen/primeapi/primeoperations/mto_shipment/update_m_t_o_shipment_responses.go
  pkg/gen/primeclient/mto_shipment/mto_shipment_client.go
  pkg/gen/primeclient/mto_shipment/update_m_t_o_shipment_parameters.go
  pkg/gen/primeclient/mto_shipment/update_m_t_o_shipment_responses.go
  pkg/handlers/primeapi/api.go
  pkg/handlers/primeapi/mto_shipment.go
  pkg/handlers/primeapi/mto_shipment_test.go
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdate.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdate.test.jsx
  src/services/primeApi.js
  swagger-def/prime.yaml
  swagger/prime.yaml
Labels: Mountain Movers, MAIN

#13590 B-20948 SSW Calculations INT
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet_test.go
Labels: Mountain Movers, INTEGRATION

#13578 B-20292: Customer's Profile | Contact info not updating the Alt. phone
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/create_service_member_payload.go
  pkg/gen/internalmessages/patch_service_member_payload.go
  pkg/gen/internalmessages/service_member_payload.go
  pkg/handlers/internalapi/service_members.go
  src/pages/MyMove/Profile/EditContactInfo.jsx
  src/pages/Office/CustomerOnboarding/CreateCustomerForm.jsx
  src/pages/Office/CustomerOnboarding/CreateCustomerForm.test.jsx
  swagger-def/internal.yaml
  swagger/internal.yaml
Labels: ByteSize M&Ms, INTEGRATION

#13559 B-20616 Add mobile shipment customer flows int
  pkg/handlers/internalapi/moves.go
  pkg/services/orchestrators/shipment/shipment_updater.go
  src/components/Customer/MobileHomeShipment/MobileHomeShipmentForm/MobileHomeShipmentForm.jsx
  src/components/Customer/MobileHomeShipment/MobileHomeShipmentForm/MobileHomeShipmentForm.module.scss
  src/components/Customer/MobileHomeShipment/MobileHomeShipmentForm/MobileHomeShipmentForm.stories.jsx
  src/components/Customer/MobileHomeShipment/MobileHomeShipmentForm/MobileHomeShipmentForm.test.jsx
  src/components/Customer/MtoShipmentForm/MtoShipmentForm.jsx
  src/components/Customer/MtoShipmentForm/getShipmentOptions.js
  src/components/Customer/Review/ShipmentCard/MobileHomeShipmentCard/MobileHomeShipmentCard.jsx
  src/components/Customer/Review/Summary/Summary.jsx
  src/components/Customer/modals/BoatAndMobileInfoModal/BoatAndMobileInfoModal.jsx
  src/components/Office/ShipmentContainer/ShipmentContainer.jsx
  src/components/ShipmentList/ShipmentList.jsx
  src/components/ShipmentList/ShipmentList.module.scss
  src/components/ShipmentTag/ShipmentTag.module.scss
  src/constants/routes.js
  src/constants/shipments.js
  src/content/shipments.js
  src/pages/MyMove/CreateOrEditMtoShipment.jsx
  src/pages/MyMove/Home/MoveHome.jsx
  src/pages/MyMove/MobileHome/MobileHomeShipmentCreate/MobileHomeShipmentCreate.jsx
  src/pages/MyMove/MobileHome/MobileHomeShipmentCreate/MobileHomeShipmentCreate.test.jsx
  src/pages/MyMove/MobileHome/MobileHomeShipmentLocationInfo/MobileHomeShipmentLocationInfo.jsx
  src/pages/MyMove/MobileHome/MobileHomeShipmentLocationInfo/MobileHomeShipmentLocationInfo.test.jsx
  src/pages/MyMove/SelectShipmentType.jsx
  src/scenes/MyMove/index.jsx
  src/shared/constants.js
  src/shared/styles/_custom.scss
  src/shared/styles/colors.scss
  src/types/shipment.js
  src/utils/shipmentInfo.js
  src/utils/shipments.js
Labels: ByteSize M&Ms, INTEGRATION

#13584 MAIN B-20706 MilMove Administrator Updates (Super Admin)
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240815182944_add_super_column_to_admin_users.up.sql
  pkg/gen/adminapi/adminoperations/mymove_api.go
  pkg/gen/adminapi/adminoperations/user/get_logged_in_admin_user.go
  pkg/gen/adminapi/adminoperations/user/get_logged_in_admin_user_parameters.go
  pkg/gen/adminapi/adminoperations/user/get_logged_in_admin_user_responses.go
  pkg/gen/adminapi/adminoperations/user/get_logged_in_admin_user_urlbuilder.go
  pkg/gen/adminapi/configure_mymove.go
  pkg/gen/adminapi/embedded_spec.go
  pkg/gen/adminmessages/admin_user.go
  pkg/gen/adminmessages/admin_user_create.go
  pkg/gen/adminmessages/admin_user_update.go
  pkg/handlers/adminapi/admin_users.go
  pkg/handlers/adminapi/api.go
  pkg/handlers/adminapi/user.go
  pkg/handlers/adminapi/user_test.go
  pkg/models/admin_user.go
  src/App/index.jsx
  src/appReducer.js
  src/pages/Admin/AdminUsers/AdminUserEdit.jsx
  src/pages/Admin/AdminUsers/AdminUserList.jsx
  src/pages/Admin/AdminUsers/AdminUserShow.jsx
  src/pages/Admin/OfficeUsers/OfficeUserEdit.jsx
  src/sagas/auth.js
  src/sagas/auth.test.js
  src/scenes/SystemAdmin/index.jsx
  src/scenes/SystemAdmin/shared/RolesPrivilegesCheckboxes.jsx
  src/shared/Entities/actions.js
  src/shared/Entities/reducer.js
  src/shared/Entities/schema.js
  src/shared/Swagger/api.js
  src/shared/store.js
  src/store/entities/selectors.js
  src/utils/api.js
  swagger-def/admin.yaml
  swagger/admin.yaml
Labels: Mountain Movers, MAIN

#13587 MAIN B-18552 deprecate prime v1 createMTOShipment endpoint
  cmd/prime-api-client/main.go
  cmd/prime-api-client/prime/create_mto_shipment.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/mto_shipment/create_m_t_o_shipment.go
  pkg/gen/primeapi/primeoperations/mto_shipment/create_m_t_o_shipment_parameters.go
  pkg/gen/primeapi/primeoperations/mto_shipment/create_m_t_o_shipment_responses.go
  pkg/gen/primeclient/mto_shipment/create_m_t_o_shipment_parameters.go
  pkg/gen/primeclient/mto_shipment/create_m_t_o_shipment_responses.go
  pkg/gen/primeclient/mto_shipment/mto_shipment_client.go
  pkg/handlers/primeapi/api.go
  pkg/handlers/primeapi/mto_shipment.go
  pkg/handlers/primeapi/mto_shipment_test.go
  src/services/primeApi.js
  swagger-def/prime.yaml
  swagger/prime.yaml
Labels: Mountain Movers, MAIN

#13568 B 20943 INT
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet_test.go
Labels: Scrummy Bears, INTEGRATION

#13566 MAIN B-20727 Prime Sim NTS-Release Weights Read Only
  src/components/PrimeUI/Shipment/Shipment.jsx
  src/components/PrimeUI/Shipment/Shipment.test.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdate.jsx
Labels: Scrummy Bears, MAIN

#13546 B 20441 int
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240821180447_populating_locked_price_cents_for_ms_and_cs.up.sql
  migrations/app/schema/20240822180409_adding_locked_price_cents_service_param.up.sql
  pkg/factory/mto_service_item_factory.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/service_item_param_name.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/service_item_param_name.go
  pkg/gen/primev2api/embedded_spec.go
  pkg/gen/primev2messages/service_item_param_name.go
  pkg/gen/primev3api/embedded_spec.go
  pkg/gen/primev3messages/service_item_param_name.go
  pkg/handlers/ghcapi/mto_service_items.go
  pkg/models/service_item_param_key.go
  pkg/payment_request/service_param_value_lookups/locked_price_cents_lookup.go
  pkg/payment_request/service_param_value_lookups/service_param_value_lookups.go
  pkg/services/ghc_rate_engine.go
  pkg/services/ghcrateengine/counseling_services_pricer.go
  pkg/services/ghcrateengine/counseling_services_pricer_test.go
  pkg/services/ghcrateengine/management_services_pricer.go
  pkg/services/ghcrateengine/management_services_pricer_test.go
  pkg/services/ghcrateengine/service_item_pricer_test.go
  pkg/services/mocks/CounselingServicesPricer.go
  pkg/services/mocks/ManagementServicesPricer.go
  pkg/services/payment_request/payment_request_recalculator_test.go
  swagger-def/definitions/ServiceItemParamName.yaml
  swagger/ghc.yaml
  swagger/prime.yaml
  swagger/prime_v2.yaml
  swagger/prime_v3.yaml
Labels: Scrummy Bears, INTEGRATION

#13423 B 20709
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240807140736_add_locked_price_cents_to_mto_service_items.up.sql
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/m_t_o_service_item.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/m_t_o_service_item.go
  pkg/gen/primemessages/m_t_o_service_item_basic.go
  pkg/gen/primemessages/m_t_o_service_item_dest_s_i_t.go
  pkg/gen/primemessages/m_t_o_service_item_domestic_crating.go
  pkg/gen/primemessages/m_t_o_service_item_origin_s_i_t.go
  pkg/gen/primemessages/m_t_o_service_item_shuttle.go
  pkg/gen/primev2api/embedded_spec.go
  pkg/gen/primev2messages/m_t_o_service_item.go
  pkg/gen/primev2messages/m_t_o_service_item_basic.go
  pkg/gen/primev2messages/m_t_o_service_item_dest_s_i_t.go
  pkg/gen/primev2messages/m_t_o_service_item_domestic_crating.go
  pkg/gen/primev2messages/m_t_o_service_item_origin_s_i_t.go
  pkg/gen/primev2messages/m_t_o_service_item_shuttle.go
  pkg/gen/primev3api/embedded_spec.go
  pkg/gen/primev3messages/m_t_o_service_item.go
  pkg/gen/primev3messages/m_t_o_service_item_basic.go
  pkg/gen/primev3messages/m_t_o_service_item_dest_s_i_t.go
  pkg/gen/primev3messages/m_t_o_service_item_domestic_crating.go
  pkg/gen/primev3messages/m_t_o_service_item_origin_s_i_t.go
  pkg/gen/primev3messages/m_t_o_service_item_shuttle.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/move_task_order_test.go
  pkg/models/mto_service_items.go
  pkg/services/move_task_order/move_task_order_updater_test.go
  pkg/services/mto_service_item/mto_service_item_creator.go
  pkg/services/mto_service_item/mto_service_item_creator_test.go
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
  swagger-def/definitions/MTOServiceItem.yaml
  swagger-def/definitions/prime/MTOServiceItem.yaml
  swagger/ghc.yaml
  swagger/prime.yaml
  swagger/prime_v2.yaml
  swagger/prime_v3.yaml
Labels: Scrummy Bears, MAIN

#13511 MAIN B-20603 backend boat office api
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/create_boat_shipment.go
  pkg/gen/ghcmessages/create_m_t_o_shipment.go
  pkg/gen/ghcmessages/update_boat_shipment.go
  pkg/gen/ghcmessages/update_shipment.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/internal/payloads/payload_to_model.go
  pkg/handlers/ghcapi/mto_shipment.go
  pkg/services/boat_shipment/boat_shipment_updater_test.go
  pkg/services/boat_shipment/rules.go
  pkg/services/boat_shipment/rules_test.go
  pkg/services/boat_shipment/validation.go
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: ByteSize M&Ms, MAIN

#13583 B 20942 int
  pkg/assets/paperwork/formtemplates/SSWPDFTemplate.pdf
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet_test.go
Labels: Scrummy Bears, INTEGRATION

#13601 MAIN-B-20824 - CLOSEOUT COMPLETE status for PPM on CONFIRM document review
  pkg/handlers/ghcapi/ppm_document_test.go
  pkg/services/ppmshipment/ppm_shipment_router.go
  pkg/services/ppmshipment/ppm_shipment_router_test.go
Labels: Scrummy Bears, MAIN

#13591 B-20445: Add Marine Corps BOS to Move Search and BOS filter in work queues
  src/components/Table/SearchResultsTable.jsx
  src/constants/queues.js
  src/pages/Office/MoveQueue/MoveQueue.jsx
  src/pages/Office/MoveQueue/MoveQueue.test.jsx
  src/pages/Office/ServicesCounselingEditShipmentDetails/ServicesCounselingEditShipmentDetails.test.jsx
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.jsx
Labels: ByteSize M&Ms, INTEGRATION

#13579 B-19191: Email Template not locating all duty location names
  pkg/notifications/move_submitted.go
  pkg/notifications/move_submitted_test.go
Labels: ByteSize M&Ms, INTEGRATION

#13600 B 20939 ssw prep dates
  cmd/generate-shipment-summary/main.go
  pkg/assets/paperwork/formtemplates/SSWPDFTemplate.pdf
  pkg/services/mocks/SSWPPMComputer.go
  pkg/services/ppmshipment/aoa_packet_creator.go
  pkg/services/shipment_summary_worksheet.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet_test.go
Labels: Scrummy Bears, MAIN

#13594 B-20947: SSW Actual Obligations 100% GCC Calculations
  cmd/generate-shipment-summary/main.go
  migrations/app/migrations_manifest.txt
  pkg/handlers/ghcapi/api.go
  pkg/handlers/internalapi/api.go
  pkg/models/worksheet_shipment.go
  pkg/services/mocks/SSWPPMComputer.go
  pkg/services/ppmshipment/aoa_packet_creator_test.go
  pkg/services/shipment_summary_worksheet.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet_test.go
Labels: Mountain Movers, INTEGRATION

#13599 B 20899 sit end date adjustments main
  pkg/handlers/primeapi/mto_service_item_test.go
  pkg/services/mto_service_item/mto_service_item_updater.go
  pkg/services/mto_service_item/mto_service_item_updater_test.go
  pkg/services/mto_service_item/mto_service_item_validators.go
  pkg/services/mto_service_item/mto_service_item_validators_test.go
Labels: Mountain Movers, MAIN
