Repository transcom/mymove, pull requests merged in 2024-04, with the labels that each got.

#12244 B 18882 int b add search capability for too and tio
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/move/search_moves.go
  pkg/gen/ghcapi/ghcoperations/queues/get_payment_requests_queue_parameters.go
  pkg/gen/ghcmessages/move_status.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload_test.go
  pkg/handlers/ghcapi/move.go
  pkg/handlers/ghcapi/move_test.go
  pkg/handlers/ghcapi/mto_service_items.go
  pkg/services/move/move_searcher.go
  pkg/services/move/move_searcher_test.go
  pkg/services/payment_request/payment_request_list_fetcher.go
  playwright/tests/office/homepage.spec.js
  playwright/tests/office/txo/tioFlows.spec.js
  playwright/tests/office/txo/tooFlows.spec.js
  playwright/tests/utils/playwrightUtility.js
  src/components/MoveSearchForm/MoveSearchForm.jsx
  src/components/Table/SearchResultsTable.jsx
  src/constants/queues.js
  src/constants/routes.js
  src/pages/Office/MoveQueue/MoveQueue.jsx
  src/pages/Office/MoveQueue/MoveQueue.test.jsx
  src/pages/Office/PaymentRequestQueue/PaymentRequestQueue.jsx
  src/pages/Office/PaymentRequestQueue/PaymentRequestQueue.test.jsx
  src/pages/Office/QAECSRMoveSearch/QAECSRMoveSearch.jsx
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.jsx
  src/pages/Office/index.jsx
  src/pages/Office/index.test.jsx
  src/shared/constants.js
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: G-Unit, INTEGRATION

#12387 make error message more descriptive for failure to find county
  pkg/handlers/ghcapi/customer_test.go
  pkg/models/service_member.go
Labels: Mountain Movers, INTEGRATION

#12390 Moved some fields from ddasit to dddsit
  src/components/Office/ServiceItemDetails/ServiceItemDetails.jsx
  src/components/Office/ServiceItemDetails/ServiceItemDetails.test.jsx
Labels: Mountain Movers, INTEGRATION

#12381 B-19120
  src/components/Office/WeightSummary/WeightSummary.jsx
  src/components/Office/WeightSummary/WeightSummary.module.scss
  src/components/Office/WeightSummary/WeightSummary.test.jsx
  src/pages/Office/ReviewBillableWeight/ReviewBillableWeight.jsx
Labels: G-Unit, MAIN

#12281 B 18821 main
  .circleci/config.yml
  .envrc
  docker-compose.ecs.yml
  docker-compose.mtls.yml
  docker-compose.prime.yml
  docker-compose.yml
  pkg/cli/auth.go
Labels: Mountain Movers, MAIN

#12358 B 18752 move history log signs submit integration
  pkg/assets/sql_scripts/move_history_fetcher.sql
  src/constants/MoveHistory/EventTemplates/SubmitMoveForApproval/SubmitMoveForApprovalMTOShipments.jsx
  src/constants/MoveHistory/EventTemplates/SubmitMoveForApproval/SubmitMoveForApprovalMTOShipments.test.jsx
  src/constants/MoveHistory/EventTemplates/SubmitMoveForApproval/SubmitMoveForApprovalPPMShipments.jsx
  src/constants/MoveHistory/EventTemplates/SubmitMoveForApproval/SubmitMoveForApprovalPPMShipments.test.jsx
  src/constants/MoveHistory/EventTemplates/SubmitMoveForApproval/submitMoveForApproval.jsx
  src/constants/MoveHistory/EventTemplates/SubmitMoveForApproval/submitMoveForApproval.test.jsx
Labels: ByteSize M&Ms, INTEGRATION

#12299 B 18909 rejected dsh or dlh main
  src/components/Office/ServiceItemsTable/ServiceItemsTable.jsx
  src/components/Office/ServiceItemsTable/ServiceItemsTable.test.jsx
Labels: Mountain Movers, MAIN

#12122 MAIN B-18824 requested office users get single user endpoint
  pkg/gen/adminapi/adminoperations/mymove_api.go
  pkg/gen/adminapi/adminoperations/requested_office_users/get_requested_office_user.go
  pkg/gen/adminapi/adminoperations/requested_office_users/get_requested_office_user_parameters.go
  pkg/gen/adminapi/adminoperations/requested_office_users/get_requested_office_user_responses.go
  pkg/gen/adminapi/adminoperations/requested_office_users/get_requested_office_user_urlbuilder.go
  pkg/gen/adminapi/adminoperations/requested_office_users/index_requested_office_users.go
  pkg/gen/adminapi/configure_mymove.go
  pkg/gen/adminapi/embedded_spec.go
  pkg/handlers/adminapi/api.go
  pkg/handlers/adminapi/requested_office_users.go
  pkg/handlers/adminapi/requested_office_users_test.go
  pkg/services/requested_office_users.go
  pkg/services/requested_office_users/requested_office_user_fetcher.go
  pkg/services/requested_office_users/requested_office_user_fetcher_test.go
  swagger-def/admin.yaml
  swagger/admin.yaml
Labels: Mountain Movers, MAIN

#12392 B 18795 main
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240322144246_updateAddressesCounty.up.sql
Labels: Mountain Movers, MAIN

#12272 MAIN B-18313 fixes and storybook updates
  src/pages/MyMove/Multi-Moves/MultiMovesLandingPage.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesLandingPage.test.jsx
Labels: Mountain Movers, MAIN

#12286 MAIN B-18653 fix for I-12658
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/internal_move.go
  pkg/handlers/internalapi/moves.go
  src/pages/MyMove/Home/MoveHome.jsx
  swagger-def/internal.yaml
  swagger/internal.yaml
Labels: Mountain Movers, MAIN

#12287 MAIN B-19164 add Okta customer group id for each environment to chamber & update config files (MERGE AFTER MAIN B-18821)
  .circleci/config.yml
  .envrc
  pkg/cli/auth.go
Labels: Mountain Movers, MAIN

#12395 B-18798: create mto shipment address with addressCreator createAddress
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/handlers/internalapi/api.go
  pkg/handlers/internalapi/mto_shipment_test.go
  pkg/handlers/primeapi/api.go
  pkg/handlers/primeapi/mto_shipment_test.go
  pkg/handlers/primeapiv2/api.go
  pkg/handlers/primeapiv2/mto_shipment_test.go
  pkg/services/mto_shipment/mto_shipment_creator.go
  pkg/services/mto_shipment/mto_shipment_creator_test.go
Labels: Mountain Movers, INTEGRATION

#12304 MAIN B-18915 create customer form for office users (MERGE AFTER MAIN B-18913 & MAIN B-19164)
  src/constants/routes.js
  src/pages/Office/CustomerOnboarding/CreateCustomerForm.jsx
  src/pages/Office/CustomerOnboarding/CreateCustomerForm.module.scss
  src/pages/Office/CustomerOnboarding/CreateCustomerForm.test.jsx
  src/pages/Office/CustomerOnboarding/CreateCustomerform.stories.jsx
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.jsx
  src/pages/Office/index.jsx
  swagger/admin.yaml
Labels: Mountain Movers, MAIN

#12260 B 18840 mto shipments pro gear migration
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240223144515_add_pro_gear_weights_to_mto_shipments.up.sql
Labels: Scrummy Bears, MAIN

#12406 MAIN-B-17922 - Deprecate INTERNAL PPM APIs
  pkg/gen/internalapi/configure_mymove.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalapi/internaloperations/mymove_api.go
  pkg/gen/internalapi/internaloperations/ppm/show_p_p_m_estimate.go
  pkg/gen/internalapi/internaloperations/ppm/show_p_p_m_estimate_parameters.go
  pkg/gen/internalapi/internaloperations/ppm/show_p_p_m_estimate_responses.go
  pkg/gen/internalapi/internaloperations/ppm/show_p_p_m_estimate_urlbuilder.go
  pkg/gen/internalapi/internaloperations/ppm/show_p_p_m_sit_estimate.go
  pkg/gen/internalapi/internaloperations/ppm/show_p_p_m_sit_estimate_parameters.go
  pkg/gen/internalapi/internaloperations/ppm/show_p_p_m_sit_estimate_responses.go
  pkg/gen/internalapi/internaloperations/ppm/show_p_p_m_sit_estimate_urlbuilder.go
  pkg/gen/internalmessages/p_p_m_sit_estimate.go
  pkg/handlers/authentication/auth.go
  pkg/services/event/internal_endpoint.go
  src/services/internalApi.js
  swagger-def/internal.yaml
  swagger/internal.yaml
Labels: Scrummy Bears, MAIN

#12404 MAIN - B-18641 display backup address in office app
  src/components/Office/DefinitionLists/CustomerInfoList.jsx
  src/components/Office/DefinitionLists/CustomerInfoList.stories.jsx
  src/components/Office/DefinitionLists/CustomerInfoList.test.jsx
  src/pages/Office/MoveDetails/MoveDetails.jsx
  src/pages/Office/MoveDetails/MoveDetails.test.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.test.jsx
Labels: Scrummy Bears, MAIN

#12370 B -18066/67-compile documents in order documentation
  cmd/generate-shipment-summary/main.go
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/ghcapi/ghcoperations/ppm/show_payment_packet.go
  pkg/gen/ghcapi/ghcoperations/ppm/show_payment_packet_parameters.go
  pkg/gen/ghcapi/ghcoperations/ppm/show_payment_packet_responses.go
  pkg/gen/ghcapi/ghcoperations/ppm/show_payment_packet_urlbuilder.go
  pkg/gen/internalapi/configure_mymove.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalapi/internaloperations/mymove_api.go
  pkg/gen/internalapi/internaloperations/ppm/show_payment_packet.go
  pkg/gen/internalapi/internaloperations/ppm/show_payment_packet_parameters.go
  pkg/gen/internalapi/internaloperations/ppm/show_payment_packet_responses.go
  pkg/gen/internalapi/internaloperations/ppm/show_payment_packet_urlbuilder.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/ppm_document.go
  pkg/handlers/ghcapi/ppm_document_test.go
  pkg/handlers/internalapi/api.go
  pkg/handlers/internalapi/ppm_shipment.go
  pkg/handlers/internalapi/ppm_shipment_test.go
  pkg/handlers/primeapi/api.go
  pkg/paperwork/generator.go
  pkg/services/mocks/PaymentPacketCreator.go
  pkg/services/paperwork/prime_download_user_upload_to_pdf_converter.go
  pkg/services/paperwork/prime_download_user_upload_to_pdf_converter_test.go
  pkg/services/ppmshipment.go
  pkg/services/ppmshipment/aoa_packet_creator_test.go
  pkg/services/ppmshipment/payment_packet_creator.go
  pkg/services/ppmshipment/payment_packet_creator_test.go
  pkg/services/ppmshipment/ppm_shipment_service_test.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet_test.go
  swagger-def/ghc.yaml
  swagger-def/internal.yaml
  swagger/ghc.yaml
  swagger/internal.yaml
Labels: Scrummy Bears, MAIN

#12368 B 18885 sit delivery miles calculation main
  .circleci/config.yml
  .envrc
  pkg/factory/mto_service_item_factory.go
  pkg/handlers/adminapi/api.go
  pkg/handlers/adminapi/moves_test.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/move_task_order_test.go
  pkg/handlers/ghcapi/mto_service_items_test.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/handlers/ghcapi/orders_test.go
  pkg/handlers/internalapi/api.go
  pkg/handlers/internalapi/mto_shipment_test.go
  pkg/handlers/primeapi/api.go
  pkg/handlers/primeapi/move_task_order_test.go
  pkg/handlers/primeapi/mto_service_item_test.go
  pkg/handlers/primeapi/mto_shipment_address_test.go
  pkg/handlers/primeapi/mto_shipment_test.go
  pkg/handlers/primeapi/sit_service_item_address_update_test.go
  pkg/handlers/primeapiv2/api.go
  pkg/handlers/primeapiv2/mto_service_item_test.go
  pkg/handlers/primeapiv2/mto_shipment_test.go
  pkg/handlers/supportapi/api.go
  pkg/handlers/supportapi/move_task_order_test.go
  pkg/handlers/supportapi/mto_service_item_test.go
  pkg/handlers/supportapi/mto_shipment_test.go
  pkg/models/mto_service_items.go
  pkg/services/move_history/move_history_fetcher_test.go
  pkg/services/move_task_order/move_task_order_updater_test.go
  pkg/services/mto_service_item/mto_service_item_creator.go
  pkg/services/mto_service_item/mto_service_item_creator_test.go
  pkg/services/mto_service_item/mto_service_item_updater.go
  pkg/services/mto_service_item/mto_service_item_updater_test.go
  pkg/services/mto_shipment/mto_shipment_address_updater.go
  pkg/services/mto_shipment/mto_shipment_address_updater_test.go
  pkg/services/mto_shipment/mto_shipment_updater.go
  pkg/services/mto_shipment/mto_shipment_updater_test.go
  pkg/services/mto_shipment/shipment_approver_test.go
  pkg/services/mto_shipment/shipment_deleter_test.go
  pkg/services/shipment_address_update/shipment_address_update_requester.go
  pkg/services/shipment_address_update/shipment_address_update_requester_test.go
  pkg/services/sit_address_update/sit_address_update_request_creator_test.go
  pkg/services/sit_extension/sit_extension_denier.go
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/testharness/make_move.go
Labels: Mountain Movers, MAIN

#12408 B 19148
  pkg/handlers/ghcapi/move_task_order.go
  pkg/handlers/ghcapi/mto_shipment.go
  pkg/handlers/ghcapi/ppm_document.go
  pkg/handlers/ghcapi/ppm_document_test.go
  pkg/handlers/internalapi/moves.go
  pkg/handlers/internalapi/office.go
  pkg/handlers/primeapi/move_task_order.go
  pkg/models/move.go
  pkg/services/mto_shipment/mto_shipment_updater.go
Labels: G-Unit, MAIN

#12411 B-18065
  playwright/tests/my/milmove/ppms/customerPpmTestFixture.js
  src/components/Office/DefinitionLists/PPMShipmentInfoList.jsx
  src/components/Office/DefinitionLists/PPMShipmentInfoList.test.jsx
  src/components/Office/ShipmentDisplay/ShipmentDisplay.jsx
  src/components/PPMSummaryList/PPMSummaryList.jsx
  src/components/PPMSummaryList/PPMSummaryList.test.jsx
  src/pages/MyMove/Home/MoveHome.jsx
  src/pages/MyMove/Home/MoveHome.test.jsx
  src/pages/MyMove/Home/index.jsx
  src/pages/MyMove/Home/index.test.jsx
  src/services/ghcApi.js
  src/services/internalApi.js
  src/shared/AsyncPacketDownloadLink/AsyncPacketDownloadLink.jsx
  src/shared/DownloadPacketErrorModal/DownloadPacketErrorModal.jsx
  src/shared/DownloadPacketErrorModal/DownloadPacketErrorModal.module.scss
Labels: Scrummy Bears, MAIN

#12410 B:19465 - Add a public GHCApi endpoint to get the transportation offices
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/ghcapi/ghcoperations/transportation_office/get_transportation_offices_open.go
  pkg/gen/ghcapi/ghcoperations/transportation_office/get_transportation_offices_open_parameters.go
  pkg/gen/ghcapi/ghcoperations/transportation_office/get_transportation_offices_open_responses.go
  pkg/gen/ghcapi/ghcoperations/transportation_office/get_transportation_offices_open_urlbuilder.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/tranportation_offices.go
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: Mountain Movers, INTEGRATION

#12391 B-18799 Address County Update Logic
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240403172437_backfill_counties_again.up.sql
  pkg/factory/address_factory.go
  pkg/factory/address_factory_test.go
  pkg/handlers/authentication/devlocal.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/handlers/internalapi/addresses.go
  pkg/handlers/internalapi/addresses_test.go
  pkg/handlers/internalapi/api.go
  pkg/handlers/internalapi/duty_locations_test.go
  pkg/handlers/internalapi/internal/payloads/model_to_payload.go
  pkg/handlers/internalapi/internal/payloads/payload_to_model.go
  pkg/handlers/internalapi/mto_shipment_test.go
  pkg/handlers/primeapi/api.go
  pkg/handlers/primeapi/mto_shipment_address_test.go
  pkg/handlers/primeapi/mto_shipment_test.go
  pkg/handlers/primeapi/payloads/model_to_payload.go
  pkg/handlers/primeapi/payloads/payload_to_model_test.go
  pkg/handlers/primeapiv2/api.go
  pkg/models/address.go
  pkg/models/address_test.go
  pkg/models/duty_location_test.go
  pkg/models/order_test.go
  pkg/models/service_member.go
  pkg/models/transportation_office_test.go
  pkg/services/address/address_creator.go
  pkg/services/address/address_creator_test.go
  pkg/services/address/address_updater.go
  pkg/services/address/address_updater_test.go
  pkg/services/mto_service_item/mto_service_item_creator.go
  pkg/services/mto_service_item/mto_service_item_updater.go
  pkg/services/mto_shipment/mto_shipment_address_updater.go
  pkg/services/mto_shipment/mto_shipment_address_updater_test.go
  pkg/services/mto_shipment/mto_shipment_creator.go
  pkg/services/mto_shipment/mto_shipment_updater.go
  pkg/services/mto_shipment/mto_shipment_updater_test.go
  pkg/testdatagen/make_address.go
Labels: Mountain Movers, INTEGRATION

#12384 INT-B-19143
  pkg/services/mto_shipment/mto_shipment_updater.go
Labels: G-Unit, INTEGRATION

#12367 B-18902 and I-12678 I-12681 fixes MAIN
  pkg/services/mto_shipment/mto_shipment_updater.go
  pkg/services/shipment_address_update/shipment_address_update_requester.go
  pkg/services/shipment_address_update/shipment_address_update_requester_test.go
Labels: Mountain Movers, MAIN

#12393 MAIN - B 18670 UI office display pro gear info
  src/components/Office/ShipmentDetails/ShipmentDetailsMain.jsx
  src/components/Office/ShipmentWeightDetails/ShipmentWeightDetails.jsx
  src/components/Office/ShipmentWeightDetails/ShipmentWeightDetails.test.jsx
Labels: Scrummy Bears, MAIN

#12403 MAIN - B-18859 prime simulator displays/updates HHG pro gear
  src/components/PrimeUI/Shipment/Shipment.jsx
  src/components/PrimeUI/Shipment/Shipment.test.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdate.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdate.test.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdateForm.jsx
  src/services/primeApi.js
Labels: Scrummy Bears, MAIN

#12290 MAIN B 18889 remove prime ability to update destination address for approved shipment outside correct endpoint
  pkg/handlers/primeapi/mto_shipment.go
  pkg/handlers/primeapi/mto_shipment_address.go
  pkg/handlers/primeapi/mto_shipment_address_test.go
  pkg/handlers/primeapi/mto_shipment_test.go
  pkg/testdatagen/scenario/e2ebasic.go
  pkg/testdatagen/testharness/make_move.go
  playwright/tests/office/primesimulator/primeSimulatorFlows.spec.js
Labels: Mountain Movers, MAIN

#12399 INT B-19458 add linehaul service item order to service item list
  src/components/Office/ServiceItemsTable/ServiceItemsTable.jsx
Labels: Mountain Movers, INTEGRATION

#12305 MAIN B-18916 create customer and okta profile as office user backend (MERGE AFTER MAIN B-18915)
  .circleci/config.yml
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/customer/create_customer_with_okta_option.go
  pkg/gen/ghcapi/ghcoperations/customer/create_customer_with_okta_option_parameters.go
  pkg/gen/ghcapi/ghcoperations/customer/create_customer_with_okta_option_responses.go
  pkg/gen/ghcapi/ghcoperations/customer/create_customer_with_okta_option_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/ghcmessages/backup_contact.go
  pkg/gen/ghcmessages/create_customer_payload.go
  pkg/gen/ghcmessages/created_customer.go
  pkg/handlers/authentication/okta/provider.go
  pkg/handlers/authentication/okta/provider_test.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/customer.go
  pkg/handlers/ghcapi/customer_test.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload_test.go
  pkg/models/okta_user_create.go
  pkg/models/okta_user_info.go
  src/pages/Office/CustomerOnboarding/CreateCustomerForm.jsx
  src/pages/Office/CustomerOnboarding/CreateCustomerForm.test.jsx
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.module.scss
  src/services/ghcApi.js
  src/shared/Entities/schema.js
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: Mountain Movers, MAIN

#12327 B-18633 Actual Move Date not in the future backend
  pkg/apperror/errors.go
  pkg/handlers/internalapi/mto_shipment.go
  pkg/services/ppmshipment/ppm_shipment_updater.go
  pkg/services/ppmshipment/ppm_shipment_updater_test.go
  pkg/services/ppmshipment/validation.go
  pkg/services/ppmshipment/validation_test.go
Labels: ByteSize M&Ms, MAIN

#12280 B 19086 ssw field additions
  pkg/assets/paperwork/formtemplates/SSWPDFTemplate.pdf
  pkg/services/shipment_summary_worksheet.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet_test.go
Labels: Scrummy Bears, MAIN

#12394 B 18634 sc ability to see mto page
  pkg/handlers/authentication/permissions.go
  src/components/Office/RequestedServiceItemsTable/RequestedServiceItemsTable.test.jsx
  src/components/Office/ServiceItemsTable/ServiceItemsTable.jsx
  src/components/Office/ServiceItemsTable/ServiceItemsTable.test.jsx
  src/components/Office/ServicesCounselingTabNav/ServicesCounselingTabNav.jsx
  src/components/Office/ServicesCounselingTabNav/ServicesCounselingTabNav.test.jsx
  src/components/Office/ShipmentAddresses/ShipmentAddresses.jsx
  src/components/Office/ShipmentAddresses/ShipmentAddresses.test.jsx
  src/components/Office/ShipmentHeading/ShipmentHeading.jsx
  src/components/Office/ShipmentHeading/ShipmentHeading.test.jsx
  src/components/Office/ShipmentWeightDetails/ShipmentWeightDetails.jsx
  src/components/Office/ShipmentWeightDetails/ShipmentWeightDetails.test.jsx
  src/components/Office/WeightDisplay/WeightDisplay.jsx
  src/components/Office/WeightDisplay/WeightDisplay.test.jsx
  src/constants/permissions.js
  src/constants/routes.js
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.test.jsx
  src/pages/Office/ServicesCounselingMoveInfo/ServicesCounselingMoveInfo.jsx
  src/pages/Office/ServicesCounselingMoveInfo/ServicesCounselingMoveInfo.test.jsx
Labels: Scrummy Bears, MAIN

#12343 MAIN B-18631 All shipment weight values displayed sc closeout
  pkg/testdatagen/testharness/dispatch.go
  pkg/testdatagen/testharness/make_move.go
  playwright/tests/office/servicescounseling/servicesCounselingWeightTickets.spec.js
  playwright/tests/utils/testharness.js
  src/components/Office/PPM/HHGWeightSummary/HHGWeightSummary.jsx
  src/components/Office/PPM/HHGWeightSummary/HHGWeightSummary.module.scss
  src/components/Office/PPM/HHGWeightSummary/HHGWeightSummary.test.jsx
  src/components/Office/PPM/ReviewWeightTicket/ReviewWeightTicket.jsx
Labels: ByteSize M&Ms, MAIN

#12374 MAIN B-18751 History Log: PPM Shipment Created
  src/constants/MoveHistory/EventTemplates/CreateMTOShipment/createMTOShipment.jsx
  src/constants/MoveHistory/EventTemplates/CreateMTOShipment/createMTOShipment.test.jsx
Labels: ByteSize M&Ms, MAIN

#12373 MAIN B-18497 B-18630 closeout office space force fixes
  src/components/Customer/PPM/Booking/DateAndLocationForm/DateAndLocationForm.jsx
  src/components/Customer/PPM/Closeout/FinalCloseoutForm/FinalCloseoutForm.jsx
  src/components/Customer/Review/ShipmentCard/PPMShipmentCard/PPMShipmentCard.jsx
  src/components/Office/ShipmentForm/ShipmentForm.jsx
  src/pages/MyMove/PPM/Booking/DateAndLocation/DateAndLocation.jsx
  src/utils/shipmentDisplay.jsx
Labels: ByteSize M&Ms, MAIN

#12314 B:18520 Update Nav Links To Return To Move Page(MERGE AFTER B-18654 & B-18913)(READY)
  .circleci/config.yml
  playwright/tests/my/milmove/ppms/customerPpmTestFixture.js
  playwright/tests/my/milmove/ppms/entireShipmentCloseout.spec.js
  playwright/tests/my/milmove/ppms/navigateToUploadDocs.spec.js
  playwright/tests/my/mymove/hhg.spec.js
  playwright/tests/my/mymove/nts.spec.js
  playwright/tests/my/mymove/ntsr.spec.js
  playwright/tests/my/mymove/onboarding.spec.js
  playwright/tests/my/mymove/orders.spec.js
  playwright/tests/my/mymove/uploads.spec.js
  playwright/tests/utils/my/customerTest.js
  playwright/tests/utils/my/waitForCustomerPage.js
  src/appReducer.js
  src/components/Customer/Review/Summary/Summary.jsx
  src/components/MilMoveHeader/CustomerUserInfo.jsx
  src/containers/Headers/CustomerLoggedInHeader.jsx
  src/containers/requireCustomerState/requireCustomerState.jsx
  src/pages/MyMove/Agreement.jsx
  src/pages/MyMove/Home/MoveHome.jsx
  src/pages/MyMove/MovingInfo.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesMoveContainer/MultiMovesMoveContainer.jsx
  src/pages/MyMove/PPM/Booking/DateAndLocation/DateAndLocation.jsx
  src/pages/MyMove/PPM/Closeout/About/About.jsx
  src/pages/MyMove/PPM/Closeout/About/About.test.jsx
  src/pages/MyMove/PPM/Closeout/Expenses/Expenses.jsx
  src/pages/MyMove/PPM/Closeout/Expenses/Expenses.test.jsx
  src/pages/MyMove/PPM/Closeout/FinalCloseout/FinalCloseout.jsx
  src/pages/MyMove/PPM/Closeout/FinalCloseout/FinalCloseout.test.jsx
  src/pages/MyMove/PPM/Closeout/ProGear/ProGear.jsx
  src/pages/MyMove/PPM/Closeout/ProGear/ProGear.test.jsx
  src/pages/MyMove/PPM/Closeout/Review/Review.jsx
  src/pages/MyMove/PPM/Closeout/Review/Review.test.jsx
  src/pages/MyMove/PPM/Closeout/WeightTickets/WeightTickets.jsx
  src/pages/MyMove/PPM/Closeout/WeightTickets/WeightTickets.test.jsx
  src/pages/MyMove/Profile/EditContactInfo.jsx
  src/pages/MyMove/Profile/EditServiceInfo.test.jsx
  src/pages/MyMove/Profile/Profile.jsx
  src/pages/MyMove/Profile/Profile.test.jsx
  src/pages/MyMove/Review/Review.jsx
  src/pages/MyMove/Review/Review.test.jsx
  src/pages/MyMove/UploadOrders.jsx
  src/store/general/action.test.js
  src/store/general/actions.js
  src/store/general/reducer.js
  src/store/general/reducer.test.js
  src/store/general/selectors.js
  src/store/general/selectors.test.js
Labels: Mountain Movers, MAIN

#12258 B 18404 sit service item info population main
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/m_t_o_service_item.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/mto_service_items.go
  playwright/tests/office/txo/sitUpdates.spec.js
  src/components/Office/RequestedServiceItemsTable/RequestedServiceItemsTable.jsx
  src/components/Office/RequestedServiceItemsTable/RequestedServiceItemsTable.test.jsx
  src/components/Office/ServiceItemDetails/ServiceItemDetails.jsx
  src/components/Office/ServiceItemDetails/ServiceItemDetails.test.jsx
  src/components/Office/ServiceItemsTable/ServiceItemsTable.jsx
  src/components/Office/ServiceItemsTable/ServiceItemsTable.test.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
  swagger-def/definitions/MTOServiceItem.yaml
  swagger/ghc.yaml
Labels: Mountain Movers, MAIN

#12288 MAIN B-18825 Admin API Approve/Reject/Update requested office user (MERGE AFTER MAIN B-18916)
  .circleci/config.yml
  pkg/gen/adminapi/adminoperations/mymove_api.go
  pkg/gen/adminapi/adminoperations/requested_office_users/update_requested_office_user.go
  pkg/gen/adminapi/adminoperations/requested_office_users/update_requested_office_user_parameters.go
  pkg/gen/adminapi/adminoperations/requested_office_users/update_requested_office_user_responses.go
  pkg/gen/adminapi/adminoperations/requested_office_users/update_requested_office_user_urlbuilder.go
  pkg/gen/adminapi/configure_mymove.go
  pkg/gen/adminapi/embedded_spec.go
  pkg/gen/adminmessages/requested_office_user_update.go
  pkg/handlers/adminapi/api.go
  pkg/handlers/adminapi/requested_office_users.go
  pkg/handlers/adminapi/requested_office_users_test.go
  pkg/services/mocks/RequestedOfficeUserUpdater.go
  pkg/services/mocks/RoleAssociater.go
  pkg/services/requested_office_users.go
  pkg/services/requested_office_users/requested_office_user_fetcher.go
  pkg/services/requested_office_users/requested_office_user_fetcher_test.go
  pkg/services/requested_office_users/requested_office_user_updater.go
  pkg/services/requested_office_users/requested_office_user_updater_test.go
  pkg/services/roles.go
  pkg/services/roles/roles.go
  pkg/services/roles/roles_service_test.go
  pkg/services/roles/roles_test.go
  swagger-def/admin.yaml
  swagger/admin.yaml
Labels: Mountain Movers, MAIN

#12424 INT B-18739 and B-18740 ppm aoa and packet download from multi move dashboard
  .circleci/config.yml
  pkg/gen/adminapi/adminoperations/requested_office_users/get_requested_office_user.go
  pkg/gen/adminapi/adminoperations/requested_office_users/update_requested_office_user.go
  pkg/gen/adminapi/embedded_spec.go
  src/components/ButtonDropdownMenu/ButtonDropdownMenu.jsx
  src/components/ButtonDropdownMenu/ButtonDropdownMenu.module.scss
  src/components/ButtonDropdownMenu/ButtonDropdownMenu.test.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesLandingPage.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesLandingPage.module.scss
  src/pages/MyMove/Multi-Moves/MultiMovesMoveContainer/MultiMovesMoveContainer.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesMoveContainer/MultiMovesMoveContainer.module.scss
  src/pages/MyMove/Multi-Moves/MultiMovesMoveContainer/MultiMovesMoveContainer.test.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesTestData.js
  swagger-def/admin.yaml
  swagger/admin.yaml
Labels: Mountain Movers, INTEGRATION

#12428 I-12742 (issue) B-18855 (story) Unable to submit payment request without adding weight billed - Internal Service Error
  pkg/payment_request/service_param_value_lookups/weight_billed_lookup.go
Labels: ByteSize M&Ms, INTEGRATION

#12418 B 18633 frontend- Integration
  playwright/tests/my/milmove/ppms/customerPpmTestFixture.js
  playwright/tests/my/milmove/ppms/entireShipmentCloseout.spec.js
  playwright/tests/my/milmove/ppms/entireShipmentOnboarding.spec.js
Labels: ByteSize M&Ms, INTEGRATION

#12432 B 18752 move history log signs submit
  pkg/assets/sql_scripts/move_history_fetcher.sql
  src/constants/MoveHistory/EventTemplates/SubmitMoveForApproval/SubmitMoveForApprovalMTOShipments.jsx
  src/constants/MoveHistory/EventTemplates/SubmitMoveForApproval/SubmitMoveForApprovalMTOShipments.test.jsx
  src/constants/MoveHistory/EventTemplates/SubmitMoveForApproval/SubmitMoveForApprovalPPMShipments.jsx
  src/constants/MoveHistory/EventTemplates/SubmitMoveForApproval/SubmitMoveForApprovalPPMShipments.test.jsx
  src/constants/MoveHistory/EventTemplates/SubmitMoveForApproval/submitMoveForApproval.jsx
  src/constants/MoveHistory/EventTemplates/SubmitMoveForApproval/submitMoveForApproval.test.jsx
Labels: ByteSize M&Ms, MAIN

#12423 B 19137 payment requests billable weight param changes int
  pkg/payment_request/service_param_value_lookups/weight_billed_lookup.go
  pkg/payment_request/service_param_value_lookups/weight_billed_lookup_test.go
  pkg/payment_request/service_param_value_lookups/weight_original_lookup.go
  pkg/payment_request/service_param_value_lookups/weight_original_lookup_test.go
  src/components/Office/ServiceItemCalculations/helpers.js
Labels: Mountain Movers, INTEGRATION

#12437 MAIN B-18829 admin UI show requested office user
  pkg/gen/adminapi/adminoperations/requested_office_users/get_requested_office_user.go
  pkg/gen/adminapi/adminoperations/requested_office_users/update_requested_office_user.go
  pkg/gen/adminapi/embedded_spec.go
  pkg/handlers/adminapi/api.go
  pkg/handlers/adminapi/requested_office_users.go
  pkg/handlers/adminapi/requested_office_users_test.go
  src/pages/Admin/RequestedOfficeUsers/RequestedOfficeUserShow.jsx
  src/scenes/SystemAdmin/Home.jsx
  swagger-def/admin.yaml
  swagger/admin.yaml
Labels: Mountain Movers, MAIN

#12440 INT B-18911 gun safe backend
  config/env/loadtest.app.env
  go.mod
  go.sum
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240404152441_add_gun_safe_to_entitlements.up.sql
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/counseling_update_allowance_payload.go
  pkg/gen/ghcmessages/entitlements.go
  pkg/gen/ghcmessages/update_allowance_payload.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/models/ghc_entitlements.go
  pkg/services/order/order_updater.go
  pkg/services/ppmshipment/validation.go
  src/pages/MyMove/MovingInfo.jsx
  src/pages/Office/CustomerOnboarding/CustomerName.jsx
  src/pages/Office/CustomerOnboarding/CustomerName.module.scss
  src/pages/Office/CustomerOnboarding/CustomerName.test.jsx
  swagger-def/ghc.yaml
  swagger/ghc.yaml
  yarn.lock
Labels: ByteSize M&Ms, INTEGRATION

#12443 B-18648 Update UI to reflect the changes made.
  playwright/tests/office/txo/tioFlows.spec.js
  src/components/Office/ServiceItemCalculations/ServiceItemCalculations.jsx
  src/components/Office/ServiceItemCalculations/ServiceItemCalculations.module.scss
  src/components/Office/ServiceItemCalculations/ServiceItemCalculations.test.jsx
  src/components/Office/ServiceItemCalculations/helpers.js
  src/components/Office/ServiceItemCalculations/helpers.test.js
  src/constants/serviceItems.js
  src/utils/formatters.js
Labels: ByteSize M&Ms, INTEGRATION

#12447 B 19470 main
  src/pages/SignIn/SignIn.jsx
  src/pages/SignIn/SignIn.module.scss
  src/scenes/SystemAdmin/index.jsx
Labels: Mountain Movers, MAIN

#12449 kickback B-18855 multiplier was not taking into account the different service items
  pkg/payment_request/service_param_value_lookups/weight_billed_lookup.go
Labels: ByteSize M&Ms, INTEGRATION

#12450 MAIN B-18831 admin UI add approve reject buttons and rejection input on overview page
  pkg/gen/adminapi/doc.go
  pkg/gen/adminapi/embedded_spec.go
  src/constants/routes.js
  src/pages/Admin/RequestedOfficeUsers/RequestedOfficeUserShow.jsx
  src/pages/Admin/RequestedOfficeUsers/RequestedOfficeUserShow.module.scss
  src/services/adminApi.js
  src/shared/Entities/schema.js
  swagger-def/admin.yaml
  swagger/admin.yaml
Labels: Mountain Movers, MAIN

#12344 B 18633 actual move date not found frontend
  playwright/tests/my/milmove/ppms/customerPpmTestFixture.js
  playwright/tests/my/milmove/ppms/entireShipmentOnboarding.spec.js
  playwright/tests/my/milmove/ppms/estimatedIncentive.spec.js
  playwright/tests/my/milmove/ppms/estimatedWeightsProgear.spec.js
  src/components/Customer/PPM/Closeout/AboutForm/AboutForm.jsx
  src/components/form/fields/DatePickerInput.jsx
Labels: ByteSize M&Ms, MAIN

#12407 B 18638 create ww order type
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/queues/list_prime_moves_parameters.go
  pkg/gen/ghcmessages/orders_type.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/orders_type.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/orders_type.go
  pkg/gen/primev2api/embedded_spec.go
  pkg/gen/primev2messages/orders_type.go
  pkg/gen/supportapi/embedded_spec.go
  pkg/gen/supportmessages/orders_type.go
  src/components/CustomerHeader/index.jsx
  src/components/MilMoveHeader/index.jsx
  src/components/Table/SearchResultsTable.jsx
  src/constants/orders.js
  src/containers/Headers/CustomerLoggedInHeader.jsx
  src/pages/MyMove/Home/MoveHome.jsx
  src/pages/MyMove/Home/index.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesMoveContainer/MultiMovesMoveContainer.jsx
  src/pages/Office/MoveQueue/MoveQueue.jsx
  src/pages/Office/PaymentRequestQueue/PaymentRequestQueue.jsx
  src/pages/Office/PaymentRequestQueue/PaymentRequestQueue.module.scss
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.jsx
  src/pages/PrimeUI/AvailableMoves/AvailableMovesQueue.jsx
  src/pages/PrimeUI/MoveTaskOrder/MoveDetails.jsx
  swagger-def/definitions/OrdersType.yaml
  swagger-def/ghc.yaml
  swagger-def/support.yaml
  swagger/ghc.yaml
  swagger/internal.yaml
  swagger/prime.yaml
  swagger/prime_v2.yaml
  swagger/support.yaml
Labels: G-Unit, MAIN

#12455 INT B-18978 add shipment locator be
  go.mod
  go.sum
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240402192009_add_shipment_locator_and_shipment_seq_num.up.sql
  pkg/assets/sql_scripts/move_history_fetcher.sql
  pkg/factory/mto_shipment_factory.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/m_t_o_shipment.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/m_t_o_shipment.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/internalapi/internal/payloads/model_to_payload.go
  pkg/models/move.go
  pkg/models/mto_shipments.go
  pkg/services/mto_shipment/mto_shipment_creator.go
  pkg/services/mto_shipment/mto_shipment_creator_test.go
  pkg/services/mto_shipment/mto_shipment_updater.go
  pkg/services/mto_shipment/shipment_deleter_test.go
  src/pages/Admin/RequestedOfficeUsers/RequestedOfficeUserShow.module.scss
  swagger-def/definitions/MTOShipment.yaml
  swagger-def/internal.yaml
  swagger/ghc.yaml
  swagger/internal.yaml
  yarn.lock
Labels: ByteSize M&Ms, INTEGRATION

#12421 B-18392 prime counseled ppm aoa link
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/internal_move.go
  pkg/gen/internalmessages/move_payload.go
  pkg/handlers/internalapi/moves.go
  src/pages/MyMove/Home/MoveHome.jsx
  src/pages/MyMove/Home/index.jsx
  swagger-def/internal.yaml
  swagger/internal.yaml
Labels: G-Unit, INTEGRATION

#12454 MAIN B-18836 send email when office account rejected
  pkg/assets/notifications/templates/office_account_rejected_template.html
  pkg/assets/notifications/templates/office_account_rejected_template.txt
  pkg/handlers/adminapi/requested_office_users.go
  pkg/notifications/office_account_rejected.go
Labels: Mountain Movers, MAIN

#12453 MAIN B-18832 admin UI add edit page for requested office users
  src/layout/AdminIdleTimeout.jsx
  src/pages/Admin/RequestedOfficeUsers/RequestedOfficeUserEdit.jsx
  src/pages/Admin/RequestedOfficeUsers/RequestedOfficeUserShow.jsx
  src/pages/Admin/RequestedOfficeUsers/RequestedOfficeUserShow.module.scss
  src/scenes/SystemAdmin/Home.jsx
  src/scenes/SystemAdmin/shared/form_validators.js
Labels: Mountain Movers, MAIN

#12463 Merging main into INT
  go.mod
  go.sum
  src/pages/MyMove/Home/MoveHome.jsx
  yarn.lock
Labels: Scrummy Bears, INTEGRATION

#12380 B-19124-INT
  src/components/Office/BillableWeight/EditBillableWeight/EditBillableWeight.jsx
  src/components/Office/BillableWeight/EditBillableWeight/EditBillableWeight.test.jsx
  src/components/Office/BillableWeight/ShipmentCard/ShipmentCard.jsx
  src/components/Office/BillableWeight/ShipmentCard/ShipmentCard.test.jsx
  src/components/ShipmentList/ShipmentList.jsx
  src/pages/Office/MovePaymentRequests/MovePaymentRequests.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.module.scss
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.test.jsx
  src/pages/Office/MoveTaskOrder/moveTaskOrderUnitTestData.js
  src/pages/Office/ReviewBillableWeight/ReviewBillableWeight.jsx
  src/pages/Office/ReviewBillableWeight/ReviewBillableWeight.test.jsx
Labels: G-Unit, INTEGRATION

#12458 INT B-18910 gun safe frontend
  src/components/Office/AllowancesDetailForm/AllowancesDetailForm.jsx
  src/components/Office/AllowancesDetailForm/AllowancesDetailForm.test.jsx
  src/components/Office/DefinitionLists/AllowancesList.jsx
  src/components/Office/DefinitionLists/AllowancesList.test.jsx
  src/pages/Office/MoveAllowances/MoveAllowances.jsx
  src/pages/Office/MoveAllowances/MoveAllowances.test.jsx
  src/pages/Office/MoveDetails/MoveDetails.jsx
  src/pages/Office/ServicesCounselingMoveAllowances/ServicesCounselingMoveAllowances.jsx
  src/pages/Office/ServicesCounselingMoveAllowances/ServicesCounselingMoveAllowances.test.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
Labels: ByteSize M&Ms, INTEGRATION

#12452 B-18798 B-18799 adding county on creation and update
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240403172437_backfill_counties_again.up.sql
  pkg/factory/address_factory.go
  pkg/factory/address_factory_test.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/address.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/address.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/address.go
  pkg/gen/primev2api/embedded_spec.go
  pkg/gen/primev2messages/address.go
  pkg/handlers/authentication/devlocal.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/customer_test.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/handlers/internalapi/addresses.go
  pkg/handlers/internalapi/addresses_test.go
  pkg/handlers/internalapi/api.go
  pkg/handlers/internalapi/duty_locations_test.go
  pkg/handlers/internalapi/internal/payloads/model_to_payload.go
  pkg/handlers/internalapi/internal/payloads/payload_to_model.go
  pkg/handlers/internalapi/mto_shipment_test.go
  pkg/handlers/internalapi/service_members_test.go
  pkg/handlers/primeapi/api.go
  pkg/handlers/primeapi/mto_shipment_address_test.go
  pkg/handlers/primeapi/mto_shipment_test.go
  pkg/handlers/primeapi/payloads/model_to_payload.go
  pkg/handlers/primeapi/payloads/payload_to_model_test.go
  pkg/handlers/primeapiv2/api.go
  pkg/handlers/primeapiv2/mto_shipment_test.go
  pkg/models/address.go
  pkg/models/address_test.go
  pkg/models/duty_location_test.go
  pkg/models/order_test.go
  pkg/models/service_member.go
  pkg/models/transportation_office_test.go
  pkg/models/us_post_region_city.go
  pkg/services/address/address_creator.go
  pkg/services/address/address_creator_test.go
  pkg/services/address/address_updater.go
  pkg/services/address/address_updater_test.go
  pkg/services/mto_service_item/mto_service_item_creator.go
  pkg/services/mto_service_item/mto_service_item_updater.go
  pkg/services/mto_shipment/mto_shipment_address_updater.go
  pkg/services/mto_shipment/mto_shipment_address_updater_test.go
  pkg/services/mto_shipment/mto_shipment_creator.go
  pkg/services/mto_shipment/mto_shipment_creator_test.go
  pkg/services/mto_shipment/mto_shipment_updater.go
  pkg/services/mto_shipment/mto_shipment_updater_test.go
  pkg/testdatagen/make_address.go
  swagger-def/definitions/Address.yaml
  swagger/admin.yaml
  swagger/ghc.yaml
  swagger/internal.yaml
  swagger/prime.yaml
  swagger/prime_v2.yaml
Labels: Mountain Movers, MAIN

#12442 B-19176-INT SC upload orders
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/doc.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/ghcapi/ghcoperations/uploads/create_upload.go
  pkg/gen/ghcapi/ghcoperations/uploads/create_upload_parameters.go
  pkg/gen/ghcapi/ghcoperations/uploads/create_upload_responses.go
  pkg/gen/ghcapi/ghcoperations/uploads/create_upload_urlbuilder.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/uploads.go
  pkg/handlers/ghcapi/uploads_test.go
  src/pages/Office/ServicesCounselingMoveDocumentWrapper/ServicesCounselingMoveDocumentWrapper.jsx
  src/pages/Office/ServicesCounselingOrders/ServicesCounselingOrders.jsx
  src/pages/Office/ServicesCounselingOrders/ServicesCounselingOrders.test.jsx
  src/services/ghcApi.js
  src/styles/documentViewerWithSidebar.module.scss
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: G-Unit, INTEGRATION

#12409 B 19095 create ff sc create moves
  src/components/Table/SearchResultsTable.jsx
  src/components/Table/SearchResultsTable.module.scss
  src/components/Table/SearchResultsTable.test.jsx
  src/components/Table/Table.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.module.scss
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.jsx
Labels: G-Unit, MAIN

#12462 Int b 18642 add origin gbloc to move screen front end - Test fix
  pkg/gen/ghcapi/embedded_spec.go
  src/components/CustomerHeader/CustomerHeader.stories.jsx
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: ByteSize M&Ms, INTEGRATION

#12469 B-19503 - spelling is hard
  src/pages/SignIn/SignIn.jsx
Labels: Mountain Movers, INTEGRATION

#12445 B:18828 - Add Create Okta Account Logic to UpdateRequestedOfficeUser(MERGE AFTER B-18821 & B-18825)(READY)
  pkg/gen/adminapi/adminoperations/requested_office_users/get_requested_office_user.go
  pkg/gen/adminapi/adminoperations/requested_office_users/index_requested_office_users.go
  pkg/gen/adminapi/adminoperations/requested_office_users/update_requested_office_user.go
  pkg/gen/adminapi/embedded_spec.go
  pkg/gen/adminmessages/okta_account_info_response.go
  pkg/gen/adminmessages/requested_office_user_update.go
  pkg/handlers/adminapi/requested_office_users.go
  pkg/handlers/adminapi/requested_office_users_test.go
  pkg/handlers/authentication/okta/provider.go
  pkg/handlers/authentication/okta/provider_test.go
  pkg/models/okta_account_creation.go
  swagger-def/admin.yaml
  swagger/admin.yaml
Labels: Mountain Movers, MAIN

#12477 update ghc.yaml to reflect changes on main
  pkg/gen/ghcapi/embedded_spec.go
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: G-Unit, INTEGRATION

#12459 INT-B-18667
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240410154749_add_safety_privilege.up.sql
  pkg/models/privileges.go
  src/components/Admin/ImportOfficeUserButton/validation.js
  src/constants/userPrivileges.js
  src/scenes/SystemAdmin/shared/RolesPrivilegesCheckboxes.jsx
Labels: G-Unit, INTEGRATION

#12400 MAIN B-18642 add origin gbloc to move screen front end
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/move.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/services/move/move_fetcher.go
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/testharness/dispatch.go
  pkg/testdatagen/testharness/make_move.go
  playwright/tests/office/servicescounseling/servicesCounselingFlows.spec.js
  playwright/tests/office/txo/tioFlows.spec.js
  playwright/tests/office/txo/tooFlows.spec.js
  playwright/tests/utils/testharness.js
  src/components/CustomerHeader/CustomerHeader.stories.jsx
  src/components/CustomerHeader/CustomerHeader.test.jsx
  src/components/CustomerHeader/index.jsx
  src/hooks/queries.js
  src/hooks/queries.test.jsx
  src/pages/Office/EditShipmentDetails/EditShipmentDetails.jsx
  src/pages/Office/ServicesCounselingMoveInfo/ServicesCounselingMoveInfo.jsx
  src/pages/Office/TXOMoveInfo/TXOMoveInfo.jsx
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: ByteSize M&Ms, MAIN

#12444 B 18800 county with address response int
  .circleci/config.yml
  pkg/gen/adminapi/embedded_spec.go
  pkg/gen/adminmessages/address.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/address.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/address.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/address.go
  pkg/gen/primev2api/embedded_spec.go
  pkg/gen/primev2messages/address.go
  pkg/gen/supportapi/embedded_spec.go
  pkg/gen/supportmessages/address.go
  pkg/handlers/adminapi/addresses.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload_test.go
  pkg/handlers/primeapi/payloads/model_to_payload_test.go
  pkg/handlers/primeapiv2/payloads/model_to_payload.go
  pkg/handlers/primeapiv2/payloads/model_to_payload_test.go
  pkg/handlers/supportapi/internal/payloads/model_to_payload.go
  swagger-def/admin.yaml
  swagger-def/definitions/Address.yaml
  swagger-def/support.yaml
  swagger/admin.yaml
  swagger/ghc.yaml
  swagger/internal.yaml
  swagger/prime.yaml
  swagger/prime_v2.yaml
  swagger/support.yaml
Labels: Mountain Movers, INTEGRATION

#12466 MAIN B-18755 move history update weight pro gear expense
  src/constants/MoveHistory/Database/FieldMappings.js
  src/constants/MoveHistory/EventTemplates/CreateMovingExpense/CreateMovingExpense.test.jsx
  src/constants/MoveHistory/EventTemplates/CreateUpload/CreatePPMUpload.jsx
  src/constants/MoveHistory/EventTemplates/CreateUpload/CreatePPMUpload.test.jsx
  src/constants/MoveHistory/EventTemplates/DeleteMovingExpense/DeleteMovingExpense.test.jsx
  src/constants/MoveHistory/EventTemplates/DeleteMovingExpense/DeleteMovingExpenseUserUploads.test.jsx
  src/constants/MoveHistory/EventTemplates/UpdateMovingExpense/UpdateMovingExpense.test.jsx
  src/constants/MoveHistory/EventTemplates/UpdateReweigh/updateReweighWeight.jsx
  src/constants/MoveHistory/EventTemplates/UpdateWeightTicket/updateWeightTicketProGear.jsx
  src/constants/MoveHistory/EventTemplates/UpdateWeightTicket/updateWeightTicketProGear.test.jsx
  src/pages/Office/MoveHistory/LabeledDetails.jsx
  src/utils/formatMtoShipment.js
Labels: ByteSize M&Ms, MAIN

#12461 kickback B-18648 multiplier was showing up as undefined on non FSC items and mileage didn't show comma
  pkg/payment_request/service_param_value_lookups/weight_billed_lookup.go
  pkg/payment_request/service_param_value_lookups/weight_billed_lookup_test.go
  src/components/Office/ServiceItemCalculations/ServiceItemCalculations.jsx
  src/components/Office/ServiceItemCalculations/helpers.js
  src/utils/formatters.js
Labels: ByteSize M&Ms, INTEGRATION

#12439 B:19465 - Add a public GHCApi endpoint to get the transportation offices(READY)
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/ghcapi/ghcoperations/transportation_office/get_transportation_offices_open.go
  pkg/gen/ghcapi/ghcoperations/transportation_office/get_transportation_offices_open_parameters.go
  pkg/gen/ghcapi/ghcoperations/transportation_office/get_transportation_offices_open_responses.go
  pkg/gen/ghcapi/ghcoperations/transportation_office/get_transportation_offices_open_urlbuilder.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/tranportation_offices.go
  pkg/handlers/routing/routing_init.go
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: Mountain Movers, MAIN

#12456 B:18830 - Add Office Account Request Form
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/office_users/create_requested_office_user.go
  src/components/MilMoveHeader/LoggedOutUserInfo.jsx
  src/components/Office/RequestAccountForm/RequestAccountForm.jsx
  src/components/Office/RequestAccountForm/RequestAccountForm.module.scss
  src/components/Office/RequestAccountForm/RequestAccountForm.test.jsx
  src/components/form/OfficeAccountRequestFields/OfficeAccountRequestFields.jsx
  src/components/form/OfficeAccountRequestFields/OfficeAccountRequestFields.test.jsx
  src/constants/routes.js
  src/constants/signInPageNames.js
  src/containers/Headers/LoggedOutHeader.jsx
  src/containers/Headers/LoggedOutHeader.test.jsx
  src/pages/Office/RequestAccount/RequestAccount.jsx
  src/pages/Office/RequestAccount/RequestAccount.test.jsx
  src/pages/Office/index.jsx
  src/pages/SignIn/SignIn.jsx
  src/pages/SignIn/Signin.test.jsx
  src/scenes/MyMove/index.jsx
  src/services/ghcApi.js
  src/utils/validation.js
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: Mountain Movers, INTEGRATION

#12480 B 19177 int qae/csr
  package.json
  pkg/factory/mto_shipment_factory_test.go
  pkg/handlers/authentication/okta/provider.go
  pkg/handlers/ghcapi/customer_test.go
  src/components/Table/SearchResultsTable.jsx
  yarn.lock
Labels: Scrummy Bears, INTEGRATION

#12386 B 18737 int
  playwright/tests/office/txo/tooFlows.spec.js
  playwright/tests/office/txo/tooFlowsNTS.spec.js
  playwright/tests/office/txo/tooFlowsNTSR.spec.js
  src/components/Office/RequestedServiceItemsTable/RequestedServiceItemsTable.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.test.jsx
  src/pages/Office/MoveTaskOrder/moveTaskOrderUnitTestData.js
  src/pages/Office/index.jsx
  src/scenes/MyMove/index.jsx
  src/scenes/SystemAdmin/index.jsx
Labels: Scrummy Bears, INTEGRATION

#12326 Main b 17960 UI fixes
  src/components/Office/PPM/ReviewDocumentsSidePanel/ReviewDocumentsSidePanel.jsx
  src/components/Office/PPM/ReviewDocumentsSidePanel/ReviewDocumentsSidePanel.module.scss
  src/components/Office/PPM/ReviewDocumentsSidePanel/ReviewDocumentsSidePanel.test.jsx
Labels: ByteSize M&Ms, MAIN

#12467 MAIN B-18756 move history log delete weight pro gear expense
  src/constants/MoveHistory/EventTemplates/CreateUpload/CreatePPMUpload.jsx
  src/constants/MoveHistory/EventTemplates/DeleteMovingExpense/DeleteMovingExpenseUserUploads.jsx
  src/constants/MoveHistory/EventTemplates/DeleteMovingExpense/DeleteMovingExpenseUserUploads.test.jsx
  src/constants/MoveHistory/EventTemplates/DeleteProGearWeightTicket/DeleteProGearWeightTicketUserUploads.jsx
  src/constants/MoveHistory/EventTemplates/DeleteProGearWeightTicket/DeleteProGearWeightTicketUserUploads.test.jsx
  src/constants/MoveHistory/EventTemplates/DeleteWeightTicket/DeleteWeightTicketUserUploads.jsx
  src/constants/MoveHistory/EventTemplates/DeleteWeightTicket/DeleteWeightTicketUserUploads.test.jsx
Labels: ByteSize M&Ms, MAIN

#12471 B-18986 Customer update UI to show the shipment locator
  playwright/tests/utils/my/customerTest.js
  src/components/Customer/Review/ShipmentCard/HHGShipmentCard/HHGShipmentCard.jsx
  src/components/Customer/Review/ShipmentCard/HHGShipmentCard/HHGShipmentCard.test.jsx
  src/components/Customer/Review/ShipmentCard/NTSRShipmentCard/NTSRShipmentCard.jsx
  src/components/Customer/Review/ShipmentCard/NTSRShipmentCard/NTSRShipmentCard.test.jsx
  src/components/Customer/Review/ShipmentCard/NTSShipmentCard/NTSShipmentCard.jsx
  src/components/Customer/Review/ShipmentCard/NTSShipmentCard/NTSShipmentCard.test.jsx
  src/components/Customer/Review/ShipmentCard/PPMShipmentCard/PPMShipmentCard.jsx
  src/components/Customer/Review/ShipmentCard/PPMShipmentCard/PPMShipmentCard.test.jsx
  src/components/Customer/Review/Summary/Summary.jsx
  src/components/ShipmentList/ShipmentList.jsx
  src/components/ShipmentList/ShipmentList.test.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesMoveContainer/MultiMovesMoveContainer.jsx
  src/types/shipment.js
  src/utils/shipmentDisplay.jsx
  src/utils/shipmentDisplay.test.jsx
Labels: ByteSize M&Ms, INTEGRATION

#12401 B 18392 prime counseled ppm aoa link
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/internal_move.go
  pkg/gen/internalmessages/move_payload.go
  pkg/handlers/internalapi/moves.go
  src/pages/MyMove/Home/MoveHome.jsx
  src/pages/MyMove/Home/index.jsx
  swagger-def/internal.yaml
  swagger/internal.yaml
Labels: G-Unit, MAIN

#12464 INT B-19474 approvals requested or approved move status check issue
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/mto_shipment.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/handlers/internalapi/api.go
  pkg/handlers/primeapi/api.go
  pkg/handlers/primeapi/mto_shipment_test.go
  pkg/services/move/move_router.go
  pkg/services/mto_shipment/shipment_deleter.go
  pkg/services/mto_shipment/shipment_deleter_test.go
  pkg/services/mto_shipment/shipment_diversion_approver.go
  pkg/services/mto_shipment/shipment_diversion_approver_test.go
Labels: Mountain Movers, INTEGRATION

#12488 B 19506 validation code feature flag int
  .envrc
  config/env/demo.app-client-tls.env
  config/env/demo.app.env
  config/env/exp.app-client-tls.env
  config/env/exp.app.env
  config/env/loadtest.app-client-tls.env
  config/env/loadtest.app.env
  config/env/prd.app-client-tls.env
  config/env/prd.app.env
  config/env/stg.app-client-tls.env
  config/env/stg.app.env
  config/flipt/storage/development.features.yaml
Labels: Mountain Movers, INTEGRATION

#12490 B-19507 limit customer access via validation code (MERGE AFTER B-19506)
  .circleci/config.yml
  .envrc
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240411201158_add_application_parameter_and_validation_code_table.up.sql
  pkg/gen/internalapi/configure_mymove.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalapi/internaloperations/application_parameters/validate.go
  pkg/gen/internalapi/internaloperations/application_parameters/validate_parameters.go
  pkg/gen/internalapi/internaloperations/application_parameters/validate_responses.go
  pkg/gen/internalapi/internaloperations/application_parameters/validate_urlbuilder.go
  pkg/gen/internalapi/internaloperations/mymove_api.go
  pkg/gen/internalmessages/validation_code.go
  pkg/handlers/internalapi/api.go
  pkg/handlers/internalapi/application_parameters.go
  pkg/handlers/internalapi/application_parameters_test.go
  pkg/models/application_parameters.go
  pkg/models/application_parameters_test.go
  playwright/tests/my/mymove/onboarding.spec.js
  playwright/tests/utils/my/customerTest.js
  src/constants/customerStates.js
  src/constants/routes.js
  src/containers/requireCustomerState/requireCustomerState.jsx
  src/containers/requireCustomerState/requireCustomerState.test.jsx
  src/pages/MyMove/ConusOrNot.jsx
  src/pages/MyMove/ConusOrNot.test.jsx
  src/pages/MyMove/Home/MoveHome.test.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesLandingPage.test.jsx
  src/pages/MyMove/Profile/Name.test.jsx
  src/pages/MyMove/Profile/ValidationCode.jsx
  src/pages/MyMove/Profile/ValidationCode.test.jsx
  src/scenes/MyMove/getWorkflowRoutes.jsx
  src/scenes/MyMove/getWorkflowRoutes.test.js
  src/scenes/MyMove/index.jsx
  src/services/internalApi.js
  src/utils/customer.js
  swagger-def/internal.yaml
  swagger/internal.yaml
Labels: Mountain Movers, INTEGRATION

#12487 B-19176 SC upload orders
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/doc.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/ghcapi/ghcoperations/uploads/create_upload.go
  pkg/gen/ghcapi/ghcoperations/uploads/create_upload_parameters.go
  pkg/gen/ghcapi/ghcoperations/uploads/create_upload_responses.go
  pkg/gen/ghcapi/ghcoperations/uploads/create_upload_urlbuilder.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/uploads.go
  pkg/handlers/ghcapi/uploads_test.go
  src/pages/Office/ServicesCounselingMoveDocumentWrapper/ServicesCounselingMoveDocumentWrapper.jsx
  src/pages/Office/ServicesCounselingOrders/ServicesCounselingOrders.jsx
  src/pages/Office/ServicesCounselingOrders/ServicesCounselingOrders.test.jsx
  src/services/ghcApi.js
  src/styles/documentViewerWithSidebar.module.scss
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: G-Unit, MAIN

#12493 I-12790 initial commit & fix
  src/pages/SignIn/SignIn.jsx
Labels: Mountain Movers, INTEGRATION

#12482 B-18459: Multi-Move Automated Regression Testing
  playwright/tests/my/milmove/ppms/about.spec.js
  playwright/tests/my/milmove/ppms/advances.spec.js
  playwright/tests/my/milmove/ppms/customerPpmTestFixture.js
  playwright/tests/my/milmove/ppms/dateAndLocation.spec.js
  playwright/tests/my/milmove/ppms/estimatedIncentive.spec.js
  playwright/tests/my/milmove/ppms/estimatedWeightsProgear.spec.js
  playwright/tests/my/milmove/ppms/expenses.spec.js
  playwright/tests/my/milmove/ppms/finalCloseout.spec.js
  playwright/tests/my/milmove/ppms/progear.spec.js
  playwright/tests/my/milmove/ppms/review.spec.js
  playwright/tests/my/milmove/ppms/weightTickets.spec.js
  src/components/ShipmentList/ShipmentList.jsx
Labels: Mountain Movers, INTEGRATION

#12495 B-18830-Addition
  src/components/Office/RequestAccountForm/RequestAccountForm.jsx
  src/components/form/OfficeAccountRequestFields/OfficeAccountRequestFields.jsx
  src/pages/SignIn/SignIn.jsx
Labels: Mountain Movers, INTEGRATION

#12494 B 19525 I 12786 show original delivery address INT
  src/components/Office/ServiceItemDetails/ServiceItemDetails.jsx
  src/components/Office/ServiceItemDetails/ServiceItemDetails.test.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
  src/types/serviceItems.js
Labels: Mountain Movers, INTEGRATION

#12497 INT B-18987 update diversion msg shipment locator
  playwright/tests/office/txo/tooFlows.spec.js
  src/components/Office/ShipmentAddresses/ShipmentAddresses.jsx
  src/components/Office/ShipmentAddresses/ShipmentAddresses.test.jsx
  src/components/Office/ShipmentDetails/ShipmentDetailsMain.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
Labels: ByteSize M&Ms, INTEGRATION

#12486 INT- B -18876- Prime ListMove amendment count
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/amendments.go
  pkg/gen/primemessages/list_move.go
  pkg/handlers/primeapi/move_task_order.go
  pkg/handlers/primeapi/move_task_order_test.go
  pkg/handlers/primeapi/payloads/model_to_payload.go
  pkg/models/order.go
  pkg/services/mocks/MoveTaskOrderFetcher.go
  pkg/services/move_task_order.go
  pkg/services/move_task_order/move_task_order_fetcher.go
  pkg/services/move_task_order/move_task_order_fetcher_test.go
  swagger-def/prime.yaml
  swagger/prime.yaml
Labels: Scrummy Bears, INTEGRATION

#12498 MAIN B-18978 add shipment locator be
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240402192009_add_shipment_locator_and_shipment_seq_num.up.sql
  pkg/assets/sql_scripts/move_history_fetcher.sql
  pkg/factory/mto_shipment_factory.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/m_t_o_shipment.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/m_t_o_shipment.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/internalapi/internal/payloads/model_to_payload.go
  pkg/models/move.go
  pkg/models/mto_shipments.go
  pkg/services/mto_shipment/mto_shipment_creator.go
  pkg/services/mto_shipment/mto_shipment_creator_test.go
  pkg/services/mto_shipment/mto_shipment_updater.go
  pkg/services/mto_shipment/shipment_deleter_test.go
  swagger-def/definitions/MTOShipment.yaml
  swagger-def/internal.yaml
  swagger/admin.yaml
  swagger/ghc.yaml
  swagger/internal.yaml
Labels: ByteSize M&Ms, MAIN

#12496 B 18990 mto shipment locator integration
  src/components/Office/ShipmentHeading/ShipmentHeading.jsx
  src/components/Office/ShipmentHeading/ShipmentHeading.test.jsx
  src/components/Office/ShipmentHeading/shipmentHeading.module.scss
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.test.jsx
Labels: ByteSize M&Ms, INTEGRATION

#12509 MAIN B-18978 sql timeout fix
  migrations/app/schema/20240402192009_add_shipment_locator_and_shipment_seq_num.up.sql
Labels: ByteSize M&Ms, MAIN

#12502 B-19124-INT weights workflows kickback
  src/components/Office/BillableWeight/EditBillableWeight/EditBillableWeight.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.test.jsx
Labels: G-Unit, INTEGRATION

#12510 B 18737 int revised
  src/components/Office/RequestedServiceItemsTable/RequestedServiceItemsTable.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
  src/shared/constants.js
  src/utils/dates.js
  src/utils/dates.test.js
Labels: Scrummy Bears, INTEGRATION

#12491 B 18882 int add search capability for too tio
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/move/search_moves.go
  pkg/gen/ghcmessages/move_status.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/internal/payloads/payload_to_model.go
  pkg/handlers/ghcapi/move.go
  pkg/services/move/move_searcher.go
  pkg/services/move/move_searcher_test.go
  playwright/tests/office/homepage.spec.js
  playwright/tests/office/txo/tioFlows.spec.js
  playwright/tests/office/txo/tooFlows.spec.js
  src/components/MoveSearchForm/MoveSearchForm.jsx
  src/components/Table/SearchResultsTable.jsx
  src/constants/queues.js
  src/constants/routes.js
  src/pages/Office/CustomerOnboarding/CreateCustomerForm.jsx
  src/pages/Office/CustomerOnboarding/CustomerName.jsx
  src/pages/Office/MoveQueue/MoveQueue.jsx
  src/pages/Office/MoveQueue/MoveQueue.test.jsx
  src/pages/Office/PaymentRequestQueue/PaymentRequestQueue.test.jsx
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: G-Unit, INTEGRATION

#12503 MAIN- B-18891 Office users can update customer contact info
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/customer.go
  pkg/gen/ghcmessages/update_customer_payload.go
  pkg/handlers/authentication/permissions.go
  src/components/Office/CustomerContactInfoForm/CustomerContactInfoForm.jsx
  src/components/Office/CustomerContactInfoForm/CustomerContactInfoForm.test.jsx
  src/components/Office/DefinitionLists/CustomerInfoList.jsx
  src/components/Office/DefinitionLists/CustomerInfoList.test.jsx
  src/components/form/CustomerAltContactInfoFields/CustomerAltContactInfoFields.test.jsx
  src/components/form/CustomerAltContactInfoFields/index.jsx
  src/constants/permissions.js
  src/constants/routes.js
  src/pages/Office/CustomerInfo/CustomerInfo.jsx
  src/pages/Office/CustomerInfo/CustomerInfo.test.jsx
  src/pages/Office/MoveDetails/MoveDetails.jsx
  src/pages/Office/MoveDetails/MoveDetails.test.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.test.jsx
  src/pages/Office/TXOMoveInfo/TXOMoveInfo.jsx
  src/pages/Office/TXOMoveInfo/TXOMoveInfo.test.jsx
  src/utils/formatters.js
  src/utils/formatters.test.js
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: Scrummy Bears, MAIN

#12504 MAIN B-18739 and b 18740 ppm aoa and packet download from multi move dashboard
  src/components/ButtonDropdownMenu/ButtonDropdownMenu.jsx
  src/components/ButtonDropdownMenu/ButtonDropdownMenu.module.scss
  src/components/ButtonDropdownMenu/ButtonDropdownMenu.test.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesLandingPage.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesLandingPage.module.scss
  src/pages/MyMove/Multi-Moves/MultiMovesMoveContainer/MultiMovesMoveContainer.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesMoveContainer/MultiMovesMoveContainer.module.scss
  src/pages/MyMove/Multi-Moves/MultiMovesMoveContainer/MultiMovesMoveContainer.test.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesTestData.js
Labels: Mountain Movers, MAIN

#12479 Main b 18757 begin ppm upload
  src/constants/MoveHistory/EventTemplates/UpdateMTOShipment/UpdateMTOShipmentPPMDetails.jsx
  src/constants/MoveHistory/EventTemplates/UpdateMTOShipment/UpdateMTOShipmentPPMDetails.test.jsx
  src/pages/Office/MoveHistory/LabeledDetails.jsx
Labels: ByteSize M&Ms, MAIN

#12506 INT-B-19557 Fix WW Label
  src/components/Table/SearchResultsTable.jsx
Labels: G-Unit, INTEGRATION

#12521 B 19177 qae/csr search table column headers
  pkg/factory/mto_shipment_factory_test.go
  src/components/Table/SearchResultsTable.jsx
Labels: Scrummy Bears, MAIN

#12511 INT B-18911 gun safe backend - Prime info addition
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240412201837_edit_gun_safe_entitlement_not_null.up.sql
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/entitlements.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/entitlements.go
  pkg/gen/primev2api/embedded_spec.go
  pkg/gen/primev2messages/entitlements.go
  pkg/gen/primev3api/embedded_spec.go
  pkg/gen/primev3messages/entitlements.go
  pkg/gen/supportapi/embedded_spec.go
  pkg/gen/supportmessages/entitlement.go
  pkg/handlers/primeapi/payloads/model_to_payload.go
  pkg/handlers/primeapiv2/payloads/model_to_payload.go
  pkg/handlers/primeapiv3/payloads/model_to_payload.go
  swagger-def/definitions/prime/Entitlements.yaml
  swagger-def/ghc.yaml
  swagger-def/support.yaml
  swagger/ghc.yaml
  swagger/prime.yaml
  swagger/prime_v2.yaml
  swagger/prime_v3.yaml
  swagger/support.yaml
Labels: ByteSize M&Ms, INTEGRATION

#12523 MAIN B-19458 add linehaul service item order to service item list
  src/components/Office/ServiceItemsTable/ServiceItemsTable.jsx
Labels: Mountain Movers, MAIN

#12528 B 19137 payment requests billable weight param changes main
  pkg/payment_request/service_param_value_lookups/weight_billed_lookup.go
  pkg/payment_request/service_param_value_lookups/weight_billed_lookup_test.go
  pkg/payment_request/service_param_value_lookups/weight_original_lookup.go
  pkg/payment_request/service_param_value_lookups/weight_original_lookup_test.go
  src/components/Office/ServiceItemCalculations/helpers.js
Labels: Mountain Movers, MAIN

#12484 INT B-18992 reweigh email shipment id
  pkg/notifications/reweigh_requested.go
  pkg/notifications/reweigh_requested_test.go
Labels: ByteSize M&Ms, INTEGRATION

#12524 B-18990 Add shipment locator officer pages KICKBACK
  playwright/tests/office/servicescounseling/servicesCounselingTestFixture.js
  src/components/Office/ShipmentDisplay/ShipmentDisplay.jsx
  src/components/Office/ShipmentDisplay/ShipmentDisplay.module.scss
  src/components/Office/ShipmentDisplay/ShipmentDisplay.test.jsx
  src/components/Office/ShipmentDisplay/ShipmentDisplayTestData.js
  src/components/Office/ShipmentHeading/shipmentHeading.module.scss
Labels: ByteSize M&Ms, INTEGRATION

#12508 B-19143
  pkg/services/mto_shipment/mto_shipment_updater.go
Labels: G-Unit, MAIN

#12512 Int b 18910 gun safe frontend
  migrations/app/schema/20240402192009_add_shipment_locator_and_shipment_seq_num.up.sql
  package.json
  src/pages/Office/MoveAllowances/MoveAllowances.jsx
  src/pages/Office/ServicesCounselingMoveAllowances/ServicesCounselingMoveAllowances.jsx
  src/pages/PrimeUI/MoveTaskOrder/MoveDetails.jsx
  src/pages/PrimeUI/MoveTaskOrder/MoveDetails.test.jsx
  yarn.lock
Labels: ByteSize M&Ms, INTEGRATION

#12532 B 19506 validation code feature flag main
  .envrc
  config/env/demo.app-client-tls.env
  config/env/demo.app.env
  config/env/exp.app-client-tls.env
  config/env/exp.app.env
  config/env/loadtest.app-client-tls.env
  config/env/loadtest.app.env
  config/env/prd.app-client-tls.env
  config/env/prd.app.env
  config/env/stg.app-client-tls.env
  config/env/stg.app.env
  config/flipt/storage/development.features.yaml
Labels: Mountain Movers, MAIN

#12530 MAIN B-19507 limit customer access via validation code (MERGE AFTER MAIN B-19506)
  .circleci/config.yml
  .envrc
  config/env/demo.app-client-tls.env
  config/env/demo.app.env
  config/env/exp.app-client-tls.env
  config/env/exp.app.env
  config/env/loadtest.app-client-tls.env
  config/env/loadtest.app.env
  config/env/prd.app-client-tls.env
  config/env/prd.app.env
  config/env/stg.app-client-tls.env
  config/env/stg.app.env
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240411201158_add_application_parameter_and_validation_code_table.up.sql
  pkg/gen/internalapi/configure_mymove.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalapi/internaloperations/application_parameters/validate.go
  pkg/gen/internalapi/internaloperations/application_parameters/validate_parameters.go
  pkg/gen/internalapi/internaloperations/application_parameters/validate_responses.go
  pkg/gen/internalapi/internaloperations/application_parameters/validate_urlbuilder.go
  pkg/gen/internalapi/internaloperations/mymove_api.go
  pkg/gen/internalmessages/validation_code.go
  pkg/handlers/internalapi/api.go
  pkg/handlers/internalapi/application_parameters.go
  pkg/handlers/internalapi/application_parameters_test.go
  pkg/models/application_parameters.go
  pkg/models/application_parameters_test.go
  playwright/tests/my/mymove/onboarding.spec.js
  playwright/tests/utils/my/customerTest.js
  src/constants/customerStates.js
  src/constants/routes.js
  src/containers/requireCustomerState/requireCustomerState.jsx
  src/containers/requireCustomerState/requireCustomerState.test.jsx
  src/pages/MyMove/ConusOrNot.jsx
  src/pages/MyMove/ConusOrNot.test.jsx
  src/pages/MyMove/Home/MoveHome.test.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesLandingPage.test.jsx
  src/pages/MyMove/Profile/Name.test.jsx
  src/pages/MyMove/Profile/ValidationCode.jsx
  src/pages/MyMove/Profile/ValidationCode.test.jsx
  src/scenes/MyMove/getWorkflowRoutes.jsx
  src/scenes/MyMove/getWorkflowRoutes.test.js
  src/scenes/MyMove/index.jsx
  src/services/internalApi.js
  src/utils/customer.js
  swagger-def/internal.yaml
  swagger/internal.yaml
Labels: Mountain Movers, MAIN

#12533 B-18667
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240405190435_add_safety_privilege.up.sql
  migrations/app/schema/20240416145256_update_safety_privilege_label.up.sql
  pkg/models/privileges.go
  src/components/Admin/ImportOfficeUserButton/validation.js
  src/constants/userPrivileges.js
  src/scenes/SystemAdmin/shared/RolesPrivilegesCheckboxes.jsx
Labels: G-Unit, MAIN

#12534 B 18823 ghc create requested office user int
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/office_users/create_requested_office_user.go
  pkg/handlers/ghcapi/office_users.go
  pkg/handlers/routing/routing_init.go
  pkg/models/errors.go
  pkg/services/office_user/office_user_creator.go
  pkg/services/office_user/office_user_creator_test.go
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: Mountain Movers, INTEGRATION

#12529 MAIN B-18987 update diversion msg shipment locator
  playwright/tests/office/txo/tooFlows.spec.js
  src/components/Office/ShipmentAddresses/ShipmentAddresses.jsx
  src/components/Office/ShipmentAddresses/ShipmentAddresses.test.jsx
  src/components/Office/ShipmentDetails/ShipmentDetailsMain.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
Labels: ByteSize M&Ms, MAIN

#12472 B-18459: Multi-Move Automated Regression Testing(Not Ready Just Testing)
  playwright/tests/my/milmove/ppms/about.spec.js
  playwright/tests/my/milmove/ppms/advances.spec.js
  playwright/tests/my/milmove/ppms/customerPpmTestFixture.js
  playwright/tests/my/milmove/ppms/dateAndLocation.spec.js
  playwright/tests/my/milmove/ppms/estimatedIncentive.spec.js
  playwright/tests/my/milmove/ppms/estimatedWeightsProgear.spec.js
  playwright/tests/my/milmove/ppms/expenses.spec.js
  playwright/tests/my/milmove/ppms/finalCloseout.spec.js
  playwright/tests/my/milmove/ppms/progear.spec.js
  playwright/tests/my/milmove/ppms/review.spec.js
  playwright/tests/my/milmove/ppms/weightTickets.spec.js
  src/components/ShipmentList/ShipmentList.jsx
Labels: Mountain Movers, MAIN

#12536 B 19500 update 858 generator
  cmd/generate-payment-request-edi/main.go
  pkg/handlers/supportapi/payment_request.go
  pkg/handlers/supportapi/payment_request_test.go
  pkg/services/payment_request/payment_request_reviewed_processor.go
Labels: G-Unit, INTEGRATION

#12518 B-18989 Show Shipment Locator for QAE tab MAIN
  src/components/Office/EvaluationReportShipmentDisplay/EvaluationReportShipmentDisplay.jsx
  src/components/Office/EvaluationReportShipmentDisplay/EvaluationReportShipmentDisplay.test.jsx
  src/components/Office/QAEReportTable/ShipmentQAEReportHeader.jsx
  src/components/Office/QAEReportTable/ShipmentQAEReportHeader.test.jsx
  src/components/Office/ShipmentDisplay/ShipmentDisplayTestData.js
Labels: ByteSize M&Ms, MAIN

#12519 B-18986 Customer: update UI to show the shipment locator
  playwright/tests/utils/my/customerTest.js
  src/components/Customer/Review/ShipmentCard/HHGShipmentCard/HHGShipmentCard.jsx
  src/components/Customer/Review/ShipmentCard/HHGShipmentCard/HHGShipmentCard.test.jsx
  src/components/Customer/Review/ShipmentCard/NTSRShipmentCard/NTSRShipmentCard.jsx
  src/components/Customer/Review/ShipmentCard/NTSRShipmentCard/NTSRShipmentCard.test.jsx
  src/components/Customer/Review/ShipmentCard/NTSShipmentCard/NTSShipmentCard.jsx
  src/components/Customer/Review/ShipmentCard/NTSShipmentCard/NTSShipmentCard.test.jsx
  src/components/Customer/Review/ShipmentCard/PPMShipmentCard/PPMShipmentCard.jsx
  src/components/Customer/Review/ShipmentCard/PPMShipmentCard/PPMShipmentCard.test.jsx
  src/components/Customer/Review/Summary/Summary.jsx
  src/components/ShipmentList/ShipmentList.jsx
  src/components/ShipmentList/ShipmentList.test.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesMoveContainer/MultiMovesMoveContainer.jsx
  src/types/shipment.js
  src/utils/shipmentDisplay.jsx
  src/utils/shipmentDisplay.test.jsx
Labels: ByteSize M&Ms, MAIN

#12546 B 19500 int update linter
  .circleci/config.yml
  go.mod
  go.sum
Labels: G-Unit, INTEGRATION

#12543 B 18737 int
  src/components/Office/ServiceItemContainer/ServiceItemContainer.jsx
  src/components/Office/ServiceItemContainer/ServiceItemContainer.module.scss
  src/components/Office/ServiceItemContainer/ServiceItemContainer.stories.jsx
  src/components/Office/ServiceItemContainer/ServiceItemContainer.test.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
Labels: Scrummy Bears, INTEGRATION

#12545 B 18863 int
  src/components/Office/ShipmentForm/ShipmentForm.jsx
  src/components/PrimeUI/Shipment/Shipment.jsx
Labels: Scrummy Bears, INTEGRATION

#12552 B:19591 - Address State Validation For Unsupported States change for CreateCustomerForm.jsx
  src/pages/Office/CustomerOnboarding/CreateCustomerForm.jsx
  src/pages/Office/CustomerOnboarding/CreateCustomerForm.test.jsx
Labels: Mountain Movers, INTEGRATION

#12537 fB-18990 Add shipment locator officer pages KICKBACK 2
  playwright/tests/office/servicescounseling/servicesCounselingNTSR.spec.js
  playwright/tests/office/servicescounseling/servicesCounselingTestFixture.js
  src/components/Office/ShipmentApprovalPreview/ShipmentApprovalPreview.jsx
  src/components/Office/ShipmentApprovalPreview/ShipmentApprovalPreview.test.jsx
  src/components/Office/ShipmentApprovalPreview/shipmentApprovalPreview.module.scss
  src/components/Office/ShipmentDisplay/ShipmentDisplay.jsx
  src/components/Office/ShipmentDisplay/ShipmentDisplay.module.scss
  src/utils/formatters.js
Labels: ByteSize M&Ms, INTEGRATION

#12550 B-18648, B-18855, and B-18851
  pkg/payment_request/service_param_value_lookups/weight_billed_lookup.go
  pkg/payment_request/service_param_value_lookups/weight_billed_lookup_test.go
  playwright/tests/office/txo/tioFlows.spec.js
  playwright/tests/office/txo/tooFlows.spec.js
  src/components/Office/ServiceItemCalculations/ServiceItemCalculations.jsx
  src/components/Office/ServiceItemCalculations/ServiceItemCalculations.module.scss
  src/components/Office/ServiceItemCalculations/ServiceItemCalculations.test.jsx
  src/components/Office/ServiceItemCalculations/helpers.js
  src/components/Office/ServiceItemCalculations/helpers.test.js
  src/constants/serviceItems.js
  src/utils/formatters.js
Labels: ByteSize M&Ms, MAIN

#12544 B 19586 int
  src/components/Office/RequestedShipments/SubmittedRequestedShipments.jsx
Labels: Scrummy Bears, INTEGRATION

#12526 B-19175-INT SC Customer Search
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/customer/search_customers.go
  pkg/gen/ghcapi/ghcoperations/customer/search_customers_parameters.go
  pkg/gen/ghcapi/ghcoperations/customer/search_customers_responses.go
  pkg/gen/ghcapi/ghcoperations/customer/search_customers_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/ghcmessages/search_customer.go
  pkg/gen/ghcmessages/search_customers.go
  pkg/gen/ghcmessages/search_customers_result.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/customer.go
  pkg/handlers/ghcapi/customer_test.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/services/customer.go
  pkg/services/mocks/CustomerSearcher.go
  pkg/services/office_user/customer/customer_searcher.go
  pkg/services/office_user/customer/customer_searcher_test.go
  src/components/CustomerSearchForm/CustomerSearchForm.jsx
  src/components/CustomerSearchForm/CustomerSearchForm.module.scss
  src/components/CustomerSearchForm/CustomerSearchForm.test.jsx
  src/components/Table/SearchResultsTable.jsx
  src/components/Table/SearchResultsTable.test.jsx
  src/constants/queryKeys.js
  src/constants/routes.js
  src/hooks/queries.js
  src/pages/Office/CreateMoveCustomerInfo/CreateMoveCustomerInfo.jsx
  src/pages/Office/CreateMoveCustomerInfo/CreateMoveCustomerInfo.test.jsx
  src/pages/Office/CustomerOnboarding/CreateCustomerForm.jsx
  src/pages/Office/ServicesCounselingAddOrders/ServicesCounselingAddOrders.jsx
  src/pages/Office/ServicesCounselingMoveInfo/ServicesCounselingMoveInfo.jsx
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.jsx
  src/pages/Office/index.jsx
  src/services/ghcApi.js
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: G-Unit, INTEGRATION

#12561 B 18882 c int add search capability for too and tio
  pkg/handlers/ghcapi/internal/payloads/model_to_payload_test.go
  pkg/handlers/ghcapi/move_test.go
  src/constants/queues.js
Labels: G-Unit, INTEGRATION

#12564 I-12839: Error or Warning needed when using Current Address box with AK or HI State for Pickup Location
  src/components/Customer/MtoShipmentForm/MtoShipmentForm.jsx
  src/components/Customer/MtoShipmentForm/MtoShipmentForm.test.jsx
  src/components/Office/ShipmentForm/ShipmentForm.jsx
  src/components/Office/ShipmentForm/ShipmentForm.test.jsx
  src/pages/Office/CustomerInfo/CustomerInfo.jsx
  src/pages/Office/CustomerInfo/CustomerInfo.test.jsx
Labels: Mountain Movers, INTEGRATION

#12567 I-12839: Error or Warning NOT needed when using Current Address box with AK or HI State for Pickup Location
  src/components/Customer/MtoShipmentForm/MtoShipmentForm.jsx
  src/components/Customer/MtoShipmentForm/MtoShipmentForm.test.jsx
  src/components/Office/ShipmentForm/ShipmentForm.jsx
  src/components/Office/ShipmentForm/ShipmentForm.test.jsx
  src/pages/Office/CustomerInfo/CustomerInfo.jsx
  src/pages/Office/CustomerInfo/CustomerInfo.test.jsx
Labels: Mountain Movers, INTEGRATION

#12483 B 18270 int
  .gitignore
  go.mod
  go.sum
  pkg/assets/paperwork/formtemplates/WeightEstimateTemplate.pdf
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalapi/internaloperations/ppm/create_p_p_m_upload_parameters.go
  pkg/gen/internalapi/internaloperations/ppm/create_p_p_m_upload_urlbuilder.go
  pkg/handlers/internalapi/api.go
  pkg/handlers/internalapi/uploads.go
  pkg/handlers/internalapi/uploads_test.go
  pkg/paperwork/generator.go
  pkg/services/mocks/WeightTicketComputer.go
  pkg/services/mocks/WeightTicketGenerator.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet.go
  pkg/services/weight_ticket_parser.go
  pkg/services/weight_ticket_parser/weight_ticket_parser.go
  pkg/services/weight_ticket_parser/weight_ticket_parser_service_test.go
  pkg/services/weight_ticket_parser/weight_ticket_parser_test.go
  pkg/testdatagen/testdata/Weight Estimator Full.xlsx
  playwright/tests/my/milmove/ppms/customerPpmTestFixture.js
  playwright/tests/my/milmove/ppms/entireShipmentCloseout.spec.js
  src/components/Customer/PPM/Closeout/WeightTicketForm/WeightTicketForm.test.jsx
  src/components/Customer/PPM/Closeout/WeightTicketUpload/WeightTicketUpload.jsx
  src/components/Office/ShipmentDisplay/ShipmentDisplay.jsx
  src/content/uploads.js
  src/pages/MyMove/Home/MoveHome.jsx
  src/pages/MyMove/Home/MoveHome.test.jsx
  src/pages/MyMove/Home/index.jsx
  src/pages/MyMove/Home/index.test.jsx
  src/pages/MyMove/PPM/Closeout/Expenses/Expenses.jsx
  src/pages/MyMove/PPM/Closeout/ProGear/ProGear.jsx
  src/pages/MyMove/PPM/Closeout/ProGear/ProGear.test.jsx
  src/pages/MyMove/PPM/Closeout/WeightTickets/WeightTickets.jsx
  src/services/internalApi.js
  src/shared/ErrorModal/ErrorModal.jsx
  src/shared/ErrorModal/ErrorModal.module.scss
  swagger-def/internal.yaml
  swagger/internal.yaml
Labels: Scrummy Bears, INTEGRATION

#12568 INT I-12832 and B-19474 fix and enhancements
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/services/mto_shipment/mto_shipment_updater.go
  pkg/services/mto_shipment/shipment_cancellation_requester.go
  pkg/services/mto_shipment/shipment_cancellation_requester_test.go
Labels: Mountain Movers, INTEGRATION

#12572 Update package json int
  package.json
  src/components/DocumentViewer/Content/Content.jsx
  yarn.lock
Labels: infra
