Repository transcom/mymove, pull requests merged in 2024-09, with the labels that each got.

#13576 INT-B-20522 SIT Validation
  pkg/services/payment_request/payment_request_creator.go
Labels: G-Unit, INTEGRATION

#13613 Nts loa and SIT flaky fix int
  playwright/tests/office/servicescounseling/servicesCounselingNTS.spec.js
  playwright/tests/office/txo/sitUpdates.spec.js
  playwright/tests/office/txo/tooFlowsNTS.spec.js
Labels: Mountain Movers, INTEGRATION

#13574 B 20940 int
  pkg/models/worksheet_shipment.go
  pkg/services/shipment_summary_worksheet.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet_test.go
Labels: Scrummy Bears, INTEGRATION

#13603 B-20671 B-20674 B-20758 simulate process TPPS cmd INT
  Makefile
  cmd/milmove-tasks/process_edis.go
  cmd/simulate-process-tpps/main.go
  pkg/cli/gex_sftp.go
  pkg/services/mto_service_item/mto_service_item_updater.go
  pkg/services/mto_service_item/mto_service_item_updater_test.go
  pkg/services/mto_service_item/mto_service_item_validators.go
Labels: Mountain Movers, INTEGRATION

#13616 B-20292 (I-13262): Kick back due to the alt telephone number reverting to original number after getting 2 forms away
  pkg/handlers/internalapi/service_members.go
  src/pages/MyMove/Profile/ContactInfo.jsx
  src/pages/Office/CustomerOnboarding/CreateCustomerForm.jsx
Labels: ByteSize M&Ms, INTEGRATION

#13612 fix flaky formatting
  playwright/tests/office/servicescounseling/servicesCounselingNTS.spec.js
  playwright/tests/office/txo/tooFlowsNTS.spec.js
Labels: Mountain Movers, MAIN

#13581 B 19463 int
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/services/order/order_fetcher.go
  src/components/Table/TableQueue.jsx
  src/hooks/queries.js
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.jsx
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.module.scss
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.test.jsx
  src/pages/Office/index.jsx
  src/utils/queues.jsx
Labels: G-Unit, INTEGRATION

#13596 B 20654 int
  go.mod
  go.sum
  pkg/services/payment_request/payment_request_reviewed_processor.go
  pkg/services/payment_request/payment_request_reviewed_processor_test.go
Labels: Mountain Movers, INTEGRATION

#13627 B 20943 INT - V2
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet.go
Labels: Scrummy Bears, INTEGRATION

#13624 B-20671 B-20674 B-20758 simulate process TPPS cmd MAIN
  .pre-commit-config.yaml
  Makefile
  cmd/milmove-tasks/process_edis.go
  cmd/simulate-process-tpps/main.go
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240802161708_tpps_paid_invoice_table.up.sql
  migrations/app/schema/20240815195730_add_fk_to_tpps_paid_invoice_reports.up.sql
  pkg/cli/gex_sftp.go
  pkg/edi/tpps_paid_invoice_report/parser.go
  pkg/edi/tpps_paid_invoice_report/parser_test.go
  pkg/edi/tpps_paid_invoice_report/tpps_data.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/payment_request.go
  pkg/gen/ghcmessages/payment_service_item.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/models/edi_errors_test.go
  pkg/models/edi_processing_test.go
  pkg/models/edi_type.go
  pkg/models/payment_request.go
  pkg/models/payment_request_to_interchange_control_number_test.go
  pkg/models/tpps_paid_invoice_report.go
  pkg/models/tpps_paid_invoice_report_test.go
  pkg/services/invoice/fixtures/tpps_paid_invoice_report_testfile.csv
  pkg/services/invoice/fixtures/tpps_paid_invoice_report_testfile_tpps_pickup_dir.csv
  pkg/services/invoice/process_edi824.go
  pkg/services/invoice/process_edi824_test.go
  pkg/services/invoice/process_tpps_paid_invoice_report.go
  pkg/services/invoice/process_tpps_paid_invoice_report_test.go
  pkg/services/payment_request/payment_request_list_fetcher.go
  src/components/Office/ExpandableServiceItemRow/ExpandableServiceItemRow.jsx
  src/components/Office/PaymentRequestCard/PaymentRequestCard.jsx
  src/components/Office/PaymentRequestCard/PaymentRequestCard.test.jsx
  src/components/Office/PaymentRequestDetails/PaymentRequestDetails.jsx
  src/components/Office/PaymentRequestDetails/PaymentRequestDetails.test.jsx
  src/types/order.js
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: Mountain Movers, MAIN

#13165 B-19935
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240628181051_drop_ppm_postal_code_fields.up.sql
  migrations/app/schema/20240628185537_update_move_to_gbloc_to_use_ppm_address.up.sql
Labels: Scrummy Bears, MAIN

#13597 B-20293: MTO Page Shipment Header Missing Values
  src/components/Office/ShipmentHeading/ShipmentHeading.jsx
  src/components/Office/ShipmentHeading/ShipmentHeading.test.jsx
Labels: Mountain Movers, MAIN

#13629 B 20654 m
  go.mod
  go.sum
  pkg/services/payment_request/payment_request_reviewed_processor.go
  pkg/services/payment_request/payment_request_reviewed_processor_test.go
Labels: Mountain Movers, MAIN

#13572 B-20438 and B-20440
  config-overrides.js
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240806230447_add_rotation_to_uploads.up.sql
  package.json
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/ghcapi/ghcoperations/uploads/get_upload.go
  pkg/gen/ghcapi/ghcoperations/uploads/get_upload_parameters.go
  pkg/gen/ghcapi/ghcoperations/uploads/get_upload_responses.go
  pkg/gen/ghcapi/ghcoperations/uploads/get_upload_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/uploads/update_upload.go
  pkg/gen/ghcapi/ghcoperations/uploads/update_upload_parameters.go
  pkg/gen/ghcapi/ghcoperations/uploads/update_upload_responses.go
  pkg/gen/ghcapi/ghcoperations/uploads/update_upload_urlbuilder.go
  pkg/gen/ghcmessages/upload.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/upload.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/upload_with_omissions.go
  pkg/gen/primev2api/embedded_spec.go
  pkg/gen/primev2messages/upload_with_omissions.go
  pkg/gen/primev3api/embedded_spec.go
  pkg/gen/primev3messages/upload_with_omissions.go
  pkg/gen/supportapi/embedded_spec.go
  pkg/gen/supportmessages/upload_with_omissions.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/uploads.go
  pkg/models/upload.go
  pkg/services/mocks/UploadUpdater.go
  pkg/services/upload.go
  pkg/services/upload/upload_updater.go
  src/components/DocumentViewer/Content/Content.jsx
  src/components/DocumentViewer/Content/Content.module.scss
  src/components/DocumentViewer/Content/Content.test.jsx
  src/components/DocumentViewer/DocumentViewer.jsx
  src/components/DocumentViewer/DocumentViewer.test.jsx
  src/constants/queryKeys.js
  src/pages/Office/MoveDocumentWrapper/MoveDocumentWrapper.jsx
  src/pages/Office/MoveDocumentWrapper/MoveDocumentWrapper.test.jsx
  src/pages/Office/ServicesCounselingMoveDocumentWrapper/ServicesCounselingMoveDocumentWrapper.jsx
  src/pages/Office/ServicesCounselingMoveDocumentWrapper/ServicesCounselingMoveDocumentWrapper.test.jsx
  src/pages/Office/ServicesCounselingOrders/ServicesCounselingOrders.jsx
  src/pages/Office/SupportingDocuments/SupportingDocuments.test.jsx
  src/services/ghcApi.js
  swagger-def/definitions/Upload.yaml
  swagger-def/definitions/UploadWithOmissions.yaml
  swagger-def/ghc.yaml
  swagger/ghc.yaml
  swagger/internal.yaml
  swagger/prime.yaml
  swagger/prime_v2.yaml
  swagger/prime_v3.yaml
  swagger/support.yaml
  yarn.lock
Labels: ByteSize M&Ms, MAIN

#13615 B 21015 int
  go.mod
  go.sum
  pkg/handlers/primeapiv3/payloads/model_to_payload.go
  pkg/handlers/primeapiv3/payloads/model_to_payload_test.go
  pkg/services/mto_service_item/mto_service_item_validators.go
  yarn.lock
Labels: Mountain Movers, INTEGRATION

#13621 B 20724
  pkg/services/mto_shipment/rules.go
Labels: Scrummy Bears, MAIN

#13602 MAIN-B-20941-ssw-duplicate-state-zip
  pkg/factory/duty_location_factory.go
  pkg/factory/duty_location_factory_test.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet_test.go
Labels: Scrummy Bears, MAIN

#13608 B 20752 move info
  src/components/Office/DefinitionLists/NTSRShipmentInfoList.jsx
  src/components/Office/DefinitionLists/NTSRShipmentInfoList.stories.jsx
  src/components/Office/DefinitionLists/NTSRShipmentInfoList.test.jsx
  src/components/Office/DefinitionLists/NTSShipmentInfoList.jsx
  src/components/Office/DefinitionLists/NTSShipmentInfoList.stories.jsx
  src/components/Office/DefinitionLists/NTSShipmentInfoList.test.jsx
  src/components/Office/DefinitionLists/ShipmentInfoListSelector.jsx
  src/components/Office/RequestedShipments/ApprovedRequestedShipments.jsx
  src/components/Office/RequestedShipments/SubmittedRequestedShipments.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
Labels: Scrummy Bears, MAIN

#13588 INT B-20949 SSW remaining ppm incentive calculation
  pkg/services/shipment_summary_worksheet.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet_test.go
Labels: Scrummy Bears, INTEGRATION

#13617 B 20942 ssw label
  pkg/assets/paperwork/formtemplates/SSWPDFTemplate.pdf
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet_test.go
Labels: Scrummy Bears, MAIN

#13558 INT-B-20466 add a frontend (filterable) column to the SC's queue
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/queues/get_services_counseling_queue_parameters.go
  pkg/gen/ghcapi/ghcoperations/queues/get_services_counseling_queue_urlbuilder.go
  pkg/gen/ghcmessages/queue_move.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/orders.go
  pkg/handlers/ghcapi/queues.go
  pkg/services/order.go
  pkg/services/order/order_fetcher.go
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.jsx
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.test.jsx
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: G-Unit, INTEGRATION

#13643 B 20441 int
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240905192913_adding_prices_to_unpriced_cs_ms_service_items.up.sql
  pkg/handlers/ghcapi/mto_service_items.go
  pkg/services/ghc_rate_engine.go
  pkg/services/ghcrateengine/counseling_services_pricer.go
  pkg/services/ghcrateengine/counseling_services_pricer_test.go
  pkg/services/ghcrateengine/management_services_pricer.go
  pkg/services/ghcrateengine/management_services_pricer_test.go
  pkg/services/mocks/CounselingServicesPricer.go
  pkg/services/mocks/ManagementServicesPricer.go
Labels: Scrummy Bears, INTEGRATION

#13445 B 20464 counseling office customer
  pkg/gen/internalapi/configure_mymove.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalapi/internaloperations/mymove_api.go
  pkg/gen/internalapi/internaloperations/transportation_offices/show_counseling_offices.go
  pkg/gen/internalapi/internaloperations/transportation_offices/show_counseling_offices_parameters.go
  pkg/gen/internalapi/internaloperations/transportation_offices/show_counseling_offices_responses.go
  pkg/gen/internalapi/internaloperations/transportation_offices/show_counseling_offices_urlbuilder.go
  pkg/gen/internalmessages/counseling_office.go
  pkg/gen/internalmessages/counseling_offices.go
  pkg/handlers/internalapi/api.go
  pkg/handlers/internalapi/internal/payloads/model_to_payload.go
  pkg/handlers/internalapi/transportation_offices.go
  pkg/handlers/internalapi/transportation_offices_test.go
  pkg/services/event/internal_endpoint.go
  pkg/services/mocks/TransportationOfficesFetcher.go
  pkg/services/transportation_office.go
  pkg/services/transportation_office/transportation_office_fetcher.go
  pkg/services/transportation_office/transportation_office_fetcher_test.go
  src/services/internalApi.js
  swagger-def/internal.yaml
  swagger/internal.yaml
Labels: G-Unit, MAIN

#13648 B 21015
  pkg/handlers/primeapiv3/payloads/model_to_payload.go
  pkg/handlers/primeapiv3/payloads/model_to_payload_test.go
Labels: Mountain Movers, MAIN

#13640 INT B-21029 rejected office users can resubmit
  pkg/factory/office_user_factory.go
  pkg/handlers/adminapi/office_users.go
  pkg/handlers/adminapi/requested_office_users.go
  pkg/handlers/ghcapi/office_users.go
  pkg/handlers/ghcapi/office_users_test.go
  pkg/models/office_user.go
  pkg/services/office_user/office_user_creator.go
  pkg/services/office_user/office_user_creator_test.go
  pkg/services/requested_office_users/requested_office_user_list_fetcher_test.go
  pkg/services/requested_office_users/requested_office_user_updater.go
  pkg/testdatagen/testharness/make_office_user.go
  src/components/Office/RequestAccountForm/RequestAccountForm.module.scss
  src/components/form/OfficeAccountRequestFields/OfficeAccountRequestFields.jsx
  src/pages/Office/RequestAccount/RequestAccount.jsx
  src/pages/Office/RequestAccount/RequestAccount.module.scss
Labels: Mountain Movers, INTEGRATION

#13641 INT B-21038 generate fake identifiers for safety moves
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/customer.go
  pkg/handlers/ghcapi/customer_test.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/orders.go
  pkg/handlers/ghcapi/queues_test.go
  src/components/CustomerHeader/CustomerHeader.test.jsx
  src/components/CustomerHeader/index.jsx
  src/components/Office/DefinitionLists/CustomerInfoList.jsx
  src/components/Office/DefinitionLists/CustomerInfoList.test.jsx
  src/pages/Office/CustomerOnboarding/CreateCustomerForm.jsx
  src/pages/Office/CustomerOnboarding/CreateCustomerForm.test.jsx
  src/pages/Office/MoveDetails/MoveDetails.jsx
  src/utils/customer.js
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: Mountain Movers, INTEGRATION

#13649 B 21036 enforce dodid and emplid int
  go.mod
  go.sum
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/create_customer_payload.go
  pkg/handlers/ghcapi/customer.go
  pkg/handlers/ghcapi/customer_test.go
  src/pages/Office/CustomerOnboarding/CreateCustomerForm.jsx
  src/pages/Office/CustomerOnboarding/CreateCustomerForm.test.jsx
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: Mountain Movers, INTEGRATION

#13563 MAIN B-20622 mobile home office api
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/create_m_t_o_shipment.go
  pkg/gen/ghcmessages/create_mobile_home.go
  pkg/gen/ghcmessages/create_mobile_home_shipment.go
  pkg/gen/ghcmessages/update_mobile_home_shipment.go
  pkg/gen/ghcmessages/update_shipment.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/internal/payloads/payload_to_model.go
  pkg/handlers/ghcapi/mto_shipment.go
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: ByteSize M&Ms, MAIN

#13642 B-20617: SC and TOO Creating Mobile Home Shipment and Shipment Card Display
  pkg/services/move/move_router.go
  playwright/tests/office/servicescounseling/servicesCounselingMobileHome.spec.js
  playwright/tests/office/txo/tooFlowsMobileHome.spec.js
  src/components/Office/DefinitionLists/MobileHomeShipmentInfoList.jsx
  src/components/Office/DefinitionLists/MobileHomeShipmentInfoList.stories.jsx
  src/components/Office/DefinitionLists/MobileHomeShipmentInfoList.test.jsx
  src/components/Office/DefinitionLists/ShipmentInfoListSelector.jsx
  src/components/Office/ShipmentForm/MobileHomeShipmentForm/MobileHomeShipmentForm.jsx
  src/components/Office/ShipmentForm/MobileHomeShipmentForm/MobileHomeShipmentForm.module.scss
  src/components/Office/ShipmentForm/MobileHomeShipmentForm/mobileHomeShipmentSchema.js
  src/components/Office/ShipmentForm/ShipmentForm.jsx
  src/components/Office/ShipmentFormRemarks/ShipmentFormRemarks.jsx
  src/pages/Office/AddShipment/AddShipment.jsx
  src/pages/Office/MoveDetails/MoveDetails.jsx
  src/pages/Office/ServicesCounselingAddShipment/ServicesCounselingAddShipment.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
  src/shared/constants.js
  src/utils/formatMtoShipment.js
Labels: ByteSize M&Ms, INTEGRATION

#13623 B19795 int doc viewer doc title change
  pkg/handlers/internalapi/uploads.go
  pkg/services/payment_request/upload_creator.go
  playwright/tests/my/milmove/ppms/customerPpmTestFixture.js
  src/components/DocumentViewer/Menu/Menu.module.scss
  src/components/DocumentViewerFileManager/DocumentViewerFileManager.jsx
  src/pages/MyMove/AdditionalDocuments/AdditionalDocuments.jsx
  src/pages/MyMove/EditOrders.jsx
  src/pages/MyMove/PPM/Closeout/Expenses/Expenses.jsx
  src/pages/MyMove/PPM/Closeout/ProGear/ProGear.jsx
  src/pages/MyMove/PPM/Closeout/WeightTickets/WeightTickets.jsx
  src/pages/MyMove/UploadOrders.jsx
Labels: ByteSize M&Ms, INTEGRATION

#13659 B-19191: Email Template not locating all duty location names
  pkg/notifications/move_submitted.go
  pkg/notifications/move_submitted_test.go
Labels: ByteSize M&Ms, MAIN

#13662 B 20940 int 2
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet_test.go
Labels: Scrummy Bears, INTEGRATION

#13606 INT B-20893 Queue export issue when switching GBLOCs as HQ user
  go.mod
  go.sum
  src/components/Table/TableCSVExportButton.jsx
  src/components/Table/TableCSVExportButton.test.jsx
  src/components/Table/TableQueue.jsx
  src/pages/Office/HeadquartersQueues/HeadquartersQueues.jsx
Labels: Scrummy Bears, INTEGRATION

#13667 MAIN B-21029 rejected office users can resubmit
  pkg/factory/office_user_factory.go
  pkg/handlers/adminapi/office_users.go
  pkg/handlers/adminapi/requested_office_users.go
  pkg/handlers/ghcapi/office_users.go
  pkg/handlers/ghcapi/office_users_test.go
  pkg/models/office_user.go
  pkg/services/office_user/office_user_creator.go
  pkg/services/office_user/office_user_creator_test.go
  pkg/services/requested_office_users/requested_office_user_list_fetcher_test.go
  pkg/services/requested_office_users/requested_office_user_updater.go
  pkg/testdatagen/testharness/make_office_user.go
  src/components/Office/RequestAccountForm/RequestAccountForm.module.scss
  src/pages/Office/RequestAccount/RequestAccount.jsx
  src/pages/Office/RequestAccount/RequestAccount.module.scss
Labels: Mountain Movers, MAIN

#13658 INT-B-20522 sit validation
  pkg/handlers/primeapi/payment_request.go
  pkg/services/payment_request/payment_request_creator.go
  pkg/testdatagen/scenario/shared.go
Labels: G-Unit, INTEGRATION

#13675 MAIN B-20946 SSW max obligation calculation correction
  pkg/services/ppm_closeout/ppm_closeout.go
  pkg/services/ppmshipment/ppm_estimator.go
  pkg/services/ppmshipment/ppm_estimator_test.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet_test.go
  playwright/tests/office/ppms/happyPathFlows.spec.js
Labels: Mountain Movers, MAIN

#13636 INT-B-20492
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/ghcapi/ghcoperations/payment_requests/bulk_download.go
  pkg/gen/ghcapi/ghcoperations/payment_requests/bulk_download_parameters.go
  pkg/gen/ghcapi/ghcoperations/payment_requests/bulk_download_responses.go
  pkg/gen/ghcapi/ghcoperations/payment_requests/bulk_download_urlbuilder.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/payment_request.go
  pkg/paperwork/generator.go
  pkg/paperwork/generator_test.go
  pkg/services/payment_request.go
  pkg/services/payment_request/payment_request_bulk_download_creator.go
  src/components/DocumentViewer/DocumentViewer.jsx
  src/components/DocumentViewer/DocumentViewer.module.scss
  src/components/DocumentViewer/DocumentViewer.test.jsx
  src/pages/Office/PaymentRequestReview/PaymentRequestReview.jsx
  src/pages/Office/PaymentRequestReview/PaymentRequestReview.test.jsx
  src/services/ghcApi.js
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: G-Unit, INTEGRATION

#13620 B 20653 mobile home shipment card
  pkg/services/move/move_router.go
  playwright/tests/my/mymove/mobileHome.spec.js
  playwright/tests/utils/my/waitForCustomerPage.js
  src/components/Customer/BoatShipment/BoatShipmentForm/BoatShipmentForm.jsx
  src/components/Customer/MobileHomeShipment/MobileHomeShipmentForm/MobileHomeShipmentForm.jsx
  src/components/Customer/MtoShipmentForm/MtoShipmentForm.jsx
  src/components/Customer/Review/ShipmentCard/MobileHomeShipmentCard/MobileHomeshipmentCard.test.jsx
  src/components/Customer/Review/Summary/Summary.test.jsx
  src/components/ShipmentList/ShipmentList.jsx
  src/content/shipments.js
  src/pages/MyMove/MobileHome/MobileHomeShipmentCreate/MobileHomeShipmentCreate.jsx
  src/pages/MyMove/MobileHome/MobileHomeShipmentCreate/MobileHomeShipmentCreate.test.jsx
  src/pages/MyMove/SelectShipmentType.jsx
Labels: ByteSize M&Ms, INTEGRATION

#13664 Services test
  src/components/Office/ShipmentForm/ShipmentForm.jsx
Labels: Scrummy Bears, MAIN

#13541 INT B-20787 NTS/NTS-Release destination/pickup addresses are set to storage facility address
  pkg/handlers/internalapi/mto_shipment_test.go
  pkg/handlers/primeapi/mto_shipment_address.go
  pkg/handlers/primeapi/mto_shipment_address_test.go
  pkg/services/mto_shipment/mto_shipment_creator.go
  pkg/services/mto_shipment/mto_shipment_creator_test.go
  pkg/services/mto_shipment/mto_shipment_updater.go
  pkg/services/shipment_address_update/shipment_address_update_requester.go
Labels: Scrummy Bears, INTEGRATION

#13672 B 20919 sit date retention main
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/s_i_t_service_item_grouping.go
  pkg/gen/ghcmessages/s_i_t_service_item_groupings.go
  pkg/gen/ghcmessages/s_i_t_status.go
  pkg/gen/ghcmessages/s_i_t_summary.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/handlers/ghcapi/payment_request_test.go
  pkg/models/re_service.go
  pkg/services/mocks/ShipmentSITStatus.go
  pkg/services/mto_shipment.go
  pkg/services/payment_request/payment_request_shipments_sit_balance.go
  pkg/services/sit_status/shipment_sit_status.go
  pkg/services/sit_status/shipment_sit_status_test.go
  playwright/tests/office/txo/sitUpdates.spec.js
  src/components/Office/ShipmentSITDisplay/ShipmentSITDisplay.jsx
  src/components/Office/ShipmentSITDisplay/ShipmentSITDisplay.test.jsx
  src/components/Office/ShipmentSITDisplay/ShipmentSITDisplayTestParams.js
  swagger-def/definitions/SITServiceItemGrouping.yaml
  swagger-def/definitions/SITServiceItemGroupings.yaml
  swagger-def/definitions/SITStatus.yaml
  swagger-def/definitions/SITSummary.yaml
  swagger/ghc.yaml
Labels: Mountain Movers, MAIN

#13676 INT B-19809 update SC flag count to include missing orders info
  src/components/Office/ServicesCounselingTabNav/ServicesCounselingTabNav.jsx
  src/components/Office/ServicesCounselingTabNav/ServicesCounselingTabNav.test.jsx
  src/components/Office/TXOTabNav/TXOTabNav.jsx
  src/components/Office/TXOTabNav/TXOTabNav.test.jsx
  src/pages/Office/MoveDetails/MoveDetails.jsx
  src/pages/Office/MoveDetails/MoveDetails.test.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.test.jsx
  src/pages/Office/ServicesCounselingMoveInfo/ServicesCounselingMoveInfo.jsx
  src/pages/Office/TXOMoveInfo/TXOMoveInfo.jsx
Labels: Mountain Movers, INTEGRATION

#13661 B 20441 int
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240905192913_adding_prices_to_unpriced_cs_ms_service_items.up.sql
  migrations/app/schema/20240909194514_pricing_unpriced_ms_cs_service_items.up.sql
  migrations/app/schema/20240910021542_populating_locked_price_cents_from_pricing_estimate_for_ms_and_cs_service_items.up.sql
Labels: Scrummy Bears, INTEGRATION

#13695 INT B-20452 - Review and submit button bug fix
  src/pages/MyMove/Home/MoveHome.jsx
  src/pages/MyMove/Home/index.jsx
Labels: ByteSize M&Ms, INTEGRATION

#13696 B 20940 disbursement
  pkg/services/shipment_summary_worksheet.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet_test.go
Labels: Scrummy Bears, MAIN

#13633 B 20943
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet_test.go
Labels: Scrummy Bears, MAIN

#13678 MAIN - B-20949 SSW remaining ppm incentive calculation
  pkg/services/shipment_summary_worksheet.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet_test.go
Labels: Scrummy Bears, MAIN

#13677 B-19810 INT
  src/pages/Office/MovePaymentRequests/MovePaymentRequests.jsx
  src/pages/Office/MovePaymentRequests/MovePaymentRequests.module.scss
  src/pages/Office/MovePaymentRequests/MovePaymentRequests.test.jsx
Labels: Mountain Movers, INTEGRATION

#13708 INT B-19809 508 Fix
  src/pages/Office/MoveDetails/MoveDetails.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
  src/shared/styles/colors.scss
Labels: Mountain Movers, INTEGRATION

#13692 B-21054-INT Prime can add second/third addresses to existing shipments
  pkg/gen/primev3api/embedded_spec.go
  pkg/gen/primev3messages/update_m_t_o_shipment.go
  pkg/gen/primev3messages/update_p_p_m_shipment.go
  pkg/handlers/primeapiv3/payloads/payload_to_model.go
  playwright/tests/office/primesimulator/primeSimulatorFlows.spec.js
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdate.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdateForm.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdatePPMForm.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdatePPMForm.test.jsx
  src/utils/formatters.js
  swagger-def/prime_v3.yaml
  swagger/prime_v3.yaml
Labels: G-Unit, INTEGRATION

#13720 INT-B-20522 sit validation
  pkg/handlers/primeapi/payment_request.go
  pkg/services/payment_request/payment_request_creator.go
Labels: G-Unit, INTEGRATION

#13730 INT B-21022 - Include/Exclude specific offices
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240917132411_update_provides_ppm_closeout_transportation_offices.up.sql
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/transportation_office/get_transportation_offices.go
  pkg/handlers/ghcapi/tranportation_offices.go
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: Scrummy Bears, INTEGRATION

#13709 B 21061 display sit authorized end dates int
  pkg/services/payment_request/payment_request_shipments_sit_balance.go
  pkg/services/payment_request/payment_request_shipments_sit_balance_test.go
  pkg/services/sit_status/shipment_sit_status.go
  pkg/services/sit_status/shipment_sit_status_test.go
  src/components/Office/ShipmentSITDisplay/ShipmentSITDisplay.jsx
  src/components/Office/ShipmentSITDisplay/ShipmentSITDisplay.module.scss
  src/components/Office/ShipmentSITDisplay/ShipmentSITDisplay.test.jsx
Labels: Mountain Movers, INTEGRATION

#13725 INT B-19044
  playwright/tests/office/servicescounseling/servicesCounselingFlows.spec.js
  src/components/Office/DefinitionLists/PPMShipmentInfoList.jsx
  src/components/Office/DefinitionLists/ShipmentInfoList.jsx
  src/components/Office/ServicesCounselingTabNav/ServicesCounselingTabNav.jsx
  src/components/Office/TXOTabNav/TXOTabNav.jsx
  src/pages/Office/MoveDetails/MoveDetails.jsx
  src/pages/Office/MoveDetails/MoveDetails.test.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.test.jsx
  src/pages/Office/ServicesCounselingMoveInfo/ServicesCounselingMoveInfo.jsx
  src/pages/Office/ServicesCounselingMoveInfo/ServicesCounselingTab.module.scss
  src/pages/Office/TXOMoveInfo/TXOMoveInfo.jsx
Labels: Mountain Movers, INTEGRATION

#13702 B-21041-INT Prime can update second/third addresses
  pkg/handlers/primeapi/mto_shipment_address.go
  pkg/services/mto_shipment/mto_shipment_address_updater.go
  src/components/PrimeUI/Shipment/Shipment.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdateAddress.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdateAddress.test.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdateAddressForm.jsx
  src/shared/constants.js
Labels: G-Unit, INTEGRATION

#13710 B 20619 prime create mobile home int
  pkg/gen/primev2api/embedded_spec.go
  pkg/gen/primev2messages/create_boat_shipment.go
  pkg/gen/primev2messages/create_mobile_home_shipment.go
  pkg/gen/primev3api/embedded_spec.go
  pkg/gen/primev3messages/create_boat_shipment.go
  pkg/gen/primev3messages/create_m_t_o_shipment.go
  pkg/gen/primev3messages/create_mobile_home_shipment.go
  pkg/gen/primev3messages/m_t_o_shipment_without_service_items.go
  pkg/gen/primev3messages/mobile_home.go
  pkg/handlers/primeapi/move_task_order.go
  pkg/handlers/primeapiv2/move_task_order.go
  pkg/handlers/primeapiv2/mto_shipment.go
  pkg/handlers/primeapiv3/move_task_order.go
  pkg/handlers/primeapiv3/mto_shipment.go
  pkg/handlers/primeapiv3/payloads/model_to_payload.go
  pkg/handlers/primeapiv3/payloads/payload_to_model.go
  pkg/handlers/routing/routing_init.go
  pkg/services/move_task_order/move_task_order_fetcher.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet_test.go
  src/components/PrimeUI/Shipment/Shipment.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentCreate.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentCreateForm.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentCreateForm.test.jsx
  src/styles/form.module.scss
  swagger-def/definitions/prime/v2/MTOShipmentWithoutServiceItems.yaml
  swagger-def/definitions/prime/v3/MTOShipmentWithoutServiceItems.yaml
  swagger-def/prime_v2.yaml
  swagger-def/prime_v3.yaml
  swagger/prime_v2.yaml
  swagger/prime_v3.yaml
Labels: ByteSize M&Ms, INTEGRATION

#13731 B-20785 Update SC Move create to self assign counseling office
  pkg/handlers/ghcapi/orders.go
  pkg/handlers/ghcapi/orders_test.go
  pkg/handlers/internalapi/office_test.go
  pkg/models/move.go
  pkg/models/move_test.go
  pkg/models/queue_test.go
Labels: G-Unit, MAIN

#13739 B 20441 int
  migrations/app/schema/20240822180409_adding_locked_price_cents_service_param.up.sql
Labels: Scrummy Bears, INTEGRATION

#13341 B-20477
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240729185147_add_cancel_to_ppm_status_enum.up.sql
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/move/move_canceler.go
  pkg/gen/ghcapi/ghcoperations/move/move_canceler_parameters.go
  pkg/gen/ghcapi/ghcoperations/move/move_canceler_responses.go
  pkg/gen/ghcapi/ghcoperations/move/move_canceler_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/ghcmessages/p_p_m_shipment_status.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/p_p_m_shipment_status.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/p_p_m_shipment_status.go
  pkg/gen/primev2api/embedded_spec.go
  pkg/gen/primev2messages/p_p_m_shipment_status.go
  pkg/gen/primev3api/embedded_spec.go
  pkg/gen/primev3messages/p_p_m_shipment_status.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/move.go
  pkg/models/ppm_shipment.go
  pkg/services/move.go
  pkg/services/move/move_canceler.go
  pkg/services/move/move_canceler_test.go
  pkg/services/move/move_router_test.go
  swagger-def/definitions/PPMShipmentStatus.yaml
  swagger-def/ghc.yaml
  swagger/ghc.yaml
  swagger/internal.yaml
  swagger/prime.yaml
  swagger/prime_v2.yaml
  swagger/prime_v3.yaml
Labels: G-Unit, MAIN

#13733 MAIN B-20787 & B-20788 & B-20789 - NTS/NTS-Release destination/pickup addresses are set to storage facility address
  pkg/handlers/internalapi/mto_shipment_test.go
  pkg/handlers/primeapi/mto_shipment_address.go
  pkg/handlers/primeapi/mto_shipment_address_test.go
  pkg/services/mto_shipment/mto_shipment_creator.go
  pkg/services/mto_shipment/mto_shipment_creator_test.go
  pkg/services/mto_shipment/mto_shipment_updater.go
  pkg/services/shipment_address_update/shipment_address_update_requester.go
Labels: Scrummy Bears, MAIN

#13644 B-21040 Prime can view third addresses
  pkg/gen/primev3api/embedded_spec.go
  pkg/gen/primev3messages/m_t_o_shipment_without_service_items.go
  pkg/gen/primev3messages/p_p_m_shipment.go
  pkg/handlers/primeapiv3/move_task_order_test.go
  pkg/handlers/primeapiv3/payloads/model_to_payload.go
  pkg/services/move_task_order/move_task_order_fetcher.go
  pkg/services/move_task_order/move_task_order_fetcher_test.go
  src/components/PrimeUI/Shipment/Shipment.jsx
  src/components/PrimeUI/Shipment/Shipment.test.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdate.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdateForm.jsx
  swagger-def/definitions/prime/v3/MTOShipmentWithoutServiceItems.yaml
  swagger-def/definitions/prime/v3/PPMShipment.yaml
  swagger/prime_v3.yaml
Labels: G-Unit, MAIN

#13735 B-20466 add a frontend (filterable) column to the SC's queue
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/queues/get_services_counseling_queue_parameters.go
  pkg/gen/ghcapi/ghcoperations/queues/get_services_counseling_queue_urlbuilder.go
  pkg/gen/ghcmessages/queue_move.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/orders.go
  pkg/handlers/ghcapi/queues.go
  pkg/services/order.go
  pkg/services/order/order_fetcher.go
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.jsx
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.test.jsx
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: G-Unit, MAIN

#13539 B 20441
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240822180409_adding_locked_price_cents_service_param.up.sql
  migrations/app/schema/20240909194514_pricing_unpriced_ms_cs_service_items.up.sql
  migrations/app/schema/20240910021542_populating_locked_price_cents_from_pricing_estimate_for_ms_and_cs_service_items.up.sql
  pkg/factory/mto_service_item_factory.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/service_item_param_name.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/service_item_param_name.go
  pkg/gen/primev2api/embedded_spec.go
  pkg/gen/primev2messages/service_item_param_name.go
  pkg/gen/primev3api/embedded_spec.go
  pkg/gen/primev3messages/service_item_param_name.go
  pkg/handlers/ghcapi/mto_service_items.go
  pkg/models/service_item_param_key.go
  pkg/payment_request/service_param_value_lookups/locked_price_cents_lookup.go
  pkg/payment_request/service_param_value_lookups/service_param_value_lookups.go
  pkg/services/ghc_rate_engine.go
  pkg/services/ghcrateengine/counseling_services_pricer.go
  pkg/services/ghcrateengine/counseling_services_pricer_test.go
  pkg/services/ghcrateengine/management_services_pricer.go
  pkg/services/ghcrateengine/management_services_pricer_test.go
  pkg/services/ghcrateengine/service_item_pricer_test.go
  pkg/services/mocks/CounselingServicesPricer.go
  pkg/services/mocks/ManagementServicesPricer.go
  pkg/services/payment_request/payment_request_recalculator_test.go
  swagger-def/definitions/ServiceItemParamName.yaml
  swagger/ghc.yaml
  swagger/prime.yaml
  swagger/prime_v2.yaml
  swagger/prime_v3.yaml
Labels: Scrummy Bears, MAIN

#13732 MAIN B-20893 - Queue export issue when switching GBLOCs as HQ user
  src/components/Table/TableCSVExportButton.jsx
  src/components/Table/TableCSVExportButton.test.jsx
  src/components/Table/TableQueue.jsx
  src/pages/Office/HeadquartersQueues/HeadquartersQueues.jsx
Labels: Scrummy Bears, MAIN

#13714 Main b 20292 alt phone update issue
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/create_service_member_payload.go
  pkg/gen/internalmessages/patch_service_member_payload.go
  pkg/gen/internalmessages/service_member_payload.go
  src/pages/MyMove/Profile/ContactInfo.jsx
  src/pages/MyMove/Profile/EditContactInfo.jsx
  src/pages/Office/CustomerOnboarding/CreateCustomerForm.test.jsx
  swagger-def/internal.yaml
  swagger/internal.yaml
Labels: ByteSize M&Ms, MAIN

#13689 MAIN B-21038 generate fake identifiers for safety moves
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/customer.go
  pkg/handlers/ghcapi/customer_test.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/orders.go
  pkg/handlers/ghcapi/queues_test.go
  src/components/CustomerHeader/CustomerHeader.test.jsx
  src/components/CustomerHeader/index.jsx
  src/components/Office/DefinitionLists/CustomerInfoList.jsx
  src/components/Office/DefinitionLists/CustomerInfoList.test.jsx
  src/pages/Office/CustomerOnboarding/CreateCustomerForm.jsx
  src/pages/Office/CustomerOnboarding/CreateCustomerForm.test.jsx
  src/pages/Office/MoveDetails/MoveDetails.jsx
  src/utils/customer.js
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: Mountain Movers, MAIN

#13734 B-20947 Fix: Apply GCC calculation Fix to Payment Packet
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet.go
Labels: Mountain Movers, INTEGRATION

#13685 MAIN B-19809 update SC flag count to include missing orders info
  src/components/Office/ServicesCounselingTabNav/ServicesCounselingTabNav.jsx
  src/components/Office/ServicesCounselingTabNav/ServicesCounselingTabNav.test.jsx
  src/components/Office/TXOTabNav/TXOTabNav.jsx
  src/components/Office/TXOTabNav/TXOTabNav.test.jsx
  src/pages/Office/MoveDetails/MoveDetails.jsx
  src/pages/Office/MoveDetails/MoveDetails.test.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.test.jsx
  src/pages/Office/ServicesCounselingMoveInfo/ServicesCounselingMoveInfo.jsx
  src/pages/Office/TXOMoveInfo/TXOMoveInfo.jsx
  src/shared/styles/colors.scss
Labels: Mountain Movers, MAIN

#13743 B-20445: Add Marine Corps BOS to Move Search and BOS filter in work queues
  src/components/Table/SearchResultsTable.jsx
  src/constants/queues.js
  src/pages/Office/MoveQueue/MoveQueue.jsx
  src/pages/Office/MoveQueue/MoveQueue.test.jsx
  src/pages/Office/ServicesCounselingEditShipmentDetails/ServicesCounselingEditShipmentDetails.test.jsx
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.jsx
Labels: ByteSize M&Ms, MAIN

#13726 B-21016 tpps received totals main
  pkg/services/invoice/process_edi997.go
  pkg/services/invoice/process_edi997_test.go
  src/components/Office/PaymentRequestCard/PaymentRequestCard.jsx
  src/components/Office/PaymentRequestCard/PaymentRequestCard.test.jsx
Labels: Mountain Movers, MAIN

#13637 B-20492 bulk download files
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/ghcapi/ghcoperations/payment_requests/bulk_download.go
  pkg/gen/ghcapi/ghcoperations/payment_requests/bulk_download_parameters.go
  pkg/gen/ghcapi/ghcoperations/payment_requests/bulk_download_responses.go
  pkg/gen/ghcapi/ghcoperations/payment_requests/bulk_download_urlbuilder.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/payment_request.go
  pkg/paperwork/generator.go
  pkg/paperwork/generator_test.go
  pkg/services/payment_request.go
  pkg/services/payment_request/payment_request_bulk_download_creator.go
  src/components/DocumentViewer/DocumentViewer.jsx
  src/components/DocumentViewer/DocumentViewer.module.scss
  src/components/DocumentViewer/DocumentViewer.test.jsx
  src/pages/Office/PaymentRequestReview/PaymentRequestReview.jsx
  src/pages/Office/PaymentRequestReview/PaymentRequestReview.test.jsx
  src/services/ghcApi.js
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: G-Unit, MAIN

#13674 B 21036 enforce dodid and emplid main
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/create_customer_payload.go
  pkg/handlers/ghcapi/customer.go
  pkg/handlers/ghcapi/customer_test.go
  src/pages/Office/CustomerOnboarding/CreateCustomerForm.jsx
  src/pages/Office/CustomerOnboarding/CreateCustomerForm.test.jsx
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: Mountain Movers, MAIN

#13746 MAIN - B-21022 - Include/Exclude specific offices
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240917132411_update_provides_ppm_closeout_transportation_offices.up.sql
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/transportation_office/get_transportation_offices.go
  pkg/handlers/ghcapi/tranportation_offices.go
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: Scrummy Bears, MAIN

#13701 B 21041 Prime can update existing second/third addresses
  pkg/handlers/primeapi/mto_shipment_address.go
  pkg/services/mto_shipment/mto_shipment_address_updater.go
  src/components/PrimeUI/Shipment/Shipment.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdateAddress.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdateAddress.test.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdateAddressForm.jsx
  src/shared/constants.js
Labels: G-Unit, MAIN

#13712 INT-B-21042
  pkg/gen/primev3api/embedded_spec.go
  pkg/gen/primev3messages/create_m_t_o_shipment.go
  pkg/gen/primev3messages/create_p_p_m_shipment.go
  pkg/handlers/primeapiv3/payloads/payload_to_model.go
  src/pages/PrimeUI/Shipment/PrimeUIShipmentCreate.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentCreateForm.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentCreateForm.test.jsx
  swagger-def/prime_v3.yaml
  swagger/prime_v3.yaml
Labels: G-Unit, INTEGRATION

#13744 B 21078 int
  src/constants/MoveHistory/EventTemplates/UpdateMTOShipment/patchMTOShipment.jsx
  src/constants/MoveHistory/EventTemplates/UpdateMTOShipment/patchMTOShipment.test.jsx
  src/constants/MoveHistory/EventTemplates/UploadAdditionalDocuments/uploadAdditionalDocuments.jsx
  src/constants/MoveHistory/EventTemplates/UploadAdditionalDocuments/uploadAdditionalDocuments.test.jsx
  src/constants/MoveHistory/EventTemplates/index.js
  src/constants/MoveHistory/UIDisplay/Operations.js
Labels: G-Unit, INTEGRATION

#13691 B-21054 Prime can add second/third addresses to existing shipments
  pkg/gen/primev3api/embedded_spec.go
  pkg/gen/primev3messages/update_m_t_o_shipment.go
  pkg/gen/primev3messages/update_p_p_m_shipment.go
  pkg/handlers/primeapiv3/payloads/payload_to_model.go
  playwright/tests/office/primesimulator/primeSimulatorFlows.spec.js
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdate.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdateForm.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdatePPMForm.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdatePPMForm.test.jsx
  src/utils/formatters.js
  swagger-def/prime_v3.yaml
  swagger/prime_v3.yaml
Labels: G-Unit, MAIN

#13754 B 20967 sit panel main
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/handlers/ghcapi/payment_request_test.go
  pkg/services/mocks/ShipmentSITStatus.go
  pkg/services/mto_service_item/mto_service_item_updater_test.go
  pkg/services/mto_shipment.go
  pkg/services/payment_request/payment_request_shipments_sit_balance.go
  pkg/services/payment_request/payment_request_shipments_sit_balance_test.go
  pkg/services/sit_status/shipment_sit_status.go
  pkg/services/sit_status/shipment_sit_status_test.go
  pkg/testdatagen/testharness/dispatch.go
  pkg/testdatagen/testharness/make_move.go
  playwright/tests/office/txo/sitUpdates.spec.js
  playwright/tests/utils/testharness.js
  src/components/Office/ShipmentSITDisplay/ShipmentSITDisplay.jsx
  src/components/Office/ShipmentSITDisplay/ShipmentSITDisplay.test.jsx
Labels: Mountain Movers, MAIN

#13736 20989 update duty_locations table data
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240917165710_update_duty_locations_provides_services_counseling.up.sql
Labels: G-Unit, MAIN

#13575 B-20522 SIT Validation
  pkg/handlers/primeapi/payment_request.go
  pkg/services/payment_request/payment_request_creator.go
  pkg/testdatagen/scenario/shared.go
Labels: G-Unit, MAIN

#13758 B 21061 display sit authorized end dates main
  pkg/services/payment_request/payment_request_shipments_sit_balance.go
  pkg/services/payment_request/payment_request_shipments_sit_balance_test.go
  pkg/services/sit_status/shipment_sit_status.go
  pkg/services/sit_status/shipment_sit_status_test.go
  src/components/Office/ShipmentSITDisplay/ShipmentSITDisplay.jsx
  src/components/Office/ShipmentSITDisplay/ShipmentSITDisplay.module.scss
  src/components/Office/ShipmentSITDisplay/ShipmentSITDisplay.test.jsx
Labels: Mountain Movers, MAIN

#13749 B-19810 Main
  src/pages/Office/MovePaymentRequests/MovePaymentRequests.jsx
  src/pages/Office/MovePaymentRequests/MovePaymentRequests.module.scss
  src/pages/Office/MovePaymentRequests/MovePaymentRequests.test.jsx
Labels: Mountain Movers, MAIN

#13500 B-20530 Office user move assign/un-assign functionality
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/move/delete_assigned_office_user.go
  pkg/gen/ghcapi/ghcoperations/move/delete_assigned_office_user_parameters.go
  pkg/gen/ghcapi/ghcoperations/move/delete_assigned_office_user_responses.go
  pkg/gen/ghcapi/ghcoperations/move/delete_assigned_office_user_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/move/update_assigned_office_user.go
  pkg/gen/ghcapi/ghcoperations/move/update_assigned_office_user_parameters.go
  pkg/gen/ghcapi/ghcoperations/move/update_assigned_office_user_responses.go
  pkg/gen/ghcapi/ghcoperations/move/update_assigned_office_user_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/ghcmessages/assign_office_user_body.go
  pkg/gen/ghcmessages/assigned_office_user.go
  pkg/gen/ghcmessages/move.go
  pkg/gen/ghcmessages/queue_move.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/move.go
  pkg/handlers/ghcapi/move_test.go
  pkg/services/move.go
  pkg/services/move/assigned_office_user_updater.go
  src/services/ghcApi.js
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: G-Unit, MAIN

#13704 B-20997
  pkg/handlers/routing/routing_init.go
Labels: G-Unit, MAIN

#13650 INT-B-20618 Office users edit/create/delete mobile home shipments
  pkg/factory/boat_shipment_factory.go
  pkg/services/move/move_router.go
  pkg/services/move/move_router_test.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet_test.go
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/testharness/dispatch.go
  pkg/testdatagen/testharness/make_move.go
  playwright/tests/office/servicescounseling/servicesCounselingMobileHome.spec.js
  playwright/tests/office/txo/tooFlowsMobileHome.spec.js
  playwright/tests/utils/office/waitForOfficePage.js
  playwright/tests/utils/testharness.js
  src/components/Office/DefinitionLists/MobileHomeShipmentInfoList.jsx
  src/constants/userRoles.js
  src/pages/Office/MoveDetails/MoveDetails.jsx
  src/pages/Office/RequestAccount/RequestAccount.module.scss
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
Labels: ByteSize M&Ms, INTEGRATION

#13765 Revert "Apply GCC calculation Fix to Payment Packet"
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet.go
Labels: Mountain Movers, INTEGRATION

#13767 add in main test checks
  .circleci/config.yml
  src/components/Customer/Review/ShipmentCard/MobileHomeShipmentCard/MobileHomeshipmentCard.test.jsx
Labels: ByteSize M&Ms, INTEGRATION

#13773 Int b 20001 part ii
  pkg/services/pptas_report/pptas_report_list_fetcher.go
Labels: G-Unit, INTEGRATION

#13772 B-20001 Part 2 fixed nil check
  pkg/services/pptas_report/pptas_report_list_fetcher.go
Labels: G-Unit, MAIN

#13778 B 21078 int
  src/constants/MoveHistory/EventTemplates/UpdateMTOShipment/patchMTOShipment.jsx
  src/constants/MoveHistory/EventTemplates/UpdateMTOShipment/patchMTOShipment.test.jsx
  src/constants/MoveHistory/EventTemplates/UploadAdditionalDocuments/uploadAdditionalDocuments.jsx
  src/constants/MoveHistory/EventTemplates/UploadAdditionalDocuments/uploadAdditionalDocuments.test.jsx
  src/constants/MoveHistory/EventTemplates/index.js
  src/constants/MoveHistory/UIDisplay/Operations.js
Labels: G-Unit, INTEGRATION

#13770 20616 add mobile shipment customer flows int
  pkg/handlers/internalapi/moves.go
  pkg/services/orchestrators/shipment/shipment_updater.go
  src/components/Customer/MobileHomeShipment/MobileHomeShipmentForm/MobileHomeShipmentForm.jsx
  src/components/Customer/MobileHomeShipment/MobileHomeShipmentForm/MobileHomeShipmentForm.module.scss
  src/components/Customer/MobileHomeShipment/MobileHomeShipmentForm/MobileHomeShipmentForm.stories.jsx
  src/components/Customer/MobileHomeShipment/MobileHomeShipmentForm/MobileHomeShipmentForm.test.jsx
  src/components/Customer/MtoShipmentForm/MtoShipmentForm.jsx
  src/components/Customer/MtoShipmentForm/getShipmentOptions.js
  src/components/Customer/Review/ShipmentCard/MobileHomeShipmentCard/MobileHomeShipmentCard.jsx
  src/components/Customer/Review/ShipmentCard/MobileHomeShipmentCard/MobileHomeShipmentCard.test.jsx
  src/components/Customer/Review/Summary/Summary.jsx
  src/components/Customer/modals/BoatAndMobileInfoModal/BoatAndMobileInfoModal.jsx
  src/components/Office/ShipmentContainer/ShipmentContainer.jsx
  src/components/ShipmentList/ShipmentList.jsx
  src/components/ShipmentList/ShipmentList.module.scss
  src/components/ShipmentTag/ShipmentTag.module.scss
  src/constants/routes.js
  src/constants/shipments.js
  src/content/shipments.js
  src/pages/MyMove/CreateOrEditMtoShipment.jsx
  src/pages/MyMove/Home/MoveHome.jsx
  src/pages/MyMove/MobileHome/MobileHomeShipmentCreate/MobileHomeShipmentCreate.jsx
  src/pages/MyMove/MobileHome/MobileHomeShipmentCreate/MobileHomeShipmentCreate.test.jsx
  src/pages/MyMove/MobileHome/MobileHomeShipmentLocationInfo/MobileHomeShipmentLocationInfo.jsx
  src/pages/MyMove/MobileHome/MobileHomeShipmentLocationInfo/MobileHomeShipmentLocationInfo.test.jsx
  src/pages/MyMove/SelectShipmentType.jsx
  src/scenes/MyMove/index.jsx
  src/shared/constants.js
  src/shared/styles/_custom.scss
  src/shared/styles/colors.scss
  src/types/shipment.js
  src/utils/shipmentInfo.js
  src/utils/shipments.js
Labels: ByteSize M&Ms, INTEGRATION

#13780 B-19463-INT after rebase
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/services/order/order_fetcher.go
  src/components/Table/TableQueue.jsx
  src/hooks/queries.js
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.jsx
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.module.scss
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.test.jsx
  src/pages/Office/index.jsx
  src/utils/queues.jsx
Labels: G-Unit, INTEGRATION

#13784 INT-B-21042
  pkg/gen/primev3api/embedded_spec.go
  pkg/gen/primev3messages/create_m_t_o_shipment.go
  pkg/gen/primev3messages/create_p_p_m_shipment.go
  pkg/handlers/primeapiv3/payloads/payload_to_model.go
  src/pages/PrimeUI/Shipment/PrimeUIShipmentCreate.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentCreateForm.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentCreateForm.test.jsx
  swagger-def/prime_v3.yaml
  swagger/prime_v3.yaml
Labels: G-Unit, INTEGRATION
