Repository transcom/mymove, pull requests merged in 2024-10, with the labels that each got.

#13787 INT B-21023 fix typo on dependents included question
  src/components/Office/AddOrdersForm/AddOrdersForm.jsx
  src/components/Office/AddOrdersForm/AddOrdersForm.test.jsx
Labels: INTEGRATION, Go-Rillaz

#13802 B-21500- CM prod datafix
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240930171315_updatePostalCodeToGbloc233BGNC.up.sql
Labels: Mountain Movers, INTEGRATION

#13783 INT B-19044 remix electric boogaloo
  eslint-plugin-ato/no-unapproved-annotation.js
  playwright/tests/office/servicescounseling/servicesCounselingFlows.spec.js
  src/components/Office/DefinitionLists/PPMShipmentInfoList.jsx
  src/components/Office/DefinitionLists/ShipmentInfoList.jsx
  src/components/Office/ReviewSITExtensionModal/ConfirmCustomerExpenseModal/ConfirmCustomerExpenseModal.test.jsx
  src/components/Office/ServicesCounselingTabNav/ServicesCounselingTabNav.jsx
  src/components/Office/ServicesCounselingTabNav/ServicesCounselingTabNav.test.jsx
  src/components/Office/TXOTabNav/TXOTabNav.jsx
  src/pages/Office/MoveDetails/MoveDetails.jsx
  src/pages/Office/MoveDetails/MoveDetails.test.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.test.jsx
  src/pages/Office/ServicesCounselingMoveInfo/ServicesCounselingMoveInfo.jsx
  src/pages/Office/ServicesCounselingMoveInfo/ServicesCounselingTab.module.scss
  src/pages/Office/TXOMoveInfo/TXOMoveInfo.jsx
Labels: Mountain Movers, INTEGRATION

#13788 INT B-20976 customer state management to avoid duplicate moves
  src/pages/MyMove/AddOrders.jsx
  src/pages/MyMove/AddOrders.test.jsx
  src/pages/MyMove/Home/index.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesLandingPage.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesLandingPage.test.jsx
  src/store/entities/selectors.js
  src/store/entities/selectors.test.js
  src/store/general/action.test.js
  src/store/general/actions.js
  src/store/general/reducer.js
  src/store/general/reducer.test.js
Labels: Mountain Movers, INTEGRATION

#13808 B-19044 I-13359 fix
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
  src/pages/Office/ServicesCounselingMoveInfo/ServicesCounselingMoveInfo.jsx
Labels: Mountain Movers, INTEGRATION

#13807 Fix SIT testharness and e2e test
  pkg/testdatagen/testharness/make_move.go
  playwright/tests/office/txo/sitUpdates.spec.js
Labels: Mountain Movers, INTEGRATION

#13814 INT B-19044 annotation test update
  eslint-plugin-ato/tests/no-unapproved-annotation.test.js
Labels: Mountain Movers, INTEGRATION

#13817 B-21426: Add is_oconus bool column to address INT
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20241001174400_add_is_oconus_column.up.sql
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/address.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/address.go
  pkg/gen/pptasapi/embedded_spec.go
  pkg/gen/pptasmessages/address.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/address.go
  pkg/gen/primev2api/embedded_spec.go
  pkg/gen/primev2messages/address.go
  pkg/gen/primev3api/embedded_spec.go
  pkg/gen/primev3messages/address.go
  pkg/gen/supportapi/embedded_spec.go
  pkg/gen/supportmessages/address.go
  pkg/models/address.go
  swagger-def/definitions/Address.yaml
  swagger-def/support.yaml
  swagger/ghc.yaml
  swagger/internal.yaml
  swagger/pptas.yaml
  swagger/prime.yaml
  swagger/prime_v2.yaml
  swagger/prime_v3.yaml
  swagger/support.yaml
Labels: Mountain Movers, INTEGRATION

#13795 create international rate area lookup
  pkg/models/service_item_param_key.go
  pkg/payment_request/service_param_value_lookups/international_rate_area_lookup.go
  pkg/payment_request/service_param_value_lookups/international_rate_area_lookup_test.go
  pkg/payment_request/service_param_value_lookups/lookup_query_helpers.go
  pkg/payment_request/service_param_value_lookups/lookup_query_helpers_test.go
  pkg/payment_request/service_param_value_lookups/service_param_value_lookups.go
Labels: Mountain Movers, INTEGRATION

#13797 INT B-21485 SC state management to avoid duplicate moves
  src/components/Table/SearchResultsTable.jsx
  src/components/Table/SearchResultsTable.test.jsx
  src/pages/MyMove/AddOrders.jsx
  src/pages/Office/PaymentRequestQueue/PaymentRequestQueue.test.jsx
  src/pages/Office/ServicesCounselingAddOrders/ServicesCounselingAddOrders.jsx
  src/pages/Office/ServicesCounselingAddOrders/ServicesCounselingAddOrders.test.jsx
Labels: Mountain Movers, INTEGRATION

#13811 INT B-20966 - tool-tips-missing-from-SIT-service-items
  src/components/Office/ServiceItemsTable/ResubmittedServiceItemDetails.test.jsx
  src/components/Office/ServiceItemsTable/ServiceItemsTable.jsx
  src/components/Office/ServiceItemsTable/ServiceItemsTable.module.scss
  src/constants/serviceItems.js
  src/constants/sitUpdates.js
  src/pages/PrimeUI/MoveTaskOrder/MoveDetails.test.jsx
  src/pages/PrimeUI/UpdateServiceItems/PrimeUIUpdateDestSITForm.jsx
  src/pages/PrimeUI/UpdateServiceItems/PrimeUIUpdateOriginSITForm.jsx
  src/pages/PrimeUI/UpdateServiceItems/PrimeUIUpdateSitServiceItem.jsx
  src/pages/PrimeUI/UpdateServiceItems/PrimeUpdateSitServiceItem.test.jsx
  src/shared/ToolTip/ToolTip.jsx
  src/shared/ToolTip/ToolTip.module.scss
  src/shared/ToolTip/ToolTip.test.jsx
Labels: ByteSize M&Ms, INTEGRATION

#13781 B 21093 enforce email domain int
  src/components/Office/RequestAccountForm/RequestAccountForm.test.jsx
  src/pages/Office/RequestAccount/RequestAccount.test.jsx
  src/utils/validation.js
Labels: ByteSize M&Ms, INTEGRATION

#13793 INT B-20554 prime sim boat shipment - rebase
  .envrc
  pkg/gen/primev2api/embedded_spec.go
  pkg/gen/primev2messages/create_boat_shipment.go
  pkg/gen/primev3api/embedded_spec.go
  pkg/gen/primev3messages/boat_shipment.go
  pkg/gen/primev3messages/create_boat_shipment.go
  pkg/gen/primev3messages/create_m_t_o_shipment.go
  pkg/gen/primev3messages/m_t_o_shipment_without_service_items.go
  pkg/handlers/primeapiv2/mto_shipment.go
  pkg/handlers/primeapiv3/mto_shipment.go
  pkg/handlers/primeapiv3/mto_shipment_test.go
  pkg/handlers/primeapiv3/payloads/model_to_payload.go
  pkg/handlers/primeapiv3/payloads/model_to_payload_test.go
  pkg/handlers/primeapiv3/payloads/payload_to_model.go
  pkg/handlers/primeapiv3/payloads/payload_to_model_test.go
  pkg/services/move_task_order/move_task_order_fetcher.go
  src/components/PrimeUI/Shipment/Shipment.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentCreate.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentCreateForm.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentCreateForm.test.jsx
  swagger-def/definitions/prime/v2/MTOShipmentWithoutServiceItems.yaml
  swagger-def/definitions/prime/v3/MTOShipmentWithoutServiceItems.yaml
  swagger-def/prime_v2.yaml
  swagger-def/prime_v3.yaml
  swagger/prime_v2.yaml
  swagger/prime_v3.yaml
Labels: ByteSize M&Ms, INTEGRATION

#13804 INT B-192226 mobile home pricing db changes
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240927145659_update_mobile_home_factor.up.sql
Labels: ByteSize M&Ms, INTEGRATION

#13774 B 20978 int show links for documents for DDASIT and DDDSIT
  src/components/Office/ServiceItemDetails/ServiceItemDetails.jsx
  src/components/Office/ServiceItemDetails/ServiceItemDetails.test.jsx
Labels: Scrummy Bears, INTEGRATION

#13819 INT-B-21115
  playwright/tests/my/mymove/onboarding.spec.js
  src/components/Customer/DodInfoForm/DodInfoForm.jsx
  src/components/Customer/DodInfoForm/DodInfoForm.test.jsx
  src/constants/routes.js
  src/containers/requireCustomerState/requireCustomerState.test.jsx
  src/pages/MyMove/ConusOrNot.jsx
  src/pages/MyMove/ConusOrNot.test.jsx
  src/pages/MyMove/Profile/DodInfo.jsx
  src/pages/MyMove/Profile/DodInfo.test.jsx
  src/pages/MyMove/Profile/Name.test.jsx
  src/pages/MyMove/Profile/ValidationCode.jsx
  src/pages/MyMove/Profile/ValidationCode.test.jsx
  src/scenes/MyMove/getWorkflowRoutes.jsx
  src/scenes/MyMove/getWorkflowRoutes.test.js
  src/utils/customer.js
Labels: G-Unit, INTEGRATION

#13779 B-20465-INT - Add Counseling Office Selection to Customer Application
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/create_update_orders.go
  pkg/gen/internalmessages/duty_location_payload.go
  pkg/handlers/internalapi/duty_locations.go
  pkg/handlers/internalapi/orders.go
  playwright/tests/my/mymove/orders.spec.js
  src/components/Customer/OrdersInfoForm/OrdersInfoForm.jsx
  src/components/Customer/OrdersInfoForm/OrdersInfoForm.test.jsx
  src/components/LocationSearchBox/LocationSearchBox.jsx
  src/components/LocationSearchBox/LocationSearchBox.test.jsx
  src/components/form/fields/CloseoutOfficeInput.jsx
  src/components/form/fields/DutyLocationInput.jsx
  src/pages/MyMove/AddOrders.jsx
  src/pages/MyMove/AddOrders.test.jsx
  src/pages/MyMove/Orders.test.jsx
  swagger-def/definitions/DutyLocationPayload.yaml
  swagger-def/internal.yaml
  swagger/internal.yaml
Labels: G-Unit, INTEGRATION

#13782 B 20529 INT add save retrieve and filter capability for assigned column sc
  pkg/factory/move_factory.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/queues/get_moves_queue_parameters.go
  pkg/gen/ghcapi/ghcoperations/queues/get_services_counseling_queue_parameters.go
  pkg/gen/ghcapi/ghcoperations/queues/get_services_counseling_queue_urlbuilder.go
  pkg/gen/ghcmessages/assigned_office_user.go
  pkg/gen/ghcmessages/queue_move.go
  pkg/gen/ghcmessages/queue_moves_result.go
  pkg/gen/ghcmessages/queue_payment_request.go
  pkg/gen/ghcmessages/queue_payment_requests_result.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/move_test.go
  pkg/handlers/ghcapi/mto_service_items_test.go
  pkg/handlers/ghcapi/queues.go
  pkg/handlers/ghcapi/queues_test.go
  pkg/services/order.go
  pkg/services/order/order_fetcher.go
  pkg/services/order/order_fetcher_test.go
  src/components/Table/TableQueue.jsx
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.jsx
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.test.jsx
  src/pages/Office/index.jsx
  src/services/ghcApi.js
  src/utils/queues.jsx
  src/utils/queues.test.jsx
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: G-Unit, INTEGRATION

#13828 INT-B-21514
  pkg/services/pptas_report/pptas_report_list_fetcher.go
Labels: G-Unit, INTEGRATION

#13809 Fix SIT testharness and e2e test
  pkg/testdatagen/testharness/make_move.go
  playwright/tests/office/txo/sitUpdates.spec.js
Labels: Mountain Movers, MAIN

#13821 B-21514 pptas report list fetcher now more payment request statuses
  pkg/services/pptas_report/pptas_report_list_fetcher.go
Labels: G-Unit, MAIN

#13826 B-20617: SC TOO Creating Mobile Home Shipment and Shipment Card Display
  pkg/services/move/move_router.go
  playwright/tests/office/servicescounseling/servicesCounselingMobileHome.spec.js
  playwright/tests/office/txo/tooFlowsMobileHome.spec.js
  src/components/Office/DefinitionLists/MobileHomeShipmentInfoList.jsx
  src/components/Office/DefinitionLists/MobileHomeShipmentInfoList.stories.jsx
  src/components/Office/DefinitionLists/MobileHomeShipmentInfoList.test.jsx
  src/components/Office/DefinitionLists/ShipmentInfoListSelector.jsx
  src/components/Office/ShipmentForm/MobileHomeShipmentForm/MobileHomeShipmentForm.jsx
  src/components/Office/ShipmentForm/MobileHomeShipmentForm/MobileHomeShipmentForm.module.scss
  src/components/Office/ShipmentForm/MobileHomeShipmentForm/mobileHomeShipmentSchema.js
  src/components/Office/ShipmentForm/ShipmentForm.jsx
  src/components/Office/ShipmentForm/ShipmentForm.test.jsx
  src/components/Office/ShipmentFormRemarks/ShipmentFormRemarks.jsx
  src/pages/Office/AddShipment/AddShipment.jsx
  src/pages/Office/MoveDetails/MoveDetails.jsx
  src/pages/Office/ServicesCounselingAddShipment/ServicesCounselingAddShipment.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
  src/shared/constants.js
  src/utils/formatMtoShipment.js
Labels: ByteSize M&Ms, INTEGRATION

#13806 INT B-21117 boat shipment db changes
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20241001144741_update_boat_factor.up.sql
Labels: ByteSize M&Ms, INTEGRATION

#13771 B-21436: Allow AK to be entered as a state and Enable Alaska FF
  .circleci/config.yml
  .envrc
  config/env/demo.app-client-tls.env
  config/env/demo.app.env
  config/env/exp.app-client-tls.env
  config/env/exp.app.env
  config/env/loadtest.app-client-tls.env
  config/env/loadtest.app.env
  config/env/prd.app-client-tls.env
  config/env/prd.app.env
  config/env/stg.app-client-tls.env
  config/env/stg.app.env
  config/flipt/storage/development.features.yaml
  src/components/Customer/MtoShipmentForm/MtoShipmentForm.test.jsx
  src/components/Customer/PPM/Closeout/AboutForm/AboutForm.test.jsx
  src/components/Office/EditFacilityInfoModal/EditFacilityInfoModal.jsx
  src/components/Office/ShipmentDetails/ShipmentDetailsSidebar.jsx
  src/constants/states.js
  src/pages/MyMove/Boat/BoatShipmentLocationInfo/BoatShipmentLocationInfo.test.jsx
  src/pages/MyMove/MobileHome/MobileHomeShipmentLocationInfo/MobileHomeShipmentLocationInfo.test.jsx
  src/pages/MyMove/PPM/Closeout/About/About.test.jsx
  src/pages/MyMove/Profile/BackupAddress.test.jsx
  src/pages/MyMove/Profile/EditContactInfo.test.jsx
  src/pages/MyMove/Profile/ResidentialAddress.test.jsx
  src/pages/Office/CustomerOnboarding/CreateCustomerForm.test.jsx
  src/pages/Office/ServicesCounselingEditShipmentDetails/ServicesCounselingEditShipmentDetails.test.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentCreate.test.jsx
  src/utils/validation.js
Labels: Mountain Movers, INTEGRATION

#13789 B 20757 int
  pkg/handlers/internalapi/mto_shipment.go
  pkg/notifications/constants.go
  pkg/payment_request/service_param_value_lookups/service_param_value_lookups.go
  pkg/route/dtod_zip5_distance.go
  pkg/route/dtod_zip5_distance_test.go
  src/pages/MyMove/PPM/Booking/EstimatedWeightsProGear/EstimatedWeightsProGear.jsx
  src/pages/MyMove/PPM/Booking/EstimatedWeightsProGear/EstimatedWeightsProGear.test.jsx
  src/shared/constants.js
Labels: Scrummy Bears, INTEGRATION

#13836 B 20977 usmc moves search int
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload_test.go
Labels: ByteSize M&Ms, INTEGRATION

#13580 B-19463 add assigned user col to SC queue; add dropdown select to row
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/services/order/order_fetcher.go
  src/components/Table/TableQueue.jsx
  src/hooks/queries.js
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.jsx
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.module.scss
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.test.jsx
  src/pages/Office/index.jsx
  src/utils/queues.jsx
Labels: G-Unit, MAIN

#13832 B-21426: Add is_oconus bool column to addresses MAIN
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20241001174400_add_is_oconus_column.up.sql
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/address.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/address.go
  pkg/gen/pptasapi/embedded_spec.go
  pkg/gen/pptasmessages/address.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/address.go
  pkg/gen/primev2api/embedded_spec.go
  pkg/gen/primev2messages/address.go
  pkg/gen/primev3api/embedded_spec.go
  pkg/gen/primev3messages/address.go
  pkg/gen/supportapi/embedded_spec.go
  pkg/gen/supportmessages/address.go
  pkg/models/address.go
  swagger-def/definitions/Address.yaml
  swagger-def/support.yaml
  swagger/ghc.yaml
  swagger/internal.yaml
  swagger/pptas.yaml
  swagger/prime.yaml
  swagger/prime_v2.yaml
  swagger/prime_v3.yaml
  swagger/support.yaml
Labels: Mountain Movers, MAIN

#13818 B 21428 add market code to shipments int
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20241001193619_market-code-enum.up.sql
  pkg/models/mto_shipments.go
  pkg/models/mto_shipments_test.go
Labels: Mountain Movers, INTEGRATION

#13835 B-20532-INT TOO Queue assignment
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/queues/get_moves_queue_parameters.go
  pkg/gen/ghcapi/ghcoperations/queues/get_moves_queue_urlbuilder.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/queues.go
  pkg/handlers/ghcapi/queues_test.go
  pkg/services/mocks/OrderFetcher.go
  pkg/services/order.go
  pkg/services/order/order_fetcher.go
  pkg/services/order/order_fetcher_test.go
  src/pages/Office/MoveQueue/MoveQueue.jsx
  src/pages/Office/MoveQueue/MoveQueue.test.jsx
  src/pages/Office/index.jsx
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: G-Unit, INTEGRATION

#13852 B 21163 int
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20241002151527_add_transportation_offices_AK_HI.up.sql
Labels: G-Unit, INTEGRATION

#13830 Int b 21409 retiree separatee email updates move submitted
  pkg/assets/notifications/templates/move_submitted_template.html
  pkg/assets/notifications/templates/move_submitted_template.txt
  pkg/notifications/move_submitted.go
  pkg/notifications/move_submitted_test.go
Labels: INTEGRATION, Go-Rillaz

#13792 MAIN B-20976 customer state management to avoid duplicate moves
  src/pages/MyMove/AddOrders.jsx
  src/pages/MyMove/AddOrders.test.jsx
  src/pages/MyMove/Home/index.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesLandingPage.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesLandingPage.test.jsx
  src/store/entities/selectors.js
  src/store/entities/selectors.test.js
  src/store/general/action.test.js
  src/store/general/actions.js
  src/store/general/reducer.js
  src/store/general/reducer.test.js
Labels: Mountain Movers, MAIN

#13798 MAIN B-21485 SC state management to avoid duplicate moves
  src/components/Table/SearchResultsTable.jsx
  src/components/Table/SearchResultsTable.test.jsx
  src/pages/MyMove/AddOrders.jsx
  src/pages/Office/PaymentRequestQueue/PaymentRequestQueue.test.jsx
  src/pages/Office/ServicesCounselingAddOrders/ServicesCounselingAddOrders.jsx
  src/pages/Office/ServicesCounselingAddOrders/ServicesCounselingAddOrders.test.jsx
Labels: Mountain Movers, MAIN

#13837 B-21362 & B-212363 UB Shipment DB/Model Updates/Customer API - INT
  .circleci/config.yml
  .envrc
  config/env/demo.app-client-tls.env
  config/env/demo.app.env
  config/env/exp.app-client-tls.env
  config/env/exp.app.env
  config/env/loadtest.app-client-tls.env
  config/env/loadtest.app.env
  config/env/prd.app-client-tls.env
  config/env/prd.app.env
  config/env/stg.app-client-tls.env
  config/env/stg.app.env
  config/flipt/storage/development.features.yaml
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20241002170242_add_ub_shipment_type.up.sql
  pkg/factory/mto_shipment_factory_test.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/m_t_o_shipment_type.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/m_t_o_shipment_type.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/m_t_o_shipment_type.go
  pkg/gen/primev2api/embedded_spec.go
  pkg/gen/primev2messages/m_t_o_shipment_type.go
  pkg/gen/primev3api/embedded_spec.go
  pkg/gen/primev3messages/m_t_o_shipment_type.go
  pkg/gen/supportapi/embedded_spec.go
  pkg/gen/supportmessages/m_t_o_shipment_type.go
  pkg/models/mto_shipments.go
  pkg/paperwork/evaluation_report_form_creator.go
  pkg/payment_request/service_param_value_lookups/weight_billed_lookup.go
  pkg/payment_request/service_param_value_lookups/weight_billed_lookup_test.go
  pkg/services/mto_shipment/mto_shipment_creator.go
  pkg/services/mto_shipment/mto_shipment_creator_test.go
  pkg/services/mto_shipment/mto_shipment_updater_test.go
  pkg/services/mto_shipment/rules_test.go
  pkg/services/mto_shipment/shipment_deleter_test.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet_test.go
  swagger-def/definitions/MTOShipmentType.yaml
  swagger-def/definitions/prime/MTOShipmentType.yaml
  swagger-def/definitions/prime/v2/MTOShipmentType.yaml
  swagger-def/definitions/prime/v3/MTOShipmentType.yaml
  swagger-def/internal.yaml
  swagger-def/support.yaml
  swagger/ghc.yaml
  swagger/internal.yaml
  swagger/prime.yaml
  swagger/prime_v2.yaml
  swagger/prime_v3.yaml
  swagger/support.yaml
Labels: Mountain Movers, INTEGRATION

#13742 B 21078 move history ppm cleanup
  src/constants/MoveHistory/EventTemplates/UpdateMTOShipment/patchMTOShipment.jsx
  src/constants/MoveHistory/EventTemplates/UpdateMTOShipment/patchMTOShipment.test.jsx
  src/constants/MoveHistory/EventTemplates/UploadAdditionalDocuments/uploadAdditionalDocuments.jsx
  src/constants/MoveHistory/EventTemplates/UploadAdditionalDocuments/uploadAdditionalDocuments.test.jsx
  src/constants/MoveHistory/EventTemplates/index.js
  src/constants/MoveHistory/UIDisplay/Operations.js
Labels: G-Unit, MAIN

#13820 B 21115
  playwright/tests/my/mymove/onboarding.spec.js
  src/components/Customer/DodInfoForm/DodInfoForm.jsx
  src/components/Customer/DodInfoForm/DodInfoForm.test.jsx
  src/constants/routes.js
  src/containers/requireCustomerState/requireCustomerState.test.jsx
  src/pages/MyMove/ConusOrNot.jsx
  src/pages/MyMove/ConusOrNot.test.jsx
  src/pages/MyMove/Profile/DodInfo.jsx
  src/pages/MyMove/Profile/DodInfo.test.jsx
  src/pages/MyMove/Profile/Name.test.jsx
  src/pages/MyMove/Profile/ValidationCode.jsx
  src/pages/MyMove/Profile/ValidationCode.test.jsx
  src/scenes/MyMove/getWorkflowRoutes.jsx
  src/scenes/MyMove/getWorkflowRoutes.test.js
  src/utils/customer.js
Labels: G-Unit, MAIN

#13829 INT B-21056 Improve PPM Address Wording
  src/components/Office/ShipmentForm/ShipmentForm.jsx
  src/components/Office/ShipmentForm/ShipmentForm.test.jsx
Labels: INTEGRATION, Go-Rillaz

#13847 INT B-19044 third times the charm
  src/components/Office/ServicesCounselingTabNav/ServicesCounselingTabNav.jsx
  src/components/Office/ServicesCounselingTabNav/ServicesCounselingTabNav.test.jsx
Labels: Mountain Movers, INTEGRATION

#13831 B 21328 int
  playwright/tests/office/txo/tioFlows.spec.js
  playwright/tests/office/txo/tioUpdateMaxBillableWeight.spec.js
  playwright/tests/office/txo/tooFlows.spec.js
  src/components/Office/BillableWeight/BillableWeightCard/BillableWeightCard.jsx
  src/components/Office/BillableWeight/BillableWeightCard/BillableWeightCard.test.jsx
  src/pages/Office/MovePaymentRequests/MovePaymentRequests.test.jsx
Labels: Scrummy Bears, INTEGRATION

#13825 B 21213 int
  pkg/factory/ppm_shipment_factory.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/queues.go
  pkg/handlers/ghcapi/queues_test.go
  pkg/services/order/order_fetcher.go
  pkg/services/order/order_fetcher_test.go
  pkg/testdatagen/scenario/shared.go
  playwright/tests/office/servicescounseling/servicesCounselingQueueFilters.spec.js
  src/constants/queues.js
Labels: Scrummy Bears, INTEGRATION

#13815 B-21489 int Update schema to accommodate multiple transportation offices for office user
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240930224757_add_transportation_office_assignments.up.sql
  pkg/models/transportation_office_assignments.go
Labels: Scrummy Bears, INTEGRATION

#13693 20616 add mobile shipment customer flows main
  pkg/handlers/internalapi/moves.go
  pkg/services/orchestrators/shipment/shipment_updater.go
  src/components/Customer/MobileHomeShipment/MobileHomeShipmentForm/MobileHomeShipmentForm.jsx
  src/components/Customer/MobileHomeShipment/MobileHomeShipmentForm/MobileHomeShipmentForm.module.scss
  src/components/Customer/MobileHomeShipment/MobileHomeShipmentForm/MobileHomeShipmentForm.stories.jsx
  src/components/Customer/MobileHomeShipment/MobileHomeShipmentForm/MobileHomeShipmentForm.test.jsx
  src/components/Customer/MtoShipmentForm/MtoShipmentForm.jsx
  src/components/Customer/MtoShipmentForm/getShipmentOptions.js
  src/components/Customer/Review/ShipmentCard/MobileHomeShipmentCard/MobileHomeShipmentCard.jsx
  src/components/Customer/Review/ShipmentCard/MobileHomeShipmentCard/MobileHomeShipmentCard.test.jsx
  src/components/Customer/Review/Summary/Summary.jsx
  src/components/Customer/modals/BoatAndMobileInfoModal/BoatAndMobileInfoModal.jsx
  src/components/Office/ShipmentContainer/ShipmentContainer.jsx
  src/components/ShipmentList/ShipmentList.jsx
  src/components/ShipmentList/ShipmentList.module.scss
  src/components/ShipmentTag/ShipmentTag.module.scss
  src/constants/routes.js
  src/constants/shipments.js
  src/content/shipments.js
  src/pages/MyMove/CreateOrEditMtoShipment.jsx
  src/pages/MyMove/Home/MoveHome.jsx
  src/pages/MyMove/MobileHome/MobileHomeShipmentCreate/MobileHomeShipmentCreate.jsx
  src/pages/MyMove/MobileHome/MobileHomeShipmentCreate/MobileHomeShipmentCreate.test.jsx
  src/pages/MyMove/MobileHome/MobileHomeShipmentLocationInfo/MobileHomeShipmentLocationInfo.jsx
  src/pages/MyMove/MobileHome/MobileHomeShipmentLocationInfo/MobileHomeShipmentLocationInfo.test.jsx
  src/pages/MyMove/SelectShipmentType.jsx
  src/scenes/MyMove/index.jsx
  src/shared/constants.js
  src/shared/styles/_custom.scss
  src/shared/styles/colors.scss
  src/types/shipment.js
  src/utils/shipmentInfo.js
  src/utils/shipments.js
Labels: ByteSize M&Ms, MAIN

#13824 B 21437 int
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/affiliation.go
  pkg/gen/ghcmessages/department_indicator.go
  pkg/gen/ghcmessages/fetch_line_of_accounting_payload.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/affiliation.go
  pkg/gen/ordersapi/embedded_spec.go
  pkg/gen/ordersmessages/affiliation.go
  pkg/gen/pptasapi/embedded_spec.go
  pkg/gen/pptasmessages/affiliation.go
  pkg/handlers/ghcapi/lines_of_accounting.go
  pkg/handlers/ghcapi/lines_of_accounting_test.go
  pkg/models/order.go
  pkg/models/service_member.go
  pkg/services/invoice/ghc_payment_request_invoice_generator.go
  pkg/services/invoice/ghc_payment_request_invoice_generator_test.go
  pkg/services/line_of_accounting.go
  pkg/services/line_of_accounting/line_of_accounting_fetcher.go
  pkg/services/line_of_accounting/line_of_accounting_fetcher_test.go
  pkg/services/mocks/LineOfAccountingFetcher.go
  pkg/services/mocks/TransportationAccountingCodeFetcher.go
  pkg/services/pptas_report/pptas_report_list_fetcher.go
  pkg/services/transportation_accounting_code.go
  pkg/services/transportation_accounting_code/transportation_accounting_code_fetcher.go
  pkg/services/transportation_accounting_code/transportation_accounting_code_fetcher_test.go
  src/pages/Office/Orders/Orders.jsx
  src/pages/Office/ServicesCounselingOrders/ServicesCounselingOrders.jsx
  src/services/ghcApi.js
  swagger-def/definitions/Affiliation.yaml
  swagger-def/definitions/DepartmentIndicator.yaml
  swagger-def/ghc.yaml
  swagger/ghc.yaml
  swagger/internal.yaml
  swagger/orders.yaml
  swagger/pptas.yaml
Labels: Scrummy Bears, INTEGRATION

#13816 INT REBASE B-20452 - Office User - Edit, Submit, Approve, Delete Boat Shipment
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/testharness/dispatch.go
  pkg/testdatagen/testharness/make_move.go
  playwright/tests/my/mymove/boat.spec.js
  playwright/tests/office/servicescounseling/servicesCounselingBoat.spec.js
  playwright/tests/office/txo/tooFlowsBoat.spec.js
  playwright/tests/utils/testharness.js
  src/components/Customer/BoatShipment/BoatShipmentForm/BoatShipmentForm.jsx
  src/components/Customer/Review/ShipmentCard/BoatShipmentCard/BoatShipmentCard.jsx
  src/components/Office/DefinitionLists/ShipmentInfoListSelector.jsx
  src/components/Office/ShipmentContainer/ShipmentContainer.jsx
  src/components/Office/ShipmentDisplay/ShipmentDisplay.jsx
  src/components/Office/ShipmentForm/BoatShipmentForm/BoatShipmentForm.jsx
  src/components/Office/ShipmentForm/ShipmentForm.jsx
  src/components/Office/ShipmentFormRemarks/ShipmentFormRemarks.jsx
  src/components/Office/ShipmentServiceItemsTable/ShipmentServiceItemsTable.jsx
  src/constants/shipments.js
  src/pages/MyMove/Home/MoveHome.jsx
  src/pages/MyMove/Home/index.jsx
  src/pages/MyMove/Review/Review.jsx
  src/utils/formatMtoShipment.js
Labels: ByteSize M&Ms, INTEGRATION

#13846 INT B-21162 Destination Address Street 1 OPTIONAL
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/create_p_p_m_shipment.go
  pkg/gen/ghcmessages/p_p_m_destination_address.go
  pkg/gen/ghcmessages/update_p_p_m_shipment.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/create_p_p_m_shipment.go
  pkg/gen/internalmessages/p_p_m_destination_address.go
  pkg/gen/internalmessages/update_p_p_m_shipment.go
  pkg/gen/primev3api/embedded_spec.go
  pkg/gen/primev3messages/create_p_p_m_shipment.go
  pkg/gen/primev3messages/p_p_m_destination_address.go
  pkg/gen/primev3messages/p_p_m_shipment.go
  pkg/gen/primev3messages/update_p_p_m_shipment.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload_test.go
  pkg/handlers/ghcapi/internal/payloads/payload_to_model.go
  pkg/handlers/ghcapi/internal/payloads/payload_to_model_test.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/handlers/internalapi/internal/payloads/model_to_payload.go
  pkg/handlers/internalapi/internal/payloads/payload_to_model.go
  pkg/handlers/internalapi/internal/payloads/payload_to_model_test.go
  pkg/handlers/internalapi/internal/payloads/payloads_test.go
  pkg/handlers/internalapi/mto_shipment_test.go
  pkg/handlers/primeapiv3/mto_shipment_test.go
  pkg/handlers/primeapiv3/payloads/model_to_payload.go
  pkg/handlers/primeapiv3/payloads/model_to_payload_test.go
  pkg/handlers/primeapiv3/payloads/payload_to_model.go
  pkg/handlers/primeapiv3/payloads/payload_to_model_test.go
  pkg/models/address.go
  src/components/Customer/PPM/Booking/DateAndLocationForm/DateAndLocationForm.jsx
  src/components/Customer/PPM/Booking/DateAndLocationForm/DateAndLocationForm.test.jsx
  src/components/Customer/PPM/Closeout/AboutForm/AboutForm.test.jsx
  src/components/Office/ShipmentForm/ShipmentForm.jsx
  src/components/Office/ShipmentForm/ShipmentForm.test.jsx
  src/components/Office/ShipmentForm/ppmShipmentSchema.js
  src/components/form/AddressFields/AddressFields.jsx
  src/pages/Office/ServicesCounselingEditShipmentDetails/ServicesCounselingEditShipmentDetails.test.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentCreate.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentCreate.test.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentCreateForm.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentCreateForm.test.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdate.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdate.test.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdatePPMForm.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdatePPMForm.test.jsx
  src/utils/validation.js
  swagger-def/definitions/PPMDestinationAddress.yaml
  swagger-def/definitions/prime/v3/PPMShipment.yaml
  swagger-def/ghc.yaml
  swagger-def/internal.yaml
  swagger-def/prime_v3.yaml
  swagger/ghc.yaml
  swagger/internal.yaml
  swagger/prime_v3.yaml
Labels: Scrummy Bears, INTEGRATION

#13866 INT B-20627 Fix circleci tests and bump dependency
  go.mod
  go.sum
  pkg/handlers/routing/primeapi_test/telemetry_test.go
  pkg/telemetry/middleware_test.go
Labels: INTEGRATION

#13776 B19795-INT-REBASE-doc viewer doc title change
  pkg/handlers/internalapi/uploads.go
  pkg/services/payment_request/upload_creator.go
  playwright/tests/my/milmove/ppms/customerPpmTestFixture.js
  src/components/DocumentViewer/Menu/Menu.module.scss
  src/components/DocumentViewerFileManager/DocumentViewerFileManager.jsx
  src/pages/MyMove/AdditionalDocuments/AdditionalDocuments.jsx
  src/pages/MyMove/EditOrders.jsx
  src/pages/MyMove/PPM/Closeout/Expenses/Expenses.jsx
  src/pages/MyMove/PPM/Closeout/ProGear/ProGear.jsx
  src/pages/MyMove/PPM/Closeout/WeightTickets/WeightTickets.jsx
  src/pages/MyMove/UploadOrders.jsx
Labels: ByteSize M&Ms, INTEGRATION

#13875 B 20619 prime create mobile home int REBASE
  pkg/gen/primev2api/embedded_spec.go
  pkg/gen/primev2messages/create_boat_shipment.go
  pkg/gen/primev2messages/create_mobile_home_shipment.go
  pkg/gen/primev3api/embedded_spec.go
  pkg/gen/primev3messages/create_boat_shipment.go
  pkg/gen/primev3messages/create_m_t_o_shipment.go
  pkg/gen/primev3messages/create_mobile_home_shipment.go
  pkg/gen/primev3messages/m_t_o_shipment_without_service_items.go
  pkg/gen/primev3messages/mobile_home.go
  pkg/handlers/primeapi/move_task_order.go
  pkg/handlers/primeapiv2/move_task_order.go
  pkg/handlers/primeapiv2/mto_shipment.go
  pkg/handlers/primeapiv3/move_task_order.go
  pkg/handlers/primeapiv3/mto_shipment.go
  pkg/handlers/primeapiv3/payloads/model_to_payload.go
  pkg/handlers/primeapiv3/payloads/payload_to_model.go
  pkg/services/move_task_order/move_task_order_fetcher.go
  src/components/PrimeUI/Shipment/Shipment.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentCreate.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentCreateForm.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentCreateForm.test.jsx
  src/styles/form.module.scss
  swagger-def/definitions/prime/v2/MTOShipmentWithoutServiceItems.yaml
  swagger-def/definitions/prime/v3/MTOShipmentWithoutServiceItems.yaml
  swagger-def/prime_v2.yaml
  swagger-def/prime_v3.yaml
  swagger/prime_v2.yaml
  swagger/prime_v3.yaml
Labels: ByteSize M&Ms, MAIN

#13822 B 21077 move shipment button int
  src/components/Office/RequestedShipments/ApprovedRequestedShipments.jsx
  src/components/Office/RequestedShipments/RequestedShipments.module.scss
  src/components/Office/RequestedShipments/RequestedShipments.test.jsx
  src/components/Office/RequestedShipments/SubmittedRequestedShipments.jsx
  src/pages/Office/MoveDetails/MoveDetails.jsx
  src/pages/Office/MoveDetails/MoveDetails.test.jsx
  src/pages/Office/TXOMoveInfo/TXOTab.module.scss
Labels: ByteSize M&Ms, INTEGRATION

#13859 B 20757 INT - V2
  pkg/handlers/ghcapi/mto_shipment.go
  pkg/handlers/internalapi/mto_shipment.go
  pkg/models/us_post_region_city.go
  pkg/services/address/address_creator_test.go
  pkg/services/address/address_updater_test.go
  pkg/services/ppmshipment/ppm_shipment_creator.go
  src/components/Office/ShipmentForm/ShipmentForm.jsx
  src/components/Office/ShipmentForm/ShipmentForm.test.jsx
  src/pages/MyMove/PPM/Booking/DateAndLocation/DateAndLocation.jsx
  src/pages/MyMove/PPM/Booking/DateAndLocation/DateAndLocation.test.jsx
  src/pages/MyMove/PPM/Booking/EstimatedWeightsProGear/EstimatedWeightsProGear.jsx
Labels: Scrummy Bears, INTEGRATION

#13878 B-21365 Customer UB Shipment Card - INT
  src/components/Customer/Home/Step/Step.stories.jsx
  src/components/Customer/MtoShipmentForm/MtoShipmentForm.jsx
  src/components/Customer/MtoShipmentForm/MtoShipmentForm.stories.jsx
  src/components/Customer/MtoShipmentForm/MtoShipmentForm.test.jsx
  src/components/Customer/MtoShipmentForm/getShipmentOptions.js
  src/components/Customer/Review/ShipmentCard/HHGShipmentCard/HHGShipmentCard.test.jsx
  src/components/Customer/Review/Summary/Summary.jsx
  src/components/Customer/Review/Summary/Summary.test.jsx
  src/components/Office/ShipmentContainer/ShipmentContainer.jsx
  src/components/Office/ShipmentContainer/ShipmentContainer.test.jsx
  src/components/ShipmentList/ShipmentList.jsx
  src/components/ShipmentList/ShipmentList.module.scss
  src/components/ShipmentList/ShipmentList.test.jsx
  src/constants/shipments.js
  src/content/shipments.js
  src/shared/constants.js
Labels: Mountain Movers, INTEGRATION

#13885 B20884-INT2-fix prime weight tool tip
  src/components/ShipmentList/ShipmentList.jsx
  src/components/ShipmentList/ShipmentList.test.jsx
  src/shared/ToolTip/ToolTip.jsx
  src/shared/ToolTip/ToolTip.test.jsx
Labels: ByteSize M&Ms, INTEGRATION

#13845 Int b 20975 too submits mto and receives incorrect validation
  src/components/Office/AddOrdersForm/AddOrdersForm.jsx
  src/components/Office/AddOrdersForm/AddOrdersForm.test.jsx
  src/components/Office/RequestedShipments/RequestedShipments.test.jsx
  src/components/Office/RequestedShipments/SubmittedRequestedShipments.jsx
  src/pages/Office/CustomerOnboarding/CreateCustomerForm.jsx
  src/pages/Office/CustomerOnboarding/CreateCustomerForm.test.jsx
Labels: INTEGRATION, Go-Rillaz

#13877 INT B-21429 and B-21431 combo for populating shipment market code
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20241008212243_populate_market_code_on_shipments_table.up.sql
  pkg/factory/address_factory.go
  pkg/factory/mto_shipment_factory.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/m_t_o_shipment.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/m_t_o_shipment.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/m_t_o_shipment_without_service_items.go
  pkg/gen/primev2api/embedded_spec.go
  pkg/gen/primev2messages/m_t_o_shipment_without_service_items.go
  pkg/gen/primev3api/embedded_spec.go
  pkg/gen/primev3messages/m_t_o_shipment_without_service_items.go
  pkg/gen/supportapi/embedded_spec.go
  pkg/gen/supportmessages/m_t_o_shipment.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload_test.go
  pkg/handlers/internalapi/internal/payloads/model_to_payload.go
  pkg/handlers/internalapi/internal/payloads/model_to_payload_test.go
  pkg/handlers/primeapi/mto_service_item_test.go
  pkg/handlers/primeapi/payloads/model_to_payload.go
  pkg/handlers/primeapi/payloads/model_to_payload_test.go
  pkg/handlers/primeapiv2/payloads/model_to_payload.go
  pkg/handlers/primeapiv2/payloads/model_to_payload_test.go
  pkg/handlers/primeapiv3/payloads/model_to_payload.go
  pkg/handlers/primeapiv3/payloads/model_to_payload_test.go
  pkg/models/mto_shipments.go
  pkg/models/mto_shipments_test.go
  pkg/services/address/address_creator.go
  pkg/services/address/address_creator_test.go
  pkg/services/address/address_updater.go
  pkg/services/mto_shipment/mto_shipment_creator.go
  pkg/services/mto_shipment/mto_shipment_creator_test.go
  pkg/services/mto_shipment/mto_shipment_updater.go
  pkg/services/mto_shipment/mto_shipment_updater_test.go
  pkg/services/orchestrators/shipment/shipment_creator.go
  pkg/services/ppmshipment/ppm_shipment_creator.go
  pkg/services/ppmshipment/ppm_shipment_creator_test.go
  pkg/services/ppmshipment/ppm_shipment_updater_test.go
  pkg/services/shipment_address_update/shipment_address_update_requester.go
  pkg/services/shipment_address_update/shipment_address_update_requester_test.go
  pkg/testdatagen/make_mto_shipment.go
  swagger-def/definitions/MTOShipment.yaml
  swagger-def/definitions/prime/MTOShipmentWithoutServiceItems.yaml
  swagger-def/definitions/prime/v2/MTOShipmentWithoutServiceItems.yaml
  swagger-def/definitions/prime/v3/MTOShipmentWithoutServiceItems.yaml
  swagger-def/internal.yaml
  swagger-def/support.yaml
  swagger/ghc.yaml
  swagger/internal.yaml
  swagger/prime.yaml
  swagger/prime_v2.yaml
  swagger/prime_v3.yaml
  swagger/support.yaml
Labels: Mountain Movers, INTEGRATION

#13887 B 21500 cm datafix
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240930171315_updatePostalCodeToGbloc233BGNC.up.sql
Labels: Mountain Movers, MAIN

#13888 B-21428 Add market code to shipments main
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20241001193619_market-code-enum.up.sql
  pkg/models/mto_shipments.go
  pkg/models/mto_shipments_test.go
Labels: Mountain Movers, MAIN, database

#13883 B-21436: Allow AK To Be Entered and FF
  .circleci/config.yml
  .envrc
  config/env/demo.app-client-tls.env
  config/env/demo.app.env
  config/env/exp.app-client-tls.env
  config/env/exp.app.env
  config/env/loadtest.app-client-tls.env
  config/env/loadtest.app.env
  config/env/prd.app-client-tls.env
  config/env/prd.app.env
  config/env/stg.app-client-tls.env
  config/env/stg.app.env
  config/flipt/storage/development.features.yaml
  src/components/Customer/MtoShipmentForm/MtoShipmentForm.test.jsx
  src/components/Customer/PPM/Closeout/AboutForm/AboutForm.test.jsx
  src/components/Office/EditFacilityInfoModal/EditFacilityInfoModal.jsx
  src/components/Office/ShipmentDetails/ShipmentDetailsSidebar.jsx
  src/constants/states.js
  src/pages/MyMove/Boat/BoatShipmentLocationInfo/BoatShipmentLocationInfo.test.jsx
  src/pages/MyMove/MobileHome/MobileHomeShipmentLocationInfo/MobileHomeShipmentLocationInfo.test.jsx
  src/pages/MyMove/PPM/Closeout/About/About.test.jsx
  src/pages/MyMove/Profile/BackupAddress.test.jsx
  src/pages/MyMove/Profile/EditContactInfo.test.jsx
  src/pages/MyMove/Profile/ResidentialAddress.test.jsx
  src/pages/Office/CustomerOnboarding/CreateCustomerForm.test.jsx
  src/pages/Office/ServicesCounselingEditShipmentDetails/ServicesCounselingEditShipmentDetails.test.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentCreate.test.jsx
  src/utils/validation.js
Labels: Mountain Movers, MAIN

#13886 B 20654 m25 int
  cmd/generate-payment-request-edi/main.go
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20241007162933_addPaymentRequestEdiFiles.up.sql
  pkg/gen/adminapi/adminoperations/mymove_api.go
  pkg/gen/adminapi/adminoperations/payment_request_syncada_file/payment_request_syncada_file.go
  pkg/gen/adminapi/adminoperations/payment_request_syncada_file/payment_request_syncada_file_parameters.go
  pkg/gen/adminapi/adminoperations/payment_request_syncada_file/payment_request_syncada_file_responses.go
  pkg/gen/adminapi/adminoperations/payment_request_syncada_file/payment_request_syncada_file_urlbuilder.go
  pkg/gen/adminapi/adminoperations/payment_request_syncada_files/index_payment_request_syncada_files.go
  pkg/gen/adminapi/adminoperations/payment_request_syncada_files/index_payment_request_syncada_files_parameters.go
  pkg/gen/adminapi/adminoperations/payment_request_syncada_files/index_payment_request_syncada_files_responses.go
  pkg/gen/adminapi/adminoperations/payment_request_syncada_files/index_payment_request_syncada_files_urlbuilder.go
  pkg/gen/adminapi/configure_mymove.go
  pkg/gen/adminapi/embedded_spec.go
  pkg/gen/adminmessages/payment_request_syncada_file.go
  pkg/gen/adminmessages/payment_request_syncada_files.go
  pkg/handlers/adminapi/api.go
  pkg/handlers/adminapi/payment_request_syncada_files.go
  pkg/handlers/adminapi/payment_request_syncada_files_test.go
  pkg/models/payment_request_edi_file.go
  pkg/payment_request/send_to_syncada.go
  pkg/payment_request/send_to_syncada_test.go
  pkg/services/payment_request/payment_request_reviewed_processor.go
  pkg/services/payment_request/payment_request_syncada_file_fetcher.go
  pkg/services/payment_request_syncada_file.go
  src/pages/Admin/PaymentRequests/PaymentRequest858List.jsx
  src/pages/Admin/PaymentRequests/PaymentRequest858Show.jsx
  src/scenes/SystemAdmin/Home.jsx
  swagger-def/admin.yaml
  swagger/admin.yaml
Labels: Mountain Movers, INTEGRATION

#13898 INT I-13395 B-21431 and B-21429 fix ppm error
  pkg/services/orchestrators/shipment/shipment_creator.go
Labels: Mountain Movers, INTEGRATION

#13890 INT B-21073 part dos
  pkg/factory/address_factory_test.go
  pkg/services/address/address_creator.go
  pkg/services/address/address_creator_test.go
  pkg/services/address/address_updater.go
  pkg/services/address/address_updater_test.go
  pkg/services/mto_shipment/mto_shipment_creator.go
  pkg/services/mto_shipment/mto_shipment_creator_test.go
  pkg/services/office_user/office_user_updater_test.go
Labels: Mountain Movers, INTEGRATION

#13843 B 21000 int - Allow customer to edit and view Counseling Office
  .envrc
  Dockerfile
  Dockerfile.local
  Dockerfile.reviewapp
  config/tls/README.md
  config/tls/dod-sw-ca-54.pem
  config/tls/dod-sw-ca-75.pem
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/create_update_orders.go
  pkg/gen/internalmessages/internal_move.go
  pkg/gen/internalmessages/move_payload.go
  pkg/handlers/internalapi/moves.go
  pkg/handlers/internalapi/orders.go
  pkg/handlers/internalapi/orders_test.go
  pkg/models/move.go
  src/components/Customer/EditOrdersForm/EditOrdersForm.jsx
  src/components/Customer/EditOrdersForm/EditOrdersForm.test.jsx
  src/components/Customer/Review/OrdersTable/OrdersTable.jsx
  src/components/Customer/Review/Summary/Summary.jsx
  src/components/form/fields/DutyLocationInput.jsx
  src/pages/MyMove/EditOrders.jsx
  src/pages/MyMove/EditOrders.test.jsx
  swagger-def/internal.yaml
  swagger/internal.yaml
Labels: G-Unit, INTEGRATION

#13903 i blame my dislexia
  pkg/services/payment_request/payment_request_reviewed_processor.go
Labels: Mountain Movers, INTEGRATION

#13862 B-20531-INT rules for queue management
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/queue_move.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/queues.go
  src/pages/Office/MoveQueue/MoveQueue.jsx
  src/pages/Office/MoveQueue/MoveQueue.test.jsx
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.jsx
  src/pages/Office/index.jsx
  src/utils/queues.jsx
  src/utils/queues.test.jsx
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: G-Unit, INTEGRATION

#13864 Int b 21380 secure sql query
  pkg/handlers/config.go
  pkg/handlers/config_test.go
Labels: INTEGRATION, Go-Rillaz

#13851 B 21163 transportation offices ak hi
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20241002151527_add_transportation_offices_AK_HI.up.sql
Labels: G-Unit, MAIN

#13882 B 21328 review weights button
  playwright/tests/office/txo/tioFlows.spec.js
  playwright/tests/office/txo/tioUpdateMaxBillableWeight.spec.js
  playwright/tests/office/txo/tooFlows.spec.js
  src/components/Office/BillableWeight/BillableWeightCard/BillableWeightCard.jsx
  src/components/Office/BillableWeight/BillableWeightCard/BillableWeightCard.test.jsx
  src/pages/Office/MovePaymentRequests/MovePaymentRequests.test.jsx
Labels: Scrummy Bears, MAIN

#13849 B-21427 & B-21430: Update & Populate Addresses is_oconus value
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20241004203140_update_addresses_is_oconus.up.sql
  pkg/factory/address_factory.go
  pkg/factory/address_factory_test.go
  pkg/handlers/authentication/devlocal.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/internalapi/addresses_test.go
  pkg/handlers/internalapi/internal/payloads/model_to_payload.go
  pkg/migrate/fixtures/copyFromStdinKeywords.sql
  pkg/models/address.go
  pkg/models/address_test.go
  pkg/models/service_member.go
  pkg/services/address/address_creator.go
  pkg/services/address/address_creator_test.go
  pkg/services/address/address_updater.go
  pkg/services/address/address_updater_test.go
  pkg/services/mto_service_item/mto_service_item_creator.go
  pkg/services/office_user/customer/customer.go
  pkg/testdatagen/make_address.go
Labels: Mountain Movers, INTEGRATION, database

#13909 Main B-21023 fix typo on dependents included question
  src/components/Office/AddOrdersForm/AddOrdersForm.jsx
  src/components/Office/AddOrdersForm/AddOrdersForm.test.jsx
Labels: MAIN, Go-Rillaz

#13805 B 21326 tget data cleanup int
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20241001122750_fix-tget-data.up.sql
Labels: Mountain Movers, INTEGRATION, database

#13914 Increasing statement timeout for Updating Addresses is_oconus migration script
  migrations/app/schema/20241004203140_update_addresses_is_oconus.up.sql
Labels: Mountain Movers, INTEGRATION, database

#13860 INT B-21393 Consolidate PPM Allowable Weights
  .envrc
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20241008133341_consolidate_allowable_weight_in_ppm_shipments.up.sql
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/p_p_m_shipment.go
  pkg/gen/ghcmessages/update_p_p_m_shipment.go
  pkg/gen/ghcmessages/update_weight_ticket.go
  pkg/gen/ghcmessages/weight_ticket.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/p_p_m_shipment.go
  pkg/gen/internalmessages/update_weight_ticket.go
  pkg/gen/internalmessages/weight_ticket.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/internal/payloads/payload_to_model.go
  pkg/models/ppm_shipment.go
  pkg/models/ppm_shipment_test.go
  pkg/models/weight_ticket.go
  pkg/models/weight_ticket_test.go
  pkg/services/ppm_closeout/ppm_closeout.go
  pkg/services/ppmshipment/ppm_shipment_new_submitter.go
  pkg/services/ppmshipment/ppm_shipment_new_submitter_test.go
  pkg/services/ppmshipment/ppm_shipment_updated_submitter.go
  pkg/services/ppmshipment/ppm_shipment_updated_submitter_test.go
  pkg/services/ppmshipment/ppm_shipment_updater_test.go
  pkg/services/ppmshipment/validation.go
  pkg/services/weight_ticket/weight_ticket_updater.go
  pkg/services/weight_ticket/weight_ticket_updater_test.go
  pkg/testdatagen/scenario/shared.go
  playwright/tests/office/servicescounseling/servicesCounselingFlows.spec.js
  playwright/tests/office/servicescounseling/servicesCounselingWeightTickets.spec.js
  src/components/Office/PPM/PPMHeaderSummary/EditPPMHeaderSummaryModal.jsx
  src/components/Office/PPM/PPMHeaderSummary/EditPPMHeaderSummaryModal.test.jsx
  src/components/Office/PPM/PPMHeaderSummary/HeaderSection.jsx
  src/components/Office/PPM/PPMHeaderSummary/HeaderSection.test.jsx
  src/components/Office/PPM/PPMHeaderSummary/PPMHeaderSummary.jsx
  src/components/Office/PPM/PPMHeaderSummary/PPMHeaderSummary.test.jsx
  src/components/Office/PPM/ReviewDocumentsSidePanel/ReviewDocumentsSidePanel.jsx
  src/components/Office/PPM/ReviewWeightTicket/ReviewWeightTicket.jsx
  src/components/Office/PPM/ReviewWeightTicket/ReviewWeightTicket.test.jsx
  src/constants/MoveHistory/Database/FieldMappings.js
  src/constants/MoveHistory/Database/WeightFields.js
  src/icons.js
  src/pages/Office/PPM/ReviewDocuments/ReviewDocuments.test.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdate.test.jsx
  src/shared/ToolTip/ToolTip.jsx
  src/shared/ToolTip/ToolTip.module.scss
  src/shared/ToolTip/ToolTip.stories.jsx
  src/shared/ToolTip/ToolTip.test.jsx
  src/utils/shipmentWeights.js
  swagger-def/definitions/PPMShipment.yaml
  swagger-def/definitions/WeightTicket.yaml
  swagger-def/ghc.yaml
  swagger-def/internal.yaml
  swagger/ghc.yaml
  swagger/internal.yaml
Labels: Scrummy Bears, INTEGRATION, database

#13718 B 20554 prime sim boat shipment
  .envrc
  pkg/gen/primev2api/embedded_spec.go
  pkg/gen/primev2messages/create_boat_shipment.go
  pkg/gen/primev3api/embedded_spec.go
  pkg/gen/primev3messages/boat_shipment.go
  pkg/gen/primev3messages/create_boat_shipment.go
  pkg/gen/primev3messages/create_m_t_o_shipment.go
  pkg/gen/primev3messages/m_t_o_shipment_without_service_items.go
  pkg/handlers/primeapiv2/mto_shipment.go
  pkg/handlers/primeapiv3/mto_shipment.go
  pkg/handlers/primeapiv3/mto_shipment_test.go
  pkg/handlers/primeapiv3/payloads/model_to_payload.go
  pkg/handlers/primeapiv3/payloads/model_to_payload_test.go
  pkg/handlers/primeapiv3/payloads/payload_to_model.go
  pkg/handlers/primeapiv3/payloads/payload_to_model_test.go
  pkg/services/move_task_order/move_task_order_fetcher.go
  src/components/PrimeUI/Shipment/Shipment.jsx
  src/components/PrimeUI/Shipment/Shipment.test.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentCreate.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentCreate.test.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentCreateForm.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentCreateForm.test.jsx
  swagger-def/definitions/prime/v2/MTOShipmentWithoutServiceItems.yaml
  swagger-def/definitions/prime/v3/MTOShipmentWithoutServiceItems.yaml
  swagger-def/prime_v2.yaml
  swagger-def/prime_v3.yaml
  swagger/prime_v2.yaml
  swagger/prime_v3.yaml
Labels: ByteSize M&Ms, MAIN

#13900 MAIN B-20452 - Office User - Edit, Submit, Approve, Delete Boat Shipment
  src/components/Customer/BoatShipment/BoatShipmentForm/BoatShipmentForm.jsx
  src/components/Customer/MobileHomeShipment/MobileHomeShipmentForm/MobileHomeShipmentForm.jsx
Labels: ByteSize M&Ms, MAIN

#13905 B 21522 int
  pkg/services/invoice/ghc_payment_request_invoice_generator.go
  pkg/services/invoice/ghc_payment_request_invoice_generator_test.go
Labels: Mountain Movers, INTEGRATION

#13923 B 21077 move shipment button int kickback
  src/components/Customer/MobileHomeShipment/MobileHomeShipmentForm/MobileHomeShipmentForm.jsx
  src/components/Office/RequestedShipments/ApprovedRequestedShipments.jsx
  src/components/Office/RequestedShipments/RequestedShipments.module.scss
  src/components/Office/RequestedShipments/SubmittedRequestedShipments.jsx
  src/components/PrimeUI/Shipment/Shipment.test.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentCreate.test.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentCreateForm.test.jsx
  yarn.lock
Labels: ByteSize M&Ms, INTEGRATION

#13911 B 20978 MAIN show links for documents for DDASIT and DDDSIT
  src/components/Office/ServiceItemDetails/ServiceItemDetails.jsx
  src/components/Office/ServiceItemDetails/ServiceItemDetails.test.jsx
Labels: Scrummy Bears, MAIN

#13934 Dtod ff update
  config/env/loadtest.app.env
Labels: INTEGRATION

#13874 B 21437 loa fix
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/affiliation.go
  pkg/gen/ghcmessages/department_indicator.go
  pkg/gen/ghcmessages/fetch_line_of_accounting_payload.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/affiliation.go
  pkg/gen/ordersapi/embedded_spec.go
  pkg/gen/ordersmessages/affiliation.go
  pkg/gen/pptasapi/embedded_spec.go
  pkg/gen/pptasmessages/affiliation.go
  pkg/handlers/ghcapi/lines_of_accounting.go
  pkg/handlers/ghcapi/lines_of_accounting_test.go
  pkg/models/order.go
  pkg/models/service_member.go
  pkg/services/invoice/ghc_payment_request_invoice_generator.go
  pkg/services/invoice/ghc_payment_request_invoice_generator_test.go
  pkg/services/line_of_accounting.go
  pkg/services/line_of_accounting/line_of_accounting_fetcher.go
  pkg/services/line_of_accounting/line_of_accounting_fetcher_test.go
  pkg/services/mocks/LineOfAccountingFetcher.go
  pkg/services/mocks/TransportationAccountingCodeFetcher.go
  pkg/services/pptas_report/pptas_report_list_fetcher.go
  pkg/services/transportation_accounting_code.go
  pkg/services/transportation_accounting_code/transportation_accounting_code_fetcher.go
  pkg/services/transportation_accounting_code/transportation_accounting_code_fetcher_test.go
  src/pages/Office/Orders/Orders.jsx
  src/pages/Office/ServicesCounselingOrders/ServicesCounselingOrders.jsx
  src/services/ghcApi.js
  swagger-def/definitions/Affiliation.yaml
  swagger-def/definitions/DepartmentIndicator.yaml
  swagger-def/ghc.yaml
  swagger/ghc.yaml
  swagger/internal.yaml
  swagger/orders.yaml
  swagger/pptas.yaml
Labels: Scrummy Bears, MAIN

#13921 Main B-21056 improve ppm address wording
  src/components/Office/ShipmentForm/ShipmentForm.jsx
  src/components/Office/ShipmentForm/ShipmentForm.test.jsx
Labels: MAIN, Go-Rillaz

#13706 B 21042 prime create 3rd address
  pkg/gen/primev3api/embedded_spec.go
  pkg/gen/primev3messages/create_m_t_o_shipment.go
  pkg/gen/primev3messages/create_p_p_m_shipment.go
  pkg/handlers/primeapiv3/payloads/payload_to_model.go
  pkg/handlers/primeapiv3/payloads/payload_to_model_test.go
  src/pages/PrimeUI/Shipment/PrimeUIShipmentCreate.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentCreateForm.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentCreateForm.test.jsx
  swagger-def/prime_v3.yaml
  swagger/prime_v3.yaml
Labels: G-Unit, MAIN

#13931 INT B-21549
  src/components/ShipmentList/ShipmentList.jsx
  src/components/ShipmentList/ShipmentList.module.scss
Labels: Mountain Movers, INTEGRATION

#13913 MAIN B-20627 Fix circleci tests and bump dependency
  go.mod
  go.sum
  pkg/handlers/routing/primeapi_test/telemetry_test.go
  pkg/telemetry/middleware_test.go
Labels: dependencies, security, MAIN, Go-Rillaz

#13936 B 20465 - Add Counseling Office Selection to Customer Application
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/create_update_orders.go
  pkg/gen/internalmessages/duty_location_payload.go
  pkg/handlers/internalapi/duty_locations.go
  pkg/handlers/internalapi/orders.go
  playwright/tests/my/mymove/orders.spec.js
  src/components/Customer/OrdersInfoForm/OrdersInfoForm.jsx
  src/components/Customer/OrdersInfoForm/OrdersInfoForm.test.jsx
  src/components/LocationSearchBox/LocationSearchBox.jsx
  src/components/LocationSearchBox/LocationSearchBox.test.jsx
  src/components/form/fields/CloseoutOfficeInput.jsx
  src/components/form/fields/DutyLocationInput.jsx
  src/pages/MyMove/AddOrders.jsx
  src/pages/MyMove/AddOrders.test.jsx
  src/pages/MyMove/Orders.test.jsx
  swagger-def/definitions/DutyLocationPayload.yaml
  swagger-def/internal.yaml
  swagger/internal.yaml
Labels: G-Unit, MAIN

#13933 B-21363 INT
  pkg/handlers/internalapi/moves.go
  pkg/handlers/internalapi/mto_shipment.go
  pkg/handlers/internalapi/mto_shipment_test.go
  src/pages/PrimeUI/Shipment/PrimeUIShipmentCreate.test.jsx
Labels: Mountain Movers, INTEGRATION

#13920 Main B-21124 mobile home db changes
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20240927145659_update_mobile_home_factor.up.sql
Labels: ByteSize M&Ms, MAIN

#13618 MAIN B-20451 - SC & TOO Creating Boat Shipment and Shipment Card Display
  playwright/tests/office/servicescounseling/servicesCounselingBoat.spec.js
  playwright/tests/office/txo/tooFlowsBoat.spec.js
  src/components/Customer/MtoShipmentForm/getShipmentOptions.js
  src/components/Office/DefinitionLists/BoatShipmentInfoList.jsx
  src/components/Office/DefinitionLists/BoatShipmentInfoList.stories.jsx
  src/components/Office/DefinitionLists/BoatShipmentInfoList.test.jsx
  src/components/Office/DefinitionLists/ShipmentInfoListSelector.jsx
  src/components/Office/ShipmentContainer/ShipmentContainer.jsx
  src/components/Office/ShipmentForm/BoatShipmentForm/BoatShipmentForm.jsx
  src/components/Office/ShipmentForm/BoatShipmentForm/BoatShipmentForm.module.scss
  src/components/Office/ShipmentForm/BoatShipmentForm/boatShipmentSchema.js
  src/components/Office/ShipmentForm/ShipmentForm.jsx
  src/components/Office/ShipmentForm/ShipmentForm.test.jsx
  src/components/Office/ShipmentFormRemarks/ShipmentFormRemarks.jsx
  src/pages/Office/AddShipment/AddShipment.jsx
  src/pages/Office/MoveDetails/MoveDetails.jsx
  src/pages/Office/ServicesCounselingAddShipment/ServicesCounselingAddShipment.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
  src/shared/constants.js
  src/utils/formatMtoShipment.js
Labels: ByteSize M&Ms, MAIN

#13870 B 21093 enforce email domain main
  src/components/Office/RequestAccountForm/RequestAccountForm.test.jsx
  src/pages/Office/RequestAccount/RequestAccount.test.jsx
  src/utils/validation.js
Labels: ByteSize M&Ms, MAIN

#13930 INT-B-20618 REBASE: Office users edit/create/delete mobile home shipments
  pkg/factory/boat_shipment_factory.go
  pkg/services/move/move_router.go
  pkg/services/move/move_router_test.go
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/testharness/dispatch.go
  pkg/testdatagen/testharness/make_move.go
  playwright/tests/office/servicescounseling/servicesCounselingMobileHome.spec.js
  playwright/tests/office/txo/tooFlowsMobileHome.spec.js
  playwright/tests/utils/office/waitForOfficePage.js
  playwright/tests/utils/testharness.js
  src/components/Office/DefinitionLists/MobileHomeShipmentInfoList.jsx
  src/components/Office/RequestedShipments/ApprovedRequestedShipments.jsx
  src/components/Office/RequestedShipments/SubmittedRequestedShipments.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
Labels: ByteSize M&Ms, INTEGRATION

#13955 B-21077 Adding back from align PR and mobile home dimensions example
  src/components/Customer/MobileHomeShipment/MobileHomeShipmentForm/MobileHomeShipmentForm.jsx
  src/components/Office/RequestedShipments/ApprovedRequestedShipments.jsx
  src/components/Office/RequestedShipments/SubmittedRequestedShipments.jsx
Labels: ByteSize M&Ms, INTEGRATION

#13810 MAIN B-20966 - tool-tips-missing-from-SIT-service-items
  src/components/Office/ServiceItemsTable/ResubmittedServiceItemDetails.test.jsx
  src/components/Office/ServiceItemsTable/ServiceItemsTable.jsx
  src/components/Office/ServiceItemsTable/ServiceItemsTable.module.scss
  src/constants/serviceItems.js
  src/constants/sitUpdates.js
  src/pages/PrimeUI/MoveTaskOrder/MoveDetails.test.jsx
  src/pages/PrimeUI/UpdateServiceItems/PrimeUIUpdateDestSITForm.jsx
  src/pages/PrimeUI/UpdateServiceItems/PrimeUIUpdateOriginSITForm.jsx
  src/pages/PrimeUI/UpdateServiceItems/PrimeUIUpdateSitServiceItem.jsx
  src/pages/PrimeUI/UpdateServiceItems/PrimeUpdateSitServiceItem.test.jsx
  src/shared/ToolTip/ToolTip.jsx
  src/shared/ToolTip/ToolTip.module.scss
  src/shared/ToolTip/ToolTip.test.jsx
Labels: ByteSize M&Ms, MAIN

#13949 B 21000 int happo
  src/components/Customer/EditOrdersForm/EditOrdersForm.jsx
  src/components/Customer/EditOrdersForm/EditOrdersForm.stories.jsx
  src/components/Customer/Review/OrdersTable/OrdersTable.stories.jsx
  src/components/Customer/Review/Review.stories.jsx
Labels: G-Unit, INTEGRATION

#13904 INT-B-21456-shipment-email-modification-for-retiree-separatee-counselor-approved-move-details
  pkg/assets/notifications/templates/move_counseled_template.html
  pkg/assets/notifications/templates/move_counseled_template.txt
  pkg/notifications/move_counseled.go
  pkg/notifications/move_counseled_test.go
Labels: INTEGRATION, Go-Rillaz

#13937 B 21000 main - Allow customer to edit and view Counseling Office
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/create_update_orders.go
  pkg/gen/internalmessages/internal_move.go
  pkg/gen/internalmessages/move_payload.go
  pkg/handlers/internalapi/moves.go
  pkg/handlers/internalapi/orders.go
  pkg/handlers/internalapi/orders_test.go
  pkg/models/move.go
  src/components/Customer/EditOrdersForm/EditOrdersForm.jsx
  src/components/Customer/EditOrdersForm/EditOrdersForm.stories.jsx
  src/components/Customer/EditOrdersForm/EditOrdersForm.test.jsx
  src/components/Customer/Review/OrdersTable/OrdersTable.jsx
  src/components/Customer/Review/OrdersTable/OrdersTable.stories.jsx
  src/components/Customer/Review/Review.stories.jsx
  src/components/Customer/Review/Summary/Summary.jsx
  src/pages/MyMove/EditOrders.jsx
  src/pages/MyMove/EditOrders.test.jsx
  swagger-def/internal.yaml
  swagger/internal.yaml
Labels: G-Unit, MAIN

#13956 B 20529 MAIN add save retrieve and filter capability for assigned column sc
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/queues/get_moves_queue_parameters.go
  pkg/gen/ghcapi/ghcoperations/queues/get_services_counseling_queue_parameters.go
  pkg/gen/ghcapi/ghcoperations/queues/get_services_counseling_queue_urlbuilder.go
  pkg/gen/ghcmessages/assigned_office_user.go
  pkg/gen/ghcmessages/queue_move.go
  pkg/gen/ghcmessages/queue_moves_result.go
  pkg/gen/ghcmessages/queue_payment_request.go
  pkg/gen/ghcmessages/queue_payment_requests_result.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/move_test.go
  pkg/handlers/ghcapi/mto_service_items_test.go
  pkg/handlers/ghcapi/queues.go
  pkg/handlers/ghcapi/queues_test.go
  pkg/services/order.go
  pkg/services/order/order_fetcher.go
  pkg/services/order/order_fetcher_test.go
  src/components/Table/TableQueue.jsx
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.jsx
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.test.jsx
  src/pages/Office/index.jsx
  src/services/ghcApi.js
  src/utils/queues.jsx
  src/utils/queues.test.jsx
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: G-Unit, MAIN

#13935 B 20977 usmc moves search
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload_test.go
Labels: ByteSize M&Ms, MAIN

#13948 INT-B-20983-filter-columns-to-be-more-user-friendly-duty-location
  pkg/services/order/order_fetcher.go
  pkg/services/order/order_fetcher_test.go
  pkg/services/payment_request/payment_request_list_fetcher.go
  pkg/services/payment_request/payment_request_list_fetcher_test.go
Labels: INTEGRATION, Go-Rillaz

#13942 B 21077 move shipment button main
  src/components/Office/RequestedShipments/ApprovedRequestedShipments.jsx
  src/components/Office/RequestedShipments/RequestedShipments.module.scss
  src/components/Office/RequestedShipments/RequestedShipments.test.jsx
  src/components/Office/RequestedShipments/SubmittedRequestedShipments.jsx
  src/pages/Office/MoveDetails/MoveDetails.jsx
  src/pages/Office/MoveDetails/MoveDetails.test.jsx
  src/pages/Office/TXOMoveInfo/TXOTab.module.scss
Labels: ByteSize M&Ms, MAIN

#13940 B 21432 display market code int
  src/components/Customer/Review/ShipmentCard/BoatShipmentCard/BoatShipmentCard.jsx
  src/components/Customer/Review/ShipmentCard/BoatShipmentCard/BoatShipmentCard.test.jsx
  src/components/Customer/Review/ShipmentCard/HHGShipmentCard/HHGShipmentCard.jsx
  src/components/Customer/Review/ShipmentCard/HHGShipmentCard/HHGShipmentCard.test.jsx
  src/components/Customer/Review/ShipmentCard/MobileHomeShipmentCard/MobileHomeShipmentCard.jsx
  src/components/Customer/Review/ShipmentCard/MobileHomeShipmentCard/MobileHomeShipmentCard.test.jsx
  src/components/Customer/Review/ShipmentCard/NTSRShipmentCard/NTSRShipmentCard.jsx
  src/components/Customer/Review/ShipmentCard/NTSRShipmentCard/NTSRShipmentCard.test.jsx
  src/components/Customer/Review/ShipmentCard/NTSShipmentCard/NTSShipmentCard.jsx
  src/components/Customer/Review/ShipmentCard/NTSShipmentCard/NTSShipmentCard.test.jsx
  src/components/Customer/Review/ShipmentCard/PPMShipmentCard/PPMShipmentCard.jsx
  src/components/Customer/Review/ShipmentCard/PPMShipmentCard/PPMShipmentCard.test.jsx
  src/components/Customer/Review/ShipmentCard/ShipmentCard.module.scss
  src/components/Customer/Review/Summary/Summary.jsx
  src/components/Office/ShipmentDisplay/ShipmentDisplay.jsx
  src/components/Office/ShipmentDisplay/ShipmentDisplay.module.scss
  src/components/Office/ShipmentDisplay/ShipmentDisplay.test.jsx
  src/components/Office/ShipmentDisplay/ShipmentDisplayTestData.js
  src/components/Office/ShipmentHeading/ShipmentHeading.jsx
  src/components/Office/ShipmentHeading/shipmentHeading.module.scss
  src/components/PrimeUI/Shipment/Shipment.jsx
  src/components/PrimeUI/Shipment/Shipment.test.jsx
  src/components/ShipmentList/ShipmentList.jsx
  src/components/ShipmentList/ShipmentList.module.scss
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
  src/pages/PrimeUI/CreatePaymentRequest/CreatePaymentRequest.test.jsx
  src/pages/PrimeUI/CreateSITExtensionRequest/CreateSITExtensionRequest.test.jsx
Labels: Mountain Movers, INTEGRATION

#13968 Int 20654 make test great again
  .circleci/config.yml
  pkg/factory/move_factory.go
  pkg/handlers/adminapi/payment_request_syncada_files_test.go
  pkg/models/payment_request_edi_file_test.go
  pkg/services/payment_request/payment_request_syncada_file_fetcher_test.go
  pkg/services/payment_request/validation_test.go
  playwright/tests/my/mymove/mobileHome.spec.js
Labels: Mountain Movers, INTEGRATION

#13945 B 20654 m25.1
  .circleci/config.yml
  cmd/generate-payment-request-edi/main.go
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20241007162933_addPaymentRequestEdiFiles.up.sql
  pkg/gen/adminapi/adminoperations/mymove_api.go
  pkg/gen/adminapi/adminoperations/payment_request_syncada_file/payment_request_syncada_file.go
  pkg/gen/adminapi/adminoperations/payment_request_syncada_file/payment_request_syncada_file_parameters.go
  pkg/gen/adminapi/adminoperations/payment_request_syncada_file/payment_request_syncada_file_responses.go
  pkg/gen/adminapi/adminoperations/payment_request_syncada_file/payment_request_syncada_file_urlbuilder.go
  pkg/gen/adminapi/adminoperations/payment_request_syncada_files/index_payment_request_syncada_files.go
  pkg/gen/adminapi/adminoperations/payment_request_syncada_files/index_payment_request_syncada_files_parameters.go
  pkg/gen/adminapi/adminoperations/payment_request_syncada_files/index_payment_request_syncada_files_responses.go
  pkg/gen/adminapi/adminoperations/payment_request_syncada_files/index_payment_request_syncada_files_urlbuilder.go
  pkg/gen/adminapi/configure_mymove.go
  pkg/gen/adminapi/embedded_spec.go
  pkg/gen/adminmessages/payment_request_syncada_file.go
  pkg/gen/adminmessages/payment_request_syncada_files.go
  pkg/handlers/adminapi/api.go
  pkg/handlers/adminapi/payment_request_syncada_files.go
  pkg/handlers/adminapi/payment_request_syncada_files_test.go
  pkg/models/payment_request_edi_file.go
  pkg/models/payment_request_edi_file_test.go
  pkg/payment_request/send_to_syncada.go
  pkg/payment_request/send_to_syncada_test.go
  pkg/services/payment_request/payment_request_reviewed_processor.go
  pkg/services/payment_request/payment_request_syncada_file_fetcher.go
  pkg/services/payment_request/payment_request_syncada_file_fetcher_test.go
  pkg/services/payment_request/validation_test.go
  pkg/services/payment_request_syncada_file.go
  src/pages/Admin/PaymentRequests/PaymentRequest858List.jsx
  src/pages/Admin/PaymentRequests/PaymentRequest858Show.jsx
  src/scenes/SystemAdmin/Home.jsx
  swagger-def/admin.yaml
  swagger/admin.yaml
Labels: Mountain Movers, MAIN

#13839 B-20617: SC TOO Creating Mobile Home Shipment and Shipment Card Display
  pkg/services/move/move_router.go
  playwright/tests/office/servicescounseling/servicesCounselingMobileHome.spec.js
  playwright/tests/office/txo/tooFlowsMobileHome.spec.js
  src/components/Office/DefinitionLists/MobileHomeShipmentInfoList.jsx
  src/components/Office/DefinitionLists/MobileHomeShipmentInfoList.stories.jsx
  src/components/Office/DefinitionLists/MobileHomeShipmentInfoList.test.jsx
  src/components/Office/DefinitionLists/ShipmentInfoListSelector.jsx
  src/components/Office/ShipmentForm/MobileHomeShipmentForm/MobileHomeShipmentForm.jsx
  src/components/Office/ShipmentForm/MobileHomeShipmentForm/MobileHomeShipmentForm.module.scss
  src/components/Office/ShipmentForm/MobileHomeShipmentForm/mobileHomeShipmentSchema.js
  src/components/Office/ShipmentForm/ShipmentForm.jsx
  src/components/Office/ShipmentForm/ShipmentForm.test.jsx
  src/components/Office/ShipmentFormRemarks/ShipmentFormRemarks.jsx
  src/pages/Office/AddShipment/AddShipment.jsx
  src/pages/Office/ServicesCounselingAddShipment/ServicesCounselingAddShipment.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
  src/utils/formatMtoShipment.js
Labels: ByteSize M&Ms, MAIN

#13958 B20884-MAIN2-fix prime weight tool tip
  src/components/ShipmentList/ShipmentList.jsx
  src/components/ShipmentList/ShipmentList.test.jsx
  src/shared/ToolTip/ToolTip.jsx
  src/shared/ToolTip/ToolTip.test.jsx
Labels: ByteSize M&Ms, MAIN

#13950 B-20531-INT part 2: revising rules for TOO
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/services/order/order_fetcher.go
  pkg/services/order/order_fetcher_test.go
Labels: G-Unit, INTEGRATION

#13919 Main B-21117 boat shipment db
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20241001144741_update_boat_factor.up.sql
Labels: ByteSize M&Ms, MAIN

#13941 B 20599 customer portal button int
  playwright/tests/my/mymove/orders.spec.js
  src/pages/MyMove/Home/MoveHome.jsx
  src/pages/MyMove/Home/MoveHome.test.jsx
Labels: ByteSize M&Ms, INTEGRATION

#13972 B 21522 main
  pkg/services/invoice/ghc_payment_request_invoice_generator.go
  pkg/services/invoice/ghc_payment_request_invoice_generator_test.go
Labels: Mountain Movers, MAIN

#13976 B-21363 Prime Updates INT
  pkg/handlers/primeapiv2/mto_shipment.go
  pkg/handlers/primeapiv2/mto_shipment_test.go
  pkg/handlers/primeapiv3/mto_shipment.go
  pkg/handlers/primeapiv3/mto_shipment_test.go
Labels: Mountain Movers, INTEGRATION

#13929 MAIN B-21549
  src/components/ShipmentList/ShipmentList.jsx
  src/components/ShipmentList/ShipmentList.module.scss
Labels: Mountain Movers, MAIN

#13969 INT B-20618 office edit mobile home hotfix
  pkg/gen/primev2api/embedded_spec.go
  pkg/gen/primev2messages/create_m_t_o_shipment.go
  pkg/handlers/apitests.go
  pkg/handlers/primeapi/move_task_order.go
  pkg/handlers/primeapiv2/move_task_order.go
  pkg/handlers/primeapiv2/mto_shipment.go
  pkg/handlers/primeapiv2/payloads/payload_to_model.go
  pkg/handlers/primeapiv2/payloads/payload_to_model_test.go
  pkg/handlers/primeapiv3/move_task_order.go
  pkg/handlers/primeapiv3/mto_shipment.go
  pkg/handlers/primeapiv3/mto_shipment_test.go
  pkg/handlers/routing/base_routing_suite.go
  pkg/testdatagen/scenario/shared.go
  src/components/Office/DefinitionLists/ShipmentInfoListSelector.jsx
  src/components/Office/ShipmentDisplay/ShipmentDisplay.jsx
  src/constants/shipments.js
  src/pages/MyMove/Profile/ResidentialAddress.test.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
  swagger-def/prime_v2.yaml
  swagger/prime_v2.yaml
Labels: ByteSize M&Ms, INTEGRATION

#13891 B 20526 int - Backend | Sort Customer dropdown of Counseling Offices
  config/tls/dod-sw-ca-75.pem
  pkg/services/transportation_office/transportation_office_fetcher.go
Labels: G-Unit, INTEGRATION

#13984 B 21427 update addresses is oconus
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20241004203140_update_addresses_is_oconus.up.sql
  pkg/factory/address_factory.go
  pkg/factory/address_factory_test.go
  pkg/handlers/authentication/devlocal.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/internalapi/addresses_test.go
  pkg/handlers/internalapi/internal/payloads/model_to_payload.go
  pkg/migrate/fixtures/copyFromStdinKeywords.sql
  pkg/models/address.go
  pkg/models/address_test.go
  pkg/models/service_member.go
  pkg/services/address/address_creator.go
  pkg/services/address/address_creator_test.go
  pkg/services/address/address_updater.go
  pkg/services/address/address_updater_test.go
  pkg/services/mto_service_item/mto_service_item_creator.go
  pkg/services/office_user/customer/customer.go
  pkg/testdatagen/make_address.go
Labels: Mountain Movers, MAIN

#13985 B-21362/B-21363 UB Shipment Updates - MAIN
  .circleci/config.yml
  .envrc
  config/env/demo.app-client-tls.env
  config/env/demo.app.env
  config/env/exp.app-client-tls.env
  config/env/exp.app.env
  config/env/loadtest.app-client-tls.env
  config/env/loadtest.app.env
  config/env/prd.app-client-tls.env
  config/env/prd.app.env
  config/env/stg.app-client-tls.env
  config/env/stg.app.env
  config/flipt/storage/development.features.yaml
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20241002170242_add_ub_shipment_type.up.sql
  pkg/factory/mto_shipment_factory_test.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/m_t_o_shipment_type.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/m_t_o_shipment_type.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/m_t_o_shipment_type.go
  pkg/gen/primev2api/embedded_spec.go
  pkg/gen/primev2messages/m_t_o_shipment_type.go
  pkg/gen/primev3api/embedded_spec.go
  pkg/gen/primev3messages/m_t_o_shipment_type.go
  pkg/gen/supportapi/embedded_spec.go
  pkg/gen/supportmessages/m_t_o_shipment_type.go
  pkg/handlers/internalapi/moves.go
  pkg/handlers/internalapi/mto_shipment.go
  pkg/handlers/internalapi/mto_shipment_test.go
  pkg/handlers/primeapiv2/mto_shipment.go
  pkg/handlers/primeapiv2/mto_shipment_test.go
  pkg/handlers/primeapiv3/mto_shipment.go
  pkg/handlers/primeapiv3/mto_shipment_test.go
  pkg/models/mto_shipments.go
  pkg/paperwork/evaluation_report_form_creator.go
  pkg/payment_request/service_param_value_lookups/weight_billed_lookup.go
  pkg/payment_request/service_param_value_lookups/weight_billed_lookup_test.go
  pkg/services/mto_shipment/mto_shipment_creator.go
  pkg/services/mto_shipment/mto_shipment_creator_test.go
  pkg/services/mto_shipment/mto_shipment_updater_test.go
  pkg/services/mto_shipment/rules_test.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet_test.go
  swagger-def/definitions/MTOShipmentType.yaml
  swagger-def/definitions/prime/MTOShipmentType.yaml
  swagger-def/definitions/prime/v2/MTOShipmentType.yaml
  swagger-def/definitions/prime/v3/MTOShipmentType.yaml
  swagger-def/internal.yaml
  swagger-def/support.yaml
  swagger/ghc.yaml
  swagger/internal.yaml
  swagger/prime.yaml
  swagger/prime_v2.yaml
  swagger/prime_v3.yaml
  swagger/support.yaml
Labels: Mountain Movers, MAIN, database

#13995 B-21362: Update INTERNATIONAL_HHG to HHG shipment_type - INT
  migrations/app/schema/20241002170242_add_ub_shipment_type.up.sql
Labels: Mountain Movers, INTEGRATION

#13991 B19795 int4 doc viewer doc title change
  src/components/DocumentViewerFileManager/DocumentViewerFileManager.test.jsx
  src/pages/MyMove/UploadOrders.test.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentCreateForm.test.jsx
Labels: ByteSize M&Ms, INTEGRATION

#13740 B19795 main doc viewer doc title change
  pkg/handlers/internalapi/uploads.go
  pkg/services/payment_request/upload_creator.go
  playwright/tests/my/milmove/ppms/customerPpmTestFixture.js
  src/components/DocumentViewer/Menu/Menu.module.scss
  src/components/DocumentViewerFileManager/DocumentViewerFileManager.jsx
  src/components/DocumentViewerFileManager/DocumentViewerFileManager.test.jsx
  src/pages/MyMove/AdditionalDocuments/AdditionalDocuments.jsx
  src/pages/MyMove/EditOrders.jsx
  src/pages/MyMove/PPM/Closeout/Expenses/Expenses.jsx
  src/pages/MyMove/PPM/Closeout/ProGear/ProGear.jsx
  src/pages/MyMove/PPM/Closeout/WeightTickets/WeightTickets.jsx
  src/pages/MyMove/UploadOrders.jsx
  src/pages/MyMove/UploadOrders.test.jsx
Labels: ByteSize M&Ms, MAIN

#13966 B 19531 int
  pkg/handlers/primeapiv2/mto_shipment.go
  pkg/handlers/primeapiv2/mto_shipment_test.go
  pkg/handlers/primeapiv3/mto_shipment.go
  pkg/handlers/primeapiv3/mto_shipment_test.go
  src/components/Customer/Review/TableDivider.jsx
  src/components/Customer/Review/TableDivider.test.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentCreate.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentCreate.test.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdate.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdate.test.jsx
Labels: Scrummy Bears, INTEGRATION

#13957 B 20473 int
  .circleci/config.yml
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/move/move_canceler_responses.go
  pkg/gen/ghcapi/ghcoperations/move/search_moves.go
  pkg/gen/ghcmessages/p_p_m_status.go
  pkg/handlers/authentication/permissions.go
  pkg/services/move/move_canceler.go
  pkg/services/move/move_canceler_test.go
  pkg/services/mto_shipment/mto_shipment_creator_test.go
  src/components/ConfirmationModals/CancelMoveConfirmationModal.jsx
  src/components/ConfirmationModals/CancelMoveConfirmationModal.stories.jsx
  src/components/ConfirmationModals/CancelMoveConfirmationModal.test.jsx
  src/components/Office/EvaluationReportShipmentDisplay/EvaluationReportShipmentDisplay.jsx
  src/components/Office/ShipmentDisplay/ShipmentDisplay.jsx
  src/components/Office/ShipmentDisplay/ShipmentDisplay.stories.jsx
  src/components/Office/ShipmentDisplay/ShipmentDisplay.test.jsx
  src/components/Office/ShipmentDisplay/ShipmentDisplayTestData.js
  src/components/Office/ShipmentHeading/ShipmentHeading.jsx
  src/components/Office/ShipmentHeading/ShipmentHeading.test.jsx
  src/components/Office/ShipmentHeading/shipmentheading.stories.jsx
  src/constants/MoveHistory/UIDisplay/Operations.js
  src/constants/permissions.js
  src/constants/queues.js
  src/constants/shipments.js
  src/pages/Office/MoveDetails/MoveDetails.jsx
  src/pages/Office/MoveDetails/MoveDetails.test.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.test.jsx
  src/pages/Office/MoveTaskOrder/moveTaskOrderUnitTestData.js
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.module.scss
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.test.jsx
  src/pages/Office/TXOMoveInfo/TXOTab.module.scss
  src/pages/PrimeUI/Shipment/PrimeUIShipmentCreateForm.test.jsx
  src/services/ghcApi.js
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: G-Unit, INTEGRATION

#13992 B-21362: Update INTERNATIONAL_HHG to HHG shipment_type
  migrations/app/schema/20241002170242_add_ub_shipment_type.up.sql
  pkg/handlers/primeapiv3/payloads/payload_to_model_test.go
Labels: Mountain Movers, MAIN

#13970 B 20756 int
  .envrc
  pkg/auth/session.go
  pkg/cli/route.go
  pkg/models/ppm_shipment.go
  pkg/models/ppm_shipment_test.go
  pkg/models/validators.go
  pkg/route/dtod_planner_test.go
  pkg/route/dtod_zip5_distance.go
  pkg/route/dtod_zip5_distance_test.go
  pkg/route/hhg_planner_test.go
  pkg/route/planner.go
  pkg/services/ppmshipment/ppm_estimator.go
  pkg/services/ppmshipment/rules.go
  pkg/services/ppmshipment/rules_test.go
  src/components/Customer/PPM/Booking/Advance/AdvanceForm.jsx
  src/components/Customer/PPM/Booking/Advance/AdvanceForm.test.jsx
  src/components/Customer/PPM/Booking/EstimatedIncentiveDetails/EstimatedIncentiveDetails.jsx
  src/components/Customer/PPM/Booking/EstimatedIncentiveDetails/EstimatedIncentiveDetails.test.jsx
  src/components/QueueTable/index.test.jsx
  src/pages/MyMove/PPM/Booking/Advance/Advance.jsx
  src/pages/MyMove/PPM/Booking/Advance/Advance.test.jsx
Labels: Scrummy Bears, INTEGRATION

#13998 B-21362 INT Test Coverage
  pkg/handlers/primeapiv3/payloads/payload_to_model_test.go
Labels: Mountain Movers, INTEGRATION

#13967 B21526-INT-add db swagger support for actual expense reimbursement
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20241011201326_changes_for_actual_expense_reimbursement_field.up.sql
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/create_p_p_m_shipment.go
  pkg/gen/ghcmessages/p_p_m_shipment.go
  pkg/gen/ghcmessages/update_p_p_m_shipment.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/create_p_p_m_shipment.go
  pkg/gen/internalmessages/p_p_m_shipment.go
  pkg/gen/internalmessages/update_p_p_m_shipment.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/create_p_p_m_shipment.go
  pkg/gen/primemessages/p_p_m_shipment.go
  pkg/gen/primemessages/update_p_p_m_shipment.go
  pkg/gen/primev2api/embedded_spec.go
  pkg/gen/primev2messages/create_p_p_m_shipment.go
  pkg/gen/primev2messages/p_p_m_shipment.go
  pkg/gen/primev2messages/update_p_p_m_shipment.go
  pkg/gen/primev3api/embedded_spec.go
  pkg/gen/primev3messages/create_p_p_m_shipment.go
  pkg/gen/primev3messages/p_p_m_shipment.go
  pkg/gen/primev3messages/update_p_p_m_shipment.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload_test.go
  pkg/handlers/ghcapi/internal/payloads/payload_to_model.go
  pkg/handlers/internalapi/internal/payloads/model_to_payload.go
  pkg/handlers/internalapi/internal/payloads/model_to_payload_test.go
  pkg/handlers/internalapi/internal/payloads/payload_to_model.go
  pkg/handlers/primeapi/payloads/model_to_payload.go
  pkg/handlers/primeapi/payloads/model_to_payload_test.go
  pkg/handlers/primeapi/payloads/payload_to_model.go
  pkg/handlers/primeapiv2/payloads/model_to_payload.go
  pkg/handlers/primeapiv2/payloads/model_to_payload_test.go
  pkg/handlers/primeapiv2/payloads/payload_to_model.go
  pkg/handlers/primeapiv3/payloads/model_to_payload.go
  pkg/handlers/primeapiv3/payloads/model_to_payload_test.go
  pkg/handlers/primeapiv3/payloads/payload_to_model.go
  pkg/handlers/primeapiv3/payloads/payload_to_model_test.go
  pkg/models/ppm_shipment.go
  pkg/services/ppmshipment/validation.go
  swagger-def/definitions/PPMShipment.yaml
  swagger-def/definitions/prime/PPMShipment.yaml
  swagger-def/definitions/prime/v3/PPMShipment.yaml
  swagger-def/ghc.yaml
  swagger-def/internal.yaml
  swagger-def/prime.yaml
  swagger-def/prime_v2.yaml
  swagger-def/prime_v3.yaml
  swagger/ghc.yaml
  swagger/internal.yaml
  swagger/prime.yaml
  swagger/prime_v2.yaml
  swagger/prime_v3.yaml
Labels: ByteSize M&Ms, INTEGRATION

#13982 B-20313: Prevent Role List Duplication
  pkg/handlers/adminapi/office_users.go
  pkg/handlers/adminapi/office_users_test.go
Labels: Mountain Movers, INTEGRATION

#13986 B-21365 Customer UB Shipment Card MAIN
  .circleci/config.yml
  pkg/handlers/primeapiv3/payloads/payload_to_model_test.go
  src/components/Customer/Home/Step/Step.stories.jsx
  src/components/Customer/MtoShipmentForm/MtoShipmentForm.jsx
  src/components/Customer/MtoShipmentForm/MtoShipmentForm.stories.jsx
  src/components/Customer/MtoShipmentForm/MtoShipmentForm.test.jsx
  src/components/Customer/MtoShipmentForm/getShipmentOptions.js
  src/components/Customer/Review/ShipmentCard/HHGShipmentCard/HHGShipmentCard.test.jsx
  src/components/Customer/Review/Summary/Summary.jsx
  src/components/Customer/Review/Summary/Summary.test.jsx
  src/components/Office/ShipmentContainer/ShipmentContainer.jsx
  src/components/Office/ShipmentContainer/ShipmentContainer.test.jsx
  src/components/ShipmentList/ShipmentList.jsx
  src/components/ShipmentList/ShipmentList.module.scss
  src/components/ShipmentList/ShipmentList.test.jsx
  src/constants/shipments.js
  src/content/shipments.js
  src/shared/constants.js
Labels: Mountain Movers, MAIN

#13983 Main b 21409 retiree separatee email updates move submitted
  pkg/assets/notifications/templates/move_submitted_template.html
  pkg/assets/notifications/templates/move_submitted_template.txt
  pkg/notifications/move_submitted.go
  pkg/notifications/move_submitted_test.go
Labels: MAIN, Go-Rillaz

#14007 B 21584 fix email domain int
  go.mod
  go.sum
  pkg/handlers/primeapiv3/payloads/payload_to_model_test.go
  src/components/Office/RequestAccountForm/RequestAccountForm.test.jsx
  src/pages/Office/RequestAccount/RequestAccount.test.jsx
  src/utils/validation.js
  swagger-def/internal.yaml
Labels: ByteSize M&Ms, INTEGRATION

#13965 Main B-21380 Secure SQL Query
  pkg/handlers/config.go
  pkg/handlers/config_test.go
Labels: MAIN, Go-Rillaz

#13907 INT-B-20777 TIO Queue Management
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/queues/get_payment_requests_queue_parameters.go
  pkg/gen/ghcapi/ghcoperations/queues/get_payment_requests_queue_urlbuilder.go
  pkg/gen/ghcmessages/queue_payment_request.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/queues.go
  pkg/services/order/order_fetcher.go
  pkg/services/payment_request.go
  pkg/services/payment_request/payment_request_list_fetcher.go
  src/pages/Office/PaymentRequestQueue/PaymentRequestQueue.jsx
  src/pages/Office/PaymentRequestQueue/PaymentRequestQueue.module.scss
  src/pages/Office/PaymentRequestQueue/PaymentRequestQueue.test.jsx
  src/pages/Office/index.jsx
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: G-Unit, INTEGRATION

#14000 INT I-13434 & B-21432 updating market code for all shipment types
  pkg/models/mto_shipments.go
  pkg/models/mto_shipments_test.go
  pkg/services/mto_shipment/mto_shipment_creator.go
  pkg/services/mto_shipment/mto_shipment_updater.go
  pkg/services/orchestrators/shipment/shipment_updater.go
  pkg/services/orchestrators/shipment/shipment_updater_test.go
  pkg/services/ppmshipment/ppm_shipment_creator.go
  pkg/services/ppmshipment/ppm_shipment_creator_test.go
  pkg/services/ppmshipment/ppm_shipment_updater.go
  pkg/services/ppmshipment/ppm_shipment_updater_test.go
  src/pages/MyMove/Profile/BackupAddress.test.jsx
  src/pages/MyMove/Profile/ResidentialAddress.test.jsx
Labels: Mountain Movers, INTEGRATION

#14016 B-21584-Fix-Email-Domain
  src/components/Office/RequestAccountForm/RequestAccountForm.test.jsx
  src/pages/Office/RequestAccount/RequestAccount.test.jsx
  src/utils/validation.js
Labels: ByteSize M&Ms, MAIN

#14017 youre welcome
  scripts/ensure-go-test-coverage
  scripts/ensure-js-test-coverage
Labels: Mountain Movers, MAIN

#13979 B 21449 int
  pkg/notifications/constants.go
  pkg/route/dtod_zip5_distance.go
  pkg/route/dtod_zip5_distance_test.go
  src/components/Office/ShipmentForm/ShipmentForm.jsx
  src/scenes/Moves/WizardHeader.css
  src/scenes/Moves/WizardHeader.jsx
Labels: Scrummy Bears, INTEGRATION

#14004 MAIN B-21429 and B-21431
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20241008212243_populate_market_code_on_shipments_table.up.sql
  pkg/factory/mto_shipment_factory.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/m_t_o_shipment.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/m_t_o_shipment.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/m_t_o_shipment_without_service_items.go
  pkg/gen/primev2api/embedded_spec.go
  pkg/gen/primev2messages/m_t_o_shipment_without_service_items.go
  pkg/gen/primev3api/embedded_spec.go
  pkg/gen/primev3messages/m_t_o_shipment_without_service_items.go
  pkg/gen/supportapi/embedded_spec.go
  pkg/gen/supportmessages/m_t_o_shipment.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload_test.go
  pkg/handlers/internalapi/internal/payloads/model_to_payload.go
  pkg/handlers/internalapi/internal/payloads/model_to_payload_test.go
  pkg/handlers/internalapi/internal/payloads/payloads_test.go
  pkg/handlers/primeapi/payloads/model_to_payload.go
  pkg/handlers/primeapi/payloads/model_to_payload_test.go
  pkg/handlers/primeapiv2/payloads/model_to_payload.go
  pkg/handlers/primeapiv2/payloads/model_to_payload_test.go
  pkg/handlers/primeapiv3/payloads/model_to_payload.go
  pkg/handlers/primeapiv3/payloads/model_to_payload_test.go
  pkg/models/mto_shipments.go
  pkg/models/mto_shipments_test.go
  pkg/services/address/address_creator_test.go
  pkg/services/mto_shipment/mto_shipment_creator.go
  pkg/services/mto_shipment/mto_shipment_creator_test.go
  pkg/services/mto_shipment/mto_shipment_updater.go
  pkg/services/mto_shipment/mto_shipment_updater_test.go
  pkg/services/orchestrators/shipment/shipment_creator.go
  pkg/services/ppmshipment/ppm_shipment_creator.go
  pkg/services/ppmshipment/ppm_shipment_creator_test.go
  pkg/services/shipment_address_update/shipment_address_update_requester.go
  pkg/services/shipment_address_update/shipment_address_update_requester_test.go
  pkg/testdatagen/make_mto_shipment.go
  playwright/tests/office/servicescounseling/servicesCounselingFlows.spec.js
  swagger-def/definitions/MTOShipment.yaml
  swagger-def/definitions/prime/MTOShipmentWithoutServiceItems.yaml
  swagger-def/definitions/prime/v2/MTOShipmentWithoutServiceItems.yaml
  swagger-def/definitions/prime/v3/MTOShipmentWithoutServiceItems.yaml
  swagger-def/internal.yaml
  swagger-def/support.yaml
  swagger/ghc.yaml
  swagger/internal.yaml
  swagger/prime.yaml
  swagger/prime_v2.yaml
  swagger/prime_v3.yaml
  swagger/support.yaml
Labels: Mountain Movers, MAIN

#14011 B 21558 int
  migrations/app/migrations_manifest.txt
  migrations/app/secure/20241024114748_create_gbloc_aors.up.sql
Labels: G-Unit, INTEGRATION

#13834 B-20532 TOO queue assignment
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/queues/get_moves_queue_parameters.go
  pkg/gen/ghcapi/ghcoperations/queues/get_moves_queue_urlbuilder.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/queues.go
  pkg/handlers/ghcapi/queues_test.go
  pkg/services/mocks/OrderFetcher.go
  pkg/services/order.go
  pkg/services/order/order_fetcher.go
  pkg/services/order/order_fetcher_test.go
  src/pages/Office/MoveQueue/MoveQueue.jsx
  src/pages/Office/MoveQueue/MoveQueue.test.jsx
  src/pages/Office/index.jsx
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: G-Unit, MAIN

#14025 Int b 20975 too submits mto and receives incorrect validation
  src/components/Office/RequestedShipments/SubmittedRequestedShipments.stories.jsx
Labels: INTEGRATION, Go-Rillaz

#14029 INT B-21592 - Move Management Fee Utilizing Base Year from Shipment Requested Pickup Date
  go.mod
  go.sum
  pkg/handlers/ghcapi/move_task_order_test.go
  pkg/services/move_task_order/move_task_order_updater_test.go
  pkg/services/mto_service_item/mto_service_item_creator.go
  pkg/services/mto_service_item/mto_service_item_creator_test.go
  playwright/tests/office/servicescounseling/servicesCounselingFlows.spec.js
  scripts/ensure-go-test-coverage
  scripts/ensure-js-test-coverage
Labels: Mountain Movers, INTEGRATION

#14045 B 21558 path fix
  migrations/app/schema/20241024114748_create_gbloc_aors.up.sql
Labels: G-Unit, INTEGRATION

#14040 B 20599 customer portal button main
  playwright/tests/my/mymove/orders.spec.js
  src/pages/MyMove/Home/MoveHome.jsx
  src/pages/MyMove/Home/MoveHome.test.jsx
Labels: ByteSize M&Ms, MAIN

#14041 MMHDT 614 Integration
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20241029144404_hdt-614-adjust-accomack-county.up.sql
Labels: Mountain Movers, INTEGRATION

#14051 INT - added test for b-21526
  pkg/handlers/internalapi/internal/payloads/model_to_payload_test.go
  pkg/handlers/internalapi/internal/payloads/payload_to_model_test.go
  pkg/handlers/primeapi/payloads/payload_to_model_test.go
  pkg/handlers/primeapiv2/payloads/payload_to_model_test.go
  pkg/handlers/primeapiv3/payloads/payload_to_model_test.go
  playwright/tests/office/ppms/happyPathFlows.spec.js
  playwright/tests/office/ppms/ppmTestFixture.js
  src/pages/MyMove/Profile/BackupAddress.test.jsx
  src/pages/Office/CustomerOnboarding/CreateCustomerForm.test.jsx
Labels: ByteSize M&Ms, INTEGRATION

#14034 Revert "create international rate area lookup"
  pkg/models/service_item_param_key.go
  pkg/payment_request/service_param_value_lookups/international_rate_area_lookup.go
  pkg/payment_request/service_param_value_lookups/international_rate_area_lookup_test.go
  pkg/payment_request/service_param_value_lookups/lookup_query_helpers.go
  pkg/payment_request/service_param_value_lookups/lookup_query_helpers_test.go
  pkg/payment_request/service_param_value_lookups/service_param_value_lookups.go
Labels: Mountain Movers, INTEGRATION

#14039 INT - B-21527 counselor actual expense reimbursement
  pkg/factory/move_factory.go
  pkg/handlers/internalapi/orders.go
  pkg/services/move/move_router.go
  pkg/services/move/move_router_test.go
  pkg/services/order/order_updater.go
  pkg/services/order/order_updater_test.go
  pkg/testdatagen/testharness/dispatch.go
  pkg/testdatagen/testharness/make_move.go
  playwright/tests/office/servicescounseling/servicesCounselingFlows.spec.js
  playwright/tests/utils/testharness.js
  src/components/Office/PPM/PPMHeaderSummary/EditPPMHeaderSummaryModal.jsx
  src/components/Office/PPM/PPMHeaderSummary/EditPPMHeaderSummaryModal.module.scss
  src/components/Office/PPM/PPMHeaderSummary/EditPPMHeaderSummaryModal.test.jsx
  src/components/Office/PPM/PPMHeaderSummary/HeaderSection.jsx
  src/components/Office/PPM/PPMHeaderSummary/HeaderSection.test.jsx
  src/components/Office/PPM/PPMHeaderSummary/PPMHeaderSummary.jsx
  src/components/Office/PPM/PPMHeaderSummary/PPMHeaderSummary.module.scss
  src/components/Office/PPM/PPMHeaderSummary/PPMHeaderSummary.test.jsx
  src/components/Office/PPM/ReviewDocumentsSidePanel/ReviewDocumentsSidePanel.jsx
  src/components/Office/PPM/ReviewExpense/ReviewExpense.jsx
  src/components/Office/PPM/ReviewProGear/ReviewProGear.jsx
  src/components/Office/PPM/ReviewWeightTicket/ReviewWeightTicket.jsx
  src/components/Office/ShipmentDisplay/ShipmentDisplay.jsx
  src/components/Office/ShipmentDisplay/ShipmentDisplay.module.scss
  src/components/Office/ShipmentDisplay/ShipmentDisplay.test.jsx
  src/components/Office/ShipmentForm/ShipmentForm.jsx
  src/components/Office/ShipmentForm/ShipmentForm.module.scss
  src/components/Office/ShipmentForm/ShipmentForm.test.jsx
  src/components/Office/ShipmentForm/ppmShipmentSchema.js
  src/pages/MyMove/PPM/Booking/DateAndLocation/DateAndLocation.jsx
  src/pages/MyMove/PPM/Booking/DateAndLocation/DateAndLocation.test.jsx
  src/pages/Office/PPM/ReviewDocuments/ReviewDocuments.jsx
  src/pages/Office/ServicesCounselingAddShipment/ServicesCounselingAddShipment.jsx
  src/pages/Office/ServicesCounselingEditShipmentDetails/ServicesCounselingEditShipmentDetails.jsx
  src/utils/formatMtoShipment.js
Labels: ByteSize M&Ms, INTEGRATION

#14013 B 21524 update counselor approved email int
  pkg/assets/notifications/templates/move_counseled_template.html
  pkg/assets/notifications/templates/move_counseled_template.txt
  pkg/factory/address_factory_test.go
  pkg/notifications/move_counseled.go
  pkg/notifications/move_counseled_test.go
Labels: ByteSize M&Ms, INTEGRATION

#14010 B 21558 create gbloc aors
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20241024114748_create_gbloc_aors.up.sql
Labels: G-Unit, MAIN

#13963 INT - B-21481 - DB - Add HI/AK duty locations
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20241017183144_add_AK_HI_duty_locations.up.sql
  pkg/handlers/internalapi/duty_locations.go
  pkg/handlers/internalapi/duty_locations_test.go
  pkg/models/duty_location.go
  pkg/models/duty_location_test.go
Labels: Scrummy Bears, INTEGRATION, database

#14030 B 20533 INT - HQ/TIO payment request cleanup
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/queues.go
  src/pages/Office/MoveQueue/MoveQueue.jsx
  src/pages/Office/PaymentRequestQueue/PaymentRequestQueue.jsx
Labels: G-Unit, INTEGRATION

#14031 B 20526 main - Backend | Sort Customer dropdown of Counseling Offices
  config/tls/dod-sw-ca-75.pem
  pkg/services/transportation_office/transportation_office_fetcher.go
Labels: G-Unit, MAIN

#14049 B-21597: Add Temporary Duty (TDY) Order Type INT
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20241029125015_add_orders_type_enum.up.sql
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/orders_type.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/orders_type.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/orders_type.go
  pkg/gen/primev2api/embedded_spec.go
  pkg/gen/primev2messages/orders_type.go
  pkg/gen/primev3api/embedded_spec.go
  pkg/gen/primev3messages/orders_type.go
  pkg/gen/supportapi/embedded_spec.go
  pkg/gen/supportmessages/orders_type.go
  src/components/Customer/EditOrdersForm/EditOrdersForm.stories.jsx
  src/components/Customer/EditOrdersForm/EditOrdersForm.test.jsx
  src/components/Customer/MtoShipmentForm/MtoShipmentForm.stories.jsx
  src/components/Customer/MtoShipmentForm/MtoShipmentForm.test.jsx
  src/components/Customer/OrdersInfoForm/OrdersInfoForm.stories.jsx
  src/components/Customer/OrdersInfoForm/OrdersInfoForm.test.jsx
  src/components/Customer/Review/Review.stories.jsx
  src/components/Customer/Review/Summary/Summary.test.jsx
  src/components/Office/DefinitionLists/OrdersList.stories.jsx
  src/components/Office/OrdersDetailForm/OrdersDetailForm.stories.jsx
  src/components/Office/ServiceItemsTable/resubmittedServiceItemUnitTestData.js
  src/constants/MoveHistory/EventTemplates/CreateOrder/createOrder.test.jsx
  src/constants/MoveHistory/EventTemplates/CreateOrders/createOrders.test.jsx
  src/constants/MoveHistory/EventTemplates/UpdateOrders/updateOrder.test.jsx
  src/constants/orders.js
  src/pages/MyMove/AddOrders.test.jsx
  src/pages/MyMove/AmendOrders/AmendOrders.test.jsx
  src/pages/MyMove/CreateOrEditMtoShipment.test.jsx
  src/pages/MyMove/EditOrders.test.jsx
  src/pages/MyMove/Home/MoveHome.test.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesLandingPage.test.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesMoveInfoList/MultiMovesInfoList.test.jsx
  src/pages/MyMove/Orders.test.jsx
  src/pages/MyMove/Review/Review.test.jsx
  src/pages/MyMove/UploadOrders.test.jsx
  src/pages/Office/MoveHistory/LabeledDetails.test.jsx
  src/pages/Office/MovePaymentRequests/MovePaymentRequests.test.jsx
  src/pages/Office/MoveTaskOrder/moveTaskOrderUnitTestData.js
  src/sagas/entities.test.js
  src/utils/orders.test.js
  swagger-def/definitions/OrdersType.yaml
  swagger-def/support.yaml
  swagger/ghc.yaml
  swagger/internal.yaml
  swagger/prime.yaml
  swagger/prime_v2.yaml
  swagger/prime_v3.yaml
  swagger/support.yaml
Labels: Mountain Movers, INTEGRATION

#14060 B-21524 adding space
  pkg/assets/notifications/templates/move_counseled_template.html
  pkg/assets/notifications/templates/move_counseled_template.txt
  pkg/notifications/move_counseled_test.go
Labels: ByteSize M&Ms, INTEGRATION
