Repository transcom/mymove, pull requests merged in 2024-12, with the labels that each got.

#14150 B 21137 Maintenance Page and Flag
  .envrc
  cmd/milmove/serve.go
  pkg/cli/maintenance.go
  pkg/cli/maintenance_test.go
  pkg/handlers/authentication/auth.go
  pkg/handlers/authentication/auth_test.go
  pkg/handlers/routing/base_routing_suite.go
  pkg/handlers/routing/routing_init.go
  src/pages/Maintenance/MaintenancePage.jsx
  src/pages/Maintenance/MaintenancePage.module.scss
  src/pages/Maintenance/MaintenancePage.test.jsx
  src/pages/Office/index.jsx
  src/pages/Office/index.test.jsx
  src/sagas/auth.js
  src/sagas/auth.test.js
  src/scenes/MyMove/index.jsx
  src/scenes/MyMove/index.test.js
  src/scenes/SystemAdmin/index.jsx
  src/store/auth/actions.js
  src/store/auth/reducer.js
  src/store/auth/reducer.test.js
  src/store/auth/selectors.js
Labels: G-Unit, MAIN

#14132 B 21542 main - DoD ID Does Not Populate in Services Counselor Queue
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/customer/search_customers.go
  pkg/gen/ghcapi/ghcoperations/move/search_moves.go
  pkg/gen/ghcapi/ghcoperations/queues/get_moves_queue_parameters.go
  pkg/gen/ghcapi/ghcoperations/queues/get_moves_queue_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/queues/get_payment_requests_queue_parameters.go
  pkg/gen/ghcapi/ghcoperations/queues/get_payment_requests_queue_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/queues/get_services_counseling_queue_parameters.go
  pkg/gen/ghcapi/ghcoperations/queues/get_services_counseling_queue_urlbuilder.go
  pkg/gen/ghcmessages/search_customer.go
  pkg/gen/ghcmessages/search_move.go
  pkg/handlers/ghcapi/customer.go
  pkg/handlers/ghcapi/customer_test.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/move.go
  pkg/handlers/ghcapi/move_test.go
  pkg/handlers/ghcapi/queues.go
  pkg/handlers/ghcapi/queues_test.go
  pkg/services/customer.go
  pkg/services/office_user/customer/customer_searcher.go
  pkg/services/office_user/customer/customer_searcher_test.go
  pkg/services/order.go
  pkg/services/order/order_fetcher.go
  pkg/services/payment_request.go
  pkg/services/payment_request/payment_request_list_fetcher.go
  pkg/services/payment_request/payment_request_list_fetcher_test.go
  playwright/tests/office/txo/tioFlows.spec.js
  playwright/tests/office/txo/tooFlows.spec.js
  src/components/Table/SearchResultsTable.jsx
  src/components/Table/SearchResultsTable.test.jsx
  src/pages/Office/HeadquartersQueues/HeadquartersQueues.test.jsx
  src/pages/Office/MoveQueue/MoveQueue.jsx
  src/pages/Office/MoveQueue/MoveQueue.test.jsx
  src/pages/Office/PaymentRequestQueue/PaymentRequestQueue.jsx
  src/pages/Office/PaymentRequestQueue/PaymentRequestQueue.test.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.jsx
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.test.jsx
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: G-Unit, MAIN

#14200 B-21538 add counseling office to closeout queue
  pkg/services/order/order_fetcher.go
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.jsx
Labels: G-Unit, MAIN

#14196 B-21637 deleted shipments longer affect ApproveOrRequestApproval func
  pkg/services/move/move_router.go
  pkg/services/move/move_router_test.go
Labels: G-Unit, MAIN

#14299 Move sequence creation from sequencer_test.go to migration
  migrations/app/migrations_manifest.txt
  migrations/app/secure/20241202163059_create_test_sequence_dev_env.up.sql
  pkg/db/sequence/sequencer_test.go
Labels: Mountain Movers, INTEGRATION

#14182 B 20991 main - Add Counseling Office Column and Filtering to TIO Queue
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/queues/get_payment_requests_queue_parameters.go
  pkg/gen/ghcapi/ghcoperations/queues/get_payment_requests_queue_urlbuilder.go
  pkg/gen/ghcmessages/queue_payment_request.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload_test.go
  pkg/handlers/ghcapi/queues.go
  pkg/services/payment_request.go
  pkg/services/payment_request/payment_request_list_fetcher.go
  src/pages/Office/PaymentRequestQueue/PaymentRequestQueue.jsx
  src/pages/Office/PaymentRequestQueue/PaymentRequestQueue.test.jsx
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.jsx
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: G-Unit, MAIN

#14289 INT-B-21568 UB Approved Service Items
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20241126222026_add_sort_column_to_re_service_items.up.sql
  pkg/models/re_service_item.go
  pkg/services/service_item/service_item_fetcher.go
Labels: INTEGRATION, Go-Rillaz

#14294 B 21680 int add indexes
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20241127133504_add_indexes_speed_up_counseling_offices.up.sql
Labels: G-Unit, INTEGRATION

#14218 B 21230 resolve canvas dependency v2 int
  .circleci/config.yml
  .eslintignore
  .gitignore
  .prettierignore
  Brewfile.local
  Dockerfile
  Dockerfile.dp3
  Dockerfile.e2e
  Dockerfile.local
  Dockerfile.reviewapp
  Makefile
  config-overrides.js
  config/env/review.app.env
  package.json
  pkg/handlers/routing/routing_init.go
  playwright/tests/office/documentViewer.spec.js
  public/static/react-file-viewer/.gitkeep
  scripts/README.md
  scripts/copy-react-file-viewer
  scripts/fetch-react-file-viewer-from-yarn
  scripts/rebuild-dependencies-without-binaries
  src/.eslintrc.js
  src/components/DocumentViewer/Content/Content.jsx
  src/pages/MyMove/AddOrders.test.jsx
  yarn.lock
Labels: Mountain Movers, INTEGRATION

#14235 INT-B-21636
  pkg/gen/pptasapi/embedded_spec.go
  pkg/gen/pptasmessages/p_p_t_a_s_report.go
  pkg/gen/pptasmessages/p_p_t_a_s_shipment.go
  pkg/services/pptas_report/pptas_report_list_fetcher.go
  swagger-def/definitions/PPTASReport.yaml
  swagger-def/definitions/PPTASShipment.yaml
  swagger/pptas.yaml
Labels: G-Unit, INTEGRATION

#14318 B 21464 int #3
  pkg/services/shipment_address_update/shipment_address_update_requester.go
Labels: Scrummy Bears, INTEGRATION

#14323 Int b 21509
  .dccache
Labels: INTEGRATION, Go-Rillaz

#14295 B-21548 Update service items BE
  pkg/services/mto_shipment/mto_shipment_updater.go
  pkg/services/mto_shipment/shipment_approver.go
  pkg/services/mto_shipment/shipment_approver_test.go
Labels: ByteSize M&Ms, INTEGRATION

#14322 B 21455 int
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.test.jsx
Labels: Scrummy Bears, INTEGRATION

#14314 MAIN B-21986
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20241203024453_add_ppm_max_incentive_column.up.sql
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/p_p_m_shipment.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/p_p_m_shipment.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/p_p_m_shipment.go
  pkg/gen/primev2api/embedded_spec.go
  pkg/gen/primev2messages/p_p_m_shipment.go
  pkg/gen/primev3api/embedded_spec.go
  pkg/gen/primev3messages/p_p_m_shipment.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/handlers/internalapi/mto_shipment_test.go
  pkg/handlers/primeapiv2/mto_shipment_test.go
  pkg/handlers/primeapiv3/mto_shipment_test.go
  pkg/models/ppm_shipment.go
  pkg/models/ppm_shipment_test.go
  pkg/models/worksheet_shipment.go
  pkg/services/mocks/PPMEstimator.go
  pkg/services/ppmshipment.go
  pkg/services/ppmshipment/ppm_estimator.go
  pkg/services/ppmshipment/ppm_estimator_test.go
  pkg/services/ppmshipment/ppm_shipment_creator.go
  pkg/services/ppmshipment/ppm_shipment_creator_test.go
  pkg/services/ppmshipment/ppm_shipment_updater.go
  pkg/services/ppmshipment/ppm_shipment_updater_test.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet_test.go
  playwright/tests/office/servicescounseling/servicesCounselingFlows.spec.js
  src/components/Office/ShipmentDisplay/ShipmentDisplay.jsx
  src/components/Office/ShipmentDisplay/ShipmentDisplay.test.jsx
  src/constants/shipments.js
  swagger-def/definitions/PPMShipment.yaml
  swagger-def/definitions/prime/PPMShipment.yaml
  swagger-def/definitions/prime/v3/PPMShipment.yaml
  swagger/ghc.yaml
  swagger/internal.yaml
  swagger/prime.yaml
  swagger/prime_v2.yaml
  swagger/prime_v3.yaml
Labels: Mountain Movers, MAIN

#14311 Main b 21113 customer address language
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/move/set_financial_review_flag.go
  pkg/gen/ghcmessages/m_t_o_shipment.go
  pkg/gen/ghcmessages/move.go
  pkg/gen/ghcmessages/shipment_address_update.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/mto_service_item/update_m_t_o_service_item.go
  pkg/gen/primeapi/primeoperations/mto_shipment/update_m_t_o_shipment_address.go
  pkg/gen/primeapi/primeoperations/mto_shipment/update_shipment_destination_address.go
  pkg/gen/primeclient/mto_service_item/mto_service_item_client.go
  pkg/gen/primeclient/mto_shipment/mto_shipment_client.go
  pkg/gen/primemessages/shipment_address_update.go
  pkg/gen/primemessages/update_shipment_destination_address.go
  pkg/gen/primev2api/embedded_spec.go
  pkg/gen/primev2messages/shipment_address_update.go
  pkg/gen/primev2messages/update_shipment_destination_address.go
  pkg/gen/primev3api/embedded_spec.go
  pkg/gen/primev3messages/create_p_p_m_shipment.go
  pkg/gen/primev3messages/shipment_address_update.go
  pkg/gen/primev3messages/update_p_p_m_shipment.go
  pkg/gen/primev3messages/update_shipment_destination_address.go
  playwright/tests/my/milmove/ppms/review.spec.js
  playwright/tests/my/mymove/hhg.spec.js
  src/components/Customer/BoatShipment/BoatShipmentConfirmationModal/BoatShipmentConfirmationModal.jsx
  src/components/Customer/BoatShipment/BoatShipmentForm/BoatShipmentForm.jsx
  src/components/Customer/EditOrdersForm/EditOrdersForm.jsx
  src/components/Customer/MtoShipmentForm/MtoShipmentForm.jsx
  src/components/Customer/MtoShipmentForm/MtoShipmentForm.test.jsx
  src/components/Customer/PPM/Booking/DateAndLocationForm/DateAndLocationForm.jsx
  src/components/Customer/PPM/Booking/DateAndLocationForm/DateAndLocationForm.test.jsx
  src/components/Customer/PPM/Closeout/AboutForm/AboutForm.jsx
  src/components/Customer/PPM/Closeout/AboutForm/AboutForm.test.jsx
  src/components/Customer/Review/ShipmentCard/BoatShipmentCard/BoatShipmentCard.test.jsx
  src/components/Customer/Review/ShipmentCard/DeliveryDisplay.jsx
  src/components/Customer/Review/ShipmentCard/HHGShipmentCard/HHGShipmentCard.test.jsx
  src/components/Customer/Review/ShipmentCard/MobileHomeShipmentCard/MobileHomeShipmentCard.test.jsx
  src/components/Customer/Review/ShipmentCard/NTSRShipmentCard/NTSRShipmentCard.test.jsx
  src/components/Customer/Review/ShipmentCard/NTSShipmentCard/NTSShipmentCard.test.jsx
  src/components/Customer/Review/ShipmentCard/PPMShipmentCard/PPMShipmentCard.jsx
  src/components/Customer/Review/ShipmentCard/PPMShipmentCard/PPMShipmentCard.test.jsx
  src/components/Customer/Review/ShipmentCard/PickupDisplay.jsx
  src/components/Office/DefinitionLists/NTSRShipmentInfoList.jsx
  swagger-def/definitions/MTOShipment.yaml
  swagger-def/definitions/ShipmentAddressUpdate.yaml
  swagger-def/ghc.yaml
  swagger-def/prime.yaml
  swagger-def/prime_v2.yaml
  swagger-def/prime_v3.yaml
  swagger/ghc.yaml
  swagger/prime.yaml
  swagger/prime_v2.yaml
  swagger/prime_v3.yaml
Labels: ByteSize M&Ms, MAIN

#13951 B-21367 Added validation rules for adding third address without a second address
  pkg/factory/move_factory.go
  pkg/factory/mto_shipment_factory.go
  pkg/gen/primev3api/embedded_spec.go
  pkg/gen/primev3messages/create_m_t_o_shipment.go
  pkg/handlers/primeapiv3/mto_shipment_test.go
  pkg/handlers/primeapiv3/payloads/payload_to_model.go
  pkg/handlers/primeapiv3/payloads/payload_to_model_test.go
  pkg/models/address.go
  pkg/models/address_test.go
  pkg/models/mto_shipments.go
  pkg/models/mto_shipments_test.go
  pkg/services/mto_shipment/mto_shipment_creator.go
  pkg/services/mto_shipment/mto_shipment_updater.go
  pkg/services/mto_shipment/mto_shipment_updater_test.go
  pkg/services/mto_shipment/rules.go
  pkg/services/mto_shipment/rules_test.go
  pkg/services/ppmshipment/ppm_shipment_creator.go
  pkg/services/ppmshipment/ppm_shipment_updater.go
  pkg/services/ppmshipment/rules.go
  pkg/services/ppmshipment/rules_test.go
  pkg/utils/utility.go
  pkg/utils/utility_test.go
  swagger-def/prime_v3.yaml
  swagger/prime_v3.yaml
Labels: G-Unit, MAIN

#14208 B 21455 main
  pkg/notifications/constants.go
  pkg/services/ppmshipment/ppm_estimator.go
  pkg/services/ppmshipment/ppm_estimator_test.go
  src/components/Office/RequestedShipments/RequestedShipments.test.jsx
  src/components/Office/RequestedShipments/RequestedShipmentsTestData.js
  src/components/Office/RequestedShipments/SubmittedRequestedShipments.jsx
  src/components/Office/RequestedShipments/SubmittedRequestedShipments.stories.jsx
  src/components/Office/ShipmentForm/ppmShipmentSchema.js
  src/pages/Office/MoveDetails/MoveDetails.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.test.jsx
Labels: Scrummy Bears, MAIN

#14303 Int b 21373 validation submit move details task order with files
  src/components/DocumentViewer/DocumentViewer.stories.jsx
  src/components/DocumentViewerFileManager/DocumentViewerFileManager.jsx
  src/components/DocumentViewerFileManager/DocumentViewerFileManager.test.jsx
  src/components/FileUpload/FileUpload.jsx
  src/components/Office/RequestedShipments/RequestedShipments.test.jsx
  src/components/Office/RequestedShipments/SubmittedRequestedShipments.jsx
  src/pages/Office/Orders/Orders.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.test.jsx
  src/pages/Office/ServicesCounselingOrders/ServicesCounselingOrders.jsx
  src/utils/validation.js
  src/utils/validation.test.js
Labels: INTEGRATION, Go-Rillaz

#14336 INT B-22057
  migrations/app/migrations_manifest.txt
  migrations/app/secure/20241204210208_retroactive_update_of_ppm_max_and_estimated_incentives_prd.up.sql
  pkg/factory/ppm_shipment_factory.go
  pkg/factory/ppm_shipment_factory_test.go
  pkg/handlers/adminapi/api.go
  pkg/handlers/adminapi/moves_test.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/move_task_order_test.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/handlers/ghcapi/orders_test.go
  pkg/handlers/internalapi/api.go
  pkg/handlers/internalapi/mto_shipment_test.go
  pkg/handlers/primeapi/api.go
  pkg/handlers/primeapi/move_task_order_test.go
  pkg/handlers/primeapi/mto_shipment_test.go
  pkg/handlers/primeapiv2/api.go
  pkg/handlers/primeapiv2/mto_shipment_test.go
  pkg/handlers/primeapiv3/api.go
  pkg/handlers/primeapiv3/mto_shipment_test.go
  pkg/handlers/supportapi/api.go
  pkg/handlers/supportapi/move_task_order_test.go
  pkg/services/move_task_order/move_task_order_fetcher.go
  pkg/services/move_task_order/move_task_order_updater.go
  pkg/services/move_task_order/move_task_order_updater_test.go
  pkg/services/mto_shipment/shipment_deleter_test.go
  pkg/services/ppmshipment/ppm_estimator.go
  pkg/testdatagen/scenario/shared.go
  src/components/Office/DefinitionLists/PPMShipmentInfoList.jsx
  src/components/Office/DefinitionLists/PPMShipmentInfoList.test.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
Labels: Mountain Movers, INTEGRATION

#14339 MAIN B-22057
  migrations/app/migrations_manifest.txt
  migrations/app/secure/20241204210208_retroactive_update_of_ppm_max_and_estimated_incentives_prd.up.sql
  pkg/factory/ppm_shipment_factory.go
  pkg/factory/ppm_shipment_factory_test.go
  pkg/handlers/adminapi/api.go
  pkg/handlers/adminapi/moves_test.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/move_task_order_test.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/handlers/ghcapi/orders_test.go
  pkg/handlers/internalapi/api.go
  pkg/handlers/internalapi/mto_shipment_test.go
  pkg/handlers/primeapi/api.go
  pkg/handlers/primeapi/move_task_order_test.go
  pkg/handlers/primeapi/mto_shipment_test.go
  pkg/handlers/primeapiv2/api.go
  pkg/handlers/primeapiv2/mto_shipment_test.go
  pkg/handlers/primeapiv3/api.go
  pkg/handlers/primeapiv3/mto_shipment_test.go
  pkg/handlers/supportapi/api.go
  pkg/handlers/supportapi/move_task_order_test.go
  pkg/services/move_task_order/move_task_order_fetcher.go
  pkg/services/move_task_order/move_task_order_updater.go
  pkg/services/move_task_order/move_task_order_updater_test.go
  pkg/services/mto_shipment/shipment_deleter_test.go
  pkg/services/ppmshipment/ppm_estimator.go
  pkg/testdatagen/scenario/shared.go
  src/components/Office/DefinitionLists/PPMShipmentInfoList.jsx
  src/components/Office/DefinitionLists/PPMShipmentInfoList.test.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
Labels: Mountain Movers, MAIN

#14325 remove exception for oconus-oconus
  .circleci/config.yml
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20241204155919_update_ordering_proc.up.sql
  scripts/ensure-go-test-coverage
Labels: Mountain Movers, INTEGRATION, database

#14329 B-21608 alaska update search counseling office query
  .circleci/config.yml
  .envrc
  config/env/demo.app-client-tls.env
  config/env/demo.app.env
  config/env/exp.app-client-tls.env
  config/env/exp.app.env
  config/env/loadtest.app-client-tls.env
  config/env/loadtest.app.env
  config/env/prd.app-client-tls.env
  config/env/prd.app.env
  config/env/stg.app-client-tls.env
  config/env/stg.app.env
  pkg/handlers/internalapi/duty_locations.go
  pkg/models/gbloc_aors.go
  pkg/models/jppso_regions.go
  pkg/models/re_oconus_rate_areas.go
  pkg/models/us_post_region_city.go
  pkg/models/us_post_region_city_test.go
  pkg/services/transportation_office/transportation_office_fetcher.go
  pkg/services/transportation_office/transportation_office_fetcher_test.go
Labels: Scrummy Bears, MAIN

#14334 B 21636 int
  pkg/services/pptas_report/pptas_report_list_fetcher.go
Labels: G-Unit, INTEGRATION

#14214 21680 counseling office timeout changes
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20241127133504_add_indexes_speed_up_counseling_offices.up.sql
  pkg/services/transportation_office/transportation_office_fetcher.go
  src/components/Customer/EditOrdersForm/EditOrdersForm.jsx
  src/components/Customer/EditOrdersForm/EditOrdersForm.test.jsx
  src/components/Customer/OrdersInfoForm/OrdersInfoForm.jsx
  src/components/Customer/OrdersInfoForm/OrdersInfoForm.test.jsx
  src/pages/MyMove/AddOrders.jsx
  src/pages/MyMove/EditOrders.jsx
Labels: G-Unit, MAIN

#14296 Happo int
  .github/workflows/happo-tests.yml
Labels: Mountain Movers, INTEGRATION

#14234 B-21636 Update PPTAS LOA Fields
  pkg/gen/pptasapi/embedded_spec.go
  pkg/gen/pptasmessages/p_p_t_a_s_report.go
  pkg/gen/pptasmessages/p_p_t_a_s_shipment.go
  pkg/services/pptas_report/pptas_report_list_fetcher.go
  swagger-def/definitions/PPTASReport.yaml
  swagger-def/definitions/PPTASShipment.yaml
  swagger/pptas.yaml
Labels: G-Unit, MAIN

#14310 B-21488: UB Allowance Warning Int
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20241127125545_add_excess_ub_weight_columns_to_move.up.sql
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/ghcapi/ghcoperations/order/acknowledge_excess_unaccompanied_baggage_weight_risk.go
  pkg/gen/ghcapi/ghcoperations/order/acknowledge_excess_unaccompanied_baggage_weight_risk_parameters.go
  pkg/gen/ghcapi/ghcoperations/order/acknowledge_excess_unaccompanied_baggage_weight_risk_responses.go
  pkg/gen/ghcapi/ghcoperations/order/acknowledge_excess_unaccompanied_baggage_weight_risk_urlbuilder.go
  pkg/gen/ghcmessages/move.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/excess_weight_record.go
  pkg/gen/primemessages/move_task_order.go
  pkg/gen/primev2api/embedded_spec.go
  pkg/gen/primev2messages/move_task_order.go
  pkg/gen/primev3api/embedded_spec.go
  pkg/gen/primev3messages/move_task_order.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload_test.go
  pkg/handlers/ghcapi/orders.go
  pkg/handlers/ghcapi/orders_test.go
  pkg/handlers/primeapi/payloads/model_to_payload.go
  pkg/handlers/primeapi/payloads/model_to_payload_test.go
  pkg/handlers/primeapiv2/payloads/model_to_payload.go
  pkg/handlers/primeapiv2/payloads/model_to_payload_test.go
  pkg/handlers/primeapiv3/payloads/model_to_payload.go
  pkg/handlers/primeapiv3/payloads/model_to_payload_test.go
  pkg/models/move.go
  pkg/services/event/ghc_endpoint.go
  pkg/services/mocks/ExcessWeightRiskManager.go
  pkg/services/move/move_weights.go
  pkg/services/move/move_weights_test.go
  pkg/services/mto_shipment/mto_shipment_updater.go
  pkg/services/order.go
  pkg/services/order/excess_weight_risk_manager.go
  pkg/services/order/excess_weight_risk_manager_test.go
  playwright/tests/office/servicescounseling/servicesCounselingProGearTickets.spec.js
  playwright/tests/office/txo/tooFlows.spec.js
  src/constants/MoveHistory/EventTemplates/AcknowledgeExcessUnaccompaniedBaggageWeightRisk/acknowledgeExcessUnaccompaniedBaggageWeightRisk.jsx
  src/constants/MoveHistory/EventTemplates/AcknowledgeExcessUnaccompaniedBaggageWeightRisk/acknowledgeExcessUnaccompaniedBaggageWeightRisk.test.jsx
  src/constants/MoveHistory/EventTemplates/index.js
  src/constants/MoveHistory/UIDisplay/Operations.js
  src/pages/Office/MoveDetails/MoveDetails.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.test.jsx
  src/pages/Office/MoveTaskOrder/moveTaskOrderUnitTestData.js
  src/services/ghcApi.js
  swagger-def/definitions/ExcessWeightRecord.yaml
  swagger-def/definitions/prime/MoveTaskOrder.yaml
  swagger-def/definitions/prime/v2/MoveTaskOrder.yaml
  swagger-def/definitions/prime/v3/MoveTaskOrder.yaml
  swagger-def/ghc.yaml
  swagger/ghc.yaml
  swagger/prime.yaml
  swagger/prime_v2.yaml
  swagger/prime_v3.yaml
Labels: Mountain Movers, INTEGRATION

#14331 B 21464 int
  pkg/iws/rbs_error_test.go
  pkg/models/mto_service_items.go
  pkg/services/mto_service_item/mto_service_item_updater.go
  pkg/services/shipment_address_update/shipment_address_update_requester.go
Labels: Scrummy Bears, INTEGRATION

#14343 add canvas binary build step to happo
  .github/workflows/happo-tests-main.yml
  .github/workflows/happo-tests.yml
Labels: Mountain Movers, INTEGRATION

#14285 INT-B-21577 Limit UB weight allowance based on Student Travel order type.
  pkg/models/entitlements.go
  pkg/models/entitlements_test.go
Labels: ByteSize M&Ms, INTEGRATION

#14321 INT - B-21415 Prime Sim update for payment requests
  pkg/payment_request/service_param_value_lookups/service_param_value_lookups.go
  pkg/services/move_task_order/move_task_order_fetcher.go
  pkg/services/move_task_order/move_task_order_fetcher_test.go
  src/components/PrimeUI/ServiceItem/ServiceItem.jsx
  src/components/PrimeUI/ServiceItem/ServiceItem.test.jsx
Labels: ByteSize M&Ms, INTEGRATION

#14333 B 21490 INT - Storybook/Happo Fixes
  src/components/DocumentViewer/DocumentViewer.stories.jsx
  src/components/Office/GblocSwitcher/GblocSwitcher.jsx
  src/components/Office/GblocSwitcher/GblocSwitcher.stories.jsx
  src/components/Table/TableQueue.stories.jsx
Labels: Scrummy Bears, INTEGRATION

#14121 MAIN B-21374 ub fields main
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20241018091722_oconus-entitlements-enhancement.up.sql
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/counseling_update_allowance_payload.go
  pkg/gen/ghcmessages/create_orders.go
  pkg/gen/ghcmessages/entitlements.go
  pkg/gen/ghcmessages/update_allowance_payload.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/create_update_orders.go
  pkg/gen/internalmessages/entitlement.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload_test.go
  pkg/handlers/ghcapi/orders.go
  pkg/handlers/ghcapi/orders_test.go
  pkg/handlers/internalapi/orders.go
  pkg/handlers/internalapi/orders_test.go
  pkg/models/ghc_entitlements.go
  pkg/models/ghc_entitlements_test.go
  pkg/services/order/order_updater.go
  pkg/services/order/order_updater_test.go
  src/components/Customer/EditOrdersForm/EditOrdersForm.jsx
  src/components/Customer/EditOrdersForm/EditOrdersForm.module.scss
  src/components/Customer/EditOrdersForm/EditOrdersForm.test.jsx
  src/components/Customer/OrdersInfoForm/OrdersInfoForm.jsx
  src/components/Customer/OrdersInfoForm/OrdersInfoForm.module.scss
  src/components/Customer/OrdersInfoForm/OrdersInfoForm.test.jsx
  src/components/Customer/Review/OrdersTable/OrdersTable.jsx
  src/components/Customer/Review/Summary/Summary.jsx
  src/components/Office/AddOrdersForm/AddOrdersForm.jsx
  src/components/Office/AddOrdersForm/AddOrdersForm.module.scss
  src/components/Office/AddOrdersForm/AddOrdersForm.test.jsx
  src/components/Office/AllowancesDetailForm/AllowancesDetailForm.jsx
  src/components/Office/AllowancesDetailForm/AllowancesDetailForm.test.jsx
  src/components/Office/DefinitionLists/AllowancesList.jsx
  src/components/Office/DefinitionLists/AllowancesList.test.jsx
  src/pages/MyMove/AddOrders.jsx
  src/pages/MyMove/AddOrders.test.jsx
  src/pages/MyMove/EditOrders.jsx
  src/pages/MyMove/EditOrders.test.jsx
  src/pages/Office/MoveAllowances/MoveAllowances.jsx
  src/pages/Office/MoveDetails/MoveDetails.jsx
  src/pages/Office/ServicesCounselingAddOrders/ServicesCounselingAddOrders.jsx
  src/pages/Office/ServicesCounselingAddOrders/ServicesCounselingAddOrders.test.jsx
  src/pages/Office/ServicesCounselingMoveAllowances/ServicesCounselingMoveAllowances.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
  src/types/order.js
  src/utils/formatters.js
  src/utils/formatters.test.js
  swagger-def/ghc.yaml
  swagger-def/internal.yaml
  swagger/ghc.yaml
  swagger/internal.yaml
Labels: Mountain Movers, MAIN

#14338 Main-B-21568 show ub preapproved service items
  Makefile
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20241126222026_add_sort_column_to_re_service_items.up.sql
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/ghcapi/ghcoperations/re_service_items/get_all_re_service_items.go
  pkg/gen/ghcapi/ghcoperations/re_service_items/get_all_re_service_items_parameters.go
  pkg/gen/ghcapi/ghcoperations/re_service_items/get_all_re_service_items_responses.go
  pkg/gen/ghcapi/ghcoperations/re_service_items/get_all_re_service_items_urlbuilder.go
  pkg/gen/ghcmessages/re_service_item.go
  pkg/gen/ghcmessages/re_service_items.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload_test.go
  pkg/handlers/ghcapi/re_service_items.go
  pkg/models/re_service_item.go
  pkg/services/mocks/ServiceItemListFetcher.go
  pkg/services/re_service_item.go
  pkg/services/service_item/service_item_fetcher.go
  pkg/services/service_item/service_item_fetcher_test.go
  pkg/services/service_item/service_item_service_test.go
  src/components/Office/ShipmentApprovalPreview/ShipmentApprovalPreview.jsx
  src/components/Office/ShipmentServiceItemsTable/ShipmentServiceItemsTable.jsx
  src/components/Office/ShipmentServiceItemsTable/ShipmentServiceItemsTable.test.jsx
  src/components/Office/ShipmentServiceItemsTable/shipmentServiceItemsTable.stories.jsx
  src/constants/serviceItems.js
  src/services/ghcApi.js
  src/shared/Entities/schema.js
  src/shared/constants.js
  swagger-def/definitions/ReServiceItem.yaml
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: MAIN, Go-Rillaz

#14124 B-21375 UB Allowance Calculation - MAIN
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20241031163018_create_ub_allowances_table.up.sql
  pkg/factory/shared.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/entitlements.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/entitlement.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/entitlements.go
  pkg/gen/primev2api/embedded_spec.go
  pkg/gen/primev2messages/entitlements.go
  pkg/gen/primev3api/embedded_spec.go
  pkg/gen/primev3messages/entitlements.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload_test.go
  pkg/handlers/ghcapi/orders.go
  pkg/handlers/internalapi/orders.go
  pkg/handlers/internalapi/orders_test.go
  pkg/models/entitlements.go
  pkg/models/entitlements_test.go
  pkg/models/ghc_entitlements.go
  pkg/models/service_member.go
  pkg/models/ub_allowances.go
  pkg/notifications/move_submitted.go
  pkg/services/order/order_updater.go
  scripts/db-truncate
  swagger-def/definitions/prime/Entitlements.yaml
  swagger-def/ghc.yaml
  swagger-def/internal.yaml
  swagger/ghc.yaml
  swagger/internal.yaml
  swagger/prime.yaml
  swagger/prime_v2.yaml
  swagger/prime_v3.yaml
Labels: Mountain Movers, MAIN

#13990 MAIN-B-21509
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20241023184337_create_ports_table.up.sql
  migrations/app/schema/20241023184350_create_port_locations_table.up.sql
  migrations/app/schema/20241023184437_insert_ports.up.sql
  migrations/app/schema/20241120221040_change_port_location_fk_to_correct_table.up.sql
  pkg/models/mto_service_items.go
  pkg/models/mto_service_items_test.go
  pkg/models/port.go
  pkg/models/port_location.go
  pkg/models/port_location_test.go
  scripts/db-truncate
Labels: MAIN, Go-Rillaz, database

#14307 B 21626 int - Update export to view Assigned column all queues
  src/pages/Office/MoveQueue/MoveQueue.jsx
  src/pages/Office/PaymentRequestQueue/PaymentRequestQueue.jsx
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.jsx
Labels: G-Unit, INTEGRATION

#14337 B-22037: Server Error Review Service Items Page
  pkg/services/payment_request/payment_request_shipments_sit_balance.go
  pkg/services/payment_request/payment_request_shipments_sit_balance_test.go
Labels: Mountain Movers, INTEGRATION

#14332 Main b 21671 db create re fsc multipliers
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20241115214553_create_re_fsc_multipliers_table.up.sql
  pkg/models/re_fsc_multipliers.go
  scripts/db-truncate
Labels: MAIN, Go-Rillaz, database

#14342 B 21682 store total dependents main
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20241122155416_total_dependents_calculation.up.sql
  pkg/handlers/internalapi/orders.go
  pkg/handlers/internalapi/orders_test.go
  pkg/models/ghc_entitlements.go
  pkg/models/ghc_entitlements_test.go
Labels: Mountain Movers, MAIN

#14240 B 21230 resolve canvas dependency v2 main
  .circleci/config.yml
  .eslintignore
  .github/workflows/happo-tests-main.yml
  .github/workflows/happo-tests.yml
  .gitignore
  .prettierignore
  Brewfile.local
  Dockerfile
  Dockerfile.dp3
  Dockerfile.e2e
  Dockerfile.local
  Dockerfile.reviewapp
  Makefile
  config-overrides.js
  config/env/review.app.env
  package.json
  pkg/handlers/routing/routing_init.go
  playwright/tests/office/documentViewer.spec.js
  public/static/react-file-viewer/.gitkeep
  scripts/README.md
  scripts/copy-react-file-viewer
  scripts/fetch-react-file-viewer-from-yarn
  scripts/rebuild-dependencies-without-binaries
  src/.eslintrc.js
  src/components/DocumentViewer/Content/Content.jsx
  src/pages/MyMove/AddOrders.test.jsx
  yarn.lock
Labels: Mountain Movers, MAIN

#14100 MAIN B-21376
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/counseling_update_allowance_payload.go
  pkg/gen/ghcmessages/update_allowance_payload.go
  pkg/handlers/internalapi/orders_test.go
  src/components/Customer/MtoShipmentForm/MtoShipmentForm.jsx
  src/components/Customer/MtoShipmentForm/MtoShipmentForm.test.jsx
  src/pages/MyMove/Home/MoveHome.jsx
  src/pages/MyMove/Home/MoveHome.test.jsx
  src/pages/MyMove/MovingInfo.jsx
  src/pages/MyMove/MovingInfo.stories.jsx
  src/pages/MyMove/MovingInfo.test.jsx
  src/store/entities/selectors.js
  src/store/entities/selectors.test.js
  src/utils/formatters.js
  src/utils/formatters.test.js
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: Mountain Movers, MAIN

#14335 B 21393 - Consolidated PPM Allowable Weights
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20241008133341_consolidate_allowable_weight_in_ppm_shipments.up.sql
  pkg/factory/ppm_shipment_factory.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/p_p_m_shipment.go
  pkg/gen/ghcmessages/update_p_p_m_shipment.go
  pkg/gen/ghcmessages/update_weight_ticket.go
  pkg/gen/ghcmessages/weight_ticket.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/p_p_m_shipment.go
  pkg/gen/internalmessages/update_weight_ticket.go
  pkg/gen/internalmessages/weight_ticket.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/internal/payloads/payload_to_model.go
  pkg/handlers/ghcapi/ppm_closeout.go
  pkg/models/ppm_shipment.go
  pkg/models/ppm_shipment_test.go
  pkg/models/weight_ticket.go
  pkg/models/weight_ticket_test.go
  pkg/services/ppm_closeout/ppm_closeout.go
  pkg/services/ppm_closeout/ppm_closeout_test.go
  pkg/services/ppmshipment/ppm_estimator.go
  pkg/services/ppmshipment/ppm_estimator_test.go
  pkg/services/ppmshipment/ppm_shipment_new_submitter.go
  pkg/services/ppmshipment/ppm_shipment_new_submitter_test.go
  pkg/services/ppmshipment/ppm_shipment_updated_submitter.go
  pkg/services/ppmshipment/ppm_shipment_updated_submitter_test.go
  pkg/services/ppmshipment/ppm_shipment_updater_test.go
  pkg/services/ppmshipment/validation.go
  pkg/services/weight_ticket/weight_ticket_updater.go
  pkg/services/weight_ticket/weight_ticket_updater_test.go
  pkg/testdatagen/scenario/shared.go
  playwright/tests/office/servicescounseling/servicesCounselingFlows.spec.js
  playwright/tests/office/servicescounseling/servicesCounselingWeightTickets.spec.js
  src/components/Office/PPM/EditNetWeights/EditPPMNetWeight.jsx
  src/components/Office/PPM/PPMHeaderSummary/EditPPMHeaderSummaryModal.jsx
  src/components/Office/PPM/PPMHeaderSummary/EditPPMHeaderSummaryModal.test.jsx
  src/components/Office/PPM/PPMHeaderSummary/HeaderSection.jsx
  src/components/Office/PPM/PPMHeaderSummary/HeaderSection.test.jsx
  src/components/Office/PPM/PPMHeaderSummary/PPMHeaderSummary.jsx
  src/components/Office/PPM/PPMHeaderSummary/PPMHeaderSummary.test.jsx
  src/components/Office/PPM/ReviewDocumentsSidePanel/ReviewDocumentsSidePanel.jsx
  src/components/Office/PPM/ReviewWeightTicket/ReviewWeightTicket.jsx
  src/components/Office/PPM/ReviewWeightTicket/ReviewWeightTicket.test.jsx
  src/constants/MoveHistory/Database/FieldMappings.js
  src/constants/MoveHistory/Database/WeightFields.js
  src/icons.js
  src/pages/Office/PPM/ReviewDocuments/ReviewDocuments.test.jsx
  src/shared/ToolTip/ToolTip.jsx
  src/shared/ToolTip/ToolTip.module.scss
  src/shared/ToolTip/ToolTip.stories.jsx
  src/shared/ToolTip/ToolTip.test.jsx
  src/utils/shipmentWeights.js
  swagger-def/definitions/PPMShipment.yaml
  swagger-def/definitions/WeightTicket.yaml
  swagger-def/ghc.yaml
  swagger-def/internal.yaml
  swagger/ghc.yaml
  swagger/internal.yaml
Labels: Scrummy Bears, MAIN

#14288 B-21667 & B-21487 MAIN
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/entitlements.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/entitlements.go
  pkg/gen/primev2api/embedded_spec.go
  pkg/gen/primev2messages/entitlements.go
  pkg/gen/primev3api/embedded_spec.go
  pkg/gen/primev3messages/entitlements.go
  pkg/gen/supportapi/embedded_spec.go
  pkg/gen/supportmessages/entitlement.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload_test.go
  pkg/handlers/primeapi/payloads/model_to_payload.go
  pkg/handlers/primeapi/payloads/model_to_payload_test.go
  pkg/handlers/primeapiv2/payloads/model_to_payload.go
  pkg/handlers/primeapiv2/payloads/model_to_payload_test.go
  pkg/handlers/primeapiv3/payloads/model_to_payload.go
  pkg/handlers/primeapiv3/payloads/model_to_payload_test.go
  pkg/handlers/supportapi/internal/payloads/model_to_payload.go
  pkg/handlers/supportapi/internal/payloads/model_to_payload_test.go
  src/components/Office/DefinitionLists/AllowancesList.jsx
  src/components/Office/DefinitionLists/AllowancesList.stories.jsx
  src/components/Office/DefinitionLists/AllowancesList.test.jsx
  src/components/Office/ShipmentForm/ShipmentForm.jsx
  src/components/Office/ShipmentForm/ShipmentForm.stories.jsx
  src/components/Office/ShipmentForm/ShipmentForm.test.jsx
  src/content/shipments.js
  src/pages/Office/MoveDetails/MoveDetails.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
  swagger-def/definitions/prime/Entitlements.yaml
  swagger-def/ghc.yaml
  swagger-def/support.yaml
  swagger/ghc.yaml
  swagger/prime.yaml
  swagger/prime_v2.yaml
  swagger/prime_v3.yaml
  swagger/support.yaml
Labels: Mountain Movers, MAIN

#14290 INT B-21683 - estimated pricing stored procedure
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20241121205457_create_estimated_pricing_stored_proc_for_intl_shipments.up.sql
  pkg/models/mto_shipments.go
Labels: Mountain Movers, INTEGRATION

#14370 MAIN B-21846
  src/components/Office/RequestedShipments/ApprovedRequestedShipments.jsx
  src/components/Office/RequestedShipments/RequestedShipments.test.jsx
  src/components/Office/RequestedShipments/SubmittedRequestedShipments.jsx
  src/components/Office/ShipmentForm/ShipmentForm.jsx
  src/components/Office/ShipmentForm/ShipmentForm.test.jsx
  src/components/ShipmentTag/ShipmentTag.module.scss
  src/pages/Office/AddShipment/AddShipment.jsx
  src/pages/Office/ServicesCounselingAddShipment/ServicesCounselingAddShipment.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.test.jsx
Labels: Mountain Movers, MAIN

#14376 B 21169 int logging
  pkg/services/address/address_lookup.go
Labels: Scrummy Bears, INTEGRATION

#14365 INT - B-22083 AOA Packet Won't Download Due to Deleted Order Record
  pkg/models/document.go
  pkg/models/document_test.go
Labels: ByteSize M&Ms, INTEGRATION

#14328 B-21676 exclude nsra15 duty locations
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20241119163933_set_inactive_NSRA15_oconus_rate_areas.up.sql
  pkg/models/duty_location.go
  pkg/models/duty_location_test.go
Labels: Scrummy Bears, MAIN, database

#14359 B 21975 int
  src/constants/MoveHistory/EventTemplates/ApproveShipment/approveShipmentUpdateAllowances.jsx
  src/constants/MoveHistory/EventTemplates/ApproveShipment/approveShipmentUpdateAllowances.test.jsx
  src/constants/MoveHistory/EventTemplates/UpdateBillableWeight/updateBillableWeight.jsx
  src/constants/MoveHistory/EventTemplates/UpdateBillableWeight/updateBillableWeightAsTIO.jsx
  src/constants/MoveHistory/EventTemplates/UpdateBillableWeight/updateBillableWeightRemarksAsTIO.jsx
  src/constants/MoveHistory/EventTemplates/UpdateMTOShipment/updateMTOShipmentUpdateAllowance.jsx
  src/constants/MoveHistory/EventTemplates/UpdateMTOShipment/updateMTOShipmentUpdateAllowance.test.jsx
  src/constants/MoveHistory/EventTemplates/index.js
  src/utils/formatters.js
Labels: Scrummy Bears, INTEGRATION, frontend

#14217 B 20972 tio ppm
  playwright/tests/office/txo/tioFlows.spec.js
  src/components/Office/PPM/PPMHeaderSummary/PPMHeaderSummary.jsx
  src/components/Office/PPM/PPMHeaderSummary/PPMHeaderSummary.test.jsx
  src/components/Office/PPM/ReviewDocumentsSidePanel/ReviewDocumentsSidePanel.jsx
  src/components/Office/PPM/ReviewDocumentsSidePanel/ReviewDocumentsSidePanel.module.scss
  src/components/Office/PPM/ReviewExpense/ReviewExpense.jsx
  src/components/Office/PPM/ReviewExpense/ReviewExpense.stories.jsx
  src/components/Office/PPM/ReviewProGear/ReviewProGear.jsx
  src/components/Office/PPM/ReviewProGear/ReviewProGear.stories.jsx
  src/components/Office/PPM/ReviewProGear/ReviewProGear.test.jsx
  src/components/Office/PPM/ReviewWeightTicket/ReviewWeightTicket.jsx
  src/components/Office/PPM/ReviewWeightTicket/ReviewWeightTicket.stories.jsx
  src/components/Office/PPM/ReviewWeightTicket/ReviewWeightTicket.test.jsx
  src/components/Office/WeightSummary/WeightSummary.jsx
  src/hooks/queries.js
  src/hooks/queries.test.jsx
  src/pages/Office/DocumentViewerSidebar/DocumentViewerSidebar.module.scss
  src/pages/Office/PPM/ReviewDocuments/ReviewDocuments.jsx
  src/pages/Office/ReviewBillableWeight/ReviewBillableWeight.jsx
  src/pages/Office/ReviewBillableWeight/ReviewBillableWeight.test.jsx
Labels: Scrummy Bears, MAIN

#14385 B 21353 price escalations main
  pkg/models/re_contract_year.go
  pkg/services/ghcrateengine/domestic_origin_pricer_test.go
  pkg/services/ghcrateengine/pricer_helpers.go
  pkg/services/ghcrateengine/pricer_helpers_test.go
  pkg/services/ghcrateengine/pricer_query_helpers.go
  pkg/services/ghcrateengine/pricer_query_helpers_test.go
  pkg/testdatagen/make_re_contract_year.go
Labels: Mountain Movers, MAIN

#14378 B21575-INT3B-add order type
  scripts/db-truncate
  src/components/Customer/EditOrdersForm/EditOrdersForm.jsx
Labels: ByteSize M&Ms, INTEGRATION

#14387 B 21169 int pr3
  pkg/handlers/ghcapi/addresses.go
  pkg/handlers/internalapi/addresses.go
  pkg/services/address.go
  pkg/services/address/address_lookup.go
  pkg/services/address/address_lookup_test.go
  pkg/services/mocks/VLocation.go
  pkg/services/move_task_order/move_task_order_fetcher.go
Labels: Scrummy Bears, INTEGRATION

#14324 B-21170-INT - Location Lookup for Prime Sim (Review After B-21168-INT & B-21169-INT)
  playwright/tests/office/primesimulator/primeSimulatorFlows.spec.js
  src/components/PrimeUI/CreateShipmentServiceItemForm/OriginSITServiceItemForm.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentCreateForm.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentCreateForm.test.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdate.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdate.test.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdateAddress.test.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdateAddressForm.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdateAddressForm.test.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdateDestinationAddress.test.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdateDestinationAddressForm.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdateDestinationAddressForm.test.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdateForm.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdatePPMForm.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdatePPMForm.test.jsx
  src/utils/formatters.js
  src/utils/validation.js
Labels: Scrummy Bears, INTEGRATION

#14298 INT-B-21819 prime 3rd address errors
  pkg/handlers/primeapiv3/mto_shipment.go
  pkg/handlers/primeapiv3/mto_shipment_test.go
  pkg/handlers/primeapiv3/payloads/payload_to_model.go
  pkg/handlers/primeapiv3/payloads/payload_to_model_test.go
Labels: G-Unit, INTEGRATION

#14361 MAIN - B-22083 AOA Packet Won't Download Due to Deleted Order Record
  pkg/models/document.go
  pkg/models/document_test.go
Labels: ByteSize M&Ms, MAIN

#14383 Change to using order type variable for comparison instead of pointer.
  pkg/models/entitlements.go
Labels: ByteSize M&Ms, INTEGRATION

#14127 B-21581: Incorrect GBLOC on Move When Origin Duty Location is Updated
  pkg/handlers/ghcapi/internal/payloads/model_to_payload_test.go
  pkg/handlers/internalapi/orders.go
  pkg/handlers/internalapi/orders_test.go
  pkg/models/order.go
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/testharness/dispatch.go
  pkg/testdatagen/testharness/make_move.go
  playwright/tests/office/servicescounseling/servicesCounselingFlows.spec.js
  playwright/tests/utils/testharness.js
Labels: ByteSize M&Ms, INTEGRATION

#14345 B-21685 INT - TOO can create shipment even when no shipments exist on move
  scripts/db-truncate
  src/pages/Office/MoveDetails/MoveDetails.jsx
  src/pages/Office/MoveDetails/MoveDetails.test.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.module.scss
Labels: Mountain Movers, INTEGRATION

#14386 B-21548 Update service items MAIN
  pkg/services/mto_shipment/mto_shipment_updater.go
  pkg/services/mto_shipment/shipment_approver.go
  pkg/services/mto_shipment/shipment_approver_test.go
Labels: ByteSize M&Ms, MAIN

#14401 B 21169 int pr4
  pkg/services/move_task_order/move_task_order_fetcher.go
Labels: Scrummy Bears, INTEGRATION

#14206 B21575-main3-add_order_types
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20241111221400_add_new_order_types.up.sql
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/orders_type.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/orders_type.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/orders_type.go
  pkg/gen/primev2api/embedded_spec.go
  pkg/gen/primev2messages/orders_type.go
  pkg/gen/primev3api/embedded_spec.go
  pkg/gen/primev3messages/orders_type.go
  pkg/gen/supportapi/embedded_spec.go
  pkg/gen/supportmessages/orders_type.go
  src/components/Customer/EditOrdersForm/EditOrdersForm.jsx
  src/components/Customer/EditOrdersForm/EditOrdersForm.test.jsx
  src/components/Customer/OrdersInfoForm/OrdersInfoForm.jsx
  src/components/Customer/OrdersInfoForm/OrdersInfoForm.test.jsx
  src/constants/orders.js
  src/pages/MyMove/EditOrders.jsx
  src/pages/MyMove/PPM/Closeout/Feedback/Feedback.test.jsx
  swagger-def/definitions/OrdersType.yaml
  swagger-def/support.yaml
  swagger/ghc.yaml
  swagger/internal.yaml
  swagger/prime.yaml
  swagger/prime_v2.yaml
  swagger/prime_v3.yaml
  swagger/support.yaml
Labels: ByteSize M&Ms, MAIN

#14320 MAIN - B-21415 Prime Sim update for payment requests
  pkg/payment_request/service_param_value_lookups/service_param_value_lookups.go
  pkg/services/move_task_order/move_task_order_fetcher.go
  pkg/services/move_task_order/move_task_order_fetcher_test.go
  src/components/PrimeUI/ServiceItem/ServiceItem.jsx
  src/components/PrimeUI/ServiceItem/ServiceItem.test.jsx
Labels: ByteSize M&Ms, MAIN

#14381 B-21686: Allow Prime Sim User to update estimated weight and actual weight independently
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdate.test.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdateForm.jsx
Labels: Mountain Movers, INTEGRATION

#14357 B 21536 int
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20241210143143_redefine_mto_shipment_audit_table.up.sql
  pkg/assets/sql_scripts/move_history_fetcher.sql
  pkg/models/port_test.go
  pkg/services/shipment_address_update/shipment_address_update_requester.go
  src/constants/MoveHistory/Database/BooleanFields.js
  src/constants/MoveHistory/Database/FieldMappings.js
Labels: Scrummy Bears, INTEGRATION

#14379 INT B-21940
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/ghcapi/ghcoperations/queues/get_destination_requests_queue.go
  pkg/gen/ghcapi/ghcoperations/queues/get_destination_requests_queue_parameters.go
  pkg/gen/ghcapi/ghcoperations/queues/get_destination_requests_queue_responses.go
  pkg/gen/ghcapi/ghcoperations/queues/get_destination_requests_queue_urlbuilder.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/queues.go
  pkg/handlers/ghcapi/queues_test.go
  pkg/services/mocks/OrderFetcher.go
  pkg/services/order.go
  pkg/services/order/order_fetcher.go
  pkg/services/order/order_fetcher_test.go
  src/constants/routes.js
  src/hooks/queries.js
  src/pages/Office/MoveQueue/MoveQueue.jsx
  src/pages/Office/MoveQueue/MoveQueue.test.jsx
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.jsx
  src/services/ghcApi.js
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: Mountain Movers, INTEGRATION

#14350 B-21976-INT Check NTS/NTSR feature flag in office app
  src/components/Office/RequestedShipments/ApprovedRequestedShipments.jsx
  src/components/Office/RequestedShipments/SubmittedRequestedShipments.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
Labels: G-Unit, INTEGRATION, frontend

#14399 INT-B-21636
  pkg/gen/pptasapi/embedded_spec.go
  pkg/gen/pptasmessages/p_p_t_a_s_report.go
  pkg/gen/pptasmessages/p_p_t_a_s_shipment.go
  pkg/services/pptas_report/pptas_report_list_fetcher.go
  swagger-def/definitions/PPTASReport.yaml
  swagger-def/definitions/PPTASShipment.yaml
  swagger/pptas.yaml
Labels: G-Unit, INTEGRATION

#14409 MAIN B-21578 - Add overall weight limit & Add TOO, TIO, Prime Functions
  pkg/factory/entitlement_factory.go
  pkg/factory/entitlement_factory_test.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/move_queue_item.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/orders.go
  pkg/handlers/internalapi/move_queue_items.go
  pkg/handlers/internalapi/orders.go
  pkg/handlers/internalapi/orders_test.go
  pkg/handlers/primeapi/payloads/model_to_payload.go
  pkg/handlers/primeapi/payloads/model_to_payload_test.go
  pkg/handlers/primeapiv2/payloads/model_to_payload.go
  pkg/handlers/primeapiv2/payloads/model_to_payload_test.go
  pkg/handlers/primeapiv3/payloads/model_to_payload.go
  pkg/handlers/primeapiv3/payloads/model_to_payload_test.go
  pkg/handlers/supportapi/internal/payloads/model_to_payload.go
  pkg/handlers/supportapi/internal/payloads/model_to_payload_test.go
  pkg/models/entitlements.go
  pkg/models/entitlements_test.go
  pkg/models/ghc_entitlements.go
  pkg/models/ghc_entitlements_test.go
  pkg/models/queue.go
  pkg/notifications/move_submitted.go
  pkg/services/move/move_weights.go
  pkg/services/order/order_updater.go
  pkg/services/pptas_report/pptas_report_list_fetcher.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet_test.go
  pkg/testdatagen/make_entitlement.go
  swagger-def/internal.yaml
  swagger/internal.yaml
Labels: ByteSize M&Ms, MAIN

#14416 B-21636 fix pptas data and reweigh check
  pkg/gen/pptasapi/embedded_spec.go
  pkg/gen/pptasmessages/p_p_t_a_s_report.go
  pkg/gen/pptasmessages/p_p_t_a_s_shipment.go
  pkg/services/pptas_report/pptas_report_list_fetcher.go
  swagger-def/definitions/PPTASReport.yaml
  swagger-def/definitions/PPTASShipment.yaml
  swagger/pptas.yaml
Labels: G-Unit, MAIN

#14421 B-21636-INT added check before TAC query
  pkg/services/pptas_report/pptas_report_list_fetcher.go
Labels: G-Unit, INTEGRATION

#14423 added check before TAC query
  pkg/services/pptas_report/pptas_report_list_fetcher.go
Labels: G-Unit, MAIN

#14417 INT B-22122
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20241217180136_add_AK_zips_to_zip3_distances.up.sql
Labels: Mountain Movers, INTEGRATION

#14428 B-21685 MAIN: TOO can create shipment even when no shipments exist on move
  src/pages/Office/MoveDetails/MoveDetails.jsx
  src/pages/Office/MoveDetails/MoveDetails.test.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.module.scss
Labels: Mountain Movers, MAIN

#14431 B-22037: Server Error Review Service Items Page
  pkg/services/payment_request/payment_request_shipments_sit_balance.go
  pkg/services/payment_request/payment_request_shipments_sit_balance_test.go
Labels: Mountain Movers, MAIN

#14429 B-21686: Allow Prime Sim User to update estimated weight and actual weight independently
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdate.test.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdateForm.jsx
Labels: Mountain Movers, MAIN

#14410 INT-B-21506
  pkg/models/port_location.go
  pkg/models/port_location_test.go
Labels: INTEGRATION, Go-Rillaz, backend

#14396 Limit UB weight allowance based on Studen Travel order type.
  pkg/models/entitlements.go
  pkg/models/entitlements_test.go
Labels: ByteSize M&Ms, MAIN

#14358 B 21533 int HQ role with Safety Move privs
  .gitlab-ci.yml
  Dockerfile.migrations
  Makefile
  package.json
  pkg/factory/admin_user_factory.go
  pkg/factory/user_factory.go
  pkg/testdatagen/testharness/dispatch.go
  pkg/testdatagen/testharness/make_office_user.go
  playwright/tests/admin/officeUsers.spec.js
  playwright/tests/utils/admin/adminTest.js
  playwright/tests/utils/testharness.js
  src/scenes/SystemAdmin/shared/RolesPrivilegesCheckboxes.jsx
  yarn.lock
Labels: Scrummy Bears, INTEGRATION

#14434 B-21690-INT Fix Assigned Column
  src/pages/Office/MoveQueue/MoveQueue.jsx
  src/pages/Office/PaymentRequestQueue/PaymentRequestQueue.jsx
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.jsx
Labels: G-Unit, INTEGRATION

#14412 B-21337-INT bulk assignment data fetch setup
  pkg/factory/move_factory.go
  pkg/factory/move_factory_test.go
  pkg/factory/office_user_factory.go
  pkg/factory/office_user_factory_test.go
  pkg/factory/shared.go
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/ghcapi/ghcoperations/queues/get_bulk_assignment_data.go
  pkg/gen/ghcapi/ghcoperations/queues/get_bulk_assignment_data_parameters.go
  pkg/gen/ghcapi/ghcoperations/queues/get_bulk_assignment_data_responses.go
  pkg/gen/ghcapi/ghcoperations/queues/get_bulk_assignment_data_urlbuilder.go
  pkg/gen/ghcmessages/available_office_user.go
  pkg/gen/ghcmessages/bulk_assignment_data.go
  pkg/gen/ghcmessages/bulk_assignment_move_i_ds.go
  pkg/gen/ghcmessages/bulk_assignment_move_id.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/queues.go
  pkg/handlers/ghcapi/queues_test.go
  pkg/models/move.go
  pkg/models/office_user.go
  pkg/models/queue.go
  pkg/services/mocks/OfficeUserFetcherPop.go
  pkg/services/move.go
  pkg/services/move/move_fetcher.go
  pkg/services/move/move_fetcher_test.go
  pkg/services/office_user.go
  pkg/services/office_user/office_user_fetcher.go
  pkg/services/office_user/office_user_fetcher_test.go
  src/constants/queryKeys.js
  src/constants/queues.js
  src/hooks/queries.js
  src/services/ghcApi.js
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: G-Unit, INTEGRATION

#14411 INT B-21657 - Prime request service items ppm
  pkg/handlers/primeapi/mto_service_item.go
  pkg/handlers/primeapi/mto_service_item_test.go
  pkg/handlers/primeapiv2/mto_service_item.go
  pkg/handlers/primeapiv2/mto_service_item_test.go
  pkg/handlers/primeapiv3/mto_service_item.go
  pkg/handlers/primeapiv3/mto_service_item_test.go
  pkg/models/mto_shipments.go
  pkg/models/mto_shipments_test.go
Labels: Scrummy Bears, INTEGRATION

#14301 Main b 21373 validation submit move details task order with files
  src/components/DocumentViewer/DocumentViewer.stories.jsx
  src/components/DocumentViewerFileManager/DocumentViewerFileManager.jsx
  src/components/DocumentViewerFileManager/DocumentViewerFileManager.test.jsx
  src/components/FileUpload/FileUpload.jsx
  src/components/Office/RequestedShipments/RequestedShipments.test.jsx
  src/components/Office/RequestedShipments/SubmittedRequestedShipments.jsx
  src/pages/Office/Orders/Orders.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.test.jsx
  src/pages/Office/ServicesCounselingOrders/ServicesCounselingOrders.jsx
  src/utils/validation.js
  src/utils/validation.test.js
Labels: Go-Rillaz, frontend

#14462 Int b 21969
  src/pages/Office/MoveQueue/MoveQueue.jsx
Labels: INTEGRATION, Go-Rillaz, frontend

#14453 INT B-22122 v2
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20241220171035_add_additional_AK_zips_to_zip3_distances.up.sql
  src/setupProxy.js
  yarn.lock
Labels: Mountain Movers, INTEGRATION

#14398 B-21488: Fixing UB Warning Message Display
  pkg/services/move/move_weights.go
  src/components/Office/TXOTabNav/TXOTabNav.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.test.jsx
Labels: Mountain Movers, INTEGRATION

#14456 INT B-21942
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20241220213134_add_destination_gbloc_db_function.up.sql
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/address.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/address.go
  pkg/gen/pptasapi/embedded_spec.go
  pkg/gen/pptasmessages/address.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/address.go
  pkg/gen/primev2api/embedded_spec.go
  pkg/gen/primev2messages/address.go
  pkg/gen/primev3api/embedded_spec.go
  pkg/gen/primev3messages/address.go
  pkg/handlers/primeapiv3/payloads/model_to_payload.go
  pkg/handlers/primeapiv3/payloads/model_to_payload_test.go
  pkg/models/address.go
  pkg/models/mto_shipments.go
  pkg/models/mto_shipments_test.go
  pkg/services/move_task_order/move_task_order_fetcher.go
  pkg/services/move_task_order/move_task_order_fetcher_test.go
  pkg/services/postal_codes/postal_code_validator_test.go
  scripts/db-truncate
  swagger-def/definitions/Address.yaml
  swagger/ghc.yaml
  swagger/internal.yaml
  swagger/pptas.yaml
  swagger/prime.yaml
  swagger/prime_v2.yaml
  swagger/prime_v3.yaml
Labels: Mountain Movers, INTEGRATION

#14471 B-21458 Main
  pkg/assets/notifications/templates/move_payment_reminder_template.html
  pkg/assets/notifications/templates/move_payment_reminder_template.txt
  pkg/models/address.go
  pkg/models/address_test.go
  pkg/notifications/move_counseled.go
  pkg/notifications/move_counseled_test.go
  pkg/notifications/move_payment_reminder.go
  pkg/notifications/move_payment_reminder_test.go
  pkg/notifications/move_submitted.go
  pkg/notifications/move_submitted_test.go
Labels: MAIN, Go-Rillaz, backend

#14477 INT B-22139
  .gitlab-ci.yml
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20241227153723_remove_empty_string_emplid_values.up.sql
  pkg/handlers/ghcapi/customer.go
  pkg/handlers/ghcapi/customer_test.go
  src/pages/Office/CustomerOnboarding/CreateCustomerForm.jsx
  src/pages/Office/CustomerOnboarding/CreateCustomerForm.test.jsx
Labels: Mountain Movers, INTEGRATION

#14476 MAIN B-22139
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20241227153723_remove_empty_string_emplid_values.up.sql
  pkg/handlers/ghcapi/customer.go
  pkg/handlers/ghcapi/customer_test.go
  src/pages/Office/CustomerOnboarding/CreateCustomerForm.jsx
  src/pages/Office/CustomerOnboarding/CreateCustomerForm.test.jsx
Labels: Mountain Movers, MAIN

#14349 B-21976 Check feature flag for NTS/NTSR in office app
  src/components/Office/RequestedShipments/ApprovedRequestedShipments.jsx
  src/components/Office/RequestedShipments/SubmittedRequestedShipments.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
Labels: G-Unit, MAIN

#14346 B 21359 int - Backend: Assigned User Cleanup
  pkg/factory/move_factory.go
  pkg/factory/move_factory_test.go
  pkg/factory/shared.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload_test.go
  pkg/handlers/ghcapi/payment_request_test.go
  pkg/handlers/primeapi/payloads/model_to_payload_test.go
  pkg/models/move.go
  pkg/services/move_task_order/move_task_order_updater.go
  pkg/services/move_task_order/move_task_order_updater_test.go
  pkg/services/mto_service_item/mto_service_item_updater.go
  pkg/services/mto_service_item/mto_service_item_updater_test.go
  pkg/services/payment_request/payment_request_status_updater.go
  pkg/services/payment_request/payment_request_status_updater_test.go
Labels: G-Unit, INTEGRATION, backend

#14297 B 21819 prime 3rd address errors
  pkg/handlers/primeapiv3/mto_shipment.go
  pkg/handlers/primeapiv3/mto_shipment_test.go
  pkg/handlers/primeapiv3/payloads/payload_to_model.go
  pkg/handlers/primeapiv3/payloads/payload_to_model_test.go
Labels: G-Unit, MAIN

#14490 B 22122 int
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20241230190638_remove_AK_zips_from_zip3.up.sql
  migrations/app/schema/20241230190647_add_missing_AK_zips_to_zip3_distances.up.sql
Labels: INTEGRATION
