Repository transcom/mymove, pull requests merged in 2025-02, with the labels that each got.

#14714 B 22271 int office user account request id in use error fix
  pkg/services/office_user/office_user_creator.go
  pkg/services/office_user/office_user_creator_test.go
Labels: G-Unit, INTEGRATION

#14682 B22018-INTb-add svc items to oconus ntsr
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20250120214107_add_international_ntsr_service_items.up.sql
  pkg/factory/mto_shipment_factory.go
  pkg/services/mto_shipment/shipment_approver.go
  pkg/services/mto_shipment/shipment_approver_test.go
Labels: ByteSize M&Ms, INTEGRATION

#14703 B-22289 remove gtcc disbursement calculation from aoa
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet_test.go
Labels: Mountain Movers, INTEGRATION

#14719 B 21464 int v2
  pkg/services/mto_service_item/mto_service_item_updater.go
Labels: Scrummy Bears, INTEGRATION

#14726 B 21803
  src/components/Office/DefinitionLists/NTSRShipmentInfoList.jsx
  src/components/Office/DefinitionLists/NTSRShipmentInfoList.test.jsx
  src/pages/Office/MoveDetails/MoveDetails.jsx
Labels: Scrummy Bears, MAIN

#14619 Int b 22056 sns sqs deps w endpoint
  .envrc
  .gitlab-ci.yml
  cmd/milmove/serve.go
  go.mod
  go.sum
  pkg/cli/receiver.go
  pkg/cli/receiver_test.go
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/doc.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/ghcapi/ghcoperations/uploads/get_upload_status.go
  pkg/gen/ghcapi/ghcoperations/uploads/get_upload_status_parameters.go
  pkg/gen/ghcapi/ghcoperations/uploads/get_upload_status_responses.go
  pkg/gen/ghcapi/ghcoperations/uploads/get_upload_status_urlbuilder.go
  pkg/handlers/apitests.go
  pkg/handlers/authentication/auth.go
  pkg/handlers/config.go
  pkg/handlers/config_test.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/move.go
  pkg/handlers/ghcapi/orders.go
  pkg/handlers/ghcapi/uploads.go
  pkg/handlers/ghcapi/uploads_test.go
  pkg/handlers/internalapi/internal/payloads/model_to_payload.go
  pkg/handlers/internalapi/moves.go
  pkg/handlers/internalapi/orders.go
  pkg/handlers/routing/base_routing_suite.go
  pkg/handlers/routing/ghcapi_test/uploads_test.go
  pkg/models/upload.go
  pkg/notifications/notification_receiver.go
  pkg/notifications/notification_receiver_stub.go
  pkg/notifications/notification_receiver_test.go
  pkg/notifications/notification_sender_stub.go
  pkg/notifications/notification_sender_test.go
  pkg/notifications/receiverMocks/SnsClient.go
  pkg/notifications/receiverMocks/SqsClient.go
  pkg/notifications/receiverMocks/ViperType.go
  pkg/storage/filesystem.go
  pkg/storage/filesystem_test.go
  pkg/storage/memory.go
  pkg/storage/memory_test.go
  pkg/storage/test/s3.go
  pkg/storage/test/s3_test.go
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: INTEGRATION, Go-Rillaz

#14734 B 22288 fix pdfcpu main
  go.mod
  go.sum
  pkg/paperwork/generator.go
  pkg/paperwork/generator_test.go
Labels: Mountain Movers, MAIN

#14729 MAIN-B-22239 show deleted agent in move history
  src/constants/MoveHistory/EventTemplates/UpdateMTOShipment/UpdateMTOShipmentAgent.module.scss
  src/constants/MoveHistory/EventTemplates/UpdateMTOShipment/updateMTOShipmentAgent.jsx
  src/constants/MoveHistory/EventTemplates/UpdateMTOShipment/updateMTOShipmentAgent.test.jsx
Labels: MAIN, Go-Rillaz

#14700 B 20636 MAIN - #26 Dependency Scan (Severity High) - ip 2.0.1 (DEV)
  package.json
  yarn.lock
Labels: Scrummy Bears, MAIN

#14583 MAIN B-21978
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20250114164752_add_ppm_estimated_incentive_proc.up.sql
  pkg/factory/ppm_shipment_factory.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/p_p_m_closeout.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload_test.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/models/port_location.go
  pkg/models/port_location_test.go
  pkg/models/ppm_shipment.go
  pkg/models/ppm_shipment_test.go
  pkg/models/re_intl_other_price.go
  pkg/models/re_intl_other_price_test.go
  pkg/models/re_service.go
  pkg/models/re_service_test.go
  pkg/payment_request/service_param_value_lookups/distance_zip_lookup.go
  pkg/payment_request/service_param_value_lookups/distance_zip_lookup_test.go
  pkg/payment_request/service_param_value_lookups/per_unit_cents_lookup.go
  pkg/payment_request/service_param_value_lookups/per_unit_cents_lookup_test.go
  pkg/payment_request/service_param_value_lookups/port_zip_lookup.go
  pkg/payment_request/service_param_value_lookups/port_zip_lookup_test.go
  pkg/payment_request/service_param_value_lookups/service_param_value_lookups.go
  pkg/payment_request/service_param_value_lookups/service_param_value_lookups_test.go
  pkg/services/ghc_rate_engine.go
  pkg/services/ghcrateengine/intl_destination_additional_days_sit_pricer.go
  pkg/services/ghcrateengine/intl_destination_additional_days_sit_pricer_test.go
  pkg/services/ghcrateengine/intl_destination_first_day_sit_pricer.go
  pkg/services/ghcrateengine/intl_destination_first_day_sit_pricer_test.go
  pkg/services/ghcrateengine/intl_origin_additional_days_sit_pricer.go
  pkg/services/ghcrateengine/intl_origin_additional_days_sit_pricer_test.go
  pkg/services/ghcrateengine/intl_origin_first_day_sit_pricer.go
  pkg/services/ghcrateengine/intl_origin_first_day_sit_pricer_test.go
  pkg/services/ghcrateengine/pricer_helpers_intl.go
  pkg/services/ghcrateengine/pricer_helpers_intl_test.go
  pkg/services/ghcrateengine/service_item_pricer.go
  pkg/services/mocks/IntlDestinationAdditionalDaySITPricer.go
  pkg/services/mocks/IntlDestinationFirstDaySITPricer.go
  pkg/services/mocks/IntlOriginAdditionalDaySITPricer.go
  pkg/services/mocks/IntlOriginFirstDaySITPricer.go
  pkg/services/mto_shipment/mto_shipment_updater.go
  pkg/services/ppm_closeout/ppm_closeout.go
  pkg/services/ppm_closeout/ppm_closeout_test.go
  pkg/services/ppmshipment/ppm_estimator.go
  pkg/services/ppmshipment/ppm_estimator_test.go
  pkg/services/ppmshipment/ppm_shipment_updater.go
  src/components/Office/PPM/PPMHeaderSummary/HeaderSection.jsx
  src/components/Office/PPM/PPMHeaderSummary/HeaderSection.test.jsx
  src/components/Office/PPM/PPMHeaderSummary/PPMHeaderSummary.jsx
  src/components/Office/PPM/PPMHeaderSummary/PPMHeaderSummary.test.jsx
  src/components/Office/PPM/SitCostBreakdown/SitCostBreakdown.jsx
  swagger-def/definitions/PPMCloseout.yaml
  swagger/ghc.yaml
Labels: Mountain Movers, MAIN

#14699 B 21935 int
  pkg/assets/notifications/templates/move_counseled_template.html
  pkg/assets/notifications/templates/move_counseled_template.txt
  pkg/assets/notifications/templates/move_submitted_template.html
  pkg/assets/notifications/templates/move_submitted_template.txt
  pkg/factory/entitlement_factory.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/shipment/review_shipment_address_update.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/entitlement.go
  pkg/gen/internalmessages/orders.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/orders_test.go
  pkg/handlers/internalapi/orders.go
  pkg/handlers/supportapi/internal/payloads/model_to_payload.go
  pkg/notifications/move_counseled.go
  pkg/notifications/move_counseled_test.go
  pkg/notifications/move_submitted_test.go
  pkg/services/order/order_updater.go
  pkg/services/order/order_updater_test.go
  src/components/Customer/MtoShipmentForm/MtoShipmentForm.jsx
  src/components/Customer/PPM/Booking/EstimatedWeightsProGearForm/EstimatedWeightsProGearForm.jsx
  src/components/Office/AllowancesDetailForm/AllowancesDetailForm.jsx
  src/pages/MyMove/Home/MoveHome.jsx
  src/pages/MyMove/Home/MoveHome.test.jsx
  src/pages/MyMove/Home/index.jsx
  src/pages/MyMove/MovingInfo.jsx
  swagger-def/ghc.yaml
  swagger-def/internal.yaml
  swagger/ghc.yaml
  swagger/internal.yaml
Labels: Mountain Movers, INTEGRATION

#14735 B-22289 remove gtcc disbursement calculation from aoa
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet_test.go
Labels: Mountain Movers, MAIN

#14702 MAIN - B-22251 Update existing process for approving move and shipment
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/move_task_order/update_move_task_order_status.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/ghcapi/ghcoperations/shipment/approve_shipments.go
  pkg/gen/ghcapi/ghcoperations/shipment/approve_shipments_parameters.go
  pkg/gen/ghcapi/ghcoperations/shipment/approve_shipments_responses.go
  pkg/gen/ghcapi/ghcoperations/shipment/approve_shipments_urlbuilder.go
  pkg/gen/ghcmessages/approve_shipments.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/move_task_order.go
  pkg/handlers/ghcapi/move_task_order_test.go
  pkg/handlers/ghcapi/mto_shipment.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/handlers/supportapi/move_task_order.go
  pkg/services/event/ghc_endpoint.go
  pkg/services/mocks/MoveTaskOrderUpdater.go
  pkg/services/mocks/ShipmentApprover.go
  pkg/services/mocks/WeightAllotmentFetcher.go
  pkg/services/mocks/WeightRestrictor.go
  pkg/services/move_task_order.go
  pkg/services/move_task_order/move_task_order_updater.go
  pkg/services/move_task_order/move_task_order_updater_test.go
  pkg/services/mto_service_item/mto_service_item_creator.go
  pkg/services/mto_service_item/mto_service_item_creator_test.go
  pkg/services/mto_shipment.go
  pkg/services/mto_shipment/shipment_approver.go
  pkg/services/mto_shipment/shipment_approver_test.go
  pkg/testdatagen/scenario/shared.go
  src/components/Office/RequestedShipments/RequestedShipments.test.jsx
  src/components/Office/RequestedShipments/RequestedShipmentsTestData.js
  src/components/Office/RequestedShipments/SubmittedRequestedShipments.jsx
  src/components/Office/ShipmentApprovalPreview/ShipmentApprovalPreview.jsx
  src/components/Office/ShipmentApprovalPreview/ShipmentApprovalPreview.test.jsx
  src/constants/MoveHistory/Database/FieldMappings.js
  src/constants/MoveHistory/EventTemplates/ApproveShipments/approveShipments.jsx
  src/constants/MoveHistory/EventTemplates/ApproveShipments/approveShipments.test.jsx
  src/constants/MoveHistory/EventTemplates/ApproveShipments/approveShipmentsApproveMove.jsx
  src/constants/MoveHistory/EventTemplates/ApproveShipments/approveShipmentsApproveMove.test.jsx
  src/constants/MoveHistory/EventTemplates/ApproveShipments/approveShipmentsServiceItem.jsx
  src/constants/MoveHistory/EventTemplates/ApproveShipments/approveShipmentsServiceItem.test.jsx
  src/constants/MoveHistory/EventTemplates/ApproveShipments/approveShipmentsUpdateAllowances.jsx
  src/constants/MoveHistory/EventTemplates/ApproveShipments/approveShipmentsUpdateAllowances.test.jsx
  src/constants/MoveHistory/EventTemplates/index.js
  src/constants/MoveHistory/UIDisplay/Operations.js
  src/pages/Office/MoveDetails/MoveDetails.jsx
  src/services/ghcApi.js
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: ByteSize M&Ms, MAIN

#14746 B 21935 int
  pkg/notifications/move_counseled.go
Labels: Mountain Movers, INTEGRATION

#14649 B 21446 tio bulk assignment be
  pkg/handlers/ghcapi/queues.go
  pkg/handlers/ghcapi/queues_test.go
  pkg/models/payment_request.go
  pkg/services/move.go
  pkg/services/move/move_fetcher.go
  pkg/services/move/move_fetcher_test.go
Labels: G-Unit, MAIN

#14727 Main b 22238 update get move task order for deleted agent
  pkg/handlers/primeapiv3/payloads/model_to_payload.go
  pkg/services/move_task_order/move_task_order_fetcher.go
  pkg/services/move_task_order/move_task_order_fetcher_test.go
Labels: MAIN, Go-Rillaz, backend

#14762 I-13829 - B 21935 int
  pkg/assets/notifications/templates/move_counseled_template.html
  pkg/assets/notifications/templates/move_submitted_template.html
  src/pages/MyMove/Home/MoveHome.jsx
  src/pages/MyMove/Home/index.jsx
Labels: Mountain Movers, INTEGRATION

#14691 B 22233 INT - Add Domestic Rate Areas to Prime API and UI
  .gitlab-ci.yml
  pkg/handlers/primeapiv3/move_task_order.go
  pkg/handlers/primeapiv3/move_task_order_test.go
  pkg/handlers/primeapiv3/payloads/model_to_payload.go
  pkg/handlers/primeapiv3/payloads/model_to_payload_test.go
  pkg/services/mocks/ShipmentRateAreaFinder.go
  pkg/services/move/move_fetcher_test.go
  pkg/services/mto_shipment.go
  pkg/services/mto_shipment/mto_shipment_rate_area_fetcher.go
  pkg/services/mto_shipment/mto_shipment_rate_area_fetcher_test.go
  src/components/PrimeUI/Shipment/Shipment.jsx
  src/components/PrimeUI/Shipment/Shipment.test.jsx
Labels: Scrummy Bears, INTEGRATION

#14743 B-21378/I-13811 Combining Both RDD calculation Implementations Into 1
  pkg/services/mto_shipment/mto_shipment_updater.go
  pkg/services/mto_shipment/mto_shipment_updater_test.go
  pkg/services/mto_shipment/rules.go
  pkg/services/mto_shipment/shipment_approver.go
Labels: Mountain Movers, INTEGRATION

#14585 B 21339 int - Bulk assignment modal: UI Layout and populate data (SC/TOO)
  .circleci/config.yml
  config/env/demo.app-client-tls.env
  config/env/demo.app.env
  pkg/services/move/move_fetcher_test.go
  pkg/services/office_user/office_user_fetcher.go
  src/components/BulkAssignment/BulkAssignmentModal.jsx
  src/components/BulkAssignment/BulkAssignmentModal.module.scss
  src/components/BulkAssignment/BulkAssignmentModal.test.jsx
  src/components/Table/TableQueue.jsx
  src/components/Table/TableQueue.module.scss
  src/pages/Office/MoveQueue/MoveQueue.jsx
  src/pages/Office/MoveQueue/MoveQueue.test.jsx
  src/pages/Office/PaymentRequestQueue/PaymentRequestQueue.jsx
  src/pages/Office/PaymentRequestQueue/PaymentRequestQueue.test.jsx
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.jsx
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.test.jsx
  src/utils/formatters.js
Labels: G-Unit, INTEGRATION, frontend

#14753 B 22247 int2
  pkg/gen/ghcapi/embedded_spec.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/services/office_user/office_user_fetcher.go
  swagger/ghc.yaml
Labels: G-Unit, INTEGRATION

#14761 INT B-21982
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20250206173204_add_hawaii_data.up.sql
Labels: Mountain Movers, INTEGRATION

#14720 B 21439 int
  pkg/gen/supportapi/embedded_spec.go
  pkg/gen/supportmessages/m_t_o_service_item.go
  pkg/gen/supportmessages/m_t_o_service_item_international_shuttle.go
  pkg/gen/supportmessages/m_t_o_service_item_model_type.go
  pkg/handlers/ghcapi/mto_service_items.go
  pkg/handlers/supportapi/internal/payloads/model_to_payload.go
  pkg/testdatagen/testharness/dispatch.go
  pkg/testdatagen/testharness/make_move.go
  playwright/tests/office/txo/tooFlowsInternational.spec.js
  playwright/tests/utils/testharness.js
  src/components/Office/ServiceItemDetails/ServiceItemDetails.jsx
  src/components/Office/ServiceItemDetails/ServiceItemDetails.test.jsx
  swagger-def/support.yaml
  swagger/support.yaml
Labels: Scrummy Bears, INTEGRATION

#14758 INT B-21939
  src/pages/PrimeUI/MoveTaskOrder/MoveDetails.jsx
  src/pages/PrimeUI/MoveTaskOrder/MoveDetails.test.jsx
Labels: Mountain Movers, INTEGRATION

#14692 Int b 22015
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20250127143137_insert_nsra_re_intl_transit_times.up.sql
  pkg/factory/address_factory.go
  pkg/services/mto_shipment/mto_shipment_updater_test.go
Labels: Scrummy Bears, INTEGRATION, database, backend

#14741 set pdfcpu fork to relaxed outline validation
  go.mod
  go.sum
Labels: Mountain Movers, INTEGRATION

#14752 INT B-22272
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20250123173216_add_destination_queue_db_func_and_gbloc_view.up.sql
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/ghcapi/ghcoperations/queues/get_destination_requests_queue.go
  pkg/gen/ghcapi/ghcoperations/queues/get_destination_requests_queue_parameters.go
  pkg/gen/ghcapi/ghcoperations/queues/get_destination_requests_queue_responses.go
  pkg/gen/ghcapi/ghcoperations/queues/get_destination_requests_queue_urlbuilder.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/queues.go
  pkg/handlers/ghcapi/queues_test.go
  pkg/models/move.go
  pkg/models/mto_shipments.go
  pkg/models/order.go
  pkg/services/mocks/OrderFetcher.go
  pkg/services/order.go
  pkg/services/order/order_fetcher.go
  pkg/services/order/order_fetcher_test.go
  src/constants/routes.js
  src/hooks/queries.js
  src/pages/Office/MoveQueue/MoveQueue.jsx
  src/pages/Office/MoveQueue/MoveQueue.test.jsx
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.jsx
  src/services/ghcApi.js
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: Mountain Movers, INTEGRATION

#14388 B-21583 - update code to calculate gbloc for AK
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20241217191012_update_move_to_gbloc_for_ak.up.sql
  migrations/app/schema/20250103130619_revert_data_change_for_gbloc_for_ak.up.sql
  migrations/app/schema/20250103142533_update_postal_codes_and_gblocs_for_ak.up.sql
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/move_test.go
  pkg/handlers/ghcapi/orders.go
  pkg/handlers/ghcapi/orders_test.go
  pkg/handlers/internalapi/orders.go
  pkg/handlers/internalapi/orders_test.go
  pkg/handlers/primeapi/payloads/model_to_payload.go
  pkg/handlers/primeapiv2/payloads/model_to_payload.go
  pkg/handlers/primeapiv3/payloads/model_to_payload.go
  pkg/models/address.go
  pkg/models/address_test.go
  pkg/models/gbloc_aors.go
  pkg/models/gbloc_aors_test.go
  pkg/models/jppso_regions.go
  pkg/models/jppso_regions_test.go
  pkg/models/move.go
  pkg/models/mto_shipments.go
  pkg/models/order.go
  pkg/models/re_oconus_rate_areas.go
  pkg/models/re_oconus_rate_areas_test.go
  pkg/models/us_post_region_city.go
  pkg/models/us_post_region_city_test.go
  pkg/services/invoice/ghc_payment_request_invoice_generator.go
  pkg/services/move_task_order/move_task_order_fetcher.go
  pkg/services/order/order_updater.go
  pkg/services/support/move_task_order/move_task_order_creator.go
  pkg/services/transportation_office/transportation_office_fetcher_test.go
  scripts/db-truncate
Labels: G-Unit, MAIN

#14688 MAIN B-22264
  pkg/payment_request/service_param_value_lookups/weight_billed_lookup.go
  pkg/payment_request/service_param_value_lookups/weight_billed_lookup_test.go
Labels: Mountain Movers, MAIN

#14721 Int b 21943 prime sim resubmit sit
  pkg/services/mto_service_item/mto_service_item_validators.go
  pkg/services/mto_service_item/mto_service_item_validators_test.go
  scripts/run-server-test
  src/pages/PrimeUI/UpdateServiceItems/PrimeUIUpdateDestSITForm.jsx
  src/pages/PrimeUI/UpdateServiceItems/PrimeUIUpdateDestSITForm.test.jsx
  src/pages/PrimeUI/UpdateServiceItems/PrimeUIUpdateOriginSITForm.jsx
  src/pages/PrimeUI/UpdateServiceItems/PrimeUIUpdateOriginSITForm.test.jsx
  src/pages/PrimeUI/UpdateServiceItems/PrimeUIUpdateServiceItem.jsx
  src/pages/PrimeUI/UpdateServiceItems/PrimeUpdateSitServiceItem.test.jsx
Labels: INTEGRATION, Go-Rillaz

#14773 fix test
  pkg/notifications/move_counseled_test.go
Labels: Mountain Movers, INTEGRATION

#14775 and a few more
  pkg/notifications/move_submitted_test.go
Labels: Mountain Movers, INTEGRATION

#14754 B-21961/I-13804: Pagination and Sorting on Transportation office
  pkg/handlers/adminapi/requested_office_users.go
  pkg/handlers/adminapi/requested_office_users_test.go
  pkg/models/errors.go
  pkg/services/mocks/RequestedOfficeUserListFetcher.go
  pkg/services/requested_office_users.go
  pkg/services/requested_office_users/requested_office_user_list_fetcher_test.go
  pkg/services/requested_office_users/requested_office_users_list_fetcher.go
  src/pages/Admin/RequestedOfficeUsers/RequestedOfficeUserList.jsx
Labels: Mountain Movers, INTEGRATION

#14772 B 21934 main
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/counseling_update_allowance_payload.go
  pkg/gen/ghcmessages/entitlements.go
  pkg/gen/ghcmessages/update_allowance_payload.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/entitlements.go
  pkg/gen/primev2api/embedded_spec.go
  pkg/gen/primev2messages/entitlements.go
  pkg/gen/primev3api/embedded_spec.go
  pkg/gen/primev3messages/entitlements.go
  pkg/gen/supportapi/embedded_spec.go
  pkg/gen/supportmessages/entitlement.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload_test.go
  pkg/handlers/ghcapi/orders.go
  pkg/handlers/primeapi/payloads/model_to_payload.go
  pkg/handlers/primeapi/payloads/model_to_payload_test.go
  pkg/handlers/primeapiv2/payloads/model_to_payload.go
  pkg/handlers/primeapiv2/payloads/model_to_payload_test.go
  pkg/handlers/primeapiv3/payloads/model_to_payload.go
  pkg/handlers/primeapiv3/payloads/model_to_payload_test.go
  pkg/services/order/order_updater.go
  pkg/services/order/order_updater_test.go
  src/components/Office/AllowancesDetailForm/AllowancesDetailForm.jsx
  src/components/Office/AllowancesDetailForm/AllowancesDetailForm.test.jsx
  src/components/Office/DefinitionLists/AllowancesList.jsx
  src/components/Office/DefinitionLists/AllowancesList.test.jsx
  src/constants/MoveHistory/Database/BooleanFields.js
  src/constants/MoveHistory/Database/FieldMappings.js
  src/pages/Office/MoveAllowances/MoveAllowances.jsx
  src/pages/Office/MoveDetails/MoveDetails.jsx
  src/pages/Office/ServicesCounselingMoveAllowances/ServicesCounselingMoveAllowances.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
  swagger-def/definitions/prime/Entitlements.yaml
  swagger-def/ghc.yaml
  swagger-def/support.yaml
  swagger/ghc.yaml
  swagger/prime.yaml
  swagger/prime_v2.yaml
  swagger/prime_v3.yaml
  swagger/support.yaml
Labels: Mountain Movers, MAIN

#14751 INT - B-22020 - TIO payment request calculations -BE
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20250110201339_add_payment_params_for_intl_crating_uncrating.up.sql
  migrations/app/schema/20250204162411_updating_create_accessorial_service_item_proc_for_crating.up.sql
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/mto_service_item/update_m_t_o_service_item.go
  pkg/gen/primeclient/mto_service_item/mto_service_item_client.go
  pkg/gen/primemessages/update_m_t_o_service_item.go
  pkg/gen/primemessages/update_m_t_o_service_item_crating.go
  pkg/gen/primemessages/update_m_t_o_service_item_model_type.go
  pkg/models/mto_service_items.go
  pkg/models/mto_service_items_test.go
  pkg/models/re_intl_accessorial_price.go
  pkg/models/service_item_param_key.go
  pkg/payment_request/service_param_value_lookups/cubic_feet_billed_lookup.go
  pkg/payment_request/service_param_value_lookups/cubic_feet_billed_lookup_test.go
  pkg/payment_request/service_param_value_lookups/external_crate_lookup.go
  pkg/payment_request/service_param_value_lookups/external_crate_lookup_test.go
  pkg/payment_request/service_param_value_lookups/service_param_value_lookups.go
  pkg/services/ghc_rate_engine.go
  pkg/services/ghcrateengine/intl_crating_pricer.go
  pkg/services/ghcrateengine/intl_crating_pricer_test.go
  pkg/services/ghcrateengine/intl_uncrating_pricer.go
  pkg/services/ghcrateengine/intl_uncrating_pricer_test.go
  pkg/services/ghcrateengine/pricer_helpers_intl.go
  pkg/services/ghcrateengine/pricer_helpers_intl_test.go
  pkg/services/ghcrateengine/service_item_pricer.go
  pkg/services/ghcrateengine/service_item_pricer_test.go
  pkg/services/ghcrateengine/shared.go
  pkg/services/mto_service_item/mto_service_item_validators.go
  swagger-def/prime.yaml
  swagger/prime.yaml
Labels: ByteSize M&Ms, INTEGRATION

#14781 B 22233 MAIN - Add Domestic Rate Areas to Prime API and UI
  pkg/handlers/primeapiv3/move_task_order.go
  pkg/handlers/primeapiv3/move_task_order_test.go
  pkg/handlers/primeapiv3/payloads/model_to_payload.go
  pkg/handlers/primeapiv3/payloads/model_to_payload_test.go
  pkg/services/mocks/ShipmentRateAreaFinder.go
  pkg/services/mto_shipment.go
  pkg/services/mto_shipment/mto_shipment_rate_area_fetcher.go
  pkg/services/mto_shipment/mto_shipment_rate_area_fetcher_test.go
  src/components/PrimeUI/Shipment/Shipment.jsx
  src/components/PrimeUI/Shipment/Shipment.test.jsx
Labels: Scrummy Bears, MAIN

#14630 B22018 main add svc items to oconus ntsr
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20250120214107_add_international_ntsr_service_items.up.sql
  pkg/factory/mto_shipment_factory.go
  pkg/services/mto_shipment/shipment_approver.go
  pkg/services/mto_shipment/shipment_approver_test.go
Labels: ByteSize M&Ms, MAIN

#14364 B-21094: Automatic Reweigh Based on Estimated Weight
  pkg/models/move.go
  pkg/services/move/move_weights.go
  pkg/services/move/move_weights_test.go
  pkg/services/mto_shipment/mto_shipment_updater.go
  pkg/services/mto_shipment/mto_shipment_updater_test.go
  src/shared/Inputs/YesNoBoolean.test.js
Labels: ByteSize M&Ms, INTEGRATION

#14750 B-22368-INT add closeout counselor label to move history
  src/constants/MoveHistory/Database/FieldMappings.js
  src/constants/MoveHistory/EventTemplates/UpdateAssignedOfficeUser/DeleteAssignedOfficeUser.jsx
  src/constants/MoveHistory/EventTemplates/UpdateAssignedOfficeUser/DeleteAssignedOfficeUser.test.jsx
  src/constants/MoveHistory/EventTemplates/UpdateAssignedOfficeUser/UpdateAssignedOfficeUser.test.jsx
  src/utils/formatters.js
  src/utils/formatters.test.js
Labels: G-Unit, INTEGRATION

#14663 B 21935
  pkg/assets/notifications/templates/move_counseled_template.html
  pkg/assets/notifications/templates/move_counseled_template.txt
  pkg/assets/notifications/templates/move_submitted_template.html
  pkg/assets/notifications/templates/move_submitted_template.txt
  pkg/factory/entitlement_factory.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/entitlement.go
  pkg/gen/internalmessages/orders.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/orders_test.go
  pkg/handlers/internalapi/orders.go
  pkg/handlers/supportapi/internal/payloads/model_to_payload.go
  pkg/notifications/move_counseled.go
  pkg/notifications/move_counseled_test.go
  pkg/notifications/move_submitted_test.go
  pkg/services/order/order_updater.go
  pkg/services/order/order_updater_test.go
  src/components/Customer/MtoShipmentForm/MtoShipmentForm.jsx
  src/components/Customer/PPM/Booking/EstimatedWeightsProGearForm/EstimatedWeightsProGearForm.jsx
  src/components/Office/AllowancesDetailForm/AllowancesDetailForm.jsx
  src/pages/MyMove/Home/MoveHome.jsx
  src/pages/MyMove/Home/MoveHome.test.jsx
  src/pages/MyMove/Home/index.jsx
  src/pages/MyMove/MovingInfo.jsx
  swagger-def/internal.yaml
  swagger/internal.yaml
Labels: Mountain Movers, MAIN

#14763 B 22305 int milmove error message has incorrect url for technical helpdesk
  src/shared/ErrorModal/ErrorModal.jsx
Labels: G-Unit, INTEGRATION

#14748 B 22301 int - Prevent User from Entering Additional Address Until the Preceding Address Is Complete
  .gitlab-ci.yml
  scripts/rds-snapshot-app-db
  scripts/run-server-test
  src/components/Customer/MtoShipmentForm/MtoShipmentForm.jsx
  src/components/Customer/MtoShipmentForm/MtoShipmentForm.test.jsx
  src/components/Customer/PPM/Booking/DateAndLocationForm/DateAndLocationForm.jsx
  src/components/Office/ShipmentForm/ShipmentForm.jsx
  src/shared/utils.js
  src/utils/formatMtoShipment.js
  src/utils/formatMtoShipment.test.js
  swagger-def/ghc.yaml
Labels: G-Unit, INTEGRATION, frontend

#14785 B-22480 - fix issue with null Prime API call and AK destination moves
  pkg/models/move.go
Labels: G-Unit, MAIN

#14766 INT B-21416 intl crating tio update for payment request-FE
  pkg/services/mocks/IntlCratingPricer.go
  pkg/services/mocks/IntlUncratingPricer.go
  pkg/testdatagen/testharness/dispatch.go
  pkg/testdatagen/testharness/make_move.go
  playwright/tests/office/txo/tioFlowsInternational.spec.js
  playwright/tests/utils/testharness.js
  src/components/Office/ServiceItemCalculations/ServiceItemCalculations.jsx
  src/components/Office/ServiceItemCalculations/ServiceItemCalculations.module.scss
  src/components/Office/ServiceItemCalculations/helpers.js
  src/components/Office/ServiceItemCalculations/helpers.test.js
  src/components/Office/ServiceItemCalculations/serviceItemTestParams.js
  src/constants/serviceItems.js
Labels: ByteSize M&Ms, INTEGRATION

#14784 INT B-22451
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20250210175754_B22451_update_dest_queue_to_consider_sit_extensions.up.sql
  pkg/factory/mto_service_item_factory.go
  pkg/factory/mto_service_item_factory_test.go
  pkg/services/order/order_fetcher_test.go
  pkg/testdatagen/testharness/dispatch.go
  pkg/testdatagen/testharness/make_move.go
  playwright/tests/utils/testharness.js
  src/components/Office/ShipmentServiceItemsTable/ShipmentServiceItemsTable.test.jsx
  src/constants/MoveHistory/EventTemplates/UpdateMTOServiceItem/updateServiceItemPricingAndWeights.test.jsx
Labels: Mountain Movers, INTEGRATION

#14768 B-21962: Create Requested Users Report
  src/pages/Admin/RequestedOfficeUsers/RequestedOfficeUserList.jsx
Labels: Mountain Movers, INTEGRATION

#14674 B-22247 bug fixes for queue assignment
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/queues/get_moves_queue_parameters.go
  pkg/gen/ghcapi/ghcoperations/queues/get_moves_queue_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/queues/get_payment_requests_queue_parameters.go
  pkg/gen/ghcapi/ghcoperations/queues/get_payment_requests_queue_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/queues/get_services_counseling_queue_parameters.go
  pkg/gen/ghcapi/ghcoperations/queues/get_services_counseling_queue_urlbuilder.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload_test.go
  pkg/handlers/ghcapi/queues.go
  pkg/handlers/ghcapi/queues_test.go
  pkg/services/office_user/office_user_fetcher.go
  pkg/services/payment_request/payment_request_list_fetcher.go
  src/components/Table/TableQueue.jsx
  src/hooks/queries.js
  src/pages/Office/HeadquartersQueues/HeadquartersQueues.jsx
  src/pages/Office/MoveQueue/MoveQueue.jsx
  src/pages/Office/PaymentRequestQueue/PaymentRequestQueue.jsx
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.jsx
  src/pages/Office/index.jsx
  src/services/ghcApi.js
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: G-Unit, MAIN

#14774 B-22306/B-22307 int deleted documents use db function
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20250207153450_add_fetch_documents_func.up.sql
  pkg/handlers/ghcapi/documents.go
  pkg/handlers/ghcapi/uploads.go
  pkg/handlers/internalapi/documents.go
  pkg/handlers/internalapi/uploads.go
  pkg/models/document.go
  pkg/models/document_test.go
  pkg/models/user_upload.go
  pkg/services/paperwork/prime_download_user_upload_to_pdf_converter.go
Labels: Scrummy Bears, INTEGRATION

#14779 INT-B-20984 Validate SIT Departure Date
  pkg/handlers/primeapi/mto_service_item_test.go
  pkg/services/mto_service_item/mto_service_item_creator.go
  pkg/services/mto_service_item/mto_service_item_creator_test.go
  pkg/services/mto_service_item/mto_service_item_validators.go
  pkg/services/mto_service_item/mto_service_item_validators_test.go
  pkg/services/sit_entry_date_update/sit_entry_date_updater.go
  pkg/services/sit_entry_date_update/sit_entry_date_updater_test.go
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.test.jsx
  src/pages/Office/MoveTaskOrder/moveTaskOrderUnitTestData.js
Labels: INTEGRATION, Go-Rillaz

#14799 MAIN B-21939
  src/pages/PrimeUI/MoveTaskOrder/MoveDetails.jsx
  src/pages/PrimeUI/MoveTaskOrder/MoveDetails.test.jsx
Labels: Mountain Movers, MAIN

#14757 Int b 21669 doc viewer file upload status per s3 events
  src/components/DocumentViewer/DocumentViewer.jsx
  src/components/DocumentViewer/DocumentViewer.test.jsx
  src/components/DocumentViewerFileManager/DocumentViewerFileManager.jsx
  src/pages/Office/MoveDocumentWrapper/MoveDocumentWrapper.jsx
  src/pages/Office/Orders/Orders.jsx
  src/pages/Office/PPM/ReviewDocuments/ReviewDocuments.test.jsx
  src/pages/Office/PaymentRequestReview/PaymentRequestReview.test.jsx
  src/pages/Office/ServicesCounselingMoveDocumentWrapper/ServicesCounselingMoveDocumentWrapper.jsx
  src/pages/Office/ServicesCounselingOrders/ServicesCounselingOrders.jsx
  src/pages/Office/SupportingDocuments/SupportingDocuments.jsx
  src/pages/Office/SupportingDocuments/SupportingDocuments.test.jsx
  src/shared/constants.js
Labels: INTEGRATION, Go-Rillaz, frontend

#14809 B 22306 int Spacing fix for fetch_documents function
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20250213151815_fix_spacing_fetch_documents.up.sql
Labels: Scrummy Bears, INTEGRATION

#14712 B-21977 MAIN - ANBD - Services Counselor can select counseling office when creating a move on behalf of customer
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/ghcapi/ghcoperations/transportation_office/get_transportation_offices_g_b_l_o_cs_responses.go
  pkg/gen/ghcapi/ghcoperations/transportation_office/show_counseling_offices.go
  pkg/gen/ghcapi/ghcoperations/transportation_office/show_counseling_offices_parameters.go
  pkg/gen/ghcapi/ghcoperations/transportation_office/show_counseling_offices_responses.go
  pkg/gen/ghcapi/ghcoperations/transportation_office/show_counseling_offices_urlbuilder.go
  pkg/gen/ghcmessages/counseling_office.go
  pkg/gen/ghcmessages/counseling_offices.go
  pkg/gen/ghcmessages/create_orders.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload_test.go
  pkg/handlers/ghcapi/orders.go
  pkg/handlers/ghcapi/orders_test.go
  pkg/handlers/ghcapi/tranportation_offices.go
  pkg/handlers/ghcapi/transportation_offices_test.go
  pkg/handlers/internalapi/internal/payloads/model_to_payload_test.go
  pkg/handlers/internalapi/transportation_offices.go
  pkg/handlers/internalapi/transportation_offices_test.go
  pkg/services/mocks/TransportationOfficesFetcher.go
  pkg/services/transportation_office.go
  pkg/services/transportation_office/transportation_office_fetcher.go
  pkg/services/transportation_office/transportation_office_fetcher_test.go
  src/components/Office/AddOrdersForm/AddOrdersForm.jsx
  src/components/Office/AddOrdersForm/AddOrdersForm.test.jsx
  src/pages/Office/ServicesCounselingAddOrders/ServicesCounselingAddOrders.test.jsx
  src/services/ghcApi.js
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: Scrummy Bears, MAIN

#14724 B 22227 int Prime API address validation
  pkg/gen/primeapi/configure_mymove.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/addresses/get_location_by_zip_city_state.go
  pkg/gen/primeapi/primeoperations/addresses/get_location_by_zip_city_state_parameters.go
  pkg/gen/primeapi/primeoperations/addresses/get_location_by_zip_city_state_responses.go
  pkg/gen/primeapi/primeoperations/addresses/get_location_by_zip_city_state_urlbuilder.go
  pkg/gen/primeapi/primeoperations/mymove_api.go
  pkg/gen/primeclient/addresses/addresses_client.go
  pkg/gen/primeclient/addresses/get_location_by_zip_city_state_parameters.go
  pkg/gen/primeclient/addresses/get_location_by_zip_city_state_responses.go
  pkg/gen/primeclient/mymove_client.go
  pkg/gen/primemessages/v_location.go
  pkg/gen/primemessages/v_locations.go
  pkg/handlers/primeapi/addresses.go
  pkg/handlers/primeapi/api.go
  pkg/handlers/primeapi/mto_shipment.go
  pkg/handlers/primeapi/mto_shipment_address.go
  pkg/handlers/primeapi/mto_shipment_address_test.go
  pkg/handlers/primeapi/mto_shipment_test.go
  pkg/handlers/primeapi/payloads/model_to_payload.go
  pkg/handlers/primeapi/payloads/model_to_payload_test.go
  pkg/handlers/primeapi/payloads/payload_to_model.go
  pkg/handlers/primeapi/payloads/payload_to_model_test.go
  pkg/handlers/primeapiv2/api.go
  pkg/handlers/primeapiv2/mto_shipment.go
  pkg/handlers/primeapiv2/mto_shipment_test.go
  pkg/handlers/primeapiv2/payloads/payload_to_model.go
  pkg/handlers/primeapiv3/api.go
  pkg/handlers/primeapiv3/mto_shipment.go
  pkg/handlers/primeapiv3/mto_shipment_test.go
  pkg/services/address.go
  pkg/services/address/address_lookup.go
  pkg/services/mocks/VLocation.go
  pkg/services/move/move_fetcher_test.go
  pkg/services/shipment_address_update/shipment_address_update_requester.go
  swagger-def/prime.yaml
  swagger/prime.yaml
Labels: Scrummy Bears, INTEGRATION

#14810 B-21941 INT
  pkg/handlers/ghcapi/queues_test.go
  pkg/services/order/order_fetcher.go
  pkg/services/order/order_fetcher_test.go
  playwright/tests/office/txo/tooFlows.spec.js
Labels: Mountain Movers, INTEGRATION

#14771 B 21399 INT
  src/components/BulkAssignment/BulkAssignmentModal.jsx
  src/components/BulkAssignment/BulkAssignmentModal.module.scss
  src/components/BulkAssignment/BulkAssignmentModal.test.jsx
Labels: G-Unit, INTEGRATION

#14736 B 21983 MAIN - Display Counseling Office in Move Details (Review After B-21977)
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/move.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/transportation_offices_test.go
  pkg/handlers/internalapi/transportation_offices_test.go
  pkg/services/move/move_fetcher.go
  src/components/Office/AddOrdersForm/AddOrdersForm.test.jsx
  src/components/Office/DefinitionLists/OrdersList.jsx
  src/components/Office/DefinitionLists/OrdersList.stories.jsx
  src/components/Office/DefinitionLists/OrdersList.test.jsx
  src/pages/Office/MoveDetails/MoveDetails.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: Scrummy Bears, MAIN

#14803 INT - B-22300 - add dependents authorized to orders page
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/counseling_update_allowance_payload.go
  pkg/gen/ghcmessages/counseling_update_order_payload.go
  pkg/gen/ghcmessages/update_allowance_payload.go
  pkg/gen/ghcmessages/update_order_payload.go
  pkg/handlers/ghcapi/orders_test.go
  pkg/services/order/order_updater.go
  pkg/services/order/order_updater_test.go
  playwright/tests/my/mymove/boat.spec.js
  playwright/tests/office/qaecsr/csrFlows.spec.js
  src/components/Office/AllowancesDetailForm/AllowancesDetailForm.jsx
  src/components/Office/DefinitionLists/AllowancesList.jsx
  src/components/Office/DefinitionLists/AllowancesList.stories.jsx
  src/components/Office/DefinitionLists/AllowancesList.test.jsx
  src/components/Office/DefinitionLists/OrdersList.jsx
  src/components/Office/DefinitionLists/OrdersList.stories.jsx
  src/components/Office/DefinitionLists/OrdersList.test.jsx
  src/components/Office/OrdersDetailForm/OrdersDetailForm.jsx
  src/components/Office/OrdersDetailForm/OrdersDetailForm.module.scss
  src/components/Office/OrdersDetailForm/OrdersDetailForm.test.jsx
  src/pages/Office/MoveAllowances/MoveAllowances.jsx
  src/pages/Office/MoveAllowances/MoveAllowances.test.jsx
  src/pages/Office/MoveDetails/MoveDetails.jsx
  src/pages/Office/Orders/Orders.jsx
  src/pages/Office/Orders/Orders.test.jsx
  src/pages/Office/ServicesCounselingMoveAllowances/ServicesCounselingMoveAllowances.jsx
  src/pages/Office/ServicesCounselingMoveAllowances/ServicesCounselingMoveAllowances.test.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
  src/pages/Office/ServicesCounselingOrders/ServicesCounselingOrders.jsx
  src/pages/Office/ServicesCounselingOrders/ServicesCounselingOrders.test.jsx
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: ByteSize M&Ms, INTEGRATION

#14824 INT B-21416 intl crating tio update for payment request-FE- PART 2
  src/components/Office/PaymentRequestDetails/PaymentRequestDetails.jsx
Labels: ByteSize M&Ms, INTEGRATION

#14814 INT B-22451 testharness enhancements
  pkg/testdatagen/testharness/make_move.go
Labels: Mountain Movers, INTEGRATION

#14821 INT B-22621
  .gitlab-ci.yml
  pkg/services/order/order_updater.go
  pkg/services/order/order_updater_test.go
  scripts/rds-snapshot-app-db
  src/components/Office/AllowancesDetailForm/AllowancesDetailForm.jsx
  src/components/Office/AllowancesDetailForm/AllowancesDetailForm.test.jsx
  src/pages/Office/MoveAllowances/MoveAllowances.jsx
  src/pages/Office/MoveAllowances/MoveAllowances.test.jsx
  src/pages/Office/ServicesCounselingMoveAllowances/ServicesCounselingMoveAllowances.jsx
  src/pages/Office/ServicesCounselingMoveAllowances/ServicesCounselingMoveAllowances.test.jsx
Labels: Mountain Movers, INTEGRATION

#14760 MAIN B-21982
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20250206173204_add_hawaii_data.up.sql
Labels: Mountain Movers, MAIN

#14764 B 22305 main milmove error message has incorrect url for technical helpdesk
  src/shared/ErrorModal/ErrorModal.jsx
Labels: G-Unit, MAIN

#14797 B 21961 add roles to requested office users list sorting
  pkg/handlers/adminapi/api.go
  pkg/handlers/adminapi/requested_office_users.go
  pkg/handlers/adminapi/requested_office_users_test.go
  pkg/handlers/ghcapi/tranportation_offices.go
  pkg/handlers/internalapi/transportation_offices.go
  pkg/models/errors.go
  pkg/models/roles/roles.go
  pkg/models/roles/roles_test.go
  pkg/services/mocks/RequestedOfficeUserListFetcher.go
  pkg/services/mocks/TransportationOfficesFetcher.go
  pkg/services/requested_office_users.go
  pkg/services/requested_office_users/requested_office_user_list_fetcher_test.go
  pkg/services/requested_office_users/requested_office_users_list_fetcher.go
  pkg/services/transportation_office.go
  pkg/services/transportation_office/transportation_office_fetcher.go
  pkg/services/transportation_office/transportation_office_fetcher_test.go
  src/pages/Admin/RequestedOfficeUsers/RequestedOfficeUserList.jsx
  src/pages/Admin/RequestedOfficeUsers/RequestedOfficeUserShow.module.scss
Labels: Mountain Movers, MAIN

#14818 B 21440 int
  src/components/Office/ServiceItemCalculations/helpers.js
Labels: Scrummy Bears, INTEGRATION

#14830 INT-B-22621 Client test fix
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/transportation_office/get_transportation_offices_g_b_l_o_cs_responses.go
  pkg/handlers/internalapi/internal/payloads/model_to_payload_test.go
  src/pages/Office/ServicesCounselingMoveAllowances/ServicesCounselingMoveAllowances.test.jsx
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: Mountain Movers, INTEGRATION

#14790 B-21322 TPPS ECS Scheduled Task - INT
  .gitlab-ci.yml
  Dockerfile.tasks_dp3
  Makefile
  cmd/ecs-deploy/put_target.go
  cmd/ecs-deploy/task_def.go
  cmd/milmove-tasks/main.go
  cmd/milmove-tasks/process_edis.go
  cmd/milmove-tasks/process_tpps.go
  cmd/milmove-tasks/process_tpps_test.go
  config/env/demo.process-tpps.env
  config/env/exp.process-tpps.env
  config/env/prd.process-tpps.env
  config/env/stg.process-tpps.env
  pkg/cli/gex_sftp.go
  pkg/cli/tpps_processing.go
  pkg/cli/tpps_processing_test.go
  pkg/edi/tpps_paid_invoice_report/parser.go
  pkg/edi/tpps_paid_invoice_report/parser_test.go
  pkg/services/invoice.go
  pkg/services/invoice/fixtures/tpps_paid_invoice_report_testfile_large_encoded.csv
  pkg/services/invoice/process_tpps_paid_invoice_report.go
  pkg/services/invoice/process_tpps_paid_invoice_report_test.go
  pkg/services/mocks/TPPSPaidInvoiceReportProcessor.go
  pkg/services/order/order_updater.go
  scripts/deploy-app-tasks
Labels: Mountain Movers, INTEGRATION

#14807 B-22205 B-22209 B-22210 Fix TGET ingestion for good
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20250122193153_drop-tac-loa-fk.up.sql
  migrations/app/schema/20250122193154_trdm-tac-composite-key.up.sql
  migrations/app/schema/20250122193234_trdm-loa-composite-key.up.sql
Labels: Mountain Movers, INTEGRATION

#14747 B-22368-MAIN Add closeout counselor to move history
  src/constants/MoveHistory/Database/FieldMappings.js
  src/constants/MoveHistory/EventTemplates/UpdateAssignedOfficeUser/DeleteAssignedOfficeUser.jsx
  src/constants/MoveHistory/EventTemplates/UpdateAssignedOfficeUser/DeleteAssignedOfficeUser.test.jsx
  src/constants/MoveHistory/EventTemplates/UpdateAssignedOfficeUser/UpdateAssignedOfficeUser.test.jsx
  src/utils/formatters.js
  src/utils/formatters.test.js
Labels: G-Unit, MAIN

#14828 B 21962 create requested users report
  src/pages/Admin/RequestedOfficeUsers/RequestedOfficeUserList.jsx
Labels: Mountain Movers, MAIN

#14708 B 21348 INT bulk assignment save
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/ghcapi/ghcoperations/queues/save_bulk_assignment_data.go
  pkg/gen/ghcapi/ghcoperations/queues/save_bulk_assignment_data_parameters.go
  pkg/gen/ghcapi/ghcoperations/queues/save_bulk_assignment_data_responses.go
  pkg/gen/ghcapi/ghcoperations/queues/save_bulk_assignment_data_urlbuilder.go
  pkg/gen/ghcmessages/bulk_assignment_for_user.go
  pkg/gen/ghcmessages/bulk_assignment_move_data.go
  pkg/gen/ghcmessages/bulk_assignment_save_payload.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/queues.go
  pkg/handlers/ghcapi/queues_test.go
  pkg/services/mocks/MoveAssigner.go
  pkg/services/mocks/MoveFetcher.go
  pkg/services/move.go
  pkg/services/move/move_assignment.go
  pkg/services/move/move_assignment_test.go
  pkg/services/move/move_fetcher.go
  src/components/BulkAssignment/BulkAssignmentModal.jsx
  src/components/BulkAssignment/BulkAssignmentModal.module.scss
  src/components/BulkAssignment/BulkAssignmentModal.test.jsx
  src/components/Table/TableQueue.jsx
  src/constants/MoveHistory/EventTemplates/SaveBulkAssignmentData/SaveBulkAssignmentData.jsx
  src/constants/MoveHistory/EventTemplates/SaveBulkAssignmentData/SaveBulkAssignmentData.test.jsx
  src/constants/MoveHistory/EventTemplates/index.js
  src/constants/MoveHistory/UIDisplay/Operations.js
  src/hooks/queries.js
  src/hooks/queries.test.jsx
  src/pages/Office/HeadquartersQueues/HeadquartersQueues.jsx
  src/pages/Office/MoveQueue/MoveQueue.jsx
  src/pages/Office/PaymentRequestQueue/PaymentRequestQueue.jsx
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.jsx
  src/services/ghcApi.js
  src/store/general/action.test.js
  src/store/general/actions.js
  src/store/general/reducer.js
  src/store/general/reducer.test.js
  src/store/general/selectors.js
  src/store/general/selectors.test.js
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: G-Unit, INTEGRATION

#14042 B-21551 estimated prices now calculates for NTS-R shipments
  pkg/services/mocks/MTOServiceItemCreator.go
  pkg/services/mto_service_item.go
  pkg/services/mto_service_item/mto_service_item_creator.go
  pkg/services/mto_service_item/mto_service_item_creator_test.go
Labels: G-Unit, MAIN

#14825 B 22301 int - Prevent User from Entering Additional Address Until the Preceding Address Is Complete
  src/components/Customer/MtoShipmentForm/MtoShipmentForm.jsx
  src/components/Customer/MtoShipmentForm/MtoShipmentForm.test.jsx
  src/components/Customer/PPM/Booking/DateAndLocationForm/DateAndLocationForm.jsx
  src/components/Customer/PPM/Booking/DateAndLocationForm/DateAndLocationForm.test.jsx
  src/shared/utils.js
Labels: G-Unit, INTEGRATION, frontend

#14749 MAIN - B-22020 - TIO payment request calculations -BE
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20250110201339_add_payment_params_for_intl_crating_uncrating.up.sql
  migrations/app/schema/20250204162411_updating_create_accessorial_service_item_proc_for_crating.up.sql
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/mto_service_item/update_m_t_o_service_item.go
  pkg/gen/primeclient/mto_service_item/mto_service_item_client.go
  pkg/gen/primemessages/update_m_t_o_service_item.go
  pkg/gen/primemessages/update_m_t_o_service_item_crating.go
  pkg/gen/primemessages/update_m_t_o_service_item_model_type.go
  pkg/models/mto_service_items.go
  pkg/models/mto_service_items_test.go
  pkg/models/re_intl_accessorial_price.go
  pkg/models/service_item_param_key.go
  pkg/payment_request/service_param_value_lookups/cubic_feet_billed_lookup.go
  pkg/payment_request/service_param_value_lookups/cubic_feet_billed_lookup_test.go
  pkg/payment_request/service_param_value_lookups/external_crate_lookup.go
  pkg/payment_request/service_param_value_lookups/external_crate_lookup_test.go
  pkg/payment_request/service_param_value_lookups/service_param_value_lookups.go
  pkg/services/ghc_rate_engine.go
  pkg/services/ghcrateengine/intl_crating_pricer.go
  pkg/services/ghcrateengine/intl_crating_pricer_test.go
  pkg/services/ghcrateengine/intl_uncrating_pricer.go
  pkg/services/ghcrateengine/intl_uncrating_pricer_test.go
  pkg/services/ghcrateengine/pricer_helpers_intl.go
  pkg/services/ghcrateengine/pricer_helpers_intl_test.go
  pkg/services/ghcrateengine/service_item_pricer.go
  pkg/services/ghcrateengine/service_item_pricer_test.go
  pkg/services/ghcrateengine/shared.go
  pkg/services/mocks/IntlCratingPricer.go
  pkg/services/mocks/IntlUncratingPricer.go
  pkg/services/mto_service_item/mto_service_item_validators.go
  swagger-def/prime.yaml
  swagger/prime.yaml
Labels: ByteSize M&Ms, MAIN

#14827 Main B-21985 counseling fee final payment review
  src/components/Office/ReviewServiceItems/ReviewAccountingCodes.test.jsx
Labels: MAIN, Go-Rillaz

#14841 MAIN B-22272 v2
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20250123173216_add_destination_queue_db_func_and_gbloc_view.up.sql
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/ghcapi/ghcoperations/queues/get_destination_requests_queue.go
  pkg/gen/ghcapi/ghcoperations/queues/get_destination_requests_queue_parameters.go
  pkg/gen/ghcapi/ghcoperations/queues/get_destination_requests_queue_responses.go
  pkg/gen/ghcapi/ghcoperations/queues/get_destination_requests_queue_urlbuilder.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/queues.go
  pkg/handlers/ghcapi/queues_test.go
  pkg/models/move.go
  pkg/models/mto_shipments.go
  pkg/models/order.go
  pkg/services/mocks/OrderFetcher.go
  pkg/services/order.go
  pkg/services/order/order_fetcher.go
  pkg/services/order/order_fetcher_test.go
  src/constants/routes.js
  src/hooks/queries.js
  src/pages/Office/MoveQueue/MoveQueue.jsx
  src/pages/Office/MoveQueue/MoveQueue.test.jsx
  src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.jsx
  src/services/ghcApi.js
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: Mountain Movers, MAIN

#14447 B 21557 estimated price
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/mto_service_items_test.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/handlers/internalapi/api.go
  pkg/handlers/internalapi/mto_shipment_test.go
  pkg/handlers/primeapiv2/api.go
  pkg/handlers/primeapiv2/mto_shipment.go
  pkg/handlers/primeapiv3/api.go
  pkg/handlers/primeapiv3/mto_shipment.go
  pkg/handlers/primeapiv3/mto_shipment_test.go
  pkg/services/mto_service_item/mto_service_item_creator.go
  pkg/services/mto_service_item/mto_service_item_creator_test.go
  pkg/services/orchestrators/shipment/shipment_updater.go
  pkg/services/orchestrators/shipment/shipment_updater_test.go
Labels: G-Unit, MAIN

#14843 MAIN B-22451 v2
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20250210175754_B22451_update_dest_queue_to_consider_sit_extensions.up.sql
  pkg/factory/mto_service_item_factory.go
  pkg/factory/mto_service_item_factory_test.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload_test.go
  pkg/models/re_service.go
  pkg/services/mto_shipment/shipment_approver_test.go
  pkg/services/order/order_fetcher_test.go
  pkg/testdatagen/testharness/dispatch.go
  pkg/testdatagen/testharness/make_move.go
  playwright/tests/utils/testharness.js
  src/components/Office/ShipmentServiceItemsTable/ShipmentServiceItemsTable.test.jsx
  src/constants/MoveHistory/EventTemplates/UpdateMTOServiceItem/updateServiceItemPricingAndWeights.test.jsx
  src/pages/PrimeUI/MoveTaskOrder/MoveDetails.test.jsx
  src/pages/PrimeUI/UpdateServiceItems/PrimeUIUpdateInternationalFuelSurchargeForm.test.jsx
Labels: Mountain Movers, MAIN

#14812 B 21941 main v3
  pkg/handlers/ghcapi/queues_test.go
  pkg/services/order/order_fetcher.go
  pkg/services/order/order_fetcher_test.go
  pkg/unit/millicents_test.go
  playwright/tests/office/txo/tooFlows.spec.js
Labels: Mountain Movers, MAIN

#14765 MAIN B-21416 intl crating tio update for payment request-FE
  pkg/testdatagen/testharness/dispatch.go
  pkg/testdatagen/testharness/make_move.go
  playwright/tests/office/txo/tioFlowsInternational.spec.js
  playwright/tests/utils/testharness.js
  src/components/Office/PaymentRequestDetails/PaymentRequestDetails.jsx
  src/components/Office/ServiceItemCalculations/ServiceItemCalculations.jsx
  src/components/Office/ServiceItemCalculations/ServiceItemCalculations.module.scss
  src/components/Office/ServiceItemCalculations/helpers.js
  src/components/Office/ServiceItemCalculations/helpers.test.js
  src/components/Office/ServiceItemCalculations/serviceItemTestParams.js
  src/constants/serviceItems.js
Labels: ByteSize M&Ms, MAIN

#14836 Main b 21943 prime sim resubmit sit
  pkg/services/mto_service_item/mto_service_item_validators.go
  pkg/services/mto_service_item/mto_service_item_validators_test.go
  scripts/run-server-test
  src/pages/PrimeUI/UpdateServiceItems/PrimeUIUpdateDestSITForm.jsx
  src/pages/PrimeUI/UpdateServiceItems/PrimeUIUpdateDestSITForm.test.jsx
  src/pages/PrimeUI/UpdateServiceItems/PrimeUIUpdateOriginSITForm.jsx
  src/pages/PrimeUI/UpdateServiceItems/PrimeUIUpdateOriginSITForm.test.jsx
  src/pages/PrimeUI/UpdateServiceItems/PrimeUIUpdateServiceItem.jsx
  src/pages/PrimeUI/UpdateServiceItems/PrimeUpdateSitServiceItem.test.jsx
Labels: MAIN, Go-Rillaz

#14566 B-21399 bulk assignment cancel modal
  src/components/BulkAssignment/BulkAssignmentModal.jsx
  src/components/BulkAssignment/BulkAssignmentModal.module.scss
  src/components/BulkAssignment/BulkAssignmentModal.test.jsx
Labels: G-Unit, MAIN

#14820 MAIN B-22621
  pkg/services/order/order_updater.go
  pkg/services/order/order_updater_test.go
  src/components/Office/AllowancesDetailForm/AllowancesDetailForm.jsx
  src/components/Office/AllowancesDetailForm/AllowancesDetailForm.test.jsx
  src/pages/Office/MoveAllowances/MoveAllowances.jsx
  src/pages/Office/MoveAllowances/MoveAllowances.test.jsx
  src/pages/Office/ServicesCounselingMoveAllowances/ServicesCounselingMoveAllowances.jsx
  src/pages/Office/ServicesCounselingMoveAllowances/ServicesCounselingMoveAllowances.test.jsx
Labels: Mountain Movers, MAIN

#14829 Main b 21698
  src/utils/ppmCloseout.jsx
  src/utils/ppmCloseout.test.jsx
  src/utils/shipmentWeights.js
  src/utils/shipmentWeights.test.js
  src/utils/test/factories/proGearWeightTicket.js
Labels: MAIN, Go-Rillaz

#14782 B-21378: Need to fix RDD Calculation
  pkg/services/mto_shipment/mto_shipment_address_updater_test.go
  pkg/services/mto_shipment/mto_shipment_updater.go
  pkg/services/mto_shipment/mto_shipment_updater_test.go
Labels: Mountain Movers, INTEGRATION

#14839 B 22726 INT
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet_test.go
Labels: G-Unit, INTEGRATION

#14512 B 21464 main
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/mto_service_items_test.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/handlers/primeapi/api.go
  pkg/handlers/primeapi/mto_service_item_test.go
  pkg/handlers/supportapi/api.go
  pkg/handlers/supportapi/mto_service_item_test.go
  pkg/iws/rbs_error_test.go
  pkg/models/mto_service_items.go
  pkg/services/mocks/MTOServiceItemUpdater.go
  pkg/services/move_history/move_history_fetcher_test.go
  pkg/services/mto_service_item.go
  pkg/services/mto_service_item/mto_service_item_updater.go
  pkg/services/mto_service_item/mto_service_item_updater_test.go
  pkg/services/mto_service_item/mto_service_item_validators.go
  pkg/services/shipment_address_update/shipment_address_update_requester.go
  pkg/services/shipment_address_update/shipment_address_update_requester_test.go
  pkg/services/sit_extension/sit_extension_denier.go
  pkg/testdatagen/scenario/shared.go
Labels: do not merge, Scrummy Bears, MAIN

#14833 Update Migrations Process
  .envrc
  .gitlab-ci.yml
  .pre-commit-config.yaml
  Dockerfile.migrations
  cmd/milmove/gen_migration.go
  cmd/milmove/migrate.go
  config/env/demo.migrations.env
  config/env/exp.migrations.env
  config/env/loadtest.migrations.env
  config/env/prd.migrations.env
  config/env/stg.migrations.env
  migrations/app/ddl_functions_manifest.txt
  migrations/app/ddl_tables_manifest.txt
  migrations/app/ddl_types_manifest.txt
  migrations/app/ddl_views_manifest.txt
  migrations/app/dml_migrations_manifest.txt
  migrations/app/migrations_manifest.txt
  pkg/cli/migration.go
  scripts/README.md
  scripts/generate-ddl-migration
  scripts/generate-secure-migration
Labels: enhancement, database, backend

#14858 B 21440 main
  pkg/testdatagen/testharness/make_move.go
  playwright/tests/office/txo/tioFlowsInternational.spec.js
  src/components/Office/ServiceItemCalculations/helpers.js
  src/constants/serviceItems.js
Labels: Scrummy Bears, MAIN

#14866 INT B-22661
  package.json
  src/components/Customer/OrdersInfoForm/OrdersInfoForm.jsx
  src/components/Customer/OrdersInfoForm/OrdersInfoForm.stories.jsx
  src/components/Customer/OrdersInfoForm/OrdersInfoForm.test.jsx
  src/components/Customer/WizardNavigation/WizardNavigation.module.scss
  src/components/LoadingSpinner/LoadingSpinner.jsx
  src/components/LoadingSpinner/LoadingSpinner.module.scss
  src/components/LoadingSpinner/LoadingSpinner.stories.jsx
  src/components/LoadingSpinner/LoadingSpinner.test.jsx
  src/pages/MyMove/Home/index.stories.jsx
  src/scenes/MyMove/index.jsx
  src/scenes/MyMove/index.test.js
  src/scenes/MyMove/index.test.jsx
  src/store/auth/selectors.js
  src/store/general/action.test.js
  src/store/general/actions.js
  src/store/general/reducer.js
  src/store/general/reducer.test.js
  yarn.lock
Labels: Mountain Movers, INTEGRATION

#14873 B-22307 int deleted documents use db function
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20250207153450_add_fetch_documents_func.up.sql
  migrations/app/schema/20250213151815_fix_spacing_fetch_documents.up.sql
  pkg/handlers/ghcapi/documents.go
  pkg/handlers/ghcapi/uploads.go
  pkg/handlers/internalapi/documents.go
  pkg/handlers/internalapi/uploads.go
  pkg/models/document.go
  pkg/models/document_test.go
  pkg/models/user_upload.go
  pkg/services/paperwork/prime_download_user_upload_to_pdf_converter.go
  pkg/services/ppm_closeout/ppm_closeout.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet.go
Labels: Scrummy Bears, MAIN

#14875 INT B-22769
  pkg/services/ghc_rate_engine.go
  pkg/services/ghcrateengine/domestic_shorthaul_pricer.go
  pkg/services/ghcrateengine/domestic_shorthaul_pricer_test.go
  pkg/services/ghcrateengine/pricer_helpers.go
  pkg/services/mocks/DomesticShorthaulPricer.go
  pkg/services/mto_service_item/mto_service_item_creator.go
  pkg/services/ppmshipment/ppm_estimator.go
Labels: Mountain Movers, INTEGRATION

#14745 B 22301 main - Prevent User from Entering Additional Address Until the Preceding Address Is Complete
  src/components/Customer/MtoShipmentForm/MtoShipmentForm.jsx
  src/components/Customer/MtoShipmentForm/MtoShipmentForm.test.jsx
  src/components/Customer/PPM/Booking/DateAndLocationForm/DateAndLocationForm.jsx
  src/components/Customer/PPM/Booking/DateAndLocationForm/DateAndLocationForm.test.jsx
  src/components/Office/ShipmentForm/ShipmentForm.jsx
  src/shared/utils.js
  src/utils/formatMtoShipment.js
  src/utils/formatMtoShipment.test.js
Labels: G-Unit, MAIN, frontend

#14655 B-21473 Add extra days for Alaska shipments
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20250123210535_update_re_intl_transit_times_for_ak_hhg.up.sql
  pkg/factory/address_factory.go
  pkg/models/address.go
  pkg/models/address_test.go
  pkg/services/mto_shipment/mto_shipment_updater.go
  pkg/services/mto_shipment/mto_shipment_updater_test.go
  pkg/services/mto_shipment/rules.go
  pkg/services/mto_shipment/shipment_approver.go
Labels: G-Unit, MAIN

#14877 Main B-20984 Validate SIT Departure Date
  pkg/handlers/primeapi/mto_service_item_test.go
  pkg/services/mto_service_item/mto_service_item_creator.go
  pkg/services/mto_service_item/mto_service_item_creator_test.go
  pkg/services/mto_service_item/mto_service_item_validators.go
  pkg/services/mto_service_item/mto_service_item_validators_test.go
  pkg/services/sit_entry_date_update/sit_entry_date_updater.go
  pkg/services/sit_entry_date_update/sit_entry_date_updater_test.go
  pkg/testdatagen/scenario/shared.go
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.test.jsx
  src/pages/Office/MoveTaskOrder/moveTaskOrderUnitTestData.js
Labels: MAIN, Go-Rillaz

#14867 B 21348 INT
  src/components/Table/TableQueue.jsx
Labels: G-Unit, INTEGRATION

#14892 Hdt 2617 main
  go.mod
  go.sum
Labels: Mountain Movers, MAIN

#14886 Int b 21480 second pr
  pkg/services/mocks/TransportationOfficesFetcher.go
  pkg/services/move/move_router.go
  pkg/services/move/move_router_test.go
  pkg/services/mto_service_item/mto_service_item_creator_test.go
  pkg/services/transportation_office.go
  pkg/services/transportation_office/transportation_office_fetcher.go
  pkg/services/transportation_office/transportation_office_fetcher_test.go
Labels: INTEGRATION, Go-Rillaz, backend

#14897 Update .gitlab-ci.yml
  .gitlab-ci.yml
Labels: MAIN

#14881 INT B-22660
  migrations/app/ddl_functions_manifest.txt
  migrations/app/ddl_migrations/ddl_functions/20250223023132_fn_get_counseling_offices.up.sql
  pkg/models/transportation_office.go
  pkg/models/transportation_office_test.go
  pkg/services/transportation_office/transportation_office_fetcher.go
  pkg/services/transportation_office/transportation_office_fetcher_test.go
  src/components/Customer/EditOrdersForm/EditOrdersForm.jsx
  src/components/Customer/EditOrdersForm/EditOrdersForm.stories.jsx
  src/components/Customer/EditOrdersForm/EditOrdersForm.test.jsx
  src/components/Customer/OrdersInfoForm/OrdersInfoForm.jsx
  src/components/Office/AddOrdersForm/AddOrdersForm.jsx
  src/pages/MyMove/AddOrders.test.jsx
  src/pages/MyMove/EditOrders.test.jsx
Labels: Mountain Movers, INTEGRATION

#14800 MAIN - B-22300 - add dependents authorized to orders page
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/counseling_update_allowance_payload.go
  pkg/gen/ghcmessages/counseling_update_order_payload.go
  pkg/gen/ghcmessages/update_allowance_payload.go
  pkg/gen/ghcmessages/update_order_payload.go
  pkg/handlers/ghcapi/orders_test.go
  pkg/services/order/order_updater.go
  pkg/services/order/order_updater_test.go
  playwright/tests/my/mymove/boat.spec.js
  playwright/tests/office/qaecsr/csrFlows.spec.js
  src/components/Office/AllowancesDetailForm/AllowancesDetailForm.jsx
  src/components/Office/DefinitionLists/AllowancesList.jsx
  src/components/Office/DefinitionLists/AllowancesList.stories.jsx
  src/components/Office/DefinitionLists/AllowancesList.test.jsx
  src/components/Office/DefinitionLists/OrdersList.jsx
  src/components/Office/DefinitionLists/OrdersList.stories.jsx
  src/components/Office/DefinitionLists/OrdersList.test.jsx
  src/components/Office/OrdersDetailForm/OrdersDetailForm.jsx
  src/components/Office/OrdersDetailForm/OrdersDetailForm.module.scss
  src/components/Office/OrdersDetailForm/OrdersDetailForm.test.jsx
  src/pages/Office/MoveAllowances/MoveAllowances.jsx
  src/pages/Office/MoveAllowances/MoveAllowances.test.jsx
  src/pages/Office/MoveDetails/MoveDetails.jsx
  src/pages/Office/Orders/Orders.jsx
  src/pages/Office/Orders/Orders.test.jsx
  src/pages/Office/ServicesCounselingMoveAllowances/ServicesCounselingMoveAllowances.jsx
  src/pages/Office/ServicesCounselingMoveAllowances/ServicesCounselingMoveAllowances.test.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
  src/pages/Office/ServicesCounselingOrders/ServicesCounselingOrders.jsx
  src/pages/Office/ServicesCounselingOrders/ServicesCounselingOrders.test.jsx
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: ByteSize M&Ms, MAIN

#14854 MAIN B-22661
  package.json
  src/components/Customer/OrdersInfoForm/OrdersInfoForm.jsx
  src/components/Customer/OrdersInfoForm/OrdersInfoForm.stories.jsx
  src/components/Customer/OrdersInfoForm/OrdersInfoForm.test.jsx
  src/components/Customer/WizardNavigation/WizardNavigation.module.scss
  src/components/LoadingSpinner/LoadingSpinner.jsx
  src/components/LoadingSpinner/LoadingSpinner.module.scss
  src/components/LoadingSpinner/LoadingSpinner.stories.jsx
  src/components/LoadingSpinner/LoadingSpinner.test.jsx
  src/pages/MyMove/Home/index.stories.jsx
  src/scenes/MyMove/index.jsx
  src/scenes/MyMove/index.test.js
  src/scenes/MyMove/index.test.jsx
  src/store/auth/selectors.js
  src/store/general/action.test.js
  src/store/general/actions.js
  src/store/general/reducer.js
  src/store/general/reducer.test.js
  yarn.lock
Labels: Mountain Movers, MAIN

#14888 B-21322 INT: stg/prd env script updates
  .gitlab-ci.yml
  Dockerfile.tasks
Labels: Mountain Movers, INTEGRATION

#14885 INT-B-22777 PPM Deleted Expense Defect
  pkg/services/ppm_closeout/ppm_closeout.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet.go
Labels: ByteSize M&Ms, INTEGRATION

#14882 B-22651 INT
  migrations/app/ddl_migrations/ddl_tables/20250221195354_tbl_alter_entitlements_B-22651.up.sql
  migrations/app/ddl_tables_manifest.txt
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/counseling_update_allowance_payload.go
  pkg/gen/ghcmessages/entitlements.go
  pkg/gen/ghcmessages/update_allowance_payload.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/entitlements.go
  pkg/gen/primev2api/embedded_spec.go
  pkg/gen/primev2messages/entitlements.go
  pkg/gen/primev3api/embedded_spec.go
  pkg/gen/primev3messages/entitlements.go
  pkg/gen/supportapi/embedded_spec.go
  pkg/gen/supportmessages/entitlement.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload_test.go
  pkg/handlers/ghcapi/orders.go
  pkg/handlers/primeapi/payloads/model_to_payload.go
  pkg/handlers/primeapi/payloads/model_to_payload_test.go
  pkg/handlers/primeapiv2/payloads/model_to_payload.go
  pkg/handlers/primeapiv2/payloads/model_to_payload_test.go
  pkg/handlers/primeapiv3/payloads/model_to_payload.go
  pkg/handlers/primeapiv3/payloads/model_to_payload_test.go
  pkg/models/ghc_entitlements.go
  pkg/services/order/order_updater.go
  pkg/services/order/order_updater_test.go
  src/components/Office/AllowancesDetailForm/AllowancesDetailForm.jsx
  src/components/Office/AllowancesDetailForm/AllowancesDetailForm.test.jsx
  src/components/Office/DefinitionLists/AllowancesList.jsx
  src/components/Office/DefinitionLists/AllowancesList.test.jsx
  src/constants/MoveHistory/Database/BooleanFields.js
  src/constants/MoveHistory/Database/FieldMappings.js
  src/pages/Office/MoveAllowances/MoveAllowances.jsx
  src/pages/Office/MoveDetails/MoveDetails.jsx
  src/pages/Office/ServicesCounselingMoveAllowances/ServicesCounselingMoveAllowances.jsx
  src/pages/Office/ServicesCounselingMoveAllowances/ServicesCounselingMoveAllowances.test.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
  swagger-def/definitions/prime/Entitlements.yaml
  swagger-def/ghc.yaml
  swagger-def/support.yaml
  swagger/ghc.yaml
  swagger/prime.yaml
  swagger/prime_v2.yaml
  swagger/prime_v3.yaml
  swagger/support.yaml
Labels: Mountain Movers, INTEGRATION

#14890 INT B-22653
  .circleci/config.yml
  .envrc
  config/env/demo.app-client-tls.env
  config/env/demo.app.env
  config/env/exp.app-client-tls.env
  config/env/exp.app.env
  config/env/loadtest.app-client-tls.env
  config/env/loadtest.app.env
  config/env/prd.app-client-tls.env
  config/env/prd.app.env
  config/env/stg.app-client-tls.env
  config/env/stg.app.env
  config/flipt/storage/development.features.yaml
  migrations/app/ddl_migrations/ddl_tables/20250224200700_tbl_ppm_shipments.up.sql
  migrations/app/ddl_migrations/ddl_types/20250224202726_ty_ppm_shipment_type.up.sql
  migrations/app/ddl_migrations/ddl_types/20250224202738_ty_moving_expenses_type.up.sql
  migrations/app/ddl_tables_manifest.txt
  migrations/app/ddl_types_manifest.txt
  pkg/factory/ppm_shipment_factory.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/p_p_m_shipment.go
  pkg/gen/ghcmessages/p_p_m_type.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/p_p_m_shipment.go
  pkg/gen/internalmessages/p_p_m_type.go
  pkg/models/moving_expense.go
  pkg/models/ppm_shipment.go
  pkg/models/ppm_shipment_test.go
  pkg/services/ppmshipment/ppm_shipment_creator.go
  pkg/services/ppmshipment/ppm_shipment_creator_test.go
  src/components/Table/TableQueue.stories.jsx
  src/shared/constants.js
  swagger-def/definitions/PPMShipment.yaml
  swagger-def/definitions/PPMType.yaml
  swagger/ghc.yaml
  swagger/internal.yaml
Labels: Mountain Movers, INTEGRATION

#14895 B 22767 INT - Origin and Destination Rate Area Should not be sent to the Prime for Shipments with Only Domestic Addresses
  pkg/handlers/primeapiv3/payloads/model_to_payload.go
  pkg/handlers/primeapiv3/payloads/model_to_payload_test.go
  pkg/services/mto_shipment/mto_shipment_rate_area_fetcher.go
  pkg/services/mto_shipment/mto_shipment_rate_area_fetcher_test.go
Labels: Scrummy Bears, INTEGRATION

#14900 disable bookmark extraction in tests
  pkg/services/ppmshipment/payment_packet_creator_test.go
Labels: Mountain Movers, MAIN

#14864 Int b 21969 export csv bttn dest gbloc queue
  src/components/Table/TableCSVExportButton.jsx
  src/components/Table/TableQueue.jsx
  src/pages/Office/MoveQueue/MoveQueue.jsx
Labels: INTEGRATION, Go-Rillaz, frontend

#14894 Int b 22586 export all office users for admin
  src/pages/Admin/OfficeUsers/OfficeUserList.jsx
Labels: INTEGRATION, Go-Rillaz, frontend

#14233 B-21322 TPPS ECS Scheduled Task - MAIN
  .gitlab-ci.yml
  Dockerfile.tasks
  Dockerfile.tasks_dp3
  Makefile
  cmd/ecs-deploy/put_target.go
  cmd/ecs-deploy/task_def.go
  cmd/milmove-tasks/main.go
  cmd/milmove-tasks/process_edis.go
  cmd/milmove-tasks/process_tpps.go
  cmd/milmove-tasks/process_tpps_test.go
  config/env/demo.process-tpps.env
  config/env/exp.process-tpps.env
  config/env/loadtest.process-tpps.env
  config/env/prd.process-tpps.env
  config/env/stg.process-tpps.env
  migrations/app/migrations_manifest.txt
  migrations/app/schema/20250213214427_drop_received_by_gex_payment_request_status_type.up.sql
  pkg/cli/gex_sftp.go
  pkg/cli/tpps_processing.go
  pkg/cli/tpps_processing_test.go
  pkg/edi/tpps_paid_invoice_report/parser.go
  pkg/edi/tpps_paid_invoice_report/parser_test.go
  pkg/services/invoice.go
  pkg/services/invoice/fixtures/tpps_paid_invoice_report_testfile_large_encoded.csv
  pkg/services/invoice/process_tpps_paid_invoice_report.go
  pkg/services/invoice/process_tpps_paid_invoice_report_test.go
  pkg/services/mocks/TPPSPaidInvoiceReportProcessor.go
  scripts/deploy-app-tasks
  src/constants/MoveHistory/EventTemplates/UpdatePaymentRequest/updatePaymentRequest.test.jsx
  src/constants/MoveHistory/EventTemplates/UpdatePaymentRequest/updatePaymentRequestJobRunner.test.jsx
  src/constants/paymentRequestStatus.js
  src/pages/Office/PaymentRequestQueue/PaymentRequestQueue.test.jsx
  src/utils/formatters.test.js
Labels: do not merge, Mountain Movers, MAIN

#14845 INT-B-21094 Fix for SIT and weight allowance issues
  pkg/services/move/move_weights.go
  pkg/services/move/move_weights_test.go
  pkg/services/mto_shipment/mto_shipment_updater.go
Labels: ByteSize M&Ms, INTEGRATION

#14879 B 22706 int
  migrations/app/ddl_migrations/ddl_tables/20250224162949_B-22706_tbl_update_moves.up.sql
  migrations/app/ddl_tables_manifest.txt
  pkg/models/move.go
Labels: G-Unit, INTEGRATION

#14901 disable bookmark extraction in tests
  pkg/services/ppmshipment/payment_packet_creator_test.go
Labels: Mountain Movers, INTEGRATION

#14899 B-21378: UB RDD Adjustments
  pkg/models/re_intl_transit_times.go
  pkg/models/re_intl_transit_times_test.go
  pkg/services/mto_shipment/mto_shipment_updater.go
  pkg/services/mto_shipment/mto_shipment_updater_test.go
Labels: Mountain Movers, INTEGRATION

#14909 Main b 21669 doc viewer file upload status per s3 events
  src/components/DocumentViewer/DocumentViewer.jsx
  src/components/DocumentViewer/DocumentViewer.test.jsx
  src/components/DocumentViewerFileManager/DocumentViewerFileManager.jsx
  src/pages/Office/MoveDocumentWrapper/MoveDocumentWrapper.jsx
  src/pages/Office/Orders/Orders.jsx
  src/pages/Office/PPM/ReviewDocuments/ReviewDocuments.test.jsx
  src/pages/Office/PaymentRequestReview/PaymentRequestReview.test.jsx
  src/pages/Office/ServicesCounselingMoveDocumentWrapper/ServicesCounselingMoveDocumentWrapper.jsx
  src/pages/Office/ServicesCounselingOrders/ServicesCounselingOrders.jsx
  src/pages/Office/SupportingDocuments/SupportingDocuments.jsx
  src/pages/Office/SupportingDocuments/SupportingDocuments.test.jsx
  src/shared/constants.js
Labels: MAIN, Go-Rillaz, frontend

#14907 Int b 22692 add prime acknowledged at columns
  migrations/app/ddl_functions_manifest.txt
  migrations/app/ddl_migrations/ddl_functions/20250225183302_fn_prime_acknowledge_moves_shipments.up.sql
  migrations/app/ddl_migrations/ddl_tables/20250225182052_tbl_B-22692_alter_moves.up.sql
  migrations/app/ddl_migrations/ddl_tables/20250225183010_tbl_B-22692_alter_mto_shipments.up.sql
  migrations/app/ddl_tables_manifest.txt
  pkg/models/move.go
  pkg/models/mto_shipments.go
Labels: INTEGRATION, Go-Rillaz

#14884 B-22657: Ignore Updating updated_at Column when Locking/Unlocking Moves
  pkg/services/lock_move/move_locker.go
  pkg/services/lock_move/move_locker_test.go
  pkg/services/lock_move/move_unlocker.go
  pkg/services/lock_move/move_unlocker_test.go
Labels: Mountain Movers, INTEGRATION

#14880 MAIN B-22660
  migrations/app/ddl_functions_manifest.txt
  migrations/app/ddl_migrations/ddl_functions/20250223023132_fn_get_counseling_offices.up.sql
  pkg/models/transportation_office.go
  pkg/models/transportation_office_test.go
  pkg/services/transportation_office/transportation_office_fetcher.go
  pkg/services/transportation_office/transportation_office_fetcher_test.go
  src/components/Customer/EditOrdersForm/EditOrdersForm.jsx
  src/components/Customer/EditOrdersForm/EditOrdersForm.stories.jsx
  src/components/Customer/EditOrdersForm/EditOrdersForm.test.jsx
  src/components/Customer/OrdersInfoForm/OrdersInfoForm.jsx
  src/components/Office/AddOrdersForm/AddOrdersForm.jsx
  src/pages/MyMove/AddOrders.test.jsx
  src/pages/MyMove/EditOrders.test.jsx
Labels: Mountain Movers, MAIN

#14914 B-22651 INT: I-13915 Update prime sim UI
  src/pages/PrimeUI/MoveTaskOrder/MoveDetails.jsx
  src/pages/PrimeUI/MoveTaskOrder/MoveDetails.test.jsx
Labels: Mountain Movers, INTEGRATION

#14874 MAIN B-22769
  pkg/services/ghc_rate_engine.go
  pkg/services/ghcrateengine/domestic_shorthaul_pricer.go
  pkg/services/ghcrateengine/domestic_shorthaul_pricer_test.go
  pkg/services/ghcrateengine/pricer_helpers.go
  pkg/services/mocks/DomesticShorthaulPricer.go
  pkg/services/mto_service_item/mto_service_item_creator.go
  pkg/services/ppmshipment/ppm_estimator.go
Labels: Mountain Movers, MAIN

#14889 MAIN B-22653
  .circleci/config.yml
  .envrc
  config/env/demo.app-client-tls.env
  config/env/demo.app.env
  config/env/exp.app-client-tls.env
  config/env/exp.app.env
  config/env/loadtest.app-client-tls.env
  config/env/loadtest.app.env
  config/env/prd.app-client-tls.env
  config/env/prd.app.env
  config/env/stg.app-client-tls.env
  config/env/stg.app.env
  config/flipt/storage/development.features.yaml
  migrations/app/ddl_migrations/ddl_tables/20250224200700_tbl_ppm_shipments.up.sql
  migrations/app/ddl_migrations/ddl_types/20250224202726_ty_ppm_shipment_type.up.sql
  migrations/app/ddl_migrations/ddl_types/20250224202738_ty_moving_expenses_type.up.sql
  migrations/app/ddl_tables_manifest.txt
  migrations/app/ddl_types_manifest.txt
  pkg/factory/ppm_shipment_factory.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/p_p_m_shipment.go
  pkg/gen/ghcmessages/p_p_m_type.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/p_p_m_shipment.go
  pkg/gen/internalmessages/p_p_m_type.go
  pkg/models/moving_expense.go
  pkg/models/ppm_shipment.go
  pkg/models/ppm_shipment_test.go
  pkg/services/ppmshipment/ppm_shipment_creator.go
  pkg/services/ppmshipment/ppm_shipment_creator_test.go
  src/components/Table/TableQueue.stories.jsx
  src/shared/constants.js
  swagger-def/definitions/PPMShipment.yaml
  swagger-def/definitions/PPMType.yaml
  swagger/ghc.yaml
  swagger/internal.yaml
Labels: Mountain Movers, MAIN

#14852 B 22602 INT - Dependency Scan (Severity Critical) JSONPath Plus Remote Code Execution (RCE) Vulnerability (Dev)
  package.json
  yarn.lock
Labels: Scrummy Bears, INTEGRATION
