Repository transcom/mymove, pull requests merged in 2025-05, with the labels that each got.

#15337 B-22482 - MAIN - Bulk Assignment Move Lock
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/queues.go
  pkg/handlers/ghcapi/queues_test.go
  pkg/services/lock_move.go
  pkg/services/lock_move/move_locker.go
  pkg/services/lock_move/move_locker_test.go
  src/components/Table/TableQueue.jsx
  src/components/Table/TableQueue.test.jsx
  src/containers/Headers/OfficeLoggedInHeader.jsx
  src/services/ghcApi.js
Labels: Scrummy Bears, MAIN

#15321 B 22910 I 14141 read only terminated shipments int
  pkg/handlers/primeapi/mto_shipment_address.go
  pkg/handlers/primeapi/mto_shipment_address_test.go
  pkg/services/mto_shipment/mto_shipment_address_updater.go
  pkg/services/mto_shipment/mto_shipment_address_updater_test.go
  pkg/services/mto_shipment/rules.go
  pkg/services/mto_shipment/rules_test.go
  pkg/services/mto_shipment/validation.go
Labels: bug, Mountain Movers, INTEGRATION, backend

#15318 B22596-INT-add crud button for expenses
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/ghcapi/ghcoperations/ppm/create_moving_expense.go
  pkg/gen/ghcapi/ghcoperations/ppm/create_moving_expense_parameters.go
  pkg/gen/ghcapi/ghcoperations/ppm/create_moving_expense_responses.go
  pkg/gen/ghcapi/ghcoperations/ppm/create_moving_expense_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/ppm/delete_moving_expense.go
  pkg/gen/ghcapi/ghcoperations/ppm/delete_moving_expense_parameters.go
  pkg/gen/ghcapi/ghcoperations/ppm/delete_moving_expense_responses.go
  pkg/gen/ghcapi/ghcoperations/ppm/delete_moving_expense_urlbuilder.go
  pkg/gen/ghcmessages/update_moving_expense.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/internal/payloads/payload_to_model.go
  pkg/handlers/ghcapi/internal/payloads/payload_to_model_test.go
  pkg/handlers/ghcapi/moving_expense.go
  pkg/handlers/ghcapi/moving_expense_test.go
  pkg/services/moving_expense/moving_expense_creator.go
  pkg/services/moving_expense/moving_expense_creator_test.go
  pkg/services/moving_expense/moving_expense_deleter.go
  pkg/services/ppmshipment/ppm_document_fetcher.go
  src/components/Customer/PPM/Closeout/ExpenseForm/ExpenseForm.jsx
  src/components/Office/PPM/ReviewExpense/ReviewExpense.jsx
  src/components/Shared/PPM/Closeout/ExpenseForm/ExpenseForm.jsx
  src/components/Shared/PPM/Closeout/ExpenseForm/ExpenseForm.module.scss
  src/components/Shared/PPM/Closeout/ExpenseForm/ExpenseForm.stories.jsx
  src/components/Shared/PPM/Closeout/ExpenseForm/ExpenseForm.test.jsx
  src/components/Shared/PPM/Closeout/SmallPackageForm/SmallPackageForm.jsx
  src/components/Shared/PPM/Closeout/SmallPackageForm/SmallPackageForm.module.scss
  src/components/Shared/PPM/Closeout/SmallPackageForm/SmallPackageForm.test.jsx
  src/pages/MyMove/PPM/Closeout/Expenses/Expenses.jsx
  src/pages/Office/PPM/Closeout/Expenses/Expenses.jsx
  src/pages/Office/PPM/Closeout/Expenses/Expenses.test.jsx
  src/pages/Office/PPM/Closeout/Review/Review.jsx
  src/pages/Office/PPM/Closeout/Review/Review.test.jsx
  src/pages/Office/ServicesCounselingMoveInfo/ServicesCounselingMoveInfo.jsx
  src/services/ghcApi.js
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: ByteSize M&Ms, INTEGRATION

#15361 B-22712-22759-INT Add approval request types to TOO queues
  migrations/app/ddl_migrations/ddl_functions/20250225233157_fn_get_destination_queue.up.sql
  src/constants/approvalRequestTypes.js
  src/constants/serviceItems.js
  src/pages/Office/MoveQueue/MoveQueue.jsx
  src/pages/Office/MoveQueue/MoveQueue.test.jsx
  src/utils/queues.jsx
  src/utils/queues.test.jsx
  yarn.lock
Labels: G-Unit, INTEGRATION

#15316 B 22732 INT - Only respond to first button click
  src/components/Customer/PPM/Booking/Advance/AdvanceForm.jsx
  src/components/Customer/PPM/Booking/DateAndLocationForm/DateAndLocationForm.jsx
  src/components/Customer/PPM/Booking/EstimatedWeightsProGearForm/EstimatedWeightsProGearForm.jsx
  src/components/LoadingButton/LoadingButton.jsx
  src/components/LoadingButton/LoadingButton.module.scss
  src/components/LoadingButton/LoadingButton.stories.jsx
  src/components/LoadingButton/LoadingButton.test.jsx
  src/components/Table/TableCSVExportButton.jsx
  src/components/Table/TableCSVExportButton.test.jsx
  src/pages/MyMove/PPM/Booking/Advance/Advance.jsx
  src/pages/MyMove/PPM/Booking/DateAndLocation/DateAndLocation.jsx
  src/pages/MyMove/PPM/Booking/EstimatedWeightsProGear/EstimatedWeightsProGear.jsx
Labels: Scrummy Bears, INTEGRATION

#15336 B-22895 too destination request assign user move history audit logs update
  pkg/assets/sql_scripts/move_history_fetcher.sql
  pkg/models/move.go
  pkg/models/re_service.go
  pkg/services/mto_service_item/mto_service_item_updater.go
  pkg/services/mto_service_item/mto_service_item_updater_test.go
  src/constants/MoveHistory/EventTemplates/UpdateAssignedOfficeUser/DeleteAssignedOfficeUser.jsx
  src/constants/MoveHistory/EventTemplates/UpdateAssignedOfficeUser/DeleteAssignedOfficeUser.test.jsx
  src/constants/MoveHistory/EventTemplates/UpdateMoveTaskOrderStatus/updateMoveTaskOrderStatus.jsx
  src/constants/MoveHistory/EventTemplates/UpdateMoveTaskOrderStatus/updateMoveTaskOrderStatus.test.jsx
  src/constants/MoveHistory/EventTemplates/UpdateServiceItemStatus/updateServiceItemStatusUpdateMove.jsx
  src/constants/MoveHistory/EventTemplates/UpdateServiceItemStatus/updateServiceItemStatusUpdateMove.test.jsx
  src/constants/MoveHistory/officeUserAssignment.js
  src/utils/formatters.js
  src/utils/formatters.test.js
Labels: MAIN, Go-Rillaz, database, frontend, backend

#15347 B22884-INT-rename pickup addr to current addr
  src/components/Office/DefinitionLists/CustomerInfoList.jsx
  src/components/Office/DefinitionLists/CustomerInfoList.test.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.test.jsx
Labels: ByteSize M&Ms, INTEGRATION

#15352 B 22663 nts inpk real pricing I-14152
  pkg/payment_request/service_param_value_lookups/shipment_type_price_lookup.go
  pkg/payment_request/service_param_value_lookups/shipment_type_price_lookup_test.go
  pkg/services/ghcrateengine/intl_hhg_pack_pricer_test.go
  pkg/services/ghcrateengine/intl_nts_pack_pricer.go
  pkg/services/ghcrateengine/intl_nts_pack_pricer_test.go
  pkg/services/payment_request/payment_request_creator_test.go
  pkg/testdatagen/testharness/make_move.go
Labels: Mountain Movers, INTEGRATION, backend

#15355 INT B-23089
  pkg/services/ppmshipment/ppm_shipment_creator.go
  pkg/services/ppmshipment/ppm_shipment_creator_test.go
  pkg/testdatagen/scenario/e2ebasic.go
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/scenario/subscenarios.go
  pkg/testdatagen/testharness/dispatch.go
  pkg/testdatagen/testharness/make_move.go
  playwright/tests/office/servicescounseling/servicesCounselingInternational.spec.js
  playwright/tests/utils/testharness.js
Labels: Mountain Movers, INTEGRATION

#15371 B22596 int kb1 add crud button for expenses
  src/pages/Office/PPM/Closeout/Expenses/Expenses.jsx
  src/pages/Office/PPM/Closeout/WeightTickets/WeightTickets.jsx
Labels: ByteSize M&Ms, INTEGRATION

#15105 MAIN - B-22565 - office user update phone number - BE
  pkg/gen/adminapi/adminoperations/office_users/update_office_user_responses.go
  pkg/gen/adminapi/embedded_spec.go
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/ghcapi/ghcoperations/office_users/update_office_user.go
  pkg/gen/ghcapi/ghcoperations/office_users/update_office_user_parameters.go
  pkg/gen/ghcapi/ghcoperations/office_users/update_office_user_responses.go
  pkg/gen/ghcapi/ghcoperations/office_users/update_office_user_urlbuilder.go
  pkg/gen/ghcmessages/office_user_update.go
  pkg/handlers/adminapi/office_users.go
  pkg/handlers/adminapi/office_users_test.go
  pkg/handlers/adminapi/payloads/payload_to_model.go
  pkg/handlers/adminapi/payloads/payload_to_model_test.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/internal/payloads/payload_to_model.go
  pkg/handlers/ghcapi/internal/payloads/payload_to_model_test.go
  pkg/handlers/ghcapi/office_users.go
  pkg/handlers/ghcapi/office_users_test.go
  pkg/services/mocks/OfficeUserUpdater.go
  pkg/services/office_user.go
  pkg/services/office_user/office_user_updater.go
  pkg/services/office_user/office_user_updater_test.go
  swagger-def/admin.yaml
  swagger-def/ghc.yaml
  swagger/admin.yaml
  swagger/ghc.yaml
Labels: ByteSize M&Ms, MAIN

#15363 INT B-23443
  pkg/handlers/primeapi/move_task_order.go
  pkg/handlers/primeapi/move_task_order_test.go
  pkg/paperwork/generator.go
  pkg/services/mocks/MoveLocker.go
  pkg/services/mocks/OfficeUserFetcherPop.go
  pkg/services/mocks/PaymentPacketCreator.go
  pkg/services/mocks/PrimeDownloadMoveUploadPDFGenerator.go
  pkg/services/paperwork.go
  pkg/services/paperwork/prime_download_user_upload_to_pdf_converter.go
  pkg/services/paperwork/prime_download_user_upload_to_pdf_converter_test.go
  pkg/services/ppmshipment.go
  pkg/services/ppmshipment/aoa_packet_creator.go
  pkg/services/ppmshipment/payment_packet_creator.go
  pkg/services/ppmshipment/payment_packet_creator_test.go
Labels: Mountain Movers, INTEGRATION

#15357 INT B-22894
  pkg/services/ghcrateengine/fuel_surcharge_pricer.go
  pkg/services/ghcrateengine/fuel_surcharge_pricer_test.go
  src/components/Office/PPM/PPMHeaderSummary/HeaderSection.jsx
  src/components/Office/PPM/PPMHeaderSummary/HeaderSection.test.jsx
Labels: Mountain Movers, INTEGRATION

#15359 INT B-22965
  src/components/Office/RequestAccountForm/RequestAccountForm.jsx
  src/components/Office/RequestAccountForm/RequestAccountForm.test.jsx
  src/components/form/OfficeAccountRequestFields/OfficeAccountRequestFields.jsx
  src/components/form/OfficeAccountRequestFields/OfficeAccountRequestFields.module.scss
  src/components/form/OfficeAccountRequestFields/OfficeAccountRequestFields.test.jsx
  src/utils/validation.js
Labels: Mountain Movers, INTEGRATION

#15374 B 22649 prime sim disable non ppm shipment submission invalid requested pickup date
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/handlers/internalapi/mto_shipment_test.go
  pkg/handlers/primeapiv2/mto_shipment_test.go
  pkg/handlers/primeapiv3/mto_shipment_test.go
  pkg/services/mto_shipment/mto_shipment_creator.go
  pkg/services/mto_shipment/mto_shipment_creator_test.go
  pkg/services/mto_shipment/rules.go
  pkg/services/mto_shipment/rules_test.go
Labels: MAIN, Go-Rillaz, backend

#15368 B-23279 INT: Handle PPM closeout pricing logic to ignore non-dollar values
  pkg/services/ppmshipment/ppm_shipment_review_documents.go
  pkg/services/ppmshipment/ppm_shipment_review_documents_test.go
Labels: Mountain Movers, INTEGRATION, backend

#15197 MAIN - B-22566 office user update phone number -FE
  pkg/handlers/adminapi/office_users.go
  pkg/handlers/ghcapi/office_users.go
  src/components/MilMoveHeader/MilMoveHeader.test.jsx
  src/components/MilMoveHeader/OfficeUserInfo.jsx
  src/components/MilMoveHeader/index.module.scss
  src/components/Office/Profile/ContactInfoDisplay.jsx
  src/components/Office/Profile/ContactInfoDisplay.module.scss
  src/components/Office/Profile/ContactInfoDisplay.stories.jsx
  src/components/Office/Profile/ContactInfoDisplay.test.jsx
  src/components/Office/Profile/ContactInfoForm/ContactInfoForm.jsx
  src/components/Office/Profile/ContactInfoForm/ContactInfoForm.stories.jsx
  src/components/Office/Profile/ContactInfoForm/ContactInfoForm.test.jsx
  src/constants/routes.js
  src/containers/Headers/OfficeLoggedInHeader.jsx
  src/pages/Office/Profile/ContactInfo.jsx
  src/pages/Office/Profile/ContactInfo.test.jsx
  src/pages/Office/Profile/Profile.jsx
  src/pages/Office/Profile/Profile.module.scss
  src/pages/Office/Profile/Profile.test.jsx
  src/pages/Office/index.jsx
  src/services/ghcApi.js
  src/styles/form.module.scss
  src/utils/formatters.js
  src/utils/formatters.test.js
Labels: ByteSize M&Ms, MAIN

#15385 INT B-23089 test fix
  pkg/services/ppmshipment/ppm_shipment_creator_test.go
Labels: Mountain Movers, INTEGRATION

#15380 B 23177 int: Customer Cancellation Email Should Not Send for Moves in Draft Status
  pkg/handlers/internalapi/office.go
Labels: INTEGRATION, backend

#15333 Int b 22978 api validation requested pickup non ppm
  .github/workflows/zap-scan.yml
  config/tls/milmove-cert-bundle.p7b
  migrations/app/dml_migrations_manifest.txt
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/handlers/primeapiv2/mto_shipment_test.go
  pkg/handlers/primeapiv3/mto_shipment_test.go
  pkg/services/mto_shipment/mto_shipment_creator_test.go
  pkg/services/mto_shipment/mto_shipment_updater.go
  pkg/services/mto_shipment/mto_shipment_updater_test.go
  pkg/services/mto_shipment/rules.go
  pkg/services/mto_shipment/rules_test.go
  pkg/services/mto_shipment/shipment_approver.go
  pkg/services/mto_shipment/shipment_approver_test.go
Labels: INTEGRATION, Go-Rillaz, backend

#15358 MAIN B-22965
  src/components/Office/RequestAccountForm/RequestAccountForm.jsx
  src/components/Office/RequestAccountForm/RequestAccountForm.test.jsx
  src/components/form/OfficeAccountRequestFields/OfficeAccountRequestFields.jsx
  src/components/form/OfficeAccountRequestFields/OfficeAccountRequestFields.module.scss
  src/components/form/OfficeAccountRequestFields/OfficeAccountRequestFields.test.jsx
  src/utils/validation.js
Labels: Mountain Movers, MAIN

#15339 B-22042-INT
  pkg/gen/adminapi/adminoperations/mymove_api.go
  pkg/gen/adminapi/adminoperations/users/delete_user.go
  pkg/gen/adminapi/adminoperations/users/delete_user_parameters.go
  pkg/gen/adminapi/adminoperations/users/delete_user_responses.go
  pkg/gen/adminapi/adminoperations/users/delete_user_urlbuilder.go
  pkg/gen/adminapi/configure_mymove.go
  pkg/gen/adminapi/embedded_spec.go
  pkg/handlers/adminapi/api.go
  pkg/handlers/adminapi/users.go
  pkg/handlers/adminapi/users_test.go
  pkg/services/mocks/UserDeleter.go
  pkg/services/user.go
  pkg/services/user/user_deleter.go
  pkg/services/user/user_deleter_test.go
  pkg/services/user/user_fetcher.go
  pkg/services/user/user_fetcher_test.go
  src/pages/Admin/Users/UserEdit.jsx
  src/pages/Admin/Users/UserEdit.module.scss
  src/services/adminApi.js
  swagger-def/admin.yaml
  swagger/admin.yaml
Labels: INTEGRATION, Go-Rillaz, frontend, backend

#15383 B 22469 int pt4 recovering change that was lost in INT
  playwright/tests/office/servicescounseling/servicesCounselingInternational.spec.js
Labels: Scrummy Bears, INTEGRATION

#15013 B 22665 tio inpk reviewing int
  pkg/services/payment_request/payment_request_creator.go
  pkg/services/payment_request/payment_request_creator_test.go
  pkg/testdatagen/testharness/dispatch.go
  pkg/testdatagen/testharness/make_move.go
  playwright/tests/office/txo/tioFlowsNTS.spec.js
  playwright/tests/office/txo/tioTestFixture.js
  playwright/tests/utils/testharness.js
  src/components/Office/ServiceItemCalculations/helpers.js
  src/components/Office/ServiceItemCalculations/helpers.test.js
  src/components/Office/ServiceItemCalculations/serviceItemTestParams.js
  src/constants/serviceItems.js
Labels: Mountain Movers, INTEGRATION, frontend, backend

#15392 B22884-INT-KB1-Rename pickup addr to current addr
  src/components/Office/CustomerContactInfoForm/CustomerContactInfoForm.jsx
  src/components/Office/CustomerContactInfoForm/CustomerContactInfoForm.test.jsx
  src/constants/MoveHistory/Database/FieldMappings.js
  src/constants/MoveHistory/EventTemplates/UpdateAddress/createAddress.test.jsx
  src/constants/MoveHistory/EventTemplates/UpdateAddress/updateAddress.test.jsx
Labels: ByteSize M&Ms, INTEGRATION

#15253 INT B-22468 International SITs UI display estimated price, actual pricing calculation breakdown
  migrations/app/ddl_functions_manifest.txt
  migrations/app/ddl_migrations/ddl_functions/20250423160104_fn_get_rate_area.up.sql
  migrations/app/dml_migrations_manifest.txt
  migrations/app/schema/20250409235021_B-22468_add_service_item_param_keys_and_service_params.up.sql
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/service_item_param_name.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/service_item_param_name.go
  pkg/gen/primev2api/embedded_spec.go
  pkg/gen/primev2messages/service_item_param_name.go
  pkg/gen/primev3api/embedded_spec.go
  pkg/gen/primev3messages/service_item_param_name.go
  pkg/handlers/primeapi/mto_service_item_test.go
  pkg/models/re_rate_area.go
  pkg/models/re_rate_area_test.go
  pkg/models/service_item_param_key.go
  pkg/notifications/failed_payment_request_notifier_test.go
  pkg/payment_request/service_param_value_lookups/per_unit_cents_lookup_test.go
  pkg/payment_request/service_param_value_lookups/rate_area_lookup.go
  pkg/payment_request/service_param_value_lookups/rate_area_lookup_test.go
  pkg/payment_request/service_param_value_lookups/service_param_value_lookups.go
  pkg/services/ghcrateengine/service_item_pricer.go
  pkg/services/mto_service_item/mto_service_item_creator.go
  pkg/services/payment_request/payment_request_shipments_sit_balance.go
  pkg/services/payment_request/payment_request_shipments_sit_balance_test.go
  scripts/db-truncate
  src/components/Office/ReviewServiceItems/ServiceItemCard.jsx
  src/components/Office/ServiceItemCalculations/ServiceItemCalculations.jsx
  src/components/Office/ServiceItemCalculations/helpers.js
  src/components/Office/ServiceItemCalculations/helpers.test.js
  src/components/Office/ServiceItemCalculations/serviceItemTestParams.js
  src/components/Office/ServiceItemDetails/ServiceItemDetails.jsx
  src/components/Office/ServiceItemDetails/ServiceItemDetails.test.jsx
  src/constants/serviceItems.js
  swagger-def/definitions/ServiceItemParamName.yaml
  swagger/ghc.yaml
  swagger/prime.yaml
  swagger/prime_v2.yaml
  swagger/prime_v3.yaml
  yarn.lock
Labels: Scrummy Bears, INTEGRATION

#15404 Main b 22772 titlecase tab names
  playwright/tests/office/gsr/gsrFlows.spec.js
  playwright/tests/office/qaecsr/csrFlows.spec.js
  playwright/tests/office/qaecsr/moveSearchFlows.spec.js
  playwright/tests/office/qaecsr/qaeFlows.spec.js
  playwright/tests/office/servicescounseling/servicesCounselingFlows.spec.js
  playwright/tests/office/txo/tooFlows.spec.js
  playwright/tests/utils/office/officeTest.js
  playwright/tests/utils/office/waitForOfficePage.js
  src/components/Office/ServicesCounselingTabNav/ServicesCounselingTabNav.jsx
  src/components/Office/TXOTabNav/TXOTabNav.jsx
  src/components/Office/TXOTabNav/TXOTabNav.module.scss
  src/components/TabNav/TabNav.stories.jsx
  src/components/Table/TableQueue.jsx
  src/pages/Office/CustomerSupportRemarks/CustomerSupportRemarks.jsx
  src/pages/Office/CustomerSupportRemarks/CustomerSupportRemarks.test.jsx
  src/pages/Office/EvaluationReports/EvaluationReports.jsx
  src/pages/Office/EvaluationReports/EvaluationReports.test.jsx
  src/pages/Office/MoveDetails/MoveDetails.jsx
  src/pages/Office/MoveDetails/MoveDetails.test.jsx
  src/pages/Office/MoveHistory/MoveHistory.jsx
  src/pages/Office/MoveHistory/MoveHistory.test.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
  src/pages/Office/MoveTaskOrder/MoveTaskOrder.test.jsx
  src/pages/Office/PPM/Closeout/Review/Review.test.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.test.jsx
  src/pages/Office/TXOMoveInfo/TXOMoveInfo.test.jsx
Labels: MAIN, frontend

#15343 Int b 22569 draft move lock
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/move_payload.go
  pkg/handlers/internalapi/moves.go
  pkg/handlers/internalapi/moves_test.go
  src/components/Customer/SubmitMoveForm/SubmitMoveForm.jsx
  src/components/Customer/SubmitMoveForm/SubmitMoveForm.test.jsx
  src/pages/MyMove/Agreement.jsx
  src/pages/MyMove/Agreement.test.jsx
  src/pages/MyMove/CreateOrEditMtoShipment.jsx
  src/pages/MyMove/EditOrders.jsx
  src/pages/MyMove/EditOrders.test.jsx
  src/pages/MyMove/Home/MoveHome.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesLandingPage.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesLandingPage.test.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesMoveContainer/MultiMovesMoveContainer.jsx
  src/pages/MyMove/Multi-Moves/MultiMovesMoveContainer/MultiMovesMoveContainer.test.jsx
  src/pages/MyMove/Review/Review.jsx
  src/shared/constants.js
  swagger-def/internal.yaml
  swagger/internal.yaml
Labels: ByteSize M&Ms, INTEGRATION

#15417 B-22549 INT Submit move form bugfix
  src/components/Customer/SubmitMoveForm/SubmitMoveForm.jsx
  src/components/Customer/SubmitMoveForm/SubmitMoveForm.test.jsx
Labels: G-Unit, INTEGRATION, frontend

#15412 B-22712-22759-INT 2 International shuttle/SIT display
  src/constants/approvalRequestTypes.js
Labels: G-Unit, INTEGRATION

#15436 B 23177 customer cancellation email should not send for moves in draft status
  pkg/handlers/internalapi/office.go
Labels: MAIN, Go-Rillaz, backend

#15396 INT-B-22043 delete users okta account
  pkg/factory/user_factory.go
  pkg/models/okta.go
  pkg/models/okta_test.go
  pkg/services/user/user_deleter.go
  pkg/services/user/user_deleter_test.go
Labels: INTEGRATION, Go-Rillaz, backend

#15441 hdt 6208 fix faulty err ref
  pkg/services/ppmshipment/payment_packet_creator.go
Labels: Mountain Movers, MAIN

#15391 INT B-23543
  migrations/app/ddl_functions_manifest.txt
  migrations/app/ddl_migrations/ddl_functions/20250505143424_fn_get_payment_request_queue.up.sql
  pkg/handlers/ghcapi/queues.go
  pkg/handlers/ghcapi/queues_test.go
  pkg/models/payment_request.go
  pkg/services/payment_request/payment_request_list_fetcher.go
  pkg/services/payment_request/payment_request_list_fetcher_test.go
Labels: Mountain Movers, INTEGRATION

#15421 B 22742 int
  migrations/app/ddl_functions_manifest.txt
  migrations/app/ddl_migrations/ddl_functions/20250221213413_fn_update_service_item_pricing.up.sql
  migrations/app/ddl_migrations/ddl_functions/20250313200647_fn_calculate_escalated_price.up.sql
  migrations/app/ddl_migrations/ddl_functions/20250512165319_fn_calculate_ppm_sit_cost.up.sql
  migrations/app/ddl_migrations/ddl_functions/20250512175124_fn_calculate_ppm_incentive.up.sql
  migrations/app/dml_migrations_manifest.txt
  migrations/app/schema/20250506192739_removing_duplicate_procedures_for_escalated_price.up.sql
  migrations/app/schema/20250509125410_add_external_crate_to_appliation_parameters.up.sql
Labels: Scrummy Bears, INTEGRATION

#15425 B 22732 - Customer PPM Forms Only Respond to First Button Click
  src/components/Customer/PPM/Booking/Advance/AdvanceForm.jsx
  src/components/Customer/PPM/Booking/DateAndLocationForm/DateAndLocationForm.jsx
  src/components/Customer/PPM/Booking/EstimatedWeightsProGearForm/EstimatedWeightsProGearForm.jsx
  src/components/LoadingButton/LoadingButton.jsx
  src/components/LoadingButton/LoadingButton.module.scss
  src/components/LoadingButton/LoadingButton.stories.jsx
  src/components/LoadingButton/LoadingButton.test.jsx
  src/components/Table/TableCSVExportButton.jsx
  src/components/Table/TableCSVExportButton.test.jsx
  src/pages/MyMove/PPM/Booking/Advance/Advance.jsx
  src/pages/MyMove/PPM/Booking/DateAndLocation/DateAndLocation.jsx
  src/pages/MyMove/PPM/Booking/EstimatedWeightsProGear/EstimatedWeightsProGear.jsx
Labels: Scrummy Bears, MAIN

#15439 Main b 22538
  .envrc
  migrations/app/ddl_migrations/ddl_tables/20250425124456_tbl_B-22538_alter_roles.up.sql
  migrations/app/ddl_migrations/ddl_tables/20250425124510_tbl_B-22538_alter_privileges.up.sql
  migrations/app/ddl_tables_manifest.txt
  migrations/app/dml_migrations_manifest.txt
  migrations/app/schema/20250425132117_B-22538_add_sort_data_to_roles_and_privileges.up.sql
  pkg/factory/office_user_factory_test.go
  pkg/factory/privilege_factory.go
  pkg/factory/shared.go
  pkg/factory/user_factory.go
  pkg/gen/adminapi/adminoperations/office_users/get_roles_privileges_responses.go
  pkg/gen/adminapi/embedded_spec.go
  pkg/gen/adminmessages/privilege.go
  pkg/gen/adminmessages/role.go
  pkg/gen/adminmessages/role_privilege.go
  pkg/handlers/adminapi/office_users.go
  pkg/handlers/adminapi/office_users_test.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload_test.go
  pkg/handlers/ghcapi/move.go
  pkg/handlers/ghcapi/queues.go
  pkg/handlers/ghcapi/queues_test.go
  pkg/handlers/internalapi/users.go
  pkg/models/role_privilege.go
  pkg/models/roles/privileges.go
  pkg/models/roles/privileges_test.go
  pkg/models/roles/role_privilege.go
  pkg/models/roles/roles.go
  pkg/models/user.go
  pkg/models/user_test.go
  pkg/services/mocks/RoleAssociater.go
  pkg/services/mocks/UserPrivilegeAssociator.go
  pkg/services/move/move_assignment_test.go
  pkg/services/move/move_searcher.go
  pkg/services/office_user/customer/customer_searcher_test.go
  pkg/services/order/order_fetcher.go
  pkg/services/payment_request/payment_request_list_fetcher.go
  pkg/services/roles.go
  pkg/services/roles/roles.go
  pkg/services/roles/roles_test.go
  pkg/services/users_privileges.go
  pkg/services/users_privileges/users_privileges.go
  pkg/services/users_privileges/users_privileges_test.go
  src/App/index.jsx
  src/constants/queryKeys.js
  src/hooks/queries.js
  src/pages/Admin/OfficeUsers/OfficeUserCreate.jsx
  src/pages/Admin/OfficeUsers/OfficeUserEdit.jsx
  src/scenes/SystemAdmin/shared/RolesPrivilegesCheckboxes.jsx
  src/services/adminApi.js
  swagger-def/admin.yaml
  swagger/admin.yaml
Labels: MAIN, Go-Rillaz, database, frontend, backend

#15297 INT-B22564_customer_email_reminders_for_safety_moves_removed
  pkg/notifications/move_payment_reminder.go
  pkg/notifications/move_payment_reminder_test.go
Labels: ByteSize M&Ms, INTEGRATION, backend

#15362 MAIN B-23443
  pkg/handlers/primeapi/move_task_order.go
  pkg/handlers/primeapi/move_task_order_test.go
  pkg/paperwork/generator.go
  pkg/services/mocks/MoveLocker.go
  pkg/services/mocks/OfficeUserFetcherPop.go
  pkg/services/mocks/PaymentPacketCreator.go
  pkg/services/mocks/PrimeDownloadMoveUploadPDFGenerator.go
  pkg/services/paperwork.go
  pkg/services/paperwork/prime_download_user_upload_to_pdf_converter.go
  pkg/services/paperwork/prime_download_user_upload_to_pdf_converter_test.go
  pkg/services/ppmshipment.go
  pkg/services/ppmshipment/aoa_packet_creator.go
  pkg/services/ppmshipment/payment_packet_creator.go
  pkg/services/ppmshipment/payment_packet_creator_test.go
Labels: Mountain Movers, MAIN

#15405 B23209-INT-remove ppm shipment from reweight
  pkg/handlers/ghcapi/mto_shipment.go
  pkg/models/mto_shipments.go
  pkg/services/move/move_weights.go
  src/components/Office/ShipmentWeightDetails/ShipmentWeightDetails.jsx
  src/components/Office/ShipmentWeightDetails/ShipmentWeightDetails.test.jsx
Labels: ByteSize M&Ms, INTEGRATION

#15397 B 23530 int
  pkg/services/ppmshipment/ppm_estimator.go
  pkg/services/ppmshipment/ppm_estimator_test.go
Labels: Scrummy Bears, INTEGRATION, backend

#15446 INT-B-22629 Fix for missing Closeout Office name in agreement text
  src/components/Shared/PPM/Closeout/FinalCloseoutForm/FinalCloseoutForm.jsx
  src/components/Shared/PPM/Closeout/FinalCloseoutForm/FinalCloseoutForm.test.jsx
  src/pages/MyMove/PPM/Closeout/FinalCloseout/FinalCloseout.jsx
  src/pages/MyMove/PPM/Closeout/FinalCloseout/FinalCloseout.test.jsx
  src/pages/Office/PPM/Closeout/FinalCloseout/FinalCloseout.jsx
  src/pages/Office/PPM/Closeout/FinalCloseout/FinalCloseout.test.jsx
Labels: ByteSize M&Ms, INTEGRATION

#15356 MAIN B-22894
  pkg/services/ghcrateengine/fuel_surcharge_pricer.go
  pkg/services/ghcrateengine/fuel_surcharge_pricer_test.go
  src/components/Office/PPM/PPMHeaderSummary/HeaderSection.jsx
  src/components/Office/PPM/PPMHeaderSummary/HeaderSection.test.jsx
Labels: Mountain Movers, MAIN

#15435 Int b 23451 customer document file extension prior to date timestamp
  pkg/handlers/internalapi/uploads.go
  pkg/utils/utility.go
  pkg/utils/utility_test.go
  src/pages/MyMove/AdditionalDocuments/AdditionalDocuments.jsx
  src/pages/MyMove/AmendOrders/AmendOrders.jsx
  src/pages/MyMove/EditOrders.jsx
  src/pages/MyMove/PPM/Closeout/Expenses/Expenses.jsx
  src/pages/MyMove/PPM/Closeout/ProGear/ProGear.jsx
  src/pages/MyMove/PPM/Closeout/WeightTickets/WeightTickets.jsx
  src/pages/MyMove/UploadOrders.jsx
  src/pages/MyMove/UploadOrders.test.jsx
  src/utils/fileUpload.js
  src/utils/fileUpload.test.js
Labels: INTEGRATION, Go-Rillaz, frontend, backend

#15450 Updating edit orders test
  src/pages/MyMove/EditOrders.test.jsx
Labels: MAIN

#15291 B 22760 main
  migrations/app/ddl_migrations/ddl_functions/20250225233157_fn_get_destination_queue.up.sql
  pkg/models/mto_service_items.go
  pkg/services/order/order_fetcher.go
Labels: G-Unit, MAIN

#15402 INT B-23566 Country Search API
  pkg/gen/ghcapi/configure_mymove.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcapi/ghcoperations/addresses/search_countries.go
  pkg/gen/ghcapi/ghcoperations/addresses/search_countries_parameters.go
  pkg/gen/ghcapi/ghcoperations/addresses/search_countries_responses.go
  pkg/gen/ghcapi/ghcoperations/addresses/search_countries_urlbuilder.go
  pkg/gen/ghcapi/ghcoperations/mymove_api.go
  pkg/gen/ghcmessages/countries.go
  pkg/gen/ghcmessages/country.go
  pkg/gen/internalapi/configure_mymove.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalapi/internaloperations/addresses/search_countries.go
  pkg/gen/internalapi/internaloperations/addresses/search_countries_parameters.go
  pkg/gen/internalapi/internaloperations/addresses/search_countries_responses.go
  pkg/gen/internalapi/internaloperations/addresses/search_countries_urlbuilder.go
  pkg/gen/internalapi/internaloperations/mymove_api.go
  pkg/gen/internalmessages/countries.go
  pkg/gen/internalmessages/country.go
  pkg/gen/primeapi/configure_mymove.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/addresses/search_countries.go
  pkg/gen/primeapi/primeoperations/addresses/search_countries_parameters.go
  pkg/gen/primeapi/primeoperations/addresses/search_countries_responses.go
  pkg/gen/primeapi/primeoperations/addresses/search_countries_urlbuilder.go
  pkg/gen/primeapi/primeoperations/mymove_api.go
  pkg/gen/primeclient/addresses/addresses_client.go
  pkg/gen/primeclient/addresses/search_countries_parameters.go
  pkg/gen/primeclient/addresses/search_countries_responses.go
  pkg/gen/primemessages/countries.go
  pkg/gen/primemessages/country.go
  pkg/handlers/ghcapi/addresses.go
  pkg/handlers/ghcapi/addresses_test.go
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload_test.go
  pkg/handlers/internalapi/addresses.go
  pkg/handlers/internalapi/addresses_test.go
  pkg/handlers/internalapi/api.go
  pkg/handlers/internalapi/internal/payloads/model_to_payload.go
  pkg/handlers/internalapi/internal/payloads/model_to_payload_test.go
  pkg/handlers/primeapi/addresses.go
  pkg/handlers/primeapi/addresses_test.go
  pkg/handlers/primeapi/api.go
  pkg/handlers/primeapi/payloads/model_to_payload.go
  pkg/handlers/primeapi/payloads/model_to_payload_test.go
  pkg/models/country.go
  pkg/services/address.go
  pkg/services/address/country_searcher.go
  pkg/services/address/country_searcher_test.go
  pkg/services/mocks/CountrySearcher.go
  swagger-def/definitions/Country.yaml
  swagger-def/ghc.yaml
  swagger-def/internal.yaml
  swagger-def/prime.yaml
  swagger/ghc.yaml
  swagger/internal.yaml
  swagger/prime.yaml
Labels: Scrummy Bears, INTEGRATION, backend

#15471 B-22662 Flaky Test Fix
  pkg/services/mto_shipment/mto_shipment_updater_test.go
  pkg/services/mto_shipment/shipment_approver_test.go
Labels: Mountain Movers, INTEGRATION, backend

#15478 INT failing test fix
  pkg/payment_request/service_param_value_lookups/per_unit_cents_lookup_test.go
  yarn.lock
Labels: Mountain Movers, INTEGRATION

#15479 B 23530 int part 2
  pkg/services/ppmshipment/ppm_estimator.go
Labels: Scrummy Bears, INTEGRATION, backend

#15477 MAIN failing test fix
  pkg/payment_request/service_param_value_lookups/per_unit_cents_lookup_test.go
Labels: Mountain Movers, MAIN

#15418 B-23444 Enable saving of PDF rotation
  package.json
  src/components/DocumentViewer/Content/Content.jsx
  src/components/DocumentViewer/Content/Content.test.jsx
  src/components/DocumentViewer/DocumentViewer.jsx
  src/components/DocumentViewer/DocumentViewer.test.jsx
  src/shared/utils.js
  yarn.lock
Labels: Mountain Movers, INTEGRATION

#15365 B-23279-MAIN
  pkg/services/ppmshipment/ppm_shipment_review_documents.go
  pkg/services/ppmshipment/ppm_shipment_review_documents_test.go
Labels: Mountain Movers, MAIN

#15283 B 22737 INT Updated Service Param
  migrations/app/dml_migrations_manifest.txt
  migrations/app/schema/20250415183418_B_22737_update_available_to_prime_service_param.up.sql
  pkg/factory/mto_service_item_factory.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/service_item_param_name.go
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primemessages/service_item_param_name.go
  pkg/gen/primev2api/embedded_spec.go
  pkg/gen/primev2messages/service_item_param_name.go
  pkg/gen/primev3api/embedded_spec.go
  pkg/gen/primev3messages/service_item_param_name.go
  pkg/handlers/primeapi/move_task_order_test.go
  pkg/handlers/primeapi/payment_request_test.go
  pkg/handlers/primeapiv2/move_task_order_test.go
  pkg/handlers/primeapiv3/move_task_order_test.go
  pkg/models/service_item_param_key.go
  pkg/payment_request/service_param_value_lookups/mto_available_to_prime_at_lookup.go
  pkg/payment_request/service_param_value_lookups/mto_available_to_prime_at_lookup_test.go
  pkg/payment_request/service_param_value_lookups/mto_earliest_requested_pickup_lookup.go
  pkg/payment_request/service_param_value_lookups/mto_earliest_requested_pickup_lookup_test.go
  pkg/payment_request/service_param_value_lookups/service_param_value_lookups.go
  pkg/payment_request/service_param_value_lookups/service_params_cache_test.go
  pkg/services/ghcrateengine/param_convert_test.go
  pkg/services/payment_request/payment_request_recalculator_test.go
  swagger-def/definitions/ServiceItemParamName.yaml
  swagger/ghc.yaml
  swagger/prime.yaml
  swagger/prime_v2.yaml
  swagger/prime_v3.yaml
Labels: G-Unit, INTEGRATION, database, backend

#15360 B-22712-22759 Add approval request types to TOO columns
  migrations/app/ddl_migrations/ddl_functions/20250225233157_fn_get_destination_queue.up.sql
  src/constants/approvalRequestTypes.js
  src/constants/serviceItems.js
  src/pages/Office/MoveQueue/MoveQueue.jsx
  src/pages/Office/MoveQueue/MoveQueue.test.jsx
  src/utils/queues.jsx
  src/utils/queues.test.jsx
Labels: G-Unit, MAIN

#15348 B22884-MAIN-Rename_pickup_addr_to_current_addr
  src/components/Office/CustomerContactInfoForm/CustomerContactInfoForm.jsx
  src/components/Office/CustomerContactInfoForm/CustomerContactInfoForm.test.jsx
  src/components/Office/DefinitionLists/CustomerInfoList.jsx
  src/components/Office/DefinitionLists/CustomerInfoList.test.jsx
  src/constants/MoveHistory/Database/FieldMappings.js
  src/constants/MoveHistory/EventTemplates/UpdateAddress/createAddress.test.jsx
  src/constants/MoveHistory/EventTemplates/UpdateAddress/updateAddress.test.jsx
  src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.test.jsx
Labels: ByteSize M&Ms, MAIN

#15226 B 22696 main - Dest Req Queue bulk assignment save & H&AL
  migrations/app/ddl_migrations/ddl_functions/20250325161603_fn_fetch_move_history.up.sql
  migrations/app/ddl_migrations/ddl_functions/20250328183455_fn_fetch_moves_for_bulk_assignment_destination.up.sql
  pkg/services/move/move_assignment.go
  pkg/services/move/move_assignment_test.go
  pkg/services/move_history/move_history_fetcher_test.go
  src/constants/MoveHistory/Database/FieldMappings.js
  src/constants/MoveHistory/EventTemplates/SaveBulkAssignmentData/SaveBulkAssignmentData.jsx
  src/constants/MoveHistory/EventTemplates/SaveBulkAssignmentData/SaveBulkAssignmentData.test.jsx
  src/constants/MoveHistory/EventTemplates/UpdateAssignedOfficeUser/DeleteAssignedOfficeUser.jsx
  src/constants/MoveHistory/EventTemplates/UpdateAssignedOfficeUser/DeleteAssignedOfficeUser.test.jsx
  src/constants/MoveHistory/EventTemplates/UpdateAssignedOfficeUser/UpdateAssignedOfficeUser.jsx
  src/constants/MoveHistory/EventTemplates/UpdateAssignedOfficeUser/UpdateAssignedOfficeUser.test.jsx
  src/utils/formatters.test.js
Labels: G-Unit, MAIN, backend

#15351 MAIN B-23089
  pkg/services/ppmshipment/ppm_shipment_creator.go
  pkg/services/ppmshipment/ppm_shipment_creator_test.go
  pkg/testdatagen/scenario/e2ebasic.go
  pkg/testdatagen/scenario/shared.go
  pkg/testdatagen/scenario/subscenarios.go
  pkg/testdatagen/testharness/dispatch.go
  pkg/testdatagen/testharness/make_move.go
  playwright/tests/office/servicescounseling/servicesCounselingInternational.spec.js
  playwright/tests/utils/testharness.js
Labels: Mountain Movers, MAIN

#15432 Int b 22980 send reweigh email for existing shipments
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/mto_service_items_test.go
  pkg/handlers/ghcapi/mto_shipment.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/handlers/internalapi/api.go
  pkg/handlers/internalapi/mto_shipment_test.go
  pkg/handlers/primeapi/api.go
  pkg/handlers/primeapi/mto_shipment_test.go
  pkg/handlers/primeapiv2/api.go
  pkg/handlers/primeapiv2/mto_shipment_test.go
  pkg/handlers/primeapiv3/api.go
  pkg/handlers/primeapiv3/mto_shipment.go
  pkg/handlers/primeapiv3/mto_shipment_test.go
  pkg/services/move/move_weights.go
  pkg/services/move/move_weights_test.go
  pkg/services/mto_shipment/mto_shipment_updater_test.go
  pkg/services/mto_shipment/shipment_approver_test.go
  pkg/services/mto_shipment/shipment_reweigh_requester.go
  pkg/services/mto_shipment/shipment_reweigh_requester_test.go
  pkg/services/orchestrators/shipment/shipment_creator_test.go
Labels: ByteSize M&Ms, INTEGRATION

#15395 B23209-MAIN-Remove_ppm_shipment_from_reweight
  pkg/handlers/ghcapi/mto_shipment.go
  pkg/models/mto_shipments.go
  pkg/services/move/move_weights.go
  src/components/Office/ShipmentWeightDetails/ShipmentWeightDetails.jsx
  src/components/Office/ShipmentWeightDetails/ShipmentWeightDetails.test.jsx
Labels: ByteSize M&Ms, MAIN

#15475 B-22042
  pkg/gen/adminapi/adminoperations/mymove_api.go
  pkg/gen/adminapi/adminoperations/users/delete_user.go
  pkg/gen/adminapi/adminoperations/users/delete_user_parameters.go
  pkg/gen/adminapi/adminoperations/users/delete_user_responses.go
  pkg/gen/adminapi/adminoperations/users/delete_user_urlbuilder.go
  pkg/gen/adminapi/configure_mymove.go
  pkg/gen/adminapi/embedded_spec.go
  pkg/handlers/adminapi/api.go
  pkg/handlers/adminapi/users.go
  pkg/handlers/adminapi/users_test.go
  pkg/services/mocks/UserDeleter.go
  pkg/services/user.go
  pkg/services/user/user_deleter.go
  pkg/services/user/user_deleter_test.go
  pkg/services/user/user_fetcher.go
  pkg/services/user/user_fetcher_test.go
  src/pages/Admin/Users/UserEdit.jsx
  src/pages/Admin/Users/UserEdit.module.scss
  src/services/adminApi.js
  swagger-def/admin.yaml
  swagger/admin.yaml
Labels: MAIN, Go-Rillaz, frontend, backend

#15473 Int b 23575 country holiday weekend data
  .circleci/config.yml
  migrations/app/ddl_migrations/ddl_functions/20250325161603_fn_fetch_move_history.up.sql
  migrations/app/ddl_migrations/ddl_tables/20250513171013_tbl_country_holidays.up.sql
  migrations/app/ddl_migrations/ddl_tables/20250513172017_tbl_country_weekends.up.sql
  migrations/app/ddl_tables_manifest.txt
  migrations/app/dml_migrations_manifest.txt
  migrations/app/schema/20250513195206_B-23575_add_data_to_country_holidays_and_country_weekends.up.sql
  pkg/models/country_holiday.go
  pkg/models/country_holiday_test.go
  pkg/models/country_weekend.go
  pkg/models/country_weekend_test.go
  pkg/services/mto_shipment/shipment_approver_test.go
  scripts/db-truncate
Labels: INTEGRATION, Go-Rillaz, database, backend

#15457 INT B-23540
  migrations/app/ddl_functions_manifest.txt
  migrations/app/ddl_migrations/ddl_functions/20250509183824_fn_get_origin_queue.up.sql
  migrations/app/ddl_migrations/ddl_views/20250515143927_vw_move_to_gbloc.up.sql
  migrations/app/ddl_migrations/ddl_views/20250515145229_vw_move_to_dest_gbloc.up.sql
  migrations/app/ddl_views_manifest.txt
  pkg/gen/ghcapi/embedded_spec.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/queues.go
  pkg/handlers/ghcapi/queues_test.go
  pkg/models/mto_service_items.go
  pkg/services/mocks/OrderFetcher.go
  pkg/services/order.go
  pkg/services/order/order_fetcher.go
  pkg/services/order/order_fetcher_test.go
  src/pages/Office/HeadquartersQueues/HeadquartersQueues.test.jsx
  src/pages/Office/MoveQueue/MoveQueue.jsx
  src/pages/Office/MoveQueue/MoveQueue.test.jsx
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: Mountain Movers, INTEGRATION

#15379 B 22556 Recalculate SIT DDD/FSC Service items
  pkg/services/shipment_address_update/shipment_address_update_requester.go
  pkg/services/shipment_address_update/shipment_address_update_requester_test.go
Labels: G-Unit, INTEGRATION, backend

#15484 Int b 23043
  playwright/tests/my/milmove/ppms/about.spec.js
  playwright/tests/my/milmove/ppms/customerPpmTestFixture.js
  src/components/Shared/PPM/Closeout/AboutForm/AboutForm.jsx
  src/components/Shared/PPM/Closeout/AboutForm/AboutForm.test.jsx
  src/pages/MyMove/PPM/Closeout/About/About.test.jsx
  src/utils/ppmCloseout.jsx
Labels: INTEGRATION, Go-Rillaz, frontend

#15491 Revert B-22712-22759-INT
  migrations/app/ddl_migrations/ddl_functions/20250225233157_fn_get_destination_queue.up.sql
  src/constants/approvalRequestTypes.js
  src/constants/serviceItems.js
  src/pages/Office/MoveQueue/MoveQueue.jsx
  src/pages/Office/MoveQueue/MoveQueue.test.jsx
  src/utils/queues.jsx
  src/utils/queues.test.jsx
Labels: G-Unit, INTEGRATION

#15493 Revert "B-22712-22759 Add approval request types to TOO columns"
  migrations/app/ddl_migrations/ddl_functions/20250225233157_fn_get_destination_queue.up.sql
  src/constants/approvalRequestTypes.js
  src/constants/serviceItems.js
  src/pages/Office/MoveQueue/MoveQueue.jsx
  src/pages/Office/MoveQueue/MoveQueue.test.jsx
  src/utils/queues.jsx
  src/utils/queues.test.jsx
Labels: G-Unit, MAIN

#15465 B 22923 int
  migrations/app/ddl_functions_manifest.txt
  migrations/app/ddl_migrations/ddl_functions/20250514141532_fn_create_accessorial_service_items_for_shipment.up.sql
Labels: Scrummy Bears, INTEGRATION, database

#15490 INT B-23447
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/p_p_m_advance_status.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/p_p_m_advance_status.go
  pkg/models/ppm_shipment.go
  pkg/services/ppmshipment/ppm_shipment_updater.go
  pkg/services/ppmshipment/ppm_shipment_updater_test.go
  swagger-def/definitions/PPMAdvanceStatus.yaml
  swagger/ghc.yaml
  swagger/internal.yaml
Labels: Mountain Movers, INTEGRATION

#15429 Int b 22878 modal buttons
  src/components/BulkAssignment/BulkAssignmentModal.jsx
  src/components/BulkAssignment/BulkAssignmentModal.module.scss
  src/components/ConfirmationModals/CancelMoveConfirmationModal.jsx
  src/components/ConfirmationModals/DeleteDocumentFileConfirmationModal.jsx
  src/components/ConfirmationModals/DeleteEvaluationReportConfirmationModal.jsx
  src/components/MigratedModal/MigratedModal.jsx
  src/components/Office/ConvertSITToCustomerExpenseModal/ConvertSITToCustomerExpenseModal.jsx
  src/components/Office/EditSitEntryDateModal/EditSitEntryDateModal.jsx
  src/components/Office/FinancialReviewModal/FinancialReviewModal.jsx
  src/components/Office/PPM/PPMHeaderSummary/EditPPMHeaderSummaryModal.jsx
  src/components/Office/RejectServiceItemModal/RejectServiceItemModal.module.scss
  src/components/Office/RequestReweighModal/RequestReweighModal.jsx
  src/components/Office/RequestShipmentCancellationModal/RequestShipmentCancellationModal.jsx
  src/components/Office/ReviewSITExtensionModal/ConfirmCustomerExpenseModal/ConfirmCustomerExpenseModal.jsx
  src/components/Office/ReviewSITExtensionModal/ReviewSITExtensionModal.jsx
  src/components/Office/ShipmentApprovalPreview/ShipmentApprovalPreview.jsx
  src/components/Office/ShipmentApprovalPreview/shipmentApprovalPreview.module.scss
  src/components/Office/SubmitMoveConfirmationModal/SubmitMoveConfirmationModal.jsx
  src/components/Office/SubmitSITExtensionModal/SubmitSITExtensionModal.jsx
  src/components/Office/TerminateShipmentModal/TerminateShipmentModal.jsx
Labels: INTEGRATION, frontend

#15505 INT B-23540 I-14209
  migrations/app/ddl_migrations/ddl_functions/20250509183824_fn_get_origin_queue.up.sql
  pkg/services/order/order_fetcher_test.go
Labels: Mountain Movers, INTEGRATION

#15466 B 22910 i 14172 read only terminated shipments int
  pkg/services/mto_shipment/rules.go
  pkg/services/mto_shipment/rules_test.go
  pkg/services/orchestrators/shipment/rules.go
  pkg/services/orchestrators/shipment/rules_test.go
Labels: Mountain Movers, INTEGRATION, backend

#15442 Int b 22704 Update Add/Edit/Delete Pro-Gear Section to Calculate Actual Pro-Gear Weight Correctly - Service Counselor
  migrations/app/ddl_functions_manifest.txt
  migrations/app/ddl_migrations/ddl_functions/20250513192427_fn_update_actual_progear_weight_totals.up.sql
  pkg/factory/progear_weight_ticket_factory.go
  pkg/services/progear_weight_ticket/progear_weight_ticket_deleter.go
  pkg/services/progear_weight_ticket/progear_weight_ticket_deleter_test.go
  pkg/services/progear_weight_ticket/progear_weight_ticket_updater.go
  pkg/services/progear_weight_ticket/progear_weight_ticket_updater_test.go
  pkg/testdatagen/testharness/dispatch.go
  pkg/testdatagen/testharness/make_move.go
  playwright/tests/office/servicescounseling/servicesCounselingProGearTickets.spec.js
  playwright/tests/utils/testharness.js
  src/pages/Office/PPM/Closeout/ProGear/ProGear.jsx
Labels: INTEGRATION, Go-Rillaz, database, frontend, backend

#15512 Int b 23201 update retiree sep order type destination location label
  src/components/Customer/EditOrdersForm/EditOrdersForm.jsx
  src/components/Customer/EditOrdersForm/EditOrdersForm.test.jsx
  src/components/Customer/OrdersInfoForm/OrdersInfoForm.jsx
  src/components/Customer/OrdersInfoForm/OrdersInfoForm.test.jsx
Labels: INTEGRATION, Go-Rillaz, frontend

#15518 INT B-23540 I-14213
  migrations/app/ddl_migrations/ddl_functions/20250509183824_fn_get_origin_queue.up.sql
  pkg/services/order/order_fetcher_test.go
  src/pages/Office/MoveQueue/MoveQueue.jsx
  src/pages/Office/MoveQueue/MoveQueue.test.jsx
Labels: Mountain Movers, INTEGRATION

#15529 INT B-23545 I-14214
  src/constants/queues.js
  src/pages/Office/MoveQueue/MoveQueue.jsx
  src/pages/Office/MoveQueue/MoveQueue.test.jsx
Labels: Mountain Movers, INTEGRATION

#15515 INT B-23627
  src/components/Table/TableCSVExportButton.jsx
  src/components/Table/TableCSVExportButton.test.jsx
Labels: Mountain Movers, INTEGRATION

#15413 B-23444 MAIN: Enable saving of PDF rotation
  package.json
  src/components/DocumentViewer/Content/Content.jsx
  src/components/DocumentViewer/Content/Content.test.jsx
  src/components/DocumentViewer/DocumentViewer.jsx
  src/components/DocumentViewer/DocumentViewer.test.jsx
  src/shared/utils.js
  yarn.lock
Labels: Mountain Movers, MAIN

#15452 Int b 23252 Update Add/Edit/Delete Pro-Gear Section to Calculate Actual Pro-Gear Weight Correctly - Service Member
  src/pages/MyMove/PPM/Closeout/ProGear/ProGear.jsx
Labels: INTEGRATION, Go-Rillaz, database, frontend, backend

#15531 B 22742 int
  migrations/app/ddl_migrations/ddl_functions/20250221213413_fn_update_service_item_pricing.up.sql
Labels: Scrummy Bears, INTEGRATION

#15497 B-23280 INT: Update document viewing zoom scale
  package.json
  src/components/DocumentViewer/Content/Content.jsx
  src/components/DocumentViewer/Content/Content.module.scss
  src/components/DocumentViewer/Content/Content.test.jsx
  yarn.lock
Labels: Mountain Movers, INTEGRATION

#15381 B 23586 INT - Backfill ppm_closeouts
  migrations/app/ddl_functions_manifest.txt
  migrations/app/ddl_migrations/ddl_functions/20250502144039_fn_calculate_ppm_closeouts.up.sql
  migrations/app/dml_migrations_manifest.txt
  migrations/app/schema/20250502143331_B-23586_backfill_ppm_closeouts_table.up.sql
Labels: Scrummy Bears, INTEGRATION, database

#15540 INT V2 B-22466 Intl SIT Pickup Delivery - Add mileage multiplier for 50 miles
  migrations/app/ddl_migrations/ddl_functions/20250221213413_fn_update_service_item_pricing.up.sql
  migrations/app/dml_migrations_manifest.txt
  migrations/app/schema/20250328155348_B-22466_update_data_re_intl_other_prices_and_service_params.up.sql
  migrations/app/schema/20250522135232_B-22466_v2_add_distance_lookup_service_params.up.sql
  pkg/payment_request/service_param_value_lookups/per_unit_cents_lookup_test.go
  pkg/services/ghc_rate_engine.go
  pkg/services/ghcrateengine/intl_destination_delivery_sit_pricer.go
  pkg/services/ghcrateengine/intl_destination_delivery_sit_pricer_test.go
  pkg/services/ghcrateengine/intl_origin_pickup_sit_pricer.go
  pkg/services/ghcrateengine/intl_origin_pickup_sit_pricer_test.go
  pkg/services/ghcrateengine/pricer_helpers_intl.go
  pkg/services/ghcrateengine/pricer_helpers_intl_test.go
  pkg/services/mocks/InternationalDestinationSITDeliveryPricer.go
  pkg/services/mocks/InternationalOriginSITPickupPricer.go
Labels: Scrummy Bears, INTEGRATION, database, backend

#15541 Main b 22795 qae report deletion retrieval error fix
  src/pages/Office/EvaluationReports/EvaluationReports.jsx
  src/pages/Office/EvaluationReports/EvaluationReports.test.jsx
Labels: MAIN, Go-Rillaz

#15539 B 23132 int
  pkg/assets/paperwork/formtemplates/ShipmentSummaryWorksheet.pdf
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet.go
Labels: Scrummy Bears, INTEGRATION, backend

#15557 B 23651 allow prime delivery update kickback
  pkg/services/shipment_address_update/shipment_address_update_requester.go
  pkg/services/shipment_address_update/shipment_address_update_requester_test.go
Labels: ByteSize M&Ms, INTEGRATION

#15426 Int b 23511 file extension updates office
  pkg/handlers/ghcapi/evaluation_report.go
  pkg/handlers/ghcapi/evaluation_report_test.go
  pkg/handlers/ghcapi/payment_request.go
  pkg/handlers/ghcapi/payment_request_test.go
  pkg/handlers/ghcapi/ppm_document.go
  pkg/handlers/ghcapi/ppm_document_test.go
  pkg/handlers/internalapi/ppm_shipment.go
  pkg/handlers/internalapi/ppm_shipment_test.go
  pkg/handlers/primeapi/move_task_order.go
  pkg/handlers/primeapi/move_task_order_test.go
  pkg/services/move/excess_weight_uploader_test.go
  pkg/services/mto_service_item/service_request_document_upload.go
  pkg/services/mto_service_item/service_request_document_upload_test.go
  pkg/services/payment_request/upload_creator.go
  pkg/services/upload/upload_creator.go
  pkg/services/upload/upload_creator_test.go
  playwright/tests/office/servicescounseling/servicesCounselingBoat.spec.js
  playwright/tests/office/servicescounseling/servicesCounselingFlows.spec.js
  playwright/tests/office/servicescounseling/servicesCounselingInternational.spec.js
  playwright/tests/office/servicescounseling/servicesCounselingMobileHome.spec.js
  playwright/tests/office/servicescounseling/servicesCounselingTestFixture.js
  playwright/tests/office/txo/tooFlowsBoat.spec.js
  playwright/tests/office/txo/tooFlowsMobileHome.spec.js
  playwright/tests/office/txo/tooFlowsNTS.spec.js
  playwright/tests/office/txo/tooFlowsNTSR.spec.js
  playwright/tests/utils/playwrightUtility.js
  src/components/DocumentViewerFileManager/DocumentViewerFileManager.jsx
  src/components/DocumentViewerFileManager/DocumentViewerFileManager.test.jsx
  src/pages/Office/PPM/Closeout/Expenses/Expenses.jsx
  src/pages/Office/PPM/Closeout/ProGear/ProGear.jsx
  src/pages/Office/PPM/Closeout/WeightTickets/WeightTickets.jsx
Labels: INTEGRATION, Go-Rillaz, frontend, backend

#15559 Main b 23451 customer document file extension prior to date timestamp
  pkg/handlers/internalapi/uploads.go
  pkg/utils/utility.go
  pkg/utils/utility_test.go
  src/pages/MyMove/AdditionalDocuments/AdditionalDocuments.jsx
  src/pages/MyMove/AmendOrders/AmendOrders.jsx
  src/pages/MyMove/EditOrders.jsx
  src/pages/MyMove/PPM/Closeout/Expenses/Expenses.jsx
  src/pages/MyMove/PPM/Closeout/ProGear/ProGear.jsx
  src/pages/MyMove/PPM/Closeout/WeightTickets/WeightTickets.jsx
  src/pages/MyMove/UploadOrders.jsx
  src/pages/MyMove/UploadOrders.test.jsx
  src/utils/fileUpload.js
  src/utils/fileUpload.test.js
Labels: MAIN, Go-Rillaz, frontend, backend

#15455 MAIN B-23540 & B-23545
  .envrc
  migrations/app/ddl_functions_manifest.txt
  migrations/app/ddl_migrations/ddl_functions/20250225233157_fn_get_destination_queue.up.sql
  migrations/app/ddl_migrations/ddl_functions/20250505143424_fn_get_payment_request_queue.up.sql
  migrations/app/ddl_migrations/ddl_functions/20250509183824_fn_get_origin_queue.up.sql
  migrations/app/ddl_migrations/ddl_views/20250515143927_vw_move_to_gbloc.up.sql
  migrations/app/ddl_migrations/ddl_views/20250515145229_vw_move_to_dest_gbloc.up.sql
  migrations/app/ddl_views_manifest.txt
  pkg/factory/mto_shipment_factory.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/queue_move.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload_test.go
  pkg/handlers/ghcapi/queues.go
  pkg/handlers/ghcapi/queues_test.go
  pkg/models/mto_service_items.go
  pkg/models/order.go
  pkg/services/mocks/OrderFetcher.go
  pkg/services/order.go
  pkg/services/order/order_fetcher.go
  pkg/services/order/order_fetcher_test.go
  pkg/services/payment_request/payment_request_list_fetcher_test.go
  src/pages/Office/HeadquartersQueues/HeadquartersQueues.test.jsx
  src/pages/Office/MoveQueue/MoveQueue.jsx
  src/pages/Office/MoveQueue/MoveQueue.test.jsx
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: Mountain Movers, MAIN

#15504 change to invalid check need tests and rename var
  pkg/handlers/primeapi/mto_shipment.go
  pkg/handlers/primeapi/mto_shipment_test.go
  pkg/models/mto_shipments.go
  pkg/models/mto_shipments_test.go
  pkg/services/shipment_address_update/shipment_address_update_requester.go
  pkg/services/shipment_address_update/shipment_address_update_requester_test.go
  src/constants/shipments.js
Labels: ByteSize M&Ms, MAIN

#15456 MAIN B-23342 - Story 1 - Enter gun safe information - customer
  .envrc
  config/env/demo.app-client-tls.env
  config/env/demo.app.env
  config/env/exp.app-client-tls.env
  config/env/exp.app.env
  config/env/loadtest.app-client-tls.env
  config/env/loadtest.app.env
  config/env/prd.app-client-tls.env
  config/env/prd.app.env
  config/env/stg.app-client-tls.env
  config/flipt/storage/development.features.yaml
  migrations/app/ddl_migrations/ddl_tables/20250221195354_tbl_alter_entitlements_B-22651.up.sql
  migrations/app/ddl_migrations/ddl_tables/20250224200700_tbl_ppm_shipments.up.sql
  migrations/app/ddl_migrations/ddl_tables/20250501152235_tbl_gunsafe_weight_tickets.up.sql
  migrations/app/ddl_tables_manifest.txt
  migrations/app/dml_migrations_manifest.txt
  migrations/app/schema/20250501151831_B-23342_insert_application_parameters.up.sql
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/p_p_m_shipment.go
  pkg/gen/internalapi/embedded_spec.go
  pkg/gen/internalmessages/p_p_m_shipment.go
  pkg/gen/internalmessages/update_p_p_m_shipment.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/internalapi/internal/payloads/model_to_payload.go
  pkg/handlers/internalapi/internal/payloads/model_to_payload_test.go
  pkg/handlers/internalapi/internal/payloads/payload_to_model.go
  pkg/handlers/internalapi/internal/payloads/payload_to_model_test.go
  pkg/handlers/internalapi/mto_shipment.go
  pkg/handlers/internalapi/mto_shipment_test.go
  pkg/handlers/internalapi/orders.go
  pkg/models/ghc_entitlements.go
  pkg/models/ghc_entitlements_test.go
  pkg/models/move.go
  pkg/models/ppm_shipment.go
  pkg/models/ppm_shipment_test.go
  pkg/models/validators.go
  pkg/models/validators_test.go
  pkg/services/move/move_weights.go
  pkg/services/ppmshipment/ppm_shipment_updater.go
  pkg/services/ppmshipment/ppm_shipment_updater_test.go
  pkg/services/ppmshipment/validation.go
  src/components/Customer/PPM/Booking/EstimatedWeightsProGearForm/EstimatedWeightsProGearForm.jsx
  src/components/Customer/PPM/Booking/EstimatedWeightsProGearForm/EstimatedWeightsProGearForm.test.jsx
  src/components/Customer/Review/ShipmentCard/PPMShipmentCard/PPMShipmentCard.jsx
  src/components/Customer/Review/ShipmentCard/PPMShipmentCard/PPMShipmentCard.test.jsx
  src/pages/MyMove/PPM/Booking/EstimatedWeightsProGear/EstimatedWeightsProGear.jsx
  src/pages/MyMove/PPM/Booking/EstimatedWeightsProGear/EstimatedWeightsProGear.test.jsx
  src/shared/constants.js
  swagger-def/definitions/PPMShipment.yaml
  swagger-def/internal.yaml
  swagger/ghc.yaml
  swagger/internal.yaml
Labels: ByteSize M&Ms, MAIN

#15544 B-22712-22759-INT Update get_origin_queue sp
  .envrc
  config/env/demo.app-client-tls.env
  config/env/demo.app.env
  config/env/exp.app-client-tls.env
  config/env/exp.app.env
  config/env/loadtest.app-client-tls.env
  config/env/loadtest.app.env
  config/env/prd.app-client-tls.env
  config/env/prd.app.env
  config/env/stg.app-client-tls.env
  config/env/stg.app.env
  config/flipt/storage/development.features.yaml
  migrations/app/ddl_migrations/ddl_functions/20250225233157_fn_get_destination_queue.up.sql
  migrations/app/ddl_migrations/ddl_functions/20250509183824_fn_get_origin_queue.up.sql
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload_test.go
  pkg/models/move.go
  src/constants/approvalRequestTypes.js
  src/constants/serviceItems.js
  src/pages/Office/HeadquartersQueues/HeadquartersQueues.jsx
  src/pages/Office/MoveQueue/MoveQueue.jsx
  src/pages/Office/MoveQueue/MoveQueue.test.jsx
  src/pages/Office/index.jsx
  src/shared/constants.js
  src/utils/queues.jsx
  src/utils/queues.test.jsx
Labels: G-Unit, INTEGRATION, database
