Repository transcom/mymove, pull requests merged in 2025-06, with the labels that each got.

#15494 MAIN B-23446
  pkg/models/order.go
  pkg/models/order_test.go
  src/components/Office/OrdersDetailForm/OrdersDetailForm.jsx
  src/pages/Office/Orders/Orders.jsx
  src/pages/Office/Orders/Orders.test.jsx
  src/pages/Office/Orders/ordersFormValidationSchema.js
  src/pages/Office/ServicesCounselingOrders/ServicesCounselingOrders.jsx
  src/pages/Office/ServicesCounselingOrders/ServicesCounselingOrders.test.jsx
  src/services/ghcApi.js
Labels: Mountain Movers, MAIN

#15573 Int b 23580 ff request account privileges
  .envrc
  config/env/demo.app-client-tls.env
  config/env/demo.app.env
  config/env/exp.app-client-tls.env
  config/env/exp.app.env
  config/env/loadtest.app-client-tls.env
  config/env/loadtest.app.env
  config/env/prd.app-client-tls.env
  config/env/prd.app.env
  config/env/stg.app-client-tls.env
  config/env/stg.app.env
  config/flipt/storage/development.features.yaml
Labels: INTEGRATION, Go-Rillaz, frontend, backend

#15586 Main b 23043 update county to display for w 2 address for customer about your ppm
  playwright/tests/my/milmove/ppms/about.spec.js
  playwright/tests/my/milmove/ppms/customerPpmTestFixture.js
  src/components/Shared/PPM/Closeout/AboutForm/AboutForm.jsx
  src/components/Shared/PPM/Closeout/AboutForm/AboutForm.test.jsx
  src/pages/MyMove/PPM/Closeout/About/About.test.jsx
  src/utils/ppmCloseout.jsx
Labels: MAIN, Go-Rillaz, frontend

#15266 B 22549 MAIN financial acknowledgement update
  playwright/tests/my/mymove/hhg.spec.js
  src/components/CertificationText/CertificationText.css
  src/components/CertificationText/CertificationText.jsx
  src/components/CertificationText/CertificationText.stories.jsx
  src/components/CertificationText/CertificationText.test.jsx
  src/components/Customer/SubmitMoveForm/SubmitMoveForm.jsx
  src/components/Customer/SubmitMoveForm/SubmitMoveForm.module.scss
  src/components/Customer/SubmitMoveForm/SubmitMoveForm.test.jsx
  src/pages/MyMove/Agreement.jsx
  src/pages/MyMove/Agreement.test.jsx
  src/utils/formatters.js
Labels: G-Unit, MAIN

#15492 B 23272 INT Update Body-Parser
  package.json
  yarn.lock
Labels: G-Unit, INTEGRATION

#15582 INT B-23375 - User Story 6 - Email changes for gun safe
  pkg/assets/notifications/templates/move_submitted_template.html
  pkg/assets/notifications/templates/move_submitted_template.txt
  pkg/handlers/internalapi/moves.go
  pkg/notifications/move_submitted.go
  pkg/notifications/move_submitted_test.go
Labels: ByteSize M&Ms, INTEGRATION, backend

#15603 INT B-23739
  go.mod
  go.sum
  migrations/app/ddl_migrations/ddl_functions/20250225233157_fn_get_destination_queue.up.sql
  migrations/app/ddl_migrations/ddl_functions/20250509183824_fn_get_origin_queue.up.sql
  pkg/services/order/order_fetcher_test.go
Labels: Mountain Movers, INTEGRATION

#15602 MAIN B-23739
  migrations/app/ddl_migrations/ddl_functions/20250225233157_fn_get_destination_queue.up.sql
  migrations/app/ddl_migrations/ddl_functions/20250509183824_fn_get_origin_queue.up.sql
  pkg/services/order/order_fetcher_test.go
Labels: Mountain Movers, MAIN

#15607 B 22467
  pkg/services/ppmshipment/ppm_shipment_updater.go
  pkg/services/ppmshipment/ppm_shipment_updater_test.go
Labels: Scrummy Bears, MAIN

#15612 B 23586 - Backfill PPM Closeouts Table
  migrations/app/ddl_functions_manifest.txt
  migrations/app/ddl_migrations/ddl_functions/20250502144039_fn_calculate_ppm_closeouts.up.sql
  migrations/app/dml_migrations_manifest.txt
  migrations/app/schema/20250502143331_B-23586_backfill_ppm_closeouts_table.up.sql
Labels: Scrummy Bears, MAIN

#15605 Int b 22032 text 508
  src/components/DocumentViewerFileManager/DocumentViewerFileManager.jsx
Labels: INTEGRATION, frontend, Screen Sharks

#15606 B 23530
  pkg/services/ppmshipment/ppm_estimator.go
  pkg/services/ppmshipment/ppm_estimator_test.go
  pkg/services/ppmshipment/ppm_shipment_updater_test.go
Labels: Scrummy Bears, MAIN

#15618 B 23278 i 14252 i 14259 int
  src/pages/Office/index.jsx
Labels: Mountain Movers, INTEGRATION, frontend

#15580 B 23167 int add max billable weight to PPTAS
  pkg/gen/pptasapi/embedded_spec.go
  pkg/gen/pptasmessages/p_p_t_a_s_report.go
  pkg/handlers/pptasapi/internal/payloads/model_to_payload.go
  pkg/handlers/pptasapi/internal/payloads/model_to_payload_test.go
  pkg/models/pptas_report.go
  pkg/services/pptas_report/pptas_report_list_fetcher.go
  pkg/services/pptas_report/pptas_report_list_fetcher_test.go
  swagger-def/definitions/PPTASReport.yaml
  swagger/pptas.yaml
Labels: G-Unit, INTEGRATION, backend

#15415 B 23206 remove sit request int
  migrations/app/ddl_migrations/ddl_types/20250522221731_ty_sit_extension_status.up.sql
  migrations/app/ddl_tables_manifest.txt
  migrations/app/ddl_types_manifest.txt
  pkg/handlers/primeapi/mto_service_item.go
  pkg/models/sit_duration_update.go
  pkg/models/sit_duration_update_test.go
  pkg/services/mocks/IntlNTSHHGPackPricer.go
  pkg/services/mto_service_item/mto_service_item_updater.go
  pkg/services/mto_service_item/mto_service_item_updater_test.go
  pkg/services/shipment_address_update/shipment_address_update_requester_test.go
  pkg/services/sit_extension/rules.go
  pkg/services/sit_extension/rules_test.go
  pkg/services/sit_extension/sit_extension_creator.go
  src/constants/MoveHistory/EventTemplates/RemoveSITExtension/removeSITExtensionServiceItem.jsx
  src/constants/MoveHistory/EventTemplates/RemoveSITExtension/removeSITExtensionServiceItem.test.jsx
  src/constants/MoveHistory/EventTemplates/index.js
  src/constants/sitExtensions.js
Labels: ByteSize M&Ms, INTEGRATION, backend

#15610 INT B-23736
  migrations/app/ddl_migrations/ddl_functions/20250512175124_fn_calculate_ppm_incentive.up.sql
  migrations/app/ddl_migrations/ddl_tables/20250224200600_tbl_gcc_multipliers.up.sql
  migrations/app/ddl_migrations/ddl_tables/20250224200700_tbl_ppm_shipments.up.sql
  migrations/app/ddl_tables_manifest.txt
  migrations/app/dml_migrations_manifest.txt
  migrations/app/schema/20250528155401_B-23736_add_multipliers.up.sql
  pkg/assets/paperwork/formtemplates/ShipmentSummaryWorksheet.pdf
  pkg/factory/ppm_shipment_factory.go
  pkg/factory/ppm_shipment_factory_test.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/p_p_m_closeout.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload_test.go
  pkg/handlers/ghcapi/ppm_closeout_test.go
  pkg/models/gcc_multiplier.go
  pkg/models/gcc_multiplier_test.go
  pkg/models/ppm_shipment.go
  pkg/models/ppm_shipment_test.go
  pkg/services/ppm_closeout/ppm_closeout.go
  pkg/services/ppm_closeout/ppm_closeout_test.go
  pkg/services/ppmshipment/ppm_estimator.go
  pkg/services/ppmshipment/ppm_estimator_test.go
  pkg/services/ppmshipment/ppm_shipment_creator.go
  pkg/services/ppmshipment/ppm_shipment_creator_test.go
  pkg/services/ppmshipment/ppm_shipment_fetcher.go
  pkg/services/ppmshipment/ppm_shipment_fetcher_test.go
  pkg/services/ppmshipment/ppm_shipment_updater.go
  pkg/services/ppmshipment/ppm_shipment_updater_test.go
  pkg/services/shipment_summary_worksheet.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet_test.go
  scripts/db-truncate
  src/components/Office/PPM/PPMHeaderSummary/HeaderSection.jsx
  src/components/Office/PPM/PPMHeaderSummary/HeaderSection.module.scss
  src/components/Office/PPM/PPMHeaderSummary/HeaderSection.test.jsx
  src/components/Office/PPM/PPMHeaderSummary/PPMHeaderSummary.jsx
  src/components/Office/PPM/ReviewDocumentsSidePanel/ReviewDocumentsSidePanel.module.scss
  src/constants/MoveHistory/Database/FieldMappings.js
  src/constants/MoveHistory/Database/MonetaryFields.js
  src/constants/ppm.test.js
  src/constants/ppms.js
  src/pages/Office/DocumentViewerSidebar/DocumentViewerSidebar.module.scss
  src/utils/formatters.js
  src/utils/formatters.test.js
  swagger-def/definitions/PPMCloseout.yaml
  swagger/ghc.yaml
Labels: Mountain Movers, INTEGRATION

#15524 B-23666 MAIN: Update move status to approved after approving shipment diversion
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/mto_shipment.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/services/mto_shipment/shipment_diversion_approver.go
  pkg/services/mto_shipment/shipment_diversion_approver_test.go
  src/constants/MoveHistory/EventTemplates/ApproveShipmentDiversion/approveShipmentDiversionApproveMove.jsx
  src/constants/MoveHistory/EventTemplates/ApproveShipmentDiversion/approveShipmentDiversionApproveMove.test.jsx
  src/constants/MoveHistory/EventTemplates/index.js
Labels: Mountain Movers, MAIN

#15588 B 23319 INT - Remove HQ Role Feature Flag
  .circleci/config.yml
  .envrc
  config/env/demo.app-client-tls.env
  config/env/demo.app.env
  config/env/exp.app-client-tls.env
  config/env/exp.app.env
  config/env/loadtest.app-client-tls.env
  config/env/loadtest.app.env
  config/env/prd.app-client-tls.env
  config/env/prd.app.env
  config/env/stg.app-client-tls.env
  config/env/stg.app.env
  config/flipt/storage/development.features.yaml
  src/pages/Office/index.jsx
  src/scenes/SystemAdmin/shared/RolesPrivilegesCheckboxes.jsx
Labels: Scrummy Bears, INTEGRATION, frontend

#15617 INT B-23757
  src/components/Office/OrdersDetailForm/OrdersDetailForm.jsx
  src/components/Office/OrdersDetailForm/OrdersDetailForm.test.jsx
  src/pages/Office/Orders/Orders.test.jsx
  src/pages/Office/ServicesCounselingOrders/ServicesCounselingOrders.test.jsx
Labels: Mountain Movers, INTEGRATION

#15401 B 23162 INT - Intra-Alaska Transit Times
  migrations/app/dml_migrations_manifest.txt
  migrations/app/schema/20250505204714_B-23162_populate_intra_alaska_transit_times.up.sql
  pkg/handlers/primeapiv3/mto_shipment_test.go
  pkg/models/re_rate_area.go
  pkg/services/mto_shipment/mto_shipment_updater.go
  pkg/services/mto_shipment/mto_shipment_updater_test.go
  pkg/services/mto_shipment/rules.go
  pkg/services/mto_shipment/shipment_approver.go
  src/components/PrimeUI/Shipment/Shipment.jsx
  src/constants/MoveHistory/Database/DateFields.js
  src/constants/MoveHistory/Database/FieldMappings.js
  src/pages/Office/MoveHistory/LabeledDetails.test.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdate.jsx
Labels: Scrummy Bears, INTEGRATION, database, frontend, backend

#15589 Int b 22539 user privilege backend validation
  pkg/handlers/adminapi/office_users.go
  pkg/handlers/adminapi/office_users_test.go
Labels: INTEGRATION, Go-Rillaz, backend

#15628 B-22712-22759-INT3
  migrations/app/ddl_migrations/ddl_functions/20250509183824_fn_get_origin_queue.up.sql
Labels: G-Unit, INTEGRATION, database

#15584 Int b 23411 papi add new before parameter to list moves prime endpoint
  pkg/gen/primeapi/embedded_spec.go
  pkg/gen/primeapi/primeoperations/move_task_order/list_moves_parameters.go
  pkg/gen/primeapi/primeoperations/move_task_order/list_moves_urlbuilder.go
  pkg/gen/primeclient/move_task_order/list_moves_parameters.go
  pkg/handlers/primeapi/move_task_order.go
  pkg/handlers/primeapi/move_task_order_test.go
  pkg/services/move_task_order.go
  pkg/services/move_task_order/move_task_order_fetcher.go
  pkg/services/move_task_order/move_task_order_fetcher_test.go
  swagger-def/prime.yaml
  swagger/prime.yaml
Labels: INTEGRATION, Go-Rillaz, backend

#15632 B-23635 fix existing orders
  migrations/app/dml_migrations_manifest.txt
  migrations/app/schema/20250606201946_B-23635_update_old_grades.up.sql
Labels: G-Unit, INTEGRATION, database

#15563 B-22968: Task Order Queue Bulk Assignment Updates
  migrations/app/ddl_functions_manifest.txt
  migrations/app/ddl_migrations/ddl_functions/20250528195649_fn_get_moves_for_bulk_assignment.up.sql
  pkg/services/move/move_fetcher.go
  pkg/services/move/move_fetcher_test.go
Labels: Mountain Movers, INTEGRATION, database

#15616 MAIN B-23757
  src/components/Office/OrdersDetailForm/OrdersDetailForm.jsx
  src/components/Office/OrdersDetailForm/OrdersDetailForm.test.jsx
  src/pages/Office/Orders/Orders.test.jsx
  src/pages/Office/ServicesCounselingOrders/ServicesCounselingOrders.test.jsx
Labels: Mountain Movers, MAIN

#15019 MAIN - B-22463 International SIT Pricing Additional days
  migrations/app/ddl_functions_manifest.txt
  migrations/app/ddl_migrations/ddl_functions/20250221213413_fn_update_service_item_pricing.up.sql
  migrations/app/ddl_migrations/ddl_functions/20250424183918_fn_get_application_parameter_value.up.sql
  migrations/app/dml_migrations_manifest.txt
  migrations/app/schema/20250310151829_B-22463_add_supporting_service_params_for_request_payment.up.sql
  migrations/app/schema/20250424182556_B-22463_add_max_sit_days_application_parameter.up.sql
  pkg/handlers/primeapi/allowed_payment_service_item_params.go
  pkg/payment_request/service_param_value_lookups/number_days_sit_lookup.go
  pkg/payment_request/service_param_value_lookups/number_days_sit_lookup_test.go
  pkg/services/mto_shipment/mto_shipment_updater_test.go
  src/components/PrimeUI/CreatePaymentRequestForm/CreatePaymentRequestForm.jsx
Labels: Scrummy Bears, MAIN, backend

#15609 MAIN B-23736
  migrations/app/ddl_functions_manifest.txt
  migrations/app/ddl_migrations/ddl_functions/20250603161001_fn_calculate_ppm_incentive.up.sql
  migrations/app/ddl_migrations/ddl_tables/20250224200600_tbl_gcc_multipliers.up.sql
  migrations/app/ddl_migrations/ddl_tables/20250224200700_tbl_ppm_shipments.up.sql
  migrations/app/ddl_tables_manifest.txt
  migrations/app/dml_migrations_manifest.txt
  migrations/app/schema/20250528155401_B-23736_add_multipliers.up.sql
  pkg/assets/paperwork/formtemplates/ShipmentSummaryWorksheet.pdf
  pkg/factory/ppm_shipment_factory.go
  pkg/factory/ppm_shipment_factory_test.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/p_p_m_closeout.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload_test.go
  pkg/handlers/ghcapi/ppm_closeout_test.go
  pkg/models/gcc_multiplier.go
  pkg/models/gcc_multiplier_test.go
  pkg/models/ppm_shipment.go
  pkg/models/ppm_shipment_test.go
  pkg/services/ppm_closeout/ppm_closeout.go
  pkg/services/ppm_closeout/ppm_closeout_test.go
  pkg/services/ppmshipment/ppm_estimator.go
  pkg/services/ppmshipment/ppm_estimator_test.go
  pkg/services/ppmshipment/ppm_shipment_creator.go
  pkg/services/ppmshipment/ppm_shipment_creator_test.go
  pkg/services/ppmshipment/ppm_shipment_fetcher.go
  pkg/services/ppmshipment/ppm_shipment_fetcher_test.go
  pkg/services/ppmshipment/ppm_shipment_updater.go
  pkg/services/ppmshipment/ppm_shipment_updater_test.go
  pkg/services/shipment_summary_worksheet.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet_test.go
  scripts/db-truncate
  src/components/Office/PPM/PPMHeaderSummary/HeaderSection.jsx
  src/components/Office/PPM/PPMHeaderSummary/HeaderSection.module.scss
  src/components/Office/PPM/PPMHeaderSummary/HeaderSection.test.jsx
  src/components/Office/PPM/PPMHeaderSummary/PPMHeaderSummary.jsx
  src/components/Office/PPM/ReviewDocumentsSidePanel/ReviewDocumentsSidePanel.module.scss
  src/constants/MoveHistory/Database/FieldMappings.js
  src/constants/MoveHistory/Database/MonetaryFields.js
  src/constants/ppm.test.js
  src/constants/ppms.js
  src/pages/Office/DocumentViewerSidebar/DocumentViewerSidebar.module.scss
  src/utils/formatters.js
  src/utils/formatters.test.js
  swagger-def/definitions/PPMCloseout.yaml
  swagger/ghc.yaml
Labels: Mountain Movers, MAIN

#15572 Main b 23580 ff request account privileges
  .envrc
  config/env/demo.app-client-tls.env
  config/env/demo.app.env
  config/env/exp.app-client-tls.env
  config/env/exp.app.env
  config/env/loadtest.app-client-tls.env
  config/env/loadtest.app.env
  config/env/prd.app-client-tls.env
  config/env/prd.app.env
  config/env/stg.app-client-tls.env
  config/env/stg.app.env
  config/flipt/storage/development.features.yaml
Labels: MAIN, Go-Rillaz

#15163 B 22466 intl sit pickup delivery
  migrations/app/ddl_functions_manifest.txt
  migrations/app/ddl_migrations/ddl_functions/20250221213413_fn_update_service_item_pricing.up.sql
  migrations/app/ddl_migrations/ddl_functions/20250313200647_fn_calculate_escalated_price.up.sql
  migrations/app/ddl_migrations/ddl_tables/20250328154338_tbl_B-22466_alter_re_intl_other_prices.up.sql
  migrations/app/ddl_tables_manifest.txt
  migrations/app/dml_migrations_manifest.txt
  migrations/app/schema/20250328155348_B-22466_update_data_re_intl_other_prices_and_service_params.up.sql
  migrations/app/schema/20250522135232_B-22466_v2_add_distance_lookup_service_params.up.sql
  pkg/models/re_intl_other_price.go
  pkg/payment_request/service_param_value_lookups/per_unit_cents_lookup.go
  pkg/payment_request/service_param_value_lookups/per_unit_cents_lookup_test.go
  pkg/payment_request/service_param_value_lookups/service_param_value_lookups.go
  pkg/services/ghc_rate_engine.go
  pkg/services/ghcrateengine/intl_destination_delivery_sit_pricer.go
  pkg/services/ghcrateengine/intl_destination_delivery_sit_pricer_test.go
  pkg/services/ghcrateengine/intl_origin_pickup_sit_pricer.go
  pkg/services/ghcrateengine/intl_origin_pickup_sit_pricer_test.go
  pkg/services/ghcrateengine/pricer_helpers_intl.go
  pkg/services/ghcrateengine/pricer_helpers_intl_test.go
  pkg/services/ghcrateengine/service_item_pricer.go
  pkg/services/mocks/InternationalDestinationSITDeliveryPricer.go
  pkg/services/mocks/InternationalOriginSITPickupPricer.go
Labels: Scrummy Bears, backend

#15631 Main b 23252
  src/pages/MyMove/PPM/Closeout/ProGear/ProGear.jsx
Labels: MAIN, Go-Rillaz, frontend

#15592 MAIN B-23180 move details warning
  src/pages/Office/MoveDetails/MoveDetails.jsx
  src/pages/Office/MoveDetails/MoveDetails.test.jsx
Labels: MAIN, Go-Rillaz, frontend

#15595 B 23196 int - Create Feature Flag for Wounded Warrior Order Type
  .envrc
  config/env/demo.app-client-tls.env
  config/env/demo.app.env
  config/env/exp.app-client-tls.env
  config/env/exp.app.env
  config/env/loadtest.app-client-tls.env
  config/env/loadtest.app.env
  config/env/prd.app-client-tls.env
  config/env/prd.app.env
  config/env/stg.app-client-tls.env
  config/env/stg.app.env
  config/flipt/storage/development.features.yaml
  src/components/Customer/EditOrdersForm/EditOrdersForm.test.jsx
  src/components/Customer/OrdersInfoForm/OrdersInfoForm.test.jsx
  src/components/Office/AddOrdersForm/AddOrdersForm.test.jsx
  src/constants/orders.js
  src/pages/MyMove/AddOrders.jsx
  src/pages/MyMove/AddOrders.test.jsx
  src/pages/MyMove/EditOrders.jsx
  src/pages/MyMove/EditOrders.test.jsx
  src/pages/MyMove/Orders.jsx
  src/pages/MyMove/Orders.test.jsx
  src/pages/Office/Orders/Orders.jsx
  src/pages/Office/Orders/Orders.test.jsx
  src/pages/Office/ServicesCounselingAddOrders/ServicesCounselingAddOrders.jsx
  src/pages/Office/ServicesCounselingAddOrders/ServicesCounselingAddOrders.test.jsx
  src/pages/Office/ServicesCounselingOrders/ServicesCounselingOrders.jsx
  src/pages/Office/ServicesCounselingOrders/ServicesCounselingOrders.test.jsx
  src/shared/constants.js
Labels: G-Unit, INTEGRATION, frontend

#15601 B-23280 Increasing PDF Zoom to 500%
  package.json
  yarn.lock
Labels: Mountain Movers, INTEGRATION

#15659 MAIN B-23775
  cmd/generate-shipment-summary/main.go
  pkg/assets/paperwork/formtemplates/ShipmentSummaryWorksheet.pdf
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/ppm_document_test.go
  pkg/handlers/internalapi/api.go
  pkg/models/gcc_multiplier.go
  pkg/models/gcc_multiplier_test.go
  pkg/services/mocks/QueryAssociation.go
  pkg/services/mocks/QueryAssociations.go
  pkg/services/mocks/QueryFilter.go
  pkg/services/mocks/QueryOrder.go
  pkg/services/mocks/SFTPFiler.go
  pkg/services/mocks/SSWPPMComputer.go
  pkg/services/mocks/SyncadaFileProcessor.go
  pkg/services/ppmshipment/aoa_packet_creator.go
  pkg/services/ppmshipment/aoa_packet_creator_test.go
  pkg/services/ppmshipment/ppm_estimator.go
  pkg/services/ppmshipment/ppm_estimator_test.go
  pkg/services/ppmshipment/ppm_shipment_review_documents.go
  pkg/services/ppmshipment/ppm_shipment_review_documents_test.go
  pkg/services/ppmshipment/ppm_shipment_updater.go
  pkg/services/ppmshipment/ppm_shipment_updater_test.go
  pkg/services/shipment_summary_worksheet.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet.go
  pkg/services/shipment_summary_worksheet/shipment_summary_worksheet_test.go
  pkg/storage/mocks/FileStorer.go
Labels: Mountain Movers, MAIN

#15621 MAIN B-23678
  src/pages/Admin/AdminUsers/AdminUserCreate.jsx
  src/pages/Admin/AdminUsers/AdminUserEdit.jsx
  src/pages/Admin/ClientCerts/ClientCertCreate.jsx
  src/pages/Admin/ClientCerts/ClientCertEdit.jsx
  src/pages/Admin/FeatureFlags/FeatureFlagEvaluate.jsx
  src/pages/Admin/FeatureFlags/FeatureFlags.module.scss
  src/pages/Admin/Moves/MoveEdit.jsx
  src/pages/Admin/OfficeUsers/OfficeUserCreate.jsx
  src/pages/Admin/OfficeUsers/OfficeUserEdit.jsx
  src/pages/Admin/OfficeUsers/OfficeUserList.jsx
  src/pages/Admin/RejectedOfficeUsers/RejectedOfficeUserList.jsx
  src/pages/Admin/RejectedOfficeUsers/RejectedOfficeUserShow.jsx
  src/pages/Admin/RequestedOfficeUsers/RequestedOfficeUserEdit.jsx
  src/pages/Admin/RequestedOfficeUsers/RequestedOfficeUserList.jsx
  src/pages/Admin/RequestedOfficeUsers/RequestedOfficeUserShow.jsx
  src/pages/Admin/RequestedOfficeUsers/RequestedOfficeUserShow.module.scss
  src/pages/Admin/Shared/SaveToolbar.jsx
  src/pages/Admin/Users/UserEdit.jsx
  src/pages/Admin/WebhookSubscriptions/WebhookSubscriptionCreate.jsx
  src/pages/Admin/WebhookSubscriptions/WebhookSubscriptionEdit.jsx
  src/pages/Admin/adminStyles.module.scss
  src/scenes/SystemAdmin/Home.jsx
  src/scenes/SystemAdmin/Home.module.scss
  src/scenes/SystemAdmin/Uploads/UploadSearch.jsx
  src/scenes/SystemAdmin/Uploads/UploadSearch.module.scss
Labels: Mountain Movers, MAIN

#15668 B 23767 main
  migrations/app/ddl_migrations/ddl_functions/20250509183824_fn_get_origin_queue.up.sql
  pkg/services/order/order_fetcher_test.go
Labels: Mountain Movers, MAIN

#15581 MAIN B-23375 - User Story 6 - Email changes for gun safe
  pkg/assets/notifications/templates/move_submitted_template.html
  pkg/assets/notifications/templates/move_submitted_template.txt
  pkg/handlers/internalapi/moves.go
  pkg/notifications/move_submitted.go
  pkg/notifications/move_submitted_test.go
Labels: ByteSize M&Ms, MAIN

#15666 B-22968: Task Order Queue Bulk Assignment Updates
  migrations/app/ddl_functions_manifest.txt
  migrations/app/ddl_migrations/ddl_functions/20250528195649_fn_get_moves_for_bulk_assignment.up.sql
  pkg/services/move/move_fetcher.go
  pkg/services/move/move_fetcher_test.go
Labels: Mountain Movers, MAIN

#15638 B 22457 INT make second pickup address selector visible prime
  playwright/tests/office/primesimulator/primeSimulatorFlows.spec.js
  src/pages/PrimeUI/Shipment/PrimeUIShipmentCreateForm.jsx
Labels: G-Unit, INTEGRATION

#15669 B 23370
  .circleci/config.yml
  .envrc
  artifacts/accessibilityReport.html
  config/env/demo.app-client-tls.env
  config/env/demo.app.env
  config/env/exp.app-client-tls.env
  config/env/exp.app.env
  config/env/loadtest.app-client-tls.env
  config/env/loadtest.app.env
  config/env/prd.app-client-tls.env
  config/env/prd.app.env
  config/env/stg.app-client-tls.env
  config/env/stg.app.env
  config/flipt/storage/development.features.yaml
  playwright/tests/my/milmove/ppms/about.spec.js
  playwright/tests/my/milmove/ppms/advances.spec.js
  playwright/tests/my/milmove/ppms/customerPpmTestFixture.js
  playwright/tests/my/milmove/ppms/dateAndLocation.spec.js
  playwright/tests/my/milmove/ppms/entireShipmentCloseout.spec.js
  playwright/tests/my/milmove/ppms/entireShipmentOnboarding.spec.js
  playwright/tests/my/milmove/ppms/estimatedIncentive.spec.js
  playwright/tests/my/milmove/ppms/estimatedWeightsProgear.spec.js
  playwright/tests/my/milmove/ppms/expenses.spec.js
  playwright/tests/my/milmove/ppms/finalCloseout.spec.js
  playwright/tests/my/milmove/ppms/navigateToUploadDocs.spec.js
  playwright/tests/my/milmove/ppms/progear.spec.js
  playwright/tests/my/milmove/ppms/review.spec.js
  playwright/tests/my/milmove/ppms/weightTickets.spec.js
  playwright/tests/my/mymove/additionalDocs.spec.js
  playwright/tests/my/mymove/boat.spec.js
  playwright/tests/my/mymove/hhg.spec.js
  playwright/tests/my/mymove/mobileHome.spec.js
  playwright/tests/my/mymove/nts.spec.js
  playwright/tests/my/mymove/ntsr.spec.js
  playwright/tests/my/mymove/onboarding.spec.js
  playwright/tests/my/mymove/orders.spec.js
  playwright/tests/my/mymove/uploads.spec.js
  src/pages/MyMove/Boat/BoatShipmentCreate/BoatShipmentCreate.jsx
  src/pages/MyMove/MobileHome/MobileHomeShipmentCreate/MobileHomeShipmentCreate.jsx
  src/pages/MyMove/MovingInfo.jsx
  src/pages/MyMove/PPM/Booking/DateAndLocation/DateAndLocation.jsx
  src/pages/MyMove/PPM/Booking/DateAndLocation/DateAndLocation.test.jsx
  src/pages/MyMove/PPM/Closeout/About/About.jsx
  src/pages/MyMove/PPM/Closeout/About/About.test.jsx
  src/pages/MyMove/PPM/Closeout/FinalCloseout/FinalCloseout.jsx
  src/pages/MyMove/PPM/Closeout/FinalCloseout/FinalCloseout.test.jsx
  src/pages/MyMove/Profile/Profile.jsx
  src/pages/MyMove/Profile/Profile.test.jsx
  src/pages/MyMove/Review/Review.jsx
  src/pages/MyMove/Review/Review.test.jsx
  src/pages/MyMove/UploadOrders.jsx
  src/scenes/MyMove/index.jsx
  src/scenes/MyMove/index.test.jsx
Labels: Scrummy Bears, MAIN

#15658 B 23178 int
  .envrc
  config/env/demo.app-client-tls.env
  config/env/demo.app.env
  config/env/exp.app-client-tls.env
  config/env/exp.app.env
  config/env/loadtest.app-client-tls.env
  config/env/loadtest.app.env
  config/env/prd.app-client-tls.env
  config/env/prd.app.env
  config/env/stg.app-client-tls.env
  config/env/stg.app.env
  config/flipt/storage/development.features.yaml
  src/components/Customer/EditOrdersForm/EditOrdersForm.test.jsx
  src/components/Customer/OrdersInfoForm/OrdersInfoForm.test.jsx
  src/components/Office/AddOrdersForm/AddOrdersForm.test.jsx
  src/constants/orders.js
  src/pages/MyMove/AddOrders.jsx
  src/pages/MyMove/AddOrders.test.jsx
  src/pages/MyMove/EditOrders.jsx
  src/pages/MyMove/EditOrders.test.jsx
  src/pages/MyMove/Orders.jsx
  src/pages/MyMove/Orders.test.jsx
  src/pages/Office/CustomerOnboarding/CreateCustomerForm.jsx
  src/pages/Office/CustomerOnboarding/CreateCustomerForm.test.jsx
  src/pages/Office/Orders/Orders.jsx
  src/pages/Office/Orders/Orders.test.jsx
  src/pages/Office/ServicesCounselingAddOrders/ServicesCounselingAddOrders.jsx
  src/pages/Office/ServicesCounselingAddOrders/ServicesCounselingAddOrders.test.jsx
  src/pages/Office/ServicesCounselingOrders/ServicesCounselingOrders.jsx
  src/pages/Office/ServicesCounselingOrders/ServicesCounselingOrders.test.jsx
  src/shared/constants.js
Labels: G-Unit, INTEGRATION

#15652 B 22883 int alternate
  src/components/DocumentViewer/Content/Content.module.scss
  src/components/DocumentViewer/DocumentViewer.jsx
  src/components/DocumentViewer/DocumentViewer.module.scss
  src/components/DocumentViewer/DocumentViewer.test.jsx
  src/shared/constants.js
Labels: Scrummy Bears, INTEGRATION, frontend

#15689 Main b 21060 508 move task
  src/pages/Office/ServicesCounselingMoveInfo/ServicesCounselingTab.module.scss
  src/pages/Office/TXOMoveInfo/TXOTab.module.scss
Labels: MAIN, frontend, Screen Sharks

#15682 B-22665 adjust playwright testharness zip code from Arizona -> California
  pkg/testdatagen/testharness/make_move.go
Labels: Mountain Movers, INTEGRATION, backend

#15629 B 23547 ppm closeout queue refactor i 14245 int
  migrations/app/ddl_migrations/ddl_functions/20250515124258_fn_get_ppm_closeout_queue.up.sql
  pkg/services/order/list_ppm_closeout.go
  pkg/services/order/list_ppm_closeout_test.go
  pkg/services/ppmshipment/ppm_shipment_creator_test.go
Labels: Mountain Movers, INTEGRATION, database, backend

#15697 B-23434 INT: Only show red required asterisk for radio buttons with no pre-filled value
  src/components/Customer/MtoShipmentForm/MtoShipmentForm.jsx
  src/components/Customer/PPM/Booking/Advance/AdvanceForm.jsx
  src/components/Customer/PPM/Booking/Advance/AdvanceForm.test.jsx
  src/components/Customer/PPM/Booking/DateAndLocationForm/DateAndLocationForm.jsx
  src/components/Customer/PPM/Booking/DateAndLocationForm/DateAndLocationForm.test.jsx
  src/components/Customer/PPM/Booking/EstimatedWeightsProGearForm/EstimatedWeightsProGearForm.jsx
  src/components/Office/ShipmentForm/ShipmentForm.jsx
  src/components/Office/ShipmentWeight/ShipmentWeight.jsx
  src/components/Shared/PPM/Closeout/AboutForm/AboutForm.jsx
  src/components/Shared/PPM/Closeout/ExpenseForm/ExpenseForm.jsx
  src/components/Shared/PPM/Closeout/SmallPackageForm/SmallPackageForm.jsx
  src/components/Shared/PPM/Closeout/WeightTicketForm/WeightTicketForm.jsx
Labels: Mountain Movers, INTEGRATION, frontend, Screen Sharks

#15696 I-14308
  src/components/DocumentViewer/DocumentViewer.jsx
Labels: bug, Scrummy Bears, INTEGRATION

#15496 B-23280 MAIN: Update document viewing zoom scale
  package.json
  src/components/DocumentViewer/Content/Content.jsx
  src/components/DocumentViewer/Content/Content.module.scss
  src/components/DocumentViewer/Content/Content.test.jsx
  yarn.lock
Labels: Mountain Movers, MAIN

#15462 B 23583 int - Rename tio_assigned_id DB column to distinguish queue work
  migrations/app/ddl_migrations/ddl_functions/20250325161603_fn_fetch_move_history.up.sql
  migrations/app/ddl_migrations/ddl_functions/20250505143424_fn_get_payment_request_queue.up.sql
  migrations/app/ddl_migrations/ddl_tables/20250224162949_B-22706_tbl_update_moves.up.sql
  pkg/factory/move_factory.go
  pkg/factory/move_factory_test.go
  pkg/factory/shared.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/move.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload_test.go
  pkg/handlers/ghcapi/move_test.go
  pkg/handlers/ghcapi/queues.go
  pkg/handlers/ghcapi/queues_test.go
  pkg/models/move.go
  pkg/services/move/assigned_office_user_updater.go
  pkg/services/move/assigned_office_user_updater_test.go
  pkg/services/move/move_assignment.go
  pkg/services/move/move_assignment_test.go
  pkg/services/move/move_fetcher.go
  pkg/services/move/move_fetcher_test.go
  pkg/services/office_user/office_user_fetcher.go
  pkg/services/payment_request.go
  pkg/services/payment_request/payment_request_list_fetcher.go
  pkg/services/payment_request/payment_request_list_fetcher_test.go
  pkg/services/payment_request/payment_request_status_updater.go
  pkg/services/payment_request/payment_request_status_updater_test.go
  src/constants/MoveHistory/EventTemplates/SaveBulkAssignmentData/SaveBulkAssignmentData.test.jsx
  src/constants/MoveHistory/EventTemplates/UpdateAssignedOfficeUser/DeleteAssignedOfficeUser.jsx
  src/constants/MoveHistory/EventTemplates/UpdateAssignedOfficeUser/DeleteAssignedOfficeUser.test.jsx
  src/constants/MoveHistory/EventTemplates/UpdateAssignedOfficeUser/UpdateAssignedOfficeUser.test.jsx
  src/constants/MoveHistory/EventTemplates/UpdatePaymentRequestStatus/UpdatePaymentRequestStatusMoves.jsx
  src/constants/MoveHistory/EventTemplates/UpdatePaymentRequestStatus/UpdatePaymentRequestStatusMoves.test.jsx
  src/constants/MoveHistory/officeUserAssignment.js
  src/utils/formatters.test.js
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: G-Unit, INTEGRATION

#15700 B 23708 INT KB
  pkg/services/move_history/move_history_fetcher_test.go
  pkg/services/mto_service_item/mto_service_item_creator.go
  pkg/services/mto_service_item/mto_service_item_creator_test.go
Labels: G-Unit, INTEGRATION, backend

#15691 INT B-23803
  pkg/services/ppmshipment/ppm_estimator.go
  pkg/services/ppmshipment/ppm_estimator_test.go
  pkg/services/ppmshipment/ppm_shipment_updater.go
  yarn.lock
Labels: Mountain Movers, INTEGRATION

#15704 B23819-INT-Remove unused col from db
  migrations/app/dml_migrations_manifest.txt
  migrations/app/schema/20250620150003_B-23819_alter_backup_contacts.up.sql
Labels: ByteSize M&Ms, INTEGRATION

#15726 B23301-INT-KB1B-Split backup contact name
  migrations/app/ddl_migrations/ddl_tables/20250528192635_tbl_backup_contacts.up.sql
  src/components/Office/DefinitionLists/CustomerInfoList.jsx
  src/components/Office/DefinitionLists/CustomerInfoList.test.jsx
  src/components/Office/DetailsPanel/DetailsPanel.stories.jsx
Labels: ByteSize M&Ms, INTEGRATION

#15714 B-23162 MAIN - Intra-Alaska Transit Time
  migrations/app/dml_migrations_manifest.txt
  migrations/app/schema/20250505204714_B-23162_populate_intra_alaska_transit_times.up.sql
  pkg/handlers/primeapiv3/mto_shipment_test.go
  pkg/models/re_rate_area.go
  pkg/services/mto_shipment/mto_shipment_updater.go
  pkg/services/mto_shipment/mto_shipment_updater_test.go
  pkg/services/mto_shipment/rules.go
  pkg/services/mto_shipment/shipment_approver.go
  src/components/PrimeUI/Shipment/Shipment.jsx
  src/constants/MoveHistory/Database/DateFields.js
  src/constants/MoveHistory/Database/FieldMappings.js
  src/pages/Office/MoveHistory/LabeledDetails.test.jsx
  src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdate.jsx
Labels: Scrummy Bears, MAIN

#15566 B-23178 create bluebark ff
  .envrc
  config/env/demo.app-client-tls.env
  config/env/demo.app.env
  config/env/exp.app-client-tls.env
  config/env/exp.app.env
  config/env/loadtest.app-client-tls.env
  config/env/loadtest.app.env
  config/env/prd.app-client-tls.env
  config/env/prd.app.env
  config/env/stg.app-client-tls.env
  config/env/stg.app.env
  config/flipt/storage/development.features.yaml
  src/components/Customer/EditOrdersForm/EditOrdersForm.test.jsx
  src/components/Customer/OrdersInfoForm/OrdersInfoForm.test.jsx
  src/components/Office/AddOrdersForm/AddOrdersForm.test.jsx
  src/constants/orders.js
  src/pages/MyMove/AddOrders.jsx
  src/pages/MyMove/AddOrders.test.jsx
  src/pages/MyMove/EditOrders.jsx
  src/pages/MyMove/EditOrders.test.jsx
  src/pages/MyMove/Orders.jsx
  src/pages/MyMove/Orders.test.jsx
  src/pages/Office/CustomerOnboarding/CreateCustomerForm.jsx
  src/pages/Office/CustomerOnboarding/CreateCustomerForm.test.jsx
  src/pages/Office/Orders/Orders.jsx
  src/pages/Office/Orders/Orders.test.jsx
  src/pages/Office/ServicesCounselingAddOrders/ServicesCounselingAddOrders.jsx
  src/pages/Office/ServicesCounselingAddOrders/ServicesCounselingAddOrders.test.jsx
  src/pages/Office/ServicesCounselingOrders/ServicesCounselingOrders.jsx
  src/pages/Office/ServicesCounselingOrders/ServicesCounselingOrders.test.jsx
  src/shared/constants.js
Labels: G-Unit, MAIN

#15422 B 23206 remove sit request main
  migrations/app/ddl_migrations/ddl_types/20250522221731_ty_sit_extension_status.up.sql
  migrations/app/ddl_types_manifest.txt
  pkg/handlers/ghcapi/api.go
  pkg/handlers/ghcapi/mto_service_items_test.go
  pkg/handlers/ghcapi/mto_shipment_test.go
  pkg/handlers/primeapi/api.go
  pkg/handlers/primeapi/mto_service_item.go
  pkg/handlers/primeapi/mto_service_item_test.go
  pkg/handlers/supportapi/api.go
  pkg/handlers/supportapi/mto_service_item_test.go
  pkg/models/re_service.go
  pkg/models/sit_duration_update.go
  pkg/models/sit_duration_update_test.go
  pkg/services/move_history/move_history_fetcher_test.go
  pkg/services/mto_service_item/mto_service_item_updater.go
  pkg/services/mto_service_item/mto_service_item_updater_test.go
  pkg/services/shipment_address_update/shipment_address_update_requester.go
  pkg/services/sit_extension/rules.go
  pkg/services/sit_extension/rules_test.go
  pkg/services/sit_extension/sit_extension_creator.go
  pkg/services/sit_extension/sit_extension_denier.go
  pkg/testdatagen/scenario/shared.go
  src/constants/MoveHistory/Database/FieldMappings.js
  src/constants/MoveHistory/EventTemplates/ApproveMoveAfterSitExtRemoval/approveMoveAfterSitExtRemoval.jsx
  src/constants/MoveHistory/EventTemplates/ApproveMoveAfterSitExtRemoval/approveMoveAfterSitExtRemoval.test.jsx
  src/constants/MoveHistory/EventTemplates/ApproveShipmentAfterSitExtRemoval/approveShipmentAfterSitExtRemoval.jsx
  src/constants/MoveHistory/EventTemplates/ApproveShipmentAfterSitExtRemoval/approveShipmentAfterSitExtRemoval.test.jsx
  src/constants/MoveHistory/EventTemplates/RemoveSITExtension/removeSITExtensionServiceItem.jsx
  src/constants/MoveHistory/EventTemplates/RemoveSITExtension/removeSITExtensionServiceItem.test.jsx
  src/constants/MoveHistory/EventTemplates/UpdateShipmentAfterSitExtCreation/updateShipmentAfterSitExtCreation.jsx
  src/constants/MoveHistory/EventTemplates/UpdateShipmentAfterSitExtCreation/updateShipmentAfterSitExtCreation.test.jsx
  src/constants/MoveHistory/EventTemplates/index.js
  src/constants/sitExtensions.js
Labels: ByteSize M&Ms, MAIN

#15725 INT B-23658 I-14316
  pkg/services/ghcrateengine/intl_shipping_and_linehaul_pricer.go
  pkg/services/ghcrateengine/intl_shipping_and_linehaul_pricer_test.go
  src/components/PrimeUI/CreatePaymentRequestForm/CreatePaymentRequestForm.jsx
Labels: Mountain Movers, INTEGRATION

#15707 INT B-23372 user story 4 edit gun safe sc closeout
  pkg/assets/notifications/templates/move_submitted_template.html
  pkg/assets/notifications/templates/move_submitted_template.txt
  pkg/models/gunsafe_weight_ticket.go
  pkg/models/gunsafe_weight_ticket_test.go
  pkg/notifications/move_submitted_test.go
  pkg/services/ppmshipment/payment_packet_creator.go
  pkg/services/ppmshipment/payment_packet_creator_test.go
  pkg/testdatagen/testharness/dispatch.go
  pkg/testdatagen/testharness/make_move.go
  playwright/tests/office/ppms/happyPathFlows.spec.js
  playwright/tests/office/servicescounseling/servicesCounselingGunSafeTickets.spec.js
  playwright/tests/utils/testharness.js
  src/components/Customer/PPM/Booking/EstimatedWeightsProGearForm/EstimatedWeightsProGearForm.jsx
  src/components/Customer/PPM/Booking/EstimatedWeightsProGearForm/EstimatedWeightsProGearForm.test.jsx
  src/components/DocumentViewerFileManager/DocumentViewerFileManager.jsx
  src/components/Office/PPM/ReviewDocumentsSidePanel/ReviewDocumentsSidePanel.jsx
  src/components/Office/PPM/ReviewDocumentsSidePanel/ReviewDocumentsSidePanel.module.scss
  src/components/Office/PPM/ReviewDocumentsSidePanel/ReviewDocumentsSidePanel.stories.jsx
  src/components/Office/PPM/ReviewDocumentsSidePanel/ReviewDocumentsSidePanel.test.jsx
  src/components/Office/PPM/ReviewGunSafe/ReviewGunSafe.jsx
  src/components/Office/PPM/ReviewGunSafe/ReviewGunSafe.module.scss
  src/components/Office/PPM/ReviewGunSafe/ReviewGunSafe.stories.jsx
  src/components/Office/PPM/ReviewGunSafe/ReviewGunSafe.test.jsx
  src/components/Office/ShipmentWeight/ShipmentWeight.jsx
  src/components/Office/ShipmentWeight/ShipmentWeight.test.jsx
  src/constants/queryKeys.js
  src/hooks/queries.js
  src/hooks/queries.test.jsx
  src/pages/Office/PPM/ReviewDocuments/ReviewDocuments.jsx
  src/pages/Office/PPM/ReviewDocuments/ReviewDocuments.test.jsx
  src/utils/test/factories/gunSafeWeightTicket.js
Labels: ByteSize M&Ms, INTEGRATION, frontend, backend

#15718 B-23437 INT: Required vs. Optional Fields - Services Counselor
  playwright/tests/my/milmove/ppms/customerPpmTestFixture.js
  playwright/tests/office/servicescounseling/servicesCounselingInternational.spec.js
  src/components/Customer/EditOrdersForm/EditOrdersForm.jsx
  src/components/Customer/MobileHomeShipment/MobileHomeShipmentForm/MobileHomeShipmentForm.jsx
  src/components/Customer/OrdersInfoForm/OrdersInfoForm.jsx
  src/components/Customer/PPM/Booking/EstimatedWeightsProGearForm/EstimatedWeightsProGearForm.jsx
  src/components/Office/AddOrdersForm/AddOrdersForm.jsx
  src/components/Office/AddOrdersForm/AddOrdersForm.test.jsx
  src/components/Office/FinancialReviewModal/FinancialReviewModal.jsx
  src/components/Office/FinancialReviewModal/FinancialReviewModal.test.jsx
  src/components/Office/OrdersDetailForm/OrdersDetailForm.jsx
  src/components/Office/OrdersDetailForm/OrdersDetailForm.test.jsx
  src/components/Office/PPM/PPMHeaderSummary/EditPPMHeaderSummaryModal.jsx
  src/components/Office/PPM/PPMHeaderSummary/EditPPMHeaderSummaryModal.test.jsx
  src/components/Office/PPM/ReviewDocumentsSidePanel/ReviewDocumentsSidePanel.jsx
  src/components/Office/PPM/ReviewExpense/ReviewExpense.jsx
  src/components/Office/PPM/ReviewExpense/ReviewExpense.test.jsx
  src/components/Office/PPM/ReviewProGear/ReviewProGear.jsx
  src/components/Office/PPM/ReviewProGear/ReviewProGear.test.jsx
  src/components/Office/PPM/ReviewWeightTicket/ReviewWeightTicket.jsx
  src/components/Office/PPM/ReviewWeightTicket/ReviewWeightTicket.test.jsx
  src/components/Office/ShipmentCustomerSIT/ShipmentCustomerSIT.jsx
  src/components/Office/ShipmentCustomerSIT/ShipmentCustomerSIT.test.jsx
  src/components/Office/ShipmentForm/BoatShipmentForm/BoatShipmentForm.jsx
  src/components/Office/ShipmentForm/MobileHomeShipmentForm/MobileHomeShipmentForm.jsx
  src/components/Office/ShipmentForm/ShipmentForm.jsx
  src/components/Office/ShipmentForm/ShipmentForm.test.jsx
  src/components/Office/ShipmentForm/ppmShipmentSchema.js
  src/components/Office/ShipmentFormRemarks/ShipmentFormRemarks.jsx
  src/components/Office/ShipmentFormRemarks/ShipmentFormRemarks.test.jsx
  src/components/Office/ShipmentIncentiveAdvance/ShipmentIncentiveAdvance.jsx
  src/components/Office/ShipmentIncentiveAdvance/ShipmentIncentiveAdvance.test.jsx
  src/components/Office/ShipmentWeight/ShipmentWeight.jsx
  src/components/Office/ShipmentWeight/ShipmentWeight.test.jsx
  src/components/Shared/PPM/Closeout/ProGearForm/ProGearForm.test.jsx
  src/components/Shared/PPM/Closeout/WeightTicketForm/WeightTicketForm.test.jsx
  src/components/Shared/PPM/Closeout/WeightTicketUpload/WeightTicketUpload.test.jsx
  src/components/form/OfficeAccountRequestFields/OfficeAccountRequestFields.jsx
  src/components/form/OfficeAccountRequestFields/OfficeAccountRequestFields.test.jsx
  src/components/form/OptionalTag.jsx
  src/components/form/OptionalTag.module.scss
  src/components/form/fields/DropdownInput.jsx
  src/components/form/fields/MaskedTextField/MaskedTextField.jsx
  src/components/form/fields/TextField/TextField.jsx
  src/pages/Office/CustomerOnboarding/CreateCustomerForm.jsx
  src/pages/Office/CustomerOnboarding/CreateCustomerForm.test.jsx
  src/pages/Office/PPM/ReviewDocuments/ReviewDocuments.test.jsx
  src/pages/Office/ServicesCounselingEditShipmentDetails/ServicesCounselingEditShipmentDetails.test.jsx
Labels: Mountain Movers, INTEGRATION, frontend, Screen Sharks

#15727 Int b 23333 admin app add acknowledgement for requested privileges
  pkg/gen/adminapi/embedded_spec.go
  pkg/gen/adminmessages/requested_office_user_update.go
  pkg/handlers/adminapi/api.go
  pkg/handlers/adminapi/requested_office_users.go
  pkg/handlers/adminapi/requested_office_users_test.go
  pkg/testdatagen/testharness/dispatch.go
  pkg/testdatagen/testharness/make_office_user.go
  playwright/tests/admin/officeUsers.spec.js
  playwright/tests/admin/requestedOfficeUser.spec.js
  playwright/tests/utils/testharness.js
  src/pages/Admin/RequestedOfficeUsers/RequestedOfficeUserEdit.jsx
  src/pages/Admin/RequestedOfficeUsers/RequestedOfficeUserPrivilegeConfirm.jsx
  src/pages/Admin/RequestedOfficeUsers/RequestedOfficeUserShow.jsx
  src/pages/Admin/RequestedOfficeUsers/RequestedOfficeUserShow.module.scss
  src/scenes/SystemAdmin/Home.jsx
  swagger-def/admin.yaml
  swagger/admin.yaml
Labels: INTEGRATION, Go-Rillaz, frontend, backend

#15447 B 23582 main - Rename too_assigned_id DB column to distinguish queue work
  migrations/app/ddl_migrations/ddl_functions/20250325161603_fn_fetch_move_history.up.sql
  migrations/app/ddl_migrations/ddl_functions/20250509183824_fn_get_origin_queue.up.sql
  migrations/app/ddl_migrations/ddl_functions/20250528195649_fn_get_moves_for_bulk_assignment.up.sql
  migrations/app/ddl_migrations/ddl_tables/20250224162949_B-22706_tbl_update_moves.up.sql
  pkg/factory/move_factory.go
  pkg/factory/move_factory_test.go
  pkg/factory/shared.go
  pkg/gen/ghcapi/embedded_spec.go
  pkg/gen/ghcmessages/move.go
  pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
  pkg/handlers/ghcapi/move_test.go
  pkg/models/move.go
  pkg/models/move_test.go
  pkg/services/move/assigned_office_user_updater.go
  pkg/services/move/move_assignment.go
  pkg/services/move/move_assignment_test.go
  pkg/services/move/move_fetcher_test.go
  pkg/services/move/move_router.go
  pkg/services/move/move_router_test.go
  pkg/services/move_task_order/move_task_order_updater.go
  pkg/services/move_task_order/move_task_order_updater_test.go
  pkg/services/mto_service_item/mto_service_item_updater_test.go
  pkg/services/mto_shipment/mto_shipment_updater_test.go
  pkg/services/office_user/office_user_fetcher.go
  pkg/services/order/order_fetcher.go
  src/constants/MoveHistory/Database/FieldMappings.js
  src/constants/MoveHistory/EventTemplates/ReviewShipmentAddressUpdate/reviewShipmentAddressUpdateMove.jsx
  src/constants/MoveHistory/EventTemplates/ReviewShipmentAddressUpdate/reviewShipmentAddressUpdateMove.test.jsx
  src/constants/MoveHistory/EventTemplates/SaveBulkAssignmentData/SaveBulkAssignmentData.test.jsx
  src/constants/MoveHistory/EventTemplates/UpdateAssignedOfficeUser/DeleteAssignedOfficeUser.jsx
  src/constants/MoveHistory/EventTemplates/UpdateAssignedOfficeUser/DeleteAssignedOfficeUser.test.jsx
  src/constants/MoveHistory/EventTemplates/UpdateAssignedOfficeUser/UpdateAssignedOfficeUser.test.jsx
  src/constants/MoveHistory/EventTemplates/UpdateMoveTaskOrderStatus/updateMoveTaskOrderStatus.jsx
  src/constants/MoveHistory/EventTemplates/UpdateMoveTaskOrderStatus/updateMoveTaskOrderStatus.test.jsx
  src/constants/MoveHistory/EventTemplates/UpdateServiceItemStatus/updateServiceItemStatusUpdateMove.jsx
  src/constants/MoveHistory/EventTemplates/UpdateServiceItemStatus/updateServiceItemStatusUpdateMove.test.jsx
  src/constants/MoveHistory/officeUserAssignment.js
  src/pages/Office/MoveHistory/LabeledDetails.jsx
  src/utils/formatters.js
  src/utils/formatters.test.js
  swagger-def/ghc.yaml
  swagger/ghc.yaml
Labels: G-Unit, MAIN
